Repository Automattic/wp-calypso, pull requests merged in 2018-04, with the labels that each got.

#23792 Payments: massively rename "source payment transaction" to "order transaction"
  client/state/action-types.js
  client/state/data-layer/wpcom/me/index.js
  client/state/data-layer/wpcom/me/transactions/order/from-api.js
  client/state/data-layer/wpcom/me/transactions/order/index.js
  client/state/data-layer/wpcom/me/transactions/order/schema.json
  client/state/data-layer/wpcom/me/transactions/order/test/from-api.js
  client/state/data-layer/wpcom/me/transactions/order/test/index.js
  client/state/index.js
  client/state/order-transactions/actions.js
  client/state/order-transactions/reducer.js
  client/state/order-transactions/test/actions.js
  client/state/order-transactions/test/reducer.js
  client/state/selectors/get-order-transaction.js
  client/state/selectors/get-source-payment-transaction-detail.js
  client/state/selectors/test/get-order-transaction.js
  client/state/selectors/test/get-source-payment-transaction-detail.js
  client/state/transactions/reducer.js
  client/state/transactions/source-payment/actions.js
  client/state/transactions/source-payment/reducer.js
  client/state/transactions/source-payment/test/actions.js
Labels: State, [Status] Needs Review

#22160 Plans: Fix plansLink get param handling
  client/jetpack-connect/controller.js
  client/jetpack-connect/plans-landing.jsx
  client/jetpack-connect/plans.jsx
  client/lib/plans/index.js
  client/lib/plans/test/plans-link.js
  client/my-sites/plan-features/header.jsx
  client/my-sites/plan-interval-discount/index.js
Labels: [Status] In Progress, [Status] Needs Review, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Bug

#23399 Animate: fixes fade-in animation name in selector
  client/components/animate/style.scss
Labels: Components, [Pri] Low, [Status] Needs Review, [Type] Janitorial

#23802 Signup: Add track events for vertical plans AB test
  client/lib/abtest/active-tests.js
  client/my-sites/plan-features/index.jsx
Labels: Analytics, Data, Signup, Testing, [Status] Needs Review, [Status] Ready to Merge

#23595 Google My Business: Add New Account page
  assets/stylesheets/sections/google-my-business.scss
  client/my-sites/google-my-business/controller.js
  client/my-sites/google-my-business/index.js
  client/my-sites/google-my-business/new-account/index.js
  client/my-sites/google-my-business/new-account/style.scss
  client/my-sites/google-my-business/select-business-type/index.js
  client/my-sites/google-my-business/select-business-type/style.scss
  client/my-sites/google-my-business/style.scss
  client/wordpress-com.js
Labels: Google My Business, [Status] Ready to Merge

#23744 Upgrade to node 8.11.0
  .nvmrc
  Dockerfile
  circle.yml
  npm-shrinkwrap.json
  package.json
Labels: Build, Framework, [Status] Needs Review, [Status] Needs e2e Testing, [Type] Task

#23832 Likes: add like_source to like requests
  client/blocks/like-button/index.jsx
  client/blocks/reader-full-post/index.jsx
  client/blocks/reader-post-actions/index.jsx
  client/reader/like-button/index.jsx
  client/reader/stream/index.jsx
  client/state/data-layer/wpcom/sites/posts/likes/mine/delete/index.js
  client/state/data-layer/wpcom/sites/posts/likes/new/index.js
  client/state/posts/likes/actions.js
Labels: Reader, [Status] Needs Review, [Type] Bug

#23748 Store: Fix store-woo signup flow
  client/extensions/woocommerce/app/dashboard/index.js
  client/extensions/woocommerce/app/dashboard/setup/tasks.js
  client/extensions/woocommerce/store-sidebar/index.js
  client/signup/steps/plans-atomic-store/index.jsx
Labels: Signup, Store, [Status] Ready to Merge

#23805 Store Dashboard: Add a base route with the site selector
  client/extensions/woocommerce/app/index.js
  client/extensions/woocommerce/index.js
Labels: Store, [Status] Ready to Merge

#23788 Store: Fix Sparkline display on newer sites
  client/extensions/woocommerce/app/dashboard/widgets/stats-widget/index.js
  client/extensions/woocommerce/app/dashboard/widgets/stats-widget/stat.js
Labels: Store, [Status] Ready to Merge

#23814 Store Dashboard: Remove the loading state from the header
  client/extensions/woocommerce/app/dashboard/index.js
  client/extensions/woocommerce/components/action-header/index.js
  client/extensions/woocommerce/components/action-header/style.scss
Labels: Store, [Status] Ready to Merge

#23322 Store Services: Add USPS shipping label signature requirement
  client/extensions/woocommerce/woocommerce-services/state/action-types.js
  client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js
  client/extensions/woocommerce/woocommerce-services/state/shipping-label/reducer.js
  client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/reducer.js
  client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-info.js
  client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/style.scss
Labels: Store Services, [Status] Ready to Merge

#23816 Store Services: style label purchase modal for mobile devices.
  client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/style.scss
  client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/style.scss
  client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/style.scss
Labels: Store, Store Services, [Status] Needs Design Review, [Status] Ready to Merge

#23823 Checkout: rename 'SourcePaymentBox' to 'RedirectPaymentBox'
  client/my-sites/checkout/checkout/redirect-payment-box.jsx
  client/my-sites/checkout/checkout/secure-payment-form.jsx
Labels: Checkout, [Status] Needs Review

#23821 Combine same-module and alphabetize imports
  client/my-sites/plan-features/index.jsx
Labels: Plans, [Pri] Low, [Status] Needs Review, [Status] Ready to Merge, [Type] Janitorial

#23843 Localize the strings in the RecommendationSelect component.
  client/blocks/nps-survey/recommendation-select.jsx
Labels: [Status] Needs Review, i18n

#23776 Update StickyPanel to use the breakpoint mixin
  client/components/sticky-panel/style.scss
Labels: Framework, [Status] Needs Review

#22971 Purchases: allow adding payment details when renewing but not a card purchase
  client/me/purchases/manage-purchase/index.jsx
Labels: Purchases, [Status] Needs Review

#23711 Remove direct usage of plan constants from credits-payment-box
  client/my-sites/checkout/checkout/credits-payment-box.jsx
  client/my-sites/checkout/checkout/test/credits-payment-box.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23699 Remove direct usage of plan constants from paypal-payment-box
  client/my-sites/checkout/checkout/paypal-payment-box.jsx
  client/my-sites/checkout/checkout/test/paypal-payment-box.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23717 Remove direct usage of plan constants from settings general form
  client/my-sites/site-settings/form-general.jsx
  client/my-sites/site-settings/test/form-general.jsx
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23724 Remove direct usage of plan constants from form-analytics
  client/my-sites/site-settings/form-analytics.jsx
  client/my-sites/site-settings/test/form-analytics.jsx
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23725 Remove direct usage of plan constants from plugins-browser
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/plugins/plugins-browser/test/index.jsx
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23736 Remove direct usage of plan constants from plugin-meta
  client/my-sites/plugins/plugin-meta/index.jsx
  client/my-sites/plugins/plugin-meta/test/index.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23737 Update/remove hardcoded constants from current plan
  client/my-sites/plans/current-plan/header.jsx
  client/my-sites/plans/current-plan/test/header.jsx
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23754 Update/remove hardcoded constants help
  client/me/help/main.jsx
  client/me/help/test/main.jsx
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23683 Replace custom logic with usage of planMatches helper in is*Plan functions
  client/lib/plans/index.js
  client/lib/plans/test/plan-lookups.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23712 Remove direct usage of plan constants from credit-card-payment-box
  client/my-sites/checkout/checkout/credit-card-payment-box.jsx
  client/my-sites/checkout/checkout/test/credit-card-payment-box.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23755 Update/remove hardcoded constants help courses
  client/me/help/help-courses/index.jsx
  client/me/help/help-courses/test/index.jsx
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23756 Update/remove hardcoded constants concierge
  client/me/concierge/main.js
  client/me/concierge/test/main.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23757 Update/remove hardcoded constants preview upgrade nudge
  client/components/seo/preview-upgrade-nudge/index.jsx
  client/components/seo/preview-upgrade-nudge/test/index.jsx
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23701 Remove direct usage of plan constants from source-payment-box
  client/my-sites/checkout/checkout/redirect-payment-box.jsx
  client/my-sites/checkout/checkout/test/redirect-payment-box.jsx
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23848 Add more helper functions such as isWpComFreePlan
  client/lib/plans/index.js
  client/lib/plans/test/plan-lookups.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23831 Jetpack connect: Actions cleanup
  client/jetpack-connect/signup.js
  client/state/jetpack-connect/actions.js
  client/state/jetpack-connect/test/actions.js
Labels: Jetpack, Testing, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Janitorial

#23774 JP Settings: Implement regeneratePostByEmail() using saveJetpackSettings()
  client/state/data-layer/wpcom/jetpack/settings/index.js
  client/state/data-layer/wpcom/jetpack/settings/test/index.js
  client/state/jetpack-onboarding/actions.js
  client/state/jetpack-onboarding/reducer.js
  client/state/jetpack-onboarding/test/actions.js
  client/state/jetpack-onboarding/test/reducer.js
Labels: Jetpack, NUX, Site Settings, State, [Status] Ready to Merge

#23678 Jetpack Connect: Give footer links equal top/bottom margins
  client/jetpack-connect/style.scss
Labels: Jetpack, [Status] Needs Review

#23766 Help: remove `inlineHelpWithContactForm` a/b test
  client/blocks/inline-help/popover.jsx
  client/lib/abtest/active-tests.js
Labels: Help, [Status] Ready to Merge, [Type] Task

#23794 Posts: fix wrong paths in page view analytics
  client/my-sites/posts/controller.js
  client/my-sites/posts/index.js
  client/my-sites/posts/main.jsx
Labels: Analytics, Posts, [Type] Bug

#22993 Enable the /checkout/:domain/:product route for logged-out users
  client/controller/index.web.js
  client/my-sites/checkout/index.js
  client/wordpress-com.js
Labels: FixTheFlows, Store, [Status] Ready to Merge

#23855 JP Settings (data-layer based): Keep Track of Module Activation State
  client/state/jetpack-onboarding/reducer.js
  client/state/jetpack-onboarding/test/reducer.js
Labels: Jetpack, NUX, Site Settings, [Status] Needs Review

#23826 Help: Focus contact form simple fields on label click
  client/me/help/help-contact-form/index.jsx
Labels: Help, [Status] Ready to Merge, [Type] Enhancement

#23770 Remove Noticons from Billing History
  client/me/billing-history/style.scss
  client/me/billing-history/transactions-header.jsx
Labels: Framework, [Status] Needs Review

#23815 Analytics: do not omit site id when a site fragment is present in the path
  client/lib/analytics/constants.js
  client/lib/analytics/test/utils.js
  client/lib/analytics/utils.js
Labels: Analytics, [Status] Needs Review

#23865 Rewind: add option to flag that a migration was opt-in
  client/my-sites/stats/activity-log/activity-log-rewind-toggle.jsx
  client/signup/steps/rewind-migrate/index.jsx
  client/state/activity-log/actions.js
  client/state/data-layer/wpcom/activity-log/activate/index.js
Labels: Activity/Rewind, [Status] Needs Review, [Type] Enhancement

#23864 Form State: Option to skip validate/sanitize on field change
  client/components/domains/contact-details-form-fields/index.jsx
  client/components/domains/contact-details-form-fields/test/__snapshots__/index.js.snap
  client/lib/form-state/index.js
  client/my-sites/domains/components/form/input.jsx
Labels: Checkout, Domains, [Status] Ready to Merge, [Type] Enhancement

#23867 Rewind: track when user migrates VaultPress to Rewind
  client/my-sites/stats/activity-log/activity-log-rewind-toggle.jsx
Labels: Activity/Rewind, [Status] Needs Review, [Type] Enhancement

#23861 Framework: Break chunk dependency cycles
  client/blocks/daily-post-button/index.jsx
  client/blocks/post-item/index.jsx
  client/blocks/reader-share/index.jsx
  client/boot/common.js
  client/components/section-nav/item.jsx
  client/extensions/wp-job-manager/components/navigation/index.jsx
  client/extensions/zoninator/app/util.js
  client/layout/masterbar/logged-in.jsx
  client/layout/masterbar/publish.jsx
  client/layout/sidebar/button.jsx
  client/layout/sidebar/item.jsx
  client/my-sites/pages/page-list.jsx
  client/my-sites/pages/page/index.js
  client/my-sites/plugins/utils.js
  client/my-sites/post-type-list/empty-content.jsx
  client/my-sites/post-type-list/post-actions-ellipsis-menu/edit.jsx
  client/reader/controller.js
  client/sections-helper.js
  client/sections-middleware.js
  client/sections-preload.js
Labels: Framework, [Status] Needs Review

#21865 Add stacktrace-translate tool
  bin/stacktrace-translate.js
  npm-shrinkwrap.json
  package.json
Labels: Build, [Status] Needs Review

#23807 Media: fix wrong paths in page view analytics
  client/my-sites/media/controller.js
  client/my-sites/media/index.js
  client/my-sites/media/main.jsx
Labels: Analytics, Media, [Status] Ready to Merge, [Type] Bug

#23767 Tracks: Validate event properties in dev
  client/lib/analytics/index.js
Labels: Analytics, [Status] Needs Review

#23612 Settings: update content in info popovers
  client/my-sites/site-settings/comment-display-settings/index.jsx
  client/my-sites/site-settings/composing/after-the-deadline.jsx
  client/my-sites/site-settings/custom-content-types/index.jsx
  client/my-sites/site-settings/form-jetpack-monitor.jsx
  client/my-sites/site-settings/jetpack-ads.jsx
  client/my-sites/site-settings/jetpack-site-stats.jsx
  client/my-sites/site-settings/masterbar.jsx
  client/my-sites/site-settings/media-settings.jsx
  client/my-sites/site-settings/protect.jsx
  client/my-sites/site-settings/publishing-tools/index.jsx
  client/my-sites/site-settings/related-posts/index.jsx
  client/my-sites/site-settings/search.jsx
  client/my-sites/site-settings/seo-settings/site-verification.jsx
  client/my-sites/site-settings/sitemaps.jsx
  client/my-sites/site-settings/spam-filtering-settings.jsx
  client/my-sites/site-settings/speed-up-site-settings.jsx
  client/my-sites/site-settings/sso.jsx
  client/my-sites/site-settings/subscriptions.jsx
  client/my-sites/site-settings/theme-enhancements.jsx
Labels: FixTheFlows, Jetpack, Site Settings, [Status] Needs Copy Review, [Status] Needs Design Review, [Status] Ready to Merge

#23781 Analytics: Remove broken and unused `site_post_count` property.
  client/lib/analytics/super-props.js
Labels: Analytics, [Status] Needs Review

#23665 Reader: move single feed fetches to the data layer (/read/feed/:feed_id)
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/state/data-layer/wpcom/read/feed/index.js
  client/state/data-layer/wpcom/read/feed/test/index.js
  client/state/reader/feeds/actions.js
  client/state/reader/feeds/test/actions.js
Labels: Reader, [Status] Ready to Merge

#23877 Share: do not query for posts
  client/blocks/post-share/index.jsx
Labels: State, [Status] Ready to Merge

#23751 Reader: set gallery image min width to 300px
  client/state/reader/posts/normalization-rules.js
Labels: Reader, [Status] Needs Review

#23818 switch to using query string parameters for display mode in `/checklist`
  client/my-sites/checklist/checklist-show/index.jsx
  client/my-sites/checklist/controller/index.jsx
  client/my-sites/checklist/index.js
  client/my-sites/checkout/checkout/checkout.jsx
  client/my-sites/checkout/gsuite-nudge/index.jsx
  client/signup/processing-screen/index.jsx
Labels: Checklist, [Status] Needs Review

#23835 Jetpack connect: Add createUser action tests
  client/state/jetpack-connect/test/actions.js
Labels: Jetpack, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Task

#23504 Component: add additional feedback form to the NPS survey
  client/blocks/nps-survey/docs/example.jsx
  client/blocks/nps-survey/index.jsx
  client/blocks/nps-survey/style.scss
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/state/action-types.js
  client/state/nps-survey/actions.js
  client/state/nps-survey/reducer.js
  client/state/nps-survey/selectors.js
  client/state/nps-survey/test/actions.js
  client/state/nps-survey/test/reducer.js
  client/state/nps-survey/test/selectors.js
  config/wpcalypso.json
Labels: Components, [Status] Needs Review

#23647 Analytics: Track /me/purchases page views with normalized paths
  client/lib/react-helpers/index.js
  client/me/billing-history/receipt.jsx
  client/me/purchases/add-credit-card/index.jsx
  client/me/purchases/cancel-privacy-protection/index.jsx
  client/me/purchases/confirm-cancel-domain/index.jsx
  client/me/purchases/controller.jsx
  client/me/purchases/index.js
  client/me/purchases/manage-purchase/index.jsx
  client/me/purchases/payment/add-card-details/index.jsx
  client/me/purchases/payment/edit-card-details/index.jsx
  client/me/purchases/purchases-list/index.jsx
Labels: Analytics, Me, Purchases, [Status] Needs Review, [Status] Needs e2e Testing

#23883 Remove direct usage of PLAN_ constants from cart-values
  client/lib/cart-values/cart-items.js
  client/lib/cart-values/test/cart-items.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23887 Remove PLAN_* constants from jetpack-thank-you-card
  client/my-sites/checkout/checkout-thank-you/jetpack-thank-you-card.jsx
  client/my-sites/checkout/checkout-thank-you/test/jetpack-thank-you-card.jsx
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23888 Remove PLAN_ constants from site-picker-submit
  client/signup/steps/site-picker/site-picker-submit.jsx
  client/signup/steps/site-picker/test/site-picker-submit.jsx
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23889 Remove PLAN_* constants from transfer-to-other-site
  client/my-sites/domains/domain-management/transfer/transfer-to-other-site/index.jsx
  client/my-sites/domains/domain-management/transfer/transfer-to-other-site/test/index.jsx
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23890 Remove PLAN_ constants from is-site-on-free-plan
  client/state/selectors/is-site-on-free-plan.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23714 Remove direct usage of plan constants from checkout-thank-you
  client/my-sites/checkout/checkout-thank-you/index.jsx
  client/my-sites/checkout/checkout-thank-you/test/index.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23716 Remove direct usage of plan constants from seo-settings form
  client/my-sites/site-settings/seo-settings/form.jsx
  client/my-sites/site-settings/seo-settings/test/form.jsx
Labels: [Status] Needs Review, [Tests] Includes Tests

#23769 NPS: Show the NPS survey form immediately
  client/layout/nps-survey-notice/index.jsx
  client/state/ui/nps-survey-notice/actions.js
Labels: [Status] Needs Review

#23847 Inline Help: make search results play nice with Meta clicks (and `Enter`s)
  client/blocks/inline-help/inline-help-search-card.jsx
  client/blocks/inline-help/inline-help-search-results.jsx
  client/blocks/inline-help/popover.jsx
Labels: Help, [Status] Ready to Merge

#23881 Store: Fix plugin fetch loop.
  client/extensions/woocommerce/app/settings/taxes/index.js
Labels: Store, [Status] Needs Review

#23828 Help: Make ChatBusinessConciergeNotice use the selected help site
  client/me/help/help-contact-form/index.jsx
Labels: Help, [Status] Needs Review, [Type] Bug, [Type] Janitorial

#23700 Activity Log - Failed backup event: add button to fix credentials
  client/my-sites/stats/activity-log-item/index.jsx
  client/my-sites/stats/activity-log-item/style.scss
  client/state/data-layer/wpcom/sites/activity/from-api.js
Labels: Activity/Rewind, [Pri] High, [Status] Needs Review, [Type] Enhancement

#23686 State: Store new password when creating a new application password
  client/state/action-types.js
  client/state/application-passwords/actions.js
  client/state/application-passwords/reducer.js
  client/state/application-passwords/test/__snapshots__/reducer.js.snap
  client/state/application-passwords/test/actions.js
  client/state/application-passwords/test/reducer.js
  client/state/data-layer/wpcom/me/two-step/application-passwords/new/index.js
  client/state/data-layer/wpcom/me/two-step/application-passwords/new/schema.js
  client/state/data-layer/wpcom/me/two-step/application-passwords/new/test/index.js
Labels: Me, State, [Status] Ready to Merge, [Type] Janitorial

#23901 framework: es6-wrapper should only warn once
  client/lib/wrap-es6-functions/index.js
Labels: Framework, [Status] Needs Review

#23859 Jetpack Onboarding: Move Credentials State to jetpack/onboarding
  client/jetpack-connect/controller.js
  client/state/data-layer/wpcom/jetpack/settings/test/index.js
  client/state/jetpack-onboarding/actions.js
  client/state/jetpack-onboarding/reducer.js
  client/state/jetpack-onboarding/schema.js
  client/state/jetpack-onboarding/test/actions.js
  client/state/jetpack-onboarding/test/reducer.js
  client/state/jetpack/onboarding/actions.js
  client/state/jetpack/onboarding/reducer.js
  client/state/jetpack/onboarding/schema.js
  client/state/jetpack/onboarding/test/actions.js
  client/state/jetpack/onboarding/test/reducer.js
  client/state/jetpack/reducer.js
  client/state/selectors/get-unconnected-site-id-by-slug.js
  client/state/selectors/get-unconnected-site.js
  client/state/selectors/test/get-jpo-user-hash.js
  client/state/selectors/test/get-unconnected-site-id-by-slug.js
  client/state/selectors/test/get-unconnected-site-url.js
  client/state/selectors/test/get-unconnected-site.js
Labels: Jetpack, NUX, [Status] Needs Review

#23812 Site Settings: add ability to disable podcasting
  client/my-sites/site-settings/form-writing.jsx
  client/my-sites/site-settings/podcasting-details/index.jsx
  client/my-sites/site-settings/podcasting-details/link.jsx
  client/my-sites/site-settings/podcasting-details/style.scss
  client/my-sites/stats/site.jsx
  client/state/sites/constants.js
Labels: Site Settings, [Status] Needs Review

#23787 Signup: Fix SSR handling of locale for `context`.
  client/signup/index.node.js
Labels: Signup, [Status] Needs Review, [Status] Needs e2e Testing

#23853 Plugins State: Add test for new isLoaded selector
  client/state/plugins/installed/test/selectors.js
Labels: Plugins, [Status] Ready to Merge, [Tests] Includes Tests

#23507 JetpackLogo - now the lightning will be white by default
  client/blocks/login/style.scss
  client/components/jetpack-colophon/style.scss
  client/components/jetpack-logo/index.jsx
  client/jetpack-connect/style.scss
  client/jetpack-onboarding/style.scss
Labels: [Status] Needs Author Reply, [Status] Ready to Merge, [Type] Enhancement

#23912 Activity Log: follow A8c's writing guidelines and use sentence case
  client/my-sites/stats/activity-log-item/index.jsx
  client/my-sites/stats/activity-log-item/style.scss
Labels: Activity/Rewind, [Status] Needs Review, [Type] Bug

#23893 Help: Use localize provided moment
  client/me/help/chat-business-concierge-notice/index.jsx
Labels: Help, [Pri] Low, [Status] Ready to Merge, [Type] Janitorial

#23896 Themes: Fix test mocks reset -> restore
  client/state/themes/test/reducer.js
Labels: Themes, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Janitorial

#23897 DevDocs: New CardHeading component
  assets/stylesheets/_components.scss
  client/components/card-heading/README.md
  client/components/card-heading/docs/example.jsx
  client/components/card-heading/index.jsx
  client/components/card-heading/style.scss
  client/devdocs/design/index.jsx
  client/my-sites/google-my-business/select-business-type/index.js
  client/my-sites/google-my-business/style.scss
Labels: DevDocs, [Status] Needs Design Review

#23760 2 year plans: Remove hardcoded plans constants from stepsForProductAndSurvey
  client/components/marketing-survey/cancel-purchase-form/steps-for-product-and-survey.js
  client/components/marketing-survey/cancel-purchase-form/test/steps-for-product-and-survey.js
Labels: [Status] Needs Review, [Tests] Includes Tests

#23669 Remove direct usage of PLAN_* constants from isGoogleMyBusinessStatsNudgeVisible
  client/state/selectors/is-google-my-business-stats-nudge-visible.js
  client/state/selectors/test/is-google-my-business-stats-nudge-visible.js
Labels: [Status] Needs Review, [Tests] Includes Tests

#23643 Remove direct usage of plan constants
  client/lib/automated-transfer/index.js
  client/lib/automated-transfer/test/index.js
Labels: [Status] Ready to Merge, [Tests] Includes Tests

#23918 Components: Introduce a QueryApplicationPasswords query component
  client/components/data/query-application-passwords/README.md
  client/components/data/query-application-passwords/index.jsx
Labels: Components, Me, State, [Status] Ready to Merge

#23906 State: Introduce a getApplicationPasswords selector
  client/state/selectors/get-application-passwords.js
  client/state/selectors/test/get-application-passwords.js
Labels: Me, State, [Status] Ready to Merge, [Type] Janitorial

#23907 State: Introduce a getNewApplicationPassword selector
  client/state/selectors/get-new-application-password.js
  client/state/selectors/test/get-new-application-password.js
Labels: Me, State, [Status] Ready to Merge, [Type] Janitorial

#23909 State: Persist application passwords
  client/state/application-passwords/reducer.js
  client/state/application-passwords/schema.js
Labels: Me, State, [Status] Ready to Merge, [Type] Enhancement

#23696 reader streams reduxification: selectors
  client/reader/stream/index.jsx
  client/reader/stream/utils.js
  client/state/selectors/get-reader-current-stream.js
  client/state/selectors/get-reader-stream-next-item.js
  client/state/selectors/get-reader-stream-offset-item.js
  client/state/selectors/get-reader-stream-prev-item.js
  client/state/selectors/get-reader-stream-should-request-recommendations.js
  client/state/selectors/get-reader-stream-transformed-items.js
  client/state/selectors/get-reader-stream.js
  client/state/selectors/test/get-reader-stream-offset-item.js
  client/state/selectors/test/get-reader-stream-should-request-recommendations.js
  client/state/ui/reader/reducer.js
Labels: Reader, [Status] Needs Review

#23801 Domains: Show price for incoming transfers
  client/components/domains/transfer-domain-step/index.jsx
  client/lib/domains/index.js
  client/state/products-list/schema.js
  client/state/products-list/test/reducer.js
Labels: Domains, [Type] Enhancement

#22798 Remove urlSearch mixin
  client/lib/mixins/url-search/README.md
  client/lib/mixins/url-search/index.js
  client/lib/url-search/README.md
  client/my-sites/people/people-section-nav/index.jsx
  client/my-sites/people/people-section-nav/people-search.jsx
  client/my-sites/plugins/main.jsx
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/post-type-filter/index.jsx
Labels: Components, [Status] Needs Review, [Type] Janitorial

#23780 Tidy up checkout styles
  client/my-sites/checkout/checkout/style.scss
Labels: Checkout, [Status] Needs Review

#23836 Discussion: enable `Follows my blog` for Jetpack and AT sites
  client/my-sites/site-settings/form-discussion.jsx
Labels: [Status] Needs Review

#23709 Pie Chart Component
  assets/stylesheets/_components.scss
  client/components/pie-chart/README.md
  client/components/pie-chart/docs/example.js
  client/components/pie-chart/index.js
  client/components/pie-chart/legend-item.js
  client/components/pie-chart/style.scss
  client/devdocs/design/index.jsx
Labels: Stats, [Status] Ready to Merge

#23873 Checkout: Try to parse some known postal codes
  client/components/domains/contact-details-form-fields/index.jsx
  client/components/domains/contact-details-form-fields/test/__snapshots__/index.js.snap
  client/components/domains/contact-details-form-fields/test/index.js
  client/lib/form-state/index.js
  client/lib/postal-code/README.md
  client/lib/postal-code/index.jsx
  client/lib/postal-code/test/index.jsx
  client/my-sites/domains/components/form/input.jsx
  client/my-sites/domains/components/form/state-select.jsx
Labels: Checkout, Domains, [Type] Enhancement

#23871 Implement "Load More" buttons for domain registration step
  client/components/domains/domain-suggestion/style.scss
  client/components/domains/register-domain-step/index.jsx
  client/components/domains/register-domain-step/style.scss
Labels: Domains, [Status] Ready to Merge

#23384 [Domains] Implement featured domains
  assets/stylesheets/_components.scss
  client/components/domains/domain-product-price/index.jsx
  client/components/domains/domain-registration-suggestion/index.jsx
  client/components/domains/domain-registration-suggestion/style.scss
  client/components/domains/domain-registration-suggestion/utility.js
  client/components/domains/domain-search-results/index.jsx
  client/components/domains/domain-suggestion/index.jsx
  client/components/domains/featured-domain-suggestions/index.jsx
  client/components/domains/featured-domain-suggestions/style.scss
Labels: Domains, [Status] Ready to Merge

#23914 [Domains] Polish search filters, take 2
  client/components/domains/register-domain-step/index.jsx
  client/components/domains/search-filters/index.jsx
  client/components/domains/search-filters/more-filters.jsx
Labels: Domains, [Status] Ready to Merge

#23915 Reader: fix edit link when post.type is missing
  client/lib/posts/test/utils.js
  client/lib/posts/utils.js
Labels: Jetpack, Reader, [Status] Needs Review

#23875 Analytics: normalize Themes paths
  client/my-sites/themes/controller.jsx
  client/my-sites/themes/helpers.js
Labels: Analytics, Themes, [Status] Ready to Merge, [Type] Bug

#23938 Theme: normalizes the site page view parameter
  client/my-sites/theme/main.jsx
Labels: Analytics, Themes, [Status] Needs Review, [Type] Bug

#23921 CSS: Replace the 1600px breakpoint with 1400px
  assets/stylesheets/shared/mixins/_breakpoints.scss
  client/blocks/reader-full-post/_content.scss
  client/my-sites/themes/themes-banner/style.scss
Labels: Reader, [Status] Needs Review

#23923 CSS: Add a breakpoint at 800px
  assets/stylesheets/shared/mixins/_breakpoints.scss
  client/notifications/style.scss
Labels: [Status] Needs Review

#23808 Google My Business: Add Select Location page
  assets/stylesheets/sections/google-my-business.scss
  client/my-sites/google-my-business/controller.js
  client/my-sites/google-my-business/index.js
  client/my-sites/google-my-business/logo/index.js
  client/my-sites/google-my-business/new-account/index.js
  client/my-sites/google-my-business/new-account/style.scss
  client/my-sites/google-my-business/select-business-type/index.js
  client/my-sites/google-my-business/select-location/index.js
  client/my-sites/google-my-business/select-location/location-type.js
  client/my-sites/google-my-business/select-location/location.js
  client/my-sites/google-my-business/select-location/style.scss
  client/my-sites/google-my-business/style.scss
  client/my-sites/sharing/connections/services/google-my-business.js
  client/my-sites/sharing/style.scss
Labels: Google My Business, [Status] Ready to Merge

#23952 Remove me/next
  assets/stylesheets/_components.scss
  client/lib/route/test/legacy-routes.js
  client/me/controller.js
  client/me/index.js
  client/me/next-steps/index.jsx
  client/me/next-steps/next-steps-box.jsx
  client/me/next-steps/next-steps-box.scss
  client/me/next-steps/next-steps.scss
  client/me/next-steps/steps.js
  client/me/sidebar/index.jsx
  client/signup/README.md
  config/desktop.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Me, [Status] Needs Review

#23749 Checkboxes: update checkbox design and remove noticons
  assets/stylesheets/shared/_forms.scss
  public/images/checkbox-icons/checkmark.svg
Labels: [Status] Needs Review

#23964 Importers: update wording for other platforms.
  client/my-sites/site-settings/site-tools/index.jsx
Labels: Import, [Status] Ready to Merge

#23955 Guided Tours: use `min-width` for button width so single buttons don't break text unnecessarily
  client/layout/guided-tours/style.scss
Labels: Guided Tours, [Status] Ready to Merge

#23970 Jetpack: Add wp-admin link on all Jetpack sites
  client/my-sites/sidebar/sidebar.jsx
Labels: Jetpack, [Status] Needs Review

#23973 Store: Check for plugin errors when setting up or fixing a store
  client/extensions/woocommerce/app/dashboard/required-plugins-install-view.js
  client/extensions/woocommerce/app/dashboard/setup/header.js
  client/extensions/woocommerce/app/dashboard/setup/style.scss
  client/state/plugins/installed/selectors.js
Labels: Store, [Status] Ready to Merge

#23957 Google My Business: Refactor urls and routing
  client/blocks/google-my-business-stats-nudge/index.js
  client/lib/analytics/index.js
  client/my-sites/google-my-business/index.js
  client/my-sites/google-my-business/new-account/index.js
  client/my-sites/google-my-business/select-business-type/index.js
  client/my-sites/google-my-business/select-location/index.js
  config/stage.json
Labels: Google My Business, [Status] Ready to Merge

#23942 Domains: Update postal code sanitizer
  client/lib/postal-code/index.jsx
  client/lib/postal-code/test/index.jsx
Labels: Checkout, Domains, [Type] Enhancement

#23953 Stats: Period Navigation: Persist relevant query params
  client/extensions/woocommerce/app/store-stats/store-stats-period-nav/index.js
  client/extensions/woocommerce/app/store-stats/utils.js
  client/my-sites/stats/stats-period-navigation/index.jsx
Labels: Stats, Store, [Status] Ready to Merge

#23951 Notices: Add to logged out layout
  client/layout/logged-out.jsx
  client/layout/test/index.js
  client/login/wp-login/index.jsx
Labels: Framework, Login, Server Side Rendering, [Status] Ready to Merge, [Type] Bug, [Type] Enhancement, [Type] Question

#23954 Tracks: Fix a bunch of rejected events
  client/lib/posts/stats.js
  client/me/security-account-recovery/manage-contact.jsx
  client/my-sites/checkout/checkout/payment-box.jsx
  client/my-sites/checkout/checkout/redirect-payment-box.jsx
  client/my-sites/post-type-list/post-action-counts/index.jsx
  client/my-sites/post-type-list/post-actions-ellipsis-menu/utils.js
  client/my-sites/site-settings/jetpack-sync-panel/index.jsx
  client/my-sites/stats/activity-log/activity-log-rewind-toggle.jsx
  client/my-sites/stats/stats-list/stats-list-item.jsx
Labels: Analytics, [Status] Needs Review, [Type] Bug

#23974 Remove unused CSS in plugins
  client/my-sites/plugins/plugins-browser-item/style.scss
Labels: [Status] Needs Review

#23846 Jetpack connect: Use promises for createAccount
  client/jetpack-connect/signup.js
  client/state/action-types.js
  client/state/jetpack-connect/actions.js
  client/state/jetpack-connect/reducer/jetpack-connect-authorize.js
  client/state/jetpack-connect/reducer/schema.js
  client/state/jetpack-connect/reducer/test/jetpack-connect-authorize.js
  client/state/jetpack-connect/test/actions.js
Labels: Jetpack, Signup, State, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Janitorial

#23671 Checkout: allow ebanx payments in Mexico
  client/components/credit-card-form-fields/index.jsx
  client/components/credit-card-form-fields/test/index.js
  client/lib/credit-card-details/constants.js
  client/lib/credit-card-details/ebanx.js
  client/lib/credit-card-details/test/ebanx.js
Labels: Payment Methods, [Status] Needs Review

#23908 Store: Add loading placeholder while we determine plugins state
  client/extensions/woocommerce/app/index.js
  client/extensions/woocommerce/index.js
  client/extensions/woocommerce/style.scss
Labels: Store, [Status] Needs Design Review, [Status] Ready to Merge

#23934 JP Remote Install: Follow redirects on supplied url, for example http->https
  client/jetpack-connect/remote-credentials.js
Labels: Jetpack, [Status] Needs Review

#23972 Rewind - credentials flow: fix font size
  client/my-sites/stats/activity-log-switch/style.scss
  client/signup/steps/creds-confirm/style.scss
Labels: Activity/Rewind, [Status] Needs Review, [Type] Bug

#23947 Add Google My Business Stats Tab
  client/blocks/stats-navigation/constants.js
  client/blocks/stats-navigation/index.js
  client/lib/route/path.js
  client/my-sites/google-my-business/controller.js
  client/my-sites/google-my-business/index.js
  client/my-sites/google-my-business/location/index.js
  client/my-sites/google-my-business/location/location-type.js
  client/my-sites/google-my-business/select-business-type/index.js
  client/my-sites/google-my-business/select-location/index.js
  client/my-sites/google-my-business/select-location/location.js
  client/my-sites/google-my-business/select-location/style.scss
  client/my-sites/google-my-business/stats/fake-data.js
  client/my-sites/google-my-business/stats/index.js
  client/my-sites/google-my-business/stats/search-data-type.js
Labels: Google My Business, [Status] Ready to Merge

#22860 Framework: Upgrade to webpack@4
  bin/loader-stats.js
  client/document/index.jsx
  npm-shrinkwrap.json
  package.json
  server/bundler/assets-writer.js
  server/bundler/index.js
  server/bundler/stats-writer.js
  server/pages/index.js
  webpack.config.js
  webpack.config.node.js
Labels: Build, Framework, Performance, [Status] Needs Review, [Status] Needs e2e Testing

#23704 Activity Log: Prevent rewinding after page refresh when a rewind process is already running
  client/my-sites/stats/activity-log/index.jsx
Labels: Activity/Rewind, [Pri] High, [Size] M, [Status] Needs Review, [Type] Bug

#23982 Documentation: Add contributor instructions for forking the upstream repo
  .github/CONTRIBUTING.md
Labels: Documentation

#23931 Activity Log: Sort events using `rewindId`
  client/lib/query-manager/activity/index.js
Labels: Activity/Rewind, [Status] Ready to Merge

#24015 Disable Google My Business Feature Flags everywhere
  config/development.json
  config/horizon.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Google My Business, [Status] Needs Review

#23579 Store: Stats: Referrer: Add ability to search and select
  client/extensions/woocommerce/app/store-stats/index.js
  client/extensions/woocommerce/app/store-stats/referrers/helpers.js
  client/extensions/woocommerce/app/store-stats/referrers/index.js
  client/extensions/woocommerce/app/store-stats/referrers/style.scss
  client/extensions/woocommerce/app/store-stats/store-stats-module/index.js
  client/extensions/woocommerce/app/store-stats/store-stats-referrer-widget/index.js
  client/extensions/woocommerce/app/store-stats/store-stats-referrer-widget/style.scss
  client/extensions/woocommerce/components/d3/horizontal-bar/index.js
  client/extensions/woocommerce/style.scss
  client/state/selectors/get-store-referrers.js
Labels: Store, [Status] Needs Review

#24010 Store: Pass user through to setup flow if on the dashboard
  client/extensions/woocommerce/app/index.js
Labels: Store, [Status] Ready to Merge

#23948 Stats: Utils: parseChartData: DRY up chart label creation
  client/state/stats/lists/test/utils.js
  client/state/stats/lists/utils.js
Labels: Accessibility, [Status] Ready to Merge

#23824 Checkout: move ebanx specific code into more generic location
  client/components/credit-card-form-fields/index.jsx
  client/components/credit-card-form-fields/test/index.js
  client/lib/checkout/constants.js
  client/lib/checkout/ebanx.js
  client/lib/checkout/test/ebanx.js
  client/lib/credit-card-details/test/validation.js
  client/lib/credit-card-details/validation.js
  client/lib/store-transactions/index.js
Labels: [Status] Needs Review

#23959 Update getBillingTimeFrame for WP.com plan to show info about biennial billing when 2-year plans are enabled
  client/lib/plans/constants.js
Labels: Plans, [Status] Needs Review

#23979 Plans. Remove vertical scrollbar on plan features selection page.
  client/my-sites/plan-features/style.scss
Labels: Design, Plans, [Status] Needs Review, [Type] Bug

#23976 WrapSettingsForm: Change order of Higher-Order Components
  client/my-sites/site-settings/wrap-settings-form.jsx
Labels: Site Settings, [Status] Ready to Merge

#23995 Add isYearly and isBienially functions to product-values
  client/lib/plans/constants.js
  client/lib/products-values/index.js
  client/lib/products-values/test/index.js
Labels: State, [Status] Needs Review

#23956 Request new API endpoints when "upgrades/2-year-plans" is enabled
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/state/data-layer/wpcom/plans/index.js
  config/desktop.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Tests] Includes Tests

#23994 Refactor getBillingMonthsForTerm out of calculateMonthlyPrice
  client/lib/plans/index.js
  client/lib/plans/test/plan-other.js
Labels: [Status] Needs Review, [Tests] Includes Tests

#23763 Remove direct usage of plan constants from plan features main
  client/my-sites/plans-features-main/index.jsx
  client/my-sites/plans-features-main/test/index.jsx
Labels: [Status] Needs Review, [Status] Needs e2e Testing, [Tests] Includes Tests

#24027 Update/2 year plans adjust cart items
  client/my-sites/checkout/cart/cart-item.jsx
  client/my-sites/checkout/cart/test/cart-item.js
Labels: [Status] Needs Review, [Tests] Includes Tests

#24026 NPS: Do NOT show when in SU/SSP mode
  client/layout/nps-survey-notice/index.jsx
Labels: Accessibility, [Type] Bug

#23958 On /plans, use default intervalType based on a current plan
  client/lib/plans/get-interval-type-for-term.js
  client/lib/plans/test/get-interval-type-for-term.js
  client/my-sites/plans/controller.jsx
  client/my-sites/plans/plans.js
  client/state/selectors/get-current-plan-term.js
  client/state/selectors/test/get-current-plan-term.js
Labels: [Status] Needs Review, [Tests] Includes Tests

#23483 Jetpack connect: Add Google login to signup
  client/jetpack-connect/signup.js
  client/jetpack-connect/test/__snapshots__/signup.js.snap
  client/state/jetpack-connect/actions.js
  client/state/jetpack-connect/test/actions.js
  config/development.json
  config/test.json
Labels: Jetpack, Signup, [Status] Needs Design Review, [Status] Ready to Merge, [Tests] Includes Tests, [Type] Enhancement

#24009 Remove a/b test
  client/lib/abtest/active-tests.js
  client/signup/steps/about/index.jsx
  client/state/action-types.js
  client/state/signup/steps/reducer.js
  client/state/signup/steps/site-goals-array/actions.js
  client/state/signup/steps/site-goals-array/reducer.js
  client/state/signup/steps/site-goals-array/schema.js
  client/state/signup/steps/site-goals-array/selectors.js
  client/state/signup/steps/site-goals-array/test/reducer.js
  client/state/signup/steps/site-goals-array/test/selectors.js
Labels: Signup, [Status] Needs Review

#24012 Rewind - Credentials: disable the button to revoke credentials when it's clicked
  client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx
  client/my-sites/site-settings/jetpack-credentials/credentials-configured/style.scss
Labels: Activity/Rewind, [Status] Needs Review, [Type] Enhancement

#24017 Showcase: Fix div padding in theme switch modal
  client/my-sites/themes/style.scss
Labels: Testing, Themes, [Status] Ready to Merge

#23910 Activity Log: when fixing credentials, send user to autoconfig flow if it's supported
  client/my-sites/stats/activity-log-item/index.jsx
Labels: Activity/Rewind, [Status] Needs Review, [Type] Bug

#23926 Me: Update ApplicationPasswords to use Redux and cleanup
  client/me/application-password-item/index.jsx
  client/me/application-passwords/README.md
  client/me/application-passwords/index.jsx
  client/me/security/controller.js
  client/me/two-step/index.jsx
Labels: Me, [Status] Ready to Merge, [Type] Janitorial

#21226 Domains: ccTLDs/ca-form: Always show organization field
  client/components/domains/registrant-extra-info/ca-form.jsx
  client/components/domains/registrant-extra-info/fr-form.jsx
  client/components/domains/registrant-extra-info/style.scss
  client/components/forms/form-label/index.jsx
  client/components/forms/form-label/style.scss
  client/my-sites/domains/components/form/input.jsx
Labels: Domains, [Status] Needs Author Reply, [Type] Bug

#23819 Update CSP policy after gathering reports
  server/pages/index.js
Labels: Security, [Status] Ready to Merge
