Repository Automattic/wp-calypso, pull requests merged in 2019-11, with the labels that each got.

#37217 Gutenboarding: Fix state updating
  client/landing/gutenboarding/components/header/index.tsx
  client/landing/gutenboarding/onboarding-block/edit.tsx
  client/landing/gutenboarding/store/index.ts
Labels: State, [Goal] Onboarding, [Status] Ready to Merge, [Type] Feature progress

#37174 Onboarding block styling
  client/landing/gutenboarding/components/header/style.scss
  client/landing/gutenboarding/gutenboard.tsx
  client/landing/gutenboarding/onboarding-block/edit.tsx
  client/landing/gutenboarding/onboarding-block/style.scss
  client/landing/gutenboarding/style.scss
Labels: Design, [Goal] Gutenberg, [Goal] Onboarding, [Status] Ready to Merge, [Type] Feature progress

#37213 Atomic Hosting: Rename PHPMyAdmin to phpMyAdmin
  client/my-sites/hosting/main.js
  client/my-sites/hosting/phpmyadmin-card/index.js
Labels: [Status] Needs Review

#37209 Stripe: loadScript already returns a promise
  client/lib/stripe/index.js
Labels: [Status] Needs Review, [Type] Janitorial

#37211 Store Transactions: move payment creator functions to separate module
  client/lib/store-transactions/index.js
  client/lib/transaction/payments.js
  client/my-sites/checkout/checkout/credit-card-selector.jsx
  client/my-sites/checkout/checkout/secure-payment-form.jsx
  client/my-sites/checkout/checkout/web-payment-box.jsx
Labels: Checkout, [Status] Needs Review

#37212 Store Transactions: move hasDomainDetails to Transaction Store
  client/lib/store-transactions/index.js
  client/lib/transaction/selectors.js
  client/lib/transaction/store.js
  client/my-sites/checkout/checkout/index.jsx
  client/my-sites/checkout/checkout/test/checkout.js
Labels: [Status] Needs Review, [Type] Janitorial

#37210 Store Transactions: move transaction analytics to a separate module
  client/lib/cart/store/cart-analytics.js
  client/lib/store-transactions/analytics.js
  client/my-sites/checkout/checkout/secure-payment-form.jsx
Labels: Checkout, [Status] Needs Review

#37218 Block picker search term tracking: turn terms lowercase before tracking
  apps/wpcom-block-editor/src/common/tracking/wpcom-block-picker-search-term-handler.js
Labels: [Status] Ready to Merge, [Type] Bug

#37161 Domains: Ensure form label wraps/targets the field its intended for
  client/my-sites/domains/domain-management/site-redirect/index.jsx
Labels: Domains, [Status] Needs Review

#37247 Extend wait times for calypso.live
  test/e2e/scripts/wait-for-running-branch.sh
Labels: [Status] Needs Review

#37252 Duplicate Submissions of Downgrades are Possible
  client/components/marketing-survey/cancel-purchase-form/index.jsx
Labels: [Status] Needs Review

#37156 Domains: Reduce right margin on Domains SectionHeader button to add a domain.
  client/my-sites/domains/domain-management/list/index.jsx
  client/my-sites/domains/domain-management/list/style.scss
Labels: Domains, [Status] Ready to Merge

#36893 Update Credit Card Logos
  client/assets/images/upgrades/cc-amex-disabled.svg
  client/assets/images/upgrades/cc-amex.svg
  client/assets/images/upgrades/cc-cvv-back.svg
  client/assets/images/upgrades/cc-cvv-front.svg
  client/assets/images/upgrades/cc-diners-disabled.svg
  client/assets/images/upgrades/cc-diners.svg
  client/assets/images/upgrades/cc-discover-disabled.svg
  client/assets/images/upgrades/cc-discover.svg
  client/assets/images/upgrades/cc-jcb-disabled.svg
  client/assets/images/upgrades/cc-jcb.svg
  client/assets/images/upgrades/cc-mastercard-disabled.svg
  client/assets/images/upgrades/cc-mastercard.svg
  client/assets/images/upgrades/cc-placeholder.svg
  client/assets/images/upgrades/cc-unionpay-disabled.svg
  client/assets/images/upgrades/cc-unionpay.svg
  client/assets/images/upgrades/cc-visa-disabled.svg
  client/assets/images/upgrades/cc-visa.svg
  client/components/credit-card-form-fields/index.jsx
  client/components/credit-card/docs/example.jsx
  client/components/credit-card/index.jsx
  client/components/credit-card/stored-card.jsx
  client/components/credit-card/stored-card.scss
  client/components/credit-card/style.scss
  client/components/payment-logo/index.jsx
  client/components/payment-logo/style.scss
  client/components/upgrades/credit-card-number-input/index.jsx
  client/components/upgrades/credit-card-number-input/style.scss
  static/images/upgrades/cc-amex-disabled.svg
  static/images/upgrades/cc-amex.svg
  static/images/upgrades/cc-diners-disabled.svg
  static/images/upgrades/cc-diners.svg
  static/images/upgrades/cc-discover-disabled.svg
  static/images/upgrades/cc-discover.svg
  static/images/upgrades/cc-jcb-disabled.svg
  static/images/upgrades/cc-jcb.svg
  static/images/upgrades/cc-mastercard-disabled.svg
  static/images/upgrades/cc-mastercard.svg
  static/images/upgrades/cc-unionpay-disabled.svg
  static/images/upgrades/cc-unionpay.svg
  static/images/upgrades/cc-visa-disabled.svg
  static/images/upgrades/cc-visa.svg
Labels: [Status] Needs Review, [Type] Janitorial

#37177 Checkout: Fix Payment Box Radio
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/my-sites/checkout/checkout/style.scss
Labels: Checkout, [Status] Ready to Merge

#37202 Revert signupWithBasicSite A/B test
  client/lib/abtest/active-tests.js
  client/signup/config/flows-pure.js
  client/signup/steps/site-type/index.jsx
  client/signup/steps/site-type/style.scss
Labels: ABTest, [Status] Needs Review, [Status] Needs e2e Testing

#37215 Dissolve the lib/upgrades module
  .github/CODEOWNERS
  client/components/data/domain-management/index.jsx
  client/components/marketing-survey/cancel-auto-renewal-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/lib/domains/dns/action-types.js
  client/lib/domains/dns/actions.js
  client/lib/domains/dns/reducer.js
  client/lib/domains/dns/test/reducer.js
  client/lib/domains/index.js
  client/lib/domains/nameservers/action-types.js
  client/lib/domains/nameservers/actions.js
  client/lib/domains/nameservers/reducer.js
  client/lib/domains/nameservers/test/store.js
  client/lib/domains/site-redirect/README.md
  client/lib/domains/site-redirect/action-types.js
  client/lib/domains/site-redirect/actions.js
  client/lib/domains/site-redirect/reducer.js
  client/lib/domains/wapi-domain-info/action-types.js
  client/lib/domains/wapi-domain-info/actions.js
  client/lib/domains/wapi-domain-info/reducer.js
  client/lib/purchases/actions.js
  client/lib/upgrades/action-types.js
  client/lib/upgrades/actions/domain-management.js
  client/lib/upgrades/actions/index.js
  client/me/purchases/cancel-purchase/button.jsx
  client/me/purchases/confirm-cancel-domain/index.jsx
  client/me/purchases/manage-purchase/auto-renew-toggle/index.jsx
  client/my-sites/checkout/checkout/notices.jsx
  client/my-sites/checkout/checkout/secure-payment-form.jsx
  client/my-sites/checkout/checkout/test/checkout.js
  client/my-sites/domains/domain-management/components/icann-verification/index.jsx
  client/my-sites/domains/domain-management/dns/dns-add-new.jsx
  client/my-sites/domains/domain-management/dns/dns-list.jsx
  client/my-sites/domains/domain-management/dns/domain-connect-record.jsx
  client/my-sites/domains/domain-management/dns/email-provider.jsx
  client/my-sites/domains/domain-management/edit/registered-domain.jsx
  client/my-sites/domains/domain-management/list/index.jsx
  client/my-sites/domains/domain-management/manage-consent/index.jsx
  client/my-sites/domains/domain-management/name-servers/index.jsx
  client/my-sites/domains/domain-management/primary-domain/index.jsx
  client/my-sites/domains/domain-management/site-redirect/index.jsx
  client/my-sites/domains/domain-management/transfer/transfer-out/icann-verification.jsx
  client/my-sites/domains/domain-management/transfer/transfer-out/locked.jsx
  client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx
  client/my-sites/site-settings/disconnect-site/confirm.jsx
  client/state/sites/domains/actions.js
Labels: Checkout, Domains, [Status] Needs Review, [Status] Needs e2e Testing

#37224 lib/route: Remove redundant implementation
  client/lib/route/add-query-args.ts
  client/lib/route/index.ts
  client/lib/route/normalize.ts
  client/lib/route/page-notifier.js
  client/lib/route/redirect.ts
  client/lib/route/trailingslashit.js
  client/lib/route/trailingslashit.ts
  client/lib/route/untrailingslashit.js
  client/lib/route/untrailingslashit.ts
Labels: [Status] Ready to Merge, [Type] Janitorial

#37228 lib/route: Declare no side effects for tree-shaking
  client/lib/route/package.json
Labels: Performance, [Status] Ready to Merge

#37203 Jetpack Backup: Cleanup all <p>s from descriptions
  client/blocks/product-selector/index.jsx
  client/components/product-card/index.jsx
  client/lib/products-values/constants.js
Labels: Jetpack, Plans, [Pri] Low, [Status] Ready to Merge, [Type] Janitorial

#37031 Node LTS 12
  .circleci/config.yml
  .nvmrc
  Dockerfile
  apps/full-site-editing/package-lock.json
  package.json
Labels: Build, Framework, [Status] Needs Review

#37298 Revert "Node LTS 12"
  .circleci/config.yml
  .nvmrc
  Dockerfile
  apps/full-site-editing/package-lock.json
  package.json
Labels: [Status] Needs Review

#37297 Plans: Use ExternalLink for Jetpack Backup external links
  client/lib/products-values/constants.js
Labels: Jetpack, Plans, [Pri] Normal, [Status] Needs Review, [Type] Enhancement

#37226 Add types to missing files in `lib/route`.
  client/lib/route/legacy-routes.ts
  client/lib/route/path.ts
Labels: [Status] Needs Review, [Type] Janitorial

#37250 Plans: Implement plan and product upsells for Jetpack backup product
  client/blocks/product-selector/README.md
  client/blocks/product-selector/index.jsx
  client/components/product-card/README.md
  client/components/product-card/index.jsx
  client/lib/plans/constants.js
  client/lib/plans/plans-list.js
  client/lib/products-values/constants.js
Labels: Jetpack, Plans, [Pri] Normal, [Status] Needs Review, [Type] Feature progress

#37303 Plans Page: update devdoc so that no longer P tag is used in description
  client/blocks/product-selector/docs/example.jsx
  client/components/product-card/README.md
  client/components/product-card/docs/example.jsx
Labels: Components, Plans, [Status] Ready to Merge, [Type] Feature progress

#37307 Fix script not waiting for correct branch
  test/e2e/scripts/wait-for-running-branch.sh
Labels: [Status] Needs Review

#36865 Importers: Simplify Importers screens
  client/lib/importer/importer-config.js
  client/my-sites/importer/author-mapping-item.scss
  client/my-sites/importer/author-mapping-pane.jsx
  client/my-sites/importer/author-mapping-pane.scss
  client/my-sites/importer/file-importer.jsx
  client/my-sites/importer/file-importer.scss
  client/my-sites/importer/importer-action-buttons/action-button.scss
  client/my-sites/importer/importer-godaddy-gocentral.jsx
  client/my-sites/importer/importer-header/index.jsx
  client/my-sites/importer/importer-header/start-button.jsx
  client/my-sites/importer/importer-header/start-button.scss
  client/my-sites/importer/importer-header/style.scss
  client/my-sites/importer/importer-logo.scss
  client/my-sites/importer/importer-wix.jsx
  client/my-sites/importer/importing-pane.jsx
  client/my-sites/importer/importing-pane.scss
  client/my-sites/importer/section-import.jsx
  client/my-sites/importer/section-import.scss
  client/my-sites/importer/site-importer/index.jsx
  client/my-sites/importer/site-importer/site-importer-importable-content.scss
  client/my-sites/importer/site-importer/site-importer-input-pane.jsx
  client/my-sites/importer/site-importer/site-importer-input-pane.scss
  client/my-sites/importer/site-importer/site-importer-site-preview.jsx
  client/my-sites/importer/site-importer/site-importer-site-preview.scss
  client/my-sites/importer/uploading-pane.jsx
  client/my-sites/importer/uploading-pane.scss
  test/e2e/lib/pages/import-page.js
Labels: Import

#36776 Full Site Editing: Stop using theme classes for template parts (experiment)
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/navigation-menu/index.php
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/editor-template-classes/index.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/templates/class-wp-template.php
Labels: [Goal] Full Site Editing, [Status] Ready to Merge

#37248 Gutenboarding: updates to question styles
  client/landing/gutenboarding/components/header/index.tsx
  client/landing/gutenboarding/components/header/style.scss
  client/landing/gutenboarding/onboarding-block/edit.tsx
  client/landing/gutenboarding/onboarding-block/style.scss
  client/landing/gutenboarding/store/actions.ts
  client/landing/gutenboarding/store/reducer.ts
  client/landing/gutenboarding/store/types.ts
Labels: [Goal] Gutenberg, [Goal] Onboarding, [Status] Needs Review, [Type] Feature progress

#37309 e2e-Fix wait script and Add FAIL status support
  test/e2e/scripts/wait-for-running-branch.sh
Labels: [Status] Needs Review

#37241 Add atomic hosting eligibility check to limit rollout to new sites
  client/my-sites/hosting/controller.js
  client/my-sites/sidebar/index.jsx
  client/state/selectors/can-site-view-atomic-hosting.js
Labels: [Status] Needs Review

#37314 lib/route: Remove deprecated redirect function
  client/lib/route/index.ts
  client/lib/route/redirect.ts
Labels: [Status] Ready to Merge, [Type] Bug

#37225 Gutenboarding: hide block UI via CSS
  client/landing/gutenboarding/gutenboard.tsx
  client/landing/gutenboarding/style.scss
Labels: [Goal] Gutenberg, [Goal] Onboarding, [Status] Ready to Merge

#37313 Gutenboarding: Simplify vertical state
  client/landing/gutenboarding/store/actions.ts
  client/landing/gutenboarding/store/reducer.ts
  client/landing/gutenboarding/store/resolvers.ts
  client/landing/gutenboarding/store/selectors.ts
  client/landing/gutenboarding/store/types.ts
Labels: NUX, [Goal] Gutenberg, [Goal] Onboarding, [Status] Needs Review, [Type] Feature progress, [Type] Janitorial

#37165 Gutenboarding: Vertical autocomplete
  client/landing/gutenboarding/onboarding-block/edit.tsx
  client/landing/gutenboarding/onboarding-block/style.scss
  client/landing/gutenboarding/store/selectors.ts
Labels: [Goal] Gutenberg, [Goal] Onboarding, [Status] Needs Review, [Type] Feature progress

#37301 Plans: Enable Jetpack Backups only on Jetpack >= 7.9alpha
  client/my-sites/plans-features-main/index.jsx
Labels: Jetpack, Plans, [Pri] Normal, [Status] Ready to Merge, [Type] Feature progress

#37101 Store: Remove createReducer from shipping-zone-method-settings
  client/extensions/woocommerce/woocommerce-services/state/shipping-zone-method-settings/reducer.js
Labels: Framework, Store, [Status] Ready to Merge, [Type] Janitorial

#37304 Blocks: Product Selector - Update included link, handle plan names better
  client/blocks/product-selector/index.jsx
Labels: Components, Jetpack, Plans, [Status] Ready to Merge, [Type] Enhancement

#35918 Credit Card: Refactor in TypeScript
  client/components/credit-card/README.md
  client/components/credit-card/index.jsx
  client/components/credit-card/index.tsx
  client/components/credit-card/stored-card.tsx
Labels: Billing, Payment Methods, Purchases, [Status] Ready to Merge

#37153 Add `webpack-config-flag-plugin`.
  babel.config.js
  client/state/lib/middleware.js
  npm-shrinkwrap.json
  package.json
  packages/webpack-config-flag-plugin/.eslintrc.js
  packages/webpack-config-flag-plugin/README.md
  packages/webpack-config-flag-plugin/index.js
  packages/webpack-config-flag-plugin/jest.config.js
  packages/webpack-config-flag-plugin/package.json
  packages/webpack-config-flag-plugin/test/__snapshots__/index.js.snap
  packages/webpack-config-flag-plugin/test/fixtures/.eslintrc.js
  packages/webpack-config-flag-plugin/test/fixtures/config.js
  packages/webpack-config-flag-plugin/test/fixtures/default-import/function.js
  packages/webpack-config-flag-plugin/test/fixtures/default-import/index.js
  packages/webpack-config-flag-plugin/test/fixtures/default-import/module.js
  packages/webpack-config-flag-plugin/test/fixtures/default-import/rename.js
  packages/webpack-config-flag-plugin/test/fixtures/default-import/shadowed-by-param.js
  packages/webpack-config-flag-plugin/test/fixtures/default-import/shadowed-by-var.js
  packages/webpack-config-flag-plugin/test/fixtures/default-import/wrong-flag.js
  packages/webpack-config-flag-plugin/test/fixtures/default-import/wrong-path.js
  packages/webpack-config-flag-plugin/test/fixtures/main.js
  packages/webpack-config-flag-plugin/test/fixtures/named-import/function.js
  packages/webpack-config-flag-plugin/test/fixtures/named-import/index.js
  packages/webpack-config-flag-plugin/test/fixtures/named-import/module.js
  packages/webpack-config-flag-plugin/test/fixtures/named-import/rename.js
  packages/webpack-config-flag-plugin/test/fixtures/named-import/shadowed-by-param.js
  packages/webpack-config-flag-plugin/test/fixtures/named-import/shadowed-by-var.js
  packages/webpack-config-flag-plugin/test/fixtures/named-import/wrong-flag.js
  packages/webpack-config-flag-plugin/test/fixtures/named-import/wrong-path.js
  packages/webpack-config-flag-plugin/test/fixtures/namespace-import/function.js
  packages/webpack-config-flag-plugin/test/fixtures/namespace-import/index.js
  packages/webpack-config-flag-plugin/test/fixtures/namespace-import/module.js
  packages/webpack-config-flag-plugin/test/fixtures/namespace-import/rename.js
  packages/webpack-config-flag-plugin/test/fixtures/namespace-import/shadowed-by-param.js
  packages/webpack-config-flag-plugin/test/fixtures/namespace-import/shadowed-by-var.js
  packages/webpack-config-flag-plugin/test/fixtures/namespace-import/wrong-flag.js
  packages/webpack-config-flag-plugin/test/fixtures/namespace-import/wrong-path.js
  packages/webpack-config-flag-plugin/test/index.js
  webpack.config.js
Labels: Build, [Status] Needs Review

#36159 Fix site clone point styling
  client/my-sites/activity/activity-log-item/style.scss
  client/signup/steps/clone-point/index.jsx
  client/signup/steps/clone-point/style.scss
Labels: Rewind, [Status] Needs Review

#37324 Add interval discount note to the product selector in Jetpack Connect flow
  client/blocks/product-selector/README.md
  client/blocks/product-selector/index.jsx
  client/components/product-card/README.md
  client/components/product-card/action.jsx
  client/my-sites/plans-features-main/index.jsx
Labels: Components, Plans, [Type] Feature progress

#37255 Refactor site options and add new HOC
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-description/edit.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-title/edit.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/lib/index.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/lib/site-options/index.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/lib/site-options/use-previous.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/lib/site-options/use-site-options.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/lib/site-options/with-site-options.js
Labels: [Goal] Full Site Editing

#37239 List Views: Correct Copy Link styling.
  client/my-sites/post-type-list/post-actions-ellipsis-menu/style.scss
Labels: [Status] Needs Design Review, [Status] Needs Review, [Type] Bug

#37234 FSE: Add back button from wp admin windowed mode
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/close-button-override/index.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/close-button-override/style.scss
Labels: [Goal] Full Site Editing, [Status] Ready to Merge

#37300 Atomic: Update blocked plugins from October 2019
  client/my-sites/plugins/plugin-meta/index.jsx
Labels: Atomic, [Type] Janitorial

#36903 Media: No Content - Migrate Image to Webpack
  client/assets/images/illustrations/media.svg
  client/my-sites/media-library/list-no-content.jsx
Labels: Media, [Status] Needs Review

#37345 Translator instructions for John Appleseed
  client/lib/signup/site-type.js
Labels: Frontend, Signup, [Status] Needs Review, i18n

#36549 Updated New Password text message to make it more meaningful
  client/me/account-password/index.jsx
Labels: [Status] String Freeze

#37319 Domains DNS: promisify the addDns, deleteDns and applyDnsTemplate actions
  client/lib/domains/dns/actions.js
  client/lib/domains/dns/index.js
  client/my-sites/domains/domain-management/dns/dns-list.jsx
  client/my-sites/domains/domain-management/dns/dns-record.jsx
  client/my-sites/domains/domain-management/dns/domain-connect-record.jsx
  client/my-sites/domains/domain-management/dns/email-provider.jsx
Labels: Domains, [Status] Needs Review

#36653 G Suite: Prevent users from adding G Suite to mapped domains without WordPress.com nameservers
  client/lib/domains/index.js
  client/lib/gsuite/index.js
  client/lib/gsuite/test/index.js
  client/my-sites/email/email-management/index.jsx
Labels: G Suite, [Status] Needs Review, [Status] Needs e2e Testing

#37350 Products Page: Minor wording update to match designs
  client/lib/products-values/constants.js
Labels: [Status] Ready to Merge, [Type] Bug

#37331 Add primary color dark var to Jetpack Connect flow to fix focus state
  client/jetpack-connect/colors.scss
Labels: Jetpack, Plans, [Status] Ready to Merge, [Type] Bug

#37330 Gutenboarding: add `isFilledFormValue` FormValue helper
  client/landing/gutenboarding/onboarding-block/edit.tsx
  client/landing/gutenboarding/store/types.ts
Labels: State, [Status] Needs Review

#36723 Modernize `date-range`
  client/components/date-range/header.js
  client/components/date-range/header.tsx
  client/components/date-range/index.js
  client/components/date-range/inputs.js
  client/components/date-range/inputs.tsx
  client/components/date-range/test/__snapshots__/index.js.snap
  client/components/date-range/trigger.js
  client/components/date-range/trigger.tsx
Labels: Components, [Status] Needs Review, [Type] Janitorial

#37358 Google Drive: Add a feature flag
  client/state/sharing/services/selectors.js
  config/development.json
Labels: Contact Form, [Status] Needs Review

#36534 Monorepo: add package.json linter
  apps/README.md
  apps/full-site-editing/package.json
  apps/notifications/package.json
  apps/o2-blocks/package.json
  apps/wpcom-block-editor/package.json
  docs/monorepo.md
  npm-shrinkwrap.json
  npmpackagejsonlint.config.js
  package.json
  packages/README.md
  packages/babel-plugin-i18n-calypso/package.json
  packages/babel-plugin-transform-wpcalypso-async/package.json
  packages/calypso-build/package.json
  packages/calypso-color-schemes/package.json
  packages/components/package.json
  packages/composite-checkout/package.json
  packages/eslint-config-wpcalypso/package.json
  packages/eslint-plugin-wpcalypso/package.json
  packages/format-currency/package.json
  packages/i18n-calypso-cli/package.json
  packages/i18n-calypso/package.json
  packages/load-script/package.json
  packages/material-design-icons/package.json
  packages/muriel-style/package.json
  packages/photon/package.json
  packages/tree-select/package.json
  packages/webpack-extensive-lodash-replacement-plugin/package.json
  packages/webpack-inline-constant-exports-plugin/package.json
Labels: Build, [Status] Needs Review, [Type] Enhancement

#37347 FSE - Nav Menu to add new page when published.
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/navigation-menu/edit.js
Labels: [Goal] Full Site Editing, [Status] Ready to Merge

#37321 Atomic Hosting: Change page title to SFTP & MySQL
  client/my-sites/hosting/main.js
Labels: [Status] Needs Review

#37139 Update Crowdsignal OAuth pages styling
  client/blocks/login/index.jsx
  client/blocks/login/login-form.jsx
  client/blocks/signup-form/crowdsignal.jsx
  client/blocks/signup-form/crowdsignal.scss
  client/layout/masterbar/crowdsignal.jsx
  client/layout/masterbar/crowdsignal.scss
  client/layout/masterbar/oauth-client.scss
  client/signup/steps/user/index.jsx
Labels: Login, Signup

#37220 Atomic Hosting: Restore DB password
  client/my-sites/hosting/phpmyadmin-card/index.js
  client/my-sites/hosting/phpmyadmin-card/restore-db-password.js
  client/my-sites/hosting/style.scss
  client/state/action-types.js
  client/state/data-layer/wpcom/sites/hosting/restore-database-password.js
  client/state/hosting/actions.js
Labels: [Status] Needs Review

#37353 SIWA: Update the login return uri
  client/lib/paths/login/index.js
  server/api/sign-in-with-apple.js
Labels: Login, [Status] Needs Review

#37369 Revert "SIWA: Update the login return uri"
  client/lib/paths/login/index.js
  server/api/sign-in-with-apple.js
Labels: Login

#37377 Update hosting cards to not use flex align-items stretch (default)
  client/my-sites/hosting/style.scss
Labels: [Status] Needs Review

#37222 Plans: Add Tracks event to Mobile Apps card on My Plan page
  client/blocks/product-purchase-features-list/index.jsx
  client/blocks/product-purchase-features-list/mobile-apps.jsx
Labels: Analytics, Plans, [Status] Needs Review, [Type] Enhancement

#37362 G Suite: Remove misleading mentions to voice calls
  client/components/gsuite/gsuite-features/index.jsx
  client/components/gsuite/gsuite-features/test/__snapshots__/compact.js.snap
  client/components/gsuite/gsuite-features/test/__snapshots__/index.js.snap
  client/components/upgrades/gsuite/gsuite-upsell-card/index.jsx
  client/my-sites/email/gsuite-purchase-cta/test/__snapshots__/index.js.snap
Labels: GSuite, [Status] Needs e2e Testing, [Status] Ready to Merge

#32899 Modernize the RootChild component (try 2)
  client/blocks/edit-gravatar/index.jsx
  client/components/accordion/status.jsx
  client/components/accordion/test/status.jsx
  client/components/dialog/index.jsx
  client/components/root-child/index.jsx
  client/components/root-child/test/index.jsx
  client/extensions/woocommerce/app/settings/email/mailchimp/sync_tab.js
  client/extensions/woocommerce/components/dashboard-widget/index.js
  client/extensions/woocommerce/woocommerce-services/components/info-tooltip/index.js
  client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/price-summary.js
  client/layout/masterbar/publish.jsx
  client/me/security-2fa-backup-codes-list/index.jsx
  client/my-sites/comments/comment/comment-author.jsx
  client/my-sites/marketing/connections/account-dialog-account.jsx
  client/my-sites/marketing/connections/account-dialog.jsx
  client/my-sites/plugins/disconnect-jetpack/disconnect-jetpack-button.jsx
  client/my-sites/site-settings/delete-site-warning-dialog/index.jsx
  client/my-sites/stats/post-trends/day.jsx
  client/my-sites/theme/test/main.jsx
  client/post-editor/editor-action-bar/view-link.jsx
  client/post-editor/editor-permalink/index.jsx
  client/post-editor/editor-sticky/index.jsx
Labels: Components, Framework, [Status] Needs Review

#37360 Split decode utils in lib/url.
  client/lib/url/decode-utils.ts
  client/lib/url/index.ts
  client/lib/url/test/decode-utils.js
Labels: [Status] Needs Review, [Type] Janitorial

#37375 Update canSiteViewAtomicHosting to include user capabilities check
  client/state/selectors/can-site-view-atomic-hosting.js
Labels: [Status] Needs Review

#37245 Classic Editor: remove the Advanced Media Editor experiment
  client/components/tinymce/plugins/media/advanced/index.jsx
  client/components/tinymce/plugins/media/plugin.jsx
  client/components/tinymce/plugins/wpeditimage/plugin.js
  client/post-editor/editor-media-advanced/index.jsx
  config/desktop-development.json
  config/development.json
  config/test.json
Labels: Editor, [Status] Needs Review, [Type] Janitorial

#36520 Refactor fetching OAuth2 client info, remove cachingActionCreatorFactory
  client/login/controller.js
  client/state/action-types.js
  client/state/oauth2-clients/actions.js
  client/state/oauth2-clients/reducer.js
  client/state/oauth2-clients/test/reducer.js
  client/state/test/utils.js
  client/state/utils/caching-action-creator-factory.js
  client/state/utils/index.ts
Labels: Login, State, [Status] Needs Review

#37310 Make template preview area use system fonts
  apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-preview.js
  apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/test/__snapshots__/template-selector-preview-test.js.snap
  apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss
Labels: [Status] Needs Review

#37386 Contact Details Form: Fix country select width
  client/components/domains/contact-details-form-fields/style.scss
Labels: Checkout, Domains, [Status] Needs Review

#37374 Store: Remove createReducer from ui-shipping-zones
  client/extensions/woocommerce/state/ui/shipping/zones/reducer.js
Labels: State, Store, [Status] Ready to Merge, [Type] Janitorial

#37373 Store: Remove createReducer from shipping-zone-locations
  client/extensions/woocommerce/state/sites/shipping-zone-locations/reducer.js
Labels: State, Store, [Status] Ready to Merge, [Type] Janitorial

#37393 Reconfigure Renovate ( Remove Calypso Packages groupname )
  renovate.json
Labels: Framework, [Status] Needs Review

#37371 SIWA: Make sure we have sent the apple user info to the server before redirecting
  client/me/social-login/action-button.jsx
  client/me/social-login/index.jsx
  client/me/social-login/service.jsx
  server/api/sign-in-with-apple.js
Labels: Login, [Status] Needs Review

#37263 Refactor lib/user out of analytics
  apps/wpcom-block-editor/src/common/tracking/track-record-event.js
  client/blocks/signup-form/passwordless.jsx
  client/boot/common.js
  client/landing/login/common.js
  client/lib/analytics/ad-tracking.js
  client/lib/analytics/index.js
  client/lib/analytics/test/google-analytics.js
  client/lib/analytics/test/index.js
  client/lib/analytics/utils/current-user.js
  client/lib/analytics/utils/get-normalized-hashed-user-email.js
  client/lib/analytics/utils/index.js
  client/lib/signup/step-actions.js
Labels: Analytics, [Status] Needs Review

#37130 Jetpack Settings: update Jetpack Anti-spam security settings card title
  client/my-sites/site-settings/form-security.jsx
Labels: Jetpack, Site Settings, [Pri] Normal, [Status] Ready to Merge, [Type] Enhancement

#37265 Add Floodlight/Google Ads Signup Start events
  client/lib/analytics/ad-tracking.js
  client/lib/analytics/index.js
Labels: Analytics, [Status] Needs Review

#37415 Signup: Add sub-header to plans step.
  client/signup/config/steps-pure.js
  client/signup/steps/plans/index.jsx
Labels: Signup, [Status] Needs Review

#37388 Jetpack Backups: Cleanup any product upsells
  client/blocks/product-selector/README.md
  client/blocks/product-selector/index.jsx
  client/lib/products-values/constants.js
Labels: Jetpack, Plans, [Status] Ready to Merge, [Type] Feature progress

#37414 Gutenboarding: Improve header
  client/landing/gutenboarding/components/header/index.tsx
  client/landing/gutenboarding/components/header/style.scss
Labels: Design, [Status] Needs Review, [Type] Feature progress

#37385 Move traintracks analytics out of suggestions
  client/components/suggestion-search/index.jsx
  client/components/suggestion-search/test/index.js
  client/components/suggestions/index.jsx
  client/components/suggestions/item.jsx
  client/components/suggestions/test/__snapshots__/index.js.snap
  client/components/suggestions/test/index.js
Labels: Analytics, Components, [Status] Needs Review, [Type] Feature progress, [Type] Janitorial

#37312 Fix `isExternal` for falsy values.
  client/lib/url/is-external.ts
Labels: [Status] Needs Review, [Type] Bug

#36678 Framework: Remove createReducer
  .eslintrc.js
  client/state/test/mocks/schema.js
  client/state/test/utils.js
  client/state/utils/create-base-reducer.js
  client/state/utils/create-reducer-with-validation.js
  client/state/utils/create-reducer.js
  client/state/utils/index.ts
  client/state/utils/reducer-utils.js
Labels: Framework, State, [Status] Ready to Merge, [Type] Janitorial

#37396 Jetpack Backups: Consider current plan and product in all states
  client/blocks/product-selector/index.jsx
  client/lib/plans/plans-list.js
Labels: Jetpack, Plans, [Pri] Normal, [Status] Ready to Merge, [Type] Feature progress

#37439 Suggestions: Extract to @automattic/omponents
  client/components/suggestion-search/index.jsx
  client/components/suggestion-search/test/index.js
  client/components/suggestions/README.md
  client/components/suggestions/docs/example.jsx
  client/devdocs/design/component-examples.js
  client/devdocs/design/index.jsx
  client/devdocs/design/playground-scope.js
  client/extensions/zoninator/components/search-autocomplete/post-suggestions.jsx
  client/my-sites/domains/domain-management/transfer/transfer-out/select-ips-tag.jsx
  npm-shrinkwrap.json
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/components/src/index.js
  packages/components/src/suggestions/README.md
  packages/components/src/suggestions/docs/example.jsx
  packages/components/src/suggestions/index.jsx
  packages/components/src/suggestions/item.jsx
  packages/components/src/suggestions/style.scss
  packages/components/src/suggestions/test/__snapshots__/index.js.snap
  packages/components/src/suggestions/test/index.js
Labels: Components, Packages, [Status] Needs Review, [Type] Enhancement, [Type] Feature progress

#37437 CancelPurchaseForm: Update class => className
  client/components/marketing-survey/cancel-purchase-form/index.jsx
Labels: Purchases, [Status] Ready to Merge, [Type] Bug, [Type] Janitorial

#37441 Jetpack Product Purchace redirect the user to the my plans page
  client/my-sites/checkout/checkout/index.jsx
Labels: Jetpack, Plans, [Status] Ready to Merge, [Type] Feature progress

#37351 Update FormToggle README to reflect supported options
  client/components/forms/form-toggle/README.md
Labels: Components, Documentation, [Status] Ready to Merge

#37355 Gutenboarding: update site vertical selector
  client/landing/gutenboarding/components/header/index.tsx
  client/landing/gutenboarding/onboarding-block/edit.tsx
  client/landing/gutenboarding/onboarding-block/vertical-select/index.tsx
  client/landing/gutenboarding/onboarding-block/vertical-select/style.scss
  client/landing/gutenboarding/store/actions.ts
  client/landing/gutenboarding/store/reducer.ts
  client/landing/gutenboarding/store/selectors.ts
  client/landing/gutenboarding/store/types.ts
Labels: [Goal] Onboarding, [Status] Ready to Merge

#37349 Fix plan bump test errors
  client/lib/abtest/active-tests.js
  client/my-sites/checkout/checkout/index.jsx
Labels: ABTest, Marketing, Post Checkout, [Status] Needs Review

#37436 Build: Divide workers between concurrent builds
  package.json
  webpack.common.js
Labels: Build, [Status] Ready to Merge, [Type] Task

#37426 Hosting: Correct whitespace around the SFTP card's table.
  client/my-sites/hosting/style.scss
Labels: [Goal] Hosting Panel, [Status] Needs Review

#36857 G Suite: Fix white screen while trying to add G Suite for a WPcom primary sub-domain
  client/lib/gsuite/index.js
  client/lib/gsuite/test/index.js
Labels: G Suite, [Status] Ready to Merge

#37403 Gutenboarding: Eyecandy for acquire intent
  client/landing/gutenboarding/onboarding-block/edit.tsx
  client/landing/gutenboarding/onboarding-block/style.scss
  client/landing/gutenboarding/onboarding-block/vertical-select/index.tsx
  client/landing/gutenboarding/onboarding-block/vertical-select/style.scss
  client/landing/gutenboarding/store/types.ts
Labels: NUX, [Goal] Gutenberg, [Goal] Onboarding, [Status] In Progress

#37299 Update Node LTS 12 (attempt 2)
  .circleci/config.yml
  .nvmrc
  Dockerfile
  apps/full-site-editing/package-lock.json
  apps/wpcom-block-editor/package-lock.json
  npm-shrinkwrap.json
  package.json
Labels: Build, Framework, [Status] Needs Review, [Status] Ready to Merge

#37452 Gutenberg: Load selected images in gallery block
  client/gutenberg/editor/calypsoify-iframe.tsx
Labels: [Status] Needs Review

#37482 Blocks: Update ProductSelector to default to last option as selected
  client/blocks/product-selector/index.jsx
Labels: Components, Jetpack, Plans, [Status] Ready to Merge, [Type] Enhancement

#37048 Add spacing before and after Uploaded themes text and Install Theme button
  client/my-sites/themes/theme-showcase.scss
  client/my-sites/themes/themes-selection-header/style.scss
  client/my-sites/themes/themes-selection.scss
Labels: Themes, [Status] Ready to Merge

#37400 [e2e] Updates for more stable runs
  test/e2e/lib/pages/editor-page.js
  test/e2e/lib/pages/frontend/comments-area-component.js
  test/e2e/specs/wp-signup-spec.js
Labels: [Status] Needs Review

#37420 Update sauce chrome config
  test/e2e/config/default.json
  test/e2e/lib/driver-helper.js
  test/e2e/lib/driver-manager.js
Labels: [Status] Needs Review

#37486 Make determineUrlType stricter.
  client/lib/url/url-type.ts
Labels: [Status] Needs Review, [Type] Enhancement

#37068 Add format method to lib/url.
  client/lib/url/format.ts
  client/lib/url/index.ts
  client/lib/url/test/format.js
Labels: [Status] Needs Review, [Type] New feature

#37378 Gutenberg-first theme ThanksModal
  client/my-sites/themes/thanks-modal.jsx
  client/my-sites/themes/theme-options.js
  client/state/selectors/get-customize-or-edit-front-page-url.js
  client/state/selectors/should-customize-homepage-with-gutenberg.js
  client/state/themes/selectors.js
  client/state/themes/utils.js
Labels: [Goal] Onboarding, [Status] Ready to Merge, [Team] Cylon

#37159 Domains: Consider removing domain URL from HeaderCake title
  client/my-sites/domains/domain-management/components/header/index.jsx
Labels: Domains, [Status] Needs Review, [Status] Needs e2e Testing

#37430 Add/sftp hosting data layer
  client/state/action-types.js
  client/state/data-layer/wpcom/sites/hosting/sftp-user.js
  client/state/hosting/actions.js
  client/state/hosting/reducer.js
  client/state/reducer.js
  client/state/selectors/get-atomic-hosting-sftp-user.js
Labels: [Status] Needs Review

#37012 Site Credit Block Structure
  apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-credit/edit.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-credit/footer-credit-choices.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-credit/index.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-credit/index.php
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-credit/style.scss
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/index.js
Labels: [Goal] Full Site Editing, [Status] Ready to Merge

#37128 Jetpack onboarding: update Anti-spam feature name in Jetpack checklist
  client/my-sites/plans/current-plan/jetpack-checklist/index.tsx
Labels: Checklist, Jetpack, [Pri] Normal, [Status] Ready to Merge, [Type] Enhancement

#37204 [reCaptcha v3]: Hide reCAPTCHA badge on phone and show our own…
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/style.scss
  client/signup/steps/user/index.jsx
Labels: Frontend, Signup, [Status] Needs Review

#37499 Reader: link to the original post when a post is unavailable
  client/blocks/reader-full-post/unavailable.jsx
  client/components/external-link/index.jsx
Labels: Reader, [Status] Needs Review

#37484 Dockerignore node_modules anywhere in directory tree
  .dockerignore
Labels: Build, [Status] Ready to Merge

#37490 PropTypes: Disable some non-offensive lint errors
  client/my-sites/marketing/connections/services/eventbrite.js
  client/my-sites/marketing/connections/services/facebook.js
  client/my-sites/marketing/connections/services/google-my-business.js
  client/my-sites/marketing/connections/services/google-photos.js
  client/my-sites/marketing/connections/services/instagram.js
  client/my-sites/marketing/connections/services/mailchimp.js
Labels: [Status] Ready to Merge, [Type] Task

#37344 Build: Add propTypes removal transform
  .eslintrc.js
  babel.config.js
  npm-shrinkwrap.json
  package.json
Labels: Build, Performance, [Status] Ready to Merge

#37496 Plans: Update single purpose title to Solutions
  client/my-sites/plans-features-main/index.jsx
Labels: Jetpack, Plans, [Status] Ready to Merge, [Type] Feature progress

#37438 Upgrade React Redux and Redux Form
  apps/notifications/src/panel/templates/index.jsx
  apps/notifications/src/panel/templates/note-list.jsx
  apps/notifications/src/panel/templates/note.jsx
  client/blocks/image-editor/image-editor-canvas.jsx
  client/blocks/image-editor/index.jsx
  client/components/domains/registrant-extra-info/test/with-contact-details-validation.js
  client/components/tinymce/index.jsx
  client/extensions/woocommerce/components/compact-tinymce/index.js
  client/extensions/zoninator/components/search-autocomplete/index.jsx
  client/extensions/zoninator/components/search-autocomplete/post-suggestions.jsx
  client/jetpack-connect/help-button.jsx
  client/jetpack-connect/test/__snapshots__/authorize.js.snap
  client/jetpack-connect/test/__snapshots__/plans.js.snap
  client/jetpack-connect/test/__snapshots__/signup.js.snap
  client/my-sites/checkout/checkout/test/web-payment-box.js
  client/my-sites/domains/domain-management/list/index.jsx
  client/my-sites/domains/domain-management/list/test/index.js
  client/my-sites/plugins/plugins-list/test/index.jsx
  npm-shrinkwrap.json
  package.json
Labels: Framework, [Status] Needs Review

#37448 Purchases: update the purchases for backup product.
  client/lib/products-values/constants.js
  client/lib/products-values/index.js
  client/lib/purchases/index.js
  client/me/purchases/manage-purchase/index.jsx
  client/me/purchases/manage-purchase/style.scss
  client/me/purchases/purchase-item/index.jsx
  client/me/purchases/purchase-item/style.scss
Labels: Jetpack, Plans, [Status] Ready to Merge

#37485 Blocks: Persist selected option through intervals in ProductSelector
  client/blocks/product-selector/index.jsx
Labels: Components, Jetpack, Plans, [Pri] Normal, [Status] Ready to Merge, [Type] Enhancement, [Type] Feature progress

#37503 chore(build): Create a new layer for node modules
  Dockerfile
Labels: Build, [Status] Needs Review

#37449 Add upgrade button click events tracking in product selector
  client/blocks/product-selector/index.jsx
Labels: Analytics, Plans, [Status] Ready to Merge, [Type] Feature progress

#37493 Rename npm-shrinkwrap.json to package-lock.json
  .circleci/config.yml
  .gitattributes
  Dockerfile
  bin/install-if-deps-outdated.js
  docs/lockfile.md
  docs/shrinkwrap.md
  package-lock.json
  package.json
Labels: [Status] Needs Review

#37443 Atomic Hosting: Display data loss warning
  client/my-sites/hosting/data-loss-warning/index.js
  client/my-sites/hosting/data-loss-warning/style.scss
  client/my-sites/hosting/main.js
  client/my-sites/hosting/style.scss
Labels: [Status] Needs Review

#37508 Fix lint errors
  client/lib/email-followers/store.js
  client/lib/followers/store.js
  client/lib/users/store.js
Labels: [Status] Needs Review, [Type] Janitorial

#37507 Plans Page: fix favour the product purchae.
  client/blocks/product-selector/index.jsx
Labels: Jetpack, Plans, [Status] Ready to Merge, [Type] Feature progress

#37506 Dependencies: Replace json-strable-stringify with fast-…
  client/lib/email-followers/store.js
  client/lib/followers/store.js
  client/lib/users/store.js
  client/lib/wp/offline-library/index.js
  client/my-sites/people/followers-list/index.jsx
  client/my-sites/people/team-list/team.jsx
  client/state/data-layer/wpcom-http/utils.js
  client/state/followers/utils.js
  package-lock.json
  package.json
Labels: Framework, Performance, [Status] Needs Review

#37483 Gutenboarding: Add Domains Suggestions Store
  client/landing/gutenboarding/components/header/index.tsx
  client/landing/gutenboarding/gutenboard.tsx
  client/landing/gutenboarding/onboarding-block/edit.tsx
  client/landing/gutenboarding/onboarding-block/vertical-select/index.tsx
  client/landing/gutenboarding/stores/domain-suggestions/actions.ts
  client/landing/gutenboarding/stores/domain-suggestions/constants.ts
  client/landing/gutenboarding/stores/domain-suggestions/index.ts
  client/landing/gutenboarding/stores/domain-suggestions/reducer.ts
  client/landing/gutenboarding/stores/domain-suggestions/resolvers.ts
  client/landing/gutenboarding/stores/domain-suggestions/selectors.ts
  client/landing/gutenboarding/stores/domain-suggestions/types.ts
  client/landing/gutenboarding/stores/onboard/actions.ts
  client/landing/gutenboarding/stores/onboard/constants.ts
  client/landing/gutenboarding/stores/onboard/index.ts
  client/landing/gutenboarding/stores/onboard/reducer.ts
  client/landing/gutenboarding/stores/onboard/resolvers.ts
  client/landing/gutenboarding/stores/onboard/selectors.ts
  client/landing/gutenboarding/stores/onboard/types.ts
  client/landing/gutenboarding/stores/type-helpers.ts
Labels: Domains, [Status] Needs Review, [Status] Ready to Merge

#37488 Jetpack Backup: Streamline the credentials entry form
  client/components/rewind-credentials-form/index.jsx
  client/components/rewind-credentials-form/style.scss
  client/my-sites/site-settings/jetpack-credentials/credentials-setup-flow/index.jsx
  client/my-sites/site-settings/jetpack-credentials/credentials-setup-flow/setup-form.jsx
  client/my-sites/site-settings/jetpack-credentials/credentials-setup-flow/setup-start.jsx
  client/my-sites/site-settings/jetpack-credentials/credentials-setup-flow/setup-tos.jsx
  client/my-sites/site-settings/jetpack-credentials/credentials-setup-flow/style.scss
  client/my-sites/site-settings/jetpack-credentials/index.jsx
  client/signup/config/flows-pure.js
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
  client/signup/steps/creds-permission/index.jsx
  client/signup/steps/creds-permission/style.scss
  client/signup/steps/rewind-add-creds/index.jsx
  client/signup/steps/rewind-add-creds/style.scss
Labels: Rewind, [Status] Needs Review

#37516 Signup: Allow reCAPTCHA test selection for any locale
  client/lib/abtest/active-tests.js
Labels: Signup

#37456 Checkout: Remove Payment Method a/b test
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/lib/abtest/active-tests.js
  client/my-sites/checkout/checkout/payment-box.jsx
  client/my-sites/checkout/checkout/style.scss
Labels: [Status] Needs e2e Testing

#37354 Remove i18n-calypso moment from a few places.
  client/blocks/calendar-popover/docs/example.jsx
  client/me/concierge/shared/appointment-info.js
  client/me/pending-payments/pending-list-item.jsx
  client/me/pending-payments/test/index.js
  client/me/pending-payments/test/pending-list-item.js
Labels: [Status] Needs Review, [Type] Janitorial

#37522 Use more execution threads for calypso builds
  webpack.common.js
Labels: Build

#37530 Revert "Signup: Allow reCAPTCHA test selection for any locale"
  client/lib/abtest/active-tests.js
Labels: Signup, [Status] Needs Review

#37117 Try splitting out signup tests
  test/e2e/magellan.json
  test/e2e/package-lock.json
  test/e2e/package.json
  test/e2e/run.sh
  test/e2e/specs/wp-signup-spec.js
Labels: [Status] Needs e2e Testing

#37533 Give another minute to time out. Sauce takes longer
  test/e2e/magellan.json
Labels: [Status] Needs Review

#37468 Private Site: Migrate Image to Webpack
  client/assets/images/illustrations/private.svg
  client/login/wp-login/private-site.jsx
Labels: [Status] Needs Review, [Type] Janitorial

#37511 Reorganize, simplify, deduplicate typings
  client/landing/gutenboarding/stores/domain-suggestions/index.ts
  client/landing/gutenboarding/stores/mapped-types.ts
  client/landing/gutenboarding/stores/onboard/index.ts
  client/landing/gutenboarding/stores/type-helpers.ts
Labels: State, [Status] Ready to Merge

#37481 Product box: Update the link to a button
  client/components/product-card/README.md
  client/components/product-card/action.jsx
  client/components/product-card/index.jsx
  client/components/product-card/style.scss
Labels: Jetpack, Plans, [Status] Ready to Merge, [Type] Feature progress

#36859 Domains: Add public whois info disclose option in the domain settings page
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/my-sites/domains/domain-management/contacts-privacy/card.jsx
  client/my-sites/domains/domain-management/contacts-privacy/contact-display.jsx
  client/my-sites/domains/domain-management/contacts-privacy/index.jsx
  client/my-sites/domains/domain-management/contacts-privacy/style.scss
  client/my-sites/domains/domain-management/edit-contact-info/privacy-enabled-card.jsx
  client/my-sites/domains/domain-management/edit/registered-domain.jsx
  client/state/action-types.js
  client/state/data-layer/wpcom/domains/privacy/index.js
  client/state/sites/domains/actions.js
  client/state/sites/domains/assembler.js
  client/state/sites/domains/reducer.js
  client/state/sites/domains/selectors.js
  client/state/sites/domains/test/actions.js
  client/state/sites/domains/test/fixture/index.js
  client/state/sites/domains/test/reducer.js
Labels: Domains, [Status] Needs Review

#37513 Blocks: Introduce a ProductPlanOverlapNotices block
  client/blocks/product-plan-overlap-notices/README.md
  client/blocks/product-plan-overlap-notices/docs/example.jsx
  client/blocks/product-plan-overlap-notices/index.jsx
  client/devdocs/design/blocks.jsx
  client/lib/products-values/constants.js
Labels: Components, Jetpack, New Component, Plans, [Pri] Normal, [Status] Ready to Merge, [Type] Feature progress

#37442 Plans: record feature link click Tracks events in the grid
  client/components/external-link/README.md
  client/components/external-link/with-tracking.jsx
  client/lib/plans/features-list.js
  client/lib/products-values/constants.js
Labels: Analytics, Plans, [Status] Ready to Merge, [Type] Enhancement

#37514 Plans: Display the plan and product overlap notices
  client/my-sites/plans-features-main/index.jsx
Labels: Jetpack, Plans, [Pri] Normal, [Status] Ready to Merge, [Type] Feature progress

#37515 Purchases: Display the plan and product overlap notices on single purchase page
  client/me/purchases/manage-purchase/index.jsx
Labels: Jetpack, Purchases, [Pri] Normal, [Status] Ready to Merge, [Type] Feature progress

#37504 Config: Enable Jetpack Backup in Plans page on staging
  config/stage.json
Labels: Framework, [Pri] Normal, [Status] Ready to Merge, [Type] Feature progress

#37512 Add/post purchase modal backups
  client/my-sites/checkout/checkout/index.jsx
  client/my-sites/plans/current-plan/controller.jsx
  client/my-sites/plans/current-plan/current-plan-thank-you/backup-thank-you.js
  client/my-sites/plans/current-plan/index.jsx
Labels: Jetpack, Plans, [Status] Ready to Merge, [Type] Feature progress

#37546 Enable domain step copy update feature for dev
  client/lib/abtest/active-tests.js
  client/signup/steps/domains/index.jsx
  config/development.json
  config/wpcalypso.json
Labels: ABTest, Domains, Signup, [Status] Needs Review

#37495 Update query param used for the new WooCommerce + Jetpack Onboarding UI
  client/blocks/login/index.jsx
  client/blocks/login/login-form.jsx
  client/blocks/signup-form/index.jsx
  client/document/index.jsx
  client/jetpack-connect/authorize.js
  client/jetpack-connect/signup.js
  client/jetpack-connect/test/authorize.js
  client/layout/index.jsx
  client/layout/logged-out.jsx
  client/lib/paths/login/index.js
  client/lib/paths/login/test/index.js
  client/login/wp-login/login-links.jsx
Labels: [Status] Needs Review

#37570 SharingButtonsPreviewButton: add forwardRef flag to connect to make the button reffable
  client/my-sites/marketing/buttons/preview-button.jsx
Labels: [Status] Needs Review, [Type] Bug

#37553 Fix Popover regressions caused by react-redux upgrade
  client/blocks/like-button/index.jsx
  client/components/ellipsis-menu/index.jsx
  client/reader/like-button/index.jsx
  client/reader/stream/index.jsx
  config/development.json
  config/stage.json
  config/wpcalypso.json
Labels: Reader, [Status] Needs Review

#37431 Update atomic hosting sftp card to use new data-layer state
  client/my-sites/hosting/main.js
  client/my-sites/hosting/sftp-card/index.js
  client/state/data-getters/index.js
Labels: [Status] Needs Review
