Repository Automattic/wp-calypso, pull requests merged in 2019-09, with the labels that each got.

#35923 [Checklist]: remove inline help checklist notification
  client/my-sites/checklist/wpcom-checklist/index.jsx
Labels: Checklist, [Status] Needs Review, [Status] Needs e2e Testing, [Type] Bug, [Type] Janitorial

#35861 Signup: removing duplicated trademark notice code
  client/signup/steps/domains/index.jsx
Labels: Domains, Signup, [Status] Needs Review, [Status] Needs e2e Testing, [Type] Defect, [Type] Janitorial

#35858 Remove unused CSS animations
  assets/stylesheets/shared/_animation.scss
  assets/stylesheets/shared/_forms.scss
Labels: CSS Migration, [Status] Needs Review, [Type] Janitorial

#35926 Signup: ensure the site type list is translated
  client/signup/steps/site-type/form.jsx
Labels: Signup, [Status] Needs Review, [Type] Defect

#35880 Full Site Editing: Update Navigation Menu block markup
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/navigation-menu/index.php
Labels: [Goal] Full Site Editing, [Status] Needs Review, [Type] Enhancement

#35930 Site importer: fix for issue where site import preview persists from previous import
  client/my-sites/importer/site-importer/site-importer-input-pane.jsx
  client/state/imports/site-importer/actions.js
Labels: Import, Site Importer

#35309 Add "continue as user" option to login.
  client/blocks/login/continue-as-user.jsx
  client/blocks/login/continue-as-user.scss
  client/blocks/login/index.jsx
  client/blocks/login/style.scss
  client/controller/index.node.js
  client/controller/index.web.js
  client/login/index.web.js
  test/e2e/lib/flows/login-flow.js
Labels: Login, [Status] Needs Review, [Status] Needs e2e Testing, [Type] New feature

#35866 Build the root stylesheet (CSS resets, color schemes) with webpack
  apps/notifications/src/panel/boot/stylesheets/style.scss
  bin/icfy-analyze.js
  client/assets/stylesheets/README.md
  client/assets/stylesheets/_main.scss
  client/assets/stylesheets/_vendor.scss
  client/assets/stylesheets/directly.scss
  client/assets/stylesheets/editor.scss
  client/assets/stylesheets/shared/_animation.scss
  client/assets/stylesheets/shared/_extends-forms.scss
  client/assets/stylesheets/shared/_extends.scss
  client/assets/stylesheets/shared/_forms.scss
  client/assets/stylesheets/shared/_functions.scss
  client/assets/stylesheets/shared/_reset.scss
  client/assets/stylesheets/shared/_typography.scss
  client/assets/stylesheets/shared/_utils.scss
  client/assets/stylesheets/shared/_variables.scss
  client/assets/stylesheets/shared/functions/_functions.scss
  client/assets/stylesheets/shared/functions/_overflow-gradient.scss
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/assets/stylesheets/shared/mixins/_banner.scss
  client/assets/stylesheets/shared/mixins/_breakpoints.scss
  client/assets/stylesheets/shared/mixins/_calc.scss
  client/assets/stylesheets/shared/mixins/_clear-fix.scss
  client/assets/stylesheets/shared/mixins/_clear-text.scss
  client/assets/stylesheets/shared/mixins/_dropdown-menu.scss
  client/assets/stylesheets/shared/mixins/_elevation.scss
  client/assets/stylesheets/shared/mixins/_heading.scss
  client/assets/stylesheets/shared/mixins/_hide-content-accessibly.scss
  client/assets/stylesheets/shared/mixins/_long-content-fade.scss
  client/assets/stylesheets/shared/mixins/_mixins.scss
  client/assets/stylesheets/shared/mixins/_no-select.scss
  client/assets/stylesheets/shared/mixins/_placeholder.scss
  client/assets/stylesheets/shared/mixins/_stats-fade-text.scss
  client/assets/stylesheets/style.scss
  client/boot/app.js
  client/document/404.jsx
  client/document/500.jsx
  client/document/browsehappy.jsx
  client/document/desktop.jsx
  client/document/domains-landing.jsx
  client/document/index.jsx
  client/document/utils/index.jsx
  client/document/utils/stylesheet.js
  client/document/utils/test/stylesheet.js
  client/landing/domains/index.jsx
  client/lib/i18n-utils/switch-locale.js
  package.json
  server/pages/index.js
  webpack.config.js
Labels: CSS Migration, [Status] Needs Review

#35924 Update from unlimited storage to 200 GB in plans list.
  client/lib/plans/features-list.js
  client/lib/plans/plans-list.js
Labels: Plans, [Status] Ready to Merge

#35408 Start replacing 'url' and 'qs' with standard APIs.
  client/blocks/reader-share/index.jsx
  client/boot/polyfills.js
  client/lib/build-url/index.ts
  client/lib/build-url/test/index.js
  client/lib/search-url/index.js
  client/my-sites/themes/theme-showcase.jsx
  npm-shrinkwrap.json
  package.json
  webpack.config.js
Labels: Performance, Reader, [Status] Ready to Merge, [Type] Janitorial

#35793 Update WooCommerce Onboarding Connection Login/Signup colors
  client/jetpack-connect/colors.scss
  client/jetpack-connect/style.scss
  client/login/wp-login/style.scss
  client/signup/style.scss
Labels: [Status] Needs Review

#35857 Remove site style step from flows and update default theme to Maywood
  client/components/signup-site-preview/utils.js
  client/lib/signup/site-styles.js
  client/lib/signup/site-type.js
  client/signup/config/flows-pure.js
  client/signup/site-mockup/index.jsx
  test/e2e/specs/wp-signup-spec.js
Labels: Signup, [Status] Needs Review, [Status] Needs e2e Testing

#35871 Improve `MultiCheckbox`: rewrite to typed, functional, propType-free component
  client/components/forms/multi-checkbox/index.jsx
  client/components/forms/multi-checkbox/index.tsx
  client/components/forms/multi-checkbox/test/index.jsx
Labels: [Status] Needs Review, [Type] Janitorial

#35919 Site Picker: Display Regardless of Site Visibility
  client/my-sites/current-site/index.jsx
Labels: [Status] In Progress

#35666 Threat Alerts: Add tracks events on fix and ignore buttons
  client/my-sites/activity/activity-log/threat-alert.jsx
Labels: Activity Log, Security, [Size] S, [Status] Needs Review

#35908 Jetpack Connection Flow: new `close_window_after_login` param
  client/jetpack-connect/authorize.js
  client/jetpack-connect/schema.js
  client/jetpack-connect/test/__snapshots__/authorize.js.snap
  client/jetpack-connect/test/__snapshots__/utils.js.snap
  client/jetpack-connect/test/authorize.js
  client/jetpack-connect/test/utils.js
  client/jetpack-connect/utils.js
Labels: Jetpack, Signup, [Status] Needs Review, [Type] Enhancement

#35856 FSE: Use get_theme_support instead of theme whitelist
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php
Labels: DO NOT MERGE, [Goal] Full Site Editing, [Status] Needs Review

#35917 FSE: Add Custom CSS card in My Plan section
  client/blocks/product-purchase-features-list/custom-css.jsx
  client/blocks/product-purchase-features-list/index.jsx
Labels: [Goal] Full Site Editing, [Status] Needs Review

#35840 SPT: add template title in large preview
  apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/preview-template-title.js
  apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-preview.js
  apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js
  apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss
Labels: [Goal] Block Previews, [Team] AJAX, [Type] Enhancement

#35962 (2P) SPT: Remove dependency on FSE
  apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss
Labels: [Goal] Block Previews, [Team] AJAX, [Type] Bug

#35779 Docs: update guides about adding new sections and CSS
  docs/coding-guidelines/css.md
  docs/guide/hello-world.md
Labels: DevDocs, Documentation

#35934 Remove legacy CSS hot reloader
  client/boot/README.md
  client/boot/common.js
  client/boot/dev-modules.js
  client/lib/css-hot-reload/index.js
  index.js
  npm-shrinkwrap.json
  package.json
  packages/calypso-build/package.json
  server/bundler/css-hot-reload.js
  server/bundler/hot-reloader.js
Labels: Build, CSS Migration, [Status] Ready to Merge

#35969 Fixup host parameter in server.listen call
  index.js
Labels: [Status] Needs Review

#35947 Jetpack Guided Tours: fix commas
  client/layout/guided-tours/tours/jetpack-backups-rewind-tour/index.js
  client/layout/guided-tours/tours/jetpack-lazy-images-tour/index.js
  client/layout/guided-tours/tours/jetpack-monitoring-tour/index.js
  client/layout/guided-tours/tours/jetpack-plugin-updates-tour/index.tsx
  client/layout/guided-tours/tours/jetpack-search-tour/index.js
  client/layout/guided-tours/tours/jetpack-sign-in-tour/index.js
  client/layout/guided-tours/tours/jetpack-site-accelerator-tour/index.js
  client/layout/guided-tours/tours/jetpack-video-hosting-tour/index.js
Labels: Jetpack, [Status] Needs Review, [Status] Ready to Merge, [Status] String Freeze

#35970 DismissableCard: Keep card hidden until preferences are recieved
  client/blocks/dismissible-card/index.jsx
Labels: [Status] Needs Review

#35864 Customer Home: Remove the customer-home feature flag to put it live
  client/lib/abtest/active-tests.js
  client/my-sites/checklist/controller.jsx
  client/my-sites/customer-home/controller.jsx
  client/my-sites/sidebar/sidebar.jsx
  client/state/selectors/is-site-eligible-for-customer-home.js
  config/stage.json
  config/wpcalypso.json
Labels: Customer Home, [Status] Needs Review

#35972 SPT: close modal once `blank` selected
  apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js
Labels: [Status] Ready to Merge, [Type] Bug

#35974 Calypso-build: Improve Jest setup
  npm-shrinkwrap.json
  packages/babel-plugin-transform-wpcalypso-async/jest.config.js
  packages/calypso-build/CHANGELOG.md
  packages/calypso-build/README.md
  packages/calypso-build/jest-preset.js
  packages/calypso-build/jest/transform/README.md
  packages/calypso-build/jest/transform/asset.js
  packages/calypso-build/jest/transform/babel.js
  packages/calypso-build/package.json
  packages/calypso-ui/jest.config.js
  packages/eslint-config-wpcalypso/jest.config.js
  packages/eslint-plugin-wpcalypso/jest.config.js
  packages/format-currency/jest.config.js
  packages/i18n-calypso/jest.config.js
  packages/load-script/jest.config.js
  packages/photon/jest.config.js
  packages/tree-select/jest.config.js
  packages/webpack-inline-constant-exports-plugin/jest.config.js
  test/client/jest.config.js
  test/server/jest.config.js
Labels: Build, Testing, [Status] Ready to Merge, [Type] Enhancement

#35819 Checkout: Show Stripe initialization error and prevent submission
  client/blocks/credit-card-form/index.jsx
  client/components/credit-card-form-fields/index.jsx
  client/lib/stripe/index.js
  client/my-sites/checkout/checkout/credit-card-payment-box.jsx
  client/my-sites/checkout/checkout/credit-card-selector.jsx
  client/my-sites/checkout/checkout/new-card-form.jsx
Labels: Checkout, [Status] Ready to Merge

#35979 Domains: Send empty fax when we don't need it in checkout
  client/components/domains/contact-details-form-fields/index.jsx
Labels: Checkout, Domains, [Status] Ready to Merge

#35983 Calypso-build: Remove esm syntax
  packages/calypso-build/.eslintrc.js
  packages/calypso-build/CHANGELOG.md
  packages/calypso-build/jest/setup.js
  packages/calypso-build/package.json
Labels: Build, Packages, [Status] Ready to Merge

#35993 Fix container styling issues in Jetpack connect/install step
  client/components/formatted-header/style.scss
  client/jetpack-connect/remote-credentials.js
  client/jetpack-connect/style.scss
Labels: [Status] Needs Jetpack e2e Testing, [Status] Needs Review, [Status] Needs e2e Testing

#35123 Jetpack Checklist: Update Modal Design
  client/my-sites/plans/current-plan/current-plan-thank-you/style.scss
  client/my-sites/plans/current-plan/current-plan-thank-you/thank-you.js
  client/my-sites/plans/current-plan/index.jsx
  client/my-sites/plans/current-plan/style.scss
Labels: Checklist, Jetpack, OSS Citizen, [Status] Needs Design Review, [Status] Needs Review, [Type] Enhancement

#35997 jetpack checklist – thank you modal: remove color overrides and fix image width
  client/my-sites/plans/current-plan/current-plan-thank-you/style.scss
Labels: Checklist, Jetpack, [Status] Ready to Merge

#35988 Fix: Open up G Suite access to Domain-Only accounts
  client/my-sites/controller.js
Labels: G Suite, [Status] Ready to Merge

#34940 Checkout: Test using Google Places API for smoother checkout
  client/blocks/location-search/index.jsx
  client/blocks/location-search/prediction.jsx
  client/blocks/location-search/style.scss
  client/components/domains/contact-details-form-fields/custom-form-fieldsets/region-address-fieldsets.jsx
  client/components/domains/contact-details-form-fields/index.jsx
  client/components/domains/contact-details-form-fields/style.scss
  client/components/domains/contact-details-form-fields/test/__snapshots__/index.js.snap
  client/lib/abtest/active-tests.js
Labels: ABTest, Checkout, Domains, [Status] Ready to Merge

#36000 Email: Fix custom domain image migration
  client/my-sites/email/email-management/index.jsx
Labels: FixTheFlows, [Status] Ready to Merge

#35982 Add Explicit Error On Invalid Google My Business Site Keyring
  client/my-sites/google-my-business/stats/index.js
  client/my-sites/google-my-business/stats/style.scss
Labels: [Project] Google My Business, [Status] Ready to Merge

#35994 FSE: Improve/fse eligibility active check v2
  apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/templates/class-wp-template.php
Labels: [Goal] Full Site Editing, [Status] Needs Review

#35998 Full Site Editing: Avoid double wrapper on fallback Navigation block
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/navigation-menu/index.php
Labels: [Goal] Full Site Editing, [Status] Needs Review, [Type] Bug

#35999 Full Site Editing: Add alignment options to the FSE blocks
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/navigation-menu/edit.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/navigation-menu/index.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/navigation-menu/index.php
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-description/index.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-description/index.php
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-title/index.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-title/index.php
Labels: [Goal] Full Site Editing, [Status] Ready to Merge, [Type] Enhancement

#36004 Update FSE plugin version to 0.7
  apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
  apps/full-site-editing/full-site-editing-plugin/readme.txt
  apps/full-site-editing/package.json
Labels: [Goal] Full Site Editing, [Status] Needs Review

#36005 Full Site Editing: Fix full-width blocks inside the Post Content block
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/post-content/index.js
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/post-content/style.scss
Labels: [Goal] Full Site Editing, [Status] Needs Review, [Type] Bug

#35648 Increment diff api version to pick up new endpoint with FSE compatiblity
  client/state/data-layer/wpcom/posts/revisions/index.js
  client/state/data-layer/wpcom/posts/revisions/test/index.js
Labels: [Goal] Full Site Editing, [Status] Ready to Merge

#35831 Signup: hide preview in domains step
  client/components/domains/domain-search-results/index.jsx
  client/components/domains/register-domain-step/index.jsx
  client/signup/main.jsx
  client/signup/steps/domains/index.jsx
  client/signup/steps/domains/style.scss
  client/state/action-types.js
  client/state/signup/preview/actions.js
  client/state/signup/preview/reducer.js
  client/state/signup/preview/selectors.js
  client/state/signup/preview/test/actions.js
  client/state/signup/preview/test/reducer.js
  client/state/signup/preview/test/selectors.js
  client/state/signup/reducer.js
Labels: Signup, [Status] Needs Design Review, [Status] Needs Review, [Status] Needs e2e Testing, [Type] Janitorial

#36007 Signup: Add exception for connect-in-place flow for Google
  client/blocks/signup-form/social.jsx
Labels: Jetpack, Signup, [Status] Ready to Merge, [Type] Feature progress

#36027 Revert "Signup: Add exception for connect-in-place flow for Google"
  client/blocks/signup-form/social.jsx
Labels: Reverted, Signup, [Status] Needs Review

#35060 Checkout: Update styles for checkout processing screen
  client/my-sites/checkout/checkout-thank-you/style.scss
  client/my-sites/checkout/checkout-thank-you/transfer-pending.jsx
Labels: Checkout, [Status] Ready to Merge

#36036 Signup: Add exception for connect-in-place flow for Google (take 2)
  client/blocks/signup-form/social.jsx
  client/jetpack-connect/schema.js
  client/jetpack-connect/utils.js
Labels: Jetpack, Signup, [Status] Needs Review, [Type] Feature progress

#36022 Support: Update GM Closure notice dates
  client/me/help/help-contact/index.jsx
Labels: [Status] Ready to Merge

#36037 Revert "Signup: Add exception for connect-in-place flow for Google (take 2)"
  client/blocks/signup-form/social.jsx
  client/jetpack-connect/schema.js
  client/jetpack-connect/utils.js
Labels: Reverted, Signup, [Status] Needs Review

#36047 [SIGNUP]: clear the state after launching a site
  client/signup/main.jsx
Labels: [Pri] High, [Status] Needs Review, [Status] Needs e2e Testing, [Type] Bug, [Type] Defect

#35920 G Suite: Add an extra field to collect an `alternateEmail` different from the domain being provisioned
  client/components/domains/contact-details-form-fields/index.jsx
  client/lib/cart-values/cart-items.js
  client/my-sites/checkout/checkout/domain-details-form.jsx
Labels: G Suite, [Status] Ready to Merge

#36051 Update: fixes an issue where a valid alternate email does not pass validation
  client/lib/cart-values/cart-items.js
Labels: G Suite, [Status] Ready to Merge

#36035 Temporarily dial down concierge upsell nudge to zero
  client/lib/abtest/active-tests.js
  client/my-sites/checkout/checkout/index.jsx
Labels: Concierge, Marketing, [Status] Needs Review

#35841 Add condition to closeUrl for block editor to handle checklist referrals
  client/gutenberg/editor/calypsoify-iframe.tsx
  client/state/selectors/get-editor-close-url.js
  client/state/selectors/is-last-non-editor-route-checklist.js
  client/state/selectors/test/get-editor-close-url.js
  client/state/selectors/test/is-last-non-editor-route-checklist.js
Labels: Checklist, [Goal] Full Site Editing, [Status] Needs Review

#36038 Climate strike setting
  client/my-sites/site-settings/form-general.jsx
Labels: Site Settings, [Status] Needs Copy Review, [Status] Needs Review

#36068 Blogger Importer: remove the inline help dialog and replace with link.
  client/lib/importer/importer-config.js
Labels: Import, [Status] Ready to Merge

#36071 Cart: Remove white background from empty cart
  client/my-sites/checkout/cart/style.scss
Labels: [Status] Ready to Merge

#36075 Import: Update WordPress, Medium, and Squarespace help links to use external link instead of modal
  client/lib/importer/importer-config.js
Labels: Import, Squarespace, [Status] Needs Review

#36082 Blogger Importer: Link to the correct support article
  client/lib/importer/importer-config.js
Labels: Import, [Status] Needs Review

#35293 Resolve the capitalizing issue at Manage >> Settings #35292
  client/my-sites/site-settings/composing/publish-confirmation.jsx
  client/my-sites/site-settings/custom-content-types/index.jsx
  client/my-sites/site-settings/form-writing.jsx
  client/my-sites/site-settings/media-settings-writing.jsx
Labels: Site Settings, [Status] Needs Review, [Status] String Freeze, [Type] Enhancement

#36079 Remove /all-about-domains support link
  client/lib/url/support.js
  client/my-sites/domains/components/domain-warnings/index.jsx
Labels: [Status] Needs Review, [Type] Bug

#36078 Enhance the specificity of the <Notice> content related selectors
  client/components/notice/style.scss
Labels: [Status] Needs Review

#36070 Wrap copy with preventWidows in several places
  client/my-sites/checkout/checkout-thank-you/header.jsx
Labels: Checkout, [Size] S, [Status] Needs Review, [Type] Enhancement

#36076 Fixed the site address changer link so that it opens in new window instead of same page.
  client/blocks/site-address-changer/index.jsx
Labels: [Status] Ready to Merge, [Type] Enhancement

#36025 Fix first click does not work when linking existing wpcom account to social
  client/blocks/login/login-form.jsx
Labels: Login

#36066 Don't check for atomic when transferring
  client/my-sites/domains/domain-management/controller.jsx
  client/my-sites/domains/domain-management/transfer/index.jsx
  client/my-sites/domains/domain-management/transfer/transfer-to-other-user/index.jsx
Labels: Atomic, Domains, [Status] Needs Review

#36080 Domains: Adjust domain mapping copy notes
  client/components/domains/map-domain-step/index.jsx
Labels: Domains, [Status] Needs Review

#36088 Domains: Fix Change Site Address modal content alignment
  client/blocks/site-address-changer/style.scss
Labels: [Status] Needs Review

#36084 Update Primary domain flag style
  client/my-sites/domains/domain-management/list/style.scss
Labels: [Status] Needs Review, [Type] Enhancement

#36077 Domains: Use color variable for included/sale price in search
  client/components/domains/domain-product-price/style.scss
Labels: Domains, [Status] Needs Review

#36074 Editor: Fix low contrast of featured image block
  client/components/drop-zone/style.scss
Labels: Color Schemes, Editor, [Status] Needs Review

#36102 Fix: Remove Plugin Upgrade nudge for VIP sites
  client/my-sites/plugins/plugins-browser/index.jsx
Labels: [Status] Needs Review

#36091 Improve whitespace between row header and data when editing domain
  client/my-sites/domains/domain-management/edit/card/property/style.scss
Labels: [Status] Needs Review, [Type] Enhancement

#36086 Domains: Fix domain not shown on Transfer Restriction page
  client/components/domains/transfer-domain-step/index.jsx
  client/components/domains/transfer-domain-step/transfer-restriction-message.jsx
Labels: Domains, [Status] Needs Review

#36090 My plan: Make CTAs full width only below 480px
  client/components/happiness-support/style.scss
  client/components/purchase-detail/style.scss
Labels: [Status] Needs Review

#36083 Plans: Remove pinned items space from navbar on pages without cart icon
  client/my-sites/plans/navigation.jsx
Labels: [Status] Needs Review

#35984 Checkout: remove ebanx to paygate fallback
  client/lib/store-transactions/index.js
Labels: Checkout

#36073 Sidebar: remove unneeded package.json file
  client/my-sites/sidebar/index.jsx
  client/my-sites/sidebar/package.json
  client/my-sites/sidebar/test/sidebar.js
Labels: [Status] Needs Review, [Type] Janitorial

#36085 Fix Overflow Fade In Stats Page "Post Published" Overflow
  client/components/chart/style.scss
Labels: Stats, [Status] Ready to Merge

#36115 Fix site cloning for Pressable sites
  client/my-sites/site-settings/site-tools/index.jsx
Labels: Rewind, [Status] Needs Review

#36114 Fix: poor contrast on subheadings in /plans page
  client/my-sites/plan-features/style.scss
Labels: Plans, [Status] Needs Review

#35145 Notifications: Improve Colour Contrast
  client/me/notification-settings/blogs-settings/style.scss
  client/me/notification-settings/push-notification-settings/style.scss
  client/me/notification-settings/settings-form/style.scss
Labels: Accessibility, OSS Citizen, [Status] Needs Review

#36120 Site Indicator: use underline decoration instead of fake border.
  client/my-sites/site-indicator/style.scss
Labels: [Status] Needs Review

#36119 Fix: Use higher contrast text color for feature card headings on my plan
  client/components/happiness-support/style.scss
Labels: Plans, [Status] Needs Review

#36124 Reader: Use unstable editor is ready if available for more reliable press this block insertion
  apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js
Labels: Reader, [Status] Needs Review

#36123 Update Jetpack Connect Colors
  client/jetpack-connect/colors.scss
  client/jetpack-connect/style.scss
  packages/calypso-color-schemes/CHANGELOG.md
  packages/calypso-color-schemes/package.json
  packages/calypso-color-schemes/src/shared/color-schemes/_default.scss
Labels: Jetpack, [Status] Ready to Merge

#36131 Post search: open the search bar on page load if there's a "s=..." in the URL
  client/my-sites/post-type-filter/index.jsx
Labels: [Status] Needs Review

#36106 Update upgrade thank you page CTA button copy
  client/my-sites/checkout/checkout-thank-you/header.jsx
Labels: Plans

#35922 Shortcode: Type Gallery shortcode
  client/components/gallery-shortcode/index.tsx
Labels: Editor, [Status] Ready to Merge, [Type] Janitorial

#35811 Card: Move to calypso-ui
  client/components/card/compact.js
  client/components/card/index.js
  client/devdocs/design/component-examples.js
  client/devdocs/design/index.jsx
  packages/calypso-build/CHANGELOG.md
  packages/calypso-build/jest-preset.js
  packages/calypso-build/package.json
  packages/calypso-ui/package.json
  packages/calypso-ui/src/card/README.md
  packages/calypso-ui/src/card/compact.jsx
  packages/calypso-ui/src/card/docs/example.jsx
  packages/calypso-ui/src/card/index.jsx
  packages/calypso-ui/src/card/style.scss
  packages/calypso-ui/src/card/test/__snapshots__/index.js.snap
  packages/calypso-ui/src/card/test/index.js
  packages/calypso-ui/src/index.js
Labels: Components, [Status] Needs Review

#36135 Invite Form: Don't attempt to submit when form hasn't been updated.
  client/blocks/signup-form/index.jsx
  client/my-sites/invites/invite-accept-logged-out/index.jsx
Labels: [Status] Needs Review

#36081 Try to sort post status absolutely
  client/my-sites/post-type-filter/index.jsx
Labels: Posts, [Size] S, [Status] Needs Review

#36136 Plugins/Themes: update messaging from "upload" to "install"
  client/blocks/upload-drop-zone/index.jsx
  client/lib/plans/features-list.js
  client/lib/plugins/notices.jsx
  client/my-sites/plans-features-main/wpcom-faq.jsx
  client/my-sites/plugins/plugin-upload/index.jsx
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/themes/theme-showcase.jsx
  client/my-sites/themes/theme-upload/index.jsx
Labels: Plugins, [Status] Needs Review

#36149 <SidebarMenu> should use <ul> instead of <li>
  client/layout/sidebar/menu.jsx
Labels: [Status] Ready to Merge

#36126 Fix: Several low contrast text areas on Stats
  client/my-sites/stats/stats-error/style.scss
  client/my-sites/stats/stats-list/style.scss
  client/my-sites/stats/stats-tabs/style.scss
Labels: Accessibility, Color Schemes, Stats, [Status] Needs Review

#36103 Refactor Stats Bar Chart X Axis Component & Fix Weird Initial Render
  client/components/chart/x-axis.jsx
Labels: Stats, [Status] Needs Review

#36139 Build: Fix server file-loader imports
  client/blocks/login/index.jsx
  packages/calypso-build/CHANGELOG.md
  packages/calypso-build/webpack/file-loader.js
  webpack.config.node.js
Labels: Build, Packages, [Status] Ready to Merge

#36127 Fix/remove upgrader nudge for vip sites in calypso
  client/my-sites/marketing/main.jsx
  client/my-sites/plugins/plugin-meta/index.jsx
  client/my-sites/post-type-list/index.jsx
  client/my-sites/site-settings/form-general.jsx
  client/my-sites/themes/single-site-wpcom.jsx
Labels: [Status] Needs Review

#36125 Update banner icons on performance settings page
  client/components/banner/style.scss
Labels: FixTheFlows, [Status] Needs Review, [Type] Enhancement

#36132 Issue/33071 update banner fix
  client/components/banner/index.jsx
  client/my-sites/themes/single-site-wpcom.jsx
Labels: [Status] Needs Review

#36092 Add P2 autocomplete to block editor
  apps/o2-blocks/src/editor.js
  apps/o2-blocks/src/p2-autocomplete/editor.js
  apps/o2-blocks/src/p2-autocomplete/editor.scss
Labels: [Status] Needs Review

#36155 Login form: remove autocorrection
  client/blocks/login/login-form.jsx
Labels: Login, [Status] Needs Review

#36152 Reader: Clearer link for Discover and site titles
  client/blocks/reader-feed-header/style.scss
Labels: FixTheFlows, Reader, [Status] Ready to Merge

#36153 Update Posts, Pages and Post types to have the full width Main Column
  client/my-sites/pages/main.jsx
  client/my-sites/posts/main.jsx
  client/my-sites/types/main.jsx
Labels: [Status] Ready to Merge

#36151 Make the post search placeholder be "Search [POST_TYPE]..."
  client/my-sites/post-type-filter/index.jsx
Labels: [Status] Needs Review

#35768 Ribbon: Move to calypso-ui
  client/components/ribbon/index.js
  client/devdocs/design/component-examples.js
  client/devdocs/design/index.jsx
  packages/calypso-ui/src/index.js
  packages/calypso-ui/src/ribbon/README.md
  packages/calypso-ui/src/ribbon/docs/example.jsx
  packages/calypso-ui/src/ribbon/index.jsx
  packages/calypso-ui/src/ribbon/style.scss
Labels: Components, [Status] Blocked / Hold

#36109 Posts, Testimonials and Portfolio Projects: Expand search scope from one tab to all tabs
  client/blocks/post-item/README.md
  client/blocks/post-item/index.jsx
  client/my-sites/post-type-filter/index.jsx
  client/my-sites/post-type-list/README.md
  client/my-sites/post-type-list/index.jsx
  client/my-sites/posts/main.jsx
  client/my-sites/types/controller.jsx
  client/my-sites/types/main.jsx
  client/state/posts/constants.js
  client/state/posts/counts/selectors.js
Labels: [Status] Needs Review

#36162 Prep calypso-ui release
  packages/calypso-ui/CHANGELOG.md
  packages/calypso-ui/package.json
Labels: Packages, [Status] Ready to Merge, [Type] Task

#36164 Tests: Fix Jest file-loader imports
  test/server/jest.config.js
Labels: Framework, Testing, [Status] Needs Review

#36171 Calypso color schemes: Fix published SASS
  packages/calypso-color-schemes/.npmignore
  packages/calypso-color-schemes/package.json
Labels: Color Schemes, Packages, [Status] Ready to Merge, [Type] Bug

#35511 My Plan: Improve Plan Icon Display
  client/my-sites/plans/current-plan/style.scss
Labels: Design, OSS Citizen, Plans, [Status] Needs Author Reply, [Status] Needs Design Review, [Type] Enhancement

#36165 Update Color Palette to the Most Recent Version
  client/components/section-nav/item.scss
  client/components/theme/style.scss
  client/me/help/help-results/style.scss
  client/me/help/style.scss
  client/my-sites/themes/current-theme/style.scss
  npm-shrinkwrap.json
  package.json
  packages/calypso-color-schemes/CHANGELOG.md
  packages/calypso-color-schemes/src/shared/color-schemes/_default.scss
  static/images/color-schemes/color-scheme-thumbnail-classic-blue.svg
  static/images/color-schemes/color-scheme-thumbnail-classic-bright.svg
  static/images/color-schemes/color-scheme-thumbnail-contrast.svg
  static/images/color-schemes/color-scheme-thumbnail-midnight.svg
  static/images/color-schemes/color-scheme-thumbnail-nightfall.svg
  static/images/color-schemes/color-scheme-thumbnail-ocean.svg
  static/images/color-schemes/color-scheme-thumbnail-powder-snow.svg
  static/images/color-schemes/color-scheme-thumbnail-sakura.svg
  static/images/color-schemes/color-scheme-thumbnail-sunset.svg
Labels: [Status] Ready to Merge

#36157 Gutenberg: Decrease width of snackbar notices in mobile screens
  apps/wpcom-block-editor/src/common/style.scss
Labels: [Goal] Gutenberg, [Status] Needs Review

#35757 Signup: Add "site created" notice checkout after signup
  client/my-sites/checkout/checkout/checkout-container.jsx
  client/my-sites/checkout/checkout/signup-site-created-notice.jsx
  client/my-sites/checkout/checkout/style.scss
  client/my-sites/checkout/controller.jsx
  client/signup/config/flows.js
  client/signup/processing-screen/index.jsx
Labels: Checkout, Signup, [Status] Needs e2e Testing, [Status] String Freeze

#36175 Build/colors: Update color schemes and SASS pipeline
  client/assets/stylesheets/shared/_utils.scss
Labels: Design, [Status] Needs Review, [Type] Bug

#35875 Enable Sign in with Apple in prod
  config/desktop.json
  config/horizon.json
  config/production.json
Labels: Login, Signup

#36161 Update: is vip check fixes for #36127
  client/blocks/eligibility-warnings/index.jsx
  client/blocks/upgrade-nudge/index.jsx
  client/my-sites/post-type-list/index.jsx
  client/my-sites/theme/main.jsx
Labels: [Status] Needs Review

#36040 Full Site Editing: Only reposition full width blocks in Post Content on large screens
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/post-content/style.scss
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/style.scss
Labels: [Goal] Full Site Editing, [Status] Needs Review, [Type] Bug

#36169 Calypso build: Transpile TypeScript
  packages/calypso-build/CHANGELOG.md
  packages/calypso-build/bin/transpile.js
Labels: Build, Packages, [Status] Ready to Merge

#35996 Customer Home: Remove the feature flag from the development config file
  config/development.json
Labels: Customer Home, [Type] Janitorial

#36003 Private by Default: Pull out AB Test & enable for 100% of relevant flows
  client/lib/abtest/active-tests.js
  client/state/selectors/should-new-site-be-private-by-default.ts
  client/state/selectors/test/should-new-site-be-private-by-default.js
Labels: Private by Default, [Status] Needs Review

#36209 Calypso build: Require resolve babel presets and plugins
  packages/calypso-build/CHANGELOG.md
  packages/calypso-build/babel/default.js
  packages/calypso-build/babel/wordpress-element.js
  packages/calypso-build/package.json
Labels: Build, Packages, [Status] Needs Review

#33992 Show store link in sidenav by default if user has a business plan
  client/extensions/woocommerce/app/dashboard/required-plugins-install-view.js
  client/extensions/woocommerce/app/dashboard/setup/style.scss
  client/my-sites/sidebar/index.jsx
  client/my-sites/sidebar/test/sidebar.js
Labels: Store, [Status] Needs Review

#36179 G Suite: Update code owners
  .github/CODEOWNERS
Labels: G Suite, [Status] Ready to Merge

#36227 Temporarily skip Sign up test
  test/e2e/specs/wp-signup-spec.js
Labels: [Status] In Progress, [Status] Needs e2e Testing

#35938 Customer Home: Add the stats banners to the Customer Home page
  client/my-sites/customer-home/main.jsx
  client/my-sites/stats/site.jsx
Labels: Customer Home, [Status] Needs Review, [Status] Needs e2e Testing

#36087 changed message text to make sure it uses the same word as used in the error message.
  client/blocks/site-address-changer/index.jsx
Labels: [Status] Ready to Merge, [Type] Enhancement

#36242 Fix emitting calypso_login_social_button_click when user clicks on the Apple login button
  client/components/social-buttons/apple.js
Labels: Login

#36243 Editor: Improve Featured Image Dropzone Colours
  client/components/drop-zone/style.scss
Labels: Editor, [Status] Needs Review

#36030 Customer Home: Change G Suite card to refer to email
  client/my-sites/customer-home/main.jsx
  static/images/customer-home/custom-domain.svg
Labels: Customer Home, [Status] Needs Review

#35531 Plan Storage Bar: Hide Nudge for Non-Admins
  client/blocks/plan-storage/bar.jsx
  client/blocks/plan-storage/index.jsx
  client/blocks/plan-storage/test/plan-storage.jsx
Labels: FixTheFlows, Media, OSS Citizen, Plans

#36219 Allow icloud.com iframes in Reader
  client/blocks/reader-full-post/_content.scss
  client/lib/post-normalizer/utils.js
Labels: Reader, [Status] Needs Review

#36249 Revert "Show store link in sidenav by default if user has a business plan"
  client/extensions/woocommerce/app/dashboard/required-plugins-install-view.js
  client/extensions/woocommerce/app/dashboard/setup/style.scss
  client/my-sites/sidebar/index.jsx
  client/my-sites/sidebar/test/sidebar.js
Labels: Store

#36250 Fix shadows produced by `elevation` mixin
  client/assets/stylesheets/shared/mixins/_elevation.scss
Labels: Frontend, [Status] Needs Review, [Type] Bug

#36220 Prevent long domain names from overflowing the DomainSuggestion component
  client/components/domains/domain-product-price/style.scss
  client/components/domains/domain-skip-suggestion/style.scss
  client/components/domains/domain-suggestion/style.scss
Labels: Signup, [Status] Needs Review, [Status] Needs e2e Testing

#36257 Remove team Luna as Jetpack connect code owner
  .github/CODEOWNERS
Labels: [Type] Janitorial

#36223 Remove climate strike setting toggle from settings
  client/my-sites/site-settings/form-general.jsx
Labels: Site Settings, [Status] Ready to Merge

#36245 e2e: Increase wait time for calypso.live
  test/e2e/scripts/wait-for-running-branch.sh
Labels: Testing, [Status] Needs Review, [Type] Task

#36228 Full Site Editing: Replace temporary template block injection from `core/template` to `core/group`
  apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js
Labels: [Goal] Full Site Editing, [Pri] BLOCKER, [Status] Needs Review

#36258 Update wp-prettier 1.18.2 distribution package
  npm-shrinkwrap.json
Labels: Build, [Status] Needs Review

#36260 Fix the Remaining RGBA Color Properties
  client/login/wp-login/style.scss
  client/my-sites/stats/stats-list/style.scss
  packages/calypso-color-schemes/CHANGELOG.md
  packages/calypso-color-schemes/package.json
  packages/calypso-color-schemes/src/shared/color-schemes/_default.scss
Labels: Color Schemes, Jetpack, [Type] Defect

#36111 Theme Sheet: Use Masterbar Colour
  client/layout/masterbar/style.scss
  client/my-sites/theme/style.scss
Labels: OSS Citizen, Themes

#36259 Prettier: install the wp-prettier fork as NPM alias rather than tarball download
  npm-shrinkwrap.json
  package.json
Labels: Build

#36188 Hide apple connected account email address in social login settings page on mobile
  client/me/social-login/style.scss
Labels: Login

#36253 User bootstrap cookie-based support session
  server/boot/index.js
  server/pages/index.js
  server/user-bootstrap/index.js
Labels: Support

#36129 Remove "Blog Post" Title from Callout
  client/my-sites/pages/blog-posts-page/index.jsx
  client/my-sites/pages/blog-posts-page/style.scss
  client/my-sites/pages/page-card-info/index.jsx
  client/my-sites/pages/page-card-info/style.scss
Labels: Pages, [Status] Ready to Merge

#35724 Signup: Show "Related" topics when searching in site topic step
  client/components/site-verticals-suggestion-search/index.jsx
  client/components/site-verticals-suggestion-search/test/__snapshots__/index.js.snap
  client/components/site-verticals-suggestion-search/test/index.js
  client/components/suggestion-search/README.md
  client/components/suggestion-search/index.jsx
  client/components/suggestions/README.md
  client/components/suggestions/index.jsx
  client/components/suggestions/item.jsx
  client/components/suggestions/style.scss
  client/components/suggestions/test/__snapshots__/index.js.snap
  client/components/suggestions/test/index.js
  client/signup/style.scss
  client/state/data-layer/wpcom/signup/verticals/index.js
  client/state/data-layer/wpcom/signup/verticals/test/index.js
Labels: Signup, Verticals, [Status] Needs Review, [Status] Needs e2e Testing

#36282 Revert "Fix/36174 search cursor placement"
  client/components/search/style.scss
Labels: [Type] Defect
