Repository Automattic/wp-calypso, pull requests merged in 2020-01, with the labels that each got.

#38579 Settings: AsyncLoad SEO Settings
  client/my-sites/site-settings/seo-settings/main.jsx
Labels: Performance, Site Settings, [Status] Ready to Merge

#38619 Marketing: A/B test reader sidebar upsell nudge
  client/lib/abtest/active-tests.js
  client/reader/sidebar/reader-sidebar-nudges/index.jsx
Labels: ABTest, Marketing, [Status] Needs Review

#38613 Bump FSE to 0.18.2
  apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
  apps/full-site-editing/full-site-editing-plugin/readme.txt
  apps/full-site-editing/package-lock.json
  apps/full-site-editing/package.json
Labels: [Goal] Full Site Editing, [Status] Needs Review

#38576 [package.json] Enable max_old_space_size Override for Desktop
  package.json
Labels: Desktop App, [Pri] BLOCKER, [Status] Needs Review, [Type] Bug

#38632 Plan bump test: Launch the variant as control
  client/lib/abtest/active-tests.js
  client/my-sites/checkout/checkout/index.jsx
Labels: Marketing, Post Checkout, [Status] Needs Review, [Status] Needs e2e Testing

#38644 Eligibility Warnings: Fix a couple of conditional strings in the "hold list"
  client/blocks/eligibility-warnings/hold-list.tsx
Labels: Atomic, Plugins, [Status] Needs Review

#38365 Clear user when an account is successfully closed (marked for deletion)
  client/state/account/actions.js
  client/state/account/test/actions.js
  client/state/data-layer/wpcom/me/account/close/test/index.js
Labels: Joint, Signup, [Status] Needs Review, [Type] Bug

#38655 Test Calypso deployment
  client/signup/README.md
Labels: [Status] Needs Review

#38560 Remove node's url from lib/i18n-utils.
  client/lib/i18n-utils/switch-locale.js
  client/lib/i18n-utils/utils.js
  client/lib/url/index.ts
  client/lib/url/url-parts.ts
Labels: [Status] Needs Review, [Type] Janitorial

#38614 Checklist: make sure icons are in front of vertical line
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/components/checklist/style.scss
Labels: Checklist, Customer Home, [Status] Ready to Merge

#38641 e2e: Skip checking for certain free domains. This will
  test/e2e/lib/flows/sign-up-step.js
  test/e2e/specs/wp-signup-spec.js
Labels: [Status] Needs Review, [Status] Needs e2e Testing

#38621 Site migration: error view
  client/my-sites/migrate/migrate-button.jsx
  client/my-sites/migrate/section-migrate.jsx
  client/my-sites/migrate/section-migrate.scss
Labels: WP Migration, [Status] Needs Review

#38659 Site migration: add confirm before starting migration
  client/my-sites/migrate/migrate-button.jsx
  client/my-sites/migrate/section-migrate.jsx
Labels: WP Migration, [Status] Needs Review

#38583 Gutenboarding: Improve a11y and lints
  client/landing/gutenboarding/onboarding-block/design-selector/design-card.tsx
  client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
  client/landing/gutenboarding/onboarding-block/design-selector/page-layout-selector.tsx
  client/landing/gutenboarding/onboarding-block/design-selector/style.scss
  package-lock.json
  package.json
Labels: Accessibility, [Status] Needs Review

#37505 Account Closure: List Sites to be Deleted
  client/me/account-close/main.jsx
  client/me/account-close/style.scss
  client/state/selectors/get-account-closure-sites.js
  client/state/selectors/test/get-account-closure-sites.js
Labels: Privacy/GDPR, [Status] Needs Review

#38670 Move single purpose products below plans grid for now
  client/my-sites/plans-features-main/index.jsx
Labels: Plans, [Status] Ready to Merge

#38623 DevDocs: Update outdated links in "Our Approach to Data" doc
  docs/our-approach-to-data.md
Labels: DevDocs, Documentation, [Status] Ready to Merge, [Type] Janitorial

#38593 Gutenboarding: Allow user-specified vertical
  client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
  client/landing/gutenboarding/onboarding-block/vertical-background.tsx
  client/landing/gutenboarding/onboarding-block/vertical-select/index.tsx
  client/landing/gutenboarding/stores/onboard/types.ts
Labels: [Goal] Gutenberg, [Goal] Onboarding, [Status] Needs Review

#38606 Build: Don't use @wordpress/element transpilation in FSE
  babel.config.js
Labels: Build, [Goal] Full Site Editing, [Goal] Gutenberg, [Goal] Onboarding, [Status] Needs Review

#37705 Classic Editor: migrate GalleryPreviewShortcode to ES6 class component
  client/post-editor/media-modal/gallery/preview-shortcode.jsx
Labels: Editor, Media, [Status] Needs Review, [Type] Janitorial

#38295 BPB: Add `path` mode in bin sync script
  apps/full-site-editing/bin/sync-blog-posts-block.sh
  apps/full-site-editing/full-site-editing-plugin/blog-posts-block/README.md
Labels: [Status] Needs Review, [Type] Enhancement

#38586 Sites: Remove Jetpack minimum version functionality
  client/jetpack-connect/test/__snapshots__/plans.js.snap
  client/jetpack-connect/test/lib/plans.js
  client/lib/ads/test/lib/mock-site.js
  client/lib/email-followers/test/lib/mock-site.js
  client/lib/followers/test/lib/mock-site.js
  client/lib/people/test/fixtures/site.js
  client/lib/plugins/test/fixtures/multi-site.js
  client/lib/plugins/test/fixtures/site.js
  client/lib/site/test/utils.js
  client/lib/site/utils.js
  client/lib/users/test/fixtures/site.js
  client/lib/viewers/test/fixtures/site.js
  client/my-sites/checkout/checkout-thank-you/jetpack-plan-details.jsx
  client/my-sites/plans/current-plan/current-plan-thank-you/paid-plan-thank-you.js
  client/my-sites/plugins/jetpack-plugins-setup/index.jsx
  client/my-sites/plugins/main.jsx
  client/my-sites/plugins/not-supported-jetpack-version.jsx
  client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx
  client/my-sites/plugins/plugin-install-button/index.jsx
  client/my-sites/plugins/plugin-remove-button/index.jsx
  client/my-sites/plugins/plugin.jsx
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/site-indicator/index.jsx
  client/my-sites/site-indicator/style.scss
  client/my-sites/site-settings/form-general.jsx
  client/my-sites/site-settings/settings-security/main.jsx
  client/state/sites/selectors/can-jetpack-site-update-files.js
  client/state/sites/selectors/get-jetpack-computed-attributes.js
  client/state/sites/selectors/index.js
  client/state/sites/selectors/site-has-minimum-jetpack-version.js
  client/state/sites/test/selectors.js
  config/_shared.json
  config/client.json
  config/desktop-development.json
  config/desktop.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Jetpack, Sites, State, [Status] Ready to Merge, [Type] Janitorial

#38683 Retry: Remove node's url from lib/i18n-utils
  client/lib/i18n-utils/switch-locale.js
  client/lib/i18n-utils/utils.js
  client/lib/url/index.ts
  client/lib/url/test/url-parts.js
  client/lib/url/url-parts.ts
Labels: [Status] Needs Review, [Type] Janitorial

#38685 Activity: fix actor column width
  client/my-sites/activity/activity-log-item/style.scss
Labels: Activity Log, Jetpack, [Status] Ready to Merge

#38522 Customer Home: Update language to be clearer after purchase.
  client/my-sites/customer-home/main.jsx
Labels: Customer Home, [Source] User testing

#38669 e2e- Upsell page changed. Updating selector
  test/e2e/lib/pages/signup/upsell-page.js
Labels: [Status] Needs Review, [Status] Needs e2e Testing

#38409 Add composer.json and use local dependencies in pre-commit hook
  .gitignore
  bin/pre-commit-hook.js
  composer.json
  composer.lock
Labels: [Status] Needs Review

#38684 Site migration: lock the UI immediately the migration starts
  client/my-sites/migrate/section-migrate.jsx
  client/state/selectors/is-site-migration-in-progress.js
Labels: WP Migration

#38695 eCommerce Upgrade: Set site public on dialog confirmation
  client/my-sites/plan-features/index.jsx
Labels: Launch, Plans, Private by Default, [Status] Needs Design Review, [Status] Needs Review, eCommerce Plan

#38673 tweak vertical centering of text inside badges
  client/components/badge/style.scss
Labels: [Status] Needs Review

#38688 Data Stores: Disable automatic type inclusion
  packages/components/tsconfig.json
  packages/composite-checkout-wpcom/src/mock/cart-endpoint.ts
  packages/composite-checkout-wpcom/tsconfig.json
  packages/data-stores/tsconfig.json
Labels: Build, Packages

#38011 Update pre-commit phpcs presence logic
  .gitignore
  bin/pre-commit-hook.js
  composer.json
  composer.lock
Labels: [Status] Needs Review

#38572 Customer Home: Migrate Images to Webpack
  client/assets/images/customer-home/apple-store.png
  client/assets/images/customer-home/comment.svg
  client/assets/images/customer-home/custom-domain.svg
  client/assets/images/customer-home/customize.svg
  client/assets/images/customer-home/google-play.png
  client/assets/images/customer-home/gsuite.svg
  client/assets/images/customer-home/happiness.png
  client/assets/images/customer-home/images.svg
  client/assets/images/customer-home/logo.svg
  client/assets/images/customer-home/menus.svg
  client/assets/images/customer-home/page.svg
  client/assets/images/customer-home/post.svg
  client/assets/images/customer-home/theme.svg
  client/my-sites/customer-home/main.jsx
Labels: Customer Home, [Status] In Progress

#38711 i18n-utils: Add translationExists function
  client/lib/i18n-utils/node.js
  client/lib/i18n-utils/test/utils.js
  client/lib/i18n-utils/utils.js
Labels: [Tests] Includes Tests, [Type] Enhancement, i18n

#38573 Add test confirming the language picker supports non latin charsets
  client/components/language-picker/test/index.jsx
Labels: Testing, [Status] Ready to Merge, i18n

#38633 Hosting: Check new manage_hosting capability for access
  client/blocks/inline-help/contextual-help.js
  client/my-sites/hosting/controller.js
  client/my-sites/hosting/main.js
  client/my-sites/sites/index.jsx
  client/state/selectors/can-site-view-atomic-hosting.js
  config/desktop.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#37643 Use native URL in several media modules.
  client/components/gravatar/index.jsx
  client/lib/media/test/actions.js
  client/lib/media/utils.js
  client/lib/resize-image-url/index.js
  client/lib/safe-image-url/index.js
Labels: [Status] Needs Review, [Type] Janitorial

#38737 Popular badge test: Remove test dependency on the nonEnglishDomainStepCopyUpdates test
  client/lib/abtest/active-tests.js
  client/lib/plans/index.js
Labels: Marketing, [Status] Needs Review

#38745 i18n-utils: Address hasTranslation warning
  client/lib/i18n-utils/utils.js
Labels: [Type] Janitorial

#38730 Eventbrite: Properly remove the Keyring connection on disconnect.
  client/my-sites/marketing/connections/services/eventbrite.js
Labels: Sharing, [Status] Needs Review

#38734 Eventbrite: Don't allow any more new connections.
  client/my-sites/marketing/connections/service-action.jsx
Labels: Sharing, [Status] Needs Review

#38728 Remove Jetpack plans extended info links
  client/jetpack-connect/plans-extended-info.jsx
  client/jetpack-connect/plans-landing.jsx
  client/jetpack-connect/plans.jsx
  client/jetpack-connect/test/__snapshots__/plans.js.snap
Labels: Jetpack, Plans, [Status] Needs Design Review, [Status] Needs Review

#38722 Sidebar: Remove payment processing nudge
  client/my-sites/current-site/notice.jsx
  client/my-sites/current-site/test/notice.jsx
  client/my-sites/current-site/test/pending-payment-notice.jsx
Labels: Sidebar

#38677 Reader: update Gutenberg gallery styles to include blocks-gallery-grid
  client/blocks/reader-full-post/_content.scss
  client/blocks/reader-full-post/gutenberg-gallery.scss
Labels: Reader, [Status] Needs Review

#38732 Add storybook instructions for @automattic/components
  packages/components/README.md
Labels: Components, Documentation

#38752 WP Migration: Redirect WordPress importer to the migration screen if migration is enabled
  client/lib/importer/importer-config.js
  client/my-sites/importer/file-importer.jsx
Labels: [Status] Needs Review, [Type] Enhancement

#38680 A/B test the plan bump offer against GSuite offer
  client/lib/abtest/active-tests.js
  client/my-sites/checkout/checkout/index.jsx
Labels: GSuite, Marketing, [Status] Needs Review, [Status] Needs e2e Testing

#38746 non-EN domain test: Launch the variant as winner
  client/lib/abtest/active-tests.js
  client/signup/steps/domains/index.jsx
Labels: Domains, Signup, [Status] Needs Review

#38749 Gutenboarding: Add Template Title in Page Selector
  client/landing/gutenboarding/onboarding-block/design-selector/page-layout-selector.tsx
  client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Labels: [Goal] Gutenberg, [Goal] Onboarding, [Status] Ready to Merge

#38374 Framework: Remove fontfaceobserver dependency
  package-lock.json
  package.json
Labels: Framework, [Status] Needs Review, [Type] Janitorial

#38747 Stop the `domainSuggestionsWithHints` abtest
  client/lib/abtest/active-tests.js
  client/lib/domains/suggestions/index.js
  client/signup/steps/domains/index.jsx
Labels: Domains, [Status] Ready to Merge

#38764 eslint-plugin-wpcalypso: make jsx-classname-namespace work well with Storybook
  packages/eslint-plugin-wpcalypso/CHANGELOG.md
  packages/eslint-plugin-wpcalypso/lib/rules/jsx-classname-namespace.js
Labels: Framework, [Status] Needs Review

#38773 Data-stores: Add Luna as data-stores codeowners
  .github/CODEOWNERS
Labels: Packages, [Status] Needs Review, [Type] Task

#38775 Remove HotJar during the Jetpack connect flow
  client/jetpack-connect/authorize.js
  client/jetpack-connect/install-instructions.jsx
  client/jetpack-connect/jetpack-new-site/index.jsx
  client/jetpack-connect/main.jsx
  client/jetpack-connect/plans-landing.jsx
  client/jetpack-connect/plans.jsx
  client/jetpack-connect/remote-credentials.js
  client/jetpack-connect/signup.js
  client/jetpack-connect/site-topic.js
  client/jetpack-connect/site-type.js
  client/jetpack-connect/sso.jsx
  client/jetpack-connect/user-type/index.js
Labels: Analytics, Jetpack, [Status] Ready to Merge

#38768 Gutenboarding: Add description to design-selector
  client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
  client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Labels: Design, [Status] Ready to Merge, [Type] Feature progress

#38771 Gutenboarding: Remove dark theme
  client/landing/gutenboarding/onboarding-block/design-selector/style.scss
  client/landing/gutenboarding/onboarding-block/edit.tsx
  client/landing/gutenboarding/onboarding-block/style.scss
  client/landing/gutenboarding/onboarding-block/vertical-background.tsx
Labels: Design, [Status] Needs Review, [Status] Ready to Merge, [Type] Task

#38772 Gutenboarding: Improve skip button styles
  client/landing/gutenboarding/onboarding-block/style.scss
Labels: Accessibility, Design, [Status] Needs Review, [Status] Ready to Merge, [Type] Feature progress

#38757 Gutenboarding: move design picker state in onboarding store
  client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
  client/landing/gutenboarding/onboarding-block/design-selector/page-layout-selector.tsx
  client/landing/gutenboarding/stores/onboard/actions.ts
  client/landing/gutenboarding/stores/onboard/index.ts
  client/landing/gutenboarding/stores/onboard/reducer.ts
  client/landing/gutenboarding/stores/onboard/types.ts
Labels: [Goal] Onboarding, [Status] Needs Review, [Status] Ready to Merge

#38724 WP.com block editor: Deprecate CoBlocks buttons block
  apps/wpcom-block-editor/README.md
  apps/wpcom-block-editor/src/wpcom/editor.js
  apps/wpcom-block-editor/src/wpcom/features/deprecate-coblocks-buttons.js
  test/e2e/specs/wp-calypso-gutenberg-coblocks-spec.js
Labels: [Status] Needs Review

#38766 E2E: Check revisions modal on Gutenberg
  test/e2e/lib/components/revisions-modal-component.js
  test/e2e/lib/gutenberg/gutenberg-editor-component.js
  test/e2e/lib/gutenberg/gutenberg-editor-sidebar-component.js
  test/e2e/specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#38765 E2E: Check homepage can be edited on Gutenberg after sign up
  client/components/checklist/task.js
  client/my-sites/checklist/wpcom-checklist/component.jsx
  test/e2e/lib/gutenberg/gutenberg-editor-component.js
  test/e2e/lib/pages/checklist-page.js
  test/e2e/specs/wp-signup-spec.js
Labels: [Status] Needs Review

#38767 E2E: Check Jetpack blocks on Gutenberg
  test/e2e/lib/driver-helper.js
  test/e2e/lib/gutenberg/gutenberg-editor-component.js
  test/e2e/lib/pages/editor-page.js
  test/e2e/specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#38784 Devdocs: serve the content of README.md files from the search index module
  bin/generate-devdocs-search-index.js
  package.json
  server/devdocs/index.js
Labels: Build, DevDocs, [Status] Needs Review

#38785 Devdocs: remove component usage counts
  client/components/focusable/docs/example.jsx
  client/devdocs/design/index.jsx
  client/devdocs/design/playground.jsx
  client/devdocs/docs-example/index.jsx
  client/devdocs/docs-example/test/index.jsx
  client/state/action-types.js
  client/state/components-usage-stats/README.md
  client/state/components-usage-stats/actions.js
  client/state/components-usage-stats/reducer.js
  client/state/components-usage-stats/test/actions.js
  client/state/components-usage-stats/test/reducer.js
  client/state/reducer.js
  config/desktop-development.json
  config/development.json
  config/test.json
  config/wpcalypso.json
  package.json
  packages/components/src/button/docs/example.jsx
  server/devdocs/bin/generate-components-usage-stats.js
  server/devdocs/index.js
  server/devdocs/integration/index.js
  tsconfig.json
  webpack.config.node.js
Labels: DevDocs, [Status] Needs Review

#38507 Gutenberg 7.2.0: Update E2E tests
  test/e2e/lib/flows/login-flow.js
  test/e2e/lib/gutenberg/blocks/image-block-component.js
  test/e2e/lib/gutenberg/gutenberg-editor-component.js
  test/e2e/lib/gutenberg/gutenberg-editor-sidebar-component.js
  test/e2e/lib/gutenberg/gutenberg-page-preview-component.js
  test/e2e/lib/gutenberg/gutenberg-post-preview-component.js
  test/e2e/specs/wp-calypso-gutenberg-coblocks-spec.js
  test/e2e/specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#38774 getUrlParts: Fix missing searchParams in relative URLs.
  client/lib/url/test/url-parts.js
  client/lib/url/url-parts.ts
Labels: [Status] Needs Review, [Type] Bug

#38760 Allow for non-absolute URLs in gravatar component.
  client/components/gravatar/index.jsx
Labels: Components, [Status] Needs Review, [Type] Bug

#38543 Reader: fix double-encoded entities in post title
  client/lib/post-normalizer/rule-decode-entities.js
Labels: Reader, [Status] Needs Review

#38738 Randomize the auto-renewal cancellation survey options.
  client/components/marketing-survey/cancel-auto-renewal-form/index.jsx
Labels: [Status] Needs Review

#38743 Site migration: go to cart when target site doesn't have a supported plan
  client/my-sites/migrate/section-migrate.jsx
  client/my-sites/migrate/section-migrate.scss
Labels: WP Migration, [Status] Needs Review

#38817 Compress FSE build to tar.gz
  .circleci/config.yml
Labels: [Goal] Full Site Editing, [Status] Needs Review, [Team] Cylon, [Type] Enhancement

#38793 remove the settings menu from gutenboarding
  client/landing/gutenboarding/components/header/index.tsx
  client/landing/gutenboarding/components/header/style.scss
  client/landing/gutenboarding/components/settings-sidebar/index.tsx
  client/landing/gutenboarding/components/sidebar/index.tsx
  client/landing/gutenboarding/gutenboard.tsx
Labels: [Status] Needs Review

#38816 Migrate Whoops Image Uses to Webpack
  client/assets/images/illustrations/whoops.svg
  client/my-sites/domains/domain-management/components/domain/maintenance-card.jsx
  client/my-sites/invites/invite-accept/index.jsx
  client/my-sites/types/post-type-forbidden/index.jsx
Labels: OSS Citizen, [Status] Needs Review, [Type] Janitorial

#38830 Revert "Fix: Sites created through the ecommerce flow should be private"
  client/lib/signup/step-actions.js
  client/state/selectors/get-new-site-public-setting.ts
  client/state/selectors/should-new-site-be-private-by-default.ts
  client/state/selectors/test/get-new-site-public-setting.js
  client/state/selectors/test/should-new-site-be-private-by-default.js
Labels: Plans, Signup, [Status] Ready to Merge, eCommerce Plan

#38758 Add vertical space around design grid
  client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
  client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Labels: [Status] Needs Review

#38705 Update/gutenboarding hide next button in intent gathering step
  client/landing/gutenboarding/components/header/index.tsx
  client/landing/gutenboarding/gutenboard.tsx
  client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
  client/landing/gutenboarding/steps.ts
  client/landing/gutenboarding/stores/onboard/actions.ts
  client/landing/gutenboarding/stores/onboard/reducer.ts
  client/landing/gutenboarding/stores/onboard/types.ts
Labels: [Goal] Gutenberg, [Goal] Onboarding, [Status] Needs Review

#38782 Gutenboarding: Fix design selector description always visible
  client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Labels: [Goal] Onboarding, [Type] Bug

#38783 Components: Suggestions escape regexp
  client/components/suggestion-search/index.jsx
  package-lock.json
  packages/components/package.json
  packages/components/src/suggestions/item.jsx
Labels: Packages, [Status] Needs Review, [Type] Bug

#38692 ESLint: Fix triple asterisks in JSdoc blocks
  client/blocks/comments/post-comment-list.jsx
  client/blocks/comments/post-comment-with-error.jsx
  client/blocks/comments/post-trackback.jsx
  client/blocks/conversation-caterpillar/index.jsx
  client/blocks/conversations/list.jsx
  client/components/auto-direction/index.jsx
  client/state/comments/actions.js
  client/state/comments/reducer.js
  client/state/comments/selectors.js
  client/state/http/actions.js
  client/state/http/index.js
  client/state/jetpack-connect/utils.js
  client/state/login/selectors.js
  client/state/oauth2-clients/selectors.js
  client/state/ui/oauth2-clients/selectors.js
Labels: [Status] Needs Review, [Type] Janitorial

#38808 E2E: Add Gutenberg basic publish post to IE11 canary test suite
  test/e2e/lib/gutenberg/gutenberg-editor-component.js
  test/e2e/specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#38660 Upgrade to core-js@3.
  apps/notifications/src/standalone/index.js
  babel.dependencies.config.js
  client/boot/polyfills.js
  client/lib/url/test/url-type-polyfill.js
  index.js
  package-lock.json
  package.json
  packages/calypso-build/babel/default.js
  packages/calypso-polyfills/.eslintrc.js
  packages/calypso-polyfills/README.md
  packages/calypso-polyfills/browser-evergreen.js
  packages/calypso-polyfills/browser-fallback.js
  packages/calypso-polyfills/node.js
  packages/calypso-polyfills/package.json
  packages/composite-checkout-wpcom/src/mock/cart-endpoint.ts
  packages/composite-checkout/demo/index.js
  webpack.config.js
Labels: Build, Framework, [Status] Needs Review, [Type] Janitorial

#38531 Build: move dependency transpilation config to calypso-build
  packages/calypso-build/CHANGELOG.md
  packages/calypso-build/babel/dependencies.js
  packages/calypso-build/webpack.config.js
  packages/calypso-build/webpack/util.js
  webpack.config.js
Labels: Build, [Status] Needs Review

#38733 Banner: Allow for more customization from parent instances
  client/components/banner/README.md
  client/components/banner/docs/example.jsx
  client/components/banner/index.jsx
  client/components/banner/style.scss
  client/components/banner/test/index.jsx
Labels: Components, [Status] Needs Review

#38848 [Coming Soon] Add isSiteComingSoon selector
  client/state/selectors/is-site-coming-soon.js
  client/state/selectors/test/is-site-coming-soon.js
Labels: Coming Soon, [Status] Needs Review, [Tests] Includes Tests

#38473 Jetpack Backup: Fix Credentials and AL wording based on currently supported product
  client/my-sites/activity/activity-log/index.jsx
  client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx
  client/state/selectors/site-supports-realtime-backup.js
  client/state/selectors/test/site-supports-realtime-backup.js
Labels: Activity Log, Jetpack, Site Settings, [Status] Ready to Merge, [Type] Enhancement

#38488 Media Modal - Remove special case for single external media image selection. Disable adding transients.
  client/post-editor/media-modal/index.jsx
  client/post-editor/media-modal/test/index.jsx
Labels: [Status] Ready to Merge, [Team] Cylon, [Type] Bug

#38838 Adds Themes and Plugins to valid JITM locations
  client/layout/index.jsx
Labels: Jetpack, [Status] Needs Review

#38862 Calypso Build: Fix Changelog
  packages/calypso-build/CHANGELOG.md
Labels: Build, [Status] Needs Review

#38648 Notifications: Update README
  apps/notifications/README.md
Labels: Notifications, [Status] Ready to Merge

#38870 Build: add Punycode to the list of transpiled NPM deps
  packages/calypso-build/CHANGELOG.md
  packages/calypso-build/webpack/util.js
Labels: Build, Packages, [Status] Needs Review

#38266 Domains: Fix refunds for domain renewals
  client/lib/purchases/index.js
  client/lib/purchases/test/data/index.js
  client/me/purchases/cancel-purchase/button.jsx
  client/me/purchases/cancel-purchase/index.jsx
  client/me/purchases/manage-purchase/index.jsx
  client/me/purchases/remove-purchase/index.jsx
Labels: Domains, [Status] Needs Review

#38851 Use proper `this` when calling i18n.hasTranslation
  client/lib/i18n-utils/test/utils.js
  client/lib/i18n-utils/utils.js
Labels: [Tests] Includes Tests, [Type] Bug

#38537 UpsellNudge: Add UpsellNudge block to unify upsell nudges going forward
  client/blocks/upsell-nudge/README.md
  client/blocks/upsell-nudge/index.jsx
  client/blocks/upsell-nudge/style.scss
Labels: [Status] Needs Review

#38719 Photon.js: remove dependency on node's url.
  packages/photon/History.md
  packages/photon/README.md
  packages/photon/package.json
  packages/photon/src/index.js
  packages/photon/test/index.js
Labels: [Status] Needs Review, [Type] Janitorial

#38863 UpsellNudge: Add UpsellNudge block examples to devdocs
  client/blocks/upsell-nudge/docs/example.jsx
  client/devdocs/design/blocks.jsx
Labels: DevDocs

#38879 Notifications: Fix to make work with current calypso-build version
  apps/notifications/package.json
  apps/notifications/postcss.config.js
  package-lock.json
Labels: Build, Notifications, [Status] Needs Review

#38463 [SIGNUP]: A/B test an alternative default logged-in landing page
  client/boot/common.js
  client/lib/abtest/active-tests.js
Labels: ABTest, Customer Home, Reader, [Status] Needs Review, [Team] Zelda

#38001 Build: upgrade mini-css-extract-plugin-with-rtl to npm-published a8c fork
  package-lock.json
  packages/calypso-build/CHANGELOG.md
  packages/calypso-build/package.json
  packages/calypso-build/webpack/sass.js
Labels: Build

#38854 Gutenboarding: design picker animations with react-spring
  client/landing/gutenboarding/onboarding-block/design-selector/design-card.tsx
  client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
  client/landing/gutenboarding/onboarding-block/design-selector/style.scss
  client/package.json
Labels: [Goal] Gutenboarding, [Status] Needs Review

#38805 Gutenboarding: fix height of card media/img
  client/landing/gutenboarding/onboarding-block/design-selector/page-layout-selector.tsx
  client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Labels: [Goal] Onboarding, [Status] Needs Design Review, [Status] Needs Review

#38803 [Coming Soon] Update "Private" copy to "Coming Soon"
  client/blocks/site/index.jsx
  client/state/sites/constants.js
Labels: Coming Soon, [Status] Needs Review

#38320 Add getAllStoredItems to lib/browser-storage
  client/lib/browser-storage/bypass.ts
  client/lib/browser-storage/index.ts
  client/lib/browser-storage/test/bypass.js
  client/lib/browser-storage/test/indexed-db.js
  client/lib/browser-storage/test/local-storage.js
  client/lib/browser-storage/types.ts
  package-lock.json
  package.json
Labels: [Status] Needs Review, [Type] Enhancement

#38657 Improve keyboard support for the language switcher
  client/components/language-picker/modal.jsx
  client/components/language-picker/test/__snapshots__/modal.js.snap
  client/components/language-picker/test/modal.js
  client/components/search/index.jsx
Labels: [Status] Ready to Merge, i18n

#38859 Make placement of JITMs to be more specific
  client/layout/index.jsx
  client/lib/route/path.ts
  client/lib/route/test/index.js
Labels: Jetpack, [Status] Ready to Merge

#38906 Jitm: Add theme jitm section
  client/my-sites/theme/main.jsx
  client/my-sites/theme/style.scss
Labels: Themes, [Status] Ready to Merge

#38897 Jetpack Cloud: PoC v3 (AKA "barebone")
  client/assets/stylesheets/jetpack-cloud.scss
  client/landing/jetpack-cloud/controller.js
  client/landing/jetpack-cloud/index.js
  client/landing/jetpack-cloud/layout.js
  client/landing/jetpack-cloud/masterbar.jsx
  client/landing/jetpack-cloud/routes.js
  client/landing/jetpack-cloud/section.js
  client/landing/jetpack-cloud/sidebar.jsx
  client/server/pages/index.js
  client/webpack.config.js
  config/development.json
Labels: Jetpack, [Status] Needs Review, [Type] New feature

#38901 Use now available Object.fromEntries in i18n-utils
  client/lib/i18n-utils/switch-locale.js
Labels: [Status] Needs Review, [Type] Janitorial

#38883 Client README: Remove reference to notifications dir
  client/README.md
Labels: Documentation, [Status] Needs Review

#38914 fix(deps): update d3-select, d3-shape
  client/package.json
  package-lock.json
Labels: Framework

#38930 Fix missing flag icons on stats
  client/lib/flags/index.js
  packages/calypso-build/jest/transform/README.md
Labels: [Type] Defect

#30287 Sign-up: Reader Landing - Move Button Outside Card
  client/signup/steps/reader-landing/content.jsx
  client/signup/steps/reader-landing/style.scss
Labels: OSS Citizen, Reader, Signup, [Status] Needs Review

#38902 Fix integration tests after the client/ monorepo reshuffling
  client/server/api/index.js
  client/server/devdocs/integration/index.js
  test/integration/jest.config.js
Labels: Build, [Status] Needs Review

#38933 Fix ContactFormBlockComponent e2e page object
  test/e2e/lib/gutenberg/blocks/contact-form-block-component.js
Labels: Testing, [Status] Needs Review, [Status] Needs e2e Testing

#38905 Customer Home: Move "Go Mobile" to top on mobile viewports
  client/my-sites/customer-home/main.jsx
Labels: [Status] Needs Review

#38712 Domains: Add copy to map or transfer domain in the removal dialog
  client/lib/url/support.js
  client/me/purchases/remove-purchase/remove-domain-dialog/index.jsx
Labels: Domains, [Status] Needs Review, [Status] String Freeze

#38940 Mobile Apps: Crop Google Play badge image
  client/blocks/get-apps/apps-badge.scss
  client/my-sites/customer-home/main.jsx
  client/my-sites/customer-home/style.scss
Labels: [Status] Needs Review

#38946 ESLint: fix import lint errors in tests
  client/.eslintrc.js
  client/components/forms/form-toggle/test/index.jsx
  client/components/phone-input/test/test-phone-number.js
  client/lib/cart-values/test/index.js
  client/lib/cart/store/test/cart-synchronizer.js
  client/lib/form-state/test/index.js
  client/lib/phone-validation/test/index.jsx
  client/state/happiness-engineers/test/selectors.js
  packages/components/.eslintrc.js
Labels: Framework, [Status] Needs Review

#38866 Move calls for email magic link to data-layer
  client/blocks/app-promo/index.jsx
  client/blocks/get-apps/mobile-download-card.jsx
  client/blocks/login/login-form.jsx
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/login/magic-login/request-login-email-form.jsx
  client/state/action-types.js
  client/state/auth/actions.js
  client/state/data-layer/wpcom/auth/send-login-email/index.js
  client/state/login/magic-login/actions.js
Labels: [Status] Needs Review, [Type] Janitorial

#38647 Notifications: Update styles
  apps/notifications/src/panel/boot/stylesheets/main.scss
  apps/notifications/src/panel/boot/stylesheets/shared/sizes.scss
  apps/notifications/src/panel/templates/summary-in-list.jsx
Labels: Notifications, [Status] In Progress

#38843 Migration: allow for free-form entry of site url
  client/my-sites/migrate/controller.js
  client/my-sites/migrate/index.js
  client/my-sites/migrate/section-migrate.jsx
  client/my-sites/migrate/section-migrate.scss
  client/my-sites/migrate/step-import-or-migrate.jsx
  client/my-sites/migrate/step-source-select.jsx
Labels: WP Migration, [Status] Needs Review

#38845 FSE: Add script to automatically sync changes to your wpcom sandbox
  apps/full-site-editing/bin/npm-run-build.js
  apps/full-site-editing/bin/wpcom-watch-and-sync.sh
  apps/full-site-editing/package.json
  package-lock.json
Labels: [Goal] Full Site Editing, [Status] Needs Review, [Team] Cylon

#38791 Gutenboarding: prevent unneccessary cursor change over gutenbo…
  client/landing/gutenboarding/gutenboard.tsx
Labels: [Goal] Gutenboarding, [Status] Needs Review

#37542 Allow removal of disconnected Jetpack purchases
  client/components/marketing-survey/cancel-auto-renewal-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/enriched-survey-data.js
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/test/enriched-survey-data.js
  client/components/marketing-survey/gsuite-cancel-purchase-dialog/index.jsx
  client/lib/purchases/assembler.js
  client/me/purchases/cancel-purchase/button.jsx
  client/me/purchases/cancel-purchase/index.jsx
  client/me/purchases/cancel-purchase/loading-placeholder.jsx
  client/me/purchases/controller.jsx
  client/me/purchases/index.js
  client/me/purchases/manage-purchase/index.jsx
  client/me/purchases/purchases-list/index.jsx
  client/my-sites/site-settings/disconnect-site/confirm.jsx
Labels: Checkout, Jetpack, [Status] Needs Review, [Type] Defect, [Type] Enhancement

#38675 Making @automattic/components work in isolation
  client/components/gsuite/gsuite-features/style.scss
  client/layout/masterbar/oauth-client.scss
  package-lock.json
  package.json
  packages/components/.storybook/config.js
  packages/components/.storybook/presets.js
  packages/components/README.md
  packages/components/src/button/index.stories.jsx
  packages/components/src/button/style.scss
  packages/components/src/card/style.scss
  packages/components/src/dialog/index.stories.jsx
  packages/components/src/dialog/style.scss
  packages/components/src/product-icon/index.stories.jsx
  packages/components/src/product-icon/index.stories.scss
  packages/components/src/progress-bar/index.stories.tsx
  packages/components/src/ribbon/index.stories.jsx
  packages/components/src/ribbon/style.scss
  packages/components/src/screen-reader-text/index.stories.jsx
  packages/components/src/styles/_breakpoints.scss
  packages/components/src/styles/_clear-fix.scss
  packages/components/src/styles/_typography.scss
  packages/components/tsconfig.json
Labels: Packages, [Status] Needs Review

#38908 JITMs: Add support for Jetpack JITM banners
  client/blocks/jitm/templates/default.jsx
  client/components/banner/README.md
  client/components/banner/docs/example.jsx
  client/components/banner/index.jsx
  client/components/banner/style.scss
  client/components/banner/test/index.jsx
Labels: Components, Jetpack, [Status] Needs Review, [Tests] Includes Tests, [Type] Enhancement

#38802 Gutenboarding: Use Card component from package
  client/landing/gutenboarding/components/card/README.md
  client/landing/gutenboarding/components/card/body.js
  client/landing/gutenboarding/components/card/context.js
  client/landing/gutenboarding/components/card/divider.js
  client/landing/gutenboarding/components/card/footer.js
  client/landing/gutenboarding/components/card/header.js
  client/landing/gutenboarding/components/card/index.js
  client/landing/gutenboarding/components/card/media.js
  client/landing/gutenboarding/components/card/styles/card-styles.js
  client/landing/gutenboarding/onboarding-block/design-selector/design-card.tsx
  client/landing/gutenboarding/onboarding-block/design-selector/page-layout-selector.tsx
Labels: [Status] Needs Review, [Type] Janitorial, [Type] Task

#38867 G Suite: Put the Stats & Email Management page behind a capability check
  client/my-sites/email/email-management/index.jsx
  client/my-sites/stats/stats-banners/index.jsx
Labels: G Suite, [Status] Needs Review

#38886 Domains: Update the domain suggestion vendor in NUX to use selected vertical as hint
  client/lib/domains/suggestions/index.js
  client/signup/steps/domains/index.jsx
Labels: Domains, [Status] Needs Review

#38666 Settings: Update footer credit upgrade banner
  client/my-sites/site-settings/form-general.jsx
Labels: Site Settings, [Status] Needs Review, [Status] String Freeze

#38828 Site Migration: Update migration confirmation UI
  client/my-sites/migrate/components/import-type-choice/index.jsx
  client/my-sites/migrate/components/import-type-choice/style.scss
  client/my-sites/migrate/helpers/index.js
  client/my-sites/migrate/migrate-button.jsx
  client/my-sites/migrate/section-migrate.jsx
  client/my-sites/migrate/section-migrate.scss
  client/my-sites/migrate/step-import-or-migrate.jsx
Labels: [Status] In Progress, [Type] Enhancement

#38717 Suggestions: Pass optional container class
  client/extensions/zoninator/components/search-autocomplete/style.scss
  client/landing/gutenboarding/onboarding-block/vertical-select/style.scss
  client/signup/steps/site-topic/style.scss
  client/signup/style.scss
  packages/components/src/suggestions/index.jsx
  packages/components/src/suggestions/style.scss
  packages/components/src/suggestions/test/__snapshots__/index.js.snap
Labels: [Goal] Gutenboarding, [Goal] Onboarding, [Status] Needs Review

#38823 Add user store to packages/data-stores and use wpcom-proxy-request for API calls
  client/landing/gutenboarding/devtools.ts
  packages/data-stores/global.d.ts
  packages/data-stores/package.json
  packages/data-stores/src/index.ts
  packages/data-stores/src/user/README.md
  packages/data-stores/src/user/actions.ts
  packages/data-stores/src/user/constants.ts
  packages/data-stores/src/user/controls.ts
  packages/data-stores/src/user/index.ts
  packages/data-stores/src/user/reducer.ts
  packages/data-stores/src/user/resolvers.ts
  packages/data-stores/src/user/selectors.ts
  packages/data-stores/src/user/types.ts
  packages/data-stores/src/utils/index.ts
  packages/data-stores/src/utils/wpcom-wrapper.ts
  packages/data-stores/tsconfig.json
Labels: [Goal] Gutenboarding, [Status] Needs Review, [Type] Task

#38839 Remove `escape-string-regexp` dependency
  CREDITS.md
  client/blocks/user-mentions/add.jsx
  client/components/tinymce/plugins/mentions/mentions.jsx
  client/package.json
  client/reader/following-manage/subscriptions.jsx
  client/server/devdocs/index.js
  packages/components/package.json
  packages/components/src/suggestions/item.jsx
Labels: Performance, [Status] Needs Review, [Status] Ready to Merge

#38938 Gutenboarding: Use pointer cursor for design selector and page layout selector.
  client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Labels: [Goal] Gutenboarding, [Status] In Progress

#38943 Switch to our fork of react-virtualized.
  client/blocks/taxonomy-manager/list.jsx
  client/blocks/term-tree-selector/terms.jsx
  client/components/virtual-list/index.jsx
  client/extensions/woocommerce/app/product-categories/list.js
  client/my-sites/post-selector/selector.jsx
  client/package.json
  client/reader/components/reader-infinite-stream/index.jsx
  client/webpack.config.js
  package-lock.json
  packages/calypso-build/webpack/util.js
Labels: Performance, [Status] Needs Review, [Type] Janitorial

#38825 [Coming Soon] Adjust privacy picker to contain Coming Soon option
  client/my-sites/site-settings/form-general.jsx
  client/my-sites/site-settings/style.scss
  client/my-sites/site-settings/test/form-general.jsx
  client/my-sites/site-settings/wrap-settings-form.jsx
  config/development.json
Labels: Coming Soon, [Status] Needs Review, [Team] Zelda, [Tests] Includes Tests

#38551 Gutenboarding: Add polyfill
  client/landing/gutenboarding/index.tsx
Labels: [Status] Ready to Merge, [Type] Task

#39009 Fix error handling in the install-if-deps-outdated script
  bin/install-if-deps-outdated.js
  package.json
Labels: Build, [Status] Needs Review, [Type] Janitorial

#39008 Npm prune and dedupe
  package-lock.json
Labels: Build, [Status] Needs Review, [Type] Janitorial

#38945 Domains: Remove prompt to contact support
  client/me/purchases/remove-purchase/remove-domain-dialog/index.jsx
Labels: Domains, Purchases, [Status] Ready to Merge

#39012 Build: Silence a tsc error on update-deps
  packages/data-stores/src/domain-suggestions/index.ts
  packages/data-stores/src/user/index.ts
  packages/data-stores/src/verticals-templates/index.ts
  packages/data-stores/src/verticals/index.ts
Labels: Build, Packages, [Status] Needs Review

#38995 composite-checkout: Fix TOS links and placeholder domain
  packages/composite-checkout-wpcom/src/components/wp-checkout-order-review.js
  packages/composite-checkout-wpcom/src/components/wp-checkout.js
  packages/composite-checkout-wpcom/src/components/wp-terms-and-conditions.js
Labels: Domains, [Status] Ready to Merge

#38992 Fix "Continue" button not working due to scaling transitions.
  client/landing/gutenboarding/onboarding-block/question/index.tsx
Labels: Design, [Goal] Gutenboarding, [Goal] Onboarding, [Status] Ready to Merge, [Type] Bug

#39006 Migration: Add upgrade confirmation step
  client/my-sites/migrate/controller.js
  client/my-sites/migrate/index.js
  client/my-sites/migrate/section-migrate.jsx
  client/my-sites/migrate/step-confirm-migration.jsx
  client/my-sites/migrate/step-upgrade.jsx
Labels: WP Migration, [Status] Ready to Merge

#38716 Gutenboarding: Align suggestions under verticals container
  client/landing/gutenboarding/onboarding-block/vertical-select/style.scss
Labels: [Goal] Onboarding, [Status] Ready to Merge

#39015 Migration: fix migration start on confirmation step
  client/my-sites/migrate/step-confirm-migration.jsx
Labels: WP Migration, [Status] Needs Review

#38954 Gutenboarding: Fix page selector card hover
  client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Labels: [Goal] Gutenboarding, [Goal] Onboarding, [Status] Ready to Merge

#39019 Update eslint and friends
  package-lock.json
  package.json
Labels: Framework

#39010 Gutenboarding: add custom pre-launch signup flow
  client/signup/config/flows-pure.js
Labels: Signup, [Goal] Gutenboarding, [Goal] Onboarding, [Status] Needs Review

#38972 Fix/suggestion search devdocs
  client/components/suggestion-search/docs/example.jsx
Labels: DevDocs, [Status] Needs Review, [Type] Bug
