Repository Automattic/wp-calypso, pull requests merged in 2021-08, with the labels that each got.

#54998 Jetpack Cloud: enable Search section
  client/components/jetpack/sidebar/menu-items/index.jsx
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
Labels: Jetpack Cloud, Jetpack Search, [Status] Ready to Merge

#55055 chore: Migrate docs to use import/order
  .eslintrc.js
  docs/coding-guidelines/javascript.md
  docs/color.md
  docs/component-readme-template.md
  docs/guide/hello-world.md
  docs/modularized-state.md
  docs/our-approach-to-data.md
  docs/routing.md
  docs/testing/component-tests.md
  docs/testing/snapshot-testing.md
Labels: [Status] Needs Review

#55060 Delete unused e2e scripts
  package.json
Labels: [Status] Needs Review

#55005 chore/update-node-16.5.0
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/tooling_request.yml
  .github/workflows/editing-toolkit-plugin.yml
  .github/workflows/icfy-stats.yml
  .nvmrc
  Dockerfile
  Dockerfile.base
  client/lib/analytics/test/mocks/config/index.js
  client/server/lib/logger/test/index.js
  client/server/pages/test/index.js
  desktop/Dockerfile
  package.json
  packages/calypso-codemods/api.js
  packages/wp-babel-makepot/Dockerfile
Labels: [Status] Needs Review

#55025 chore: migrate `apps/wpcom-block-editor` to `import/order`
  .eslintrc.js
  apps/wpcom-block-editor/src/calypso/editor.js
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
  apps/wpcom-block-editor/src/calypso/features/tinymce.js
  apps/wpcom-block-editor/src/calypso/tinymce.js
  apps/wpcom-block-editor/src/default/editor.js
  apps/wpcom-block-editor/src/default/features/rich-text.js
  apps/wpcom-block-editor/src/default/view.js
  apps/wpcom-block-editor/src/utils.js
  apps/wpcom-block-editor/src/wpcom/editor.js
  apps/wpcom-block-editor/src/wpcom/features/deprecate-coblocks-buttons.js
  apps/wpcom-block-editor/src/wpcom/features/fix-block-invalidation-errors.js
  apps/wpcom-block-editor/src/wpcom/features/images.js
  apps/wpcom-block-editor/src/wpcom/features/reorder-block-categories.js
  apps/wpcom-block-editor/src/wpcom/features/tracking.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/delegate-event-tracking.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/track-record-event.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-donations-plan-upgrade.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-donations-stripe-connect.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-close-click.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-details-open.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-global-styles-tab-selected.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-list-view-select.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-template-part-detach-blocks.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-premium-content-plan-upgrade.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-premium-content-stripe-connect.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-inserter-inline-search-term.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-inserter-menu-search-term.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-inserter-tab-panel-selected.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-template-part-choose-existing.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-template-part-replace.js
  apps/wpcom-block-editor/src/wpcom/features/use-classic-block-guide.js
  apps/wpcom-block-editor/src/wpcom/features/utils.js
  apps/wpcom-block-editor/webpack.config.js
Labels: [Status] Needs Review

#55091 chore: migrate `client/server` to `import/order`
  .eslintrc.js
  client/server/api/index.js
  client/server/api/integration/index.js
  client/server/api/sign-in-with-apple.js
  client/server/boot/index.js
  client/server/bundler/index.js
  client/server/bundler/utils.js
  client/server/config/index.js
  client/server/config/parser.js
  client/server/config/test/parser.js
  client/server/devdocs/index.js
  client/server/devdocs/selectors/index.js
  client/server/index.js
  client/server/isomorphic-routing/index.js
  client/server/isomorphic-routing/test/index.js
  client/server/lib/analytics/index.js
  client/server/lib/analytics/test/index.js
  client/server/lib/logger/index.js
  client/server/lib/logger/test/index.js
  client/server/middleware/assets.js
  client/server/middleware/build-target.js
  client/server/middleware/logger.js
  client/server/middleware/test/logger.js
  client/server/pages/analytics.js
  client/server/pages/index.js
  client/server/pages/test/analytics.js
  client/server/pages/test/index.js
  client/server/pwa/index.js
  client/server/pwa/manifest.js
  client/server/render/index.js
  client/server/render/test/index.js
  client/server/sanitize/test/index.js
  client/server/state-cache/index.js
  client/server/user-bootstrap/index.js
Labels: [Status] Needs Review

#55092 chore: migrate `client/jetpack-connect` to `import/order`
  .eslintrc.js
  client/jetpack-connect/auth-form-header.jsx
  client/jetpack-connect/authorize.js
  client/jetpack-connect/controller.js
  client/jetpack-connect/disclaimer.jsx
  client/jetpack-connect/example-components/jetpack-activate.jsx
  client/jetpack-connect/example-components/jetpack-connect.jsx
  client/jetpack-connect/example-components/jetpack-install.jsx
  client/jetpack-connect/flow-types.js
  client/jetpack-connect/happychat-button.jsx
  client/jetpack-connect/help-button.jsx
  client/jetpack-connect/index.js
  client/jetpack-connect/install-instructions.jsx
  client/jetpack-connect/install-step.jsx
  client/jetpack-connect/jetpack-connect-notices.jsx
  client/jetpack-connect/jetpack-connection.jsx
  client/jetpack-connect/jetpack-remote-install-notices.jsx
  client/jetpack-connect/main-header.jsx
  client/jetpack-connect/main-wrapper.jsx
  client/jetpack-connect/main.jsx
  client/jetpack-connect/no-direct-access-error.js
  client/jetpack-connect/persistence-utils.js
  client/jetpack-connect/remote-credentials.js
  client/jetpack-connect/search.jsx
  client/jetpack-connect/signup.js
  client/jetpack-connect/site-url-input.jsx
  client/jetpack-connect/sso.jsx
  client/jetpack-connect/store-footer.tsx
  client/jetpack-connect/store-header.tsx
  client/jetpack-connect/test/auth-form-header.js
  client/jetpack-connect/test/authorize.js
  client/jetpack-connect/test/jetpack-connect-notices.js
  client/jetpack-connect/test/main-wrapper.jsx
  client/jetpack-connect/test/signup.js
  client/jetpack-connect/test/utils.js
  client/jetpack-connect/utils.js
Labels: [Status] Needs Review

#55061 Emails: Create checklist setup card for Professional Emails
  client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
  client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
  client/state/data-layer/wpcom/checklist/index.js
Labels: [Status] Needs Review

#53221 server: Redirect fallback browsers to /browsehappy
  client/document/browsehappy.jsx
  client/landing/browsehappy/circle.jsx
  client/landing/browsehappy/circle.scss
  client/landing/browsehappy/illustration.svg
  client/landing/browsehappy/index.jsx
  client/landing/browsehappy/logo-wide.jsx
  client/landing/browsehappy/style.scss
  client/server/middleware/unsupported-browser.js
  client/server/pages/index.js
  client/server/pages/test/index.js
  client/webpack.config.js
  config/development.json
  config/horizon.json
  config/wpcalypso.json
  static/images/drake/drake-all-done.svg
  static/images/drake/drake-browser.svg
Labels: [Status] Needs Review

#55094 chore: migrate `desktop/app` to `import/order`
  .eslintrc.js
  desktop/app/app-handlers/crash-reporting/index.js
  desktop/app/app-handlers/exceptions/index.js
  desktop/app/app-handlers/preferences/index.js
  desktop/app/app-handlers/printer/index.js
  desktop/app/app-handlers/secrets/index.js
  desktop/app/app-handlers/updater/auto-updater/index.js
  desktop/app/app-handlers/updater/index.js
  desktop/app/app-handlers/updater/manual-updater/index.js
  desktop/app/app.js
  desktop/app/env.js
  desktop/app/index.js
  desktop/app/lib/app-instance/index.js
  desktop/app/lib/archiver/index.js
  desktop/app/lib/calypso-commands/index.js
  desktop/app/lib/config/index.js
  desktop/app/lib/crash-tracker/index.js
  desktop/app/lib/is-calypso/index.js
  desktop/app/lib/logger/index.js
  desktop/app/lib/menu/app-menu.js
  desktop/app/lib/menu/calypso-menu.js
  desktop/app/lib/menu/help-menu.js
  desktop/app/lib/menu/index.js
  desktop/app/lib/menu/main-menu.js
  desktop/app/lib/menu/view-menu.js
  desktop/app/lib/menu/window-menu.js
  desktop/app/lib/platform/index.js
  desktop/app/lib/platform/linux/index.js
  desktop/app/lib/platform/mac/dock-menu.js
  desktop/app/lib/platform/mac/index.js
  desktop/app/lib/platform/windows/index.js
  desktop/app/lib/platform/windows/tray-menu.js
  desktop/app/lib/settings/index.js
  desktop/app/lib/settings/settings-file.js
  desktop/app/lib/system/index.js
  desktop/app/lib/updater/index.js
  desktop/app/lib/window-manager/index.js
  desktop/app/mainWindow/index.js
  desktop/app/window-handlers/external-links/index.js
  desktop/app/window-handlers/failed-to-load/index.js
  desktop/app/window-handlers/get-logs/index.js
  desktop/app/window-handlers/login-status/index.js
  desktop/app/window-handlers/navigation/index.js
  desktop/app/window-handlers/notifications/index.js
  desktop/app/window-handlers/spellcheck/index.js
  desktop/app/window-handlers/window-saver/index.js
Labels: [Status] Needs Review

#55064 Setup Mailbox: Redirect to new Thank You page on successful creation
  client/my-sites/email/titan-setup-mailbox/titan-setup-mailbox-form.jsx
Labels: Professional Email, [Status] Needs Review

#55031 Revert "Revert "Jetpack Backup plugin skip the plans page on auth""
  client/jetpack-connect/authorize.js
  client/jetpack-connect/test/authorize.js
Labels: [Status] Needs Review

#54615 Add new card when you haven't used your free domain credit
  client/my-sites/domains/domain-management/list/empty-domains-list-card.jsx
  client/my-sites/domains/domain-management/list/index.jsx
  client/my-sites/domains/domain-management/list/style.scss
Labels: Domains, [Status] Needs Review

#55076 Playwright: Revert changes from #54858 relevant to the LoginPage and LoginFlow.
  packages/calypso-e2e/src/lib/flows/login-flow.ts
  packages/calypso-e2e/src/lib/pages/login-page.ts
Labels: [Status] Needs Review

#54732 Add tracks to the domain connect mapping page
  client/my-sites/domains/domain-management/domain-connect-mapping/index.jsx
Labels: Domains, [Status] Needs Review

#54926 Change the notice in case you search for a domain that's already registered
  client/components/domains/domain-search-results/index.jsx
  client/components/domains/domain-search-results/style.scss
Labels: Domains, [Status] Needs Review

#54940 Checkout: Move iDEAL payment method to wpcom-checkout
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-methods/index.ts
  packages/composite-checkout/src/public-api.ts
  packages/wpcom-checkout/src/index.ts
  packages/wpcom-checkout/src/payment-methods/ideal.tsx
Labels: Checkout, [Status] Ready to Merge

#54994 Domains: Fix organization field error message when the field is optional
  client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
  client/my-sites/checkout/composite-checkout/contact-validation.js
  client/my-sites/checkout/composite-checkout/hooks/wpcom-store.ts
  client/my-sites/checkout/composite-checkout/types/wpcom-store-state.ts
  client/my-sites/domains/components/form/hidden-input.jsx
  packages/wpcom-checkout/src/types.ts
Labels: Domains, [Status] Needs Review

#54762 Updating audio upload nudge copy
  client/my-sites/media-library/list-plan-upgrade-nudge.jsx
Labels: Media, Plans, [Status] String Freeze, [Type] Bug

#54624 State free domain policy on /plans for all users
  client/lib/plans/features-list.js
  client/my-sites/plan-features/index.jsx
  client/my-sites/plans-features-main/wpcom-faq.jsx
Labels: Plans, [Status] Needs Review, [Status] String Freeze, [Type] Enhancement

#54976 Fallback to non-adjusted time if site offset is unavailable
  client/components/activity-card-list/index.jsx
Labels: [Status] Needs Review

#54645 Update how the WordPress.com subdomain is managed from the domains page
  client/my-sites/domains/domain-management/list/index.jsx
  client/my-sites/domains/domain-management/list/utils.js
  client/my-sites/domains/domain-management/list/wpcom-domain-item.jsx
  client/my-sites/domains/domain-management/list/wpcom-domain-item.scss
Labels: Domains, [Status] Needs Review

#55083 Checkout: Update calypso checkout tests to use waitFor
  client/my-sites/checkout/composite-checkout/test/composite-checkout.js
Labels: [Status] Needs Review

#55108 Checkout: Add isMounted guards to some hooks
  client/my-sites/checkout/composite-checkout/hooks/use-add-products-from-url.ts
  client/my-sites/checkout/composite-checkout/hooks/use-remove-from-cart-and-redirect.ts
Labels: [Status] Needs Review

#55049 My Home/DotPager: Add animation to DotPager when content height changed
  client/components/dot-pager/index.jsx
  client/components/dot-pager/style.scss
  client/my-sites/customer-home/locations/primary/index.jsx
  client/my-sites/customer-home/locations/secondary/learn-grow/index.jsx
Labels: [Status] Needs Review

#54586 Jetpack Cloud: finish removing Connect, Checkout and Plans sections
  client/boot/common.js
  client/jetpack-cloud/sections/pricing/controller.tsx
  client/jetpack-cloud/sections/pricing/index.ts
  client/my-sites/checkout/index.js
  client/my-sites/plans/jetpack-plans/build-checkout-url.ts
  client/sections.js
  client/server/pages/index.js
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
Labels: Jetpack Cloud, [Status] Needs Review, [Type] Janitorial

#55096 Prefetch the current A/A (temporarily)
  client/signup/controller.js
Labels: [Status] Needs Review

#55097 Emails: Enable new signup step for Professional Email in all environments
  config/horizon.json
  config/production.json
  config/stage.json
Labels: Professional Email, Signup, [Status] Needs Review

#55068 Make Jetpack product card button handle long strings
  client/components/jetpack/card/jetpack-product-card/style.scss
Labels: Jetpack Cloud, [Size] XS

#54346 Add Beta Testing page
  client/data/posts/use-posts-query.js
  client/my-sites/beta-testing/controller.js
  client/my-sites/beta-testing/index.js
  client/my-sites/beta-testing/main.jsx
  client/my-sites/beta-testing/style.scss
  client/sections.js
Labels: [Status] Needs Review, [Status] String Freeze

#55129 Revert "Update the appearance of the "Add a domain" button"
  client/my-sites/domains/domain-management/list/add-domain-button.jsx
  client/my-sites/domains/domain-management/list/index.jsx
  client/my-sites/domains/domain-management/list/options-domain-button.jsx
  client/my-sites/domains/domain-management/list/options-domain-button.scss
  client/my-sites/domains/style.scss
  test/e2e/lib/pages/domains-page.js
  test/e2e/specs/specs-calypso/wp-manage-domains__add-a-domain-spec.js
  test/e2e/specs/specs-calypso/wp-manage-domains__map-a-domain-spec.js
Labels: [Status] Needs Review

#55126 Remove padding from inline-help button
  client/blocks/inline-help/style.scss
Labels: [Status] Needs Review

#55106 Jetpack site-less Checkout: include the temporary site's blog id in the payload
  client/my-sites/checkout/checkout-thank-you/jetpack-checkout-siteless-thank-you.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-complete-callback.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
  client/my-sites/checkout/controller.jsx
  client/state/data-layer/wpcom/jetpack-checkout/support-ticket/index.js
  client/state/jetpack-checkout/actions.ts
Labels: Jetpack, [Size] XS, [Status] Needs Review

#55063 Jetpack site-less Checkout: send both the receipt and the event id to `/onboarding-call`
  client/my-sites/checkout/checkout-thank-you/jetpack-checkout-siteless-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/utils.js
Labels: Jetpack, [Size] XS, [Status] Needs Review

#55082 Shopping Cart: Remove leftover loading properties added by CartStore
  client/components/domains/transfer-domain-step/index.jsx
  client/me/purchases/upcoming-renewals/upcoming-renewals-dialog.tsx
  client/my-sites/checkout/cart/cart-free-user-plan-upsell.jsx
  client/my-sites/checkout/cart/cart-total.jsx
  client/my-sites/checkout/cart/upcoming-renewals-reminder.tsx
  client/my-sites/checkout/composite-checkout/components/secondary-cart-promotions.tsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
  client/my-sites/checkout/composite-checkout/test/composite-checkout.js
Labels: Checkout, Domains, Shopping Cart, [Status] Ready to Merge

#54995 Shopping Cart: Always prevent refetch-on-focus for temporary cart keys
  client/my-sites/checkout/calypso-shopping-cart-provider.tsx
  client/my-sites/checkout/get-cart-key.ts
  client/my-sites/checkout/use-cart-key.ts
  packages/shopping-cart/src/shopping-cart-provider.tsx
  packages/shopping-cart/src/types.ts
  packages/shopping-cart/src/use-refetch-on-focus.ts
  packages/shopping-cart/src/use-shopping-cart-manager.ts
Labels: [Status] Ready to Merge

#55136 Checkout: Enable Jetpack siteless and userless checkout in wpcalypso
  config/wpcalypso.json
Labels: [Status] Needs Review

#55067 Display translated strings in cloud pricing page nav
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/index.tsx
Labels: Jetpack Cloud, [Size] XS, [Status] Needs Review

#54991 Refactor InlineSupportLink component to move context links to object
  client/components/inline-support-link/README.md
  client/components/inline-support-link/context-links.js
  client/components/inline-support-link/index.jsx
Labels: [Goal] Trail Marker, [Status] Ready to Merge

#54620 Full Site Editing: allow toggling of the Site Editor
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-universal-themes/index.php
Labels: [Goal] Full Site Editing, [Status] Needs Review

#55143 resize dotpager card when children change
  client/components/dot-pager/index.jsx
Labels: [Status] Needs Review

#55144 E2E: Update configuration file
  .teamcity/settings.kts
  test/e2e/config/encrypted.enc
Labels: [Status] Needs Review

#55146 E2E: Update configuration file, take 2
  .teamcity/settings.kts
  test/e2e/config/encrypted.enc
Labels: [Status] Needs Review

#55145 Fix: change search purchase link to landing page for Calypso and Jetpack Cloud
  client/my-sites/jetpack-search/upsell.tsx
Labels: Jetpack Cloud, Jetpack Search, [Status] Needs Review

#50415 Update wording on auto-renew disable confirmation buttons
  client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-disabling-dialog/index.jsx
Labels: Purchases, [Status] Needs Review

#55117 Change description of Substack URL to Recommended
  client/lib/importer/importer-config.js
Labels: [Status] Needs Review

#55121 My Home: Fix the behavior of toggling QuickLinks many times quickly is weird
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
  client/my-sites/customer-home/cards/actions/wp-for-teams-quick-links/index.jsx
  client/package.json
Labels: [Status] Needs Review

#55101 Emails: Automatically redirect to email management if only one provider to manage
  client/my-sites/email/email-management/email-home.jsx
Labels: [Status] Needs Review

#55125 Break line for longer domain names in email signups
  client/signup/steps/emails/index.jsx
  client/signup/steps/emails/style.scss
Labels: [Status] Needs Review

#55152 state(inline-help): remove unused `inlineHelp.ui` reducer
  client/state/action-types.ts
  client/state/inline-help/reducer.js
  client/state/inline-help/test/reducer.js
Labels: [Status] Needs Review, [Type] Janitorial

#55124 Themes: Fix Button Icon Alignment
  client/my-sites/themes/current-theme/style.scss
  client/my-sites/themes/themes-magic-search-card/style.scss
Labels: OSS Citizen, Themes, [Status] Needs Review

#55131 Welcome Tour and Modal: Allow modal to be dismissed on mobile devices
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-modal/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/style-tour.scss
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js
Labels: Editor, Editor Welcome, [Status] Needs Review

#55073 Checkout: show transfer progress during ecommerce plan checkout
  client/my-sites/checkout/checkout-thank-you/transfer-pending.jsx
  client/my-sites/checkout/checkout-thank-you/transfer-pending/index.tsx
  client/my-sites/checkout/checkout-thank-you/transfer-pending/style.scss
Labels: [Status] Design Input Requested, [Status] Needs Review

#55148 Fix deprecated selector and DRY the `openBlockInserterAndSearch` method
  test/e2e/lib/components/abstract-editor-component.js
  test/e2e/lib/components/site-editor-component.js
  test/e2e/lib/gutenberg/gutenberg-editor-component.js
Labels: [Status] Needs Review

#54741 Use new GitHub template for Happiness Bug Report
  .github/ISSUE_TEMPLATE/happiness-bug-report.md
  .github/ISSUE_TEMPLATE/happiness-bug-report.yml
Labels: [Status] Needs Review

#55123 Cart: Round Price to Appropriate Decimal Point
  client/my-sites/checkout/cart/cart-item.jsx
Labels: OSS Citizen, Shopping Cart, [Status] Ready to Merge

#55071 Playwright: remove migrated Selenium tests
  test/e2e/specs/specs-calypso/wp-notifications-spec.js
  test/e2e/specs/specs-calypso/wp-plan-purchase__comparing-spec.js
  test/e2e/specs/specs-calypso/wp-plan-purchase__renew-spec.js
  test/e2e/specs/specs-calypso/wp-plan-purchase__upgrade-spec.js
Labels: [Status] Needs Review

#55172 Use Jetpack.com/upgrade link in Scan Upsell
  client/my-sites/scan/scan-upsell/index.jsx
Labels: [Status] Needs Review

#55159 Add better availability message when no site is selected
  client/components/domains/domain-search-results/index.jsx
Labels: Domains, [Status] Needs Review

#54881 desktop: Bump version to 7.1.0-beta1
  desktop/package.json
Labels: Releases, [Status] Needs Review

#55165 CI: extract common Selenium steps to a function.
  .teamcity/_self/projects/WebApp.kt
Labels: [Status] Needs Review

#55156 Marketplace: enables feature in staging.
  config/stage.json
  config/wpcalypso.json
Labels: Marketplace

#55192 Empty Content Component: Truncate Button Text
  client/components/empty-content/style.scss
Labels: OSS Citizen

#54675 Support: update generic 'email support' text
  client/blocks/domain-to-plan-nudge/index.jsx
  client/components/marketing-survey/cancel-purchase-form/step-components/downgrade-step.jsx
  client/lib/plans/features-list.js
  client/me/help/gm-closure-notice/index.jsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.js
  packages/calypso-products/src/plans-list.js
Labels: OSS Citizen, [Status] String Freeze

#55109 Legacy FSE: Update editor classes for template block styles
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/plugins/editor-template-classes/index.js
Labels: [Type] Bug, [Status] Needs Review

#55154 InlineHelp: use `wpcom.req.get` directly instead of `Undocumented.getHelpLinks`
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/state/inline-help/actions.js
Labels: [Status] Needs Review, [Type] Janitorial

#55208 Full Site Editing: Fix template part editing for legacy FSE
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-universal-themes/index.php
Labels: [Status] Needs Review, [Goal] Full Site Editing

#55039 Change the design of the Filters section in the domain suggestions screen
  client/components/domains/register-domain-step/index.jsx
  client/components/domains/search-filters/dropdown-filters.jsx
  client/components/domains/search-filters/style.scss
  client/components/token-field/docs/example.jsx
  client/components/token-field/helpers.js
  client/components/token-field/index.jsx
  client/components/token-field/style.scss
  client/components/token-field/suggestions-list.jsx
  client/components/token-field/test/__snapshots__/index.jsx.snap
  packages/material-design-icons/src/content/outline-filter_list-24px.svg
  packages/material-design-icons/svg-sprite/material-icons.svg
Labels: [Status] Needs Review, Domains

#54845 Update/desktop win tile icons
  desktop/resource/appx/Square150x150Logo.png
  desktop/resource/appx/Wide310x150Logo.png
Labels: [Status] Needs Review, Desktop App

#55210 desktop: refine home button behavior
  desktop/app/window-handlers/navigation/index.js
Labels: [Status] Needs Review

#54715 Adding account-only signup flow
  client/lib/login/index.js
  client/lib/paths/login/index.js
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  client/signup/config/steps-pure.js
  client/signup/steps/user/index.jsx
  client/state/login/reducer.js
Labels: [Status] Needs Review, Signup

#55173 Fix failing Site Editor /Global Styles tracking tests.
  test/e2e/specs/specs-wpcom/wp-calypso-gutenberg-site-editor-tracking-spec.js
Labels: [Status] Needs Review

#55212 Desktop: Add instructions when trying to login with an email link
  desktop/app/window-handlers/external-links/index.js
  desktop/app/window-handlers/navigation/index.js
  desktop/public_desktop/magic-links-unsupported.html
  desktop/public_desktop/preload.js
Labels: [Status] Needs Review

#55170 Domains: Show "Get Domain Card" even if paid user does not have free domain credits anymore
  client/my-sites/domains/domain-management/list/empty-domains-list-card.jsx
Labels: [Status] Needs Review, Domains

#55216 Playwright: Re-enable the plans manage tests in mobile
  test/e2e/specs/specs-playwright/wp-plans__purchases-spec.ts
Labels: [Status] Needs Review

#55166 Playwright: Move components and objects off BaseContainer.
  packages/calypso-e2e/src/lib/base-container.ts
  packages/calypso-e2e/src/lib/components/comments-component.ts
  packages/calypso-e2e/src/lib/components/navbar-component.ts
  packages/calypso-e2e/src/lib/components/notifications-component.ts
  packages/calypso-e2e/src/lib/components/preview-component.ts
  packages/calypso-e2e/src/lib/components/sidebar-component.ts
  packages/calypso-e2e/src/lib/components/support-component.ts
  packages/calypso-e2e/src/lib/flows/login-flow.ts
  packages/calypso-e2e/src/lib/flows/new-post-flow.ts
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
  packages/calypso-e2e/src/lib/pages/login-page.ts
  packages/calypso-e2e/src/lib/pages/marketing-page.ts
  packages/calypso-e2e/src/lib/pages/media-page.ts
  packages/calypso-e2e/src/lib/pages/my-home-page.ts
  packages/calypso-e2e/src/lib/pages/published/published-post-page.ts
  packages/calypso-e2e/src/lib/pages/published/published-posts-list-page.ts
  packages/calypso-e2e/src/lib/pages/settings-page.ts
  packages/calypso-e2e/src/lib/pages/themes-detail-page.ts
  packages/calypso-e2e/src/lib/pages/themes-page.ts
  test/e2e/specs/specs-playwright/wp-calypso__coblocks-gutter-spec.js
  test/e2e/specs/specs-playwright/wp-calypso__coblocks-spec.js
  test/e2e/specs/specs-playwright/wp-likes__comment-spec.js
  test/e2e/specs/specs-playwright/wp-likes__post-spec.js
  test/e2e/specs/specs-playwright/wp-media__edit-spec.js
  test/e2e/specs/specs-playwright/wp-media__upload-spec.js
  test/e2e/specs/specs-playwright/wp-notifications__trash-spec.js
  test/e2e/specs/specs-playwright/wp-seo__preview-spec.js
  test/e2e/specs/specs-playwright/wp-support__search-spec.js
  test/e2e/specs/specs-playwright/wp-theme__details-preview-activate.js
  test/e2e/specs/specs-playwright/wp-theme__popover-preview.js
Labels: [Status] Needs Review

#54952 My Home: Update CTA for when the "finish store setup" task is complete
  client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
Labels: [Status] Needs Review, [Status] String Freeze, Plans: eCommerce, My Home Pod

#55014 My Home: Add new eCommerce cards to Learn & Grow section
  client/assets/images/customer-home/illustration--secondary-find-success.svg
  client/assets/images/customer-home/illustration--secondary-respond-to-customer-feedback.svg
  client/my-sites/customer-home/cards/constants.js
  client/my-sites/customer-home/cards/education/find-success/index.jsx
  client/my-sites/customer-home/cards/education/respond-to-customer-feedback/index.jsx
  client/my-sites/customer-home/locations/secondary/learn-grow/index.jsx
Labels: [Status] Needs Review, [Status] String Freeze, My Home Pod

#55223 Revert "Adding account-only signup flow"
  client/lib/login/index.js
  client/lib/paths/login/index.js
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  client/signup/config/steps-pure.js
  client/signup/steps/user/index.jsx
  client/state/login/reducer.js
Labels: [Status] Needs Review, Signup

#55178 [E2E][GB 11.2.0] Test fixes for Gutenberg v11.2.0
  test/e2e/lib/gutenberg/blocks/layout-grid-block-component.js
  test/e2e/lib/gutenberg/gutenberg-editor-sidebar-component.js
Labels: [Status] Needs Review, caused-by-gutenberg-upgrade

#55149 Support custom domains by removing .substack.com validation
  client/lib/importer/importer-config.js
  client/my-sites/importer/uploading-pane.jsx
Labels: [Status] Needs Review

#55225 My Home: Parent of `TASK_RENEW_EXPIRED_PLAN` needs a dark background
  client/my-sites/customer-home/locations/primary/index.jsx
  client/my-sites/customer-home/style.scss
Labels: [Type] Bug, [Status] Needs Review, My Home Pod

#55089 WIP: Update My Home: dismiss one of many cards
  client/components/dot-pager/index.jsx
  client/data/home/use-skip-current-view-mutation.ts
  client/my-sites/customer-home/cards/notices/celebrate-notice/index.jsx
  client/my-sites/customer-home/cards/tasks/task.jsx
Labels: [Status] Needs Review

#55226 Experiment: Convert package to ESM
  client/webpack.config.js
  packages/accessible-focus/jest.config.js
  packages/accessible-focus/package.json
Labels: [Status] Needs Review

#55104 Titan: Update all flows to use Set Up Mailbox page for setting up unused mailboxes
  client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
  client/my-sites/email/controller.js
  client/my-sites/email/email-management/home/email-plan-warnings.jsx
  client/my-sites/email/index.js
  client/my-sites/email/paths.js
  client/my-sites/email/titan-add-mailboxes/index.jsx
  client/my-sites/email/titan-add-mailboxes/titan-unused-mailbox-notice.jsx
  client/my-sites/email/titan-setup-mailbox/index.js
  client/my-sites/email/titan-setup-mailbox/style.scss
  client/my-sites/email/titan-setup-mailbox/titan-setup-mailbox-form.jsx
Labels: [Status] Needs Review, Professional Email, Email management

#55153 Emails: Make the ThankYou react component to be a completely isolated component
  client/components/thank-you/index.tsx
  client/components/thank-you/types.ts
Labels: [Status] Needs Review

#55233 Revert "Welcome tour: fix footer alignment"
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/style-tour.scss
Labels: [Status] Needs Review, Editing Toolkit, Editor Welcome

#54900 Activity Log: Add the notion of retention limits + an upsell for them
  client/components/activity-card-list/index.jsx
  client/components/activity-card-list/retention-limit-upsell/hooks.ts
  client/components/activity-card-list/retention-limit-upsell/index.tsx
  client/components/activity-card-list/retention-limit-upsell/style.scss
  client/components/data/query-activity-log-retention-policy/index.ts
  client/state/action-types.ts
  client/state/activity-log/actions.js
  client/state/activity-log/reducer.js
  client/state/activity-log/retention-policy/actions.ts
  client/state/activity-log/retention-policy/reducer.ts
  client/state/data-layer/wpcom/activity-log/get-retention-policy/index.ts
  client/state/selectors/get-site-activity-log-retention-days.ts
  client/state/selectors/is-requesting-site-activity-log-retention-policy.ts
  config/development.json
  config/jetpack-cloud-development.json
Labels: [Type] Enhancement, [Status] Needs Review, [Status] Needs Design Review, [Size] M, Activity Log, Jetpack Cloud, [Status] Design Input Requested

#55211 Add PageViews to Jetpack Checkout Thank-You Pages
  client/my-sites/checkout/checkout-thank-you/jetpack-checkout-siteless-thank-you-completed.tsx
  client/my-sites/checkout/checkout-thank-you/jetpack-checkout-siteless-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/jetpack-checkout-thank-you.tsx
Labels: Jetpack, [Status] Needs Review, Analytics, Checkout, [Size] XS

#55176 Signup: remove the soon-to-be-deactivated tt1-blocks theme
  packages/design-picker/src/available-designs-config.json
Labels: [Status] Needs Review, Signup

#55139 desktop: exempt net error 27 from "failed to load" handler
  desktop/app/window-handlers/failed-to-load/index.js
Labels: [Status] Needs Review

#55252 Revert "Support custom domains by removing .substack.com validation"
  client/lib/importer/importer-config.js
  client/my-sites/importer/uploading-pane.jsx
Labels: [Status] Needs Review, Site Importer

#55245 E2e abstract-editor-component - update class selector for editor wrapper
  test/e2e/lib/components/abstract-editor-component.js
Labels: [Status] Needs Review, [Status] Needs e2e Testing, [Status] Needs e2e Testing horizon, [Status] Needs e2e Testing Gutenberg Edge

#55247 Site Editor tracking e2e - Fix broken template part test
  test/e2e/specs/specs-wpcom/wp-calypso-gutenberg-site-editor-tracking-spec.js
Labels: [Status] Needs Review, [Status] Needs e2e Testing, [Status] Needs e2e Testing horizon, [Status] Needs e2e Testing Gutenberg Edge

#55255 [E2E][GB 11.2.1] Test fixes for Gutenberg v11.2.1
  test/e2e/lib/gutenberg/blocks/layout-grid-block-component.js
Labels: [Status] Needs Review, caused-by-gutenberg-upgrade

#55236 Fix drafts are not shown in the WordPress menu in the editor
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
Labels: [Status] Needs Review

#55220 My Home log tracks event only when a primary card is viewed
  client/components/dot-pager/index.jsx
  client/my-sites/customer-home/locations/primary/index.jsx
  client/my-sites/customer-home/locations/secondary/learn-grow/index.jsx
Labels: [Status] Needs Review

#54747 Fixes flaky test for shouldRenderMonthlyRenewalOption
  client/lib/purchases/test/index.js
Labels: [Status] Needs Review

#55227 Desktop: 7.1.0 release
  desktop/package.json
Labels: [Status] Needs Review, Desktop App, Releases

#55290 Jetpack Sync: Don't show last synced time when the finished time is invalid
  client/my-sites/site-settings/jetpack-sync-panel/index.jsx
Labels: [Type] Bug, Jetpack, [Status] Needs Review

#55218 Playwright: migrate `wp-stats` spec.
  packages/calypso-e2e/src/lib/pages/index.ts
  packages/calypso-e2e/src/lib/pages/stats-page.ts
  test/e2e/specs/specs-calypso/wp-stats-insights-spec.js
  test/e2e/specs/specs-playwright/wp-stats__insights-spec.ts
Labels: [Status] Needs Review

#55271 Importer: Fix Broken Support Document
  client/lib/importer/importer-config.js
Labels: [Status] Needs Review, Import, OSS Citizen

#55293 Full Site Editing: prevent REST API errors
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-universal-themes/index.php
Labels: [Status] Needs Review, [Goal] Full Site Editing

#55246 Activity Log: Fall back to moment when applySiteOffset isn't available
  client/components/activity-card-list/index.jsx
Labels: [Type] Bug, [Status] Needs Review, Activity Log, Jetpack Cloud, [Size] XS

#55214 Issue Templates: Add more granular fields for impact
  .github/ISSUE_TEMPLATE/happiness-bug-report.yml
Labels: [Status] Needs Review

#55142 Goodbye, IE 11
  config/production.json
  config/stage.json
  config/test.json
  docs/development-workflow.md
  docs/fallback-development-workflow.md
  docs/merge-checklist.md
Labels: [Status] Needs Review

#55296 Domains: Fix bulk email edit page
  client/components/domains/registrant-extra-info/ca-form.jsx
  client/my-sites/checkout/composite-checkout/components/contact-details-container.tsx
  client/my-sites/checkout/composite-checkout/components/domain-contact-details.tsx
Labels: [Status] Needs Review, Domains

#54524 desktop: fix devtools and zoom controls
  desktop/app/lib/menu/debug-menu.js
  desktop/app/lib/menu/view-menu.js
Labels: [Status] Needs Review

#55234 Fix how we render notices in the domain suggestion screen in signup
  client/components/domains/domain-search-results/index.jsx
  client/components/domains/featured-domain-suggestions/style.scss
  client/components/domains/register-domain-step/style.scss
Labels: [Status] Needs Review, Domains

#55318 Disable email step in signup
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Signup, Professional Email

#55249 Refactor titan mailbox and mailbox-list components
  client/my-sites/email/email-providers-comparison/index.jsx
  client/my-sites/email/titan-add-mailboxes/index.jsx
  client/my-sites/email/titan-add-mailboxes/style.scss
  client/my-sites/email/titan-new-mailbox-list/index.jsx
  client/my-sites/email/titan-new-mailbox-list/style.scss
  client/my-sites/email/titan-new-mailbox/index.jsx
  client/my-sites/email/titan-new-mailbox/style.scss
  client/my-sites/email/titan-setup-mailbox/titan-setup-mailbox-form.jsx
Labels: OSS Citizen

#55307 Emails: Fix warning not displayed in sidebar for Google Workspace accounts pending ToS acceptance
  client/my-sites/domains/components/domain-warnings/index.jsx
  client/my-sites/domains/components/domain-warnings/pending-gsuite-tos-notice.jsx
  client/my-sites/email/email-management/titan-manage-mailboxes/index.jsx
Labels: [Status] Needs Review, G Suite, Professional Email

#55302 Shopping Cart: Add refetchOnWindowFocus tests
  packages/shopping-cart/src/types.ts
  packages/shopping-cart/test/cart-actions.tsx
Labels: [Status] Needs Review

#55253 Playwright: migrate Support: Home spec.
  packages/calypso-e2e/src/lib/components/support-component.ts
  test/e2e/specs/specs-calypso/wp-inline-help-support-search-spec.js
  test/e2e/specs/specs-calypso/wp-my-home-support-search-spec.js
  test/e2e/specs/specs-playwright/wp-support__home-spec.ts
  test/e2e/specs/specs-playwright/wp-support__popover-spec.js
Labels: [Status] Needs Review

#55164 Fix/update the Tracks 'checkout_flow' prop to accomodate siteless checkout
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-checkout-flow-track-key.ts
  client/my-sites/checkout/controller.jsx
Labels: [Status] Needs Review, Checkout

#54649 Domains: Update domain item list layout
  client/components/popover/menu.jsx
  client/lib/domains/get-domain-type-text.js
  client/lib/domains/resolve-domain-status.js
  client/my-sites/domains/domain-management/components/domain-notice/index.jsx
  client/my-sites/domains/domain-management/components/domain-notice/style.scss
  client/my-sites/domains/domain-management/list/add-domain-button.jsx
  client/my-sites/domains/domain-management/list/domain-item.jsx
  client/my-sites/domains/domain-management/list/empty-domains-list-card.jsx
  client/my-sites/domains/domain-management/list/index.jsx
  client/my-sites/domains/domain-management/list/list-all.jsx
  client/my-sites/domains/domain-management/list/list-header.jsx
  client/my-sites/domains/domain-management/list/style.scss
  client/my-sites/domains/domain-management/list/test/index.js
  test/e2e/lib/pages/domains-page.js
Labels: [Status] Needs Review, Domains

#55295 Jetpack Activity Log: Move backup/restore from ellipsis menu to buttons
  client/my-sites/activity/activity-log-item/index.jsx
  client/my-sites/activity/activity-log-item/style.scss
Labels: [Status] Needs Review, [Pod] Flow Patrol (Manage)

#55162 Add conflicting themes list, which prefer to fetch info from jetpack
  client/components/data/query-canonical-theme/index.jsx
  client/state/themes/selectors/get-canonical-theme.js
Labels: [Status] Needs Review, [Pod] Flow Patrol (Manage)

#54685 Introduce a new connect a domain flow
  client/assets/images/illustrations/domain-connected.svg
  client/components/domains/connect-domain-step/connect-domain-step-advanced-records.jsx
  client/components/domains/connect-domain-step/connect-domain-step-advanced-start.jsx
  client/components/domains/connect-domain-step/connect-domain-step-clipboard-button.jsx
  client/components/domains/connect-domain-step/connect-domain-step-done.jsx
  client/components/domains/connect-domain-step/connect-domain-step-login.jsx
  client/components/domains/connect-domain-step/connect-domain-step-progress.jsx
  client/components/domains/connect-domain-step/connect-domain-step-suggested-records.jsx
  client/components/domains/connect-domain-step/connect-domain-step-suggested-start.jsx
  client/components/domains/connect-domain-step/connect-domain-step-support-info-link.jsx
  client/components/domains/connect-domain-step/connect-domain-step-switch-setup-info-link.jsx
  client/components/domains/connect-domain-step/connect-domain-step-verification-error-notice.jsx
  client/components/domains/connect-domain-step/connect-domain-step-verification-status-parsing.js
  client/components/domains/connect-domain-step/connect-domain-step-wrapper.jsx
  client/components/domains/connect-domain-step/constants.jsx
  client/components/domains/connect-domain-step/index.jsx
  client/components/domains/connect-domain-step/page-definitions.jsx
  client/components/domains/connect-domain-step/style.scss
  client/components/domains/domain-transfer-recommendation/index.jsx
  client/components/domains/domain-transfer-recommendation/style.scss
  client/lib/url/support.js
  client/my-sites/domains/controller.jsx
  client/my-sites/domains/index.js
  client/my-sites/domains/paths.js
  packages/wpcom.js/src/lib/domain.js
Labels: [Status] Needs Review, Domains

#55336 Desktop CI: Use calypso.live
  .teamcity/_self/projects/DesktopApp.kt
Labels: [Status] Needs Review

#55260 Playwright: migrate the `Import Site` spec.
  packages/calypso-e2e/src/lib/pages/index.ts
  packages/calypso-e2e/src/lib/pages/site-import-page.ts
  test/e2e/specs/specs-playwright/wp-site-import__verify-spec.ts
Labels: [Status] Needs Review

#55278 Fix focusOnHover doesn't work on CopyLink
  client/components/popover/menu-item-clipboard.jsx
Labels: [Status] Needs Review

#55292 Tooling/Building CalypsO: Bump `sharp` dependency version to 0.28 to allow building of Calypso on M1 macs
  package.json
  yarn.lock
Labels: [Type] Bug, [Status] Needs Review, [Type] Tooling

#55201 Signup - Fix wrong props used in user step component methods
  client/signup/steps/user/index.jsx
Labels: [Status] Needs Review, Signup, Login

#54716 P2: customize Join screen
  client/assets/stylesheets/_p2-vars.scss
  client/my-sites/invites/invite-accept-logged-in/index.jsx
  client/my-sites/invites/invite-accept-logged-out/index.jsx
  client/my-sites/invites/invite-accept/index.jsx
  client/my-sites/invites/p2/invite-accept-footer.jsx
  client/my-sites/invites/p2/invite-accept-header.jsx
  client/my-sites/invites/p2/invite-accept-logged-in.jsx
  client/my-sites/invites/p2/invite-accept-logged-out.jsx
  client/my-sites/invites/p2/style.scss
Labels: [Status] Ready to Merge

#55284 Show less domain suggestions if the customer entered a FQDN that is available
  client/components/domains/domain-search-results/index.jsx
  client/components/domains/featured-domain-suggestions/index.jsx
  client/components/domains/register-domain-step/index.jsx
  client/components/domains/register-domain-step/utility.js
Labels: [Status] Needs Review, Domains

#55158 Update eslint-branch tool to support --fix flag and deleted files
  bin/eslint-branch.js
Labels: [Status] Needs Review, [Type] Tooling

#55373 fix(browsehappy): ensure `from` is a valid url
  client/landing/browsehappy/index.jsx
Labels: [Pri] High, [Status] Needs Review, Security

#55368 Create new onboarding-with-email signup flow
  client/signup/config/flows-pure.js
  config/_shared.json
Labels: [Status] Ready to Merge, Signup, Professional Email

#55280 Ensure we query for products from email comparison
  client/my-sites/email/email-providers-comparison/index.jsx
Labels: [Status] Needs Review, [Status] Ready to Merge, Email management

#55250 Purchase Redirect: Consider active jetpack plugins when redirecting
  client/components/jetpack/sidebar/index.jsx
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-complete-callback.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
  client/state/sites/selectors/get-jetpack-checkout-redirect-url.js
  client/state/sites/selectors/get-site-admin-page.js
  client/state/sites/selectors/index.js
  client/state/sites/selectors/is-backup-plugin-active.js
Labels: [Status] Needs Review

#55382 Update jetpack activity log padding
  client/my-sites/activity/activity-log-item/style.scss
Labels: [Status] Needs Review, [Pod] Flow Patrol (Manage)

#55324 Use Full Jetpack Filter to only manage site with the Full Plugin in Calypso
  client/state/sites/test/actions.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Jetpack, [Status] Needs Review

#55341 Playwright: remove spec `wp-import-site` from Selenium.
  test/e2e/specs/specs-calypso/wp-import-site-spec.js
Labels: [Status] Needs Review

#55179 Playwright: implement Site Selector.
  packages/calypso-e2e/src/data-helper.ts
  packages/calypso-e2e/src/lib/components/index.ts
  packages/calypso-e2e/src/lib/components/site-select-component.ts
  test/e2e/specs/specs-playwright/wp-theme__details-preview-activate.js
  test/e2e/specs/specs-playwright/wp-theme__popover-preview.js
Labels: [Status] Needs Review

#55209 Add new 'Use a domain I own' page
  client/assets/images/illustrations/domain.svg
  client/components/domains/use-my-domain/index.jsx
  client/components/domains/use-my-domain/style.scss
  client/lib/domains/registration/availability-messages.js
  client/my-sites/domains/controller.jsx
  client/my-sites/domains/index.js
  client/my-sites/domains/paths.js
Labels: [Status] Needs Review, Domains

#54988 Playwright: update documentation
  test/e2e/README.md
  test/e2e/docs/overview.md
  test/e2e/docs/setup.md
  test/e2e/docs/style-guide-playwright.md
  test/e2e/docs/style-guide-selenium.md
  test/e2e/docs/style-guide.md
  test/e2e/docs/writing_tests.md
Labels: [Status] Needs Review

#55206 Backup: Display when the site's retention period limit has been reached
  client/components/activity-card-list/retention-limit-upsell/index.tsx
  client/components/jetpack/daily-backup-status/index.jsx
  client/components/jetpack/daily-backup-status/status-card/beyond-retention-period.tsx
  client/components/jetpack/daily-backup-status/status-card/style.scss
  client/my-sites/backup/backup-date-picker/hooks.ts
  client/my-sites/backup/backup-date-picker/index.tsx
  client/my-sites/backup/backup-date-picker/test/hooks.js
  client/my-sites/backup/hooks.js
  client/my-sites/backup/status/index.jsx
Labels: [Type] Enhancement, [Status] Needs Review, [Status] Needs Design Review, [Size] S, Jetpack Cloud, Jetpack Backup, [Status] Design Input Requested

#55298 Activity Log: Limit visible Activities + add an upsell for Calypso Blue
  client/components/activity-card-list/index.jsx
  client/components/activity-card-list/retention-limit-upsell/index.tsx
  client/components/activity-card-list/retention-limit-upsell/style.scss
  client/my-sites/activity/activity-log/index.jsx
  client/state/selectors/get-site-activity-log-retention-policy-request-status.ts
Labels: [Type] Enhancement, [Status] Needs Review, [Status] Needs Design Review, [Size] S, Activity Log, [Status] Design Input Requested

#55338 Domains: Remove "Manage all your domains" card
  client/my-sites/domains/domain-management/list/index.jsx
Labels: Domains

#55254 Domains: Update domain search empty state and input placeholder
  client/components/domains/register-domain-step/index.jsx
  client/components/domains/register-domain-step/search.jsx
Labels: [Status] Needs Review, Domains

#55396 Temporarily remove continue anyways
  client/landing/browsehappy/index.jsx
Labels: [Status] Needs Review

#55334 Playwright: migrate Media Blocks (Upload) spec.
  packages/calypso-e2e/src/lib/blocks/audio-block.ts
  packages/calypso-e2e/src/lib/blocks/file-block.ts
  packages/calypso-e2e/src/lib/blocks/image-block.ts
  packages/calypso-e2e/src/lib/blocks/index.ts
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
  packages/calypso-e2e/src/media-helper.ts
  test/e2e/specs/specs-playwright/wp-blocks__media-spec.ts
Labels: [Status] Needs Review

#55034 Domains: Update domain suggestions cards layout
  client/components/domains/domain-product-price/index.jsx
  client/components/domains/domain-product-price/style.scss
  client/components/domains/domain-registration-suggestion/index.jsx
  client/components/domains/domain-suggestion/index.jsx
  client/components/domains/domain-suggestion/style.scss
  client/components/domains/featured-domain-suggestions/index.jsx
  client/components/domains/featured-domain-suggestions/placeholder.jsx
  client/components/domains/featured-domain-suggestions/placeholder.scss
  client/components/domains/featured-domain-suggestions/style.scss
  client/my-sites/domains/domain-search/index.jsx
  test/e2e/lib/components/find-a-domain-component.js
  test/e2e/lib/pages/domains-page.js
Labels: [Status] Needs Review, Domains

#55262 Jetpack site-less Checkout: trigger ticket update from `ThankYouCompleted` page after scheduling call
  client/my-sites/checkout/checkout-thank-you/hooks.ts
  client/my-sites/checkout/checkout-thank-you/jetpack-checkout-siteless-thank-you-completed.tsx
  client/my-sites/checkout/checkout-thank-you/jetpack-checkout-siteless-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/utils.js
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
  client/my-sites/checkout/controller.jsx
Labels: Jetpack, [Status] Needs Review, [Size] S

#54646 Login: use redesigned page for reskin
  client/blocks/login/index.jsx
  client/blocks/login/login-form.jsx
  client/blocks/login/social.jsx
  client/blocks/login/style.scss
  client/layout/logged-out.jsx
  client/lib/login/index.js
  client/lib/login/test/index.js
  client/lib/paths/login/index.js
  client/lib/url/http-utils.ts
  client/login/magic-login/index.jsx
  client/login/magic-login/style.scss
  client/login/wp-login/index.jsx
  client/login/wp-login/login-links.jsx
  client/login/wp-login/style.scss
  client/signup/steps/user/index.jsx
Labels: [Status] Needs Review, Signup, Login

#55312 Emails: Show labels in add mailbox in Google Workspace
  client/components/gsuite/gsuite-new-user-list/index.tsx
  client/components/gsuite/gsuite-new-user-list/new-user.tsx
  client/components/gsuite/gsuite-new-user-list/style.scss
  client/my-sites/email/email-providers-comparison/index.jsx
Labels: [Status] Needs Review

#55378 Add Reader Featured image alt text
  client/blocks/reader-full-post/featured-image.jsx
  client/blocks/reader-full-post/index.jsx
  client/reader/get-helpers.js
Labels: [Status] Needs Review, Reader

#55301 Sharing Buttons: Update private site notice
  client/my-sites/marketing/buttons/tray.jsx
  client/my-sites/marketing/style.scss
Labels: Sharing, [Status] Needs Review

#55450 Signup: Update other log-in URLs to link to the reskinned pages
  client/blocks/signup-form/index.jsx
Labels: [Status] Needs Review, Signup, Login
