Repository Automattic/wp-calypso, pull requests merged in 2021-05, with the labels that each got.

#52054 create `useProtectForm` custom hook
  client/lib/protect-form/index.tsx
  client/me/account-password/index.jsx
  client/my-sites/people/edit-team-member-form/index.jsx
  client/state/data-layer/wpcom/me/settings/index.js
Labels: [Status] Needs Review

#52447 P2: add more tracking
  client/my-sites/people/invite-people/index.jsx
  client/signup/steps/p2-details/index.jsx
Labels: [Status] Needs Review

#52459 Reorganize constants in calypso-products package
  client/my-sites/plan-features/index.jsx
  client/my-sites/plans/jetpack-plans/plans-header.tsx
  packages/calypso-products/src/constants/domain.ts
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/constants/google.ts
  packages/calypso-products/src/constants/index.ts
  packages/calypso-products/src/constants/jetpack.ts
  packages/calypso-products/src/constants/store.ts
  packages/calypso-products/src/constants/terms.ts
  packages/calypso-products/src/constants/titan.ts
  packages/calypso-products/src/constants/types.ts
  packages/calypso-products/src/constants/wpcom.ts
  packages/calypso-products/src/plans-utilities.js
Labels: [Size] S, [Status] Needs Review

#52169 Display email forward details in new email pages
  client/lib/emails/email-provider-constants.js
  client/lib/emails/get-email-forward-address.js
  client/lib/emails/index.js
  client/lib/emails/is-email-forward-verified.js
  client/lib/emails/is-email-forward.js
  client/my-sites/email/email-management/home/email-plan-mailboxes-list.jsx
  client/my-sites/email/email-management/home/email-plan.jsx
  client/my-sites/email/email-management/style.scss
Labels: [Status] Needs Review

#52382 Enable Jetpack legacy plan redirect in production
  config/jetpack-cloud-production.json
  config/production.json
Labels: Jetpack, Plans, [Size] XS, [Status] Needs Review

#52420 Checkout: Include additional information in the introductory offers terms of service
  client/lib/url/support.js
  client/my-sites/checkout/composite-checkout/components/additional-terms-of-service-in-cart.tsx
Labels: Checkout, [Status] Ready to Merge

#52516 Checkout: Format tax postalCode for transactions endpoint
  client/my-sites/checkout/composite-checkout/lib/free-purchase-processor.ts
  client/my-sites/checkout/composite-checkout/lib/paypal-express-processor.ts
  client/my-sites/checkout/composite-checkout/lib/translate-cart.ts
  client/my-sites/checkout/composite-checkout/test/apple-pay-processor.ts
  client/my-sites/checkout/composite-checkout/test/existing-card-processor.ts
  client/my-sites/checkout/composite-checkout/test/free-purchase-processor.ts
  client/my-sites/checkout/composite-checkout/test/full-credits-processor.ts
  client/my-sites/checkout/composite-checkout/test/generic-redirect-processor.ts
  client/my-sites/checkout/composite-checkout/test/multi-partner-card-processor.ts
  client/my-sites/checkout/composite-checkout/test/paypal-express-processor.ts
  client/my-sites/checkout/composite-checkout/test/we-chat-processor.ts
Labels: Checkout, [Estimate] 1, [Status] Ready to Merge

#52475 Checkout: Format postalCode in TaxFields
  client/my-sites/checkout/composite-checkout/components/contact-details-container.tsx
  client/my-sites/checkout/composite-checkout/components/tax-fields.tsx
Labels: [Estimate] 1, [Status] Ready to Merge

#52440 desktop: Bump version to 6.14.0
  desktop/package.json
Labels: Releases, [Status] Needs Review

#52470 Update .teamcity/ codeowners
  .github/CODEOWNERS
Labels: [Status] Needs Review

#52469 Remove unused ETK files
  apps/editing-toolkit/.eslintrc.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/tests/fse-back-button.spec.js
  apps/editing-toolkit/editing-toolkit-plugin/e2e-test-helpers/activate-theme.js
  apps/editing-toolkit/editing-toolkit-plugin/e2e-test-helpers/index.js
  apps/editing-toolkit/editing-toolkit-plugin/whats-new/src/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-modal/images/block.svg
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/disable-core-nux.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/images/block-picker.svg
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/images/block.svg
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/images/editor.svg
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/images/finish.png
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/images/preview.svg
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/images/private.svg
  apps/editing-toolkit/jest.config.js
  apps/editing-toolkit/package.json
  yarn.lock
Labels: Editing Toolkit, [Status] Needs Review

#52514 Update Link to Support Doc on Jetpack's Skip User Page
  client/blocks/jetpack-connect-skip-user/index.js
Labels: Jetpack, [Status] Needs Author Reply, [Status] Needs Review

#52436 Block patterns: use source site slug to create cache key
  apps/editing-toolkit/editing-toolkit-plugin/block-patterns/class-block-patterns-from-api.php
Labels: Editing Toolkit, [Status] Needs Review

#52508 ci(circleci): Delete unused CircleCI jobs
  .circleci/config.yml
Labels: [Status] Needs Review

#52503 chore(eslint): Fix `import/no-duplicates`
  .eslintrc.js
  client/components/date-range/trigger.tsx
  client/components/jetpack/backup-card/backup-failed.tsx
  client/components/jetpack/backup-card/backup-scheduled.tsx
  client/components/jetpack/backup-card/index.tsx
  client/components/jetpack/backup-card/no-backups-on-selected-date.tsx
  client/components/jetpack/backup-card/no-backups-yet.tsx
  client/components/seo-preview-pane/utils.ts
  client/my-sites/checkout/composite-checkout/components/checkout-help-link.tsx
  client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-prepare-products-for-cart.ts
  client/my-sites/checkout/composite-checkout/lib/get-plan-features.ts
  client/my-sites/earn/home.tsx
  client/my-sites/jetpack-search/main.tsx
  client/my-sites/migrate/step-import-or-migrate.jsx
  client/my-sites/plans-features-main/plan-type-selector.tsx
  client/my-sites/plans/current-plan/jetpack-checklist/index.tsx
  client/my-sites/plans/jetpack-plans/product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-grid/index.tsx
  client/my-sites/plans/jetpack-plans/product-grid/utils.ts
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
  client/my-sites/plans/jetpack-plans/utils.ts
  client/my-sites/site-settings/seo-settings/utils.ts
  client/my-sites/site-settings/utils.ts
  client/state/partner-portal/partner/handlers.ts
  client/state/sites/products/conflicts.ts
  packages/composite-checkout/src/components/checkout-submit-button.tsx
  packages/domain-picker/src/components/domain-suggestion-item/suggestion-item.tsx
  packages/explat-client/src/internal/requests.ts
  packages/launch/src/focused-launch/index.tsx
  packages/launch/src/hooks/use-domain-search.ts
  packages/launch/src/utils.ts
Labels: [Status] Needs Review

#52490 chore(eslint): Fix violations of import/default
  client/state/selectors/test/get-active-discount.js
  client/state/selectors/test/is-site-google-my-business-eligible.js
  packages/webpack-config-flag-plugin/test/fixtures/.eslintrc.js
  packages/wpcom.js/.eslintrc.js
Labels: [Status] Needs Review

#52392 ExPlat: Use memoized anonId in LocalStorage
  packages/explat-client/CHANGELOG.md
  packages/explat-client/src/internal/experiment-assignment-store.ts
  packages/explat-client/src/internal/local-storage.ts
  packages/explat-client/src/internal/requests.ts
  packages/explat-client/src/internal/test/experiment-assignment-store.ts
  packages/explat-client/src/internal/test/requests.ts
  packages/explat-client/src/test/create-explat-client.ts
Labels: [Status] Needs Review

#52512 Sidebar nudge: fix bg color in contrast color scheme.
  client/my-sites/sidebar-unified/style.scss
Labels: [Status] Needs Review

#52517 Emails: Remove old Email Comparison page
  client/my-sites/email/email-management/index.jsx
  client/my-sites/email/email-providers-comparison/email-provider-details/email-provider-feature.jsx
  client/my-sites/email/email-providers-comparison/email-provider-details/index.jsx
  client/my-sites/email/email-providers-comparison/email-provider-details/style.scss
  client/my-sites/email/email-providers-comparison/index.jsx
  client/my-sites/email/email-providers-comparison/style.scss
Labels: Email Product, G Suite, [Status] Needs Review

#52518 Titan: Remove old Add New Mailboxes page
  client/my-sites/email/controller.js
  client/my-sites/email/titan-mail-quantity-selection/index.jsx
  client/my-sites/email/titan-mail-quantity-selection/style.scss
Labels: Email Product, [Status] Needs Review

#52419 Framework: Refactor away from _.isObjectLike()
  apps/wpcom-block-editor/src/wpcom/features/tracking/track-record-event.js
  client/my-sites/site-settings/wrap-settings-form.jsx
  client/state/data-layer/utils.js
  packages/calypso-analytics/src/tracks.ts
Labels: Framework, [Status] Needs Review, [Type] Enhancement, [Type] Janitorial

#52545 Remove unused helpers from lib/paths
  client/lib/paths/index.js
  client/lib/paths/test/index.js
Labels: [Status] Needs Review, [Type] Janitorial

#52425 E2E: Make screenSize prop case consistent
  test/e2e/lib/async-base-container.js
  test/e2e/lib/components/inline-help-checklist-component.js
  test/e2e/lib/components/site-preview-component.js
  test/e2e/lib/pages/gutenboarding/style-preview-page.js
  test/e2e/lib/pages/plans-page.js
  test/e2e/lib/pages/profile-page.js
Labels: [Status] Needs Review

#52509 Emails: Hide trash button of first user/mailbox in Add New Users and Add New Mailboxes forms
  client/components/gsuite/gsuite-learn-more/test/__snapshots__/index.js.snap
  client/components/gsuite/gsuite-new-user-list/index.tsx
  client/components/gsuite/gsuite-new-user-list/new-user.tsx
  client/components/gsuite/gsuite-new-user-list/style.scss
  client/lib/url/support.js
  client/my-sites/email/titan-mail-add-mailboxes/style.scss
  client/my-sites/email/titan-mail-add-mailboxes/titan-new-mailbox-list.jsx
  client/my-sites/email/titan-mail-add-mailboxes/titan-new-mailbox.jsx
  config/wpcalypso.json
Labels: Email Product, G Suite, [Status] Needs Review

#52557 Remove the jetpackReverseFeaturedProducts test, resetting to the control variation
  client/lib/abtest/active-tests.js
  client/my-sites/plans/jetpack-plans/iterations.ts
  client/my-sites/plans/jetpack-plans/product-grid/products-order.ts
Labels: ABTest, Jetpack Cloud, Plans, [Size] XS, [Status] Needs Review, [Type] Task

#52550 Emails: Refactor components from Email Comparison page
  client/my-sites/email/email-management/email-home.jsx
  client/my-sites/email/email-management/index.jsx
  client/my-sites/email/email-provider-features/index.js
  client/my-sites/email/email-provider-features/list.js
  client/my-sites/email/email-provider-features/style.scss
  client/my-sites/email/email-providers-comparison/email-provider-card.jsx
  client/my-sites/email/email-providers-comparison/index.jsx
  client/my-sites/email/email-providers-comparison/style.scss
Labels: Email Product, G Suite, [Status] Needs Review

#52536 Theme Showcase: Decode Entities on Screenshot Alt Text
  client/components/theme/index.jsx
Labels: OSS Citizen

#52465 Refactor types in `calypso-products`
  client/my-sites/plans/jetpack-plans/utils.ts
  packages/calypso-products/src/constants/jetpack.ts
  packages/calypso-products/src/is-jetpack-legacy-item.ts
  packages/calypso-products/src/is-jetpack-purchasable-item.ts
  packages/calypso-products/src/product-values-types.ts
  packages/calypso-products/src/products-list.ts
  packages/calypso-products/src/types.ts
Labels: [Size] S, [Status] Needs Review

#52523 Removed unused Jetpack legacy plan code in jetpack connect
  client/jetpack-connect/main-header.jsx
  client/jetpack-connect/main.jsx
Labels: Jetpack, Plans, [Size] XS, [Status] Needs Review

#52553 Make test resilient to stale element reference errors
  test/e2e/lib/driver-helper.js
Labels: [Status] Needs Review

#52534 Rename calypso products types
  client/my-sites/plans/jetpack-plans/constants.ts
  client/my-sites/plans/jetpack-plans/plan-upgrade/types.ts
  client/my-sites/plans/jetpack-plans/plan-upgrade/utils.ts
  client/my-sites/plans/jetpack-plans/product-grid/index.tsx
  client/my-sites/plans/jetpack-plans/product-grid/products-order.ts
  client/my-sites/plans/jetpack-plans/utils.ts
  packages/calypso-products/src/is-jetpack-legacy-item.ts
  packages/calypso-products/src/types.ts
Labels: [Size] XS, [Status] Needs Review

#52454 Jetpack Search: Show Correct Information if Disabled
  client/my-sites/jetpack-search/main.tsx
Labels: Jetpack Search, OSS Citizen, [Status] Needs Review

#52467 Update stalebot workflow definition to include PRs.
  .github/workflows/mark-issue-stale.yml
Labels: [Status] Needs Review

#52006 Improve Gutenframe redirect handling
  client/gutenberg/editor/calypsoify-iframe.tsx
Labels: [Status] Needs Review

#52441 Gutenboarding/new/design: Uniform hover-scroll speed
  packages/design-picker/src/components/mshots-image/index.tsx
  packages/design-picker/src/components/mshots-image/style.scss
Labels: [Goal] New Onboarding, [Status] Needs Review

#52569 E2E: Ignore notice when applying coupon
  test/e2e/lib/components/secure-payment-component.js
Labels: Flaky e2e, [Status] Needs Review

#52572 E2E: gitignore all *.log files
  test/e2e/.gitignore
Labels: [Status] Needs Review

#52559 Remove deprecated code in pricing page
  client/my-sites/plans/jetpack-plans/constants.ts
  client/my-sites/plans/jetpack-plans/types.ts
  client/my-sites/plans/jetpack-plans/utils.ts
Labels: Jetpack, Plans, [Size] XS, [Status] Needs Review

#52618 Remove code for deprecated Security and Backup options
  client/my-sites/plans/jetpack-plans/constants.ts
  client/my-sites/site-settings/analytics/form-google-analytics-jetpack.jsx
  client/my-sites/site-settings/seo-settings/test/form.jsx
  client/my-sites/site-settings/test/form-google-analytics.jsx
Labels: Jetpack, Plans, [Size] XS, [Status] Needs Review

#52305 Enable site-specific purchase paths for domain-only sites
  client/my-sites/controller.js
Labels: [Status] Needs Review

#52575 Jetpack Backup plugin skip the plans page on auth
  client/jetpack-connect/authorize.js
  client/jetpack-connect/test/authorize.js
Labels: Jetpack, [Status] Ready to Merge, [Type] Enhancement

#52391 Site Editor: revert to opening pages in the post editor
  client/gutenberg/editor/calypsoify-iframe.tsx
Labels: [Goal] Full Site Editing, [Status] Needs Review

#52183 E2E fixes for Gutenberg v10.5.x
  test/e2e/lib/gutenberg/blocks/image-block-component.js
  test/e2e/lib/gutenberg/blocks/layout-grid-block-component.js
  test/e2e/lib/gutenberg/gutenberg-editor-component.js
Labels: DO NOT MERGE, [Status] Needs e2e Testing Gutenberg Edge

#52099 Add links to last slide of welcome tour
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/class-wpcom-block-editor-nux.php
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/block-editor-nux.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-content.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.js
Labels: Editor Welcome, [Status] Needs Review

#52607 ci(teamcity): Schedule gutenberg e2e
  .teamcity/_self/projects/WPComTests.kt
Labels: [Status] Needs Review

#52634 Design Picker: skip flakey unit test
  packages/design-picker/src/utils/__tests__/available-designs.test.ts
Labels: Design Picker, Testing, [Status] Needs Review

#52515 Reader Sidebar: removes language & country restriction from upsell nudge.
  client/reader/sidebar/reader-sidebar-nudges/index.jsx
Labels: [Status] Needs Review

#52636 Analytics: Remove unused cart analytics functions
  client/lib/analytics/cart.js
  client/lib/analytics/test/cart.js
Labels: Analytics, Shopping Cart, [Status] Needs Review, [Type] Janitorial

#52570 Framework: Refactor away from `_.forOwn()`
  client/components/embed-container/index.jsx
  client/lib/post-normalizer/rule-decode-entities.js
  client/lib/post-normalizer/rule-safe-image-properties.js
  client/state/data-layer/wpcom/sites/activity-types/from-api.js
Labels: Framework, [Status] Needs Review, [Type] Enhancement, [Type] Janitorial

#52622 Lead users to Jetpack branded login form when coming from Jetpack's Pricing
  client/my-sites/plans/jetpack-plans/utils.ts
Labels: Jetpack, Jetpack Cloud, [Size] XS, [Status] Needs Review

#52640 Remove deprecated features code
  client/lib/plans/features-list.js
  client/my-sites/plans/jetpack-plans/constants.ts
  client/my-sites/plans/jetpack-plans/types.ts
  client/my-sites/plans/jetpack-plans/utils.ts
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/types.ts
Labels: Plans, [Size] S, [Status] Needs Review

#51285 Playwright: change browser management in BrowserManager.
  .teamcity/_self/projects/WebApp.kt
  packages/calypso-e2e/src/browser-manager.ts
  test/e2e/.mocharc_playwright.yml
  test/e2e/config/default.json
  test/e2e/lib/hooks-playwright/hooks.ts
  test/e2e/magellan-playwright.json
  test/e2e/specs-playwright/wp-log-in-out-spec.js
Labels: [Status] Needs Review

#52653 Fix tour on atomic sites due to get_blog_details check
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/class-wp-rest-wpcom-block-editor-nux-status-controller.php
Labels: [Impact] High, [Status] Needs Review, [Type] Bug

#52621 Emails: Add button to toggle list of features in Email Comparison page on mobile
  client/components/gsuite/gsuite-new-user-list/style.scss
  client/lib/titan/new-mailbox.js
  client/my-sites/email/email-provider-features/index.js
  client/my-sites/email/email-provider-features/style.scss
  client/my-sites/email/email-provider-features/toggle-button.js
  client/my-sites/email/email-providers-comparison/email-provider-card.jsx
  client/my-sites/email/email-providers-comparison/style.scss
Labels: Email Product, G Suite, [Status] Needs Review

#52660 Remove trailing whitespace below Google card in email comparison page
  client/my-sites/email/email-providers-comparison/style.scss
Labels: [Status] Needs Review

#52638 Checkout: Remove unused functions
  client/lib/checkout/constants.js
  client/lib/checkout/index.js
  client/lib/checkout/test/index.js
Labels: Checkout, [Status] Needs Review, [Type] Janitorial

#52558 Framework: Refactor away from `_.toArray()`
  client/lib/highlight/index.js
  client/lib/post-normalizer/rule-content-make-links-safe.js
  client/lib/post-normalizer/rule-create-better-excerpt.js
  client/my-sites/media-library/test/list.jsx
  client/state/posts/utils/get-term-ids-from-edits.js
  client/state/posts/utils/is-terms-equal.js
Labels: Framework, [Status] Needs Review, [Type] Enhancement, [Type] Janitorial

#52358 Plans redesign experiment wrap up: Remove code that references the experiment
  client/my-sites/plan-features-comparison/style.scss
  client/signup/steps/plans/index.jsx
  client/signup/steps/plans/style.scss
Labels: Plans, Signup, [Status] Needs Review

#52685 Adding FBSAVE25 Coupon to Whitelist
  client/my-sites/checkout/controller.jsx
Labels: [Status] Needs Review, [Team] MarTech

#52680 Add build and suite for gutenberg mobile tests
  .teamcity/_self/projects/WPComTests.kt
Labels: [Status] Needs Review

#52690 [TeamCity] Keep the previous Desktop screenSize builtType for its historical data
  .teamcity/_self/projects/WPComTests.kt
Labels: [Status] Needs Review

#52573 Jetpack Connection: track the "skip user connection" events
  client/blocks/jetpack-connect-skip-user/index.js
  client/blocks/login/login-form.jsx
  client/jetpack-connect/signup.js
Labels: Jetpack, [Status] Needs Review

#52662 Jetpack: add external link to Customizer sidebar item
  client/my-sites/sidebar/index.jsx
Labels: Jetpack, Navigation, [Status] Ready to Merge, [Type] Bug

#52668 Posts: Remove lib/post-metadata
  client/blocks/post-share/index.jsx
  client/blocks/sharing-preview-pane/utils.js
  client/components/seo-preview-pane/index.jsx
  client/lib/post-metadata/README.md
  client/lib/post-metadata/index.js
  client/lib/post-metadata/test/index.js
  client/my-sites/pages/page-card-info/index.jsx
Labels: Posts, Sharing, [Status] Needs Review, [Type] Enhancement, [Type] Janitorial

#52672 Framework: Get rid of impure-lodash
  client/lib/impure-lodash/README.md
  client/lib/impure-lodash/index.js
  client/lib/media/test/utils.js
  client/lib/media/utils/create-transient-media-id.js
  client/post-editor/media-modal/test/index.jsx
  client/state/data-layer/wpcom/concierge/initial/test/index.js
  client/state/data-layer/wpcom/concierge/schedules/appointments/book/test/index.js
  client/state/data-layer/wpcom/concierge/schedules/appointments/cancel/test/index.js
  client/state/data-layer/wpcom/concierge/schedules/appointments/detail/test/index.js
  client/state/data-layer/wpcom/concierge/schedules/appointments/reschedule/test/index.js
  client/state/notices/actions.ts
  client/state/notices/test/__snapshots__/actions.js.snap
  client/state/notices/test/actions.js
  client/state/partner-portal/licenses/test/handlers.js
Labels: Framework, [Status] Needs Review, [Type] Enhancement, [Type] Janitorial

#52548 OAuth Authorize flow: remove intermediate screen
  client/auth/connect.jsx
  client/auth/controller.js
  client/auth/index.js
  client/auth/style.scss
  client/boot/common.js
  client/sections.js
Labels: Login, [Status] Needs Review

#52703 Use uuid for gutenberg e2e tests
  .teamcity/_self/projects/WPComTests.kt
Labels: [Status] Ready to Merge

#52658 Try bail instead of mocha-steps
  test/e2e/.mocharc.yml
  test/e2e/lib/shared-steps/wp-signup-spec.js
  test/e2e/package.json
  test/e2e/scripts/jetpack/wp-jetpack-activate.js
  test/e2e/scripts/jetpack/wp-jetpack-deactivate.js
  test/e2e/scripts/jetpack/wp-jetpack-jn-activate.js
  test/e2e/specs-gutenberg/wp-calypso-gutenberg-blocks-spec.js
  test/e2e/specs-gutenberg/wp-calypso-gutenberg-checkout-spec.js
  test/e2e/specs-gutenberg/wp-calypso-gutenberg-coblocks-spec.js
  test/e2e/specs-gutenberg/wp-calypso-gutenberg-editor-tracking-spec.js
  test/e2e/specs-gutenberg/wp-calypso-gutenberg-focused-launch-spec.js
  test/e2e/specs-gutenberg/wp-calypso-gutenberg-page-editor-spec.js
  test/e2e/specs-gutenberg/wp-calypso-gutenberg-post-editor-spec.js
  test/e2e/specs-gutenberg/wp-calypso-gutenberg-upgrade-spec.js
  test/e2e/specs-gutenberg/wp-comments-spec.js
  test/e2e/specs-gutenberg/wp-gutenberg-experimental-features-spec.js
  test/e2e/specs-i18n/logged-out-redirect-i18n-spec.js
  test/e2e/specs-jetpack-calypso/wp-jetpack-connect-spec.js
  test/e2e/specs-jetpack-calypso/wp-jetpack-plans-spec.js
  test/e2e/specs-jetpack-calypso/wp-jetpack-plugins-spec.js
  test/e2e/specs-jetpack-calypso/wp-jetpack-settings-writing-media-spec.js
  test/e2e/specs-jetpack-calypso/wp-pressable-nux-spec.js
  test/e2e/specs-playwright/wp-log-in-out-spec.js
  test/e2e/specs/wp-calypso-seo-preview.js
  test/e2e/specs/wp-gutenboarding-spec.js
  test/e2e/specs/wp-import-site-spec.js
  test/e2e/specs/wp-inline-help-support-search-spec.js
  test/e2e/specs/wp-invite-users-spec.js
  test/e2e/specs/wp-launch-spec.js
  test/e2e/specs/wp-likes-spec.js
  test/e2e/specs/wp-log-in-out-spec.js
  test/e2e/specs/wp-manage-domains-spec.js
  test/e2e/specs/wp-media-editor-spec.js
  test/e2e/specs/wp-media-upload-spec.js
  test/e2e/specs/wp-my-home-support-search-spec.js
  test/e2e/specs/wp-notifications-spec.js
  test/e2e/specs/wp-plan-purchase-spec.js
  test/e2e/specs/wp-reader-spec.js
  test/e2e/specs/wp-signup-spec.js
  test/e2e/specs/wp-site-editor-spec.js
  test/e2e/specs/wp-ssr-spec.js
  test/e2e/specs/wp-stats-insights-spec.js
  test/e2e/specs/wp-theme-multisite-spec.js
  test/e2e/specs/wp-theme-switch-spec.js
  yarn.lock
Labels: [Status] Needs Review

#52673 Framework: Refactor away from `_.uniqueId()`
  client/components/forms/range/index.jsx
  client/components/search/index.jsx
  client/extensions/woocommerce/state/data-layer/request/actions.js
  client/layout/sidebar/expandable.jsx
  client/lib/form-state/index.js
  client/state/terms/actions.js
Labels: Framework, [Status] Needs Review, [Type] Enhancement, [Type] Janitorial

#52627 Checkout: Extract web pay mechanisms from Apple Pay
  client/lib/checkout/processor-specific.js
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-methods/index.ts
  client/my-sites/checkout/composite-checkout/hooks/use-is-apple-pay-available.ts
  client/my-sites/checkout/composite-checkout/lib/filter-appropriate-payment-methods.ts
  client/my-sites/checkout/composite-checkout/lib/is-payment-method-enabled.ts
  client/my-sites/checkout/composite-checkout/lib/translate-payment-method-names.ts
  client/my-sites/checkout/composite-checkout/lib/web-pay-processor.ts
  client/my-sites/checkout/composite-checkout/record-analytics.js
  client/my-sites/checkout/composite-checkout/test/translate-cart.js
  client/my-sites/checkout/composite-checkout/test/web-pay-processor.ts
  packages/calypso-stripe/src/index.tsx
  packages/wpcom-checkout/src/index.ts
  packages/wpcom-checkout/src/payment-methods/apple-pay.tsx
  packages/wpcom-checkout/src/payment-methods/web-pay-utils.tsx
  packages/wpcom-checkout/src/types.ts
  packages/wpcom-checkout/src/use-is-web-payment-available.ts
Labels: Checkout, [Estimate] 3, [Status] Needs Review

#52678 Add eslint rule on maximum top level suites in a spec file.
  .eslintrc.js
Labels: [Status] Needs Review

#52629 Fix Jetpack product grid translations
  client/my-sites/plans/jetpack-plans/product-grid/index.tsx
  packages/calypso-products/src/plans-list.js
Labels: Jetpack, Plans, [Status] Needs Review, i18n

#52708 My Home: Fix spacing on "go mobile" task between action button and skip
  client/my-sites/customer-home/cards/tasks/task.jsx
Labels: Customer Home, My Home Pod, [Status] Needs Review

#52734 ci(e2e): Do not install custom chrome version
  .teamcity/_self/projects/WebApp.kt
Labels: [Status] Needs Review

#52699 ci(e2e): Use test name for assets path
  packages/magellan-mocha-plugin/lib/test_run.js
  packages/magellan-mocha-plugin/package.json
  packages/magellan-mocha-plugin/test/test_run.spec.js
Labels: [Status] Needs Review

#52675 ExPlat: Add message to logStash properties
  client/lib/explat/internals/log-error.ts
  client/lib/explat/internals/test/log-error.ts
Labels: [Status] Needs Review

#52295 Design Picker: add FSE-enabled blank canvas option
  packages/design-picker/src/available-designs-config.json
Labels: Design Picker, Signup, [Goal] Full Site Editing, [Goal] New Onboarding, [Goal] Onboarding, [Status] In Progress

#52715 Layout: makes wide layout full width.
  client/components/main/style.scss
  client/extensions/woocommerce/app/dashboard/index.js
  client/extensions/woocommerce/app/store-stats/index.js
  client/jetpack-cloud/sections/partner-portal/primary/billing-dashboard/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/licenses/index.tsx
  client/me/account/main.jsx
  client/me/connected-applications/index.jsx
  client/me/memberships/main.jsx
  client/me/memberships/subscription.jsx
  client/me/notification-settings/comment-settings/index.jsx
  client/me/notification-settings/main.jsx
  client/me/notification-settings/reader-subscriptions/index.jsx
  client/me/notification-settings/wpcom-settings/index.jsx
  client/me/pending-payments/index.jsx
  client/me/privacy/main.jsx
  client/me/profile/index.jsx
  client/me/purchases/add-new-payment-method/index.jsx
  client/me/purchases/billing-history/main.tsx
  client/me/purchases/billing-history/receipt.jsx
  client/me/purchases/components/loading-placeholder/index.jsx
  client/me/purchases/controller.jsx
  client/me/purchases/payment-methods/main.tsx
  client/me/purchases/purchases-list/index.jsx
  client/me/security-account-recovery/index.jsx
  client/me/security-checkup/index.jsx
  client/me/security/main.jsx
  client/me/site-blocks/main.jsx
  client/me/social-login/index.jsx
  client/me/two-step/index.jsx
  client/my-sites/customer-home/main.jsx
  client/my-sites/earn/main.jsx
  client/my-sites/hosting/main.js
  client/my-sites/plans/main.jsx
  client/my-sites/purchases/billing-history/index.tsx
  client/my-sites/purchases/main.tsx
  client/my-sites/purchases/payment-methods/index.tsx
  client/my-sites/purchases/subscriptions/index.tsx
  client/my-sites/stats/comment-follows/index.jsx
  client/my-sites/stats/site.jsx
  client/my-sites/stats/summary/index.jsx
  client/my-sites/stats/wordads/index.jsx
  client/my-sites/themes/single-site-jetpack.jsx
  client/my-sites/themes/single-site-wpcom.jsx
Labels: [Status] Needs Review

#52748 Reverts wide layout to 1040px.
  client/components/main/style.scss
Labels: [Status] Needs Review

#49608 New onboarding: re-enable Reynolds design
  packages/design-picker/src/available-designs-config.json
Labels: Signup, [Goal] New Onboarding, [Status] Needs Rebase, [Status] Needs Review

#52679 Delete superfluous condition in Jetpack product card button `isDisabled` prop
  client/components/jetpack/card/jetpack-product-card/index.tsx
Labels: Jetpack, Plans, [Status] Needs Review

#52723 Update E2E Documentation.
  test/e2e/README.md
  test/e2e/docs/config.md
  test/e2e/docs/overview.md
  test/e2e/docs/running-tests.md
  test/e2e/docs/setup.md
  test/e2e/docs/troubleshooting.md
Labels: [Status] Ready to Merge

#52751 Create mocha-debug-reporter
  .teamcity/_self/projects/WebApp.kt
  packages/magellan-mocha-plugin/lib/test_run.js
  packages/magellan-mocha-plugin/test/test_run.spec.js
  packages/mocha-debug-reporter/.eslintrc.js
  packages/mocha-debug-reporter/package.json
  packages/mocha-debug-reporter/src/index.ts
  packages/mocha-debug-reporter/tsconfig.json
  test/e2e/mocha-reporter.json
  test/e2e/package.json
  yarn.lock
Labels: [Status] Needs Review

#52709 Framework: Refactor away from `_.invoke()`
  client/blocks/inline-help/inline-help-compact-result.jsx
  client/signup/steps/import-url-onboarding/index.jsx
  client/signup/steps/import-url/index.jsx
Labels: Framework, [Status] Needs Review, [Type] Enhancement, [Type] Janitorial

#52714 State: Remove unused `getMenuItemTypes` selector
  client/state/selectors/get-menu-item-types.js
  client/state/selectors/test/get-menu-item-types.js
Labels: State, [Status] Needs Review, [Type] Janitorial

#52713 State: Remove unused `isUserSettingUnsaved` selector
  client/state/selectors/is-user-setting-unsaved.js
Labels: State, [Status] Needs Review, [Type] Janitorial

#52774 Themes: use fullWidthLayout in logged-out and multi-site views
  client/my-sites/themes/logged-out.jsx
  client/my-sites/themes/multi-site.jsx
  client/my-sites/themes/single-site.jsx
Labels: Themes, [Status] Needs Review

#52501 SwitcherShell: refactor away from `UNSAFE_componentWillReceiveProps`
  client/blocks/author-selector/index.jsx
  client/blocks/author-selector/switcher-shell.jsx
Labels: [Status] Needs Review, [Type] Janitorial

#52711 Framework: Refactor away from `_.each()`
  .eslintrc.js
  client/components/rating/test/index.js
  client/components/token-field/index.jsx
  client/lib/perfmon/index.js
  client/my-sites/activity/activity-log-tasklist/index.jsx
  client/my-sites/comments/comment-navigation/index.jsx
  client/my-sites/comments/comment/comment-html-editor/index.jsx
  client/my-sites/comments/controller.js
Labels: Code Style, Framework, [Status] Needs Review, [Type] Enhancement, [Type] Janitorial

#52731 clientRouter: Replace hydrate with render in dev
  client/controller/index.web.js
Labels: [Pod] Design Selection, [Status] Needs Review

#52529 Checkout: Validate tax contact information in contact step
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/my-sites/checkout/composite-checkout/components/tax-fields.tsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
  client/my-sites/checkout/composite-checkout/contact-validation.js
Labels: [Estimate] 2, [Status] Ready to Merge

#52311 Checkout: Add Google Pay payment method
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-methods/index.ts
  client/my-sites/checkout/composite-checkout/lib/translate-payment-method-names.ts
  config/desktop-development.json
  config/desktop.json
  config/development.json
  config/horizon.json
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  packages/wpcom-checkout/package.json
  packages/wpcom-checkout/src/custom.d.ts
  packages/wpcom-checkout/src/google-pay-mark.tsx
  packages/wpcom-checkout/src/index.ts
  packages/wpcom-checkout/src/payment-method-logos.ts
  packages/wpcom-checkout/src/payment-methods/google-pay.tsx
  packages/wpcom-checkout/src/payment-request-button.tsx
Labels: Checkout, [Estimate] 4

#51950 All Sites View: Update Labels for Posts & Pages
  client/my-sites/pages/main.jsx
  client/my-sites/posts/main.jsx
Labels: OSS Citizen, [Status] Ready to Merge, [Status] String Freeze

#52756 Playwright: Implement video capture.
  packages/calypso-e2e/.eslintrc.js
  packages/calypso-e2e/package.json
  packages/calypso-e2e/src/browser-manager.ts
  packages/calypso-e2e/src/hooks/browser.ts
  packages/calypso-e2e/src/hooks/index.ts
  packages/calypso-e2e/src/hooks/recording.ts
  packages/calypso-e2e/src/index.ts
  packages/calypso-e2e/src/media-helper.ts
  test/e2e/.mocharc_playwright.yml
  test/e2e/lib/hooks-playwright/hooks.ts
  test/e2e/lib/hooks-playwright/index.ts
  test/e2e/magellan-playwright.json
  test/e2e/specs-playwright/wp-log-in-out-spec.js
  yarn.lock
Labels: [Status] Needs Review

#52689 Partner Portal: Fix billing dashboard header flex wrap
  client/jetpack-cloud/sections/partner-portal/primary/billing-dashboard/style.scss
Labels: Jetpack Cloud, [Status] Needs Review

#47652 Media Library: Autofocus Pexels Search Bar
  client/my-sites/media-library/filter-bar.jsx
Labels: Media, OSS Citizen, [Pod] Design Selection, [Status] Needs Review

#42416 Media Library: Add Focus Styling to Images
  client/my-sites/media-library/list-item.scss
Labels: OSS Citizen, [Pod] Design Selection

#52795 Allow redirecting to /checkout/jetpack when feature flag is active
  client/my-sites/plans/jetpack-plans/utils.ts
  config/jetpack-cloud-stage.json
Labels: Jetpack Cloud, [Status] Needs Review

#51953 Jetpack: Introduce logged-out visitor checkout
  client/blocks/jetpack-connect-skip-user/index.js
  client/layout/logged-out.jsx
  client/layout/masterbar/checkout.jsx
  client/my-sites/checkout/checkout-system-decider.js
  client/my-sites/checkout/checkout-thank-you/jetpack-checkout-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/style.scss
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-complete-callback.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/index.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-prepare-products-for-cart.ts
  client/my-sites/checkout/composite-checkout/lib/submit-wpcom-transaction.ts
  client/my-sites/checkout/composite-checkout/lib/translate-cart.ts
  client/my-sites/checkout/composite-checkout/payment-method-helpers.js
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
  client/my-sites/checkout/composite-checkout/test/existing-card-processor.ts
  client/my-sites/checkout/composite-checkout/test/free-purchase-processor.ts
  client/my-sites/checkout/composite-checkout/test/full-credits-processor.ts
  client/my-sites/checkout/composite-checkout/test/generic-redirect-processor.ts
  client/my-sites/checkout/composite-checkout/test/multi-partner-card-processor.ts
  client/my-sites/checkout/composite-checkout/test/paypal-express-processor.ts
  client/my-sites/checkout/composite-checkout/test/we-chat-processor.ts
  client/my-sites/checkout/composite-checkout/test/web-pay-processor.ts
  client/my-sites/checkout/controller.jsx
  client/my-sites/checkout/index.js
  client/my-sites/checkout/upsell-nudge/purchase-modal/index.tsx
  client/state/products-list/selectors/get-product-name.js
  client/state/products-list/selectors/index.js
  packages/shopping-cart/src/shopping-cart-endpoint.ts
  packages/wpcom-checkout/src/types.ts
Labels: Checkout, DO NOT MERGE, Jetpack, [Status] In Progress, [Status] Needs Review

#52782 Fixup style syntax incompatible with dart-sass
  client/blocks/login/two-factor-authentication/push-notification-illustration.scss
  client/components/notice/style.scss
  client/my-sites/migrate/section-migrate.scss
  client/my-sites/stats/post-trends/style.scss
Labels: Build, [Status] Needs Review

#52796 Enable Jetpack checkout in staging
  config/stage.json
Labels: DO NOT MERGE, Jetpack, Jetpack Cloud, [Status] Needs Review

#52649 Error Reporting for GB/WP-Admin: Add crossorigin to other relevant script els and add return early in case of sanitized error
  apps/editing-toolkit/editing-toolkit-plugin/error-reporting/index.js
  apps/editing-toolkit/editing-toolkit-plugin/error-reporting/index.php
Labels: [Status] Needs Review

#52802 `?shuffle` param on My Home will request shuffled views
  client/components/data/query-home-layout/index.js
  client/my-sites/customer-home/controller.jsx
  client/my-sites/customer-home/main.jsx
  client/state/data-layer/wpcom/sites/home/layout/index.js
  client/state/home/actions.js
Labels: Customer Home, My Home Pod, [Status] Needs Review

#52770 ci(e2e): Move site-editor-spec to gutenberg suite
  test/e2e/specs-gutenberg/wp-site-editor-spec.js
Labels: [Status] Needs Review

#52631 Jetpack Search: instant search toggle should change with Jetpack Search toggle
  client/my-sites/site-settings/jetpack-module-toggle.jsx
  client/my-sites/site-settings/search.jsx
  client/my-sites/site-settings/settings-performance/main.jsx
  client/my-sites/site-settings/wrap-settings-form.jsx
Labels: Jetpack Search, Site Settings, [Status] Ready to Merge

#52777 Replace bind( this ) pattern with arrow functions
  apps/notifications/src/panel/rest-client/index.js
  client/components/bulk-select/docs/example.jsx
  client/components/section-nav/docs/example.jsx
  client/components/segmented-control/README.md
  client/components/token-field/index.jsx
  client/components/token-field/suggestions-list.jsx
  client/devdocs/doc.jsx
  client/devdocs/main.jsx
  client/extensions/woocommerce/components/action-header/actions.js
  client/lib/abtest/index.js
  client/lib/data-poller/poller.js
  client/lib/form-state/index.js
  client/lib/network-connection/index.js
  client/lib/products-list/index.js
  client/lib/two-step-authorization/index.js
  client/me/security-2fa-code-prompt/index.jsx
  client/me/security-2fa-enable/index.jsx
  client/me/security-2fa-initial-setup/index.jsx
  client/my-sites/domains/domain-search/site-redirect-step.jsx
  client/my-sites/media-library/list.jsx
  client/signup/steps/about/index.jsx
  client/signup/steps/site/index.jsx
Labels: [Status] Needs Review, [Type] Janitorial

#52780 Material Design Icons: Add icons for new Add Manage All Mailboxes page
  packages/material-design-icons/README.md
  packages/material-design-icons/src/action/outline-mediation-24px.svg
  packages/material-design-icons/src/communication/outline-forward_to_inbox-24px.svg
  packages/material-design-icons/src/content/outline-move_to_inbox-24px.svg
  packages/material-design-icons/src/device/outline-dvr-24px.svg
  packages/material-design-icons/src/hardware/outline-smartphone-24px.svg
  packages/material-design-icons/svg-sprite/material-icons.svg
Labels: Design, Professional Email, [Status] Needs Review

#52785 Emails: Extract header from Email Plan page to standalone component
  client/my-sites/email/email-management/home/email-plan-header.jsx
  client/my-sites/email/email-management/home/email-plan.jsx
  client/my-sites/email/email-management/home/utils.js
  client/my-sites/email/email-management/style.scss
Labels: Professional Email, [Status] Needs Review

#52781 Components: Add new top-level component to display list of links with icons and descriptions
  client/components/vertical-nav/README.md
  client/components/vertical-nav/docs/example.jsx
  client/components/vertical-nav/item/enhanced.jsx
  client/components/vertical-nav/item/index.jsx
  client/components/vertical-nav/item/style.scss
  client/devdocs/design/playground-scope.js
  client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
  client/my-sites/domains/domain-management/edit/navigation/style.scss
Labels: Design, DevDocs, Domains, [Status] Needs Review

#52794 Design picker: re-write and re-enable randomized designs unit tests
  packages/design-picker/src/utils/__tests__/available-designs.test.ts
  packages/design-picker/src/utils/__tests__/shuffle.test.ts
  packages/design-picker/src/utils/available-designs.ts
  packages/design-picker/src/utils/shuffle.ts
Labels: [Status] Needs Review

#52778 Partner Portal: Add the full blog url in the license details card
  client/jetpack-cloud/sections/partner-portal/license-details/actions.tsx
  client/jetpack-cloud/sections/partner-portal/license-details/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-preview/index.tsx
  client/jetpack-cloud/sections/partner-portal/revoke-license-dialog/index.tsx
Labels: Jetpack Cloud, [Status] Needs Review

#52819 WooCommerce: Remove state as it's no longer in use
  client/extensions/woocommerce/app/dashboard/store-move-notice-view.js
  client/extensions/woocommerce/components/action-header/index.js
  client/extensions/woocommerce/index.js
  client/extensions/woocommerce/lib/analytics/index.js
  client/extensions/woocommerce/lib/analytics/test/tracks-utils.js
  client/extensions/woocommerce/lib/analytics/tracks-utils.js
  client/extensions/woocommerce/state/README.md
  client/extensions/woocommerce/state/action-types.js
  client/extensions/woocommerce/state/constants.js
  client/extensions/woocommerce/state/data-layer/index.js
  client/extensions/woocommerce/state/data-layer/request/actions.js
  client/extensions/woocommerce/state/data-layer/request/index.js
  client/extensions/woocommerce/state/data-layer/request/test/index.js
  client/extensions/woocommerce/state/data-layer/utils.js
  client/extensions/woocommerce/state/helpers.js
  client/extensions/woocommerce/state/reducer.js
  client/extensions/woocommerce/state/sites/README.md
  client/extensions/woocommerce/state/sites/http-request.js
  client/extensions/woocommerce/state/sites/reducer.js
  client/extensions/woocommerce/state/sites/request.js
  client/extensions/woocommerce/state/sites/selectors.js
  client/extensions/woocommerce/state/sites/setup-choices/actions.js
  client/extensions/woocommerce/state/sites/setup-choices/reducer.js
  client/extensions/woocommerce/state/sites/setup-choices/selectors.js
  client/extensions/woocommerce/state/sites/setup-choices/test/actions.js
  client/extensions/woocommerce/state/sites/setup-choices/test/reducer.js
  client/extensions/woocommerce/state/sites/setup-choices/test/selectors.js
  client/extensions/woocommerce/state/sites/status/reducer.js
  client/extensions/woocommerce/state/sites/status/wc-api/actions.js
  client/extensions/woocommerce/state/sites/status/wc-api/error-reducer.js
  client/extensions/woocommerce/state/sites/status/wc-api/reducer.js
  client/extensions/woocommerce/state/sites/status/wc-api/selectors.js
  client/extensions/woocommerce/state/sites/status/wc-api/test/error-reducer.js
  client/extensions/woocommerce/state/sites/status/wc-api/test/selectors.js
  client/extensions/woocommerce/state/sites/test/http-request.js
  client/extensions/woocommerce/state/sites/test/reducer.js
  client/extensions/woocommerce/state/sites/test/request.js
  client/extensions/woocommerce/state/test/helpers/index.js
  client/extensions/woocommerce/state/wc-api/reducer.js
  client/extensions/woocommerce/state/wc-api/status/reducer.js
  client/extensions/woocommerce/state/wc-api/status/test/reducer.js
  client/extensions/woocommerce/state/wc-api/test/utils.js
  client/extensions/woocommerce/state/wc-api/utils.js
  client/extensions/woocommerce/store-sidebar/index.js
Labels: Extensions, State, WooCommerce, [Status] Needs Review, [Type] Janitorial

#52814 Sidebar nudges: make nudge more compact - symmetric when sidebar is collapsed.
  client/my-sites/sidebar-unified/style.scss
Labels: [Status] Needs Review

#52122 Calypsoify: Handle Query block link and handle links in site editor too
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Labels: Calypsoify, [Status] Ready to Merge

#52807 Plugins: Fix install button missing from plugins page
  client/my-sites/plugins/plugin-meta/index.jsx
Labels: Atomic Upgrade Flows, Plugins, [Status] Needs Review

#52768 Add FullStory Analytics
  client/lib/analytics/ad-tracking/constants.js
  client/lib/analytics/fullstory.js
  client/lib/analytics/page-view.js
  client/lib/analytics/record-purchase.js
  client/lib/analytics/signup.js
  config/desktop-development.json
  config/desktop.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Analytics, [Status] Needs Review

#52829 Calypsoify: Fix observer error
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Labels: Calypsoify, [Status] Needs Review

#34583 App Banner: Remove Unnecessary Logic for Activity Log
  client/blocks/app-banner/test/app-banner.jsx
  client/blocks/app-banner/utils.js
Labels: Activity Log, OSS Citizen, [Status] Ready to Merge

#35146 Plans & FAQ: Improve Colour Contrast
  client/components/faq/style.scss
  client/my-sites/plan-interval-discount/style.scss
Labels: Accessibility, OSS Citizen, [Status] Needs Review

#38989 Media: Warn about Personal File Uploads in Guided Tours
  client/layout/guided-tours/tours/media-basics-tour/index.js
  client/post-editor/media-modal/detail/detail-fields.jsx
Labels: Media, OSS Citizen, [Status] Ready to Merge

#38598 Crowdsignal Login: Fix Height of 2FA Buttons
  client/blocks/login/two-factor-authentication/two-factor-actions.scss
Labels: Crowdsignal, OSS Citizen, [Status] Ready to Merge

#52754 Jetpack Cloud Pricing: Fix Jetpack Free button does not respect site protocol.
  client/components/jetpack/card/jetpack-free-card/test/button.jsx
  client/components/jetpack/card/jetpack-free-card/use-jetpack-free-button-props.ts
Labels: Jetpack, Jetpack Cloud, [Status] Needs Review

#52846 Update app banners design
  client/assets/images/illustrations/app-banner-editor.svg
  client/assets/images/illustrations/app-banner-notifications.svg
  client/assets/images/illustrations/app-banner-reader.svg
  client/assets/images/illustrations/app-banner-stats.svg
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/blocks/app-banner/index.jsx
  client/blocks/app-banner/style.scss
  client/devdocs/design/illustrations.jsx
Labels: NUX, [Type] Enhancement

#52817 ci(e2e): Refactor screenrecorder and framebuffer logs
  test/e2e/lib/hooks/browser.js
  test/e2e/lib/hooks/framebuffer.js
  test/e2e/lib/hooks/index.js
  test/e2e/lib/hooks/video-recorder.js
  test/e2e/lib/mocha-hooks.js
  test/e2e/lib/test-utils.js
  test/e2e/lib/video-recorder.js
Labels: [Status] Needs Review

#52812 ci(e2e): Migrate saveLogs hook to Root Hooks
  test/e2e/lib/hooks/browser-logs.js
  test/e2e/lib/hooks/index.js
  test/e2e/lib/hooks/save-console-log.js
  test/e2e/lib/mocha-hooks.js
Labels: [Status] Needs Review

#52704 Jetpack Connection: rename 'skip_user' parameter
  client/blocks/jetpack-connect-site-only/index.js
  client/blocks/jetpack-connect-site-only/style.scss
  client/blocks/login/login-form.jsx
  client/jetpack-connect/schema.js
  client/jetpack-connect/signup.js
  client/jetpack-connect/test/__snapshots__/utils.js.snap
  client/jetpack-connect/test/utils.js
  client/jetpack-connect/utils.js
  client/lib/paths/login/index.js
Labels: Jetpack, [Status] Ready to Merge

#52541 Use MShotImage (Hover-Scroll) in Page Layout Picker
  packages/design-picker/src/components/index.tsx
  packages/design-picker/src/components/mshots-image/index.tsx
  packages/design-picker/src/index.ts
  packages/page-pattern-modal/jest.config.js
  packages/page-pattern-modal/package.json
  packages/page-pattern-modal/src/components/pattern-selector-item.tsx
  packages/page-pattern-modal/src/styles/page-pattern-modal.scss
Labels: [Status] Needs Review

#52818 Use account-specific titles for mailbox list
  client/lib/emails/email-provider-constants.js
  client/my-sites/email/email-management/home/email-plan-mailboxes-list.jsx
  client/my-sites/email/email-management/home/email-plan.jsx
Labels: [Status] Needs Review

#52750 Fix mobile display for new email forward page
  client/my-sites/email/email-management/home/email-plan-mailboxes-list.jsx
  client/my-sites/email/email-management/style.scss
Labels: [Status] Ready to Merge

#52659 Rename isSwitched to isRelatedContentEnabled in toggle button
  client/my-sites/email/email-provider-features/toggle-button.js
  client/my-sites/email/email-providers-comparison/email-provider-card.jsx
Labels: [Status] Ready to Merge

#49011 Show renewal-aware warnings when renewals are removed from the cart
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
  packages/wpcom-checkout/src/index.ts
  packages/wpcom-checkout/src/is-wpcom-product-renewal.ts
Labels: Checkout, [Status] Needs Review

#52612 Remove Code from Hide eCommerce Experiment
  client/my-sites/plan-features-comparison/style.scss
  client/my-sites/plans-features-main/index.jsx
  client/signup/controller.js
Labels: [Status] Needs Review

#52855 ci(e2e): Delete unused Jetpack tests
  test/e2e/scripts/jetpack/wp-jetpack-activate.js
  test/e2e/scripts/jetpack/wp-jetpack-deactivate.js
  test/e2e/scripts/jetpack/wp-jetpack-jn-activate.js
Labels: [Status] Needs Review

#52793 Framework: Refactor away from `_.unionBy()`
  client/my-sites/activity/activity-log-tasklist/to-update.jsx
  client/state/comments/reducer.js
  client/state/comments/trees/reducer.js
Labels: Framework, [Status] Needs Review, [Type] Enhancement, [Type] Janitorial

#52825 Components: Remove unused SiteTitle component
  client/components/site-title/README.md
  client/components/site-title/docs/example.jsx
  client/components/site-title/index.jsx
  client/devdocs/design/component-examples.js
  client/devdocs/design/index.jsx
  client/devdocs/design/playground-scope.js
Labels: Components, [Status] Needs Review, [Type] Janitorial

#52823 Framework: Refactor away from `_.head()`
  client/blocks/image-selector/dropzone.jsx
  client/blocks/signup-form/index.jsx
  client/blocks/user-mentions/add.jsx
  client/components/community-translator/utils.js
  client/components/domains/contact-details-form-fields/index.jsx
  client/gutenberg/editor/media-utils.js
  client/jetpack-connect/utils.js
  client/lib/importer/importer-config.js
  client/me/account-password/index.jsx
  client/my-sites/checkout/checkout-thank-you/custom-domain-purchase-detail.jsx
  client/my-sites/media-library/content.jsx
  client/my-sites/site-settings/podcast-cover-image-setting/index.jsx
  client/my-sites/site-settings/site-icon-setting/index.jsx
  client/my-sites/theme/main.jsx
  client/post-editor/editor-revisions-list/index.jsx
  client/post-editor/media-modal/index.jsx
  client/signup/validation-fieldset/index.jsx
  client/state/data-layer/wpcom-http/pipeline/remove-duplicate-gets/index.js
Labels: Framework, [Status] Needs Review, [Type] Enhancement, [Type] Janitorial

#52828 Config: Remove unused WooCommerce extension flags
  config/desktop-development.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Framework, WooCommerce, [Status] Needs Review, [Type] Janitorial

#52861 webpack config: Restore `RequireChunkCallbackPlugin`
  client/webpack.config.js
Labels: Build, [Status] Needs Review, [Type] Bug, i18n

#52421 Show placeholder instead of NaN in discount
  client/my-sites/plan-features-comparison/header.jsx
  client/my-sites/plan-features-comparison/style.scss
Labels: Plans, Signup, [Pri] High, [Status] Ready to Merge

#52864 Make inline help button compact
  client/blocks/inline-help/index.jsx
Labels: [Pri] Normal, [Status] Needs Review

#52791 i18n: Add all preloaded translation chunks at once
  client/lib/i18n-utils/switch-locale.js
Labels: Performance, [Status] Needs Review, i18n

#52813 Themes controller: move logged-in handlers to a new module not imported by SSR
  client/my-sites/theme/controller.jsx
  client/my-sites/themes/controller-logged-in.jsx
  client/my-sites/themes/controller.jsx
  client/my-sites/themes/index.web.js
  client/webpack.config.node.js
Labels: Server Side Rendering, Themes, [Status] Needs Review

#52858 Ensure verification button in email forward page is right-aligned
  client/my-sites/email/email-management/style.scss
Labels: [Status] Needs Review

#51901 Adds renew monthly option for annual plan downgrades
  client/lib/purchases/index.js
  client/lib/purchases/test/index.js
  client/me/purchases/manage-purchase/index.jsx
  client/me/purchases/manage-purchase/style.scss
Labels: [Status] Needs Review

#52815 Emails: Add new No Domain page
  client/my-sites/email/email-management/email-home.jsx
  client/my-sites/email/email-management/home/email-no-domain.jsx
  client/my-sites/email/email-management/home/email-plan.jsx
Labels: G Suite, Professional Email, [Status] Needs Review

#52831 My Home: Replace "More Help" with "Contact Support"
  client/my-sites/customer-home/cards/features/help-search/index.jsx
Labels: OSS Citizen

#52870 codeowners: Add I18n section
  .github/CODEOWNERS
Labels: [Status] Needs Review

#33795 Media Modal: Tone Down Accent Colours
  client/my-sites/media-library/header.jsx
  client/my-sites/media-library/upload-button.jsx
  client/post-editor/media-modal/secondary-actions.jsx
Labels: Color Schemes, OSS Citizen, [Status] Needs Review

#52839 Jetpack Plans: Hide yearly billing discount message when monthly billing is selected.
  client/my-sites/plans/jetpack-plans/plans-filter-bar/index.tsx
  client/my-sites/plans/jetpack-plans/plans-filter-bar/style.scss
Labels: Jetpack, Jetpack Cloud, Plans, [Status] Needs Review

#52892 Reader: Update Reader CSS for Story block
  client/blocks/reader-full-post/story.scss
  client/components/embed-container/index.jsx
Labels: Reader, [Status] Needs Review
