Repository Automattic/wp-calypso, pull requests merged in 2021-01, with the labels that each got.

#48631 Domain Picker: use ref to focus on SuggestionItem
  packages/domain-picker/src/domain-picker/index.tsx
  packages/domain-picker/src/domain-picker/suggestion-item.tsx
Labels: [Status] Needs Review

#48455 Importers: remove confusing workarounds when rendering active importers
  client/my-sites/importer/file-importer.jsx
  client/my-sites/importer/importer-blogger.jsx
  client/my-sites/importer/importer-godaddy-gocentral.jsx
  client/my-sites/importer/importer-squarespace.jsx
  client/my-sites/importer/importer-wix.jsx
  client/my-sites/importer/importer-wordpress.jsx
  client/my-sites/importer/importing-pane.jsx
  client/my-sites/importer/section-import.jsx
  client/my-sites/importer/site-importer/index.jsx
Labels: Import, [Status] Needs Review

#48615 Nav Unification: set hover state to false when expandable menu is clicked
  client/layout/sidebar/expandable.jsx
Labels: Nav Unification, Nav Unification [Alpha], [Status] Needs Review

#48613 Nav Unification: expand current section after collapsing all
  client/my-sites/sidebar-unified/item.jsx
  client/my-sites/sidebar-unified/menu.jsx
Labels: Nav Unification, Nav Unification [Alpha], [Status] Needs Review

#48606 Nav Unification: fix sidebar sub-menu overlap
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/my-sites/sidebar-unified/style.scss
Labels: Nav Unification, Nav Unification [Alpha], [Status] Needs Review

#48604 P2 Free: remove "Manage plan" btn
  client/my-sites/plan-features/actions.jsx
Labels: Plans

#48644 Deduplicate react and react-dom in yarn.lock
  yarn.lock
Labels: [Status] Needs Review, [Type] Janitorial

#48389 Anchor Gutenboarding sends the user to new post, not edit homepage
  client/landing/gutenboarding/hooks/use-on-site-creation.ts
  client/landing/gutenboarding/onboarding-block/create-site-error/index.tsx
  client/landing/gutenboarding/onboarding-block/edit.tsx
  client/landing/gutenboarding/path.ts
Labels: [Status] Needs Review

#48605 P2+: fix the renewal button & add the plan to isPlan check
  client/lib/products-values/is-p2-plus.js
  client/lib/products-values/is-plan.js
  client/me/purchases/manage-purchase/index.jsx
Labels: [Status] Needs Review

#48541 Signup: Track if the user selected video storage in the new site features step
  client/landing/gutenboarding/lib/analytics/types.ts
  client/landing/gutenboarding/onboarding-block/features/index.tsx
Labels: Signup, VideoPress, [Status] Needs Review

#48633 Titan: Show control panel in an iframe
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/my-sites/email/email-management/titan-control-panel-login-card/index.jsx
  config/development.json
  config/wpcalypso.json
Labels: Domains, [Status] Needs Review

#48510 Earn: Update color variable for icons
  client/my-sites/earn/style.scss
Labels: [Status] Needs Review, [Type] Bug

#48112 Onboarding: Fix plan picker comparison table width on large displays
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/plan-step/styles.scss
  packages/onboarding/styles/mixins.scss
  packages/plans-grid/src/plans-details/style.scss
  packages/plans-grid/src/plans-grid/style.scss
  packages/plans-grid/src/variables.scss
Labels: Editing Toolkit, Launch, [Goal] New Onboarding, [Status] Needs Review, [Type] Bug

#48435 Checkout: Move analytics for redirect payment methods into payment processors
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-complete-callback.tsx
  client/my-sites/checkout/composite-checkout/lib/analytics.js
  client/my-sites/checkout/composite-checkout/lib/analytics.ts
  client/my-sites/checkout/composite-checkout/payment-method-processors.js
  client/my-sites/checkout/composite-checkout/payment-methods/ebanx-tef.js
  client/my-sites/checkout/composite-checkout/payment-methods/id-wallet.js
  client/my-sites/checkout/composite-checkout/payment-methods/netbanking.js
  client/my-sites/checkout/composite-checkout/payment-methods/wechat/index.js
  client/my-sites/checkout/composite-checkout/record-analytics.js
  client/my-sites/checkout/composite-checkout/types/payment-processors.ts
  packages/calypso-analytics/src/tracks.ts
  packages/composite-checkout/src/lib/payment-methods/alipay.js
  packages/composite-checkout/src/lib/payment-methods/bancontact.js
  packages/composite-checkout/src/lib/payment-methods/eps.js
  packages/composite-checkout/src/lib/payment-methods/giropay.js
  packages/composite-checkout/src/lib/payment-methods/ideal.js
  packages/composite-checkout/src/lib/payment-methods/p24.js
  packages/composite-checkout/src/lib/payment-methods/paypal.js
  packages/composite-checkout/src/lib/payment-methods/sofort.js
  packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
Labels: Checkout, [Estimate] 1, [Status] Ready to Merge

#48437 Domains: Update RegisterDomainStep to use withShoppingCart and remove CartData
  client/components/domains/register-domain-step/index.jsx
  client/my-sites/domains/domain-search/index.jsx
  client/signup/steps/domains/index.jsx
Labels: Domains, Shopping Cart, [Estimate] 1, [Status] Ready to Merge

#48495 Checkout: Remove unused TransactionFlow and dependencies
  client/lib/analytics/store-transactions.js
  client/lib/store-transactions/README.md
  client/lib/store-transactions/index.js
  client/lib/store-transactions/step-types.js
Labels: Checkout, [Estimate] 1, [Status] Ready to Merge

#48501 Checkout: remove handleCheckoutCompleteRedirect
  client/my-sites/checkout/checkout/index.jsx
Labels: Checkout, [Estimate] 1, [Status] Ready to Merge

#47339 Removing redundant fallback headline from launch flow.
  client/signup/config/steps-pure.js
Labels: [Status] Needs Review

#48637 Bugfix: Catch non-array API responses in useStoredCards hook
  client/my-sites/checkout/composite-checkout/hooks/use-stored-cards.ts
Labels: Checkout, [Estimate] 1, [Status] Needs Review, [Type] Bug

#48653 Plans, Jetpack Cloud: Add New Year 2021 sale banner to connect and plans pages
  client/components/jetpack/new-year-2021-sale-banner/index.tsx
  client/components/jetpack/new-year-2021-sale-banner/new-year-banner-2x.png
  client/components/jetpack/new-year-2021-sale-banner/new-year-banner.png
  client/components/jetpack/new-year-2021-sale-banner/new-year-banner_mobile-2x.png
  client/components/jetpack/new-year-2021-sale-banner/new-year-banner_mobile.png
  client/components/jetpack/new-year-2021-sale-banner/style.scss
  client/jetpack-cloud/sections/pricing/header/index.tsx
  client/jetpack-cloud/sections/pricing/header/new-year-2021-sale-banner/index.tsx
  client/jetpack-connect/controller.js
  client/jetpack-connect/store-header.tsx
  client/my-sites/plans/jetpack-plans/plans-header.tsx
Labels: Jetpack Cloud, Plans, [Status] Needs Review

#48512 Checkout: Remove old checkout's Checkout component
  client/lib/checkout/validation.js
  client/my-sites/checkout/cart/cart-ad.jsx
  client/my-sites/checkout/cart/cart-body/index.jsx
  client/my-sites/checkout/cart/cart-coupon.jsx
  client/my-sites/checkout/cart/cart-free-user-plan-upsell.jsx
  client/my-sites/checkout/cart/cart-plan-ad-theme.jsx
  client/my-sites/checkout/cart/style.scss
  client/my-sites/checkout/cart/test/cart-coupon.js
  client/my-sites/checkout/cart/test/cart-plan-discount-ad.js
  client/my-sites/checkout/checkout/README.md
  client/my-sites/checkout/checkout/checkout-container.jsx
  client/my-sites/checkout/checkout/checkout-container.scss
  client/my-sites/checkout/checkout/index.jsx
  client/my-sites/checkout/checkout/notices.jsx
  client/my-sites/checkout/checkout/recent-renewals.jsx
  client/my-sites/checkout/checkout/signup-site-created-notice.jsx
  client/my-sites/checkout/checkout/style.scss
  client/my-sites/checkout/checkout/subscription-text.scss
  client/my-sites/plans/README.md
Labels: Checkout, [Estimate] 1, [Status] Ready to Merge

#48640 Patterns: guard premium patterns indicator behind an Object.isExtensible check to prevent fatals in debug mode
  apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx
Labels: Patterns, [Status] Needs Review, [Type] Bug

#48492 Step-by-step credentials API (with wpcom-proxy-request fix)
  client/jetpack-cloud/sections/settings/advanced-credentials/index.tsx
  client/package.json
  client/state/action-types.js
  client/state/data-layer/wpcom-http/actions.js
  client/state/data-layer/wpcom-http/index.js
  client/state/data-layer/wpcom-http/utils.js
  client/state/data-layer/wpcom/activity-log/update-credentials/index.js
  client/state/data-layer/wpcom/jetpack-install/test/__snapshots__/index.js.snap
  client/state/jetpack/credentials/actions.js
  packages/wpcom-proxy-request/History.md
  packages/wpcom-proxy-request/src/index.js
  yarn.lock
Labels: Rewind, [Status] Needs Review

#48642 Adds box-shadow to sidebar flyouts
  client/my-sites/sidebar-unified/style.scss
Labels: Nav Unification [Alpha], [Status] Needs Review

#48668 Imports: provide stable key for ImporterComponent to prevent re-mount
  client/my-sites/importer/section-import.jsx
Labels: Import, [Status] Needs Review, [Type] Bug

#48667 Nav Unification: Fixes flyout arrow
  client/my-sites/sidebar-unified/style.scss
Labels: [Status] Needs Review

#48202 Domain Management: Finish replacing CartData with ShoppingCartProvider
  client/components/data/domain-management/README.md
  client/components/data/domain-management/index.jsx
  client/components/domains/domain-registration-suggestion/index.jsx
  client/components/domains/domain-search-results/index.jsx
  client/components/domains/featured-domain-suggestions/index.jsx
  client/components/domains/map-domain-step/index.jsx
  client/components/domains/register-domain-step/index.jsx
  client/components/domains/transfer-domain-step/index.jsx
  client/components/upgrades/gsuite/README.md
  client/components/upgrades/gsuite/index.jsx
  client/my-sites/domains/controller.jsx
  client/my-sites/domains/domain-management/controller.jsx
  client/my-sites/domains/domain-management/list/index.jsx
  client/my-sites/domains/domain-search/index.jsx
Labels: Domains, G Suite, Shopping Cart, [Estimate] 2, [Status] Needs Review, [Status] Needs e2e Testing

#48530 Reader: Use the same styles for post comments as post content
  client/assets/stylesheets/shared/_typography.scss
  client/assets/stylesheets/shared/_utils.scss
  client/blocks/comments/post-comment-content.scss
  client/blocks/reader-full-post/_content.scss
  client/blocks/reader-full-post/gutenberg-gallery.scss
Labels: Reader, [Status] Needs Review, [Type] Enhancement

#48176 P2+: enable in production
  client/lib/plans/constants.js
  client/lib/plans/features-list.js
  client/lib/plans/plans-list.js
  config/desktop.json
  config/horizon.json
  config/production.json
  config/wpcalypso.json
Labels: [Status] Ready to Merge

#48515 Form toggles: Use admin color schemes' primary color as background
  client/assets/stylesheets/_main.scss
  client/assets/stylesheets/_wp-components-overrides.scss
  client/assets/stylesheets/style.scss
Labels: Admin Color Schemes Unification, Color Schemes, Components, [Status] Needs Review

#48678 Jetpack Plans Page: Remove Jetpack CRM Monthly product.
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
Labels: Jetpack, Plans, [Status] Needs Review

#48679 composite-checkout: Fix types on Checkout steps
  packages/composite-checkout/src/components/checkout-next-step-button.tsx
  packages/composite-checkout/src/components/checkout-payment-methods.tsx
  packages/composite-checkout/src/components/checkout-review-order.tsx
  packages/composite-checkout/src/components/checkout-steps.tsx
  packages/composite-checkout/src/components/default-steps.tsx
  packages/composite-checkout/src/types.ts
Labels: Checkout, [Estimate] 1, [Status] Ready to Merge

#48506 Anchor: Include info about Anchor flavoring when submitting Gutenboarding signup.
  client/config/index.js
  client/landing/gutenboarding/components/signup-form/index.tsx
  packages/data-stores/src/user/types.ts
Labels: [Status] Needs Review

#48672 Domains: Reduxify notices in EditContactInfoFormCard
  client/my-sites/domains/domain-management/edit-contact-info/form-card.jsx
Labels: Domains, State, [Status] Ready to Merge, [Type] Enhancement

#47901 Nav-unification - Sidebar Scroll: fix scrolling when content is shorter than sidebar.
  client/layout/utils.ts
  client/my-sites/sidebar-unified/style.scss
Labels: Nav Unification, [Status] Needs Review

#48172 Domain Picker: make items keyboard accessible
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/domain-step/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/domain-step/styles.scss
  packages/domain-picker/src/domain-picker/index.tsx
  packages/domain-picker/src/domain-picker/style.scss
  packages/domain-picker/src/domain-picker/suggestion-item.tsx
  packages/domain-picker/src/info-tooltip/index.tsx
  packages/domain-picker/test/suggestion-item.tsx
  packages/launch/src/focused-launch/summary/index.tsx
Labels: Accessibility, Focused Launch, [Goal] New Onboarding

#48663 Focused-Launch: Update mobile styling for select buttons
  packages/domain-picker/src/domain-picker/style.scss
  packages/domain-picker/src/domain-picker/suggestion-item.tsx
Labels: Focused Launch, [Status] Needs e2e Testing

#48638 Activity Log Tasklist: Fix Colour Contrast
  client/my-sites/activity/activity-log-tasklist/style.scss
Labels: OSS Citizen, [Status] Ready to Merge

#48519 Help Form: Align Form Button
  client/me/help/help-contact-form/style.scss
Labels: OSS Citizen, [Status] Needs Review

#48681 Anchor Gutenboarding: "Log in" link preserves all three anchor params
  client/landing/gutenboarding/components/signup-form/index.tsx
Labels: [Status] Needs Review

#48686 Admin Menu: Show update count in submenu items
  client/layout/sidebar/style.scss
  client/my-sites/sidebar-unified/item.jsx
Labels: Nav Unification, [Status] Needs Review, [Type] Enhancement

#48687 Domains: Update GSuiteAddUsers to use withShoppingCart
  client/my-sites/email/controller.js
  client/my-sites/email/gsuite-add-users/index.jsx
Labels: G Suite, Shopping Cart, [Status] Needs Review

#48658 Shopping cart: Add CartMessages to CalypsoShoppingCartProvider
  client/components/upgrades/gsuite/index.jsx
  client/my-sites/checkout/calypso-shopping-cart-provider.tsx
  client/my-sites/checkout/cart/cart-messages.jsx
  client/my-sites/checkout/cart/popover-cart.jsx
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
Labels: Shopping Cart, [Estimate] 1, [Status] Needs Review

#48583 Add notice about the current payment method when it's not available to select on the Update Payment Method page
  client/lib/purchases/assembler.js
  client/lib/purchases/test/assembler.js
  client/me/purchases/manage-purchase/change-payment-method/index.jsx
  client/state/purchases/test/selectors.js
Labels: Billing, [Status] Ready to Merge, [Status] String Freeze

#48476 Purchases: update payment method notices
  client/me/purchases/manage-purchase/notices.jsx
Labels: Billing, [Estimate] 1, [Status] Needs Review, [Status] String Freeze

#48584 Coming Soon: add php unit tests
  apps/editing-toolkit/README.md
  apps/editing-toolkit/editing-toolkit-plugin/coming-soon/coming-soon.php
  apps/editing-toolkit/editing-toolkit-plugin/coming-soon/test/class-coming-soon-test.php
  apps/editing-toolkit/editing-toolkit-plugin/phpunit.xml.dist
Labels: Coming Soon, Editing Toolkit, [Status] Needs Review, [Tests] Includes Tests

#48244 Reader: update client/reader components to use new recordReaderTracksEvent action - part two
  client/reader/following-manage/empty.jsx
  client/reader/following-manage/index.jsx
  client/reader/following/intro.jsx
  client/reader/liked-stream/empty.jsx
  client/reader/list-gap/index.jsx
  client/reader/list-stream/empty.jsx
  client/reader/list-stream/index.jsx
  client/reader/list-stream/missing.jsx
  client/reader/search-stream/empty.jsx
  client/reader/search-stream/index.jsx
  client/reader/search-stream/suggestion.jsx
  client/reader/sidebar/reader-sidebar-lists/list-item-create-link.jsx
  client/reader/sidebar/reader-sidebar-lists/list-item.jsx
  client/reader/sidebar/reader-sidebar-organizations/list-item.jsx
  client/reader/sidebar/reader-sidebar-tags/index.jsx
  client/reader/sidebar/reader-sidebar-tags/list-item.jsx
Labels: Reader, [Status] Needs Review

#47995 GSuite to Google Workspace migration
  client/blocks/inline-help/admin-sections.js
  client/lib/gsuite/constants.js
  client/lib/gsuite/get-google-mail-service-family.js
  client/lib/gsuite/index.js
  client/my-sites/domains/domain-management/dns/email-provider.jsx
  client/my-sites/domains/domain-management/list/list-header.jsx
  client/my-sites/domains/domain-management/name-servers/dns-templates.jsx
  client/state/data-layer/wpcom/gsuite-users/index.js
Labels: [Status] Ready to Merge

#48708 G Suite: Fix error preventing new G Suite users from being added
  client/my-sites/email/controller.js
Labels: G Suite, [Status] Needs Review, [Type] Bug

#48682 Fix e2e tests to work on newer chrome browsers
  test/e2e/lib/driver-manager.js
  test/e2e/lib/pages/wp-home-page.js
Labels: [Status] Needs Review

#46785 Nav Unification - implement conditionals for static fallback nav data
  client/my-sites/sidebar-unified/fallback-data.js
  client/my-sites/sidebar-unified/use-site-menu-items.js
Labels: Nav Unification, [Status] Needs Review

#48366 me/profile: create and use `withFormBase` hoc
  client/me/form-base/with-form-base.jsx
  client/me/profile/index.jsx
Labels: Me, [Status] Needs Review

#48695 Checkout: fix chat icon margin
  client/my-sites/checkout/composite-checkout/components/payment-chat-button.jsx
  client/my-sites/checkout/composite-checkout/components/payment-chat-button.tsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.js
Labels: Checkout, [Status] Needs Review

#48693 Editing Toolkit: Update to 2.8.17
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/readme.txt
  apps/editing-toolkit/package.json
Labels: Editing Toolkit, [Status] Needs Review

#48193 New onboarding: user who picked “free” from plans grid A/B test non-EN
  client/lib/abtest/active-tests.js
  client/signup/controller.js
Labels: ABTest, [Goal] New Onboarding, [Status] Needs Review

#48379 Sidebar: Redesign upsell nudge
  client/blocks/upsell-nudge/style.scss
  client/layout/sidebar/style.scss
  client/my-sites/current-site/style.scss
  client/my-sites/sidebar-unified/style.scss
Labels: Admin Color Schemes Unification, [Status] Needs Review

#48713 Jetpack Connection Manager UI: Skip the plans page
  client/jetpack-connect/authorize.js
  client/jetpack-connect/test/authorize.js
Labels: Jetpack, [Type] Enhancement

#48698 Plans Page: Display tiered pricing for products that have it
  client/components/jetpack/card/jetpack-product-card-i5/index.tsx
  client/components/jetpack/card/jetpack-product-card-i5/style.scss
  client/my-sites/plans/jetpack-plans/product-card-i5/index.tsx
  client/my-sites/plans/jetpack-plans/types.ts
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
  client/my-sites/plans/jetpack-plans/use-item-price.ts
  client/my-sites/plans/jetpack-plans/utils.ts
  client/state/products-list/selectors/get-product-price-tiers.ts
  client/state/products-list/selectors/index.js
Labels: Jetpack, Jetpack Cloud, Plans, [Status] Needs Design Review, [Status] Needs Review

#48683 Styles: Use correct theme colors for WordPress/components Button
  client/assets/stylesheets/_wp-components-overrides.scss
Labels: Color Schemes, Components, [Status] Needs Design Review, [Status] Needs Review

#48680 Help: Fix domains link, update Contact Us icon color
  client/me/help/main.jsx
  client/me/help/style.scss
Labels: Help, [Status] Needs Review, [Type] Bug, [Type] Janitorial

#48439 AnchorFM: Add theme names and screenshots
  client/landing/gutenboarding/available-designs-config.json
  static/images/design-screenshots/gilbert_gilbert_gilbert.jpg
  static/images/design-screenshots/gilbert_gilbert_gilbert.webp
  static/images/design-screenshots/riley_riley_riley.jpg
  static/images/design-screenshots/riley_riley_riley.webp
Labels: [Status] Needs Review

#48723 Gutenboarding: Remove Doyle design temporarily due to issue with Alves theme and that design
  client/landing/gutenboarding/available-designs-config.json
Labels: [Status] Needs Review

#48688 Update copy for store deprecation/removal
  client/extensions/woocommerce/app/dashboard/store-move-notice-view.js
  client/extensions/woocommerce/components/store-deprecated-notice/index.js
  client/my-sites/sidebar/index.jsx
  client/my-sites/sidebar/style.scss
Labels: [Status] Needs Review

#48485 Plugins: Decouple plugins from sites in PluginsList
  client/my-sites/plugins/plugins-list/index.jsx
  client/my-sites/plugins/plugins-list/test/index.jsx
Labels: Plugins, State, [Status] Needs Review, [Type] Enhancement

#48249 Store|Woo: Update/store redirect dashboard
  client/extensions/woocommerce/index.js
Labels: Store, [Status] Ready to Merge

#48572 Plugins: Remove last arg of doActionOverSelected
  client/my-sites/plugins/plugins-list/index.jsx
Labels: Plugins, [Status] Needs Review, [Type] Janitorial

#48712 Checkout: Remove unused google vouchers code
  client/blocks/product-purchase-features-list/google-vouchers.jsx
  client/blocks/product-purchase-features-list/test/product-purchase-features-list.jsx
  client/blocks/product-purchase-features-list/test/video-audio-posts.jsx
  client/components/data/query-site-vouchers/index.jsx
  client/my-sites/checkout/checkout-thank-you/google-voucher/index.jsx
  client/my-sites/checkout/checkout-thank-you/google-voucher/style.scss
  client/my-sites/checkout/checkout-thank-you/google-voucher/terms-and-conditions.jsx
  client/my-sites/marketing/business-tools/style.scss
  client/my-sites/marketing/tools/style.scss
  client/state/action-types.js
  client/state/sites/reducer.js
  client/state/sites/test/reducer.js
  client/state/sites/vouchers/README.md
  client/state/sites/vouchers/actions.js
  client/state/sites/vouchers/reducer.js
  client/state/sites/vouchers/schema.js
  client/state/sites/vouchers/selectors.js
  client/state/sites/vouchers/service-types.js
  client/state/sites/vouchers/test/actions.js
  client/state/sites/vouchers/test/fixture/index.js
  client/state/sites/vouchers/test/reducer.js
  client/state/sites/vouchers/test/selectors.js
Labels: Checkout, Plans, [Status] Needs Review, [Type] Janitorial

#47614 Step-by-step credentials verification (progress only)
  .eslintignore
  .prettierignore
  client/jetpack-cloud/sections/settings/advanced-credentials/index.tsx
  client/jetpack-cloud/sections/settings/advanced-credentials/verification/index.tsx
  client/jetpack-cloud/sections/settings/advanced-credentials/verification/style.scss
  client/state/data-layer/wpcom/activity-log/update-credentials/index.js
  client/state/data-layer/wpcom/activity-log/update-credentials/vendor/README.txt
  client/state/data-layer/wpcom/activity-log/update-credentials/vendor/credentials-test-progress.ts
  client/state/data-layer/wpcom/activity-log/update-credentials/vendor/index.ts
  client/state/data-layer/wpcom/activity-log/update-credentials/vendor/stream-result.ts
  client/state/data-layer/wpcom/activity-log/update-credentials/vendor/transport-error.ts
  client/state/jetpack/credentials/actions.js
  client/state/jetpack/credentials/reducer.js
  client/state/selectors/get-jetpack-credentials-update-progress.js
Labels: Rewind, [Status] Needs Review

#48570 Plugins: Reduxify plugin sites
  client/lib/plugins/README.md
  client/lib/plugins/store.js
  client/lib/plugins/test/store.js
  client/my-sites/plugins/notices.jsx
  client/my-sites/plugins/plugin-meta/index.jsx
  client/my-sites/plugins/plugin-meta/test/index.js
  client/my-sites/plugins/plugin-site-list/index.jsx
  client/my-sites/plugins/plugin-site-update-indicator/index.jsx
  client/my-sites/plugins/plugin.jsx
  client/state/plugins/installed/actions.js
  client/state/plugins/installed/selectors.js
  client/state/plugins/installed/test/selectors.js
Labels: Plugins, State, [Status] Needs Review, [Type] Enhancement

#48430 Fetch Podcast Title From Gutenboarding
  client/landing/gutenboarding/gutenboard.tsx
  client/landing/gutenboarding/hooks/use-podcast-title.ts
  client/landing/gutenboarding/hooks/use-site-title.ts
Labels: Podcasting, [Status] Needs Review

#48694 Jetpack Pricing Page: Make Jetpack CRM Monthly product disabled.
  client/components/jetpack/card/jetpack-product-card-i5/index.tsx
  client/components/jetpack/card/jetpack-product-card-i5/style.scss
  client/my-sites/plans/jetpack-plans/constants.ts
  client/my-sites/plans/jetpack-plans/product-card-i5/index.tsx
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
Labels: Jetpack, Plans, [Status] Needs Review

#48720 Plans Page: Adds estimate for Search
  client/components/jetpack/card/jetpack-product-card-i5/index.tsx
  client/components/jetpack/card/jetpack-product-card-i5/style.scss
  client/landing/gutenboarding/hooks/use-podcast-title.ts
  client/my-sites/plans/jetpack-plans/product-card-i5/index.tsx
  client/my-sites/plans/jetpack-plans/types.ts
  client/my-sites/plans/jetpack-plans/use-item-price.ts
  client/my-sites/plans/jetpack-plans/utils.ts
  client/state/sites/products/assembler.js
Labels: Plans, [Status] Needs Review

#48717 Styles: Add overrides for ButtonGroup, RadioControl, and fix on Button style
  client/assets/stylesheets/_wp-components-overrides.scss
Labels: Components, [Status] Needs Review, [Type] Enhancement

#48106 Step-by-step credentials: full verification screen
  client/jetpack-cloud/sections/settings/advanced-credentials/index.tsx
  client/jetpack-cloud/sections/settings/advanced-credentials/verification/index.tsx
  client/jetpack-cloud/sections/settings/advanced-credentials/verification/style.scss
  client/my-sites/checkout/upsell-nudge/index.jsx
  client/state/action-types.js
  client/state/data-layer/wpcom/activity-log/get-credentials/index.js
  client/state/data-layer/wpcom/activity-log/update-credentials/index.js
  client/state/jetpack/credentials/reducer.js
  client/state/selectors/get-jetpack-credentials-update-error.ts
Labels: Rewind, [Status] Needs Review

#48412 Jetpack Backup: On the Backup page, show when there is a backup in progress
  client/components/jetpack/backup-card/backup-in-progress.tsx
  client/components/jetpack/backup-card/backup-just-completed.tsx
  client/components/jetpack/backup-card/hooks.ts
  client/components/jetpack/backup-card/style.scss
  client/components/jetpack/daily-backup-status/index-alternate.tsx
  client/components/jetpack/daily-backup-status/index.jsx
  client/components/jetpack/daily-backup-status/status-card/backup-in-progress.tsx
  client/components/jetpack/daily-backup-status/status-card/backup-just-completed.tsx
  client/components/jetpack/daily-backup-status/test/index.jsx
  client/lib/jetpack/hooks/use-date-with-offset.ts
  client/lib/site/timezone.js
  client/my-sites/backup/backup-date-picker/hooks.ts
  client/my-sites/backup/backup-date-picker/index.tsx
  client/my-sites/backup/backup-date-picker/test/hooks.js
  client/my-sites/backup/hooks.js
  client/my-sites/backup/main.jsx
  client/my-sites/backup/status/index.jsx
  client/my-sites/backup/status/simplified-i4.jsx
  client/state/rewind/selectors/get-in-progress-backup-for-site.ts
  client/state/rewind/selectors/index.ts
  client/state/rewind/selectors/site-has-backup-in-progress.ts
  client/state/rewind/selectors/site-has-realtime-backups.ts
Labels: Jetpack Backup, Jetpack Cloud, [Status] Needs Design Review, [Status] Needs Review, [Status] String Freeze

#48612 Fix wording on the Payment Methods listing page
  client/me/purchases/payment-methods/payment-method-list.jsx
Labels: Billing, [Estimate] 1, [Status] Ready to Merge, [Status] String Freeze

#48737 Anchor Gutenboarding: Hide locale button
  client/landing/gutenboarding/components/header/index.tsx
Labels: [Status] Needs Review

#48705 AnchorFM: Augment Signup Events with AnchorFM Flow
  client/landing/gutenboarding/constants.ts
  client/landing/gutenboarding/hooks/use-on-site-creation.ts
  client/landing/gutenboarding/hooks/use-track-onboarding-start.ts
  client/landing/gutenboarding/lib/analytics/index.ts
  client/landing/gutenboarding/lib/analytics/types.ts
  client/landing/gutenboarding/path.ts
Labels: [Status] Needs Review

#48290 desktop: Bump version to 6.7.0
  .circleci/config.yml
  client/desktop/lib/menu/main-menu.js
  client/desktop/lib/menu/view-menu.js
  desktop/bin/make-changelog.sh
  desktop/package.json
  desktop/public_desktop/preferences.html
Labels: Releases, [Status] Needs Review

#48594 Deduplicate browserslist
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48592 Deduplicate babel-plugin-dynamic-import-node
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48590 Deduplicate aria-query
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48591 Deduplicate autoprefixer
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48593 Deduplicate babel-preset-current-node-syntax
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48669 Add "Renews at {renewal_price} / year" label to domain picker suggestion items
  packages/domain-picker/src/domain-picker/style.scss
  packages/domain-picker/src/domain-picker/suggestion-item.tsx
  packages/domain-picker/test/suggestion-item.tsx
Labels: Focused Launch, [Status] Needs Review

#48671 Security: Reduxify password page notices
  client/me/security/controller.js
Labels: Security, State, [Status] Needs Review, [Type] Enhancement

#48711 Themes: Reduxify notices in theme upload
  client/my-sites/themes/theme-upload/index.jsx
Labels: State, Themes, [Status] Needs Review, [Type] Enhancement

#48302 Drop support for package-relative imports
  .eslintrc.js
  client/webpack.config.desktop.js
  client/webpack.config.js
  client/webpack.config.node.js
  packages/eslint-plugin-wpcalypso/.eslintrc.js
  packages/eslint-plugin-wpcalypso/lib/rules/index.js
  packages/eslint-plugin-wpcalypso/lib/rules/no-package-relative-imports.js
  packages/eslint-plugin-wpcalypso/lib/rules/test/no-package-relative-imports.js
  packages/webpack-config-flag-plugin/test/fixtures/.eslintrc.js
  test/client/jest.config.js
  test/integration/jest.config.js
  test/server/jest.config.js
Labels: [Status] Needs Review

#48454 Account: use Redux to change user password
  client/me/account-password/index.jsx
  client/me/security/controller.js
  client/state/action-types.js
  client/state/data-layer/wpcom/me/settings/index.js
  client/state/user-settings/actions.js
  client/state/user-settings/reducer.js
  client/state/user-settings/selectors.js
  client/state/user-settings/test/reducer.js
Labels: Me, [Status] Needs Review

#48670 Settings: Reduxify notices in SiteTools
  client/my-sites/site-settings/site-tools/index.jsx
Labels: Site Settings, State, [Status] Needs Review, [Type] Enhancement

#48689 Settings: Reduxify notices in SEO settings
  client/my-sites/site-settings/seo-settings/form.jsx
  client/my-sites/site-settings/seo-settings/main.jsx
  client/my-sites/site-settings/seo-settings/site-verification.jsx
Labels: SEO Tools, Site Settings, [Status] Needs Review, [Type] Enhancement

#48715 G Suite: Update Email Comparison page for Google Workspace
  client/assets/images/email-providers/google-workspace.svg
  client/lib/cart-values/cart-items.js
  client/lib/cart/action-types.js
  client/lib/cart/actions.js
  client/lib/cart/store/index.js
  client/my-sites/email/email-providers-comparison/index.jsx
  config/development.json
  config/wpcalypso.json
Labels: G Suite, [Status] Ready to Merge

#48716 Email: Enable renewals and cancellation for Titan Mail
  client/lib/cart-values/cart-items.js
  client/lib/products-values/index.js
  client/lib/products-values/is-titan-mail.js
  client/me/purchases/manage-purchase/index.jsx
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js
Labels: [Status] Ready to Merge

#48735 Devdocs: Add the color scheme picker to the WP components library
  client/devdocs/design/wordpress-components-gallery/index.tsx
Labels: Components, DevDocs, [Status] Needs Review

#48738 Add Custom Description for Rollback Fixer
  client/components/jetpack/threat-item/utils.ts
Labels: Jetpack Scan, [Status] Needs Review

#48774 Adding feature flag for Cloudflare partnership dev work
  config/desktop-development.json
  config/desktop.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#48718 Billing: Add physical address to self-serve receipts
  client/me/purchases/billing-history/receipt.jsx
  client/me/purchases/billing-history/style.scss
Labels: [Estimate] 2, [Status] Needs Design Review, [Status] Ready to Merge

#48553 Payment Methods: add PayPal to change payment method form
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/me/purchases/manage-purchase/change-payment-method/assignment-processor-functions.ts
  client/me/purchases/manage-purchase/change-payment-method/index.jsx
  client/me/purchases/manage-purchase/change-payment-method/tos-text.tsx
  client/me/purchases/manage-purchase/change-payment-method/url-event-handlers.ts
  client/me/purchases/manage-purchase/change-payment-method/use-create-assignable-payment-methods.ts
  client/my-sites/checkout/composite-checkout/use-create-payment-methods.js
  packages/calypso-stripe/src/index.tsx
  packages/composite-checkout/src/components/use-process-payment.ts
  packages/composite-checkout/src/lib/invalid-payment-processor-response-error.ts
  packages/composite-checkout/src/lib/payment-methods/paypal.js
  packages/composite-checkout/src/public-api.ts
Labels: Payment Methods, [Status] Needs Review

#48659 Fix Store info icon alignment
  client/my-sites/sidebar/index.jsx
  client/my-sites/sidebar/style.scss
Labels: [Status] Ready to Merge

#48726 Adjust padding for the button in the store move notice
  client/extensions/woocommerce/app/dashboard/style.scss
Labels: [Status] Ready to Merge

#48641 Add from-calypso arg to WC URL used during and after sunsetting Store
  client/my-sites/sidebar/index.jsx
  client/my-sites/sidebar/test/sidebar.js
Labels: [Status] Ready to Merge

#48784 Editor welcome tour: Remove editor welcome tour images and replace with images urls from the CDN
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-welcome-tour/src/images/add_block.gif
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-welcome-tour/src/images/all_blocks.gif
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-welcome-tour/src/images/make_bold.gif
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-welcome-tour/src/images/more_options.gif
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-welcome-tour/src/images/move_block.gif
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-welcome-tour/src/images/undo.gif
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-welcome-tour/src/images/welcome.png
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-welcome-tour/src/tour-content.js
Labels: [Status] Needs Review

#48783 Welcome Tour: update copy and add i18n wrappers
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-welcome-tour/src/tour-card.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-welcome-tour/src/tour-content.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-welcome-tour/src/tour-launch.js
Labels: Editing Toolkit, Editor Welcome, [Status] Needs Review

#48665 Plugins: Reduxify getPlugins
  client/my-sites/plugins/main.jsx
  client/my-sites/plugins/plugin-item/plugin-item.jsx
  client/my-sites/plugins/plugin-list-header/index.jsx
  client/my-sites/plugins/plugins-list/index.jsx
  client/my-sites/plugins/plugins-list/test/fixtures/index.js
  client/my-sites/plugins/plugins-list/test/index.jsx
  client/state/plugins/installed/selectors.js
  client/state/plugins/installed/test/selectors.js
Labels: Plugins, State, [Status] Needs Review, [Type] Enhancement

#48345 Plans: Roll out Monthly pricing globally
  client/components/plans/plan-pill/index.jsx
  client/components/plans/plan-pill/style.scss
  client/lib/plans/plans-list.js
  client/my-sites/checkout/composite-checkout/components/item-variation-picker.tsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-review.js
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.js
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js
  client/my-sites/checkout/composite-checkout/hooks/product-variants.js
  client/my-sites/checkout/composite-checkout/lib/get-plan-features.ts
  client/my-sites/checkout/composite-checkout/lib/translate-cart.ts
  client/my-sites/plan-features/header.jsx
  client/my-sites/plan-features/index.jsx
  client/my-sites/plan-features/style.scss
  client/my-sites/plan-features/test/header.jsx
  client/my-sites/plan-price/index.jsx
  client/my-sites/plans-features-main/free-plan-banner.tsx
  client/my-sites/plans-features-main/index.jsx
  client/my-sites/plans-features-main/plan-type-selector.tsx
  client/my-sites/plans-features-main/style.scss
  client/my-sites/plans-features-main/test/free-plan-banner.jsx
  client/my-sites/plans-features-main/test/index.jsx
  client/my-sites/plans/main.jsx
  client/signup/steps/domains/index.jsx
  client/signup/steps/plans/index.jsx
  client/state/marketing/selectors.ts
Labels: [Status] Needs Review

#48764 Components: Reduxify notices in UploadDropZone
  client/blocks/upload-drop-zone/index.jsx
Labels: Components, State, [Status] Needs Review, [Type] Enhancement

#48757 Deduplicate caniuse-lite
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48755 Deduplicate compute-scroll-into-view
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48754 Deduplicate chokidar
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48753 Deduplicate chalk
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48664 react-i18n: Upgrade @wordpress/hooks dependency version
  packages/react-i18n/package.json
  packages/react-i18n/src/index.tsx
  yarn.lock
Labels: Packages, [Status] Needs Review, i18n

#48119 Domain Picker: Added "Use a domain I own" item
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/utils.ts
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
  client/blocks/editor-launch-modal/index.tsx
  client/gutenberg/editor/calypsoify-iframe.tsx
  packages/domain-picker/package.json
  packages/domain-picker/src/domain-picker/index.tsx
  packages/domain-picker/src/domain-picker/style.scss
  packages/domain-picker/src/domain-picker/use-your-domain-item.tsx
  packages/domain-picker/test/use-your-domain-item.tsx
  packages/domain-picker/tsconfig.json
  packages/launch/src/context.ts
  packages/launch/src/focused-launch/domain-details/index.tsx
  packages/launch/src/launch/index.tsx
  packages/onboarding/src/action-buttons/index.tsx
  packages/onboarding/src/action-buttons/style.scss
  packages/onboarding/src/index.ts
Labels: Focused Launch, [Status] Needs e2e Testing

#48535 Focused Launch: Debounce domain search for focused launch on key press
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/name-step/index.tsx
  packages/data-stores/src/launch/actions.ts
  packages/data-stores/src/launch/reducer.ts
  packages/data-stores/src/launch/selectors.ts
  packages/launch/package.json
  packages/launch/src/focused-launch/summary/index.tsx
  packages/launch/src/hooks/use-title.ts
Labels: Focused Launch, [Type] Bug

#48797 Upsells offers copy change
  client/my-sites/checkout/upsell-nudge/business-plan-upgrade-upsell/index.jsx
  client/my-sites/checkout/upsell-nudge/premium-plan-upgrade-upsell/index.jsx
Labels: [Status] Needs Review

#48369 Jetpack Licensing: Add the foundation for the Jetpack Licensing Portal
  client/components/data/query-jetpack-partner-portal-partners/index.js
  client/jetpack-cloud/sections/partner-portal/controller.tsx
  client/jetpack-cloud/sections/partner-portal/header/index.tsx
  client/jetpack-cloud/sections/partner-portal/header/style.scss
  client/jetpack-cloud/sections/partner-portal/index.ts
  client/jetpack-cloud/sections/partner-portal/select-partner-key/index.tsx
  client/jetpack-cloud/sections/partner-portal/select-partner-key/style.scss
  client/jetpack-cloud/sections/partner-portal/sidebar/index.tsx
  client/jetpack-cloud/sections/partner-portal/style.scss
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/sections.js
  client/state/action-types.js
  client/state/partner-portal/actions/index.js
  client/state/partner-portal/actions/partners.ts
  client/state/partner-portal/index.d.ts
  client/state/partner-portal/init.js
  client/state/partner-portal/package.json
  client/state/partner-portal/reducer/index.js
  client/state/partner-portal/reducer/partners.ts
  client/state/partner-portal/selectors/index.js
  client/state/partner-portal/selectors/partners.ts
  config/_shared.json
  config/jetpack-cloud-development.json
Labels: Jetpack Cloud, [Status] Needs Review

#48791 Batch de-duplication
  yarn.lock
Labels: [Status] Needs Review

#48388 Add Dialog to Classic Editor Redirect Flow
  client/desktop/window-handlers/external-links/editor/index.js
  client/desktop/window-handlers/external-links/index.js
  client/desktop/window-handlers/external-links/open-in-browser/index.js
Labels: [Status] Needs Review

#48781 Add/richer titan navigation
  client/my-sites/email/controller.js
  client/my-sites/email/email-management/gsuite-users-card/index.jsx
  client/my-sites/email/email-management/index.jsx
  client/my-sites/email/email-management/titan-control-panel-login-card/index.jsx
  client/my-sites/email/email-management/titan-functions.js
  client/my-sites/email/email-management/titan-management-iframe/index.jsx
  client/my-sites/email/email-management/titan-management-nav/index.jsx
  client/my-sites/email/index.js
  client/my-sites/email/paths.js
Labels: [Status] Needs Review

#48474 Template Selector: Use patterns API
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/class-starter-page-templates.php
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/index.js
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/components/template-selector-control.js
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/components/template-selector-item.js
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/components/test/__snapshots__/template-selector-control.test.js.snap
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/components/test/__snapshots__/template-selector-preview.test.js.snap
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/components/test/helpers/templates-blocks-helpers.js
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/components/test/template-selector-control.test.js
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/components/test/template-selector-preview.test.js
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/index.js
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/utils/tracking.js
Labels: [Goal] Page Templates, [Status] Needs Review, [Type] Enhancement

#48821 Update default Titan feature flags
  config/development.json
  config/wpcalypso.json
Labels: [Status] Ready to Merge

#48820 Add tooling issue template
  .github/ISSUE_TEMPLATE/tooling_request.md
Labels: [Type] Tooling

#48744 Customizer: Change Customize to use checkout url for adding a theme
  client/my-sites/customize/main.jsx
Labels: Customizer, Shopping Cart, [Status] Ready to Merge

#48745 Admin Menu: Show update count in expendable sidebar menus
  client/layout/sidebar/expandable-heading.jsx
  client/layout/sidebar/style.scss
  client/my-sites/sidebar-unified/menu.jsx
Labels: Nav Unification, Nav Unification [Alpha], [Type] Bug

#48829 Editing Toolkit: Update to 2.9.0
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/readme.txt
  apps/editing-toolkit/package.json
Labels: Editing Toolkit, [Status] Needs Review

#48213 Reduxify importers
  client/lib/importer/actions.js
  client/lib/importer/store.js
  client/lib/importer/test/api-interaction.js
  client/my-sites/importer/file-importer.jsx
  client/my-sites/importer/importer-action-buttons/close-button.jsx
  client/my-sites/importer/importer-action-buttons/done-button.jsx
  client/my-sites/importer/importing-pane.jsx
  client/my-sites/importer/section-import.jsx
  client/my-sites/importer/site-importer/index.jsx
  client/my-sites/importer/site-importer/site-importer-input-pane.jsx
  client/my-sites/importer/uploading-pane.jsx
  client/state/imports/actions.js
  client/state/imports/api.js
  client/state/imports/reducer.js
  client/state/imports/selectors.js
  client/state/imports/site-importer/actions.js
  client/state/imports/site-importer/reducer.js
  client/state/imports/test/api-interaction.js
  client/state/imports/test/api-payloads/defunct-importer.json
  client/state/imports/test/api-payloads/expired-importer.json
  client/state/imports/test/api-payloads/no-imports.json
  client/state/imports/test/api-payloads/running-importer.json
  client/state/imports/uploads/reducer.js
Labels: Import, [Status] Needs Review

#48691 Update Upwork Banner to Point to DFIM
  client/blocks/upwork-banner/index.jsx
  client/blocks/upwork-banner/test/__snapshots__/index.js.snap
  client/lib/abtest/active-tests.js
  client/my-sites/themes/theme-showcase.jsx
Labels: [Status] Needs Review

#48765 State: Reduxify immediate login notices
  client/state/lib/middleware.js
Labels: State, [Status] Needs Review, [Type] Enhancement

#48792 Deduplicate cross-spawn
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48793 Deduplicate css-loader
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48795 Deduplicate debug
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48802 Deduplicate enzyme-adapter-react-16
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48801 Deduplicate enzyme-to-json
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#48645 localizeUrl: Don't modify contact URL when logged-in
  packages/i18n-utils/src/localize-url.tsx
  packages/i18n-utils/src/test/localize-url.js
Labels: [Status] Needs Review, i18n

#48855 Signup: Allow only public-api for social signup redirect URL
  client/signup/config/flows.js
  client/signup/steps/user/index.jsx
Labels: Social Signup, [Status] Needs Review, [Type] Enhancement

#48836 Jetpack Cloud: Fix Pricing page shown twice in a row
  client/components/jetpack/card/jetpack-free-card-button/index.tsx
  client/jetpack-cloud/sections/pricing/controller.tsx
  client/my-sites/plans/jetpack-plans/products-grid-i5/index.tsx
Labels: Jetpack Cloud, Plans, [Status] Needs Review

#48828 Fix Titan navigation styles
  client/my-sites/email/email-management/titan-management-nav/index.jsx
  client/my-sites/email/email-management/titan-management-nav/style.scss
Labels: [Status] Needs Review

#48762 update: account password data
  client/lib/account-password-data/index.js
  client/lib/generate-password/index.js
  client/me/account-password/index.jsx
  client/me/security/controller.js
  client/me/security/main.jsx
Labels: Security, [Status] Needs Review

#48730 reduxify: `withFormBase` and `me/profile`
  client/me/controller.js
  client/me/form-base/with-form-base.jsx
  client/me/profile/index.jsx
  client/state/action-types.js
  client/state/data-layer/wpcom/me/settings/index.js
  client/state/data-layer/wpcom/me/settings/test/index.js
  client/state/selectors/get-user-settings.js
  client/state/user-settings/actions.js
  client/state/user-settings/reducer.js
  client/state/user-settings/selectors.js
  client/state/user-settings/test/reducer.js
Labels: [Status] Needs Review

#48794 Fixes cloud.jetpack.com with nav-unification enabled:
  client/assets/stylesheets/_nav-unification.scss
  client/blocks/site/index.jsx
  client/components/jetpack/sidebar/style.scss
  client/components/sidebar-navigation/index.jsx
Labels: [Status] Ready to Merge

#48807 End the Free Plans Domain Upsell experiment
  client/lib/abtest/active-tests.js
  client/lib/signup/step-actions/index.js
Labels: [Status] Needs Review

#48810 Enable seen counts in production for automatticians
  client/blocks/reader-combined-card/index.jsx
  client/blocks/reader-combined-card/post.jsx
  client/blocks/reader-feed-header/index.jsx
  client/blocks/reader-full-post/index.jsx
  client/blocks/reader-post-card/index.jsx
  client/blocks/reader-post-options-menu/index.jsx
  client/reader/a8c/main.jsx
  client/reader/following/main.jsx
  client/reader/get-helpers.js
  client/reader/stream/x-post.jsx
  client/state/reader-ui/seen-posts/selectors.js
  client/state/selectors/is-feed-wpforteams.js
  config/production.json
Labels: [Status] Needs Review

#48838 Domains: Update MapDomain and MapDomainStep to use withShoppingCart
  client/components/domains/map-domain-step/index.jsx
  client/my-sites/domains/controller.jsx
  client/my-sites/domains/map-domain/index.jsx
  client/signup/steps/domains/index.jsx
Labels: Domains, Shopping Cart, [Estimate] 1, [Status] Ready to Merge

#48834 Help: Remove unused feature flag
  client/me/help/controller.js
  client/me/help/index.js
  config/desktop-development.json
  config/desktop.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Type] Janitorial

#48743 Billing: Update PlanBillingPeriod to remove CartStore action
  client/me/purchases/manage-purchase/plan-details/billing-period.jsx
  client/me/purchases/manage-purchase/plan-details/test/billing-period.jsx
Labels: Billing, Shopping Cart, [Status] Needs Review

#48782 Guided transfer: Update checkout redirects to use product slug instead of cart modification
  client/my-sites/exporter/guided-transfer-card/complete-purchase-notice.jsx
  client/my-sites/guided-transfer/host-credentials-page/index.jsx
Labels: Checkout, Export, [Status] Ready to Merge

#48674 Updating event names and display criteria for nav bar.
  client/my-sites/marketing/business-tools/index.tsx
  client/my-sites/marketing/main.jsx
  client/my-sites/marketing/tools/index.tsx
Labels: [Status] Needs Review

#48871 Email: Update post checkout page for Titan Mail
  client/my-sites/checkout/checkout-thank-you/features-header.jsx
  client/my-sites/checkout/checkout-thank-you/header.jsx
  client/my-sites/checkout/checkout-thank-you/index.jsx
Labels: [Status] Ready to Merge

#48869 Jetpack Cloud: construct wp-admin URL from site in query parameters
  client/components/jetpack/card/jetpack-free-card-button/index.tsx
Labels: Jetpack Cloud, [Status] Needs Review

#48843 Domains: Add busy state to "Add" button
  client/components/domains/map-domain-step/index.jsx
Labels: Domains, [Estimate] 1, [Status] Ready to Merge

#48845 AnchorFM: Font Selection CTA
  client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
Labels: [Status] Needs Review
