Repository Automattic/wp-calypso, pull requests merged in 2021-02, with the labels that each got.

#49100 Fix case where uninstall of WC then going to WC install page would cause redirect to WP Core with access denied
  client/extensions/woocommerce/app/dashboard/index.js
Labels: [Status] Needs Review

#49099 Fix business sub without WC showing both Store and WooCommerce
  client/my-sites/sidebar/index.jsx
  client/my-sites/sidebar/test/sidebar.js
Labels: [Status] Needs Review

#49407 ci(docker): Speed up docker image creation
  .teamcity/settings.kts
  client/webpack.common.js
  desktop/Makefile
  docs/development-workflow.md
  docs/install.md
  package.json
Labels: [Status] Needs Review

#49450 Deduplicate is-regex
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49449 Deduplicate is-core-module
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49448 Deduplicate is-callable
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49447 Deduplicate interpret
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49446 Deduplicate inquirer
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49445 Deduplicate ignore
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49408 Nav Unification: address color schemes Beta feedback
  client/assets/stylesheets/_nav-unification.scss
  client/my-sites/sidebar-unified/style.scss
  packages/calypso-color-schemes/src/shared/color-schemes/_blue.scss
  packages/calypso-color-schemes/src/shared/color-schemes/_sunrise.scss
Labels: Nav Unification, Nav-Unification [Beta], [Status] Needs Review

#49185 Fix how we handle invalid-quantity errors for Titan mailboxes
  client/my-sites/email/titan-mail-quantity-selection/index.jsx
Labels: [Status] Needs Review

#49189 Adds theme selection task to site checklist
  client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
  client/state/data-layer/wpcom/checklist/index.js
Labels: [Status] Needs Review

#49405 Checkout: Reduxify notices in PurchaseModal
  client/my-sites/checkout/upsell-nudge/purchase-modal/util.js
Labels: Checkout, [Status] Needs Review, [Type] Enhancement

#49476 Security2faSMSSettings: clean up `verifyByApp` class prop
  client/me/security-2fa-sms-settings/index.jsx
Labels: 2FA, Security, [Status] Needs Review

#49518 PlansGrid: Use selected plan's billing period to initialize billingPeriod state
  packages/plans-grid/src/hooks/use-supported-plans.ts
  packages/plans-grid/src/plans-accordion-item/index.tsx
  packages/plans-grid/src/plans-accordion/index.tsx
  packages/plans-grid/src/plans-details/index.tsx
  packages/plans-grid/src/plans-grid/index.tsx
  packages/plans-grid/src/plans-table/index.tsx
  packages/plans-grid/src/plans-table/plan-item.tsx
  packages/plans-grid/src/stores.ts
Labels: Focused Launch, [Goal] New Onboarding, [Status] Needs Review

#49399 Data Layer: Move the home settings import to sites
  client/state/site-settings/actions.js
  client/state/sites/actions.js
Labels: Pages, Site Settings, Sites, [Pri] Normal, [Status] Needs Review, [Type] Bug

#49524 Fix broken plans styles related to scrolling
  client/my-sites/plan-features/style.scss
Labels: [Status] Needs Review

#49464 DomainPicker: update price formatting
  packages/data-stores/src/domain-suggestions/resolvers.ts
  packages/data-stores/src/domain-suggestions/test/reducer.ts
  packages/data-stores/src/domain-suggestions/types.ts
  packages/data-stores/src/domain-suggestions/utils.ts
  packages/data-stores/src/plans/resolvers.ts
  packages/domain-picker/src/domain-picker/suggestion-item.tsx
  packages/launch/src/utils.ts
Labels: [Goal] New Onboarding, [Status] Needs Review

#49352 Nav Unification: Adds a fallback menu for Jetpack sites
  client/my-sites/sidebar-unified/static-data/jetpack-fallback-menu.js
  client/my-sites/sidebar-unified/use-site-menu-items.js
Labels: [Status] Needs Review

#49294 build(webpack): Enable contenthash naming strategy for JS and CSS files
  build-tools/webpack/extract-manifest-plugin.js
  client/webpack.config.js
  package.json
  packages/calypso-build/package.json
  packages/webpack-rtl-plugin/package.json
  yarn.lock
Labels: [Status] Needs Review

#49490 Remove tagline in latest version of pricing page
  client/jetpack-cloud/sections/pricing/header/index.tsx
Labels: Jetpack Cloud, Plans, [Status] Needs Review

#49526 i18n: Fix language picker incomplete notice translatable string
  client/components/language-picker/modal.tsx
Labels: [Status] Needs Review, i18n

#49474 Remove pricing v1 and v2
  client/components/jetpack/card/jetpack-free-card-alt/index.tsx
  client/components/jetpack/card/jetpack-free-card-alt/style.scss
  client/components/jetpack/card/jetpack-product-card-alt-2/assets/ribbon.svg
  client/components/jetpack/card/jetpack-product-card-alt-2/features-item.tsx
  client/components/jetpack/card/jetpack-product-card-alt-2/features-product-slide-out.tsx
  client/components/jetpack/card/jetpack-product-card-alt-2/features.tsx
  client/components/jetpack/card/jetpack-product-card-alt-2/index.tsx
  client/components/jetpack/card/jetpack-product-card-alt-2/style.scss
  client/components/jetpack/card/jetpack-product-card-alt-2/types.ts
  client/components/jetpack/card/jetpack-product-card-alt/features-item.tsx
  client/components/jetpack/card/jetpack-product-card-alt/features.tsx
  client/components/jetpack/card/jetpack-product-card-alt/index.tsx
  client/components/jetpack/card/jetpack-product-card-alt/style.scss
  client/jetpack-cloud/sections/pricing/header/index.tsx
  client/jetpack-cloud/sections/pricing/style.scss
  client/jetpack-connect/controller.js
  client/jetpack-connect/style.scss
  client/lib/plans/features-list.js
  client/lib/plans/plans-list.js
  client/lib/products-values/translations.js
  client/my-sites/plans/jetpack-plans/abtest.ts
  client/my-sites/plans/jetpack-plans/constants.ts
  client/my-sites/plans/jetpack-plans/iterations.ts
  client/my-sites/plans/jetpack-plans/plans-filter-bar/index.tsx
  client/my-sites/plans/jetpack-plans/plans-filter-bar/style.scss
  client/my-sites/plans/jetpack-plans/product-card-alt-2/index.tsx
  client/my-sites/plans/jetpack-plans/product-card-alt/index.tsx
  client/my-sites/plans/jetpack-plans/product-grid/products-order.ts
  client/my-sites/plans/jetpack-plans/product-grid/utils.ts
  client/my-sites/plans/jetpack-plans/products-grid-alt-2/index.tsx
  client/my-sites/plans/jetpack-plans/products-grid-alt-2/style.scss
  client/my-sites/plans/jetpack-plans/products-grid-alt/index.tsx
  client/my-sites/plans/jetpack-plans/products-grid-alt/style.scss
  client/my-sites/plans/jetpack-plans/records-details-alt/index.tsx
  client/my-sites/plans/jetpack-plans/records-details/styles.scss
  client/my-sites/plans/jetpack-plans/selector.tsx
  client/my-sites/plans/jetpack-plans/test/utils.js
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
  client/my-sites/plans/jetpack-plans/utils.ts
Labels: Jetpack Cloud, Plans, [Status] Needs Jetpack e2e Testing, [Status] Needs Review

#48938 Anchor: Gutenboarding Launch works immediately without domain or plan selection
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/index.php
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-launch-sidebar.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/constants.ts
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-button/index.ts
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-modal/index.tsx
  packages/data-stores/src/launch/actions.ts
  packages/data-stores/src/launch/index.ts
  packages/data-stores/src/launch/reducer.ts
Labels: [Status] Ready to Merge

#49475 deps: Replace `warn` with `@wordpress/warning`
  client/components/domains/registrant-extra-info/with-contact-details-validation.jsx
  client/extensions/woocommerce/app/dashboard/index.js
  client/extensions/woocommerce/app/promotions/fields/promotion-applies-to-field/applies-to-filtered-list.js
  client/extensions/woocommerce/app/promotions/fields/promotion-applies-to-field/index.js
  client/extensions/woocommerce/app/promotions/promotion-form.js
  client/extensions/woocommerce/state/data-layer/products/index.js
  client/extensions/woocommerce/state/data-layer/products/test/index.js
  client/extensions/woocommerce/state/sites/coupons/handlers.js
  client/lib/create-selector/index.js
  client/lib/warn/README.md
  client/lib/warn/index.js
  client/my-sites/plans-features-main/index.jsx
  client/package.json
  client/state/data-layer/wpcom-http/utils.js
  client/state/data-layer/wpcom/read/streams/index.js
  client/state/data-layer/wpcom/read/streams/test/index.js
  client/state/happychat/ui/test/index.js
  client/state/reader/streams/test/reducer.js
  client/state/reader/watermarks/test/reducer.js
  client/state/test/utils.js
  client/state/utils/schema-utils.js
Labels: Maintenance, Packages, [Status] Needs Review, dependencies

#49481 Change DIFM CTA href to string- no curly braces needed.
  client/blocks/upwork-banner/index.jsx
Labels: [Status] Needs Review

#49496 Update e2e testing documentation
  test/e2e/README.md
  test/e2e/docs/config_values.md
  test/e2e/docs/environment_variables.md
  test/e2e/docs/overview.md
  test/e2e/docs/running-tests.md
  test/e2e/docs/setup.md
  test/e2e/docs/style-guide.md
  test/e2e/docs/troubleshooting.md
  test/e2e/docs/writing_tests.md
Labels: [Status] Needs Review

#49554 e2e: Fix renew test for local runs
  test/e2e/lib/pages/purchases-page.js
Labels: [Status] Needs Review

#49561 Premium Content: Remove from the Editing Toolkit plugin
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/buttons/edit.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/buttons/index.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/buttons/save.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/blocks.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/context.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/controls.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/edit.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/icons.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/index.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/inspector.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/new-plan.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/plan.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/plans.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/save.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/stripe-nudge.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/tab.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/tabs.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/icon.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/logged-out-view/deprecated/index.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/logged-out-view/deprecated/v1/index.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/logged-out-view/deprecated/v2/index.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/logged-out-view/edit.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/logged-out-view/index.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/logged-out-view/save.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/login-button/color-edit.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/login-button/color-props.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/login-button/edit.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/login-button/index.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/login-button/save.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/subscriber-view/deprecated/v1/index.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/subscriber-view/edit.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/subscriber-view/index.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/subscriber-view/save.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/editor.css
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/index.js
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/premium-content.php
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/style.css
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/subscription-service/class-jetpack-token-subscription-service.php
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/subscription-service/class-jwt.php
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/subscription-service/class-subscription-service.php
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/subscription-service/class-token-subscription-service.php
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/subscription-service/class-token-subscription.php
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/subscription-service/class-unconfigured-subscription-service.php
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/subscription-service/class-wpcom-offline-subscription-service.php
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/subscription-service/class-wpcom-token-subscription-service.php
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/subscription-service/include.php
  apps/editing-toolkit/editing-toolkit-plugin/premium-content/view.js
  apps/editing-toolkit/package.json
Labels: Editing Toolkit, Premium Content, [Status] Needs Review

#49057 Checkout: Modify useCreateExistingCards to only rememoize only when ids change
  client/my-sites/checkout/composite-checkout/use-create-payment-methods.js
Labels: Checkout, [Estimate] 1, [Status] Ready to Merge

#49557 Checkout: Move line item subtotal calculation to display logic
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js
  client/my-sites/checkout/composite-checkout/lib/filter-appropriate-payment-methods.ts
  client/my-sites/checkout/composite-checkout/lib/translate-cart.ts
  client/my-sites/checkout/composite-checkout/test/translate-cart.js
  client/my-sites/checkout/composite-checkout/types/checkout-cart.ts
  packages/composite-checkout/README.md
  packages/composite-checkout/demo/index.js
  packages/composite-checkout/src/types.ts
Labels: Checkout, [Estimate] 1, [Status] Ready to Merge

#49494 Change stalebot message to include references to issue closure reason label and disable auto-closing of issues
  .github/stale.yml
Labels: [Status] Needs Review

#49058 Billing: Update ChangePaymentMethod to use PaymentMethodSelector
  client/lib/purchases/index.js
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/me/purchases/components/payment-method-form/style.scss
  client/me/purchases/manage-purchase/change-payment-method/assignment-processor-functions.ts
  client/me/purchases/manage-purchase/change-payment-method/index.jsx
  client/me/purchases/manage-purchase/change-payment-method/use-create-assignable-payment-methods.ts
  client/me/purchases/manage-purchase/payment-method-selector/assignment-processor-functions.ts
  client/me/purchases/manage-purchase/payment-method-selector/get-payment-method-id-from-payment.ts
  client/me/purchases/manage-purchase/payment-method-selector/index.tsx
  client/me/purchases/manage-purchase/payment-method-selector/stored-payment-method-api.ts
  client/me/purchases/manage-purchase/payment-method-selector/style.scss
  client/me/purchases/manage-purchase/payment-method-selector/tos-text.tsx
  client/me/purchases/manage-purchase/payment-method-selector/url-event-handlers.ts
Labels: Payment Methods, [Estimate] 2, [Status] Ready to Merge

#49493 Editing Toolkit: Update Newspack Blocks to v1.19.0
  apps/editing-toolkit/editing-toolkit-plugin/newspack-blocks/index.php
  apps/editing-toolkit/package.json
  yarn.lock
Labels: Editing Toolkit, [Status] Needs Review

#49516 Deduplicate make-dir
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49515 Deduplicate js-yaml
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49514 Deduplicate jest-worker
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49513 Deduplicate istanbul-lib-instrument
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49512 Deduplicate http-proxy
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49532 ci(docker) Rename docker images
  .teamcity/settings.kts
  Dockerfile.base
Labels: Build, Expedited Review, [Status] Needs Review

#49586 ci(docker): Copy composer utils from cache image
  Dockerfile.base
Labels: CI, Expedited Review, [Status] Needs Review

#49584 docs: Fix examples of bad code
  docs/coding-guidelines/typescript.md
Labels: [Status] Needs Review

#49521 state(user-settings): allow for nested attributes in `unsavedUserSettings`
  client/state/user-settings/helpers.js
  client/state/user-settings/reducer.js
  client/state/user-settings/test/helpers.js
  client/state/user-settings/test/reducer.js
Labels: State, [Status] Needs Review, [Tests] Includes Tests

#48710 Split ME Account settings form fields into two groups/cards
  client/lib/user-settings/index.js
  client/me/account/main.jsx
  client/me/form-base/index.js
Labels: [Status] In Progress, [Status] Needs Review

#49414 G Suite: Rename product selector and add more granular ones
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/lib/cart-values/cart-items.js
  client/lib/products-values/index.js
  client/lib/products-values/is-google-apps.js
  client/lib/products-values/is-gsuite.js
  client/me/purchases/cancel-purchase/cancellation-effect.jsx
  client/me/purchases/cancel-purchase/test/cancellation-effect.jsx
  client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-disabling-dialog/index.jsx
  client/me/purchases/manage-purchase/index.jsx
  client/me/purchases/manage-purchase/purchase-meta.jsx
  client/me/purchases/product-link/index.jsx
  client/me/purchases/remove-purchase/index.jsx
  client/my-sites/checkout/cart/cart-item.jsx
  client/my-sites/checkout/cart/test/cart-item.js
  client/my-sites/checkout/checkout-thank-you/blogger-plan-details.jsx
  client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx
  client/my-sites/checkout/checkout-thank-you/domain-registration-details.jsx
  client/my-sites/checkout/checkout-thank-you/ecommerce-plan-details.jsx
  client/my-sites/checkout/checkout-thank-you/features-header.jsx
  client/my-sites/checkout/checkout-thank-you/google-apps-details.jsx
  client/my-sites/checkout/checkout-thank-you/header.jsx
  client/my-sites/checkout/checkout-thank-you/index.jsx
  client/my-sites/checkout/checkout-thank-you/personal-plan-details.jsx
  client/my-sites/checkout/checkout-thank-you/premium-plan-details.jsx
Labels: G Suite, [Status] Ready to Merge

#49542 Help: Reduxify notices in HelpContact
  client/me/help/help-contact/index.jsx
Labels: Help, State, Support, [Status] Needs Review, [Type] Enhancement

#49544 Docs: Deprecate the legacy notices library
  client/notices/README.md
Labels: Documentation, [Pri] Low, [Status] Needs Review

#49459 Signup: Make sure the password field does not have extra margin
  client/blocks/signup-form/style.scss
Labels: Signup, [Status] Ready to Merge

#49460 Domains: Fix positioning of the example domain
  client/components/domains/example-domain-browser/index.jsx
Labels: Domains, [Status] Ready to Merge

#49465 Domains: Fix hover state for featured domain suggestions
  client/components/domains/domain-suggestion/style.scss
Labels: Domains, [Status] Ready to Merge

#49461 State: Type notice actions and their options
  client/state/notices/actions.js
  client/state/notices/actions.ts
  client/state/notices/test/__snapshots__/actions.js.snap
  client/state/notices/types.ts
Labels: State, [Status] Needs Review, [Type] Enhancement

#49597 Domains: Fix bad translation string components
  client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
Labels: Domains, [Status] Needs Review, [Type] Bug, i18n

#49590 Remove links to manifest.js in dev mode
  client/document/domains-landing.jsx
  client/document/index.jsx
Labels: Build, [Status] Needs Review

#49556 Account settings: Add dashboard appearance toggle for using WP Admin links
  client/me/account/main.jsx
  client/me/account/style.scss
Labels: Nav Unification, [Status] Needs Review

#49600 Me: Use Redux for notices in formBase mixin
  client/me/form-base/index.js
Labels: Me, State, [Status] Needs Review, [Type] Enhancement

#49545 ci(teamcity): Use '/base:latest' images to run tests
  .teamcity/settings.kts
Labels: CI, Expedited Review, [Status] Needs Review

#49546 ci(teamcity) Allow image_tag to be configurable
  .teamcity/settings.kts
Labels: CI, Expedited Review, [Status] Needs Review

#49596 perf(rum): Instrument calls to i18n.addTranslations
  client/lib/i18n-utils/switch-locale.js
  client/lib/performance-tracking/collectors/translations.js
  client/lib/performance-tracking/lib.js
  client/lib/performance-tracking/test/lib.js
Labels: [Status] Needs Review

#49559 Plans store: always pass locale to the plans store
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx
  client/landing/gutenboarding/hooks/use-selected-plan.ts
  client/landing/gutenboarding/hooks/use-steps.ts
  client/landing/gutenboarding/onboarding-block/language/index.tsx
  packages/data-stores/src/launch/selectors.ts
  packages/data-stores/src/plans/selectors.ts
  packages/launch/src/focused-launch/summary/index.tsx
  packages/launch/src/hooks/use-cart.ts
  packages/plans-grid/src/plans-accordion/index.tsx
Labels: Focused Launch, Launch, Plans, [Status] Needs Review

#49479 Gutenboarding: update tt-blocks theme slug
  client/landing/gutenboarding/available-designs-config.json
Labels: [Status] Needs Review

#49201 Jetpack FAQ: update refund FAQ to account for monthly and yearly plans
  client/my-sites/plans-features-main/jetpack-faq-i5/index.tsx
  client/my-sites/plans-features-main/jetpack-faq.jsx
Labels: Billing, Jetpack, [Status] Ready to Merge, [Status] String Freeze

#49607 Signup: Fix Google sign-up unexpected error.
  client/signup/steps/user/index.jsx
Labels: Social Signup, [Status] Needs Review, [Type] Bug

#48827 Partner Portal: Add masterbar navigation to switch between managing sites and the portal
  client/components/jetpack/masterbar/index.jsx
  client/components/jetpack/portal-nav/index.tsx
  client/components/jetpack/portal-nav/style.scss
  client/jetpack-cloud/sections/partner-portal/select-partner-key/index.tsx
  client/state/partner-portal/actions/partner.ts
  client/state/partner-portal/index.d.ts
  client/state/partner-portal/reducer/partner.ts
  client/state/partner-portal/selectors/index.js
  client/state/partner-portal/selectors/partner.ts
Labels: Jetpack Cloud, [Status] Needs Review

#48937 Partner Portal: Add static license listing UI
  client/jetpack-cloud/sections/partner-portal/controller.tsx
  client/jetpack-cloud/sections/partner-portal/license-list-item/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-list-item/style.scss
  client/jetpack-cloud/sections/partner-portal/license-list/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-preview/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-preview/style.scss
  client/jetpack-cloud/sections/partner-portal/sidebar/index.tsx
  client/jetpack-cloud/sections/partner-portal/utils.ts
  packages/material-design-icons/src/communication/filled-vpn_key-24px.svg
  packages/material-design-icons/svg-sprite/material-icons.svg
Labels: Jetpack Cloud, [Status] Needs Review

#49272 Partner Portal: Introduce the license details toggle UI
  client/jetpack-cloud/sections/partner-portal/license-details/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-details/style.scss
  client/jetpack-cloud/sections/partner-portal/license-preview/index.tsx
Labels: Jetpack Cloud, [Status] Needs Review

#49483 Checkout: Add Jetpack Redirect after Jetpack Cloud Checkout[Revised]
  client/lib/plans/constants.js
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
Labels: Jetpack Cloud, Post Checkout, [Status] Needs Review

#49580 Checkout: Use ResponseCart directly for products in CompositeCheckout component
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-is-apple-pay-available.ts
  client/my-sites/checkout/composite-checkout/hooks/use-stored-cards.ts
Labels: Checkout, [Status] Ready to Merge

#49623 ABTest: Stop the jetpackSimplifyPricingPage test
  client/lib/abtest/active-tests.js
  client/my-sites/plans/jetpack-plans/abtest.ts
Labels: ABTest, Plans, [Status] Needs Review

#49059 Billing: Update account-level AddNewPaymentMethod to use PaymentMethodSelector
  client/me/purchases/add-new-payment-method/index.jsx
Labels: Payment Methods, [Estimate] 2, [Status] Ready to Merge

#49579 Try: Switching to Jetpack's PHPCS
  apps/phpcs.xml
  composer.json
  composer.lock
Labels: Editing Toolkit, Jetpack, [Status] Needs Review, [Type] Janitorial, [Type] Tooling

#49443 Decrease grid gap sizes to increase image size in design view
  client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Labels: [Goal] New Onboarding, [Status] Needs Review

#49642 E2E test: Move check for the Premium Content block from Earn to Grow
  test/e2e/specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#49441 Login: improve password fields on iOS
  client/components/forms/form-password-input/index.jsx
Labels: Login, [Pri] Low, [Status] Needs Review

#49583 WelcomeTour: capture mousedown event and call preventDefault on the event
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.js
Labels: Editor Welcome, [Status] Ready to Merge

#49582 ci(docker): Don't download Chromedriver in CI image
  Dockerfile.base
Labels: CI, Expedited Review, [Status] Needs Review

#49033 Domains: Reduxify ICANN verification notices
  client/my-sites/domains/domain-management/transfer/transfer-out/icann-verification.jsx
Labels: Domains, [Status] Ready to Merge, [Type] Enhancement

#49530 Purchases: Reduxify notices in RemovePurchase
  client/me/purchases/remove-purchase/index.jsx
Labels: Purchases, [Status] Needs Review, [Type] Enhancement

#49547 ci(docker) Use cache when building docker images for e2e tests
  .teamcity/settings.kts
Labels: CI, Expedited Review, [Status] Needs Review

#49411 i18n: Throttle i18n.addTranslations calls
  client/lib/i18n-utils/switch-locale.js
Labels: Performance, [Status] In Progress, [Status] Needs Review, i18n

#49658 Prevent redirection for missing quantity errors
  client/my-sites/email/titan-mail-quantity-selection/index.jsx
Labels: Email Product, [Status] Ready to Merge

#49659 Adds missing php7.4-mbstring dependency
  Dockerfile.base
Labels: [Status] Needs Review

#49657 build(webpack): Enable persistent cache (opt-in)
  .teamcity/settings.kts
  Dockerfile
  Dockerfile.base
  client/webpack.config.js
Labels: CI, [Status] Needs Review

#49619 Jetpack Cloud Checkout: Redirect to site's /wp-admin after checkout
  client/lib/plans/constants.js
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
Labels: Jetpack Cloud, Post Checkout, [Status] Needs Review

#49606 ABTest: Create new test to prefill FRESHPACK code
  client/lib/abtest/active-tests.js
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
Labels: ABTest, Checkout, [Status] Needs Review

#49625 Anchor: Update the CTA button.
  client/my-sites/customer-home/cards/tasks/podcasting/index.jsx
Labels: [Status] Needs Review

#48719 Help: New styles for Helpful Articles and search results
  client/assets/images/illustrations/help-domains.svg
  client/assets/images/illustrations/help-getstarted.svg
  client/assets/images/illustrations/help-plugins.svg
  client/assets/images/illustrations/help-privacy.svg
  client/assets/images/illustrations/help-website.svg
  client/devdocs/design/illustrations.jsx
  client/me/help/help-results/index.jsx
  client/me/help/help-results/item.jsx
  client/me/help/help-results/style.scss
  client/me/help/help-search/index.jsx
  client/me/help/help-search/style.scss
  client/me/help/main.jsx
  client/me/help/style.scss
Labels: Help, [Status] Needs Review, [Type] Janitorial

#49637 Update DIFM CTA on /themes to use ExternalLink.
  client/blocks/upwork-banner/index.jsx
  client/blocks/upwork-banner/test/__snapshots__/index.js.snap
Labels: Back to Basics, [Status] Needs Review

#49431 Added AL access for sites with purchased Scan Product
  client/my-sites/activity/activity-log-v2/index.tsx
Labels: [Status] Needs Review

#49671 i18n: Use `useLocalizedUrl` for ToS link on signup step
  client/landing/gutenboarding/components/signup-form/index.tsx
Labels: [Status] Needs Review

#49674 Gutenboarding: Enable language picker on production.
  client/landing/gutenboarding/components/header/index.tsx
  config/development.json
  config/horizon.json
  config/stage.json
  config/wpcalypso.json
  test/e2e/specs/wp-gutenboarding-spec.js
Labels: [Goal] New Onboarding

#49662 Launch from editor: update tracks event props
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-button/index.ts
Labels: Editing Toolkit, Expedited Review, [Status] Needs Review

#49611 Force light color scheme in the Jetpack Connection header
  client/components/jetpack-header/eurodns.jsx
  client/jetpack-connect/main-wrapper.jsx
Labels: Jetpack, NUX

#49281 Adminbar: hide in WP Mobile Apps
  client/document/index.jsx
  client/layout/index.jsx
  client/layout/logged-out.jsx
  client/layout/masterbar/empty.jsx
  client/layout/masterbar/style.scss
  client/layout/style.scss
  client/lib/mobile-app/index.js
  client/server/lib/is-wp-mobile-app/index.js
  client/server/pages/index.js
Labels: Testing, [Status] Needs Review

#49683 Revert "Gutenboarding: Enable language picker on production."
  client/landing/gutenboarding/components/header/index.tsx
  config/development.json
  config/horizon.json
  config/stage.json
  config/wpcalypso.json
  test/e2e/specs/wp-gutenboarding-spec.js
Labels: [Goal] New Onboarding, [Status] Needs Review

#49569 Editing Toolkit: Update to 2.17.0
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/readme.txt
  apps/editing-toolkit/package.json
Labels: Editing Toolkit, Releases, [Status] Needs Review

#49656 Deduplicate neo-async
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49654 Deduplicate nan
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49652 Deduplicate meow
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49649 Deduplicate globby
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49647 Deduplicate mime
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49646 Deduplicate mime-types
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49567 New Onboarding: re-add top bar to checkout
  client/layout/index.jsx
Labels: Checkout, [Goal] New Onboarding, [Status] Needs Review

#49686 Adminbar: hide in WP Mobile Apps - with fixes
  client/document/index.jsx
  client/layout/index.jsx
  client/layout/logged-out.jsx
  client/layout/masterbar/empty.jsx
  client/layout/masterbar/style.scss
  client/layout/style.scss
  client/lib/mobile-app/index.js
  client/my-sites/theme/style.scss
  client/server/lib/is-wp-mobile-app/index.js
  client/server/pages/index.js
Labels: [Status] Needs Review

#49527 G Suite: Remove code from former Email page
  client/lib/domains/email-forwarding/index.js
  client/lib/domains/email-forwarding/test/index.js
  client/my-sites/email/email-management/index.jsx
  client/my-sites/email/gsuite-purchase-cta/index.jsx
  client/my-sites/email/gsuite-purchase-cta/sku-info.jsx
  client/my-sites/email/gsuite-purchase-cta/style.scss
  client/my-sites/email/gsuite-purchase-cta/test/__snapshots__/index.js.snap
  client/my-sites/email/gsuite-purchase-cta/test/__snapshots__/sku-info.js.snap
  client/my-sites/email/gsuite-purchase-cta/test/index.js
  client/my-sites/email/gsuite-purchase-cta/test/sku-info.js
Labels: G Suite, [Status] Ready to Merge

#49303 Help: Reduxify notices in HelpUnverifiedWarning
  client/me/help/help-unverified-warning/index.jsx
Labels: Help, State, [Status] Needs Review, [Type] Enhancement

#49373 Social Previews: Fix the white screen for the SEO device.
  client/blocks/reader-post-card/index.jsx
Labels: [Status] Needs Review

#48550 Focused Launch: convert cart domains into domain picker suggestion items
  packages/data-stores/src/domain-suggestions/index.ts
  packages/data-stores/src/domain-suggestions/types.ts
  packages/domain-picker/src/hooks/use-domain-suggestions.ts
  packages/domain-picker/src/index.tsx
  packages/domain-picker/src/utils.ts
  packages/launch/src/hooks/use-domain-selection.ts
  packages/launch/src/utils.ts
Labels: Focused Launch, [Status] In Progress, [Status] Needs Review

#49598 State: Move account recovery notices away from middleware
  client/state/account-recovery/settings/actions.js
  client/state/account-recovery/settings/notices.js
  client/state/notices/middleware.js
Labels: Me, State, [Status] Needs Review, [Type] Enhancement

#49601 Adds plan specific signup flows for monthly plans
  client/signup/config/flows-pure.js
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
Labels: [Status] Needs Review

#49412 Focused Launch - Summary View: Update the plan's prices with monthly/annual toggle
  packages/launch/src/focused-launch/summary/index.tsx
Labels: Focused Launch, [Status] Needs Review

#49697 Deduplicate nopt
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49699 Deduplicate object-inspect
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49701 Deduplicate mime-db
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49696 Deduplicate node-sass
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49702 Deduplicate minimist-options
  yarn.lock
Labels: Expedited Review, Framework, [Status] Needs Review

#49710 Nav Unification: ensure Classic Bright shows when intentionally selected
  packages/calypso-color-schemes/src/shared/color-schemes/_default.scss
Labels: Nav Unification, [Status] Needs Review

#49709 New Onboarding: Add Padding under Feature List
  client/landing/gutenboarding/onboarding-block/features/style.scss
Labels: Mobile Web, OSS Citizen, [Goal] New Onboarding, [Status] Needs Review

#49668 Store|Woo: Update Store deprecation message
  client/extensions/woocommerce/app/dashboard/store-move-notice-view.js
Labels: Store, WooCommerce, [Status] Ready to Merge

#49687 Change import to import type in client/lib/url helpers
  client/lib/url/add-query-args.ts
  client/lib/url/format.ts
Labels: [Status] Needs Review

#49716 Fixes layout padding for <660px breakpoints
  client/my-sites/sidebar-unified/style.scss
Labels: [Status] Needs Review

#49571 Anchor Gutenboarding: Query the WPCOM backend for matching anchor sites and redir
  client/landing/gutenboarding/hooks/use-detect-matching-anchor-site.ts
  client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
  client/lib/wpcom-undocumented/lib/undocumented.js
Labels: [Status] Needs Review

#49719 Jetpack Cloud, Plans: Change site slug replace to replaceAll on Free card
  client/components/jetpack/card/jetpack-free-card-button/index.tsx
Labels: Jetpack Cloud, Plans, [Status] Needs Review

#49676 Anchor: Add Anchor to the Horizon and wpcalypso environments.
  config/horizon.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#49728 Gutenboarding: hide Brice from design picker
  client/landing/gutenboarding/available-designs-config.json
  client/landing/gutenboarding/available-designs.ts
  client/landing/gutenboarding/stores/onboard/types.ts
Labels: Themes, [Goal] New Onboarding, [Status] Needs Review

#49738 Happy Chat: Set section name as a Custom Field
  client/state/happychat/middleware-calypso.js
  client/state/happychat/test/middleware-calypso.js
Labels: [Status] Needs Review

#49533 Purchases: Reduxify notices in GSuiteCancelPurchaseDialog
  client/components/marketing-survey/gsuite-cancel-purchase-dialog/index.jsx
Labels: G Suite, Purchases, [Status] Ready to Merge, [Type] Enhancement

#47947 New Onboarding: Localize help contact url in Step-by-step launch flow
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx
Labels: Editing Toolkit, [Goal] New Onboarding, [Status] Needs Review, i18n

#49593 Nav Unification: Announcement Modal
  client/blocks/nav-unification-modal/index.jsx
  client/blocks/nav-unification-modal/style.scss
  client/layout/index.jsx
  static/images/nav-unification-announcement/unify-nav-desktop-1.jpg
  static/images/nav-unification-announcement/unify-nav-desktop-2.jpg
  static/images/nav-unification-announcement/unify-nav-desktop-3.jpg
  static/images/nav-unification-announcement/unify-nav-mobile-1.jpg
  static/images/nav-unification-announcement/unify-nav-mobile-2.jpg
  static/images/nav-unification-announcement/unify-nav-mobile-3.jpg
Labels: [Status] Needs e2e Testing

#49715 Framework: Remove usages of lodash pull()
  client/extensions/woocommerce/app/products/product-variation-types-form.js
  client/extensions/woocommerce/state/ui/shipping/zones/locations/reducer.js
  client/lib/post-normalizer/rule-wait-for-images-to-load.js
  client/my-sites/media-library/filter-bar.jsx
Labels: Framework, [Status] Needs Review, [Type] Enhancement, [Type] Janitorial

#49711 Fix/annual plan view missing per monthly
  client/my-sites/plan-features/header.jsx
  client/my-sites/plan-features/index.jsx
  client/my-sites/plan-features/style.scss
  client/signup/steps/plans/index.jsx
Labels: [Status] Needs Review

#49402 Upsell nudge: Redirect to signup destination if eligible
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
  client/my-sites/checkout/upsell-nudge/index.jsx
Labels: Back to Basics, Post Checkout, [Status] Needs Review

#49761 Plans Grid: Remove maxMonthlyDiscountPercentage fallback value
  packages/plans-grid/src/plans-interval-toggle/index.tsx
Labels: Plans, [Goal] New Onboarding, [Status] Needs Review

#49758 Focused Launch - Summary View: Fix checkmark size in sidebar
  packages/launch/src/focused-launch/summary/style.scss
Labels: Focused Launch, OSS Citizen, [Status] Needs Review

#49708 Checkout thank-you unit test: fix variable name
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
Labels: [Status] Needs Review

#49672 Gutenboarding: Fix long site title overflow issue on header.
  client/landing/gutenboarding/components/header/index.tsx
  client/landing/gutenboarding/components/header/style.scss
Labels: [Goal] New Onboarding, [Status] Needs Review

#49523 Focused Launch: fix disabled free plan regressions, add missing "translators" comments
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx
  packages/domain-picker/src/domain-picker/suggestion-item.tsx
  packages/plans-grid/src/plans-feature-list/style.scss
  packages/plans-grid/src/plans-table/plan-item.tsx
Labels: Focused Launch, [Status] Needs Review

#49769 Load the Portal navigation asynchonously to avoid an unnecessary bump in initial entrypoint bundle size
  client/components/jetpack/masterbar/index.jsx
Labels: Jetpack Cloud, [Status] Needs Review

#48722 Adding Whats New modal to the block editor
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/whats-new/class-whats-new.php
  apps/editing-toolkit/editing-toolkit-plugin/whats-new/index.js
  apps/editing-toolkit/editing-toolkit-plugin/whats-new/src/public-path.js
  apps/editing-toolkit/editing-toolkit-plugin/whats-new/src/store.js
  apps/editing-toolkit/editing-toolkit-plugin/whats-new/src/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/whats-new/src/whats-new.js
  apps/editing-toolkit/package.json
Labels: [Status] In Progress

#49724 PlansGrid: update Signup label for annual plans on details table
  packages/plans-grid/src/plans-details/index.tsx
Labels: Plans, [Goal] New Onboarding, [Status] Needs Review

#49732 My Home: Activate dev mode on Horizon and wpcalypso for testing.
  config/horizon.json
  config/wpcalypso.json
Labels: Customer Home, OSS Citizen, [Type] Task

#49772 Intent capture: dont set value needlessly in intent capture field
  client/landing/gutenboarding/onboarding-block/acquire-intent/acquire-intent-text-input/index.tsx
Labels: Expedited Review, [Status] Needs Review, [Type] Bug

#48700 Add Apple Silicon Support
  .circleci/config.yml
  .gitignore
  desktop/bin/after_sign_hook.js
  desktop/bin/build-mac-ci.js
  desktop/electron-builder.json
  desktop/package.json
  desktop/yarn.lock
Labels: [Status] Needs Review

#49560 Anchor: Update branding in the My Home podcasting card.
  client/assets/images/customer-home/illustration--task-podcasting.svg
Labels: Customer Home, [Status] Needs Review

#49740 ETK: Change PLUGIN_VERSION to A8C_ETK_PLUGIN_VERSION
  .teamcity/settings.kts
  apps/editing-toolkit/editing-toolkit-plugin/block-patterns/class-block-patterns-from-api.php
  apps/editing-toolkit/editing-toolkit-plugin/coming-soon/coming-soon.php
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/class-starter-page-templates.php
Labels: Editing Toolkit, [Status] Needs Review, [Type] Janitorial

#49726 Checkout: Redirecting non-connected Jetpack users to the connection flow
  client/my-sites/checkout/checkout/test/maybe-jetpack-authorize.js
  client/my-sites/controller.js
  client/state/sites/actions.js
Labels: Checkout, Jetpack, OSS Citizen, [Status] In Progress, [Status] Needs Review, [Type] Enhancement

#49780 What's New: fix store issues related to missing function
  apps/editing-toolkit/editing-toolkit-plugin/whats-new/src/store.js
  apps/editing-toolkit/editing-toolkit-plugin/whats-new/src/whats-new.js
Labels: Editing Toolkit, [Status] Needs Review, [Type] Bug

#49777 Anchor Gutenboarding: Listen for "site" and "post" params
  client/landing/gutenboarding/hooks/use-detect-matching-anchor-site.ts
  client/landing/gutenboarding/path.ts
  client/lib/wpcom-undocumented/lib/undocumented.js
Labels: [Status] Needs Review

#49778 Update newspack blocks to v1.20
  apps/editing-toolkit/bin/sync-newspack-blocks.sh
  apps/editing-toolkit/editing-toolkit-plugin/newspack-blocks/index.php
  apps/editing-toolkit/package.json
  yarn.lock
Labels: Editing Toolkit, [Status] Needs Review, dependencies

#49784 Fix anchor backend errors when visiting gutenboarding
  client/lib/wpcom-undocumented/lib/undocumented.js
Labels: [Status] Needs Review

#49692 ETK: Fix PHPCS issues
  apps/editing-toolkit/editing-toolkit-plugin/coming-soon/test/class-coming-soon-test.php
  apps/editing-toolkit/editing-toolkit-plugin/common/index.php
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/templates/class-template-image-inserter.php
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/templates/class-wp-template-inserter.php
  apps/editing-toolkit/editing-toolkit-plugin/event-countdown-block/index.php
  apps/editing-toolkit/editing-toolkit-plugin/jetpack-timeline/index.php
  apps/editing-toolkit/editing-toolkit-plugin/mailerlite/subscriber-popup.php
  apps/editing-toolkit/editing-toolkit-plugin/phpunit/bootstrap.php
  apps/editing-toolkit/editing-toolkit-plugin/posts-list-block/templates/posts-list.php
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/class-wp-rest-sideload-image-controller.php
  apps/editing-toolkit/package.json
  apps/phpcs.xml
Labels: Code Style, [Status] Needs Review, [Type] Tooling
