Repository Automattic/wp-calypso, pull requests merged in 2021-06, with the labels that each got.

#53275 Remove the jetpack/connect/remote-install feature flag
  client/jetpack-connect/index.js
  client/jetpack-connect/jetpack-connection.jsx
  client/jetpack-connect/remote-credentials.js
  config/development.json
  config/horizon.json
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-stage.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Type] Janitorial

#53191 Remove the always-enabled login feature flags
  client/blocks/login/index.jsx
  client/blocks/login/social.jsx
  client/blocks/signup-form/index.jsx
  client/controller/index.web.js
  client/devdocs/controller.js
  client/jetpack-connect/authorize.js
  client/jetpack-connect/controller.js
  client/jetpack-connect/index.js
  client/jetpack-connect/signup.js
  client/layout/masterbar/logged-out.jsx
  client/lib/paths/index.js
  client/lib/paths/login/index.js
  client/lib/paths/login/test/__snapshots__/index.js.snap
  client/lib/paths/login/test/index.js
  client/lib/paths/lost-password.ts
  client/login/index.web.js
  client/login/magic-login/emailed-login-link-expired.jsx
  client/login/magic-login/emailed-login-link-successfully.jsx
  client/login/magic-login/handle-emailed-link-form-jetpack-connect.tsx
  client/login/magic-login/handle-emailed-link-form.jsx
  client/login/magic-login/index.jsx
  client/login/wp-login/login-links.jsx
  client/me/sidebar/index.jsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
  client/my-sites/purchase-product/index.js
  client/server/pages/index.js
  client/server/pages/test/index.js
  client/signup/controller.js
  client/signup/steps/p2-details/index.jsx
  client/signup/steps/p2-site/index.jsx
  client/signup/steps/site/index.jsx
  client/signup/steps/user/index.jsx
  client/state/login/reducer.js
  client/state/login/utils.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Type] Janitorial

#53282 Remove unneeded mocking of lib/abtest and i18n-calypso
  client/blocks/plan-storage/test/bar.jsx
  client/blocks/plan-storage/test/plan-storage.jsx
  client/blocks/post-share/test/nudges.jsx
  client/components/banner/test/index.jsx
  client/components/seo/preview-upgrade-nudge/test/index.jsx
  client/layout/test/index.js
  client/lib/automated-transfer/test/index.js
  client/lib/signup/test/step-actions.js
  client/me/concierge/test/main.js
  client/my-sites/checkout/checkout-thank-you/test/header.js
  client/my-sites/checkout/checkout-thank-you/test/index.js
  client/my-sites/domains/domain-management/transfer/transfer-to-other-site/test/index.jsx
  client/my-sites/plan-features/test/header.jsx
  client/my-sites/plan-features/test/index.jsx
  client/my-sites/plans-features-main/test/index.jsx
  client/my-sites/plugins/plugin-meta/test/index.js
  client/my-sites/plugins/plugins-browser/test/index.jsx
  client/my-sites/sidebar/test/sidebar.js
  client/my-sites/site-settings/test/form-general.jsx
  client/my-sites/themes/test/logged-out.jsx
  client/signup/config/test/index.js
  client/signup/steps/site-picker/test/site-picker-submit.jsx
  client/signup/steps/user/test/index.js
  client/signup/test/utils.js
  client/state/products-list/test/selectors.js
Labels: [Status] Needs Review, [Type] Janitorial

#53279 State: Refactor `getFileUploader` away from `redux-bridge`
  client/lib/media/utils/get-file-uploader.js
  client/state/media/thunks/add-media.js
  client/state/media/thunks/add-woocommerce-product-image.js
  client/state/media/thunks/index.js
Labels: Media, State, [Status] Needs Review, [Type] Janitorial

#53277 E2e: Remove abtesting helpers and overrides
  client/lib/user/user.js
  test/e2e/lib/async-base-container.js
  test/e2e/lib/components/find-a-domain-component.js
  test/e2e/lib/flows/login-flow.js
  test/e2e/lib/override-abtest.js
  test/e2e/lib/pages/signup/start-page.js
  test/e2e/specs/specs-calypso/wp-manage-domains-spec.js
Labels: Testing, [Status] Needs Review, [Status] Needs e2e Testing, [Type] Janitorial

#53042 Remove Redux navigation actions
  client/blocks/disconnect-jetpack/index.jsx
  client/devdocs/controller.js
  client/extensions/zoninator/state/data-layer/zones/index.js
  client/gutenberg/editor/calypsoify-iframe.tsx
  client/layout/masterbar/publish.jsx
  client/lib/desktop-listeners/index.js
  client/lib/navigate/index.ts
  client/my-sites/activity/activity-log-tasklist/index.jsx
  client/my-sites/comments/comment/comment-link.jsx
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
  client/my-sites/customer-home/cards/actions/wp-for-teams-quick-links/index.jsx
  client/my-sites/customer-home/cards/education/educational-content/index.jsx
  client/my-sites/customer-home/cards/features/quick-start/index.js
  client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
  client/my-sites/hosting/support-card/index.js
  client/my-sites/invites/controller.js
  client/my-sites/invites/invite-accept-logged-in/index.jsx
  client/state/action-types.ts
  client/state/data-layer/wpcom/read/lists/delete/index.js
  client/state/data-layer/wpcom/read/lists/index.js
  client/state/navigation/README.md
  client/state/navigation/middleware.js
  client/state/ui/actions/history.js
  client/state/ui/actions/index.js
  client/state/ui/actions/navigate.js
  client/state/ui/test/actions.js
Labels: Framework, [Status] Needs Review

#53177 Remove all cart products when starting the marketplace flow
  client/my-sites/plugins/marketplace/marketplace-plugin-details/index.tsx
  client/my-sites/plugins/marketplace/marketplace-plugin-details/purchase-area.tsx
  client/my-sites/plugins/marketplace/marketplace-plugin-details/test/index.js
Labels: [Status] Needs Review

#53284 Restructure routes
  client/my-sites/plugins/controller.js
  client/my-sites/plugins/index.js
  client/my-sites/plugins/marketplace/marketplace-domain-upsell/index.tsx
  client/my-sites/plugins/marketplace/marketplace-plugin-details/index.tsx
Labels: [Status] Needs Review

#53195 Notifications: Remove lodash
  apps/notifications/package.json
  apps/notifications/src/panel/rest-client/index.js
  apps/notifications/src/panel/state/action-middleware/utils.js
  apps/notifications/src/panel/state/notes/reducer.js
  apps/notifications/src/panel/state/selectors/get-all-notes.js
  apps/notifications/src/panel/state/selectors/get-is-note-read.js
  apps/notifications/src/panel/state/selectors/note-has-filtered-read.js
  apps/notifications/src/panel/suggestions/index.jsx
  apps/notifications/src/panel/templates/button-edit.jsx
  apps/notifications/src/panel/templates/filter-bar-controller.js
  apps/notifications/src/panel/templates/functions.jsx
  apps/notifications/src/panel/templates/index.jsx
  apps/notifications/src/panel/templates/note-list.jsx
  apps/notifications/src/panel/templates/summary-in-list.jsx
  apps/notifications/src/panel/utils/noticon2gridicon.js
Labels: Framework, Notifications, [Size] XS, [Status] Needs Review, [Type] Enhancement

#53096 Jetpack Backup: Update multisites to allow backup archive download
  client/components/activity-card/index.jsx
  client/components/activity-card/style.scss
  client/components/jetpack/daily-backup-status/action-buttons.jsx
  client/components/jetpack/daily-backup-status/status-card/backup-successful.jsx
  client/components/jetpack/daily-backup-status/status-card/style.scss
  client/my-sites/backup/controller.js
  client/state/selectors/get-allow-restore.js
  client/state/selectors/site-has-subscription.tsx
  client/state/selectors/test/site-has-subscription.js
Labels: Jetpack, Jetpack Backup, Multi-Site Plans, [Status] Needs Review

#53147 With Plugin Redirect: fix i18n string
  client/my-sites/plugins/with-plugin-redirect/index.js
Labels: [Size] S, [Status] Ready to Merge, [Status] String Freeze, i18n

#53189 Prevent users from purchasing additional mailboxes when the associated subscription expires/is expiring
  client/my-sites/email/email-management/home/email-plan.jsx
Labels: Email management, [Status] Needs Review

#52850 Checkout: Also show delete button when order review step is inactive
  client/my-sites/checkout/composite-checkout/components/delete-icon.svg
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
  client/my-sites/checkout/composite-checkout/test/composite-checkout.js
  packages/composite-checkout/src/components/checkout-modal.tsx
  packages/composite-checkout/src/components/checkout-steps.tsx
Labels: Checkout, [Estimate] 1, [Status] Needs Review

#53062 Update/52927 atomic upload theme tracks events
  client/my-sites/themes/install-theme-button.jsx
Labels: [Status] Needs Review

#53257 Reader: Fix "List Not Found" Error
  client/reader/list-manage/index.jsx
  client/reader/list-stream/missing.jsx
  client/state/reader/lists/reducer.js
  client/state/reader/lists/selectors.js
  client/state/reader/lists/test/reducer.js
  client/state/reader/lists/test/selectors.js
Labels: OSS Citizen, Reader, [Status] Needs Review

#53206 ci(unit): Refactor unit tests
  client/lib/directly/test/index.js
  client/lib/geocoding/test/index.js
  client/lib/happychat/test/index.js
  client/state/exporter/test/actions.js
  client/state/plugins/installed/test/actions.js
  client/state/reader/related-posts/test/actions.js
  client/state/reader/tags/images/test/actions.js
  client/state/reader/thumbnails/test/actions.js
  client/state/terms/test/actions.js
Labels: [Status] Needs Review

#53303 p2 Signup: Use Redux to check if user is logged in
  client/signup/main.jsx
Labels: Signup, [Status] Needs Review, [Type] Enhancement

#53187 requestSite should return a rejected promise on error
  client/blocks/site-address-changer/index.jsx
  client/jetpack-cloud/controller.ts
  client/my-sites/checkout/checkout/test/maybe-jetpack-authorize.js
  client/my-sites/controller.js
  client/my-sites/marketing/controller.js
  client/signup/controller.js
  client/state/site-address-change/actions.js
  client/state/sites/actions.js
  client/state/sites/test/actions.js
Labels: Framework, [Status] Needs Review

#53328 Move getSiteId to state/sites/selectors
  client/components/site-offset/context.tsx
  client/jetpack-cloud/controller.ts
  client/lib/signup/step-actions/fetch-sites-and-user.js
  client/lib/signup/step-actions/index.js
  client/my-sites/comment/main.jsx
  client/my-sites/comments/main.jsx
  client/my-sites/controller.js
  client/my-sites/migrate/controller.js
  client/signup/controller.js
  client/signup/main.jsx
  client/signup/steps/plans-atomic-store/index.jsx
  client/state/sites/selectors/get-site-id.js
  client/state/sites/selectors/index.js
Labels: [Status] Needs Review, [Type] Janitorial

#53224 Don't show 'Add' button for email when user can't add email for a domain
  client/my-sites/domains/domain-management/list/domain-item.jsx
Labels: Domains, Email management, [Status] Needs Review

#53298 i18n: Add context for `Add Site` string in Profile links section
  client/me/profile-links-add-wordpress/index.jsx
Labels: [Status] Needs Review, [Status] String Freeze, i18n

#53161 Emails: Fix wrong mailbox labels and titles for Google Workspace in emails management pages
  client/components/gsuite/gsuite-new-user-list/index.tsx
  client/my-sites/email/email-management/gsuite-users-card/index.jsx
  client/my-sites/email/email-management/home/email-plan.jsx
  client/my-sites/email/email-management/home/utils.js
  client/my-sites/email/email-management/titan-manage-mailboxes/index.jsx
  client/my-sites/email/gsuite-add-users/index.jsx
  client/my-sites/email/paths.js
  client/my-sites/email/titan-add-mailboxes/index.jsx
Labels: G Suite, Professional Email, [Status] Needs Review, [Status] String Freeze

#53255 P2: Redirect to hub on user management pages
  client/my-sites/controller.js
  client/my-sites/people/index.js
Labels: [Status] Needs Review

#46800 Set the right autocomplete value on 2FA code field
  client/components/forms/form-verification-code-input/index.jsx
Labels: 2FA, Login, [Status] Needs Review

#53151 Add A/B experiment showing clearer total discount in JP pricing page
  client/components/jetpack/card/jetpack-product-card/index.tsx
Labels: ABTest, Jetpack Cloud, Plans, [Size] S, [Status] Needs Review

#53343 Jetpack Plans: update Priority Support copy
  client/my-sites/plans/jetpack-plans/product-grid/index.tsx
Labels: Jetpack, Jetpack Cloud, [Size] XS, [Status] Needs Review

#53293 Domains: Ensure consistent type for selectedDomainName prop in DomainManagementHeader component
  client/my-sites/domains/domain-management/change-site-address/index.jsx
  client/my-sites/domains/domain-management/components/header/index.jsx
  client/my-sites/domains/domain-management/transfer/index.jsx
Labels: Domains, [Status] Needs Review

#53342 Emails: Fix Add new mailboxes link not shown for email forwards on Email Plan page
  client/my-sites/email/email-management/home/email-plan-subscription.jsx
  client/my-sites/email/email-management/home/email-plan.jsx
Labels: Email management, [Status] Needs Review, [Type] Bug

#53082 Theme Showcase: Update language around homepage switching
  client/my-sites/themes/auto-loading-homepage-modal.jsx
Labels: Theme Showcase, [Pod] Design Selection, [Status] Needs Review, [Status] String Freeze

#53144 Media Library: don't allow uploading videos for free sites from the UI
  client/blocks/upsell-nudge/index.jsx
  client/components/banner/index.jsx
  client/components/banner/style.scss
  client/my-sites/media-library/index.jsx
  client/my-sites/media-library/test/index.jsx
Labels: Media, Simple/Atomic Parity, [Size] S, [Status] Ready to Merge

#53335 Temporary fix for editor crash when getLocaleData is undefined.
  packages/i18n-utils/src/locale-context.tsx
Labels: [Status] Needs Review

#53355 Happy Chat: Show in-chat unread messages indicator
  client/components/happychat/autoscroll.js
  client/components/happychat/timeline.jsx
  client/components/happychat/timeline.scss
Labels: [Status] Needs Review

#53357 Happy Chat: Fix floating bubble's "unread" visual indication
  client/state/happychat/selectors/has-unread-messages.js
  client/state/happychat/selectors/test/has-unread-messages.js
Labels: [Status] Needs Review

#53314 Settings: Move Search card above Cloudflare card
  client/my-sites/site-settings/settings-performance/main.jsx
Labels: Jetpack Search, Site Settings, [Status] Needs Review

#53338 Migrating marketplace files to a separate section of calypso
  client/my-sites/marketplace/controller.js
  client/my-sites/marketplace/index.js
  client/my-sites/plugins/controller.js
  client/my-sites/plugins/index.js
  client/sections.js
Labels: [Status] Needs Review

#53333 ci(e2e): Disable tests that don't work well in parallel
  test/e2e/specs/specs-calypso/wp-invite-users__viewer-spec.js
  test/e2e/specs/specs-calypso/wp-manage-domains-spec.js
Labels: [Status] Needs Review

#53329 Remove Lodash from sites selectors
  client/state/selectors/get-network-sites.js
  client/state/selectors/get-site-icon-id.js
  client/state/selectors/get-site-icon-url.js
  client/state/selectors/get-site-migration-status.js
  client/state/selectors/get-site-url.js
  client/state/selectors/is-connected-secondary-network-site.js
  client/state/selectors/is-domain-only-site.js
  client/state/selectors/is-eligible-for-dotcom-checklist.js
  client/state/selectors/is-eligible-for-upwork-support.ts
  client/state/selectors/is-mapped-domain-site.js
  client/state/selectors/is-site-eligible-for-full-site-editing.js
  client/state/selectors/is-site-failed-migration-source.js
  client/state/selectors/is-site-using-core-site-editor.js
  client/state/selectors/is-site-using-full-site-editing.js
  client/state/selectors/test/is-mapped-domain-site.js
  client/state/selectors/user-has-any-atomic-sites.js
  client/state/sites/selectors/build-seo-title.js
  client/state/sites/selectors/can-jetpack-site-auto-update-files.js
  client/state/sites/selectors/can-jetpack-site-update-files.js
  client/state/sites/selectors/get-customizer-url.js
  client/state/sites/selectors/get-jetpack-site-update-files-disabled-reasons.js
  client/state/sites/selectors/get-seo-title-formats-for-site.js
  client/state/sites/selectors/get-seo-title-formats.js
  client/state/sites/selectors/get-seo-title.js
  client/state/sites/selectors/get-site-by-slug.js
  client/state/sites/selectors/get-site-collisions.js
  client/state/sites/selectors/get-site-option.js
  client/state/sites/selectors/get-site-plan-slug.js
  client/state/sites/selectors/get-site-plan.ts
  client/state/sites/selectors/get-site-theme-showcase-path.js
  client/state/sites/selectors/get-updates-by-site-id.js
  client/state/sites/selectors/has-site-product.ts
  client/state/sites/selectors/index.js
  client/state/sites/selectors/is-jetpack-module-active.js
  client/state/sites/selectors/is-single-user-site.js
  client/state/sites/selectors/is-site-conflicting.js
  client/state/sites/test/selectors.js
Labels: [Status] Needs Review, [Type] Janitorial

#52522 Update site creation labels and an option
  client/lib/signup/step-actions/index.js
  client/signup/config/flows-pure.js
  client/signup/steps/p2-site/index.jsx
Labels: [Status] Needs Review

#53300 Framework: Remove abtest library
  .github/CODEOWNERS
  client/boot/common.js
  client/lib/abtest/README.md
  client/lib/abtest/active-tests.js
  client/lib/abtest/index.js
  client/lib/abtest/test/index.js
  client/lib/abtest/utility.js
  client/lib/signup/step-actions/index.js
  client/lib/user/user.js
  client/me/purchases/manage-purchase/index.jsx
  client/my-sites/checkout/composite-checkout/payment-method-helpers.js
  client/my-sites/plan-features-comparison/index.jsx
  client/my-sites/plan-features/index.jsx
  client/server/user-bootstrap/index.js
  client/state/products-list/selectors/plan-slug-to-plan-product.js
  client/state/selectors/get-active-discount.js
  client/state/selectors/test/get-active-discount.js
Labels: ABTest, Framework, [Status] Needs Review, [Type] Janitorial

#53367 ci(build): Add support for Firefox ESR
  package.json
Labels: [Status] Needs Review

#53330 Theme Showcase - Live Demos: Record Tracks Events
  client/my-sites/theme/main.jsx
Labels: OSS Citizen, Theme Showcase, [Pod] Design Selection, [Pri] Normal, [Status] Needs Review

#53382 Allow turning off each web payment method for specific currencies
  packages/wpcom-checkout/src/use-is-web-payment-available.ts
Labels: Checkout, [Status] Needs Review

#53387 Add @Automattic/quality-squad as one of the co-owners of test/e2e/.
  .github/CODEOWNERS
Labels: [Status] Needs Review

#52832 E2E fixes for Gutenberg 10.6.x / 10.7.x
  test/e2e/lib/gutenberg/gutenberg-editor-component.js
  test/e2e/specs/specs-wpcom/wp-calypso-gutenberg-upgrade-spec.js
  test/e2e/specs/specs-wpcom/wp-gutenberg-experimental-features-spec.js
Labels: [Status] Needs Review

#53395 E2E: Remove deprecated inserted block item CSS query
  test/e2e/lib/gutenberg/gutenberg-editor-component.js
Labels: [Status] Needs Review

#53241 Fix: incorrect description of the Live Chat feature
  client/lib/plans/features-list.js
  packages/calypso-products/src/plans-list.js
Labels: [Status] Needs Review, [Status] String Freeze, [Type] Bug

#53398 Cloudflare: fix class > className
  client/my-sites/site-settings/cloudflare.js
Labels: Site Settings, [Status] Needs Review, [Type] Janitorial

#53363 SiteNotice: add missing translate() call and improve moment.js date comparison
  client/my-sites/current-site/notice.jsx
Labels: [Status] Needs Review, [Type] Janitorial

#53369 Fix Professional Email mailbox validation
  client/lib/titan/new-mailbox.js
  client/my-sites/email/email-providers-comparison/index.jsx
  client/my-sites/email/titan-add-mailboxes/index.jsx
  client/my-sites/email/titan-add-mailboxes/titan-new-mailbox-list.jsx
  client/my-sites/email/titan-add-mailboxes/titan-new-mailbox.jsx
Labels: Email management, Professional Email, [Status] Needs Review, [Type] Bug

#53304 Jetpack Connect: Remove version checks from install step
  client/jetpack-connect/example-components/jetpack-connect.jsx
  client/jetpack-connect/install-instructions.jsx
  client/jetpack-connect/install-step.jsx
  client/jetpack-connect/style.scss
Labels: Jetpack, [Goal] Onboarding, [Pri] Low, [Status] Needs Review, [Type] Janitorial

#53225 Jetpack Connect: Refactor away from `lib/user` in route definitions
  client/jetpack-connect/controller.js
  client/jetpack-connect/index.js
Labels: Jetpack, [Status] Needs Review, [Type] Enhancement

#52230 Enables font smoothing on wpcom interfaces for Automatticians
  apps/editing-toolkit/editing-toolkit-plugin/common/index.php
  apps/editing-toolkit/editing-toolkit-plugin/common/index.scss
  apps/notifications/src/panel/Notifications.jsx
  apps/notifications/src/panel/boot/stylesheets/main.scss
  apps/notifications/src/panel/rest-client/wpcom.js
  apps/notifications/src/panel/utils/font-smoothing.js
  apps/notifications/src/standalone/index.js
  client/assets/stylesheets/_main.scss
  client/assets/stylesheets/gutenboarding.scss
  client/landing/gutenboarding/gutenboard.tsx
  client/landing/gutenboarding/hooks/test/use-body-class.test.ts
  client/landing/gutenboarding/hooks/use-body-class.ts
  client/landing/gutenboarding/stores/reader/index.ts
  client/layout/index.jsx
  client/layout/logged-out.jsx
  client/layout/masterbar/style.scss
  packages/data-stores/src/index.ts
  packages/data-stores/src/reader/actions.ts
  packages/data-stores/src/reader/constants.ts
  packages/data-stores/src/reader/index.ts
  packages/data-stores/src/reader/persist.ts
  packages/data-stores/src/reader/reducer.ts
  packages/data-stores/src/reader/resolvers.ts
  packages/data-stores/src/reader/selectors.ts
  packages/data-stores/src/reader/test/reader-store.test.ts
Labels: Design, [Status] Needs Review

#53370 Undocumented: Remove unused saveABTestData method
  client/lib/wpcom-undocumented/lib/undocumented.js
Labels: Framework, [Status] Needs Review, [Type] Janitorial

#53344 Jetpack Partner Portal: Add pages for listing and adding payment methods
  client/jetpack-cloud/sections/partner-portal/controller.tsx
  client/jetpack-cloud/sections/partner-portal/index.ts
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-add/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-list/index.tsx
  client/jetpack-cloud/sections/partner-portal/sidebar/index.tsx
  config/jetpack-cloud-development.json
  config/jetpack-cloud-stage.json
  packages/material-design-icons/src/editor/filled-attach_money-24px.svg
  packages/material-design-icons/svg-sprite/material-icons.svg
Labels: Jetpack Cloud, Jetpack Partner Portal, [Pri] Normal, [Size] M, [Status] Needs Review

#52871 Render new sidebar component on Jetpack sites
  client/state/selectors/is-nav-unification-enabled.js
Labels: Nav Unification, [Status] Ready to Merge

#53389 Remove lodash references from client/boot
  client/boot/common.js
  client/boot/locale.js
Labels: [Size] XS, [Status] Needs Review, [Type] Janitorial, i18n

#53346 Checkout: Move Giropay to wpcom-checkout package
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-methods/index.ts
  packages/composite-checkout/src/public-api.ts
  packages/wpcom-checkout/src/index.ts
  packages/wpcom-checkout/src/payment-methods/giropay.tsx
Labels: Checkout, [Estimate] 1, [Status] Ready to Merge

#53169 Playwright: Part 1. Implement components, pages and flows and migrate part of wp-likes spec.
  .teamcity/_self/projects/WebApp.kt
  packages/calypso-e2e/package.json
  packages/calypso-e2e/src/browser-manager.ts
  packages/calypso-e2e/src/data-helper.ts
  packages/calypso-e2e/src/decs.d.ts
  packages/calypso-e2e/src/lib/base-container.ts
  packages/calypso-e2e/src/lib/components/index.ts
  packages/calypso-e2e/src/lib/components/likes-component.ts
  packages/calypso-e2e/src/lib/components/navbar-component.ts
  packages/calypso-e2e/src/lib/components/sidebar-component.ts
  packages/calypso-e2e/src/lib/flows/index.ts
  packages/calypso-e2e/src/lib/flows/login-flow.ts
  packages/calypso-e2e/src/lib/flows/new-post-flow.ts
  packages/calypso-e2e/src/lib/index.ts
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
  packages/calypso-e2e/src/lib/pages/index.ts
  packages/calypso-e2e/src/lib/pages/my-home-page.ts
  test/e2e/.mocharc_playwright.yml
  test/e2e/config/default.json
  test/e2e/specs/specs-playwright/wp-likes-spec.js
Labels: [Status] Needs Review

#53423 Design Picker: Hide Coutoire design
  packages/design-picker/src/available-designs-config.json
Labels: Design Picker, [Status] Needs Review

#53244 Playwright: reduce boilerplate in test file
  packages/calypso-e2e/src/browser-manager.ts
  packages/calypso-e2e/src/data-helper.ts
  test/e2e/.mocharc_playwright.yml
  test/e2e/config/default.json
  test/e2e/specs/specs-playwright/wp-likes-spec.js
Labels: [Status] Needs Review

#53391 desktop: tweak title bar button styling
  desktop/public_desktop/default.css
  desktop/public_desktop/index.html
Labels: [Status] Needs Review

#53390 desktop: disable back to wordpress btn on login
  client/login/wp-login/login-links.jsx
Labels: [Status] Needs Review

#53388 desktop: fix window/title bar resize
  desktop/app/mainWindow/index.js
Labels: [Status] Needs Review

#52530 desktop: Bump version to 6.15.0
  desktop/app/app-handlers/updater/auto-updater/index.js
  desktop/app/lib/updater/index.js
  desktop/desktop-config/config-development.json
  desktop/desktop-config/config-release.json
  desktop/desktop-config/config-updater.json
  desktop/package.json
Labels: Releases, [Status] Needs Review

#53354 Playwright: separate style guide between Selenium and Playwright frameworks
  test/e2e/README.md
  test/e2e/docs/running-tests.md
  test/e2e/docs/style-guide-playwright.md
  test/e2e/docs/style-guide-selenium.md
  test/e2e/docs/style-guide.md
Labels: [Status] Needs Review

#53439 Revert "chore(lint): Fixes a few eslint errors"
  .eslintrc.js
  apps/notifications/.eslintrc.js
  apps/notifications/src/panel/helpers/notes.js
  apps/notifications/src/panel/templates/block-user.jsx
  apps/notifications/src/panel/templates/container-hotkey.jsx
  apps/notifications/src/panel/templates/summary-in-list.jsx
  apps/notifications/src/panel/templates/summary-in-single.jsx
  apps/o2-blocks/.eslintrc.js
  client/blocks/conversation-caterpillar/docs/example.jsx
  client/blocks/post-edit-button/docs/example.jsx
  client/blocks/reader-featured-video/docs/example.jsx
  client/blocks/reader-full-post/header.jsx
  client/blocks/reader-recommended-sites/docs/example.jsx
  client/blocks/reader-related-card/index.jsx
  client/components/back-button/docs/example.jsx
  client/components/count/docs/example.jsx
  client/components/diff-viewer/docs/example.jsx
  client/components/marked-lines/docs/example.jsx
  client/components/time-since/docs/example.jsx
  client/lib/css-safe-url/index.js
  client/lib/highlight/index.js
  client/lib/performance-tracking/use-performance-tracker-stop.js
  client/lib/phone-validation/index.jsx
  client/lib/post-normalizer/rule-content-remove-styles.js
  client/lib/reader-connect-site/index.js
  client/lib/shortcode/index.js
  client/my-sites/site-settings/amp/jetpack.jsx
  client/state/data-layer/wpcom/sites/utils.js
  client/state/push-notifications/utils.js
  client/state/reader/lists/reducer.js
  client/state/reader/lists/test/reducer.js
  packages/components/.eslintrc.js
  packages/eslint-plugin-wpcalypso/lib/rules/i18n-mismatched-placeholders.js
  packages/eslint-plugin-wpcalypso/lib/rules/i18n-named-placeholders.js
  packages/eslint-plugin-wpcalypso/lib/rules/i18n-no-placeholders-only.js
  packages/material-design-icons/README.md
  packages/wpcom.js/.eslintrc.js
  packages/wpcom.js/examples/media-editor/source.js
Labels: [Status] Needs Review

#53440 Revert "Revert "chore(lint): Fixes a few eslint errors""
  .eslintrc.js
  apps/notifications/.eslintrc.js
  apps/notifications/src/panel/helpers/notes.js
  apps/notifications/src/panel/templates/block-user.jsx
  apps/notifications/src/panel/templates/container-hotkey.jsx
  apps/notifications/src/panel/templates/summary-in-list.jsx
  apps/notifications/src/panel/templates/summary-in-single.jsx
  apps/o2-blocks/.eslintrc.js
  client/blocks/conversation-caterpillar/docs/example.jsx
  client/blocks/post-edit-button/docs/example.jsx
  client/blocks/reader-featured-video/docs/example.jsx
  client/blocks/reader-full-post/header.jsx
  client/blocks/reader-recommended-sites/docs/example.jsx
  client/blocks/reader-related-card/index.jsx
  client/components/back-button/docs/example.jsx
  client/components/count/docs/example.jsx
  client/components/diff-viewer/docs/example.jsx
  client/components/marked-lines/docs/example.jsx
  client/components/time-since/docs/example.jsx
  client/lib/css-safe-url/index.js
  client/lib/highlight/index.js
  client/lib/performance-tracking/use-performance-tracker-stop.js
  client/lib/phone-validation/index.jsx
  client/lib/post-normalizer/rule-content-remove-styles.js
  client/lib/reader-connect-site/index.js
  client/lib/shortcode/index.js
  client/my-sites/site-settings/amp/jetpack.jsx
  client/state/data-layer/wpcom/sites/utils.js
  client/state/push-notifications/utils.js
  client/state/reader/lists/reducer.js
  client/state/reader/lists/test/reducer.js
  packages/components/.eslintrc.js
  packages/eslint-plugin-wpcalypso/lib/rules/i18n-mismatched-placeholders.js
  packages/eslint-plugin-wpcalypso/lib/rules/i18n-named-placeholders.js
  packages/eslint-plugin-wpcalypso/lib/rules/i18n-no-placeholders-only.js
  packages/material-design-icons/README.md
  packages/wpcom.js/.eslintrc.js
  packages/wpcom.js/examples/media-editor/source.js
Labels: [Status] Needs Review

#53404 Add calypso.live comment to PRs
  .github/workflows/calypso-live.yml
  .teamcity/_self/projects/WebApp.kt
  bin/add-pr-comment.sh
Labels: [Status] Needs Review

#53302 Import: Use Redux current user for mapping authors
  client/state/imports/site-importer/actions.js
Labels: Framework, Import, Site Importer, [Status] Needs Review, [Type] Enhancement

#53301 User: Remove optimistic site count `(in|de)`crement methods
  client/lib/user/user.d.ts
  client/lib/user/user.js
  client/state/lib/middleware.js
Labels: Framework, [Status] Needs Review, [Type] Enhancement

#53402 Add a dev helper for quick switching between OAuth and cookies auth
  client/boot/common.js
  client/components/environment-badge/index.jsx
  client/document/index.jsx
  client/jetpack-cloud/index.js
  client/lib/auth-helper/index.jsx
  client/lib/auth-helper/style.scss
  client/lib/jetpack/oauth-override.ts
  client/lib/wp/browser.js
  client/sections.js
  client/server/pages/index.js
  config/development.json
  config/jetpack-cloud-development.json
  config/wpcalypso.json
Labels: 3rd Party Cookies, Framework, [Status] Needs Review

#53409 Remove feature flags for Woo-styling login and signup
  client/blocks/login/index.jsx
  client/blocks/login/login-form.jsx
  client/blocks/signup-form/index.jsx
  client/document/index.jsx
  client/jetpack-connect/auth-form-header.jsx
  client/jetpack-connect/authorize.js
  client/jetpack-connect/main-wrapper.jsx
  client/layout/index.jsx
  client/layout/logged-out.jsx
  client/lib/login/index.js
  client/login/wp-login/login-links.jsx
  client/server/pages/index.js
  client/signup/steps/user/index.jsx
  config/development.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Type] Janitorial

#53407 Remove removeFollowers helpers from wpcom.undocumented
  client/data/followers/use-remove-follower-mutation.js
  client/lib/wpcom-undocumented/lib/site.js
Labels: [Status] Needs Review, [Type] Janitorial

#53374 Remove the promisify helper from client/utils
  client/lib/signup/step-actions/fetch-sites-and-user.js
  client/utils.js
Labels: [Status] Needs Review, [Type] Janitorial

#53450 Allow `./bin/add-pr-comment.sh` to fail (happens if there is no PR, for example)
  .teamcity/_self/projects/WebApp.kt
  bin/add-pr-comment.sh
Labels: [Status] Needs Review

#53372 Plans: Remove unused price components
  client/my-sites/plan-price-free/index.tsx
  client/my-sites/plan-price-free/style.scss
  client/my-sites/plans/wpcom-plan-price/index.jsx
Labels: Plans, [Pri] Low, [Status] Needs Review, [Type] Janitorial

#53465 remove unused `requestFromUrl` data getter
  client/state/data-getters/index.js
  client/state/data-getters/request-from-url.js
Labels: Data, [Status] Needs Review

#53362 My Home: Skipping a view tells the backend which view specifically to skip
  client/my-sites/customer-home/cards/notices/celebrate-notice/index.jsx
  client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
  client/my-sites/customer-home/cards/tasks/task.jsx
  client/state/action-types.ts
  client/state/data-layer/wpcom/sites/home/layout/index.js
  client/state/home/actions.js
Labels: My Home Pod, [Status] Needs Review, [Status] Needs e2e Testing, [Type] Bug

#52853 Jetpack Search: Make instructions clearer for Business plan Instant Search toggle
  client/my-sites/site-settings/search.jsx
  client/my-sites/site-settings/settings-performance/main.jsx
  client/my-sites/site-settings/wrap-settings-form.jsx
  packages/calypso-products/src/main.js
Labels: Jetpack Search, Site Settings, [Status] Ready to Merge

#53296 Search: match Jetpack Cloud look and feel
  client/components/jetpack/upsell/index.tsx
  client/my-sites/jetpack-search/README.md
  client/my-sites/jetpack-search/content.tsx
  client/my-sites/jetpack-search/footer.tsx
  client/my-sites/jetpack-search/logo.tsx
  client/my-sites/jetpack-search/main.tsx
  client/my-sites/jetpack-search/placeholder.tsx
  client/my-sites/jetpack-search/style.scss
  client/my-sites/jetpack-search/upsell.tsx
Labels: Jetpack Cloud, Jetpack Search, [Status] Ready to Merge

#53455 Remove always-on manage/* feature flags
  client/blocks/product-purchase-features-list/custom-css.jsx
  client/blocks/product-purchase-features-list/customize-theme.jsx
  client/blocks/product-purchase-features-list/index.jsx
  client/gutenberg/editor/index.js
  client/me/purchases/index.js
  client/me/purchases/payment-methods/payment-method-list.jsx
  client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx
  client/my-sites/checkout/checkout-thank-you/ecommerce-plan-details.jsx
  client/my-sites/checkout/checkout-thank-you/jetpack-plan-details.jsx
  client/my-sites/customize/index.js
  client/my-sites/people/people-list-item/index.jsx
  client/my-sites/plugins/index.js
  client/my-sites/plugins/main.jsx
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/sidebar/site-menu.jsx
  client/my-sites/sidebar/tools-menu.jsx
  client/my-sites/site-settings/form-writing.jsx
  client/my-sites/site-settings/navigation.jsx
  client/my-sites/site-settings/settings-writing/index.js
  client/my-sites/types/controller.jsx
  client/my-sites/types/index.js
  config/README.md
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Type] Janitorial

#53406 Remove wpcom.undocumented().mailingList() methods
  client/lib/wpcom-undocumented/lib/mailing-list.js
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/mailing-lists/main.jsx
  client/mailing-lists/utils.js
Labels: [Status] Needs Review, [Type] Janitorial

#53469 SiftScience: Use Redux for current user
  client/lib/siftscience/README.md
  client/lib/siftscience/index.js
  client/my-sites/checkout/index.js
  client/my-sites/domains/index.js
Labels: Checkout, Domains, Framework, [Status] Needs Review, [Type] Enhancement

#53490 Fix addSubscriber/deleteSubscriber REST methods
  client/mailing-lists/utils.js
Labels: [Status] Needs Review

#53446 Fix the "Switch Site" arrow direction for RTL
  client/my-sites/current-site/index.jsx
Labels: [Status] Needs Review

#53305 Signup: Use Redux user in signup actions
  client/lib/signup/step-actions/index.js
  client/lib/signup/test/step-actions.js
Labels: Framework, Signup, [Status] Needs Review, [Type] Enhancement

#53405 Block Editor Tracking: Make sure undo and redo is tracked in all cases
  apps/wpcom-block-editor/src/wpcom/features/tracking.js
Labels: [Status] Needs Review

#53467 Desktop: Use current user from Redux
  client/lib/desktop-listeners/index.js
Labels: Desktop App, Framework, [Status] Needs Review, [Type] Enhancement

#53345 Jetpack Checkout: Set post purchase destination to wp-admin recommendations page.
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
  packages/calypso-products/src/constants/jetpack.ts
  packages/calypso-products/src/plans-utilities.js
Labels: Jetpack, Post Checkout, [Status] Needs Review

#53470 Fix: Reader not showing protocol-relative images
  client/lib/post-normalizer/rule-content-make-images-safe.js
  client/lib/post-normalizer/test/index.js
Labels: Reader, [Size] XS, [Status] Needs Review, [Type] Bug

#53311 Storefront: Add unique theme demo URL for Storefront as a temporary workaround
  client/my-sites/theme/main.jsx
  client/state/themes/selectors/get-theme-demo-url.js
Labels: Theme Showcase, [Status] Needs Review

#53392 Checkout: remove coupon notices before displaying new ones
  client/my-sites/checkout/cart/cart-messages.tsx
Labels: Checkout, [Estimate] 1, [Status] Ready to Merge

#53323 Playwright: migrate the SEO Preview test spec.
  packages/calypso-e2e/src/lib/components/sidebar-component.ts
  packages/calypso-e2e/src/lib/pages/index.ts
  packages/calypso-e2e/src/lib/pages/marketing-page.ts
  test/e2e/specs/specs-playwright/wp-seo__preview-spec.js
Labels: [Status] Needs Review

#53428 Remove lodash from my-sites/plans
  client/my-sites/plans/controller.jsx
  client/my-sites/plans/current-plan/current-plan-thank-you/thank-you.tsx
  client/my-sites/plans/current-plan/index.jsx
  client/my-sites/plans/current-plan/jetpack-checklist/index.tsx
  client/my-sites/plans/jetpack-plans/product-grid/index.tsx
  client/my-sites/plans/jetpack-plans/use-detect-window-boundary.ts
  client/my-sites/plans/jetpack-plans/utils.ts
  client/my-sites/plans/p2-plans-main.jsx
Labels: Checklist, Jetpack Search, Plans, [Size] XS, [Status] Needs Review, [Type] Janitorial

#53480 Add new eslint rule for calypos-e2e package: require-jsdoc.
  packages/calypso-e2e/.eslintrc.js
Labels: [Status] Needs Review

#53511 Plans: Use IntersectionObserver to control PlansFilterBar stickiness
  client/my-sites/plans/jetpack-plans/plans-filter-bar/index.tsx
  client/my-sites/plans/jetpack-plans/use-detect-window-boundary.ts
Labels: Plans, [Size] XS, [Status] Needs Review, [Type] Janitorial

#53133 Me: Add VAT Info page
  client/components/forms/form-setting-explanation/index.jsx
  client/me/purchases/billing-history/main.tsx
  client/me/purchases/billing-history/receipt.jsx
  client/me/purchases/billing-history/style.scss
  client/me/purchases/controller.jsx
  client/me/purchases/index.js
  client/me/purchases/paths.js
  client/me/purchases/titles.js
  client/me/purchases/vat-info/index.tsx
  client/me/purchases/vat-info/style.scss
  client/me/purchases/vat-info/use-vat-details.ts
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Billing, [Estimate] 3, [Status] Ready to Merge, [Type] Task

#53327 My Home: Remove code that handles the start_site_setup checklist task
  client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
  client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
  client/state/data-layer/wpcom/checklist/index.js
  client/state/selectors/is-site-checklist-complete.js
Labels: My Home Pod, [Status] Needs Review

#53421 Checkout: Display tax breakdown when available
  client/my-sites/checkout/composite-checkout/components/payment-method-step.tsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.js
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
  packages/shopping-cart/src/empty-carts.ts
  packages/shopping-cart/src/shopping-cart-endpoint.ts
  packages/wpcom-checkout/src/transformations.ts
  packages/wpcom-checkout/test/transformations.js
Labels: Checkout, [Status] Ready to Merge

#53520 Add error_code to Email Comparison clicks for diagnostics
  client/my-sites/email/email-providers-comparison/index.jsx
Labels: Email management, Professional Email, [Status] Needs Review

#53532 Fix JavaScript syntax highlighting on GitHub
  .gitattributes
Labels: [Status] Needs Review

#53498 Framework: Remove `userUtils.getLocaleSlug()`
  client/lib/user/utils.js
Labels: Framework, [Status] Needs Review, [Type] Janitorial

#53497 Checkout: Remove unnecessary `lib/user` mock from `getThankYouPageUrl`
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
Labels: Checkout, Framework, [Status] Needs Review, [Type] Janitorial

#53503 site-roles: migrate to use react query
  client/components/data/query-site-roles/README.md
  client/components/data/query-site-roles/index.jsx
  client/data/site-roles/use-site-roles-query.js
  client/data/site-roles/with-site-roles.js
  client/lib/wpcom-undocumented/lib/site.js
  client/my-sites/people/invite-people/index.jsx
  client/my-sites/people/role-select/index.jsx
  client/my-sites/site-settings/jetpack-site-stats.jsx
  client/state/action-types.ts
  client/state/site-roles/README.md
  client/state/site-roles/actions.js
  client/state/site-roles/init.js
  client/state/site-roles/package.json
  client/state/site-roles/reducer.js
  client/state/site-roles/schema.js
  client/state/site-roles/selectors.js
  client/state/site-roles/test/actions.js
  client/state/site-roles/test/reducer.js
  client/state/site-roles/test/selectors.js
  client/state/sites/selectors/get-wpcom-follower-role.js
  client/state/sites/selectors/index.js
Labels: Data, [Status] Needs Review

#53533 wpcom-undocumented: Remove unused site methods
  client/lib/wpcom-undocumented/lib/site.js
Labels: Framework, [Status] Needs Review, [Type] Janitorial

#53535 Sections: Re-order `/me/*` section definitions
  client/sections.js
Labels: Me, Server Side Rendering, [Status] Needs Review, [Type] Bug

#53408 i18n-utils: Add localize url mappings for `/theme` and `/themes`
  packages/i18n-utils/src/localize-url.tsx
  packages/i18n-utils/src/test/localize-url.js
Labels: Packages, [Status] Needs Review, i18n

#53491 Signup: Use Redux logged in user logic in utils
  client/lib/signup/flow-controller.ts
  client/lib/signup/step-actions/index.js
  client/signup/config/flows.js
  client/signup/controller.js
  client/signup/main.jsx
  client/signup/navigation-link/index.jsx
  client/signup/navigation-link/test/index.jsx
  client/signup/steps/domains/index.jsx
  client/signup/steps/survey/index.jsx
  client/signup/steps/user/index.jsx
  client/signup/test/flows.js
  client/signup/utils.js
Labels: Framework, Signup, [Status] Needs Review, [Type] Enhancement

#53494 Purchase Product: Refactor to use Redux user
  client/my-sites/purchase-product/controller.js
  client/my-sites/purchase-product/index.js
Labels: Framework, Jetpack, Jetpack Search, [Status] Needs Review, [Type] Enhancement

#53521 Remove pricing page A/A experiment
  client/my-sites/plans/jetpack-plans/selector.tsx
Labels: ABTest, Jetpack Cloud, [Size] XS, [Status] Needs Review

#53550 Fix Themes Placeholders Loading
  client/components/data/query-themes/index.jsx
Labels: [Status] Needs Review

#53526 Analytics: Fix recordTracksEvent import in analytics library docs
  packages/calypso-analytics/README.md
Labels: [Estimate] 1, [Status] Needs Review

#53216 Plans: Ensure that the interval layout is used for all
  client/my-sites/plans-features-main/index.jsx
  client/my-sites/plans-features-main/plan-type-selector.tsx
  client/my-sites/plans/main.jsx
  client/my-sites/plans/navigation.jsx
  client/state/selectors/is-eligible-for-wpcom-monthly-plan.js
  test/e2e/lib/pages/plans-page.js
  test/e2e/specs/specs-calypso/wp-plan-purchase__viewing-spec.js
Labels: Plans, Simple/Atomic Parity, [Status] Needs Review

#53487 VAT: add tracks events to details form
  client/me/purchases/vat-info/index.tsx
Labels: VAT, [Status] Needs Review

#53475 Desktop: simplify external links handler
  desktop/app/window-handlers/external-links/index.js
  desktop/app/window-handlers/external-links/open-in-browser/index.js
Labels: [Status] Needs Review

#53472 Desktop: Replace the title bar nav icons with new versions
  desktop/public_desktop/arrow-left.svg
  desktop/public_desktop/arrow-right.svg
  desktop/public_desktop/default.css
  desktop/public_desktop/index.html
  desktop/public_desktop/wordpress.svg
Labels: [Status] Needs Review

#53058 Add composeHandlers() helper
  client/controller/shared.js
  client/my-sites/themes/controller-logged-in.jsx
  client/my-sites/themes/validate-filters.js
Labels: [Status] Needs Review

#53332 Add button to open webmail for Professional Email purchases
  client/my-sites/checkout/checkout-thank-you/header.jsx
  client/my-sites/checkout/checkout-thank-you/style.scss
Labels: Professional Email, [Status] Needs Review

#53461 Desktop: Update the icon files and resources
  desktop/public_desktop/app-logo.png
  desktop/public_desktop/default.css
  desktop/public_desktop/failed-to-start.html
  desktop/public_desktop/hey.html
  desktop/public_desktop/index.html
  desktop/public_desktop/win10-tray-icon-notification.ico
  desktop/public_desktop/win10-tray-icon.ico
  desktop/public_desktop/win7-tray-icon-notification.ico
  desktop/public_desktop/win7-tray-icon.ico
  desktop/public_desktop/windows-tray-bubble.png
  desktop/public_desktop/wordpress-desktop.css
  desktop/resource/icons/background.png
  desktop/resource/icons/background@2x.png
  desktop/resource/icons/icon.icns
  desktop/resource/icons/icon.ico
Labels: [Status] Needs Review

#53417 Editor: Adding new fonts.
  apps/editing-toolkit/editing-toolkit-plugin/global-styles/README.md
  apps/editing-toolkit/editing-toolkit-plugin/global-styles/class-global-styles.php
Labels: Editor, [Pod] Design Selection, [Status] Needs Review

#53460 ci(e2e): Skip flaky test
  test/e2e/specs/specs-calypso/wp-my-home-support-search-spec.js
Labels: [Status] Needs Review

#53489 Remove the Redux navigation middleware and update Activity Log filter actions
  client/my-sites/activity/controller.jsx
  client/my-sites/backup/controller.js
  client/state/activity-log/actions.js
  client/state/index.js
  client/state/navigation/middleware.js
Labels: Activity Log, [Status] Needs Review

#53534 Remove wpcom.undocumented() payment config methods
  client/blocks/editor-checkout-modal/index.tsx
  client/lib/store-transactions/index.js
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/my-sites/checkout/checkout-system-decider.js
  client/my-sites/checkout/composite-checkout/payment-method-helpers.js
Labels: Checkout, [Status] Needs Review, [Type] Janitorial

#53565 My Home: Add aria labels and list markup to site setup checklist
  client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
  client/my-sites/customer-home/cards/tasks/site-setup-list/nav-item.jsx
  client/my-sites/customer-home/cards/tasks/site-setup-list/style.scss
Labels: Accessibility, Customer Home, My Home Pod, [Status] Needs Review

#53542 Remove signup feature flags
  client/blocks/upsell-nudge/index.jsx
  client/components/banner/index.jsx
  client/lib/login/index.js
  client/me/security-section-nav/index.jsx
  client/me/security/index.js
  client/my-sites/current-site/notice.jsx
  client/my-sites/sidebar/index.jsx
  client/my-sites/sidebar/site-menu.jsx
  client/my-sites/sidebar/test/sidebar.js
  client/my-sites/sidebar/tools-menu.jsx
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
  client/signup/steps/site-type/index.jsx
  client/signup/steps/site-type/style.scss
  client/signup/steps/theme-selection/index.jsx
  client/state/sites/selectors/can-current-user-use-any-woocommerce-based-store.js
  client/state/sites/test/selectors.js
  config/_shared.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Type] Janitorial

#53573 `useHappinessEngineersQuery`: use `wp.req.get` directly
  client/data/happiness-engineers/use-happiness-engineers-query.js
  client/lib/wpcom-undocumented/lib/undocumented.js
Labels: Data, [Pri] Low, [Status] Needs Review, [Type] Janitorial

#53576 State: Move post-invite-accept user fetching to action
  client/state/invites/actions.js
  client/state/lib/middleware.js
Labels: People Management, State, [Status] Ready to Merge, [Type] Bug

#53496 Checkout: Use Redux to check for logged in user
  client/my-sites/checkout/controller.jsx
Labels: Checkout, Framework, [Status] Needs Review, [Type] Enhancement

#53538 move `getWpcomFollowerRole` out of selector space
  client/lib/get-wpcom-follower-role.js
  client/my-sites/people/invite-people/index.jsx
  client/my-sites/people/role-select/index.jsx
  client/state/sites/selectors/index.js
Labels: [Status] Needs Review, [Type] Janitorial

#53582 State: Introduce `clearCurrentUser` thunk
  client/state/action-types.ts
  client/state/current-user/actions.js
Labels: State, [Status] Needs Review, [Type] Enhancement

#53502 E2E: Create a tmp free site for domain tests
  test/e2e/lib/components/domain-registration-unavailable-component.js
  test/e2e/lib/components/sidebar-component.js
  test/e2e/lib/pages/domains-page.js
  test/e2e/specs/specs-calypso/wp-manage-domains-spec.js
  test/e2e/specs/specs-calypso/wp-manage-domains__add-a-domain-spec.js
  test/e2e/specs/specs-calypso/wp-manage-domains__map-a-domain-spec.js
Labels: [Status] Needs Review

#53340 E2E: Clean up & document driver helpers
  test/e2e/config/default.json
  test/e2e/config/development.json
  test/e2e/config/test.json
  test/e2e/docs/config_values.md
  test/e2e/lib/driver-helper.js
  test/e2e/lib/flows/jetpack-connect-flow.js
  test/e2e/lib/hooks/browser-logs.js
  test/e2e/lib/pages/frontend/comments-area-component.js
  test/e2e/lib/pages/wp-admin/wp-admin-customizer-page.js
  test/e2e/lib/pages/wp-admin/wp-admin-dashboard-page.js
  test/e2e/lib/pages/wp-admin/wp-admin-new-user-page.js
  test/e2e/lib/pages/wp-admin/wp-admin-sidebar.js
  test/e2e/specs/specs-calypso/wp-theme__switch-activate-spec.js
  test/e2e/specs/specs-jetpack/wp-jetpack-connect-spec.js
  test/e2e/specs/specs-jetpack/wp-jetpack-plans-spec.js
Labels: [Status] Ready to Merge

#53549 Minor reskinned signup style improvments
  client/blocks/signup-form/index.jsx
  client/signup/main.jsx
  client/signup/steps/user/index.jsx
  client/signup/style.scss
Labels: [Status] Design Input Requested, [Status] Needs Design Review, [Status] Needs Review

#53590 Urgent follow up: remove jumper flag for reskinned
  client/signup/main.jsx
Labels: Expedited Review, [Status] Needs Review

#53579 `useRemoveViewerMutation`: align with current practices
  client/data/viewers/use-remove-viewer-mutation.js
  client/lib/wpcom-undocumented/lib/site.js
  client/my-sites/people/viewers-list/index.jsx
  client/my-sites/people/viewers-list/viewers.jsx
Labels: Data, [Status] Needs Review, [Type] Janitorial

#53594 Plan Grid: Allow purchase of monthly plans before site creation
  client/state/selectors/is-eligible-for-wpcom-monthly-plan.js
Labels: [Status] Needs Review

#53560 Plans: Split jetpack-plans 'utils' into separate files
  client/components/jetpack/card/jetpack-product-card/time-frame.tsx
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
  client/my-sites/plans/jetpack-plans/build-card-features-from-item.ts
  client/my-sites/plans/jetpack-plans/checkout.ts
  client/my-sites/plans/jetpack-plans/constants.ts
  client/my-sites/plans/jetpack-plans/controller.tsx
  client/my-sites/plans/jetpack-plans/convert-slug-terms.ts
  client/my-sites/plans/jetpack-plans/get-price-tier-for-units.ts
  client/my-sites/plans/jetpack-plans/manage-site-purchase.ts
  client/my-sites/plans/jetpack-plans/object-is-plan.ts
  client/my-sites/plans/jetpack-plans/plan-upgrade/index.tsx
  client/my-sites/plans/jetpack-plans/plans-filter-bar/get-highest-annual-discount.ts
  client/my-sites/plans/jetpack-plans/plans-filter-bar/index.tsx
  client/my-sites/plans/jetpack-plans/product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-card/product-above-button-text.ts
  client/my-sites/plans/jetpack-plans/product-card/product-button-label.ts
  client/my-sites/plans/jetpack-plans/product-card/product-tooltip.ts
  client/my-sites/plans/jetpack-plans/product-grid/utils.ts
  client/my-sites/plans/jetpack-plans/selector.tsx
  client/my-sites/plans/jetpack-plans/slug-to-selector-product.ts
  client/my-sites/plans/jetpack-plans/test/utils.js
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
  client/my-sites/plans/jetpack-plans/utils.ts
Labels: Checkout, Plans, [Size] XS, [Status] Needs Review, [Type] Janitorial

#53596 Revert "Jetpack Checkout: Set post purchase destination to wp-admin recommendations page."
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
  packages/calypso-products/src/constants/jetpack.ts
  packages/calypso-products/src/plans-utilities.js
Labels: [Status] Needs Review

#53597 Tests- Add trigger and notifications for visual regression testing
  .teamcity/_self/projects/WPComTests.kt
Labels: [Status] Needs Review

#53607 e2e- Skip this test until a fix can be found
  test/e2e/specs/specs-calypso/wp-theme__switch-activate-spec.js
Labels: [Status] Needs Review

#53610 Me: Enable the VAT details form in production
  config/production.json
Labels: VAT, [Status] Needs Review

#53571 My Home: "Create a logo" link renamed to "Create a logo with Fiverr"
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
Labels: My Home Pod, [Status] Needs Review

#53570 My Home: Remove icons from educational material cards on My Home
  client/my-sites/customer-home/cards/education/earn/index.jsx
  client/my-sites/customer-home/cards/education/free-photo-library/index.jsx
Labels: My Home Pod, [Status] Needs Review

#53569 My Home: Remove chevrons from internal links on My Home
  client/my-sites/customer-home/cards/actions/quick-links/action-box.jsx
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
  client/my-sites/customer-home/cards/actions/quick-links/style.scss
  client/my-sites/customer-home/cards/features/go-mobile/style.scss
  client/my-sites/customer-home/cards/features/help-search/index.jsx
  client/my-sites/customer-home/cards/features/help-search/style.scss
  client/my-sites/customer-home/cards/tasks/style.scss
Labels: My Home Pod, [Status] Needs Review

#53600 Activate Google Analytics on Jetpack Cloud/Calypso Green
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
Labels: Analytics, Jetpack Cloud, [Status] Needs Review

#53603 Playwright: fix eslint errors.
  packages/calypso-e2e/src/hooks/recording.ts
  packages/calypso-e2e/src/lib/pages/marketing-page.ts
  packages/calypso-e2e/src/lib/pages/my-home-page.ts
Labels: [Status] Needs Review

#53572 My Home: Secondary area of My Home supports the support search card
  client/my-sites/customer-home/locations/secondary/index.jsx
Labels: My Home Pod, [Status] Needs Review

#53458 desktop: add appx target
  .circleci/config.yml
  desktop/app/app-handlers/updater/index.js
  desktop/app/app-handlers/updater/manual-updater/index.js
  desktop/app/lib/config/index.js
  desktop/bin/build-desktop-config.js
  desktop/electron-builder-appx.json
  desktop/electron-builder.json
  desktop/package.json
  desktop/resource/appx/Square150x150Logo.png
  desktop/resource/appx/Square150x150Logo.targetsize-150_altform-unplated.png
  desktop/resource/appx/Square44x44Logo.png
  desktop/resource/appx/Square44x44Logo.targetsize-44_altform-unplated.png
  desktop/resource/appx/StoreLogo.png
  desktop/resource/appx/Wide310x150Logo.png
  desktop/resource/background.png
  desktop/resource/background@2x.png
  desktop/resource/icon.icns
  desktop/resource/icon.ico
Labels: [Status] Needs Review

#53368 My Home: Play Store button shouldn't on the Go Mobile card on iPad
  client/my-sites/customer-home/cards/features/go-mobile/index.jsx
  client/my-sites/customer-home/cards/features/go-mobile/style.scss
Labels: Mobile Web, My Home Pod, [Status] Needs Review

#53479 Wpcom plugins: Add PR reminder comment
  .teamcity/_self/PluginBaseBuild.kt
  .teamcity/_self/projects/WPComPlugins.kt
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
Labels: [Status] Needs Review
