Repository Automattic/wp-calypso, pull requests merged in 2021-12, with the labels that each got.

#58561 Remove site picker step from woocommerce-installation
  client/signup/config/flows-pure.js
  client/signup/config/steps-pure.js
  client/signup/controller.js
  client/signup/steps/woocommerce-install/confirm/index.tsx
  client/signup/steps/woocommerce-install/index.tsx
  client/signup/steps/woocommerce-install/select-site/index.tsx
  client/signup/steps/woocommerce-install/select-site/style.scss
  client/signup/steps/woocommerce-install/transfer/index.tsx
Labels: [Status] Needs Review, [Status] Ready to Merge

#58582 Cleanup various superfluous arguments
  client/blocks/app-banner/index.jsx
  client/landing/login/common.js
  client/my-sites/controller.js
  client/my-sites/site-settings/analytics/form-cloudflare-analytics.js
  client/my-sites/site-settings/analytics/form-google-analytics-simple.jsx
  client/my-sites/stats/controller.jsx
  client/root.js
  client/state/data-layer/wpcom/sites/blog-stickers/index.js
Labels: Framework, [Status] Needs Review, [Type] Janitorial

#58583 Activity Log: Fix template syntax in string literal
  client/state/data-layer/wpcom/activity-log/rewind/to/index.js
Labels: [Pri] Low, [Status] Needs Review, [Type] Janitorial, Activity Log

#58585 State: Cleanup unused Reader action types
  client/state/reader/action-types.js
Labels: [Status] Needs Review, Reader, [Type] Janitorial, State

#58580 Store Stats: Fix direct state mutation in search form
  client/my-sites/store/app/store-stats/referrers/index.js
Labels: [Type] Bug, Stats, [Status] Needs Review, Store

#58586 State: Remove unused `getCurrentUserLocaleVariant` selector
  client/state/current-user/selectors.js
  client/state/current-user/test/selectors.js
Labels: [Status] Needs Review, [Type] Janitorial, State

#58584 Comments: Cleanup unused component state in `PostCommentList`
  client/blocks/comments/post-comment-list.jsx
Labels: [Pri] Low, [Status] Needs Review, [Type] Janitorial, Comments

#58491 New import E2E tests
  packages/calypso-e2e/src/lib/flows/start-import-flow.ts
  test/e2e/specs/specs-playwright/wp-start__importer.ts
Labels: [Status] Needs Review

#58602 Woop Installer: Add checkout step
  client/signup/steps/woocommerce-install/confirm/index.tsx
  client/signup/steps/woocommerce-install/hooks/use-woop-handling/Readme.md
  client/signup/steps/woocommerce-install/hooks/use-woop-handling/index.ts
Labels: [Type] Enhancement, [Status] Needs Review, [Size] L, Woop

#58700 Woop installer: improve redirect_to checkout URL
  client/signup/steps/woocommerce-install/hooks/use-woop-handling/index.ts
Labels: [Type] Enhancement, [Status] Needs Review, [Size] S, Woop

#58672 Update additional info column to a fixed width of 25%.
  client/my-sites/plugins/style.scss
Labels: Marketplace

#58681 Plugin focus and hover effect
  client/my-sites/plugins/plugins-browser-item/style.scss
  client/my-sites/plugins/style.scss
Labels: [Status] Needs Review

#58597 Domains: Add conditions to show transfer options depending on type of site
  client/my-sites/domains/domain-management/transfer/transfer-page/index.tsx
  client/my-sites/domains/domain-management/transfer/transfer-page/types.tsx
Labels: [Status] Needs Review, Domains

#58679 Checkout: Record plan length change analytics directly
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/record-analytics.js
Labels: [Status] Ready to Merge

#58600 WordAds: Stop collecting WordAds owner information for US residents
  client/my-sites/earn/ads/form-settings.jsx
  client/state/selectors/get-wordads-settings.js
  client/state/selectors/test/get-wordads-settings.js
Labels: [Status] Needs Review

#58676 Checkout: Record 3ds auth modal display analytics directly
  client/my-sites/checkout/composite-checkout/lib/existing-card-processor.ts
  client/my-sites/checkout/composite-checkout/lib/multi-partner-card-processor.ts
  client/my-sites/checkout/composite-checkout/record-analytics.js
Labels: [Status] Needs Review

#58553 Domains: Add header to the redesigned transfer page
  client/my-sites/domains/domain-management/transfer/transfer-page/index.tsx
  client/my-sites/domains/domain-management/transfer/transfer-page/style.scss
Labels: [Status] Needs Review, Domains

#58534 Videos UI: Add the call-to-action capabilities to the modal footer component.
  client/components/videos-ui/modal-footer-bar.jsx
  client/components/videos-ui/modal-footer-bar.scss
  client/components/videos-ui/modal-header-bar.jsx
  client/components/videos-ui/style.scss
Labels: [Status] Needs Review, Blogger Experience Pod

#58660 Domains: Email setup component design fixes
  client/my-sites/domains/domain-management/email-setup/index.jsx
  client/my-sites/domains/domain-management/email-setup/style.scss
Labels: [Status] Needs Review, Domains

#58399 Domains: Update bulk contact information editing to use the new components
  client/me/purchases/manage-purchase/auto-renew-toggle/index.jsx
  client/my-sites/domains/domain-management/list/all-domains.jsx
  client/my-sites/domains/domain-management/list/bulk-edit-contact-info.jsx
  client/my-sites/domains/domain-management/list/domain-row.jsx
  client/my-sites/domains/domain-management/list/domain-row.scss
  client/my-sites/domains/domain-management/list/domains-table.jsx
  client/my-sites/domains/domain-management/list/style.scss
Labels: [Status] Needs Review, Domains

#58691 Videos UI: Record a Tracks event for every video marked as completed.
  client/components/videos-ui/index.jsx
  client/components/videos-ui/video-player.jsx
Labels: [Status] Needs Review, Blogger Experience Pod

#58668 Update/marketplace-thank-you-page
  client/assets/images/marketplace/check-circle.svg
  client/components/thank-you/index.tsx
  client/components/thank-you/style.scss
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
Labels: [Status] Needs Review

#58715 E2E: disable flakey spec `Site Import`.
  test/e2e/specs/specs-playwright/wp-start__importer.ts
Labels: [Status] Needs Review

#58707 Videos UI: keeps the video ref inside the VideoPlayer component
  client/components/videos-ui/index.jsx
  client/components/videos-ui/video-player.jsx
Labels: [Status] Needs Review

#58721 Licensing post-checkout: Fix site dropdown width when site URL's are short
  client/my-sites/checkout/checkout-thank-you/licensing-thank-you-auto-activation.tsx
  client/my-sites/checkout/checkout-thank-you/style.scss
Labels: Jetpack, [Status] Needs Review, Jetpack Licensing

#58684 Playwright: wait until checkout cart stabilizes.
  packages/calypso-e2e/src/lib/pages/cart-checkout-page.ts
Labels: [Status] Needs Review

#58717 Videos UI: Tracks for completed video.
  client/components/videos-ui/index.jsx
  client/components/videos-ui/video-player.jsx
Labels: [Status] Needs Review, Blogger Experience Pod

#58719 Woop installer: Implement new design / error handling
  client/components/eligibility-warnings/card/index.tsx
  client/components/eligibility-warnings/domain-warning/index.tsx
  client/components/eligibility-warnings/info-label/index.tsx
  client/components/eligibility-warnings/plan-warning/index.tsx
  client/components/eligibility-warnings/warnings-list/index.tsx
  client/components/warning-card/index.tsx
  client/signup/config/steps-pure.js
  client/signup/steps/woocommerce-install/confirm/index.tsx
  client/signup/steps/woocommerce-install/confirm/style.scss
  client/signup/steps/woocommerce-install/hooks/use-woop-handling/index.ts
  packages/onboarding/src/action-buttons/index.tsx
  packages/onboarding/src/action-buttons/style.scss
Labels: [Type] Enhancement, [Status] Ready to Merge, [Size] L, Woop

#58267 Playwright: QoL improvements to the authentication cookie mechanism
  packages/calypso-e2e/src/browser-manager.ts
  packages/calypso-e2e/src/lib/pages/login-page.ts
  test/e2e/lib/jest/globalSetup.ts
Labels: [Status] Needs Review

#58728 Follow-up to Playwright: refinements to auth cookie login method
  packages/calypso-e2e/src/browser-manager.ts
  test/e2e/lib/jest/globalSetup.ts
Labels: [Status] Needs Review

#58730 Revert "Playwright: wait until checkout cart stabilizes."
  packages/calypso-e2e/src/lib/pages/cart-checkout-page.ts
Labels: [Status] Needs Review

#58630 chore: Drop unused fork-ts-checker-webpack-plugin
  package.json
  yarn.lock
Labels: [Status] Needs Review

#58640 Drop jest-junit
  .teamcity/_self/projects/WPComPlugins.kt
  .teamcity/_self/projects/WebApp.kt
  apps/editing-toolkit/package.json
  package.json
  yarn.lock
Labels: [Status] Needs Review

#58633 core: Clean up tour-kit package
  packages/tour-kit/README.md
  packages/tour-kit/package.json
  packages/tour-kit/src/index.stories.tsx
  packages/tour-kit/tsconfig-cjs.json
  yarn.lock
Labels: [Status] Needs Review, Tour Kit

#58628 Drop regenerator runtime
  package.json
  packages/calypso-polyfills/browser.js
  packages/calypso-polyfills/package.json
  packages/data-stores/jest.config.js
  packages/data-stores/package.json
  packages/viewport-react/package.json
  packages/viewport-react/test/index.js
  packages/viewport/package.json
  packages/viewport/test/index.js
  test/client/jest.config.js
  test/server/jest.config.js
  yarn.lock
Labels: [Status] Needs Review

#58549 Add count bubble besides the status header in the site domains list
  client/my-sites/domains/domain-management/list/all-domains.jsx
  client/my-sites/domains/domain-management/list/domains-table-header.jsx
  client/my-sites/domains/domain-management/list/site-domains.jsx
  client/my-sites/domains/domain-management/list/style.scss
  client/my-sites/domains/domain-management/list/test/utils.js
  client/my-sites/domains/domain-management/list/utils.js
Labels: [Status] Needs Review, Domains

#58570 Remove usages of Lodash has
  client/blocks/author-compact-profile/index.jsx
  client/blocks/reader-combined-card/post.jsx
  client/components/date-range/index.js
  client/gutenberg/editor/controller.js
  client/me/account/main.jsx
  client/my-sites/importer/importing-pane.jsx
  client/my-sites/importer/site-importer/site-importer-input-pane.jsx
  client/my-sites/site-settings/date-time-format/utils.js
  client/my-sites/site-settings/form-general.jsx
  client/my-sites/themes/theme-options.js
  client/post-editor/editor-diff-viewer/index.jsx
  client/reader/xpost-helper.js
  client/state/comments/ui/reducer.js
  client/state/happychat/middleware-calypso.js
  client/state/reader/lists/reducer.js
  client/state/reader/lists/selectors.js
  client/state/signup/progress/reducer.js
  client/state/support-articles-alternates/selectors.js
  client/state/ui/action-log/reducer.js
Labels: [Status] Needs Review

#58735 Blank box appearing on a search result for specific plugin keywords
  client/my-sites/plugins/plugins-browser-list/style.scss
  client/my-sites/plugins/plugins-browser/index.jsx
Labels: [Status] Needs Review, Marketplace

#58740 Plugin Details: Show CTA only when plugin status has resolved.
  client/my-sites/plugins/plugin-details.jsx
  client/my-sites/plugins/style.scss
Labels: [Status] Needs Review

#58703 Emails: Update Email Forwarding form in Email Comparison page to be more consistent
  client/my-sites/email/email-forwarding/email-forwarding-add-new-compact.jsx
  client/my-sites/email/email-forwarding/style.scss
  client/my-sites/email/email-providers-comparison/index.jsx
  client/my-sites/email/email-providers-comparison/style.scss
Labels: [Status] Needs Review, G Suite

#58546 E2E: Fix publishing when certain blocks cause the post-publish panel to close
  packages/calypso-e2e/src/lib/blocks/image-block.ts
  packages/calypso-e2e/src/lib/blocks/logos-block.ts
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
  test/e2e/specs/specs-playwright/wp-blocks__coblocks.ts
  test/e2e/specs/specs-playwright/wp-blocks__media-spec.ts
Labels: [Status] Needs Review

#58699 Small fixes for the domains table design view
  client/my-sites/domains/domain-management/components/breadcrumbs/style.scss
  client/my-sites/domains/domain-management/list/domain-row.jsx
  client/my-sites/domains/domain-management/list/domain-row.scss
  client/my-sites/domains/domain-management/list/free-domain-item.jsx
  client/my-sites/domains/domain-management/list/free-domain-item.scss
  client/my-sites/domains/domain-management/list/style.scss
Labels: [Status] Needs Review

#58677 Theme Showcase: Remove references to individual theme prices
  client/components/theme/index.jsx
  client/components/theme/style.scss
  client/components/theme/test/__snapshots__/index.jsx.snap
  client/components/theme/test/index.jsx
  client/my-sites/theme/main.jsx
Labels: [Status] Needs Review, Theme Showcase

#58756 Fix Reader combined card error on missing author
  client/blocks/reader-combined-card/post.jsx
Labels: [Type] Bug, [Status] Needs Review, Reader

#58727 Videos UI - Add front-end reflection of videos UI user progression
  client/components/videos-ui/index.jsx
  client/components/videos-ui/video-player.jsx
  client/data/courses/use-update-user-course-progression-mutation.js
Labels: [Status] Needs Review, Blogger Experience Pod

#58754 Woop installer: skip to transfer when ready
  client/signup/steps/woocommerce-install/confirm/index.tsx
  client/signup/steps/woocommerce-install/hooks/use-woop-handling/Readme.md
  client/signup/steps/woocommerce-install/hooks/use-woop-handling/index.ts
Labels: [Type] Enhancement, [Status] Ready to Merge, [Size] M, Woop

#58723 Checkout: Record cart item removal analytics events directly
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-review.tsx
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
  client/my-sites/checkout/composite-checkout/record-analytics.js
  packages/wpcom-checkout/src/checkout-line-items.tsx
Labels: [Status] Ready to Merge

#58722 Checkout: Record "thank you generated" logstash event directly
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/record-analytics.js
Labels: [Status] Ready to Merge

#58609 Shopping Cart: Convert lib/cart-values to TypeScript
  client/lib/cart-values/cart-items.js
  client/lib/cart-values/cart-items.ts
  client/lib/cart-values/index.js
  client/lib/cart-values/index.ts
  packages/calypso-products/src/is-free-wordpress-com-domain.ts
  packages/shopping-cart/src/types.ts
Labels: [Status] Ready to Merge, Shopping Cart

#58743 Add premium theme ref to cart
  client/my-sites/checkout/composite-checkout/lib/get-plan-features.ts
Labels: [Status] Needs Review

#58695 Full Site Editing Design Picker: Enable Arbutus theme
  packages/design-picker/src/available-designs-config.json
Labels: [Status] Needs Review, [Goal] Full Site Editing, Design Picker

#58565 Design Picker: Make blank canvas as button
  .stylelintrc
  client/signup/steps/design-picker/index.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
  packages/design-picker/src/available-designs-config.json
  packages/design-picker/src/components/design-picker-category-filter/index.tsx
  packages/design-picker/src/components/featured-picks-buttons/index.tsx
  packages/design-picker/src/components/featured-picks-buttons/style.scss
  packages/design-picker/src/components/index.tsx
  packages/design-picker/src/index.ts
  packages/design-picker/src/types.ts
  packages/design-picker/src/utils/__tests__/available-designs.test.ts
  packages/design-picker/src/utils/available-designs.ts
Labels: [Status] Needs Review, [Status] String Freeze, Blogger Experience Pod

#58796 Design Picker: Turn on making Blank Canvas a button
  config/horizon.json
  config/production.json
  config/stage.json
Labels: [Status] Needs Review, Blogger Experience Pod

#58702 Use new woo eligibility hook in woo install landing page
  client/components/cta-section/index.tsx
  client/my-sites/woocommerce/controller.js
  client/my-sites/woocommerce/dashboard/required-plugins-install-view.jsx
  client/my-sites/woocommerce/index.js
  client/my-sites/woocommerce/main.jsx
  client/my-sites/woocommerce/woop/landing-page.tsx
  client/signup/steps/woocommerce-install/confirm/index.tsx
  client/signup/steps/woocommerce-install/hooks/use-woop-handling/index.ts
Labels: [Type] Enhancement, [Status] Needs Review, [Size] S, Woop

#58744 Checkout: Show refund periods for each product if DIFM Lite is in cart
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx
  client/my-sites/checkout/composite-checkout/lib/get-refund-text.ts
Labels: [Status] Needs Review, difm-lite

#58658 Tour Kit: viewport based reference element and code style refactors
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/style-tour.scss
  packages/tour-kit/.storybook/preview.js
  packages/tour-kit/package.json
  packages/tour-kit/src/components/tour-kit-frame.tsx
  packages/tour-kit/src/components/tour-kit-overlay.tsx
  packages/tour-kit/src/components/tour-kit-portal.tsx
  packages/tour-kit/src/components/tour-kit-spotlight.tsx
  packages/tour-kit/src/index.ts
  packages/tour-kit/src/styles.scss
  packages/tour-kit/src/types-patch.d.ts
  yarn.lock
Labels: [Status] Needs Review, Mobile Web, Editor Welcome, Welcome Tour, Tour Kit

#58711 Add type definitions to interpolate-components
  packages/interpolate-components/CHANGELOG.md
  packages/interpolate-components/README.md
  packages/interpolate-components/package.json
  packages/interpolate-components/types/index.d.ts
  yarn.lock
Labels: [Status] Needs Review

#58745 Simplify the QueryMediaStorage component and related actions and state
  client/components/data/query-media-storage/index.jsx
  client/state/action-types.ts
  client/state/data-layer/wpcom/sites/media-storage/index.js
  client/state/data-layer/wpcom/sites/media-storage/test/__snapshots__/index.js.snap
  client/state/data-layer/wpcom/sites/media-storage/test/index.js
  client/state/sites/media-storage/reducer.js
  client/state/sites/media-storage/selectors.js
  client/state/sites/media-storage/test/reducer.js
  client/state/sites/media-storage/test/selectors.js
Labels: [Status] Needs Review, Media

#58762 Server: remove the handleLocaleSubdomains route handler
  client/server/pages/index.js
  client/server/pages/test/index.js
Labels: [Status] Needs Review

#58784 Update PluginUpdateIndicator layout and position
  client/my-sites/plugins/plugin-action/plugin-action.jsx
  client/my-sites/plugins/plugin-action/style.scss
  client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx
  client/my-sites/plugins/plugin-remove-button/index.jsx
  client/my-sites/plugins/plugin-remove-button/style.scss
  client/my-sites/plugins/plugin-site-jetpack/index.jsx
  client/my-sites/plugins/plugin-site-jetpack/style.scss
  client/my-sites/plugins/plugin-site-update-indicator/index.jsx
  client/my-sites/plugins/plugin-site-update-indicator/style.scss
Labels: Marketplace

#58768 Woop installer: Error in landing page, improve loading state, handling Atomic sites
  client/components/cta-section/index.tsx
  client/my-sites/woocommerce/woop/landing-page.tsx
  client/signup/steps/woocommerce-install/confirm/index.tsx
  client/signup/steps/woocommerce-install/confirm/style.scss
  client/signup/steps/woocommerce-install/hooks/use-woop-handling/Readme.md
  client/signup/steps/woocommerce-install/hooks/use-woop-handling/index.ts
  client/state/selectors/has-active-site-feature.js
Labels: [Type] Enhancement, [Status] Needs Review, [Size] M, Woop

#58528 Videos UI: Add a header component for onboarding.
  client/components/videos-ui/index.jsx
  client/components/videos-ui/onboarding-footer-bar.jsx
  client/components/videos-ui/onboarding-footer-bar.scss
  client/components/videos-ui/onboarding-header-bar.jsx
  client/components/videos-ui/onboarding-header-bar.scss
  client/components/videos-ui/style.scss
Labels: [Status] Needs Review, Blogger Experience Pod

#58781 Videos UI: Remove duplicate Tracks event for video completion.
  client/components/videos-ui/video-player.jsx
Labels: [Status] Needs Review, Blogger Experience Pod

#58809 Fix showing presales chat button on checkout page
  client/my-sites/checkout/composite-checkout/components/checkout-help-link.tsx
Labels: [Status] Needs Review, Checkout

#58810 Add keyboard event for the PluginSiteUpdateIndicator.
  client/my-sites/plugins/plugin-site-update-indicator/index.jsx
  client/my-sites/plugins/plugin-site-update-indicator/style.scss
Labels: [Status] Needs Review, Marketplace

#58747 Add premium theme ref to /start/plans
  client/lib/plans/features-list.js
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review

#58779 [Fix] woop confirmation step mobile styles
  client/components/eligibility-warnings/card/index.tsx
  client/components/eligibility-warnings/info-label/index.tsx
  client/signup/steps/woocommerce-install/confirm/index.tsx
  client/signup/steps/woocommerce-install/confirm/style.scss
Labels: [Status] Ready to Merge

#58662 Domains: Add right-hand column to the transfer page
  client/my-sites/domains/domain-management/transfer/transfer-page/index.tsx
  client/my-sites/domains/domain-management/transfer/transfer-page/style.scss
Labels: [Status] Needs Review, Domains

#58820 Update WP.me Shortlinks support info URL
  client/my-sites/site-settings/shortlinks.jsx
Labels: Jetpack, [Type] Janitorial

#58221 Start User: Add Continue as user to the sign in flow
  client/blocks/login/continue-as-user.jsx
  client/blocks/login/continue-as-user.scss
  client/blocks/signup-form/index.jsx
  client/signup/config/flows.js
  client/signup/steps/user/index.jsx
  client/signup/style.scss
Labels: [Status] Needs Review

#58785 Checkout: Record stored card error and card invalid field error directly
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-fields.js
  client/my-sites/checkout/composite-checkout/record-analytics.js
Labels: [Status] Needs Review

#58811 Woop installer: restore autotransferring handling
  client/signup/steps/woocommerce-install/confirm/index.tsx
  client/signup/steps/woocommerce-install/transfer/index.tsx
Labels: [Type] Enhancement, [Status] Needs Review, [Size] S, Woop

#58826 Woop installer: remove 'on us' from domain warning
  client/components/eligibility-warnings/domain-warning/index.tsx
Labels: [Status] Needs Review, i18n, [Size] S, Woop

#58821 Add getSignupCompareAvailableFeatures to getAllFeaturesForPlan
  packages/calypso-products/src/main.ts
Labels: [Status] Needs Review

#58733 Remove setup-site-after-checkout and hero-flow feature flags
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Type] Janitorial, Blogger Experience Pod

#58847 chore: Replace rimraf with actual rm -fr command
  apps/editing-toolkit/package.json
  apps/notifications/package.json
  apps/o2-blocks/package.json
  apps/wpcom-block-editor/package.json
  package.json
  packages/accessible-focus/package.json
  packages/browser-data-collector/package.json
  packages/calypso-analytics/package.json
  packages/calypso-color-schemes/package.json
  packages/calypso-config/package.json
  packages/calypso-e2e/package.json
  packages/calypso-products/package.json
  packages/calypso-stripe/package.json
  packages/calypso-url/package.json
  packages/components/package.json
  packages/composite-checkout/package.json
  packages/create-calypso-config/package.json
  packages/data-stores/package.json
  packages/design-picker/package.json
  packages/domain-picker/package.json
  packages/explat-client-react-helpers/package.json
  packages/explat-client/package.json
  packages/format-currency/package.json
  packages/i18n-calypso/package.json
  packages/i18n-utils/package.json
  packages/interpolate-components/package.json
  packages/js-utils/package.json
  packages/language-picker/package.json
  packages/languages/package.json
  packages/launch/package.json
  packages/load-script/package.json
  packages/mocha-debug-reporter/package.json
  packages/onboarding/package.json
  packages/page-pattern-modal/package.json
  packages/photon/package.json
  packages/plans-grid/package.json
  packages/popup-monitor/package.json
  packages/request-external-access/package.json
  packages/search/package.json
  packages/shopping-cart/package.json
  packages/social-previews/package.json
  packages/state-utils/package.json
  packages/tour-kit/package.json
  packages/viewport-react/package.json
  packages/viewport/package.json
  packages/whats-new/package.json
  packages/wp-babel-makepot/package.json
  packages/wpcom-checkout/package.json
  packages/wpcom-proxy-request/package.json
  packages/wpcom-xhr-request/package.json
  packages/wpcom.js/package.json
Labels: [Status] Needs Review

#58753 `QueryKeyringServices`: Migrate away from `UNSAFE_` methods
  client/components/data/query-keyring-services/index.jsx
Labels: [Type] Enhancement, Framework, Sharing, [Status] Needs Review, Data

#58757 `QueryPlans`: Migrate away from `UNSAFE_` methods
  client/components/data/query-plans/index.jsx
Labels: [Type] Enhancement, Framework, Plans, [Status] Needs Review, Data

#58764 Site Settings: Migrate `JetpackSyncPanel` away from `UNSAFE_` methods
  client/my-sites/site-settings/jetpack-sync-panel/index.jsx
Labels: [Type] Enhancement, Site Settings, Framework, Jetpack, [Status] Needs Review

#58760 Components: Remove unused Facebook button and icon
  client/components/social-buttons/facebook.js
  client/components/social-icons/facebook.jsx
Labels: Framework, [Status] Needs Review, Components, [Type] Janitorial

#58807 i18n: Localize the support docs link on the Start Over page
  client/my-sites/site-settings/start-over.jsx
Labels: [Status] Needs Review

#58519 Fix "All domains list" header style (WIP)
  client/my-sites/domains/domain-management/components/breadcrumbs/index.jsx
  client/my-sites/domains/domain-management/components/breadcrumbs/style.scss
Labels: [Status] Needs Review, Domains

#58488 Fix "Claim your free domain" banner style
  client/my-sites/domains/domain-management/list/style.scss
Labels: [Status] Needs Review, Domains

#58493 Add/guard installation flow
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
  client/my-sites/marketplace/pages/marketplace-plugin-setup-status/style.scss
  client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx
  client/my-sites/marketplace/pages/marketplace-plugin-upload-status/style.scss
  client/my-sites/marketplace/pages/marketplace-plugin-upload-status/types.ts
  client/my-sites/plugins/plugin-details.jsx
  client/my-sites/plugins/plugin-upload/index.jsx
  client/state/marketplace/purchase-flow/reducer.ts
  client/state/marketplace/purchase-flow/schema.js
Labels: [Status] Needs Review

#58850 Plugins: Migrate `SinglePlugin` away from `UNSAFE_` methods
  client/my-sites/plugins/plugin.jsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Plugins

#58815 PrecancellationChatButton: show only when enabled in server config
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/precancellation-chat-button/index.jsx
  client/me/purchases/remove-purchase/index.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Happychat

#58838 Section loading indicator: fix centering and scrolling
  client/layout/loader.scss
Labels: [Type] Bug, [Status] Needs Review

#58632 Add/new email comparison card props
  client/components/promo-section/promo-card/index.tsx
  client/components/promo-section/promo-card/price.tsx
  client/my-sites/email/controller.js
  client/my-sites/email/email-providers-stacked-comparison/email-provider-stacked-card/email-provider-stacked-features.tsx
  client/my-sites/email/email-providers-stacked-comparison/email-provider-stacked-card/index.tsx
  client/my-sites/email/email-providers-stacked-comparison/email-provider-stacked-card/style.scss
  client/my-sites/email/email-providers-stacked-comparison/index.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/professional-email-card.scss
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/professional-email-card.tsx
  client/my-sites/email/email-providers-stacked-comparison/style.scss
Labels: [Status] Needs Review

#58650 WPCOM: Migrate `wpcom.undocumented()` reader post to `wpcom.req`
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/state/reader/posts/actions.js
  client/state/reader/posts/test/actions.js
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Reader, State

#58578 WPCOM: Migrate `wpcom.undocumented()` reader import to `wpcom.req`
  client/blocks/reader-import-button/index.jsx
  client/lib/wpcom-undocumented/lib/undocumented.js
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Reader

#58653 Update domains contact info page
  client/components/domains/layout/style.scss
  client/components/domains/layout/two-columns-layout.tsx
  client/components/domains/layout/types.ts
  client/my-sites/domains/domain-management/components/domain/non-owner-card.jsx
  client/my-sites/domains/domain-management/edit-contact-info-page/index.tsx
  client/my-sites/domains/domain-management/edit-contact-info-page/style.scss
  client/my-sites/domains/domain-management/edit-contact-info-page/types.tsx
Labels: [Status] Needs Review, Domains

#58816 Update premium theme selectors and restore isPremiumThemeAvailable tests
  client/state/themes/selectors/is-premium-theme-available.js
  client/state/themes/test/selectors.js
Labels: [Status] Needs Review

#58864 Domains: Fix domain-only flow adding `siteUrl` missing dependency
  client/signup/config/steps-pure.js
Labels: [Status] Needs Review, Domains

#58400 Add/new email provider comparison component
  client/components/promo-section/promo-card/price.tsx
  client/lib/titan/new-mailbox.js
  client/my-sites/email/email-providers-stacked-comparison/email-provider-stacked-card/index.tsx
  client/my-sites/email/email-providers-stacked-comparison/email-provider-stacked-card/style.scss
  client/my-sites/email/email-providers-stacked-comparison/index.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/professional-email-card.scss
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/professional-email-card.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/provider-card-props.ts
  client/my-sites/email/titan-new-mailbox-list/index.jsx
  client/my-sites/email/titan-new-mailbox/index.jsx
  client/my-sites/scan/types.tsx
Labels: [Status] Needs Review

#58604 media: migrate `updateMedia` to use React Query
  client/data/media/use-update-media-mutation.js
  client/data/media/with-update-media.js
  client/post-editor/media-modal/detail/detail-fields.jsx
  client/post-editor/media-modal/gallery/caption.jsx
  client/state/action-types.ts
  client/state/data-layer/wpcom/sites/media/index.js
  client/state/media/actions.js
  client/state/media/thunks/index.js
  client/state/media/thunks/update-media.js
Labels: [Status] Needs Review, Media, Data

#58827 Checkout: Record transaction begin analytics directly in webPayProcessor
  client/my-sites/checkout/composite-checkout/lib/web-pay-processor.ts
  client/my-sites/checkout/composite-checkout/record-analytics.js
  packages/wpcom-checkout/src/types.ts
Labels: [Status] Ready to Merge, Checkout

#58673 Add/new email comparison card props for google workspace
  client/components/gsuite/gsuite-new-user-list/index.tsx
  client/components/promo-section/promo-card/index.tsx
  client/my-sites/email/email-providers-stacked-comparison/index.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/google-workspace-card.scss
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/google-workspace-card.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/professional-email-card.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/provider-card-props.ts
  client/my-sites/email/email-providers-stacked-comparison/style.scss
Labels: [Status] Needs Review

#58840 Remove `test` from Stripe dashboard link in Earn > Payments
  client/my-sites/earn/memberships/index.jsx
Labels: [Type] Bug, [Pri] Low, [Status] Ready to Merge, Earn

#58752 E2E: Use smaller test images
  test/e2e/image-uploads/image1.jpg
  test/e2e/image-uploads/image2.jpg
  test/e2e/image-uploads/test-audio-01.mp3
  test/e2e/image-uploads/test-image-01.png
  test/e2e/image-uploads/test-image-02.png
  test/e2e/image-uploads/test-image-03.png
  test/e2e/image-uploads/test-unsupported-file-01.mkv
  test/e2e/image-uploads/unsupported_extension.mkv
  test/e2e/lib/media-helper.js
  test/e2e/specs/constants.js
  test/e2e/specs/specs-playwright/wp-media__upload-spec.ts
Labels: [Status] Needs Review

#58749 Add premium theme ref to My Plan page
  client/blocks/product-purchase-features-list/find-new-theme.jsx
  client/blocks/product-purchase-features-list/index.jsx
Labels: [Status] Needs Review

#58300 My Plan: Enable storage upgrades for Backup and Security
  client/me/purchases/manage-purchase/index.jsx
  client/me/purchases/manage-purchase/purchase-meta.jsx
  client/me/purchases/manage-purchase/style.scss
  client/me/purchases/remove-purchase/style.scss
  client/my-sites/purchases/main.tsx
  packages/calypso-products/src/constants/jetpack.ts
Labels: [Type] Enhancement, Plans, [Status] Needs Review, [Status] Needs Design Review, [Size] S, [Status] Design Input Requested

#58788 Add premium theme ref to checkout thank you page
  client/my-sites/checkout/checkout-thank-you/premium-plan-details.jsx
Labels: [Status] Needs Review

#58200 Purchases: Add notice that purchases may use backup if available
  client/lib/purchases/types.ts
  client/me/pending-payments/test/index.js
  client/me/purchases/manage-purchase/index.jsx
  client/me/purchases/manage-purchase/payment-info-block.tsx
  client/me/purchases/manage-purchase/purchase-meta.jsx
  client/me/purchases/manage-purchase/style.scss
  client/me/purchases/manage-purchase/test/payment-info-block.js
  client/me/purchases/purchase-item/index.jsx
  client/me/purchases/purchases-list/index.jsx
  client/me/purchases/purchases-site/index.jsx
  client/me/purchases/purchases-site/index.tsx
  client/me/purchases/style.scss
  client/my-sites/purchases/subscriptions/index.tsx
  client/my-sites/purchases/subscriptions/subscriptions-content.tsx
  client/state/stored-cards/selectors.js
Labels: [Status] Needs Review, Purchases

#58832 Checkout: Record existing card analytics events directly
  client/my-sites/checkout/composite-checkout/lib/analytics.ts
  client/my-sites/checkout/composite-checkout/lib/existing-card-processor.ts
  client/my-sites/checkout/composite-checkout/lib/is-payment-method-enabled.ts
  client/my-sites/checkout/composite-checkout/lib/translate-payment-method-names.ts
  client/my-sites/checkout/composite-checkout/record-analytics.js
  packages/wpcom-checkout/src/payment-methods/existing-credit-card.tsx
  packages/wpcom-checkout/src/types.ts
Labels: [Status] Needs Review, [Status] Ready to Merge, Checkout

#58823 Videos UI: Get completions from the courses endpoint.
  client/components/videos-ui/index.jsx
Labels: Blogger Experience Pod

#58797 CI: Use Playwright 1.17
  desktop/package.json
  packages/calypso-e2e/package.json
  packages/calypso-e2e/src/browser-manager.ts
  packages/calypso-e2e/src/hooks.ts
  test/e2e/package.json
  yarn.lock
Labels: [Status] In Progress, [Status] Needs Review

#56665 Payment Methods: Add toggle for backup payment methods
  client/components/inline-support-link/context-links.js
  client/components/section-header/style.scss
  client/me/purchases/payment-methods/payment-method-backup-toggle.tsx
  client/me/purchases/payment-methods/payment-method-delete.tsx
  client/me/purchases/payment-methods/payment-method-list.jsx
  client/me/purchases/payment-methods/style.scss
  client/state/action-types.ts
  client/state/stored-cards/actions.js
  client/state/stored-cards/reducer.js
  client/state/stored-cards/test/reducer.js
Labels: [Status] Ready to Merge, Payment Methods

#58833 E2E: update steps for Support:Popover spec.
  test/e2e/specs/specs-playwright/wp-support__popover-valid.ts
Labels: [Status] Needs Review

#58615 Domains: "Add/update DNS record" page design fixes
  client/my-sites/domains/domain-management/dns/add-dns-record.scss
  client/my-sites/domains/domain-management/dns/dns-add-new.jsx
Labels: [Status] Needs Review, Domains

#58878 Revert "CI: Use Playwright 1.17"
  desktop/package.json
  packages/calypso-e2e/package.json
  packages/calypso-e2e/src/browser-manager.ts
  packages/calypso-e2e/src/hooks.ts
  test/e2e/package.json
  yarn.lock
Labels: [Status] Needs Review

#58601 Domains: Update breadcrumbs styling to reflect latest Figma designs
  client/my-sites/domains/domain-management/components/breadcrumbs/index.jsx
  client/my-sites/domains/domain-management/components/breadcrumbs/style.scss
Labels: [Status] Needs Review, Domains

#58881 G Suite: Fix TypeScript types for getItemsForCart
  client/lib/gsuite/get-gsuite-subscription-status.js
  client/lib/gsuite/has-gsuite-with-us.js
  client/lib/gsuite/new-users.ts
Labels: [Status] Needs Review

#58871 Remove unused puppeteer dependency
  apps/editing-toolkit/package.json
  yarn.lock
Labels: [Status] Needs Review

#58872 Enable the Hero Flow for non-en users in the wpcalypso environment
  client/signup/config/flows.js
  config/development.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Blogger Experience Pod

#58305 Domain: Create new domain settings page stub
  client/my-sites/domains/domain-management/controller.jsx
  client/my-sites/domains/domain-management/index.jsx
  client/my-sites/domains/domain-management/settings/index.tsx
Labels: [Status] Needs Review, Domains

#58482 build: Use focused workspaces
  .github/workflows/editing-toolkit-plugin.yml
  .teamcity/_self/PluginBaseBuild.kt
  apps/editing-toolkit/package.json
  apps/wpcom-block-editor/src/wpcom/features/use-classic-block-guide.js
  packages/calypso-config/package.json
  yarn.lock
Labels: [Status] Needs Review

#58460 Refactor TeamCity templates
  .teamcity/_self/PluginBaseBuild.kt
  .teamcity/_self/lib/wpcom/WPComPluginBuild.kt
  .teamcity/_self/projects/WPComPlugins.kt
Labels: [Status] Needs Review

#58862 WPCOM: migrate wpcom.undocumented().wordAdsApprove() to wpcom.req
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/state/wordads/approve/actions.js
Labels: [Status] Needs Review, WordAds

#58853 Me: Cleanup unused `MembershipsHistory` and related styles
  client/me/memberships/main.jsx
  client/me/memberships/style.scss
Labels: [Status] Needs Review, Me, [Type] Janitorial, Memberships

#58860 Analytics: Migrate `TrackComponentView` away from `UNSAFE_` methods
  client/lib/analytics/track-component-view/index.jsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Analytics

#58573 media: migrate `deleteMedia` to use React Query
  client/data/media/use-delete-media-mutation.js
  client/data/media/with-delete-media.js
  client/my-sites/media/main.jsx
  client/post-editor/media-modal/index.jsx
  client/post-editor/media-modal/test/index.jsx
  client/state/action-types.ts
  client/state/data-layer/wpcom/sites/media/index.js
  client/state/media/actions.js
  client/state/media/thunks/delete-media.js
  client/state/media/thunks/index.js
Labels: [Status] Needs Review, Media, Data

#58896 Migrate wpcom.undocumented().oauth2ClientId() to wpcom.req
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/state/oauth2-clients/actions.js
Labels: [Status] Needs Review, Login

#58769 Switch to `lodash-es` on the Notifications app
  .gitignore
  apps/notifications/package.json
  apps/notifications/webpack.config.js
  yarn.lock
Labels: [Type] Enhancement, [Status] Needs Review, Notifications, Performance

#58746 Add/new email comparison card workspace wire
  client/my-sites/email/email-providers-stacked-comparison/index.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/google-workspace-card.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/provider-card-props.ts
Labels: [Status] Needs Review

#58863 Videos UI: use `duration_seconds`
  client/components/videos-ui/index.jsx
Labels: Blogger Experience Pod

#58861 FSE Beta: increase opt-in percentage to 20%
  client/landing/gutenboarding/hooks/use-fse-beta-eligibility.ts
Labels: [Status] Needs Review, [Goal] Full Site Editing

#58178 Plans, Activity Log: Remove activity-log/display-rules and jetpack/only-realtime-products flags
  client/components/activity-card-list/index.jsx
  client/components/jetpack/card/jetpack-product-card/display-price/index.tsx
  client/components/jetpack/card/jetpack-product-card/display-price/style.scss
  client/components/jetpack/card/product-without-price/default.tsx
  client/components/jetpack/card/product-without-price/index.tsx
  client/components/jetpack/card/product-without-price/only-realtime-products.tsx
  client/components/jetpack/card/product-without-price/style.scss
  client/components/jetpack/daily-backup-status/index.jsx
  client/my-sites/activity/activity-log/index.jsx
  client/my-sites/backup/backup-upsell/index.tsx
  client/my-sites/backup/hooks.js
  client/my-sites/backup/main.jsx
  client/my-sites/backup/wpcom-backup-upsell.tsx
  client/my-sites/plans/current-plan/purchases-listing.jsx
  client/my-sites/plans/jetpack-plans/constants.ts
  client/my-sites/plans/jetpack-plans/iterations.ts
  client/my-sites/plans/jetpack-plans/jetpack-crm-free-card/index.tsx
  client/my-sites/plans/jetpack-plans/jetpack-crm-free-card/style.scss
  client/my-sites/plans/jetpack-plans/jetpack-crm-free-card/with-price.tsx
  client/my-sites/plans/jetpack-plans/jetpack-crm-free-card/without-price.tsx
  client/my-sites/plans/jetpack-plans/jetpack-free-card/index.tsx
  client/my-sites/plans/jetpack-plans/jetpack-free-card/with-price.tsx
  client/my-sites/plans/jetpack-plans/jetpack-free-card/without-price.tsx
  client/my-sites/plans/jetpack-plans/jetpack-storage-plans.ts
  client/my-sites/plans/jetpack-plans/product-grid/index.tsx
  client/my-sites/plans/jetpack-plans/product-grid/products-order.ts
  client/my-sites/plans/jetpack-plans/product-grid/style.scss
  client/my-sites/plans/jetpack-plans/product-grid/utils.ts
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
  client/my-sites/scan/wpcom-scan-upsell.tsx
  config/development.json
  config/horizon.json
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/test/plan-lookups.js
Labels: Plans, [Status] Needs Review, [Type] Janitorial, [Size] L, Activity Log, Jetpack Cloud, Jetpack Backup

#58903 Move wpcom.undocumented().getAtomicSiteMediaViaProxy to a separate module
  client/blocks/image-editor/image-editor-canvas.jsx
  client/lib/get-atomic-site-media/index.js
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/my-sites/media-library/proxied-image.tsx
Labels: [Status] Needs Review

#58851 Onboarding: update `start building` link
  client/signup/steps/import/ready/index.tsx
  test/e2e/specs/specs-playwright/wp-start__importer.ts
Labels: [Status] Needs Review

#58813 Enable Jetpack User-Licensing feature flag in production.
  config/production.json
Labels: Jetpack, [Status] Needs Review, Jetpack Licensing

#58794 Videos UI: Count video play clicks from in the video player controls.
  client/components/videos-ui/video-player.jsx
Labels: [Status] Needs Review, Blogger Experience Pod

#58887 Add script for yarnrc maintinence
  bin/update-yarnrc.sh
Labels: [Type] Enhancement, [Status] Needs Review

#58913 Payment Methods: Do not display backup checkbox for non-cards
  client/lib/checkout/payment-methods.ts
  client/me/purchases/payment-methods/payment-method-details.tsx
  client/me/purchases/payment-methods/payment-method-list.tsx
  client/me/purchases/payment-methods/payment-method.tsx
  client/my-sites/checkout/composite-checkout/types/stored-cards.ts
Labels: [Status] Needs Review

#58824 Plugin Details: Split the page structure into smaller components
  client/my-sites/plugins/_variables.scss
  client/my-sites/plugins/plugin-details-CTA/index.jsx
  client/my-sites/plugins/plugin-details-CTA/style.scss
  client/my-sites/plugins/plugin-details-header/index.jsx
  client/my-sites/plugins/plugin-details-header/style.scss
  client/my-sites/plugins/plugin-details-sidebar/index.jsx
  client/my-sites/plugins/plugin-details-sidebar/style.scss
  client/my-sites/plugins/plugin-details.jsx
  client/my-sites/plugins/style.scss
Labels: [Status] Needs Review, Marketplace

#58718 Playwright: Use selector instead to locate the `close tour` button.
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
Labels: [Pri] High, [Status] Needs Review

#58912 Emails: Price badge improvements in styling and use
  client/my-sites/email/email-providers-stacked-comparison/email-provider-stacked-card/index.tsx
  client/my-sites/email/email-providers-stacked-comparison/email-provider-stacked-card/style.scss
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/google-workspace-card.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/professional-email-card.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/provider-card-props.ts
Labels: [Status] Needs Review

#58885 Checkout: Record stripe and ebanx transaction start analytics directly
  client/my-sites/checkout/composite-checkout/lib/analytics.ts
  client/my-sites/checkout/composite-checkout/lib/multi-partner-card-processor.ts
  client/my-sites/checkout/composite-checkout/lib/translate-payment-method-names.ts
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-pay-button.js
  client/my-sites/checkout/composite-checkout/record-analytics.js
  packages/wpcom-checkout/src/types.ts
Labels: [Status] Ready to Merge

#58692 Domains: Fix DNS pages header design issues
  client/my-sites/domains/domain-management/components/breadcrumbs/style.scss
  client/my-sites/domains/domain-management/dns/dns-add-new-record-button.tsx
  client/my-sites/domains/domain-management/dns/dns-records-list-item.jsx
  client/my-sites/domains/domain-management/dns/dns-records.jsx
  client/my-sites/domains/domain-management/dns/style.scss
  client/my-sites/domains/domain-management/dns/types.tsx
Labels: [Status] Needs Review, Domains

#58610 Playwright: update e2e documentation.
  test/e2e/.eslintrc.js
  test/e2e/README.md
  test/e2e/docs/config_values.md
  test/e2e/docs/debugging.md
  test/e2e/docs/environment_variables.md
  test/e2e/docs/library_objects.md
  test/e2e/docs/miscellaneous.md
  test/e2e/docs/overview.md
  test/e2e/docs/resources/free-flat-design-linear-vector-icon-set.jpg
  test/e2e/docs/resources/playwright_debug_iframe.gif
  test/e2e/docs/resources/playwright_debug_inspector.png
  test/e2e/docs/resources/saved_auth_cookies.gif
  test/e2e/docs/resources/teamcity_branch_view.png
  test/e2e/docs/resources/teamcity_build_manually_trigger.png
  test/e2e/docs/running-tests.md
  test/e2e/docs/setup.md
  test/e2e/docs/style-guide-playwright.md
  test/e2e/docs/style-guide-selenium.md
  test/e2e/docs/style_guide.md
  test/e2e/docs/test_environment.md
  test/e2e/docs/tests_ci.md
  test/e2e/docs/tests_local.md
  test/e2e/docs/troubleshooting.md
  test/e2e/docs/writing_tests.md
Labels: [Status] Needs Review

#58926 Dispatch action to recognize plugin click on installation flow.
  client/my-sites/plugins/plugin-details-CTA/index.jsx
Labels: [Status] Ready to Merge, Marketplace

#58889 chore: Drop jest-junit
  .teamcity/_self/projects/WebApp.kt
  package.json
  yarn.lock
Labels: [Status] Needs Review

#58899 ci: Fail build on tsc errors
  .teamcity/_self/projects/WebApp.kt
Labels: [Status] Needs Review

#58934 Reader: check that post.tags exists before using it in x-post helper
  client/reader/xpost-helper.js
Labels: [Status] Needs Review, Reader

#58908 Signup: Cleanup unused tabbed plans
  client/signup/steps/plans/tabbed-plans-style.scss
  client/signup/steps/plans/tabbed-plans.js
Labels: Plans, [Status] Needs Review, Signup, [Type] Janitorial

#58901 WPCOM: Migrate `wpcom.undocumented()` settings to `wpcom.req`
  client/lib/signup/step-actions/index.js
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/state/site-settings/actions.js
Labels: [Type] Enhancement, Site Settings, Framework, [Status] Needs Review, State

#58905 Extract jest config from calypso-build to calypso-jest
  package.json
  packages/calypso-build/CHANGELOG.md
  packages/calypso-build/README.md
  packages/calypso-build/jest-preset.js
  packages/calypso-build/package.json
  packages/calypso-jest/.eslintrc.js
  packages/calypso-jest/CHANGELOG.md
  packages/calypso-jest/README.md
  packages/calypso-jest/jest-preset.js
  packages/calypso-jest/package.json
  packages/calypso-jest/src/module-resolver.js
  packages/calypso-jest/src/setup.js
  packages/calypso-jest/src/transform/README.md
  packages/calypso-jest/src/transform/asset.js
  packages/calypso-jest/src/transform/babel.js
  packages/calypso-jest/tsconfig.json
  packages/design-picker/package.json
  packages/languages/jest.config.js
  test/client/jest.config.js
  test/integration/jest.config.js
  test/packages/jest-preset.js
  test/server/jest.config.js
  yarn.lock
Labels: [Status] Needs Review

#58894 Add breadcrumbs to domain settings page
  client/my-sites/domains/domain-management/settings/index.tsx
  client/my-sites/domains/domain-management/settings/types.tsx
Labels: [Status] Needs Review, Domains

#56347 Editor Welcome: Add instructional graphics for mobile UI
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/hooks/index.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/hooks/use-prefetch-tour-assets.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/style-tour.scss
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-steps.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/types.ts
  packages/viewport-react/package.json
  packages/viewport-react/types.d.ts
  packages/viewport/src/index.js
Labels: Editor, [Status] Needs Review, Mobile Web, Editor Welcome, Welcome Tour

#58902 WPCOM: Migrate `wpcom.undocumented()` get domain price to `wpcom.req`
  client/components/domains/register-domain-step/index.jsx
  client/lib/wpcom-undocumented/lib/undocumented.js
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Domains

#58897 WPCOM: Migrate `wpcom.undocumented()` theme transfer status to `wpcom.req`
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/state/themes/actions/theme-transfer.js
Labels: [Type] Enhancement, Themes, Framework, [Status] Needs Review, State, Atomic Upgrade Flows
