Repository Automattic/wp-calypso, pull requests merged in 2021-07, with the labels that each got.

#53207 My Home: simplify My Home data layer by migrating to React Query
  client/components/data/query-home-layout/index.js
  client/data/home/use-home-layout-query-params.ts
  client/data/home/use-home-layout-query.ts
  client/data/home/use-skip-current-view-mutation.ts
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
  client/my-sites/customer-home/cards/actions/wp-for-teams-quick-links/index.jsx
  client/my-sites/customer-home/cards/notices/celebrate-notice/index.jsx
  client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
  client/my-sites/customer-home/cards/tasks/task.jsx
  client/my-sites/customer-home/controller.jsx
  client/my-sites/customer-home/locations/secondary/learn-grow/index.jsx
  client/my-sites/customer-home/locations/tertiary/manage-site/index.jsx
  client/my-sites/customer-home/main.jsx
  client/state/action-types.ts
  client/state/data-layer/wpcom/sites/home/layout/index.js
  client/state/home/actions.js
  client/state/home/init.js
  client/state/home/package.json
  client/state/home/reducer.js
  client/state/preferences/constants.js
  client/state/preferences/schema.js
  client/state/selectors/get-home-layout.js
  client/state/selectors/is-home-quick-links-expanded.js
Labels: Framework, My Home Pod, [Status] In Progress, [Status] Needs Review

#53748 Complete free plugin and purchased plugin installation flow when custom domain is set to a site
  client/my-sites/checkout/checkout-thank-you/index.jsx
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
  client/my-sites/plugins/marketplace/components/simulated-progressbar/index.tsx
  client/my-sites/plugins/marketplace/constants.ts
  client/my-sites/plugins/marketplace/marketplace-plugin-details/index.tsx
  client/my-sites/plugins/marketplace/marketplace-plugin-setup-status/index.tsx
  client/my-sites/plugins/marketplace/marketplace-test/admin-menu-fetch.tsx
  client/my-sites/plugins/marketplace/marketplace-test/index.tsx
  client/my-sites/plugins/marketplace/util.ts
  client/state/action-types.ts
  client/state/automated-transfer/actions.js
  client/state/automated-transfer/constants.ts
  client/state/automated-transfer/reducer.js
  client/state/data-layer/wpcom/sites/automated-transfer/status/index.js
  client/state/plugins/installed/status/constants.ts
  client/state/plugins/installed/status/reducer.js
  client/state/plugins/marketplace/actions.ts
  client/state/plugins/marketplace/reducer.ts
  client/state/plugins/marketplace/selectors.ts
  client/state/plugins/marketplace/test/marketplace-state.ts
  client/state/plugins/marketplace/types.ts
  packages/calypso-products/src/is-marketplace-product.ts
Labels: [Status] Needs Review

#54059 Apply new short term designs to my home page
  client/my-sites/customer-home/cards/actions/quick-links/style.scss
  client/my-sites/customer-home/cards/features/go-mobile/index.jsx
  client/my-sites/customer-home/cards/features/go-mobile/style.scss
  client/my-sites/customer-home/cards/features/help-search/index.jsx
  client/my-sites/customer-home/cards/features/help-search/style.scss
  client/my-sites/customer-home/cards/features/quick-start/index.js
  client/my-sites/customer-home/cards/features/stats/index.jsx
  client/my-sites/customer-home/cards/features/stats/style.scss
  client/my-sites/customer-home/cards/tasks/site-setup-list/style.scss
  client/my-sites/customer-home/cards/tasks/style.scss
  client/my-sites/customer-home/locations/secondary/learn-grow/index.jsx
  client/my-sites/customer-home/locations/secondary/learn-grow/style.scss
  client/my-sites/customer-home/style.scss
Labels: My Home Pod, [Status] Needs Review

#54186 Show domain/email dates in the customer time zone
  client/lib/domains/resolve-domain-status.js
  client/my-sites/domains/domain-management/edit/card/notices/expiring-soon.jsx
  client/my-sites/domains/domain-management/edit/domain-types/helpers.jsx
  client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
  client/my-sites/email/email-management/home/email-plan-subscription.jsx
Labels: [Status] Needs Review

#54178 Fixed chat window overflow on mobile device
  client/components/happychat/composer.scss
Labels: [Status] Needs Review

#54205 Connections: Fix keyring user label when no ID
  client/my-sites/marketing/connections/connection.jsx
Labels: Sharing, [Status] Needs Review, [Type] Bug

#53988 Hide menubar on theme pages
  client/layout/style.scss
  client/my-sites/sidebar-unified/style.scss
Labels: [Status] Needs Review

#54213 Add feature flag: theme/showcase-revamp
  client/my-sites/themes/themes-magic-search-card/index.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Pod] Design Selection, [Status] Needs Review

#54211 config/README.md: Remove reference to non-existent json files
  config/README.md
Labels: [Pod] Design Selection, [Status] Needs Review

#54193 desktop(ci): fix mac notarization step
  .circleci/config.yml
  desktop/bin/after_sign_hook.js
  desktop/package.json
Labels: [Status] Needs Review

#54215 Themes Magic Search Card: Only allow 'feature', 'columns', 'subject' filters (Redux)
  client/my-sites/themes/themes-magic-search-card/index.jsx
Labels: [Pod] Design Selection, [Status] Needs Review

#54140 Theme Showcase: Use UpsellNudge component for Upwork banner
  client/blocks/upwork-banner/index.jsx
  client/blocks/upwork-banner/style.scss
  client/blocks/upwork-banner/test/__snapshots__/index.js.snap
  client/blocks/upwork-banner/test/index.js
Labels: Theme Showcase, [Pod] Design Selection, [Status] Needs Review, [Status] String Freeze

#54218 Theme Showcase: Magic Search Welcome Bar: Add an advanced toggle (Redux)
  client/my-sites/themes/themes-magic-search-card/index.jsx
  client/my-sites/themes/themes-magic-search-card/style.scss
Labels: [Pod] Design Selection, [Status] Needs Review

#54008 My Home: Padding and hover style updates in the stats card
  client/my-sites/customer-home/cards/features/stats/index.jsx
  client/my-sites/customer-home/cards/features/stats/style.scss
  client/my-sites/customer-home/cards/tasks/style.scss
Labels: [Status] Needs Review

#54234 Purchases: update reducer tests to Jest
  client/state/purchases/test/reducer.js
Labels: Purchases, [Status] Needs Review, [Type] Janitorial

#54233 add border radius to quicklinks when collapsed
  client/my-sites/customer-home/cards/actions/quick-links/style.scss
Labels: [Status] Needs Review

#54232 Fix whitespace (spaces to tabs)
  client/my-sites/customer-home/cards/features/go-mobile/style.scss
  client/my-sites/customer-home/cards/features/stats/style.scss
  client/my-sites/customer-home/style.scss
Labels: [Status] Needs Review, [Type] Janitorial

#54208 Janitorial: Remove unused component state
  apps/notifications/src/panel/templates/index.jsx
  apps/notifications/src/panel/templates/note-list.jsx
  client/blocks/post-share/index.jsx
  client/blocks/signup-form/index.jsx
  client/me/account/main.jsx
  client/me/purchases/cancel-purchase/button.jsx
  client/me/purchases/remove-purchase/index.jsx
  client/me/reauth-required/index.jsx
  client/my-sites/domains/domain-management/edit-contact-info/form-card.jsx
  client/my-sites/email/titan-add-mailboxes/index.jsx
  client/my-sites/email/titan-redirector/index.jsx
  client/my-sites/invites/invite-accept/index.jsx
  client/my-sites/migrate/section-migrate.jsx
  client/my-sites/scan/main.tsx
  client/my-sites/site-settings/seo-settings/form.jsx
  client/my-sites/themes/thanks-modal.jsx
  client/my-sites/themes/theme-showcase.jsx
  client/signup/steps/plans/index.jsx
  client/signup/steps/user/index.jsx
Labels: Framework, [Status] Needs Review, [Type] Janitorial

#54236 Add notice on wordads setting if site is private
  client/my-sites/earn/ads/wrapper.jsx
Labels: [Status] Needs Review

#54159 Invites: Update user email verified setting to Redux
  client/lib/user/user.d.ts
  client/lib/user/user.js
  client/my-sites/invites/controller.js
  client/state/action-types.ts
  client/state/current-user/actions.js
  client/state/current-user/reducer.js
Labels: People Management, State, [Status] Needs Review, [Type] Enhancement

#54237 New Onboarding: remove Reynolds design
  packages/design-picker/src/available-designs-config.json
Labels: Design Picker, [Goal] New Onboarding, [Status] Needs Review

#53227 Calypso Config: Disable gutenboarding/alpha-templates feature flag
  config/development.json
  config/wpcalypso.json
Labels: [Goal] New Onboarding, [Status] Needs Review

#54238 Reader: Remove redux bridge use from `ReaderLikeButton`
  client/reader/like-button/index.jsx
Labels: Framework, Reader, [Status] Needs Review, [Type] Enhancement

#53811 Customer Home: Adjust the eligibility checks to add email to include Professional Email
  client/lib/domains/can-current-user-add-email.js
  client/lib/emails/has-paid-email-with-us.js
  client/lib/emails/index.js
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
  client/my-sites/customer-home/cards/actions/wp-for-teams-quick-links/index.jsx
Labels: Customer Home, [Status] Needs Review

#54203 Fixed the navigation not opening on mobile for the Calypso settings pages
  client/layout/masterbar/item.jsx
  client/layout/masterbar/logged-in.jsx
  client/my-sites/site-settings/index.js
  client/sections.js
  test/e2e/lib/components/nav-bar-component.js
  test/e2e/lib/components/sidebar-component.js
Labels: [Status] Needs Review

#54166 Earn: Fix Broken Support Document Link on "Related Fees"
  client/my-sites/earn/memberships/index.jsx
Labels: Earn, OSS Citizen, [Pri] Normal, [Size] XS, [Type] Bug

#54132 Don't show 'Create Site' option for domain-only site when unavailable
  client/lib/domains/can-current-user-create-site-from-domain-only.js
  client/lib/domains/index.js
  client/my-sites/domains/domain-management/list/domain-only.jsx
  client/state/sites/domains/assembler.js
  client/state/sites/domains/test/fixture/index.js
Labels: Domains, [Status] Needs Review

#53894 Jetpack Checkout without site for logged-in and logged-out users
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/lib/submit-wpcom-transaction.ts
  client/my-sites/checkout/composite-checkout/lib/translate-cart.ts
  client/my-sites/checkout/controller.jsx
  client/my-sites/checkout/index.js
Labels: Checkout, Jetpack, [Status] Needs Review

#54245 Happy Chat: Allow customers to receive message updates
  client/components/happychat/timeline.jsx
  client/components/happychat/timeline.scss
  client/lib/happychat/connection.js
  client/state/action-types.ts
  client/state/happychat/chat/reducer.js
  client/state/happychat/connection/actions.js
  client/state/happychat/selectors/get-happychat-timeline.js
  client/state/happychat/selectors/test/get-happychat-timeline.js
Labels: [Status] Needs Review

#54183 Domains: Notify user when they are cancelling a domain that is used as for WPCOM email contact
  client/me/purchases/remove-purchase/remove-domain-dialog/index.jsx
Labels: Domains, [Status] Needs Review

#54221 Disable security checklist menu flag
  config/development.json
  config/stage.json
  config/wpcalypso.json
Labels: Security, [Status] Needs Review

#54209 Add translation context to the Extensions label in domain search filter
  client/components/domains/search-filters/dropdown-filters.jsx
Labels: Domains, [Status] Needs Review, [Status] String Freeze, i18n

#54258 Reinstate upgrade option for email forwards
  client/my-sites/email/email-management/home/email-plan.jsx
Labels: Email management, [Status] Needs Review

#54047 Support removing mailboxes for Professional Email
  client/data/emails/use-emails-query.js
  client/data/emails/use-remove-titan-mailbox-mutation.js
  client/lib/emails/get-email-address.js
  client/lib/emails/index.js
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/my-sites/email/email-management/home/email-mailbox-action-menu.jsx
  client/my-sites/email/email-management/style.scss
Labels: Professional Email, [Status] Needs Review

#54071 isTitanEmail: Check product is defined
  client/my-sites/checkout/checkout-thank-you/header.jsx
Labels: Checkout, [Status] Needs Review

#54229 Gutenboarding: Use site ID instead of slug for fetching the cart in useOnSiteCreation
  client/landing/gutenboarding/hooks/use-on-site-creation.ts
Labels: Shopping Cart, Signup, [Estimate] 1, [Status] Needs Review, [Type] Bug

#54255 Site-only Jetpack Checkout: allow logged-in users coming from the Pricing page
  client/my-sites/checkout/controller.jsx
Labels: Checkout, Jetpack, [Size] XS, [Status] Needs Review

#54242 Add WP Admin Dashboard to Home Quick Links if Nav Unification is enabled
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
Labels: [Status] Needs Review

#54120 Signup: use standard line height for domain suggestions
  client/components/domains/domain-suggestion/style.scss
Labels: Signup, [Status] Needs Review

#54279 Boot: Pass user ID when retrieving initial state
  client/boot/common.js
Labels: Performance, State, [Pri] High, [Status] Needs Review

#54281 Code owners: add Ground control to monitor node version changes
  .github/CODEOWNERS
Labels: [Status] Needs Review, [Type] Tooling

#54277 chore(renovate): Add a group for @testing-library packages
  renovate.json
Labels: [Status] Needs Review

#54250 P2: Better error message when trying to delete a P2 hub with spaces
  client/state/sites/actions.js
Labels: [Status] Ready to Merge

#54283 Components: Remove unneded check in QuerySites
  client/components/data/query-sites/index.jsx
Labels: Components, Data, [Status] Needs Review, [Type] Janitorial

#54124 Signup: Domain step should show empty state when the query is emptied
  client/components/domains/register-domain-step/index.jsx
Labels: Domains, Signup, [Status] Needs Review

#53964 Playwright: add mobile support to pages used by `seo_preview` spec.
  packages/calypso-e2e/src/lib/pages/marketing-page.ts
Labels: [Status] Needs Review

#54261 Shopping Cart: Move CalypsoShoppingCartProvider to top of render tree
  client/blocks/editor-checkout-modal/index.tsx
  client/components/data/domain-management/index.jsx
  client/components/upgrades/gsuite/README.md
  client/controller/index.web.js
  client/my-sites/checkout/checkout-system-decider.js
  client/my-sites/checkout/controller.jsx
  client/my-sites/current-site/index.jsx
  client/my-sites/domains/controller.jsx
  client/my-sites/email/controller.js
  client/my-sites/plan-features/index.jsx
  client/my-sites/plans/navigation.jsx
  client/my-sites/plugins/marketplace/marketplace-domain-upsell/index.tsx
  client/my-sites/plugins/marketplace/marketplace-plugin-details/index.tsx
  client/signup/steps/domains/index.jsx
Labels: Framework, Shopping Cart, [Estimate] 1, [Status] Needs Review

#54297 Revert "Shopping Cart: Move CalypsoShoppingCartProvider to top of render tree"
  client/blocks/editor-checkout-modal/index.tsx
  client/components/data/domain-management/index.jsx
  client/components/upgrades/gsuite/README.md
  client/controller/index.web.js
  client/my-sites/checkout/checkout-system-decider.js
  client/my-sites/checkout/controller.jsx
  client/my-sites/current-site/index.jsx
  client/my-sites/domains/controller.jsx
  client/my-sites/email/controller.js
  client/my-sites/plan-features/index.jsx
  client/my-sites/plans/navigation.jsx
  client/my-sites/plugins/marketplace/marketplace-domain-upsell/index.tsx
  client/my-sites/plugins/marketplace/marketplace-plugin-details/index.tsx
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review

#54263 Domains: Update outdated domain mapping mentions
  client/components/domains/domain-search-results/index.jsx
  client/components/domains/transfer-domain-step/index.jsx
  client/my-sites/domains/domain-search/index.jsx
Labels: Domains, [Status] Needs Review

#53835 Playwright: make Gutenberg publish and visit post steps more reliable.
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
Labels: [Status] Needs Review

#54282 Janitorial: Remove more unused component state
  client/blocks/calendar-button/index.jsx
  client/blocks/get-apps/apps-badge.jsx
  client/blocks/keyring-connect-button/index.js
  client/blocks/reader-post-card/photo.jsx
  client/components/chart/bar.jsx
  client/components/section-nav/tabs.jsx
  client/extensions/woocommerce/app/store-stats/referrers/index.js
  client/extensions/woocommerce/components/action-header/actions.js
  client/jetpack-connect/main.jsx
  client/jetpack-connect/search.jsx
  client/me/connected-application-item/index.jsx
  client/me/purchases/billing-history/billing-history-filters.jsx
  client/me/security-2fa-backup-codes/index.jsx
  client/me/security-account-recovery/edit-phone.jsx
  client/my-sites/domains/domain-management/dns/index.jsx
  client/my-sites/importer/site-importer/site-importer-site-preview.jsx
  client/my-sites/purchase-product/search.jsx
  client/my-sites/purchases/site-level-purchases-error-boundary.tsx
  client/my-sites/site-settings/site-tools/index.jsx
  client/my-sites/stats/stats-date-picker/index.jsx
  client/reader/following-manage/index.jsx
  client/reader/search-stream/index.jsx
  client/reader/tag-stream/main.jsx
  packages/composite-checkout/src/components/checkout-error-boundary.tsx
Labels: Components, [Status] Needs Review, [Type] Janitorial

#54288 My Sites: Delete unused `jetpackModuleActive`
  client/my-sites/controller.js
Labels: Sites, [Status] Needs Review, [Type] Janitorial

#48003 Modularise support state
  client/lib/user/support-user-interop.js
  client/state/reducer.js
  client/state/support/actions.js
  client/state/support/constants.js
  client/state/support/init.js
  client/state/support/package.json
  client/state/support/reducer.js
  client/state/support/selectors.js
  client/state/support/test/reducer.js
Labels: State, [Status] Needs Review, [Type] Enhancement

#54122 User: Move verification polling to a component
  client/components/email-verification/index.js
  client/layout/index.jsx
  client/lib/user/user.d.ts
  client/lib/user/user.js
  client/lib/user/verification-checker.js
Labels: Framework, [Status] Needs Review

#54292 Remove font size redundant CSS for plans title
  client/signup/steps/plans/style.scss
Labels: [Status] Needs Review

#53416 Jetpack Partner Portal: Introduce list of credit cards in payment method list
  client/jetpack-cloud/sections/partner-portal/add-stored-credit-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/add-stored-credit-card/style.scss
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-list/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-list/style.scss
  client/jetpack-cloud/sections/partner-portal/stored-credit-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/stored-credit-card/style.scss
Labels: Jetpack Partner Portal, [Size] S, [Status] Needs Review, [Type] Task

#54259 Plans: Adapt Jetpack Free card so its code can be re-used
  client/components/jetpack/card/jetpack-free-card/button.tsx
  client/components/jetpack/card/jetpack-free-card/index.tsx
  client/components/jetpack/card/jetpack-free-card/test/button.jsx
  client/components/jetpack/card/product-without-price/index.tsx
  client/components/jetpack/card/product-without-price/style.scss
  client/my-sites/plans/jetpack-plans/jetpack-free-card/index.tsx
  client/my-sites/plans/jetpack-plans/jetpack-free-card/test/use-jetpack-free-button-props.js
  client/my-sites/plans/jetpack-plans/jetpack-free-card/use-jetpack-free-button-props.ts
  client/my-sites/plans/jetpack-plans/product-grid/index.tsx
  client/my-sites/plans/jetpack-plans/types.ts
Labels: Plans, [Size] XS, [Status] Needs Review, [Type] Janitorial

#54317 Try/cleanup templates and parts with data api
  test/e2e/specs/specs-wpcom/wp-calypso-gutenberg-site-editor-tracking-spec.js
Labels: [Status] Needs Review

#53724 Playwright: migrate `wp-media-edit-spec` with additional tests
  packages/calypso-e2e/src/element-helper.ts
  packages/calypso-e2e/src/index.ts
  packages/calypso-e2e/src/lib/pages/index.ts
  packages/calypso-e2e/src/lib/pages/media-page.ts
  test/e2e/specs/specs-playwright/wp-media__edit-spec.js
Labels: [Status] Needs Review

#54300 Shopping Cart: Use middleware to sync cart with server
  packages/shopping-cart/src/sync.ts
  packages/shopping-cart/src/types.ts
  packages/shopping-cart/src/use-cart-update-and-revalidate.ts
  packages/shopping-cart/src/use-shopping-cart-manager.ts
  packages/shopping-cart/src/use-shopping-cart-reducer.ts
  packages/shopping-cart/test/cart-actions.tsx
Labels: Shopping Cart, [Estimate] 3, [Status] Ready to Merge

#54323 ci(e2e): Fix types in mocha-debug-reporter
  .teamcity/_self/projects/WebApp.kt
  packages/mocha-debug-reporter/tsconfig.json
  packages/typography/tsconfig.json
  packages/webpack-config-flag-plugin/tsconfig.json
  packages/webpack-extensive-lodash-replacement-plugin/tsconfig.json
  packages/webpack-inline-constant-exports-plugin/tsconfig.json
  packages/webpack-rtl-plugin/tsconfig.json
  packages/wp-babel-makepot/tsconfig.json
Labels: [Status] Needs Review

#54324 Remove 'await act' from useShoppingCart tests
  packages/shopping-cart/test/cart-actions.tsx
Labels: Shopping Cart, [Estimate] 1, [Status] Needs Review

#54195 Skip the tracking test for 'wpcom_block_editor_close_click' in mobile due to missing elements on the page
  test/e2e/lib/components/site-editor-component.js
  test/e2e/lib/gutenberg/tracking/general-tests.js
  test/e2e/specs/specs-wpcom/wp-calypso-gutenberg-site-editor-tracking-spec.js
Labels: [Status] Needs Review

#54315 Jetpack Checkout: enable `Logged Out Visitor Checkout` flow in production
  config/horizon.json
  config/jetpack-cloud-production.json
  config/production.json
Labels: Jetpack, [Size] XS, [Status] Needs Review

#54334 Happy Chat: Notify operator of link interactions
  client/components/happychat/timeline.jsx
Labels: [Status] Needs Review

#54333 Revert "Theme Showcase: Use UpsellNudge component for Upwork banner"
  client/blocks/upwork-banner/index.jsx
  client/blocks/upwork-banner/style.scss
  client/blocks/upwork-banner/test/__snapshots__/index.js.snap
  client/blocks/upwork-banner/test/index.js
Labels: Theme Showcase, [Pod] Design Selection, [Pri] Normal, [Size] XS

#53897 Playwright: add mobile support for interacting with WPCOM sidebar.
  packages/calypso-e2e/src/lib/components/navbar-component.ts
  packages/calypso-e2e/src/lib/components/sidebar-component.ts
  packages/calypso-e2e/src/lib/pages/marketing-page.ts
  test/e2e/specs/specs-playwright/wp-seo__preview-spec.js
Labels: [Status] Needs Review

#54296 Checkout: Only allow masterbar close to go to relative redirect_to
  client/layout/masterbar/checkout.jsx
  client/my-sites/backup/wpcom-backup-upsell.tsx
  client/my-sites/scan/wpcom-scan-upsell.tsx
Labels: Checkout, [Estimate] 1, [Status] Needs Review

#54275 Update to Node 14.17.2
  .circleci/config.yml
  .github/workflows/editing-toolkit-plugin.yml
  .github/workflows/icfy-stats.yml
  .nvmrc
  Dockerfile
  Dockerfile.base
  desktop/Dockerfile
  package.json
  packages/wp-babel-makepot/Dockerfile
Labels: [Status] Needs Review

#54305 My Home: The verify email task sends the task id along with it's track event
  client/my-sites/customer-home/cards/tasks/verify-email/index.tsx
Labels: Analytics, Customer Home, My Home Pod, [Status] Needs Review, [Type] Bug

#54343 Revert "Update to Node 14.17.2"
  .circleci/config.yml
  .github/workflows/editing-toolkit-plugin.yml
  .github/workflows/icfy-stats.yml
  .nvmrc
  Dockerfile
  Dockerfile.base
  desktop/Dockerfile
  package.json
  packages/wp-babel-makepot/Dockerfile
Labels: [Status] Needs Review

#54202 My Home: Directly Link to Support Documentation
  client/blocks/inline-help/inline-help-search-results.jsx
  client/my-sites/customer-home/cards/features/help-search/index.jsx
Labels: Customer Home, OSS Citizen, [Status] Needs Review

#54241 Restructure marketplace code locations
  client/my-sites/checkout/checkout-thank-you/index.jsx
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
  client/my-sites/marketplace/components/index.tsx
  client/my-sites/marketplace/components/marketplace-shopping-cart/index.tsx
  client/my-sites/marketplace/components/simulated-progressbar/index.tsx
  client/my-sites/marketplace/constants.ts
  client/my-sites/marketplace/controller.js
  client/my-sites/marketplace/marketplace-domain-upsell/index.tsx
  client/my-sites/marketplace/marketplace-domain-upsell/style.scss
  client/my-sites/marketplace/marketplace-plugin-details/index.tsx
  client/my-sites/marketplace/marketplace-plugin-details/purchase-area.tsx
  client/my-sites/marketplace/marketplace-plugin-details/test/index.tsx
  client/my-sites/marketplace/marketplace-plugin-setup-status/index.tsx
  client/my-sites/marketplace/marketplace-plugin-setup-status/style.scss
  client/my-sites/marketplace/marketplace-stand-alone-thank-you/index.tsx
  client/my-sites/marketplace/marketplace-test/admin-menu-fetch.tsx
  client/my-sites/marketplace/marketplace-test/component-demo.tsx
  client/my-sites/marketplace/marketplace-test/index.tsx
  client/my-sites/marketplace/theme.ts
  client/my-sites/marketplace/util.ts
  client/state/marketplace/init.ts
  client/state/marketplace/package.json
  client/state/marketplace/purchase-flow/actions.ts
  client/state/marketplace/purchase-flow/reducer.ts
  client/state/marketplace/purchase-flow/selectors.ts
  client/state/marketplace/purchase-flow/test/index.ts
  client/state/marketplace/reducer.ts
  client/state/marketplace/types.ts
  client/state/plugins/reducer.ts
  client/state/types.ts
Labels: [Status] Needs Review

#54325 Sharing: Add Notice for Atomic Private Sites
  client/my-sites/marketing/buttons/buttons.jsx
Labels: OSS Citizen, Sharing, [Status] Needs Review

#48122 Modularise document head state
  client/landing/login/store.js
  client/server/pages/test/index.js
  client/state/document-head/actions.js
  client/state/document-head/init.js
  client/state/document-head/package.json
  client/state/document-head/reducer.js
  client/state/document-head/selectors/get-document-head-formatted-title.js
  client/state/document-head/selectors/get-document-head-link.js
  client/state/document-head/selectors/get-document-head-meta.js
  client/state/document-head/selectors/get-document-head-title.js
  client/state/document-head/selectors/get-document-head-unread-count.js
  client/state/reducer.js
Labels: State, [Status] Needs Review, [Type] Enhancement

#54167 Boot: Try independent user initialization
  client/boot/common.js
  client/landing/login/common.js
  client/landing/login/index.js
  client/lib/user/shared-utils.js
  client/state/current-user/actions.js
Labels: Framework, State, [Status] Needs Review

#54168 Framework: Remove `lib/user` event emitter and unused types
  client/lib/user/index.d.ts
  client/lib/user/index.js
  client/lib/user/user.d.ts
  client/lib/user/user.js
  client/state/current-user/actions.js
Labels: Epic, Framework, [Status] Needs Review

#54316 Plans: Re-position CRM Free card next to Free card
  client/components/jetpack/card/product-without-price/style.scss
  client/my-sites/plans/jetpack-plans/constants.ts
  client/my-sites/plans/jetpack-plans/iterations.ts
  client/my-sites/plans/jetpack-plans/jetpack-crm-free-card/index.tsx
  client/my-sites/plans/jetpack-plans/jetpack-crm-free-card/style.scss
  client/my-sites/plans/jetpack-plans/jetpack-free-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-grid/index.tsx
  client/my-sites/plans/jetpack-plans/product-grid/products-order.ts
  client/my-sites/plans/jetpack-plans/product-grid/style.scss
  client/my-sites/plans/jetpack-plans/selector.tsx
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
Labels: Jetpack Cloud, Plans, [Size] XS, [Status] Needs Review, [Type] Enhancement

#53636 Checkout: Remove OVO payment method
  bin/audit-svg-colors.js
  client/components/payment-logo/index.jsx
  client/lib/cart-values/index.js
  client/lib/checkout/validation.js
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-methods/index.ts
  client/my-sites/checkout/composite-checkout/lib/translate-payment-method-names.ts
  client/my-sites/checkout/composite-checkout/payment-methods/id-wallet.js
  packages/wpcom-checkout/src/types.ts
  static/images/upgrades/ovo.svg
Labels: Checkout, [Estimate] 1

#54093 Site Editor Tracking - Template Part creation / replacement flows.
  apps/wpcom-block-editor/src/wpcom/features/tracking.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/delegate-event-tracking.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-template-part-choose-existing.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-template-part-replace.js
  test/e2e/lib/components/site-editor-component.js
  test/e2e/specs/specs-wpcom/wp-calypso-gutenberg-site-editor-tracking-spec.js
Labels: [Status] Needs Review

#54222 Jetpack Products: Add new constants for realtime products
  packages/calypso-products/src/constants/jetpack.ts
  packages/calypso-products/src/constants/types.ts
  packages/calypso-products/src/plans-list.js
  packages/calypso-products/src/products-list.ts
  packages/calypso-products/src/translations.js
  packages/calypso-products/test/plan-lookups.js
Labels: [Status] Ready to Merge

#54145 Theme Showcase: Make the keyed suggestions matches even more strict
  client/components/keyed-suggestions/index.jsx
  client/lib/trigram/README.md
  client/lib/trigram/index.js
  client/lib/trigram/test/index.js
  client/my-sites/themes/themes-magic-search-card/index.jsx
Labels: [Pod] Design Selection, [Status] Needs Review

#54142 Converting current theme bar display to new, more clear design
  client/my-sites/themes/current-theme/button.jsx
  client/my-sites/themes/current-theme/index.jsx
  client/my-sites/themes/current-theme/style.scss
Labels: [Status] Needs Review

#54254 Theme Showcase: Enable the Theme Showcase feature flag on production
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Theme Showcase, [Pod] Design Selection, [Status] Needs Review

#54095 Theme Showcase: Do away with "Show all themes" button, add tabs
  client/my-sites/themes/recommended-themes.jsx
  client/my-sites/themes/theme-showcase.jsx
  client/my-sites/themes/theme-showcase.scss
  client/my-sites/themes/themes-magic-search-card/index.jsx
  test/e2e/lib/pages/themes-page.js
Labels: Theme Showcase, [Pod] Design Selection, [Status] Needs Review

#54359 DO NOT MERGE: Revert "Theme Showcase: Do away with "Show all themes" button, add tabs"
  client/my-sites/themes/recommended-themes.jsx
  client/my-sites/themes/theme-showcase.jsx
  client/my-sites/themes/theme-showcase.scss
  client/my-sites/themes/themes-magic-search-card/index.jsx
  test/e2e/lib/pages/themes-page.js
Labels: Theme Showcase, [Pod] Design Selection, [Status] Needs Review

#54327 Domains: Hide postal code when unsupported
  client/components/domains/contact-details-form-fields/custom-form-fieldsets/eu-address-fieldset.jsx
  client/components/domains/contact-details-form-fields/custom-form-fieldsets/region-address-fieldsets.jsx
  client/components/domains/contact-details-form-fields/custom-form-fieldsets/test/eu-address-fieldset.js
  client/components/domains/contact-details-form-fields/custom-form-fieldsets/test/uk-address-fieldset.js
  client/components/domains/contact-details-form-fields/custom-form-fieldsets/test/us-address-fieldset.js
  client/components/domains/contact-details-form-fields/custom-form-fieldsets/uk-address-fieldset.jsx
  client/components/domains/contact-details-form-fields/custom-form-fieldsets/us-address-fieldset.jsx
  client/components/domains/contact-details-form-fields/helper.js
  client/components/domains/contact-details-form-fields/index.jsx
  client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx
  client/components/domains/contact-details-form-fields/test/__snapshots__/index.js.snap
  client/my-sites/checkout/composite-checkout/test/composite-checkout.js
Labels: Domains, [Status] Needs Review

#54111 Jetpack Search: fix enabled check for Jetpack sites
  client/my-sites/jetpack-search/content.tsx
  client/my-sites/jetpack-search/controller.js
  client/my-sites/jetpack-search/details.tsx
  client/my-sites/jetpack-search/main-jetpack.tsx
  client/my-sites/jetpack-search/main-wpcom-simple.tsx
  client/my-sites/jetpack-search/placeholder.tsx
  client/my-sites/jetpack-search/purchases.ts
Labels: Jetpack Search, [Status] Ready to Merge

#54156 Add Substack Importer UI
  client/lib/importer/importer-config.js
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/my-sites/importer/file-importer.jsx
  client/my-sites/importer/importer-logo.jsx
  client/my-sites/importer/importer-logo.scss
  client/my-sites/importer/importer-substack.jsx
  client/my-sites/importer/logos/substack.jsx
  client/my-sites/importer/section-import.jsx
  client/my-sites/importer/uploading-pane.jsx
  client/state/imports/actions.js
  config/development.json
  config/test.json
  config/wpcalypso.json
  packages/calypso-color-schemes/src/shared/color-schemes/_classic-dark.scss
  packages/calypso-color-schemes/src/shared/color-schemes/_default.scss
Labels: [Status] Ready to Merge

#54373 chore: Update to Node 14.17.3
  .circleci/config.yml
  .github/workflows/editing-toolkit-plugin.yml
  .github/workflows/icfy-stats.yml
  .nvmrc
  Dockerfile
  Dockerfile.base
  desktop/Dockerfile
  package.json
  packages/wp-babel-makepot/Dockerfile
Labels: [Status] Needs Review

#54347 Domains: Remove some unused component state
  client/landing/domains/registrant-verification/index.jsx
  client/landing/domains/transfer-away-confirmation/index.jsx
  client/my-sites/domains/domain-management/name-servers/dns-templates.jsx
  client/signup/steps/domains/index.jsx
Labels: Domains, [Status] Needs Review, [Type] Janitorial

#54128 Gutenberg Editor Tracking: Track list view block select
  apps/wpcom-block-editor/src/wpcom/features/tracking/delegate-event-tracking.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-list-view-select.js
  test/e2e/lib/gutenberg/tracking/general-tests.js
Labels: [Status] Needs Review

#54382 User: Split shared utils to modules
  client/lib/user/shared-utils.js
  client/lib/user/shared-utils/filter-user-object.js
  client/lib/user/shared-utils/get-computed-attributes.js
  client/lib/user/shared-utils/get-logout-url.js
  client/lib/user/shared-utils/index.js
  client/lib/user/shared-utils/initialize-current-user.js
  client/lib/user/shared-utils/package.json
  client/lib/user/shared-utils/raw-current-user-fetch.js
Labels: Framework, [Status] Needs Review, [Type] Enhancement

#54318 Signup: align step counter with the number of interactive steps
  client/signup/README.md
  client/signup/config/steps-pure.js
  client/signup/main.jsx
  client/signup/signup-header/index.jsx
Labels: Signup, [Status] Needs Review

#54177 Adding account creation flows for Akismet and Gravitar.
  client/lib/login/index.js
  client/lib/oauth2-clients.js
Labels: Signup, [Status] Needs Review, [Type] Bug

#53592 Block Editor Tracking: Track convert to template part and detach blocks from template part actions
  apps/wpcom-block-editor/src/wpcom/features/tracking.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/delegate-event-tracking.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-template-part-detach-blocks.js
  apps/wpcom-block-editor/src/wpcom/features/utils.js
  test/e2e/specs/specs-wpcom/wp-calypso-gutenberg-site-editor-tracking-spec.js
Labels: [Status] Needs Review

#54023 Block Editor: Make sure unsaved changes popup appears in multi entity editing context
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Labels: [Status] Needs Review

#54253 Add siteless checkout thank you page (and post-checkout redirect).
  client/my-sites/checkout/checkout-thank-you/jetpack-checkout-siteless-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/style.scss
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
  client/my-sites/checkout/controller.jsx
  client/my-sites/checkout/index.js
Labels: Jetpack, Post Checkout, [Status] Needs Review

#54339 Fixes Yoast Redirect URL After Plugin Install
  client/state/sites/selectors/get-site-wordpress-seo-wizard-url.js
Labels: [Status] Ready to Merge, [Type] Bug

#54386 Composite Checkout: fix font-weight variable
  packages/composite-checkout/src/components/button.tsx
Labels: Checkout, [Status] Needs Review

#54225 Hide the masterbar during the checkout process from simple to Atomic site.
  client/my-sites/checkout/checkout-thank-you/atomic-store-thank-you-card.jsx
  client/my-sites/checkout/controller.jsx
  client/my-sites/checkout/index.js
Labels: Atomic Upgrade Flows, [Status] Needs Review, [Type] Bug

#54390 Contact: Change confirmation wording
  client/me/help/help-contact/index.jsx
Labels: [Status] Needs Review

#54256 Checkout: Change existingCardProcessor to get postalCode/countryCode from contactDetails
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/lib/existing-card-processor.ts
  client/my-sites/checkout/composite-checkout/lib/merge-if-objects.ts
  client/my-sites/checkout/composite-checkout/test/existing-card-processor.ts
  client/my-sites/checkout/composite-checkout/types/payment-processors.ts
  client/my-sites/checkout/upsell-nudge/index.jsx
  client/my-sites/checkout/upsell-nudge/purchase-modal/index.tsx
  client/my-sites/checkout/upsell-nudge/purchase-modal/util.ts
Labels: Checkout, [Estimate] 1, [Status] Ready to Merge

#54365 Checkout: Refactor variant picker and add tests
  client/my-sites/checkout/composite-checkout/components/item-variation-picker.tsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-review.tsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx
  client/my-sites/checkout/composite-checkout/test/composite-checkout.js
Labels: Checkout, [Estimate] 3, [Status] Ready to Merge

#54400 Upsell Nudge: Prevent canceling card validation if cards have not changed
  client/my-sites/checkout/upsell-nudge/index.jsx
Labels: Checkout, [Estimate] 1, [Status] Needs Review, [Status] Ready to Merge, [Type] Bug

#54364 DevDocs: Fix import statement in Dot-Pager example
  client/components/dot-pager/README.md
Labels: DevDocs, [Status] Ready to Merge

#54345 My Home: "Add menu" task takes unverified users to the correct view in the customiser
  client/state/selectors/get-menus-url.js
  client/state/selectors/test/get-menus-url.js
Labels: My Home Pod, [Status] Needs Review, [Type] Bug

#54404 fix(account recovery): component state access
  client/me/security-account-recovery/edit-phone.jsx
Labels: 2FA, [Status] Needs Review, [Type] Bug

#54240 Jetpack: Remove `<JetpackManageErrorPage />` in favor of `<EmptyContent />`.
  client/my-sites/domains/controller.jsx
  client/my-sites/jetpack-manage-error-page/README.md
  client/my-sites/jetpack-manage-error-page/index.jsx
  client/my-sites/jetpack-manage-error-page/package.json
  client/my-sites/plugins/jetpack-plugins-setup/index.jsx
  client/my-sites/plugins/plugin.jsx
  client/my-sites/site-settings/settings-jetpack/main.jsx
  client/my-sites/site-settings/settings-security/main.jsx
Labels: Components, Jetpack, [Status] Needs Review, [Type] Janitorial

#54412 Jetpack Utils: Import calypso-products functions directly from calypso-products API
  client/my-sites/plans/jetpack-plans/plan-upgrade/utils.ts
Labels: Jetpack, [Estimate] 1, [Status] Needs Review

#54413 Inline Support Modal: add max-width and update styling
  client/blocks/support-article-dialog/content.scss
  client/blocks/support-article-dialog/style.scss
Labels: Support, [Status] Needs Review

#54415 editor tracks - fix replace blocks flow not triggering insert event
  apps/wpcom-block-editor/src/wpcom/features/tracking.js
Labels: [Status] Needs Review

#54416 Legacy Dotcom FSE: Prevent multiple calls to iframe open template part event handler
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Labels: Calypsoify, [Goal] Full Site Editing, [Status] Needs Review, [Type] Bug

#54380 Add an upload animation for large imports
  client/my-sites/importer/uploading-pane.jsx
  client/my-sites/importer/uploading-pane.scss
Labels: [Status] Needs Review

#54379 Use asset modules instead of file-loader
  client/webpack.config.js
  client/webpack.config.node.js
  packages/calypso-build/CHANGELOG.md
  packages/calypso-build/package.json
  packages/calypso-build/webpack/file-loader.js
  yarn.lock
Labels: [Status] Needs Review

#54406 State: Modularize userSettings tree
  client/state/reducer.js
  client/state/selectors/get-original-user-setting.js
  client/state/selectors/get-unsaved-user-settings.js
  client/state/selectors/get-user-setting.js
  client/state/selectors/get-user-settings.js
  client/state/selectors/has-unsaved-user-settings.js
  client/state/selectors/has-user-settings.js
  client/state/selectors/is-pending-email-change.js
  client/state/selectors/is-two-step-enabled.js
  client/state/selectors/is-two-step-sms-enabled.js
  client/state/user-settings/actions.js
  client/state/user-settings/init.js
  client/state/user-settings/package.json
  client/state/user-settings/reducer.js
  client/state/user-settings/selectors.js
  client/state/user-settings/thunks/save-two-step-sms-settings.js
  client/state/user-settings/thunks/save-unsaved-user-settings.js
  client/state/user-settings/thunks/set-user-setting.js
Labels: State, [Status] Needs Review, [Type] Enhancement

#53657 migrate `NameServers` to use react-query
  client/components/data/query-domain-nameservers/README.md
  client/components/data/query-domain-nameservers/index.jsx
  client/data/domains/nameservers/use-domain-nameservers-query.js
  client/data/domains/nameservers/use-update-nameservers-mutation.js
  client/my-sites/domains/components/mapping-instructions/index.jsx
  client/my-sites/domains/domain-management/name-servers/constants.js
  client/my-sites/domains/domain-management/name-servers/index.jsx
  client/my-sites/domains/domain-management/name-servers/with-domain-nameservers.js
  client/state/action-types.ts
  client/state/data-layer/wpcom/domains/nameservers/index.js
  client/state/domains/nameservers/actions.js
  client/state/domains/nameservers/initial.js
  client/state/domains/nameservers/reducer.js
  client/state/domains/nameservers/selectors.js
  client/state/domains/nameservers/test/reducer.js
  client/state/domains/nameservers/test/selectors.js
  client/state/domains/reducer.js
  client/state/domains/test/reducer.js
Labels: Data, [Status] Needs Review

#53269 Stats: Include URL in CSV Export Data
  client/state/stats/lists/test/utils.js
  client/state/stats/lists/utils.js
Labels: OSS Citizen, Stats, [Status] Needs Review

#53858 General Settings: Add Prompt For Changing Site Addresses
  client/my-sites/site-settings/form-general.jsx
Labels: OSS Citizen, Site Settings, [Status] Needs Review

#54455 Welcome tour: fix footer alignment
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/style-tour.scss
Labels: Editing Toolkit, Editor Welcome, [Pri] High, [Status] Needs Review

#54244 route to site selection when going to /theme
  client/controller/index.node.js
  client/controller/index.web.js
  client/layout/style.scss
  client/my-sites/theme/index.web.js
  client/my-sites/themes/controller-logged-in.jsx
  client/my-sites/themes/index.web.js
Labels: [Status] Needs Review

#54196 Enable anti-alias font smoothing for all.
  apps/editing-toolkit/editing-toolkit-plugin/common/index.php
  apps/editing-toolkit/editing-toolkit-plugin/common/index.scss
  apps/notifications/src/panel/Notifications.jsx
  apps/notifications/src/panel/boot/stylesheets/main.scss
  apps/notifications/src/panel/rest-client/wpcom.js
  apps/notifications/src/panel/utils/font-smoothing.js
  apps/notifications/src/standalone/index.js
  client/assets/stylesheets/_main.scss
  client/assets/stylesheets/gutenboarding.scss
  client/landing/gutenboarding/gutenboard.tsx
  client/landing/gutenboarding/hooks/test/use-body-class.test.ts
  client/landing/gutenboarding/hooks/use-body-class.ts
  client/landing/gutenboarding/stores/reader/index.ts
  client/layout/index.jsx
  client/layout/logged-out.jsx
  client/layout/masterbar/style.scss
Labels: Design, [Status] Needs Review

#54313 Emails: Hide the second emails header and hide the back button when necessary
  client/my-sites/email/email-management/email-home.jsx
  client/my-sites/email/email-providers-comparison/index.jsx
Labels: Email management, Professional Email, [Status] Needs Review

#54431 Showcase: update active theme styles
  client/my-sites/themes/current-theme/style.scss
  client/my-sites/themes/recommended-themes.jsx
  client/my-sites/themes/theme-showcase.jsx
  client/my-sites/themes/theme-showcase.scss
  client/my-sites/themes/themes-selection-header/index.jsx
  client/my-sites/themes/themes-selection-header/style.scss
  client/my-sites/themes/themes-selection.jsx
Labels: Theme Showcase, [Status] Needs Review

#53612 ETK: Fix for dotcom legacy FSE to work with current Gutenberg versions
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/class-full-site-editing.php
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/editor/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/plugins/editor-template-classes/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/templates/class-rest-templates-controller.php
Labels: Editing Toolkit, [Status] Needs Review, [Type] Bug

#53685 Displaying domain expiration date when auto-renew is enabled.
  client/me/purchases/manage-purchase/auto-renew-toggle/index.jsx
  client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
  client/my-sites/domains/domain-management/edit/domain-types/renew-options-row.jsx
Labels: Billing, Domains, [Status] Needs Review, [Status] String Freeze, [Type] Enhancement

#54474 Toolbar: Only toggle the toolbar in the TransferPending component
  client/my-sites/checkout/checkout-thank-you/atomic-store-thank-you-card.jsx
  client/my-sites/checkout/checkout-thank-you/transfer-pending.jsx
  client/my-sites/checkout/controller.jsx
  client/my-sites/checkout/index.js
Labels: [Status] Needs Review

#53904 Checkout: Prevent plan upgrade variants which are term downgrades
  client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx
  client/my-sites/checkout/composite-checkout/test/composite-checkout.js
  client/state/products-list/selectors/compute-full-and-monthly-prices-for-plan.js
  client/state/products-list/test/selectors.js
Labels: Checkout, [Estimate] 2, [Status] Needs Review, [Status] Ready to Merge

#54414 Fix empty-cart redirect when coming from Jetpack Cloud pricing page
  client/layout/masterbar/checkout.jsx
  client/layout/masterbar/checkout.tsx
  client/layout/masterbar/logged-in.jsx
  client/layout/masterbar/logged-out.jsx
  client/my-sites/checkout/composite-checkout/hooks/use-remove-from-cart-and-redirect.ts
  client/my-sites/checkout/composite-checkout/hooks/use-valid-checkout-back-url.ts
  client/state/selectors/get-initial-query-arguments.js
Labels: Checkout, Jetpack, Jetpack Cloud, Shopping Cart, [Status] Needs Review

#54451 chore: Migrate packages/accessible-focus to import/order
  .eslintrc.js
  bin/import-order.sh
  packages/accessible-focus/src/test/index.js
Labels: [Status] Needs Review

#53863 Domains reskin: Improve mobile view - take 2
  client/components/domains/domain-search-results/index.jsx
  client/components/domains/domain-suggestion/style.scss
  client/components/domains/featured-domain-suggestions/style.scss
  client/components/domains/register-domain-step/style.scss
Labels: Domains, Mobile Web, Signup, [Goal] Onboarding, [Status] Needs Review

#54442 State: Modularize `i18n` reducer
  client/landing/login/store.js
  client/state/i18n/init.js
  client/state/i18n/language-names/actions.js
  client/state/i18n/locale-suggestions/actions.js
  client/state/i18n/package.json
  client/state/i18n/reducer.js
  client/state/reducer.js
  client/state/selectors/get-locale-suggestions.js
  client/state/selectors/get-localized-language-names.js
Labels: State, [Status] Needs Review, [Type] Enhancement, i18n

#54449 State: Modularize `currencyCode` reducer
  client/state/currency-code/init.js
  client/state/currency-code/package.json
  client/state/currency-code/reducer.js
  client/state/currency-code/selectors.js
  client/state/plans/actions.js
  client/state/products-list/actions.js
  client/state/reducer.js
  client/state/sites/plans/actions.js
  client/state/sites/products/actions.js
Labels: State, [Status] Needs Review, [Type] Enhancement

#54447 `withDeleteUser`: simplify success & error notices
  client/data/users/use-delete-user-mutation.js
  client/my-sites/people/delete-user/with-delete-user.js
Labels: Data, [Status] Needs Review, [Type] Janitorial

#54348 `withUpdateUser`: simplify success & error notices
  client/data/users/use-update-user-mutation.js
  client/my-sites/people/edit-team-member-form/with-update-user.js
Labels: Data, [Status] Needs Review, [Type] Janitorial

#54492 chore: migrate client/sections-helper.js to import/order
  .eslintrc.js
  client/sections-helper.js
Labels: [Status] Needs Review

#54493 chore: migrate client/sections-filter to import/order
  .eslintrc.js
  client/sections-filter.js
Labels: [Status] Needs Review

#54361 Theme Showcase: Do away with "Show all themes" button, add tabs, take 2
  client/my-sites/themes/recommended-themes.jsx
  client/my-sites/themes/single-site-jetpack.jsx
  client/my-sites/themes/single-site-wpcom.jsx
  client/my-sites/themes/theme-showcase.jsx
  client/my-sites/themes/theme-showcase.scss
  client/my-sites/themes/themes-magic-search-card/index.jsx
  test/e2e/lib/pages/themes-page.js
Labels: Theme Showcase, [Pod] Design Selection, [Status] Needs Review

#54479 Shopping Cart: Improve offline errors
  packages/shopping-cart/src/use-refetch-on-focus.ts
  packages/shopping-cart/src/use-shopping-cart-reducer.ts
Labels: Shopping Cart, [Estimate] 1, [Status] Ready to Merge

#54523 Playwright: update how `filterThemes` work.
  packages/calypso-e2e/src/lib/pages/themes-page.ts
Labels: [Status] Needs Review

#54517 Update the link to the cancel FAQ
  client/lib/url/support.js
Labels: Domains, [Status] Needs Review

#54518 Theme Showcase: Higher z-index on search so focus outline doesn't get cut off
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/my-sites/themes/themes-magic-search-card/style.scss
Labels: Theme Showcase, [Pod] Design Selection, [Status] Needs Review

#54515 Make KeyedSuggestions float
  client/components/keyed-suggestions/style.scss
  client/my-sites/themes/themes-magic-search-card/index.jsx
  client/my-sites/themes/themes-magic-search-card/style.scss
Labels: [Pod] Design Selection, [Status] Needs Review

#54006 Playwright: remove default selector waits and postInits where possible.
  packages/calypso-e2e/src/lib/components/comments-component.ts
  packages/calypso-e2e/src/lib/components/index.ts
  packages/calypso-e2e/src/lib/components/navbar-component.ts
  packages/calypso-e2e/src/lib/components/post-likes-component.ts
  packages/calypso-e2e/src/lib/components/support-article-component.ts
  packages/calypso-e2e/src/lib/components/support-component.ts
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
  packages/calypso-e2e/src/lib/pages/marketing-page.ts
  packages/calypso-e2e/src/lib/pages/my-home-page.ts
  packages/calypso-e2e/src/lib/pages/published/published-post-page.ts
  packages/calypso-e2e/src/lib/pages/published/published-posts-list-page.ts
  packages/calypso-e2e/src/lib/pages/settings-page.ts
  packages/calypso-e2e/src/lib/pages/themes-detail-page.ts
  packages/calypso-e2e/src/lib/pages/themes-page.ts
  test/e2e/specs/specs-playwright/wp-theme__switch-preview-spec.js
Labels: [Status] Needs Review

#54471 Move transfer lock form to separate component and update text color
  client/my-sites/domains/domain-management/components/transfer-lock-opt-out-form/index.jsx
  client/my-sites/domains/domain-management/components/transfer-lock-opt-out-form/style.scss
  client/my-sites/domains/domain-management/edit-contact-info/form-card.jsx
Labels: Domains, [Status] Needs Review

#54440 My Home: Fix locale query param sent with checklist API calls
  client/state/data-layer/wpcom/checklist/index.js
Labels: My Home Pod, [Status] Needs Review, [Type] Bug

#54527 Legacy FSE: Fix navigating back to page template
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
  client/gutenberg/editor/calypsoify-iframe.tsx
Labels: [Status] Needs Review

#54490 Remove externalRedirect helper in favor of lib/navigate
  client/jetpack-connect/authorize.js
  client/jetpack-connect/controller.js
  client/jetpack-connect/install-instructions.jsx
  client/jetpack-connect/jetpack-connection.jsx
  client/jetpack-connect/test/utils.js
  client/jetpack-connect/utils.js
  client/lib/route/path.ts
  client/my-sites/controller.js
  client/my-sites/domains/domain-management/domain-connect-mapping/index.jsx
  client/my-sites/sidebar-unified/menu.jsx
  client/state/jetpack-connect/actions/retry-auth.js
Labels: [Status] Needs Review, [Type] Janitorial

#54498 Jetpack Search Purchase: remove unused code for logged-out state
  client/jetpack-connect/controller.js
  client/jetpack-connect/index.js
  client/jetpack-connect/search.jsx
  client/my-sites/purchase-product/controller.js
  client/my-sites/purchase-product/search.jsx
Labels: [Status] Needs Review, [Type] Janitorial

#54491 Remove the jetpack/connect-redirect-pressable-credential-approval feature flag
  client/jetpack-connect/authorize.js
  config/development.json
  config/production.json
  config/stage.json
Labels: [Status] Needs Review, [Type] Janitorial
