Repository Automattic/wp-calypso, pull requests merged in 2021-09, with the labels that each got.

#55882 Checkout: Make state field not required in domainRequiredContactDetails
  client/my-sites/checkout/composite-checkout/types/wpcom-store-state.ts
Labels: [Status] Needs Review

#55885 Preview: remove Inline Help Popover interaction
  client/components/web-preview/content.jsx
  client/my-sites/preview/controller.js
  client/my-sites/preview/main.jsx
Labels: [Status] Needs Review, [Type] Janitorial, Help

#55863 Theme Showcase: Remove segmented control for theme tiers
  client/my-sites/themes/theme-showcase.jsx
  client/my-sites/themes/themes-magic-search-card/index.jsx
  client/my-sites/themes/themes-magic-search-card/style.scss
  client/my-sites/themes/themes-selection.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  packages/calypso-e2e/src/lib/pages/themes-page.ts
  test/e2e/specs/specs-playwright/wp-theme__details-preview-activate.js
  test/e2e/specs/specs-playwright/wp-theme__popover-preview.js
Labels: [Status] Needs Review, Theme Showcase

#55797 Emails: Update positions for Titan button: add mail, mailboxes and remove
  client/my-sites/email/email-providers-comparison/style.scss
  client/my-sites/email/titan-new-mailbox-list/index.jsx
  client/my-sites/email/titan-new-mailbox-list/style.scss
Labels: [Status] Needs Review, Professional Email

#55817 Do it for me purchase flow skeleton
  client/my-sites/marketing/controller.js
  client/my-sites/marketing/do-it-for-me/landing.tsx
  client/my-sites/marketing/do-it-for-me/site-info-collection.tsx
  client/my-sites/marketing/index.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#55889 Plans: Remove unlimited themes from /plans
  client/state/sites/plans/test/selectors.js
  client/state/themes/test/selectors.js
  packages/calypso-products/src/plans-list.js
Labels: [Status] Needs Review

#55070 Show prices in LTR direction in cloud pricing page
  client/components/jetpack/card/jetpack-product-card/index.tsx
Labels: [Status] Needs Review, [Size] S, Jetpack Cloud

#55886 chore: Fix import/order
  bin/categorize-component-styles.js
  bin/generate-style-variants.js
  client/blocks/eligibility-warnings/test/index.tsx
  client/me/concierge/shared/appointment-info.js
  client/me/concierge/shared/available-time-card.js
  client/me/concierge/shared/closure-notice.js
  client/me/concierge/shared/gm-closure-notice.js
  client/me/help/contact-form-notice/chat-covid-limited-availability.jsx
  client/me/help/contact-form-notice/chat-generic-closure.jsx
  client/me/help/contact-form-notice/chat-holiday-closure.jsx
  client/me/help/contact-form-notice/chat-reduced-availability.jsx
  client/me/help/contact-form-notice/index.jsx
  client/me/help/gm-closure-notice/index.jsx
  client/me/notification-settings/blogs-settings/header.jsx
  client/me/purchases/manage-purchase/test/notices.js
  client/me/purchases/manage-purchase/test/payment-info-block.js
  client/me/purchases/upcoming-renewals/test/upcoming-renewals-dialog.tsx
  client/me/reauth-required/index.jsx
  client/me/security-2fa-backup-codes-prompt/index.jsx
  client/me/security-2fa-code-prompt/index.jsx
  client/me/security-2fa-enable/index.jsx
  client/me/security-2fa-initial-setup/index.jsx
  client/my-sites/stats/stats-list/index.jsx
  desktop/app/lib/desktop-analytics/index.js
  desktop/bin/validate_tag.js
  packages/calypso-doctor/evaluations/node-npm-cache.js
  packages/magellan-mocha-plugin/test/test_run.spec.js
  test/e2e/lib/reporter/magellan-reporter.js
  test/visual/backstop_data/engine_scripts/puppeteer/login.js
Labels: [Status] Needs Review

#54669 Introducing a separate product cancellation flow for Jetpack Products
  client/blocks/jetpack-benefits/site-visits.tsx
  client/components/marketing-survey/cancel-jetpack-form/index.tsx
  client/components/marketing-survey/cancel-jetpack-form/jetpack-cancellation-survey.tsx
  client/components/marketing-survey/cancel-jetpack-form/steps.ts
  client/components/marketing-survey/cancel-jetpack-form/style.scss
  client/me/purchases/remove-purchase/index.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Jetpack, [Status] Ready to Merge

#55900 Remove references to premium themes
  client/lib/plans/features-list.js
  client/my-sites/plans-features-main/wpcom-faq.jsx
  client/my-sites/theme/main.jsx
  client/my-sites/themes/single-site-jetpack.jsx
  client/my-sites/themes/single-site-wpcom.jsx
  client/my-sites/themes/theme-showcase.jsx
  client/state/themes/selectors/get-jetpack-upgrade-url-if-premium-theme.js
  client/state/themes/selectors/is-premium-theme-available.js
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/plans-list.js
Labels: [Status] Needs Review

#55867 Billing History: Print Receipt hides reminder text
  client/me/purchases/billing-history/receipt.jsx
  client/me/purchases/billing-history/style.scss
  client/my-sites/purchases/billing-history/index.tsx
  client/my-sites/purchases/billing-history/style.scss
Labels: [Status] Needs Review

#55899 ci: Do not install Chrome on CircleCI
  .circleci/config.yml
Labels: [Status] Needs Review

#55724 Change translation context into a comment
  client/me/purchases/billing-history/receipt.jsx
Labels: [Status] Needs Review

#55876 Add hasTranslation to strings added to inlineSupportLinks in Calypso sections
  client/me/purchases/billing-history/main.tsx
  client/me/purchases/payment-methods/main.tsx
  client/my-sites/purchases/billing-history/index.tsx
  client/my-sites/purchases/main.tsx
  client/my-sites/purchases/payment-methods/index.tsx
Labels: [Pri] Low, [Status] Needs Review

#55663 Desktop: Bump version to 7.2.0
  desktop/package.json
Labels: [Status] Needs Review, Desktop App, Releases

#55698 Gutenboarding: Use shopping-cart package to add products to the cart
  client/landing/gutenboarding/hooks/use-on-site-creation.ts
Labels: [Status] Needs Review, Signup, Shopping Cart

#55907 Update a8c deps
  client/package.json
  packages/components/package.json
  yarn.lock
Labels: [Status] Needs Review

#55633 Add feature flag for License-based Checkout, Milestone 1
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#55829 Fix theme of DesignPicker
  client/signup/controller.js
  client/signup/main.jsx
  client/signup/steps/design-picker/index.jsx
  client/signup/style.scss
  client/signup/utils.js
Labels: [Status] Needs Review, Blogger Experience Pod

#55436 Blogger Experience: add tags education link under Tags section
  apps/editing-toolkit/README.md
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/tags-education/README.md
  apps/editing-toolkit/editing-toolkit-plugin/tags-education/class-tags-education.php
  apps/editing-toolkit/editing-toolkit-plugin/tags-education/index.js
  apps/editing-toolkit/editing-toolkit-plugin/tags-education/src/add-tags-education-link.js
  apps/editing-toolkit/package.json
Labels: [Status] Needs Review, [Status] String Freeze

#54683 Iframe Bridge: improve reliability of sidebar observer
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Labels: [Status] Needs Review

#55924 Remove wpcom.undocumented() methods for retrieving and removing purchases
  client/lib/wpcom-undocumented/lib/me.js
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/my-sites/domains/domain-management/list/test/index.js
  client/state/purchases/actions.js
Labels: [Status] Needs Review, [Type] Janitorial

#55928 chore: Update use-memo-one
  yarn.lock
Labels: [Status] Needs Review

#55929 chore: Update react-resize-aware
  yarn.lock
Labels: [Status] Needs Review

#55753 migrate `InlineHelp` to use `react-query`
  client/blocks/inline-help/data/use-inline-help-search-query.js
  client/blocks/inline-help/inline-help-search-card.jsx
  client/blocks/inline-help/inline-help-search-results.jsx
  client/blocks/inline-help/popover.jsx
  client/components/data/query-inline-help-search/index.jsx
  client/layout/popup-search/index.js
  client/state/inline-help/actions.js
  client/state/inline-help/reducer.js
  client/state/inline-help/selectors/get-inline-help-admin-section-search-results-query.js
  client/state/inline-help/selectors/get-inline-help-search-results-for-query.js
  client/state/inline-help/selectors/is-requesting-inline-help-search-results-for-query.js
  client/state/inline-help/test/reducer.js
  client/state/inline-help/test/selectors.js
Labels: [Status] Needs Review, Help

#55931 chore: Drop chai-enzyme dependency
  client/blocks/app-promo/test/index.jsx
  client/components/count/test/index.jsx
  client/components/forms/form-text-input/test/index.jsx
  client/components/sub-masterbar-nav/test/dropdown.jsx
  package.json
  test/client/setup-test-framework.js
  yarn.lock
Labels: [Status] Needs Review

#55892 Adds form to DIFM Lite
  client/my-sites/marketing/do-it-for-me/site-info-collection.tsx
  client/my-sites/marketing/index.js
  config/_shared.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  package.json
  yarn.lock
Labels: [Status] Needs Review

#55866 People: Differentiate between followers and viewers for private sites
  client/my-sites/people/people-profile/index.jsx
Labels: [Status] Needs Review, People Management

#55905 Implement JP pricing page without monthly experiment
  client/my-sites/plans/jetpack-plans/product-grid/index.tsx
  client/my-sites/plans/jetpack-plans/product-grid/style.scss
Labels: [Status] Needs Review, [Size] S, ABTest, Jetpack Cloud

#55915 Checkout: Remove text for logged-in email contact field
  client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx
Labels: [Status] Ready to Merge, Checkout

#55665 Signup: Use shopping cart manager
  client/lib/signup/cart.ts
  client/lib/signup/step-actions/index.js
  client/lib/signup/test/cart.js
Labels: [Status] Ready to Merge, Signup, Shopping Cart

#55734 Checkout: Move WPLineItem and associates to own file
  client/lib/cart-values/cart-items.js
  client/my-sites/checkout/composite-checkout/components/payment-method-step.tsx
  client/my-sites/checkout/composite-checkout/components/wp-line-item.tsx
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
  client/my-sites/checkout/composite-checkout/lib/translate-cart.ts
  client/my-sites/marketplace/components/marketplace-shopping-cart/index.tsx
  packages/wpcom-checkout/jest.config.js
  packages/wpcom-checkout/package.json
  packages/wpcom-checkout/src/checkout-labels.ts
  packages/wpcom-checkout/src/index.ts
  yarn.lock
Labels: [Status] Needs Review, Checkout

#55914 Composite Checkout: Clean up remaining JavaScript code
  packages/composite-checkout/README.md
  packages/composite-checkout/demo/index.js
  packages/composite-checkout/src/components/payment-logos.tsx
  packages/composite-checkout/src/lib/payment-methods/payment-logo.tsx
  packages/composite-checkout/src/lib/stripe-credit-card-fields-demo.js
  packages/composite-checkout/src/public-api.ts
Labels: [Status] Needs Review, Checkout

#55869 Playwright: add step to accept cookies when viewing published post
  packages/calypso-e2e/src/lib/components/cookie-banner-component.ts
  packages/calypso-e2e/src/lib/components/index.ts
  test/e2e/specs/specs-playwright/wp-notifications__trash-spec.js
Labels: [Status] Needs Review

#55933 /plans: Append ref param if it exists
  client/server/pages/index.js
Labels: [Status] Needs Review

#55942 Fix/55926 remove premium references
  client/blocks/inline-help/contextual-help.js
  client/blocks/post-share/nudges.jsx
  client/blocks/product-purchase-features-list/find-new-theme.jsx
  client/blocks/product-purchase-features-list/index.jsx
  client/lib/plans/features-list.js
  client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx
  client/my-sites/checkout/composite-checkout/lib/get-plan-features.ts
  client/my-sites/themes/single-site-jetpack.jsx
  client/my-sites/themes/single-site-wpcom.jsx
  client/state/plans/test/fixture/index.js
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/plans-list.js
  packages/launch/src/focused-launch/summary/index.tsx
Labels: [Status] Needs Review

#55809 Composite Checkout: Remove useMessages from CheckoutProvider
  client/me/purchases/manage-purchase/payment-method-selector/index.tsx
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-complete-callback.tsx
  client/my-sites/checkout/upsell-nudge/purchase-modal/index.tsx
  packages/composite-checkout/README.md
  packages/composite-checkout/demo/index.js
  packages/composite-checkout/src/components/checkout-provider.tsx
  packages/composite-checkout/src/components/transaction-status-handler.ts
  packages/composite-checkout/src/components/use-messages.ts
  packages/composite-checkout/src/lib/checkout-context.ts
  packages/composite-checkout/src/public-api.ts
  packages/composite-checkout/src/types.ts
  packages/composite-checkout/test/checkout-provider.js
  packages/composite-checkout/test/checkout.js
Labels: [Status] Needs Review, Checkout

#55953 Remove unused getCart/setCart undocumented functions
  client/lib/wpcom-undocumented/lib/undocumented.js
Labels: [Status] Needs Review

#55963 Playwright: replace build configuration objects with a function.
  .teamcity/_self/projects/WPComTests.kt
Labels: [Status] Needs Review

#55872 [GB 11.4.0-rc1][E2E] Add GB edge support to Playwright Gutenberg widgets E2E
  test/e2e/specs/specs-playwright/wp-widgets__spec.ts
  test/e2e/tsconfig.json
Labels: [Status] Needs Review

#55862 Add new skip button style to design picker step
  client/signup/navigation-link/index.jsx
  client/signup/step-wrapper/index.jsx
  client/signup/step-wrapper/style.scss
  client/signup/steps/design-picker/index.jsx
  client/signup/steps/domains/index.jsx
  client/signup/steps/emails/index.jsx
  client/signup/style.scss
Labels: [Status] Needs Review, Blogger Experience Pod

#55930 Fix site selector style in inline help
  client/blocks/inline-help/style.scss
Labels: [Status] Needs Review, [Type] Janitorial, Help

#55984 Jetpack cloud: update sidebar items
  client/components/jetpack/sidebar/index.jsx
  client/components/jetpack/sidebar/menu-items/index.jsx
  client/components/jetpack/sidebar/menu-items/jetpack-cloud.jsx
  client/components/jetpack/sidebar/menu-items/jetpack-icons.jsx
  client/components/jetpack/sidebar/style.scss
  client/jetpack-cloud/sections/partner-portal/sidebar/index.tsx
Labels: Jetpack, [Status] Ready to Merge, Jetpack Cloud, Jetpack Partner Portal

#55989 Theme Showcase: Fix copy on upsell
  client/my-sites/themes/single-site-wpcom.jsx
Labels: [Status] Needs Review, Theme Showcase

#55979 Google Analytics: Update Support Link
  client/my-sites/site-settings/analytics/form-google-analytics-jetpack.jsx
  client/my-sites/site-settings/analytics/form-google-analytics-simple.jsx
Labels: [Status] Needs Review, OSS Citizen

#55399 Purchases: Adjust modal message when deleting a Domain Mapping subscription.
  client/lib/purchases/index.js
  client/me/purchases/remove-purchase/index.jsx
Labels: [Type] Bug, [Status] Needs Review, Domains, User Report

#56004 Improve unit tests for React 17 PR
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/test/store.test.js
  packages/i18n-calypso/test/use-translate.js
Labels: [Status] Needs Review

#55883 Run headstart after pick design
  client/lib/signup/step-actions/index.js
  client/signup/config/flows-pure.js
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
Labels: [Status] Needs Review, Blogger Experience Pod

#56014 Fix cmd + click not work on link in post publish panel or toast notification
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Labels: [Status] Needs Review, Blogger Experience Pod

#55985 Reader: Fix Gallery block caption render
  client/blocks/reader-full-post/_content.scss
Labels: [Status] Needs Review, Reader

#55891 Purchases: Redesigned pre-cancellation survey for plans
  client/components/blank-canvas/index.js
  client/components/blank-canvas/style.scss
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/initial-survey-state.js
  client/components/marketing-survey/cancel-purchase-form/precancellation-chat-button/index.jsx
  client/components/marketing-survey/cancel-purchase-form/precancellation-chat-button/style.scss
  client/components/marketing-survey/cancel-purchase-form/steps-for-product-and-survey.js
  client/components/marketing-survey/cancel-purchase-form/steps.js
  client/components/marketing-survey/cancel-purchase-form/style.scss
  client/components/marketing-survey/cancel-purchase-form/test/initial-survey-state.js
  packages/material-design-icons/src/communication/outline-chat_bubble-24px.svg
  packages/material-design-icons/svg-sprite/material-icons.svg
Labels: [Status] Needs Review, Components, Purchases

#55967 `InlineHelp`: remove usage of `support_type`
  client/blocks/inline-help/admin-sections.js
  client/blocks/inline-help/inline-help-search-results.jsx
  client/blocks/inline-help/test/admin-sections.js
Labels: [Status] Needs Review, [Type] Janitorial, Help

#55831 Domains: Add GSuite email upsell skip button
  client/my-sites/domains/email-providers-upsell/index.jsx
  client/my-sites/email/email-providers-comparison/index.jsx
  client/my-sites/email/email-providers-comparison/style.scss
Labels: [Status] Needs Review, OSS Citizen

#55880 Checkout: Simplify contact validation and add tests
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
  client/my-sites/checkout/composite-checkout/contact-validation.js
  client/my-sites/checkout/composite-checkout/lib/contact-validation.tsx
  client/my-sites/checkout/composite-checkout/test/composite-checkout.js
  client/my-sites/checkout/composite-checkout/test/hydrate-nested-object.js
  client/my-sites/checkout/composite-checkout/test/util/index.js
  client/my-sites/checkout/composite-checkout/types/wpcom-store-state.ts
  client/my-sites/checkout/upsell-nudge/index.jsx
  packages/composite-checkout/src/components/checkout-steps.tsx
  packages/wpcom-checkout/src/types.ts
Labels: Checkout

#55913 Move Reader filter buttons
  client/reader/search-stream/index.jsx
  client/reader/search-stream/style.scss
Labels: [Status] Needs Review, Reader

#55542 Activity Log: Get display rules from real API endpoint
  client/components/activity-card-list/index.jsx
  client/components/activity-card-list/visible-days-limit-upsell/index.tsx
  client/components/data/query-rewind-policies/index.ts
  client/components/jetpack/daily-backup-status/index.jsx
  client/components/jetpack/daily-backup-status/status-card/visible-days-limit.tsx
  client/my-sites/activity/activity-log/index.jsx
  client/my-sites/backup/hooks.js
  client/state/action-types.ts
  client/state/activity-log/actions.js
  client/state/activity-log/display-rules/actions.ts
  client/state/activity-log/display-rules/reducer.ts
  client/state/activity-log/reducer.js
  client/state/data-layer/wpcom/activity-log/get-display-rules/index.ts
  client/state/data-layer/wpcom/sites/rewind/policies/from-api.ts
  client/state/data-layer/wpcom/sites/rewind/policies/index.ts
  client/state/rewind/policies/actions.ts
  client/state/rewind/policies/reducer.ts
  client/state/rewind/policies/types.ts
  client/state/rewind/reducer.js
  client/state/rewind/selectors/get-activity-log-visible-days.ts
  client/state/rewind/selectors/get-rewind-policies-request-status.ts
  client/state/rewind/selectors/is-requesting-rewind-policies.ts
  client/state/selectors/is-requesting-activity-log-display-rules.ts
Labels: [Type] Enhancement, [Status] Needs Review, [Size] S, Activity Log

#56044 Composite Checkout: Prepare for 1.0 release
  packages/composite-checkout/CHANGELOG.md
  packages/composite-checkout/package.json
Labels: [Status] Needs Review

#55981 re-apply "change add a menu link to point to the top level of customier"
  client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
  client/state/sites/selectors/get-customizer-url.js
  client/state/sites/test/selectors.js
Labels: [Status] Needs Review

#55971 Webpack: Reqire process.js for polyfills
  client/package.json
  client/webpack.config.js
  yarn.lock
Labels: [Status] Needs Review

#55927 Use flags to control the destination of onboarding flow
  client/signup/config/flows.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Blogger Experience Pod

#56026 Purchases: Run experiment for redesigned pre-cancellation survey
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/steps-for-product-and-survey.js
Labels: [Type] Task, Purchases, Atomic, ABTest

#55750 Reorder the domain transfer bullets so that the one year renewal one is the first one
  client/components/domains/use-my-domain/utilities/option-info.js
Labels: [Status] Needs Review, Domains

#56048 chore: Fix eslint rule no-use-before-define
  client/lib/wporg/jsonp.js
Labels: [Status] Needs Review

#55987 Welcome Tour: Show overlay controls when the focus is within
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/style-tour.scss
Labels: [Status] Needs Review, Editor Welcome, Welcome Tour

#55992 Jetpack Cancellation Form: Fix selected site id
  client/components/marketing-survey/cancel-jetpack-form/index.tsx
  client/me/purchases/remove-purchase/index.jsx
Labels: Jetpack, [Status] Needs Review, [Size] XS

#55871 Subscriptions: Remove CSS rule that prevented displaying the image placeholder
  client/blocks/reader-feed-header/index.jsx
  client/blocks/reader-feed-header/style.scss
Labels: Reader, [Status] Ready to Merge

#55897 Jetpack site-less Checkout: add new UI for automatic provisioning
  client/my-sites/checkout/checkout-thank-you/jetpack-checkout-siteless-thank-you-completed.tsx
  client/my-sites/checkout/checkout-thank-you/style.scss
  client/my-sites/checkout/checkout-thank-you/test/utils.js
  client/my-sites/checkout/checkout-thank-you/utils.js
  client/state/data-layer/wpcom/jetpack-checkout/support-ticket/index.js
  client/state/jetpack-checkout/reducer.ts
  client/state/selectors/get-jetpack-checkout-support-ticket-destination-site-id.ts
Labels: Jetpack, [Status] Needs Review, [Size] S

#55995 Playwright: Remove deprecated focused launch e2e spec
  test/e2e/specs/specs-wpcom/wp-calypso-gutenberg-focused-launch-spec.js
Labels: [Status] Needs Review

#55713 Add account-only SSO signup flow
  client/lib/login/index.js
  client/lib/paths/login/index.js
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  client/signup/config/steps-pure.js
  client/signup/steps/user/index.jsx
  client/state/login/reducer.js
Labels: [Status] Needs Review, Signup

#55961 Playwright: merge and migrate `Invite: Editor` and `Invite: Viewer` spec.
  packages/calypso-e2e/src/lib/pages/index.ts
  packages/calypso-e2e/src/lib/pages/people-page.ts
  packages/calypso-e2e/src/lib/pages/user-signup-page.ts
  test/e2e/specs/specs-calypso/wp-invite-users__editor-spec.js
  test/e2e/specs/specs-playwright/wp-invite__new-user.ts
  test/e2e/specs/specs-playwright/wp-invite__revoke.ts
Labels: [Status] Needs Review

#56005 Show Jetpack Plans page for Jetpack Product Sites
  client/my-sites/plans/controller.jsx
  client/state/sites/selectors/index.js
  client/state/sites/selectors/is-jetpack-product-site.js
Labels: Plans, [Status] Needs Review, [Size] XS, Jetpack Backup

#55993 Stats: Add banner for Parse.ly
  client/assets/images/icons/parsely-logo.svg
  client/my-sites/stats/site.jsx
  client/my-sites/stats/style.scss
Labels: Stats, [Status] Needs Review

#56033 Themes Showcase: nudge business plan instead of premium
  client/my-sites/themes/single-site-wpcom.jsx
  client/my-sites/themes/single-site.jsx
Labels: [Status] Needs Review, Theme Showcase, Upsell Nudge

#56040 Jetpack site-less checkout: disable site-less purchases of Search products
  client/jetpack-connect/controller.js
  client/my-sites/plans/jetpack-plans/build-checkout-url.ts
  client/my-sites/purchase-product/controller.js
  client/my-sites/purchase-product/index.js
Labels: Jetpack, [Status] Needs Review, Jetpack Search, [Size] XS

#56042 Shopping Cart: Prepare for 2.0 release
  client/package.json
  packages/launch/package.json
  packages/shopping-cart/CHANGELOG.md
  packages/shopping-cart/package.json
  packages/wpcom-checkout/package.json
  yarn.lock
Labels: [Status] Needs Review

#56082 Composite Checkout: Remove border and background from disabled text buttons
  packages/composite-checkout/src/components/button.tsx
Labels: [Status] Needs Review

#55997 Refactor storybook config
  bin/storybook-default-config.js
  packages/components/.storybook/main.js
  packages/composite-checkout/.storybook/main.js
  packages/search/.storybook/main.js
Labels: [Status] Needs Review

#56008 Checkout: US 9 digit zip code validation/formatting
  packages/wpcom-checkout/src/postal-code.ts
Labels: [Status] Needs Review, Checkout, Quick Fix

#55878 [E2E][GB 11.4.x] Test fixes for Gutenberg
  test/e2e/lib/components/abstract-editor-component.js
  test/e2e/lib/components/site-editor-component.js
  test/e2e/lib/driver-helper.js
  test/e2e/lib/gutenberg/gutenberg-editor-component.js
Labels: [Status] Needs Review, [Status] Needs Author Reply, caused-by-gutenberg-upgrade

#55594 Incorporate feedback from HEs in the GitHub issue template.
  .github/ISSUE_TEMPLATE/happiness-bug-report.yml
Labels: [Status] Needs Review

#56053 Change tags education link to support doc for users in different langs
  apps/editing-toolkit/editing-toolkit-plugin/tags-education/src/add-tags-education-link.js
Labels: [Status] Needs Review, Blogger Experience Pod

#56049 Updates copy of first step in the editor welcome guide
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-content.js
Labels: [Status] Needs Review, Editor Welcome, Blogger Experience Pod, Welcome Tour

#55903 Update UTM params for the wp.me/logo-maker url
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
  client/my-sites/marketing/tools/index.tsx
Labels: [Status] Needs Review

#55890 Emails: Change wording on cancelation survey for Google Workspace
  client/components/marketing-survey/gsuite-cancel-purchase-dialog/gsuite-cancellation-features.jsx
  client/components/marketing-survey/gsuite-cancel-purchase-dialog/index.jsx
  client/lib/gsuite/get-gsuite-subscription-status.js
  client/lib/gsuite/has-gsuite-with-another-provider.js
  client/lib/gsuite/has-gsuite-with-us.js
  client/lib/gsuite/index.js
Labels: [Status] Needs Review, G Suite

#55978 inline-help: decouple filtering `contextualResults` for _Managing Purchases_ from other results
  client/blocks/inline-help/inline-help-search-results.jsx
Labels: [Status] Needs Review, Help

#56029 server: Server all requests using evergreen
  client/document/domains-landing.jsx
  client/document/index.jsx
  client/package.json
  client/server/middleware/assets.js
  client/server/middleware/build-target.js
  client/server/middleware/unsupported-browser.js
  client/server/pages/index.js
  client/server/pages/test/analytics.js
  client/server/pages/test/index.js
  yarn.lock
Labels: [Status] Needs Review

#55471 Site Editor: Prevent opening the navigation sidebar, navigate home instead
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-site-editor/index.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-site-editor/index.php
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-site-editor/navigation-toggle/index.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-site-editor/navigation-toggle/style.scss
  apps/editing-toolkit/package.json
Labels: Editor, [Status] Ready to Merge, [Status] Blocked / Hold, [Goal] Full Site Editing, [Team] Cylon

#55558 Site Editor Tracks - skip nav sidebar tests
  test/e2e/specs/specs-wpcom/wp-calypso-gutenberg-site-editor-tracking-spec.js
Labels: [Status] Ready to Merge, [Status] Blocked / Hold

#55910 Theme Showcase: Replace QueryTheme with QueryCanonicalTheme for ThemePreview
  client/my-sites/themes/theme-preview.jsx
Labels: [Status] Needs Review, Theme Showcase

#56069 Try jest-runner-groups as a way for e2e suites
  .teamcity/_self/projects/WPComTests.kt
  .teamcity/_self/projects/WebApp.kt
  test/e2e/.eslintrc.js
  test/e2e/docs/running-tests.md
  test/e2e/docs/writing_tests.md
  test/e2e/jest.config.js
  test/e2e/package.json
  test/e2e/specs/specs-playwright/wp-blocks__coblocks-gutter-spec.ts
  test/e2e/specs/specs-playwright/wp-blocks__coblocks.ts
  test/e2e/specs/specs-playwright/wp-blocks__media-spec.ts
  test/e2e/specs/specs-playwright/wp-editor__tracks-events.ts
  test/e2e/specs/specs-playwright/wp-gutenboarding__happy-path.ts
  test/e2e/specs/specs-playwright/wp-gutenboarding__language.ts
  test/e2e/specs/specs-playwright/wp-invite__revoke.ts
  test/e2e/specs/specs-playwright/wp-likes__comment-spec.js
  test/e2e/specs/specs-playwright/wp-likes__post-spec.js
  test/e2e/specs/specs-playwright/wp-media__edit-spec.js
  test/e2e/specs/specs-playwright/wp-media__upload-spec.js
  test/e2e/specs/specs-playwright/wp-notifications__trash-spec.js
  test/e2e/specs/specs-playwright/wp-plans__purchases-spec.ts
  test/e2e/specs/specs-playwright/wp-reader__view-spec.ts
  test/e2e/specs/specs-playwright/wp-seo__preview-spec.js
  test/e2e/specs/specs-playwright/wp-site-import.ts
  test/e2e/specs/specs-playwright/wp-ssr_check.ts
  test/e2e/specs/specs-playwright/wp-stats__insights-spec.ts
  test/e2e/specs/specs-playwright/wp-support__home-spec.ts
  test/e2e/specs/specs-playwright/wp-support__popover-spec.js
  test/e2e/specs/specs-playwright/wp-theme__details-preview-activate.js
  test/e2e/specs/specs-playwright/wp-theme__popover-preview.js
  test/e2e/specs/specs-playwright/wp-widgets__spec.ts
  yarn.lock
Labels: [Status] Ready to Merge

#56099 Stats: Update Parse.ly link, tweaks to mobile styles
  client/my-sites/stats/site.jsx
  client/my-sites/stats/style.scss
Labels: Stats

#56045 Checkout: Make delete icon text-only
  client/my-sites/checkout/composite-checkout/components/delete-icon.svg
  client/my-sites/checkout/composite-checkout/components/wp-line-item.tsx
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
Labels: [Status] Ready to Merge, Checkout

#56065 Fix a bug in the amount of time that is shown remaining for a product during the Jetpack product cancellation flow
  client/components/marketing-survey/cancel-jetpack-form/jetpack-benefits-step.tsx
Labels: [Status] Needs Review

#56107 [E2E][GB] Fix non-awaited argument to `getInputText`
  test/e2e/lib/gutenberg/gutenberg-editor-component.js
Labels: [Status] Needs Review

#55939 Purchase Cancellation: Enable custom Jetpack cancellation flow in pro…
  client/me/purchases/remove-purchase/index.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Jetpack, [Status] Needs Review, [Size] XS

#56105 Playwright: Fix references to Calypso live for Playwright WPCOM tests in TeamCity
  .teamcity/_self/projects/WPComTests.kt
Labels: [Status] Needs Review

#55675 Domains: Update Domain Transfer checkout page
  client/assets/images/illustrations/domain-transferred-success.svg
  client/components/thank-you/index.tsx
  client/components/thank-you/types.ts
  client/my-sites/checkout/checkout-thank-you/domains/domain-mapping-thank-you.jsx
  client/my-sites/checkout/checkout-thank-you/domains/domain-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/domains/style.scss
  client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-mapping.tsx
  client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-transfer.tsx
  client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/index.tsx
  client/my-sites/checkout/checkout-thank-you/domains/types.ts
  client/my-sites/checkout/checkout-thank-you/index.jsx
Labels: [Status] Needs Review, Domains

#55994 Colour Scheme Picker: Display Success Notice on Change
  client/blocks/color-scheme-picker/index.jsx
  client/components/global-notices/README.md
Labels: Site Settings, [Status] Needs Review, OSS Citizen

#53366 ci(build): Drop fallback build
  .teamcity/_self/projects/WebApp.kt
  apps/editing-toolkit/package.json
  package.json
Labels: [Status] Needs Review

#55901 Difm lite thank you page
  client/lib/cart-values/cart-items.js
  client/my-sites/checkout/checkout-thank-you/difm/difm-lite-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/difm/style.scss
  client/my-sites/checkout/checkout-thank-you/index.jsx
  client/my-sites/checkout/checkout-thank-you/test/index.js
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
  packages/calypso-products/src/constants/wpcom.ts
  packages/calypso-products/src/is-difm-product.ts
  packages/calypso-products/src/product-values.ts
Labels: [Status] Needs Review, difm-lite

#56028 Updates on the difm lite landing page
  client/assets/images/difm/IT-1.png
  client/assets/images/difm/consult-1.png
  client/assets/images/difm/consult-2.png
  client/assets/images/difm/dietician-1.png
  client/assets/images/difm/musician-1.png
  client/assets/images/difm/photography-1.png
  client/assets/images/difm/phsych-1.png
  client/assets/images/difm/restaurant-1.png
  client/assets/images/difm/tree-removal.png
  client/my-sites/marketing/do-it-for-me/landing.tsx
Labels: [Status] Needs Review, difm-lite

#56095 Add comparison context to EmailProvidersComparison tracking
  client/my-sites/domains/email-providers-upsell/index.jsx
  client/my-sites/email/controller.js
  client/my-sites/email/email-management/email-home.jsx
  client/my-sites/email/email-providers-comparison/index.jsx
Labels: [Status] Needs Review

#56101 Jetpack: update copy styling on Site Search popover
  client/components/jetpack/card/jetpack-product-card/style.scss
Labels: Jetpack, [Status] Ready to Merge, Jetpack Cloud

#56027 Emails: Update thank you page for check out when buying a professional email
  client/my-sites/checkout/checkout-thank-you/index.jsx
  client/my-sites/email/titan-set-up-thank-you/index.tsx
Labels: [Status] Needs Review, Professional Email

#56137 Fix typo in `Once the transfer is done you can can point %(domain)s to your WordPress.com site.`
  client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-transfer.tsx
Labels: [Status] Needs Review

#55592 Domains: Route to new email upsell page after adding domain to cart
  client/my-sites/domains/domain-search/index.jsx
  client/my-sites/domains/paths.js
  client/my-sites/email/email-providers-comparison/index.jsx
Labels: OSS Citizen

#56112 Track legacy plan redirects in Jetpack pricing page
  client/my-sites/plans/jetpack-plans/selector.tsx
Labels: [Status] Needs Review, Jetpack Cloud, [Size] XS

#55531 Purchases: Request removals through `wpcom/v2` endpoints
  client/lib/purchases/actions.js
  client/lib/wpcom-undocumented/lib/me.js
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/me/purchases/cancel-purchase/button.jsx
  client/me/purchases/confirm-cancel-domain/index.jsx
  client/state/purchases/actions.js
  client/state/purchases/test/actions.js
Labels: API, [Status] Needs Review, Purchases

#56141 Adds typeform id to config
  config/_shared.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
Labels: [Status] Needs Review

#56143 Enable feature flag for difm lite pilot
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#56031 Simplify the domain mapping verification screen
  client/components/domains/connect-domain-step/connect-domain-step-ownership-auth-code.jsx
  client/components/domains/use-my-domain/utilities/connect-domain-action.js
  packages/wpcom.js/src/lib/domains.js
  packages/wpcom.js/src/lib/site.js
Labels: [Status] Needs Review, Domains

#56132 Merge Desktop 7.2.0 release to trunk
  desktop/package.json
Labels: [Status] Needs Review, Releases

#55637 ETK: Restrict HEIC image uploads
  apps/editing-toolkit/editing-toolkit-plugin/common/disable-heic-images.js
  apps/editing-toolkit/editing-toolkit-plugin/common/index.php
  apps/editing-toolkit/package.json
Labels: [Status] Needs Review, Editing Toolkit

#55693 Playwright: use an interface for passing TestFile paths.
  packages/calypso-e2e/src/index.ts
  packages/calypso-e2e/src/media-helper.ts
  test/e2e/lib/jest/environment.js
  test/e2e/specs/constants.js
  test/e2e/specs/specs-playwright/wp-blocks__coblocks.ts
  test/e2e/specs/specs-playwright/wp-blocks__media-spec.ts
  test/e2e/specs/specs-playwright/wp-media__edit-spec.ts
  test/e2e/specs/specs-playwright/wp-media__upload-spec.ts
  test/e2e/tsconfig.json
Labels: [Status] Needs Review

#56011 Add ownership verification steps to connection flow
  client/components/domains/connect-domain-step/connect-domain-step-login.jsx
  client/components/domains/connect-domain-step/connect-domain-step-ownership-auth-code.jsx
  client/components/domains/connect-domain-step/constants.jsx
  client/components/domains/connect-domain-step/page-definitions.js
  client/components/domains/connect-domain-step/style.scss
  client/components/domains/use-my-domain/index.jsx
  client/components/domains/use-my-domain/utilities/connect-domain-action.js
  packages/wpcom.js/src/lib/domains.js
  packages/wpcom.js/src/lib/site.js
Labels: [Status] Needs Review, Domains

#55991 Pw/editor post basic flow
  packages/calypso-e2e/src/browser-helper.ts
  packages/calypso-e2e/src/lib/components/editor-settings-sidebar-component.ts
  packages/calypso-e2e/src/lib/components/index.ts
  packages/calypso-e2e/src/lib/components/preview-component.ts
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
  packages/calypso-e2e/src/lib/pages/published/published-post-page.ts
  test/e2e/specs/specs-playwright/wp-editor__post-basic-flow-spec.ts
  test/e2e/specs/specs-playwright/wp-widgets__spec.ts
Labels: [Status] Needs Review

#56148 Selenium: fix selector for G Suite upsell, now replaced with TItan Email upsell
  test/e2e/lib/components/find-a-domain-component.js
  test/e2e/specs/specs-calypso/wp-manage-domains__add-a-domain-spec.js
Labels: [Status] Needs Review

#56109 Wraps "Manage" in the translate function
  client/my-sites/domains/domain-management/list/wpcom-domain-item.jsx
Labels: [Status] Needs Review

#56039 Playwright: update viewports and associated modules/specs.
  .teamcity/_self/projects/WPComTests.kt
  .teamcity/_self/projects/WebApp.kt
  packages/calypso-e2e/__mocks__/config.js
  packages/calypso-e2e/src/browser-helper.ts
  packages/calypso-e2e/src/browser-manager.ts
  packages/calypso-e2e/src/data-helper.ts
  packages/calypso-e2e/src/element-helper.ts
  packages/calypso-e2e/src/lib/components/navbar-component.ts
  packages/calypso-e2e/src/lib/components/sidebar-component.ts
  packages/calypso-e2e/src/lib/flows/gutenboarding-flow.ts
  packages/calypso-e2e/src/lib/flows/new-post-flow.ts
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
  packages/calypso-e2e/src/lib/pages/marketing-page.ts
  packages/calypso-e2e/src/lib/pages/media-page.ts
  packages/calypso-e2e/src/lib/pages/people-page.ts
  packages/calypso-e2e/src/lib/pages/plans-page.ts
  packages/calypso-e2e/src/lib/pages/published/published-post-page.ts
  packages/calypso-e2e/src/lib/pages/stats-page.ts
  packages/calypso-e2e/src/types.d.ts
  packages/calypso-e2e/test/browser-helper.test.ts
  packages/calypso-e2e/test/data-helper.test.ts
  test/e2e/config/default.json
  test/e2e/docs/environment_variables.md
  test/e2e/specs/specs-playwright/wp-editor__post-basic-flow-spec.ts
  test/e2e/specs/specs-playwright/wp-gutenboarding__language.ts
  test/e2e/specs/specs-playwright/wp-invite__revoke.ts
  test/e2e/specs/specs-playwright/wp-media__edit-spec.ts
  test/e2e/specs/specs-playwright/wp-plans__purchases-spec.ts
  test/e2e/specs/specs-playwright/wp-seo__preview-spec.js
  test/e2e/specs/specs-playwright/wp-stats__insights-spec.ts
Labels: [Status] Needs Review

#56121 Update Newspack blocks to v1.37.1
  .yarnrc.yml
  apps/editing-toolkit/editing-toolkit-plugin/newspack-blocks/index.php
  apps/editing-toolkit/package.json
  yarn.lock
Labels: [Status] Needs Review

#56129 build: Drop lerna
  .gitignore
  docs/dependency-management.md
  docs/monorepo.md
  package.json
  yarn.lock
Labels: [Status] Needs Review

#56164 Editor Welcome: fix overlay controls on touch devices
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/style-tour.scss
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js
Labels: [Status] Needs Review, Accessibility, Editor Welcome, Welcome Tour

#56097 Allow buttons to track if link has context.
  apps/notifications/src/panel/indices-to-html/index.js
Labels: Notifications, [Status] Ready to Merge, Billing

#55936 Welcome Tour: Add keyboard navigation via left/right arrow keys & Esc
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/hooks/use-focus-handler.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/hooks/use-keydown-handler.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.js
Labels: [Status] Needs Review, Accessibility, Editor Welcome, Welcome Tour

#56093 Update icon used for typography:global styles
  apps/editing-toolkit/editing-toolkit-plugin/global-styles/src/global-styles-sidebar.js
  apps/editing-toolkit/editing-toolkit-plugin/global-styles/src/icon.js
Labels: [Status] Needs Review

#56146 Notifications: update button styling
  apps/notifications/src/panel/boot/stylesheets/main.scss
  apps/notifications/src/panel/boot/stylesheets/shared/buttons.scss
Labels: [Status] Needs Review, Notifications, Billing

#56169 Theme Showcase: Fix for Atomic themes no loading
  client/my-sites/themes/single-site.jsx
Labels: [Status] Needs Review, Theme Showcase

#55038 Global Styles: Add more robust support for multiple font weights for some font families
  apps/editing-toolkit/editing-toolkit-plugin/global-styles/class-global-styles.php
Labels: [Status] Needs Review, Editing Toolkit

#56153 Playwright: Add step to wait for comment to be trashed.
  test/e2e/specs/specs-playwright/wp-notifications__trash-spec.js
Labels: [Status] Needs Review

#56171 Fix incorrectly named ownership verification component
  client/components/domains/connect-domain-step/connect-domain-step-ownership-auth-code.jsx
Labels: [Status] Needs Review, Domains

#55968 Jetpack Backup: Get storage usage info from the WPCOM API
  client/components/backup-storage-space/backup-storage-space-upsell/index.tsx
  client/components/backup-storage-space/hooks.ts
  client/components/backup-storage-space/index.tsx
  client/components/backup-storage-space/storage-usage-levels.ts
  client/components/backup-storage-space/style.scss
  client/components/backup-storage-space/test/hooks.js
  client/components/backup-storage-space/test/storage-usage-levels.js
  client/components/backup-storage-space/usage-display.tsx
  client/components/data/query-rewind-policies/index.ts
  client/components/data/query-rewind-size/index.tsx
  client/my-sites/backup/main.jsx
  client/my-sites/plans/current-plan/purchases-listing.jsx
  client/state/action-types.ts
  client/state/data-layer/wpcom/sites/rewind/size/from-api.ts
  client/state/data-layer/wpcom/sites/rewind/size/index.ts
  client/state/rewind/reducer.js
  client/state/rewind/selectors/get-rewind-bytes-available.ts
  client/state/rewind/selectors/get-rewind-bytes-used.ts
  client/state/rewind/selectors/get-rewind-size-request-status.ts
  client/state/rewind/selectors/get-site-backup-storage-available.ts
  client/state/rewind/selectors/get-site-backup-storage-used.ts
  client/state/rewind/selectors/index.ts
  client/state/rewind/selectors/is-requesting-rewind-policies.ts
  client/state/rewind/selectors/is-requesting-rewind-size.ts
  client/state/rewind/size/actions.ts
  client/state/rewind/size/reducer.ts
  client/state/rewind/size/types.ts
Labels: [Type] Enhancement, [Status] Needs Review, Purchases, [Size] M, Jetpack Backup

#56084 SEO Tools: add archive_title page title token
  client/components/seo/meta-title-editor/index.jsx
  client/components/title-format-editor/index.jsx
  client/state/sites/selectors/build-seo-title.js
  client/state/sites/test/selectors.js
Labels: Jetpack, [Status] Blocked / Hold, SEO Tools

#56154 Replace LazyRender with intersection observer library
  client/devdocs/design/search-collection.jsx
  client/my-sites/domains/domain-management/list/list-all.jsx
  client/package.json
  yarn.lock
Labels: [Status] Needs Review

#56000 Update isolated block editor
  .yarnrc.yml
  client/package.json
  package.json
  yarn.lock
Labels: [Status] Needs Review

#56170 Themes Showcase: show WPcom upsell for Atomic sites
  client/my-sites/themes/single-site-jetpack.jsx
  client/my-sites/themes/single-site-wpcom.jsx
Labels: [Status] Needs Review, Atomic, Theme Showcase

#56128 Design Picker: Increase size of thumbnails in design-setup-site step
  client/signup/config/steps-pure.js
  client/signup/steps/design-picker/index.jsx
  client/signup/steps/design-picker/style.scss
  packages/design-picker/src/components/index.tsx
Labels: [Status] Needs Review, Design Picker, Blogger Experience Pod

#56166 Remove is_previewable site computed attribute
  client/blocks/site-preview/index.jsx
  client/blocks/taxonomy-manager/list-item.jsx
  client/components/web-preview/README.md
  client/state/guided-tours/contexts/is-selected-site-previewable.js
  client/state/selectors/test/get-public-sites.js
  client/state/selectors/test/get-visible-sites.js
  client/state/sites/selectors/get-site-computed-attributes.js
  client/state/sites/test/selectors.js
  client/state/ui/test/selectors.js
Labels: [Status] Needs Review, [Type] Janitorial

#56131 Remove Lodash from Layout components (layout + masterbar)
  client/layout/index.jsx
  client/layout/logged-out.jsx
  client/layout/masterbar/crowdsignal.jsx
  client/layout/masterbar/logged-out.jsx
  client/layout/sidebar/expandable.jsx
Labels: [Status] Needs Review, [Type] Janitorial

#56193 Two small fixes for the server build
  client/server/api/sign-in-with-apple.js
  client/webpack.config.node.js
Labels: [Status] Needs Review, [Type] Janitorial

#56196 Build: remove postcss-custom-properties plugin
  client/package.json
  client/webpack.config.js
  yarn.lock
Labels: [Status] Needs Review, Build

#56197 Build: remove guard that emitted images only for evergreen builds
  client/webpack.config.js
Labels: [Status] Needs Review, Build

#56136 Remove wpcom.undocumented() methods for /help endpoints
  client/lib/directly/index.js
  client/lib/wpcom-undocumented/lib/undocumented.js
  client/me/help/help-contact-form/index.jsx
  client/me/help/help-contact/index.jsx
  client/state/happychat/user/actions.js
  client/state/help/ticket/actions.js
Labels: [Status] Needs Review, [Type] Janitorial, Help

#56195 build: Simplify generation of assets list
  bin/loader-stats.js
  client/server/middleware/assets.js
  client/server/pages/test/index.js
  client/webpack.config.js
Labels: [Status] Needs Review

#56100 Add readme files to images folders
  client/assets/images/README.md
  static/images/README.md
Labels: Documentation, [Status] Needs Review

#56187 Cancellation Flow: Fix Jetpack button variations in cancellation flow
  client/components/marketing-survey/cancel-jetpack-form/index.tsx
Labels: Jetpack, [Status] Needs Review

#55904 Checkout: Disable required fields
  client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx
  client/components/domains/registrant-extra-info/ca-form.jsx
  client/my-sites/checkout/composite-checkout/components/contact-details-container.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-cached-domain-contact-details.ts
  client/my-sites/checkout/composite-checkout/types/wpcom-store-state.ts
Labels: [Status] Needs Review, Checkout

#56150 Playwright: Create re-usable block smoke testing structure, and migrate jetpack extended blocks
  packages/calypso-e2e/src/lib/blocks/audio-block.ts
  packages/calypso-e2e/src/lib/blocks/click-to-tweet-block.ts
  packages/calypso-e2e/src/lib/blocks/dynamic-hr-block.ts
  packages/calypso-e2e/src/lib/blocks/file-block.ts
  packages/calypso-e2e/src/lib/blocks/hero-block.ts
  packages/calypso-e2e/src/lib/blocks/image-block.ts
  packages/calypso-e2e/src/lib/blocks/index.ts
  packages/calypso-e2e/src/lib/blocks/jetpack-extended/index.ts
  packages/calypso-e2e/src/lib/blocks/jetpack-extended/instagram.ts
  packages/calypso-e2e/src/lib/blocks/jetpack-extended/twitter.ts
  packages/calypso-e2e/src/lib/blocks/logos-block.ts
  packages/calypso-e2e/src/lib/blocks/pricing-table-block.ts
  packages/calypso-e2e/src/lib/blocks/schemas.ts
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
  test/e2e/.eslintrc.js
  test/e2e/docs/style-guide-playwright.md
  test/e2e/docs/writing_tests.md
  test/e2e/specs/specs-playwright/shared-specs/block-testing.ts
  test/e2e/specs/specs-playwright/wp-blocks__coblocks-gutter-spec.ts
  test/e2e/specs/specs-playwright/wp-blocks__coblocks.ts
  test/e2e/specs/specs-playwright/wp-blocks__jetpack-extended.ts
  test/e2e/specs/specs-playwright/wp-blocks__media-spec.ts
Labels: [Status] Needs Review

#56087 Playwright: migrate WordPress.com Free/Publish subsuite of Signup spec.
  packages/calypso-e2e/src/email-client.ts
  packages/calypso-e2e/src/lib/components/domain-search-component.ts
  packages/calypso-e2e/src/lib/components/index.ts
  packages/calypso-e2e/src/lib/components/me/index.ts
  packages/calypso-e2e/src/lib/components/me/me-sidebar-component.ts
  packages/calypso-e2e/src/lib/components/navbar-component.ts
  packages/calypso-e2e/src/lib/flows/gutenboarding-flow.ts
  packages/calypso-e2e/src/lib/pages/account-closed-page.ts
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
  packages/calypso-e2e/src/lib/pages/index.ts
  packages/calypso-e2e/src/lib/pages/login-page.ts
  packages/calypso-e2e/src/lib/pages/me/account-settings-page.ts
  packages/calypso-e2e/src/lib/pages/me/index.ts
  packages/calypso-e2e/src/lib/pages/signup-pick-plan-page.ts
  packages/calypso-e2e/src/types.d.ts
  test/e2e/specs/specs-playwright/wp-signup__free.ts
Labels: [Status] Needs Review

#56104 Make masterbar in cloud pricing page wider
  client/jetpack-cloud/sections/pricing/controller.tsx
  client/jetpack-cloud/sections/pricing/header/index.tsx
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/style.scss
  client/my-sites/plans/jetpack-plans/controller.tsx
  client/my-sites/plans/jetpack-plans/selector.tsx
  client/my-sites/plans/jetpack-plans/types.ts
Labels: [Status] Needs Review, Jetpack Cloud, [Size] XS

#56213 Remove calendly appointment URL
  config/production.json
Labels: Jetpack, [Status] Needs Review, [Size] XS
