Repository Automattic/wp-calypso, pull requests merged in 2022-07, with the labels that each got.

#65148 Generated design picker: Validate the pre-selected design
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx
Labels: [Type] Bug, [Status] Needs Review

#64933 When user has a single domain that has email, auto-redirect to management screen
  client/my-sites/email/email-management/email-home.tsx
  client/my-sites/email/email-management/home/email-plan.jsx
Labels: [Status] Needs Review

#65150 Fix issue where browser URL would not reflect internal page state
  client/my-sites/email/email-management/email-home.tsx
Labels: [Status] Needs Review

#65123 Plugins: Remove upgrade banners
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/plugins/plugins-browser/test/index.jsx
Labels: [Status] Needs Review, Plugins, Upsell Nudge, Marketplace, Limited Atomic

#65117 Improve flow handling of pre-selected designs
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  packages/data-stores/src/onboard/actions.ts
  packages/data-stores/src/onboard/reducer.ts
Labels: [Type] Bug, [Status] Needs Review

#65057 Fix checkout cancel URL in Jetpack upsell flow
  client/my-sites/plans/jetpack-plans/get-purchase-url-callback.ts
Labels: [Status] Needs Review, [Size] XS

#65139 Localize the 'Learn More' link in 'What can be imported?' popup
  client/blocks/import/ready/platform-details.tsx
Labels: [Status] Needs Review

#65086 Google Sign-in: Migrate the Redirect flow to the new Google Identity Services API
  client/components/social-buttons/google.js
Labels: [Status] Needs Review

#65131 Config: Update README to provide a concept of progression of environments
  config/README.md
Labels: [Status] Needs Review

#65156 Wrap importer descriptions in translate function
  client/blocks/importer/components/importer-drag/config.tsx
Labels: [Status] Needs Review

#63774 [ETK][TeamCity] Show full diff output in the ETK build process if there's a diff between builds
  .teamcity/_self/lib/wpcom/WPComPluginBuild.kt
Labels: [Status] Needs Review

#64679 Update Jetpack Search heading font & logo.
  client/my-sites/jetpack-search/content.tsx
  client/my-sites/jetpack-search/main.tsx
  client/my-sites/jetpack-search/style.scss
Labels: Jetpack, [Status] Ready to Merge, Jetpack Search

#65146 Import: skip WordPress Migration selector for WP imports starting from I don't have a website
  client/blocks/import/ready/index.tsx
  client/blocks/import/ready/platform-details.tsx
  client/blocks/importer/wordpress/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import-ready/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import/helper.ts
Labels: [Status] Needs Review

#65124 Add `signup/goals-step-2` feature flag to all config .json files
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Goals Capture

#64904 Replace Editor Help Link for Widgets with WPcom
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-documentation-links/class-wpcom-documentation-links.php
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-documentation-links/src/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-documentation-links/src/style.css
Labels: Documentation, Editor, [Status] Needs Review, Help

#65084 `ContactDetailsFormFields`: refactor tests to `@testing-library/react`
  client/components/domains/contact-details-form-fields/test/__snapshots__/index.js.snap
  client/components/domains/contact-details-form-fields/test/index.js
Labels: Framework, [Status] Needs Review, Testing

#64122 Jetpack Cloud: Enable the agency signup flow in production
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
Labels: [Status] Needs Review, Jetpack Cloud, Jetpack Licensing Portal

#65178 i18n: Place the WordPress logo in the correct location during onboarding
  client/landing/stepper/declarative-flow/internals/global.scss
Labels: [Status] Needs Review

#64685 Disconnect Stripe account by site
  client/my-sites/earn/memberships/index.jsx
  client/state/memberships/settings/actions.js
Labels: [Status] Needs Review

#65179 Checkout: Improve types of checkout pending and post-checkout redirect
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/utils.ts
  client/blocks/editor-checkout-modal/index.tsx
  client/gutenberg/editor/calypsoify-iframe.tsx
  client/my-sites/checkout/checkout-thank-you/pending.tsx
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-complete-callback.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/index.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/wechat/wechat-payment-qrcode.tsx
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.ts
  client/my-sites/checkout/controller.jsx
  client/my-sites/checkout/modal/index.tsx
  client/my-sites/checkout/upsell-nudge/index.jsx
  client/state/order-transactions/constants.js
  client/state/selectors/get-order-transaction.js
  client/state/selectors/get-order-transaction.ts
  packages/launch/src/context.ts
Labels: [Status] Needs Review

#65145 Onboarding: Remove redirect to site editor
  client/landing/stepper/declarative-flow/site-setup-flow.ts
Labels: [Status] Needs Review, NUX, [Goal] Onboarding, Stepper

#65141 Help Contact Form: Allow eligible users to connect to happy chat when jetpack connection is broken
  client/me/help/help-contact/index.jsx
Labels: [Status] Needs Review, Help

#64214 E2E: add WordPress.com Starter plan spec.
  packages/calypso-e2e/src/lib/pages/plans-page.ts
  test/e2e/specs/plans/plans__signup-starter.ts
Labels: [Status] Needs Review

#65210 Design Picker: Removes the pricing information from premium themes
  packages/design-picker/src/components/index.tsx
Labels: [Status] Needs Review, Design Picker

#65213 Checkout: Remove invalid urls from getThankYouPageUrl
  client/my-sites/checkout/checkout-thank-you/pending.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.ts
Labels: [Status] Needs Review

#64931 Import: fix other links not redirecting to correct location
  client/landing/stepper/declarative-flow/internals/steps-repository/import-ready/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import/helper.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
Labels: [Status] Needs Review

#65189 Atomic: Use allowed mime types set by site
  client/lib/media/utils/is-site-allowed-file-types-to-be-trusted.js
Labels: [Status] Needs Review, Media, VideoPress, Limited Atomic

#65019 Fix/migrate enzyme to react testing library
  client/components/head/test/__snapshots__/index.jsx.snap
  client/components/head/test/index.jsx
Labels: [Status] Needs Review, OSS Citizen

#65190 `SiteSettingsSecurity`: refactor tests to `@testing-library/react`
  client/my-sites/site-settings/settings-security/test/main.jsx
Labels: Framework, [Status] Needs Review, Testing

#65224 `CloudflareAnalyticsSettings`: refactor tests to `@testing-library/react`
  client/my-sites/site-settings/test/form-cloudflare-analytics.jsx
Labels: Framework, [Status] Needs Review, Testing

#65226 `GoogleAnalytics(Simple|Jetpack)Form`: refactor tests to `@testing-library/react`
  client/my-sites/site-settings/analytics/form-google-analytics-jetpack.jsx
  client/my-sites/site-settings/analytics/form-google-analytics-simple.jsx
  client/my-sites/site-settings/test/form-google-analytics.jsx
Labels: Framework, [Status] Needs Review, Testing

#65234 People: Refactor `PeopleInviteDetails` tests to `@testing-library/react`
  client/my-sites/people/people-invite-details/test/index.jsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review, People Management, Testing

#65099 Design Picker: The tooltip was not displaying appropriately
  packages/design-picker/src/components/premium-badge/index.tsx
  packages/design-picker/src/components/premium-badge/style.scss
Labels: [Status] Needs Review, Design Picker

#65058 Update email upsell button to link directly to email addition page
  client/my-sites/email/add-mailboxes/index.tsx
  client/my-sites/email/inbox/index.jsx
  client/my-sites/email/inbox/mailbox-selection-list/index.jsx
  client/my-sites/email/inbox/mailbox-selection-list/style.scss
  client/my-sites/email/inbox/new-mailbox-upsell/index.tsx
  client/my-sites/email/inbox/new-mailbox-upsell/style.scss
Labels: [Status] Needs Review

#65122 Me: Improve UI when photo and Gravatar profile are hidden
  client/blocks/edit-gravatar/index.jsx
  client/blocks/edit-gravatar/style.scss
  client/blocks/edit-gravatar/test/index.jsx
  client/me/profile/index.jsx
  client/me/profile/style.scss
  client/me/profile/updated-gravatar-string.js
Labels: [Status] Needs Review, [Status] Needs Design Review, Me, [Status] Needs Copy Review, [Status] Design Input Requested, [Status] Editorial Input Requested, Build Maintenance

#65202 Jetpack Agency Dashboard: fix icon vertical misalignment
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-card/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-table/style.scss
Labels: [Status] Needs Review, Jetpack Cloud, [Size] XS, Quick Fix

#64498 Jetpack Licensing Portal - Exclude certain products from the license issue screen
  client/state/partner-portal/licenses/hooks/use-products-query.ts
  client/state/partner-portal/licenses/test/hooks.js
Labels: [Status] Needs Review, [Size] S, [Status] Blocked / Hold, Jetpack Cloud, Jetpack Licensing Portal

#65125 Marketplace: Add Support for Preinstalled Premium Plugins
  client/lib/plugins/utils.js
  client/my-sites/plugins/constants.js
  client/my-sites/plugins/plugin-details-CTA/CTA-button.jsx
  client/my-sites/plugins/plugin-details-CTA/index.jsx
  client/my-sites/plugins/plugin-details-CTA/preinstalled-premium-plugins-CTA.jsx
  client/my-sites/plugins/plugin-details.jsx
  client/my-sites/plugins/plugins-browser-item/index.jsx
  client/my-sites/plugins/use-preinstalled-premium-plugin/index.js
Labels: [Status] Needs Review, Marketplace, Marketplace: add Jetpack Search

#65215 Plugins: Add eligibility exception for Starter plans
  client/my-sites/plugins/plugin-details-CTA/index.jsx
Labels: [Status] Needs Review

#65236 Revert "Plugins: Remove upgrade banners"
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/plugins/plugins-browser/test/index.jsx
Labels: [Status] Needs Review, Plugins, Marketplace, Limited Atomic

#65205 Onboarding: Remove redirect to WooCommerce wp-admin page
  client/landing/stepper/declarative-flow/site-setup-flow.ts
Labels: [Status] Needs Review, NUX, Stepper

#65142 Editing Toolkit: Add feature flags to the help center
  apps/editing-toolkit/editing-toolkit-plugin/help-center/class-help-center.php
  packages/help-center/src/components/help-center-container.tsx
  packages/help-center/src/contexts/FeatureFlagContext.tsx
  packages/help-center/src/types.ts
Labels: [Status] Needs Review, Next Steps/Help Center V1

#65107 Reset to default color when user clicks "Clear"
  apps/editing-toolkit/editing-toolkit-plugin/jetpack-timeline/blocks/src/timeline-item.js
Labels: [Type] Bug, Editing Toolkit, [Status] Reviewer Approved, Block: Timeline block

#65251 Sites Dashboard: First pass at Sites Table design
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/components/sites-table.tsx
  packages/components/src/index.js
  packages/components/src/sites-table/index.tsx
Labels: [Status] Needs Review, [Type] Task, Sites Management Dashboard

#65271 Checkout: Allow string versions of receiptId etc in getThankYouPageUrl
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.ts
Labels: [Status] Needs Review

#65227 Fix incorrect design_type in calypso_signup_design_type_submit event
  packages/design-picker/src/hooks/use-theme-designs-query.ts
Labels: [Type] Bug, [Status] Needs Review

#64604 Enable Tus uploads only for VideoPress
  client/data/media/use-add-media.js
  client/lib/media/utils/can-use-videopress.js
  client/lib/media/utils/index.js
  packages/wpcom.js/src/lib/site.media.js
Labels: [Type] Bug, [Status] Needs Review, Media, VideoPress

#65191 Purchases: Show new pre-cancellation form when cancelling non-plan products
  client/components/blank-canvas/style.scss
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/is-survey-filled-in.js
  client/components/marketing-survey/cancel-purchase-form/previous-step.js
  client/components/marketing-survey/cancel-purchase-form/radio-option.jsx
  client/components/marketing-survey/cancel-purchase-form/style.scss
  client/components/marketing-survey/cancel-purchase-form/test/previous-step.js
  client/me/purchases/cancel-purchase/button.jsx
  client/me/purchases/remove-purchase/index.jsx
  client/state/purchases/selectors/will-atomic-site-revert-after-purchase-deactivation.js
Labels: [Status] Needs Review, Purchases, Limited Atomic

#64993 Implement GA4 analytics for Jetpack Green
  client/lib/analytics/ad-tracking/constants.js
  client/lib/analytics/ad-tracking/google-analytics-4.ts
  client/lib/analytics/ad-tracking/google-analytics.js
  client/lib/analytics/ad-tracking/record-order.js
  client/lib/analytics/ad-tracking/setup-gtag.js
  client/lib/analytics/ad-tracking/setup.js
  client/lib/analytics/ga.js
  client/lib/analytics/record-add-to-cart.js
  client/lib/analytics/utils/cost-to-usd.js
  client/lib/analytics/utils/jetpack-cart-to-ga-purchase.ts
  client/lib/analytics/utils/jetpack-product-to-ga-item.ts
  client/lib/analytics/utils/split-wpcom-jetpack-cart-info.ts
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-complete-callback.tsx
  client/tsconfig.json
  package.json
  yarn.lock
Labels: [Status] Needs Review, GA4

#65220 Stepper: Added HotJar and FullStory scripts
  client/landing/stepper/index.tsx
Labels: [Status] Needs Review, Analytics

#65158 Goals Capture: Enable Goals Step i2 layout based on the feature flag
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/goals-capture-container.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/goals.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/select-goals.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/style.scss
Labels: [Status] Needs Review, Goals Capture

#65280 Help Center: Improved percentage and simple sites management
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  client/layout/index.jsx
  client/layout/masterbar/logged-in.jsx
  client/state/sites/selectors/index.js
  client/state/sites/selectors/is-simple-site.ts
  config/development.json
  config/stage.json
  config/wpcalypso.json
  packages/data-stores/src/support-queries/use-support-availability.ts
  packages/happychat-connection/src/use-happychat-available.ts
  packages/help-center/src/components/help-center.tsx
  packages/help-center/src/components/index.d.ts
  packages/help-center/src/hooks/use-still-need-help-url.tsx
  packages/help-center/src/index.ts
  packages/help-center/src/utils.ts
Labels: [Status] Needs Review, Help Center

#64953 Removes the [emails/show-new-comparison-component] feature flag
  client/my-sites/domains/controller.jsx
  client/my-sites/domains/email-providers-upsell/index.jsx
  client/my-sites/domains/email-providers-upsell/index.tsx
  client/my-sites/email/email-providers-stacked-comparison/index.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/email-upsell-navigation.scss
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/email-upsell-navigation.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/get-on-submit-new-mailboxes-handler.ts
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/get-upsell-props.ts
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/google-workspace-card.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/professional-email-card.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/selectors/get-product-by-provider-and-interval.ts
  client/my-sites/email/email-providers-stacked-comparison/style.scss
Labels: [Status] Needs Review, Email form unification

#65232 Update sites and analyzer data stores
  config/development.json
  config/wpcalypso.json
  packages/data-stores/src/analyzer/index.ts
  packages/data-stores/src/site/actions.ts
  packages/data-stores/src/site/reducer.ts
  packages/data-stores/src/site/selectors.ts
  packages/data-stores/src/site/types.ts
Labels: [Status] Needs Review

#65270 plugin-site: Correct calculate plugin manage permissions
  client/my-sites/plugins/plugin-site/plugin-site.jsx
Labels: [Status] Needs Review

#65090 Jetpack Agency Dashboard: Add partner key selection
  client/jetpack-cloud/sections/agency-dashboard/dashboard-overview/index.tsx
  client/jetpack-cloud/sections/partner-portal/controller.tsx
  client/jetpack-cloud/sections/partner-portal/license-select-partner-key/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-select-partner-key/style.scss
  client/jetpack-cloud/sections/partner-portal/primary/select-partner-key/index.tsx
  client/jetpack-cloud/sections/partner-portal/utils.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud, Jetpack Licensing Portal, Jetpack Licensing

#65287 Premium themes: Add correct cart item for Atomic sites
  client/my-sites/theme/main.jsx
  client/state/themes/selectors/get-jetpack-upgrade-url-if-premium-theme.js
Labels: Themes, [Status] Needs Review, Limited Atomic

#65293 Update menu after purchasing a marketplace plugin
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
  client/state/admin-menu/actions/index.js
Labels: [Status] Needs Review, Marketplace, Limited Atomic

#65268 CI: add Authentication E2E build.
  .teamcity/_self/projects/WebApp.kt
  test/e2e/specs/authentication/authentication__magic-link.ts
  test/e2e/specs/authentication/authentication__sms.ts
  test/e2e/specs/authentication/authentication__totp.ts
Labels: [Status] Needs Review

#65301 Show upgrade banner when installing a theme on a Limited Atomic site
  client/my-sites/themes/theme-upload/index.jsx
Labels: Themes, [Status] Needs Review, Limited Atomic

#64908 Add WPCOM_FEATURES_INSTALL_PURCHASED_PLUGINS to the starter plan
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review

#65297 Launch Marketplace plugins on Starter plan
  config/horizon.json
  config/production.json
  config/stage.json
Labels: [Status] Needs Review, Limited Atomic

#65296 Sites Management Dashboard: Add SitesBadge and style the tabs for desktop and mobile
  client/sites-dashboard/components/sites-badge.tsx
  client/sites-dashboard/components/sites-table-filter-tabs.tsx
Labels: [Status] Needs Review, Sites Management Dashboard

#65043 Editing Toolkit Plugin: Prevent phpcbf errors from stopping sync process
  apps/editing-toolkit/bin/sync-newspack-blocks.sh
Labels: [Status] Needs Review, Editing Toolkit

#65286 Enable generated design picker when intent = write
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx
Labels: [Status] Needs Review

#65180 Update/remove unused code for old comparison page and cleanup paths
  client/components/gsuite/docs/example.tsx
  client/components/gsuite/docs/new-user-list.tsx
  client/components/gsuite/gsuite-new-user-list/domains-select.tsx
  client/components/gsuite/gsuite-new-user-list/index.tsx
  client/components/gsuite/gsuite-new-user-list/new-user.tsx
  client/components/gsuite/gsuite-new-user-list/style.scss
  client/devdocs/design/index.jsx
  client/my-sites/domains/email-providers-upsell/index.tsx
  client/my-sites/email/controller.js
  client/my-sites/email/email-management/email-home.tsx
  client/my-sites/email/email-providers-comparison/email-provider-card.jsx
  client/my-sites/email/email-providers-comparison/index.jsx
  client/my-sites/email/email-providers-comparison/stacked/email-provider-stacked-card/email-provider-stacked-features.tsx
  client/my-sites/email/email-providers-comparison/stacked/email-provider-stacked-card/index.tsx
  client/my-sites/email/email-providers-comparison/stacked/email-provider-stacked-card/style.scss
  client/my-sites/email/email-providers-comparison/stacked/index.tsx
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/email-upsell-navigation.scss
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/email-upsell-navigation.tsx
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/get-on-submit-new-mailboxes-handler.ts
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/get-upsell-props.ts
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/google-workspace-card.scss
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/google-workspace-card.tsx
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/professional-email-card.scss
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/professional-email-card.tsx
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/provider-card-props.ts
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/selectors/get-product-by-provider-and-interval.ts
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/utils.tsx
  client/my-sites/email/email-providers-comparison/stacked/style.scss
  client/my-sites/email/email-providers-comparison/style.scss
  client/my-sites/email/form/mailboxes/components/new-mailbox-list/style.scss
  client/my-sites/email/titan-new-mailbox-list/index.jsx
  client/my-sites/email/titan-new-mailbox-list/style.scss
  client/my-sites/email/titan-new-mailbox/index.jsx
  client/my-sites/email/titan-new-mailbox/style.scss
Labels: [Status] Needs Review, Email form unification

#65203 Fix issue with not working autocomplete for Posts Carousel block
  apps/editing-toolkit/editing-toolkit-plugin/newspack-blocks/index.php
Labels: [Status] Needs Review

#65326 Fix - Issue 65324 - JITM modal style is broken on mobile
  client/blocks/jitm/templates/modal-style.scss
Labels: [Status] Needs Review

#64289 Plans overhaul: Add-ons page/route in my-sites
  client/my-sites/add-ons/components/add-ons-card.tsx
  client/my-sites/add-ons/components/add-ons-grid.tsx
  client/my-sites/add-ons/controller.tsx
  client/my-sites/add-ons/hooks/use-add-on-display-cost.ts
  client/my-sites/add-ons/hooks/use-add-on-feature-slugs.ts
  client/my-sites/add-ons/hooks/use-add-on-purchase-status.ts
  client/my-sites/add-ons/hooks/use-add-ons.ts
  client/my-sites/add-ons/icons/custom-design.tsx
  client/my-sites/add-ons/icons/no-ads.tsx
  client/my-sites/add-ons/icons/unlimited-themes.tsx
  client/my-sites/add-ons/index.ts
  client/my-sites/add-ons/main.tsx
  client/my-sites/sidebar/static-data/fallback-menu.js
  client/my-sites/sidebar/use-site-menu-items.js
  client/sections.js
  client/state/products-list/selectors/get-product-currency-code.ts
  client/state/products-list/selectors/get-product-description.ts
  client/state/products-list/selectors/get-product-term.ts
  client/state/products-list/selectors/get-products-list.ts
  client/state/products-list/selectors/index.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  package.json
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/constants/wpcom.ts
  yarn.lock
Labels: [Status] In Progress, [Status] Needs Review, [Status] String Freeze, Plans Overhaul

#64451 Add-on: Signup flow, implement step on Free sites to sell add-ons
  client/lib/signup/step-actions/index.js
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
  client/signup/config/steps.js
  client/signup/steps/add-ons/index.tsx
  client/signup/steps/add-ons/styles.scss
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Status] String Freeze, Plans Overhaul

#65342 Welcome Tour: ensure 'welcomeGuide' feature is toggled off
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/disable-core-nux.js
Labels: [Status] Needs Review, Welcome Tour

#65294 Allow plugin slugs and store slugs to diverge
  packages/calypso-products/src/has-marketplace-product.ts
  packages/calypso-products/test/has-marketplace-product.js
Labels: Marketplace, Marketplace Scaling Product Addition

#65319 Add a progressbar to /marketplace/thank-you/<product-slug>
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
  client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx
  client/my-sites/marketplace/pages/marketplace-plugin-install/use-marketplace-additional-steps.tsx
Labels: [Status] Needs Review

#65376 Revert "Signup: enable add-on flow on wpcalypso"
  config/wpcalypso.json
Labels: [Status] Needs Review

#65372 WoA: Stop recommending default static file 404
  client/my-sites/hosting/web-server-settings-card/index.js
Labels: [Status] Needs Review

#65368 Seller Experience: Removes info button until further notice
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx
Labels: [Status] Needs Review, Seller Experience

#65315 Fix the display of the new Custom CSS and Premium Themes add-ons in checkout
  packages/calypso-products/src/is-add-on.ts
Labels: [Status] Needs Review

#65275 Checkout: Add ":receiptId" placeholder replacement to CheckoutPending
  client/my-sites/checkout/checkout-thank-you/pending.tsx
Labels: [Status] Needs Review

#65397 CI: upgrade Playwright to 1.23
  desktop/package.json
  packages/calypso-e2e/package.json
  test/e2e/package.json
  yarn.lock
Labels: [Status] Needs Review

#65276 Forms: Hide Microsoft Edge password reveal toggle
  client/components/forms/form-password-input/style.scss
Labels: [Status] Needs Review, Login, [Status] Design Input Requested

#65298 Goals Capture: Update `goalsToIntent` logic for Goals Capture i2 screen
  packages/data-stores/src/onboard/test/utils.ts
  packages/data-stores/src/onboard/utils.ts
Labels: [Status] Needs Review

#65399 Enable all FTM flows for all languages
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/index.tsx
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  client/signup/steps/choose-service/index.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#65379 Mailbox forms: Switch to using individual useState() hooks for <MailboxesForm/>
  client/my-sites/email/add-mailboxes/index.tsx
Labels: [Status] Needs Review

#65332 WP Toolbar location changed from settings/writing to settings/general section (#16631).
  client/my-sites/site-settings/form-general.jsx
  client/my-sites/site-settings/form-writing.jsx
  client/my-sites/site-settings/test/form-general.jsx
Labels: [Type] Enhancement, Site Settings, [Status] Ready to Merge, OSS Citizen

#65317 CDN Upsell Nudge: Take the user directly to the Pro checkout
  client/my-sites/site-settings/cloudflare.js
Labels: [Type] Bug, [Status] Needs Review, Build Maintenance

#65388 Site Switcher: Track "Switch Site" and "All My Sites" click
  client/components/site-selector/index.jsx
  client/my-sites/current-site/index.jsx
Labels: [Status] Needs Review, Sites Management Dashboard

#65284 Conditionally hide sharing section from JP cloud
  client/my-sites/marketing/connections/service-example.jsx
  client/my-sites/marketing/connections/service-examples.jsx
  client/my-sites/marketing/connections/service-tip.jsx
  client/my-sites/marketing/style.scss
Labels: Jetpack, [Status] Needs Review, Publicize, Jetpack Cloud

#65408 Marketing Connections: Display tips for WPCOM Simple
  client/my-sites/marketing/connections/service-examples.jsx
  client/my-sites/marketing/connections/service-tip.jsx
Labels: [Status] Needs Review, Publicize

#65406 Add-ons: Signup - fix bug with missing cart items in step submission
  client/signup/steps/add-ons/index.tsx
Labels: [Status] Needs Review

#65343 Plans Overhaul: AB test add-ons step in signup
  client/signup/config/flows-pure.js
  client/signup/controller.js
  config/_shared.json
Labels: [Status] Needs Review, Plans Overhaul

#64464 social-previews: Declare missing peer dependency on `@babel/runtime`
  packages/social-previews/CHANGELOG.md
  packages/social-previews/package.json
  yarn.lock
Labels: [Status] Needs Review

#65359 Sites Dashboard: Indicate launch status with labels
  client/sites-dashboard/components/sites-launch-status-badge.tsx
  client/sites-dashboard/components/sites-p2-badge.tsx
  client/sites-dashboard/components/sites-table-row.tsx
Labels: [Status] Needs Review, [Type] Task, Sites Management Dashboard

#65320 Design Picker: Enable the flag to release the design updates
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Design Picker

#65309 Sites Management Dashboard: Create resuseable ListTile component
  client/devdocs/design/index.jsx
  client/sites-dashboard/components/sites-table-row.tsx
  packages/components/src/index.js
  packages/components/src/list-tile/README.md
  packages/components/src/list-tile/docs/example.jsx
  packages/components/src/list-tile/index.tsx
  packages/components/src/list-tile/style.scss
Labels: [Status] Needs Review, [Type] Task, Sites Management Dashboard

#65391 Showing new plans to legacy Personal and Premium
  client/my-sites/plans-comparison/plans-comparison-action.tsx
  client/my-sites/plans/main.jsx
  test/e2e/specs/plans/plans__legacy-renew.ts
Labels: [Status] Needs Review, Plans Overhaul

#65155 Generated design picker: Add translation to buttons
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#65106 Signup: Add more messages on the processing screen
  client/signup/reskinned-processing-screen/index.jsx
Labels: [Status] Needs Review, [Status] String Freeze

#64696 Import: update import flow tracking
  client/blocks/import/capture/index.tsx
  client/blocks/import/list/index.tsx
  client/blocks/import/ready/index.tsx
  client/blocks/importer/blogger/index.tsx
  client/blocks/importer/components/complete-screen/index.tsx
  client/blocks/importer/components/error-message/index.tsx
  client/blocks/importer/components/importing-pane/importing-pane.tsx
  client/blocks/importer/medium/index.tsx
  client/blocks/importer/squarespace/index.tsx
  client/blocks/importer/wix/index.tsx
  client/blocks/importer/wordpress/content-chooser/index.tsx
  client/blocks/importer/wordpress/import-everything/confirm-upgrade-plan.tsx
  client/blocks/importer/wordpress/import-everything/confirm.tsx
  client/blocks/importer/wordpress/import-everything/index.tsx
  client/blocks/importer/wordpress/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import-ready/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-medium/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-wordpress/index.tsx
  client/landing/stepper/declarative-flow/internals/types.ts
  client/my-sites/importer/author-mapping-pane.jsx
  client/my-sites/migrate/section-migrate.jsx
Labels: [Status] Needs Review

#65403 Poll plugin installation less often after purchasing a premium plugin
  client/state/admin-menu/actions/index.js
Labels: [Status] Needs Review

#65370 Prevent Media Library Item from appearing in wrong day
  client/my-sites/media-library/list.jsx
Labels: [Status] Needs Review

#64981 Update/whats new styling
  packages/whats-new/package.json
  packages/whats-new/src/components/guide.tsx
  packages/whats-new/src/index.js
  packages/whats-new/src/index.tsx
  packages/whats-new/src/style.scss
  packages/whats-new/src/whats-new-page.tsx
  packages/whats-new/types.d.ts
  yarn.lock
Labels: [Status] Needs Review, Help Center

#65161 Google Sign-in: enable migration feature flag on every environment
  client/components/social-buttons/google.js
  config/development.json
  config/horizon.json
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#65441 Remove `marketplace-starter-plan` feature flag
  client/blocks/eligibility-warnings/hold-list.tsx
  client/lib/plugins/utils.js
  client/my-sites/plugins/plugin-details-CTA/usps.tsx
  client/my-sites/plugins/plugins-browser/index.jsx
  client/state/purchases/selectors/will-atomic-site-revert-after-purchase-deactivation.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Marketplace, Limited Atomic

#64780 Onboarding: Add DIFM landing page
  client/assets/images/difm/site1.jpg
  client/assets/images/difm/site2.jpg
  client/assets/images/difm/site3.jpg
  client/assets/images/difm/site4.jpg
  client/assets/images/difm/site5.jpg
  client/landing/stepper/declarative-flow/internals/steps-repository/difm-starting-point/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/difm-starting-point/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  client/lib/signup/step-actions/index.js
  client/my-sites/marketing/do-it-for-me/difm-landing.tsx
  client/my-sites/marketing/do-it-for-me/site-build-showcase.tsx
  client/signup/config/flows-pure.js
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
  client/signup/steps/choose-service/index.tsx
  client/signup/steps/choose-service/style.scss
  client/signup/steps/choose-service/types.ts
Labels: [Status] Needs Review, DIFM Lite

#65443 Sites Dashboard: Persist launch status state in URLs
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/components/sites-table-filter-tabs.tsx
  client/sites-dashboard/controller.tsx
Labels: [Status] Needs Review, [Type] Task, Sites Management Dashboard

#63634 Add Sentry error logging to checkout decider error boundary
  client/my-sites/checkout/checkout-system-decider.js
Labels: [Status] Needs Review

#65473 [TeamCity] Fix: pass the right GB version to the --url-prefix param for the GB source-maps build
  .teamcity/_self/projects/WPComPlugins.kt
Labels: [Status] Needs Review

#65431 Vertical step: Disable synonym search for non-Engligh locale
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/index.tsx
Labels: [Status] Needs Review

#65433 Enable include_weighted_roots in query get_verticals
  client/data/site-verticals/use-site-verticals-query.ts
Labels: [Status] Needs Review

#64987 Theme showcase: Update theme support forums link
  client/my-sites/theme/main.jsx
  client/state/themes/selectors/get-theme-forum-url.js
  client/state/themes/test/selectors.js
Labels: [Status] Needs Review, Theme Showcase

#65470 Sidebar: Hide external link icon when collapsed
  client/layout/sidebar/item.jsx
Labels: [Type] Bug, [Status] Needs Review, Build Maintenance

#65484 Jetpack Agency Dashboard: fix site column heading misalignment
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-table/style.scss
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#65434 HelpCenter: add back to top button for articles
  packages/help-center/src/components/back-to-top-button.scss
  packages/help-center/src/components/back-to-top-button.tsx
  packages/help-center/src/components/help-center-embed-result.tsx
  packages/help-center/src/components/help-center-search.scss
Labels: [Status] Needs Review, Help Center

#65265 Add/agency marketing to jetpack connect
  client/components/jetpack/intro-pricing-banner/index.tsx
  client/components/jetpack/intro-pricing-banner/people.svg
  client/components/jetpack/intro-pricing-banner/style.scss
  client/my-sites/plans/jetpack-plans/constants.ts
  client/my-sites/plans/jetpack-plans/more-info-box/index.tsx
  client/my-sites/plans/jetpack-plans/more-info-box/style.scss
  client/my-sites/plans/jetpack-plans/product-grid/index.tsx
  client/my-sites/plans/jetpack-plans/product-grid/style.scss
Labels: [Status] Needs Review

#65377 Stepper: Allow data to be passed from navigate() to the next step component
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/types.ts
Labels: [Status] Needs Review, Stepper

#65396 calypso-e2e: wait for response from `plans` endpoint to complete in mobile viewport.
  packages/calypso-e2e/src/lib/pages/plans-page.ts
  test/e2e/specs/plans/plans__legacy-renew.ts
Labels: [Status] Needs Review

#65325 E2E: add spec to cover Login with Google.
  Dockerfile.base
  packages/calypso-e2e/package.json
  packages/calypso-e2e/src/env-variables.ts
  packages/calypso-e2e/src/jest-playwright-config/environment.ts
  packages/calypso-e2e/src/jest-playwright-config/playwright-config.ts
  packages/calypso-e2e/src/lib/pages/google-login-page.ts
  packages/calypso-e2e/src/lib/pages/index.ts
  packages/calypso-e2e/src/lib/pages/login-page.ts
  packages/calypso-e2e/src/secrets/encrypted.enc
  packages/calypso-e2e/src/secrets/secrets-manager.ts
  packages/calypso-e2e/src/types/env-variables.types.ts
  test/e2e/.eslintrc.js
  test/e2e/specs/authentication/authentication__google.ts
  yarn.lock
Labels: [Status] Needs Review

#65507 Themes: Convert themes-header.jsx to TypeScript
  client/my-sites/themes/themes-header.tsx
Labels: [Status] In Progress, [Status] Needs Review

#65329 HelpCenter: upgrade all endpoints to proxy through Jetpack
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/help-center/class-help-center.php
  apps/editing-toolkit/editing-toolkit-plugin/help-center/class-wp-rest-help-center-fetch-post.php
  apps/editing-toolkit/editing-toolkit-plugin/help-center/class-wp-rest-help-center-search.php
  apps/editing-toolkit/editing-toolkit-plugin/help-center/class-wp-rest-help-center-support-availability.php
  apps/editing-toolkit/tsconfig.json
  client/components/data/query-reader-post/index.jsx
  client/layout/index.jsx
  client/layout/masterbar/logged-in.jsx
  client/state/reader/posts/actions.js
  client/state/sites/selectors/is-simple-site.ts
  packages/data-stores/src/index.ts
  packages/data-stores/src/support-queries/types.ts
  packages/data-stores/src/support-queries/use-support-availability.ts
  packages/help-center/src/components/help-center-article-content.scss
  packages/help-center/src/components/help-center-article-content.tsx
  packages/help-center/src/components/help-center-article-fetching-content.tsx
  packages/help-center/src/components/help-center-container.tsx
  packages/help-center/src/components/help-center-embed-result.tsx
  packages/help-center/src/components/help-center-header.tsx
  packages/help-center/src/components/help-center-search-results.tsx
  packages/help-center/src/components/help-center-search.scss
  packages/help-center/src/components/help-center-search.tsx
  packages/help-center/src/components/help-center.tsx
  packages/help-center/src/components/index.d.ts
  packages/help-center/src/components/placeholder-lines.scss
  packages/help-center/src/components/placeholder-lines.tsx
  packages/help-center/src/hooks/use-help-search-query.ts
  packages/help-center/src/hooks/use-should-render-chat-option.tsx
  packages/help-center/src/hooks/use-should-render-email-option.tsx
  packages/help-center/src/hooks/use-still-need-help-url.tsx
  packages/help-center/src/styles.scss
Labels: [Status] Needs Review, Help Center

#65549 Google Sign-In Migration: namespace auth code exchange failure event correctly
  client/components/social-buttons/google.js
Labels: [Status] Needs Review, Social Signup, Google Auth

#65274 Marketplace: Add back 2fa branding
  client/blocks/login/index.jsx
  client/lib/paths/login/index.js
  client/state/login/utils.js
Labels: [Status] Needs Review

#65537 Design Picker: Hide description & badge in DIFM flow
  client/signup/config/steps-pure.js
  client/signup/steps/design-picker/index.jsx
  packages/design-picker/src/components/index.tsx
Labels: [Status] Needs Review, DIFM Lite

#65485 Support header_pattern_ids and footer_pattern_ids from the recipe
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx
  packages/data-stores/src/site/actions.ts
  packages/design-picker/src/types.ts
  packages/design-picker/src/utils/__tests__/designs.test.ts
  packages/design-picker/src/utils/designs.ts
Labels: [Status] Needs Review

#65533 Fix/help center warnings
  packages/help-center/src/icons/mail.tsx
Labels: [Status] Needs Review, Help Center

#65126 WIP: Add Monthly to Plans Grid
  client/my-sites/plan-features-comparison/style.scss
  client/my-sites/plans-comparison/plans-comparison-action.tsx
  client/my-sites/plans-comparison/plans-comparison-row.tsx
  client/my-sites/plans-comparison/plans-comparison.tsx
  client/my-sites/plans-comparison/use-plan-prices.tsx
  client/my-sites/plans-comparison/use-plans.tsx
  client/my-sites/plans-features-main/plan-type-selector.tsx
  client/my-sites/plans/main.jsx
  client/signup/steps/plans/index.jsx
  packages/calypso-products/src/constants/wpcom.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/types.ts
  packages/calypso-products/test/plan-lookups.js
Labels: [Status] Needs Review

#65564 Change Wix input title
  client/lib/importer/importer-config.tsx
Labels: [Status] Needs Review

#65517 Refactor date-picker button tests to use @testing-library/react
  client/my-sites/backup/backup-date-picker/test/date-button.jsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Domains

#65578 Import: fix event tracking bug on import-everything screen
  client/blocks/importer/wordpress/import-everything/index.tsx
Labels: [Status] Needs Review

#65188 Plans Step: fix design alignment issues
  client/my-sites/plans-comparison/plans-comparison-col-cta.tsx
  client/my-sites/plans-comparison/plans-comparison-col-header.tsx
  client/my-sites/plans-comparison/plans-comparison.tsx
Labels: [Status] Needs Review, Plans Overhaul

#65494 Plugins on starter: adds the announcement modal in customer home.
  client/assets/images/marketplace/plugins-browser.svg
  client/blocks/announcement-modal/index.jsx
  client/blocks/announcement-modal/style.scss
  client/my-sites/customer-home/main.jsx
  client/my-sites/plugins/plugins-announcement-modal/index.jsx
  client/my-sites/plugins/plugins-browser/index.jsx
Labels: [Status] Needs Review

#65505 Sites Management Dashboard: add search mechanism
  client/components/search-sites/index.js
  client/components/search-sites/utils.ts
  client/sites-dashboard/components/searchable-sites-table.tsx
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/components/sites-search-icon.tsx
  client/sites-dashboard/components/sites-search.ts
  client/sites-dashboard/components/sites-table-filter-tabs.tsx
Labels: [Status] Needs Review, Sites Management Dashboard

#64204 Stepper: Add check in the site-setup flow for site owner
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  client/landing/stepper/hooks/use-user-can-manage-options.ts
Labels: [Status] Needs Review, Stepper

#65573 Recommend PHP 8.0 for WoA sites
  client/my-sites/hosting/web-server-settings-card/index.js
Labels: [Status] Needs Review

#65266 ETK Timeline Block: Use enableAlpha=true to allow 'transparent' as an available `background` color
  apps/editing-toolkit/editing-toolkit-plugin/jetpack-timeline/blocks/src/timeline-item.js
Labels: [Status] Needs Review, [Block] Timeline, Build Maintenance

#65607 Redirect global styles doc link to WP.com
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-documentation-links/src/index.tsx
Labels: [Status] Needs Review, Welcome Tour

#65618 Checkout: Get correct shopping cart for creating Google/Apple Pay payment request
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-methods/index.ts
  packages/wpcom-checkout/src/payment-methods/apple-pay.tsx
  packages/wpcom-checkout/src/payment-methods/google-pay.tsx
  packages/wpcom-checkout/src/payment-methods/web-pay-utils.tsx
Labels: [Status] Needs Review

#65615 E2E: update `defaultUser` in the secrets file.
  packages/calypso-e2e/src/secrets/encrypted.enc
  test/e2e/specs/onboarding/setup__importer.ts
  test/e2e/specs/onboarding/start__importer.ts
Labels: [Status] Needs Review

#65467 Sites Management Dashboard: Add design for empty states
  client/sites-dashboard/components/searchable-sites-table.tsx
  client/sites-dashboard/components/sites-container.tsx
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/components/sites-table-filter-tabs.tsx
Labels: [Status] Needs Review, Sites Management Dashboard

#65628 Repo gardening: add new task to gather all ticket references
  .github/workflows/gardening.yml
Labels: [Type] Enhancement, [Pri] Normal, [Status] Needs Review

#65632 Improve "Installed plugins" navigation
  client/my-sites/plugins/main.jsx
  client/my-sites/plugins/plugins-browser/index.jsx
Labels: [Status] Needs Review, Plugins, Limited Atomic

#65617 HelpCenter: fix api endpoint permission
  apps/editing-toolkit/editing-toolkit-plugin/help-center/class-wp-rest-help-center-fetch-post.php
  apps/editing-toolkit/editing-toolkit-plugin/help-center/class-wp-rest-help-center-search.php
Labels: [Status] Needs Review, Help Center

#65253 Help Center: Publish in all locales
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/help-center/src/CalypsoStateProvider.js
  apps/editing-toolkit/editing-toolkit-plugin/help-center/src/help-center.js
  client/blocks/inline-help/admin-sections.js
  client/layout/masterbar/logged-in.jsx
  packages/data-stores/src/contextual-help/admin-sections.ts
  packages/data-stores/src/index.ts
  packages/help-center/src/components/help-center-contact-form.tsx
  packages/help-center/src/components/help-center-contact-page.tsx
  packages/help-center/src/components/help-center-more-resources.tsx
  packages/help-center/src/components/help-center-search-results.tsx
  packages/help-center/src/components/help-center-search.tsx
  packages/help-center/src/components/help-center-sibyl-articles.tsx
  packages/help-center/src/hooks/use-help-search-query.ts
Labels: [Status] Needs Review, Help Center

#65577 Site Editor: Back to dashboard button in Calypso always redirects to my home
  client/state/route/last-non-editor-route/reducer.js
Labels: [Type] Bug, [Status] Needs Review, [Goal] Full Site Editing

#65509 Checkout: Add immediate redirect on pre-filled receipt ID to pending page
  client/my-sites/checkout/checkout-thank-you/header.jsx
  client/my-sites/checkout/checkout-thank-you/pending.tsx
  client/my-sites/checkout/composite-checkout/lib/pending-page.ts
  client/my-sites/checkout/composite-checkout/test/generic-redirect-processor.ts
  client/my-sites/checkout/composite-checkout/test/pending-page.ts
  client/my-sites/checkout/controller.jsx
Labels: [Status] Needs Review

#65643 Sites Dashboard: Fix warnings for `SitesSearchIcon`
  client/sites-dashboard/components/sites-search-icon.tsx
Labels: [Type] Bug, [Status] Needs Review, Sites Management Dashboard

#65646 Checkout: Allow getThankYouPageUrl to return upsells when an order is present
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.ts
Labels: [Status] Needs Review

#64497 Fix/home edit site button link update theme switch
  client/data/themes/use-active-theme-query.ts
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
Labels: [Status] Needs Review

#65647 Shopping Cart: Make the cartKey arg to useShoppingCart required
  packages/shopping-cart/src/use-shopping-cart.ts
  packages/shopping-cart/test/use-shopping-cart.tsx
Labels: [Status] Needs Review

#65626 Remove unnecessary translation check in Gravatar settings
  client/me/profile/updated-gravatar-string.js
Labels: [Status] Needs Review, [Type] Janitorial

#65531 Design Picker: Verticalize standard themes
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/generated-design-picker-web-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
  packages/data-stores/package.json
  packages/data-stores/src/site/actions.ts
  packages/data-stores/src/site/test/actions.ts
  packages/data-stores/src/site/test/reducer.ts
  packages/data-stores/src/site/test/selectors.ts
  packages/design-picker/src/components/generated-design-picker.tsx
  packages/design-picker/src/components/index.tsx
  packages/design-picker/src/types.ts
  packages/design-picker/src/utils/__tests__/designs.test.ts
  packages/design-picker/src/utils/designs.ts
  yarn.lock
Labels: [Status] Needs Review
