Repository Automattic/wp-calypso, pull requests merged in 2022-02, with the labels that each got.

#60609 Signup: Fix branching steps if the user comes back from PayPal
  client/lib/signup/flow-controller.ts
  client/signup/hooks/use-branch-steps.ts
  client/signup/steps/intent/index.tsx
  client/signup/steps/starting-point/index.tsx
  client/signup/types.ts
  client/state/action-types.ts
  client/state/signup/flow/actions.js
  client/state/signup/flow/reducer.js
  client/state/signup/flow/selectors.js
  client/state/signup/progress/schema.ts
Labels: [Status] Needs Review, Blogger Experience Pod

#58981 Experiment : Plans: Add billed as wording on mobile
  client/my-sites/plan-features/header.jsx
  client/my-sites/plan-features/index.jsx
  client/my-sites/plan-features/style.scss
  client/my-sites/plan-price/style.scss
  client/my-sites/plans-features-main/index.jsx
  client/signup/controller.js
  client/signup/steps/plans/index.jsx
  client/signup/steps/plans/style.scss
Labels: Plans, [Status] Needs Review, Mobile Web

#60526 WPCOM Block Editor: Send save click tracks event with more data
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-save-click.js
Labels: Editor, [Status] Needs Review, [Goal] Full Site Editing

#60184 Bring back crossed out UI to show the first-year discount.
  client/my-sites/plan-features/header.jsx
  client/my-sites/plan-features/style.scss
  client/my-sites/plan-features/test/header.jsx
Labels: Plans, [Status] Needs Review

#60669 `QueryConciergeAppointmentDetails`: refactor away from `UNSAFE_*`
  client/components/data/query-concierge-appointment-details/index.js
Labels: [Status] Needs Review, Data, Concierge

#60670 `QueryReaderTagImages`: refactor away from `UNSAFE_*`
  client/components/data/query-reader-tag-images/index.jsx
Labels: [Status] Needs Review, Reader, Data

#60625 Welcome Tour: Remove check for translation used in 59488
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-steps.js
Labels: [Status] Needs Review, i18n, Welcome Tour

#60673 Emails: Fix display issues cropping up when stylesheets are loaded in a specific order
  client/my-sites/email/email-management/style.scss
Labels: [Type] Bug, [Status] Needs Review, G Suite, Professional Email

#60663 Components: Refactor `WebPreview` away from `UNSAFE_` lifecycle methods
  client/components/web-preview/component.jsx
  client/components/web-preview/content.jsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Components

#60126 Stats: Cleanup unused Cloudflare banner
  client/my-sites/stats/cloudflare.js
Labels: Stats, [Status] Needs Review, [Type] Janitorial

#60688 Update the grid columns from 12 to 3 at Plugin Details page.
  client/my-sites/plugins/style.scss
Labels: Marketplace

#59360 Update the plugin install direct access screen to allow the user to continue the plugin installation.
  client/data/marketplace/use-wpcom-plugins-query.ts
  client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx
  client/my-sites/marketplace/pages/marketplace-plugin-install/style.scss
  client/my-sites/plugins/plugin-details.jsx
Labels: [Status] Needs Review

#60689 Seller experience: Replace Woo logo for a svg version
  client/assets/images/onboarding/woo-commerce.svg
  client/assets/images/onboarding/woo.png
  client/signup/steps/store-features/index.tsx
Labels: [Status] Needs Review, Seller Experience

#60640 Change wordings and a bit of style for p2 creation
  client/signup/p2-processing-screen/index.jsx
  client/signup/p2-step-wrapper/index.jsx
  client/signup/steps/p2-site/index.jsx
  client/signup/steps/p2-site/style.scss
Labels: [Status] Ready to Merge

#60600 CI: add new project for MarTech/Legal.
  .teamcity/_self/projects/MarTech.kt
Labels: [Pri] High, [Status] Needs Review

#60311 Adjust styling of product cancelation buttons
  client/me/memberships/subscription.jsx
  client/me/memberships/subscription.scss
  client/me/purchases/manage-purchase/index.jsx
  client/me/purchases/remove-purchase/index.jsx
  client/me/purchases/remove-purchase/style.scss
Labels: [Type] Bug, [Status] Needs Review

#60633 Domains: Update free domain with annual plan nudge flow
  client/my-sites/plan-features/index.jsx
  client/my-sites/plan-features/plan-features-action-wrapper.jsx
  client/my-sites/plans-features-main/index.jsx
  client/my-sites/plans/controller.jsx
Labels: [Status] Needs Review, Domains

#60721 CI: Register `MarTech` as a subproject.
  .teamcity/settings.kts
Labels: [Status] Needs Review

#60722 Unmask Jetpack Pricing Page in FullStory
  client/my-sites/plans/jetpack-plans/selector.tsx
Labels: [Status] Ready to Merge, [Size] XS

#60645 Gutenboarding: add Livro theme to design picker
  packages/design-picker/src/available-designs-config.json
Labels: [Status] Needs Review, [Goal] Full Site Editing, [Goal] New Onboarding

#60653 Design Picker: Tidy up unit test warnings
  packages/design-picker/src/__tests__/integration.test.tsx
  packages/design-picker/src/components/index.tsx
Labels: [Status] Needs Review, [Type] Janitorial

#60737 Try/help happychat calypso app setup
  .teamcity/_self/projects/WPComPlugins.kt
  apps/happychat/package.json
  apps/inline-help/package.json
  packages/calypso-apps-builder/index.js
  yarn.lock
Labels: [Status] Needs Review

#60560 Woo installer: Add site and error info to snag error tracking
  client/signup/steps/woocommerce-install/transfer/index.tsx
  client/signup/steps/woocommerce-install/transfer/install-plugins.tsx
  client/signup/steps/woocommerce-install/transfer/transfer-site.tsx
Labels: [Status] Needs Review, Woop

#60603 Fix auto-renew dialog max-width styles
  client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-disabling-dialog/style.scss
  client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-payment-method-dialog/style.scss
Labels: [Status] Needs Review

#60740 Fix calypso apps TeamCity build
  .teamcity/_self/lib/wpcom/WPComPluginBuild.kt
  .teamcity/_self/projects/WPComPlugins.kt
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/class-full-site-editing.php
  apps/happychat/README.md
  apps/inline-help/README.md
  apps/inline-help/package.json
  apps/inline-help/webpack.config.js
  yarn.lock
Labels: [Status] Needs Review

#60697 Woo landing page design iterations
  client/components/empty-content/README.md
  client/components/empty-content/index.jsx
  client/my-sites/woocommerce/style.scss
  client/my-sites/woocommerce/woop/landing-page.tsx
  client/my-sites/woocommerce/woop/style.scss
Labels: [Status] Ready to Merge

#60745 Avoid posting PR comments for happychat and inline-help
  .teamcity/_self/lib/wpcom/WPComPluginBuild.kt
  .teamcity/_self/projects/WPComPlugins.kt
Labels: [Status] Needs Review

#60656 Add margin after my-sites' heading when there are no primary cards
  client/my-sites/customer-home/style.scss
Labels: [Status] Needs Review

#60749 Uploading plugins fails on Atomic Sites
  packages/calypso-products/src/has-marketplace-product.ts
Labels: [Status] Needs Review, Marketplace

#60545 Signup: Track the user upgrades plan in Hero Flow
  client/lib/analytics/signup.js
  client/signup/main.jsx
  client/signup/steps/design-picker/index.jsx
  client/state/sites/selectors/get-site-plan-name.js
  client/state/sites/selectors/index.js
Labels: [Status] Needs Review, Blogger Experience Pod

#60531 Signup: Turn on checkout flow in Design Picker
  config/horizon.json
  config/production.json
  config/stage.json
Labels: [Status] Needs Review, Blogger Experience Pod

#60701 Fix | Jetpack "Backup in Progress" screen flashes another screen before it
  client/my-sites/backup/status/index.jsx
  client/state/rewind/backups/reducer.js
  client/state/rewind/backups/test/reducer.js
  client/state/rewind/selectors/is-rewind-backups-initialized.ts
  client/state/selectors/get-rewind-backups.js
  client/state/selectors/test/get-last-good-rewind-backup.js
  client/state/selectors/test/get-rewind-backups.js
Labels: [Type] Bug, [Status] Needs Review

#60674 Update domain only flow: `loader` message
  client/signup/reskinned-processing-screen/index.jsx
Labels: Domains

#60662 Correctly format currency in new domain-only search
  client/components/domains/domain-registration-suggestion/index.jsx
Labels: [Status] Needs Review, Domains

#60712 Query product list even when a jetpack self hosted site is selected.
  client/my-sites/plugins/plugins-browser/index.jsx
Labels: Marketplace

#60501 Framework: Remove keyboard shortcuts
  client/blocks/inline-help/index.jsx
  client/blocks/reader-full-post/index.jsx
  client/boot/common.js
  client/layout/index.jsx
  client/lib/keyboard-shortcuts/README.md
  client/lib/keyboard-shortcuts/global.js
  client/lib/keyboard-shortcuts/index.js
  client/lib/keyboard-shortcuts/key-bindings.js
  client/lib/keyboard-shortcuts/menu.jsx
  client/lib/keyboard-shortcuts/menu.scss
  client/lib/keyboard-shortcuts/test/index.js
  client/post-editor/editor-revisions-list/index.jsx
  client/reader/stream/index.jsx
  client/state/lib/middleware.js
  client/state/reader-ui/reducer.js
  client/state/reader/action-types.js
  client/state/reader/streams/actions.js
  client/state/reader/streams/reducer.js
  client/state/reader/streams/selectors/get-reader-stream-next-item.js
  client/state/reader/streams/selectors/get-reader-stream-offset-item.js
  client/state/reader/streams/selectors/get-reader-stream-prev-item.js
  client/state/reader/streams/selectors/index.js
  client/state/reader/streams/test/reducer.js
  client/state/selectors/get-reader-current-stream.js
  client/state/selectors/test/get-reader-stream-offset-item.js
  client/support/support-user/index.jsx
  config/development.json
  config/horizon.json
  config/test.json
  config/wpcalypso.json
Labels: Framework, [Status] Needs Review, Reader, [Type] Janitorial, Help

#60295 Editor: Remove unused `ResumeEditing` component and last draft state
  client/layout/masterbar/logged-in.jsx
  client/my-sites/resume-editing/index.jsx
  client/my-sites/resume-editing/style.scss
  client/state/action-types.ts
  client/state/editor/last-draft/actions.js
  client/state/editor/last-draft/reducer.js
  client/state/editor/last-draft/selectors.js
  client/state/editor/last-draft/test/actions.js
  client/state/editor/last-draft/test/reducer.js
  client/state/editor/last-draft/test/selectors.js
  client/state/editor/reducer.js
  client/state/editor/test/reducer.js
Labels: [Type] Enhancement, Framework, Editor, [Status] Needs Review, [Type] Janitorial, State

#60729 Signup: Anchor.fm users take a different path after signup
  client/landing/gutenboarding/hooks/use-on-site-creation.ts
Labels: [Status] Needs Review, Anchor.FM

#60247 State: Cleanup unused site features cleaning and refreshing
  client/state/action-types.ts
  client/state/sites/features/actions.js
  client/state/sites/features/reducer.js
  client/state/sites/features/test/reducer.js
Labels: Sites, [Status] Needs Review, [Type] Janitorial, State

#60487 Reader: Refactor `ConversationCommentList` away from `UNSAFE_` methods
  client/blocks/conversations/list.jsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Reader

#60734 Show "Footer credit" setting on Atomic sites.
  client/my-sites/site-settings/form-general.jsx
Labels: [Status] Needs Review

#60738 Seller Experience: Update the preemptive translations.
  client/signup/translations/seller-experience.js
Labels: [Status] Needs Review, Seller Experience

#60494 Tour Kit/Welcome Tour: Mobile & Desktop classNames for Steps
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/style-tour.scss
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-steps.js
  packages/tour-kit/src/components/tour-kit-step.tsx
  packages/tour-kit/src/types.ts
Labels: [Status] Needs Review, Welcome Tour, Tour Kit

#60775 ToS acceptance screenshots: Remove /start/domain flow for blue background signup
  test/e2e/specs/specs-playwright/wp-signup__screenshot.ts
Labels: [Status] Needs Review

#60742 WooCommerce Install Landing Page Cleanup - Remove unused images
  client/assets/images/woocommerce/woop-cta-image01.jpeg
  client/assets/images/woocommerce/woop-cta-image02.jpeg
  client/assets/images/woocommerce/woop-cta-image03.jpeg
  client/assets/images/woocommerce/woop-cta-image04.jpeg
Labels: [Status] Needs Review

#60739 WooCommerce Install Landing Page - Changing Colophon Link
  client/my-sites/woocommerce/woocommerce-colophon.tsx
  client/my-sites/woocommerce/woop/landing-page.tsx
Labels: [Status] Needs Review

#60682 Fix back link on the support card for WooCommerce on plans installation flow
  client/signup/steps/woocommerce-install/components/support-card/index.tsx
Labels: [Status] Needs Review, Woop

#60711 Seller experience: Make options requirement aware of current site plan
  client/signup/steps/store-features/index.tsx
Labels: [Status] Needs Review, Seller Experience

#60777 Seller Experience - Adding tracks event for store features step in onboarding
  client/signup/steps/store-features/index.tsx
Labels: [Status] Needs Review, Seller Experience

#60755 Woo landing page: Add footer section
  client/my-sites/woocommerce/woop/landing-page.tsx
  client/my-sites/woocommerce/woop/style.scss
Labels: [Status] Needs Review

#60631 Ensure stacked comparison page is logging events correctly
  client/my-sites/email/controller.js
  client/my-sites/email/email-management/email-home.jsx
  client/my-sites/email/email-management/home-page.tsx
  client/my-sites/email/email-providers-stacked-comparison/index.tsx
  client/my-sites/email/email-providers-stacked-comparison/page.tsx
  client/my-sites/email/inbox/index.jsx
  client/my-sites/email/inbox/mailbox-selection-list/index.jsx
Labels: [Status] Needs Review

#60794 Use correct self-closing component interpolation syntax for br in FEATURE_FREE_DOMAIN
  client/lib/plans/features-list.js
Labels: [Status] Needs Review

#60761 Remove usage of Calypso components and styles from dev helpers
  client/lib/auth-helper/index.jsx
  client/lib/auth-helper/style.scss
  client/lib/features-helper/feature-list.js
  client/lib/features-helper/style.scss
  client/lib/preferences-helper/preference-list.js
  client/lib/preferences-helper/style.scss
Labels: [Status] Needs Review

#60756 Migrate requestActivityLogs to React Query
  client/components/activity-card-list/index.jsx
  client/components/data/query-rewind-capabilities/index.jsx
  client/components/jetpack/backup-card/backup-in-progress.tsx
  client/components/jetpack/backup-card/backup-just-completed.tsx
  client/components/jetpack/backup-delta/index.jsx
  client/components/jetpack/daily-backup-status/status-card/backup-in-progress.tsx
  client/components/jetpack/daily-backup-status/status-card/backup-just-completed.tsx
  client/data/activity-log/use-activity-log-query.js
  client/lib/jetpack/hooks/use-date-with-offset.ts
  client/my-sites/activity/activity-log-v2/index.tsx
  client/my-sites/activity/activity-log/index.jsx
  client/my-sites/activity/filterbar/style.scss
  client/my-sites/backup/backup-date-picker/index.tsx
  client/my-sites/backup/backup-date-picker/test/index.jsx
  client/my-sites/backup/hooks.js
  client/my-sites/backup/search-results.jsx
  client/my-sites/backup/status/hooks.js
  client/my-sites/backup/status/index.jsx
  client/my-sites/backup/status/simplified-i4.jsx
  client/signup/steps/clone-point/index.jsx
  client/state/data-getters/get-request-activity-logs-id.js
  client/state/data-getters/index.js
  client/state/data-getters/request-activity-logs.js
Labels: [Status] Needs Review, Activity Log, Jetpack Cloud, Jetpack Backup

#60762 Rename slack p2 service
  client/my-sites/marketing/connections/connection.jsx
  client/my-sites/marketing/connections/service-description.jsx
  client/my-sites/marketing/connections/service-examples.jsx
  client/my-sites/marketing/connections/services/index.js
  client/my-sites/marketing/connections/services/p2-slack.js
  static/images/sharing/p2-slack-logo.svg
Labels: [Status] Needs Review

#60766 Hide "Add existing site" option in `site-or-domain` step, if the user doesn't have any site
  client/signup/steps/site-or-domain/index.jsx
Labels: Domains

#60658 Validate if a domain is mapped before rendering the mapping setup flow
  client/components/domains/connect-domain-step/index.jsx
Labels: [Status] Needs Review, Domains

#60548 Website content UI shell and REDUX implementation
  client/signup/accordion-form/accordion-form.tsx
  client/signup/accordion-form/form-components.tsx
  client/signup/accordion-form/types.ts
  client/signup/steps/site-info-collection/index.tsx
  client/signup/steps/website-content/components.tsx
  client/signup/steps/website-content/index.tsx
  client/signup/steps/website-content/page-details.tsx
  client/signup/steps/website-content/section-generator.tsx
  client/signup/steps/website-content/style.scss
  client/signup/steps/website-content/wordpress-media-upload.tsx
  client/state/action-types.ts
  client/state/signup/steps/website-content/actions.ts
  client/state/signup/steps/website-content/reducer.ts
  client/state/signup/steps/website-content/schema.ts
  client/state/signup/steps/website-content/test/reducer.js
  client/state/signup/steps/website-content/test/schema.js
  client/state/signup/steps/website-content/test/selectors.js
Labels: [Status] Needs Review

#60681 Update/onboarding importer improvements 3
  client/signup/steps/import-from/index.tsx
  client/signup/steps/import-from/wordpress/import-everything/index.tsx
  client/signup/steps/import-from/wordpress/index.tsx
Labels: [Status] Needs Review

#60759 Add `domain-only` filter to All domains list
  client/my-sites/domains/domain-management/list/all-domains.jsx
  client/my-sites/domains/domain-management/list/helpers.ts
  client/state/ui/selectors/site-data.ts
Labels: [Status] Needs Review, Domains

#60147 Jetpack Cloud: Update price per license copy on billing page
  client/jetpack-cloud/sections/partner-portal/billing-details/index.tsx
Labels: [Status] Needs Review, Jetpack Cloud, Jetpack Licensing Portal, Jetpack Licensing

#60288 State: Cleanup unused publicize connection request state
  client/state/action-types.ts
  client/state/sharing/publicize/actions.js
  client/state/sharing/publicize/reducer.js
  client/state/sharing/publicize/selectors.js
  client/state/sharing/publicize/test/actions.js
  client/state/sharing/publicize/test/reducer.js
  client/state/sharing/publicize/test/selectors.js
Labels: [Status] Needs Review, [Type] Janitorial, State, Publicize

#60136 Framework: Refactor `CloseOnEscape` away from Lodash
  client/components/close-on-escape/index.jsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Components

#60439 Site Settings: Refactor Monitor settings to `react-query` and remove UNSAFE methods
  client/components/data/query-site-monitor-settings/README.md
  client/components/data/query-site-monitor-settings/index.jsx
  client/data/site-monitor/use-site-monitor-settings-query.js
  client/data/site-monitor/use-update-site-monitor-settings-mutation.js
  client/data/site-monitor/with-site-monitor-settings.js
  client/my-sites/site-settings/form-jetpack-monitor.jsx
  client/state/action-types.ts
  client/state/selectors/get-site-monitor-settings.js
  client/state/selectors/is-requesting-site-monitor-settings.js
  client/state/selectors/is-updating-site-monitor-settings.js
  client/state/selectors/test/get-site-monitor-settings.js
  client/state/selectors/test/is-requesting-site-monitor-settings.js
  client/state/selectors/test/is-updating-site-monitor-settings.js
  client/state/sites/monitor/actions.js
  client/state/sites/monitor/reducer.js
  client/state/sites/monitor/test/actions.js
  client/state/sites/monitor/test/reducer.js
  client/state/sites/reducer.js
  client/state/sites/test/reducer.js
Labels: [Type] Enhancement, Site Settings, Framework, [Status] Needs Review, [Type] Janitorial, State, Data

#60642 Themes showcase: remove Beta badge for FSE themes
  client/components/theme/index.jsx
  client/components/themes-list/test/__snapshots__/index.jsx.snap
  client/my-sites/theme/main.jsx
  client/my-sites/themes/current-theme/index.tsx
  client/my-sites/themes/theme-showcase.jsx
Labels: Themes, [Status] Needs Review, [Goal] Full Site Editing

#60776 Playwright: Migrate ETK Smoke Tests
  packages/calypso-e2e/.eslintrc.js
  packages/calypso-e2e/src/lib/blocks/block-flows/blog-posts.ts
  packages/calypso-e2e/src/lib/blocks/block-flows/index.ts
  packages/calypso-e2e/src/lib/blocks/block-flows/post-carousel.ts
  packages/calypso-e2e/src/lib/blocks/block-flows/timeline.ts
  packages/calypso-e2e/src/lib/blocks/schemas.ts
  test/e2e/specs/specs-playwright/shared-specs/block-testing.ts
  test/e2e/specs/specs-wpcom/wp-blocks__etk.ts
Labels: [Status] Needs Review

#60779 Jetpack pricing page: update footer
  client/jetpack-cloud/sections/pricing/jpcom-footer/assets/app-store-badge.png
  client/jetpack-cloud/sections/pricing/jpcom-footer/assets/google-play-badge.png
  client/jetpack-cloud/sections/pricing/jpcom-footer/assets/logo-a8c-white.svg
  client/jetpack-cloud/sections/pricing/jpcom-footer/index.tsx
  client/jetpack-cloud/sections/pricing/jpcom-footer/style.scss
  client/jetpack-cloud/sections/pricing/style.scss
  client/my-sites/plans/jetpack-plans/selector.tsx
Labels: [Status] Needs Review, [Size] M, Jetpack Cloud

#60813 Turn on the onboarding WordPress flow for wpcalypso env
  config/wpcalypso.json
  test/e2e/specs/specs-playwright/wp-start__importer.ts
Labels: [Status] Needs Review

#60782 Signup: Correct page title grammar.
  client/signup/config/flows-pure.js
Labels: [Status] Needs Review, Signup, Seller Experience

#60819 Memoize ImportPreview component
  client/signup/steps/import/ready/preview.tsx
Labels: [Status] Needs Review

#60730 Update Payment Method to Methods
  client/jetpack-cloud/sections/partner-portal/add-stored-credit-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/index.ts
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-add/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-list/index.tsx
  client/jetpack-cloud/sections/partner-portal/sidebar/index.tsx
Labels: [Status] Needs Review

#60368 Removing test config and implementing new mobile registration page
  client/blocks/signup-form/index.jsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-review.tsx
  client/signup/steps/user/index.jsx
Labels: [Status] Needs Review, Signup, ABTest

#60828 Reversing signup test commits
  client/blocks/signup-form/index.jsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-review.tsx
  client/signup/steps/user/index.jsx
Labels: [Status] Needs Review

#60829 Change how we push some tags.
  .teamcity/_self/projects/WebApp.kt
Labels: [Status] Needs Review

#60511 Fix/3rd party cookies disabled notice mobile
  client/components/social-buttons/google.js
Labels: [Status] Needs Review, Login, Mobile Web

#60120 Update node to 16.13.2
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/tooling_request.yml
  .github/workflows/editing-toolkit-plugin.yml
  .github/workflows/icfy-stats.yml
  .nvmrc
  Dockerfile
  Dockerfile.base
  package.json
  packages/wp-babel-makepot/Dockerfile
Labels: [Status] Needs Review

#60225 Remove jquery from wpcom block editor
  apps/wpcom-block-editor/package.json
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
  yarn.lock
Labels: [Status] Needs Review

#60833 Playwright: use correct environment variable for target viewport and fix failing tests.
  .teamcity/_self/projects/WPComTests.kt
  .teamcity/_self/projects/WebApp.kt
  packages/calypso-e2e/src/lib/blocks/block-flows/whatsapp-button.ts
  packages/calypso-e2e/src/lib/components/editor-settings-sidebar-component.ts
  packages/calypso-e2e/src/lib/pages/published/published-post-page.ts
  test/e2e/specs/specs-playwright/shared-specs/privacy-testing.ts
Labels: [Status] Needs Review

#60798 Add backUrl to SupportCard component
  client/signup/steps/woocommerce-install/components/support-card/index.tsx
  client/signup/steps/woocommerce-install/transfer/error.tsx
Labels: [Status] Needs Review

#60796 Log snag errors to logstash
  client/signup/steps/woocommerce-install/transfer/index.tsx
Labels: [Status] Needs Review

#60666 Checkout: Reset the DIFM-L refund period to 14 days
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx
Labels: [Status] Needs Review, difm-lite

#60827 Hide California notice in Jetpack footer for non Californian users
  client/jetpack-cloud/sections/pricing/jpcom-footer/index.tsx
Labels: [Status] Needs Review, Jetpack Cloud, [Size] XS

#60781 Domains: Add link to domain connection setup in domain notice
  client/lib/domains/resolve-domain-status.tsx
Labels: [Status] Needs Review, Domains

#60822 Update/onboarding importer improvements 5
  client/signup/steps/import-from/blogger/index.tsx
  client/signup/steps/import-from/medium/index.tsx
  client/signup/steps/import-from/squarespace/index.tsx
  client/signup/steps/import-from/types.ts
  client/signup/steps/import-from/wix/index.tsx
Labels: [Status] Needs Review

#60826 Add locale switcher to Jetpack pricing page
  client/jetpack-cloud/sections/pricing/jpcom-footer/index.tsx
  client/jetpack-cloud/sections/pricing/jpcom-footer/locale-switcher/index.tsx
  client/jetpack-cloud/sections/pricing/jpcom-footer/locale-switcher/style.scss
  client/jetpack-cloud/sections/pricing/jpcom-footer/locale-switcher/translations.tsx
  client/jetpack-cloud/sections/pricing/jpcom-footer/style.scss
Labels: [Status] Needs Review, [Size] S, Jetpack Cloud

#60787 Replace link button with InlineSupportLink
  client/components/inline-support-link/context-links.js
  client/my-sites/woocommerce/woop/landing-page.tsx
  client/my-sites/woocommerce/woop/style.scss
Labels: [Status] Needs Review

#60524 Themes: Mobile implement new design
  client/my-sites/themes/current-theme/index.tsx
  client/my-sites/themes/current-theme/style.scss
  client/my-sites/themes/theme-showcase.scss
  client/my-sites/themes/themes-header.scss
Labels: Themes, [Status] Needs Review, Mobile Web, Theme Showcase

#60719 Playwright: wait until `networkidle` is fired when using navtabs within the MarketingPage.
  packages/calypso-e2e/src/lib/pages/marketing-page.ts
  test/e2e/specs/specs-playwright/wp-marketing__seo.ts
Labels: [Status] Needs Review

#60835 Playwright: update Gutenboarding flow to check for Site Editor issues.
  packages/calypso-e2e/src/lib/flows/close-account-flow.ts
  packages/calypso-e2e/src/lib/pages/me/account-settings-page.ts
  test/e2e/specs/specs-playwright/wp-gutenboarding__happy-path.ts
Labels: [Status] Needs Review

#59310 Domains page copy experiment (signup flow)
  client/components/domains/register-domain-step/index.jsx
  client/signup/controller.js
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review, Signup, Domains, ABTest

#60192 State: Remove unnecessary preferences state
  client/state/action-types.ts
  client/state/preferences/actions.js
  client/state/preferences/reducer.js
  client/state/preferences/selectors.js
  client/state/preferences/test/actions.js
  client/state/preferences/test/reducer.js
Labels: [Status] Needs Review, [Type] Janitorial, State

#60764 State: Remove unused site keyrings save requests state
  client/state/action-types.ts
  client/state/site-keyrings/actions.js
  client/state/site-keyrings/reducer.js
  client/state/site-keyrings/selectors.js
Labels: [Status] Needs Review, [Type] Janitorial, State

#60801 Use new final_discount property for displayed percentage
  client/jetpack-cloud/sections/pricing/sale-banner/index.tsx
Labels: [Status] Needs Review, [Size] XS

#60767 Jetpack Checkout Thank You: migrate data getter to React Query
  client/my-sites/checkout/checkout-thank-you/jetpack-checkout-thank-you.tsx
Labels: Jetpack, [Status] Needs Review, Checkout

#60845 P2: update endpoint for settings validation
  client/my-sites/site-settings/settings-p2/preapproved-domains.jsx
Labels: [Status] Reviewer Approved

#60824 Fix Site Editor tracking tests for Gv12.5
  test/e2e/lib/components/site-editor-component.js
  test/e2e/specs/specs-wpcom/wp-calypso-gutenberg-site-editor-tracking-spec.js
Labels: [Status] Needs Review

#60874 FSE: roll out to 100% of new sites
  client/lib/signup/step-actions/index.js
Labels: [Status] Needs Review, [Goal] Full Site Editing

#60821 Use "Installed Plugins" instead of "Manage plugins" for consistency.
  client/my-sites/plugins/main.jsx
  client/my-sites/plugins/plugins-browser/index.jsx
Labels: Marketplace

#60707 Bugfix: Retrieve installed plugins information when not available in cache
  client/components/data/query-jetpack-plugins/index.jsx
  client/my-sites/sidebar-unified/use-site-menu-items.js
Labels: [Status] Needs Review

#60806 phpMyAdmin hosting card: migrate data getter to direct wpcom.req.post
  client/my-sites/hosting/phpmyadmin-card/index.js
Labels: [Status] Needs Review

#60465 Fix post checkout flow for Professional Email upsell
  client/my-sites/checkout/upsell-nudge/index.jsx
  client/my-sites/checkout/upsell-nudge/professional-email-upsell/index.tsx
Labels: [Status] Needs Review, Checkout, Post Checkout, Professional Email

#60865 Domains: Fix typo in connected domain notice
  client/lib/domains/resolve-domain-status.tsx
Labels: [Status] Needs Review, Domains

#60860 Domains: Fix style of domain delete card button
  client/my-sites/domains/domain-management/components/domain/domain-info-card/delete/index.tsx
  client/my-sites/domains/domain-management/components/domain/domain-info-card/style.scss
Labels: [Status] Needs Review, Domains

#60686 Checkout: show the plan upsell even for PWPO users
  client/my-sites/checkout/cart/cart-free-user-plan-upsell.jsx
  client/my-sites/checkout/composite-checkout/components/secondary-cart-promotions.tsx
Labels: [Status] Needs Review, Checkout

#60856 Domains: Fix hover style of disabled DNS records popover menu items
  client/my-sites/domains/domain-management/dns/style.scss
Labels: [Status] Needs Review, Domains

#60886 Remove http-data framework
  client/state/action-types.ts
  client/state/data-layer/http-data.ts
  client/state/index.js
  client/state/reducer.js
Labels: [Status] Needs Review

#60863 Themes: Fix overlap in on the theme page.
  client/components/theme/style.scss
Labels: [Type] Bug, Themes, [Status] Needs Review, [Status] Ready to Merge, Empathy Testing

#60752 Shopping Cart: Remove unused properties of RequestCart
  client/my-sites/checkout/composite-checkout/test/composite-checkout-variant-picker.tsx
  client/my-sites/checkout/composite-checkout/test/composite-checkout.js
  client/my-sites/checkout/composite-checkout/test/util/index.ts
  packages/shopping-cart/src/cart-functions.ts
  packages/shopping-cart/src/empty-carts.ts
  packages/shopping-cart/src/types.ts
Labels: [Status] Ready to Merge, Shopping Cart

#60525 Handle Disconnected WPCOM Jetpack Sites
  client/my-sites/plugins/plugin-details-CTA/index.jsx
  client/my-sites/plugins/plugin-details.jsx
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/plugins/plugins-browser/test/index.jsx
Labels: [Status] Needs Review

#60854 Credit cards: Set cardholderName error when field is empty during validation
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-pay-button.js
Labels: [Status] Ready to Merge, Checkout, Payment Methods

#57678 Jetpack License Portal: Update issue license screen to new design
  client/jetpack-cloud/sections/partner-portal/issue-license-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-form/style.scss
  client/jetpack-cloud/sections/partner-portal/license-product-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-product-card/style.scss
  client/jetpack-cloud/sections/partner-portal/primary/issue-license/index.tsx
Labels: [Type] Enhancement, [Status] Needs Review, Jetpack Licensing Portal

#60772 Seller Experience: Add redirection to site editor for "Start simple"
  client/signup/steps/intent/index.tsx
  client/signup/steps/store-features/index.tsx
  client/state/selectors/get-site-editor-url.js
Labels: [Status] Needs Review, Seller Experience

#60889 Update sidebar Plan name when user cancels or downgrades their plan.
  client/state/purchases/actions.js
  client/state/purchases/test/actions.js
Labels: [Status] Needs Review

#60838 Woo landing page: Align icons
  client/my-sites/woocommerce/landing-page.tsx
  client/my-sites/woocommerce/style.scss
Labels: [Status] Needs Review

#60908 Update design picker config so that only Blank Canvas would have the is_featured_picks property
  packages/design-picker/src/available-designs-config.json
Labels: [Status] Needs Review

#60807 Fix reskinned domain search step layout
  client/components/domains/domain-product-price/style.scss
  client/components/domains/domain-suggestion/style.scss
  client/components/domains/featured-domain-suggestions/style.scss
  client/signup/style.scss
Labels: [Status] Needs Review, Domains

#60880 Render dev helpers in Gutenboarding after extracting a common function (try 2)
  client/boot/common.js
  client/landing/gutenboarding/index.tsx
  client/landing/login/common.js
  client/lib/features-helper/style.scss
  client/lib/load-dev-helpers/index.js
  client/server/pages/index.js
  client/server/pages/test/index.js
Labels: [Status] Needs Review

#60818 CI: Add `Translate` build config for WebApp
  .teamcity/_self/projects/WebApp.kt
Labels: [Status] Needs Review, TeamCity

#60244 Plugins: Remove legacy unused components
  client/components/version/README.md
  client/components/version/docs/example.jsx
  client/components/version/index.jsx
  client/components/version/style.scss
  client/devdocs/design/component-examples.js
  client/devdocs/design/index.jsx
  client/devdocs/design/playground-scope.js
  client/lib/automated-transfer/index.js
  client/lib/automated-transfer/test/index.js
  client/my-sites/plugins/plugin-automated-transfer/README.md
  client/my-sites/plugins/plugin-automated-transfer/index.jsx
  client/my-sites/plugins/plugin-automated-transfer/style.scss
  client/my-sites/plugins/plugin-information/README.md
  client/my-sites/plugins/plugin-information/index.jsx
  client/my-sites/plugins/plugin-information/style.scss
  client/my-sites/plugins/plugin-install-button-wpcom/index.jsx
  client/my-sites/plugins/plugin-meta/README.md
  client/my-sites/plugins/plugin-meta/index.jsx
  client/my-sites/plugins/plugin-meta/style.scss
  client/my-sites/plugins/plugin-meta/test/index.js
  client/my-sites/plugins/with-plugin-redirect/index.js
  client/my-sites/plugins/with-plugin-redirect/utils.js
  client/state/plugins/installed/selectors.js
  client/state/sites/selectors/get-site-wordpress-seo-wizard-url.js
  client/state/sites/selectors/index.js
Labels: [Status] Needs Review, [Type] Janitorial, Plugins

#60919 Reader: Include data layer for tag subscription
  client/state/reader/lists/actions.js
Labels: [Type] Bug, [Status] Needs Review, Reader

#60851 Licensing Portal – Improve the credit cards grid to support small viewports
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-list/style.scss
Labels: [Status] Needs Review, [Size] XS, Jetpack Licensing Portal

#60914 Reader: Refactor `ReaderFeaturedVideo` away from `UNSAFE_` lifecycle methods
  client/blocks/reader-featured-video/index.jsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Reader

#60915 Reader: Refactor `FeaturedImage` away from `UNSAFE_` lifecycle methods
  client/blocks/reader-full-post/featured-image.jsx
  client/blocks/reader-full-post/test/featured-image.jsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Reader

#60725 Improve messages to user when deleting a P2 workspace
  client/data/p2/use-p2-hub-p2s-query.js
  client/data/p2/with-p2-hub-p2-count.js
  client/my-sites/site-settings/delete-site-warning-dialog/index.jsx
  client/my-sites/site-settings/site-tools/index.jsx
Labels: [Status] Needs Review

#60692 Remove "Menus" and "AMP" submenus
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-universal-themes/index.php
Labels: Menus, [Status] Needs Review

#60930 Themes Showcase: Fix current theme track click event names
  client/my-sites/themes/current-theme/index.tsx
Labels: [Status] Needs Review

#60716 Removing the redirects for premium theme pages
  client/my-sites/themes/controller.jsx
  client/my-sites/themes/index.node.js
  client/my-sites/themes/test/controller.js
Labels: [Status] Needs Review

#60901 Seller Experience: Use signup infrastructure rather than a hard-coded redirect
  client/lib/signup/step-actions/index.js
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  client/signup/config/steps-pure.js
  client/signup/config/steps.js
  client/signup/steps/store-features/index.tsx
Labels: [Status] Needs Review

#60933 Revert "Seller Experience: Use signup infrastructure rather than a hard-coded redirect"
  client/lib/signup/step-actions/index.js
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  client/signup/config/steps-pure.js
  client/signup/config/steps.js
  client/signup/steps/store-features/index.tsx
Labels: [Status] Needs Review

#60902 CI: upgrade to Playwright 1.18
  desktop/test/e2e/specs/login.js
  packages/calypso-e2e/package.json
  test/e2e/package.json
  yarn.lock
Labels: [Status] In Progress, [Status] Needs Review

#60911 Prevent scrolling on preview page in start flow
  client/signup/steps/design-picker/style.scss
Labels: [Status] Needs Review

#60083 WooCommerce: Remove disabled store referrers stats
  client/my-sites/store/app/store-stats/constants.js
  client/my-sites/store/app/store-stats/controller.js
  client/my-sites/store/app/store-stats/index.js
  client/my-sites/store/app/store-stats/referrers/chart/index.js
  client/my-sites/store/app/store-stats/referrers/chart/style.scss
  client/my-sites/store/app/store-stats/referrers/helpers.js
  client/my-sites/store/app/store-stats/referrers/index.js
  client/my-sites/store/app/store-stats/referrers/style.scss
  client/my-sites/store/app/store-stats/referrers/test/helpers.js
  client/my-sites/store/app/store-stats/store-stats-referrer-conv-widget/index.js
  client/my-sites/store/app/store-stats/store-stats-referrer-conv-widget/style.scss
  client/my-sites/store/app/store-stats/store-stats-referrer-widget-base/index.js
  client/my-sites/store/app/store-stats/store-stats-referrer-widget-base/style.scss
  client/my-sites/store/app/store-stats/store-stats-referrer-widget/index.js
  client/my-sites/store/app/store-stats/store-stats-referrer-widget/style.scss
  client/my-sites/store/app/store-stats/test/utils.js
  client/my-sites/store/app/store-stats/utils.js
  client/my-sites/store/style.scss
  client/state/selectors/get-store-referrers-by-date.js
  client/state/selectors/get-store-referrers-by-referrer.js
  client/state/stats/lists/actions.js
  client/state/stats/lists/test/utils.js
  client/state/stats/lists/utils.js
  config/development.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: Framework, Stats, [Status] Needs Review, [Type] Janitorial, WooCommerce

#60943 Signup: Fix spacing of select items in intent screen
  client/signup/select-items-alt/style.scss
  client/signup/select-items/style.scss
Labels: [Status] Needs Review, Blogger Experience Pod

#60954 Fix: Annual discount calculation fails on P2 plans
  client/my-sites/plan-features/header.jsx
Labels: [Type] Bug, Plans, [Status] Ready to Merge

#60825 Stop showing the untested version message when the site is not jetpack (simple site users).
  client/my-sites/plugins/plugins-browser-item/index.jsx
Labels: Marketplace

#60941 Detect swipe gestures in DotPager to hide popovers in containing Tasks components
  packages/components/src/popover/index.jsx
Labels: [Status] Needs Review

#60780 Partner portal: remove footer references
  client/jetpack-cloud/sections/partner-portal/controller.tsx
Labels: [Status] Needs Review, Jetpack Cloud, [Size] XS, Jetpack Licensing Portal

#59912 Add Downgrades to Monthly within the refund period
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/step-components/downgrade-step.jsx
  client/me/purchases/cancel-purchase/button.jsx
Labels: [Status] Needs Review, [Status] String Freeze

#60414 Checkout: Add a partner logo during checkout when partner coupon is present
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
  packages/wpcom-checkout/src/checkout-line-items.tsx
  packages/wpcom-checkout/src/index.ts
  packages/wpcom-checkout/src/partner-coupon.ts
  packages/wpcom-checkout/src/partner-logo-ionos.tsx
Labels: Jetpack, [Status] Needs Review, Checkout, Shopping Cart

#60955 Update the Anti-Spam card stats copy
  client/lib/plans/features-list.js
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/products-list.ts
Labels: [Status] Needs Review, [Size] XS

#60963 AMP: safer adding/removal/juggling
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-universal-themes/index.php
Labels: [Status] Needs Review

#60904 Theme: Remove setNextLayoutFocus sidebar
  client/my-sites/theme/controller.jsx
Labels: Themes, [Status] Needs Review, Mobile Web, Theme Showcase

#60968 CI: Iterate on initial `Translate` build configuration
  .teamcity/_self/projects/WebApp.kt
Labels: [Status] Needs Review, TeamCity

#60694 Support Article: Add url query parameter to make the modal work as expected with back buttons
  client/blocks/inline-help/inline-help-rich-result.jsx
  client/blocks/support-article-dialog/dialog.jsx
  client/blocks/support-article-dialog/index.jsx
  client/components/inline-support-link/index.jsx
  client/lib/url-search-query-state/index.js
  client/state/inline-support-article/reducer.js
  client/state/selectors/is-inline-support-article-visible.js
Labels: [Status] Needs Review, Support, Help, Mobile Web

#60934 Seller Experience: Use Headstart to set up the payments pattern
  client/lib/signup/step-actions/index.js
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  client/signup/config/steps-pure.js
  client/signup/config/steps.js
  client/signup/steps/store-features/index.tsx
Labels: [Status] In Progress, [Status] Needs Review, DO NOT MERGE, Seller Experience

#60939 Update upsell nudge copy for Atomic sites.
  client/my-sites/themes/single-site-jetpack.jsx
Labels: Themes, Atomic, Theme Showcase, Upsell Nudge

#60896 Add Jetpack Sale Coupons to Variant Selectors
  client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx
  client/state/marketing/selectors.ts
  client/state/products-list/selectors/compute-full-and-monthly-prices-for-plan.js
  client/state/products-list/test/selectors.js
Labels: [Type] Enhancement, [Status] Needs Review, [Size] S, Shopping Cart

#60942 Fix Calypso Analytics debug filtering instructions for Tracks
  client/lib/analytics/README.md
Labels: [Status] Needs Review

#60944 Signup: Remove ecommerce-onboarding flow
  client/signup/config/flows-pure.js
  client/signup/steps/domains/index.jsx
  client/signup/steps/site-type/index.jsx
  config/_shared.json
Labels: [Status] Needs Review, Blogger Experience Pod

#60917 Mini-cart: improve CSS styles
  packages/mini-cart/src/mini-cart.tsx
Labels: [Status] Needs Review, Shopping Cart
