Repository Automattic/wp-calypso, pull requests merged in 2022-03, with the labels that each got.

#61533 Jetpack Cloud | Disable navigation to back in time on initial backup screen
  client/my-sites/backup/backup-date-picker/hooks.ts
  client/my-sites/backup/backup-date-picker/index.tsx
  client/my-sites/backup/backup-date-picker/test/index.jsx
  client/my-sites/backup/status/index.jsx
Labels: [Type] Bug, [Status] Needs Review

#61528 Update the Jetpack connection support link
  client/components/jetpack/jetpack-disconnected-wpcom/index.tsx
  client/components/jetpack/jetpack-disconnected/index.tsx
  client/lib/url/support.js
Labels: [Type] Enhancement, [Status] Needs Review

#61529 Show site disconnection error message from the API error response
  client/blocks/disconnect-jetpack/index.jsx
Labels: [Status] Needs Review

#61560 Domains: Fix a typo in the copy-DNS suggestion
  client/components/domains/connect-domain-step/connect-domain-step-suggested-start.jsx
Labels: [Status] Needs Review

#61541 `OrgRemoteCredentials`: refactor away from `UNSAFE_*`
  client/jetpack-connect/remote-credentials.js
  client/state/jetpack-remote-install/reducer.js
  client/state/selectors/is-remote-installing-jetpack.js
Labels: [Status] Needs Review, [Type] Janitorial

#61360 Guided Tours: Refactor `Quit` away from `UNSAFE_` lifecycle methods
  client/layout/guided-tours/config-elements/quit.js
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Guided Tours

#61455 Themes: Add unit tests for getPremiumThemePrice
  client/state/themes/selectors/get-premium-theme-price.js
  client/state/themes/test/selectors.js
Labels: [Status] Needs Review, Testing, Tests

#61546 Remove Jetpack Search Coupon Injection
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-maybe-jetpack-intro-coupon-code.ts
Labels: [Status] Needs Review, [Size] S

#61431 Playwright: refactor EditorPublishPanelComponent out of GutenbergEditorPage.
  packages/calypso-e2e/src/lib/components/editor-publish-panel-component.ts
  packages/calypso-e2e/src/lib/components/index.ts
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
  test/e2e/specs/editor/editor__page-basic-flow.ts
  test/e2e/specs/editor/editor__post-advanced-flow.ts
  test/e2e/specs/editor/editor__post-basic-flow.ts
  test/e2e/specs/editor/editor__schedule.ts
  test/e2e/specs/editor/editor__tracks-events.ts
  test/e2e/specs/editor/shared/privacy-testing.ts
  test/e2e/specs/published-content/likes__comment.ts
  test/e2e/specs/published-content/likes__post.ts
Labels: [Status] Needs Review

#61554 Woo landing page: Remove 100% width on wide-layout
  client/my-sites/woocommerce/style.scss
Labels: [Status] Ready to Merge

#61590 Update e2e encrypted file password and TeamCity config.
  .teamcity/settings.kts
  test/e2e/config/encrypted.enc
Labels: [Status] Needs Review

#61583 Licensing portal: Rename the existing payment methods state
  client/jetpack-cloud/sections/partner-portal/credit-card-fields/credit-card-submit-button.tsx
  client/jetpack-cloud/sections/partner-portal/payment-methods/hooks/use-create-stored-credit-card.ts
  client/jetpack-cloud/sections/partner-portal/payment-methods/stored-credit-card-method.tsx
  client/state/partner-portal/credit-card-form/actions.ts
  client/state/partner-portal/credit-card-form/index.ts
  client/state/partner-portal/credit-card-form/reducer.ts
  client/state/partner-portal/credit-card-form/selectors.ts
  client/state/partner-portal/credit-card-form/test/actions.js
  client/state/partner-portal/credit-card-form/test/selectors.js
Labels: [Status] Needs Review

#61579 Plugins: Fix word break in plugins sections
  client/my-sites/plugins/plugin-sections/style.scss
Labels: [Status] Needs Review

#61566 Emails: Refactor GoogleMailboxPricingNotice into MailboxPricingNotice
  client/my-sites/email/email-pricing-notice/index.tsx
  client/my-sites/email/gsuite-add-users/index.jsx
Labels: [Status] Needs Review, G Suite

#61446 DIFM Lite: Contact page section improvements
  client/signup/steps/website-content/page-details.tsx
  client/signup/steps/website-content/section-generator.tsx
Labels: [Status] Needs Review, difm-lite

#61572 Emails: Remove former Email Forwarding page
  client/my-sites/domains/domain-management/controller.jsx
  client/my-sites/domains/domain-management/dns/delete-email-forwards-dialog.jsx
  client/my-sites/domains/index.js
  client/my-sites/domains/paths.js
  client/my-sites/email/controller.js
  client/my-sites/email/email-forwarding/email-forwarding-add-new.jsx
  client/my-sites/email/email-forwarding/email-forwarding-custom-mx-list.jsx
  client/my-sites/email/email-forwarding/email-forwarding-details.jsx
  client/my-sites/email/email-forwarding/email-forwarding-gsuite-details-another-provider.jsx
  client/my-sites/email/email-forwarding/email-forwarding-gsuite-details.jsx
  client/my-sites/email/email-forwarding/email-forwarding-item.jsx
  client/my-sites/email/email-forwarding/email-forwarding-limit.jsx
  client/my-sites/email/email-forwarding/email-forwarding-list.jsx
  client/my-sites/email/email-forwarding/email-forwarding-placeholder.jsx
  client/my-sites/email/email-forwarding/index.jsx
  client/my-sites/email/email-forwarding/style.scss
  client/my-sites/email/email-forwarding/test/__snapshots__/email-forwarding-item.js.snap
  client/my-sites/email/email-forwarding/test/email-forwarding-item.js
  client/my-sites/email/email-management/home/email-plan.jsx
  client/my-sites/email/index.js
  client/state/selectors/get-email-forwarding-limit.js
  client/state/selectors/get-email-forwarding-mx-servers.js
  client/state/selectors/get-email-forwarding-type.js
Labels: [Status] Needs Review, Email management

#58518 Adds support for in-app purchases
  client/lib/purchases/assembler.js
  client/lib/purchases/types.ts
  client/me/purchases/manage-purchase/index.jsx
  client/me/purchases/manage-purchase/notices.jsx
  client/me/purchases/manage-purchase/payment-info-block.tsx
  client/me/purchases/manage-purchase/plan-details/billing-period.jsx
  client/me/purchases/manage-purchase/purchase-meta.jsx
  client/me/purchases/purchase-item/index.jsx
  client/my-sites/plans-features-main/index.jsx
  client/my-sites/plans/current-plan/purchases-listing.jsx
  client/my-sites/plans/jetpack-plans/product-card/index.tsx
  client/state/purchases/test/selectors.js
  client/state/selectors/can-upgrade-to-plan.js
Labels: [Status] Needs Review, [Status] Needs Design Review, Purchases, Payment Methods, [Status] String Freeze, [Status] Needs Copy Review, [Status] Design Input Requested, [Status] Editorial Input Requested

#61569 Unify/titan notice components into one refactored component
  client/my-sites/email/email-pricing-notice/index.tsx
  client/my-sites/email/gsuite-add-users/google-workspace-pricing-notice.tsx
  client/my-sites/email/titan-add-mailboxes/index.jsx
  client/my-sites/email/titan-add-mailboxes/titan-mailbox-pricing-notice.tsx
Labels: [Status] Needs Review, Professional Email

#61585 Signup: Link to My Home rather than wp-admin for "Start from scratch"
  client/signup/config/flows.js
  client/signup/steps/intent/index.tsx
  client/signup/steps/intent/intents.tsx
Labels: [Status] Needs Review, Signup

#61606 Seller Experience v2: Add initial translations for the Woo upsell banner on My Home
  client/my-sites/customer-home/translations/woo-upsell-banner.js
Labels: [Status] In Progress, [Status] Needs Review, Seller Experience

#61603 Theme Showcase: Removed theme category nav from theme showcase
  client/my-sites/themes/theme-showcase.jsx
Labels: [Status] Needs Review, Theme Showcase

#61610 Domains: Hide email card when canCurrentUserAddEmail is false
  client/my-sites/domains/domain-management/components/domain/domain-info-card/email/index.tsx
Labels: [Status] Ready to Merge

#61521 Fix: Product/Plan Management URL in Overlap Notice
  client/blocks/product-plan-overlap-notices/index.jsx
Labels: [Type] Bug, [Status] In Progress, [Status] Needs Review, [Size] XS

#61565 Show next steps for DIFM in Checkout
  client/my-sites/checkout/composite-checkout/components/checkout-next-steps.tsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
Labels: [Status] Needs Review, difm-lite

#61596 Configure ICFY action to retain uploaded stats only for 7 days
  .github/workflows/icfy-stats.yml
Labels: [Status] Needs Review

#61592 Adds Attar, Hari, Marl, Winkel, and Dorna themes to /new flow
  packages/design-picker/src/available-designs-config.json
Labels: [Status] Needs Review, [Goal] New Onboarding

#61625 Update the displaying of compact breadcrumbs
  client/components/breadcrumb/index.tsx
  client/my-sites/plugins/plugin-details.jsx
Labels: Marketplace

#61453 Legacy FSE editor integration removal
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/navigation-menu/edit.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/navigation-menu/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/navigation-menu/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/post-content/edit.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/post-content/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/post-content/save.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/post-content/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/site-credit/edit.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/site-credit/footer-credit-choices.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/site-credit/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/site-credit/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/site-description/edit.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/site-description/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/site-description/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/site-title/edit.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/site-title/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/site-title/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/template/edit.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/template/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/template/site-logo.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/template/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/class-full-site-editing.php
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/editor/block-inserter/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/editor/block-inserter/post-content-block-appender.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/editor/image-block-keywords/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/editor/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/editor/remove-editor-panels/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/editor/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/editor/suppress-draft-action/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/editor/suppress-trash-action/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/editor/template-validity-override/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/helpers.php
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/lib/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/lib/site-options/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/lib/site-options/use-previous.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/lib/site-options/use-site-options.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/lib/site-options/with-site-options.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/plugins/close-button-override/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/plugins/close-button-override/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/plugins/editor-template-classes/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/plugins/template-update-notice/index.js
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/sass/_mixins.scss
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/serialize-block-fallback.php
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/templates/class-rest-templates-controller.php
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/templates/class-template-image-inserter.php
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/templates/class-wp-template-inserter.php
  apps/editing-toolkit/package.json
Labels: [Status] Needs Review, [Goal] Full Site Editing

#60683 Filterbar: Increase specificity
  client/my-sites/activity/filterbar/style.scss
Labels: [Type] Bug, [Status] Needs Review, Activity Log

#61545 Seller Experience: Add the Design Picker to the flow
  client/lib/signup/step-actions/index.js
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  client/signup/config/steps-pure.js
  client/signup/steps/design-picker/index.jsx
  client/signup/steps/intent/index.tsx
  client/signup/steps/store-features/index.tsx
Labels: [Status] Needs Review, Seller Experience

#61646 [E2E][GB 12.7.x] Test fix for Gutenberg
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
Labels: caused-by-gutenberg-upgrade

#61502 Playwright: refactor EditorToolbarComponent and EditorNavSidebarComponent out of GutenbergEditorPage.
  packages/calypso-e2e/src/lib/components/editor-nav-sidebar-component.ts
  packages/calypso-e2e/src/lib/components/editor-publish-panel-component.ts
  packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts
  packages/calypso-e2e/src/lib/components/index.ts
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
  test/e2e/specs/blocks/blocks__jetpack-grow.ts
  test/e2e/specs/editor/editor__navbar.ts
  test/e2e/specs/editor/editor__post-basic-flow.ts
  test/e2e/specs/editor/editor__schedule.ts
  test/e2e/specs/onboarding/signup__free.ts
Labels: [Status] In Progress, [Status] Needs Review

#61134 App Banner: remove mobile app banner if previous flow was onboarding
  client/state/selectors/should-display-app-banner.ts
Labels: [Status] Needs Review

#61653 Implement the missing term selectors
  packages/calypso-products/src/main.ts
  packages/calypso-products/test/plan-lookups.js
Labels: [Status] Needs Review

#61626 Media: Refactor media storage to use `react-query`
  client/blocks/plan-storage/README.md
  client/blocks/plan-storage/index.jsx
  client/blocks/plan-storage/test/plan-storage.jsx
  client/components/data/query-media-storage/README.md
  client/components/data/query-media-storage/index.jsx
  client/data/media-storage/use-media-storage-query.js
  client/data/media-storage/with-media-storage.js
  client/data/media/use-upload-media-mutation.js
  client/data/media/with-delete-media.js
  client/my-sites/exporter/export-media-card/index.js
  client/my-sites/site-settings/media-settings-performance.jsx
  client/state/action-types.ts
  client/state/data-layer/wpcom/sites/media-storage/index.js
  client/state/data-layer/wpcom/sites/media-storage/test/index.js
  client/state/selectors/get-media-storage-limit.js
  client/state/selectors/get-media-storage-used.js
  client/state/selectors/test/get-media-storage-limit.js
  client/state/selectors/test/get-media-storage-used.js
  client/state/sites/media-storage/actions.js
  client/state/sites/media-storage/reducer.js
  client/state/sites/media-storage/schema.js
  client/state/sites/media-storage/selectors.js
  client/state/sites/media-storage/test/actions.js
  client/state/sites/media-storage/test/reducer.js
  client/state/sites/media-storage/test/selectors.js
  client/state/sites/reducer.js
  client/state/sites/test/reducer.js
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Media, State, Data

#61600 Plugins Browser: Use compact breadcrumbs when on mobile layout
  client/my-sites/plugins/plugins-browser/index.jsx
  packages/calypso-e2e/src/lib/pages/plugins-page.ts
  test/e2e/specs/plugins/plugins__browse.ts
Labels: [Status] Needs Review

#61638 Add warning when a domain already has paid email service
  client/lib/gsuite/get-gsuite-subscription-status.js
  client/lib/gsuite/get-gsuite-subscription-status.ts
  client/lib/gsuite/has-gsuite-with-another-provider.ts
  client/lib/gsuite/has-gsuite-with-us.ts
  client/lib/titan/has-titan-mail-with-us.js
  client/lib/titan/has-titan-mail-with-us.ts
  client/my-sites/email/email-existing-paid-service-notice/index.tsx
  client/my-sites/email/email-providers-stacked-comparison/index.tsx
Labels: [Status] Needs Review, G Suite, Professional Email, Email management

#61658 Reimport the useState hook.
  client/my-sites/plugins/plugins-browser/index.jsx
Labels: Marketplace

#61637 Styled site delete confirmation
  client/signup/steps/difm-site-picker/index.tsx
  client/signup/steps/difm-site-picker/site-delete-confirmation-dialog.tsx
  client/signup/steps/difm-site-picker/styles.scss
Labels: [Status] Needs Review, difm-lite

#61507 Legacy FSE: remove all Calypso references
  client/blocks/product-purchase-features-list/index.jsx
  client/components/data/query-site-checklist/index.js
  client/data/site-checklist/use-site-checklist.ts
  client/gutenberg/editor/calypsoify-iframe.tsx
  client/gutenberg/editor/controller.js
  client/my-sites/current-site/domain-warnings.jsx
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
  client/my-sites/customer-home/cards/actions/wp-for-teams-quick-links/index.jsx
  client/my-sites/domains/components/domain-warnings/index.jsx
  client/my-sites/domains/components/domain-warnings/test/index.js
  client/my-sites/pages/blog-posts-page/index.jsx
  client/my-sites/pages/page/index.js
  client/my-sites/sidebar/index.jsx
  client/state/checklist/actions.js
  client/state/data-layer/wpcom/theme-filters/index.js
  client/state/selectors/get-customize-or-edit-front-page-url.js
  client/state/selectors/get-customize-url.js
  client/state/selectors/get-editor-close-config.js
  client/state/selectors/is-site-eligible-for-legacy-fse.js
  client/state/selectors/is-site-using-legacy-fse.js
  client/state/selectors/test/get-editor-close-config.js
  client/state/selectors/test/is-site-eligible-for-full-site-editing.js
  client/state/selectors/test/is-site-using-full-site-editing.js
  client/state/sites/constants.js
Labels: [Status] Needs Review, [Type] Janitorial, [Goal] Full Site Editing

#61664 Fix Tab Order in Cart
  packages/wpcom-checkout/src/checkout-line-items.tsx
Labels: [Type] Bug, [Status] Ready to Merge, [Size] XS

#61349 [GB][E2E] Introduce a simpler upgrade smoke test E2E for blocks in simple and AT sites
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
  test/e2e/.eslintrc.js
  test/e2e/specs/blocks/blocks__smoke-test-across-gb-edge-versions.ts
  test/e2e/specs/wpcom-old/gutenberg__upgrade.js
Labels: [Status] Needs Review

#61640 Seller Experience: Add Woo upsell to My Home banner
  client/assets/images/customer-home/illustration--seller.svg
  client/my-sites/customer-home/cards/constants.js
  client/my-sites/customer-home/cards/notices/site-launch-seller-upsell/index.jsx
  client/my-sites/customer-home/locations/primary/index.jsx
Labels: [Status] Needs Review, Customer Home, Seller Experience

#61046 View Switcher: Add Tracking and update tab label
  client/components/screen-options-tab/index.js
Labels: [Status] Needs Review, [Type] Task, Nav Unification

#61247 Licensing Portal: Remove non-primary payment methods modal
  client/jetpack-cloud/sections/partner-portal/payment-method-actions/index.tsx
  client/jetpack-cloud/sections/partner-portal/payment-method-delete-dialog/index.tsx
  client/jetpack-cloud/sections/partner-portal/payment-method-delete-dialog/style.scss
  client/jetpack-cloud/sections/partner-portal/stored-credit-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/stored-credit-card/style.scss
  client/state/partner-portal/stored-cards/actions.ts
  client/state/partner-portal/stored-cards/reducer.ts
  client/state/partner-portal/stored-cards/selectors.ts
Labels: [Status] Needs Review

#61479 Disable domain actions for domains at auction
  client/my-sites/domains/domain-management/components/domain/aftermarket-auction-notice.tsx
  client/my-sites/domains/domain-management/components/domain/domain-info-card/transfer/index.tsx
  client/my-sites/domains/domain-management/list/domain-row.jsx
  client/my-sites/domains/domain-management/settings/cards/registered-domain-details.tsx
  client/my-sites/domains/domain-management/settings/set-as-primary/index.tsx
  client/my-sites/domains/domain-management/transfer/transfer-page/index.tsx
  client/my-sites/domains/domain-management/transfer/transfer-to-other-site/transfer-domain-to-other-site.tsx
  client/my-sites/domains/domain-management/transfer/transfer-to-other-site/types.ts
  client/my-sites/domains/domain-management/transfer/transfer-to-other-user/transfer-domain-to-other-user.jsx
Labels: [Status] Needs Review, Domains

#61562 Migrate App Passwords from Redux to React Query
  client/components/data/query-application-passwords/README.md
  client/components/data/query-application-passwords/index.jsx
  client/data/application-passwords/use-app-passwords-query.js
  client/data/application-passwords/use-create-app-password-mutation.js
  client/data/application-passwords/use-delete-app-password-mutation.js
  client/me/application-password-item/index.jsx
  client/me/application-passwords/form.jsx
  client/me/application-passwords/index.jsx
  client/me/application-passwords/list.jsx
  client/me/application-passwords/new-password.jsx
  client/state/action-types.ts
  client/state/application-passwords/actions.js
  client/state/application-passwords/init.js
  client/state/application-passwords/package.json
  client/state/application-passwords/reducer.js
  client/state/application-passwords/schema.js
  client/state/application-passwords/test/__snapshots__/reducer.js.snap
  client/state/application-passwords/test/actions.js
  client/state/application-passwords/test/reducer.js
  client/state/data-layer/wpcom/me/two-step/application-passwords/delete/index.js
  client/state/data-layer/wpcom/me/two-step/application-passwords/delete/test/index.js
  client/state/data-layer/wpcom/me/two-step/application-passwords/index.js
  client/state/data-layer/wpcom/me/two-step/application-passwords/new/index.js
  client/state/data-layer/wpcom/me/two-step/application-passwords/new/schema.js
  client/state/data-layer/wpcom/me/two-step/application-passwords/new/test/index.js
  client/state/data-layer/wpcom/me/two-step/application-passwords/schema.js
  client/state/data-layer/wpcom/me/two-step/application-passwords/test/index.js
  client/state/selectors/get-application-passwords.js
  client/state/selectors/get-new-application-password.js
  client/state/selectors/test/get-application-passwords.js
  client/state/selectors/test/get-new-application-password.js
Labels: [Status] Needs Review, [Type] Janitorial, 2FA

#61567 Remove unused routes and code, styles behind those routes from previous iterations of the Jetpack Checkout
  client/my-sites/checkout/checkout-thank-you/jetpack-checkout-siteless-thank-you-completed.tsx
  client/my-sites/checkout/checkout-thank-you/jetpack-checkout-siteless-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/style.scss
  client/my-sites/checkout/controller.jsx
  client/my-sites/checkout/index.js
Labels: Jetpack, [Status] Needs Review

#61633 Clear existing error notices on re-submit add payment method
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-add/index.tsx
Labels: Jetpack, [Status] Needs Review

#61482 Stepper: make step CSS reusable
  client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/intents.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/types.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-options/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-options/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/step-layouts/horizontal-layout.scss
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  packages/onboarding-components/src/components/onboarding-components-select-items/style.scss
Labels: [Status] Needs Review

#61666 Payment Methods: Re-throw errors in fetchStoredCards/deleteStoredCard
  client/state/stored-cards/actions.js
  client/state/stored-cards/test/actions.js
Labels: [Status] Needs Review, Payment Methods

#61671 Add Error Notice when an Introductory Offers Request Fails
  client/state/data-layer/wpcom/introductory-offers/index.tsx
Labels: [Type] Bug, [Type] Enhancement, [Status] Needs Review, [Status] Ready to Merge, [Size] S

#61700 Seller Experience: Add initial translations for updated Woo landing page
  client/my-sites/customer-home/translations/woo-upsell-banner.js
Labels: [Status] Needs Review, Seller Experience

#61712 Seller Experience: Adding payment contextual help
  client/blocks/inline-help/constants.js
  client/blocks/inline-help/contextual-help.js
Labels: [Status] Needs Review, Seller Experience

#61586 My Home: Add Store education card
  client/assets/images/customer-home/home-education-store.svg
  client/my-sites/customer-home/cards/constants.js
  client/my-sites/customer-home/cards/education/store/index.jsx
  client/my-sites/customer-home/locations/secondary/learn-grow/index.jsx
Labels: [Status] Needs Review, Customer Home, Seller Experience

#61525 Checkout: Fix display of plan overlap notices for backup-related plans
  client/my-sites/checkout/composite-checkout/components/prepurchase-notices/cart-plan-overlaps-owned-product-notice.tsx
  client/my-sites/checkout/composite-checkout/components/prepurchase-notices/index.jsx
  client/state/sites/products/conflicts.ts
  client/state/sites/products/test/conflicts.ts
Labels: [Type] Bug, Jetpack, [Status] Needs Review, Checkout, [Size] S

#61673 Checkout: Allow non-admins to access the shopping cart for a site
  client/my-sites/checkout/get-cart-key.ts
  client/my-sites/checkout/use-cart-key.ts
Labels: [Status] Needs Review, Checkout

#61672 Checkout: Do not try to update cart location if cart is loading
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-cached-domain-contact-details.ts
Labels: [Status] Needs Review, Checkout

#61663 Hide variation picker for partner coupons
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
Labels: [Status] Needs Review

#61705 Simplify Pricing For Jetpack Backup Storage Pricing Page
  client/components/jetpack/card/jetpack-product-card/display-price/paid.tsx
  client/my-sites/plans/jetpack-plans/storage-pricing/index.tsx
Labels: [Status] Needs Review, [Size] S, Jetpack Cloud

#61656 Plans overhaul Phase 1: apply new plans mix
  client/my-sites/plans-comparison/is-eligible-for-managed-plan.ts
  client/my-sites/plans/controller.jsx
  client/my-sites/plans/current-plan/controller.jsx
  client/my-sites/plans/current-plan/index.jsx
  client/my-sites/plans/navigation.jsx
  packages/calypso-products/src/is-flexible-plan.ts
  packages/calypso-products/src/product-values.ts
Labels: [Status] Needs Review

#61407 P2: move to the new signup flow
  client/lib/signup/step-actions/index.js
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  client/signup/main.jsx
  client/signup/p2-step-wrapper/index.jsx
  client/signup/p2-step-wrapper/style-p2new.scss
  client/signup/p2-step-wrapper/style-p2v1.scss
  client/signup/p2-step-wrapper/style.scss
  client/signup/steps/p2-confirm-email/index.jsx
  client/signup/steps/p2-confirm-email/style.scss
  client/signup/steps/p2-site/index.jsx
  client/signup/steps/p2-site/style.scss
  client/signup/utils.js
Labels: [Status] Needs Review

#61584 Show Pricing & Packaging Hotjar survey for eligible users
  client/my-sites/customer-home/main.jsx
Labels: [Status] Needs Review

#61701 Removing the days since signup from the Fiverr logo maker links.
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
  client/my-sites/marketing/tools/index.tsx
  client/my-sites/site-settings/form-general.jsx
Labels: [Status] Needs Review

#61715 Update Cart Line Item Design
  client/my-sites/checkout/composite-checkout/components/item-variation-picker.tsx
  packages/wpcom-checkout/src/checkout-labels.ts
  packages/wpcom-checkout/src/checkout-line-items.tsx
Labels: [Type] Enhancement, [Status] Needs Review, [Size] S, Shopping Cart

#61736 Marketplace plugin install: skip eligibility check for Atomic sites
  client/my-sites/plugins/plugin-details-CTA/index.jsx
Labels: [Type] Bug, [Status] Needs Review, Marketplace

#61668 Update Cart Variant Price Calculation Logic
  client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx
  client/state/marketing/selectors.ts
  client/state/products-list/selectors/compute-full-and-monthly-prices-for-plan.js
  client/state/products-list/selectors/compute-products-with-prices.js
  client/state/products-list/selectors/get-product-sale-coupon-cost.ts
  client/state/products-list/selectors/get-product-sale-coupon-discount.ts
  client/state/products-list/selectors/index.js
  client/state/products-list/test/selectors.js
Labels: [Type] Enhancement, [Status] In Progress, [Status] Needs Review, [Size] M, Shopping Cart

#61714 CI: upgrade Playwright to 1.19.
  desktop/package.json
  packages/calypso-e2e/package.json
  test/e2e/package.json
  yarn.lock
Labels: [Status] Needs Review

#61737 Seller Experience: Add context to Woo landing page translations
  client/my-sites/customer-home/translations/woo-upsell-banner.js
  client/my-sites/woocommerce/landing-page.tsx
Labels: [Status] Needs Review, [Status] String Freeze, Seller Experience

#61728 Fix grammar in backup messaging date and time
  client/components/jetpack/daily-backup-status/use-get-display-date.js
Labels: [Type] Bug, [Status] Needs Review

#61687 Add 'jetpack/backup-messaging-i3' feature-flags for production
  config/jetpack-cloud-production.json
  config/production.json
Labels: [Type] Enhancement

#61734 Refactor account email handling into dedicated component
  client/me/account/account-email-field.tsx
  client/me/account/main.jsx
Labels: [Status] Needs Review, Me

#61735 Add managed signup flow
  client/signup/config/flows-pure.js
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
  config/_shared.json
Labels: [Status] Needs Review, [Status] Ready to Merge, Signup

#61731 Packages - Onboarding: add intent-screen
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/intents.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/style.scss
  client/package.json
  client/signup/steps/import-from/wordpress/content-chooser/index.tsx
  client/signup/steps/import-from/wordpress/content-chooser/style.scss
  client/signup/steps/intent/index.tsx
  client/signup/steps/intent/intents.tsx
  client/signup/steps/site-or-domain/index.jsx
  client/signup/steps/site-or-domain/style.scss
  client/signup/steps/starting-point/starting-point.tsx
  client/signup/steps/store-features/index.tsx
  packages/calypso-e2e/src/lib/flows/start-import-flow.ts
  packages/design-picker/jest.config.js
  packages/domain-picker/jest.config.js
  packages/launch/jest.config.js
  packages/onboarding-components/README.md
  packages/onboarding-components/jest.config.js
  packages/onboarding-components/package.json
  packages/onboarding-components/src/index.ts
  packages/onboarding-components/tsconfig-cjs.json
  packages/onboarding-components/tsconfig.json
  packages/onboarding/jest.config.js
  packages/onboarding/package.json
  packages/onboarding/src/index.ts
  packages/onboarding/src/intent-screen/components/intent-screen-select-items-alt/index.tsx
  packages/onboarding/src/intent-screen/components/intent-screen-select-items-alt/style.scss
  packages/onboarding/src/intent-screen/components/intent-screen-select-items/index.tsx
  packages/onboarding/src/intent-screen/components/intent-screen-select-items/style.scss
  packages/onboarding/src/intent-screen/components/intent-screen.tsx
  packages/onboarding/src/intent-screen/index.ts
  packages/onboarding/src/intent-screen/types.ts
  packages/page-pattern-modal/jest.config.js
  packages/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review, Signup, Packages

#61730 Signup Icons: ( 1min review ) change path attributes to camelCase
  client/signup/icons/index.tsx
Labels: [Status] Needs Review, Signup

#59949 Tour Kit / Welcome Tour: WPCOM Tour Kit variant
  apps/editing-toolkit/__mocks__/@automattic/viewport.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/hooks/index.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/hooks/use-prefetch-tour-assets.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/style-tour.scss
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-step-renderer.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-steps.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/types.ts
  apps/editing-toolkit/package.json
  packages/tour-kit/.storybook/preview.js
  packages/tour-kit/README.md
  packages/tour-kit/package.json
  packages/tour-kit/src/components/tour-kit-context.tsx
  packages/tour-kit/src/components/tour-kit-frame.tsx
  packages/tour-kit/src/components/tour-kit-minimized.tsx
  packages/tour-kit/src/components/tour-kit-portal.tsx
  packages/tour-kit/src/components/tour-kit-spotlight.tsx
  packages/tour-kit/src/components/tour-kit-step.tsx
  packages/tour-kit/src/components/tour-kit.tsx
  packages/tour-kit/src/error-boundary.tsx
  packages/tour-kit/src/index.ts
  packages/tour-kit/src/storybook/index.stories.tsx
  packages/tour-kit/src/types.ts
  packages/tour-kit/src/variants/wpcom/components/wpcom-tour-kit-minimized.tsx
  packages/tour-kit/src/variants/wpcom/components/wpcom-tour-kit-rating.tsx
  packages/tour-kit/src/variants/wpcom/components/wpcom-tour-kit-step-card-navigation.tsx
  packages/tour-kit/src/variants/wpcom/components/wpcom-tour-kit-step-card-overlay-controls.tsx
  packages/tour-kit/src/variants/wpcom/components/wpcom-tour-kit-step-card.tsx
  packages/tour-kit/src/variants/wpcom/components/wpcom-tour-kit-step.tsx
  packages/tour-kit/src/variants/wpcom/components/wpcom-tour-kit.tsx
  packages/tour-kit/src/variants/wpcom/hooks/use-prefetch-tour-assets.tsx
  packages/tour-kit/src/variants/wpcom/icons/maximize.tsx
  packages/tour-kit/src/variants/wpcom/icons/minimize.tsx
  packages/tour-kit/src/variants/wpcom/icons/thumbs_down.tsx
  packages/tour-kit/src/variants/wpcom/icons/thumbs_up.tsx
  packages/tour-kit/src/variants/wpcom/index.ts
  packages/tour-kit/src/variants/wpcom/storybook/index.stories.tsx
  packages/tour-kit/src/variants/wpcom/styles.scss
  packages/tour-kit/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review, Welcome Tour, Tour Kit

#61702 Editor: Cache page view stats properties by props
  client/gutenberg/editor/calypsoify-iframe.tsx
Labels: [Type] Enhancement, Editor, [Status] Needs Review, Performance

#61703 Editor: Cache default and empty media data sources
  client/gutenberg/editor/media-utils.js
Labels: [Type] Enhancement, Editor, [Status] Needs Review, Media, Performance

#61704 Lib: Optimize route modal to avoid extra object recreation
  client/lib/route-modal/use-route-modal.tsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Performance

#61707 Notice: Optimize notices selector default values
  client/state/notices/selectors.js
Labels: [Type] Enhancement, Framework, [Status] Needs Review, State, Performance

#61708 Media: Optimize selected items selector when empty
  client/state/selectors/get-media-library-selected-items.js
Labels: [Type] Enhancement, [Status] Needs Review, Media, State, Performance

#61691 Jetpack Cloud: Add new FAQ about how to get started with Jetpack to Pricing page.
  client/my-sites/plans/jetpack-plans/faq/index.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#61759 Follow up for #61222: handle undefined `pageEntity`
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/seller-celebration-modal/index.jsx
Labels: [Pri] High, [Status] Needs Review, FSE

#61726 Marketplace: Adds Education Footer
  client/components/link-card/README.md
  client/components/link-card/docs/example.jsx
  client/components/link-card/index.tsx
  client/components/link-card/style.scss
  client/components/section/README.md
  client/components/section/docs/example.jsx
  client/components/section/index.tsx
  client/components/section/style.scss
  client/devdocs/design/index.jsx
  client/my-sites/plugins/education-footer/index.tsx
  client/my-sites/plugins/plugins-browser/index.jsx
Labels: [Status] Needs Review

#61745 Run full eslint when eslint packages update
  .teamcity/settings.kts
Labels: [Status] Needs Review

#61779 Marketplace: Education Footer Background Change and Hover State
  client/components/link-card/index.tsx
  client/components/section/index.tsx
Labels: [Status] Needs Review

#61751 Refactor user settings selectors to TS and remove lodash
  client/me/account/account-email-field.tsx
  client/state/selectors/get-unsaved-user-settings.js
  client/state/selectors/get-unsaved-user-settings.ts
  client/state/selectors/get-user-setting.js
  client/state/selectors/get-user-setting.ts
  client/state/selectors/get-user-settings.js
  client/state/selectors/get-user-settings.ts
Labels: [Status] Needs Review

#61757 Plans overhaul Phase 1: apply new design changes
  client/components/formatted-header/index.jsx
  client/jetpack-connect/test/__snapshots__/auth-form-header.js.snap
  client/my-sites/plan-price/index.jsx
  client/my-sites/plans-comparison/constant.ts
  client/my-sites/plans-comparison/index.tsx
  client/my-sites/plans-comparison/plans-comparison-col-header.tsx
  client/my-sites/plans-comparison/plans-comparison-features.tsx
  client/my-sites/plans-comparison/plans-comparison-row-header.tsx
  client/my-sites/plans-comparison/plans-comparison-row.tsx
  client/my-sites/plans-comparison/plans-comparison.tsx
  client/my-sites/plans/current-plan/index.jsx
  client/my-sites/plans/current-plan/purchases-listing.jsx
  client/my-sites/plans/main.jsx
  client/my-sites/plans/navigation.jsx
  client/signup/steps/plans/index.jsx
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review

#61768 Add dedicated page for changing account email below `/me/security`
  client/me/account/account-email-field.scss
  client/me/account/account-email-field.tsx
  client/me/security-account-email/index.tsx
  client/me/security-checkup/account-email.jsx
  client/me/security/controller.js
  client/me/security/index.js
Labels: [Status] Needs Review, Security

#61706 Guided Tours: Optimize defaults in selectors
  client/state/guided-tours/selectors/index.js
Labels: [Type] Enhancement, [Status] Needs Review, Guided Tours, State, Performance

#61763 State: Remove unused AT request status once state
  client/state/action-types.ts
  client/state/automated-transfer/actions.js
  client/state/automated-transfer/reducer.js
  client/state/data-layer/wpcom/sites/automated-transfer/status/index.js
Labels: [Status] Needs Review, [Type] Janitorial, State, Atomic Upgrade Flows

#61794 DIFM: Remove retired Glen and Antin themes
  client/signup/steps/difm-design-picker/themes.tsx
Labels: [Status] Needs Review, difm-lite

#61758 Redesigned DIFM New/Existing Site Step
  client/assets/images/difm/difm.svg
  client/assets/images/difm/existing-site-image.svg
  client/assets/images/difm/new-site-image.svg
  client/signup/icons/index.tsx
  client/signup/steps/new-or-existing-site/index.tsx
  client/signup/steps/new-or-existing-site/new-or-existing-site-choice.tsx
  client/signup/steps/new-or-existing-site/new-or-existing-site.tsx
  client/signup/steps/new-or-existing-site/style.scss
  client/signup/steps/new-or-existing-site/types.ts
Labels: [Status] Needs Review, difm-lite

#61766 Ensure we refetch account recovery data after reauthorizing
  client/lib/two-step-authorization/index.js
  client/state/account-recovery/settings/actions.js
Labels: [Status] Needs Review, Security, 2FA

#61792 Enable Security Checkup feature in development, horizon, and wpcalypso
  config/development.json
  config/horizon.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Me, Security

#61791 Consolidate data fetching in SecurityCheckup component
  client/me/security-checkup/account-email.jsx
  client/me/security-checkup/account-recovery-email.jsx
  client/me/security-checkup/account-recovery-phone.jsx
  client/me/security-checkup/index.jsx
  client/me/security-checkup/two-factor-authentication.jsx
  client/me/security-checkup/two-factor-backup-codes.jsx
Labels: [Status] Needs Review, Me, Security

#61804 Earn: Add a Tracks event to the Connect Stripe button
  client/my-sites/earn/memberships/index.jsx
Labels: [Status] Ready to Merge, Earn

#61810 Marketplace: Fixes Education Footer Links
  client/components/link-card/index.tsx
  client/my-sites/plugins/education-footer/index.tsx
Labels: [Status] Needs Review

#61780 CI: update list of pre-authenticated accounts for WPCOM tests.
  .teamcity/_self/projects/WPComTests.kt
Labels: [Status] Needs Review

#61787 Update Jetpack Pricing Page For Price Update
  client/components/jetpack/intro-pricing-banner/index.tsx
  client/my-sites/plans/jetpack-plans/product-grid/index.tsx
  client/my-sites/plans/jetpack-plans/use-item-price.ts
  client/state/selectors/get-best-intro-offer-discount.ts
  client/state/selectors/get-is-requesting-into-offers.ts
  client/state/sites/intro-offers/reducer.ts
  client/state/sites/intro-offers/test/reducer.ts
  client/state/sites/intro-offers/types.ts
Labels: [Type] Enhancement, [Status] Needs Review, [Size] S

#61786 Managed Plan: Allow sites to be moved to Atomic
  client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx
  client/state/marketplace/selectors.ts
  client/state/purchases/selectors/should-revert-atomic-site-before-deactivation.js
  client/state/selectors/is-site-on-atomic-plan.js
Labels: [Status] Needs Review, Atomic

#61770 Onboarding: move SelectItems to their own component
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/intents.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/style.scss
  client/signup/steps/import-from/wordpress/content-chooser/style.scss
  client/signup/steps/intent/intents.tsx
  client/signup/steps/site-or-domain/style.scss
  packages/calypso-e2e/src/lib/flows/start-import-flow.ts
  packages/onboarding/src/index.ts
  packages/onboarding/src/intent-screen/components/intent-screen-select-items/index.tsx
  packages/onboarding/src/intent-screen/index.ts
  packages/onboarding/src/intent-screen/index.tsx
  packages/onboarding/src/intent-screen/types.ts
  packages/onboarding/src/select-items-alt/README.md
  packages/onboarding/src/select-items-alt/index.tsx
  packages/onboarding/src/select-items-alt/style.scss
  packages/onboarding/src/select-items/README.md
  packages/onboarding/src/select-items/index.tsx
  packages/onboarding/src/select-items/style.scss
Labels: [Status] Needs Review, Packages

#61824 Update @wordpress/url to 3.3.2
  apps/editing-toolkit/package.json
  apps/wpcom-block-editor/package.json
  client/package.json
  package.json
  packages/data-stores/package.json
  packages/design-picker/package.json
  packages/launch/package.json
  yarn.lock
Labels: [Status] Needs Review

#61795 Adds feature flag for the redesigned DIFM flow
  client/signup/config/flows-pure.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, difm-lite

#61802 Improve mobile styles for security checkup menu
  client/me/security-checkup/style.scss
Labels: [Status] Needs Review, Me, Security

#61796 HackWeek: Add a banner in Stats page when the user has its site set to private
  client/my-sites/stats/site.jsx
  client/my-sites/stats/style.scss
Labels: HackWeek

#61636 Export types in @automattic/explat-client-react-helpers that are used in consumers
  packages/explat-client-react-helpers/CHANGELOG.md
  packages/explat-client-react-helpers/package.json
  packages/explat-client-react-helpers/src/index.tsx
Labels: [Status] Needs Review

#61830 DIFM: Updates subheader copy for the new/existing site step
  client/signup/steps/new-or-existing-site/index.tsx
Labels: [Status] Needs Review, difm-lite

#61540 Nav Unification: Remove old sidebar (part 2)
  client/blocks/site/index.jsx
  client/layout/masterbar/logged-in.jsx
  client/layout/sidebar/expandable.jsx
  client/me/account/main.jsx
  client/my-sites/current-site/index.jsx
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
  client/my-sites/theme/test/main.jsx
  client/state/selectors/get-preferred-editor-view.js
Labels: [Status] Needs Review, Nav Unification, 20percent

#61837 Jetpack Cloud: Backup - Introduce support links at the bottom of the "Backup Failed" card (aka Alert view)
  client/components/jetpack/daily-backup-status/status-card/backup-failed.jsx
  client/components/jetpack/daily-backup-status/status-card/backup-support-links.jsx
  client/components/jetpack/daily-backup-status/status-card/style.scss
Labels: [Status] Needs Review, Support, Jetpack Cloud, Jetpack Backup

#61755 IntentScreen: ( 1min review ) add readme
  packages/onboarding/src/intent-screen/README.md
Labels: [Status] Needs Review, Packages

#61568 Comments: Refactor `PostCommentList` away from `UNSAFE_` methods
  client/blocks/comments/post-comment-list.jsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Comments

#61832 Rename track event for domain-only upsell carousel card impression
  client/my-sites/domains/domain-management/list/domain-only-upsell-carousel.tsx
Labels: [Status] Needs Review, Domains

#61498 FSE: add theme activation notice
  client/my-sites/themes/test/thanks-modal.jsx
  client/my-sites/themes/thanks-modal.jsx
  client/my-sites/themes/thanks-modal.scss
Labels: [Status] Needs Review, [Status] String Freeze, [Goal] Full Site Editing

#61855 Payment Methods: Change getPaymentMethodSummary into a component
  client/jetpack-cloud/sections/partner-portal/payment-method-delete-dialog/index.tsx
  client/lib/checkout/payment-methods.tsx
  client/me/purchases/payment-methods/payment-method-delete.tsx
  client/me/purchases/payment-methods/payment-method-details.tsx
Labels: [Status] Needs Review, Payment Methods

#61857 Checkout: Move existing-credit-card payment method to calypso
  client/me/purchases/payment-methods/existing-credit-card.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-methods/use-create-existing-cards.ts
  packages/wpcom-checkout/src/index.ts
Labels: [Status] Needs Review, Checkout

#61866 Fix infinite loop in post comment list
  client/blocks/comments/post-comment-list.jsx
Labels: [Status] Needs Review

#61716 Add pre-purchase notices for Jetpack Anti-Spam and Scan
  client/my-sites/checkout/composite-checkout/components/prepurchase-notices/index.jsx
  client/state/sites/products/conflicts.ts
  client/state/sites/products/test/conflicts.ts
Labels: [Type] Enhancement, Jetpack, [Status] Needs Review, Checkout, [Size] S

#61901 Nav Unification: Remove old sidebar (part 3)
  client/layout/index.jsx
  client/my-sites/navigation/index.jsx
  client/my-sites/sidebar/constants.js
  client/my-sites/sidebar/index.jsx
  client/my-sites/sidebar/site-menu.jsx
  client/my-sites/sidebar/style.scss
  client/my-sites/sidebar/test/sidebar.js
  client/my-sites/sidebar/tools-menu.jsx
  client/state/selectors/is-nav-unification-enabled.js
Labels: [Status] Needs Review, Sidebar, Nav Unification

#61854 Full importer: Improved logic of showing install Jetpack button
  client/signup/steps/import-from/wordpress/content-chooser/index.tsx
Labels: [Status] Needs Review, Reindeer Pod

#61488 Add/import color flow
  client/signup/config/flows-pure.js
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
  client/signup/icons/index.tsx
  client/signup/steps/import-light/capture/capture-input.tsx
  client/signup/steps/import-light/capture/index.tsx
  client/signup/steps/import-light/capture/style.scss
  client/signup/steps/import-light/colors/index.tsx
  client/signup/steps/import-light/colors/style.scss
  client/signup/steps/import-light/index.tsx
  client/signup/steps/import-light/scanning/index.tsx
  client/signup/steps/import-light/scanning/style.scss
  client/signup/steps/import-light/style.scss
  client/signup/steps/import-light/summary/index.tsx
  client/signup/steps/import-light/summary/style.scss
  client/signup/steps/import/capture/index.tsx
  client/signup/steps/import/scanning/style.scss
  client/signup/steps/import/style.scss
  client/signup/steps/import/util.ts
  config/_shared.json
  config/development.json
  config/wpcalypso.json
  static/images/importer/onboarding-3.svg
Labels: [Status] Needs Review, Reindeer Pod

#61880 My Profile: add sub-header with inline support link
  client/components/inline-support-link/context-links.js
  client/me/account/main.jsx
  client/me/profile/index.jsx
Labels: [Status] Needs Review, Support

#61906 Fix Sidebar Scroll synchronizer
  client/layout/index.jsx
Labels: [Status] Needs Review, Sidebar, Nav Unification, 20percent

#61175 Site Settings: refactor and update support links
  client/my-sites/site-settings/composing/index.jsx
  client/my-sites/site-settings/composing/latex.jsx
  client/my-sites/site-settings/composing/markdown.jsx
  client/my-sites/site-settings/composing/shortcodes.jsx
  client/my-sites/site-settings/custom-content-types/blog-posts.jsx
  client/my-sites/site-settings/custom-content-types/index.jsx
  client/my-sites/site-settings/custom-content-types/portfolios.jsx
  client/my-sites/site-settings/custom-content-types/testimonials.jsx
  client/my-sites/site-settings/form-writing.jsx
  client/my-sites/site-settings/masterbar.jsx
  client/my-sites/site-settings/media-settings-performance.jsx
  client/my-sites/site-settings/media-settings-writing.jsx
  client/my-sites/site-settings/press-this/index.jsx
  client/my-sites/site-settings/publishing-tools/index.jsx
  client/my-sites/site-settings/speed-up-site-settings.jsx
  client/my-sites/site-settings/theme-enhancements.jsx
  client/my-sites/site-settings/widgets.jsx
Labels: Site Settings, [Status] Needs Review

#61813 Try add missing learn more links
  client/components/inline-support-link/context-links.js
  client/my-sites/people/main.jsx
  client/my-sites/people/people-invites/index.jsx
  client/my-sites/site-settings/settings-performance/main.jsx
Labels: [Status] Needs Review

#61807 Stepper Flow: Export step container
  client/landing/stepper/declarative-flow/internals/steps-repository/build.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domain.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/sell.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-options/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/step-layouts/horizontal-layout.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/wpadmin.tsx
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  packages/onboarding/src/index.ts
  packages/onboarding/src/step-container/index.tsx
  packages/onboarding/src/step-container/style.scss
  packages/onboarding/src/step-navigation-link/index.tsx
  packages/onboarding/src/step-navigation-link/style.scss
Labels: [Status] Needs Review, Signup

#61577 Checkout: Fix and Improve Jetpack Pre-Purchase Notices
  client/my-sites/checkout/composite-checkout/components/prepurchase-notices/cart-plan-overlaps-owned-product-notice.tsx
  client/my-sites/checkout/composite-checkout/components/prepurchase-notices/index.jsx
  client/my-sites/checkout/composite-checkout/components/prepurchase-notices/site-plan-includes-cart-product-notice.tsx
  client/state/sites/products/conflicts.ts
  client/state/sites/products/test/conflicts.ts
Labels: [Type] Bug, Jetpack, [Status] Needs Review, [Status] Ready to Merge, Checkout, [Size] M

#61852 Remove disabled actions from `DnsRecordsListItem`
  client/lib/url/support.js
  client/my-sites/domains/domain-management/dns/dns-record-data.jsx
  client/my-sites/domains/domain-management/dns/dns-records-list-item.jsx
  client/my-sites/domains/domain-management/dns/dns-records-list.jsx
Labels: [Status] Needs Review, Domains

#61816 Add Wrapper around Cart Variant Picker
  client/my-sites/checkout/composite-checkout/components/item-variation-picker/index.tsx
  client/my-sites/checkout/composite-checkout/components/item-variation-picker/item-variation-radio-buttons.tsx
  client/my-sites/checkout/composite-checkout/components/item-variation-picker/types.ts
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
Labels: [Status] Needs Review, [Size] S, Shopping Cart

#61860 Licensing Portal: Update position of the placeholder card for adding new payment method
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-list/index.tsx
Labels: [Status] Ready to Merge

#61865 Domains: Update conditions to show domain renew elements
  client/lib/domains/resolve-domain-status.tsx
  client/my-sites/domains/domain-management/list/domain-row.jsx
  client/my-sites/domains/domain-management/settings/cards/registered-domain-details.tsx
Labels: [Status] Needs Review, Domains

#61951 Emails: Remove discount star from Google Workspace section in Email Comparison page
  client/my-sites/email/email-providers-comparison/email-provider-card.jsx
  client/my-sites/email/email-providers-comparison/index.jsx
  client/my-sites/email/email-providers-comparison/style.scss
Labels: [Status] Needs Review, G Suite

#61678 Onboarding import module: Reorganize base/common styles inside the package
  client/signup/steps/import-from/index.tsx
  client/signup/steps/import-from/style.scss
  client/signup/steps/import-light/style.scss
  client/signup/steps/import/style.scss
  client/signup/steps/import/style/base.scss
  client/signup/steps/import/style/components.scss
  client/signup/steps/import/style/mixins.scss
Labels: [Status] Needs Review, Reindeer Pod

#61905 Emails: Remove old email-home.jsx component
  client/my-sites/email/email-management/email-home.jsx
Labels: [Status] Needs Review

#61919 India Hotjar survey: Batch 3 questions launched in the editor
  client/gutenberg/editor/calypsoify-iframe.tsx
  client/my-sites/customer-home/main.jsx
  client/state/selectors/is-user-registration-days-within-range.js
Labels: [Status] Needs Review

#61741 Jetpack Licensing Portal: License assignment step progress component
  client/jetpack-cloud/sections/partner-portal/assign-license-step-progress/index.tsx
  client/jetpack-cloud/sections/partner-portal/assign-license-step-progress/style.scss
  client/jetpack-cloud/sections/partner-portal/primary/assign-license/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/issue-license/index.tsx
Labels: [Type] Enhancement, [Status] Needs Review, Jetpack Cloud, Jetpack Licensing Portal

#61828 Purchases: Refactor `CancelPurchase` away from `UNSAFE_` methods
  client/me/purchases/cancel-purchase/index.jsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Purchases

#61808 Payments Inserter Tracking: Added support for Payment Inserter block
  apps/wpcom-block-editor/src/wpcom/features/tracking.js
Labels: [Status] Ready to Merge

#61930 Retrieve the featured list of plugins from WPCOM '/plugins/featured' namespace.
  client/data/marketplace/use-wpcom-plugins-query.ts
  client/my-sites/plugins/plugins-browser/index.jsx
  packages/calypso-e2e/src/lib/pages/plugins-page.ts
  test/e2e/specs/plugins/plugins__browse.ts
Labels: [Status] Needs Review

#61960 Seller Experience: Fix action button for contextual Payments doc
  client/blocks/inline-help/constants.js
  client/blocks/inline-help/contextual-help.js
Labels: [Status] Needs Review, Seller Experience

#61669 Playwright: refactor `EditorSettingsSidebarComponent` to use FrameLocator.
  packages/calypso-e2e/src/lib/components/editor-settings-sidebar-component.ts
  packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts
  packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
  test/e2e/specs/editor/editor__page-basic-flow.ts
  test/e2e/specs/editor/editor__post-basic-flow.ts
  test/e2e/specs/editor/editor__revisions.ts
  test/e2e/specs/editor/editor__schedule.ts
  test/e2e/specs/editor/shared/privacy-testing.ts
Labels: [Status] Needs Review

#61723 Calypso apps: build meta json file with cache buster
  .teamcity/_self/lib/wpcom/WPComPluginBuild.kt
  .teamcity/_self/projects/WPComPlugins.kt
  apps/happychat/webpack.config.js
  apps/inline-help/webpack.config.js
  apps/notifications/webpack.config.js
  apps/wpcom-block-editor/webpack.config.js
  packages/calypso-apps-builder/build-meta-webpack-plugin.cjs
  packages/calypso-apps-builder/build_meta_template.txt
  packages/calypso-apps-builder/package.json
  yarn.lock
Labels: [Status] Needs Review

#61939 Add more branch names to lint test in TeamCity
  .teamcity/settings.kts
Labels: [Status] Needs Review

#61929 Refactor Variant Item Rendering
  client/my-sites/checkout/composite-checkout/components/item-variation-picker/item-variation-radio-buttons.tsx
  client/my-sites/checkout/composite-checkout/components/item-variation-picker/types.ts
  client/my-sites/checkout/composite-checkout/components/item-variation-picker/variant-price.tsx
  client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx
Labels: [Status] Needs Review, [Size] M, Shopping Cart

#61966 Playwright: update TODO verbiage
  packages/calypso-e2e/src/env-variables.ts
Labels: [Status] Needs Review

#61969 Fix calypso app build issue where normalizer couldn't access build meta
  .teamcity/_self/lib/wpcom/WPComPluginBuild.kt
Labels: [Status] Needs Review

#61967 Change the default branch in Kotlin DSL to force update.
  .teamcity/settings.kts
Labels: [Status] Needs Review

#61968 Restore default branch in Kotlin DSL.
  .teamcity/settings.kts
Labels: [Status] Needs Review

#61835 DIFM Lite: Adds state slice for social profiles
  client/state/action-types.ts
  client/state/difm/init.js
  client/state/difm/package.json
  client/state/difm/reducer.ts
  client/state/difm/social-profiles/actions.ts
  client/state/difm/social-profiles/reducer.ts
  client/state/difm/social-profiles/schema.ts
  client/state/difm/social-profiles/selectors.ts
  client/state/difm/social-profiles/test/reducer.js
  client/state/difm/social-profiles/test/selectors.js
Labels: [Status] Needs Review, difm-lite

#61971 Dummy change to trigger TeamCity build
  .teamcity/_self/lib/utils/MergeTrunk.kt
Labels: [Status] Needs Review
