Repository Automattic/wp-calypso, pull requests merged in 2022-11, with the labels that each got.

#69549 Generated designs: Update how generated designs are displayed to users
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/categories.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/test/unified-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  packages/design-picker/src/components/style.scss
  packages/design-picker/src/components/unified-design-picker.tsx
  packages/design-picker/src/constants.ts
  packages/design-picker/src/hooks/use-categorization.ts
Labels: [Status] Needs Review

#69560 Pattern Assembler - Show selected pattern when replacing it
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector-loader.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/style.scss
Labels: [Status] Needs Review

#69611 Pattern Assembler - Delayed pattern previews to use the API cache
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/delayed-render-hook.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx
Labels: [Status] Needs Review

#69605 Agency Dashboard: Make the Add button selectable
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-table-row/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-table-row/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/utils.ts
  client/state/jetpack-agency-dashboard/action-types.js
  client/state/jetpack-agency-dashboard/actions.ts
  client/state/jetpack-agency-dashboard/reducer.ts
  client/state/jetpack-agency-dashboard/selectors.ts
Labels: [Status] Needs Review, Jetpack Cloud

#69613 Pattern Assembler: Update Home template if it's existed
  packages/data-stores/src/site/actions.ts
Labels: [Status] Needs Review

#69388 Add new newsletter intro content
  client/assets/images/onboarding/newsletter-intro-bottom-mobile.png
  client/assets/images/onboarding/newsletter-intro-bottom.png
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/intro.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/styles.scss
  packages/onboarding/src/step-container/index.tsx
  packages/onboarding/src/step-container/style.scss
Labels: [Status] Needs Review, [Status] String Freeze, Stepper, Tailored Flows

#69654 Jetpack Cloud Pricing | Fix client-side redirect on initial load
  client/my-sites/plans/jetpack-plans/product-store/index.tsx
Labels: [Type] Bug, [Status] Needs Review

#68563 Tailored Flows: Replace Calypso input fields with Wordpress/TextControl
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/components/setup-form/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/components/setup-form/style.scss
Labels: [Status] Needs Review, Signup, Stepper, Tailored Flows

#69061 TailoredFlows: Patterns step take available space for small devices
  client/landing/stepper/declarative-flow/internals/steps-repository/patterns/styles.scss
  packages/pattern-picker/src/index.tsx
  packages/pattern-picker/src/styles.scss
Labels: [Status] Needs Review

#69653 Agency Dashboard: Add issue license and cancel buttons
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/utils.ts
Labels: [Status] Needs Review, Jetpack Cloud

#69183 Partner Portal: add react-query mutation to handle assigning multiple licenses flow
  client/jetpack-cloud/sections/partner-portal/hooks.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#69556 E2E (Atomic): Fix Jetpack Earn
  packages/calypso-e2e/src/lib/blocks/block-flows/pay-with-paypal.ts
  test/e2e/specs/blocks/blocks__jetpack-earn.ts
Labels: [Status] Needs Review

#69494 Checkout: Add biennial plan upsell to sidebar
  client/components/promo-section/promo-card/cta.tsx
  client/my-sites/checkout/composite-checkout/components/checkout-sidebar-plan-upsell/index.tsx
  client/my-sites/checkout/composite-checkout/components/checkout-sidebar-plan-upsell/style.scss
  client/my-sites/checkout/composite-checkout/components/item-variation-picker/variant-price.tsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
  client/my-sites/checkout/composite-checkout/test/composite-checkout-variant-picker.tsx
Labels: [Status] Needs Review, Checkout

#69638 Receipts: Explicitly handle arrays when flattening in assembler
  client/state/receipts/assembler.ts
Labels: [Status] Needs Review

#69501 Atomic Revival: Display My Home notices for all three stages of revival
  client/components/inline-support-link/index.jsx
  client/my-sites/customer-home/cards/constants.js
  client/my-sites/customer-home/cards/tasks/reactivate-expired-plan/index.tsx
  client/my-sites/customer-home/cards/tasks/revive-auto-reverted-atomic/index.tsx
  client/my-sites/customer-home/cards/tasks/style.scss
  client/my-sites/customer-home/cards/tasks/task.tsx
  client/my-sites/customer-home/locations/primary/index.jsx
Labels: [Status] Needs Review, Atomic Revival i1

#69462 Replace No Ads upsell Nudge with Premium plan nudge
  client/lib/plans/features-list.js
  client/my-sites/add-ons/hooks/use-add-ons.ts
  client/my-sites/add-ons/icons/no-ads.tsx
  client/my-sites/add-ons/icons/unlimited-themes.tsx
  client/my-sites/marketing/main.jsx
Labels: [Status] Needs Review

#69590 WooCommerce Tailored Flow: Added design carousel component and step
  client/landing/stepper/declarative-flow/internals/steps-repository/design-carousel/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
  client/landing/stepper/declarative-flow/tailored-ecommerce-flow.ts
  package.json
  packages/design-carousel/.eslintrc.js
  packages/design-carousel/package.json
  packages/design-carousel/src/index.tsx
  packages/design-carousel/src/item.tsx
  packages/design-carousel/src/styles.scss
  packages/design-carousel/src/swiper.d.ts
  packages/design-carousel/tsconfig-cjs.json
  packages/design-carousel/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review, Stepper

#69659 Fix issue with missing Follower role for the private site
  client/my-sites/people/invite-people/index.jsx
Labels: [Status] Needs Review, Subscriber Importer

#69649 Stats: Fix chart rendering and adjust period header content
  client/components/chart/index.jsx
  client/my-sites/stats/stats-chart-tabs/index.jsx
  client/my-sites/stats/stats-chart-tabs/style.scss
  client/my-sites/stats/stats-date-picker/index.jsx
  client/my-sites/stats/stats-period-navigation/style.scss
  client/my-sites/stats/wordads-chart-tabs/index.jsx
Labels: Stats, [Status] Needs Review

#69652 Update import to fix deprecation warning
  apps/wpcom-block-editor/src/default/features/rich-text.js
Labels: [Status] Needs Review

#69595 Hide "Edit" and "Remove" buttons from the checkout line item when rendered in a Woo mobile webview
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
  client/my-sites/checkout/composite-checkout/test/composite-checkout-variant-picker.tsx
  client/my-sites/checkout/composite-checkout/test/util/index.ts
Labels: [Status] Needs Review

#69154 Fix block-inserted-events e2e testing
  packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts
  test/e2e/specs/editor-tracking/editor-tracking__block-inserted-event.ts
Labels: [Status] Needs Review

#69637 Marketplace: Show Gifting Toggle when Auto-Renew is off
  client/my-sites/site-settings/form-general.jsx
Labels: [Status] Needs Review

#69656 Fix pattern assembler CTA vertical spacing
  packages/design-picker/src/components/style.scss
Labels: [Status] Needs Review

#69678 Atomic Revival: Use dark variant of illustration for urgent atomic revival tasks
  client/my-sites/customer-home/cards/tasks/revive-auto-reverted-atomic/index.tsx
Labels: [Status] Needs Review, Customer Home, Atomic Revival i1

#69614 DIFM Website Content: Fetch data from new endpoint
  client/signup/steps/website-content/index.tsx
  client/signup/steps/website-content/use-poll-site-for-difm-details.ts
Labels: [Status] Needs Review

#69621 BBE : Onboarding : Page Picker : Remove extra pages feature flag and related code
  client/lib/signup/step-actions/index.js
  client/signup/difm/constants.tsx
  client/signup/steps/page-picker/index.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#69557 Update the Educational Footer design
  client/components/feature-item/index.tsx
  client/components/section/index.tsx
  client/my-sites/plugins/education-footer/index.tsx
Labels: [Status] Needs Review

#69655 Enable SSR for Plugins Category pages
  client/my-sites/plugins/controller-logged-out.js
  client/my-sites/plugins/controller.js
  client/my-sites/plugins/index.node.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#69618 Switch the dialog backdrop to dark in blazepress modal
  client/components/blazepress-widget/index.tsx
  client/components/blazepress-widget/style.scss
Labels: [Status] Needs Review

#69684 DIFM Landing: Cleanup after pricing test
  client/my-sites/marketing/do-it-for-me/difm-landing.tsx
Labels: [Status] Needs Review

#69576 Third-Party Premium Themes: Externally Managed theme should be available only when purchased
  client/state/themes/selectors/is-premium-theme-available.js
  client/state/themes/test/selectors.js
Labels: [Status] Needs Review

#69697 DIFM Landing: Fixes price not showing if stored currency is null
  client/my-sites/marketing/do-it-for-me/difm-landing.tsx
Labels: [Status] Needs Review

#69514 BBE: Copy changes for DIFM to BBE rebrand
  client/blocks/site/index.jsx
  client/my-sites/marketing/do-it-for-me/difm-landing.tsx
  client/signup/steps/new-or-existing-site/index.tsx
  client/signup/steps/new-or-existing-site/style.scss
Labels: [Status] Needs Review, DO NOT MERGE, BuiltByExpress

#69669 Licensing Portal: add new license multi-selection page
  client/jetpack-cloud/sections/partner-portal/issue-multiple-licenses-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/issue-multiple-licenses-form/style.scss
  client/jetpack-cloud/sections/partner-portal/issue-multiple-licenses-form/types.ts
  client/jetpack-cloud/sections/partner-portal/primary/issue-license/index.tsx
  client/state/partner-portal/licenses/hooks/use-products-query.ts
  client/state/partner-portal/licenses/test/hooks.js
  client/state/partner-portal/types.ts
Labels: [Status] Needs Review, [Size] M, Jetpack Cloud

#69701 Update Gifting settings toggle texts
  client/my-sites/site-settings/form-general.jsx
Labels: [Status] Needs Review

#69634 Woo Tailored Onboarding: Add intro/login and store profiler steps
  client/assets/images/onboarding/ecommerce-intro-1.jpg
  client/assets/images/onboarding/ecommerce-intro-2.jpg
  client/assets/images/onboarding/ecommerce-intro-3.jpg
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/store-profiler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/store-profiler/style.scss
  client/landing/stepper/declarative-flow/tailored-ecommerce-flow.ts
  client/landing/stepper/index.tsx
  packages/onboarding/src/utils/flows.ts
Labels: [Status] Needs Review, Seller Experience, Tailored Flows

#69707 Update Gifting settings toggle WordPress.com text
  client/my-sites/site-settings/form-general.jsx
Labels: [Status] Needs Review

#69709 Insights: Show Tags & Categories section for Jetpack sites
  client/my-sites/stats/stats-insights/index.jsx
Labels: Stats, Jetpack

#69580 Add Hotjar to Signup flow
  client/signup/main.jsx
Labels: [Status] Needs Review

#69460 WPCOM SSH: Add reauth form to hosting config page to display ssh keys when cookie expire
  client/me/reauth-required/index.jsx
  client/my-sites/hosting/sftp-card/index.js
  client/my-sites/hosting/sftp-card/test/index.js
Labels: [Status] Needs Review, 2FA, WPCOM SSH i2

#69640 Stats: Add 7-day highlights to the traffic page
  client/my-sites/stats/highlights-section/index.tsx
  client/my-sites/stats/site.jsx
  client/state/action-types.ts
  client/state/data-layer/wpcom/sites/stats/highlights/index.ts
  client/state/data-layer/wpcom/sites/stats/index.js
  client/state/stats/highlights/actions.ts
  client/state/stats/highlights/reducer.ts
  client/state/stats/highlights/schema.ts
  client/state/stats/highlights/selectors.ts
  client/state/stats/reducer.js
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  packages/components/src/highlight-cards/highlight-card.tsx
  packages/components/src/highlight-cards/index.tsx
  packages/components/src/highlight-cards/style.scss
Labels: [Type] Enhancement, Stats, [Status] Needs Review

#69691 Update tasks to allow navigation back to launchpad
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
Labels: [Status] Needs Review

#69642 Site Editor: Add document actions dropdown tracks events
  apps/wpcom-block-editor/src/wpcom/features/tracking/delegate-event-tracking.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-site-editor-document-actions-dropdown-click.js
Labels: [Status] Needs Review, [Goal] Full Site Editing

#69719 Jetpack pricing: add link to GDPR page to FAQ
  client/my-sites/plans/jetpack-plans/faq/index.tsx
Labels: Jetpack Cloud, [Size] XS

#69714 Jetpack pricing: add link to GDPR page to footer
  client/jetpack-cloud/sections/pricing/jpcom-footer/index.tsx
Labels: Jetpack Cloud, [Size] XS

#69545 Stats: Swapping Posts & pages component
  client/my-sites/stats/stats-list/stats-list-actions.jsx
  client/my-sites/stats/stats-list/stats-list-posts.jsx
  client/my-sites/stats/stats-list/style.scss
  client/my-sites/stats/stats-module/index.jsx
  client/my-sites/stats/stats-module/style.scss
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  packages/components/src/horizontal-bar-list/horizontal-bar-grid-item.tsx
  packages/components/src/horizontal-bar-list/index.tsx
  packages/components/src/horizontal-bar-list/stats-card.scss
  packages/components/src/horizontal-bar-list/stats-card.tsx
  packages/components/src/horizontal-bar-list/style.scss
  packages/components/src/horizontal-bar-list/types.ts
Labels: Stats, [Status] Needs Review

#67706 /plugins: Integrate the LOHP footer section
  client/layout/logged-out.jsx
  client/layout/universal-navbar-footer-automattic/index.tsx
  client/layout/universal-navbar-footer-automattic/style.scss
  client/layout/universal-navbar-footer/index.tsx
  client/layout/universal-navbar-footer/style.scss
Labels: [Status] Needs Review, [Status] String Freeze

#69645 Provide `themeSlugWithRepo` and `comingSoon` prop from the step data definition.
  client/signup/config/steps-pure.js
  client/signup/steps/plans/index.jsx
Labels: [Status] Needs Review

#69681 Pattern Assembler: Avoid uniquifying the slug of newly created Home template
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  packages/data-stores/src/site/actions.ts
Labels: [Status] Needs Review

#69482 Improve cancellation flow (revived)
  client/components/marketing-survey/cancel-purchase-form/cancellation-reasons.ts
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/precancellation-chat-button/index.jsx
  client/components/marketing-survey/cancel-purchase-form/precancellation-chat-button/style.scss
  client/components/marketing-survey/cancel-purchase-form/step-components/feedback-step.tsx
  client/components/marketing-survey/cancel-purchase-form/step-components/next-adventure-step.tsx
  client/components/marketing-survey/cancel-purchase-form/step-components/upsell-step.tsx
  client/components/marketing-survey/cancel-purchase-form/steps.js
  client/components/marketing-survey/cancel-purchase-form/style.scss
  client/components/marketing-survey/cancel-purchase-form/to-select-options.ts
Labels: Plans, [Status] Needs Review, Domains, Purchases, [Status] String Freeze

#69377 Add contextual trigger for Backup add-on products
  client/components/backup-storage-space/hooks.tsx
  client/components/backup-storage-space/index.tsx
  client/components/backup-storage-space/style.scss
  client/components/backup-storage-space/test/hooks.js
  client/components/backup-storage-space/usage-warning/action-button.tsx
  client/components/backup-storage-space/usage-warning/index.tsx
  client/components/backup-storage-space/usage-warning/manage-storage.tsx
  client/components/backup-storage-space/usage-warning/style.scss
  client/components/backup-storage-space/usage-warning/upsell.tsx
  client/components/backup-storage-space/usage-warning/use-upsell-slug.ts
  client/my-sites/backup/main.jsx
  client/my-sites/plans/current-plan/index.jsx
  packages/calypso-products/src/constants/jetpack.ts
  packages/calypso-products/src/products-list.ts
  packages/calypso-products/src/translations.tsx
  packages/components/src/product-icon/config.ts
  packages/components/src/product-icon/images/jetpack-backup-addon.svg
Labels: [Status] Needs Review, DO NOT MERGE

#69699 Enable SSR for Plugins Detail page
  client/data/marketplace/use-wpcom-plugins-query.ts
  client/lib/plugins/utils.js
  client/my-sites/plugins/controller-logged-out.js
  client/my-sites/plugins/index.node.js
  client/server/render/index.js
  client/state/plugins/wporg/reducer.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#69728 Signup: Fixes styling for plans-site-selected step
  client/signup/steps/plans/style.scss
  client/signup/style.scss
Labels: Plans, [Status] Needs Review, Signup

#69488 Translate label and description of the Featured image email toggle
  client/my-sites/site-settings/featured-image-toggle.jsx
  client/my-sites/site-settings/form-writing.jsx
Labels: Featured Image Template Toggle

#69738 Atomic Revival: Switch 'Renew the Plan' to 'Renew Your Plan'
  client/my-sites/customer-home/cards/tasks/revive-auto-reverted-atomic/index.tsx
Labels: [Type] Task, Atomic Revival i1

#69619 Components: Refactor `SitesDropdown` tests to RTL
  client/components/sites-dropdown/test/index.js
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Components, Testing

#69561 Stepper: make the flowname part of the pathname
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/test/unified-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer/hooks/use-step-navigator.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/importer/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/launchpad-site-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/woo-confirm/index.tsx
  client/landing/stepper/declarative-flow/link-in-bio-post-setup.ts
  client/landing/stepper/declarative-flow/link-in-bio.ts
  client/landing/stepper/declarative-flow/newsletter-post-setup.ts
  client/landing/stepper/declarative-flow/newsletter.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  client/landing/stepper/hooks/use-capture-flow-exception.ts
  client/landing/stepper/hooks/use-flow-param.ts
  client/landing/stepper/index.tsx
  client/my-sites/importer/error-pane.jsx
  client/my-sites/themes/theme-options.js
  client/signup/config/flows-pure.js
  client/signup/steps/intent/index.tsx
  client/utils.ts
  packages/calypso-e2e/src/lib/flows/start-import-flow.ts
  packages/onboarding/src/utils/flows.ts
  test/e2e/specs/onboarding/ftme__sell.ts
  test/e2e/specs/onboarding/ftme__write.ts
  test/e2e/specs/onboarding/setup__build.ts
Labels: [Status] Needs Review

#69713 Theme Subscriptions: Add third-party theme options to the theme kebab menu
  client/my-sites/theme/main.jsx
  client/my-sites/themes/theme-options.js
  client/my-sites/themes/themes-selection.jsx
Labels: [Status] Needs Review, Subscriptions, Theme Showcase

#69492 Update mentions of "site stats" with "Jetpack Stats" (retry attempt)
  client/blocks/disconnect-jetpack/index.jsx
  client/blocks/jetpack-benefits/site-visits.tsx
  client/lib/plans/features-list.js
  client/my-sites/plans/jetpack-plans/jetpack-free-card/index.tsx
  client/my-sites/site-settings/analytics/form-google-analytics-jetpack.jsx
  client/my-sites/site-settings/analytics/form-google-analytics-simple.jsx
  client/my-sites/site-settings/jetpack-site-stats.jsx
  client/my-sites/stats/site.jsx
Labels: Stats, [Status] Ready to Merge, [Status] String Freeze

#69761 themes: thanks-modal: Update the plugin bundle redirect url
  client/my-sites/themes/thanks-modal.jsx
Labels: [Status] Needs Review

#69676 Stats: Add annual highlights to insights page
  client/my-sites/stats/annual-highlights-section/index.tsx
  client/my-sites/stats/annual-highlights-section/style.scss
  client/my-sites/stats/highlights-section/index.tsx
  client/my-sites/stats/stats-insights/index.jsx
  client/my-sites/stats/stats-shares/index.jsx
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  packages/components/src/highlight-cards/annual-highlight-cards.tsx
  packages/components/src/highlight-cards/stories/index.stories.jsx
  packages/components/src/highlight-cards/style.scss
  packages/components/src/index.ts
Labels: [Type] Enhancement, Stats, [Status] Needs Review

#66049 Global Styles Tracking: Customize debounce function
  apps/wpcom-block-editor/src/wpcom/features/utils.js
Labels: [Status] In Progress, [Status] Needs Review

#69643 Checkout: Remove edit button and show only longer term variants
  client/lib/use-stable-callback/index.ts
  client/my-sites/checkout/composite-checkout/components/item-variation-picker/types.ts
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
  client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx
  client/my-sites/checkout/composite-checkout/test/composite-checkout-variant-picker.tsx
  client/my-sites/checkout/composite-checkout/test/util/index.ts
  packages/shopping-cart/src/types.ts
Labels: Checkout

#69765 Stats: Add title link to the Annual Highlights section
  client/my-sites/stats/annual-highlights-section/index.tsx
  packages/components/src/highlight-cards/annual-highlight-cards.tsx
  packages/components/src/highlight-cards/style.scss
Labels: [Type] Enhancement, Stats, [Status] Needs Review

#69725 Update license assignment page
  client/jetpack-cloud/sections/partner-portal/assign-license-form/index.tsx
Labels: [Status] Needs Review

#69766 Checkout: show biennial nudge for 'en' locale
  client/my-sites/checkout/composite-checkout/components/checkout-sidebar-plan-upsell/index.tsx
Labels: [Status] Needs Review, Checkout

#69743 Stats: Update Ads main chart styling
  client/my-sites/stats/modernized-chart-tabs-styles.scss
  client/my-sites/stats/wordads-chart-tabs/index.jsx
  client/my-sites/stats/wordads/index.jsx
  client/my-sites/stats/wordads/style.scss
Labels: Stats, [Status] Needs Review

#69702 Support 'disassociated' retired themes
  client/my-sites/theme/main.jsx
  client/my-sites/theme/style.scss
Labels: [Status] String Freeze

#69745 E2E (Atomic): Fix Jetpack Other
  packages/calypso-e2e/src/lib/blocks/block-flows/slideshow.ts
  packages/calypso-e2e/src/lib/blocks/block-flows/tiled-gallery.ts
Labels: [Status] Needs Review

#69762 Fix minor reader feed alignment issue
  client/blocks/reader-post-card/style.scss
Labels: [Status] Needs Review, Reader

#69720 Licensing Portal: create new component for bundles (Security and Complete)
  client/jetpack-cloud/sections/partner-portal/issue-multiple-licenses-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-bundle-card-description/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-bundle-card-description/style.scss
  client/jetpack-cloud/sections/partner-portal/license-bundle-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-bundle-card/style.scss
  client/jetpack-cloud/sections/partner-portal/license-product-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/utils.ts
Labels: [Status] Needs Review, [Status] String Freeze, [Size] M, Jetpack Cloud

#69790 Revert "Licensing Portal: create new component for bundles (Security and Complete)"
  client/jetpack-cloud/sections/partner-portal/issue-multiple-licenses-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-bundle-card-description/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-bundle-card-description/style.scss
  client/jetpack-cloud/sections/partner-portal/license-bundle-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-bundle-card/style.scss
  client/jetpack-cloud/sections/partner-portal/license-product-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/utils.ts
Labels: [Status] Needs Review

#69742 Plugins: Update the get started link on the footer to have a business plan selected
  client/my-sites/plugins/education-footer/index.tsx
Labels: [Status] Needs Review

#69792 Licensing Portal: create new component for bundles (Security and Complete) V2
  client/jetpack-cloud/sections/partner-portal/issue-multiple-licenses-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-bundle-card-description/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-bundle-card-description/style.scss
  client/jetpack-cloud/sections/partner-portal/license-bundle-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-bundle-card/style.scss
  client/jetpack-cloud/sections/partner-portal/license-product-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/utils.ts
Labels: [Status] Needs Review, [Size] M, Jetpack Cloud

#69751 Fix alignment of accent color dropdown color swatch & label
  client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/style.scss
Labels: [Status] Needs Review

#69748 Adds `product` post type to the promoted posts tool
  client/lib/promote-post/index.ts
  client/lib/user/shared-utils/filter-user-object.js
  client/lib/user/user.d.ts
  client/my-sites/promote-post/main.tsx
  client/my-sites/promote-post/utils/index.ts
Labels: [Status] Needs Review

#69667 Rename View to Promote
  client/my-sites/stats/stats-list/action-promote.jsx
Labels: [Status] Needs Review

#69594 Avoid logging static requests in dev mode
  client/server/lib/is-static-request/index.ts
  client/server/lib/is-static-request/test/index.js
  client/server/middleware/logger.js
  client/server/middleware/profiler.js
  client/server/middleware/test/logger.js
Labels: [Status] Needs Review

#69446 Draft of Notifications: Trash e2e fix utilizing REST API
  packages/calypso-e2e/src/lib/components/notifications-component.ts
  packages/calypso-e2e/src/rest-api-client.ts
  packages/calypso-e2e/src/types/rest-api-client.types.ts
  test/e2e/specs/infrastructure/notification__actions.ts
  test/e2e/specs/infrastructure/notifications__trash.ts
Labels: [Status] Ready to Merge

#69807 Support: Ensure chat closure notice shows for eligible users
  client/me/help/help-contact/index.jsx
  packages/help-center/src/components/help-center-contact-page.tsx
Labels: [Status] Needs Review

#69730 BBE: Enable for WoA sites
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/intents.tsx
  client/signup/steps/difm-site-picker/index.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#69780 Pattern Assembler - Redirection to start the flow from the first step
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
Labels: [Status] Needs Review

#69651 Marketplace: Redirect to vendor return url after the checkout
  client/my-sites/checkout/checkout-thank-you/pending/index.tsx
  client/my-sites/checkout/composite-checkout/lib/pending-page.ts
  client/my-sites/checkout/composite-checkout/test/pending-page.ts
  client/state/receipts/assembler.ts
  client/state/receipts/test/assembler.js
  client/state/receipts/types.ts
Labels: [Status] Needs Review, Marketplace, Marketplace SaaS Licensing

#69814 Pattern Assembler - Enable signup/design-picker-pattern-assembler on Horizon
  config/horizon.json
Labels: [Status] Needs Review

#69810 Stats: Recover Traffic nested bar charts behind the new main chart feature
  client/my-sites/stats/modernized-chart-tabs-styles.scss
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-chart-tabs/index.jsx
  client/my-sites/stats/stats-chart-tabs/style.scss
Labels: Stats, [Status] Needs Review

#69077 Hide write button in masterbar for Ecommerce plan
  client/layout/masterbar/logged-in.jsx
Labels: [Status] Needs Review

#69809 Agency Dashboard: Do not trigger API requests to the /test-connection endpoint on window refocus
  client/data/agency-dashboard/use-fetch-test-connection.ts
Labels: [Status] Needs Review, Jetpack Cloud

#69784 Deploy winning variant BBE copy in the goals screen
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/goals.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/select-goals.tsx
  client/lib/signup/step-actions/index.js
Labels: [Status] Needs Review, BuiltByExpress

#69769 Checkout: add renewal gift route
  client/my-sites/checkout/checkout-main-wrapper.tsx
  client/my-sites/checkout/composite-checkout/components/checkout-main.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-add-products-from-url.ts
  client/my-sites/checkout/composite-checkout/hooks/use-prepare-products-for-cart.ts
  client/my-sites/checkout/controller.jsx
  client/my-sites/checkout/index.js
  client/my-sites/checkout/test/utils.js
  client/my-sites/checkout/utils.ts
  client/my-sites/controller.js
  packages/shopping-cart/src/types.ts
Labels: [Status] Needs Review

#69672 Store: Modify thank you card for Woo mobile
  client/my-sites/checkout/checkout-thank-you/atomic-store-thank-you-card.jsx
Labels: [Status] Needs Review

#69774 Checkout: Hide plan upsells in Woo mobile webview
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
Labels: [Status] Needs Review

#69726 Stats: Swapping Videos component
  client/my-sites/stats/stats-list/stats-list-card.jsx
  client/my-sites/stats/stats-module/index.jsx
  client/my-sites/stats/stats-module/style.scss
  packages/components/src/horizontal-bar-list/_stats-variables.scss
Labels: [Type] Enhancement, Stats, [Status] Ready to Merge

#69372 Stats: Use FixedNavigationHeader on summary pages.
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-insights/index.jsx
  client/my-sites/stats/stats-post-detail/index.jsx
  client/my-sites/stats/style.scss
  client/my-sites/stats/summary/index.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Stats, [Status] Needs Review

#69812 Stats: Swapping `File downloads` component
  client/my-sites/stats/stats-list/stats-list-actions.jsx
  client/my-sites/stats/stats-list/stats-list-card.jsx
  client/my-sites/stats/stats-module/index.jsx
  packages/components/src/horizontal-bar-list/horizontal-bar-grid-item.tsx
  packages/components/src/horizontal-bar-list/stats-card.tsx
  packages/components/src/horizontal-bar-list/stories/sampleData.jsx
  packages/components/src/horizontal-bar-list/types.ts
Labels: [Type] Enhancement, Stats, [Status] Ready to Merge

#69779 Pattern Assembler - Add header and footer template parts when no selection is made
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/utils.ts
Labels: [Status] Needs Review

#69729 Thank you page for gifted purchases
  client/components/thank-you/index.tsx
  client/components/thank-you/types.ts
  client/my-sites/checkout/checkout-thank-you/gift/gift-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/gift/style.scss
  client/my-sites/checkout/controller.jsx
  client/my-sites/checkout/index.js
Labels: [Status] Needs Review

#69821 Agency Dashboard: Trigger requests to the /test-connection endpoint on component mount
  client/data/agency-dashboard/use-fetch-test-connection.ts
Labels: [Status] Needs Review, Jetpack Cloud

#69185 Partner Portal: implement assign multiple licenses flow
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-add-license-notification/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
  client/jetpack-cloud/sections/partner-portal/hooks.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/issue-multiple-licenses-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/issue-multiple-licenses-form/types.ts
  client/jetpack-cloud/sections/partner-portal/license-product-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-product-card/style.scss
  client/jetpack-cloud/sections/partner-portal/primary/issue-license/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-add/index.tsx
  client/jetpack-cloud/sections/partner-portal/types.ts
  client/state/jetpack-agency-dashboard/actions.ts
  client/state/jetpack-agency-dashboard/reducer.ts
  client/state/jetpack-agency-dashboard/selectors.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#69746 Stats: Refactor main chart tabs styles
  client/my-sites/stats/modernized-chart-tabs-styles.scss
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-chart-tabs/index.jsx
  client/my-sites/stats/stats-chart-tabs/style.scss
  client/my-sites/stats/style.scss
  client/my-sites/store/app/store-stats/index.js
  client/my-sites/store/app/store-stats/store-stats-chart/index.js
  client/my-sites/store/app/store-stats/store-stats-chart/style.scss
Labels: Stats, [Status] Ready to Merge

#69834 Gifting: show gifted site name in Checkout
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-review.tsx
  packages/shopping-cart/src/types.ts
Labels: [Status] Needs Review

#69596 Launchpad: Make copy to clipboard button keyboard navigable
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
Labels: [Status] Needs Review, LaunchPad

#69715 Add QR code in post action ellipsis menu
  client/my-sites/pages/page/index.js
  client/my-sites/post-actions-qr-code/index.jsx
  client/my-sites/post-type-list/post-actions-ellipsis-menu/index.jsx
  client/my-sites/post-type-list/post-actions-ellipsis-menu/qrcode.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Ready to Merge

#69721 Woo Onboarding MVP: Update/store profiler persistence
  client/landing/stepper/declarative-flow/internals/steps-repository/store-profiler/index.tsx
  packages/data-stores/src/onboard/actions.ts
  packages/data-stores/src/onboard/index.ts
  packages/data-stores/src/onboard/reducer.ts
  packages/data-stores/src/onboard/selectors.ts
Labels: [Status] Ready to Merge, Seller Experience, Tailored Flows

#69844 Stats: Pull site slug value from Redux state
  client/my-sites/stats/stats-post-detail/index.jsx
  client/my-sites/stats/summary/index.jsx
Labels: Stats, [Status] Needs Review

#69851 Stats: Restore preview button in page header
  client/my-sites/stats/stats-post-detail/index.jsx
Labels: Stats, [Status] Needs Review

#69775 Update Assign Later redirect
  client/jetpack-cloud/sections/partner-portal/assign-license-form/index.tsx
Labels: [Status] Needs Review

#69861 Stats: Enable shares module for Jetpack sites
  client/my-sites/stats/stats-insights/index.jsx
  client/my-sites/stats/stats-shares/index.jsx
Labels: [Type] Enhancement, Stats, [Status] Needs Review

#69837 Checkout: remove post-checkout polling for site for create_new_blog
  client/lib/domains/cart-utils.js
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-complete-callback.tsx
Labels: [Status] Needs Review

#69819 Components: Add PromoCard component
  packages/components/src/index.ts
  packages/components/src/promo-card/index.tsx
  packages/components/src/promo-card/stories/index.stories.jsx
  packages/components/src/promo-card/style.scss
  packages/components/src/promo-card/svg-icons.jsx
Labels: Stats, [Status] Ready to Merge, Components

#69858 (TeamCity/E2Es) Disable parallel test runs for WPCOM/Calypso Atomic E2Es
  .teamcity/_self/projects/WPComTests.kt
Labels: [Status] Needs Review

#69867 (TeamCIty/WPCOM Atomic E2Es) Disable/parallel runs for wpcom atomic e2es, take 2
  .teamcity/_self/projects/WPComTests.kt
Labels: [Status] Needs Review

#69841 Stats: Swapping Search and Countries components
  client/my-sites/stats/stats-list/stats-list-card.jsx
  client/my-sites/stats/stats-list/stats-list-country-flag.jsx
  client/my-sites/stats/stats-list/style.scss
  client/my-sites/stats/stats-module/index.jsx
  packages/components/src/horizontal-bar-list/_stats-variables.scss
  packages/components/src/horizontal-bar-list/horizontal-bar-grid-item.tsx
  packages/components/src/horizontal-bar-list/stats-card.scss
  packages/components/src/horizontal-bar-list/stats-card.tsx
  packages/components/src/horizontal-bar-list/stories/sampleData.jsx
  packages/components/src/horizontal-bar-list/style.scss
  packages/components/src/horizontal-bar-list/types.ts
Labels: [Type] Enhancement, Stats, [Status] Needs Review

#69845 Use the new gift thank you page
  client/my-sites/checkout/get-thank-you-page-url/index.ts
  client/my-sites/checkout/get-thank-you-page-url/test/get-thank-you-page-url.ts
  packages/shopping-cart/src/types.ts
Labels: [Status] Needs Review, [Status] Ready to Merge

#69647 Introduce the custom callback mechanism upon a sign-up flow completion.
  client/lib/signup/flow-controller.ts
  client/lib/signup/step-actions/index.js
  client/signup/config/flows-pure.js
  client/signup/main.jsx
Labels: [Status] Needs Review

#69886 Revert "Introduce the custom callback mechanism upon a sign-up flow completion."
  client/lib/signup/flow-controller.ts
  client/lib/signup/step-actions/index.js
  client/signup/config/flows-pure.js
  client/signup/main.jsx
Labels: [Status] Needs Review

#69866 VideoPress onboarding: Add new options to old onboarding flow
  client/lib/signup/step-actions/index.js
Labels: [Status] Needs Review

#69685 Pre Cancellation Modal - add tracking events
  client/me/purchases/pre-cancellation-dialog/index.tsx
Labels: [Status] Needs Review

#69788 SSH add screen: Redirect the user back to hosting configuration
  client/me/security-ssh-key/security-ssh-key.tsx
  client/my-sites/hosting/sftp-card/index.js
  client/my-sites/hosting/sftp-card/ssh-keys.tsx
Labels: [Status] Needs Review

#69593 SSR markup cache short-circuit
  client/controller/shared.js
  client/my-sites/plugins/controller-logged-out.js
  client/my-sites/theme/controller.jsx
  client/my-sites/themes/controller.jsx
  client/server/isomorphic-routing/index.js
  client/server/render/index.js
Labels: [Status] Needs Review, Server Side Rendering, Performance

#69359 [WordAds]: Update Privacy & Consent settings copy
  client/my-sites/earn/ads/form-settings.jsx
Labels: [Status] Needs Review, WordAds, [Status] String Freeze

#69505 Jetpack Search: don't change jetpack_search to wpcom_search
  client/my-sites/checkout/composite-checkout/hooks/use-prepare-products-for-cart.ts
  client/my-sites/site-settings/search.jsx
Labels: [Status] Needs Review, Jetpack Search

#69864 Update the license assignment page
  client/jetpack-cloud/sections/partner-portal/assign-license-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/assign-license/index.tsx
Labels: [Status] Needs Review

#69856 Updating link button and badges to use new purple styling.
  client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-domain/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-plan/style.scss
Labels: [Status] Ready to Merge

#69855 Stats: Adjust new page header
  client/blocks/stats-navigation/index.js
  client/my-sites/stats/modernized-page-header-styles.scss
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-insights/index.jsx
  client/my-sites/stats/stats-period-header/style.scss
  client/my-sites/stats/style.scss
  client/my-sites/stats/wordads/index.jsx
  client/my-sites/stats/wordads/style.scss
  client/my-sites/store/app/store-stats/index.js
  client/my-sites/store/style.scss
Labels: Stats, [Status] Needs Review

#69891 Stats: Fix the last query date section for empty content
  client/my-sites/stats/stats-date-picker/index.jsx
  client/my-sites/stats/wordads/index.jsx
Labels: [Type] Bug, Stats, [Status] Needs Review

#69900 Domains: Refactor `canSetAsPrimary` check into a function
  client/lib/domains/utils/can-set-as-primary.ts
  client/my-sites/domains/domain-management/list/domain-row.jsx
  client/my-sites/domains/domain-management/settings/set-as-primary/index.tsx
Labels: [Status] Needs Review, Domains

#69898 Import a Domain flow: Implement new layout
  client/components/domains/use-my-domain/domain-input.jsx
  client/components/domains/use-my-domain/index.jsx
  client/components/domains/use-my-domain/style.scss
  client/signup/style.scss
Labels: [Status] Needs Review

#69872 Gifting: Add gift purchases to doNotStripProducts to preserve URL on refresh
  client/my-sites/checkout/composite-checkout/hooks/use-prepare-products-for-cart.ts
Labels: [Status] Needs Review

#69489 Domains: Update / add focus styles and address tabbing behaviour for a11y
  client/components/breadcrumb/index.tsx
  client/my-sites/domains/domain-management/list/domain-row.scss
  client/my-sites/domains/domain-management/list/domains-table-header.jsx
  client/my-sites/domains/domain-management/list/style.scss
Labels: [Status] In Progress, [Status] Needs Review, Accessibility, Domains

#69849 Signup: Clean up signup/stepper feature flags
  client/components/theme/index.jsx
  client/components/theme/test/__snapshots__/index.jsx.snap
  client/components/theme/test/index.jsx
  client/landing/stepper/declarative-flow/internals/steps-repository/blogger-starting-point/starting-points.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/difm-link.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/goals-capture-container.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/goals.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/import-link.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/select-goals.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/index.tsx
  client/landing/stepper/declarative-flow/plugin-bundle-flow.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  client/landing/stepper/hooks/use-site-setup-flow-progress.ts
  client/my-sites/email/titan-set-up-thank-you/index.tsx
  client/signup/config/flows.js
  client/signup/config/steps-pure.js
  client/signup/main.jsx
  client/signup/steps/design-picker/index.jsx
  client/signup/steps/starting-point/starting-point.tsx
  client/signup/utils.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#69700 Pattern Assembler - Add an API param to optimize the previews by removing unnecessary assets
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-assembler-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/utils.ts
  packages/design-picker/src/types.ts
  packages/design-picker/src/utils/designs.ts
Labels: [Status] Needs Review

#69876 Partner Portal: redirect to licenses page when not via dashboard & show notifications
  client/jetpack-cloud/sections/partner-portal/hooks.tsx
  client/jetpack-cloud/sections/partner-portal/primary/licenses/index.tsx
Labels: Jetpack, [Status] Ready to Merge, Jetpack Cloud

#69880 Partner Portal: redirect to licenses or assign licenses after issuing licenses when no site is selected
  client/jetpack-cloud/sections/partner-portal/hooks.tsx
Labels: Jetpack, [Status] Ready to Merge, Jetpack Cloud

#69565 Add sympathy dev warning
  client/components/sympathy-dev-warning/index.tsx
  client/layout/index.jsx
  client/layout/logged-out.jsx
  client/state/initial-state.js
Labels: [Status] Needs Review

#69888 Agency Dashboard: Show the Dashboard item in the navigation menu after agency signs up
  client/state/action-types.ts
  client/state/current-user/actions.js
  client/state/current-user/reducer.js
  client/state/partner-portal/partner/actions.ts
Labels: [Status] Needs Review, Jetpack Cloud

#69822 Tailored flows: Implement random patterns in LiB
  client/landing/stepper/hooks/use-theme-details.ts
  client/landing/stepper/index.tsx
  packages/pattern-picker/src/use-query-patterns.ts
Labels: [Status] Needs Review, Tailored Flows

#69924 Update lighthouse project board
  .github/workflows/lighthouse-review-requested.yml
Labels: [Status] Needs Review

#69912 Help Center: update resource title
  packages/help-center/src/components/help-center-more-resources.tsx
Labels: [Status] Needs Review, Help Center

#69385 Pull Request Template: Update to add privacy check
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Needs Review, Privacy/GDPR, [Type] Tooling

#69929 Site Editor: dashboard link compat for Gutenberg 14.5
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/class-wpcom-block-editor-nav-sidebar.php
Labels: [Status] Needs Review, [Goal] Full Site Editing

#69931 VideoPress Onboarding: Fix positioning of footer on intro view
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/styles.scss
Labels: [Status] Needs Review, VideoPress, [Goal] Onboarding

#69933 Checkout: Add gift badge to gifted line items
  packages/wpcom-checkout/src/checkout-line-items.tsx
Labels: [Status] Needs Review, Checkout

#69896 Get only rewindable Activity Log items when cloning a site into a previous state
  client/signup/steps/clone-point/index.jsx
Labels: [Status] Needs Review

#69231 Add Stats Standalone App for Jetpack plugins
  apps/stats/README.md
  apps/stats/package.json
  apps/stats/src/app.jsx
  apps/stats/src/components/layout.jsx
  apps/stats/src/page-middleware/layout.jsx
  apps/stats/src/page-middleware/setup-context.jsx
  apps/stats/src/routes.js
  apps/stats/webpack.config.js
  client/layout/masterbar/style.scss
  client/lib/wp/browser.js
  client/lib/wpcom-xhr-wrapper/index.js
  client/my-sites/stats/controller.jsx
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-shares/index.jsx
  client/my-sites/stats/style.scss
  client/state/selectors/is-google-my-business-location-connected.js
  config/_shared.json
  packages/components/src/gridicon/no-asset.tsx
  yarn.lock
Labels: Stats, [Status] Needs Review

#69915 Stats: Swapping Authors, Click and Referrers components
  client/my-sites/stats/stats-list/stats-list-card.jsx
  client/my-sites/stats/stats-module/index.jsx
  packages/components/src/horizontal-bar-list/_stats-variables.scss
  packages/components/src/horizontal-bar-list/horizontal-bar-grid-item.tsx
  packages/components/src/horizontal-bar-list/index.tsx
  packages/components/src/horizontal-bar-list/sideElements/avatar.tsx
  packages/components/src/horizontal-bar-list/stats-card.scss
  packages/components/src/horizontal-bar-list/stories/index.stories.jsx
  packages/components/src/horizontal-bar-list/style.scss
  packages/components/src/horizontal-bar-list/types.ts
  packages/components/src/index.ts
Labels: [Type] Enhancement, Stats, [Status] Ready to Merge

#69942 Stats: Limiting new layout to Traffic page
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-module/index.jsx
Labels: Stats, [Status] Needs Review, Quick Fix

#69944 Stats: Restoring new layout for Countries component
  client/my-sites/stats/stats-countries/index.jsx
Labels: Stats, [Status] Needs Review

#69937 Stats: Add All-time highlights section with mock data
  client/my-sites/stats/all-time-highlights-section/index.tsx
  client/my-sites/stats/all-time-highlights-section/style.scss
  client/my-sites/stats/stats-insights/index.jsx
  client/my-sites/stats/stats-period-header/style.scss
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Stats, [Status] Ready to Merge

#69877 Stats: Ship fixed nav headers to public
  client/my-sites/stats/stats-post-detail/index.jsx
  client/my-sites/stats/summary/index.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Stats, [Status] Ready to Merge
