Repository Automattic/wp-calypso, pull requests merged in 2022-08, with the labels that each got.

#66074 Support site_tagline in design previews
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  packages/design-picker/src/types.ts
  packages/design-picker/src/utils/designs.ts
Labels: [Type] Enhancement, [Status] Needs Review

#66078 Do not set site title if users have not provided one during onboarding
  client/landing/stepper/declarative-flow/site-setup-flow.ts
Labels: [Status] Needs Review

#66081 Show domain USP in marketplace only if the billing interval is yearly
  client/my-sites/plugins/plugin-details-CTA/usps.tsx
  client/my-sites/plugins/use-plugins-support-text/index.js
Labels: Plans, [Status] Needs Review, Marketplace

#65728 Revert: Experiment: Add Upgrade button to Masterbar
  client/layout/masterbar/logged-in.jsx
  client/layout/masterbar/plan-upsell.jsx
  client/layout/masterbar/style.scss
Labels: [Status] Needs Review

#66056 Update spacing for design preview title
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss
  client/signup/signup-header/style.scss
  client/signup/step-wrapper/style.scss
  packages/onboarding/src/step-container/style.scss
Labels: [Status] Needs Review

#65888 Help Center: Show in all calypso
  client/layout/index.jsx
  client/layout/masterbar/checkout.tsx
  client/layout/masterbar/logged-in.jsx
  client/layout/masterbar/masterbar-help-center.jsx
  client/my-sites/checkout/composite-checkout/components/checkout-help-link.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
  packages/calypso-e2e/src/lib/components/support-component.ts
  packages/help-center/src/components/help-center-sibyl-articles.tsx
  packages/help-center/src/components/index.d.ts
  packages/help-center/src/index.ts
  packages/help-center/src/styles.scss
  packages/help-center/src/utils.ts
  test/e2e/specs/support/support__home.ts
  test/e2e/specs/support/support__popover-invalid.ts
  test/e2e/specs/support/support__popover-valid.ts
  test/e2e/specs/support/support__showme-where.ts
Labels: [Status] Needs Review, Help Center

#66090 Signup: add link-in-bio flow
  client/signup/config/flows-pure.js
  client/signup/controller.js
  client/signup/main.jsx
  client/signup/signup-header/index.jsx
  client/signup/steps/domains/index.jsx
  client/signup/steps/emails/index.jsx
  client/signup/steps/plans/index.jsx
  client/signup/utils.js
  config/_shared.json
Labels: [Status] Needs Review, Signup

#66095 ETK: Starter_Page_Templates: Only calculate cache key when needed
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/class-starter-page-templates.php
Labels: [Status] Needs Review

#66106 Professional Email: Hide optional fields in the "Add mailbox" form for consistency with the Email Comparison view
  client/my-sites/email/add-mailboxes/index.tsx
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/professional-email-card.scss
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/professional-email-card.tsx
  client/my-sites/email/form/mailboxes/components/new-mailbox-list/index.tsx
  client/my-sites/email/form/mailboxes/components/password-reset-tip-field/index.tsx
  client/my-sites/email/form/mailboxes/components/password-reset-tip-field/style.scss
  client/my-sites/email/titan-set-up-mailbox/titan-set-up-mailbox-form.tsx
Labels: [Status] Needs Review

#66129 Help Center: Fix for css targeting
  packages/help-center/src/styles.scss
Labels: [Status] Needs Review

#65947 Checkout: Refactor post-checkout URL generation to clarify behavior
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-complete-callback.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/index.tsx
  client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.ts
  client/my-sites/checkout/post-checkout-upsell-experiment-redirector/index.tsx
  client/my-sites/checkout/upsell-nudge/index.jsx
  client/state/selectors/is-eligible-for-signup-destination.js
  packages/shopping-cart/src/types.ts
Labels: [Status] Needs Review

#65980 Jetpack Licensing: Make whole sites list item clickable/tappable
  client/jetpack-cloud/sections/partner-portal/assign-license-form/index.tsx
Labels: [Status] Needs Review, Jetpack Licensing Portal, Jetpack Licensing

#65988 Jetpack Licensing: Update license revoke dialog to make it fullscreen on mobile and some extra tweaks
  client/jetpack-cloud/sections/partner-portal/revoke-license-dialog/style.scss
Labels: [Status] Needs Review, Jetpack Licensing Portal, Jetpack Licensing

#65997 [GB 13.7.x] Open Site Editor in the Gutenframe by using the `site-editor.php` route
  client/gutenberg/editor/calypsoify-iframe.tsx
  client/state/selectors/get-site-editor-url.js
Labels: [Status] Needs Review, [Goal] Gutenberg

#66028 Replace /block-editor with /themes?status=active endpoint
  client/data/block-editor/use-block-editor-settings-query.ts
  client/lib/signup/step-actions/index.js
  client/signup/config/flows.js
  client/signup/config/steps-pure.js
  packages/data-stores/src/site/actions.ts
Labels: [Status] Needs Review

#65912 Plans Revert: upgrade plan from Free to Premium on existing site with content.
  packages/calypso-e2e/package.json
  packages/calypso-e2e/src/lib/pages/media-page.ts
  packages/calypso-e2e/src/lib/pages/plans-page.ts
  packages/calypso-e2e/src/rest-api-client.ts
  packages/calypso-e2e/src/test/rest-api-client.createPost.test.ts
  packages/calypso-e2e/src/types/rest-api-client.types.ts
  test/e2e/specs/plans/plans__existing-free-site-upgrade.ts
  test/e2e/specs/plans/plans__upgrade.ts
  test/e2e/specs/shared/api-delete-site.ts
  yarn.lock
Labels: [Status] Needs Review

#66101 Checkout: Improve pending page UI
  client/my-sites/checkout/checkout-thank-you/pending/index.tsx
  client/my-sites/checkout/checkout-thank-you/pending/style.scss
Labels: [Status] Needs Review, Post Checkout

#65572 Add: Backup Retention Disclaimer Information
  client/components/foldable-faq/index.tsx
  client/components/jetpack/card/jetpack-product-card/index.tsx
  client/components/jetpack/card/jetpack-product-card/style.scss
  client/lib/plans/features-list.js
  client/my-sites/plans/jetpack-plans/faq/index.tsx
  client/my-sites/plans/jetpack-plans/faq/style.scss
  client/my-sites/plans/jetpack-plans/slug-to-selector-product.ts
  client/my-sites/plans/jetpack-plans/storage-tier-upgrade/hooks/use-get-storage-upgrade-product.ts
  client/my-sites/plans/jetpack-plans/storage-tier-upgrade/style.scss
  client/my-sites/plans/jetpack-plans/types.ts
  packages/calypso-products/src/get-jetpack-product-disclaimer.ts
  packages/calypso-products/src/product-values.ts
  packages/calypso-products/src/products-list.ts
  packages/calypso-products/src/translations.tsx
  packages/calypso-products/src/types.ts
Labels: [Status] Needs Review

#66151 Add blocks and editor tags to the Design category
  client/my-sites/plugins/categories/use-categories.tsx
Labels: [Status] Needs Review

#66080 DIFM Landing: Increment counter on page view
  client/my-sites/marketing/do-it-for-me/difm-landing.tsx
  client/state/persistent-counter/actions.ts
Labels: [Status] Needs Review, DIFM Lite

#66133 Enable the `marketplace-jetpack-plugin-search` flag on the wpcalypso environment
  config/wpcalypso.json
Labels: Marketplace, Marketplace search: MVP (WP.org results)

#66108 `CheckoutThankYouHeader`: refactor tests to `@testing-library/react`
  client/my-sites/checkout/checkout-thank-you/test/header.js
Labels: Framework, [Status] Needs Review, Testing

#66057 Add premium plan to VideoPress site.
  client/lib/signup/step-actions/index.js
  client/signup/config/flows-pure.js
  client/signup/config/steps-pure.js
  client/signup/steps/videopress-site/index.jsx
  packages/shopping-cart/src/types.ts
Labels: [Status] Needs Review

#66114 `CheckoutThankYou`: refactor tests to `@testing-library/react`
  client/my-sites/checkout/checkout-thank-you/test/index.js
Labels: Framework, [Status] Needs Review, Testing

#65766 Theme Showcase: Updating design for the theme popover on the themes page
  client/components/theme/index.jsx
  client/components/theme/style.scss
  client/components/theme/test/premium-popover.jsx
Labels: [Status] Needs Review, Theme Showcase

#65908 Social Sign Up: Warn the user about an already existing account
  client/blocks/signup-form/index.jsx
  client/login/controller.js
  client/signup/steps/user/index.jsx
  client/state/action-types.ts
  client/state/login/reducer.js
Labels: [Status] Needs Review, DO NOT MERGE, Social Signup, Google Auth

#65966 Fix conditions that prevent from editing or removing the site's owner
  client/my-sites/people/delete-user/index.jsx
  client/my-sites/people/edit-team-member-form/edit-user-form.jsx
Labels: [Status] Needs Review, Reviewer Can Merge

#66148 Draft: Add sign up link to the unknown_user message
  client/blocks/login/error-notice.jsx
  client/blocks/login/index.jsx
Labels: [Status] Needs Review

#66116 `PlanTypeSelector`: refactor tests to `@testing-library/react`
  client/my-sites/plans-features-main/test/plan-type-selector.jsx
Labels: Framework, [Status] Needs Review, Testing

#66122 Marketplace: premium plugins now require a personal plan.
  client/blocks/eligibility-warnings/hold-list.tsx
  client/blocks/eligibility-warnings/index.tsx
  client/lib/plugins/utils.js
  client/my-sites/checkout/composite-checkout/components/item-variation-picker/item-variation-dropdown.tsx
  client/my-sites/plugins/plugin-details-CTA/CTA-button.jsx
  client/my-sites/plugins/plugin-details-CTA/usps.tsx
  client/my-sites/plugins/plugin-install-button/index.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#66103 Checkout: Rename CheckoutSystemDecider and CompositeCheckout
  client/blocks/editor-checkout-modal/index.tsx
  client/my-sites/checkout/checkout-main-wrapper.tsx
  client/my-sites/checkout/composite-checkout/components/checkout-main.tsx
  client/my-sites/checkout/composite-checkout/test/checkout-contact-step.js
  client/my-sites/checkout/composite-checkout/test/checkout-main.js
  client/my-sites/checkout/composite-checkout/test/checkout-payment-method-list.js
  client/my-sites/checkout/composite-checkout/test/composite-checkout-variant-picker.tsx
  client/my-sites/checkout/controller.jsx
  client/my-sites/checkout/modal/index.tsx
Labels: [Status] Needs Review

#65909 Social Login: Offer to create a new account if it doesn't exist
  client/blocks/login/error-notice.jsx
  client/blocks/login/index.jsx
Labels: [Status] Needs Review, Login, Google Auth, Reviewer Can Merge

#65041 Jetpack Agency Dashboard: Use jetpack_partner_types to detect agencies
  client/components/jetpack/portal-nav/index.tsx
  client/jetpack-cloud/index.js
  client/jetpack-cloud/sections/agency-dashboard/controller.tsx
  client/jetpack-cloud/sections/agency-dashboard/dashboard-overview/index.tsx
  client/jetpack-cloud/sections/site-landing.jsx
  client/lib/user/shared-utils/filter-user-object.js
  client/lib/user/user.d.ts
  client/state/partner-portal/partner/selectors.ts
Labels: Jetpack, [Status] Ready to Merge, Jetpack Cloud, Jetpack Licensing Portal

#66127 Reenable e2e tests for adding template parts
  test/e2e/specs/editor-tracking/editor-tracking__fse-template-events.ts
Labels: [Status] In Progress, [Status] Needs Review

#66168 Jetpack Agency dashboard: enable plugin management in calypso.live
  config/jetpack-cloud-horizon.json
Labels: [Status] Needs Review, Jetpack Cloud, [Size] XS

#66064 E2E: update `Signup: Paid` spec to cover the FTME and Launch flows.
  packages/calypso-e2e/src/lib/flows/start-site-flow.ts
  packages/calypso-e2e/src/lib/pages/general-settings-page.ts
  packages/calypso-e2e/src/lib/pages/index.ts
  packages/calypso-e2e/src/lib/pages/my-home-page.ts
  packages/calypso-e2e/src/lib/pages/signup/index.ts
  packages/calypso-e2e/src/lib/pages/signup/signup-domain-page.ts
  packages/calypso-e2e/src/lib/pages/signup/signup-pick-plan-page.ts
  packages/calypso-e2e/src/lib/pages/signup/user-signup-page.ts
  packages/calypso-e2e/src/types/rest-api-client.types.ts
  test/e2e/specs/onboarding/ftme__sell.ts
  test/e2e/specs/onboarding/signup__free.ts
  test/e2e/specs/onboarding/signup__paid.ts
  test/e2e/specs/plans/plans__signup-business.ts
  test/e2e/specs/shared/api-close-account.ts
Labels: [Status] Needs Review

#66181 Help Center: Restrict help-center CSS to the help center
  packages/help-center/src/styles.scss
Labels: [Status] Needs Review, Quick Fix, Help Center

#66024 Add promote posts button to stats entries, with feature flag
  client/my-sites/stats/stats-list/action-promote.jsx
  client/my-sites/stats/stats-list/stats-list-item.jsx
  client/my-sites/stats/stats-list/style.scss
  client/state/stats/lists/test/utils.js
  client/state/stats/lists/utils.js
Labels: [Status] Needs Review

#65861 Jetpack post-connection: Redirect secondary user back to wp-admin.
  client/jetpack-connect/authorize.js
  client/jetpack-connect/controller.js
Labels: Jetpack, [Status] Needs Review

#66136 Add/dsp widget entrypoint tracking
  client/lib/promote-post/index.ts
  client/my-sites/customer-home/cards/tasks/promote-post/index.js
Labels: [Status] Needs Review

#65860 App Banner: Remove the banner experiemnt
  client/blocks/app-banner/index.jsx
  client/blocks/app-banner/utils.js
Labels: [Status] Needs Review, Mobile Web

#66198 Unified design picker: Always enable passing vertical_id when the design type is vertical
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
Labels: [Type] Bug, [Status] Needs Review

#65680 Framework: Refactor away from `_.isPlainObject()`
  client/lib/preferences-helper/preference.js
  client/state/data-layer/utils.js
  client/state/posts/utils/get-term-ids-from-edits.js
  client/state/posts/utils/is-terms-equal.js
  client/state/site-settings/test/utils.js
  client/state/site-settings/utils.js
  docs/coding-guidelines/javascript.md
Labels: [Type] Enhancement, Framework, [Status] Needs Review, State

#66205 Import step: Remove translation fallback
  client/blocks/import/capture/capture-input.tsx
Labels: [Status] Needs Review

#66118 `PurchaseDetail`: refactor tests to `@testing-library/react`
  client/components/purchase-detail/test/index.jsx
Labels: Framework, [Status] Needs Review, Testing

#66166 `CountrySpecificPaymentFields`: refactor tests to `@testing-library/react`
  client/my-sites/checkout/checkout/test/__snapshots__/country-specific-payment-fields.js.snap
  client/my-sites/checkout/checkout/test/country-specific-payment-fields.js
Labels: Framework, [Status] Needs Review, Testing

#66214 Site status displayed in column rather than with badges
  client/sites-dashboard/components/sites-table-row.tsx
  client/sites-dashboard/components/sites-table.tsx
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66221 Sites Management Page: Tweak sites managment page styles
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/components/sites-table-row.tsx
  client/sites-dashboard/components/sites-table.tsx
  packages/components/src/sites-table/sites-count-badge.tsx
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#65920 Happychat Connection: Update Tests
  packages/happychat-connection/jest.config.js
  packages/happychat-connection/jestSetup.ts
  packages/happychat-connection/test/index.ts
Labels: [Status] Needs Review, Help Center

#66138 Prevent unnecessary renders in PurchaseNotice
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/purchase-notice/index.jsx
Labels: [Status] Needs Review, Editing Toolkit, Seller Experience

#66093 Update the sidebar height to fit-content.
  client/my-sites/plugins/style.scss
Labels: [Status] Needs Review, 20percent

#66174 Sites Dashboard Page: replace history when search or tab status change
  client/sites-dashboard/components/sites-dashboard.tsx
Labels: [Status] Needs Review, Sites Management Page

#66226 `PlanDetails`: refactor tests to `@testing-library/react`
  client/me/purchases/manage-purchase/plan-details/test/index.jsx
Labels: Framework, [Status] Needs Review, Testing

#66170 theme: Use isThemePremium selector to determine if a theme is premium
  client/components/theme/index.jsx
Labels: [Status] Needs Review

#66173 theme: use isThemePurchased selector to detect purchase
  client/components/theme/index.jsx
  client/components/theme/test/premium-popover.jsx
Labels: [Status] Needs Review

#66054 Plugin Details: Manage plugin actions
  client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx
  client/my-sites/plugins/plugin-details-CTA/activation-button.jsx
  client/my-sites/plugins/plugin-details-CTA/index.jsx
  client/my-sites/plugins/plugin-details-CTA/manage-plugin-menu.jsx
  client/my-sites/plugins/plugin-details-CTA/style.scss
  client/my-sites/plugins/plugin-details.jsx
Labels: [Status] Needs Review

#65252 Marketplace: Update Preinstalled Premium Plugins Browser Item
  client/my-sites/plugins/plugin-details-CTA/preinstalled-premium-plugins-CTA.jsx
  client/my-sites/plugins/plugin-price/preinstalled-premium-plugin-price-display.jsx
  client/my-sites/plugins/plugins-browser-item/index.jsx
  client/my-sites/plugins/plugins-browser-item/preinstalled-premium-plugin-browser-item-pricing.jsx
  client/my-sites/plugins/use-preinstalled-premium-plugin/index.js
Labels: [Status] Needs Review, Marketplace, Marketplace: add Jetpack Search

#66183 theme: Replace price test with a new themeNeedsPurchase variable
  client/components/theme/index.jsx
Labels: [Status] Needs Review

#66184 theme: Rename isPremiumThemesAvailable -> hasPremiumThemesFeature
  client/components/theme/index.jsx
  client/components/theme/test/premium-popover.jsx
Labels: [Status] Needs Review

#66175 format-currency: Add isSmallestUnit option to support integer amounts
  packages/format-currency/README.md
  packages/format-currency/src/index.ts
  packages/format-currency/src/types.ts
  packages/format-currency/test/index.ts
Labels: [Status] Needs Review

#65049 Refactor `UpgradeATStep` tests to @testing-library/react
  client/components/marketing-survey/cancel-purchase-form/step-components/test/upgrade-at-step.jsx
Labels: Framework, [Status] Needs Review, Components, Testing

#66196 Sites Management Page: use @emotion/css to generate class names instead of `<ClassNames>` wrapper
  client/package.json
  client/sites-dashboard/components/sites-table-row.tsx
  yarn.lock
Labels: [Status] Needs Review, dependencies, Sites Management Page, Reviewer Can Merge

#66012 Unify owner deleting prevention for simple and atomic sites
  client/my-sites/people/delete-user/index.jsx
Labels: [Status] Needs Review, Reviewer Can Merge

#66104 Unified design picker: Tailored UI based on intent
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  packages/data-stores/src/starter-designs-queries/use-starter-designs-query.ts
Labels: [Status] In Progress, [Status] Needs Review

#66217 Add newsletter setup step
  client/components/site-icon-with-picker/index.tsx
  client/components/site-icon-with-picker/style.scss
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/style.scss
  client/landing/stepper/declarative-flow/newsletters.ts
  packages/data-stores/src/index.ts
  packages/data-stores/src/queries/use-site-logo-mutation.ts
  packages/data-stores/src/site/types.ts
  packages/wpcom-proxy-request/types/index.d.ts
Labels: [Status] Needs Review, Signup, Stepper

#66249 Tracking: Submit site vertical in English
  client/components/select-vertical/index.tsx
  client/components/select-vertical/suggestion-search.tsx
  client/components/select-vertical/types.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/form.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/index.tsx
  packages/components/src/suggestions/index.tsx
Labels: [Status] Needs Review

#66218 Filter site status using drop down instead of tabs
  client/sites-dashboard/components/no-sites-message.tsx
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/components/sites-search.ts
  client/sites-dashboard/components/test/no-sites-message.tsx
  client/sites-dashboard/controller.tsx
  packages/components/src/sites-table/test/use-sites-table-filtering.tsx
  packages/components/src/sites-table/use-sites-table-filtering.tsx
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66157 update: switch over to new endpoint on jetpack backup page
  client/my-sites/backup/hooks.js
  client/my-sites/backup/search-results.jsx
  client/my-sites/backup/status/hooks.js
Labels: Jetpack, [Status] Needs Review, Jetpack Backup

#66256 Sites Management Page: Disable autocorrect in search input
  client/sites-dashboard/components/sites-dashboard.tsx
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66259 Sites Management Page: Change '+ New site' to 'Add new site'
  client/sites-dashboard/components/sites-dashboard.tsx
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66242 Theme Showcase: Improve cursor style consistency
  client/components/theme/style.scss
Labels: [Status] Needs Review

#66239 Unified Design Picker: Theme Preview recognizes individual premium theme purchases
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/util/get-theme-id-from-design.tsx
Labels: [Status] Needs Review

#66185 VideoPress Onboarding: Save title and site description when site is created
  client/lib/signup/step-actions/index.js
  client/signup/config/steps-pure.js
  client/signup/config/steps.js
  client/signup/steps/videopress-site/index.jsx
Labels: [Status] Needs Review

#66187 Design Picker: Theme Card recognizes individual premium theme purchases
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/state/themes/selectors/get-purchased-themes.js
  client/state/themes/selectors/index.js
  client/state/themes/test/selectors.js
  packages/design-picker/src/components/unified-design-picker.tsx
Labels: [Status] Needs Review

#66164 Add/link in bio setup
  client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-setup/link-in-bio-input.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-setup/styles.scss
  client/landing/stepper/declarative-flow/link-in-bio.ts
Labels: [Status] Needs Review, Signup, Stepper

#66265 Editor Iframe: remove unnecessary check that site editor is enabled
  client/gutenberg/editor/controller.js
Labels: Editor, [Status] Needs Review

#66240 Checkout: use formatCurrency directly in term variant picker
  client/my-sites/checkout/composite-checkout/components/item-variation-picker/variant-price.tsx
  client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx
Labels: [Status] Needs Review

#66268 Help Center: Calypso-related style and support fixes
  packages/help-center/src/components/help-center-contact-form.scss
  packages/help-center/src/components/help-center-search.scss
  packages/help-center/src/hooks/use-still-need-help-url.tsx
  packages/help-center/src/styles.scss
  packages/site-picker/src/hooks.tsx
  packages/site-picker/src/index.tsx
Labels: [Status] Needs Review

#66178 E2E: add fallback for `ElementHelper` to force through the click action in case of timeout.
  packages/calypso-e2e/src/element-helper.ts
Labels: [Status] Needs Review

#66230 Flaky E2E: correct expected outcome after selecting a design and landing at home dashboard.
  test/e2e/specs/onboarding/ftme__sell.ts
Labels: [Status] Needs Review

#66046 Editing Toolkit: Add block-editor preview button url override
  apps/editing-toolkit/editing-toolkit-plugin/common/index.php
  apps/editing-toolkit/editing-toolkit-plugin/common/override-preview-button-url.js
  apps/editing-toolkit/package.json
Labels: [Status] Needs Review

#66288 Signup: Remove stroke value on WP logo
  client/components/wordpress-logo/index.jsx
  client/signup/style.scss
Labels: [Status] Needs Review

#66117 WooCommerce.com login - move ToS above actions
  client/blocks/login/social-connect-prompt.jsx
  client/layout/masterbar/oauth-client.scss
Labels: [Status] Needs Review

#66257 Adds tracks event for the promote post button
  client/my-sites/stats/stats-list/action-promote.jsx
Labels: [Status] Needs Review

#66290 Add/site icon component
  client/components/site-icon-with-picker/style.scss
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-setup/link-in-bio-input.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-setup/styles.scss
Labels: [Status] Needs Review, Signup, Stepper

#66297 WooCommerce.com login - fix line-height of ToS
  client/layout/masterbar/oauth-client.scss
Labels: [Status] Needs Review

#66263 Stepper: Implement color picker popover for newsletter accent color
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/style.scss
Labels: [Status] Needs Review

#66199 Sites Management Page: Remove wrapper div from search field
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/components/sites-search.ts
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66267 Fix - the password reset email UI should not be present when adding a mailbox for Google Workspace
  client/my-sites/email/add-mailboxes/index.tsx
Labels: [Status] Needs Review

#66051 Add routine to claim discount during cancellation
  client/assets/images/jetpack/cloud-icon.svg
  client/assets/images/jetpack/decorative-card-background.jpg
  client/assets/images/jetpack/decorative-card-icon.svg
  client/components/jetpack-decorative-card/index.tsx
  client/components/jetpack-decorative-card/style.scss
  client/components/marketing-survey/cancel-jetpack-form/index.tsx
  client/components/marketing-survey/cancel-jetpack-form/jetpack-cancellation-offer-accepted.tsx
  client/components/marketing-survey/cancel-jetpack-form/jetpack-cancellation-offer.tsx
  client/components/marketing-survey/cancel-jetpack-form/steps.ts
  client/components/marketing-survey/cancel-jetpack-form/style.scss
  client/me/purchases/cancel-purchase/button.jsx
  client/me/purchases/remove-purchase/index.jsx
  client/state/action-types.ts
  client/state/cancellation-offers/actions.js
  client/state/cancellation-offers/reducer.ts
  client/state/cancellation-offers/selectors/get-cancellation-offer-apply-error.js
  client/state/cancellation-offers/selectors/get-cancellation-offer-apply-success.js
  client/state/cancellation-offers/selectors/get-cancellation-offers.js
  client/state/cancellation-offers/selectors/is-applying-cancellation-offer.js
  client/state/cancellation-offers/selectors/is-fetching-cancellation-offers.js
  client/state/data-layer/wpcom-http/actions.js
  client/state/data-layer/wpcom/cancellation-offers/index.tsx
Labels: [Status] Needs Review

#66264 Fix condition that decides about displaying owner edit form
  client/my-sites/people/edit-team-member-form/edit-user-form.jsx
Labels: [Type] Bug, [Status] Needs Review, User Management

#66305 Help Center: Adjust Happychat endpoint in help center according to env
  apps/happychat/src/index.ejs
  packages/help-center/src/components/help-center-inline-chat.tsx
Labels: [Type] Bug, [Status] Needs Review

#66309 VideoPress onboarding: Redirect to site editor after plan purchase
  client/signup/config/flows-pure.js
Labels: [Status] Needs Review

#66246 Implementing A/B test on the domains step.
  client/components/domains/reskin-side-explainer/index.jsx
Labels: [Status] Needs Review, Signup, Domains, ABTest

#66276 Social Auth: Remove Google API migration feature flag and obsolete code
  client/blocks/login/social.jsx
  client/blocks/signup-form/social.jsx
  client/components/social-buttons/google.js
  client/me/social-login/action-button.jsx
  config/development.json
  config/horizon.json
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Social Signup, Google Auth

#66311 Sites Management Page: Ignore match location using fuzzy search
  packages/search/src/use-fuzzy-search.ts
Labels: [Type] Bug, [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66312 Licensing Portal: fix Billing page design on mobile
  client/jetpack-cloud/sections/partner-portal/billing-details/index.tsx
  client/jetpack-cloud/sections/partner-portal/billing-details/style.scss
  client/jetpack-cloud/sections/partner-portal/billing-summary/style.scss
Labels: [Status] Needs Review, Jetpack Licensing Portal, Jetpack Licensing

#66302 Sites Management Page: Only show `<FilterBar>` when user has sites
  client/sites-dashboard/components/sites-dashboard.tsx
Labels: [Status] Needs Review, [Type] Task, Sites Management Page, Reviewer Can Merge

#66182 Jetpack Agency Dashboard: Move the /plugins/manage redirect from rendering to routing
  client/jetpack-cloud/sections/plugin-management/controller.tsx
  client/jetpack-cloud/sections/plugin-management/plugins-overview/index.tsx
Labels: Jetpack, [Status] Needs Review, Plugins, Jetpack Cloud

#66318 E2E: Use has-text selector for skip domains button
  packages/calypso-e2e/src/lib/pages/signup/signup-domain-page.ts
Labels: [Status] Needs Review

#66279 Site Setup Design Picker: Recognize individual theme purchases
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx
  packages/design-picker/src/components/index.tsx
Labels: [Status] Needs Review

#65503 [etk/error-reporting] Setup action hook callback to capture React Error Boundary exceptions
  apps/editing-toolkit/editing-toolkit-plugin/error-reporting/index.js
Labels: [Status] Needs Review

#66317 Sites Management Page: Fix hiding columns on mobile
  client/sites-dashboard/components/sites-table-row.tsx
Labels: [Type] Bug, [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66200 fix mobile padding on unified design picker
  packages/design-picker/src/components/style.scss
Labels: [Status] Needs Review

#66202 fix viewport controlls being hidden on resize
  client/components/web-preview/content.jsx
Labels: [Status] Needs Review

#66083 Import: fix back routing from Pick a design page
  client/landing/stepper/declarative-flow/site-setup-flow.ts
Labels: [Status] Needs Review, Improve Importer Onboarding Flows

#66310 Marketplace: Update alt & display name on submission success page
  client/my-sites/marketplace/pages/submission-success/signup-success.tsx
Labels: [Status] Ready to Merge

#65827 Calypso Config: Don't throw error when missing the config data
  packages/calypso-config/src/index.ts
Labels: [Status] Needs Review

#66219 Plugin Management: Implement multi-site(large screen) view for the plugin management
  client/components/section-nav/index.jsx
  client/components/section-nav/item.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/style.scss
  client/jetpack-cloud/sections/plugin-management/plugins-overview/style.scss
  client/my-sites/plugins/main.jsx
  client/my-sites/plugins/plugin-management-v2/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-row-formatter/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-row-formatter/style.scss
  client/my-sites/plugins/plugin-management-v2/plugins-table/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugins-table/style.scss
  client/my-sites/plugins/plugin-management-v2/style.scss
  client/my-sites/plugins/plugin-management-v2/types.ts
  client/my-sites/plugins/plugin-management-v2/update-plugin/index.tsx
  client/my-sites/plugins/plugin-management-v2/update-plugin/style.scss
  client/my-sites/plugins/plugin-management-v2/utils/get-allowed-plugin-actions.ts
  client/my-sites/plugins/plugins-list/index.jsx
  client/my-sites/plugins/style.scss
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#66293 UDP: Remove space on the left of category select
  packages/design-picker/src/components/style.scss
Labels: [Status] In Progress, [Status] Needs Review

#66330 [Calypso] Update 'Something else' vertical tracking id
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/index.tsx
Labels: [Status] In Progress, [Status] Needs Review

#66338 Add default payment block plan name
  client/my-sites/earn/memberships/add-edit-plan-modal.jsx
Labels: [Status] Needs Review

#65000 Add/offer step in cancellation flow
  client/assets/images/jetpack/cloud-icon.svg
  client/assets/images/jetpack/decorative-card-background.jpg
  client/assets/images/jetpack/decorative-card-icon.svg
  client/components/data/query-purchase-cancellation-offers/README.md
  client/components/data/query-purchase-cancellation-offers/index.tsx
  client/components/jetpack-decorative-card/index.tsx
  client/components/jetpack-decorative-card/style.scss
  client/components/marketing-survey/cancel-jetpack-form/index.tsx
  client/components/marketing-survey/cancel-jetpack-form/jetpack-cancellation-offer-accepted.tsx
  client/components/marketing-survey/cancel-jetpack-form/jetpack-cancellation-offer.tsx
  client/components/marketing-survey/cancel-jetpack-form/steps.ts
  client/components/marketing-survey/cancel-jetpack-form/style.scss
  client/me/purchases/cancel-purchase/button.jsx
  client/me/purchases/remove-purchase/index.jsx
  client/state/action-types.ts
  client/state/cancellation-offers/actions.js
  client/state/cancellation-offers/init.js
  client/state/cancellation-offers/package.json
  client/state/cancellation-offers/reducer.ts
  client/state/cancellation-offers/selectors/get-cancellation-offer-apply-error.js
  client/state/cancellation-offers/selectors/get-cancellation-offer-apply-success.js
  client/state/cancellation-offers/selectors/get-cancellation-offers.js
  client/state/cancellation-offers/selectors/is-applying-cancellation-offer.js
  client/state/cancellation-offers/selectors/is-fetching-cancellation-offers.js
  client/state/cancellation-offers/test/reducer.ts
  client/state/cancellation-offers/types.ts
  client/state/data-layer/wpcom-http/actions.js
  client/state/data-layer/wpcom/cancellation-offers/index.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
Labels: [Status] Needs Review

#66308 Add form check and ui state for validations
  client/assets/images/onboarding/green-checkmark.svg
  client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-setup/link-in-bio-input.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-setup/styles.scss
Labels: [Status] Needs Review, Signup, Stepper

#66321 unified-design-picker: Flatten text conditional
  packages/design-picker/src/components/unified-design-picker.tsx
Labels: [Status] Needs Review

#66342 Fuzzy Search: Remove unnecessary default `distance`
  packages/search/src/use-fuzzy-search.ts
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66322 Sites Management Dashboard: Add site display mode switcher buttons
  client/sites-dashboard/components/sites-content-controls.tsx
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/components/sites-display-mode-switcher.tsx
  client/sites-dashboard/components/sites-list-icon.tsx
  client/sites-dashboard/components/sites-tiles-icon.tsx
Labels: [Status] Needs Review, Sites Management Page

#66323 Sites Management Dashboard: persist display mode as a preference
  client/sites-dashboard/components/sites-display-mode-switcher.tsx
Labels: [Status] Needs Review, Sites Management Page

#65560 Search: match edge fade color with `--color-surface` variable
  packages/search/package.json
  packages/search/src/search.stories.jsx
  packages/search/src/search.stories.scss
  packages/search/src/style.scss
  yarn.lock
Labels: [Status] Needs Review, Packages

#66360 Revert "Help Center: Adjust Happychat endpoint in help center according to env"
  apps/happychat/src/index.ejs
  packages/help-center/src/components/help-center-inline-chat.tsx
Labels: [Status] Needs Review

#66281 SMP: add loading placeholder
  client/data/sites/use-site-excerpts-query.ts
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/components/sites-table-row-loading.tsx
  client/sites-dashboard/components/sites-table.tsx
  packages/components/src/index.js
  packages/components/src/loading-placeholder/index.tsx
  packages/components/src/loading-placeholder/loading-placeholder.stories.tsx
  packages/components/src/loading-placeholder/loading-placeholder.tsx
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66365 Disable the Help Center everywhere
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#66194 Launchpad: Create step in Stepper flow
  client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
  client/landing/stepper/declarative-flow/link-in-bio.ts
  client/landing/stepper/declarative-flow/newsletters.ts
  client/landing/stepper/declarative-flow/podcasts.ts
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
Labels: [Status] Needs Review, LaunchPad v1

#66061 Add/sites thumbnails
  client/components/image/index.js
  client/components/image/index.tsx
  client/sites-dashboard/components/sites-table-row.tsx
  packages/components/package.json
  packages/components/src/site-thumbnail/index.tsx
  packages/components/src/site-thumbnail/style.scss
  packages/components/src/site-thumbnail/use-dominant-color.tsx
  yarn.lock
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66339 Vertical Step: Track whether submitted vertical is eligible for design verticalization
  client/components/select-vertical/index.tsx
  client/components/select-vertical/types.ts
  client/data/site-verticals/types.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/index.tsx
Labels: [Type] Enhancement, [Status] Needs Review

#66374 Add prop intent to calypso_signup_{step_start, generated_design_picker_view}
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx
Labels: [Status] Needs Review

#66197 Marketplace: Create DiscoveryPage component
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/plugins/plugins-discovery-page/README.md
  client/my-sites/plugins/plugins-discovery-page/index.jsx
  client/my-sites/plugins/plugins-discovery-page/style.scss
  packages/calypso-e2e/src/lib/pages/plugins-page.ts
  test/e2e/specs/plugins/plugins__browse-calypso-user.ts
Labels: [Status] Needs Review, [Status] Ready to Merge

#66252 Plugin Management: Implement single-site(large screen) view for the plugin management
  client/my-sites/plugins/plugin-activate-toggle/style.scss
  client/my-sites/plugins/plugin-management-v2/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-row-formatter/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-row-formatter/style.scss
  client/my-sites/plugins/plugin-management-v2/plugins-table/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugins-table/style.scss
  client/my-sites/plugins/plugin-management-v2/update-plugin/style.scss
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#66341 Marketplace: Add hover state to dropdown menu items
  packages/components/src/responsive-toolbar-group/style.scss
Labels: [Status] In Progress

#66294 DIFM Step: Show loader when saving preferences
  client/my-sites/marketing/do-it-for-me/difm-landing.tsx
  client/my-sites/marketing/do-it-for-me/site-build-showcase.tsx
Labels: [Status] Needs Review, DIFM Lite

#66390 Fix incorrect visibility of privacy field in image edit form
  client/post-editor/media-modal/detail/detail-fields.jsx
  client/post-editor/media-modal/detail/test/index.jsx
Labels: [Status] Needs Review, Media, Reviewer Can Merge

#66373 Fix - Expose password reset email field if user's email is not a valid alternate email
  client/my-sites/email/add-mailboxes/index.tsx
Labels: [Status] Needs Review

#66398 Goals Capture: Hide DIFM goal for non-EN users.
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/goals.tsx
Labels: [Status] Needs Review, Goals Capture

#66272 Yoast Upsell: removes unnecessary aria-hidden attribute
  client/components/promo-card/index.jsx
Labels: [Status] Needs Review

#66394 Update "Launched" wording to "Public"
  client/sites-dashboard/components/no-sites-message.tsx
  client/sites-dashboard/components/sites-table-row.tsx
  client/sites-dashboard/components/test/no-sites-message.tsx
  packages/components/src/sites-table/test/use-sites-table-filtering.tsx
  packages/components/src/sites-table/use-sites-table-filtering.tsx
Labels: [Status] Needs Review, Sites Management Page

#66375 Added Checklist and ChecklistItem components for Launchpad
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/checklist-item.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/checklist.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/tasks.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/types.ts
Labels: [Status] In Progress, [Status] Needs Review

#66392 Sites Managment Page: Boost filtering performance by taking advantage site data object equality
  client/sites-dashboard/components/sites-table-row.tsx
  packages/components/src/sites-table/test/use-sites-table-filtering.tsx
  packages/components/src/sites-table/test/use-sites-table-sorting.jsx
  packages/components/src/sites-table/use-sites-table-sorting.tsx
Labels: [Status] Needs Review, Performance, Sites Management Page

#66354 Design Setup: Remove references to monthly subscriptions from upgrade modal
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/upgrade-modal.tsx
Labels: [Status] Needs Review, Design Picker

#66325 Site Management Dashboard: introduce tile view
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/components/sites-display-mode-switcher.tsx
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
  client/sites-dashboard/components/sites-grid-item-loading.tsx
  client/sites-dashboard/components/sites-grid-item.tsx
  client/sites-dashboard/components/sites-grid-tile.tsx
  client/sites-dashboard/components/sites-grid.tsx
  client/sites-dashboard/components/sites-launch-status-badge.tsx
  client/sites-dashboard/components/sites-site-item-thumbnail.tsx
  client/sites-dashboard/components/sites-site-name.ts
  client/sites-dashboard/components/sites-site-url.ts
  client/sites-dashboard/components/sites-table-row.tsx
  client/sites-dashboard/hooks/use-site-status.ts
  client/sites-dashboard/utils.ts
  packages/components/package.json
  packages/components/src/index.ts
  packages/components/src/site-thumbnail/index.tsx
  packages/components/src/site-thumbnail/style.scss
  packages/components/src/sites-table/use-sites-table-filtering.tsx
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66415 Site Management Dashboard: Use Gridicons instead of custom SVGs on display mode switcher
  client/sites-dashboard/components/sites-display-mode-switcher.tsx
  client/sites-dashboard/components/sites-list-icon.tsx
  client/sites-dashboard/components/sites-tiles-icon.tsx
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66007 add/promoted posts list page
  client/data/promote-post/use-promote-post-campaigns-query.ts
  client/lib/promote-post/index.ts
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
  client/my-sites/customer-home/cards/constants.js
  client/my-sites/customer-home/cards/education/promote-post/index.jsx
  client/my-sites/customer-home/cards/tasks/promote-post/index.js
  client/my-sites/customer-home/locations/secondary/learn-grow/index.jsx
  client/my-sites/promote-post/components/campaign-item/index.tsx
  client/my-sites/promote-post/components/campaign-item/style.scss
  client/my-sites/promote-post/components/campaigns-empty/index.tsx
  client/my-sites/promote-post/components/campaigns-empty/style.scss
  client/my-sites/promote-post/components/campaigns-list/index.tsx
  client/my-sites/promote-post/components/campaigns-list/style.scss
  client/my-sites/promote-post/components/post-item/index.tsx
  client/my-sites/promote-post/components/post-item/style.scss
  client/my-sites/promote-post/components/posts-list-banner/index.tsx
  client/my-sites/promote-post/components/posts-list-banner/style.scss
  client/my-sites/promote-post/components/posts-list/index.tsx
  client/my-sites/promote-post/components/posts-list/style.scss
  client/my-sites/promote-post/components/promoted-post-filter/index.tsx
  client/my-sites/promote-post/components/promoted-post-filter/style.scss
  client/my-sites/promote-post/controller.js
  client/my-sites/promote-post/index.js
  client/my-sites/promote-post/main.tsx
  client/my-sites/promote-post/style.scss
  client/sections.js
  client/state/action-types.ts
Labels: [Status] Needs Review, WordAds

#66353 Adds meatball menu to promote content in the Post and Page list
  client/my-sites/pages/page/index.js
  client/my-sites/post-type-list/post-actions-ellipsis-menu/index.jsx
  client/my-sites/post-type-list/post-actions-ellipsis-menu/promote.jsx
Labels: [Status] Needs Review, [Status] String Freeze

#66361 SMP: invalidate query on window focus and on mount
  client/data/sites/use-site-excerpts-query.ts
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66424 Add/launchpad site preview integration
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/launchpad-site-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
Labels: [Status] Needs Review

#66417 Sites Management Dashboard: Stack display controls on smaller screens
  client/sites-dashboard/components/sites-content-controls.tsx
  client/sites-dashboard/components/sites-search.ts
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66421 Site Management Dashboard: Display slug if there is no site title
  client/data/sites/use-site-excerpts-query.ts
  client/sites-dashboard/components/sites-grid-item.tsx
  client/sites-dashboard/components/sites-site-item-thumbnail.tsx
  client/sites-dashboard/components/sites-table-row.tsx
Labels: [Status] Needs Review, Sites Management Page, Reviewer Can Merge

#66333 [Calypso] Fix generated design progress bar not sticky
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx
  packages/onboarding/src/step-container/style.scss
Labels: [Status] In Progress, [Status] Needs Review

#66251 Fix Jetpack installation UX issues
  client/jetpack-connect/remote-credentials.js
  client/jetpack-connect/site-url-input.jsx
Labels: [Status] Needs Review, WordPress Migrator

#66385 Import: enable onboarding/import-redirect-to-themes in wpcalypso/stage/production
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Improve Importer Onboarding Flows

#66395 Fix error that occurs when not existing status filter is used
  packages/components/src/sites-table/use-sites-table-filtering.tsx
Labels: [Status] Needs Review, Sites Management Page
