Repository Automattic/wp-calypso, pull requests merged in 2022-04, with the labels that each got.

#62135 Themes: Refactor `ThemesSelectionWithPage` away from `UNSAFE_` methods
  client/my-sites/themes/themes-selection.jsx
Labels: [Type] Enhancement, Themes, Framework, [Status] Needs Review

#62258 [Re-Revert] Fix: locale redirect on pricing page
  client/controller/shared.js
  client/controller/test/shared.js
  client/jetpack-cloud/controller.ts
  client/jetpack-cloud/sections/pricing/controller.tsx
  client/jetpack-cloud/sections/pricing/index.ts
  client/jetpack-connect/controller.js
  client/my-sites/checkout/index.js
  client/my-sites/plans/jetpack-plans/controller.tsx
  client/my-sites/plans/jetpack-plans/get-purchase-url-callback.ts
  client/my-sites/plans/jetpack-plans/selector.tsx
  client/my-sites/plans/jetpack-plans/storage-pricing/index.tsx
  client/my-sites/plans/jetpack-plans/storage-tier-upgrade/index.tsx
  client/my-sites/plans/jetpack-plans/test/get-purchase-url-callback.js
  client/my-sites/plans/jetpack-plans/types.ts
Labels: [Status] Needs Review

#62451 Re-enable Olark in signup flow
  client/signup/main.jsx
Labels: [Status] Needs Review

#62378 Licensing Portal: Add better "missing payment method" explanation
  client/jetpack-cloud/sections/partner-portal/issue-license-form/index.tsx
  client/state/partner-portal/licenses/hooks/use-issue-license-mutation.ts
Labels: [Status] Needs Review

#62454 Sharing: Remove unused helper functions
  client/components/share/helpers.js
Labels: [Status] Needs Review, Components, [Type] Janitorial, Social Previews

#62446 Editing Toolkit: add more blocks to wpcom-block-description-links
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-description-links/src/index.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-description-links/src/inline-block-link.tsx
Labels: [Status] Needs Review, Editing Toolkit

#61262 Add VideoPress JWT-based auth.
  client/post-editor/media-modal/detail/detail-fields.jsx
  client/post-editor/media-modal/detail/detail-preview-videopress.jsx
Labels: [Status] Needs Review, Media, VideoPress

#62432 Marketplace: Popular Search click now correctly updates the Search component keyword
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/plugins/search-box-header/index.jsx
  packages/search/src/search.tsx
Labels: [Status] Needs Review

#62440 Plugins: Fix Renew Now action, take 2
  client/lib/cart-values/cart-items.ts
  client/lib/cart-values/test/cart-items.js
  client/me/purchases/manage-purchase/index.jsx
Labels: [Status] Needs Review

#62357 Site Editor: Unregister site editor feedback plugin
  apps/wpcom-block-editor/src/calypso/features/fse-beta/feedback-form.js
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Labels: [Status] Needs Review, [Goal] Full Site Editing

#62445 Pro Plan: add included features to plan definition
  packages/calypso-products/src/plans-list.tsx
Labels: Plans, [Status] Needs Review

#62442 Add an error message to the Use a domain I own flow when the user selects a subdomain
  client/components/domains/use-my-domain/utilities/get-option-info.js
Labels: [Status] Needs Review, Domains

#62474 Media Library: Fix the storage bar to show the correct limit for legacy sites
  client/blocks/plan-storage/index.jsx
  client/state/selectors/is-legacy-site-with-higher-limits.ts
  client/state/selectors/test/is-legacy-site-with-higher-limits.js
Labels: [Status] Needs Review

#62480 New plans page copy update for traffic limit description
  client/my-sites/plans-comparison/plans-comparison-features.tsx
Labels: [Status] Needs Review

#62482 Visits tooltip: Add fallback string if string is not translated
  client/my-sites/plans-comparison/plans-comparison-features.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#61245 Welcome Tour/FSE: New FSE slide if in Site Editor
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/test/tour-steps.test.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-steps.tsx
Labels: [Status] Needs Review, Welcome Tour, FSE

#62458 Onboarding intent screen: Fix enabling import button
  client/signup/steps/import/list/style.scss
  client/signup/steps/intent/index.tsx
Labels: [Status] Needs Review, Reindeer Pod

#62297 Emails: Add support for in-depth comparison in Emails Stacked comparison upsell/add
  client/my-sites/domains/controller.jsx
  client/my-sites/domains/email-providers-upsell/index.jsx
  client/my-sites/email/controller.js
  client/my-sites/email/email-management/email-home.tsx
  client/my-sites/email/email-management/home-page.tsx
  client/my-sites/email/email-providers-comparison/in-depth/comparison-list.tsx
  client/my-sites/email/email-providers-comparison/in-depth/comparison-table.tsx
  client/my-sites/email/email-providers-comparison/in-depth/email-provider-price.tsx
  client/my-sites/email/email-providers-comparison/in-depth/index.tsx
  client/my-sites/email/email-providers-comparison/in-depth/select-button.tsx
  client/my-sites/email/email-providers-comparison/in-depth/types.ts
  client/my-sites/email/email-providers-comparison/price/google-workspace.tsx
  client/my-sites/email/email-providers-comparison/price/professional-email.tsx
  client/my-sites/email/email-providers-stacked-comparison/provider-cards/professional-email-card.tsx
  client/my-sites/email/paths.js
Labels: [Status] Needs Review, Email management

#60949 Components: Refactor `DocumentHead` away from `UNSAFE_` methods
  client/components/data/document-head/index.jsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review, Components

#62322 Playwright: deal with flakiness in the `Plans` page when using mobile viewport.
  packages/calypso-e2e/src/element-helper.ts
  packages/calypso-e2e/src/lib/pages/plans-page.ts
Labels: [Status] Needs Review

#62367 E2E: add step to close the block inserter in mobile in case the auto-dismissal fails.
  packages/calypso-e2e/src/lib/components/editor-sidebar-block-inserter-component.ts
  packages/calypso-e2e/src/lib/pages/editor-page.ts
Labels: [Status] Needs Review

#62359 Update Jetpack Cloud Upsells to RNA designs
  client/assets/images/jetpack/rna-card-bg.png
  client/assets/images/jetpack/rna-image-backup.png
  client/assets/images/jetpack/rna-image-default.png
  client/assets/images/jetpack/rna-image-scan.png
  client/assets/images/jetpack/rna-image-search.png
  client/components/jetpack/card/jetpack-product-card/display-price/index.tsx
  client/components/jetpack/card/jetpack-product-card/display-price/paid.tsx
  client/components/jetpack/card/jetpack-product-card/display-price/style.scss
  client/components/jetpack/card/jetpack-product-card/display-price/time-frame.tsx
  client/components/jetpack/card/jetpack-rna-action-card/index.tsx
  client/components/jetpack/card/jetpack-rna-action-card/style.scss
  client/components/jetpack/upsell-product-card/index.tsx
  client/components/jetpack/upsell-product-card/style.scss
  client/components/jetpack/upsell-switch/index.tsx
  client/components/jetpack/upsell/style.scss
  client/my-sites/backup/backup-upsell/index.tsx
  client/my-sites/backup/backup-upsell/style.scss
  client/my-sites/jetpack-search/content.tsx
  client/my-sites/jetpack-search/controller.js
  client/my-sites/jetpack-search/index.js
  client/my-sites/jetpack-search/jetpack-search-upsell/index.tsx
  client/my-sites/jetpack-search/jetpack-search-upsell/style.scss
  client/my-sites/jetpack-search/main-jetpack.tsx
  client/my-sites/jetpack-search/main-wpcom-simple.tsx
  client/my-sites/jetpack-search/main.tsx
  client/my-sites/jetpack-search/placeholder.tsx
  client/my-sites/jetpack-search/style.scss
  client/my-sites/plan-price/style.scss
  client/my-sites/scan/scan-upsell/index.jsx
  client/my-sites/scan/scan-upsell/style.scss
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud, Jetpack Search, Jetpack Backup, Jetpack Scan, Upsell Nudge

#62375 Help Center: New container
  packages/help-center/.storybook/main.js
  packages/help-center/.storybook/preview.js
  packages/help-center/.storybook/styles.scss
  packages/help-center/README.md
  packages/help-center/jest.config.js
  packages/help-center/package.json
  packages/help-center/src/components/help-center-container.tsx
  packages/help-center/src/components/help-center-content.tsx
  packages/help-center/src/components/help-center-footer.tsx
  packages/help-center/src/components/help-center-header.tsx
  packages/help-center/src/components/help-center.tsx
  packages/help-center/src/components/types.ts
  packages/help-center/src/index.ts
  packages/help-center/src/storybook/index.stories.tsx
  packages/help-center/src/styles.scss
  packages/help-center/tsconfig-cjs.json
  packages/help-center/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review

#62390 Update Cloud empty purchases screen to RNA design.
  client/components/data/query-billing-transaction/index.jsx
  client/me/purchases/titles.js
  client/my-sites/plans/navigation.jsx
  client/my-sites/purchases/billing-history/index.tsx
  client/my-sites/purchases/main.tsx
  client/my-sites/purchases/navigation.tsx
  client/my-sites/purchases/payment-methods/index.tsx
  client/my-sites/purchases/subscriptions/subscriptions-content.tsx
Labels: Jetpack, [Status] Needs Review, Purchases, Jetpack Cloud

#62467 Videos UI: README
  client/components/videos-ui/README.md
Labels: [Status] Needs Review

#62029 Add subtitles and descriptions to scan results based on threat signature
  client/components/jetpack/threat-description/index.tsx
  client/components/jetpack/threat-item-subheader/index.tsx
  client/components/jetpack/threat-item/index.tsx
  client/components/jetpack/threat-item/test/utils.ts
  client/components/jetpack/threat-item/types.tsx
  client/components/jetpack/threat-item/utils.ts
Labels: [Type] Enhancement, [Status] Needs Review, Jetpack Scan

#62317 Domains: Prevent domain actions for domains with `pendingRegistration`
  client/lib/domains/resolve-domain-status.tsx
  client/my-sites/domains/domain-management/components/domain/domain-info-card/delete/index.tsx
  client/my-sites/domains/domain-management/components/domain/domain-info-card/transfer/index.tsx
  client/my-sites/domains/domain-management/settings/cards/registered-domain-details.tsx
  client/my-sites/domains/domain-management/transfer/transfer-page/index.tsx
  client/my-sites/domains/domain-management/transfer/transfer-to-other-site/transfer-domain-to-other-site.tsx
  client/my-sites/domains/domain-management/transfer/transfer-to-other-user/transfer-domain-to-other-user.jsx
  client/my-sites/domains/domain-management/transfer/transfer-unavailable-notice/index.tsx
  client/my-sites/domains/domain-management/transfer/transfer-unavailable-notice/style.scss
  client/my-sites/domains/domain-management/transfer/transfer-unavailable-notice/types.ts
Labels: [Status] Needs Review, Domains

#62463 Seller Experience/Stepper: Hook to load WooCommerce countries from the API
  client/landing/stepper/hooks/test/use-countries.jsx
  client/landing/stepper/hooks/use-countries.ts
Labels: [Status] Needs Review, Seller Experience, Stepper

#62408 Fix border hover cosmetic issues
  client/signup/difm/components/BrowserView.tsx
  client/signup/difm/images/page-descriptions/about-page.svg
  client/signup/difm/images/page-descriptions/blog-page.svg
  client/signup/difm/images/page-descriptions/contact-page.svg
  client/signup/difm/images/page-descriptions/faq.svg
  client/signup/difm/images/page-descriptions/home-page.svg
  client/signup/difm/images/page-descriptions/photo-gallery.svg
  client/signup/difm/images/page-descriptions/podcast.svg
  client/signup/difm/images/page-descriptions/portfolio.svg
  client/signup/difm/images/page-descriptions/profiles.svg
  client/signup/difm/images/page-descriptions/service-showcase.svg
  client/signup/difm/images/page-descriptions/video-gallery.svg
  client/signup/difm/images/three-dots.svg
  client/signup/steps/page-picker/index.tsx
Labels: [Status] Needs Review, difm-lite

#62503 Marketplace: Indicate that popular search term has been clicked
  client/my-sites/plugins/search-box-header/index.jsx
  client/my-sites/plugins/search-box-header/style.scss
Labels: [Status] Needs Review, [Status] Ready to Merge, Marketplace

#62338 Add a new site name independent path to redirect users to a domain's management page.
  client/lib/domains/get-site-slug-domain.ts
  client/my-sites/domains/controller.jsx
  client/my-sites/domains/domain-redirect-to-site/index.tsx
  client/my-sites/domains/index.js
Labels: [Status] Needs Review, Domains

#62509 Support: Fix wordpress importers context link
  client/components/inline-support-link/context-links.js
Labels: [Type] Enhancement, [Status] Needs Review, Support, Help

#62100 Add TUS uploader for video files uploads from media library
  packages/wpcom.js/package.json
  packages/wpcom.js/src/lib/site.media.js
  packages/wpcom.js/src/lib/tus-uploader.js
  yarn.lock
Labels: [Status] Ready to Merge, VideoPress

#62464 Fix validation of checkoutBackURL for localised jetpack url
  client/my-sites/checkout/composite-checkout/hooks/use-valid-checkout-back-url.ts
Labels: Jetpack, [Status] Needs Review, Checkout

#62518 WooCommerce installer: Fix upgrade warning
  client/signup/steps/woocommerce-install/hooks/use-woop-handling/index.ts
  client/state/selectors/has-available-site-feature.js
Labels: [Status] Needs Review, Woop

#62524 Pick the right plan in the checkout route
  client/my-sites/migrate/section-migrate.jsx
Labels: [Status] Needs Review

#62529 Pro plan: add missing feature related to the site migration
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review

#62534 Domains: Fix wrong description for domains with pending registration transfer
  client/my-sites/domains/domain-management/transfer/transfer-page/index.tsx
  client/my-sites/domains/domain-management/transfer/transfer-to-other-site/transfer-domain-to-other-site.tsx
  client/my-sites/domains/domain-management/transfer/transfer-to-other-user/transfer-domain-to-other-user.jsx
Labels: [Status] Needs Review, Domains

#62525 Seller Experience - Stepper: Add WooCommerce PoC feature flag
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Seller Experience, Stepper

#62522 Update the storage space to 1024 in plan-storage
  client/blocks/plan-storage/index.jsx
Labels: [Status] Needs Review

#62535 Checkout: Ignore analytics errors when adding products
  client/my-sites/checkout/composite-checkout/composite-checkout.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-record-cart-loaded.ts
Labels: [Status] Needs Review, Checkout

#62536 Update message shown when selected subdomain is a wordpress.com free URL subdomain
  client/lib/domains/registration/availability-messages.js
Labels: [Status] Needs Review, Domains

#62542 Domains: Show an error message when trying to connect an already connected subdomain
  client/components/domains/use-my-domain/utilities/get-availability-error-message.js
Labels: [Status] Needs Review, Domains

#62504 Fix "open in new tab" keyboard modifiers in wpcom block editor
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Labels: [Type] Bug, [Status] Needs Review

#62507 Fix nav from the individual domain view back to the all domains view
  client/my-sites/domains/domain-management/settings/index.tsx
Labels: [Type] Bug, [Status] Needs Review, Domains

#62493 `SiteRedirectCard`: refactor away from `UNSAFE_*`
  client/my-sites/domains/domain-management/settings/cards/site-redirect-card.jsx
Labels: [Status] Needs Review, [Type] Janitorial, Domains

#62483 Olark chat: Add error boundary
  client/components/olark-chat/README.md
  client/components/olark-chat/index.jsx
  client/components/olark-chat/main.jsx
  client/components/olark-chat/olark-error-boundary.jsx
  client/jetpack-cloud/sections/partner-portal/header/index.tsx
  client/signup/main.jsx
Labels: [Status] Needs Review

#62530 Stepper: add all missing data pieces and activate going to checkout on upgrading
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/index.tsx
  packages/data-stores/src/site/types.ts
Labels: [Status] Needs Review

#62489 Help center: Implement help center entry point
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/help-center/class-help-center.php
  apps/editing-toolkit/editing-toolkit-plugin/help-center/index.js
  apps/editing-toolkit/editing-toolkit-plugin/help-center/src/help-center.js
  apps/editing-toolkit/editing-toolkit-plugin/help-center/src/help-center.scss
  apps/editing-toolkit/package.json
  apps/wpcom-block-editor/src/calypso/editor.js
  yarn.lock
Labels: [Status] Needs Review

#61361 Experiment: Add Upgrade button to Masterbar
  client/layout/masterbar/logged-in.jsx
  client/layout/masterbar/plan-upsell.jsx
  client/layout/masterbar/style.scss
Labels: [Status] Needs Review

#62547 Remove box shadow from search icon when focused
  client/my-sites/plugins/search-box-header/style.scss
Labels: [Status] Needs Review, [Status] Ready to Merge

#62324 E2E: re-add existing tests to the Jetpack group.
  .teamcity/_self/projects/WPComTests.kt
  packages/calypso-e2e/src/env-variables.ts
  packages/calypso-e2e/src/lib/pages/themes-page.ts
  test/e2e/config/encrypted.enc
  test/e2e/package.json
  test/e2e/specs/appearance/theme__details-preview-activate.ts
  test/e2e/specs/appearance/theme__popover-preview.ts
  test/e2e/specs/media/media__edit.ts
  test/e2e/specs/media/media__upload.ts
  yarn.lock
Labels: [Status] Needs Review

#62427 Site Design Picker : Remove button to use blank canvas
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/index.tsx
  client/signup/steps/design-picker/index.jsx
Labels: [Status] Needs Review, Design Picker

#62519 Add infinite scroll hook to WP.org requests.
  client/data/marketplace/use-wporg-plugin-query.ts
  client/my-sites/plugins/plugins-browser/index.jsx
Labels: [Status] Needs Review

#62385 Seller Experience - Stepper: Implement the store-address step
  client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/store-address/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/store-address/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/store-address/support-card.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/style.scss
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  packages/data-stores/src/onboard/actions.ts
  packages/data-stores/src/onboard/reducer.ts
  packages/data-stores/src/onboard/selectors.ts
  packages/data-stores/src/shared-types.ts
Labels: [Status] Needs Review, Seller Experience, Stepper

#62500 Seller experience: Replace plan checks by features
  client/landing/stepper/declarative-flow/internals/steps-repository/store-features/index.tsx
  client/signup/steps/store-features/index.tsx
  client/signup/steps/store-features/intents.tsx
  packages/data-stores/src/site/selectors.ts
Labels: Seller Experience

#62533 Plugins Browser: Use infinite scroll when searching plugins.
  client/data/marketplace/use-wporg-plugin-query.ts
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/plugins/plugins-browser/test/index.jsx
Labels: [Status] Needs Review

#62532 Marketplace: Fixes search bar on the header when scrolling.
  client/components/fixed-navigation-header/index.tsx
  client/lib/use-scroll-above-element/README.md
  client/lib/use-scroll-above-element/index.tsx
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/plugins/search-box-header/index.jsx
  client/my-sites/plugins/search-box-header/style.scss
Labels: [Status] Needs Review

#62487 Updates copy on DIFM options page
  client/signup/steps/site-options/index.tsx
  client/signup/steps/site-options/site-options.tsx
Labels: [Status] Needs Review, difm-lite

#62550 Design updates for the DIFM flow
  client/signup/difm/translation-hooks.tsx
  client/signup/steps/page-picker/index.tsx
  client/signup/steps/social-profiles/index.tsx
  client/signup/steps/social-profiles/social-profiles.tsx
  client/signup/steps/website-content/index.tsx
Labels: [Status] Needs Review, difm-lite

#62365 Implement site vertical step in onboarding
  client/assets/images/onboarding/site-vertical.svg
  client/components/select-vertical/index.tsx
  client/components/select-vertical/style.scss
  client/components/select-vertical/suggestion-search.tsx
  client/components/select-vertical/types.ts
  client/data/site-verticals/index.ts
  client/data/site-verticals/types.ts
  client/data/site-verticals/use-site-verticals-query.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/form.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/form.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/index.tsx
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#62559 Stepper: Fixed missing style in stepper web preview
  client/components/web-preview/component.jsx
  client/components/web-preview/content.jsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss
Labels: [Status] Needs Review

#62581 Add on-enter searchMode to search component
  client/my-sites/plugins/search-box-header/index.jsx
  packages/search/src/search.tsx
Labels: [Status] Needs Review

#62548 Move cta hiding to woo landing page
  client/components/fixed-navigation-header/index.tsx
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/woocommerce/landing-page.tsx
Labels: [Status] Needs Review, [Status] Ready to Merge

#62472 Query all sites features when there is no selected site
  client/components/data/query-site-features/index.jsx
  client/layout/index.jsx
  client/my-sites/plugins/plugin-details.jsx
  client/signup/steps/store-features/index.tsx
Labels: [Status] Needs Review

#62353 Plugin Details: Upgrade needed site list
  client/lib/plugins/utils.js
  client/my-sites/plugins/plugin-details-CTA/index.jsx
  client/my-sites/plugins/plugin-details.jsx
  client/my-sites/plugins/plugin-install-button/index.jsx
  client/state/plugins/installed/selectors.js
Labels: [Status] Needs Review

#62583 Force PluginsBrowser rendering when a search term is present
  client/my-sites/plugins/controller.js
Labels: [Status] Needs Review, Marketplace

#62612 Disable feature flag for signup/site-vertical-step in favor of explicitly via URL
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#62588 Add Jetpack Boost products to allow for variant selection
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/constants/jetpack.ts
  packages/calypso-products/src/products-list.ts
Labels: [Status] Needs Review

#62601 Stepper: Fix overlapping header on mobile
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss
Labels: [Status] Needs Review

#62591 People: Prevent viewers from being created on Atomic sites
  client/my-sites/people/invite-people/index.jsx
Labels: [Status] Needs Review, People Management

#62567 Help Center: Show help center after click on icon
  apps/editing-toolkit/editing-toolkit-plugin/help-center/src/help-center.js
  apps/editing-toolkit/editing-toolkit-plugin/help-center/src/help-center.scss
  apps/editing-toolkit/package.json
  yarn.lock
Labels: [Status] Needs Review

#62400 Show verticalized designs in the Design Picker
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/categories.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/index.tsx
  client/signup/steps/difm-design-picker/themes.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
  packages/design-picker/src/components/index.tsx
  packages/design-picker/src/generated-designs-config.json
  packages/design-picker/src/hooks/use-generated-designs.ts
  packages/design-picker/src/hooks/use-theme-designs-query.ts
  packages/design-picker/src/index.ts
  packages/design-picker/src/types.ts
  packages/design-picker/src/utils/__tests__/designs.test.ts
  packages/design-picker/src/utils/available-designs.ts
  packages/design-picker/src/utils/designs.ts
  packages/design-picker/src/utils/index.ts
Labels: [Status] Needs Review

#62590 DIFM: Fixes prop for signup submit event
  client/state/signup/progress/actions.js
Labels: [Status] Needs Review, difm-lite

#62565 G Suite: Import Google Workspace functions from Calypso Products package directly
  client/lib/gsuite/index.js
  client/lib/gsuite/new-users.ts
  client/my-sites/checkout/checkout-thank-you/google-apps-details.jsx
  client/my-sites/checkout/checkout-thank-you/header.jsx
  client/my-sites/checkout/composite-checkout/lib/get-contact-details-type.ts
  packages/calypso-products/src/constants/google.ts
Labels: [Status] Needs Review, G Suite

#62569 G Suite: Move Google Workspace selectors in Calypso Products package into their own files
  packages/calypso-products/src/gsuite-product-slug.ts
  packages/calypso-products/src/index.ts
  packages/calypso-products/src/is-google-workspace-extra-license.ts
  packages/calypso-products/src/is-google-workspace-product-slug.ts
  packages/calypso-products/src/is-google-workspace.ts
  packages/calypso-products/src/is-gsuite-extra-license-product-slug.ts
  packages/calypso-products/src/is-gsuite-or-extra-license-or-google-workspace.ts
  packages/calypso-products/src/is-gsuite-or-extra-license-product-slug.ts
  packages/calypso-products/src/is-gsuite-or-extra-license.ts
  packages/calypso-products/src/is-gsuite-or-google-workspace-product-slug.ts
  packages/calypso-products/src/is-gsuite-or-google-workspace.ts
  packages/calypso-products/src/is-gsuite-product-slug.ts
  packages/calypso-products/src/is-gsuite.ts
  packages/calypso-products/src/product-values.ts
Labels: [Status] Needs Review, G Suite

#62593 Enable the redesigned DIFM flow
  client/signup/steps/social-profiles/social-profiles.tsx
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, difm-lite

#62626 Domains: Remove old NameServers component
  client/lib/domains/resolve-domain-status.tsx
  client/me/purchases/remove-purchase/remove-domain-dialog/index.jsx
  client/my-sites/controller.js
  client/my-sites/domains/components/domain-warnings/index.jsx
  client/my-sites/domains/domain-management/controller.jsx
  client/my-sites/domains/domain-management/dns/dns-records.jsx
  client/my-sites/domains/domain-management/edit/domain-only-notice.jsx
  client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
  client/my-sites/domains/domain-management/index.jsx
  client/my-sites/domains/domain-management/name-servers/index.jsx
  client/my-sites/domains/domain-management/transfer/transfer-out/warning.jsx
  client/my-sites/domains/index.js
  client/my-sites/domains/paths.js
Labels: [Status] Needs Review, Domains

#62604 Change labels in Memebership Subscription Page for one-time payment
  client/me/memberships/subscription.jsx
Labels: [Status] Ready to Merge

#62624 Hide tab's contents until the tab is hovered
  client/components/environment-badge/style.scss
Labels: [Status] Needs Review

#62616 Stripe connected accounts can access earn regardless of plan
  client/my-sites/earn/home.tsx
  client/my-sites/earn/memberships/index.jsx
  client/my-sites/earn/memberships/products.jsx
  packages/calypso-products/src/constants/features.ts
Labels: [Status] Ready to Merge

#62465 Site Editor: Remove unused site editor feedback form logic
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.scss
  client/gutenberg/editor/calypsoify-iframe.tsx
  client/lib/fse-beta/send-site-editor-beta-feedback.js
Labels: [Status] Needs Review, [Goal] Full Site Editing

#62498 Site Editor: Override the help link to point to the correct support document
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-documentation-links/src/index.tsx
Labels: Documentation, [Status] Needs Review, Editing Toolkit

#62635 Plans: Handle case where there is no highestPlan and planProperties is empty
  client/my-sites/plan-features/index.jsx
Labels: [Type] Bug, Plans

#62628 Updating free domain copy on the domain step.
  client/components/domains/reskin-side-explainer/index.jsx
  client/components/domains/reskin-side-explainer/style.scss
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review, Signup

#62637 Plugins: Check site type when defining shouldUpgrade const
  client/my-sites/plugins/plugin-details-CTA/index.jsx
Labels: [Status] Needs Review

#62610 [ETK][error-reporting] Point the Sentry SDK configuration to a test release in Sentry
  apps/editing-toolkit/editing-toolkit-plugin/error-reporting/index.js
Labels: [Status] Needs Review

#62632 [ETK][error-reporting] Update Sentry packages
  apps/editing-toolkit/package.json
  yarn.lock
Labels: [Status] Needs Review

#62652 Add labels for Jetpack Boost product as shown on My Plans page
  packages/calypso-products/src/translations.tsx
Labels: [Status] Needs Review

#62381 DIFM: Fetch themes from the server
  client/signup/steps/design-picker/index.jsx
  client/signup/steps/design-picker/let-us-choose.tsx
  client/signup/steps/difm-design-picker/themes.tsx
  packages/design-picker/src/types.ts
Labels: [Status] Needs Review, DO NOT MERGE, difm-lite

#62625 Stepper: fix scroll position when changing route
  client/landing/stepper/declarative-flow/internals/index.tsx
Labels: [Status] Needs Review, Stepper

#62012 Domains: Remove unused `DomainNotice` component
  client/my-sites/domains/domain-management/components/domain-notice/index.jsx
  client/my-sites/domains/domain-management/components/domain-notice/style.scss
  client/my-sites/domains/domain-management/list/style.scss
Labels: [Status] Needs Review, [Type] Janitorial, Domains

#62552 Make DocumentHead work in SSR
  client/boot/common.js
  client/components/data/document-head/index.jsx
  client/landing/login/index.js
  client/server/pages/index.js
  client/server/pages/test/index.js
  client/server/render/index.js
  client/state/add-reducer.ts
  client/state/initial-state.js
  client/state/redux-store.ts
  client/state/test/initial-state.js
Labels: [Status] Needs Review

#62556 Emails: Adding mailboxes fails when provisioning is happening on server-side
  client/my-sites/email/email-management/home/email-plan.jsx
Labels: [Status] Needs Review, Email management

#62655 Fix: Pro plan price in the site launch flow is zero
  client/my-sites/plans-comparison/plans-comparison.tsx
  client/my-sites/plans-comparison/use-plan-prices.tsx
Labels: [Status] Needs Review

#62527 Disable bilmur on the desktop app
  packages/calypso-config/src/desktop.ts
Labels: [Status] Needs Review

#62350 Licensing Portal: Update billing UI to display usage for daily usage pricing
  client/jetpack-cloud/sections/partner-portal/billing-details/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-product-card/index.tsx
  client/state/partner-portal/licenses/hooks/use-billing-dashboard-query.ts
  client/state/partner-portal/licenses/test/hooks.js
  client/state/partner-portal/types.ts
Labels: [Status] Needs Review, Jetpack Cloud, Jetpack Licensing Portal

#62606 Enable VideoPress Privacy Setting on wpcom simple sites.
  client/post-editor/media-modal/detail/detail-fields.jsx
Labels: [Status] Needs Review, VideoPress

#62675 Seller Experience: Change subtitle on Start simple
  client/signup/steps/store-features/intents.tsx
Labels: [Status] Needs Review, Seller Experience

#62676 Anchor: Add the `anchor-fm` feature flag, enabled only on dev
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Anchor.FM

#62505 Stepper: Added business-info step
  client/landing/stepper/declarative-flow/internals/steps-repository/business-info/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/business-info/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  packages/data-stores/src/site/actions.ts
  packages/data-stores/src/site/reducer.ts
  packages/data-stores/src/site/resolvers.ts
  packages/data-stores/src/site/selectors.ts
  packages/data-stores/src/site/types.ts
Labels: [Status] Needs Review

#62611 Add tracking and store site preferences on vertical question submission
  client/components/select-vertical/index.tsx
  client/components/select-vertical/style.scss
  client/components/select-vertical/suggestion-search.tsx
  client/data/site-verticals/types.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/blogger-starting-point/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intent-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/form.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/store-features/index.tsx
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  packages/data-stores/src/site/actions.ts
  packages/data-stores/src/site/reducer.ts
  packages/data-stores/src/site/types.ts
Labels: [Status] Needs Review

#62380 Limit P2 functionality only for P2 sites
  client/blocks/reader-combined-card/index.jsx
  client/blocks/reader-combined-card/post.jsx
  client/blocks/reader-feed-header/index.jsx
  client/blocks/reader-full-post/index.jsx
  client/blocks/reader-post-card/index.jsx
  client/blocks/reader-post-options-menu/index.jsx
  client/reader/a8c/main.jsx
  client/reader/following/main.jsx
  client/reader/get-helpers.js
  client/reader/sidebar/reader-sidebar-followed-sites/index.jsx
  client/reader/stream/x-post.jsx
  client/state/reader/follows/selectors/get-reader-follow-for-feed.js
  client/state/reader/follows/selectors/has-reader-follows-organization.js
  client/state/reader/follows/selectors/index.js
Labels: [Status] Needs Review

#62568 `EditorMediaModalDetailFields`: refactor away from `UNSAFE_*`
  client/post-editor/media-modal/detail/detail-fields.jsx
  client/post-editor/media-modal/detail/detail-item.jsx
Labels: [Status] Needs Review, Media, [Type] Janitorial

#62658 `EditorMediaModalGallery`: refactor away from `UNSAFE_*`
  client/post-editor/media-modal/gallery/index.jsx
Labels: [Status] Needs Review, Media, [Type] Janitorial

#62621 Full importer improvements
  client/my-sites/migrate/section-migrate.jsx
  client/signup/steps/import-from/wordpress/import-everything/confirm-upgrade-plan.tsx
Labels: [Status] Needs Review, Reindeer Pod

#62379 Stepper: added processing screen at end of seller flow
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/style.scss
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  packages/data-stores/src/onboard/actions.ts
  packages/data-stores/src/onboard/reducer.ts
  packages/data-stores/src/onboard/selectors.ts
Labels: [Status] Needs Review

#62429 Stepper: Change Stepper pathname to setup
  client/landing/stepper/index.tsx
  client/landing/stepper/section.ts
  client/server/pages/index.js
Labels: [Status] Needs Review

#62620 Remove billing period toggle for a free plugin that requires an upgrade
  client/my-sites/plugins/plugin-details.jsx
Labels: [Status] Needs Review, Marketplace

#62594 Marketplace: Font size in search input is less than 16px on mobile
  client/my-sites/plugins/search-box-header/style.scss
Labels: [Status] Needs Review, [Status] Ready to Merge, Marketplace

#62636 Playwright: Editor Tracking -- Add initial block insertion event specs
  packages/calypso-e2e/src/env-variables.ts
  packages/calypso-e2e/src/index.ts
  packages/calypso-e2e/src/lib/pages/editor-page.ts
  packages/calypso-e2e/src/lib/utils/editor-tracks-event-manager.ts
  packages/calypso-e2e/src/types.d.ts
  test/e2e/specs/editor-tracking/editor-tracking__block-events.ts
Labels: [Status] Needs Review

#62711 VideoPress: increase chunk size to speed up uploads
  packages/wpcom.js/src/lib/tus-uploader.js
Labels: [Status] Needs Review, VideoPress

#62573 Marketplace: "search on hit enter" search component
  client/my-sites/plugins/search-box-header/index.jsx
  packages/search/CHANGELOG.md
  packages/search/README.md
  packages/search/package.json
  packages/search/src/search.stories.jsx
  packages/search/src/search.tsx
  packages/search/src/test/index.js
  yarn.lock
Labels: [Status] Needs Review

#62663 Fix default site suggestion positioning
  client/signup/steps/p2-site/index.jsx
  client/signup/steps/p2-site/style.scss
Labels: [Status] Needs Review

#62629 Add padding to stepper container
  packages/onboarding/src/step-container/style.scss
Labels: [Status] Needs Review, Stepper

#62586 MediaModal: refactor video editing related cmps away from `UNSAFE_*`
  client/blocks/video-editor/index.jsx
  client/post-editor/media-modal/detail/detail-preview-video.jsx
  client/post-editor/media-modal/detail/detail-preview-videopress.jsx
Labels: Framework, [Status] Needs Review, Media, [Type] Janitorial

#62469 Licensing Portal: Add an Invoices section
  client/components/jetpack/sidebar/menu-items/jetpack-icons.jsx
  client/jetpack-cloud/sections/partner-portal/controller.tsx
  client/jetpack-cloud/sections/partner-portal/index.ts
  client/jetpack-cloud/sections/partner-portal/invoices-list/index.tsx
  client/jetpack-cloud/sections/partner-portal/invoices-list/style.scss
  client/jetpack-cloud/sections/partner-portal/primary/invoices-dashboard/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/invoices-dashboard/style.scss
  client/jetpack-cloud/sections/partner-portal/sidebar/index.tsx
  client/state/partner-portal/invoices/hooks/use-invoices-query.ts
  client/state/partner-portal/invoices/test/hooks.js
  client/state/partner-portal/licenses/test/hooks.js
  client/state/partner-portal/types.ts
Labels: [Status] Needs Review, Jetpack Cloud, Jetpack Licensing Portal

#62602 Licensing Portal: Add notices about automatic billing on credit card management screens
  client/jetpack-cloud/sections/partner-portal/payment-method-delete-primary-confirmation/index.tsx
  client/jetpack-cloud/sections/partner-portal/payment-method-delete-primary-confirmation/style.scss
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-add/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-add/style.scss
Labels: [Status] Needs Review, Jetpack Cloud, Jetpack Licensing Portal

#62708 Use the default 'Not found' image when a theme is not found
  client/my-sites/theme/theme-not-found-error.jsx
Labels: [Status] Needs Review

#62678 Begin adding Anchor.fm as a separate flow
  client/landing/stepper/declarative-flow/anchor-fm-flow.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/font-pairing/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/podcast-title/index.tsx
  client/landing/stepper/index.tsx
Labels: [Status] Needs Review, Anchor.FM

#62320 Checkout: Convert new credit card payment method to TypeScript
  client/me/purchases/add-new-payment-method/index.tsx
  client/me/purchases/manage-purchase/change-payment-method/use-create-assignable-payment-methods.ts
  client/my-sites/checkout/composite-checkout/components/spinner.js
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-methods/index.ts
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/contact-fields.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-cvv-field.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-expiry-field.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-fields.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-loading.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-number-field.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-pay-button.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/cvv-image.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/form-layout-components.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/index.js
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/index.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/store.ts
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/types.ts
  client/my-sites/checkout/composite-checkout/test/credit-card.tsx
  client/my-sites/checkout/composite-checkout/test/util/index.ts
  client/my-sites/purchases/payment-methods/index.tsx
  packages/wpcom-checkout/src/field.tsx
Labels: [Status] Needs Review, Checkout

#62704 Upgrades: Rename 'New Plans' tab for free and flexible sites to 'Plans'
  client/my-sites/plans/navigation.jsx
Labels: Plans, [Status] Needs Review

#62741 Seller Experience: Site data-store selector for checking if a site is atomic
  client/landing/stepper/hooks/use-is-site-atomic.ts
  packages/data-stores/src/site/selectors.ts
Labels: [Status] Needs Review, Seller Experience, Stepper

#62680 Anchor: Add podcast title step UI
  client/landing/stepper/declarative-flow/internals/steps-repository/podcast-title/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/podcast-title/style.scss
Labels: [Status] Needs Review, Anchor.FM

#62642 Mini-cart: Fix scrollbar styles
  packages/mini-cart/src/mini-cart-line-items.tsx
Labels: [Status] Needs Review

#62572 Checkout: Do not update cart contact details on auto-refresh
  client/my-sites/checkout/composite-checkout/hooks/use-cached-domain-contact-details.ts
Labels: [Type] Bug, [Status] Needs Review, Checkout

#62748 Stepper: Anchor.fm, Added check for anchor_podcast query param
  client/landing/stepper/index.tsx
Labels: [Status] Needs Review

#62677 Remove premium content & newsletter for jp sites
  client/my-sites/earn/home.tsx
Labels: [Status] Ready to Merge, Earn

#62732 `ConfirmCancelDomain`: refactor away from `UNSAFE_*`
  client/me/purchases/confirm-cancel-domain/index.jsx
Labels: [Status] Needs Review, [Type] Janitorial, Domains

#62766 Add a fragment component to the required key.
  client/my-sites/plugins/search-box-header/index.jsx
Labels: [Status] Needs Review

#62502 Disable free plan when user is connecting a domain in signup
  client/my-sites/plans-comparison/plans-comparison-action.tsx
  client/my-sites/plans-comparison/plans-comparison.tsx
  client/my-sites/plans-comparison/plans-domain-connection-info.tsx
  client/signup/steps/plans/index.jsx
Labels: [Status] Needs Review, Domains, [Status] String Freeze

#62471 Playwright: Create site editor POM and start FSE related tracking specs
  packages/calypso-e2e/src/lib/components/editor-block-list-view-component.ts
  packages/calypso-e2e/src/lib/components/editor-popover-menu-component.ts
  packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts
  packages/calypso-e2e/src/lib/components/editor-welcome-tour-component.ts
  packages/calypso-e2e/src/lib/components/index.ts
  packages/calypso-e2e/src/lib/pages/editor-page.ts
  packages/calypso-e2e/src/lib/pages/full-site-editor-page.ts
  packages/calypso-e2e/src/lib/pages/index.ts
  packages/calypso-e2e/src/lib/pages/shared-types/editor-types.ts
  packages/calypso-e2e/src/lib/pages/shared-types/index.ts
  packages/calypso-e2e/src/lib/utils/editor-tracks-event-manager.ts
  test/e2e/specs/editor-tracking/editor-tracking__toolbar-events.ts
Labels: [Status] Needs Review

#62775 ETK NUX: fix duplicating masterbar from blogger flow
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/post-published-modal/index.tsx
  apps/editing-toolkit/typings/index.d.ts
Labels: [Type] Bug, [Status] Needs Review, NUX

#62607 Fix/hide atomic credentials
  client/components/advanced-credentials/credentials-form/index.tsx
  client/components/advanced-credentials/credentials-form/inline-info.tsx
  client/components/advanced-credentials/form.ts
  client/components/advanced-credentials/index.tsx
Labels: [Status] Needs Review, Atomic, Jetpack Backup

#62737 VideoPress: Allow player events to set the isPlaying state in the video editor controls
  client/blocks/video-editor/index.jsx
  client/post-editor/media-modal/detail/detail-preview-videopress.jsx
Labels: [Status] Needs Review

#62736 Backup: Make the storage usage bar more visible/readable
  client/components/activity-card-list/visible-days-limit-upsell/index.tsx
  client/components/backup-storage-space/hooks.tsx
  client/components/backup-storage-space/index.tsx
  client/components/backup-storage-space/storage-usage-levels.ts
  client/components/backup-storage-space/style.scss
  client/components/backup-storage-space/test/hooks.js
  client/components/backup-storage-space/usage-display.tsx
  client/components/backup-storage-space/usage-warning/action-button.tsx
  client/components/backup-storage-space/usage-warning/index.tsx
  client/components/backup-storage-space/usage-warning/manage-storage.tsx
  client/components/backup-storage-space/usage-warning/upsell.tsx
  client/components/backup-storage-space/usage-warning/use-storage-status-text.ts
  client/components/jetpack/daily-backup-status/status-card/visible-days-limit.tsx
  client/my-sites/plans/current-plan/my-plan-card/style.scss
  client/state/plans/selectors/get-jetpack-storage-upgrade-url.ts
  client/state/plans/selectors/index.js
Labels: [Type] Enhancement, Plans, [Status] Needs Review, [Type] Janitorial, [Size] S, Jetpack Cloud, Jetpack Backup

#62787 Revert "Checkout: Do not update cart contact details on auto-refresh"
  client/my-sites/checkout/composite-checkout/hooks/use-cached-domain-contact-details.ts
Labels: [Status] Needs Review

#62751 Jetpack Cloud: Add search redirect for landing page
  client/jetpack-cloud/sections/landing.tsx
  client/state/purchases/selectors/site-has-search-product-purchase.js
Labels: [Type] Enhancement, [Status] Needs Review, Jetpack Cloud, Jetpack Search

#62743 Stepper: Add state management for Anchor.fm - Podcast name step
  client/landing/stepper/declarative-flow/internals/steps-repository/podcast-title/index.tsx
Labels: [Status] Needs Review

#62735 Anchor: Add design selection UI
  client/landing/stepper/declarative-flow/get-anchor-podcast-id.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/anchor-fm-themes.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss
  client/landing/stepper/index.tsx
  packages/design-picker/src/components/index.tsx
  packages/design-picker/src/utils/designs.ts
Labels: [Status] Needs Review, Anchor.FM

#61665 Experiment: Domains mobile add domain description
  client/components/domains/register-domain-step/style.scss
  client/signup/controller.js
  client/signup/steps/domains/index.jsx
  client/signup/steps/domains/style.scss
Labels: [Status] Needs Review, Signup, Domains

#62738 Experiment: Update Masterbar Upgrade experiment name
  client/layout/masterbar/plan-upsell.jsx
Labels: [Status] Needs Review

#62681 Fix product card incorrectly displays multisite incompatible
  client/components/jetpack/card/jetpack-product-card/index.tsx
  client/components/jetpack/card/jetpack-product-card/style.scss
  client/my-sites/plans/jetpack-plans/product-card/index.tsx
Labels: Jetpack, Plans, [Status] Needs Review

#62818 Stepper: fix ESLINT warning
  client/landing/stepper/README.md
Labels: Stepper

#62742 Help Center: apply styling changes
  packages/help-center/.storybook/styles.scss
  packages/help-center/src/components/help-center-header.tsx
  packages/help-center/src/styles.scss
Labels: [Status] Needs Review, Help Center

#62694 Stepper: support for siteId and added useAssertConditions
  client/landing/stepper/README.md
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/types.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  client/landing/stepper/hooks/test/use-site-id-param.ts
  client/landing/stepper/hooks/use-site-id-param.ts
  client/landing/stepper/hooks/use-site.ts
Labels: [Status] Needs Review, Stepper

#62605 Guidance: Implement the new mobile master bar
  client/assets/stylesheets/_nav-unification.scss
  client/layout/masterbar/logged-in.jsx
  client/layout/masterbar/masterbar-menu.tsx
  client/layout/masterbar/style.scss
  client/layout/masterbar/write-icon.tsx
Labels: [Status] Needs Review, Help Center

#62780 Anchor: Apply styles from site-setup flow to Anchor signup flow
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/podcast-title/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/podcast-title/style.scss
Labels: [Status] Needs Review, Anchor.FM, Stepper

#62726 Add stored vertical from site settings to the vertical question screen (if site has already set a vertical)
  client/components/select-vertical/index.tsx
  client/components/select-vertical/style.scss
  client/components/select-vertical/suggestion-search.tsx
  client/data/site-verticals/index.ts
  client/data/site-verticals/types.ts
  client/data/site-verticals/use-site-vertical-query-by-id.ts
  client/data/site-verticals/use-site-verticals-query.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/form.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/index.tsx
  packages/data-stores/src/site/actions.ts
  packages/data-stores/src/site/reducer.ts
  packages/data-stores/src/site/selectors.ts
  packages/data-stores/src/site/types.ts
Labels: [Status] Needs Review

#62790 Checkout: Do not update cart contact details on auto-refresh, take 2
  client/my-sites/checkout/composite-checkout/hooks/use-cached-domain-contact-details.ts
Labels: [Type] Bug, [Status] Needs Review, Checkout
