Repository Automattic/wp-calypso, pull requests merged in 2022-09, with the labels that each got.

#67146 Import: adjust the gap between the columns of the import layout
  client/blocks/import/style/base.scss
Labels: [Status] Needs Review

#66909 Lint: use @wordpress/stylelint-config preset
  .stylelintrc
  .yarnrc.yml
  package.json
  yarn.lock
Labels: [Status] Needs Review, [Type] Tooling

#67204 Pricing page rework: Update cards to display existing subscriptions
  client/my-sites/plans/jetpack-plans/product-card/product-button-label.ts
  client/my-sites/plans/jetpack-plans/product-store/bundles-list.tsx
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-store-item-info.ts
  client/my-sites/plans/jetpack-plans/product-store/item-price.tsx
  client/my-sites/plans/jetpack-plans/product-store/products-list.tsx
  client/my-sites/plans/jetpack-plans/product-store/simple-product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/style.scss
  client/my-sites/plans/jetpack-plans/product-store/types.ts
Labels: [Type] Enhancement, [Status] Needs Review

#67122 Remove Professional Email experiment code
  client/lib/plans/features-list.js
  client/my-sites/plan-features/index.jsx
  client/my-sites/plans-features-main/index.jsx
  client/my-sites/plans/main.jsx
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review

#67077 Design Picker: Enable standard-theme-v13n flag
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#67169 Plugin Management: Enable bulk actions in all possible cases in Jetpack Cloud
  client/my-sites/plugins/plugin-activate-toggle/style.scss
  client/my-sites/plugins/plugin-list-header/index.jsx
  client/my-sites/plugins/plugin-management-v2/plugin-row-formatter/index.tsx
  client/state/plugins/installed/actions.js
  client/state/plugins/installed/test/actions.js
Labels: [Status] Needs Review, Jetpack Cloud

#67217 Newsletter Accent Color: Display accent color input text in same color as other inputs
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/style.scss
Labels: [Status] Needs Review

#67200 Plugins Management: Disable actions per single item when bulk actions are active
  client/my-sites/plugins/plugin-management-v2/plugin-row-formatter/index.tsx
Labels: [Status] Needs Review, Jetpack Cloud, Quick Fix

#67162 My Home: fix adjusting height of Banners on receiving them in different order
  client/components/swipeable/index.js
  client/my-sites/customer-home/locations/primary/index.jsx
Labels: [Status] Needs Review, Components

#67186 SMP: Use `<PageViewTracker>` to record page views
  client/sites-dashboard/controller.tsx
Labels: [Status] Needs Review, Analytics, Reviewer Can Merge, Sites Management Page i2

#67235 Remove `launch-wpcom-ssh` feature flag
  client/my-sites/hosting/sftp-card/index.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Type] Task, Launch WPCOM SSH

#67246 SMP: Test the logic that generates a site's initial used in the fallback site icon
  client/sites-dashboard/components/sites-site-item-thumbnail.tsx
  client/sites-dashboard/components/test/sites-site-item-thumbnail.tsx
Labels: [Status] Needs Review, [Type] Janitorial, Reviewer Can Merge, Sites Management Page i2

#67218 Close promote post widget "are you sure" dialog
  client/components/blazepress-widget/index.tsx
Labels: [Status] Needs Review

#67226 Increases the "promote posts" sidebar so that it stretches to fill th…
  client/components/blazepress-widget/index.tsx
  client/components/blazepress-widget/style.scss
Labels: [Status] Needs Review

#67206 Issue 592: make wide layout for promoted posts page
  client/my-sites/promote-post/main.tsx
Labels: [Status] Needs Review

#67135 Login: accept redirect_to from QR login
  client/blocks/qr-code-login/index.jsx
Labels: [Status] Needs Review, Signup, Stepper

#67259 Fix issue when handling the onClose function in BlazePress
  client/components/blazepress-widget/index.tsx
Labels: [Status] Needs Review

#66888 Checkout: Update the Marketplace agreement border color to the error color (red) instead of blue
  client/my-sites/checkout/composite-checkout/components/third-party-plugins-developer-account.tsx
Labels: [Status] Needs Review

#67176 Add VideoPress flow to "tailored signup" flow to skip plugins upsell
  client/my-sites/checkout/get-thank-you-page-url/index.ts
  client/my-sites/checkout/get-thank-you-page-url/test/get-thank-you-page-url.ts
  packages/onboarding/src/utils.ts
Labels: [Status] Needs Review

#66907 SiteIconPicker: add dropzone
  client/components/site-icon-with-picker/index.tsx
  client/components/site-icon-with-picker/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/style.scss
Labels: [Status] Needs Review, Signup

#67013 [Jetpack App Migration] Update App Banner Branding
  client/blocks/app-banner/index.jsx
  client/blocks/app-banner/style.scss
  client/blocks/app-banner/utils.js
  package.json
  static/animations/app-promo/jp-notifications-rtl.json
  static/animations/app-promo/jp-notifications.json
  static/animations/app-promo/jp-reader-rtl.json
  static/animations/app-promo/jp-reader.json
  static/animations/app-promo/jp-stats-rtl.json
  static/animations/app-promo/jp-stats.json
  static/animations/app-promo/wp-to-jp-rtl.json
  static/animations/app-promo/wp-to-jp.json
  test/client/jest.config.js
  yarn.lock
Labels: [Status] Needs Review

#67268 Update launchpad dependency validation logic
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
Labels: [Status] Needs Review

#67053 Features: Add signup flow related features for Newsletter and Link in Bio
  client/lib/plans/features-list.js
  client/my-sites/plan-features-comparison/index.jsx
  client/my-sites/plan-features-comparison/util.ts
  client/my-sites/plan-features/index.jsx
  client/my-sites/plan-features/style.scss
  client/signup/steps/plans/index.jsx
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/types.ts
Labels: [Status] In Progress, [Status] Needs Review, Signup, [Status] String Freeze

#67267 Jetpack New pricing page - fix the header text in WPcom
  client/my-sites/plans/jetpack-plans/plans-header.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#67179 Checkout: Convert UpsellNudge to TypeScript
  client/my-sites/checkout/controller.jsx
  client/my-sites/checkout/upsell-nudge/index.tsx
  client/my-sites/domains/domain-management/settings/settings-header.tsx
  client/state/sites/plans/selectors/get-plan-discounted-raw-price.js
  client/state/sites/plans/selectors/get-site-plan-raw-price.js
  packages/components/src/index.ts
Labels: [Status] Needs Review

#67273 stepper: processing step: log errors to console
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/index.tsx
Labels: [Status] Needs Review

#67265 Pricing page rework: Add features list for Security and Complete bundles
  .stylelintrc
  client/assets/images/jetpack/jetpack-green-checkmark.svg
  client/assets/images/jetpack/jetpack-icon-growth.svg
  client/assets/images/jetpack/jetpack-icon-lock.svg
  client/assets/images/jetpack/jetpack-icon-performance.svg
  client/assets/images/jetpack/jetpack-red-cross.svg
  client/my-sites/plans/jetpack-plans/product-store/bundles-list.tsx
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/features-list.tsx
  client/my-sites/plans/jetpack-plans/product-store/features.tsx
  client/my-sites/plans/jetpack-plans/product-store/hero-image/style.scss
  client/my-sites/plans/jetpack-plans/product-store/simple-product-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/style.scss
  client/my-sites/plans/jetpack-plans/product-store/types.ts
Labels: [Type] Enhancement, [Status] Needs Review

#67190 Launchpad: Add site launch functionality to link in bio flow
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/checklist-item.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/checklist.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/types.ts
  client/landing/stepper/declarative-flow/link-in-bio.ts
Labels: [Status] Needs Review, LaunchPad v1

#67231 Jetpack De-Fusion: Slideshow shortcode
  client/components/embed-container/index.jsx
  client/components/gallery-shortcode/index.tsx
Labels: Jetpack, [Status] Needs Review

#67241 plugin-bundle-flow: Add GetCurrentThemeSoftwareSets step
  client/landing/stepper/declarative-flow/internals/steps-repository/get-current-theme-software-sets/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
  client/landing/stepper/declarative-flow/plugin-bundle-flow.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
Labels: [Status] Needs Review

#67277 Update progress bar consistency with updated tasks
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/checklist.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
Labels: [Status] Needs Review

#67284 Jetpack: Redirect jetpack-videopress connections back to wp-admin
  client/jetpack-connect/authorize.js
Labels: Jetpack, [Status] Needs Review, NUX

#67264 HelpCenter: fix hidden header tooltips (1 Min Review)
  packages/help-center/src/styles.scss
Labels: [Status] Needs Review, Help Center

#66167 Docs: Allow `git rebase trunk` or `git merge trunk` in Git workflow
  docs/git-workflow.md
Labels: Documentation, [Status] Needs Review

#67136 Checkout: Update EBANX terms 'BUY' text to be more accurate
  client/my-sites/checkout/composite-checkout/components/ebanx-terms-of-service.tsx
Labels: [Status] Needs Review

#67019 Sites Management Page: Create hook to allow scrolling to top of window or an element
  client/sites-dashboard/components/sites-dashboard.tsx
  packages/components/src/index.ts
  packages/components/src/scroll-to-top/use-scroll-to-top.ts
  packages/components/src/site-thumbnail/style.scss
  packages/help-center/src/components/back-to-top-button.tsx
Labels: [Status] Needs Review, Sites Management Page i2

#66468 Add/test site credentials
  client/components/advanced-credentials/index.tsx
Labels: [Status] Needs Review

#67288 Launchpad: Use query params for my home redirect
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
  client/my-sites/customer-home/controller.jsx
Labels: [Status] Needs Review, LaunchPad v1

#67251 Remove padding when viewing pricing page in wide view.
  client/my-sites/plans/jetpack-plans/style.scss
Labels: [Type] Enhancement, Jetpack, [Status] Ready to Merge, Jetpack Cloud

#67301 Revert "Features: Add signup flow related features for Newsletter and Link in Bio"
  client/lib/plans/features-list.js
  client/my-sites/plan-features-comparison/index.jsx
  client/my-sites/plan-features-comparison/util.ts
  client/my-sites/plan-features/index.jsx
  client/my-sites/plan-features/style.scss
  client/signup/steps/plans/index.jsx
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/types.ts
Labels: [Status] Needs Review

#67203 Add description for Most Popular products/bundles to calypso-products
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/slug-to-selector-product.ts
  client/my-sites/plans/jetpack-plans/types.ts
  packages/calypso-products/src/get-jetpack-product-featured-text.tsx
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/product-values.ts
  packages/calypso-products/src/translations.tsx
  packages/calypso-products/src/types.ts
Labels: [Type] Enhancement, [Status] Ready to Merge, Jetpack Cloud

#66559 DIFM: Manage Purchases: Show extra page price breakdown using price tiers
  client/lib/purchases/assembler.ts
  client/lib/purchases/index.ts
  client/lib/purchases/types.ts
  client/lib/signup/step-actions/index.js
  client/me/purchases/manage-purchase/index.jsx
  client/me/purchases/manage-purchase/purchase-meta.jsx
Labels: [Status] Needs Review, DIFM Lite

#67160 Add subscriber package integration with the Users section
  client/landing/stepper/declarative-flow/internals/steps-repository/subscribers/index.tsx
  client/my-sites/people/controller.js
  client/my-sites/people/edit-team-member-form/edit-user-form.jsx
  client/my-sites/people/followers-list/followers.jsx
  client/my-sites/people/index.js
  client/my-sites/people/invite-button.jsx
  client/my-sites/people/invite-people/index.jsx
  client/my-sites/people/people-add-subscribers/index.jsx
  client/my-sites/people/people-list-section-header/index.jsx
  client/my-sites/people/people-section-nav/index.jsx
  client/my-sites/people/role-select/index.jsx
  config/development.json
  config/wpcalypso.json
  packages/onboarding/src/step-container/style.scss
  packages/subscriber/src/components/add-form/index.tsx
Labels: [Status] Needs Review, Subscriber Importer

#67309 Revert tab name
  client/my-sites/people/people-section-nav/index.jsx
Labels: [Status] Needs Review, Subscriber Importer

#67244 Theme/Plugin Bundling: Added UI changes for bundled themes
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/theme-info-popup.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/upgrade-modal.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/upgrade-modal.tsx
  client/landing/stepper/hooks/use-theme-details.ts
Labels: Themes, [Status] Needs Review

#67196 Fix text headers font size and spacing for both Desktop and Mobile view.
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/products-list.tsx
  client/my-sites/plans/jetpack-plans/product-store/style.scss
  client/my-sites/plans/jetpack-plans/product-store/types.ts
  client/my-sites/plans/jetpack-plans/selector.tsx
Labels: [Type] Enhancement, Jetpack, [Status] Needs Review, Jetpack Cloud

#67304 Jetpack Cloud: Apply Jetpack cloud base styles when user is logged out
  client/layout/logged-out.jsx
Labels: [Status] Needs Review

#67312 Add button type to prevent default submit
  client/blocks/image-editor/image-editor-toolbar.jsx
Labels: [Status] Needs Review, Signup, Stepper

#67308 Change background color to white
  client/landing/stepper/declarative-flow/internals/steps-repository/completing-purchase/style.scss
  client/signup/tailored-flow-processing-screen/style.scss
Labels: [Status] Needs Review, Signup, Stepper

#67305 Take 2: Add signup flow related features for Newsletter and Link in Bio
  client/lib/plans/features-list.js
  client/my-sites/plan-features-comparison/index.jsx
  client/my-sites/plan-features-comparison/util.ts
  client/my-sites/plan-features/index.jsx
  client/my-sites/plan-features/style.scss
  client/signup/steps/plans/index.jsx
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/types.ts
Labels: [Status] Needs Review

#67281 Site Switcher: Add Tracks event for click on site item
  client/components/site-selector/index.jsx
Labels: [Status] Needs Review, Reviewer Can Merge, Site Switcher i1

#66691 Domain-only sites: Add missing fallback items to the sidebar
  client/my-sites/sidebar/static-data/domain-only-fallback-menu.ts
  client/my-sites/sidebar/use-site-menu-items.js
Labels: Menus, [Status] Needs Review

#67315 Link-in-bio / Newsletter flow: Show info popover in logged in /plans page
  client/my-sites/plan-features-comparison/util.ts
  client/my-sites/plan-features/index.jsx
Labels: [Status] Needs Review

#67313 Fix popular plan for link in bio in mobile
  client/my-sites/plans-features-main/index.jsx
Labels: [Status] Needs Review

#67310 Make each tab a dedicated route
  client/my-sites/promote-post/components/promoted-post-filter/index.tsx
  client/my-sites/promote-post/controller.js
  client/my-sites/promote-post/index.js
  client/my-sites/promote-post/main.tsx
  client/sections.js
Labels: [Status] Needs Review

#67094 3 mins review: LiB pattern picker: use MShots for better perf
  packages/pattern-picker/src/item.tsx
  packages/pattern-picker/src/styles.scss
Labels: [Status] Needs Review, Signup

#67243 Launchpad: Improve placement/styles of Launchpad admin link
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
Labels: [Status] In Progress, [Status] Needs Review

#67211 Checkout: add flow related features for newsletter and link in bio
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx
  client/my-sites/checkout/composite-checkout/lib/get-flow-plan-features.ts
Labels: [Status] Needs Review, Signup, Checkout

#67216 Remove special chars for domain validation
  client/components/domains/register-domain-step/index.jsx
  client/lib/domains/get-fixed-domain-search.js
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review, Signup, Stepper

#67237 Bundled Plugins: Add redirect to bundle plugin flow from the themes/thanks-modal
  client/my-sites/themes/thanks-modal.jsx
Labels: [Status] Needs Review

#67280 remove feature flags for launchpad
  client/landing/stepper/declarative-flow/link-in-bio.ts
  client/landing/stepper/declarative-flow/newsletter.ts
  client/landing/stepper/declarative-flow/podcasts.ts
  client/my-sites/customer-home/controller.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
Labels: [Status] Needs Review

#67317 Pricing page rework: Fix styles on WPCOM Plans page
  client/my-sites/plans/jetpack-plans/product-store/features.tsx
  client/my-sites/plans/jetpack-plans/product-store/hero-image/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/wpcom-styles.scss
  client/my-sites/plans/jetpack-plans/style.scss
Labels: [Type] Bug, [Status] Needs Review

#67337 Site Thumbnail: Don't render blur background when `img` is ready
  packages/components/src/site-thumbnail/index.tsx
  packages/components/src/site-thumbnail/test/site-thumbnail.test.jsx
  packages/components/src/site-thumbnail/use-mshots-img.tsx
Labels: [Type] Bug, [Status] Needs Review, Sites Management Page i2

#67329 Theme/Plugin Bundling: Check for eligibility before entering the plugin-bundle flow
  client/landing/stepper/declarative-flow/internals/steps-repository/get-current-theme-software-sets/index.tsx
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  client/landing/stepper/hooks/use-is-plugin-bundle-eligible.ts
Labels: Themes, [Status] Needs Review, Plugins, Stepper

#67345 Hide the "Create your website" banner from the site preview
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/launchpad-site-preview.tsx
Labels: [Status] Needs Review, LaunchPad

#67024 Rework Quick Start flow to avoid use of SitePicker
  client/me/concierge/constants.js
  client/me/purchases/concierge-banner/index.jsx
  client/me/purchases/concierge-banner/style.scss
  client/me/purchases/purchases-list/index.jsx
  client/me/purchases/purchases-list/purchase-list-concierge-banner.tsx
  client/me/purchases/purchases-list/test/purchase-list-concierge-banner.tsx
  client/my-sites/purchases/main.tsx
  client/state/concierge/available-sessions/reducer.js
  client/state/concierge/reducer.js
  client/state/data-layer/wpcom/concierge/initial/from-api.js
  client/state/data-layer/wpcom/concierge/initial/schema.json
  client/state/data-layer/wpcom/concierge/schedules/appointments/detail/from-api.js
  client/state/selectors/get-available-concierge-sessions.ts
Labels: [Status] Needs Review

#67248 DIFM: Update copy on onboarding landing page
  client/landing/stepper/declarative-flow/internals/steps-repository/difm-starting-point/index.tsx
  client/my-sites/marketing/do-it-for-me/difm-landing.tsx
Labels: [Status] Needs Review, DIFM Lite

#67302 DIFM: Fix new site link on site picker page
  client/signup/config/steps-pure.js
  client/signup/steps/difm-site-picker/index.tsx
  client/signup/steps/difm-site-picker/site-delete-confirmation-dialog.tsx
  client/signup/steps/difm-site-picker/styles.scss
Labels: [Status] Needs Review, DIFM Lite

#67299 Revert plan page quick improvements copy test
  client/lib/plans/features-list.js
  client/my-sites/plan-features-comparison/index.jsx
  client/my-sites/plan-features-comparison/item.jsx
  client/my-sites/plan-features-comparison/style.scss
  client/my-sites/plan-features/index.jsx
  client/my-sites/plan-features/style.scss
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review

#67319 Split Product store styling into separate component styling.
  client/my-sites/plans/jetpack-plans/product-store/bundle-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/bundle-list/style.scss
  client/my-sites/plans/jetpack-plans/product-store/features-list/features.tsx
  client/my-sites/plans/jetpack-plans/product-store/features-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/features-list/style.scss
  client/my-sites/plans/jetpack-plans/product-store/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/item-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/item-list/style.scss
  client/my-sites/plans/jetpack-plans/product-store/item-price/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/item-price/style.scss
  client/my-sites/plans/jetpack-plans/product-store/jetpack-free/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/jetpack-free/style.scss
  client/my-sites/plans/jetpack-plans/product-store/most-popular/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/most-popular/style.scss
  client/my-sites/plans/jetpack-plans/product-store/need-more-info/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/need-more-info/style.scss
  client/my-sites/plans/jetpack-plans/product-store/pricing-banner/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/pricing-banner/style.scss
  client/my-sites/plans/jetpack-plans/product-store/product-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/product-list/style.scss
  client/my-sites/plans/jetpack-plans/product-store/recommendations/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/recommendations/style.scss
  client/my-sites/plans/jetpack-plans/product-store/see-all-features/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/see-all-features/style.scss
  client/my-sites/plans/jetpack-plans/product-store/style.scss
  client/my-sites/plans/jetpack-plans/product-store/view-filter/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/view-filter/style.scss
Labels: [Type] Enhancement, Jetpack, [Status] Needs Review, Jetpack Cloud

#66528 i18n: Localize partial routes for logged-out users
  client/lib/i18n-utils/localize-path.js
  client/lib/i18n-utils/test/localize-path.js
  packages/i18n-utils/src/index.ts
  packages/i18n-utils/src/localize-url.tsx
Labels: [Status] Needs Review, i18n, [Status] Needs i18n Review

#67247 Import: Skip plans page in JPC flow if user comes from migration flow
  client/blocks/importer/wordpress/index.tsx
  client/jetpack-connect/authorize.js
  client/jetpack-connect/connection-notice-types.js
  client/jetpack-connect/jetpack-connect-notices.jsx
  client/jetpack-connect/jetpack-connection.jsx
  client/jetpack-connect/persistence-utils.js
Labels: [Status] Needs Review, WordPress Migrator

#67269 Update/subscriber package
  client/my-sites/people/followers-list/followers.jsx
  client/my-sites/people/people-add-subscribers/index.jsx
  packages/subscriber/src/components/add-form/index.tsx
  packages/subscriber/src/hooks/use-active-job-recognition.ts
  packages/subscriber/src/hooks/use-in-progress-state.ts
Labels: [Status] Needs Review, Subscriber Importer

#67364 Fix misalignment of item price component in the new pricing page when viewed in mobile.
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/item-price/style.scss
Labels: [Type] Enhancement, Jetpack, [Status] Needs Review, Jetpack Cloud

#67221 Add Product Lightbox styling
  client/components/forms/multi-checkbox/index.tsx
  client/my-sites/plans/jetpack-plans/product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/icons/check.svg
  client/my-sites/plans/jetpack-plans/product-lightbox/icons/icons.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/icons/tags.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/index.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/style.scss
Labels: Jetpack, [Status] Needs Review, [Status] Needs Design Review, [Status] Design Input Requested

#67363 Update Premium Themes copy
  client/lib/plans/features-list.js
Labels: [Status] Needs Review

#67225 Signup: When creating a new user, also attribute variationName of query params
  client/lib/signup/step-actions/index.js
Labels: [Status] Needs Review

#67157 Email comparison view: Add the ability to present regional discounts
  client/my-sites/email/email-providers-comparison/price-with-interval/index.tsx
  client/my-sites/email/email-providers-comparison/price/google-workspace.tsx
  client/my-sites/email/email-providers-comparison/price/price-information.tsx
  client/my-sites/email/email-providers-comparison/price/professional-email.tsx
  client/my-sites/email/email-providers-comparison/price/style.scss
  client/my-sites/email/email-providers-comparison/price/use-get-domain-introductory-offer-eligibilities.ts
Labels: [Status] Needs Review

#67151 Condensed Features Experiment
  client/lib/plans/features-list.js
  client/my-sites/plan-features-comparison/index.jsx
  client/my-sites/plan-features-comparison/style.scss
  client/my-sites/plans-features-main/index.jsx
  client/signup/steps/plans/index.jsx
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/types.ts
Labels: [Status] Needs Review

#67128 Add Payments Features Video Course
  client/components/videos-ui/style.scss
  client/components/videos-ui/video-modal.jsx
  client/data/courses/constants.ts
  client/my-sites/customer-home/cards/education/blogging-quick-start/index.jsx
  client/my-sites/customer-home/cards/education/blogging-quick-start/style.scss
  client/my-sites/customer-home/cards/education/earn/index.jsx
Labels: [Status] Needs Review, Earn

#67361 Promoted posts: Update url to include siteId
  client/data/promote-post/use-promote-post-campaigns-query.ts
  client/my-sites/promote-post/components/campaign-item/index.tsx
  client/my-sites/promote-post/components/campaign-item/style.scss
Labels: [Status] Needs Review, WordAds

#67066 Style selection in design picker: Implement style variation in the full-screen theme preview
  .yarnrc.yml
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/package.json
  packages/data-stores/src/index.ts
  packages/data-stores/src/starter-designs-queries/use-starter-design-by-slug.ts
  packages/data-stores/src/starter-designs-queries/use-starter-designs-query.ts
  packages/design-picker/src/components/style-variation-badges/badge.tsx
  packages/design-picker/src/components/style-variation-badges/index.tsx
  packages/design-picker/src/components/style-variation-badges/style.scss
  packages/design-picker/src/components/style-variation-badges/utils.ts
  packages/design-picker/src/components/theme-style-variation-badges/index.ts
  packages/design-picker/src/components/theme-style-variation-badges/theme-style-variation-badge.tsx
  packages/design-picker/src/components/theme-style-variation-badges/theme-style-variation-badges.tsx
  packages/design-picker/src/components/unified-design-picker.tsx
  packages/design-picker/src/index.ts
  packages/design-picker/src/types.ts
  packages/design-preview/.eslintrc.js
  packages/design-preview/jest.config.js
  packages/design-preview/package.json
  packages/design-preview/src/components/index.tsx
  packages/design-preview/src/components/sidebar.tsx
  packages/design-preview/src/components/style-variation.tsx
  packages/design-preview/src/components/style.scss
  packages/design-preview/src/index.ts
  packages/design-preview/src/wp-edit-site-types.d.ts
  packages/design-preview/tsconfig-cjs.json
  packages/design-preview/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review, PT Style selection in onboarding

#67411 Promoted Posts: Set correct widget js src in prod
  config/_shared.json
  config/production.json
Labels: [Status] Needs Review

#67255 LiB flow: set the site title, tagline and logo url for every patterns
  client/landing/stepper/declarative-flow/internals/steps-repository/patterns/index.tsx
  client/landing/stepper/hooks/use-setup-onboarding-site.ts
  packages/data-stores/src/index.ts
  packages/data-stores/src/onboard/actions.ts
  packages/data-stores/src/onboard/index.ts
  packages/data-stores/src/onboard/reducer.ts
  packages/data-stores/src/onboard/selectors.ts
  packages/data-stores/src/queries/use-site-logo-mutation.ts
  packages/pattern-picker/package.json
  packages/pattern-picker/src/constants.ts
  packages/pattern-picker/src/index.tsx
  packages/pattern-picker/src/item.tsx
  packages/pattern-picker/src/patterns.ts
  packages/pattern-picker/src/types.tsx
  packages/pattern-picker/src/use-query-patterns.ts
  yarn.lock
Labels: [Status] Needs Review

#67384 Pricing page rework: Fix WPCOM styles
  client/my-sites/plans/jetpack-plans/product-store/simple-product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/simple-product-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/style.scss
  client/my-sites/plans/jetpack-plans/product-store/wpcom-styles.scss
Labels: [Type] Bug, [Status] Needs Review

#67409 Pricing page rework: Show "Jetpack successfully installed" only after connection.
  client/components/jetpack/licensing-prompt-dialog/index.tsx
  client/my-sites/plans/jetpack-plans/controller.tsx
  client/my-sites/plans/jetpack-plans/product-store/user-licenses-dialog.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#67306 Style selection: Site preview
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  packages/design-picker/src/components/theme-preview/icons.tsx
  packages/design-picker/src/components/theme-preview/index.tsx
  packages/design-picker/src/components/theme-preview/style.scss
  packages/design-picker/src/components/theme-preview/toolbar.tsx
  packages/design-picker/src/components/unified-design-picker.tsx
  packages/design-picker/src/constants.ts
  packages/design-picker/src/index.ts
  packages/design-picker/src/types.ts
  packages/design-preview/package.json
  packages/design-preview/src/components/index.tsx
  packages/design-preview/src/components/sidebar.tsx
  packages/design-preview/src/components/site-preview.tsx
  packages/design-preview/src/components/style-variation.tsx
  packages/design-preview/src/components/style.scss
  yarn.lock
Labels: [Status] Needs Review, PT Style selection in onboarding

#67343 Jetpack New Pricing page - Disable manage subscription button for user who isn't a plan purchaser
  client/lib/purchases/types.ts
  client/me/purchases/purchase-item/index.jsx
  client/me/purchases/purchase-item/owner-info.tsx
  client/my-sites/plans/current-plan/purchases-listing.jsx
  client/my-sites/plans/jetpack-plans/plan-upgrade/test/index.tsx
  client/my-sites/plans/jetpack-plans/product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/bundle-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-store-item-info.ts
  client/my-sites/plans/jetpack-plans/product-store/product-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/simple-product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/style.scss
  client/my-sites/plans/jetpack-plans/product-store/types.ts
  client/state/purchases/selectors/get-user-owns-purchase.ts
  client/state/purchases/utils/index.ts
  client/state/purchases/utils/is-user-purchase-owner.ts
  client/state/purchases/utils/use-is-user-purchase-owner.ts
Labels: [Type] Enhancement, [Status] Needs Review, Jetpack Cloud

#67324 Jetpack new pricing page - fix typo for featured text
  packages/calypso-products/src/translations.tsx
Labels: [Type] Enhancement, [Status] Needs Review, Jetpack Cloud

#66344 Enable Server Side rendering for logged-out Plugins section
  client/boot/common.js
  client/controller/ssr-setup-locale.js
  client/data/marketplace/use-es-query.ts
  client/data/marketplace/use-wpcom-plugins-query.ts
  client/data/marketplace/use-wporg-plugin-query.ts
  client/document/index.jsx
  client/lib/plugins/sanitize-section-content.js
  client/lib/plugins/server-dom-parser.js
  client/lib/plugins/test/server-dom-parser.js
  client/lib/plugins/utils.js
  client/my-sites/plugins/categories/use-categories.tsx
  client/my-sites/plugins/controller-logged-out.js
  client/my-sites/plugins/controller.js
  client/my-sites/plugins/index.node.js
  client/my-sites/plugins/plugin-details-CTA/index.jsx
  client/my-sites/plugins/plugin-details.jsx
  client/my-sites/plugins/plugins-navigation-header/index.jsx
  client/my-sites/plugins/test/logged-out.jsx
  client/my-sites/plugins/utils.js
  client/server/pages/index.js
  client/server/render/index.js
  client/state/initial-state.js
  client/state/query-client.ts
  client/webpack.config.node.js
  package.json
  packages/calypso-e2e/src/lib/pages/plugins-page.ts
  packages/i18n-utils/src/locale-context.tsx
  packages/search/src/search.tsx
  yarn.lock
Labels: [Status] Needs Review, Server Side Rendering, Plugins

#67398 IntroStep: increase intro button padding
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/styles.scss
Labels: [Status] Needs Review, Signup, Stepper

#67381 Newsletter Accent Color: Fix displaying of validity check for the color input
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/style.scss
Labels: [Status] Needs Review

#67418 Fix: Logged-out Plugins CTA doesn't redirect to /pricing
  client/my-sites/plugins/plugin-details-CTA/index.jsx
Labels: [Status] Needs Review

#67383 Change page title to "advertising" to match the page URL
  client/components/blazepress-widget/index.tsx
  client/my-sites/promote-post/components/campaign-item/index.tsx
  client/my-sites/promote-post/components/post-item/index.tsx
  client/my-sites/promote-post/components/post-item/style.scss
  client/my-sites/promote-post/components/posts-list/index.tsx
  client/my-sites/promote-post/main.tsx
  client/my-sites/promote-post/style.scss
Labels: [Status] Needs Review

#67395 DomainPicker: enable newsletter vendor for newsletter flow
  packages/domain-picker/src/utils/index.ts
Labels: [Status] Needs Review, Signup, Domains

#67374 `PluginsBrowser`: refactor tests to `@testing-library/react`
  client/my-sites/plugins/plugins-browser/test/index.jsx
Labels: Framework, [Status] Needs Review, Testing

#67376 `PluginsBrowserList`: refactor tests to `@testing-library/react`
  client/my-sites/plugins/plugins-browser-list/test/index.jsx
Labels: Framework, [Status] Needs Review, Testing

#67389 Integrate lightbox component to feature and simple card
  client/components/jetpack/card/jetpack-product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/bundle-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-bundles-to-display.ts
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-item-lightbox.ts
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-products-to-display.ts
  client/my-sites/plans/jetpack-plans/product-store/item-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/product-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/simple-product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/types.ts
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
Labels: [Type] Enhancement, Jetpack, [Status] Needs Review, Jetpack Cloud

#67419 Devdocs: remove test for `devdocs/design/component-playground`
  client/devdocs/design/test/component-playground.js
Labels: Framework, [Status] Needs Review, Testing

#67390 Plugin Management: implement action status for plugin management actions
  client/my-sites/plugins/plugin-management-v2/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-action-status/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-action-status/render-status-message.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-action-status/style.scss
  client/my-sites/plugins/plugin-management-v2/plugin-common/plugin-common-list/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-common/plugin-common-list/style.scss
  client/my-sites/plugins/plugin-management-v2/plugin-common/plugin-common-table/style.scss
  client/my-sites/plugins/plugin-management-v2/plugin-row-formatter/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-row-formatter/style.scss
  client/my-sites/plugins/plugin-management-v2/types.ts
  client/my-sites/plugins/plugin-management-v2/utils/get-plugin-action-status-messages.ts
  client/my-sites/plugins/plugins-list/index.jsx
  client/state/action-types.ts
  client/state/plugins/installed/status/actions.js
  client/state/plugins/installed/status/reducer.js
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#67332 Plans Subheader: fix subheader for tailored flows to respect the 'hideFreePlan' value
  client/lib/signup/step-actions/index.js
  client/signup/steps/domains/index.jsx
  client/signup/steps/plans/index.jsx
Labels: [Status] Ready to Merge, Signup, Needs Multiple Reviews

#66407 Help Center: implement session continuity
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/help-center/src/config.js
  apps/editing-toolkit/editing-toolkit-plugin/help-center/src/help-center.js
  apps/happychat/src/happychat.jsx
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
  client/components/happychat/button.jsx
  client/gutenberg/editor/calypsoify-iframe.tsx
  client/layout/index.jsx
  client/layout/masterbar/checkout.tsx
  client/layout/masterbar/masterbar-help-center.jsx
  client/my-sites/checkout/composite-checkout/components/checkout-help-link.tsx
  client/state/ui/actions/index.js
  client/state/ui/help-center-visible/actions.js
  client/state/ui/help-center-visible/reducer.js
  client/state/ui/reducer.js
  client/state/ui/selectors/help-center-is-visible.js
  config/development.json
  packages/data-stores/src/help-center/index.ts
  packages/data-stores/src/help-center/persist.ts
  packages/data-stores/src/help-center/reducer.ts
  packages/data-stores/src/help-center/selectors.ts
  packages/happychat-connection/src/connection.ts
  packages/happychat-connection/src/types.ts
  packages/happychat-connection/src/use-happychat-auth.ts
  packages/happychat-connection/src/use-happychat-available.ts
  packages/happychat-connection/test/index.ts
  packages/help-center/src/components/help-center-contact-form.tsx
  packages/help-center/src/components/help-center-contact-page.tsx
  packages/help-center/src/components/help-center-container.tsx
  packages/help-center/src/components/help-center-embed-result.tsx
  packages/help-center/src/components/help-center-header.tsx
  packages/help-center/src/components/help-center-search-results.tsx
  packages/help-center/src/components/help-center-search.tsx
  packages/help-center/src/components/help-center.tsx
  packages/help-center/src/happychat-window-communicator.ts
  packages/help-center/src/hooks/use-should-render-chat-option.tsx
  packages/help-center/src/hooks/use-still-need-help-url.tsx
  packages/help-center/src/index.ts
  packages/help-center/src/query-client.ts
  packages/help-center/src/types.ts
  packages/help-center/src/utils.ts
Labels: [Status] Needs Review, DO NOT MERGE, Help Center

#67421 PatternPicker: adjust timeout
  packages/pattern-picker/src/index.tsx
Labels: [Status] Needs Review, Signup, Stepper

#67342 theme-showcase: thanks-modal: Only redirect to bundled software flow if eligible
  client/my-sites/themes/thanks-modal.jsx
Labels: [Status] Needs Review

#67444 Theme Sheet: Hide upsell banner for bundled premium themes
  client/my-sites/theme/main.jsx
Labels: [Status] Needs Review

#67347 theme-showcase: seller-upgrade: WooCommerce theme specific upsell
  client/components/theme/index.jsx
Labels: [Status] Needs Review

#67399 Tailored Flows: remove completingPurchase step and set up the site /start
  client/landing/stepper/declarative-flow/internals/steps-repository/completing-purchase/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/completing-purchase/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/subscribers/index.tsx
  client/landing/stepper/declarative-flow/link-in-bio.ts
  client/landing/stepper/declarative-flow/newsletter.ts
  client/landing/stepper/hooks/use-setup-onboarding-site.ts
  client/lib/signup/step-actions/index.js
  client/signup/config/flows-pure.js
  packages/onboarding/package.json
  packages/onboarding/src/index.ts
  packages/onboarding/src/mshots-image/index.tsx
  packages/onboarding/src/setup-tailored-site-after-creation.ts
  packages/onboarding/src/upload-and-set-site-logo.ts
  yarn.lock
Labels: [Status] Needs Review, Tailored Flows

#67397 Checkout: move sidebar email support message logic to getPlanFeatures
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx
  client/my-sites/checkout/composite-checkout/lib/get-plan-features.ts
Labels: [Status] Needs Review, Checkout

#67403 E2E: skip domain selection for Plans: Business flow.
  test/e2e/specs/plans/plans__signup-business.ts
Labels: [Status] Needs Review

#67412 Plugin Management: plugin details page enhancements
  client/jetpack-cloud/sections/plugin-management/plugins-overview/style.scss
  client/my-sites/plugins/plugin-management-v2/plugin-details-v2/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-details-v2/style.scss
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#67295 Site Switcher: Introduce "Manage Sites" button at the bottom
  client/components/search-sites/index.js
  client/components/site-selector/index.jsx
  client/components/site-selector/style.scss
  client/jetpack-cloud/style.scss
  client/layout/index.jsx
  client/my-sites/navigation/index.jsx
  client/my-sites/picker/picker.jsx
  client/my-sites/sidebar/static-data/all-sites-menu.js
Labels: [Status] Needs Review, Sidebar, Reviewer Can Merge, Site Switcher i1

#67407 E2E: add retry mechanism to the domain search and selection step.
  packages/calypso-e2e/src/lib/components/domain-search-component.ts
Labels: [Status] Needs Review

#67290 Update/videopress remove tube
  client/signup/steps/videopress-site/index.jsx
Labels: [Status] Needs Review

#67461 Extract selector: doesThemeBundleUsableSoftwareSet
  client/my-sites/themes/thanks-modal.jsx
  client/state/themes/selectors/does-theme-bundle-software-set.js
  client/state/themes/selectors/does-theme-bundle-usable-software-set.js
  client/state/themes/selectors/index.js
  client/state/themes/selectors/is-site-eligible-for-bundled-software.js
Labels: [Status] Needs Review

#67466 Theme Showcase: Detect when a WooCommerce theme is included in plan
  client/components/theme/index.jsx
Labels: [Status] Needs Review

#67341 Theme/Plugin Bundling: Fix padding on theme upgrade modal
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/upgrade-modal.scss
Labels: [Status] Needs Review, Theme Showcase

#67458 Launchpad: Fix chevron direction for RTL languages
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/checklist-item.tsx
Labels: [Status] Needs Review, LaunchPad

#67459 Site Switcher: Update 'Add new site' button styles
  client/components/site-selector/add-site.tsx
  client/components/site-selector/index.jsx
  client/components/site-selector/style.scss
  client/jetpack-cloud/style.scss
  packages/calypso-color-schemes/src/shared/color-schemes/_blue.scss
  packages/calypso-color-schemes/src/shared/color-schemes/_coffee.scss
  packages/calypso-color-schemes/src/shared/color-schemes/_modern.scss
Labels: [Status] Needs Review, Sidebar, Jetpack Cloud, Reviewer Can Merge, Site Switcher i1

#67296 v13n: Avoid sending empty vertical id
  config/horizon.json
  config/stage.json
  config/wpcalypso.json
  packages/data-stores/src/site/actions.ts
  packages/data-stores/src/site/test/actions.ts
  packages/data-stores/src/site/types.ts
  test/e2e/specs/onboarding/ftme__write.ts
  test/e2e/specs/onboarding/setup__build.ts
Labels: [Status] Needs Review

#67433 Pricing page rework: Display additional legacy product cards
  client/assets/images/jetpack/jetpack-product-icon-complete.svg
  client/assets/images/jetpack/jetpack-product-icon-security.svg
  client/my-sites/plans/jetpack-plans/product-store/bundle-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/bundle-list/style.scss
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-store-item-info.tsx
  client/my-sites/plans/jetpack-plans/product-store/product-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/simple-product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/utils/get-product-icon.ts
Labels: [Type] Enhancement, [Status] Needs Review

#67380 `PluginsList`: refactor tests to `@testing-library/react`
  client/my-sites/plugins/plugin-item/plugin-item.jsx
  client/my-sites/plugins/plugins-list/test/index.jsx
Labels: Framework, [Status] Needs Review, Testing

#66921 Adjustments to domain step in `onboarding-with-email` signup flow
  client/components/domains/reskin-side-explainer/index.jsx
  client/signup/config/flows-pure.js
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
  client/signup/steps/domains/index.jsx
  client/signup/steps/domains/style.scss
  client/signup/style.scss
Labels: [Status] Needs Review, [Status] String Freeze

#67435 Make product lightbox url accessible using hash fragment
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-item-lightbox.ts
  client/my-sites/plans/jetpack-plans/product-store/item-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/more-info-link/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/more-info-link/style.scss
  client/my-sites/plans/jetpack-plans/product-store/simple-product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/simple-product-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/types.ts
  client/my-sites/plans/jetpack-plans/product-store/utils/sanitize-location-hash.ts
Labels: [Type] Enhancement, Jetpack, [Status] Needs Review, Jetpack Cloud

#67482 TailoredFlows: update styles so that fields and buttons share the same border radius
  client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-setup/styles.scss
  packages/subscriber/src/components/add-form/style.scss
Labels: [Status] Needs Review, Signup

#67479 v13n: Turn on signup/standard-theme-v13n flag (second try)
  config/production.json
Labels: [Status] Needs Review

#67446 Newsletter Accent Color: Display warning when accent color with too low contrast ratio is selected
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/style.scss
  client/signup/icons/index.tsx
  packages/onboarding/src/utils/contrastChecker.ts
  packages/onboarding/src/utils/flows.ts
  packages/onboarding/src/utils/index.ts
Labels: [Status] Needs Review

#67046 Adjustments to email step in `onboarding-with-email` signup flow
  client/components/emails/email-product-price/index.jsx
  client/components/emails/email-product-price/style.scss
  client/components/emails/email-signup-titan-card/index.jsx
  client/components/emails/email-step-side-bar/style.scss
  client/my-sites/email/email-providers-comparison/price/price-information.tsx
  client/signup/config/flows-pure.js
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
  client/signup/steps/emails/index.jsx
  client/signup/steps/emails/style.scss
  client/signup/style.scss
  client/state/signup/progress/actions.js
Labels: [Status] Needs Review, [Status] String Freeze

#67485 Pricing page rework: Extract items list component logic for re-usability
  client/my-sites/plans/jetpack-plans/product-store/bundle-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/bundle-list/style.scss
  client/my-sites/plans/jetpack-plans/product-store/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/item-list/style.scss
  client/my-sites/plans/jetpack-plans/product-store/items-list/all-items.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/bundles-list.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/most-popular.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/products-list.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/style-most-popular.scss
  client/my-sites/plans/jetpack-plans/product-store/items-list/style.scss
  client/my-sites/plans/jetpack-plans/product-store/most-popular/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/product-list/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/types.ts
Labels: [Status] Needs Review, [Type] Task

#67465 Add bulk action warning notices
  client/my-sites/plugins/plugin-list-header/index.jsx
  client/my-sites/plugins/plugins-list/index.jsx
Labels: [Status] Needs Review

#67417 Update: multiple choice question component
  client/components/multiple-choice-question/README.md
  client/components/multiple-choice-question/index.jsx
  client/components/multiple-choice-question/test/__snapshots__/index.js.snap
  client/my-sites/plans/jetpack-plans/product-lightbox/index.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/style.scss
Labels: Jetpack, [Status] Needs Review, Components

#67457 Plugin Management: Design fixes and improvements
  client/my-sites/plugins/plugin-list-header/index.jsx
  client/my-sites/plugins/plugin-list-header/style.scss
  client/my-sites/plugins/plugin-management-v2/plugin-common/plugin-common-table/style.scss
  client/my-sites/plugins/plugin-management-v2/plugin-row-formatter/style.scss
Labels: [Status] Needs Review, Jetpack Cloud

#67489 Update ImportSubscribersResponse response
  packages/data-stores/src/subscriber/actions.ts
  packages/data-stores/src/subscriber/types.ts
Labels: [Status] Needs Review, Subscriber Importer

#67486 Remove jetpack logo for LiB
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-setup/index.tsx
  client/signup/tailored-flow-processing-screen/index.jsx
Labels: [Status] Needs Review, Signup, Stepper

#67432 Add url locale on stepper
  client/boot/locale.js
  client/landing/stepper/declarative-flow/link-in-bio.ts
  client/landing/stepper/declarative-flow/newsletter.ts
Labels: [Status] Needs Review, Signup, Stepper, Needs Multiple Reviews

#67495 Pricing page rework: Decouple card components from the product logic
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/items-list/all-items.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/most-popular.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/style-most-popular.scss
  client/my-sites/plans/jetpack-plans/product-store/items-list/style.scss
  client/my-sites/plans/jetpack-plans/product-store/more-info-link/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/simple-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/simple-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/simple-product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/types.ts
  client/my-sites/plans/jetpack-plans/product-store/wpcom-styles.scss
Labels: [Status] Needs Review, [Type] Task

#66254 Whats New: Working in Atomic
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/help-center/src/help-center.js
  apps/editing-toolkit/editing-toolkit-plugin/whats-new/class-whats-new.php
  apps/editing-toolkit/editing-toolkit-plugin/whats-new/class-wp-rest-wpcom-block-editor-whats-new-dot-controller.php
  apps/editing-toolkit/editing-toolkit-plugin/whats-new/class-wp-rest-wpcom-block-editor-whats-new-list-controller.php
  client/components/data/query-reader-post/index.jsx
  client/layout/masterbar/checkout.tsx
  client/state/reader/posts/actions.js
  packages/data-stores/src/queries/use-has-seen-whats-new-modal-query.ts
  packages/help-center/src/components/help-center-more-resources.tsx
  packages/help-center/src/components/help-center-search-results.tsx
  packages/help-center/src/hooks/use-help-search-query.ts
  packages/help-center/src/hooks/use-still-need-help-url.tsx
  packages/help-center/src/index.ts
  packages/help-center/src/utils.ts
  packages/whats-new/src/index.tsx
  packages/whats-new/src/whats-new-page.tsx
  packages/wpcom-proxy-request/src/index.js
  packages/wpcom-proxy-request/types/index.d.ts
Labels: [Status] Needs Review, Help Center

#67359 Plugin Management: Update button style and implement show plugin update status in Jetpack Cloud
  client/my-sites/plugins/plugin-management-v2/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-action-status/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-common/plugin-common-card/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-common/plugin-common-card/style.scss
  client/my-sites/plugins/plugin-management-v2/plugin-common/plugin-common-table/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-details-v2/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-details-v2/sites-with-installed-plugin-list.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-row-formatter/index.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-row-formatter/style.scss
  client/my-sites/plugins/plugin-management-v2/plugins-list/index.tsx
  client/my-sites/plugins/plugin-management-v2/sites-list/index.tsx
  client/my-sites/plugins/plugin-management-v2/types.ts
  client/my-sites/plugins/plugin-management-v2/update-plugin/index.tsx
  client/my-sites/plugins/plugin-management-v2/update-plugin/style.scss
  client/my-sites/plugins/plugin-management-v2/utils/get-plugin-action-status-messages.ts
  client/my-sites/plugins/plugin-management-v2/utils/get-plugin-action-statuses.ts
  client/my-sites/plugins/plugins-list/index.jsx
  client/state/plugins/installed/selectors.js
  client/state/plugins/installed/test/selectors.js
Labels: [Status] Needs Review, Jetpack Cloud

#67415 i18n: Make onboarding course details strings reactive
  client/components/videos-ui/index.jsx
  client/components/videos-ui/test/index.jsx
  client/data/courses/constants.ts
  client/data/courses/index.ts
  client/data/courses/use-course-details.ts
Labels: [Type] Bug, [Status] Needs Review, i18n, [Goal] Onboarding

#67422 i18n: Make infinite scroll options labels translatable
  client/my-sites/site-settings/theme-enhancements.jsx
Labels: [Status] Needs Review, [Status] String Freeze

#67220 Adjustments to plans step in `onboarding-with-email` signup flow
  client/my-sites/checkout/checkout-thank-you/index.jsx
  client/my-sites/email/titan-set-up-mailbox/index.tsx
  client/my-sites/email/titan-set-up-thank-you/index.tsx
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
  client/signup/reskinned-processing-screen/index.jsx
  client/signup/steps/plans/index.jsx
  client/signup/steps/plans/style.scss
  client/signup/style.scss
Labels: [Status] Needs Review, [Status] String Freeze

#67500 Hosting Configuration: Remove beta notice for SSH access
  client/my-sites/hosting/sftp-card/index.js
Labels: [Status] Needs Review, Reviewer Can Merge, Launch WPCOM SSH

#67275 Fill input with state data
  client/components/site-icon-with-picker/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/index.tsx
  packages/data-stores/src/onboard/actions.ts
  packages/data-stores/src/onboard/reducer.ts
  packages/onboarding/src/index.ts
  packages/onboarding/src/setup-tailored-site-after-creation.ts
Labels: [Status] Needs Review, [Status] Ready to Merge, Signup, Stepper

#67252 Fix step navigation using assign over replace
  client/landing/stepper/declarative-flow/link-in-bio.ts
  client/landing/stepper/declarative-flow/newsletter.ts
  client/landing/stepper/declarative-flow/plugin-bundle-flow.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
Labels: [Status] Needs Review, Signup, Stepper

#67470 Theme showcase: Restrict bundled themes on premium plans
  client/components/theme/index.jsx
  client/state/themes/selectors/is-premium-theme-available.js
Labels: [Status] Needs Review

#67427 Revert "Revert "Help Center: Adjust Happychat endpoint in help center according to env""
  apps/happychat/src/index.ejs
  packages/help-center/src/components/help-center-inline-chat.tsx
Labels: [Status] Needs Review

#67506 TailoredFlows: skip domain selection using the same code path as othe…
  client/lib/signup/step-actions/index.js
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review

#67503 Use pattern.html instead of pattern.content and fix the API version of icon setting endpoint
  client/landing/stepper/declarative-flow/internals/steps-repository/patterns/index.tsx
  packages/onboarding/src/upload-and-set-site-logo.ts
  packages/pattern-picker/src/index.tsx
  packages/pattern-picker/src/types.tsx
Labels: [Status] Needs Review, Tailored Flows

#67483 ProcessBar: update styles to match wordpress blue
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/style.scss
  client/signup/reskinned-processing-screen/style.scss
  packages/components/src/progress-bar/style.scss
Labels: [Status] Needs Review, Components

#67396 Jetpack Agency Dashboard: set container element's height to 100%
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/style.scss
  client/jetpack-cloud/sections/plugin-management/plugins-overview/style.scss
  client/my-sites/plugins/style.scss
Labels: [Status] Needs Review, Jetpack Cloud, [Size] XS

#67484 Plugin Management: enable plugin management on staging and to only agency users
  client/components/jetpack/sidebar/menu-items/jetpack-cloud.jsx
  client/jetpack-cloud/sections/plugin-management/controller.tsx
  config/jetpack-cloud-stage.json
  config/stage.json
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud
