Repository Automattic/wp-calypso, pull requests merged in 2023-11, with the labels that each got.

#83690 Jetpack E2E: update dashboard smoke test to use the active tab instead of looking for screen reader text.
  packages/calypso-e2e/src/lib/pages/wp-admin/jetpack-dashboard-page.ts
  test/e2e/specs/jetpack/jetpack__dashboard-smoke.ts
Labels: [Status] Needs Review

#83688 Authentication E2E: update Magic Link spec to normalize URL.
  packages/calypso-e2e/src/email-client.ts
  test/e2e/specs/authentication/authentication__magic-link.ts
Labels: [Pri] High, [Status] Needs Review

#83727 Domains: Update domain sidebar width to prevent word orphans
  client/components/domains/domain-product-price/style.scss
  client/components/domains/domain-suggestion/style.scss
  client/signup/steps/domains/style.scss
Labels: [Status] Needs Review

#83458 Processing Screen: Change copy for BBE flows
  client/signup/reskinned-processing-screen/index.jsx
Labels: [Status] Needs Review

#83364 Checkout: show pricing grid features
  client/my-sites/checkout/src/components/wp-checkout-order-summary.tsx
  client/my-sites/checkout/src/lib/get-plan-features.ts
Labels: [Status] Needs Review

#83702 Assembler: Fix the jetpack blocks might not be rendered
  packages/block-renderer/src/components/block-renderer-container.tsx
  packages/block-renderer/src/components/pattern-renderer.tsx
Labels: [Status] Needs Review

#83742 Assembler: Page preview UI improvements
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-page-preview-list.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-page-preview-list.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-page-preview.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-page-preview.tsx
Labels: [Status] Needs Review

#83739 Jetpack Manage: Fix the nesting li element in the submenu component.
  client/layout/sidebar-v2/navigator/navigator-menu.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#83460 Rename Launchpad to LaunchpadInternal, DefaultWiredLaunchpad to Launchpad
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/my-sites/customer-home/cards/launchpad/index.tsx
  client/my-sites/earn/launchpad/index.tsx
  packages/launchpad-navigator/src/floating-navigator/index.tsx
  packages/launchpad/README.md
  packages/launchpad/src/default-wired-launchpad.tsx
  packages/launchpad/src/index.ts
  packages/launchpad/src/launchpad-internal.tsx
  packages/launchpad/src/launchpad.tsx
  packages/launchpad/src/test/launchpad.tsx
Labels: [Status] Needs Review, [Feature] Launchpad

#83543 Jetpack Manage: Show some fields only on the sign up form - not on edit
  client/jetpack-cloud/sections/agency-signup/agency-signup-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/company-details-form/index.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#83722 wp-admin Site Default: delay left admin menu refresh and sync it with the notice
  client/my-sites/hosting/site-admin-interface-card/use-select-interface-mutation.ts
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting Configuration, wp-admin Site Default

#83757 FHT: Ensure start trial CTA is not hidden by the floating action buttons
  client/landing/stepper/declarative-flow/internals/steps-repository/trial-acknowledge/style.scss
Labels: [Status] Needs Review, Reviewer Can Merge, Free Hosting Trial

#83724 Plans 2023: Escape hatch to show all plans in tailored /plans mix (applies for Newsletter sites)
  client/my-sites/plans-features-main/index.tsx
  client/my-sites/plans-features-main/style.scss
Labels: [Status] Needs Review, [Status] Needs Design Review, [Status] Design Input Requested

#83762 Hosting config: Update recommended PHP version to 8.1
  client/my-sites/hosting/web-server-settings-card/index.js
Labels: [Status] Needs Review, Hosting Configuration

#83681 Plugin Details: Update layout breakpoints
  client/my-sites/marketplace/components/billing-interval-switcher/index.tsx
  client/my-sites/plugins/plugin-details-CTA/style.scss
  client/my-sites/plugins/plugin-details-header/style.scss
  client/my-sites/plugins/plugin-details-sidebar-usp/index.jsx
  client/my-sites/plugins/plugin-details.jsx
  client/my-sites/plugins/style.scss
Labels: Marketplace Plugins, Marketplace Plugin Details

#83760 Launchpad: Ensure data consistence in the Navigator Progress ring
  client/my-sites/customer-home/cards/launchpad/index.tsx
  packages/data-stores/src/index.ts
  packages/data-stores/src/queries/use-launchpad-navigator.ts
  packages/launchpad-navigator/src/icon/index.tsx
Labels: [Status] Needs Review, [Feature] Launchpad

#83443 Refactor: Remove plan-features legacy component and dependent dead atomic store dead code
  client/my-sites/checkout/src/lib/get-flow-plan-features.ts
  client/my-sites/plan-features/actions.jsx
  client/my-sites/plan-features/header.jsx
  client/my-sites/plan-features/index.jsx
  client/my-sites/plan-features/item.jsx
  client/my-sites/plan-features/placeholder.jsx
  client/my-sites/plan-features/plan-features-action-wrapper.jsx
  client/my-sites/plan-features/scroller.jsx
  client/my-sites/plan-features/style.scss
  client/my-sites/plan-features/test/__snapshots__/header.jsx.snap
  client/my-sites/plan-features/test/header.jsx
  client/my-sites/plan-features/test/index.jsx
  client/my-sites/plan-features/util.ts
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
  client/signup/steps/plans-atomic-store/index.jsx
  client/signup/steps/plans-atomic-store/style.scss
  client/signup/steps/plans-atomic-store/test/index.jsx
  client/signup/steps/plans/test/index.jsx
Labels: [Status] Needs Review

#83611 ActivityLog: prevent 'Copy site' button from wrapping text
  client/my-sites/activity/activity-log-v2/index.tsx
  client/my-sites/activity/activity-log-v2/style.scss
  client/my-sites/backup/main.jsx
  client/my-sites/backup/style.scss
Labels: [Status] Needs Review

#83550 Hosting Configuration: Improve adding SSH key language
  client/my-sites/hosting/sftp-card/ssh-keys.tsx
Labels: [Status] Needs Review, Hosting Configuration

#83778 Happy Blocks: Rename Store to Commerce on header
  apps/happy-blocks/block-library/universal-header/index.php
Labels: [Status] Needs Review

#83748 Assembler: Preselect the About page
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/constants.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-pattern-pages.ts
  config/development.json
Labels: [Status] Needs Review

#83776 Settings: Update "checklist site title tour" z-index to appear beneath Media modal
  client/layout/guided-tours/tours/checklist-site-title-tour/index.js
Labels: [Status] Needs Review

#83734 Stats Date Picker: Add outside click handler to close popover
  client/components/stats-date-control/stats-date-control-picker.tsx
Labels: Stats, [Status] Needs Review

#83738 CI: send detailed notification of failures for Pre-Release Tests.
  .teamcity/_self/projects/WebApp.kt
  .teamcity/settings.kts
  bin/teamcity-e2e-slack-notify.mjs
Labels: [Status] Needs Review

#83773 Invalid intent prematurely set when site intent is being loaded from the backend
  client/my-sites/plans-features-main/index.tsx
Labels: [Status] Needs Review

#83736 Assembler: Load rendered patterns by category
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-assembler-container.tsx
  packages/block-renderer/src/components/patterns-renderer-provider.tsx
  packages/block-renderer/src/hooks/use-rendered-patterns.ts
Labels: [Status] Needs Review

#83744 Assembler: Remove the checkbox on the activation screen
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-activation.tsx
Labels: [Status] Needs Review

#83743 Jetpack Manage: Fix issue with page refreshing when selecting a site from the site selector.
  client/jetpack-cloud/sections/landing/controller.tsx
  client/jetpack-cloud/sections/landing/main.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#83781 Stats: Fix data quantity for bar chart and partial date periods
  client/my-sites/stats/site.jsx
Labels: Stats, [Status] Needs Review

#83789 Assembler: Fix issue where the preselect page About cannot be deselected
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-pattern-pages.ts
Labels: [Status] Needs Review

#83794 Assembler: Fix the page patterns are not rendered
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-category-patterns-map.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-pattern-pages-map-by-category.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-patterns-map-by-category.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
Labels: [Status] Needs Review

#83766 Assembler: use the new `can_replace_content` param
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  packages/data-stores/src/site/actions.ts
  packages/data-stores/src/site/types.ts
Labels: [Status] Needs Review

#83695 Replace reader tag header with navigation header
  client/reader/stream/style.scss
  client/reader/tag-stream/header.jsx
  client/reader/tag-stream/main.jsx
  client/reader/tag-stream/style.scss
Labels: [Status] Needs Review

#83761 Signup: User step use email query arg
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/passwordless.jsx
  client/blocks/signup-form/signup-form-social-first.tsx
Labels: [Status] Needs Review

#83792 Update/reader search header
  client/reader/search-stream/index.jsx
  client/reader/search-stream/style.scss
Labels: [Status] Needs Review

#83764 Big Sky: Bail flow
  client/landing/stepper/declarative-flow/ai-assembler.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/ai-site-prompt/index.tsx
Labels: [Status] Needs Review

#83801 Nextdoor: Update the connections screen styling
  client/assets/images/connections/connections-nextdoor.png
  client/my-sites/marketing/connections/service-description.jsx
  client/my-sites/marketing/connections/service-examples.jsx
  client/my-sites/marketing/style.scss
Labels: [Status] Needs Review

#83746 Social previews | Add Nextdoor preview
  client/blocks/sharing-preview-pane/index.jsx
  client/components/share/nextdoor-share-preview/index.jsx
  client/components/vertical-menu/items/social-item.jsx
  packages/calypso-products/src/constants/features.ts
  packages/social-previews/CHANGELOG.md
  packages/social-previews/package.json
  packages/social-previews/src/helpers.tsx
  packages/social-previews/src/index.ts
  packages/social-previews/src/nextdoor-preview/constants.ts
  packages/social-previews/src/nextdoor-preview/footer-actions.tsx
  packages/social-previews/src/nextdoor-preview/icons/chevron-icon.tsx
  packages/social-previews/src/nextdoor-preview/icons/comment-icon.tsx
  packages/social-previews/src/nextdoor-preview/icons/default-avatar.tsx
  packages/social-previews/src/nextdoor-preview/icons/default-image.tsx
  packages/social-previews/src/nextdoor-preview/icons/globe-icon.tsx
  packages/social-previews/src/nextdoor-preview/icons/like-icon.tsx
  packages/social-previews/src/nextdoor-preview/icons/share-icon.tsx
  packages/social-previews/src/nextdoor-preview/index.tsx
  packages/social-previews/src/nextdoor-preview/link-preview.tsx
  packages/social-previews/src/nextdoor-preview/post-preview.tsx
  packages/social-previews/src/nextdoor-preview/previews.tsx
  packages/social-previews/src/nextdoor-preview/style.scss
  packages/social-previews/src/nextdoor-preview/types.ts
Labels: [Status] Needs Review, [Feature] Social Media Integration

#83798 Fix the condition for setting the intent state value and for showing the loading spinner
  client/my-sites/plans-features-main/index.tsx
Labels: [Status] Needs Review

#83042 Plans Comparison: add sticky behaviour to the header bar
  client/my-sites/plans-features-main/style.scss
  client/my-sites/plans-grid/components/comparison-grid/index.tsx
  client/my-sites/plans-grid/components/features-grid/index.tsx
  client/my-sites/plans-grid/components/sticky-container.tsx
  client/my-sites/plans-grid/index.tsx
  client/my-sites/plans-grid/style.scss
Labels: [Status] Needs Review

#83769 Reader - Logged out /read - Rediect to /discover instead of signup page.
  client/reader/controller.js
  client/reader/index.js
Labels: [Status] Needs Review

#83813 Logged-out Reader - Add #comments id to url of blog post link when in a comments context.
  client/reader/utils.js
Labels: [Status] Needs Review

#83473 Refactor: Remove is reskinned parameter from plan grid related code
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/plans-wrapper.tsx
  client/my-sites/plans-features-main/index.tsx
  client/my-sites/plans-grid/components/features-grid/index.tsx
  client/my-sites/plugins/plans/index.tsx
Labels: [Status] Needs Review

#83780 ActivityLog: improve Filterbar loading state in Jetpack Cloud
  client/components/activity-card-list/index.jsx
Labels: [Status] Ready to Merge

#83803 Theme Discovery: Restore Theme Showcase row elements to match production
  client/components/themes-list/style.scss
  client/my-sites/themes/theme-showcase.jsx
Labels: [Status] Needs Review, [Feature] Theme Showcase, T-Rex

#83799 Theme Discovery: Remove Discovery view and default back to Recommended view
  client/my-sites/themes/collections/style.scss
  client/my-sites/themes/collections/theme-collection-view-header.jsx
  client/my-sites/themes/collections/theme-collection-view-header.scss
  client/my-sites/themes/index.node.js
  client/my-sites/themes/index.web.js
  client/my-sites/themes/theme-showcase.jsx
Labels: [Status] Needs Review, [Feature] Theme Showcase, T-Rex

#83816 Subscriber Stats: Use null values for points before table creation
  client/my-sites/stats/stats-subscribers-chart-section/index.tsx
Labels: Stats, [Status] Needs Review, [Stats] Subscribers

#83423 Subscriber management: link to stats instead of subscriber block docs
  client/my-sites/subscribers/components/grow-your-audience/grow-your-audience.tsx
  client/my-sites/subscribers/helpers/index.ts
Labels: [Status] Needs Review, [Status] String Freeze, Subscribers Page

#83784 Update/2023 dotcom division meetup support closures for Quick Start support
  client/me/concierge/shared/closure-notice.js
  client/me/concierge/shared/primary-header.js
Labels: [Status] Needs Review

#83490 Add support for ALIAS records
  client/my-sites/domains/domain-management/dns/alias-record.jsx
  client/my-sites/domains/domain-management/dns/dns-add-new.jsx
  client/state/domains/dns/utils.js
Labels: [Status] Needs Review

#83818 Stepper for non-EN does not redirect to the localised URL
  client/landing/stepper/utils/path.ts
Labels: [Status] Needs Review

#83767 Signup: handle passswordless existing accounts
  client/blocks/login/index.jsx
  client/blocks/login/login-form.jsx
  client/blocks/signup-form/passwordless.jsx
Labels: [Status] Needs Review

#83824 Multi Domains: Disable the experiment and enable multi-domains on onboarding
  client/components/domains/domain-registration-suggestion/index.jsx
  client/signup/steps/domains/index.jsx
  client/signup/steps/domains/utils.js
  packages/data-stores/package.json
Labels: [Status] Needs Review

#83786 ActivityLog: display number of activities selected when `showAppliedFiltersCount` prop is passed
  client/my-sites/activity/filterbar/type-selector/activity-type-selector.jsx
  client/my-sites/activity/filterbar/type-selector/type-selector.jsx
Labels: [Status] Needs Review

#83204 Checkout: reorganize line items and summary for new design behind flag
  client/my-sites/checkout/src/components/checkout-sidebar-plan-upsell/index.tsx
  client/my-sites/checkout/src/components/item-variation-picker/item-variation-dropdown.tsx
  client/my-sites/checkout/src/components/item-variation-picker/variant-dropdown-price.tsx
  client/my-sites/checkout/src/components/payment-method-step.tsx
  client/my-sites/checkout/src/components/wp-checkout-order-review.tsx
  client/my-sites/checkout/src/components/wp-checkout-order-summary.tsx
  client/my-sites/checkout/src/components/wp-checkout.tsx
  client/my-sites/checkout/src/components/wp-order-review-line-items.tsx
  client/my-sites/checkout/src/hooks/product-variants.tsx
  client/my-sites/customer-home/cards/features/site-preview/index.tsx
  config/development.json
  config/horizon.json
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  packages/shopping-cart/src/types.ts
  packages/wpcom-checkout/package.json
  packages/wpcom-checkout/src/checkout-line-items.tsx
  packages/wpcom-checkout/src/checkout-version-checker.ts
  packages/wpcom-checkout/src/index.ts
  yarn.lock
Labels: [Status] Needs Review, [Feature] Checkout

#83839 Improve header margins on mobile screen sizes
  client/reader/following/main.jsx
  client/reader/following/style.scss
Labels: [Status] Needs Review

#83841 Update/likes header
  client/reader/liked-stream/main.jsx
  client/reader/liked-stream/style.scss
Labels: [Status] Needs Review

#83795 Jetpack Manage: Fix internal links causing a full page reload.
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/index.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#83836 Update/reader lists header
  client/reader/list-stream/header.jsx
  client/reader/list-stream/style.scss
Labels: [Status] Needs Review

#83838 Assembler: Update the CTA copy on the Styles screen
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-screen.tsx
Labels: [Status] Needs Review

#83843 Remove excessive padding for /plans for mobile
  client/my-sites/plans/style.scss
Labels: [Status] Needs Review

#83840 Assembler: use the perf test endpoint when flag is true
  packages/data-stores/src/site/actions.ts
Labels: [Status] Needs Review

#83793 The hiding free subdomain test on the paid media flow – 2nd attempt
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review

#83854 Conversations header fixes - css leaks to search
  client/reader/conversations/stream.js
  client/reader/conversations/stream.scss
Labels: [Status] Needs Review

#83855 Padding for navigation header on mobile discover page in the reader
  client/reader/discover/discover-navigation.scss
Labels: [Status] Needs Review

#83856 Revert "chore(deps): update wordpress monorepo"
  .yarnrc.yml
  apps/editing-toolkit/package.json
  apps/happy-blocks/package.json
  apps/o2-blocks/package.json
  apps/odyssey-stats/package.json
  apps/wpcom-block-editor/package.json
  client/package.json
  package.json
  packages/block-renderer/package.json
  packages/calypso-babel-config/package.json
  packages/calypso-build/package.json
  packages/calypso-e2e/package.json
  packages/components/package.json
  packages/composite-checkout/package.json
  packages/data-stores/package.json
  packages/design-carousel/package.json
  packages/design-picker/package.json
  packages/design-preview/package.json
  packages/domain-picker/package.json
  packages/domains-table/package.json
  packages/eslint-plugin-package-json/package.json
  packages/global-styles/package.json
  packages/help-center/package.json
  packages/i18n-calypso/package.json
  packages/i18n-utils/package.json
  packages/language-picker/package.json
  packages/launchpad-navigator/package.json
  packages/launchpad/package.json
  packages/mini-cart/package.json
  packages/onboarding/package.json
  packages/page-pattern-modal/package.json
  packages/plans-grid/package.json
  packages/search/package.json
  packages/site-picker/package.json
  packages/sites/package.json
  packages/social-previews/package.json
  packages/state-utils/package.json
  packages/subscriber/package.json
  packages/tour-kit/package.json
  packages/viewport-react/package.json
  packages/whats-new/package.json
  packages/wpcom-checkout/package.json
  packages/wpcom-template-parts/package.json
  yarn.lock
Labels: [Status] Needs Review

#83844 Fix Nextdoor connection description when connected
  client/blocks/post-share/connection.jsx
  client/blocks/post-share/style.scss
  client/my-sites/marketing/connections/service-description.jsx
Labels: [Status] Needs Review

#83812 Akismet pricing: Upgrade calypso upgrade map
  packages/calypso-products/src/constants/akismet.ts
Labels: [Status] Needs Review

#83860 calypso-e2e: Update translateFromPage utility to accept context
  packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts
  packages/calypso-e2e/src/lib/utils/translate.ts
Labels: [Type] Bug, [Status] Needs Review, i18n, Tests

#83135 Add/app promo to login link
  client/blocks/app-promo/README.md
  client/blocks/app-promo/docs/example.jsx
  client/blocks/app-promo/index.jsx
  client/blocks/app-promo/index.tsx
  client/blocks/app-promo/qr-code.tsx
  client/blocks/app-promo/style.scss
  client/blocks/get-apps/apps-badge.jsx
  client/blocks/get-apps/mobile-download-card.jsx
  client/blocks/get-apps/style.scss
  client/lib/user-agent/index.js
  client/login/magic-login/index.jsx
  client/login/magic-login/style.scss
  client/my-sites/customer-home/cards/features/app-promo/index.tsx
  client/my-sites/customer-home/cards/tasks/go-mobile/index.js
  client/my-sites/customer-home/locations/tertiary/manage-site/index.jsx
  client/my-sites/customer-home/style.scss
Labels: [Status] Needs Review, Login, Jetpack App

#83237 FoldableCard to packages (Step 4): Remove FoldableCard component shim
  client/components/foldable-card/index.jsx
Labels: [Status] Needs Review, Plans: NPM essential

#83831 Domains: Update domain-only flow to show "free domain with plan" promo like /start
  client/lib/cart-values/cart-items.ts
Labels: [Status] Needs Review

#83865 Switch the default category for build intent
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/categories.ts
Labels: [Status] Needs Review

#83845 Jetpack Manage: Fix the issue with the sidebar closing when clicking the search bar.
  client/my-sites/navigation/index.jsx
Labels: [Status] Needs Review, Jetpack Cloud

#83864 Fixed button position on the managing plans section
  client/my-sites/plans-grid/components/features-grid/index.tsx
  client/my-sites/plans-grid/style.scss
Labels: [Status] Needs Review

#83802 Staging Sites: Disable site database sync for production site with Woo
  client/my-sites/hosting/staging-site-card/card-content/staging-sync-card.tsx
  client/my-sites/hosting/staging-site-card/sync-options-panel.tsx
  client/my-sites/hosting/staging-site-card/test/sync-options-panel.js
Labels: [Status] Needs Review, Staging Sites i3

#83704 Login: Direct to login link page if user not allowed
  client/blocks/login/index.jsx
  client/blocks/login/login-form.jsx
Labels: [Status] In Progress, [Status] Needs Review

#83825 [Odie] UX Improvements
  client/odie/context/index.tsx
  client/odie/context/use-load-previous-chat.ts
  client/odie/data/index.ts
  client/odie/index.tsx
  client/odie/message/index.tsx
  client/odie/message/jump-to-recent.tsx
  client/odie/message/style.scss
  client/odie/query/index.ts
  client/odie/send-message-input/index.tsx
  client/odie/style.scss
  packages/help-center/src/components/help-center-odie.tsx
  packages/help-center/src/styles.scss
Labels: [Status] Needs Review

#83561 Refactor: remove shopping cart provider from the plans grid
  client/my-sites/plans-grid/index.tsx
Labels: [Status] Needs Review

#83879 E2E Test - Update Subscribe Block for New Behavior
  packages/calypso-e2e/src/lib/blocks/block-flows/subscribe.ts
Labels: [Status] Needs Review

#83883 E2E Test - Update Subscribe Block for New Behavior Take Two
  packages/calypso-e2e/src/lib/blocks/block-flows/subscribe.ts
Labels: [Status] Needs Review

#83810 Pricing page: Fix Jetpack Search product CTA
  client/my-sites/plans/jetpack-plans/get-purchase-url-callback.ts
  client/my-sites/sites/style.scss
Labels: [Status] Needs Review

#83717 add ai response to email ticket
  packages/help-center/src/components/help-center-contact-form.tsx
  packages/help-center/src/data/use-jetpack-search-ai.ts
  packages/help-center/src/data/use-submit-support-ticket.ts
Labels: [Status] Needs Review

#83887 Set TXT record limit to 2048 characters
  client/my-sites/domains/domain-management/dns/txt-record.jsx
  client/state/domains/dns/utils.js
Labels: [Status] Needs Review

#83834 Stats: Fix a stuck loading indicator for the Traffic chart
  client/components/stats-date-control/types.d.ts
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-chart-tabs/index.jsx
  client/my-sites/stats/stats-period-navigation/index.jsx
Labels: Stats, [Status] Needs Review

#83884 Blog onboarding: Use `key` to fix domains step default search
  client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-domain/index.tsx
Labels: [Status] Needs Review

#83783 FHT: Disable the plans/hosting-trial flag in development
  config/development.json
Labels: [Status] Needs Review, Reviewer Can Merge, Free Hosting Trial

#83696 Add bloganuary customization to blogging prompts card
  client/components/blogging-prompt-card/index.jsx
  client/components/blogging-prompt-card/prompts-navigation.jsx
  client/components/blogging-prompt-card/style.scss
  client/data/blogging-prompt/is-bloganuary.ts
  client/data/blogging-prompt/use-blogging-prompts.ts
  config/development.json
Labels: [Status] Needs Review

#76518 Updates blogging prompts to use v3 endpoint
  client/components/blogging-prompt-card/index.jsx
  client/components/blogging-prompt-card/prompts-navigation.jsx
  client/components/blogging-prompt-card/style.scss
  client/data/blogging-prompt/is-bloganuary.ts
  client/data/blogging-prompt/use-blogging-prompts.ts
  config/development.json
Labels: [Status] Needs Review, [Status] Blocked / Hold

#83899 Jetpack Manage: Fix page break when the site is expanded & minor UI issue.
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/backup-storage.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/hooks/use-extracted-backup-title.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/style.scss
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#83756 Unverified domain email address: show a notice on the relevant screens
  client/my-sites/domains/components/domain-warnings/style.scss
  client/my-sites/domains/domain-management/edit-contact-info/form-card.jsx
  client/my-sites/domains/domain-management/settings/index.tsx
  client/my-sites/domains/domain-management/settings/types.tsx
Labels: [Status] Needs Review, Reviewer Can Merge

#83909 Remove margin for NavigationHeader and fix /plans Header
  client/components/navigation-header/style.scss
  client/my-sites/plans/modernized-layout.tsx
Labels: [Status] Needs Review

#83826 Home screen: show notice if domain email is unverified
  client/my-sites/customer-home/main.jsx
Labels: [Status] Needs Review, Reviewer Can Merge

#83859 Remove free domain copy from mobile view in plans page for Woo Express $1 offer
  client/my-sites/plans-grid/components/features-grid/index.tsx
Labels: [Status] Needs Review

#83659 Add Jetpack Creator data
  client/assets/images/jetpack/jetpack-product-icon-creator.svg
  client/blocks/product-purchase-features-list/index.jsx
  client/my-sites/checkout/src/components/wp-checkout-order-summary.tsx
  client/my-sites/checkout/src/lib/get-jetpack-product-features.ts
  client/my-sites/earn/home.tsx
  client/my-sites/plans/jetpack-plans/product-store/utils/get-product-icon.ts
  client/my-sites/plans/jetpack-plans/slug-to-selector-product.ts
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
  packages/calypso-products/src/constants/jetpack.ts
  packages/calypso-products/src/constants/types.ts
  packages/calypso-products/src/is-jetpack-creator-slug.ts
  packages/calypso-products/src/main.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/product-values.ts
  packages/calypso-products/test/plan-lookups.js
  packages/components/src/product-icon/config.ts
  packages/components/src/product-icon/images/jetpack-creator.svg
Labels: [Status] Needs Review

#83907 Launchpad: Add the `subscribers-launchpad` feature flag
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#83869 Reader suggested follows dialog - add tracking event for initial view.
  client/blocks/reader-suggested-follows/dialog.jsx
Labels: [Status] Needs Review

#83835 Launchpad: Removes the Navigator request calls
  client/landing/stepper/utils/skip-launchpad.ts
  client/my-sites/customer-home/cards/launchpad/index.tsx
  packages/launchpad/src/setup-actions.ts
Labels: [Status] Needs Review, [Feature] Launchpad

#83888 Add feedback capabilities to the Odie client
  client/odie/message/index.tsx
  client/odie/message/was-this-helpful-buttons.tsx
  client/odie/query/index.ts
  client/odie/types/index.ts
Labels: [Status] Needs Review

#83889 Checkout v2: Set checkoutVersion config to true for staging
  config/stage.json
Labels: [Status] Needs Review

#83897 Domains Table: Fix loading experience where checkbox column has too much space
  packages/domains-table/src/domains-table-header/header-loading.tsx
  packages/domains-table/src/domains-table/domains-table-row-loading.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, [Feature] Domain Management

#83720 Blog onboarding: Offer option to logged users to create a new site
  client/landing/stepper/declarative-flow/design-first.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/new-or-existing-site/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/new-or-existing-site/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/site-picker-list/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-picker-list/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/sites-checker/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/sites-checker/styles.scss
  client/landing/stepper/declarative-flow/start-writing.ts
Labels: [Status] Needs Review, [Status] String Freeze

#83926 Domain: Move .page and .gay badges back to info icons and style them inline
  client/components/domains/domain-registration-suggestion/index.jsx
  client/components/domains/domain-registration-suggestion/premium-badge/style.scss
  client/components/domains/domain-registration-suggestion/style.scss
  client/components/domains/domain-suggestion/style.scss
Labels: [Status] Needs Review

#83927 Stats: Add "I don't solicit donations or sponsorships" to site identification conditions
  client/my-sites/stats/stats-purchase/stats-purchase-personal.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
Labels: Stats, [Status] Needs Review

#83858 Assembler: remove check icon from the category list
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-category-list.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-main.tsx
Labels: [Status] Needs Review

#83902 Assembler: Implement click to enlarge page preview
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/events.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-page-preview-list.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-page-preview.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-page-preview.tsx
Labels: [Status] Needs Review

#83914 Add behaviour in theme intro screen to go back using history
  client/my-sites/theme/main.jsx
Labels: [Status] Needs Review

#83933 Show "Get Business" CTA for trial sites plan upgrade
  client/my-sites/plans-grid/components/features-grid/index.tsx
  packages/calypso-products/src/main.ts
Labels: [Status] Needs Review, Reviewer Can Merge, Free Hosting Trial

#83938 Assembler: Enable flag pattern-assembler/add-pages in horizon, stage, and wpcalypso
  config/horizon.json
  config/stage.json
  config/wpcalypso.json
  test/e2e/specs/onboarding/onboarding__site-assembler.ts
Labels: [Status] Needs Review

#83901 Subscriber Stats: Align subscribers total within the All-time stats and chart sections
  client/my-sites/stats/hooks/use-subscribers-query.tsx
  client/my-sites/stats/hooks/use-subscribers-totals-query.tsx
Labels: Stats, [Status] Needs Review, [Stats] Subscribers

#83300 BBE: Revamp new/existing site step
  client/landing/stepper/declarative-flow/internals/steps-repository/difm-starting-point/index.tsx
  client/lib/signup/step-actions/index.js
  client/my-sites/marketing/do-it-for-me/difm-landing.tsx
  client/signup/config/steps-pure.js
  client/signup/config/steps.js
  client/signup/steps/new-or-existing-site/index.tsx
  client/signup/steps/new-or-existing-site/style.scss
Labels: [Status] Needs Review, BuiltByExpress

#83870 Upgrade Pricing Plan Happy block request doesn't contain user data
  apps/happy-blocks/block-library/pricing-plans/hooks/pricing-plans.ts
Labels: [Status] Needs Review

#83924 Change Creator from plan to product
  client/blocks/product-purchase-features-list/index.jsx
  client/my-sites/checkout/src/lib/get-jetpack-product-features.ts
  client/my-sites/plans/jetpack-plans/product-store/utils/get-product-icon.ts
  client/my-sites/plans/jetpack-plans/slug-to-selector-product.ts
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
  packages/calypso-products/src/constants/jetpack.ts
  packages/calypso-products/src/constants/types.ts
  packages/calypso-products/src/is-jetpack-creator-slug.ts
  packages/calypso-products/src/main.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/products-list.ts
  packages/calypso-products/src/translations.tsx
  packages/calypso-products/test/plan-lookups.js
Labels: [Status] Needs Review

#83862 Hosting Command Palette: Create an initial prototype for Calypso /sites with default commands - version 2
  client/components/command-pallette/use-command-pallette.tsx
  client/components/command-pallette/wpcom-command-pallette.tsx
  client/package.json
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/components/wpcom-smp-commands.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  package.json
  yarn.lock
Labels: [Type] Task, Components, Sites Management Page, Hosting Command Palette

#83959 `state(siteAddressChange): refactor away from `lodash`
  client/state/site-address-change/actions.js
  client/state/site-address-change/reducer.js
Labels: [Status] Needs Review, [Type] Janitorial, State, Code Style

#83955 state(siteSettings): refactor away from `lodash`
  client/my-sites/media-library/test/list-item-video.jsx
  client/state/selectors/test/is-authors-email-blocked.js
  client/state/selectors/test/is-site-supporting-image-editor.js
  client/state/site-settings/reducer.js
  client/state/site-settings/selectors.js
Labels: [Status] Needs Review, [Type] Janitorial, Code Style

#83962 BBE: Add error logging for processItemCart & createSiteWithCart
  client/lib/signup/step-actions/index.js
Labels: [Status] Needs Review, Built By Express

#83925 Newsletter: require the site slug before redirect
  client/landing/stepper/declarative-flow/newsletter.ts
Labels: [Type] Bug, [Status] Needs Review

#83949 Fix mailbox header
  client/my-sites/email/mailboxes/mailbox-selection-list/style.scss
Labels: [Status] Needs Review

#83915 Signup: Add email validation failure tracks event
  client/blocks/signup-form/index.jsx
Labels: [Status] Needs Review, [Feature] Tracks Metrics & Monitoring

#83921 Fixed typo in magic link message
  client/login/magic-login/resend-email.jsx
Labels: [Status] Needs Review

#83969 Update some e2e CODEOWNERS
  .github/CODEOWNERS
Labels: [Status] Needs Review, [Type] Tooling

#83301 Add blogging prompt links to sidebar
  client/reader/stream/reader-tag-sidebar/index.jsx
  client/reader/stream/style.scss
Labels: [Status] Needs Review

#83790 Blogging Prompts: Add 'answered' indicator to my-home card
  client/components/blogging-prompt-card/prompts-navigation.jsx
  client/components/blogging-prompt-card/style.scss
  client/data/blogging-prompt/use-blogging-prompts.ts
Labels: [Status] Needs Review

#83977 Subscriber Stats: Use Jetpack's main color for the subscriber chart on Odyssey Stats
  client/my-sites/stats/stats-subscribers-chart-section/index.tsx
  packages/components/src/chart-uplot/index.tsx
  packages/components/src/chart-uplot/lib/get-gradient-fill.ts
Labels: Stats, [Status] Needs Review, Odyssey Stats, [Stats] Subscribers

#83946 Assembler: Add Store to the Pages screen
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/constants.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-page-list.tsx
Labels: [Status] Needs Review

#83945 Fix active theme not shown in themes showcase
  client/state/themes/selectors/get-themes-for-query-ignoring-page.js
Labels: [Status] Needs Review

#83981 Odyssey Stats: only show Subscriber chart section for stats admin >= 0.11.0-alpha
  client/my-sites/stats/stats-subscribers/index.tsx
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Stats, [Status] Needs Review, Reviewer Can Merge, [Stats] Subscribers

#83806 Jetpack Manage: Split Site status content into separate components based on type.
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/toggle-activate-monitoring/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-select-checkbox/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/hooks/test/use-row-metadata.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/hooks/use-is-multisite-supported.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/hooks/use-row-metadata.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/hooks/use-tooltip.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/lib/get-links.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/site-name-column.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/site-stats-column.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/site-status-column.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
Labels: [Status] Ready to Merge, Jetpack Cloud

#83788 Remove the disabled GF signup tests.
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review

#83987 Assembler: Inject page title to page patterns
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-page-preview.tsx
  packages/block-renderer/src/components/pattern-renderer.tsx
Labels: [Status] Needs Review

#81682 state: refactor away from `_.xor` (and some _.map)
  client/state/posts/test/utils.js
  client/state/posts/utils/is-terms-equal.js
  client/state/reader-ui/sidebar/reducer.js
Labels: [Type] Enhancement, [Status] Needs Review, [Type] Janitorial, Code Style

#83975 Subscriber page: Update modal opening mechanism to respond to URL hash changes
  client/my-sites/subscribers/components/add-subscribers-modal/add-subscribers-modal.tsx
Labels: [Status] Needs Review, Subscribers Page

#83990 Jetpack Manage: Redirect plugin links to WordPress.com if the site is Atomic
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/hooks/test/use-row-metadata.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/lib/get-links.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-table/test/site-table.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#83357 Plans 2023: Remove usePlanPrices abstraction and memoize getPlanPrices one
  client/my-sites/plans-features-main/components/plan-upsell-modal/components/suggested-plan-section.tsx
  client/my-sites/plans-features-main/components/plan-upsell-modal/free-plan-free-domain-dialog.tsx
  client/my-sites/plans/hooks/use-plan-prices.ts
  client/my-sites/plans/test/use-plan-prices.ts
  client/state/plans/selectors/get-plan-prices.ts
Labels: [Status] Needs Review

#83442 Plans 2023: Remove ExternalLinkWithTracking dependency
  client/my-sites/plans-grid/components/actions.tsx
Labels: [Status] Needs Review

#83800 Plans 2023: Migrate and uncouple touch-detect lib
  client/my-sites/plans-grid/components/plans-2023-tooltip.tsx
  client/my-sites/plans-grid/hooks/use-manage-tooltip-toggle.ts
  client/my-sites/plans-grid/lib/touch-detect/README.md
  client/my-sites/plans-grid/lib/touch-detect/index.js
Labels: [Status] Needs Review, Plans: NPM essential

#83908 Devdocs: Update notice component documentation to display example for is-transparent-info status
  client/components/notice/docs/example.jsx
  client/components/notice/style.scss
Labels: DevDocs

#83706 Plans 2023: Refactor use of createSelector in main add-ons hook
  client/my-sites/add-ons/hooks/use-add-ons.ts
  client/my-sites/plans-features-main/index.tsx
  client/my-sites/plans-features-main/test/index.jsx
Labels: [Status] Needs Review, Storage Addon, Plans: NPM essential

#83970 Sign up: don't go to checkout automatically without a site slug
  client/signup/config/flows.js
Labels: [Status] Needs Review

#83993 Fix `getThemesForQueryIgnoringPage` selector dependency list
  client/state/themes/selectors/get-themes-for-query-ignoring-page.js
  client/state/themes/test/selectors.js
Labels: [Status] Needs Review

#83530 Plans 2023: Migrate PlanPill under plans-grid component
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/components/plans/plan-pill/index.jsx
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/style.scss
  client/my-sites/plans-features-main/style.scss
  client/my-sites/plans-grid/components/popular-badge.tsx
  client/my-sites/plans-grid/components/shared/plan-pill/index.jsx
  client/my-sites/plans-grid/components/shared/plan-pill/style.scss
  client/my-sites/plans-grid/style.scss
Labels: [Status] Needs Review

#83823 jcl: unmangle `fetchTestConnection` from `fetchDashboardSites`
  client/data/agency-dashboard/use-fetch-dashboard-sites.ts
  client/data/agency-dashboard/use-fetch-test-connection.ts
  client/jetpack-cloud/sections/agency-dashboard/dashboard-bulk-actions/edit-button.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-bulk-select/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-card/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-content/test/site-content.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-table-row/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
Labels: [Status] Needs Review, [Type] Janitorial, Data, Jetpack Cloud

#83957 Upgrade Pricing Plan Happy block request doesn't contain user data - 2nd attempt
  apps/happy-blocks/block-library/pricing-plans/hooks/pricing-plans.ts
Labels: [Status] Needs Review

#83996 Subscriber Page: Add SubscriberLaunchpad to manage subscriber tasks
  client/my-sites/subscribers/components/subscriber-launchpad/index.ts
  client/my-sites/subscribers/components/subscriber-launchpad/styles.scss
  client/my-sites/subscribers/components/subscriber-launchpad/subscriber-launchpad.tsx
  client/my-sites/subscribers/components/subscriber-list-container/subscriber-list-container.tsx
  client/my-sites/subscribers/hooks/index.ts
  client/my-sites/subscribers/hooks/use-subscriber-launchpad-tasks.ts
Labels: [Status] Needs Review, Subscribers Page

#84010 wp-admin Site Default: Enable wp-admin on staging and production
  config/production.json
  config/stage.json
Labels: [Status] Needs Review, [Type] Task, wp-admin Site Default

#83728 Refactor/remove is in vertical scrolling experiment prop
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/plans-wrapper.tsx
  client/my-sites/checkout/src/lib/get-flow-plan-features.ts
  client/signup/steps/plans/index.jsx
Labels: [Status] Needs Review

#84004 Add new tier hash and fix display prices for plans
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.tsx
  client/my-sites/earn/memberships/constants.ts
  client/my-sites/earn/memberships/products.tsx
  client/my-sites/earn/memberships/section.tsx
Labels: [Status] Needs Review

#83929 Multi-domain: Fix onboarding E2E test to support multi-domain selection
  client/signup/steps/domains/utils.js
  packages/calypso-e2e/src/lib/components/domain-search-component.ts
  packages/calypso-e2e/src/lib/flows/site-assembler-flow.ts
  packages/calypso-e2e/src/lib/pages/signup/signup-domain-page.ts
  test/e2e/specs/onboarding/onboarding__site-assembler.ts
  test/e2e/specs/onboarding/onboarding__write.ts
Labels: [Status] Needs Review

#83928 Login: Add site icon to magic login
  client/login/magic-login/request-login-email-form.jsx
  client/login/magic-login/style.scss
Labels: [Status] Needs Review, Login
