Repository Automattic/wp-calypso, pull requests merged in 2023-05, with the labels that each got.

#76417 Stats Widget: Apply 7-Day Highlights section mobile layout redesign
  apps/odyssey-stats/src/widget/highlights.jsx
  apps/odyssey-stats/src/widget/hightlights.scss
  apps/odyssey-stats/src/widget/index.scss
  apps/odyssey-stats/src/widget/mini-chart.scss
Labels: Stats, [Status] Needs Review, [Status] Needs Design Review, [Status] Design Input Requested, Odyssey Stats

#75762 Newsletters: update intro copy
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/index.tsx
Labels: [Status] String Freeze

#76268 E2E: in case of checkout timeout, manually navigate to the next expected URL.
  test/e2e/specs/plans/plans__signup-business.ts
  test/e2e/specs/plans/plans__upgrade.ts
Labels: [Pri] High, [Status] Needs Review

#75831 Replace Lynx patterns with virtual themes
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/constants.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-assembler-container.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/patterns/index.tsx
  packages/data-stores/src/onboard/actions.ts
  packages/data-stores/src/onboard/index.ts
  packages/data-stores/src/onboard/reducer.ts
  packages/data-stores/src/onboard/selectors.ts
  packages/data-stores/src/site/actions.ts
  packages/data-stores/src/site/constants.ts
  packages/onboarding/src/setup-tailored-site-after-creation.ts
  packages/pattern-picker/src/constants.ts
  packages/pattern-picker/src/index.tsx
  packages/pattern-picker/src/item.tsx
  packages/pattern-picker/src/use-link-in-bio-designs.ts
  packages/pattern-picker/src/use-query-patterns.ts
Labels: [Status] Needs Review, Tailored Flows

#76453 Staging Sites: Enable for all environments
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
Labels: Staging Sites i2

#76162 Fix small issue with misalignment of x-post layout in Reader
  client/blocks/reader-avatar/style.scss
Labels: [Type] Bug, [Status] Needs Review, Reader, [Size] S

#76455 Staging Sites: Link to support doc from the Hosting Config card
  client/components/inline-support-link/context-links.js
  client/my-sites/hosting/cache-card/index.js
  client/my-sites/hosting/staging-site-card/index.js
Labels: [Status] Needs Review, Staging Sites i2

#76458 Staging Sites: Clear 'Staging site added' notice upon delete, etc.
  client/my-sites/hosting/staging-site-card/index.js
  client/my-sites/hosting/staging-site-card/use-delete-staging-site.ts
Labels: [Status] Needs Review, Staging Sites i2

#76212 Adjusting feature text on the Jetpack Social pricing card
  client/jetpack-cloud/sections/jetpack-social/promo.jsx
  client/lib/plans/features-list.tsx
  client/my-sites/checkout/composite-checkout/lib/get-jetpack-product-features.ts
  client/my-sites/marketing/tools/index.tsx
  packages/calypso-products/src/translations.tsx
  packages/components/src/jetpack-upsell-card/index.tsx
Labels: [Status] Needs Review

#76401 Jetpack Pro Dashboard: Add a feature flag for the multiple email recipients for the downtime monitoring project
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/configure-email-notification/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud, Reviewer Can Merge

#76464 Ecommerce tailored flow: Update TLD vendor string for Woo Express and ecommerce flows
  packages/domain-picker/src/utils/index.ts
Labels: [Status] Needs Review, Woo Express

#76233 Signup Stepper: Only add products to cart if a site slug exists
  client/landing/stepper/declarative-flow/domain-upsell.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-plan/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-creation-step/index.tsx
Labels: [Status] Needs Review

#76382 Add newsletter status to posts page
  client/my-sites/post-relative-time-status/index.jsx
  client/my-sites/post-relative-time-status/style.scss
Labels: [Status] Needs Review

#76475 Remove earn upsell nudge since all plans support payments.
  client/my-sites/earn/memberships/index.jsx
Labels: [Status] Needs Review

#76436 Stats: Adds an overview cards section on the Subscribers page
  client/my-sites/stats/stats-subscribers-overview/index.tsx
  client/my-sites/stats/stats-subscribers-page/index.jsx
Labels: Stats, [Status] Needs Review

#76411 Block Renderer: Support custom scripts
  packages/block-renderer/src/components/block-renderer-container.tsx
  packages/block-renderer/src/components/pattern-renderer.tsx
  packages/block-renderer/src/types.ts
  packages/block-renderer/src/utils/load-scripts.ts
Labels: [Status] Needs Review

#76392 Changing the re-direct URL of the resetting password page for Gravatar
  client/login/wp-login/login-links.jsx
Labels: [Status] Needs Review, Login

#76456 Learn: Mobile fixes for content footer CTA and resources
  apps/happy-blocks/block-library/support-content-footer/index.php
  apps/happy-blocks/block-library/support-content-footer/style.scss
Labels: [Status] Needs Review

#76484 SMP: add guard when wpcom_staging_blog_ids is empty
  packages/sites/src/use-sites-list-sorting.tsx
  packages/sites/tests/use-sites-list-sorting.test.ts
Labels: [Type] Bug, [Status] Needs Review, Sites Management Page, Staging Sites i2

#76126 NewsletterInto: fix backgrounds
  client/assets/images/onboarding/newsletter-intro-bottom-mobile.png
  client/assets/images/onboarding/newsletter-intro-bottom.png
Labels: [Status] Needs Review

#76349 Enable the Unified Importer on atomic
  client/lib/importer/importer-config.tsx
  client/my-sites/importer/section-import.jsx
  client/my-sites/sidebar/use-site-menu-items.js
  config/horizon.json
  config/production.json
  config/stage.json
Labels: [Status] Needs Review, Unified Importer

#76345 Plans: Fix interval toggle margins
  client/my-sites/plan-features-2023-grid/_media-queries.scss
  client/my-sites/plan-features-2023-grid/style.scss
  client/my-sites/plans-features-main/components/plan-type-selector.tsx
  client/my-sites/plans/modernized-layout.tsx
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#76466 Domain search: Update TLD recs for ecommerce sites to use ecommerce vendor string
  client/my-sites/domains/domain-search/index.jsx
  client/state/sites/plans/selectors/index.js
  client/state/sites/plans/selectors/is-site-on-ecommerce.ts
  client/state/sites/plans/selectors/is-site-on-woo-express.ts
Labels: [Status] Needs Review, Domains, Plans: eCommerce, Woo Express, Plans: eCommerce Trial

#76207 Stepper: Connect Domain flow
  client/landing/stepper/declarative-flow/connect-domain.ts
  client/landing/stepper/declarative-flow/internals/components/step-route/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/plans-wrapper.tsx
  client/landing/stepper/declarative-flow/registered-flows.ts
  packages/onboarding/src/utils/flows.ts
Labels: [Status] Needs Review, Stepper

#76410 Subscriptions Management: Create the "Notify me of new posts" toggle for the Sites page (logged-in user)
  client/landing/subscriptions/components/settings-popover/site-settings/notify-me-of-new-posts-toggle.tsx
  client/landing/subscriptions/components/settings-popover/site-settings/site-settings.tsx
  client/landing/subscriptions/components/settings-popover/styles.scss
  client/landing/subscriptions/components/site-list/site-row.tsx
  packages/data-stores/src/reader/helpers/index.ts
  packages/data-stores/src/reader/index.ts
  packages/data-stores/src/reader/mutations/index.ts
  packages/data-stores/src/reader/mutations/use-site-notify-me-of-new-posts-mutation.ts
  packages/data-stores/src/reader/mutations/use-site-unsubscribe-mutation.ts
  packages/data-stores/src/reader/types/index.ts
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#76429 Marketplace Thank You: Centralize footer
  client/my-sites/checkout/checkout-thank-you/marketplace/style.scss
Labels: [Status] Needs Review

#75571 Backup: Staging suggestion list on clone flow
  client/my-sites/backup/clone-flow/index.tsx
  client/my-sites/backup/clone-flow/step-progress/index.tsx
  client/my-sites/backup/clone-flow/style.scss
  client/my-sites/backup/clone-flow/suggestion-search/index.tsx
  client/my-sites/backup/clone-flow/suggestion-search/style.scss
  client/my-sites/backup/clone-flow/test/index.jsx
  client/state/action-types.ts
  client/state/activity-log/actions.js
  client/state/data-layer/wpcom/activity-log/rewind/to/index.js
  client/state/rewind/selectors/get-backup-staging-sites.ts
  client/state/rewind/selectors/has-fetched-staging-sites-list.ts
  client/state/rewind/selectors/is-fetching-staging-sites-list.ts
  client/state/rewind/test/selectors.js
Labels: [Status] Needs Review, Jetpack Cloud, Jetpack Backup

#76445 Odyssey Widget: use container query with media query as fallback
  apps/odyssey-stats/package.json
  apps/odyssey-stats/src/app.scss
  apps/odyssey-stats/src/styles/widget-base.scss
  apps/odyssey-stats/src/widget/hightlights.scss
  apps/odyssey-stats/src/widget/index.scss
  apps/odyssey-stats/src/widget/modules.scss
  apps/odyssey-stats/src/widget/variables.scss
  yarn.lock
Labels: Stats, [Status] Needs Review, Reviewer Can Merge, Odyssey Stats, Odyssey Stats Widget

#76474 Add back button if coming from theme activation
  client/landing/stepper/declarative-flow/internals/steps-repository/store-address/index.tsx
  client/landing/stepper/declarative-flow/plugin-bundle-flow.ts
  client/landing/stepper/hooks/use-coming-from-theme-activation.ts
  client/my-sites/themes/thanks-modal.jsx
Labels: [Type] Bug, [Status] Needs Review

#76514 Launchpad: Use fetchLaunchpad from data store in my home controller
  client/my-sites/customer-home/controller.jsx
Labels: [Status] Needs Review, Launchpad Checklist Refactor

#76424 Blog onboarding: Create new setup-blog step
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/tasks.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/step-content.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/setup-blog/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/setup-blog/styles.scss
  client/landing/stepper/declarative-flow/start-writing.ts
Labels: [Status] Needs Review

#76335 Monthly plan upsell: Update translation formats
  client/my-sites/checkout/upsell-nudge/annual-upsell/upsell-translations.js
Labels: [Status] Needs Review

#76347 Implement monthly to annual upsell page
  client/assets/images/checkout-upsell/upsell-annual.png
  client/my-sites/checkout/upsell-nudge/annual-upsell/index.jsx
  client/my-sites/checkout/upsell-nudge/annual-upsell/style.scss
  client/my-sites/checkout/upsell-nudge/index.tsx
Labels: [Status] Needs Review

#76481 Odyssey Widget: button to install Akismet
  apps/odyssey-stats/src/styles/variables.scss
  apps/odyssey-stats/src/widget/index.jsx
  apps/odyssey-stats/src/widget/modules.jsx
  apps/odyssey-stats/src/widget/modules.scss
Labels: Stats, [Status] Needs Review, [Status] Needs Design Review, [Status] Design Input Requested, Reviewer Can Merge, Odyssey Stats, Odyssey Stats Widget

#76482 Odyssey Widget: remove external link icon
  apps/odyssey-stats/package.json
  apps/odyssey-stats/src/widget/highlights.jsx
  yarn.lock
Labels: Stats, [Status] Needs Review, Reviewer Can Merge, Odyssey Stats, Odyssey Stats Widget

#76409 Marketplace: Add category to Plugin page title
  client/my-sites/plugins/plugins-browser/index.jsx
Labels: [Status] Needs Review

#76388 Monthly plan upsell: setup the code for the experiment
  client/lib/user/shared-utils/filter-user-object.js
  client/lib/user/user.d.ts
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-complete-callback.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/index.tsx
  client/my-sites/checkout/get-thank-you-page-url/index.ts
  client/my-sites/checkout/get-thank-you-page-url/test/get-thank-you-page-url.ts
  client/state/selectors/is-monthly-to-annual-post-purchase-experiment-user.js
Labels: [Status] Needs Review

#76527 Unlocks Unified Importer for Jetpack users
  client/blocks/jetpack-plugin-update-warning/index.tsx
  client/lib/importer/importer-config.tsx
  client/my-sites/importer/section-import.jsx
  client/my-sites/sidebar/use-site-menu-items.js
Labels: [Status] Needs Review, Unified Importer

#76526 wpcom-block-editor: Track search term when inserting a block or pattern
  apps/wpcom-block-editor/src/wpcom/features/tracking.js
Labels: [Status] Needs Review

#76524 Monthly plan upsell: remove annual business plan upsell for users upgrading to premium annual through this upsell
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-complete-callback.tsx
  client/my-sites/checkout/get-thank-you-page-url/index.ts
  client/my-sites/checkout/get-thank-you-page-url/test/get-thank-you-page-url.ts
Labels: [Status] Needs Review

#76511 Newsletter: small visual fix to checkbox
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/style.scss
Labels: [Status] Needs Review

#76419 localizeUrl: option to preserve trailing slash variation
  packages/i18n-utils/CHANGELOG.md
  packages/i18n-utils/package.json
  packages/i18n-utils/src/localize-url.tsx
  packages/i18n-utils/src/test/localize-url.js
  packages/wpcom-template-parts/src/universal-header-navigation/index.tsx
Labels: [Type] Bug, [Type] Enhancement, Themes, [Status] Needs Review, i18n

#76374 Blog onboarding: Add choose domain task
  client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-domain/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-domain/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/types.ts
  client/landing/stepper/declarative-flow/start-writing.ts
  packages/data-stores/src/site/types.ts
Labels: [Status] Needs Review

#76427 Marketplace Thank You: Guarantee 3 sections on footer
  client/my-sites/checkout/checkout-thank-you/marketplace/use-thank-you-footer.tsx
Labels: [Status] Needs Review

#76492 Fix/videopress e2e flaky test
  client/landing/stepper/declarative-flow/videopress.ts
Labels: [Status] Needs Review

#76533 GitHub Integration: Only show in development and wpcalypso
  client/my-sites/hosting/main.js
  config/development.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#76516 Blog onboarding: Add task disabling to Start writing v1
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
Labels: [Status] Needs Review

#76538 Staging Sites: Remove feature flag
  client/my-sites/hosting/main.js
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Staging Sites i2

#76536 Woo Express: Redirect completed Woo Express trials to WooCommerce home
  client/landing/stepper/declarative-flow/trial-wooexpress-flow.ts
Labels: [Status] Needs Review, Woo Express, Woo Express Trial

#76539 Sites: Only show the 'Deploy from GitHub' menu item when enabled
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
Labels: Sites, [Status] Needs Review

#76537 Iterated on visual changes for blog-onboarding
  client/components/domains/register-domain-step/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
Labels: [Status] Needs Review

#76540 Do not treat Atomic sites as Jetpack in useValidCheckoutBackUrl
  client/my-sites/checkout/composite-checkout/hooks/use-valid-checkout-back-url.ts
Labels: [Status] Needs Review

#76420 Added new post and new comment columns to Sites list in Subscription Manager
  client/landing/subscriptions/components/site-list/site-list.tsx
  client/landing/subscriptions/components/site-list/site-row.tsx
  client/landing/subscriptions/components/site-list/styles.scss
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#76545 Woo Express: Memoize tasks list for post-upgrade screen
  client/my-sites/plans/ecommerce-trial/upgrade-confirmation/index.tsx
Labels: [Status] Needs Review, Woo Express

#76542 Cleanup: WoA Logging feature flags
  client/my-sites/hosting/main.js
  client/my-sites/hosting/web-server-logs-card/index.js
  client/my-sites/hosting/web-server-logs-card/style.scss
  client/my-sites/hosting/web-server-logs-card/test/index.js
  client/my-sites/sidebar/static-data/fallback-menu.js
  client/my-sites/site-logs/index.ts
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Type] Janitorial, Reviewer Can Merge, WoA Logging i1

#76546 Staging Sites: Tweak card layouts and add more 'Learn more' links
  client/my-sites/hosting/staging-site-card/index.js
  client/my-sites/hosting/staging-site-card/staging-site-production-card.tsx
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
Labels: [Status] Needs Review, Staging Sites i2

#76553 Updated strategy to close sidebar on first editor load
  apps/wpcom-block-editor/src/wpcom/features/redirect-onboarding-user-after-publishing-post.js
  apps/wpcom-block-editor/src/wpcom/features/test/redirect-onboarding-user-after-publishing-post.test.js
Labels: [Status] Needs Review

#75309 Checkout: Show helpful error message for renewal URLs with incorrect site
  client/my-sites/checkout/composite-checkout/components/checkout-main.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-add-products-from-url.ts
  client/my-sites/checkout/composite-checkout/hooks/use-prepare-products-for-cart.ts
  client/my-sites/checkout/composite-checkout/test/checkout-contact-autocomplete.tsx
  client/my-sites/checkout/composite-checkout/test/checkout-contact-step.tsx
  client/my-sites/checkout/composite-checkout/test/checkout-extra-tax-fields.tsx
  client/my-sites/checkout/composite-checkout/test/checkout-main.tsx
  client/my-sites/checkout/composite-checkout/test/checkout-payment-method-list.tsx
  client/my-sites/checkout/composite-checkout/test/checkout-vat-form.tsx
  client/my-sites/checkout/composite-checkout/test/util/index.ts
  client/my-sites/checkout/composite-checkout/test/util/mock-checkout.tsx
  client/my-sites/checkout/controller.jsx
  client/my-sites/checkout/index.js
  client/my-sites/controller.js
Labels: [Status] Needs Review, Checkout

#76547 Blog onboarding: Start writing v1 design iteration
  client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-domain/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/setup-blog/index.tsx
Labels: [Status] Needs Review

#76559 Blog onboarding: Updated plans page using 2023 model
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/plans-wrapper.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/style.scss
Labels: [Status] Needs Review

#76556 Stats: Migrate untyped files to TypeScript
  client/components/jetpack-colophon/index.tsx
  client/my-sites/stats/controller.jsx
  client/my-sites/stats/stats-subscribers-chart-section/index.tsx
  client/my-sites/stats/stats-subscribers-chart-section/style.scss
  client/my-sites/stats/stats-subscribers/index.jsx
  client/my-sites/stats/stats-subscribers/index.tsx
  client/my-sites/stats/stats-subscribers/subscribers-highlight-section.scss
  client/my-sites/stats/stats-subscribers/subscribers-highlight-section.tsx
  packages/components/src/highlight-cards/count-comparison-card.tsx
Labels: Stats, [Status] Needs Review, [Type] Janitorial

#76502 Stats Widget: Add empty state placeholder and styling
  apps/odyssey-stats/src/widget/mini-chart.jsx
  apps/odyssey-stats/src/widget/mini-chart.scss
  client/my-sites/stats/stats-empty-state/index.tsx
  yarn.lock
Labels: Stats, [Status] Needs Review, [Status] Needs Design Review, [Status] Design Input Requested, Odyssey Stats

#76525 Theme Showcase: Fix live demo loading for 3rd-party themes
  client/my-sites/theme/main.jsx
Labels: [Type] Bug, [Status] Needs Review, Theme Showcase

#76025 Pricing page: Add Backup FAQs info on the product lightbox.
  client/my-sites/plans/jetpack-plans/faq/index.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/faq-list.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/product-details.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/style.scss
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-included-product-description-map.tsx
  client/my-sites/plans/jetpack-plans/slug-to-selector-product.ts
  client/my-sites/plans/jetpack-plans/types.ts
  packages/calypso-products/src/get-jetpack-product-faqs.ts
  packages/calypso-products/src/product-values.ts
  packages/calypso-products/src/translations.tsx
  packages/calypso-products/src/types.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud, Pricing/plans Page

#76405 Social Previews | Update Google Search preview
  client/components/seo-preview-pane/index.jsx
  packages/social-previews/src/google-search-preview/index.tsx
  packages/social-previews/src/google-search-preview/style.scss
  packages/social-previews/src/index.ts
  packages/social-previews/src/search-preview/index.jsx
  packages/social-previews/test/index.js
Labels: [Status] Needs Review

#76572 Fix: Plans step broken UI in domain-upsell flow
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/plans-wrapper.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/style.scss
  packages/calypso-products/src/plans-utilities.ts
Labels: [Status] Needs Review

#76574 Pricing page: Add storage limit FAQs in Backup lightbox.
  client/my-sites/plans/jetpack-plans/faq/index.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/faq-list.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/product-details.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/style.scss
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-included-product-description-map.tsx
  client/my-sites/plans/jetpack-plans/slug-to-selector-product.ts
  client/my-sites/plans/jetpack-plans/types.ts
  packages/calypso-products/src/get-jetpack-product-faqs.ts
  packages/calypso-products/src/product-values.ts
  packages/calypso-products/src/translations.tsx
  packages/calypso-products/src/types.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud, Pricing/plans Page

#76504 Subscriptions Management: Create the "Email me new posts" toggle for the Sites page (logged-in user)
  client/landing/subscriptions/components/settings-popover/site-settings/delivery-frequency-input.tsx
  client/landing/subscriptions/components/settings-popover/site-settings/email-me-new-posts-toggle.tsx
  client/landing/subscriptions/components/settings-popover/site-settings/site-settings.tsx
  client/landing/subscriptions/components/settings-popover/styles.scss
  client/landing/subscriptions/components/site-list/site-row.tsx
  packages/data-stores/src/reader/index.ts
  packages/data-stores/src/reader/mutations/index.ts
  packages/data-stores/src/reader/mutations/use-site-email-me-new-posts-mutation.ts
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#76529 Theme Detail Page: Theme preview should not block the logged-out footer
  client/my-sites/theme/main.jsx
  client/my-sites/theme/style.scss
Labels: [Type] Bug, [Status] Needs Review, Theme Showcase

#76078 Pricing page: Add new Jetpack Scan FAQs in the pricing page.
  client/my-sites/plans-features-main/components/jetpack-faq.jsx
  client/my-sites/plans/jetpack-plans/faq/index.tsx
  client/my-sites/plans/jetpack-plans/faq/style.scss
  client/my-sites/plans/jetpack-plans/slug-to-selector-product.ts
  packages/calypso-products/src/get-jetpack-product-faqs.ts
  packages/calypso-products/src/translations.tsx
Labels: Jetpack, [Status] Needs Review, [Status] String Freeze, Jetpack Cloud, Pricing/plans Page

#76283 Newsletter: switch few setup step label names
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-post-setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/index.tsx
Labels: [Status] String Freeze

#76131 Newsletter: update "Lettre" colour to "Allegro Blue"
  client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx
Labels: [Status] String Freeze

#76581 Prepare social-previews package for the release
  packages/social-previews/CHANGELOG.md
  packages/social-previews/package.json
Labels: [Status] Needs Review

#76094 Revamp Blaze banner
  client/assets/images/blaze/zenit-photo-banner.jpeg
  client/assets/images/customer-home/illustration--blaze.svg
  client/my-sites/promote-post-i2/components/campaigns-table/index.tsx
  client/my-sites/promote-post-i2/components/post-item/style.scss
  client/my-sites/promote-post-i2/components/posts-list-banner/index.tsx
  client/my-sites/promote-post-i2/components/posts-list-banner/style.scss
  client/my-sites/promote-post-i2/components/posts-list/index.tsx
  client/my-sites/promote-post-i2/components/search-bar/style.scss
  client/my-sites/promote-post-i2/main.tsx
  client/my-sites/promote-post-i2/style.scss
Labels: [Status] Needs Review

#76586 Staging Sites: Allow installing free plugins on staging sites
  client/my-sites/plugins/plugin-details-CTA/index.jsx
Labels: [Type] Bug, [Status] Needs Review, Reviewer Can Merge, Staging Sites i2

#76503 E2E: update regex of `waitForResponse` when waiting for the EditorPage to initially load.
  packages/calypso-e2e/src/lib/pages/editor-page.ts
Labels: [Status] Needs Review

#76454 Plans: Move query to domain-suggestions store
  client/my-sites/plan-features-2023-grid/components/features.tsx
  client/my-sites/plan-features-2023-grid/hooks/use-get-wordpress-subdomain.ts
  client/my-sites/plans-features-main/components/free-plan-paid-domain-dialog.tsx
  packages/data-stores/src/domain-suggestions/index.ts
  packages/data-stores/src/domain-suggestions/queries.ts
Labels: [Status] Needs Review

#75174 Newsletter Flow: Plan step to use new grid
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/plans-wrapper.tsx
  client/landing/stepper/declarative-flow/newsletter.ts
  client/lib/plans/features-list.tsx
  client/my-sites/plan-features-2023-grid/components/plan-comparison-grid.tsx
  client/my-sites/plan-features-2023-grid/components/popular-badge.tsx
  client/my-sites/plan-features-2023-grid/hooks/use-highlight-adjacency-matrix.ts
  client/my-sites/plan-features-2023-grid/hooks/use-highlight-label.ts
  client/my-sites/plan-features-2023-grid/index.tsx
  client/my-sites/plans-features-main/index.jsx
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/main.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/plans-utilities.ts
  packages/calypso-products/src/types.ts
  packages/data-stores/src/onboard/actions.ts
  packages/data-stores/src/onboard/reducer.ts
  packages/data-stores/src/onboard/selectors.ts
Labels: [Status] Needs Review, [Status] Needs Design Review, [Status] String Freeze, [Status] Design Input Requested, Tailored Flows

#76585 Subscriptions Management: Hide the right header menu items for logged-in users
  client/landing/subscriptions/components/subscription-manager-page/subscription-manager-page.tsx
  packages/wpcom-template-parts/src/universal-header-navigation/style.scss
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#76568 Blog onboarding: On the domain step CTAs should say “Select” not “Upgrade”
  client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-domain/index.tsx
Labels: [Status] Needs Review

#76510 Launchpad: Show Steps Number in Help Center
  packages/help-center/src/components/help-center-launchpad.scss
Labels: [Status] Needs Review, Launchpad Checklist Refactor

#75850 Updates theme detection of full site editing to use is_block_theme
  client/data/themes/use-active-theme-query.ts
  client/data/themes/with-is-fse-active.js
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-theme-section.tsx
Labels: Themes, [Status] Needs Review

#76560 Launchpad: Remove unnecessary launchpad task definition attributes
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/step-content.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/task-helper.ts
Labels: [Status] Needs Review, Launchpad Checklist Refactor

#76599 Launchpad: Remove unused task definitions
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/tasks.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/task-helper.ts
Labels: [Status] Needs Review, Launchpad Checklist Refactor

#76573 Stats: Updating Subscribers graph
  packages/components/src/chart-uplot/index.tsx
Labels: Stats, [Status] Needs Review

#76371 Site Editor: update `getSiteEditorUrl` for the post-iframe era.
  client/components/themes-list/index.jsx
  client/gutenberg/editor/controller.js
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
  client/my-sites/themes/test/thanks-modal.jsx
  client/state/selectors/get-site-editor-url.js
Labels: [Status] Needs Review, [Goal] Full Site Editing

#76520 Stats: Adding navigation arrows for subscribers
  client/my-sites/stats/hooks/use-subscribers-query.js
  client/my-sites/stats/navigation-arrows/index.tsx
  client/my-sites/stats/stats-subscribers-chart-section/index.tsx
  client/my-sites/stats/stats-subscribers-chart-section/style.scss
  client/my-sites/stats/stats-subscribers-chart-section/subscribers-navigation-arrows.tsx
  client/my-sites/stats/stats-subscribers-chart-section/test/subscribers-navigation-arrows.test.js
  client/my-sites/stats/stats-subscribers/index.tsx
Labels: Stats, [Status] Needs Review

#76577 Jetpack Pro Dashboard: implement UI to display the default email address in downtime monitoring settings
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/configure-email-notification/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/configure-email-notification/style.scss
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#76622 Fix social previews build error
  packages/social-previews/package.json
  packages/social-previews/src/facebook-preview/index.tsx
  packages/social-previews/src/facebook-preview/post/header/index.tsx
  packages/social-previews/src/index.ts
  packages/social-previews/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review

#76548 Subscription Manager: add "Paused" value in Email Frequency when no email subscription
  client/landing/subscriptions/components/site-list/site-row.tsx
Labels: [Status] Needs Review, [Status] Needs Author Reply, Subscription Management, [SM] Calypso Portal

#76623 Update loading of Pricing Plans block configuration
  apps/happy-blocks/block-library/pricing-plans/index.php
Labels: [Status] Needs Review

#76595 Subscriptions Management: Create "Email me new comments" toggle for the Sites page (logged-in user)
  client/landing/subscriptions/components/settings-popover/site-settings/email-me-new-comments-toggle.tsx
  client/landing/subscriptions/components/settings-popover/site-settings/site-settings.tsx
  client/landing/subscriptions/components/settings-popover/styles.scss
  client/landing/subscriptions/components/site-list/site-row.tsx
  packages/data-stores/src/reader/index.ts
  packages/data-stores/src/reader/mutations/index.ts
  packages/data-stores/src/reader/mutations/use-site-email-me-new-comments-mutation.ts
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#76593 Fix the infinite loading state on Jetpack Backups list
  client/my-sites/backup/status/hooks.js
Labels: [Status] Needs Review, Jetpack Backup

#76584 Blog onboarding: Add post launch screen
  client/components/formatted-header/index.jsx
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-domain/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/start-writing-done/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/start-writing-done/site-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/start-writing-done/styles.scss
  client/landing/stepper/declarative-flow/start-writing.ts
  packages/onboarding/src/step-container/style.scss
Labels: [Status] Needs Review, [Status] String Freeze

#75891 E2E: Stabilize the Editor post schedule tests
  packages/calypso-e2e/src/lib/pages/editor-page.ts
Labels: [Status] Needs Review

#76403 Add track-resurrections unit tests
  client/lib/analytics/track-resurrections/test/index.jsx
Labels: [Status] Needs Review, Analytics, [Tests] Includes Tests

#76600 Newsletter: highlight personal plan instead of premium
  client/my-sites/plan-features-2023-grid/hooks/use-highlight-adjacency-matrix.ts
  client/my-sites/plan-features-2023-grid/hooks/use-highlight-label.ts
Labels: [Status] Needs Review

#76508 Subscription Manager: if user is logged in, unfollow site has different endpoint
  client/landing/subscriptions/components/site-list/site-row.tsx
  packages/data-stores/src/reader/mutations/use-site-unsubscribe-mutation.ts
  packages/data-stores/src/reader/queries/use-site-subscriptions-query.ts
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#76624 Blog onboarding: Disable edit overlay in launchpad preview
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/launchpad-site-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/launchpad-site-preview.tsx
Labels: [Status] Needs Review

#76628 Update social-previews package to use icons as data URIs
  packages/social-previews/package.json
  packages/social-previews/src/facebook-preview/post/header/default-avatar.png
  packages/social-previews/src/facebook-preview/post/header/index.tsx
  packages/social-previews/src/facebook-preview/post/icons/fb-icons.png
  packages/social-previews/src/facebook-preview/post/icons/index.tsx
  packages/social-previews/src/facebook-preview/post/icons/styles.scss
  packages/social-previews/tsconfig.json
  packages/social-previews/types.d.ts
Labels: [Status] Needs Review

#76459 Limited Global Styles: Improve launchbar notice
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-global-styles/index.php
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-global-styles/wpcom-global-styles-view.js
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-global-styles/wpcom-global-styles-view.scss
Labels: [Status] Needs Review, Global Styles

#76635 Subscriber import: remove unclear follower notice
  packages/subscriber/src/components/add-form/index.tsx
Labels: [Status] Needs Review

#76629 Fix reader search redirect
  client/server/pages/index.js
Labels: [Status] Needs Review

#76541 Domain Upsell: Use updateLaunchpadSettings from data-stores
  client/landing/stepper/declarative-flow/domain-upsell.ts
  packages/data-stores/src/queries/use-launchpad.ts
Labels: [Status] In Progress, [Status] Needs Review, Launchpad

#76360 Update posts and recommended posts on reader search page
  client/reader/search-stream/post-results.jsx
  client/reader/search-stream/style.scss
  client/reader/search/controller.js
  client/reader/stream/empty-search-recommended-site.jsx
  client/reader/stream/index.jsx
  client/reader/stream/reader-list-followed-sites/item.jsx
  client/reader/stream/reader-search-sidebar/index.jsx
  client/reader/stream/style.scss
  client/reader/style.scss
  client/state/data-layer/wpcom/read/streams/index.js
Labels: [Status] Needs Review

#76608 Jetpack Backup: Add Tracks events for Clone Flow clicks
  client/components/advanced-credentials/index.tsx
  client/my-sites/activity/activity-log-v2/index.tsx
  client/my-sites/backup/clone-flow/index.tsx
  client/my-sites/backup/main.jsx
Labels: [Status] Needs Review, Jetpack Backup

#76543 Start Writing Flow: Use Launchpad hook from data-stores
  client/landing/stepper/declarative-flow/start-writing.ts
  packages/data-stores/src/queries/use-launchpad.ts
Labels: [Status] In Progress, [Status] Needs Review, Launchpad, Launchpad Checklist Refactor

#76566 Adds "Copy this site" functionality to the agency dashboard
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-actions/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-backup-staging/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-backup-staging/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-card/test/site-card.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-content/test/site-content.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-table-row/test/site-table-row.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-table/test/site-table.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/utils.ts
Labels: [Status] Needs Review, Jetpack Backup

#76611 Add Jetpack Starter to pricing page
  client/assets/images/jetpack/hero-backup-lg.png
  client/assets/images/jetpack/hero-backup-sm.png
  client/assets/images/jetpack/hero-complete-lg.png
  client/assets/images/jetpack/hero-complete-md.png
  client/assets/images/jetpack/hero-complete-sm.png
  client/assets/images/jetpack/hero-complete.png
  client/assets/images/jetpack/hero-security-lg.png
  client/assets/images/jetpack/hero-security-sm.png
  client/assets/images/jetpack/hero-security.png
  client/assets/images/jetpack/hero-starter.png
  client/assets/images/jetpack/hero-videopress-lg.png
  client/assets/images/jetpack/hero-videopress-sm.png
  client/assets/images/jetpack/jetpack-product-icon-starter.svg
  client/components/jetpack/intro-pricing-banner/index.tsx
  client/lib/plans/features-list.tsx
  client/my-sites/checkout/composite-checkout/lib/get-jetpack-product-features.ts
  client/my-sites/plan-features/test/__snapshots__/header.jsx.snap
  client/my-sites/plans/jetpack-plans/constants.ts
  client/my-sites/plans/jetpack-plans/product-lightbox/icons/tags.tsx
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/hero-image/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/hero-image/style.scss
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-included-product-description-map.tsx
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-pricing-breakdown.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/most-popular.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/style-most-popular.scss
  client/my-sites/plans/jetpack-plans/product-store/pricing-banner/style.scss
  client/my-sites/plans/jetpack-plans/product-store/style.scss
  client/my-sites/plans/jetpack-plans/product-store/types.ts
  client/my-sites/plans/jetpack-plans/product-store/utils/get-product-icon.ts
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/constants/jetpack.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/products-list.ts
  packages/calypso-products/src/translations.tsx
  packages/components/src/product-icon/config.ts
  packages/components/src/product-icon/images/jetpack-bundles.svg
Labels: [Status] Needs Review

#76634 Blog onboarding: Redirect paid domain selection to plans selection
  client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-domain/index.tsx
  client/landing/stepper/declarative-flow/start-writing.ts
Labels: [Status] Needs Review

#76647 Pricing Page: Fix duplicate Backup product card showing when Jetpack Starter Plan is owned.
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
Labels: Jetpack, [Status] Needs Review, Pricing/plans Page, Jetpack Starter

#76651 Pricing page: Update JP Starter and Security product card plan features.
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Ready to Merge, [Size] XS, Pricing/plans Page, Copy task

#76583 Theme Showcase: Fix generating links that are causing HTTP 302 redirects
  client/my-sites/theme/controller.jsx
  client/my-sites/theme/index.node.js
  client/my-sites/theme/theme-features-card.js
Labels: [Type] Bug, [Status] Needs Review, Theme Showcase

#76654 Theme Showcase: Add typeof window check
  client/state/selectors/get-site-editor-url.js
Labels: [Type] Bug, [Status] Needs Review, Theme Showcase

#76612 Hosting site creation flow ends on /sites page
  client/my-sites/checkout/checkout-thank-you/pending/index.tsx
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  client/sites-dashboard/components/sites-content-controls.tsx
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/controller.tsx
  client/sites-dashboard/index.ts
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting onboarding i2

#76655 Hosting Onboarding: Add i2 flag flag
  config/development.json
  config/horizon.json
  config/production.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting onboarding i2

#76563 Subscribers form: change parent element from <p> to <div>
  packages/subscriber/src/components/add-form/index.tsx
Labels: [Status] Needs Review, Subscriber Importer

#76557 Import focused flow: Skip preview step if it comes from move to wpcom plugin
  client/landing/stepper/declarative-flow/internals/steps-repository/import-ready-preview/index.tsx
Labels: [Status] Needs Review, Migration Plugin i2

#76637 Blog onboarding: Allow the user to change their domain on writing flow
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
  client/landing/stepper/declarative-flow/start-writing.ts
  packages/onboarding/src/cart/index.tsx
  packages/onboarding/src/index.ts
Labels: [Status] Needs Review

#76666 Social Previews | Update docs for the package
  packages/social-previews/README.md
Labels: [Status] Needs Review

#76665 Social Previews | Unify the props/types to make them consistent
  client/components/share/linkedin-share-preview/index.jsx
  packages/social-previews/src/facebook-preview/hooks/use-image-hook.ts
  packages/social-previews/src/facebook-preview/types.ts
  packages/social-previews/src/google-search-preview/index.tsx
  packages/social-previews/src/index.ts
  packages/social-previews/src/linkedin-preview/index.tsx
  packages/social-previews/src/shared/section-heading/index.tsx
  packages/social-previews/src/tumblr-preview/full-preview.tsx
  packages/social-previews/src/tumblr-preview/types.ts
  packages/social-previews/src/twitter-preview/types.ts
  packages/social-previews/src/types.ts
Labels: [Status] Needs Review

#76358 LinkInBio Flow: Plan step to use new grid
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/plans-wrapper.tsx
  client/landing/stepper/declarative-flow/link-in-bio.ts
  client/lib/plans/features-list.tsx
  client/my-sites/plan-features-2023-grid/hooks/use-highlight-adjacency-matrix.ts
  client/my-sites/plan-features-2023-grid/hooks/use-highlight-label.ts
  client/my-sites/plan-features-2023-grid/index.tsx
  client/my-sites/plans-features-main/index.jsx
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/main.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/plans-utilities.ts
  packages/calypso-products/src/types.ts
Labels: [Status] Needs Review, [Status] String Freeze

#76378 Update/move purchase overlap to thank you page
  client/my-sites/checkout/checkout-thank-you/akismet-checkout-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/style.scss
  client/my-sites/checkout/composite-checkout/components/prepurchase-notices/akismet-product-overlaps-owned-product-notice.tsx
  client/my-sites/checkout/composite-checkout/components/prepurchase-notices/index.jsx
Labels: [Status] Needs Review

#76377 Checkout: Render loading info and support link if loading is slow
  client/my-sites/checkout/composite-checkout/components/checkout-loading-placeholder.tsx
  client/my-sites/checkout/composite-checkout/components/checkout-main.tsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
  packages/composite-checkout/README.md
  packages/composite-checkout/src/components/checkout-steps.tsx
  packages/composite-checkout/src/public-api.ts
Labels: [Status] Needs Review, [Status] String Freeze

#76609 Payments: Replace fallback with "tax (VAT/GST/CT)" for "Add VAT details"
  client/me/purchases/billing-history/main.tsx
  client/me/purchases/controller.jsx
  client/me/purchases/vat-info/index.tsx
  client/my-sites/checkout/composite-checkout/components/vat-form/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#76428 Blog onboarding: Add preemptive translations
  client/landing/stepper/declarative-flow/blog-onboarding-translations.js
Labels: [Status] Needs Review, [Status] String Freeze

#76669 Fix Reader Search paging
  client/reader/search-stream/style.scss
  client/state/data-layer/wpcom/read/streams/index.js
Labels: [Status] Needs Review

#76519 Purchases: Convert PurchaseMeta to TypeScript
  client/components/user/index.tsx
  client/lib/purchases/types.ts
  client/me/purchases/manage-purchase/purchase-meta-owner.tsx
  client/me/purchases/manage-purchase/purchase-meta-payment-details.tsx
  client/me/purchases/manage-purchase/purchase-meta-price.tsx
  client/me/purchases/manage-purchase/purchase-meta.tsx
Labels: [Status] Needs Review

#76638 Stats Widget: Add external link support to Top Referrer items
  apps/odyssey-stats/package.json
  apps/odyssey-stats/src/hooks/use-referrers-query.js
  apps/odyssey-stats/src/widget/highlights.jsx
  yarn.lock
Labels: Stats, [Status] Needs Review, Odyssey Stats, Odyssey Stats Widget

#76555 Me: Add an 'I am a developer' toggle
  client/me/profile/index.jsx
  client/me/profile/style.scss
Labels: [Status] Needs Review, Me, [Status] String Freeze

#76658 Only allow post, page and product to show for blaze
  client/my-sites/promote-post-i2/main.tsx
  client/my-sites/promote-post/main.tsx
Labels: [Status] Needs Review

#76683 Stats: Fixing week view for Subscribers
  client/my-sites/stats/hooks/use-subscribers-query.js
Labels: Stats, [Status] Needs Review

#76046 E2E: get CoBlocks specs to a green state.
  packages/calypso-e2e/src/secrets/encrypted.enc
  test/e2e/specs/blocks/blocks__shallowly_smoke_test_popular_blocks.ts
  test/e2e/specs/fse/fse__temp-smoke-test.ts
Labels: [Status] Needs Review

#76631 Jetpack Pro Dashboard: Implement UI to add email addresses to downtime monitor notification settings
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/configure-email-notification/add-new-email-modal.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/configure-email-notification/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/configure-email-notification/style.scss
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#76691 Odyssey Stats: Migrate non-component code to TypeScript - Migration Part 1
  apps/odyssey-stats/src/hooks/use-module-data-query.ts
  apps/odyssey-stats/src/hooks/use-referrers-query.ts
  apps/odyssey-stats/src/hooks/use-top-posts-query.ts
  apps/odyssey-stats/src/hooks/use-visits-query.ts
  apps/odyssey-stats/src/lib/can-current-user.js
  apps/odyssey-stats/src/lib/can-current-user.ts
  apps/odyssey-stats/src/lib/config-api.ts
  apps/odyssey-stats/src/lib/init-app-config.ts
  apps/odyssey-stats/src/lib/init-widget-config.ts
  apps/odyssey-stats/src/lib/set-locale.ts
  apps/odyssey-stats/src/page-middleware/setup-context.ts
  apps/odyssey-stats/src/routes.ts
  apps/odyssey-stats/src/typings.ts
  apps/odyssey-stats/src/widget-loader.ts
  apps/odyssey-stats/tsconfig.json
  client/tsconfig-reference.json
Labels: Stats, [Status] Needs Review, Odyssey Stats, Odyssey Stats Widget

#76674 Jetpack Pro Dashboard: show the verification status for downtime monitor notification email addresses.
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/configure-email-notification/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/configure-email-notification/style.scss
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#76668 Signup: Fix incorrect domain upsell alignment
  client/my-sites/plan-features-2023-grid/components/features.tsx
Labels: [Status] Needs Review

#76620 Remove Autobots as code owners
  .github/CODEOWNERS
Labels: [Status] Needs Review

#76706 Reader: Set static height in search area
  client/reader/search-stream/index.jsx
Labels: [Status] Needs Review

#76633 Enable Export button for still-Atomic expired eCommerce trial sites
  client/my-sites/plans/ecommerce-trial/ecommerce-trial-expired/index.tsx
Labels: Export, [Status] Needs Review, Woo Express, Woo Express Trial

#76717 Checkout: display 14-day refund copy below CTA for biennially and triennially products
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
Labels: [Status] Needs Review, Checkout, Hosting onboarding i1

#76679 Subscriptions management: Fix the URL for querying post subscriptions for logged-in users
  packages/data-stores/src/reader/queries/use-post-subscriptions-query.ts
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#76657 Hosting Onboarding: New site creation flow for users interested in "hosting"
  client/landing/stepper/declarative-flow/hosting-site-creation-flow.ts
  client/landing/stepper/declarative-flow/internals/components/step-route/index.tsx
  client/landing/stepper/declarative-flow/internals/hosting-site-creation-flow.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/plans-wrapper.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-creation-step/index.tsx
  client/landing/stepper/declarative-flow/registered-flows.ts
  packages/calypso-products/src/plans-utilities.ts
  packages/onboarding/src/utils/flows.ts
Labels: [Status] Needs Review, Hosting onboarding i2

#76718 Remove uses of aspect ratio since height is known
  packages/design-carousel/src/styles.scss
Labels: [Status] Needs Review

#76521 Purchases: Convert ManagePurchase to TypeScript
  client/lib/site/utils.js
  client/me/purchases/manage-purchase/auto-renew-toggle/index.tsx
  client/me/purchases/manage-purchase/index.tsx
  client/me/purchases/manage-purchase/test/purchase-management-buttons.js
  client/me/purchases/pre-cancellation-dialog/index.tsx
  client/my-sites/domains/domain-management/settings/cards/registered-domain-details.tsx
  client/state/products-list/selectors/get-products-list.ts
  packages/calypso-products/src/main.ts
  packages/data-stores/src/site/types.ts
Labels: [Status] Needs Review

#76698 Odyssey Stats: Migrate create-odyssey-config.js to TypeScript - Migration Part 3
  apps/odyssey-stats/src/lib/create-odyssey-config.js
  apps/odyssey-stats/src/lib/create-odyssey-config.ts
  apps/odyssey-stats/tsconfig.json
  config/production.json
Labels: Stats, [Status] Needs Review, Odyssey Stats, Odyssey Stats Widget

#76692 Odyssey Stats: Migrate components to TypeScript - Migration Part 2
  apps/odyssey-stats/src/app.tsx
  apps/odyssey-stats/src/components/layout.jsx
  apps/odyssey-stats/src/components/layout.tsx
  apps/odyssey-stats/src/components/nothing.tsx
  apps/odyssey-stats/src/page-middleware/layout.tsx
  apps/odyssey-stats/src/widget/highlights.scss
  apps/odyssey-stats/src/widget/highlights.tsx
  apps/odyssey-stats/src/widget/index.tsx
  apps/odyssey-stats/src/widget/mini-chart.tsx
  apps/odyssey-stats/src/widget/modules.tsx
  client/lib/track-element-size/index.ts
  client/my-sites/stats/stats-empty-state/index.tsx
Labels: Stats, [Status] Needs Review, Odyssey Stats, Odyssey Stats Widget

#54009 Reader: in search, show 'no sites found' message
  client/reader/search-stream/site-results.jsx
  client/reader/search-stream/style.scss
Labels: [Status] Needs Review, Reader

#71025 Change default theme from zoologist to twentytwentythree
  client/lib/signup/site-type.js
Labels: [Type] Enhancement, Lego Maintenance

#76460 Social Previews: Add Tumblr preview as shared by others
  packages/social-previews/src/tumblr-preview/full-preview.tsx
  packages/social-previews/src/tumblr-preview/index.tsx
  packages/social-previews/src/tumblr-preview/link-preview.tsx
  packages/social-previews/src/tumblr-preview/post-preview.tsx
  packages/social-previews/src/tumblr-preview/post/header/index.tsx
  packages/social-previews/src/tumblr-preview/styles.scss
  packages/social-previews/src/tumblr-preview/variables.scss
Labels: [Status] Needs Review, [Size] S, Social Previews
