Repository Automattic/wp-calypso, pull requests merged in 2023-03, with the labels that each got.

#73912 Happy Blocks: fix missing index in build
  apps/happy-blocks/package.json
  apps/happy-blocks/webpack.config.js
Labels: [Status] Needs Review

#73751 Add skipCta params after checkout page to kick off migration
  client/blocks/importer/wordpress/import-everything/confirm.tsx
  client/blocks/importer/wordpress/import-everything/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer/hooks/use-step-navigator.ts
Labels: [Status] Needs Review, Migration Plugin

#73592 Stats: Hide StatsDetailsNavigation on the post details page for Odyssey Stats
  client/my-sites/stats/post-detail-highlights-section/index.tsx
Labels: Stats, [Status] Ready to Merge, Odyssey Stats

#73771 Stats: Refactor the All-time highlights section layouts with ComponentSwapper
  client/my-sites/stats/all-time-highlights-section/index.tsx
  client/my-sites/stats/all-time-highlights-section/style.scss
  client/my-sites/stats/modernized-layout-styles.scss
  client/my-sites/stats/post-trends/style.scss
  packages/components/src/component-swapper/index.tsx
  packages/components/src/post-stats-card/style.scss
Labels: Stats, [Status] Needs Review

#73916 GitHub Integration: Refactor card heading into shared component
  client/my-sites/hosting/github/deployment-card/index.tsx
  client/my-sites/hosting/github/github-authorize-card/index.tsx
  client/my-sites/hosting/github/github-card-heading/index.tsx
  client/my-sites/hosting/github/github-connect-card/index.tsx
  client/my-sites/hosting/github/github-placeholder-card/index.tsx
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
Labels: [Status] Needs Review, Reviewer Can Merge

#73863 Jetpack Pro Dashboard: implement site expanded content & add insights data for small screens
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-card/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-card/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/insights-stats.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/test/utils.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/utils.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#73752 Move features as required
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/types.ts
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#73918 GitHub Integration: Add beta badge to GitHub feature in hosting config
  client/my-sites/hosting/github/github-card-heading/index.tsx
  client/my-sites/hosting/github/github-card-heading/style.scss
Labels: [Status] Needs Review, Reviewer Can Merge

#73923 Theme Showcase: Theme Detail page UI improvements
  client/my-sites/theme/main.jsx
  client/my-sites/theme/style.scss
  client/my-sites/theme/theme-style-variations/index.tsx
  client/my-sites/theme/theme-style-variations/style.scss
Labels: [Type] Enhancement, [Status] Needs Review, Theme Showcase

#73762 Upsells: Hide second upsell in /themes if fewer than 6 rows
  client/components/themes-list/index.jsx
Labels: [Status] Needs Review

#73921 Jetpack Pro Dashboard: fix site table row styles when there is a site with an error.
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-table-row/style.scss
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#73878 Import focus flow: skip `from` query param if it's a falsy value
  client/landing/stepper/declarative-flow/import-flow.ts
Labels: [Status] Needs Review, Migration Plugin

#73929 Fix Jetpack version incompatible check only for Jetpack sites
  client/my-sites/importer/section-import.jsx
Labels: [Status] Needs Review

#73639 Site Assembler: Handle select color variation
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-assembler-container.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-color-palettes.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/with-global-styles-provider.tsx
  client/landing/stepper/declarative-flow/internals/types.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  packages/block-renderer/package.json
  packages/block-renderer/src/components/block-renderer-container.tsx
  packages/block-renderer/src/components/block-renderer-context.tsx
  packages/block-renderer/src/components/block-renderer-provider.tsx
  packages/global-styles/src/components/color-palette-variations/index.tsx
  packages/global-styles/src/hooks/index.ts
  packages/global-styles/src/hooks/use-sync-global-styles.ts
  packages/global-styles/src/index.tsx
  yarn.lock
Labels: [Status] Needs Review

#73640 Site Assembler: Handle submit selected patterns with color variation
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  packages/data-stores/src/site/actions.ts
  packages/global-styles/src/hooks/index.ts
  packages/global-styles/src/hooks/use-sync-global-styles-user-config.ts
  packages/global-styles/src/index.tsx
Labels: [Status] Needs Review

#73848 WooExpress: Added trial upgrade confirmation mobile styles
  client/my-sites/plans/ecommerce-trial/upgrade-confirmation/index.tsx
  client/my-sites/plans/ecommerce-trial/upgrade-confirmation/style.scss
Labels: [Status] Needs Review, WooExpress

#73855 Staging Sites: Query for staging site attributes for use in UI
  client/data/sites/site-excerpt-constants.ts
  packages/data-stores/src/site/types.ts
Labels: [Status] Needs Review, Staging Sites i1

#73902 Plugin Details: Avoid the shrink of icon when the plugin title is too big
  client/my-sites/plugins/plugin-details-header/style.scss
Labels: [Status] Needs Review

#73805 Hosting Page Cards: make all icons 32px.
  client/my-sites/hosting/cache-card/index.js
  client/my-sites/hosting/restore-plan-software-card/index.js
  packages/material-design-icons/src/action/outline-autorenew-32px.svg
  packages/material-design-icons/src/navigation/outline-apps-32px.svg
  packages/material-design-icons/svg-sprite/material-icons.svg
Labels: [Status] Needs Review, [Type] Janitorial, Reviewer Can Merge, WPCOM + GitHub Integration i1

#73945 Developer UX: use start and end day for daterange in server logs
  client/my-sites/hosting/web-server-logs-card/index.js
Labels: [Status] Needs Review, Hosting Configuration, Developer UX i1

#73774 Developer UX: Use <DateRange> component for Web server logs
  client/components/date-range/index.js
  client/my-sites/hosting/web-server-logs-card/index.js
Labels: [Status] Needs Review, Reviewer Can Merge, Developer UX i1

#73947 Hosting Configuration: Add a missing period
  client/my-sites/hosting/cache-card/index.js
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting Configuration

#73943 Staging Sites: Add better loading and progress indicators
  client/my-sites/hosting/staging-site-card/index.js
Labels: [Status] Needs Review, Staging Sites i1

#73913 Blaze: Only query for page and posts in the Jetpack App
  client/my-sites/promote-post/main.tsx
Labels: [Status] Needs Review, Blaze, Jetpack App

#73910 Blaze: Update the Jetpack App webview to remove post-action-counts
  client/my-sites/post-type-list/post-action-counts/style.scss
Labels: [Status] Needs Review, Blaze, Jetpack App

#73897 Plugins: Update the popular list to search only on wporg data
  client/data/marketplace/use-es-query.ts
Labels: [Status] Needs Review, Marketplace, Marketplace Jetpack Search

#73909 Stats: Simplify module headings on insights page
  client/my-sites/stats/stats-reach/index.jsx
  client/my-sites/stats/stats-shares/index.jsx
Labels: Stats, [Status] Needs Review

#73963 Sidebar Upsell Flow: Fix styles when already searching a domain
  client/my-sites/domains/domain-search/index.jsx
Labels: [Status] Needs Review

#73959 happy-blocks: Fix filepath keys in translation-manifest
  apps/happy-blocks/bin/build-translations-manifest.js
Labels: [Status] Needs Review, i18n

#73825 Import onboarding flow: fix issue with flickering screens
  client/blocks/importer/wordpress/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer/index.tsx
Labels: [Status] Needs Review, Migration Plugin

#73911 Stats: Apply new styling to the WordAds earnings table
  client/my-sites/earn/main.jsx
  client/my-sites/stats/stats-module/style.scss
  client/my-sites/stats/wordads/earnings.jsx
  client/my-sites/stats/wordads/earnings.scss
  client/my-sites/stats/wordads/highlights-section.jsx
  client/my-sites/stats/wordads/highlights-section.scss
  client/my-sites/stats/wordads/index.jsx
  client/my-sites/stats/wordads/style.scss
  packages/components/src/highlight-cards/highlight-card-simple.jsx
  packages/components/src/index.ts
Labels: Stats, [Status] Needs Review

#73781 Launchpad: Stop duplicate calypso_signup_start call for newsletter flow
  client/signup/main.jsx
  packages/onboarding/src/utils/flows.ts
Labels: [Status] Needs Review, Launchpad

#73967 Launchpad: Fix URL state for Celebrate Launch Modal
  client/my-sites/customer-home/components/celebrate-launch-modal.jsx
Labels: [Status] Needs Review, Launchpad

#73969 [Offer jetpack complete]: CSS fix CTA buttons breaking to new line (in other languages)
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/components/cta-buttons/style.scss
Labels: Jetpack, [Status] Needs Review, Pricing/plans Page, post-connection

#73964 Launchpad: Change Back Button Text & URL for Domain Flow
  client/my-sites/domains/components/domain-and-plan-package/navigation/index.jsx
  client/my-sites/domains/domain-search/index.jsx
Labels: [Status] Needs Review, Launchpad

#73800 Update tour events to include `editor_type`
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/get-editor-type.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/test/tour-steps.test.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-steps.tsx
Labels: [Status] Needs Review

#73971 GitHub Integration: Translate description and proper casing
  client/my-sites/hosting/github/github-authorize-card/index.tsx
  client/my-sites/hosting/github/github-connect-card/index.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, WPCOM + GitHub Integration i1

#73974 GitHub Integration: Add a skeleton screen loading placeholder
  client/my-sites/hosting/github/github-placeholder-card/index.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, WPCOM + GitHub Integration i1

#73936 Pricing page: fix pricing billing text alignment issue.
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/item-price/style.scss
  client/my-sites/plans/jetpack-plans/product-store/item-price/style.scss
Labels: [Status] Needs Review, Jetpack Cloud

#73981 GitHub Integration: Match GitHub beta badge style with FSE's beta badge
  client/my-sites/hosting/github/github-card-heading/index.tsx
  client/my-sites/hosting/github/github-card-heading/style.scss
Labels: [Status] Needs Review, Reviewer Can Merge, WPCOM + GitHub Integration i1

#73972 GitHub Integration: Tweak copy in notices
  client/my-sites/hosting/github/deployment-card/index.tsx
  client/my-sites/hosting/github/github-connect-card/index.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, WPCOM + GitHub Integration i1

#73954 LNB: Set the request for the free domain suggestion to only return one w.link subdomain
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/domain-form-control.tsx
Labels: [Status] Needs Review

#73926 Plan page: Fix shifting comparison UI page.
  client/jetpack-cloud/sections/comparison/header/style.scss
  client/jetpack-cloud/sections/comparison/style.scss
  client/jetpack-cloud/sections/comparison/table/style.scss
Labels: [Status] Needs Review, Jetpack Cloud

#73949 Improve the audience list to divide in different targets
  client/data/promote-post/use-promote-post-campaigns-query.ts
  client/my-sites/promote-post/components/audience-block/index.tsx
  client/my-sites/promote-post/components/campaign-item/index.tsx
  client/my-sites/promote-post/utils/index.ts
Labels: [Status] Needs Review

#73824 Developer UX: Add Hosting Configuration item with upsell info
  client/my-sites/hosting/web-server-logs-card/index.js
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
  packages/components/src/index.ts
  packages/components/src/upsell-menu-group/index.tsx
Labels: [Status] Needs Review, Sites Management Page, Developer UX i1

#73987 Happyblocks: Fix incorrect block name
  apps/happy-blocks/block-library/pricing-plans/block.json
  apps/happy-blocks/block-library/pricing-plans/rtl/block.json
Labels: [Status] Needs Review

#73091 Site Assembler: Support font variations
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-font-pairings.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-main.tsx
  packages/global-styles/src/components/font-pairing-variations/font-families-loader.tsx
  packages/global-styles/src/components/font-pairing-variations/index.tsx
  packages/global-styles/src/components/font-pairing-variations/preview.tsx
  packages/global-styles/src/components/font-pairing-variations/style.scss
  packages/global-styles/src/components/index.ts
  packages/global-styles/src/hooks/index.ts
  packages/global-styles/src/hooks/use-font-pairing-variations.ts
  packages/global-styles/src/types.ts
Labels: [Status] Needs Review

#73847 My Home Upsell: use new domain upsell flow
  client/my-sites/customer-home/cards/features/domain-upsell/index.jsx
  client/my-sites/customer-home/cards/features/domain-upsell/test/index.jsx
  client/my-sites/domains/domain-search/index.jsx
  client/my-sites/plan-features-2023-grid/index.tsx
  client/my-sites/plan-features/index.jsx
  client/my-sites/plans-features-main/index.jsx
  client/my-sites/plans-features-main/plan-type-selector.tsx
  client/my-sites/plans-features-main/style.scss
  client/my-sites/plans/components/domain-upsell-dialog/style.scss
  client/my-sites/plans/main.jsx
  client/my-sites/plans/style.scss
  packages/calypso-e2e/src/lib/pages/cart-checkout-page.ts
  packages/calypso-e2e/src/lib/pages/my-home-page.ts
  packages/calypso-e2e/src/lib/pages/plans-page.ts
  test/e2e/specs/domain-upsell/domain-upsell__my-home.ts
Labels: [Status] Needs Review

#73989 Prevent calypso_signup_design_scrolled_to_end from being tracked if designs have not been loaded
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/test/unified-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
Labels: [Status] Needs Review, Design Picker

#73882 HelpCenter: Add HelpCenter to the new WPSupport page
  apps/editing-toolkit/editing-toolkit-plugin/help-center/class-help-center.php
  packages/help-center/src/components/help-center-inline-chat.tsx
Labels: [Status] Needs Review, Help Center, wpsupport3

#73966 [Offer jetpack complete]: cleanup and some tests
  client/my-sites/plans/jetpack-plans/controller.tsx
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/index.tsx
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/test/index.js
Labels: Jetpack, [Status] Ready to Merge, Tests

#73988 Hosting Configuration: Add tests for web-server-logs card
  client/my-sites/hosting/web-server-logs-card/index.js
  client/my-sites/hosting/web-server-logs-card/test/index.js
  packages/components/src/forms/form-input-validation/index.tsx
Labels: [Status] Needs Review, Developer UX i1

#73999 Remove/rollback last changes on help center for wpsupport theme
  apps/editing-toolkit/editing-toolkit-plugin/help-center/class-help-center.php
  packages/help-center/src/components/help-center-inline-chat.tsx
Labels: [Status] Needs Review, Help Center, wpsupport3

#73984 Launchpad: Hide domain upgrade badge when domain upsell task exists
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/tasks.tsx
Labels: [Status] Needs Review, Launchpad

#73991 TSC: Fix unsupported TS syntax in `getTransformedStreamItems` selector
  client/state/reader/streams/selectors/get-reader-stream-transformed-items.ts
  packages/tree-select/src/index.ts
Labels: [Type] Bug, Framework, [Status] Needs Review, [Type] Tooling

#73973 [Offer Jetpack Complete]: Switch Feature Flag to True
  config/production.json
Labels: Jetpack, [Status] Needs Review, Releases

#73982 Hosting Configuration: add ssh loading state and improve scrollToAnchor
  client/components/scroll-to-anchor-on-mount/index.tsx
  client/my-sites/hosting/main.js
  client/my-sites/hosting/sftp-card/index.js
  client/my-sites/hosting/sftp-card/sftp-card-loading-placeholder.tsx
  client/state/hosting/reducer.js
  client/state/hosting/test/reducer.js
  client/state/selectors/get-atomic-hosting-is-loading-sftp-data.js
  client/state/selectors/get-atomic-hosting-is-loading-sftp-users.js
  client/state/selectors/get-atomic-hosting-is-loading-ssh-access.js
Labels: [Status] Needs Review, Hosting Configuration, Developer UX i1

#73514 Odyssey Stats: Add a Jetpack upsell section to the traffic page
  client/my-sites/stats/jetpack-upsell-section/index.tsx
  client/my-sites/stats/jetpack-upsell-section/use-purchased-products.tsx
  client/my-sites/stats/site.jsx
  packages/components/src/index.ts
  packages/components/src/jetpack-upsell-card/index.tsx
  packages/components/src/jetpack-upsell-card/stories/index.stories.tsx
  packages/components/src/jetpack-upsell-card/style.scss
  packages/components/src/jetpack-upsell-section/stories/index.stories.tsx
  packages/components/src/jetpack-upsell-section/style.scss
Labels: Stats, [Status] Needs Review, Odyssey Stats

#74010 E2E: fix issues with FSE: Smoke Test introduced with new Gutenberg version
  packages/calypso-e2e/src/lib/pages/full-site-editor-page.ts
  test/e2e/specs/fse/fse__temp-smoke-test.ts
Labels: [Status] Reviewer Approved

#74006 Launchpad: Refactor query param retrieval for launchpad related logic
  client/my-sites/customer-home/controller.jsx
  client/my-sites/customer-home/main.jsx
Labels: [Status] Needs Review

#73904 Launchpad: Add Next Steps button at the end of domain flow
  client/my-sites/checkout/checkout-thank-you/domains/domain-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-registration.tsx
  client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/index.tsx
Labels: [Status] Needs Review, Launchpad

#73919 BackupRetention: Add purchase storage and update retention flow
  client/components/backup-retention-management/index.tsx
  client/components/backup-retention-management/test/index.jsx
  client/jetpack-cloud/sections/settings/controller.tsx
Labels: [Status] Ready to Merge, [Status] String Freeze, Jetpack Cloud, Jetpack Backup

#73915 Odyssey: hide mini carousel
  client/my-sites/stats/mini-carousel/index.jsx
  client/my-sites/stats/site.jsx
Labels: Stats, [Status] Needs Review, Odyssey Stats

#74026 Gutenberg: Avoid redirecting to home from within the iframe
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Labels: [Status] Needs Review

#73983 Theme Showcase: Remove style variation collapsibility
  client/my-sites/theme/theme-style-variations/index.tsx
  client/my-sites/theme/theme-style-variations/style.scss
Labels: [Type] Enhancement, [Status] Needs Review, Theme Showcase

#74030 Site Assembler: Update spellings of copies
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-color-palettes.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-font-pairings.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-main.tsx
Labels: [Status] Needs Review

#74041 Gardening: add Kitkat notification mechanism
  .github/workflows/gardening.yml
Labels: [Status] Needs Review, [Type] Janitorial

#74024 Staging Sites: Fix icon styling on smaller screens
  client/my-sites/hosting/style.scss
Labels: [Type] Bug, [Status] Needs Review, Reviewer Can Merge, Staging Sites i1

#74043 StatModuleFollowers: Wrap the time period strings for translation
  client/my-sites/stats/stats-followers/index.jsx
Labels: [Status] Needs Review

#73990 StoreStatsOrdersChart: Wrap the "since" label for translation
  client/my-sites/store/app/store-stats/store-stats-orders-chart/index.js
Labels: [Status] Needs Review

#73993 Social: Remove feature flag.
  client/my-sites/plans/jetpack-plans/product-lightbox/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/all-items.tsx
  config/development.json
  config/horizon.json
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
Labels: [Status] In Progress, [Status] Needs Review

#73710 Social: Make the advanced product as the default one for social.
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
  packages/calypso-products/src/constants/jetpack.ts
Labels: [Status] Needs Review

#74037 Site Assembler: Introduce feature flag to use inline styles
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-assembler-container.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
  packages/block-renderer/src/components/block-renderer-provider.tsx
  packages/block-renderer/src/hooks/use-block-renderer-settings.ts
Labels: [Status] Needs Review

#73994 Design Picker: Add pattern based virtual themes under a virtual-themes/onboarding flag
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  config/development.json
  packages/data-stores/src/starter-designs-queries/use-starter-designs-query.ts
  packages/design-picker/src/components/unified-design-picker.tsx
  packages/design-picker/src/utils/available-designs.ts
Labels: [Status] Needs Review

#73690 Plugin Bundle Flow: Redirect back to the activated theme page
  client/landing/stepper/declarative-flow/plugin-bundle-flow.ts
Labels: [Status] Needs Review

#74029 Theme Showcase: Add global style upgrade modal in the Theme Detail page
  client/my-sites/theme/main.jsx
Labels: [Type] Enhancement, [Status] Needs Review, Theme Showcase

#74045 i18n: Add context for Jetpack `Security` strings
  client/jetpack-cloud/sections/comparison/table/useComparisonData.tsx
  client/jetpack-cloud/sections/comparison/table/useProductsToCompare.ts
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/index.tsx
  packages/calypso-products/src/plans-list.tsx
  packages/components/src/jetpack-upsell-card/index.tsx
  packages/data-stores/src/contextual-help/contextual-help.tsx
Labels: [Status] Needs Review, i18n

#73901 Theme Showcase: Update install upsell for commerce trial sites
  client/my-sites/themes/theme-upload/index.jsx
Labels: [Status] Needs Review, Woo Express

#73898 Theme Showcase: Update upsell to reflect WooExpress trial changes
  client/my-sites/themes/single-site-jetpack.jsx
Labels: [Status] Needs Review, Woo Express

#74033 Site Assembler: Fix the padding and background of the preview
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-large-preview.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-large-preview.tsx
  packages/block-renderer/src/components/block-renderer-provider.tsx
  packages/global-styles/src/index.tsx
Labels: [Status] Needs Review

#73965 Fetch the TLDs for domain filters from endpoint
  client/components/domains/register-domain-step/index.jsx
Labels: [Status] Needs Review

#73797 BackupRetention: Add retention setting in Calypso Blue
  client/components/advanced-credentials/index.tsx
  client/components/advanced-credentials/style.scss
  client/components/backup-retention-management/info-tooltip/style.scss
  client/components/backup-retention-management/style.scss
  client/components/backup-storage-space/hooks.tsx
  client/components/backup-storage-space/test/hooks.js
  client/jetpack-cloud/sections/settings/controller.tsx
  client/my-sites/site-settings/settings-jetpack/main.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Jetpack Backup

#74023 Hosting Configuration: Use skeleton screen for 'Web server settings'
  client/my-sites/hosting/web-server-settings-card/index.js
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting Configuration

#74021 Sites Management Page: Use `react-intersection-observer` for `inView`
  client/package.json
  client/sites-dashboard/components/sites-grid-item.tsx
  client/sites-dashboard/components/sites-table-row.tsx
  package.json
  yarn.lock
Labels: Sites, [Status] Needs Review

#74046 Developer UX: refactor submenu events and add upsell events
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, Sites Management Page, Developer UX i1

#74061 Developer UX: remove feature flag and deploy SMP submenu
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
  config/development.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Reviewer Can Merge

#73946 My Home Upsell: Show for yearly plans with different copy
  client/my-sites/customer-home/cards/features/domain-upsell/index.jsx
  client/my-sites/customer-home/cards/features/domain-upsell/test/index.jsx
  client/my-sites/domains/components/domain-and-plan-package/navigation/index.jsx
  client/my-sites/domains/domain-search/index.jsx
  test/e2e/specs/domain-upsell/domain-upsell__sidebar.ts
Labels: [Status] Needs Review

#74013 add tracking event on page render
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/index.tsx
Labels: Jetpack, [Status] Needs Review

#74028 Stats: Set "Stats" sidebar menu item as selected for the Store and Google My Business pages - Take 2
  client/my-sites/sidebar/utils.js
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#74018 Odyssey: remove dup query string on reload
  apps/odyssey-stats/src/app.jsx
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-email-detail/index.jsx
  client/my-sites/stats/test/utils.js
  client/my-sites/stats/utils.js
Labels: Stats, [Status] Needs Review, Reviewer Can Merge, Odyssey Stats

#74036 Odyssey: black segment controls all around
  apps/odyssey-stats/src/styles/wp-admin.scss
Labels: Stats, [Status] Needs Review, Reviewer Can Merge, Odyssey Stats

#74044 Stats: Refactoring summary page header
  client/my-sites/stats/stats-module/all-time-nav.jsx
  client/my-sites/stats/stats-module/index.jsx
  client/my-sites/stats/stats-module/summary-nav.scss
  client/my-sites/stats/summary/index.jsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#74047 Stepper Framework: Show WordPress logo instead of white screen when a step is loading
  client/landing/stepper/declarative-flow/internals/components/stepper-loader/index.tsx
  client/landing/stepper/declarative-flow/internals/components/stepper-loader/style.scss
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-assembler-container.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/with-global-styles-provider.tsx
  packages/block-renderer/src/components/block-renderer-provider.tsx
  packages/global-styles/src/components/global-styles-provider/index.tsx
Labels: [Status] Needs Review

#74039 Theme Showcase: Scale out web preview to display desktop view in the Theme Detail page
  client/my-sites/theme/style.scss
Labels: [Type] Enhancement, [Status] Needs Review, Theme Showcase

#74050 Site Assembler: Remove client-side-render feature flag
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/constants.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/lazy.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-assembler-preview.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-assembler-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-preview-auto-height.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-footer.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-header.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-pattern-list.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/utils.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  client/landing/stepper/declarative-flow/with-theme-assembler-flow.ts
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#74087 Stepper Framework: Fix WordPressLogo not found
  client/landing/stepper/declarative-flow/internals/index.tsx
Labels: [Status] Needs Review

#74051 Check for expired eCommerce trials in the Marketplace upgrade nudge
  client/my-sites/plugins/plugins-discovery-page/upgrade-nudge.jsx
Labels: [Status] Needs Review, Woo Express

#74086 Theme Showcase: Remove style variation upsell banner in the Theme Detail page
  client/my-sites/theme/main.jsx
Labels: [Type] Enhancement, [Status] Needs Review, Theme Showcase

#73582 Plans 2023: Featured badge for current plan
  client/my-sites/plan-features-2023-grid/hooks/use-highlight-adjacency-matrix.ts
  client/my-sites/plan-features-2023-grid/hooks/use-highlight-label.ts
  client/my-sites/plan-features-2023-grid/index.tsx
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  client/my-sites/plan-features-2023-grid/style.scss
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#73756 Site Assembler: Add global styles gating
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-global-styles-upgrade-modal.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-main.tsx
  client/lib/analytics/tracks.js
Labels: [Status] Needs Review

#74000 Plugins: Use category on tags search when tags are not found
  client/data/marketplace/search-api.ts
Labels: [Status] Needs Review

#74101 Design picker: Updated tracking for pattern based virtual themes in onboarding
  client/landing/stepper/declarative-flow/internals/analytics/record-design.ts
Labels: [Status] Needs Review

#73962 Add domain upsell to profile page
  client/me/profile/index.jsx
  client/my-sites/customer-home/cards/features/domain-upsell/index.jsx
  client/my-sites/customer-home/cards/features/domain-upsell/style.scss
  client/my-sites/customer-home/cards/features/domain-upsell/test/index.jsx
Labels: [Status] Needs Review

#73896 Payment Methods: Support address field for tax information
  client/me/purchases/manage-purchase/payment-method-selector/assignment-processor-functions.ts
  client/me/purchases/manage-purchase/payment-method-selector/stored-payment-method-api.ts
  client/my-sites/checkout/composite-checkout/components/payment-method-tax-info/payment-method-tax-info.tsx
  client/my-sites/checkout/composite-checkout/components/payment-method-tax-info/types.ts
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/contact-fields.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-pay-button.tsx
  client/my-sites/checkout/composite-checkout/payment-methods/paypal.tsx
Labels: [Status] Needs Review

#74017 Add context when adding global-stylesstickers
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-global-styles/index.php
Labels: [Status] Needs Review, Global Styles

#74082 Launchpad: add onboarding signup goals default site intent v3
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  packages/data-stores/src/onboard/reducer.ts
  test/e2e/specs/plans/plans__signup-business.ts
Labels: [Status] Needs Review, Launchpad

#73953 Plugins: Redirect to /plans when on the commerce trial
  client/my-sites/plugins/controller.js
  client/my-sites/plugins/index.web.js
Labels: [Status] Needs Review, Plugins, Woo Express

#74109 Interim update to ecommerce trial features
  client/assets/images/plans/wpcom/ecommerce-trial/google-analytics.svg
  client/assets/images/plans/wpcom/ecommerce-trial/payment-card-checked.svg
  client/my-sites/plans/current-plan/ecommerce-trial/index.tsx
Labels: Plans, [Status] Needs Review, Woo Express

#74090 Add Tracks event for CTA clicks in eCommerce trial Plans page
  client/my-sites/plans/ecommerce-trial/index.tsx
Labels: Plans, [Status] Needs Review, Woo Express

#74064 Add links and tracking to eCommerce trial post-purchase screen
  client/my-sites/plans/ecommerce-trial/controller.jsx
  client/my-sites/plans/ecommerce-trial/upgrade-confirmation/confirmation-task/index.tsx
  client/my-sites/plans/ecommerce-trial/upgrade-confirmation/confirmation-task/style.scss
  client/my-sites/plans/ecommerce-trial/upgrade-confirmation/confirmation-tasks.ts
  client/my-sites/plans/ecommerce-trial/upgrade-confirmation/index.tsx
  client/my-sites/plans/index.js
Labels: [Status] Needs Review, Woo Express

#74093 Ensure that upgrades from the trial Plans pages show post-purchase UI
  client/lib/ecommerce-trial/get-ecommerce-trial-checkout-url.ts
  client/my-sites/plans/current-plan/ecommerce-trial/index.tsx
  client/my-sites/plans/ecommerce-trial/index.tsx
Labels: Plans, [Status] Needs Review, Plans: eCommerce, Woo Express

#74129 Switch to separate flags for wooexpress medium and small
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Woo Express

#74084 Stats: fix chart flickering
  client/components/chart/bar.jsx
  client/components/chart/index.jsx
Labels: Stats, [Status] Needs Review

#73702 Make reader tag pages public
  client/blocks/follow-button/index.jsx
  client/blocks/like-button/button.jsx
  client/blocks/reader-post-options-menu/reader-post-ellipsis-menu.jsx
  client/components/data/sync-reader-follows/index.js
  client/controller/index.node.js
  client/controller/index.web.js
  client/layout/logged-out.jsx
  client/lib/paths/index.js
  client/reader/controller.js
  client/reader/full-post/index.js
  client/reader/index.js
  client/reader/tag-stream/index.js
  client/reader/tag-stream/main.jsx
  client/reader/utils.js
  client/sections.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  packages/wpcom-template-parts/src/universal-header-navigation/style.scss
Labels: [Status] Needs Review

#74020 Launchpad: Update task-helpers to use addQueryArgs
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
Labels: [Status] In Progress, Launchpad

#73996 Contact form/Help-Center: track q&a results display
  client/me/help/help-contact-form/index.jsx
  packages/help-center/src/components/help-center-sibyl-articles.tsx
Labels: [Status] Needs Review, Help, Help Center

#74100 happy-blocks: Add missing slash for translations filepath
  apps/happy-blocks/block-library/pricing-plans/index.php
Labels: [Type] Bug, [Status] Needs Review

#73931 Subscription Management: Create `subscription-manager` package
  client/my-sites/subscriptions/index.tsx
  client/package.json
  packages/subscription-manager/README.md
  packages/subscription-manager/package.json
  packages/subscription-manager/src/components/SubscriptionManagerContainer/SubscriptionManagerContainer.tsx
  packages/subscription-manager/src/components/SubscriptionManagerContainer/index.ts
  packages/subscription-manager/src/components/index.d.ts
  packages/subscription-manager/src/index.tsx
  packages/subscription-manager/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review, Subscription Management

#74104 Site Assembler: Sidebar revamp adjustment
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/navigator-header/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/navigator-header/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-layout.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-footer.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-header.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-homepage.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-main-deprecated.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-main.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-pattern-list.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/style.scss
Labels: [Status] Needs Review

#74156 Subscription Management: Enable the path for external users
  client/sections.js
Labels: [Status] Needs Review, Subscription Management, [SM] External Portal

#74004 Sensei Tailored Flow: Don't install WooCommerce, save selected purposes
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-launch/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-launch/use-atomic-site-checklist.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-launch/use-sub-steps.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-purpose/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-purpose/purposes.ts
Labels: [Status] Needs Review

#73507 Update Connect Domain screens to allow for Domain Connect
  client/components/domains/connect-domain-step/connect-domain-step-dc-start.jsx
  client/components/domains/connect-domain-step/connect-domain-step-done.jsx
  client/components/domains/connect-domain-step/connect-domain-step-switch-setup-info-link.jsx
  client/components/domains/connect-domain-step/connect-domain-steps.jsx
  client/components/domains/connect-domain-step/constants.ts
  client/components/domains/connect-domain-step/index.jsx
  client/components/domains/connect-domain-step/page-definitions.js
  client/components/domains/connect-domain-step/style.scss
  client/components/domains/use-my-domain/utilities/connect-domain-action.js
  client/lib/domains/resolve-domain-status.tsx
  client/my-sites/domains/controller.jsx
Labels: [Status] Needs Review

#73607 localizeUrl: Allow localization of Spanish Go blog post URLs
  packages/i18n-utils/src/localize-url.tsx
  packages/i18n-utils/src/test/localize-url.js
Labels: [Status] Needs Review

#73948 My home upsell: Show the upsell to monthly paid plans without a domain
  client/my-sites/customer-home/cards/features/domain-upsell/index.jsx
  client/my-sites/plans/main.jsx
  client/my-sites/plans/style.scss
  packages/calypso-e2e/src/lib/pages/plans-page.ts
  test/e2e/specs/domain-upsell/domain-upsell__my-home.ts
Labels: [Status] Needs Review, [Status] String Freeze

#73126 Updating sharing button mockup styles in marketing section
  client/my-sites/marketing/style.scss
Labels: Sharing

#74003 Fix overall budget and 0 day campaign duration string
  client/my-sites/promote-post/components/campaign-item/index.tsx
  client/my-sites/promote-post/utils/index.ts
Labels: [Status] Needs Review

#74169 WooExpress: Redirect `/plugins` routes to `/plans` on trial sites
  client/my-sites/plugins/controller.js
  client/my-sites/plugins/index.web.js
Labels: [Status] Needs Review, Plugins, Woo Express

#74069 My home upsell: Add dismiss button
  client/my-sites/customer-home/cards/features/domain-upsell/index.jsx
  client/my-sites/customer-home/cards/features/domain-upsell/style.scss
  client/my-sites/customer-home/cards/features/domain-upsell/test/index.jsx
Labels: [Status] Needs Review

#74168 Launchpad: Remove unused Sensei code
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/launchpad-site-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/tasks.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/translations.tsx
Labels: [Status] Needs Review

#73920 GitHub Deploy: show a message when no branches are returned; auto refresh on refocus
  client/my-sites/hosting/github/github-connect-card/search-branches.tsx
  client/my-sites/hosting/github/github-connect-card/use-github-branches-query.ts
Labels: [Status] Needs Review, Reviewer Can Merge, WPCOM + GitHub Integration i1

#74178 Site Editor: fix template sidebar navigation
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Labels: [Type] Bug, Editor, [Status] Needs Review, caused-by-gutenberg-upgrade

#74139 Update domain upsell globe icon
  client/components/domains/domain-upsell-callout/index.jsx
Labels: [Status] Needs Review

#74085 Theme Showcase: Add global style upgrade modal in the theme preview
  client/my-sites/theme/main.jsx
  client/my-sites/themes/theme-preview.jsx
Labels: [Type] Enhancement, [Status] Needs Review, Theme Showcase

#74150 Plans 2023: Fix RTL styling issues and enable for all locales
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  client/my-sites/plan-features-2023-grid/style.scss
  packages/calypso-products/src/plans-utilities.ts
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#73980 fix: tweaked the duration and font of the wooexpress setup messages
  client/assets/images/onboarding/woo-purple-heart.png
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/assign-trial-plan/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/hooks/types.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/hooks/use-processing-loading-messages.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-creation-step/index.tsx
Labels: [Status] Needs Review

#74190 Site Assembler: Fix issues related to action bar and scrollbar
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/style.scss
Labels: [Status] Needs Review

#74170 Update plugin slug for Sensei Pro in the marketplace
  client/my-sites/plugins/categories/use-categories.tsx
Labels: [Status] Needs Review

#74173 Task: Updated links from the trial My Plan page to Woo Express
  client/my-sites/plans/current-plan/ecommerce-trial/index.tsx
Labels: [Status] Needs Review

#74198 Contact form: change the query sent to the Q&A endpoint
  client/me/help/help-contact-form/index.jsx
Labels: [Status] Needs Review

#74197 Staging Sites: Add staging badge to SMP and site switcher
  client/blocks/site/index.jsx
  client/sites-dashboard/components/sites-grid-item.tsx
  client/sites-dashboard/components/sites-staging-badge.tsx
  client/sites-dashboard/components/sites-table-row.tsx
  client/state/sites/constants.js
Labels: [Status] Needs Review, Sites Management Page, Staging Sites i1

#74133 Site editor & site preview domain upsell: disable for p2s
  client/components/domains/domain-upsell-callout/index.jsx
  client/components/domains/domain-upsell-callout/test/index.js
Labels: [Status] Needs Review

#74179 Checkout: Move extra tax field tests to own file
  client/my-sites/checkout/composite-checkout/test/checkout-extra-tax-fields.tsx
  client/my-sites/checkout/composite-checkout/test/checkout-vat-form.tsx
Labels: [Status] Needs Review

#74161 Subscription Management: Add wpcom header for the external path
  client/layout/logged-out.jsx
  packages/wpcom-template-parts/src/types.ts
  packages/wpcom-template-parts/src/universal-header-navigation/index.tsx
  packages/wpcom-template-parts/src/universal-header-navigation/style.scss
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#74162 SMP: update submenu popover dimensions calculation
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
  packages/components/src/submenu-popover/index.tsx
Labels: [Status] Needs Review, Sites Management Page

#74177 Jetpack Connection: fix checkout flow for new WPCOM users
  client/controller/index.web.js
  client/my-sites/controller.js
Labels: [Status] Needs Review

#74140 Added WX Medium to plans-list.tsx
  packages/calypso-products/src/constants/wpcom.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/test/plan-lookups.js
Labels: [Status] Needs Review

#74171 Cancel Purchase: Make refund currency more accurate
  client/lib/purchases/assembler.ts
  client/lib/purchases/types.ts
  client/me/purchases/cancel-purchase/index.jsx
  client/state/purchases/test/selectors.js
Labels: Purchases

#74218 calypso-products: Remove Backup/Security (1TB) variants
  packages/calypso-products/src/constants/jetpack.ts
Labels: [Type] Enhancement, [Pri] High, [Status] Needs Review, Marketing, Jetpack Cloud, [Size] XS, Jetpack Backup

#74226 Domains List: Fix actions column styling
  client/my-sites/domains/domain-management/list/domain-row.scss
Labels: [Status] Needs Review, Domains

#74034 Jetpack Settings: Display notice for Atomic sites when navigating to settings/jetpack
  client/my-sites/site-settings/settings-jetpack/main.jsx
Labels: [Status] Needs Review
