Repository Automattic/wp-calypso, pull requests merged in 2023-04, with the labels that each got.

#74923 Make the newsletter badge more subtle
  client/my-sites/earn/memberships/products.jsx
Labels: [Status] Needs Review

#73787 Launchpad :: add newsletter steps (stripe/paid subscriptions)
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/tasks.tsx
  client/my-sites/earn/memberships/constants.js
  client/my-sites/earn/memberships/index.jsx
  client/state/memberships/product-list/actions.js
  packages/data-stores/src/site/types.ts
Labels: [Status] In Progress, [Status] Needs Review, Subscriptions, Earn

#73464 Tags page: Add top section of public tags page
  client/assets/images/reader/tags-bg.png
  client/components/global-notices/style.scss
  client/controller/index.node.js
  client/controller/index.web.js
  client/controller/shared.js
  client/layout/index.jsx
  client/layout/logged-out.jsx
  client/reader/style.scss
  client/reader/tags/controller.tsx
  client/reader/tags/index.node.js
  client/reader/tags/index.web.js
  client/reader/tags/main.tsx
  client/reader/tags/package.json
  client/reader/tags/style.scss
  client/reader/tags/trending-tags.tsx
  client/sections.js
  client/server/lib/performance-mark/index.ts
Labels: [Status] Needs Review

#75200 Logging: Make `/site-logs` available to all users
  client/my-sites/site-logs/controller.tsx
  client/my-sites/site-logs/index.ts
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Reviewer Can Merge, WoA Logging i1

#75024 Jetpack Pro Dashboard: add track events to the expandable block changes
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-card/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/backup-storage.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/boost-site-performance.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/insights-stats.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-table/index.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud, Reviewer Can Merge, [Status] Needs Privacy Updates

#75169 Themes: Avoid duplicate themes.
  client/components/themes-list/index.jsx
Labels: [Status] Needs Review

#75171 Fix: Complete card mentioning Basic plan instead of Advanced
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-included-product-description-map.tsx
Labels: [Status] Needs Review

#75126 Staging Sites: Ensure users can't transfer domain to a staging site
  client/my-sites/domains/domain-management/transfer/transfer-to-other-site/transfer-domain-to-other-site.tsx
  client/my-sites/sites/index.jsx
Labels: [Status] Needs Review, Staging Sites i1

#75087 Marketplace Thank You: Isolate logic for atomic transfer to use it for plugins or themes
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/marketplace/use-atomic-transfer.tsx
  client/my-sites/checkout/checkout-thank-you/marketplace/use-plugins-thank-you-data.tsx
  client/my-sites/checkout/checkout-thank-you/marketplace/use-themes-thank-you-data.tsx
  client/state/themes/selectors/is-externally-managed-theme.tsx
Labels: [Status] Needs Review

#74725 Redirect from cart to marketplace thank you page
  client/my-sites/checkout/get-thank-you-page-url/index.ts
  client/my-sites/checkout/get-thank-you-page-url/test/get-thank-you-page-url.ts
  client/state/themes/actions/add-external-managed-theme-to-cart.tsx
  packages/shopping-cart/src/types.ts
Labels: [Status] Needs Review, DO NOT MERGE

#74848 Marketplace thank you: Update progress bar steps for each product type
  client/components/thank-you/types.ts
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/marketplace/use-plugins-thank-you-data.tsx
  client/my-sites/checkout/checkout-thank-you/marketplace/use-thank-you-steps.tsx
  client/my-sites/checkout/checkout-thank-you/marketplace/use-themes-thank-you-data.tsx
Labels: [Status] Needs Review

#75128 Virtual themes i1: Remove A/B test
  client/landing/stepper/declarative-flow/internals/analytics/record-design.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  packages/data-stores/src/starter-designs-queries/use-starter-designs-query.ts
  packages/design-picker/src/components/style-variation-badges/index.tsx
  packages/design-picker/src/components/unified-design-picker.tsx
  packages/design-picker/src/types.ts
Labels: [Status] Needs Review, Design Picker

#75228 Staging sites: update error text
  client/my-sites/hosting/staging-site-card/index.js
Labels: Hosting Configuration, Staging Sites i1

#75229 Woo Express: Added custom labels to WX Plans CtA
  client/my-sites/plan-features-2023-grid/hooks/use-highlight-label.ts
  client/my-sites/plan-features-2023-grid/index.tsx
  packages/calypso-products/src/main.ts
Labels: [Status] Needs Review, Woo Express

#75232 Woo Express: Added interval toggle to Woo Express plans
  client/my-sites/plans/ecommerce-trial/index.tsx
  client/my-sites/plans/ecommerce-trial/wooexpress-plans/index.tsx
  client/my-sites/plans/ecommerce-trial/wooexpress-plans/style.scss
Labels: [Status] Needs Review, Woo Express

#74901 Support: Update live chat closure times for Easter 2023
  client/me/concierge/shared/primary-header.js
  client/me/help/help-contact/index.jsx
  packages/help-center/src/components/help-center-contact-page.tsx
Labels: [Status] Needs Review, Support, Help Center

#75235 Woo Express: Added Woo Express styles to CtA
  client/my-sites/plan-features-2023-grid/index.tsx
  client/my-sites/plan-features-2023-grid/style.scss
  packages/calypso-products/src/main.ts
Labels: [Status] Needs Review, Woo Express

#75202 Launchpad: Update build flow set up site task copy
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
Labels: [Status] Needs Review, Launchpad

#75242 Revert "Staging Sites: Enable for everyone"
  client/my-sites/hosting/main.js
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
  config/development.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Staging Sites i1

#75066 Stats: Add simple empty state messaging.
  client/my-sites/stats/subscribers-section/index.jsx
  client/my-sites/stats/subscribers-section/style.scss
Labels: Stats, [Status] Needs Review

#75145 Launchpad: Update useQuery implementation for fetching data
  client/data/sites/use-launchpad.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx
Labels: [Status] Needs Review

#75191 Add Akismet API key to thank you page
  client/my-sites/checkout/checkout-thank-you/akismet-checkout-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/style.scss
  client/my-sites/checkout/index.js
Labels: [Status] Needs Review

#74996 Shopping Cart: Remove create_new_blog property
  client/my-sites/checkout/composite-checkout/hooks/use-create-payment-complete-callback.tsx
  client/my-sites/checkout/composite-checkout/lib/create-wpcom-account-before-transaction.ts
  client/my-sites/checkout/composite-checkout/lib/translate-cart.ts
  client/my-sites/checkout/composite-checkout/test/existing-card-processor.ts
  client/my-sites/checkout/composite-checkout/test/free-purchase-processor.ts
  client/my-sites/checkout/composite-checkout/test/generic-redirect-processor.ts
  client/my-sites/checkout/composite-checkout/test/multi-partner-card-processor.tsx
  client/my-sites/checkout/composite-checkout/test/paypal-express-processor.ts
  client/my-sites/checkout/composite-checkout/test/util/index.ts
  client/my-sites/checkout/composite-checkout/test/we-chat-processor.ts
  client/my-sites/checkout/composite-checkout/test/web-pay-processor.ts
  client/my-sites/checkout/get-thank-you-page-url/index.ts
  client/my-sites/checkout/get-thank-you-page-url/test/get-thank-you-page-url.ts
  packages/data-stores/src/site/types.ts
  packages/shopping-cart/src/empty-carts.ts
  packages/shopping-cart/src/types.ts
Labels: [Status] Needs Review

#75246 Add plans grid to Woo Express plans
  client/my-sites/plan-features-2023-grid/index.tsx
  client/my-sites/plans/ecommerce-trial/wooexpress-plans/index.tsx
  client/my-sites/plans/ecommerce-trial/wooexpress-plans/style.scss
  client/my-sites/plans/main.jsx
  client/my-sites/plans/woo-express-plans-page/index.tsx
  client/my-sites/plans/woo-express-plans-page/style.scss
  client/my-sites/plans/wx-medium/index.tsx
  packages/calypso-products/src/constants/wpcom.ts
  packages/calypso-products/src/plans-list.tsx
Labels: Plans, [Status] Needs Review, Woo Express, Woo Express Performance, Woo Express Essential

#75097 Stats: Use uPlot for the subscriber counts graph
  client/my-sites/stats/subscribers-section/index.tsx
  client/my-sites/stats/subscribers-section/style.scss
  client/package.json
  packages/components/src/chart-uplot/index.tsx
  packages/components/src/chart-uplot/stories/index.stories.tsx
  packages/components/src/chart-uplot/style.scss
  yarn.lock
Labels: [Type] Enhancement, Stats, [Status] Needs Review

#75248 Add Woo Express plans grid to expired trial page
  client/my-sites/plans/ecommerce-trial/ecommerce-trial-expired/index.tsx
Labels: [Status] Needs Review, Woo Express, Woo Express Essential, Woo Express Trial

#75178 Add boost feature flag
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/utils.ts
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
Labels: [Status] Needs Review, Jetpack Cloud

#75259 Site Assembler - Enable pattern-assembler/notices on production
  config/production.json
Labels: [Status] Needs Review

#75243 Subscription management: Create empty state for Sites
  client/landing/subscriptions/notice/notice.tsx
  client/landing/subscriptions/tab-views/sites.tsx
Labels: [Status] Needs Review, Subscription Management

#75249 Subscriptions Manager: Add loading state to unfollow button
  client/landing/subscriptions/settings-popover/site-settings/site-settings.tsx
  client/landing/subscriptions/settings-popover/site-settings/unfollow-site-button.tsx
  client/landing/subscriptions/settings-popover/styles.scss
  client/landing/subscriptions/site-list/site-row.tsx
Labels: [Status] Needs Review

#75211 Site Assembler - Pattern Categories - Review translations
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-pattern-categories.ts
Labels: [Status] Needs Review

#75231 LiB Domain: Remove plans step from lib connect
  client/landing/stepper/declarative-flow/link-in-bio-domain.ts
Labels: [Status] Needs Review, Tailored Flows

#75230 Enable plans/wooexpress-small feature flag on wpcalypso
  config/wpcalypso.json
Labels: [Status] Needs Review, Woo Express, Woo Express Essential

#75037 Delete editor site launch
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/focused-launch.ts
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/gutenboarding-launch.ts
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/index.php
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/launch-button.ts
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-launch-sidebar.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/constants.ts
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-button/index.ts
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-button/styles.scss
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-menu/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-menu/item.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-menu/styles.scss
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-modal/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-modal/styles.scss
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-progress/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-progress/styles.scss
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-sidebar/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-sidebar/styles.scss
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-step/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-step/styles.scss
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/domain-step/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/styles.scss
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/name-step/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/name-step/styles.scss
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/plan-step/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/plan-step/styles.scss
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/stores/index.ts
  apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/utils.ts
  apps/editing-toolkit/package.json
  apps/editing-toolkit/tsconfig.json
  apps/editing-toolkit/typings/index.d.ts
  yarn.lock
Labels: [Status] Needs Review

#74722 Plans 2023: Update action buttons to Upgrade when site on shorter term plan
  client/my-sites/plan-features-2023-grid/actions.tsx
  client/my-sites/plan-features-2023-grid/hooks/use-highlight-label.ts
  client/my-sites/plan-features-2023-grid/index.tsx
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  client/my-sites/plan-features-2023-grid/test/actions.tsx
  client/my-sites/plans-features-main/index.jsx
  client/my-sites/plans/controller.jsx
  client/my-sites/plans/index.js
  client/my-sites/plans/main.jsx
  client/my-sites/plans/test/index.js
  config/development.json
Labels: [Status] Needs Review, [Status] String Freeze

#74117 Plans 2023: Ability to dismiss notices on new /plans page
  client/my-sites/plan-features-2023-grid/index.tsx
Labels: [Status] Needs Review

#75272 Add optimistic UI updates to the mutations
  client/landing/subscriptions/settings-popover/site-settings/delivery-frequency-input.tsx
  client/landing/subscriptions/settings-popover/site-settings/site-settings.tsx
  client/landing/subscriptions/settings-popover/styles.scss
  client/landing/subscriptions/site-list/site-row.tsx
  packages/data-stores/src/reader/mutations/use-site-delivery-frequency-mutation.ts
  packages/data-stores/src/reader/mutations/use-site-unfollow-mutation.ts
  packages/data-stores/src/reader/mutations/use-user-settings-mutation.ts
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#74656 Data Stores: Refactor partner portal credit card store to `createReduxStore()`
  client/jetpack-cloud/sections/partner-portal/credit-card-fields/credit-card-element-field.tsx
  client/jetpack-cloud/sections/partner-portal/credit-card-fields/credit-card-submit-button.tsx
  client/jetpack-cloud/sections/partner-portal/credit-card-fields/index.tsx
  client/jetpack-cloud/sections/partner-portal/payment-methods/hooks/use-create-stored-credit-card.ts
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-add/index.tsx
  client/state/partner-portal/credit-card-form/index.ts
  client/state/partner-portal/types.ts
Labels: [Type] Enhancement, Framework, Jetpack, [Status] Needs Review, Jetpack Licensing Portal, Data-Store

#75238 Staging sites: Fix when we show the space quota message
  client/my-sites/hosting/staging-site-card/index.js
Labels: [Type] Bug, [Status] Needs Review, Staging Sites i1

#75277 Update/Subscription site list link details
  client/landing/subscriptions/site-list/site-row.tsx
  client/landing/subscriptions/site-list/styles.scss
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#75239 Subscriptions Manager: Fix SettingsPopover position
  client/landing/subscriptions/settings-popover/settings-popover.tsx
Labels: [Status] Needs Review

#72670 Add a site down filter option
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
  client/my-sites/activity/filterbar/type-selector/issue-type-selector.tsx
Labels: [Status] In Progress, [Status] Needs Review, Jetpack Cloud

#75247 @automattic/components: Make Dialog onClose optional
  packages/components/src/dialog/index.tsx
Labels: [Status] Ready to Merge, Components

#75251 Stats: Fix hover functionality for subscriber count uPlot
  client/my-sites/stats/subscribers-section/index.tsx
Labels: [Type] Bug, Stats, [Status] Needs Review

#75267 ETK: Cleanup dependencies after editor site launch removal
  apps/editing-toolkit/package.json
  apps/editing-toolkit/tsconfig.json
  packages/launch/src/focused-launch/style.scss
  yarn.lock
Labels: [Status] Needs Review, [Type] Janitorial, dependencies, Editing Toolkit

#75234 Plugins: Fix missing plugin prop in `PluginAutoUpdateToggle`
  client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx
Labels: [Type] Bug, [Status] Needs Review, Plugins

#75084 Checkout: Refactor Jetpack pre-purchase notice not showing warning in some cases
  client/my-sites/checkout/composite-checkout/components/prepurchase-notices/index.jsx
Labels: [Type] Bug, Jetpack, [Status] Needs Review, Checkout, [Size] S, Jetpack Cloud

#75111 Add software software and org slugs to plugin object
  client/data/marketplace/constants.ts
  client/data/marketplace/types.ts
  client/data/marketplace/use-es-query.ts
Labels: [Status] Needs Review

#75255 Stats Widget: remove redux for stats widget
  apps/odyssey-stats/package.json
  apps/odyssey-stats/src/app.jsx
  apps/odyssey-stats/src/lib/set-locale.js
  apps/odyssey-stats/src/widget/index.jsx
  package.json
  yarn.lock
Labels: Stats, [Status] Needs Review, Odyssey Stats

#75297 Site Editor: maintain calypso origin through testing envs
  apps/wpcom-block-editor/package.json
  apps/wpcom-block-editor/src/wpcom/editor.js
  apps/wpcom-block-editor/src/wpcom/features/site-editor-env-consistency.js
  packages/calypso-url/CHANGELOG.md
  packages/calypso-url/package.json
  packages/calypso-url/src/get-calypso-url.ts
  packages/calypso-url/src/index.ts
  packages/calypso-url/test/get-calypso-url.js
  yarn.lock
Labels: [Status] Needs Review

#75183 Site Editor: test loading without iframes
  client/gutenberg/editor/controller.js
  client/gutenberg/editor/index.js
  config/development.json
  config/wpcalypso.json
  packages/calypso-e2e/src/lib/components/full-side-editor-nav-sidebar-component.ts
  packages/calypso-e2e/src/lib/pages/full-site-editor-page.ts
  test/e2e/specs/editor-tracking/editor-tracking__block-inserted-event.ts
  test/e2e/specs/editor-tracking/editor-tracking__document-actions-events.ts
  test/e2e/specs/editor-tracking/editor-tracking__fse-template-events.ts
  test/e2e/specs/editor-tracking/editor-tracking__global-styles-events.ts
  test/e2e/specs/editor-tracking/editor-tracking__other-block-events.ts
  test/e2e/specs/editor-tracking/editor-tracking__toolbar-events.ts
  test/e2e/specs/fse/fse__limited-global-styles.ts
  test/e2e/specs/fse/fse__temp-smoke-test.ts
Labels: [Status] Needs Review

#75208 Stats: Adding Subscribers stats page
  apps/odyssey-stats/src/routes.js
  client/blocks/stats-navigation/constants.js
  client/my-sites/stats/controller.jsx
  client/my-sites/stats/hooks/use-subscribers-query.js
  client/my-sites/stats/index.js
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-subscribers-page/index.jsx
  client/my-sites/stats/subscribers-section/index.tsx
  config/development.json
Labels: Stats, [Status] Needs Review

#75266 Jetpack Pro Dashboard: create and use date offset hook for a site in the latest backup expandable card.
  client/components/jetpack/daily-backup-status/use-get-display-date.js
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/backup-storage.tsx
  client/lib/jetpack/hooks/use-date-offset-for-site.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#75268 Logged-out Plugin details: Add ref param to CTA button
  client/my-sites/plugins/plugin-details-CTA/index.jsx
Labels: [Status] Needs Review

#75322 Site Assembler - Categories - Remove feature flag pattern-assembler/categories
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-pattern-list.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#75265 Subscription management: Fix an exception on settings view
  client/landing/subscriptions/tab-views/settings.tsx
  client/landing/subscriptions/user-settings/user-settings.tsx
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#75263 Staging Sites: Improve staging site card design
  client/my-sites/hosting/staging-site-card/index.js
  client/my-sites/hosting/staging-site-card/test/index.js
Labels: Staging Sites i1

#75324 Fix wrong position of popover when window is resized in between mounts
  packages/components/src/popover/index.jsx
  packages/components/src/popover/util.js
Labels: [Status] Needs Review, [SM] Calypso Portal

#75237 Subscriptions Manager: Remove temporary redirect from Sites tab.
  client/landing/subscriptions/tabs-switcher/tabs-switcher.tsx
Labels: [Status] Needs Review

#75285 Display domain ContactVerificationCard only if the domain requires Nominet verification (or it has been suspended)
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/lib/fixtures.ts
  client/lib/domains/types.ts
  client/my-sites/domains/domain-management/settings/index.tsx
  client/state/sites/domains/assembler.js
  client/state/sites/domains/schema.js
  client/state/sites/domains/test/fixture/index.js
Labels: [Status] Needs Review, Domains

#75280 Fix blogging prompt style in search stream
  client/reader/stream/style.scss
Labels: [Status] Needs Review

#75127 Staging Sites: Hide staging sites module on Pro Plan
  client/my-sites/hosting/main.js
  client/my-sites/hosting/staging-site-card/index.js
  packages/calypso-products/src/constants/features.ts
Labels: [Type] Bug, [Status] In Progress, [Status] Needs Review, Staging Sites i1

#75187 Update comment list in conversations
  client/blocks/conversations/list.jsx
  client/blocks/reader-post-card/conversation-post.jsx
  client/reader/conversations/controller.js
  client/reader/conversations/stream.js
  client/reader/follow-sources.jsx
  client/state/data-layer/wpcom/read/streams/index.js
  client/state/data-layer/wpcom/read/streams/test/index.js
Labels: [Status] Needs Review

#75320 Site Assembler - Refactoring to align the pattern data with PTK API response
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-categories-order.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-patterns-map-by-category.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-recipe.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/notices/notices.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-large-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-layout.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-panel.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-renderer.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/patterns-data.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-category-list.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/types.ts
Labels: [Status] Needs Review

#75271 Virtual themes i2: Release
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Design Picker

#75290 WooExpress: Features on the plans page don't match the design
  client/lib/plans/features-list.tsx
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review, Woo Express

#75269 Packages: Remove unused `@automattic/launch` package and launch store
  .yarnrc.yml
  apps/editing-toolkit/editing-toolkit-plugin/common/data-stores/index.ts
  apps/editing-toolkit/editing-toolkit-plugin/common/data-stores/launch.ts
  apps/editing-toolkit/package.json
  apps/editing-toolkit/tsconfig.json
  packages/data-stores/src/index.ts
  packages/data-stores/src/launch/actions.ts
  packages/data-stores/src/launch/constants.ts
  packages/data-stores/src/launch/data.ts
  packages/data-stores/src/launch/index.ts
  packages/data-stores/src/launch/reducer.ts
  packages/data-stores/src/launch/selectors.ts
  packages/data-stores/src/launch/types.ts
  packages/data-stores/src/mapped-types.ts
  packages/launch/README.md
  packages/launch/jest.config.js
  packages/launch/package.json
  packages/launch/src/_variables.scss
  packages/launch/src/constants.ts
  packages/launch/src/context.ts
  packages/launch/src/focused-launch/domain-details/index.tsx
  packages/launch/src/focused-launch/domain-details/test/index.tsx
  packages/launch/src/focused-launch/go-back-button/index.tsx
  packages/launch/src/focused-launch/go-back-button/style.scss
  packages/launch/src/focused-launch/index.tsx
  packages/launch/src/focused-launch/plan-details/index.tsx
  packages/launch/src/focused-launch/route.ts
  packages/launch/src/focused-launch/style.scss
  packages/launch/src/focused-launch/success/index.tsx
  packages/launch/src/focused-launch/success/style.scss
  packages/launch/src/focused-launch/summary/focused-launch-summary-item/index.tsx
  packages/launch/src/focused-launch/summary/focused-launch-summary-item/style.scss
  packages/launch/src/focused-launch/summary/index.tsx
  packages/launch/src/focused-launch/summary/style.scss
  packages/launch/src/hooks/index.ts
  packages/launch/src/hooks/use-cart.ts
  packages/launch/src/hooks/use-domain-search.ts
  packages/launch/src/hooks/use-domain-selection.ts
  packages/launch/src/hooks/use-domain-suggestion.ts
  packages/launch/src/hooks/use-has-ecommerce-plan.ts
  packages/launch/src/hooks/use-on-launch.ts
  packages/launch/src/hooks/use-plans.tsx
  packages/launch/src/hooks/use-site-domains.ts
  packages/launch/src/hooks/use-site.ts
  packages/launch/src/hooks/use-title.ts
  packages/launch/src/index.ts
  packages/launch/src/launch/index.tsx
  packages/launch/src/launch/styles.scss
  packages/launch/src/stores.ts
  packages/launch/src/types.d.ts
  packages/launch/src/utils.ts
  packages/launch/tsconfig-cjs.json
  packages/launch/tsconfig.json
  packages/onboarding/package.json
  packages/onboarding/src/index.ts
  packages/onboarding/src/scroll-to-top/index.tsx
  packages/onboarding/src/scroll-to-top/test/index.tsx
  packages/tsconfig.json
  yarn.lock
Labels: Framework, [Status] Needs Review, [Type] Janitorial, Packages, Data-Store

#74473 Data Stores: Refactor `WpcomFeatures` store to `createReduxStore()`
  apps/editing-toolkit/editing-toolkit-plugin/common/data-stores/index.ts
  apps/editing-toolkit/editing-toolkit-plugin/common/data-stores/wpcom-features.ts
  packages/data-stores/src/index.ts
  packages/data-stores/src/wpcom-features/index.ts
  packages/data-stores/src/wpcom-features/types.ts
  packages/plans-grid/src/plans-accordion/index.tsx
  packages/plans-grid/src/stores.ts
Labels: [Type] Enhancement, Framework, Plans, [Status] Needs Review, Data-Store

#75279 Data Stores: Remove unused i18n store
  packages/data-stores/package.json
  packages/data-stores/src/i18n/actions.ts
  packages/data-stores/src/i18n/constants.ts
  packages/data-stores/src/i18n/index.ts
  packages/data-stores/src/i18n/reducer.ts
  packages/data-stores/src/i18n/resolvers.ts
  packages/data-stores/src/i18n/selectors.ts
  packages/data-stores/src/i18n/test/reducer.js
  packages/data-stores/src/i18n/test/resolvers.js
  packages/data-stores/src/i18n/test/selectors.js
  packages/data-stores/src/i18n/types.ts
  packages/data-stores/src/index.ts
  yarn.lock
Labels: [Status] Needs Review, i18n, [Type] Janitorial, Data-Store

#75291 Happy-blocks: Move universal-header to a PHP template
  apps/happy-blocks/block-library/universal-header/block.json
  apps/happy-blocks/block-library/universal-header/edit.tsx
  apps/happy-blocks/block-library/universal-header/includes.php
  apps/happy-blocks/block-library/universal-header/index.js
  apps/happy-blocks/block-library/universal-header/index.php
  apps/happy-blocks/block-library/universal-header/index.tsx
  apps/happy-blocks/block-library/universal-header/placeholder.tsx
  apps/happy-blocks/block-library/universal-header/rtl/block.json
  apps/happy-blocks/block-library/universal-header/style.scss
  apps/happy-blocks/block-library/universal-header/types.ts
  apps/happy-blocks/block-library/universal-header/view.js
  apps/happy-blocks/block-library/universal-header/view.tsx
  apps/happy-blocks/index.php
  apps/happy-blocks/webpack.config.js
  apps/phpcs.xml
Labels: [Status] Needs Review

#74826 Tailored Flows: Improve newsletter flow copies
  client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/components/setup-form/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/tasks.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/step-content.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/translations.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/translations.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/plans-wrapper.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/tailored-flow-precheckout-screen/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/subscribers/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/subscribers/style.scss
  client/signup/step-wrapper/index.jsx
  client/signup/steps/user/index.jsx
  packages/subscriber/src/components/add-form/index.tsx
  packages/subscriber/src/components/add-form/style.scss
Labels: [Status] Needs Review, Signup, [Status] String Freeze, Stepper, Tailored Flows

#75186 Marketplace: Theme Installation page redirecting to the Thank You Page
  client/my-sites/checkout/checkout-thank-you/marketplace/use-themes-thank-you-data.tsx
  client/my-sites/marketplace/controller.js
  client/my-sites/marketplace/index.js
  client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx
  client/my-sites/marketplace/pages/marketplace-plugin-install/types.ts
  client/state/atomic/transfers/actions.ts
  client/state/data-layer/wpcom/sites/atomic/test/transfers/index.js
  client/state/data-layer/wpcom/sites/atomic/transfers/index.js
Labels: [Status] Needs Review

#75140 State: Convert getDiscountedRawPrice to TypeScript
  client/blocks/post-share/nudges.jsx
  client/my-sites/checkout/upsell-nudge/index.tsx
  client/my-sites/plan-features-2023-grid/index.tsx
  client/my-sites/plan-features/index.jsx
  client/my-sites/plans-comparison/use-plan-prices.tsx
  client/my-sites/plans-features-main/plan-type-selector.tsx
  client/my-sites/plans/hooks/use-plan-prices.ts
  client/state/plans/selectors/get-discounted-raw-price.ts
  client/state/plans/selectors/get-plan-raw-price.ts
  client/state/products-list/selectors/get-plan-price.ts
  client/state/products-list/test/selectors.js
  client/state/sites/plans/selectors/get-plan-discounted-raw-price.ts
  client/state/sites/plans/selectors/get-plan-raw-discount.ts
  client/state/sites/plans/selectors/get-site-plan-raw-price.js
  client/state/sites/plans/selectors/get-site-plan-raw-price.ts
  client/state/sites/plans/test/selectors.js
Labels: [Status] Needs Review

#75340 One-click checkout: Only bail on email upsell if there are actually cart errors
  client/my-sites/checkout/upsell-nudge/index.tsx
Labels: [Status] Needs Review, Checkout, Post Checkout

#75307 Components: Make uPlot container responsive
  packages/components/src/chart-uplot/index.tsx
Labels: Stats, [Status] Needs Review, Components

#75252 Purchases: Use formatCurrency for receipts
  client/me/purchases/billing-history/receipt.tsx
  client/me/purchases/billing-history/test/filter-transactions.ts
  client/me/purchases/billing-history/test/tax.ts
  client/me/purchases/billing-history/test/utils.ts
  client/me/purchases/billing-history/utils.tsx
  client/state/billing-transactions/individual-transactions/test/actions.js
  client/state/billing-transactions/types.ts
Labels: [Status] Needs Review

#75348 Checkout: add tests for one click professional email upsell
  client/my-sites/checkout/composite-checkout/test/util/index.ts
  client/my-sites/checkout/upsell-nudge/index.tsx
  client/my-sites/checkout/upsell-nudge/test/upsell-nudge.tsx
Labels: [Status] Needs Review, Checkout, Post Checkout

#75201 Logging: Remove log download UI from Hosting Configuration
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, WoA Logging i1

#75355 Launchpad: Remove Choose Domain Task for Flows that include a Domain Step
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/tasks.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/task-helper.ts
Labels: [Status] Needs Review, Launchpad

#75190 Stats Widget: Introduce new Stats Widget with a basic chart
  apps/odyssey-stats/src/app.scss
  apps/odyssey-stats/src/hooks/use-visits-query.js
  apps/odyssey-stats/src/styles/wp-admin.scss
  apps/odyssey-stats/src/widget/index.jsx
  apps/odyssey-stats/src/widget/index.scss
  apps/odyssey-stats/src/widget/mini-chart.jsx
  apps/odyssey-stats/src/widget/mini-chart.scss
  client/blocks/stats-navigation/intervals.js
Labels: Stats, [Status] Needs Review, Odyssey Stats

#75260 Public tags page: Add the alphabetic tag listing section
  client/reader/tags/alphabetic-tags.tsx
  client/reader/tags/controller.tsx
  client/reader/tags/index.node.js
  client/reader/tags/index.web.js
  client/reader/tags/main.tsx
  client/reader/tags/style.scss
Labels: [Status] Needs Review

#75112 Site Assembler: Make the arrow icon accessible to the RTL language
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-category-list.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-category-list.tsx
  client/landing/stepper/index.tsx
  packages/block-renderer/src/components/block-renderer-container.scss
Labels: [Status] Needs Review

#75163 Theme Showcase: Add click event for primary action button
  client/my-sites/theme/main.jsx
  client/my-sites/themes/theme-preview.jsx
Labels: [Type] Bug, [Status] Needs Review, Theme Showcase

#75204 Update required Jetpack version to 12.0 for Unified Importer
  client/my-sites/importer/section-import.jsx
Labels: [Status] Needs Review

#75367 Theme Showcase: Fix issue where the Unlock this style button is shown for the default style variation
  client/my-sites/theme/main.jsx
Labels: [Type] Bug, [Status] Needs Review, Theme Showcase

#75365 Focus on the first pattern in the pattern panel
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-renderer.tsx
Labels: [Status] Needs Review

#75283 Upgrade `react-router-dom` to version 6
  client/landing/stepper/declarative-flow/internals/components/step-route/index.tsx
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/hooks/test/use-is-anchor-fm.tsx
  client/landing/stepper/hooks/use-parameter.ts
  client/landing/stepper/utils/kebabCase.ts
  client/landing/stepper/utils/path.ts
  client/package.json
  client/state/jitm/actions.js
  packages/data-stores/package.json
  packages/data-stores/src/help-center/actions.ts
  packages/data-stores/src/help-center/reducer.ts
  packages/data-stores/src/help-center/selectors.ts
  packages/help-center/src/components/back-button.tsx
  packages/help-center/src/components/help-center-contact-form.tsx
  packages/help-center/src/components/help-center-container.tsx
  packages/help-center/src/components/help-center-content.tsx
  packages/help-center/src/components/help-center-embed-result.tsx
  packages/help-center/src/components/help-center-footer.tsx
  packages/help-center/src/components/help-center-header.tsx
  packages/help-center/src/components/help-center-search.tsx
  packages/help-center/src/components/help-center-sibyl-articles.tsx
  packages/help-center/src/components/history-recorder.tsx
  packages/help-center/src/components/test/back-button.tsx
  packages/onboarding/package.json
  yarn.lock
Labels: [Status] Needs Review

#74625 Jetpack Pro Dashboard: implement site expanded content for monitor activity on large and small screens
  client/components/chart/README.md
  client/components/chart/bar-container.jsx
  client/components/chart/index.jsx
  client/data/agency-dashboard/use-fetch-monitor-data.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/expanded-card.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/monitor-activity.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/utils.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#75351 Subscriptions Management: Create CommentsView component
  client/landing/subscriptions/subscription-manager/subscription-manager.tsx
  client/landing/subscriptions/tab-views/comments.tsx
  client/landing/subscriptions/tab-views/index.tsx
  client/landing/subscriptions/tab-views/settings.tsx
  client/landing/subscriptions/tab-views/sites.tsx
  client/landing/subscriptions/tab-views/styles.scss
  client/landing/subscriptions/tab-views/tab-view.tsx
Labels: [Status] Needs Review

#75368 Site Assembler: Avoid the content and scrollbar of the sidebar overlapping
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/navigator-buttons/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/style.scss
Labels: [Status] Needs Review

#75286 Woo Express: Update redirect post-checkout, add Tracks events
  client/my-sites/plans/ecommerce-trial/ecommerce-trial-expired/index.tsx
  client/my-sites/plans/ecommerce-trial/index.tsx
  client/my-sites/plans/ecommerce-trial/upgrade-confirmation/index.tsx
  client/my-sites/plans/ecommerce-trial/wooexpress-plans/index.tsx
  client/my-sites/plans/woo-express-plans-page/index.tsx
Labels: Plans, [Status] Ready to Merge, Woo Express, Woo Express Performance, Plans: eCommerce Trial, Woo Express Essential, Woo Express Trial

#75384 Marketplace: avoid plugin overflows in thank you page if descriptions is big.
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-plugin-section.tsx
Labels: [Status] Needs Review

#75358 Fix untranslated text on /stats/ads/ admin page
  client/blocks/stats-navigation/constants.js
  client/my-sites/stats/wordads/index.jsx
Labels: [Status] Needs Review, i18n

#75395 Update storage for Woo Express Essential to 50GB
  packages/calypso-products/src/plans-list.tsx
Labels: Plans, [Status] Needs Review, Pricing/plans Page, Woo Express, Woo Express Performance, Woo Express Essential

#75361 Fix: Add the inline styles back to the inline-help-search-results
  client/blocks/inline-help/inline-help-search-results.jsx
Labels: [Status] Needs Review, MyHome

#75303 Components: Update CircularProgressBar Prop Handling
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  packages/components/src/circular-progress-bar/index.tsx
Labels: [Status] Needs Review, Launchpad

#75275 Launchpad: Update Copy Icon & Fix Tooltip Z-index
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
  client/my-sites/customer-home/components/celebrate-launch-modal.jsx
  client/my-sites/customer-home/components/celebrate-launch-modal.scss
Labels: [Status] Needs Review, Launchpad

#75319 Signup: Attempt to handle redirect after Apple sign in
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/social.jsx
  client/signup/steps/user/index.jsx
Labels: [Status] Needs Review, Signup

#75063 Plans 2023: The 1y/2y term presentation test
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  client/my-sites/plans-features-main/index.jsx
  client/my-sites/plans-features-main/plan-type-selector.tsx
  client/my-sites/plans-features-main/term-experiment-plan-type-selector.tsx
  client/signup/main.jsx
Labels: [Status] Needs Review

#75392 Staging Sites: Place staging sites below production site
  packages/sites/src/site-type.ts
  packages/sites/src/use-sites-list-sorting.tsx
  packages/sites/tests/use-sites-list-sorting.test.ts
Labels: [Status] Needs Review, Staging Sites i1

#75326 Site Assembler - All Dotcom patterns and categories with feature flag
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-dotcom-patterns.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-pattern-categories.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/patterns-data.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-footer.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-header.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
  packages/block-renderer/src/hooks/use-rendered-patterns.ts
Labels: [Status] Needs Review

#75338 Unlock UIMP Wix importer
  client/lib/importer/importer-config.tsx
Labels: [Status] Needs Review, Unified Importer

#75391 Hosting onboarding: use passwordless mode on signup step
  client/signup/steps/user/index.jsx
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting onboarding i1

#75388 Plans Grid: Remove unused components and data stores
  packages/data-stores/src/index.ts
  packages/data-stores/src/onboard/actions.ts
  packages/data-stores/src/onboard/reducer.ts
  packages/data-stores/src/plans/constants.ts
  packages/data-stores/src/shared-types.ts
  packages/data-stores/src/site/types.ts
  packages/data-stores/src/wpcom-features/constants.tsx
  packages/data-stores/src/wpcom-features/features-data.tsx
  packages/data-stores/src/wpcom-features/index.ts
  packages/data-stores/src/wpcom-features/reducer.ts
  packages/data-stores/src/wpcom-features/selectors.ts
  packages/data-stores/src/wpcom-features/types.ts
  packages/onboarding/src/feature-icon/index.tsx
  packages/plans-grid/package.json
  packages/plans-grid/src/badge/index.tsx
  packages/plans-grid/src/badge/style.scss
  packages/plans-grid/src/index.ts
  packages/plans-grid/src/plans-accordion-item/index.tsx
  packages/plans-grid/src/plans-accordion-item/plans-item-placeholder.tsx
  packages/plans-grid/src/plans-accordion-item/style.scss
  packages/plans-grid/src/plans-accordion/index.tsx
  packages/plans-grid/src/plans-accordion/style.scss
  packages/plans-grid/src/plans-details/index.tsx
  packages/plans-grid/src/plans-details/style.scss
  packages/plans-grid/src/plans-feature-list/plans-feature-list-placeholder.tsx
  packages/plans-grid/src/plans-feature-list/style.scss
  packages/plans-grid/src/plans-grid/index.tsx
  packages/plans-grid/src/plans-grid/style.scss
  packages/plans-grid/src/plans-table/index.tsx
  packages/plans-grid/src/variables.scss
  yarn.lock
Labels: Plans, [Status] Needs Review, [Type] Janitorial, Packages, Data-Store

#75377 Data Stores: Refactor partner portal credit card store to `createReduxStore()` - take 2
  client/jetpack-cloud/sections/partner-portal/credit-card-fields/credit-card-element-field.tsx
  client/jetpack-cloud/sections/partner-portal/credit-card-fields/credit-card-submit-button.tsx
  client/jetpack-cloud/sections/partner-portal/credit-card-fields/index.tsx
  client/jetpack-cloud/sections/partner-portal/credit-card-fields/test/credit-card-submit-button.jsx
  client/jetpack-cloud/sections/partner-portal/payment-methods/hooks/use-create-stored-credit-card.ts
  client/jetpack-cloud/sections/partner-portal/payment-methods/stored-credit-card-method.tsx
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-add/index.tsx
  client/state/partner-portal/credit-card-form/index.ts
  client/state/partner-portal/types.ts
Labels: [Type] Enhancement, Framework, Jetpack, [Status] Needs Review, Jetpack Licensing Portal, Data-Store

#75061 Stepper: Load Newsletter flow steps async
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/style.scss
  client/landing/stepper/declarative-flow/internals/types.ts
  client/landing/stepper/declarative-flow/newsletter.ts
  client/landing/stepper/declarative-flow/plugin-bundle-flow.ts
Labels: [Status] Needs Review

#75415 Domains: Enable the new .uk contact verification card for all users
  client/my-sites/domains/domain-management/settings/index.tsx
Labels: [Status] Needs Review, Domains

#75359 Media Library: Show Video Upload Progress
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/my-sites/media-library/list-item.scss
  client/my-sites/media-library/list-item.tsx
  packages/wpcom.js/src/lib/tus-uploader.js
Labels: [Status] Needs Review, VideoPress

#75433 Payment Methods: Allow deleting expired payment methods
  client/me/purchases/payment-methods/payment-method-delete.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-stored-payment-methods.tsx
Labels: [Status] Needs Review

#75431 Make ContactVerificationCard open by default
  client/my-sites/domains/domain-management/settings/index.tsx
Labels: [Status] Needs Review, Domains

#75044 VAT Info: Use string interpolation for tax names
  client/me/purchases/billing-history/main.tsx
  client/me/purchases/controller.jsx
  client/me/purchases/titles.js
  client/me/purchases/vat-info/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze, VAT, Taxes

#75352 Extend timeouts in e2e test purchases
  test/e2e/specs/plans/plans__signup-business.ts
  test/e2e/specs/plans/plans__upgrade.ts
Labels: [Status] Needs Review

#75129 Launchpad - Update launchpad site preview height for desktop viewport
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
Labels: [Status] Needs Review, Launchpad

#75354 Use domcontentloaded as load event when checking ssr in e2e tests
  test/e2e/specs/infrastructure/infrastructure__ssr-enabled.ts
Labels: [Status] Needs Review

#75413 Remove unused type packages
  package.json
  yarn.lock
Labels: [Status] Needs Review

#75357 Flaky E2E: When naving directly to plugins page, add safer waiting
  packages/calypso-e2e/src/lib/pages/plugins-page.ts
  test/e2e/specs/plugins/plugins__browse.ts
Labels: [Status] Needs Review

#75310 Stats: Restore legend to subscriber section
  client/my-sites/stats/subscribers-section/index.tsx
  client/my-sites/stats/subscribers-section/style.scss
  packages/components/src/chart-uplot/index.tsx
  packages/components/src/chart-uplot/stories/index.stories.tsx
  packages/components/src/chart-uplot/style.scss
Labels: Stats, [Status] Needs Review

#75379 Stats: Update grid on the Subscribers page (take 2)
  client/my-sites/stats/grid-layout.scss
  client/my-sites/stats/stats-subscribers-page/index.jsx
Labels: Stats, [Status] Needs Review

#75382 Stats: Extract Emails module into wrapper component
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-module-emails/index.jsx
  client/my-sites/stats/stats-subscribers-page/index.jsx
Labels: Stats, [Status] Needs Review

#75442 ExPlat: stop logging `dangerouslyGetExperimentAssignment-error`
  packages/explat-client/src/create-explat-client.ts
  packages/explat-client/src/test/create-explat-client.ts
Labels: [Status] Needs Review

#75424 Fix: Filtered plans comparison grid features
  client/my-sites/plan-features-2023-grid/index.tsx
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  client/my-sites/plan-features-2023-grid/types.ts
  client/my-sites/plans-features-main/index.jsx
Labels: [Status] Needs Review

#75133 Launchpad - Update launchpad domain upsell completion
  client/data/sites/use-launchpad.ts
  client/landing/stepper/declarative-flow/domain-upsell.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/types.ts
Labels: [Status] Needs Review, Launchpad

#75449 Hide missing domain connect support link until
  client/components/domains/connect-domain-step/connect-domain-step-support-info-link.jsx
Labels: [Status] Needs Review

#75100 chore: use [Type] Flaky E2E label for issues reported with the Flaky E2E template.
  .github/ISSUE_TEMPLATE/flaky-e2e-spec-report.yml
Labels: [Status] Needs Review

#75093 AT E2E: accommodate difference between AT and Simple for the Dynamic HR block.
  test/e2e/specs/blocks/blocks__coblocks__blocks.ts
Labels: [Status] Needs Review

#75001 Atomic E2E: add new users for AT Site Editor users.
  packages/calypso-e2e/src/lib/utils/criteria-for-test-accounts.ts
  packages/calypso-e2e/src/secrets/encrypted.enc
  packages/calypso-e2e/src/secrets/secrets-manager.ts
Labels: [Status] Needs Review

#60497 Jetpack Licensing activation: Adjust css for licensing activation title
  client/components/jetpack/licensing-activation/style.scss
Labels: Jetpack, [Status] Needs Review, [Type] Janitorial, Jetpack Licensing

#74877 Clarify the domain registration & transfer policy in the domain management screen.
  client/my-sites/domains/domain-management/list/empty-domains-list-card.jsx
Labels: [Status] Needs Review, [Status] String Freeze

#74875 Plans 2023: update copy for sharing feature
  client/lib/plans/features-list.tsx
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/feature-group-plan-map.ts
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review, [Status] String Freeze, 2023 Pricing Page ⚡

#75188 WoA Logging i1: Add the ability to expand row to show logs vertical layout.
  client/my-sites/site-logs/components/site-logs-table/index.tsx
  client/my-sites/site-logs/components/site-logs-table/site-logs-expanded-content.tsx
  client/my-sites/site-logs/components/site-logs-table/site-logs-table-row.tsx
  client/my-sites/site-logs/components/site-logs-table/style.scss
  client/my-sites/site-logs/test/main.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, WoA Logging i1

#75015 Refactor away from Lodash functionality in bin/audit-svg-colors
  bin/audit-svg-colors.js
Labels: [Status] Needs Review

#75454 Fix the redirect to primary slug if there is a hashstring
  client/my-sites/controller.js
Labels: [Status] Needs Review

#75408 Subscriptions Management: Fix delivery frequency translation
  client/landing/subscriptions/site-list/site-row.tsx
Labels: [Status] Needs Review

#75276 Fix vertical alignment of notice component
  client/landing/subscriptions/notice/style.scss
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#75314 DotOrg Theme: Active theme on the Marketplace Theme Installation page
  client/my-sites/themes/thanks-modal.jsx
  client/state/themes/actions/activate.js
Labels: [Status] Needs Review

#75473 Subscription management: Add TimeSince component
  client/landing/subscriptions/site-list/site-row.tsx
  packages/data-stores/src/reader/queries/use-site-subscriptions-query.ts
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#75313 DotOrg Theme: Update upsell URL to redirect to the theme installation page
  client/my-sites/theme/main.jsx
Labels: [Status] Needs Review

#75476 Subscription management: Fix delivery frequency overflow
  client/landing/subscriptions/settings-popover/styles.scss
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#75464 Subscription management: Remove settings popover outline
  client/landing/subscriptions/settings-popover/styles.scss
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#75479 Subscription manager: Check if toDateString() exists
  client/landing/subscriptions/site-list/site-row.tsx
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#75426 Social Previews | Update Twitter preview
  packages/social-previews/package.json
  packages/social-previews/src/helpers.js
  packages/social-previews/src/twitter-preview/style.scss
  packages/social-previews/src/twitter-preview/tweet.jsx
  packages/social-previews/src/variables.scss
  yarn.lock
Labels: [Status] Needs Review

#75441 desktop: replace windows codesigning cert
  .circleci/config.yml
  desktop/docs/codesigning.md
  desktop/resource/certificates/win.p12.enc
Labels: [Status] Needs Review, Desktop App

#75412 Anchor: Remove My Home right sidebar promo link
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
Labels: [Status] Needs Review, Anchor.FM

#75498 Woo Express: Fix fatal error on the plans page.
  client/my-sites/plan-features-2023-grid/index.tsx
Labels: [Type] Bug, [Status] Needs Review, Woo Express, Woo Express Trial

#75467 Stats: Address feedback on Subscribers page
  client/my-sites/stats/stats-subscribers-page/index.jsx
Labels: Stats, [Status] Needs Review

#75503 Revert "Anchor: Remove My Home right sidebar promo link"
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
Labels: [Status] Needs Review, Anchor.FM

#75505 Remove "Start Writing" step from newsletter launchpad flow
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/tasks.tsx
Labels: [Status] Needs Review

#74027 Cancel Purchase Form: Provide more context about product being canceled
  client/components/marketing-survey/cancel-purchase-form/index.jsx
Labels: [Status] Needs Review

#75362 Tags page: Add tracking and fix alphabetic listing on tablet
  client/reader/tags/alphabetic-tags.tsx
  client/reader/tags/style.scss
  client/reader/tags/trending-tags.tsx
Labels: [Status] Needs Review

#75422 New ThemeCard component
  client/components/theme/index.jsx
  client/components/theme/test/__snapshots__/index.jsx.snap
  client/components/theme/test/index.jsx
  packages/calypso-e2e/src/lib/pages/themes-page.ts
  packages/design-picker/src/components/theme-card/index.tsx
  packages/design-picker/src/components/theme-card/style.scss
  packages/design-picker/src/index.ts
Labels: [Status] Needs Review, Theme Showcase
