Repository Automattic/wp-calypso, pull requests merged in 2023-12, with the labels that each got.

#84672 Assembler: Improve Pages screen resize behavior
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pages/page-preview.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pages/page-preview.tsx
Labels: [Status] Needs Review

#84675 ActivityLog: Filter bar visual tweaks and fixed tablet layout
  client/my-sites/activity/filterbar/style.scss
Labels: [Status] Needs Review

#84699 Stats: Use API query for the plan usage section
  client/my-sites/stats/hooks/use-plan-usage-query.ts
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-plan-usage/index.tsx
  config/development.json
Labels: Stats, [Status] Needs Review

#84677 Remove some unverified domain email nags
  client/data/domains/use-domain-email-verfication.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/types.ts
  client/my-sites/checkout/checkout-thank-you/domains/domain-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-registration.tsx
  client/my-sites/checkout/checkout-thank-you/domains/types.ts
Labels: [Status] Needs Review, Suspended Domains i1

#84680 Implement the flow level props
  client/signup/config/flows-pure.js
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
  client/signup/main.jsx
Labels: [Status] Needs Review

#84636 Add the Pressable promotion banner under the plans grid
  client/my-sites/plans-features-main/components/pressable-promo-banner.tsx
  client/my-sites/plans-features-main/index.tsx
  client/signup/config/flows-pure.js
  client/signup/steps/plans/index.jsx
  packages/components/src/index.ts
  packages/components/src/logos/pressable-logo/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze, Customer Report

#84737 Add the Pressable promotion banner under the plans grid - the 2nd attempt
  client/my-sites/plans-features-main/components/pressable-promo-banner.tsx
  client/my-sites/plans-features-main/index.tsx
  client/signup/config/flows-pure.js
  client/signup/steps/plans/index.jsx
  packages/components/src/index.ts
  packages/components/src/logos/pressable-logo/index.tsx
Labels: [Status] Needs Review

#84735 BBE Landing: update header text
  client/my-sites/marketing/do-it-for-me/difm-landing.tsx
Labels: [Status] Needs Review

#84638 Jetpack Manage: Merged products and plans variants in the same product card.
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/licenses-form/hooks/use-product-and-plans.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/licenses-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/licenses-form/sections.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/licenses-form/style.scss
  client/jetpack-cloud/sections/partner-portal/lib/get-product-title.ts
  client/jetpack-cloud/sections/partner-portal/lib/get-product-variant-short-title.ts
  client/jetpack-cloud/sections/partner-portal/license-multi-product-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-product-card/style.scss
Labels: [Status] Needs Review, Jetpack Cloud

#84629 Jetpack Manage: Fix the issue license sticky header responsiveness
  client/jetpack-cloud/components/layout/style.scss
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/index.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/style.scss
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/total-cost/style.scss
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud, Reviewer Can Merge

#84717 Render the legal_agreements so that we can show mutliple legal agreements for certain domains
  client/my-sites/checkout/src/components/domain-registration-agreement.jsx
Labels: [Status] Needs Review

#84566 ResponsiveToolbarGroup: Fix the popover loading in a fallback container
  packages/components/src/responsive-toolbar-group/dropdown-group.tsx
Labels: [Status] Needs Review

#84715 Theme Showcase: Hide the Screen Switcher
  client/my-sites/themes/theme-showcase-header.jsx
Labels: [Status] Needs Review, DO NOT MERGE, [Feature] Calypso & wp-admin Navigation, [Feature] Theme Showcase

#84726 Hosting Command Palette: Rank current site at the top
  client/components/command-palette/use-command-palette.tsx
  client/components/command-palette/use-current-site-rank-top.ts
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting Command Palette

#84712 Hosting Command Palette: Add loading notices to actions
  client/sites-dashboard/components/wpcom-smp-commands.tsx
Labels: [Status] Needs Review, Hosting Command Palette

#84020 Add suggested tags to post publish share modal
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/sharing-modal/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/sharing-modal/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/sharing-modal/suggested-tags.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/sharing-modal/use-add-tags-to-post.ts
Labels: [Status] Needs Review

#84650 Jetpack Manage: Add product search field in bundling licenses UI
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/licenses-form/hooks/use-product-and-plans.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/licenses-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/licenses-form/product-filter-search.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/licenses-form/style.scss
Labels: [Status] Needs Review, Jetpack Cloud

#84544 Promote Subscription: Enable setting for all languages
  client/my-sites/site-settings/settings-newsletter/main.tsx
Labels: [Status] Needs Review

#84720 Fix discount percentage issues on wpcom products and don't show discount on selected item
  client/my-sites/checkout/src/components/item-variation-picker/util.ts
  client/my-sites/checkout/src/components/item-variation-picker/variant-dropdown-price.tsx
Labels: [Status] Needs Review

#84728 (chore)(gutenberg releases)(wpcom) Remove mention to @kit-squad in the Calypso Gutenberg E2E slack results
  .teamcity/_self/projects/WPComTests.kt
Labels: [Status] Needs Review

#84653 Add dailyprompt block to editor when answering a daily prompt.
  apps/wpcom-block-editor/src/default/editor.js
  apps/wpcom-block-editor/src/default/features/blogging-prompt.js
Labels: [Status] Needs Review

#84713 Posts: Properly handle new post status in PostRelativeTime
  client/my-sites/post-relative-time-status/index.jsx
Labels: [Type] Bug, Posts, [Status] Needs Review

#84006 E2E: Rotate secret
  .teamcity/settings.kts
  packages/calypso-e2e/src/secrets/encrypted.enc
Labels: [Status] Needs Review

#84781 Update desktop e2e password
  .teamcity/_self/projects/DesktopApp.kt
Labels: [Status] Needs Review

#84787 Launchpad: remove remnants of old recordSignupComplete logic
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx
  packages/launchpad/src/checklist-item/index.tsx
Labels: [Type] Bug, [Status] Needs Review, [Feature] Launchpad

#84727 Importers flow: Extend importers list with the Substack importer
  client/blocks/import/list/index.tsx
  client/blocks/import/types.ts
  client/blocks/import/util.ts
  client/landing/stepper/declarative-flow/import-flow.ts
  client/landing/stepper/declarative-flow/import-hosted-site.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
Labels: [Status] Needs Review

#84794 Bold free blog subdomains as if they were tlds
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review

#84802 Stats: Update slider SCSS to use “math.div” calls
  client/my-sites/stats/stats-purchase/stats-purchase-tier-upgrade-slider.scss
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#84792 Hosting Command Palette: Fix hook name
  client/components/command-palette/README.md
  client/components/command-palette/index.tsx
  client/components/command-palette/use-command-palette.tsx
Labels: [Status] Needs Review, Hosting Command Palette

#84551 Log in: make form divider text transparent
  client/blocks/authentication/form-divider/style.scss
  client/blocks/login/style.scss
  client/layout/masterbar/oauth-client.scss
  client/layout/masterbar/woo.scss
  client/signup/videopress-step-wrapper/style.scss
Labels: [Status] Needs Review

#84789 Hosting Command Palette: Use more tailored search placeholders
  client/sites-dashboard/components/wpcom-smp-commands.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting Command Palette

#84774 Remove Button dependency
  client/odie/button/index.tsx
  client/odie/button/style.scss
  client/odie/ellipsis-menu/index.tsx
  client/odie/ellipsis-menu/style.scss
  client/odie/message/index.tsx
  packages/help-center/src/components/help-center-odie.tsx
  packages/help-center/src/components/index.d.ts
Labels: [Status] Needs Review

#84718 Jetpack Manage: enable purchasing of licenses with a specified quantity
  client/jetpack-cloud/sections/partner-portal/hooks/use-issue-and-assign-licenses.tsx
  client/jetpack-cloud/sections/partner-portal/hooks/use-issue-licenses.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/hooks/use-submit-form.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/licenses-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/review-licenses/pricing-summary.tsx
  client/jetpack-cloud/sections/partner-portal/issue-multiple-licenses-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/lib/querystring-products.ts
  client/jetpack-cloud/sections/partner-portal/lib/test/querystring-products.ts
  client/jetpack-cloud/sections/partner-portal/primary/payment-method-add/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/wpcom-atomic-hosting/card-content.tsx
  client/state/partner-portal/licenses/hooks/use-issue-license-mutation.ts
Labels: [Type] Enhancement, [Status] Needs Review, [Size] S, Jetpack Cloud

#84729 Stats: Use yearly product tier pricing as default and a refactoring
  client/my-sites/stats/stats-purchase/index.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-tier-upgrade-slider.tsx
  client/my-sites/stats/stats-purchase/types.ts
  client/my-sites/stats/stats-purchase/use-available-upgrade-tiers.tsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#84830 Fix: Verify email hook throws null user exception
  client/landing/stepper/declarative-flow/internals/steps-repository/trial-acknowledge/test/use-verify-email.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/trial-acknowledge/use-verify-email.tsx
Labels: [Status] Needs Review, Maintenance, Reviewer Can Merge

#84741 Stats: Updating purchase button
  client/my-sites/stats/stats-purchase/stats-purchase-checkout-redirect.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-tier-upgrade-slider.tsx
Labels: Stats, [Status] Needs Review

#84800 Assembler: Add component PatternTooltipDeadClick
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pages/page-preview.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pages/page-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-large-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-tooltip-dead-click.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-tooltip-dead-click.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/style.scss
Labels: [Status] Needs Review

#84791 Hosting Command Palette: Add more site management commands
  client/sites-dashboard/components/wpcom-smp-commands.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting Command Palette

#84829 Hosting Command Palette: Check if site fragment exists in the URL to move currentSite to the top
  client/components/command-palette/use-current-site-rank-top.ts
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting Command Palette

#84807 `flowName` is not a valid event prop name. Use `flow` instead.
  client/my-sites/plans-features-main/index.tsx
Labels: [Status] Needs Review

#84755 Jetpack Manage: Make the Multi-variant card entire area clickable.
  client/components/multiple-choice-question/index.jsx
  client/components/multiple-choice-question/test/__snapshots__/index.js.snap
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/constants.ts
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/licenses-form/product-filter-select.tsx
  client/jetpack-cloud/sections/partner-portal/license-multi-product-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-product-card/style.scss
Labels: [Status] Needs Review, Jetpack Cloud

#84799 Render Global Style notice only when necessary
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-global-styles/notice.scss
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-global-styles/notices.js
Labels: [Status] Needs Review

#84801 Jetpack Cloud: Fix the responsiveness of the nav tabs when the content overflows.
  client/jetpack-cloud/components/layout/nav.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/index.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#84635 Jetpack Manage: Redirect to https://jetpack.com/manage/ if a non-agency user visits dashboard with `wp-admin` as origin
  client/jetpack-cloud/sections/agency-dashboard/controller.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud, Reviewer Can Merge

#84844 Refine the Pressable promo banner
  client/my-sites/plans-features-main/components/pressable-promo-banner.tsx
  packages/components/src/logos/pressable-logo/index.tsx
Labels: [Status] Needs Review, Customer Report

#84795 Unverified domain email nag: make sure we send the email and show feedback.
  client/my-sites/customer-home/main.jsx
Labels: [Status] Needs Review, Reviewer Can Merge, Suspended Domains i1

#84688 LoTS: Introduce the assembler-first flow
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
  client/components/themes-list/get-site-assembler-url.js
  client/landing/stepper/declarative-flow/assembler-first-flow.ts
  client/landing/stepper/declarative-flow/build.ts
  client/landing/stepper/declarative-flow/design-first.ts
  client/landing/stepper/declarative-flow/free.ts
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/launchpad-site-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/new-or-existing-site/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/new-or-existing-site/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-creation-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-picker-list/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-picker-list/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/sites-checker/index.tsx
  client/landing/stepper/declarative-flow/internals/steps.tsx
  client/landing/stepper/declarative-flow/link-in-bio-tld.ts
  client/landing/stepper/declarative-flow/link-in-bio.ts
  client/landing/stepper/declarative-flow/newsletter.ts
  client/landing/stepper/declarative-flow/registered-flows.ts
  client/landing/stepper/declarative-flow/start-writing.ts
  client/landing/stepper/declarative-flow/videopress.ts
  client/landing/stepper/declarative-flow/write.ts
  client/landing/stepper/utils/skip-launchpad.ts
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
  packages/data-stores/src/onboard/constants.ts
  packages/onboarding/src/utils/flows.ts
Labels: [Status] Needs Review

#84836 Self service site reset: Add hook to reset site
  packages/data-stores/src/mutations/test/use-site-reset-mutation.tsx
  packages/data-stores/src/mutations/use-site-reset-mutation.ts
Labels: [Status] Needs Review, Reviewer Can Merge, Self-service site reset

#84690 Set admin interface to classic during sensei onboarding flow
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-launch/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-launch/launch-completion-tasks.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-launch/use-sub-steps.ts
Labels: [Status] Needs Review, Sensei Onboarding Flow

#84812 Migrate subscribers: update support link
  client/my-sites/subscribers/components/migrate-subscribers-modal/migrate-subscribers-modal.tsx
Labels: [Status] Needs Review

#84703 Sidebar: link "all sites" to sites dash
  client/blocks/all-sites/index.jsx
  client/blocks/all-sites/style.scss
  client/my-sites/current-site/index.jsx
Labels: [Status] Needs Review

#84182 Tooltip to packages (Step 3): Update references to use new package component
  client/blocks/taxonomy-manager/list-item.jsx
  client/components/backup-retention-management/info-tooltip/index.tsx
  client/components/chart/index.jsx
  client/components/date-picker/events-tooltip.jsx
  client/components/line-chart/index.js
  client/components/podcast-indicator/index.jsx
  client/components/token-field/token.jsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/not-available-badge/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/toggle-activate-monitoring/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/boost-site-performance.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/in-progress-icon.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-select-checkbox/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/site-host-info.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/site-status-column.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-table-expand/site-table-tooltip.tsx
  client/jetpack-cloud/sections/partner-portal/billing-summary/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/wpcom-atomic-hosting/card-content.tsx
  client/jetpack-cloud/sections/partner-portal/primary/wpcom-atomic-hosting/feature-item.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/me/security-2fa-backup-codes-list/index.jsx
  client/my-sites/comments/comment/comment-author.jsx
  client/my-sites/customer-home/components/celebrate-launch-modal.jsx
  client/my-sites/exporter/export-card/post-type-options.jsx
  client/my-sites/plans-grid/components/plans-2023-tooltip.tsx
  client/my-sites/stats/post-trends/day.jsx
Labels: [Status] Needs Review, Plans: NPM essential

#84835 Improving likes: Update sharing buttons preview
  client/my-sites/marketing/buttons/preview.jsx
  client/my-sites/marketing/style.scss
Labels: [Status] Needs Review

#84183 Tooltip to packages (Step 4): Remove Tooltip component shim
  client/components/tooltip/index.jsx
Labels: [Status] Needs Review, Plans: NPM essential

#84697 Hosting Command Palette: Display all the commands in scroll in Calypso and move up by context
  client/components/command-palette/index.tsx
  client/components/command-palette/use-command-palette.tsx
  client/sites-dashboard/components/wpcom-smp-commands.tsx
Labels: [Type] Task, Hosting Command Palette

#84702 Import flow: Update content only step
  client/blocks/importer/components/error-message/style.scss
  client/blocks/importer/components/importer-drag/index.tsx
  client/blocks/importer/components/importer-drag/style.scss
  client/blocks/importer/components/progress-screen/index.tsx
  client/blocks/importer/components/uploading-pane/uploading-pane.scss
  client/blocks/importer/wordpress/import-content-only/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer/style.scss
Labels: [Status] Needs Review

#84112 Newsletter payment plans: drop "(yearly)" from the name
  client/my-sites/earn/components/add-edit-plan-modal/index.tsx
Labels: [Status] Needs Review, Newsletters

#84827 Marketplace review: update success message wording
  client/my-sites/marketplace/components/reviews-modal/index.tsx
Labels: Reviews & Ratings

#84585 BBE In Progress Page: switch to dedicated endpoint
  client/landing/stepper/declarative-flow/internals/steps-repository/free-post-setup/test/lib/fixtures.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/lib/fixtures.ts
  client/my-sites/marketing/do-it-for-me/difm-lite-in-progress.tsx
  client/state/selectors/get-difm-lite-site-page-titles.ts
  client/state/selectors/is-difm-lite-website-content-submitted.ts
  client/state/signup/steps/website-content/hooks/use-get-website-content-query.ts
  client/state/sites/constants.js
  packages/data-stores/src/site/types.ts
  packages/launchpad/src/test/lib/fixtures.ts
Labels: [Status] Needs Review

#84861 Hosting Command Palette: Add missing slash to `View my purchases` and `Manage domains` commands
  client/sites-dashboard/components/wpcom-smp-commands.tsx
Labels: [Status] Needs Review, Hosting Command Palette

#84071 Site Monitoring: Add initial severity filter for error logs
  client/data/hosting/use-site-logs-query.ts
  client/my-sites/site-monitoring/components/site-logs-table/index.tsx
  client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx
  client/my-sites/site-monitoring/components/site-logs-toolbar/style.scss
  client/my-sites/site-monitoring/components/site-monitoring-tab-panel/index.tsx
  client/my-sites/site-monitoring/hooks/use-site-logs-downloader.ts
  client/my-sites/site-monitoring/logs-tab.tsx
  client/my-sites/site-monitoring/site-monitoring-filter-params.ts
Labels: [Status] Needs Review, Site Monitoring

#84793 Import flow: Update UpgradePlan step
  client/blocks/importer/types.ts
  client/blocks/importer/wordpress/import-everything/index.tsx
  client/blocks/importer/wordpress/import-everything/pre-migration/index.tsx
  client/blocks/importer/wordpress/import-everything/style.scss
  client/blocks/importer/wordpress/upgrade-plan/index.tsx
  client/blocks/importer/wordpress/upgrade-plan/style.scss
  client/blocks/importer/wordpress/upgrade-plan/upgrade-plan-details.tsx
  client/blocks/importer/wordpress/upgrade-plan/upgrade-plan-feature-list.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer/hooks/use-step-navigator.ts
Labels: [Status] Needs Review

#84349 Plans 2023: Fix large-currency logic issues. More consistent application in comparison grid.
  client/my-sites/plans-grid/components/comparison-grid/index.tsx
  client/my-sites/plans-grid/components/header-price.tsx
  client/my-sites/plans-grid/hooks/npm-ready/use-is-large-currency.ts
  client/my-sites/plans-grid/hooks/use-plan-pricing-info-from-grid-plans.ts
Labels: [Status] Needs Review

#84819 Hosting Command Palette: Add cache action commands on Calypso
  client/sites-dashboard/components/wpcom-smp-commands.tsx
Labels: [Status] Needs Review, [Type] Task, Hosting Command Palette

#84866 Hosting Command Palette: Update referrer value on business-related URLs
  client/sites-dashboard/components/wpcom-smp-commands.tsx
Labels: [Status] Needs Review, Hosting Command Palette

#84824 Theme Showcase Survey: Add survey to code
  client/my-sites/themes/survey/index.tsx
  client/my-sites/themes/survey/survey.scss
  client/my-sites/themes/theme-showcase.jsx
Labels: [Status] Needs Review, [Feature] Theme Showcase

#84775 Add Ratings component and Reviews link to Theme screen
  client/my-sites/marketplace/components/reviews-summary/index.tsx
  client/my-sites/marketplace/components/reviews-summary/styles.scss
  client/my-sites/theme/main.jsx
  client/my-sites/theme/style.scss
Labels: [Status] Needs Review

#84756 Added hover state to subscription management in reader
  client/landing/subscriptions/components/settings/comment-settings/comment-settings.tsx
  client/landing/subscriptions/components/settings/site-settings/styles.scss
  client/reader/site-subscriptions-manager/style.scss
Labels: [Status] Needs Review, Maintenance, Subscription Management

#84102 Hosting Command Palette: enable the feature on staging
  config/stage.json
Labels: [Status] Needs Review, [Type] Task, Reviewer Can Merge, Hosting Command Palette

#84782 Jetpack Manage: 134 - add quick links nav to overview sidebar
  client/jetpack-cloud/sections/overview/controller.tsx
  client/jetpack-cloud/sections/overview/foldable-nav/index.tsx
  client/jetpack-cloud/sections/overview/foldable-nav/style.scss
  client/jetpack-cloud/sections/overview/foldable-nav/types.ts
  client/jetpack-cloud/sections/overview/primary/quick-links-nav/index.tsx
  client/jetpack-cloud/sections/overview/primary/sidebar/index.tsx
  client/jetpack-cloud/sections/overview/primary/sidebar/style.scss
  client/jetpack-cloud/sections/overview/sidebar/index.tsx
  client/state/jetpack-agency-dashboard/selectors.ts
  packages/components/src/foldable-card/index.jsx
Labels: [Status] Needs Review

#84771 Checkout: add non-production hosts to pending page redirect allowed list
  client/my-sites/checkout/src/lib/pending-page.ts
Labels: [Status] Needs Review, Post Checkout

#84831 Multi-Domains: Honoring a free domain name after a free + custom domain selection
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review

#84847 Stats: Filter already purchased tiers
  client/my-sites/stats/stats-purchase/index.tsx
  client/my-sites/stats/stats-purchase/use-available-upgrade-tiers.tsx
Labels: Stats, [Status] Needs Review

#84674 Self service site reset: Add initial UI card
  client/my-sites/site-settings/start-over.jsx
  client/my-sites/site-settings/style.scss
  packages/data-stores/src/index.ts
  packages/data-stores/src/mutations/use-site-reset-mutation.ts
Labels: Reviewer Can Merge, Self-service site reset

#84862 BBE Page Picker: switch to 2 column grid on mobile
  client/signup/difm/components/BrowserView.tsx
  client/signup/steps/page-picker/index.tsx
Labels: [Status] Needs Review

#84897 Design First: Fix issue where URL query params are not carried over
  client/landing/stepper/declarative-flow/design-first.ts
Labels: [Status] Needs Review

#84853 Assembler First Flow: Add the personalize your site step
  client/landing/stepper/declarative-flow/assembler-first-flow.ts
  client/landing/stepper/declarative-flow/free-post-setup.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.tsx
  client/landing/stepper/declarative-flow/internals/steps.tsx
Labels: [Status] Needs Review

#84848 Jetpack Manage: Update the Licenses page to group bundles and their child licenses together
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/review-licenses/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-details/bundle-details.tsx
  client/jetpack-cloud/sections/partner-portal/license-list-item/style.scss
  client/jetpack-cloud/sections/partner-portal/license-list/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-preview/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-preview/style.scss
  client/state/partner-portal/licenses/handlers.ts
  client/state/partner-portal/licenses/hooks/use-bundle-licenses-query.ts
  client/state/partner-portal/types.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud, Reviewer Can Merge

#84632 Purchase Modal: extract checkout functions from upsell nudge
  client/my-sites/checkout/upsell-nudge/index.tsx
  client/my-sites/checkout/upsell-nudge/purchase-modal/content.tsx
  client/my-sites/checkout/upsell-nudge/purchase-modal/index.tsx
  client/my-sites/checkout/upsell-nudge/purchase-modal/use-is-eligible-for-one-click-checkout.ts
  client/my-sites/checkout/upsell-nudge/purchase-modal/use-submit-transaction.ts
  client/my-sites/checkout/upsell-nudge/purchase-modal/with-is-eligible-for-one-click-checkout.tsx
Labels: [Status] Needs Review

#84742 Jetpack Manage: Update the discount info for licenses based on the bundle size
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/upgrade-link/index.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/lib/pricing.ts
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/licenses-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/review-licenses/pricing-breakdown.tsx
  client/jetpack-cloud/sections/partner-portal/license-multi-product-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-product-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/prices/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/product-price-with-discount-info/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/wpcom-atomic-hosting/card-content.tsx
  client/state/partner-portal/products/selectors.ts
  client/state/partner-portal/types.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud, Reviewer Can Merge

#84903 Assembler First Flow: Adjust styles for the new-or-existing, site-picker, and launchpad step
  client/landing/stepper/declarative-flow/internals/components/step-route/index.tsx
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/new-or-existing-site/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/site-picker-list/styles.scss
Labels: [Status] Needs Review

#84772 Jetpack Manage: Add an empty state when searching for products or plans
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/licenses-form/index.tsx
  client/lib/url/support.js
Labels: [Status] Needs Review

#84904 Improve UI responsiveness for reader recommendations
  client/blocks/reader-unsubscribed-feeds-search-list/reader-unsubscribed-feed-item.tsx
  client/blocks/reader-unsubscribed-feeds-search-list/style.scss
Labels: [Status] Needs Review, [SM] Reader Portal

#84909 Gained more space in subscription page in mobile
  client/blocks/reader-unsubscribed-feeds-search-list/reader-unsubscribed-feed-item.tsx
Labels: [Status] Needs Review, Subscription Management

#84854 Assembler First Flow: Handle the launch site task
  client/landing/stepper/declarative-flow/assembler-first-flow.ts
  client/landing/stepper/declarative-flow/design-first.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/celebration-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/celebration-step/use-celebration-data.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-global-styles-upgrade-props.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-launch/index.tsx
  client/landing/stepper/declarative-flow/internals/steps.tsx
  client/landing/stepper/declarative-flow/start-writing.ts
  client/landing/stepper/hooks/use-checkout.ts
  client/landing/stepper/utils/checkout.ts
Labels: [Status] Needs Review

#84865 E2E: Add test to access the with-theme flow from LOHP
  test/e2e/specs/onboarding/signup__with-theme-LOHP.ts
Labels: [Status] Needs Review

#84926 Revert "E2E: Add test to access the with-theme flow from LOHP"
  test/e2e/specs/onboarding/signup__with-theme-LOHP.ts
Labels: [Status] Needs Review

#84928 Congrats page box-shadow fix
  client/my-sites/checkout/checkout-thank-you/redesign-v2/style.scss
Labels: [Status] Needs Review

#84925 Add missing translators comment
  client/components/theme-upgrade-modal/index.tsx
Labels: [Status] Needs Review

#84834 Multi-domain: Add error message if domain removal or add fails
  client/components/domains/register-domain-step/index.jsx
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review

#84902 Add defensive code against undefined plan object in My Plans
  client/my-sites/plans/current-plan/index.jsx
Labels: [Feature] Plans & Upgrades, [Status] Needs Review, [Feature] Purchase Management

#84931 Multi-Domains: Avoiding mini-cart blinking
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review

#84517 Checkout: Call useExperiment for collapse payment method step test
  client/my-sites/checkout/src/components/checkout-main.tsx
  client/my-sites/checkout/src/components/payment-method-step.tsx
  client/my-sites/checkout/src/components/wp-checkout.tsx
  client/my-sites/checkout/src/hooks/use-cached-domain-contact-details.ts
  client/my-sites/checkout/src/hooks/use-should-collapse-last-step.tsx
  client/my-sites/checkout/src/test/use-cached-domain-contact-details.tsx
  packages/composite-checkout/src/components/checkout-payment-methods.tsx
Labels: [Status] Needs Review, [Feature] Checkout

#84833 Reader: Add support for the Post Carousel and Jetpack Slideshow blocks
  client/blocks/reader-full-post/_content.scss
  client/blocks/reader-full-post/carousel.scss
  client/components/embed-container/index.jsx
Labels: [Status] Needs Review, [Feature] Reader

#84837 Add extra description for Jetpack AI tiered plans
  client/me/purchases/manage-purchase/index.tsx
  packages/wpcom-checkout/src/checkout-labels.ts
Labels: [Status] Needs Review

#84938 Checkout: Update experiment name for collapse payment method step test
  client/my-sites/checkout/src/hooks/use-should-collapse-last-step.tsx
Labels: [Status] Needs Review

#84880 Stats: Introduce Tier Upgrade Notice for showing upgrade information
  client/my-sites/stats/hooks/use-notice-visibility-query.ts
  client/my-sites/stats/stats-notices/all-notice-definitions.ts
  client/my-sites/stats/stats-notices/tier-upgrade-notice.tsx
  config/development.json
  packages/components/src/icons/danger.tsx
  packages/components/src/icons/index.tsx
  packages/components/src/notice-banner/index.tsx
  packages/components/src/notice-banner/style.scss
Labels: Stats, [Status] Needs Review

#84939 Assembler: Improve page preview CSS when full-screen
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pages/page-preview-list.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pages/page-preview.scss
  packages/block-renderer/src/components/block-renderer-container.scss
  packages/block-renderer/src/components/block-renderer-container.tsx
Labels: [Status] Needs Review

#84109 Redesign blogging prompt card for blogganuary
  client/components/blogging-prompt-card/bloganuary-icon.jsx
  client/components/blogging-prompt-card/index.jsx
Labels: [Status] Needs Review, Customer Report

#83939 Make font size consistent for inline comments (on p2s)
  client/blocks/comments/post-comment-list.scss
Labels: [Status] Needs Review

#84941 Stats: Update purchase page layout
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-tier-upgrade-slider.scss
  client/my-sites/stats/stats-purchase/styles.scss
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#84951 Remove `plan-interval-discount` component
  client/my-sites/plan-interval-discount/index.js
  client/my-sites/plan-interval-discount/style.scss
Labels: [Status] Needs Review

#84953 Design Picker: Set design slug as component key
  packages/design-picker/src/components/unified-design-picker.tsx
Labels: [Status] Needs Review

#84922 Jetpack Manage: Fix monitor toggle border color
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/toggle-activate-monitoring/style.scss
Labels: [Status] Needs Review, Jetpack Cloud

#84645 Plans 2023: Update intro offers to be derived from either site-plans or plans endpoints
  packages/data-stores/src/plans/hooks/test/use-current-plan.ts
  packages/data-stores/src/plans/hooks/test/use-intro-offers.ts
  packages/data-stores/src/plans/hooks/use-intro-offers.ts
  packages/data-stores/src/plans/mock/next/index.ts
  packages/data-stores/src/plans/mock/next/store/plans.ts
  packages/data-stores/src/plans/mock/next/store/site-plans.ts
  packages/data-stores/src/plans/queries/lib/unpack-intro-offer.ts
  packages/data-stores/src/plans/queries/use-plans.ts
  packages/data-stores/src/plans/queries/use-site-plans.ts
  packages/data-stores/src/plans/types.ts
Labels: [Status] Needs Review

#84869 Import flow: Recognize playground file and adapt a flow for that use-case
  client/blocks/importer/components/uploading-pane/uploading-pane.tsx
  client/blocks/importer/types.ts
  client/blocks/importer/wordpress/import-content-only/index.tsx
  client/my-sites/importer/uploading-pane.jsx
  client/state/imports/api.js
Labels: [Status] Needs Review

#84924 Live Preview: Disable the Global Styles limit when live previewing Woo and Premium themes
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-global-styles/index.php
Labels: [Status] Needs Review

#84884 Jetpack Manage: add Get Help nav to overview page
  client/jetpack-cloud/sections/overview/foldable-nav/index.tsx
  client/jetpack-cloud/sections/overview/foldable-nav/types.ts
  client/jetpack-cloud/sections/overview/primary/get-help-nav/index.tsx
  client/jetpack-cloud/sections/overview/primary/sidebar/index.tsx
Labels: [Status] Needs Review

#84920 Stepper: Use pagetitle from flow in signup and login
  client/signup/signup-header/index.tsx
Labels: [Status] Needs Review

#84979 Fix inconsistencies in Reader > Recent
  client/reader/stream/index.jsx
  client/reader/stream/reader-list-followed-sites/index.jsx
Labels: [Status] Needs Review, [SM] Reader Portal

#84982 Fix for event is undefined error
  client/blocks/reader-import-button/index.tsx
Labels: [Status] Needs Review

#84261 Domains: Add Glue Records management UI
  client/components/domains/accordion/index.tsx
  client/components/domains/accordion/types.ts
  client/data/domains/glue-records/domain-glue-record-query-key.ts
  client/data/domains/glue-records/use-delete-glue-record-mutation.ts
  client/data/domains/glue-records/use-domain-glue-records-query.ts
  client/data/domains/glue-records/use-update-glue-record-mutation.ts
  client/my-sites/domains/domain-management/settings/cards/glue-records-card.tsx
  client/my-sites/domains/domain-management/settings/cards/style.scss
  client/my-sites/domains/domain-management/settings/index.tsx
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] In Progress, [Status] Needs Review

#84532 Use site id for launchpad within the start writing flow
  client/landing/stepper/declarative-flow/design-first.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/celebration-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/index.tsx
  client/landing/stepper/declarative-flow/start-writing.ts
Labels: [Status] Needs Review

#84985 Fixed margins in mobile view for search subscriptions
  client/blocks/reader-unsubscribed-feeds-search-list/style.scss
Labels: [Status] Needs Review, Subscription Management

#84937 Staging Sites: Redirect from site tools subpages if accessing them directly
  client/my-sites/site-settings/controller.js
  client/state/selectors/can-current-user-start-site-owner-transfer.ts
Labels: [Status] Needs Review, Staging Sites, Self-service site reset

#84978 Jetpack Manage: add contact support button and video to overview page sidebar
  client/jetpack-cloud/components/content-sidebar/style.scss
  client/jetpack-cloud/sections/overview/foldable-nav/style.scss
  client/jetpack-cloud/sections/overview/primary/overview/style.scss
  client/jetpack-cloud/sections/overview/primary/sidebar/index.tsx
  client/jetpack-cloud/sections/overview/primary/sidebar/style.scss
Labels: [Status] Needs Review

#84940 Checkout: Add condition to load treatment only on checkout page
  client/my-sites/checkout/src/hooks/use-tos-foldable-card.tsx
Labels: [Status] Needs Review, [Feature] Checkout

#84973 Components: Fix NoticeBanner style variables
  packages/components/src/notice-banner/style.scss
Labels: Stats, [Status] Needs Review, Components

#84983 Stats: Apply upgrade link to the plan usage section
  client/my-sites/stats/hooks/use-plan-usage-query.ts
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-plan-usage/index.tsx
Labels: Stats, [Status] Needs Review

#84942 Stats: Visual updates for the new purchase slider
  client/my-sites/stats/stats-purchase/stats-purchase-tier-upgrade-slider.scss
  client/my-sites/stats/stats-purchase/stats-purchase-tier-upgrade-slider.tsx
  client/my-sites/stats/stats-purchase/use-available-upgrade-tiers.tsx
  packages/components/src/pricing-slider/index.tsx
Labels: Stats, [Status] Needs Review

#84991 E2E: Fix test for Jetpack change
  test/e2e/specs/published-content/forms__submissions.ts
Labels: [Pri] High, [Status] Needs Review

#84946 Self-service site reset: make the UI match the mockup
  client/my-sites/site-settings/start-over.jsx
  client/my-sites/site-settings/style.scss
  packages/data-stores/src/index.ts
  packages/data-stores/src/site-reset/index.ts
  packages/data-stores/src/site-reset/test/use-site-reset-mutation.tsx
  packages/data-stores/src/site-reset/use-site-reset-content-summary-query.ts
  packages/data-stores/src/site-reset/use-site-reset-mutation.ts
Labels: [Status] Needs Review, Self-service site reset

#84944 Self service site reset: Add built by upsell banner
  client/my-sites/site-settings/built-by-upsell-banner.tsx
  client/my-sites/site-settings/form-general.jsx
  client/my-sites/site-settings/start-over.jsx
  client/my-sites/site-settings/style.scss
Labels: [Status] Needs Review, Self-service site reset

#84945 Put Akismet quantity dropdown behind feature-flag.
  client/my-sites/checkout/src/components/wp-order-review-line-items.tsx
  config/development.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#84917 Launchpad: Disable the Plan task only when the task is completed and the site has a paid plan
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.tsx
Labels: [Status] Needs Review

#84958 Stats: Update slider thumb to match design
  client/my-sites/stats/stats-purchase/tier-upgrade-slider/index.tsx
Labels: Stats, [Status] Needs Review

#84393 Checkout: Add the “Number of licenses” dropdown in Akismet checkout
  client/components/forms/form-select/index.tsx
  client/my-sites/checkout/src/components/akismet-pro-quantity-dropdown/index.tsx
  client/my-sites/checkout/src/components/akismet-pro-quantity-dropdown/types.ts
  client/my-sites/checkout/src/components/checkout-main.tsx
  client/my-sites/checkout/src/components/wp-checkout-order-review.tsx
  client/my-sites/checkout/src/components/wp-checkout.tsx
  client/my-sites/checkout/src/components/wp-order-review-line-items.tsx
  config/development.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#85000 Set the signup_domain_origin prop on multi-domain selection
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review

#84960 Assembler: Use new theme under feature flag
  client/landing/stepper/declarative-flow/assembler-first-flow.ts
  client/landing/stepper/declarative-flow/with-theme-assembler-flow.ts
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
  packages/design-picker/src/components/unified-design-picker.tsx
  packages/design-picker/src/constants.ts
  packages/design-picker/src/index.ts
  packages/design-picker/src/utils/designs.ts
Labels: [Status] Needs Review

#84721 Add 'Unlimited sites (Akismet Business)' as option in Ak Pro quantity dropdown in checkout
  client/my-sites/checkout/src/components/akismet-pro-quantity-dropdown/index.tsx
  client/my-sites/checkout/src/components/akismet-pro-quantity-dropdown/types.ts
  client/my-sites/checkout/src/components/item-variation-picker/item-variation-dropdown.tsx
  client/my-sites/checkout/src/components/item-variation-picker/types.ts
  client/my-sites/checkout/src/components/wp-order-review-line-items.tsx
  packages/calypso-products/src/constants/akismet.ts
Labels: [Status] Needs Review

#84788 Akismet Pro checkout line item prices should reflect license quantity
  client/my-sites/checkout/src/components/akismet-pro-quantity-dropdown/index.tsx
  client/my-sites/checkout/src/components/wp-order-review-line-items.tsx
  packages/wpcom-checkout/src/checkout-line-items.tsx
Labels: [Status] Needs Review, Customer Report

#85012 Launchpad: Fix styles for free & link-in-bio flow
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-setup/styles.scss
Labels: [Status] Needs Review

#84956 Assembler AI: Add account steps to the ai-assembler flow
  client/landing/stepper/declarative-flow/ai-assembler.ts
  client/landing/stepper/declarative-flow/assembler-first-flow.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/ai-site-prompt/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/new-or-existing-site/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/new-or-existing-site/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/registered-flows.ts
  packages/data-stores/src/onboard/constants.ts
Labels: [Status] Needs Review

#84997 Fix/mobile subscription manager padding
  client/blocks/reader-unsubscribed-feeds-search-list/reader-unsubscribed-feed-item.tsx
  client/blocks/reader-unsubscribed-feeds-search-list/style.scss
Labels: [Status] Needs Review, Subscription Management

#84999 Subscription Management: Improve resubscribe flow on subscriptions list
  client/landing/subscriptions/components/site-subscriptions-list/site-subscription-row.tsx
  packages/data-stores/src/reader/mutations/use-site-subscribe-mutation.ts
  packages/data-stores/src/reader/mutations/use-site-unsubscribe-mutation.ts
  packages/data-stores/src/reader/types/index.ts
Labels: [Status] Needs Review

#85019 Assembler First Flow: Keep using default assembler theme for testing
  packages/design-picker/src/utils/designs.ts
Labels: [Status] Needs Review

#85009 Jetpack Manage: Implement a revoke button for the License bundle.
  client/jetpack-cloud/sections/partner-portal/license-details/actions.tsx
  client/jetpack-cloud/sections/partner-portal/license-list-item/style.scss
  client/jetpack-cloud/sections/partner-portal/license-preview/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-preview/license-actions.tsx
  client/jetpack-cloud/sections/partner-portal/license-preview/license-bundle-dropdown.tsx
  client/jetpack-cloud/sections/partner-portal/license-preview/style.scss
  client/jetpack-cloud/sections/partner-portal/revoke-license-dialog/index.tsx
  client/jetpack-cloud/sections/partner-portal/types.ts
Labels: [Status] Needs Review, Jetpack Cloud

#84763 Plans 2023: Updated billing descriptions for WPCOM introductory offers
  client/my-sites/plans-grid/components/billing-timeframe.tsx
  client/my-sites/plans-grid/components/header-price.tsx
Labels: [Status] Needs Review

#85021 Fixed info icon margins in user list
  client/my-sites/people/people-profile/style.scss
Labels: [Status] Needs Review, Maintenance

#84987 Theme Showcase: Create the `theme/tiers` Feature Flag
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Feature] Theme Showcase, Feature-Flags

#84705 Remove translation check for subscriber launchpad.
  client/my-sites/subscribers/components/subscriber-launchpad/subscriber-launchpad.tsx
  client/my-sites/subscribers/components/subscriber-list-container/subscriber-list-container.tsx
Labels: [Status] Needs Review

#84704 Separate context for subscriber stats launchpad.
  client/my-sites/stats/stats-subscribers-highlight-section/index.tsx
  client/my-sites/subscribers/components/subscriber-launchpad/subscriber-launchpad.tsx
Labels: [Status] Needs Review

#85016 Jetpack Manage: Improve Issue license page header with actions responsiveness breakpoint.
  client/jetpack-cloud/components/layout/header.tsx
  client/jetpack-cloud/components/layout/style.scss
  client/jetpack-cloud/sections/partner-portal/issue-license-v2/index.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#85030 Show only launchpad on Subscriber Stats when no subscribers.
  client/my-sites/stats/stats-subscribers-highlight-section/index.tsx
  client/my-sites/stats/stats-subscribers/index.tsx
Labels: [Status] Ready to Merge

#85040 Disable comment email follow field
  client/my-sites/site-settings/settings-newsletter/EmailsTextSetting.tsx
Labels: [Status] Needs Review

#84998 Checkout: Implement ToS experiment attempt 2
  client/my-sites/checkout/src/hooks/use-tos-foldable-card.tsx
Labels: [Status] Needs Review

#85033 Stats: Apply dynamic progress to the usage bar
  client/my-sites/stats/stats-plan-usage/index.tsx
  client/my-sites/stats/stats-plan-usage/style.scss
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#85025 Assembler First: Don't use the new base theme (season 2)
  client/landing/stepper/declarative-flow/assembler-first-flow.ts
  packages/design-picker/src/utils/designs.ts
Labels: [Status] Needs Review

#85062 Theme Showcase: Keep the logged-in users going to the with-theme-assembler flow
  client/components/themes-list/get-site-assembler-url.js
Labels: [Status] Needs Review

#84966 fix: css overrides for auth separator under woo signup login page
  client/layout/masterbar/woo.scss
Labels: [Status] Needs Review
