Repository Automattic/wp-calypso, pull requests merged in 2023-06, with the labels that each got.

#77412 Sites page: use consistent URLs in the CTAs
  client/sites-dashboard/components/sites-dashboard-ctas.tsx
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/hooks/use-sites-dashboard-create-site-url.ts
  client/sites-dashboard/hooks/use-sites-dashboard-import-site-url.ts
  client/sites-dashboard/utils.ts
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting onboarding i2

#77613 Change wording from upgrade to update for Move to WordPress.com screen
  client/blocks/importer/wordpress/import-everything/pre-migration/index.tsx
  client/blocks/importer/wordpress/import-everything/pre-migration/update-plugins.tsx
Labels: [Status] Needs Review, Migration Plugin i2

#77516 Fix scroll on tags page.
  client/reader/tags/alphabetic-tags.tsx
Labels: [Status] Needs Review

#77641 Revert "Turn on new migration plugin / import flow feature flag on wpcalypso"
  client/blocks/importer/wordpress/import-everything/pre-migration/upgrade-plan.tsx
  config/wpcalypso.json
  packages/calypso-e2e/src/lib/flows/start-import-flow.ts
  test/e2e/specs/onboarding/setup__importer.ts
  test/e2e/specs/onboarding/start__importer.ts
Labels: [Status] Needs Review

#77594 Blog onboarding: fix plan step width
  client/my-sites/plan-features-2023-grid/style.scss
Labels: [Status] Needs Review

#77470 include deployment instructions in readme.
  apps/happy-blocks/README.md
Labels: [Status] Needs Review

#77421 Add links to the tags page
  client/reader/components/reader-blank-suggestions/index.js
  client/reader/search-stream/index.jsx
  client/reader/sidebar/reader-sidebar-tags/list.jsx
  client/reader/sidebar/style.scss
  client/reader/stream/reader-tag-sidebar/index.jsx
  client/reader/stream/style.scss
Labels: [Status] Needs Review

#77528 Help Center: Reduce the amount of AI search requests
  packages/help-center/src/components/help-center-contact-form.tsx
  packages/help-center/src/components/help-center-gpt.tsx
Labels: [Status] Needs Review, Help Center

#77638 Remove flaky site creation tests and fix jest callbacks
  client/lib/signup/test/step-actions.js
Labels: [Status] Needs Review

#77649 Import: update progress bar style and unify the progress bar
  client/blocks/importer/wordpress/import-everything/index.tsx
  client/blocks/importer/wordpress/import-everything/style.scss
Labels: [Status] Needs Review, Migration Plugin i2

#77608 Display a warning when the IG account is not connected to a Facebook page
  client/my-sites/marketing/connections/services/instagram-business.jsx
Labels: [Status] Needs Review

#77591 Email stats: Change breadcrumbs title
  client/my-sites/stats/stats-email-detail/index.jsx
Labels: [Status] Needs Review, Newsletter Stats

#77502 Subscribers Page: Create the page scaffolding
  client/my-sites/subscribers/controller.js
  client/my-sites/subscribers/index.js
  client/my-sites/subscribers/main.tsx
  client/sections.js
Labels: [Status] Needs Review, Subscribers Page

#77467 G Suite: Post-checkout screen styles update
  client/components/purchase-detail/purchase-button.jsx
  client/components/purchase-detail/style.scss
Labels: [Status] Ready to Merge, G Suite, OSS Citizen

#77659 PA in LiTS: Go to the editor on the small screen
  client/components/themes-list/index.jsx
Labels: [Status] Needs Review

#77620 Reader: Add Suggested Follows to Search Post Results Stream
  client/blocks/reader-post-actions/index.jsx
  client/blocks/reader-post-card/index.jsx
  client/blocks/reader-suggested-follows/dialog.jsx
  client/data/reader/use-related-sites.ts
Labels: [Status] Needs Review

#77629 ETK - update site intent hook to use existing data on window object
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/lib/site-intent/use-site-intent.js
Labels: [Status] Needs Review

#77634 Marketplace Thank You: Remove param key for empty product types
  client/my-sites/checkout/get-thank-you-page-url/index.ts
Labels: [Status] Needs Review

#77671 Reader: Update full post page to pass post ID to suggested follows
  client/blocks/reader-full-post/index.jsx
Labels: [Status] Needs Review

#77630 wpcom-block-editor: update site intent hook to use existing data on window object
  apps/wpcom-block-editor/src/wpcom/features/use-site-intent.js
Labels: [Status] Needs Review

#77624 Site transfers: Refactor site transfer screen
  client/my-sites/site-settings/site-owner-transfer/pending-domain-transfer.tsx
  client/my-sites/site-settings/site-owner-transfer/site-owner-transfer.tsx
  client/my-sites/site-settings/site-owner-transfer/site-owner-user-search.tsx
  client/my-sites/site-settings/site-owner-transfer/start-site-owner-transfer.tsx
Labels: [Status] Needs Review, Site Transfers i1

#77550 Add `getThemeType` selector
  client/signup/config/flows.js
  client/signup/steps/plans-theme-preselected/index.tsx
  client/state/themes/selectors/get-theme-signup-url.js
  client/state/themes/selectors/get-theme-type.js
  client/state/themes/selectors/index.js
  packages/design-picker/src/constants.ts
  packages/design-picker/src/index.ts
Labels: [Status] Needs Review

#77673 New hosted site: do not go to cart if picking the free plan
  client/landing/stepper/declarative-flow/new-hosted-site-flow.ts
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting onboarding i2

#77618 Agency Dashboard Monitoring add warning to multi-site editing
  client/components/jetpack/alert-banner/index.tsx
  client/components/jetpack/alert-banner/style.scss
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#77551 Add `canUseTheme` selector
  client/state/themes/selectors/can-use-theme.js
  client/state/themes/selectors/index.js
Labels: [Status] Needs Review

#77685 Email stats: Set max height of country list
  client/my-sites/stats/stats-email-detail/style.scss
Labels: [Status] Needs Review, Newsletter Stats

#77593 Email stats: Change pane placement
  client/my-sites/stats/grid-layout.scss
Labels: [Status] Needs Review, Newsletter Stats

#77688 Reader: Fix suggested follows - no related sites found
  client/blocks/reader-suggested-follows/dialog.jsx
Labels: [Status] Needs Review

#77632 Stats: subscribers overview cards data - move subscribers payload to interface declaration
  client/my-sites/stats/hooks/use-subscribers-query.tsx
Labels: Stats, [Status] Needs Review

#77626 Hosting onboarding: Allow dev accounts to be set when using social signup.
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/social.jsx
Labels: Hosting onboarding i2

#77637 Components: Allow Intl.NumberFormat to degrade gracefully
  packages/components/src/number-formatters/formatted-number.tsx
  packages/components/src/number-formatters/index.tsx
  packages/components/src/number-formatters/lib/format-number.ts
  packages/components/src/number-formatters/lib/test/format-number.ts
Labels: Stats, [Status] Needs Review, Components

#77695 Reader search link - add equal margin above
  client/reader/sidebar/index.jsx
Labels: [Status] Needs Review

#77511 Launchpad: Add Wrapper component
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
  packages/launchpad/package.json
  packages/launchpad/src/checklist-item/index.tsx
  packages/launchpad/src/checklist-item/style.scss
  packages/launchpad/src/checklist/index.tsx
  packages/launchpad/src/checklist/style.scss
  packages/launchpad/src/index.ts
  packages/launchpad/src/launchpad.tsx
  packages/launchpad/src/test/checklist-item.tsx
  yarn.lock
Labels: [Status] Needs Review, Launchpad

#77680 New hosted site: display site options for non-Atomic sites
  client/landing/stepper/declarative-flow/internals/steps-repository/site-options/new-hosted-site-options.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-options/style.scss
  client/landing/stepper/declarative-flow/new-hosted-site-flow.ts
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting onboarding i2

#77691 Dev accounts: use consistent new site url in site selector, sidebar and sites dashboard
  client/components/site-selector/add-site.tsx
  client/jetpack-cloud/sections/agency-dashboard/sidebar/test/sidebar.jsx
  client/lib/paths/use-add-new-site-url.tsx
  client/my-sites/sidebar/add-new-site.jsx
  client/sites-dashboard/components/sites-dashboard-ctas.tsx
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/hooks/use-sites-dashboard-create-site-url.ts
  client/sites-dashboard/hooks/use-sites-dashboard-import-site-url.ts
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting onboarding i2

#77712 Hosting onboarding i2: Gate /setup/new-hosted-site behind feature flag
  client/lib/paths/use-add-new-site-url.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting onboarding i2

#77646 Stats: Updating Subscribers summary to use real data
  client/my-sites/stats/hooks/use-subscribers-totals-query.tsx
  client/my-sites/stats/stats-subscribers/index.tsx
  client/my-sites/stats/stats-subscribers/subscribers-highlight-section.tsx
Labels: Stats, [Status] Needs Review

#77657 Blog onboarding: Fix tracks event for plan step
  client/landing/stepper/declarative-flow/internals/analytics/record-submit-step.ts
Labels: [Status] Needs Review

#77643 Enable updating already set plan and site name in the launchpad start writing flow
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
Labels: [Status] Needs Review

#77203 Jetpack Pro Dashboard: integrate request and verify email verification code API
  client/data/agency-dashboard/use-fetch-monitor-verified-contacts.ts
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/configure-email-notification/email-address-editor.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/hooks.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
  client/state/jetpack-agency-dashboard/hooks/use-request-contact-verification-code.ts
  client/state/jetpack-agency-dashboard/hooks/use-validate-contact-verification-code.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#77583 Jetpack Pro Dashboard: handle error scenario for GET `/jetpack-agency/contacts`
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/configure-email-notification/email-address-editor.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/hooks.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/dashboard-data-context.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#77687 Import: remove unnecessary styles and use props for progress bar
  client/blocks/importer/wordpress/import-everything/index.tsx
  client/blocks/importer/wordpress/import-everything/style.scss
Labels: [Status] Needs Review, Migration Plugin i2

#77485 Jetpack Pro Dashboard: Implement showing monitor settings unsaved changes warning alert.
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/configure-email-notification/email-address-editor.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#77477 Enable sharing modal on atomic
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/class-wp-rest-wpcom-block-editor-sharing-modal-controller.php
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/sharing-modal/use-sharing-modal-dismissed.ts
Labels: [Status] Needs Review

#77664 Import: turn on new migration plugin / import flow feature flag on wpcalypso
  config/wpcalypso.json
  packages/calypso-e2e/src/lib/flows/start-import-flow.ts
  test/e2e/specs/onboarding/setup__importer.ts
  test/e2e/specs/onboarding/start__importer.ts
Labels: [Status] Needs Review, Migration Plugin i2

#77661 Fix the logic to decide if a migration can proceed
  client/blocks/importer/hooks/use-site-can-migrate.ts
Labels: [Status] Needs Review, Migration Plugin i2

#77522 Social Preview | Improve defaults & Fix multiple empty lines
  packages/social-previews/CHANGELOG.md
  packages/social-previews/package.json
  packages/social-previews/src/helpers.tsx
  packages/social-previews/src/linkedin-preview/constants.ts
  packages/social-previews/src/linkedin-preview/icons/default-avatar.tsx
  packages/social-previews/src/linkedin-preview/link-preview.tsx
  packages/social-previews/src/linkedin-preview/post-preview.tsx
  packages/social-previews/src/linkedin-preview/previews.tsx
  packages/social-previews/src/linkedin-preview/style.scss
  packages/social-previews/src/twitter-preview/constants.ts
  packages/social-previews/src/twitter-preview/header.tsx
  packages/social-previews/src/twitter-preview/icons/default-avatar.tsx
  packages/social-previews/src/twitter-preview/link-preview.tsx
  packages/social-previews/src/twitter-preview/previews.tsx
  packages/social-previews/src/twitter-preview/sidebar.tsx
  packages/social-previews/src/twitter-preview/style.scss
  packages/social-previews/src/twitter-preview/types.ts
Labels: [Status] Needs Review

#77333 Split the Global Styles variations in two: default and premium
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/my-sites/theme/main.jsx
  client/my-sites/theme/theme-style-variations/index.tsx
  client/my-sites/theme/theme-style-variations/style.scss
  packages/design-preview/src/components/index.tsx
  packages/design-preview/src/components/sidebar.tsx
  packages/design-preview/src/components/style-variation.tsx
  packages/design-preview/src/components/style.scss
  packages/global-styles/src/components/global-styles-variations/index.tsx
  packages/global-styles/src/components/global-styles-variations/style.scss
Labels: [Status] Needs Review

#77542 Subscription manager: Make action bar behave better on mobile
  client/landing/subscriptions/components/tab-views/comments/comments.tsx
  client/landing/subscriptions/components/tab-views/sites/sites.tsx
  client/landing/subscriptions/styles/styles.scss
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#77552 Show commission fee at Earn page
  client/my-sites/earn/components/commission-fees.tsx
  client/my-sites/earn/home.tsx
  client/my-sites/earn/memberships/index.jsx
  client/my-sites/earn/memberships/style.scss
  client/my-sites/earn/style.scss
Labels: [Status] Needs Review, Earn

#77739 Subscription Management: Add Manage Purchase button on individual site subscription page.
  client/landing/subscriptions/components/site-subscription-page/site-subscription-details.tsx
  client/landing/subscriptions/components/site-subscription-page/site-subscription-helpers.tsx
  client/landing/subscriptions/components/site-subscription-page/styles.scss
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#77660 Site transfers: Display notice on transfer success
  client/sites-dashboard/components/sites-dashboard.tsx
Labels: [Status] Needs Review, Site Transfers i1

#77214 ESLint: Enable `@tanstack/eslint-plugin-query`
  .eslintrc.js
  package.json
  yarn.lock
Labels: Framework, [Status] In Progress, [Status] Needs Review, DO NOT MERGE, Code Style

#77545 Update font of plans header
  client/my-sites/plans/components/plans-header/index.tsx
Labels: [Status] Needs Review

#77738 `useFollowerQuery`: fix `queryKey` eslint violations
  client/data/followers/use-follower-query.js
Labels: [Status] Needs Review, [Type] Janitorial, Data, Code Style

#77714 Hosting signup: display "Creating your account" in the progress bar
  client/signup/reskinned-processing-screen/index.jsx
Labels: [Status] Needs Review, Signup, Social Signup, Reviewer Can Merge, Hosting onboarding i2

#77735 Site Transfers: Fix font style and font size for site transfers
  client/my-sites/site-settings/site-owner-transfer/site-owner-transfer.tsx
  client/my-sites/site-settings/site-owner-transfer/site-owner-user-search.tsx
Labels: [Status] Needs Review, [Type] Task, Site Transfers i1

#77704 Checkout: update 2-year plan upsell card text
  client/my-sites/checkout/composite-checkout/components/checkout-sidebar-plan-upsell/index.tsx
Labels: [Status] Needs Review, Checkout

#77744 Fix regression: fix selector for applying color palette
  client/jetpack-connect/style.scss
Labels: [Status] Needs Review

#77737 Sharing Preview Pane | Fix WSOD when Mastodon is not enabled
  client/blocks/sharing-preview-pane/index.jsx
Labels: [Type] Bug, [Status] Needs Review

#77621 Blog Onboarding: Add loading state for domains selections
  client/components/domains/domain-registration-suggestion/index.jsx
  client/components/domains/domain-search-results/index.jsx
  client/components/domains/featured-domain-suggestions/index.jsx
  client/components/domains/register-domain-step/index.jsx
  client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-domain/index.tsx
Labels: [Status] Needs Review

#77723 Hosting onboarding i2: After creating a hosted site, wait in the stepper until the atomic transfer is complete
  client/landing/stepper/declarative-flow/internals/components/step-route/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/index.tsx
  client/landing/stepper/declarative-flow/new-hosted-site-flow.ts
  client/landing/stepper/declarative-flow/registered-flows.ts
  client/landing/stepper/declarative-flow/transferring-hosted-site-flow.ts
  packages/onboarding/src/utils/flows.ts
Labels: [Status] Needs Review, Hosting onboarding i2

#77750 Post-Likes Popover - Fix styles for the has display names state.
  client/blocks/post-likes/style.scss
Labels: [Status] Needs Review

#77701 Blog onboarding: Redirect users with sites to theme selection on design-first flow
  client/landing/stepper/declarative-flow/design-first.ts
Labels: [Status] Needs Review

#77693 Fixes an error with redux in the Blaze Dashboard app
  apps/blaze-dashboard/package.json
  yarn.lock
Labels: [Status] Needs Review

#77702 URL Search component: Fix browser hard refreshing on search param update
  client/lib/url-search/index.js
  client/lib/url-search/test/index.js
Labels: [Status] Needs Review

#77521 Backup: Redirect from backup plugin to wp-admin on connect when site has a backup plan
  client/jetpack-connect/authorize.js
Labels: [Status] Ready to Merge

#77588 Hosting onboarding: allow importing a site without specifying a target WPCOM site
  client/blocks/import/capture/capture-input.tsx
  client/blocks/import/capture/index.tsx
  client/blocks/importer/wordpress/import-everything/index.tsx
  client/landing/stepper/declarative-flow/import-hosted-site.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/import-with-site-address/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import-with-site-address/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/import/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/importer/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-creation-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-options/new-hosted-site-options.tsx
  client/landing/stepper/declarative-flow/registered-flows.ts
  client/landing/stepper/hooks/use-get-site-suggestions-query.ts
  client/sites-dashboard/hooks/use-sites-dashboard-import-site-url.ts
  packages/onboarding/src/utils/flows.ts
Labels: [Status] Needs Review, Import, Hosting onboarding i2

#77537 Reader: Tidy up Search sites sidebar styles
  client/blocks/reader-avatar/index.jsx
  client/blocks/reader-subscription-list-item/index.jsx
  client/blocks/reader-subscription-list-item/placeholder.jsx
  client/blocks/reader-subscription-list-item/style.scss
  client/reader/search-stream/style.scss
Labels: [Status] Needs Review

#77742 Reader: Revert passing post ID to related sites in post stream
  client/blocks/reader-feed-header/index.jsx
  client/blocks/reader-post-actions/index.jsx
  client/blocks/reader-related-card/index.jsx
  client/blocks/reader-subscription-list-item/index.jsx
  client/blocks/reader-suggested-follows/dialog.jsx
  client/data/reader/use-related-sites.ts
Labels: [Status] Needs Review

#77770 Site creation step: check for the existence of `urlData` before accessing it
  client/landing/stepper/declarative-flow/internals/steps-repository/site-creation-step/index.tsx
Labels: [Type] Bug, [Status] Needs Review, Free Onboarding Flow, Hosting onboarding i2

#77772 Hosting onboarding i2: enable it in wpcalypso
  config/wpcalypso.json
Labels: [Status] Needs Review, Hosting onboarding i2

#77769 Checkout: Add required fields to Google Workspace contact form
  client/components/domains/contact-details-form-fields/g-suite-fields.tsx
  client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx
  client/components/domains/contact-details-form-fields/style.scss
  client/my-sites/checkout/composite-checkout/components/tax-fields.tsx
  client/my-sites/checkout/composite-checkout/test/checkout-extra-tax-fields.tsx
  client/my-sites/checkout/composite-checkout/test/util/index.ts
  client/my-sites/checkout/composite-checkout/types/wpcom-store-state.ts
  packages/wpcom-checkout/src/types.ts
Labels: [Status] Needs Review, Checkout, G Suite, Reviewer Can Merge, Taxes

#77779 Revert "ESLint: Enable `@tanstack/eslint-plugin-query` (#77214)"
  .eslintrc.js
  package.json
  yarn.lock
Labels: [Status] Needs Review

#67007 Make the agency sign-up select dropdown searchable
  client/jetpack-cloud/sections/partner-portal/company-details-form/hooks/use-countries-and-states.ts
  client/jetpack-cloud/sections/partner-portal/company-details-form/index.tsx
  client/jetpack-cloud/sections/partner-portal/company-details-form/style.scss
  client/jetpack-cloud/sections/partner-portal/searchable-dropdown/index.tsx
  client/jetpack-cloud/sections/partner-portal/searchable-dropdown/style.scss
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#77553 `/read/subscriptions`: Render `SiteSubscriptionsManager` component
  client/landing/subscriptions/components/comment-list/comment-row.tsx
  client/landing/subscriptions/components/comment-list/styles.scss
  client/landing/subscriptions/components/site-icon/site-icon.tsx
  client/landing/subscriptions/components/site-icon/styles.scss
  client/landing/subscriptions/components/site-list/index.ts
  client/landing/subscriptions/components/site-list/site-list.tsx
  client/landing/subscriptions/components/site-subscriptions-manager/index.ts
  client/landing/subscriptions/components/site-subscriptions-manager/site-row.tsx
  client/landing/subscriptions/components/site-subscriptions-manager/site-subscriptions-list-actions-bar.tsx
  client/landing/subscriptions/components/site-subscriptions-manager/site-subscriptions-list.tsx
  client/landing/subscriptions/components/site-subscriptions-manager/site-subscriptions-manager-context.tsx
  client/landing/subscriptions/components/site-subscriptions-manager/site-subscriptions-manager.tsx
  client/landing/subscriptions/components/site-subscriptions-manager/styles.scss
  client/landing/subscriptions/components/sort-controls/sort-controls.tsx
  client/landing/subscriptions/components/tab-views/comments/comments.tsx
  client/landing/subscriptions/components/tab-views/comments/styles.scss
  client/landing/subscriptions/components/tab-views/index.ts
  client/landing/subscriptions/components/tab-views/sites/index.tsx
  client/landing/subscriptions/components/tab-views/sites/sites.tsx
  client/landing/subscriptions/components/tab-views/styles.scss
  client/landing/subscriptions/components/tab-views/tab-filters/tab-filters.tsx
  client/landing/subscriptions/components/tab-views/tab-view.tsx
  client/landing/subscriptions/components/tabs-switcher/tabs-switcher.tsx
  client/landing/subscriptions/helpers/index.ts
  client/landing/subscriptions/hooks/index.ts
  client/landing/subscriptions/hooks/use-site-subscriptions-filter-options.ts
  client/landing/subscriptions/styles/list-actions-bar.scss
  client/landing/subscriptions/styles/row-title-label.scss
  client/landing/subscriptions/styles/search-component.scss
  client/landing/subscriptions/styles/styles.scss
  client/reader/subscriptions/site-subscriptions-list/index.ts
  client/reader/subscriptions/site-subscriptions-list/site-subscriptions-list.tsx
  client/reader/subscriptions/site-subscriptions-list/styles.scss
  client/reader/subscriptions/subscription-manager/styles.scss
  client/reader/subscriptions/subscription-manager/subscription-manager.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
  packages/data-stores/src/reader/queries/index.ts
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal

#77754 Email stats: Remove the bar below the chart
  client/my-sites/stats/stats-email-chart-tabs/index.jsx
Labels: [Status] Needs Review, Newsletter Stats

#77668 happy-blocks: Fix translations relative path for RTL locales
  apps/happy-blocks/index.php
Labels: [Type] Bug, [Status] Needs Review, i18n

#77728 Blog onboarding: Fix tracks event for plan step
  client/landing/stepper/declarative-flow/internals/analytics/record-submit-step.ts
Labels: [Status] Needs Review

#77726 Site Transfers: Enable ownerhsip transfers for Atomic sites
  client/state/selectors/can-current-user-start-site-owner-transfer.ts
Labels: [Status] Needs Review, Site Transfers i1

#77577 Domains: Redirect user to "Use a domain I own" flow in domain search results page
  client/my-sites/domains/domain-search/index.jsx
Labels: [Status] Needs Review

#77775 Backup: add defaultProps and propTypes to ActionButtons component
  client/components/jetpack/daily-backup-status/action-buttons.jsx
  client/components/jetpack/daily-backup-status/test/action-buttons.jsx
Labels: [Status] Ready to Merge

#77499 Help Center: Refactor Zendesk Messaging hooks
  client/components/jetpack/jetpack-presales-chat-widget/index.tsx
  client/components/jetpack/portal-nav/index.tsx
  client/components/presales-zendesk-chat/index.tsx
  client/components/presales-zendesk-chat/test/index.js
  client/lib/jetpack/use-jp-presales-availability-query.ts
  client/lib/presales-chat/index.ts
  client/my-sites/checkout/composite-checkout/components/checkout-help-link.tsx
  client/my-sites/plans/jetpack-plans/product-store/index.tsx
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
  packages/data-stores/src/help-center/actions.ts
  packages/data-stores/src/support-queries/types.ts
  packages/help-center/src/components/help-center-contact-form.tsx
  packages/help-center/src/components/help-center-contact-page.tsx
  packages/help-center/src/components/help-center-content.tsx
  packages/help-center/src/components/help-center-inline-chat.tsx
  packages/help-center/src/components/help-center.tsx
  packages/help-center/src/hooks/index.ts
  packages/help-center/src/hooks/use-chat-status.ts
  packages/help-center/src/hooks/use-chat-widget.ts
  packages/help-center/src/hooks/use-messaging-auth.ts
  packages/help-center/src/hooks/use-messaging-availability.ts
  packages/help-center/src/hooks/use-should-render-chat-option.tsx
  packages/help-center/src/hooks/use-zendesk-messaging.ts
  packages/help-center/src/styles.scss
Labels: [Status] Needs Review, Help Center

#77755 Update variant dropdown for multiple-year plans to display discounts
  client/my-sites/checkout/composite-checkout/components/item-variation-picker/variant-dropdown-price.tsx
Labels: Jetpack, [Status] Needs Review, Checkout

#77767 BackupBrowser: Add backup file browser page scaffolding
  client/my-sites/backup/backup-contents-page/index.tsx
  client/my-sites/backup/backup-contents-page/style.scss
  client/my-sites/backup/controller.js
  client/my-sites/backup/index.js
  client/my-sites/backup/paths.ts
  config/development.json
  config/jetpack-cloud-development.json
Labels: [Status] Ready to Merge, Jetpack Backup

#77816 Disable github-integration-i2 feature flag
  config/development.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Reviewer Can Merge

#77804 Pattern Assembler: Fix broken previews when the assets are failed to load
  packages/block-renderer/src/components/block-renderer-container.tsx
  packages/block-renderer/src/utils/load-scripts.ts
  packages/block-renderer/src/utils/load-styles.ts
Labels: [Status] Needs Review

#77703 Stats: Subscribers overview rename subscribersData to subscribersDataArrays
  client/my-sites/stats/stats-subscribers-overview/index.tsx
Labels: Stats, [Status] Needs Review

#77806 Stats: Integrate module settings API to the highlights settings panel for period toggling
  client/my-sites/stats/highlights-section/index.tsx
  client/my-sites/stats/site.jsx
  client/state/action-types.ts
  client/state/data-layer/wpcom/sites/stats/module-settings/index.ts
  client/state/stats/module-settings/actions.ts
  client/state/stats/module-settings/reducer.ts
  client/state/stats/module-settings/schema.ts
  client/state/stats/module-settings/selectors.ts
  client/state/stats/reducer.js
Labels: Stats, [Status] Needs Review, Odyssey Stats

#77778 Stats: Add static page modules show/hide settings
  client/blocks/stats-navigation/index.js
  client/blocks/stats-navigation/style.scss
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  packages/components/src/highlight-cards/style.scss
Labels: Stats, [Status] Needs Review, Odyssey Stats

#77697 Make BlazePress Posts screen responsive
  client/my-sites/promote-post-i2/components/campaigns-table/style.scss
  client/my-sites/promote-post-i2/components/post-item/style.scss
  client/my-sites/promote-post-i2/components/posts-list-banner/style.scss
  client/my-sites/promote-post-i2/components/search-bar/style.scss
  client/my-sites/promote-post-i2/style.scss
Labels: [Status] Needs Review

#77821 Import: fix cache issue on reselect the same site in site picker
  client/blocks/importer/hooks/use-site-can-migrate.ts
  client/blocks/importer/wordpress/import-everything/pre-migration/index.tsx
Labels: [Status] Needs Review, Migration Plugin i2

#77820 Theme card: Update CSS specificity
  packages/design-picker/src/components/theme-card/style.scss
Labels: [Status] Needs Review

#77743 Assembler: Survey Modal
  client/components/banner/index.jsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-main.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/survey/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/survey/survey.scss
Labels: [Status] Needs Review

#77354 Update Jetpack tests for Premium Content block rename
  packages/calypso-e2e/src/lib/blocks/block-flows/index.ts
  packages/calypso-e2e/src/lib/blocks/block-flows/paid-content.ts
  test/e2e/specs/blocks/blocks__jetpack-grow.ts
  test/e2e/specs/blocks/shared/block-smoke-testing.ts
Labels: [Status] Needs Review

#77793 Import flow: Improve logic of showing loading screen
  client/landing/stepper/declarative-flow/internals/steps-repository/importer/index.tsx
Labels: [Status] Needs Review, Migration Plugin i2

#77442 Migrate remaining plan notices to the Plans2023 Grid
  client/my-sites/plans-features-main/components/plan-notice.tsx
  client/my-sites/plans-features-main/components/test/plan-notice.tsx
  client/my-sites/plans-features-main/index.jsx
  client/my-sites/plans-features-main/test/index.jsx
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#77788 Jetpack Pro Dashboard: refactor the NotificationSettings component into multiple smaller components
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/form-content/email-notification.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/form-content/footer.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/form-content/mobile-push-notification.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/form-content/notification-duration.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#77825 Jetpack Pro Dashboard: Change the verify email error code to show correct error message
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/hooks.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#77571 Marketplace Thank You: Add support for SaaS products to redirect to the Thank You page
  client/my-sites/checkout/get-thank-you-page-url/index.ts
  packages/shopping-cart/src/types.ts
Labels: [Status] Needs Review

#77720 Fix - Plan upgrade credit information on the checkout page
  packages/wpcom-checkout/src/checkout-line-items.tsx
Labels: [Status] Needs Review

#77854 Revert "Fix - Plan upgrade credit information on the checkout page"
  packages/wpcom-checkout/src/checkout-line-items.tsx
Labels: [Status] Needs Review

#77298 ActivityPub: skeleton of the UI for enabling the fediverse
  client/my-sites/site-settings/reading-fediverse-settings/JetpackFediverseSettingsSection.js
  client/my-sites/site-settings/reading-fediverse-settings/WpcomFediverseSettingsSection.js
  client/my-sites/site-settings/reading-fediverse-settings/hooks.js
  client/my-sites/site-settings/reading-fediverse-settings/index.jsx
  client/my-sites/site-settings/settings-reading/main.tsx
  config/development.json
  config/horizon.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#77830 Launchpad: Adds the keep building card
  client/my-sites/customer-home/cards/constants.js
  client/my-sites/customer-home/cards/launchpad/keep-building.jsx
  client/my-sites/customer-home/locations/primary/index.jsx
Labels: [Status] Needs Review, Launchpad Checklist Refactor

#77785 Editor modals: align border radius
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/sharing-modal/style.scss
  packages/whats-new/src/style.scss
Labels: [Status] Needs Review

#77037 Implment the GA promo banner in /stats
  client/components/dot-pager/index.jsx
  client/my-sites/stats/mini-carousel/index.jsx
Labels: [Status] Needs Review

#77780 Add /setup/blog binary selection screen for blog onboarding
  client/landing/stepper/declarative-flow/blog.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/blogger-intent/icons.jsx
  client/landing/stepper/declarative-flow/internals/steps-repository/blogger-intent/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/blogger-intent/style.scss
  client/landing/stepper/declarative-flow/registered-flows.ts
Labels: [Status] Needs Review

#77834 Cleanup completed plans grid A/B test
  client/signup/steps/plans/index.jsx
Labels: [Status] Needs Review

#77868 Theme Card: Fix active theme card CSS specificity
  packages/design-picker/src/components/theme-card/style.scss
Labels: [Status] Needs Review

#77771 Import onboarding flow: Mark the return type of the `getUrlData` selector as nullable
  client/blocks/importer/components/importer-drag/index.tsx
  client/blocks/importer/components/importing-pane/importing-pane.tsx
  client/blocks/importer/types.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/import-ready-preview/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import-ready/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer/index.tsx
  client/state/imports/url-analyzer/selectors.ts
Labels: [Status] Needs Review, [Type] Task, Import, Hosting onboarding i2

#77833 Fix/migration reset endpoint
  client/my-sites/migrate/section-migrate.jsx
Labels: [Status] Needs Review, Migration Plugin i2

#77867 Stats: Persist highlights setting notice status
  client/my-sites/stats/highlights-section/index.tsx
  client/my-sites/stats/hooks/use-notice-visibility-mutation.ts
  client/my-sites/stats/hooks/use-notice-visibility-query.ts
  packages/components/src/highlight-cards/weekly-highlight-cards.tsx
Labels: Stats, [Status] Needs Review

#77875 Import: remove site request from loading check to prevent re-render
  client/landing/stepper/declarative-flow/internals/steps-repository/importer/index.tsx
Labels: [Status] Needs Review, Migration Plugin i2

#76667 Use more granular feature checks in Hosting Configuration page
  client/my-sites/hosting/main.js
  client/my-sites/hosting/style.scss
  client/my-sites/hosting/test/index.js
Labels: [Status] In Progress, [Status] Needs Review, [Platform] Atomic, Hosting Configuration, Woo Express Trial

#77880 Theme Showcase: Don't show BCPA CTA under the My Themes tab
  client/components/themes-list/index.jsx
  client/my-sites/themes/theme-showcase.jsx
  client/my-sites/themes/themes-selection.jsx
Labels: [Status] Needs Review

#77813 Design Picker: Fix Premium Badge Style Specificity
  packages/design-picker/src/components/premium-badge/style.scss
Labels: [Status] In Progress, [Status] Needs Review, Design Picker

#77838 Update tailored flows to Product menus for /themes, /plugins and /tags
  packages/wpcom-template-parts/src/universal-header-navigation/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#77865 Update Product menus copy & order for happy-blocks (/support)
  apps/happy-blocks/block-library/universal-header/index.php
Labels: [Status] Needs Review

#77803 Help Center AI quick answers: log the answer source in tracks
  packages/data-stores/src/queries/use-jetpack-search-ai.ts
  packages/help-center/src/components/help-center-gpt.tsx
Labels: [Status] Needs Review

#77885 Ensure private data isn't recored in the `calypso_signup_actions_submit_step` event
  client/state/signup/progress/actions.js
Labels: [Status] Needs Review, Reviewer Can Merge

#77746 Site Transfers: Add margin below Search user and continue button
  client/my-sites/site-settings/site-owner-transfer/site-owner-user-search.tsx
Labels: [Type] Enhancement, [Status] Needs Review, [Type] Task, Site Transfers i1

#77846 Subscribers Page: Introduce `useSubscribersQuery` hook
  client/my-sites/subscribers/queries/index.ts
  client/my-sites/subscribers/queries/use-subscribers-query.tsx
Labels: [Status] Needs Review, Subscribers Page

#77896 Convert ReaderAvatar to TypeScript
  client/blocks/reader-avatar/index.tsx
  client/blocks/site-icon/index.tsx
  client/lib/resize-image-url/index.js
  client/my-sites/media-library/media-file.tsx
  client/my-sites/media-library/media-image.tsx
  client/reader/recommended-sites/recommended-site.tsx
  packages/calypso-url/src/safe-image-url/index.ts
  packages/components/src/gravatar/index.tsx
Labels: [Status] Needs Review, Subscription Management

#77845 reader search popular sites - add follow button
  client/blocks/reader-subscription-list-item/connected.jsx
  client/blocks/reader-subscription-list-item/index.jsx
  client/reader/follow-sources.jsx
  client/reader/search-stream/index.jsx
  client/reader/search-stream/site-results.jsx
  client/reader/search-stream/style.scss
  client/reader/stream/reader-search-sidebar/index.jsx
Labels: [Status] Needs Review

#77907 Reader search - add margin to section nav on smaller viewports
  client/reader/stream/style.scss
Labels: [Status] Needs Review

#77265 removing Coupon code for Akismet checkout
  client/my-sites/checkout/composite-checkout/components/wp-checkout-order-review.tsx
Labels: [Status] Needs Review

#77815 Fix/promote post v2 widescreen layout
  client/my-sites/promote-post-i2/components/campaigns-list/index.tsx
  client/my-sites/promote-post-i2/components/posts-list-banner/index.tsx
  client/my-sites/promote-post-i2/components/posts-list-banner/style.scss
  client/my-sites/promote-post-i2/components/posts-list/index.tsx
  client/my-sites/promote-post-i2/style.scss
Labels: [Status] Needs Review, Blaze

#77866 Stats: Apply module toggling API along with modules layout changing
  client/blocks/stats-navigation/constants.ts
  client/blocks/stats-navigation/index.js
  client/my-sites/stats/grid-layout.scss
  client/my-sites/stats/site.jsx
  client/state/action-types.ts
  client/state/data-layer/wpcom/sites/stats/module-toggles/index.ts
  client/state/stats/module-toggles/actions.ts
  client/state/stats/module-toggles/reducer.ts
  client/state/stats/module-toggles/schema.ts
  client/state/stats/module-toggles/selectors.ts
  client/state/stats/reducer.js
  packages/components/src/highlight-cards/style.scss
Labels: Stats, [Status] Needs Review, Odyssey Stats

#77752 Design Picker: Skip flagged virtual themes from going to SA
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  packages/data-stores/src/starter-designs-queries/use-starter-designs-query.ts
Labels: [Status] Needs Review

#77871 Adjust the mobile style of the sharing modal
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/sharing-modal/style.scss
Labels: [Status] Needs Review

#77930 (chore)(error-tracking)(sentry) Change the `sentry-cli` install command in the `Dockerfile.base` to install the latest stable version
  .teamcity/_self/projects/WPComPlugins.kt
  Dockerfile.base
Labels: [Status] Needs Review

#77931 (chore)(calypso/client)(etk) Update Sentry packages
  apps/editing-toolkit/package.json
  client/package.json
  yarn.lock
Labels: [Status] Needs Review

#77848 Sites: track empty state view
  client/sites-dashboard/controller.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting onboarding i2

#77921 Stats: Add module toggling tooltip
  client/blocks/stats-navigation/index.js
  packages/components/src/highlight-cards/style.scss
Labels: Stats, [Status] Needs Review, Odyssey Stats

#77884 Blogger onboarding binary selection page css fixes
  client/landing/stepper/declarative-flow/internals/steps-repository/blogger-intent/style.scss
Labels: [Status] Needs Review

#77870 Stats: Fixing domain banner position
  client/my-sites/stats/stats-insights/index.jsx
  client/my-sites/stats/stats-subscribers/index.tsx
Labels: Stats, [Status] Needs Review

#77877 Remove siteTitle from dependency store when starting a new flow to avoid managed_subdomain_not_available API error.
  client/landing/stepper/declarative-flow/import-hosted-site.ts
Labels: [Type] Bug, [Status] Needs Review, Import

#77782 Enable search page for logged out users
  client/layout/logged-out.jsx
  client/reader/lib/header-section/index.tsx
  client/reader/search-stream/index.jsx
  client/reader/search-stream/style.scss
  client/reader/search-stream/suggestion-provider.jsx
  client/reader/search/controller.js
  client/reader/search/index.js
  client/reader/style.scss
  client/reader/tag-stream/controller.js
  client/reader/tag-stream/style.scss
  client/sections.js
Labels: [Status] Needs Review

#77892 Pattern Assembler: Use the stylesheet from the activated result to support self-hosted site
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-global-styles/index.php
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/with-theme-assembler-flow.ts
  client/state/themes/actions/activate-theme.js
Labels: [Status] Needs Review

#77849 Signup: store `is_dev_account` property in Tracks
  client/blocks/signup-form/index.jsx
  client/signup/steps/user/index.jsx
  client/state/signup/progress/actions.js
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting onboarding i2

#77902 downtime monitor sms notification change mobile to push
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/form-content/mobile-push-notification.tsx
Labels: [Status] Needs Review, Jetpack Cloud, Reviewer Can Merge

#77851 Hosting flows: add `is_in_hosting_flow` property to `calypso_signup_step_start`
  client/signup/main.jsx
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting onboarding i2

#77498 Update image upload copy on website submission step
  client/signup/steps/website-content/section-types/contact-page-details.tsx
  client/signup/steps/website-content/section-types/default-page-details.tsx
Labels: [Status] Needs Review, [Status] String Freeze, BuiltByExpress

#77938 Jetpack Pro Dashboard: Add a feature flag for the monitor SMS notification settings project
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#77905 Subscribers Page: Remove subscriber mutation
  client/my-sites/subscribers/helpers/index.ts
  client/my-sites/subscribers/mutations/index.ts
  client/my-sites/subscribers/mutations/use-subscriber-remove-mutation.ts
  client/my-sites/subscribers/queries/use-subscribers-query.tsx
  client/my-sites/subscribers/types/index.ts
Labels: [Status] In Progress

#77952 Remove unnecessary z-index style from plan badge
  client/my-sites/plan-features-2023-grid/style.scss
Labels: [Status] Needs Review, Quick Fix

#77904 Downtime Monitor add SMS section to the modal
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/form-content/sms-notification.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
Labels: [Status] Needs Review, Jetpack Cloud, Reviewer Can Merge

#77906 Syncing incompatible plugins
  client/my-sites/plugins/plugin-compatibility.js
Labels: Build Maintenance

#77897 Hosting Configuration: Only show data center picker when eligible
  client/blocks/eligibility-warnings/index.tsx
Labels: [Type] Bug, [Status] Needs Review, Reviewer Can Merge, Hosting Configuration

#77950 Subscription Management: Add locale support on route for individual site subscription page.
  client/landing/subscriptions/index.tsx
Labels: [Status] Needs Review, Subscription Management, [SM] Calypso Portal
