Repository Automattic/wp-calypso, pull requests merged in 2023-01, with the labels that each got.

#71489 Add SitesGridItem to DevDocs for easier testing different cases
  client/devdocs/design/index.jsx
  client/sites-dashboard/components/docs/sample-site-data.jsx
  client/sites-dashboard/components/sites-grid-item/README.md
  client/sites-dashboard/components/sites-grid-item/docs/example.jsx
  client/sites-dashboard/components/sites-table-row/docs/example.jsx
Labels: [Status] Needs Review

#71585 Reading Settings: Add 'For each new post, include...' RSS feed setting
  client/my-sites/site-settings/reading-rss-feed-settings/ExcerptSetting.tsx
  client/my-sites/site-settings/reading-rss-feed-settings/index.tsx
  client/my-sites/site-settings/settings-reading/main.tsx
Labels: [Status] Needs Review

#71575 Reading Settings: Add 'Related Posts' setting
  client/my-sites/marketing/traffic/index.js
  client/my-sites/site-settings/reading-site-settings/RelatedPostsSetting.tsx
  client/my-sites/site-settings/reading-site-settings/index.tsx
  client/my-sites/site-settings/related-posts/index.jsx
  client/my-sites/site-settings/settings-reading/main.tsx
Labels: [Status] Reviewer Approved

#71533 eCommerce flow: Added geolocation to storeProfiler step
  client/landing/stepper/declarative-flow/internals/steps-repository/store-profiler/index.tsx
Labels: [Status] Needs Review, Stepper

#70641 New Welcome Tour Slide for Site Editor
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-steps.tsx
  apps/editing-toolkit/jest.config.js
  apps/editing-toolkit/package.json
  client/gutenberg/editor/calypsoify-iframe.tsx
  client/gutenberg/editor/controller.js
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  packages/tour-kit/src/types.ts
  packages/tour-kit/src/variants/wpcom/components/wpcom-tour-kit-step-card-navigation.tsx
  packages/tour-kit/src/variants/wpcom/components/wpcom-tour-kit-step-card.tsx
  packages/tour-kit/src/variants/wpcom/styles.scss
  yarn.lock
Labels: [Status] Needs Review, [Status] String Freeze

#71568 Add data flow for email open stats country view
  client/my-sites/stats/geochart/index.jsx
  client/state/stats/emails/actions.js
  client/state/stats/emails/selectors.js
  client/state/stats/lists/utils.js
  packages/wpcom.js/src/lib/site.js
Labels: [Status] Needs Review

#71479 Jetpack Pro Dashboard: implement validation for notification settings form
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/style.scss
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#71587 Fix unified design picker mShot config
  packages/design-picker/src/components/unified-design-picker.tsx
  packages/design-picker/src/utils/available-designs.ts
Labels: [Status] Needs Review

#71607 BBE: Do not set theme in flow
  client/lib/signup/step-actions/index.js
  client/signup/config/steps-pure.js
  client/signup/config/steps.js
Labels: [Status] Needs Review

#71472 Tailored Ecommerce: Remove the post-checkout storeAddress step for tailored ecommerce
  client/landing/stepper/declarative-flow/tailored-ecommerce-flow.ts
Labels: [Status] Needs Review, DO NOT MERGE, Plans: eCommerce

#71471 Ecommerce Tailored Flow: Remove the intro step
  client/landing/stepper/declarative-flow/internals/steps-repository/store-profiler/index.tsx
  client/landing/stepper/declarative-flow/tailored-ecommerce-flow.ts
Labels: [Status] Needs Review, DO NOT MERGE, Plans: eCommerce

#71620 Fixed Unique Opens Count in Email Stats
  client/my-sites/stats/controller.jsx
  client/my-sites/stats/stats-email-chart-tabs/utility.js
  client/my-sites/stats/stats-email-open-detail/index.jsx
Labels: [Status] Needs Review

#71629 Fix the email opens summary + make it clickable
  client/state/stats/lists/actions.js
  client/state/stats/lists/utils.js
Labels: [Status] Needs Review

#71351 CI: streamline the `WPComPlugin` build configuration to reduce queue sizes.
  .teamcity/_self/lib/wpcom/WPComPluginBuild.kt
Labels: [Pri] Normal, [Status] Needs Review

#71534 Stats: remove "Unknown Search Terms" from the Search Terms stats module
  client/state/stats/lists/test/utils.js
  client/state/stats/lists/utils.js
Labels: Stats, [Status] Needs Review

#71579 Odyssey Stats: Apply Jetpack colors
  apps/odyssey-stats/src/app.jsx
  apps/odyssey-stats/src/app.scss
  apps/odyssey-stats/src/styles/theme.scss
  apps/odyssey-stats/src/styles/wp-admin.scss
Labels: [Type] Enhancement, Stats, [Status] Needs Review

#71644 Fix warning when running e2e decrypt
  packages/calypso-e2e/package.json
Labels: [Type] Enhancement, [Status] Needs Review

#71649 Revert "CI: streamline the `WPComPlugin` build configuration to reduce queue sizes."
  .teamcity/_self/lib/wpcom/WPComPluginBuild.kt
Labels: [Status] Needs Review

#71515 Remove the middle destination mechanism from the signup framework.
  client/signup/config/flows.js
  client/signup/main.jsx
Labels: [Status] Needs Review

#71563 Theme Showcase: Implement Theme Preview modal component
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/components/premium-badge/index.js
  client/components/premium-badge/style.scss
  client/components/theme-preview-modal/index.tsx
  client/components/theme-preview-modal/navigation.tsx
  client/components/theme-preview-modal/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/my-sites/themes/theme-preview.jsx
  client/state/sites/hooks/use-premium-global-styles.ts
  client/state/sites/hooks/use-site-global-styles-status.ts
  client/state/themes/selectors/is-theme-premium.js
  packages/design-picker/src/components/premium-badge/index.tsx
  packages/design-preview/src/components/index.tsx
  packages/design-preview/src/components/sidebar.tsx
  packages/design-preview/src/components/style-variation.tsx
  packages/design-preview/src/components/style.scss
Labels: [Status] Needs Review, Theme Showcase

#71624 Stats: Release the All-time insights section on the Insights page
  client/my-sites/stats/all-time-views-section/index.tsx
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Stats, [Status] Ready to Merge

#71658 Refetch data when date query argument changes
  client/components/data/query-email-stats/index.jsx
Labels: [Status] Needs Review

#71417 Introduce block-renderer to site assembler to improve performance
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-assembler-container.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-large-preview.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-large-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-renderer.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-renderer.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/patterns-data.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/style.scss
  client/landing/stepper/hooks/use-theme-details.ts
  client/package.json
  packages/block-renderer/.eslintrc.js
  packages/block-renderer/README.md
  packages/block-renderer/jest.config.js
  packages/block-renderer/package.json
  packages/block-renderer/src/components/block-renderer-container.scss
  packages/block-renderer/src/components/block-renderer-container.tsx
  packages/block-renderer/src/components/block-renderer-provider.tsx
  packages/block-renderer/src/components/index.tsx
  packages/block-renderer/src/components/pattern-renderer.tsx
  packages/block-renderer/src/components/patterns-renderer-context.tsx
  packages/block-renderer/src/components/patterns-renderer-provider.tsx
  packages/block-renderer/src/constants.ts
  packages/block-renderer/src/global.d.ts
  packages/block-renderer/src/hooks/use-block-renderer-settings.ts
  packages/block-renderer/src/hooks/use-rendered-patterns.ts
  packages/block-renderer/src/index.tsx
  packages/block-renderer/src/types.ts
  packages/block-renderer/tsconfig-cjs.json
  packages/block-renderer/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review

#71648 VideoPress Onboarding: Move theme chooser up before account creation
  client/landing/stepper/declarative-flow/videopress.ts
Labels: [Status] Needs Review

#71667 VideoPress Onboarding: updated failing onboarding e2e test after step move
  test/e2e/specs/onboarding/setup__videopress.ts
Labels: [Status] Needs Review

#71580 Stats polish: Posting Activity UI in the Insights page
  client/layout/style.scss
  client/my-sites/stats/post-trends/day.jsx
  client/my-sites/stats/post-trends/index.jsx
  client/my-sites/stats/post-trends/style.scss
  client/my-sites/stats/stats-insights/index.jsx
  client/my-sites/stats/stats-module/style.scss
Labels: Stats, [Status] Needs Review, [Status] Needs Design Review, [Status] Design Input Requested

#71646 Stats: Fix the toggleable mobile menu for list items
  client/my-sites/stats/stats-list/stats-list-actions.jsx
  client/my-sites/stats/stats-list/stats-list-card.jsx
Labels: Stats, [Status] Ready to Merge

#71674 VideoPress onboarding: update flow order for progress bar
  packages/onboarding/src/flow-progress/use-flow-progress.ts
Labels: [Status] Ready to Merge

#71634 chore: Update encrypted secrets entry for simpleSiteFreePlanUser.
  packages/calypso-e2e/src/secrets/encrypted.enc
Labels: [Status] Needs Review

#71429 Free Flow: Add blog title to free flow createSiteWithCart()
  client/landing/stepper/declarative-flow/internals/steps-repository/site-creation-step/index.tsx
Labels: [Status] Needs Review, Free Onboarding Flow

#71615 Stats: add styling for annual insights table
  client/my-sites/stats/summary/style.scss
Labels: Stats, [Status] Ready to Merge

#71683 Stats: Fixing hover colour for small screens for horizontal bars
  packages/components/src/horizontal-bar-list/style.scss
Labels: Stats, [Status] Needs Review

#71363 Components: Create Circular Progress Bar for Launchpad
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
  packages/components/src/circular-progress-bar/README.md
  packages/components/src/circular-progress-bar/index.tsx
  packages/components/src/circular-progress-bar/style.scss
  packages/components/src/index.ts
Labels: [Status] In Progress, [Status] Needs Review, LaunchPad

#71530 Stats: Adjust post detail layout for FixedNavigationHeader and Highlight cards
  client/blocks/post-likes/index.jsx
  client/components/fixed-navigation-header/index.tsx
  client/my-sites/stats/modernized-layout-styles.scss
  client/my-sites/stats/modernized-stats-table-styles.scss
  client/my-sites/stats/post-detail-highlights-section/style.scss
  client/my-sites/stats/stats-post-detail/index.jsx
Labels: Stats, [Status] Needs Review, [Status] Ready to Merge

#71605 Jetpack Pro Dashboard: Implement API integration to save the notification settings for the selected sites.
  client/data/agency-dashboard/use-fetch-dashboard-sites.ts
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/toggle-activate-monitoring/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/hooks.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#71541 Fix response for home template in /pages for Coming Soon sites
  apps/editing-toolkit/editing-toolkit-plugin/coming-soon/coming-soon.php
Labels: [Status] Needs Review

#71565 Theme showcase: clean up themes/showcase-i4/search-and-filter flag
  client/blocks/jitm/style.scss
  client/my-sites/themes/current-theme/README.md
  client/my-sites/themes/current-theme/index.tsx
  client/my-sites/themes/current-theme/style.scss
  client/my-sites/themes/logged-out.jsx
  client/my-sites/themes/recommended-themes.jsx
  client/my-sites/themes/single-site-jetpack.jsx
  client/my-sites/themes/single-site-wpcom.jsx
  client/my-sites/themes/test/logged-out.jsx
  client/my-sites/themes/theme-showcase.jsx
  client/my-sites/themes/theme-showcase.scss
  client/my-sites/themes/themes-header.scss
  client/my-sites/themes/themes-header.tsx
  client/my-sites/themes/themes-magic-search-card/index.jsx
  client/my-sites/themes/themes-magic-search-card/style.scss
  client/my-sites/themes/themes-magic-search-card/taxonomies-config.js
  client/my-sites/themes/themes-magic-search-card/welcome.jsx
  client/my-sites/themes/trending-themes.jsx
  client/state/themes/selectors/get-outdated-themes.js
  client/state/themes/selectors/get-themes-for-query-ignoring-page.js
  client/state/themes/selectors/index.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Type] Janitorial, Theme Showcase

#71668 Add email stats for devices & clients
  client/my-sites/stats/stats-email-module/index.jsx
  client/my-sites/stats/stats-email-open-detail/index.jsx
  client/my-sites/stats/stats-email-open-detail/style.scss
  client/my-sites/stats/stats-strings.js
  client/state/stats/emails/actions.js
  client/state/stats/lists/utils.js
  packages/wpcom.js/src/lib/site.js
Labels: [Status] Needs Review

#71636 Launchpad: Use share code to bypass sites atomic sites "Coming Soon"
  client/components/site-preview-link/index.tsx
  client/components/site-preview-link/use-site-preview-links.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/launchpad-site-preview.tsx
  client/landing/stepper/hooks/use-site-preview-share-code.ts
Labels: [Status] Needs Review, Simple/Atomic Parity, LaunchPad v1

#71591 Implement the revamped Logged out Plugins header
  client/components/main/index.jsx
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/plugins/plugins-browser/style.scss
  client/my-sites/plugins/search-box-header/index.jsx
  client/my-sites/plugins/search-box-header/style.scss
  client/my-sites/plugins/style.scss
Labels: [Status] Needs Review

#71689 SSH: show old keys instead of spinner when the tab focuses on Hosting Configuration
  client/my-sites/hosting/sftp-card/ssh-key-card.tsx
  client/my-sites/hosting/sftp-card/ssh-keys.tsx
Labels: [Status] Needs Review, Hosting Configuration

#71687 VideoPress Onboarding: Fix 'busy' button style on mobile
  client/signup/videopress-step-wrapper/style.scss
Labels: [Status] Needs Review, VideoPress, [Goal] Onboarding

#71680 Jetpack Cloud Cart Integration - Fix mobile cart alignment
  client/components/jetpack/intro-pricing-banner/hooks/use-bounding-client-rect.ts
  client/components/jetpack/intro-pricing-banner/index.tsx
  client/components/jetpack/intro-pricing-banner/style.scss
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/cloud-cart/index.tsx
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/style.scss
  client/jetpack-cloud/sections/pricing/style.scss
  client/layout/masterbar/masterbar-cart/masterbar-cart-count.scss
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-store-item-info.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#71691 Stats: Fixing year selection when swapping sites
  client/my-sites/stats/annual-highlights-section/index.tsx
Labels: Stats, [Status] Needs Review

#71611 WooExpress Trial: Initial flow framework
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/registered-flows.ts
  client/landing/stepper/declarative-flow/trial-wooexpress-flow.ts
  packages/calypso-products/src/constants/wpcom.ts
  packages/data-stores/src/plans/constants.ts
  packages/onboarding/src/utils/flows.ts
Labels: [Status] Needs Review, [Status] Ready to Merge, Signup, Plans: eCommerce, Stepper

#71684 VideoPress Onboarding: don't show site preview for VideoPress flow if a supported plan has not been purchased
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/launchpad-site-preview.tsx
  packages/data-stores/src/onboard/actions.ts
  packages/data-stores/src/site/types.ts
Labels: [Status] Needs Review

#71728 E2E: update passwords for test user accounts.
  packages/calypso-e2e/src/secrets/encrypted.enc
Labels: [Status] Needs Review

#71735 Remove unused slack notification build
  .circleci/config.yml
Labels: [Status] Needs Review

#71676 Stats: fix some details on the Posting Activity section
  client/components/tooltip/style.scss
  client/my-sites/stats/post-trends/day.jsx
  client/my-sites/stats/post-trends/style.scss
Labels: Stats, [Status] Needs Review

#71719 Add context to "Discover" when referring to credit card name
  client/lib/checkout/payment-methods.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#71739 chore: update the Desktop E2E test user.
  .teamcity/_self/projects/DesktopApp.kt
  packages/calypso-e2e/src/secrets/encrypted.enc
  packages/calypso-e2e/src/secrets/secrets-manager.ts
Labels: [Status] Needs Review

#71738 [HOLD] desktop: rotate secrets
  .teamcity/_self/projects/DesktopApp.kt
  desktop/resource/calypso/secrets.json.enc
  desktop/resource/certificates/mac.p12.enc
  desktop/resource/certificates/win.p12.enc
Labels: [Status] Needs Review

#71686 Stats Page Redesign: Update table row hover colors
  client/my-sites/stats/stats-module/style.scss
Labels: Stats, [Status] Needs Review

#71652 Theme Showcase: Show theme preview modal with selected style variation
  client/components/theme-preview-modal/index.tsx
  client/components/theme/index.jsx
  client/components/theme/more-button.jsx
  client/components/themes-list/index.jsx
  client/my-sites/themes/helpers.js
  client/my-sites/themes/theme-preview.jsx
  client/my-sites/themes/themes-selection.jsx
  client/state/themes/actions/set-theme-preview-options.js
  client/state/themes/reducer.js
  packages/design-picker/src/components/style-variation-badges/index.tsx
Labels: [Status] Needs Review

#71600 Add ability to render custom list items in Banner component
  client/components/banner/README.md
  client/components/banner/docs/example.jsx
  client/components/banner/index.jsx
Labels: [Status] Needs Review

#71659 Jetpack Pro Dashboard: Implement email validation for monitor notification settings
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#71702 Virtual page: Hide description and popover when the template is not able to resolve
  client/my-sites/pages/virtual-page/index.tsx
Labels: [Type] Bug, [Status] Needs Review

#71527 Site Assembler: Add scroll behavior to pattern large preview
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-assembler-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-large-preview.tsx
Labels: [Status] Needs Review

#71692 Append text to Calypso's Zendesk ticket creation to flag WCCOM NUX
  client/signup/config/flows.js
  packages/help-center/src/components/help-center-contact-form.tsx
Labels: [Status] Needs Review

#71753 Revert 71583 update/pricing grid launch to en
  client/my-sites/plan-features-2023-grid/header-price.jsx
  client/my-sites/plan-features-2023-grid/index.jsx
  client/my-sites/plan-price/index.jsx
  client/my-sites/plans-features-main/index.jsx
  client/signup/config/flows-pure.js
  client/signup/main.jsx
  client/signup/steps/plans/index.jsx
Labels: [Status] Needs Review

#71656 Better click target for domain management three-dot menu
  client/my-sites/domains/domain-management/list/domain-row.scss
  package.json
Labels: [Status] Needs Review

#71378 New Pricing Grid: Integration PR
  client/assets/images/onboarding/bloomberg-logo.svg
  client/assets/images/onboarding/cnn-logo.svg
  client/assets/images/onboarding/condenast-logo.svg
  client/assets/images/onboarding/disney-logo.svg
  client/assets/images/onboarding/facebook-logo.svg
  client/assets/images/onboarding/salesforce-logo.svg
  client/assets/images/onboarding/slack-logo.svg
  client/assets/images/onboarding/time-logo.svg
  client/assets/images/onboarding/vip-logo.svg
  client/assets/images/onboarding/woo-logo.svg
  client/lib/plans/features-list.js
  client/my-sites/plan-features-2023-grid/actions.jsx
  client/my-sites/plan-features-2023-grid/billing-timeframe.jsx
  client/my-sites/plan-features-2023-grid/features.jsx
  client/my-sites/plan-features-2023-grid/header-price.jsx
  client/my-sites/plan-features-2023-grid/header.jsx
  client/my-sites/plan-features-2023-grid/index.jsx
  client/my-sites/plan-features-2023-grid/item.jsx
  client/my-sites/plan-features-2023-grid/style.scss
  client/my-sites/plan-features-2023-grid/util.ts
  client/my-sites/plan-features-comparison/actions.jsx
  client/my-sites/plan-features-comparison/style.scss
  client/my-sites/plan-features/style.scss
  client/my-sites/plan-price/index.jsx
  client/my-sites/plans-features-main/index.jsx
  client/my-sites/plans-features-main/style.scss
  client/signup/main.jsx
  client/signup/steps/plans/index.jsx
  client/signup/steps/plans/style.scss
  client/signup/style.scss
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/constants/types.ts
  packages/calypso-products/src/constants/wpcom.ts
  packages/calypso-products/src/main.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/types.ts
  packages/calypso-products/test/plan-lookups.js
Labels: [Status] Needs Review

#71744 Update: Create new random passwords for all runtime-created E2E accounts
  packages/calypso-e2e/package.json
  packages/calypso-e2e/src/data-helper.ts
  packages/calypso-e2e/src/secrets/encrypted.enc
  packages/calypso-e2e/src/secrets/secrets-manager.ts
  packages/calypso-e2e/src/secrets/types.ts
  test/e2e/docs/config_values.md
  yarn.lock
Labels: [Status] Needs Review

#71643 i18n: Wrap "Join thousands of others" Earn paragraph for translation
  client/my-sites/earn/memberships/index.jsx
Labels: [Status] Needs Review, [Status] String Freeze

#71769 Chart: Fix a bug in the detection of empty charts
  client/components/chart/index.jsx
Labels: [Type] Bug, Stats, [Status] Ready to Merge

#71715 Stats: Deprecate the feature flag "stats/all-time-views"
  client/my-sites/stats/all-time-views-section/style.scss
  client/my-sites/stats/post-detail-table-section/style.scss
  client/my-sites/stats/stats-insights/index.jsx
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Stats, [Status] Needs Review

#71710 Stats: Deprecate the feature flag "stats/new-main-chart"
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-email-chart-tabs/index.jsx
  client/my-sites/stats/stats-insights/index.jsx
  client/my-sites/stats/wordads/index.jsx
  client/my-sites/store/app/store-stats/index.js
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Stats, [Status] Needs Review

#71747 Block Renderer: Support rendering customized site info
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-assembler-container.tsx
  packages/block-renderer/src/components/patterns-renderer-provider.tsx
  packages/block-renderer/src/hooks/use-rendered-patterns.ts
  packages/block-renderer/src/index.tsx
  packages/block-renderer/src/types.ts
Labels: [Status] Needs Review

#71784 Site Assembler: Enable the pattern-assembler/client-side-render flag on dev
  config/development.json
Labels: [Status] Needs Review

#71517 Users management: Update users profiles
  client/my-sites/people/controller.js
  client/my-sites/people/edit-team-member-form/edit-user-form.jsx
  client/my-sites/people/edit-team-member-form/index.jsx
  client/my-sites/people/edit-team-member-form/style.scss
  client/my-sites/people/index.js
  client/my-sites/people/invite-people/index.jsx
  client/my-sites/people/people-invite-details/index.jsx
  client/my-sites/people/people-invite-details/style.scss
  client/my-sites/people/people-invite-details/test/index.jsx
  client/my-sites/people/people-list-item/index.jsx
  client/my-sites/people/people-list-item/style.scss
  client/my-sites/people/people-profile/index.jsx
  client/my-sites/people/people-profile/style.scss
  client/my-sites/people/subscriber-details/index.tsx
  client/my-sites/people/subscriber-details/style.scss
  client/my-sites/people/subscribers-team/index.tsx
  client/my-sites/people/subscribers/index.tsx
  client/my-sites/people/team-invites-accepted/index.tsx
  client/my-sites/people/team-invites-accepted/style.scss
  client/my-sites/people/team-invites/index.tsx
Labels: [Status] Needs Review, User Management Revamp

#71734 i18n: Localize the nav URLs on the logged-out themes and plugins pages
  client/layout/universal-navbar-footer/index.tsx
  client/layout/universal-navbar-header/index.jsx
  packages/i18n-utils/src/localize-url.tsx
  packages/i18n-utils/src/test/localize-url.js
Labels: [Status] Needs Review

#71801 Fix pre-release e2e test - button selector
  packages/calypso-e2e/src/lib/pages/people-page.ts
Labels: [Status] Needs Review, User Management Revamp

#71768 WooExpress Trial: Ensure that wooexpress trial sites are created as Private
  client/landing/stepper/declarative-flow/internals/steps-repository/site-creation-step/index.tsx
Labels: [Status] Ready to Merge, Stepper, WooExpress

#71742 Update site disconnected filter key
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
  client/my-sites/activity/filterbar/type-selector/issue-type-selector.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#71475 Reading Settings: Add new email template text settings
  client/my-sites/site-settings/reading-newsletter-settings/EmailsTextSetting.tsx
  client/my-sites/site-settings/reading-newsletter-settings/index.tsx
  client/my-sites/site-settings/settings-reading/main.tsx
  client/my-sites/site-settings/style.scss
Labels: [Status] In Progress, [Status] Needs Review

#71720 Users management: Update user details screen
  client/my-sites/people/edit-team-member-form/edit-user-form.jsx
  client/my-sites/people/edit-team-member-form/index.jsx
  client/my-sites/people/people-invite-details/index.jsx
Labels: [Status] Needs Review, User Management Revamp

#71737 PlanPrice: convert to TypeScript and improve strip-zeros behavior
  client/blocks/importer/wordpress/import-everything/confirm-upgrade-plan.tsx
  client/my-sites/plan-price/index.jsx
  client/my-sites/plan-price/index.tsx
  client/my-sites/plan-price/test/index.js
  client/my-sites/plans-comparison/plans-comparison-col-cta.tsx
  client/my-sites/plans-comparison/plans-comparison.tsx
  client/my-sites/plans/jetpack-plans/product-store/pricing-breakdown/render-price.tsx
  client/my-sites/plans/jetpack-plans/upsell/index.tsx
Labels: [Status] Needs Review

#71771 chore: remove older password hashes from TeamCity configuration.
  .teamcity/settings.kts
Labels: [Status] Needs Review

#71803 Jetpack Cloud Cart integration - split changes in layout and mini-cart folder
  client/layout/masterbar/masterbar-cart/masterbar-cart-button.tsx
  client/layout/masterbar/masterbar-cart/masterbar-cart-count.scss
  client/layout/masterbar/masterbar-cart/masterbar-cart-count.tsx
  packages/mini-cart/src/mini-cart.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#71387 format-currency: Change formatCurrency to use locale
  client/components/forms/docs/example.jsx
  client/components/gsuite/gsuite-price/test/__snapshots__/index.js.snap
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/lib/gsuite/utils/format-price.js
  client/my-sites/plan-price/test/index.js
  client/my-sites/store/app/store-stats/test/utils.js
  packages/format-currency/CHANGELOG.md
  packages/format-currency/README.md
  packages/format-currency/package.json
  packages/format-currency/src/currencies.ts
  packages/format-currency/src/index.ts
  packages/format-currency/src/number-format.ts
  packages/format-currency/src/types.ts
  packages/format-currency/test/index.ts
  packages/format-currency/test/number-format.ts
Labels: [Status] Needs Review

#70588 Cart on Jetpack cloud Pricing page
  client/components/jetpack/intro-pricing-banner/hooks/use-bounding-client-rect.ts
  client/components/jetpack/intro-pricing-banner/index.tsx
  client/components/jetpack/intro-pricing-banner/style.scss
  client/jetpack-cloud/sections/pricing/controller.tsx
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/cloud-cart/cloud-cart-icon.tsx
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/cloud-cart/empty-cart.scss
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/cloud-cart/empty-cart.tsx
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/cloud-cart/index.tsx
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/index.tsx
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/style.scss
  client/jetpack-cloud/sections/pricing/style.scss
  client/jetpack-cloud/style.scss
  client/my-sites/plans/jetpack-plans/product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-card/product-button-label.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/index.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/style.scss
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-shopping-cart-tracker.ts
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-store-item-info.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/all-items.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/most-popular.tsx
  client/my-sites/plans/jetpack-plans/product-store/simple-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/simple-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/types.ts
  client/my-sites/plans/jetpack-plans/selector.tsx
  client/state/sites/selectors/index.js
  client/state/sites/selectors/is-jetpack-cloud-cart-enabled.ts
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
  packages/calypso-products/src/product-values.ts
Labels: [Status] Needs Review

#71781 Theme Showcase: Enable theme card's more button
  client/components/theme/index.jsx
  client/my-sites/themes/theme-showcase.scss
Labels: [Status] Needs Review, Theme Showcase

#71754 Theme Showcase: Activate themes with the selected style variation
  client/components/theme-preview-modal/index.tsx
  client/my-sites/theme/main.jsx
  client/my-sites/themes/theme-preview.jsx
  client/my-sites/themes/themes-selection.jsx
  client/state/themes/actions/activate-theme.js
  client/state/themes/actions/set-theme-preview-options.js
  client/state/themes/actions/theme-activated.js
  client/state/themes/reducer.js
  client/state/themes/test/actions.js
Labels: [Status] Needs Review, Theme Showcase

#71790 Chart Component: Fix bug in empty state test.
  client/components/chart/index.jsx
Labels: [Type] Bug, Stats, [Status] Ready to Merge, Components

#71751 Add user came through info to happy chat
  apps/happychat/src/getUserInfo.ts
  packages/help-center/src/components/help-center-inline-chat.tsx
Labels: [Status] Needs Review

#71755 Stats: Refactor navigation arrows into a shared component.
  client/my-sites/stats/annual-highlights-section/style.scss
  client/my-sites/stats/annual-highlights-section/year-navigation.tsx
  client/my-sites/stats/navigation-arrows/index.jsx
  client/my-sites/stats/navigation-arrows/style.scss
  client/my-sites/stats/stats-period-navigation/index.jsx
  client/my-sites/stats/stats-period-navigation/style.scss
Labels: Stats, [Status] Needs Review

#71708 Enable feature flag to unlock blank-canvas-3
  client/signup/config/flows.js
  client/signup/controller.js
  client/state/themes/actions/request-themes.js
  client/state/themes/test/actions.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#71821 Stats: fix the padding at the top of the Traffic page
  client/my-sites/stats/modernized-layout-styles.scss
Labels: Stats, [Status] Needs Review

#71745 Stats: Update Charts Empty State
  client/my-sites/stats/stats-chart-tabs/index.jsx
  client/my-sites/stats/stats-empty-state/index.tsx
  client/my-sites/stats/stats-empty-state/style.scss
  client/my-sites/stats/stats-summary/index.jsx
  client/my-sites/stats/wordads-chart-tabs/index.jsx
  client/my-sites/store/app/store-stats/store-stats-chart/index.js
Labels: Stats, [Status] Needs Review

#71678 Plugins: Allow the Plugins Post-Purchase (Thank you) page to support multiple plugins via URL
  client/data/marketplace/use-wpcom-plugins-query.ts
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
  client/my-sites/marketplace/pages/marketplace-test/index.jsx
  client/my-sites/plugins/plugins-browser/test/index.jsx
  client/my-sites/plugins/use-plugins/index.ts
  client/state/plugins/installed/selectors.js
  client/state/plugins/wporg/selectors.js
Labels: [Status] Needs Review

#71828 Hosting Config: Add key icon to material-design-icons package
  client/my-sites/hosting/sftp-card/index.js
  packages/material-design-icons/src/communication/outline-key-32px.svg
  packages/material-design-icons/svg-sprite/material-icons.svg
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting Configuration, Hosting Configuration Upsell Nudge Revamp

#71825 chore: fix test user account used for editor tracking.
  packages/calypso-e2e/src/secrets/encrypted.enc
Labels: [Status] Needs Review

#71766 Refactor getSiteFragment to add new exception for plan upsell path
  client/lib/route/path.ts
  client/lib/route/test/index.js
Labels: [Status] Needs Review

#71811 Headers with underscores are no longer allowed, so switch to dashes.
  .teamcity/_self/lib/wpcom/WPComPluginBuild.kt
  .teamcity/_self/projects/WebApp.kt
Labels: [Status] Needs Review

#71740 Free Onboarding Flow: Update post setup screen to match initial setup screen & update test cases
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/free-post-setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/free-post-setup/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/free-post-setup/test/lib/fixtures.ts
Labels: [Status] Needs Review, Free Onboarding Flow

#71805 WooExpress Trial: Add the ecommerce-trial-bundle-monthly plan to a new trial site
  client/landing/stepper/declarative-flow/internals/steps-repository/assign-trial-plan/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/assign-trial-plan/styles.scss
  client/landing/stepper/declarative-flow/trial-wooexpress-flow.ts
Labels: [Status] Needs Review, Stepper, WooExpress

#71743 Stats: Extended number component with default formatter
  client/my-sites/stats/all-time-highlights-section/index.tsx
  packages/components/src/highlight-cards/highlight-card.tsx
  packages/components/src/index.ts
  packages/components/src/number-formatters/formatted-number.tsx
  packages/components/src/number-formatters/index.tsx
  packages/components/src/number-formatters/stories/index.stories.jsx
  packages/components/src/shortened-number/stories/index.stories.jsx
Labels: Stats, [Status] Needs Review

#71894 Stats: Reorder sections on the insights page
  client/my-sites/stats/post-trends/index.jsx
  client/my-sites/stats/post-trends/style.scss
  client/my-sites/stats/stats-insights/index.jsx
  client/my-sites/stats/stats-module/style.scss
Labels: Stats, [Status] Needs Review

#71896 Add `getSiteFragment` unit test to cover domain renewal
  client/lib/route/test/index.js
Labels: [Status] Needs Review

#71890 Site Editor: Use relative path for site editor back button
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Labels: [Type] Bug, [Status] Needs Review

#71822 Stats: Remove showNewModules and apply horizontal bars to other components
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-countries/index.jsx
  client/my-sites/stats/stats-insights/index.jsx
  client/my-sites/stats/stats-list/stats-list-card.jsx
  client/my-sites/stats/stats-module/index.jsx
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  packages/components/src/horizontal-bar-list/horizontal-bar-grid-item.tsx
Labels: Stats, [Status] Needs Review

#70976 Purchase Management: Hide 'remove product' button when auto-renew is enabled
  client/lib/purchases/assembler.ts
  client/lib/purchases/index.ts
  client/me/purchases/cancel-purchase/index.jsx
  client/me/purchases/manage-purchase/index.jsx
  client/me/purchases/manage-purchase/purchase-meta.jsx
  client/me/purchases/manage-purchase/test/purchase-management-buttons.js
  client/state/selectors/get-media-query-manager.js
Labels: [Status] Needs Review

#71902 Site Editor: Catch exceptions for site editor back to dashboard button
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Labels: [Status] Needs Review

#71625 BBE: Add initial store flow
  client/lib/signup/step-actions/index.js
  client/signup/config/flows-pure.js
  client/signup/config/step-components.js
  client/signup/config/steps-pure.js
  client/signup/reskinned-processing-screen/index.jsx
  client/signup/steps/new-or-existing-site/index.tsx
  client/signup/steps/site-options/index.scss
  client/signup/steps/site-options/index.tsx
  client/state/difm/assemblers.ts
  config/_shared.json
Labels: [Status] Needs Review, BuiltByExpress

#71846 Jetpack Pro Dashboard: disable toggle monitor when a site is down
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/toggle-activate-monitoring/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/toggle-activate-monitoring/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#71752 Jetpack Pro Dashboard: Implement pause & resume monitor(bulk)
  client/data/agency-dashboard/use-fetch-dashboard-sites.ts
  client/jetpack-cloud/sections/agency-dashboard/dashboard-bulk-actions/hooks.tsx
  client/jetpack-cloud/sections/agency-dashboard/dashboard-bulk-actions/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/dashboard-bulk-actions/style.scss
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/toggle-activate-monitoring/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/hooks.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-content/test/site-content.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/test/utils.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/utils.ts
  client/state/jetpack-agency-dashboard/action-types.js
  client/state/jetpack-agency-dashboard/actions.ts
  client/state/jetpack-agency-dashboard/reducer.ts
  client/state/jetpack-agency-dashboard/selectors.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#71626 BBE: Update theme filters for the store flow
  client/signup/steps/design-picker/index.jsx
  client/signup/steps/design-picker/let-us-choose.tsx
Labels: [Status] Needs Review, BuiltByExpress

#71887 E2E: add new `atomicUser` for use in Atomic E2E testing.
  .teamcity/_self/projects/WebApp.kt
  packages/calypso-e2e/src/env-variables.ts
  packages/calypso-e2e/src/secrets/encrypted.enc
  packages/calypso-e2e/src/secrets/secrets-manager.ts
  test/e2e/docs/environment_variables.md
  test/e2e/docs/tests_local.md
  test/e2e/specs/media/media__edit.ts
  test/e2e/specs/media/media__upload.ts
  test/e2e/specs/stats/stats__insights.ts
  test/e2e/specs/support/support__home.ts
  test/e2e/specs/support/support__popover-invalid.ts
  test/e2e/specs/support/support__popover-valid.ts
  test/e2e/specs/support/support__showme-where.ts
  test/e2e/specs/tools/marketing__seo.ts
Labels: [Status] Needs Review

#71758 Users management: Record missing track events and edit form adjustments
  client/my-sites/people/edit-team-member-form/edit-user-form.jsx
  client/my-sites/people/edit-team-member-form/index.jsx
  client/my-sites/people/subscriber-details/index.tsx
  client/my-sites/people/subscribers-team/index.tsx
  client/my-sites/people/subscribers/index.tsx
Labels: [Status] Needs Review, User Management Revamp

#71865 State: Remove unused gsuite users state tree
  client/components/data/query-gsuite-users/README.md
  client/components/data/query-gsuite-users/index.jsx
  client/state/action-types.ts
  client/state/data-layer/wpcom/gsuite-users/index.js
  client/state/data-layer/wpcom/gsuite-users/test-utils.js
  client/state/data-layer/wpcom/gsuite-users/test/index.js
  client/state/gsuite-users/actions.js
  client/state/gsuite-users/init.js
  client/state/gsuite-users/package.json
  client/state/gsuite-users/reducer.js
  client/state/gsuite-users/schema.js
  client/state/gsuite-users/test/reducer.js
  client/state/selectors/get-gsuite-users.js
  client/state/selectors/has-loaded-gsuite-users.js
  client/state/selectors/is-requesting-gsuite-users.js
Labels: [Status] Needs Review, [Type] Janitorial, G Suite, State

#71854 Domains: Remove unused domain management components
  client/my-sites/domains/domain-management/components/domain/maintenance-card.jsx
  client/my-sites/domains/domain-management/components/outbound-transfer-confirmation/index.jsx
  client/my-sites/domains/domain-management/components/outbound-transfer-confirmation/style.scss
  client/my-sites/domains/domain-management/edit/card/notices/expiring-credit-card.jsx
  client/my-sites/domains/domain-management/edit/card/notices/expiring-soon.jsx
  client/my-sites/domains/domain-management/edit/domain-types/helpers.jsx
  client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
  client/my-sites/domains/domain-management/edit/navigation/style.scss
  client/my-sites/domains/domain-management/name-servers/wpcom-nameservers-toggle.jsx
Labels: [Status] Needs Review, [Type] Janitorial, Domains

#71824 Users management: Optimize calling updateUser function
  client/my-sites/people/edit-team-member-form/edit-user-form.jsx
Labels: [Status] Needs Review, User Management Revamp

#71851 Subscriber-Team screen: Turn on the ScreenOptionsTab component
  client/my-sites/people/subscribers-team/index.tsx
Labels: [Status] Needs Review, User Management Revamp

#71879 Users managements: Fix the issue of highlighting Users -> Add a new submenu item
  client/my-sites/sidebar/utils.js
Labels: [Status] Needs Review, User Management Revamp

#71920 CopySite: add parameters into the flow and show url in intro step
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/index.tsx
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
Labels: [Status] Needs Review

#71665 BBE: Checkout improvements
  client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx
  packages/wpcom-checkout/src/can-item-be-removed-from-cart.ts
Labels: [Status] Needs Review, BuiltByExpress

#71627 BBE: Update the page picker step for the store flow
  client/signup/difm/components/BrowserView.tsx
  client/signup/difm/constants.tsx
  client/signup/difm/translation-hooks.tsx
  client/signup/steps/page-picker/index.tsx
  client/signup/steps/page-picker/shopping-cart-for-difm.tsx
  client/signup/steps/page-picker/use-cart-for-difm.tsx
Labels: [Status] Needs Review, BuiltByExpress

#71840 Marketplace: Use dynamic plugins endpoint
  client/data/marketplace/use-wpcom-plugins-query.ts
  client/lib/plugins/utils.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Marketplace

#71922 Fixes in blaze logo
  client/assets/images/icons/blaze-icon.svg
  client/components/blaze-logo/index.jsx
  client/components/blaze-logo/style.scss
  client/components/blazepress-widget/index.tsx
  client/components/blazepress-widget/style.scss
Labels: [Status] Needs Review

#71924 i18n: Fix adding preloaded translations batch throttling
  client/lib/i18n-utils/switch-locale.js
Labels: [Type] Bug, [Status] Needs Review, i18n

#71927 Allow 3-year to monthly downgrades in the cancel flow
  client/components/marketing-survey/cancel-purchase-form/get-upsell-type.ts
Labels: [Status] Needs Review

#71921 Adding isMigrateFromWp flag and site creation step to importer flow
  client/blocks/importer/wordpress/index.tsx
  client/blocks/importer/wordpress/utils.js
  client/landing/stepper/declarative-flow/import-flow.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-creation-step/index.tsx
  packages/data-stores/src/onboard/actions.ts
  packages/data-stores/src/onboard/reducer.ts
  packages/data-stores/src/onboard/selectors.ts
  packages/onboarding/src/utils/flows.ts
Labels: [Status] Needs Review, WordPress Migrator

#71856 Email stats open rate UI
  client/components/data/query-email-stats/index.jsx
  client/my-sites/stats/stats-email-module/index.jsx
  client/my-sites/stats/stats-email-open-detail/index.jsx
  client/my-sites/stats/stats-email-open-detail/style.scss
  client/my-sites/stats/stats-email-open-top-row/icons.jsx
  client/my-sites/stats/stats-email-open-top-row/index.jsx
  client/my-sites/stats/stats-email-open-top-row/style.scss
  client/my-sites/stats/stats-email-open-top-row/top-card.jsx
  client/state/stats/emails/actions.js
  client/state/stats/emails/selectors.js
  packages/wpcom.js/src/lib/site.js
Labels: [Status] Needs Review

#71849 Enable `marketplace-jetpack-plugin-search` feature flag outside production
  config/horizon.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  test/e2e/specs/plugins/plugins__search.ts
Labels: [Status] Needs Review

#71928 Update filtering by category to support WC.com products
  client/data/marketplace/search-api.ts
Labels: [Status] Needs Review

#71923 Add hotfix for 1$ intro prices for jetpack_backup_tier_1 (similar to Jetpack Social)
  client/my-sites/plans/jetpack-plans/use-item-price.ts
Labels: [Status] Reviewer Approved

#71876 Update/re revert shopping cart with fixes
  client/components/jetpack/intro-pricing-banner/hooks/use-bounding-client-rect.ts
  client/components/jetpack/intro-pricing-banner/index.tsx
  client/components/jetpack/intro-pricing-banner/style.scss
  client/jetpack-cloud/sections/comparison/content.tsx
  client/jetpack-cloud/sections/comparison/table/index.tsx
  client/jetpack-cloud/sections/pricing/controller.tsx
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/cloud-cart/cloud-cart-icon.tsx
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/cloud-cart/empty-cart.scss
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/cloud-cart/empty-cart.tsx
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/cloud-cart/index.tsx
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/index.tsx
  client/jetpack-cloud/sections/pricing/jpcom-masterbar/style.scss
  client/jetpack-cloud/sections/pricing/style.scss
  client/jetpack-cloud/style.scss
  client/my-sites/plans/jetpack-plans/product-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-card/product-button-label.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/index.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/style.scss
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-shopping-cart-tracker.ts
  client/my-sites/plans/jetpack-plans/product-store/hooks/use-store-item-info.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/all-items.tsx
  client/my-sites/plans/jetpack-plans/product-store/items-list/most-popular.tsx
  client/my-sites/plans/jetpack-plans/product-store/simple-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/simple-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/types.ts
  client/my-sites/plans/jetpack-plans/selector.tsx
  client/state/sites/selectors/index.js
  client/state/sites/selectors/is-jetpack-cloud-cart-enabled.ts
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
  packages/calypso-products/src/product-values.ts
Labels: [Status] Needs Review

#71847 Marketplace: Add a confetti animation to the post-purchase page
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
  packages/components/package.json
  packages/components/src/confetti/index.ts
  packages/components/src/index.ts
  yarn.lock
Labels: [Status] Needs Review

#71878 Stats: Refactor "stats-views__key" to Heat Map Legend
  client/my-sites/stats/all-time-views-section/index.tsx
  client/my-sites/stats/modernized-stats-table-styles.scss
  client/my-sites/stats/post-detail-table-section/index.tsx
  client/my-sites/stats/stats-heap-map/legend.tsx
  client/my-sites/stats/stats-heap-map/style.scss
  client/my-sites/stats/stats-views/style.scss
Labels: Stats, [Status] Needs Review

#71936 Fix display price if no intro offer is found
  client/my-sites/plans/jetpack-plans/use-item-price.ts
Labels: [Status] Needs Review

#71829 [GB 14.8+] Misc Calypso GB E2E test fixes
  packages/calypso-e2e/src/lib/components/editor-settings-sidebar-component.ts
Labels: [Status] Needs Review

#71877 update Newspack Blocks to v1.60.0
  .patches/swiper@4.5.1.diff
  .yarnrc.yml
  apps/editing-toolkit/bin/sync-newspack-blocks.sh
  apps/editing-toolkit/editing-toolkit-plugin/newspack-blocks/index.php
  apps/editing-toolkit/package.json
  client/package.json
  package.json
  packages/calypso-stripe/package.json
  packages/design-carousel/package.json
  packages/pattern-picker/package.json
  packages/wpcom-checkout/package.json
  yarn.lock
Labels: [Status] Needs Review

#71757 Update Post Purchase Upsell design with experiment
  client/assets/images/checkout-upsell/upsell-rocket.png
  client/my-sites/checkout/upsell-nudge/business-plan-upgrade-upsell/new-design-202301.jsx
  client/my-sites/checkout/upsell-nudge/business-plan-upgrade-upsell/style-new-design.scss
  client/my-sites/checkout/upsell-nudge/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#71895 format-currency: Set currency locale when changing translation locale
  client/state/ui/language/actions.ts
  packages/format-currency/src/index.ts
  packages/format-currency/test/index.ts
Labels: [Status] Needs Review

#71942 Add unit test covering checkout when 3rd position is not site fragment
  client/lib/route/test/index.js
Labels: [Status] Needs Review

#71925 WooExpress: Add WaitForAtomic step
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/assign-trial-plan/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/wait-for-atomic/index.tsx
  client/landing/stepper/declarative-flow/trial-wooexpress-flow.ts
Labels: [Status] Needs Review, Stepper, WooExpress

#71905 Stats: adds styling to ads earning history table
  client/my-sites/stats/wordads/style.scss
Labels: Stats, [Status] Needs Review

#71750 Hosting Config: Describe premium features in the upsell nudge
  client/blocks/upsell-nudge/index.jsx
  client/components/banner/index.jsx
  client/my-sites/hosting/hosting-upsell-nudge/icons/icon-cloud.svg
  client/my-sites/hosting/hosting-upsell-nudge/icons/icon-comments.svg
  client/my-sites/hosting/hosting-upsell-nudge/icons/icon-php.svg
  client/my-sites/hosting/hosting-upsell-nudge/icons/icon-server-racks.svg
  client/my-sites/hosting/hosting-upsell-nudge/icons/icon-ssh.svg
  client/my-sites/hosting/hosting-upsell-nudge/icons/icon-terminal.svg
  client/my-sites/hosting/hosting-upsell-nudge/index.tsx
  client/my-sites/hosting/hosting-upsell-nudge/style.scss
  client/my-sites/hosting/main.js
  client/my-sites/hosting/style.scss
Labels: [Status] Needs Review, ABTest, Upsell Nudge, Hosting Configuration

#71931 Update free flow site preview default device
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/launchpad-site-preview.tsx
Labels: [Status] Needs Review

#71955 Site Editor: Use relative path for site editor back button ( Attempt 2 )
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
  client/gutenberg/editor/calypsoify-iframe.tsx
Labels: [Status] Needs Review

#71898 Hosting Configuration: Update copy and icon in revamped
  client/my-sites/hosting/hosting-upsell-nudge/icons/icon-database.svg
  client/my-sites/hosting/hosting-upsell-nudge/icons/icon-php.svg
  client/my-sites/hosting/hosting-upsell-nudge/index.tsx
Labels: [Status] Needs Review

#71959 PlanPrice: Add additional tests
  client/my-sites/plan-price/test/index.js
Labels: [Status] Needs Review

#71582 Jetpack Search: do not mark as conflicting with Jetpack Complete
  client/blocks/product-plan-overlap-notices/index.jsx
Labels: [Status] Needs Review, Jetpack Search

#71944 Show domain information to user if migrate the site using plugin
  client/blocks/importer/components/domain-info/index.tsx
  client/blocks/importer/components/domain-info/style.scss
  client/blocks/importer/components/done-button/index.tsx
  client/blocks/importer/types.ts
  client/blocks/importer/wordpress/import-everything/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer/hooks/use-step-navigator.ts
  packages/onboarding/src/hooray/style.scss
Labels: [Status] Needs Review, WordPress Migrator

#71792 Jetpack Pro Dashboard: Implement custom notifications(bulk)
  client/jetpack-cloud/sections/agency-dashboard/dashboard-bulk-actions/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/style.scss
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/toggle-activate-monitoring/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content.tsx
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#68766 Redirect Calypso Home to WooCommerce Home in Ecommerce plans
  client/my-sites/customer-home/controller.jsx
  client/my-sites/customer-home/main.jsx
  client/my-sites/customer-home/wc-home-placeholder.js
  client/my-sites/customer-home/wc-home-placeholder.scss
Labels: [Status] Needs Review

#71841 Jetpack Pro Dashboard: implement reset notification(bulk)
  client/jetpack-cloud/sections/agency-dashboard/dashboard-bulk-actions/hooks.tsx
  client/jetpack-cloud/sections/agency-dashboard/dashboard-bulk-actions/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/utils.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#71910 Design Picker: Hide retiring designs
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/constants.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
Labels: [Status] Needs Review

#71906 Design Picker: use high-res mShots image for non-mobile devices
  packages/design-picker/src/components/unified-design-picker.tsx
Labels: [Status] Needs Review

#71971 ETE: Replace the now-retired Dorna theme with Zoologist
  test/e2e/specs/onboarding/ftme__sell.ts
Labels: [Status] Needs Review
