Repository Automattic/wp-calypso, pull requests merged in 2023-02, with the labels that each got.

#72593 Flaky E2E: reorganize URL extraction logic in `EditorPage.publish`.
  packages/calypso-e2e/src/lib/pages/editor-page.ts
Labels: [Pri] High, [Status] Needs Review

#72756 Stats: Some styling adjustments per Odyssey design
  apps/odyssey-stats/src/styles/theme.scss
  apps/odyssey-stats/src/styles/wp-admin.scss
  client/blocks/stats-navigation/style.scss
  client/my-sites/stats/annual-highlights-section/index.tsx
  client/my-sites/stats/highlights-section/index.tsx
  client/my-sites/stats/wordads/highlights-section.jsx
Labels: Stats, [Status] Needs Review, Odyssey Stats

#72813 Disable flag themes/theme-switch-persist-template in all enviroments
  config/development.json
  config/horizon.json
Labels: [Status] Needs Review

#72142 Theme Showcase: Add Style selection Tracks events
  client/components/theme-preview-modal/index.tsx
  client/components/theme-preview-modal/style.scss
  client/components/theme/index.jsx
  client/components/theme/more-button.jsx
  client/components/themes-list/index.jsx
  client/my-sites/theme/main.jsx
  client/my-sites/themes/theme-preview.jsx
  client/my-sites/themes/themes-selection.jsx
  packages/design-preview/src/components/style.scss
Labels: [Status] Needs Review, Theme Showcase

#72849 Theme Showcase: Show pricing in logged-out theme showcase
  client/components/theme/index.jsx
  client/my-sites/themes/test/logged-out.jsx
Labels: [Status] Needs Review, Theme Showcase

#72752 Display PatternAssembler CTA on Logged-out ThemShowcase
  client/components/theme/style.scss
  client/components/themes-list/index.jsx
  client/components/themes-list/style.scss
  client/components/themes-list/test/__snapshots__/index.jsx.snap
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/constants.ts
  client/landing/stepper/declarative-flow/site-assembler-flow.ts
  client/my-sites/themes/theme-showcase.scss
  client/signup/config/flows.js
  client/state/themes/actions/request-themes.js
  packages/design-picker/src/constants.ts
  packages/design-picker/src/index.ts
Labels: [Status] Needs Review

#72833 Marketplace Themes: Fix the CTA on the Theme page when the user isn't logged in
  client/my-sites/theme/main.jsx
Labels: Themes, [Status] Needs Review

#72779 Theme Preview: Add Limited Global Styles Tracks Events
  client/my-sites/themes/theme-preview.jsx
Labels: [Status] Needs Review, Theme Showcase, Global Styles

#72706 Reading Settings: Uptake the dropdown-page api's change in its response format
  client/data/dropdown-pages/use-dropdown-pages.ts
  client/my-sites/site-settings/reading-site-settings/YourHomepageDisplaysSetting.tsx
Labels: [Status] Needs Review

#72709 Reading Settings: Rename 'Default posts page' default option to 'None'
  client/my-sites/site-settings/reading-site-settings/YourHomepageDisplaysSetting.tsx
Labels: [Status] Needs Review

#72815 Use 'Paid' badge for marketplace themes
  client/components/theme/index.jsx
  client/components/theme/style.scss
Labels: [Status] Needs Review, Theme Showcase, Marketplace

#72823 Change behaviour of dotorg theme nudge
  client/my-sites/theme/main.jsx
Labels: [Status] Needs Review, Theme Showcase

#72679 Fix CoBlocks fonts issue for simple sites
  apps/wpcom-block-editor/README.md
  apps/wpcom-block-editor/src/wpcom/editor.js
  apps/wpcom-block-editor/src/wpcom/features/fix-coblocks-fonts.js
Labels: [Status] Needs Review

#72855 Plans Grid 2023: Fix broken interval switch
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  client/my-sites/plans-features-main/index.jsx
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72866 Plan Grid 2023: Adds free plan by default and buttons for managing
  client/my-sites/plan-features-2023-grid/actions.tsx
  client/my-sites/plan-features-2023-grid/index.tsx
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  client/my-sites/plan-features-2023-grid/style.scss
  client/my-sites/plans/main.jsx
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72848 Pricing 2023 : Add all tooltips and fix a few errors in text
  client/lib/plans/features-list.tsx
  client/my-sites/plan-features-2023-grid/plans-2023-tooltip.tsx
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72862 Reading Settings: Update Reading settings fallback menu URL
  client/my-sites/sidebar/static-data/fallback-menu.js
Labels: [Status] Needs Review, Reading Settings

#72832 Adds a dummy downgrade button with a tooltip for eligible plans
  client/my-sites/plan-features-2023-grid/actions.tsx
  client/my-sites/plan-features-2023-grid/style.scss
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72852 Reading Settings: Unset `page_for_posts` when `page_on_front` is changed to default
  client/my-sites/site-settings/reading-site-settings/YourHomepageDisplaysSetting.tsx
Labels: [Status] Needs Review

#72861 Reading Settings: Enable `settings/modernize-reading-settings` feature flag in production
  config/production.json
Labels: [Status] Needs Review, Reading Settings

#72836 WooExpress: Update plans page upgrade button copy
  client/my-sites/plan-features-2023-grid/actions.tsx
  client/my-sites/plan-features/actions.jsx
Labels: [Status] Needs Review, WooExpress

#72841 @wordpress/data: Change DispatchFromMap to return Promise<void> instead of void
  client/landing/gutenboarding/onboarding-block/create-site-error/index.tsx
  packages/data-stores/src/mapped-types.ts
Labels: [Status] Needs Review

#72853 UI only fix for Ecommerce plan name and logo for business plan
  client/assets/images/onboarding/cloud-logo.svg
  client/my-sites/plan-features-2023-grid/index.tsx
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  client/my-sites/plan-features-2023-grid/style.scss
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review

#72835 Checkout: Add types to checkout data store actions and selectors
  client/my-sites/checkout/composite-checkout/components/checkout-main.tsx
  client/my-sites/checkout/composite-checkout/components/contact-details-container.tsx
  client/my-sites/checkout/composite-checkout/components/international-fee-notice.tsx
  client/my-sites/checkout/composite-checkout/components/vat-form/index.tsx
  client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx
  client/my-sites/checkout/composite-checkout/components/wp-contact-form-summary.tsx
  client/my-sites/checkout/composite-checkout/components/wp-contact-form.tsx
  client/my-sites/checkout/composite-checkout/hooks/use-cached-domain-contact-details.ts
  client/my-sites/checkout/composite-checkout/hooks/use-detected-country-code.ts
  client/my-sites/checkout/composite-checkout/hooks/wpcom-store.ts
  client/my-sites/checkout/composite-checkout/test/use-cached-domain-contact-details.tsx
  client/signup/recaptcha/index.jsx
Labels: [Status] Needs Review

#72879 Add a coblocks atomic e2e user
  packages/calypso-e2e/src/secrets/encrypted.enc
  packages/calypso-e2e/src/secrets/secrets-manager.ts
Labels: [Status] Needs Review

#72733 Plugins: Decode html-encoded title when installing or reading a plugin
  client/components/breadcrumb/index.tsx
  client/my-sites/plugins/plugin-details-header/index.jsx
  client/my-sites/plugins/plugin-remove-button/index.jsx
  client/state/plugins/installed/reducer.js
  client/state/plugins/installed/test/fixtures/plugins.js
  client/state/plugins/installed/test/reducer.js
Labels: [Status] Needs Review

#72875 Themes: Add new an action to fetch a specific theme
  client/state/themes/actions/index.js
  client/state/themes/actions/request-theme-on-atomic.js
  client/state/themes/test/actions.js
Labels: Themes, [Status] Needs Review

#72776 Add/help center launchpad navigation v1
  packages/help-center/src/components/help-center-launchpad.scss
  packages/help-center/src/components/help-center-launchpad.tsx
  packages/help-center/src/components/help-center-search.tsx
Labels: [Status] Needs Review

#72695 Purchase Management: Add a disconnected state warning to purchase page
  client/me/purchases/manage-purchase/index.jsx
  client/me/purchases/manage-purchase/style.scss
Labels: [Status] Needs Review

#72856 Stats: Better localized formatting in highlights
  client/my-sites/stats/wordads/highlights-section.jsx
Labels: Stats, [Status] Needs Review, WordAds

#72696 Purchase Management: Add correct status information when owner removed from site
  client/me/purchases/purchase-item/index.jsx
Labels: [Status] Needs Review

#72697 Purchase Management: Add early return to block loading of '/cancel' endpoint
  client/me/purchases/cancel-purchase/index.jsx
Labels: [Status] Needs Review

#72830 Stats: Release the enhanced post details page
  client/my-sites/stats/modernized-stats-table-styles.scss
  client/my-sites/stats/post-detail-highlights-section/index.tsx
  client/my-sites/stats/post-detail-table-section/index.tsx
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Stats, [Status] Needs Review

#72688 Flaky E2E: do not use `waitForNavigation` with `ReaderPage` POM.
  packages/calypso-e2e/src/lib/pages/reader-page.ts
Labels: [Status] Needs Review

#72834 Writing prompts: conditionally shows responses link on Home card
  client/data/blogging-prompt/use-blogging-prompts.ts
  client/my-sites/customer-home/cards/features/blogging-prompt/index.jsx
  client/my-sites/customer-home/cards/features/blogging-prompt/prompts-navigation.jsx
Labels: [Status] Needs Review, writing prompts

#72899 Stats: Fixing Traffic grid syntax for small screens
  client/my-sites/stats/grid-layout.scss
Labels: Stats, [Status] Needs Review

#72762 Stats: Add mobile promo card to Ads page.
  client/my-sites/stats/annual-site-stats/index.js
  client/my-sites/stats/promo-cards/index.jsx
  client/my-sites/stats/site.jsx
  client/my-sites/stats/wordads/index.jsx
Labels: Stats, [Status] Needs Review

#72876 Sharing buttons: add Mastodon colors
  client/components/social-logo/docs/example.jsx
  client/my-sites/marketing/style.scss
  client/package.json
  packages/calypso-color-schemes/CHANGELOG.md
  packages/calypso-color-schemes/src/shared/color-schemes/_classic-dark.scss
  packages/calypso-color-schemes/src/shared/color-schemes/_default.scss
  packages/components/CHANGELOG.md
  yarn.lock
Labels: [Type] Enhancement, Sharing, [Pri] Normal, [Status] Ready to Merge

#71333 Limited Global Styles: Add E2E test
  packages/calypso-e2e/src/lib/components/cookie-banner-component.ts
  packages/calypso-e2e/src/lib/components/editor-site-styles-component.ts
  packages/calypso-e2e/src/lib/pages/full-site-editor-page.ts
  test/e2e/specs/editor-tracking/editor-tracking__global-styles-events.ts
  test/e2e/specs/fse/fse__limited-global-styles.ts
Labels: [Status] Needs Review, Global Styles

#72857 Pricing 2023: Fix failing prerelease e2e tests and enable feature flag on wpcalypso
  config/wpcalypso.json
  packages/calypso-e2e/src/lib/pages/plans-page.ts
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72662 Add option to purchases to reinstall plugins
  client/data/marketplace/reinstall-plugins-api.ts
  client/data/marketplace/types.ts
  client/me/purchases/manage-purchase/index.jsx
Labels: [Status] Needs Review, [Status] String Freeze

#72908 Plans Grid 2023: Fix typo in button
  client/my-sites/plan-features-2023-grid/actions.tsx
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72379 Add a post-purchase redirect parameter for Premium themes upgrade nudge
  client/my-sites/plans-features-main/plan-type-selector.tsx
  client/my-sites/theme/main.jsx
Labels: [Status] Needs Review

#72330 Licensing Portal: Add descriptions for Social and Search plans
  client/jetpack-cloud/sections/partner-portal/license-bundle-card-description/index.tsx
Labels: [Status] Needs Review, Jetpack Cloud, Jetpack Licensing Portal

#72901 ETK: update loading coming-soon check
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
Labels: Editing Toolkit

#72930 Add queryParam to invalid cache when navigating away from site setup flow
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  client/my-sites/customer-home/controller.jsx
Labels: [Status] Needs Review

#72904 Prevent GitHub from appearing in /marketing/connections view
  client/state/sharing/services/selectors.js
Labels: [Status] Needs Review, Reviewer Can Merge, WPCOM + GitHub Integration i1

#72925 Payment Methods: Make the placeholder submit button disabled
  client/me/purchases/components/payment-method-loader/index.jsx
  client/me/purchases/manage-purchase/change-payment-method/index.tsx
Labels: [Status] Needs Review

#72839 Payment Methods: Add tests for ChangePaymentMethod
  client/me/purchases/manage-purchase/test/change-payment-method.tsx
  client/my-sites/checkout/composite-checkout/test/util/index.ts
Labels: [Status] Needs Review

#72687 Teamcity: improve webpack cache hit rate
  .teamcity/_self/bashNodeScript.kt
  .teamcity/_self/projects/WebApp.kt
  Dockerfile
  bin/check-log-for-cache-invalidation.sh
  client/webpack.config.js
Labels: [Status] Needs Review

#72939 Write to webpack cache on trunk
  .teamcity/_self/projects/WebApp.kt
  Dockerfile
Labels: [Status] Needs Review

#72942 Revert webpack cache changes
  .teamcity/_self/bashNodeScript.kt
  .teamcity/_self/projects/WebApp.kt
  Dockerfile
  bin/check-log-for-cache-invalidation.sh
  client/webpack.config.js
Labels: [Status] Needs Review

#72850 Theme Showcase: Clean up flag themes/showcase i4/cards-only
  client/components/theme/index.jsx
  client/components/theme/test/__snapshots__/index.jsx.snap
  client/components/theme/test/index.jsx
  client/my-sites/themes/logged-out.jsx
  client/my-sites/themes/single-site-jetpack.jsx
  client/my-sites/themes/single-site-wpcom.jsx
  client/my-sites/themes/theme-showcase.scss
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Type] Janitorial, Theme Showcase

#72933 Hosting Config: Remove fallback copy from hosting config upsell
  client/my-sites/hosting/hosting-upsell-nudge/index.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting Configuration

#72935 Hosting Config: Update hosting upsell margin to match Figma mockup
  client/my-sites/hosting/hosting-upsell-nudge/style.scss
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting Configuration

#72907 Logged-out TS: Hide eCommerce plan if destination flow is site assembler
  client/components/themes-list/index.jsx
  client/my-sites/plans-features-main/index.jsx
  client/signup/config/flows.js
  client/signup/controller.js
  client/signup/steps/plans/index.jsx
Labels: [Status] Needs Review

#72943 Logged-out TS: Enable PA on horizon and wpcalypso
  config/horizon.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#72143 BBE: Update copy for the existing site flow
  client/signup/steps/difm-site-picker/site-delete-confirmation-dialog.tsx
  client/signup/steps/new-or-existing-site/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze, BuiltByExpress

#69731 Add the Universal Footer to /themes and /theme sections
  client/layout/logged-out.jsx
  client/layout/universal-navbar-footer/index.tsx
  packages/i18n-utils/src/test/utils.js
  packages/i18n-utils/src/utils.ts
Labels: [Status] Needs Review

#72843 Change <span> tag to <h1> for theme__sheet-bar-title
  client/my-sites/theme/main.jsx
Labels: [Status] Needs Review

#72915 Plans 2023: Update focus states
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  client/my-sites/plan-features-2023-grid/style.scss
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72926 Plans 2023 : Minor typo in feature tooltip for - Managed malware protection
  client/lib/plans/features-list.tsx
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72929 Always show free plan for the new pricing grid pages
  client/signup/main.jsx
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72869 Plans 2023: Fix breakpoints on logged in plans page
  client/my-sites/plan-features-2023-grid/_media-queries.scss
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  client/my-sites/plan-features-2023-grid/style.scss
  client/my-sites/plans-features-main/style.scss
  client/signup/steps/plans/style.scss
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72912 HappyBlocks: Remove automatic domain detection in Pricing Plans block
  apps/happy-blocks/src/pricing-plans/edit.tsx
Labels: [Status] Needs Review

#72911 HappyBlocks: Add common custom blocks class
  apps/happy-blocks/src/pricing-plans/components/pricing-plans.tsx
Labels: [Status] Needs Review

#72748 Site Assembler - Write Flow (dotcom patterns only)
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/constants.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-assembler-container.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/patterns-data.ts
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
  packages/data-stores/src/site/actions.ts
  packages/data-stores/src/site/types.ts
  packages/design-picker/src/types.ts
Labels: [Status] Needs Review

#72225 Add some new BlazePress translations
  client/lib/promote-post/README.md
  client/lib/promote-post/string.ts
Labels: [Status] Needs Review, [Status] String Freeze

#72952 Plans 2023: Add notices on the /plans page
  client/my-sites/plan-features-2023-grid/index.tsx
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72954 Plans 2023: Update breakpoints for the /plans page
  client/my-sites/plan-features-2023-grid/_media-queries.scss
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72956 Plans 2023: Fix width of interval toggle
  client/my-sites/plan-features-2023-grid/_media-queries.scss
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  client/my-sites/plan-features-2023-grid/style.scss
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72286 Themes Showcase: Replace empty search card with more theme options
  client/assets/images/themes/pro-themes-banner.svg
  client/components/themes-list/index.jsx
  client/components/themes-list/style.scss
  client/components/themes-list/test/index.jsx
  client/my-sites/themes/test/logged-out.jsx
Labels: Themes, [Status] Needs Review

#72957 Theme: Fix DIFM link in emtpy search
  client/components/themes-list/index.jsx
Labels: [Status] Needs Review

#72959 Theme: Fix DIFM link in empty search (take 2)
  client/components/themes-list/index.jsx
Labels: Themes, [Status] Needs Review

#72958 Plans 2023: Match Plans header width to My Plan
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
  client/my-sites/plan-features-2023-grid/style.scss
  client/my-sites/plans/header.scss
  client/my-sites/plans/main.jsx
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72897 Flaky E2E: extend timeout when force dismissing the welcome tour.
  packages/calypso-e2e/src/lib/components/editor-welcome-tour-component.ts
  packages/calypso-e2e/src/lib/pages/editor-page.ts
Labels: [Status] Needs Review

#72974 Copy Site: Tweak strings according to Pick's feedback
  client/landing/stepper/declarative-flow/copy-site.tsx
  client/my-sites/customer-home/cards/notices/celebrate-site-copy/index.js
Labels: [Type] Task, Copy Site i1

#72951 Stats: Restore totals under Tools → Earn.
  client/my-sites/stats/wordads/earnings.jsx
  client/my-sites/stats/wordads/index.jsx
Labels: Stats, [Status] Needs Review, WordAds

#72972 Stats: Enable tooltips of the 7-day highlights cards
  client/my-sites/stats/highlights-section/index.tsx
  packages/components/src/highlight-cards/highlight-card.tsx
  packages/components/src/highlight-cards/index.tsx
  packages/components/src/highlight-cards/style.scss
Labels: Stats, [Status] Needs Review

#72992 Make current plan slug check safe against undefined data
  client/my-sites/plans/main.jsx
Labels: Plans, Plans: eCommerce

#72865 Social: Fix pricing page bug after buying the advanced plan
  client/my-sites/plans/jetpack-plans/product-store/utils/get-product-icon.ts
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
  client/my-sites/plans/jetpack-plans/use-item-price.ts
  packages/calypso-products/src/constants/jetpack.ts
Labels: [Status] Needs Review

#72685 Update WP Courses banners to WP Learn
  client/assets/images/customer-home/courses-logo.png
  client/assets/images/customer-home/illustration--secondary-wp-courses.svg
  client/assets/images/customer-home/illustration--secondary-wp-learn.png
  client/assets/images/customer-home/learn-logo.png
  client/my-sites/customer-home/cards/education/wpcourses/index.jsx
  client/my-sites/customer-home/cards/tasks/wp-courses/index.jsx
Labels: [Status] Needs Review, [Type] Task

#72971 Sites Management Page: Render site icon fallback if mShots fails
  packages/components/src/site-thumbnail/fetch-await-redirect.ts
  packages/components/src/site-thumbnail/fetch-is-redirect.ts
  packages/components/src/site-thumbnail/index.tsx
  packages/components/src/site-thumbnail/test/site-thumbnail.test.tsx
  packages/components/src/site-thumbnail/use-mshots-img.tsx
Labels: [Type] Bug, Sites, [Status] Needs Review, Reviewer Can Merge

#72998 Plans 2023: Fix action buttons in comparison grid
  client/my-sites/plan-features-2023-grid/actions.tsx
  client/my-sites/plan-features-2023-grid/index.tsx
  client/my-sites/plan-features-2023-grid/plan-comparison-grid.tsx
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#72867 Fix premium domain not rendering the correct price when not returned from the suggestion endpoint
  client/components/domains/register-domain-step/index.jsx
Labels: [Status] Needs Review

#73005 E2E: Fix the Welcome Tour popup handler error
  packages/calypso-e2e/src/lib/components/editor-welcome-tour-component.ts
Labels: [Status] Needs Review

#72291 Copy Site: Include Marketplace Plugins when purchasing a new Copy Site
  client/landing/stepper/declarative-flow/internals/steps-repository/site-creation-step/index.tsx
  client/landing/stepper/hooks/use-site-copy.tsx
  client/my-sites/site-settings/site-tools/index.jsx
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
  packages/data-stores/src/onboard/actions.ts
  packages/data-stores/src/onboard/index.ts
  packages/data-stores/src/onboard/reducer.ts
  packages/data-stores/src/onboard/selectors.ts
  packages/onboarding/src/cart/index.tsx
  packages/onboarding/src/index.ts
Labels: Copy Site i1

#72931 Marketplace Themes: Fix the customize CTA on the theme page
  client/my-sites/theme/main.jsx
Labels: Themes, [Status] Needs Review

#72975 Docker webpack cache changes
  .teamcity/_self/bashNodeScript.kt
  .teamcity/_self/projects/WebApp.kt
  Dockerfile
  Dockerfile.base
  bin/check-log-for-cache-invalidation.sh
  client/webpack.config.js
Labels: [Status] Needs Review

#73019 Run cache check in separate Dockerfile step
  Dockerfile
Labels: [Status] Needs Review

#72469 Add/trial my plan page
  client/my-sites/plans/current-plan/ecommerce-trial/index.tsx
  client/my-sites/plans/current-plan/ecommerce-trial/style.scss
  client/my-sites/plans/current-plan/feature-included-card/index.tsx
  client/my-sites/plans/current-plan/feature-included-card/style.scss
  client/my-sites/plans/current-plan/feature-not-included-card/index.tsx
  client/my-sites/plans/current-plan/feature-not-included-card/style.scss
  client/my-sites/plans/current-plan/index.jsx
  client/my-sites/plans/doughnut-chart/index.tsx
  client/my-sites/plans/doughnut-chart/style.scss
  static/images/plans/wpcom/ecommerce-trial/advanced-customization.svg
  static/images/plans/wpcom/ecommerce-trial/best-in-class-hosting.svg
  static/images/plans/wpcom/ecommerce-trial/email.png
  static/images/plans/wpcom/ecommerce-trial/google-analytics.svg
  static/images/plans/wpcom/ecommerce-trial/jetpack-features.svg
  static/images/plans/wpcom/ecommerce-trial/launch.png
  static/images/plans/wpcom/ecommerce-trial/money.png
  static/images/plans/wpcom/ecommerce-trial/premium-themes.svg
  static/images/plans/wpcom/ecommerce-trial/priority-support.svg
  static/images/plans/wpcom/ecommerce-trial/promote.png
  static/images/plans/wpcom/ecommerce-trial/seo-tools.svg
  static/images/plans/wpcom/ecommerce-trial/shipping.png
  static/images/plans/wpcom/ecommerce-trial/themes.png
  static/images/plans/wpcom/ecommerce-trial/unlimited-products.svg
Labels: [Status] Needs Review

#73022 Exclude cache seralization messages from webpack log
  bin/check-log-for-cache-invalidation.sh
Labels: [Status] Needs Review

#72936 Merge trunk to branch docker image builds
  .teamcity/_self/lib/utils/MergeTrunk.kt
  .teamcity/_self/projects/WebApp.kt
Labels: [Status] Needs Review

#72940 Improve reader focus management when using "J" and "K" keyboard navigation
  client/reader/stream/index.jsx
Labels: [Status] Needs Review

#72842 Add built by wp marketing card
  client/assets/images/illustrations/built-by-wp-vert-blue.svg
  client/my-sites/marketing/tools/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#72793 Update domain upsell copy
  client/my-sites/customer-home/cards/features/domain-upsell/index.jsx
Labels: [Status] Needs Review, [Status] String Freeze

#72937 Odyssey: Add opt-out notice for odyssey
  apps/odyssey-stats/src/styles/wp-admin.scss
  client/lib/wpcom-xhr-wrapper/index.js
  client/my-sites/stats/site.jsx
  client/my-sites/stats/style.scss
  client/state/action-types.ts
  client/state/data-layer/wpcom/sites/jitm/index.js
  client/state/jitm/actions.js
  client/state/sites/selectors/has-opt-out-new-stats-notice.js
  packages/components/src/notice-banner/index.tsx
  packages/components/src/notice-banner/notice-banner.stories.jsx
  packages/components/src/notice-banner/style.scss
Labels: Stats, [Status] Needs Review, Odyssey Stats

#72816 Add "recycle content" to the Basic plan
  packages/calypso-products/src/translations.tsx
Labels: [Status] Needs Review

#72854 Added disclaimer for products in beta.
  client/my-sites/checkout/composite-checkout/components/checkout-terms.jsx
  client/my-sites/checkout/composite-checkout/components/jetpack-social-advanced-pricing-disclaimer.tsx
Labels: [Status] Needs Review

#72788 Add ability to resume Copy Site process
  client/landing/stepper/declarative-flow/copy-site.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-creation-step/index.tsx
  client/my-sites/customer-home/cards/constants.js
  client/my-sites/customer-home/cards/tasks/site-resume-copy/index.jsx
  client/my-sites/customer-home/locations/primary/index.jsx
  client/state/sites/constants.js
  packages/onboarding/src/cart/index.tsx
Labels: [Status] Needs Review, Copy Site i1

#72905 Marketplace: show only launched products from the dynamic catalog
  client/data/marketplace/use-wpcom-plugins-query.ts
  client/my-sites/plugins/use-plugins/index.ts
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#73043 Copy Site: Enable for all environments
  client/landing/stepper/declarative-flow/registered-flows.ts
  client/my-sites/site-settings/site-tools/index.jsx
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
  config/development.json
  config/wpcalypso.json
Labels: [Type] Task, Copy Site i1

#73010 Copy Site: Customize text used on initial Processing screen
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/hooks/use-processing-loading-messages.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/index.tsx
Labels: [Status] Needs Review, [Type] Task, Reviewer Can Merge, Copy Site i1

#73023 Pull Request Template: Use <h2> for description headings, move issue reference to the top
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Needs Review, DO NOT MERGE

#73020 Copy Site: Include Marketplace Themes when copying a site
  client/landing/stepper/hooks/use-site-copy.tsx
Labels: [Status] Needs Review, [Type] Task, Reviewer Can Merge, Copy Site i1

#72873 Copy Site: Add back functionality on domains step
  client/landing/stepper/declarative-flow/copy-site.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/domain-form-control.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx
Labels: [Status] Needs Review, Stepper, Copy Site i1

#72514 Improve tooltips in theme showcase
  client/components/theme/index.jsx
  client/components/theme/style.scss
  client/components/theme/test/premium-popover.jsx
  client/state/themes/selectors/get-marketplace-theme-subscription-prices.ts
  client/state/themes/selectors/index.js
  client/types.ts
Labels: Themes, [Status] Needs Review, [Status] String Freeze, Theme Showcase

#73011 Fix bug where centered paragraphs show up left aligned on reader full post view
  client/blocks/reader-full-post/style.scss
Labels: [Type] Bug, [Status] Needs Review, Reader

#72882 Proposal: WooExpress, Change default site creation from private to coming soon
  client/landing/stepper/declarative-flow/internals/steps-repository/site-creation-step/index.tsx
  client/my-sites/site-settings/form-general.jsx
Labels: [Status] Needs Review, WooExpress

#73027 Checkout: Support setting quantity of cart items by URL
  client/my-sites/checkout/composite-checkout/hooks/use-prepare-products-for-cart.ts
  client/my-sites/checkout/composite-checkout/test/checkout-main.tsx
  client/my-sites/checkout/composite-checkout/test/util/index.ts
Labels: [Status] Ready to Merge, Checkout

#72111 Update/add WooPay marketing email category settings
  client/mailing-lists/main.jsx
Labels: [Status] Needs Review

#73014 Fix bug where right aligned paragraphs show up left aligned on reader full post view
  client/blocks/reader-full-post/style.scss
Labels: [Type] Bug, [Status] Needs Review, Reader

#72582 Sensei Tailored Flow: Add 'Choose the purpose of your site' step
  client/landing/stepper/declarative-flow/internals/sensei-variables.scss
  client/landing/stepper/declarative-flow/internals/sensei.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/components/sensei-step-container/components.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/components/sensei-step-container/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/components/sensei-step-error/components.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/components/sensei-step-error/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/components/sensei-step-progress/components.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/components/sensei-step-progress/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-domain/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-launch/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-plan/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-plan/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-purpose/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-purpose/purpose-item.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-purpose/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/style.scss
  client/landing/stepper/declarative-flow/sensei.ts
  packages/onboarding/src/flow-progress/use-flow-progress.ts
Labels: [Status] Needs Review

#72840 Remove links to /courses and replace it with /learn in Universal Header & Footer Navbars for Calypso
  client/layout/universal-navbar-footer/index.tsx
  client/layout/universal-navbar-header/index.jsx
Labels: [Status] Needs Review

#73031 Jetpack Backup: Fetch last backup size
  client/state/data-layer/wpcom/sites/rewind/size/from-api.ts
  client/state/rewind/selectors/get-backup-current-site-size.ts
  client/state/rewind/selectors/index.ts
  client/state/rewind/size/reducer.ts
  client/state/rewind/size/test/reducer.js
  client/state/rewind/size/types.ts
  client/state/rewind/test/selectors.js
Labels: [Status] Ready to Merge, Jetpack Backup

#73029 Change to triggering base images twice a day
  .teamcity/settings.kts
Labels: [Status] Needs Review

#72847 Post editor domain upsell: add callout
  client/components/domains/domain-upsell-callout/index.jsx
  client/components/domains/domain-upsell-callout/style.scss
  client/gutenberg/editor/calypsoify-iframe.tsx
Labels: [Status] Needs Review

#72985 Jetpack Connection: redirect to user connection from checkout page
  client/my-sites/controller.js
Labels: Jetpack, [Status] Needs Review, Checkout, Jetpack Search, Jetpack Backup

#73032 Update backup features tests to use strings from function
  client/my-sites/checkout/composite-checkout/test/wp-checkout-order-summary.tsx
Labels: [Status] Needs Review

#72938 Create the domain upsell steps component
  client/assets/images/icons/wordpress-logo.svg
  client/my-sites/domains/components/domain-and-plan-package/README.md
  client/my-sites/domains/components/domain-and-plan-package/navigation/index.jsx
  client/my-sites/domains/components/domain-and-plan-package/navigation/style.scss
Labels: [Status] Needs Review, [Status] String Freeze

#73063 Add better pricing messaging on trial plans
  client/components/jetpack/card/jetpack-product-card/display-price/paid.tsx
  client/components/jetpack/card/jetpack-product-card/display-price/price-aria-label.tsx
  client/components/jetpack/card/jetpack-product-card/display-price/style.scss
  client/components/jetpack/card/jetpack-product-card/display-price/time-frame.tsx
  client/my-sites/plan-price/index.tsx
  client/my-sites/plans/jetpack-plans/product-lightbox/payment-plan.tsx
Labels: [Status] Needs Review

#72361 Add/dailyprompt blockquote in reader
  client/blocks/reader-excerpt/index.jsx
  client/blocks/reader-excerpt/style.scss
Labels: [Status] Needs Review

#72991 Pattern Assembler - Move posts patterns to the top of the list in the write flow
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/patterns-data.ts
Labels: [Status] Needs Review

#73075 Plans 2023: Add tooltip to logos
  client/my-sites/plan-features-2023-grid/index.tsx
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#73079 i18n: Fix plural placeholder in Jetpack partial discount
  client/components/jetpack/card/jetpack-product-card/display-price/time-frame.tsx
Labels: [Status] Needs Review

#73008 E2E: Fix flaky comment unliking
  test/e2e/specs/published-content/likes__comment.ts
Labels: [Status] Needs Review

#72970 Update/calypso signup complete event
  client/lib/analytics/signup.js
  client/signup/main.jsx
Labels: [Status] Needs Review

#72576 update/pricing page title
  client/jetpack-cloud/sections/comparison/content.tsx
Labels: Jetpack, [Status] Needs Review, [Status] String Freeze, Jetpack Cloud

#72914 Plans Grid 2023: mobile card margins
  client/my-sites/plan-features-2023-grid/style.scss
Labels: [Status] Needs Review, 2023 Pricing Page ⚡

#73040 Reading Settings: Update the label/description on the "Welcome email text" and "Comment follow email text" settings
  client/my-sites/site-settings/reading-newsletter-settings/EmailsTextSetting.tsx
  client/my-sites/site-settings/style.scss
Labels: [Status] Needs Review, Reading Settings

#73006 Marketplace: Add Jetpack Search free plan
  client/my-sites/plugins/constants.js
  client/my-sites/plugins/plugin-details-CTA/preinstalled-premium-plugins-CTA.jsx
  client/my-sites/plugins/use-preinstalled-premium-plugin/index.js
Labels: [Status] Needs Review, [Status] String Freeze

#72960 Plans section: Modernized header and navbar / part 1
  client/my-sites/plans/current-plan/index.jsx
  client/my-sites/plans/current-plan/style.scss
  client/my-sites/plans/header.jsx
  client/my-sites/plans/header.scss
  client/my-sites/plans/main.jsx
  client/my-sites/plans/modernized-layout.scss
  client/my-sites/plans/modernized-layout.tsx
  client/my-sites/plans/navigation.jsx
  client/my-sites/plans/style.scss
Labels: [Status] In Progress, [Status] Needs Review, [Status] Needs Design Review, [Status] Design Input Requested, 2023 Pricing Page ⚡

#73007 Jetpack Backup: Update component to use custom backup retention days if set
  client/components/backup-storage-space/index.tsx
  client/components/backup-storage-space/storage-usage-levels.ts
  client/state/data-layer/wpcom/sites/rewind/size/from-api.ts
  client/state/rewind/selectors/get-backup-retention-days.ts
  client/state/rewind/selectors/index.ts
  client/state/rewind/size/reducer.ts
  client/state/rewind/size/test/reducer.js
  client/state/rewind/size/types.ts
  client/state/rewind/test/selectors.js
Labels: [Status] Needs Review, Jetpack Cloud, Jetpack Backup

#73017 Prepare the domain page to work with the experiment - backend strategy
  client/layout/index.jsx
  client/lib/user/shared-utils/filter-user-object.js
  client/lib/user/user.d.ts
  client/my-sites/domains/domain-search/index.jsx
  client/my-sites/domains/style.scss
  client/state/selectors/is-domain-sidebar-experiment-user.js
  client/state/selectors/test/is-domain-sidebar-experiment-user.js
Labels: [Status] Needs Review

#72978 Redux: Convert countries state slice to TypeScript
  client/my-sites/checkout/composite-checkout/hooks/use-country-list.ts
  client/signup/steps/woocommerce-install/step-store-address/index.tsx
  client/state/countries/actions.ts
  client/state/countries/reducer.js
  client/state/countries/reducer.ts
  client/state/countries/types.ts
  client/state/selectors/get-countries.js
  client/state/selectors/get-countries.ts
  client/state/types.ts
Labels: [Status] Needs Review

#72948 Add quick filters for domain upsell experiment
  client/components/domains/register-domain-step/index.jsx
  client/components/domains/register-domain-step/style.scss
  packages/search/src/search.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#73064 Stats: Change wording 'Followers' to 'Subscribers'
  client/blocks/followers-count/index.jsx
  client/my-sites/stats/comment-follows/index.jsx
  client/my-sites/stats/stats-comment-followers-page/index.jsx
  client/my-sites/stats/stats-comments/index.jsx
  client/my-sites/stats/stats-followers/index.jsx
  client/my-sites/stats/stats-reach/index.jsx
  client/my-sites/stats/stats-strings.js
  packages/components/src/highlight-cards/annual-highlight-cards.tsx
Labels: Stats, [Status] Needs Review

#73117 Revert "Plans section: Modernized header and navbar / part 1"
  client/my-sites/plans/current-plan/index.jsx
  client/my-sites/plans/current-plan/style.scss
  client/my-sites/plans/header.jsx
  client/my-sites/plans/header.scss
  client/my-sites/plans/main.jsx
  client/my-sites/plans/modernized-layout.scss
  client/my-sites/plans/modernized-layout.tsx
  client/my-sites/plans/navigation.jsx
  client/my-sites/plans/style.scss
Labels: [Status] Needs Review

#73066 Stats: Format numbers in 7-day highlight
  packages/components/src/highlight-cards/highlight-card.tsx
Labels: [Type] Bug, [Status] Ready to Merge

#73118 Stats: Fix retrieve the startDate from a nullable object inside the StatsPostSummary page
  client/my-sites/stats/stats-post-summary/index.jsx
Labels: [Type] Bug, Stats, [Status] Ready to Merge

#72987 Stats: Replace comparing text with icon and tooltips for the 7-day highlights section
  packages/components/src/highlight-cards/charts/comparingInfoBars.tsx
  packages/components/src/highlight-cards/charts/comparingInfoRange.tsx
  packages/components/src/highlight-cards/charts/index.tsx
  packages/components/src/highlight-cards/index.tsx
  packages/components/src/highlight-cards/style.scss
Labels: Stats, [Status] Ready to Merge

#73021 VideoPress Onboarding: add support for an optional "more" button on Intro step
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/icons/checkmark-icon.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/icons/close-icon.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/intro.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/videopress-intro-modal-content.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/videopress-intro-modal-styles.scss
Labels: [Status] Needs Review

#73119 Domains: Fix problem with domain-only signup flows
  client/signup/main.jsx
Labels: Domains

#73071 GH Integration: Disconnect button which deletes the keyring connection
  client/my-sites/hosting/github/disconnect-github-expander/index.tsx
  client/my-sites/hosting/github/disconnect-github-expander/style.scss
  client/my-sites/hosting/github/github-connect-card/index.tsx
  client/my-sites/hosting/github/index.tsx
  client/my-sites/hosting/github/test/disconnect-github-expander.test.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting Configuration, WPCOM + GitHub Integration i1

#73122 Add steps style to mobile view and add steps to domain search page
  client/my-sites/domains/components/domain-and-plan-package/navigation/index.jsx
  client/my-sites/domains/components/domain-and-plan-package/navigation/style.scss
  client/my-sites/domains/domain-search/index.jsx
Labels: [Status] Needs Review

#73062 Prepare the plans page to work with the experiment (backend strategy)
  client/components/domains/register-domain-step/style.scss
  client/my-sites/plan-features-comparison/actions.jsx
  client/my-sites/plan-features-comparison/index.jsx
  client/my-sites/plans-features-main/index.jsx
  client/my-sites/plans/main.jsx
  client/my-sites/plans/style.scss
Labels: [Status] Needs Review, [Status] String Freeze

#73123 Stats: Split insights, wordads, post detail and comment follows from the first bundle
  client/my-sites/stats/controller.jsx
Labels: Stats, [Status] Needs Review, Odyssey Stats

#73070 reader: Restore focus when using back button from full post view to feed
  client/reader/stream/index.jsx
Labels: [Status] Needs Review

#73033 Filter out duplicate pending comments
  client/state/lasagna/post-channel/middleware.js
Labels: [Status] Needs Review

#73127 Fix typos in scss comments added in #73071
  client/my-sites/hosting/github/disconnect-github-expander/style.scss
Labels: WPCOM + GitHub Integration i1
