Repository Automattic/wp-calypso, pull requests merged in 2023-09, with the labels that each got.

#81309 (2nd try) Assembler Flow: Prepare the Celebration step
  client/landing/stepper/declarative-flow/design-first.ts
  client/landing/stepper/declarative-flow/internals/components/site-preview/index.tsx
  client/landing/stepper/declarative-flow/internals/components/site-preview/preview-toolbar.scss
  client/landing/stepper/declarative-flow/internals/components/site-preview/preview-toolbar.tsx
  client/landing/stepper/declarative-flow/internals/components/site-preview/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/celebration-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/celebration-step/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/celebration-step/test/index.test.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/celebration-step/test/use-celebration-data.test.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/celebration-step/use-celebration-data.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/launchpad-site-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
  client/landing/stepper/declarative-flow/start-writing.ts
  client/landing/stepper/declarative-flow/with-theme-assembler-flow.ts
  packages/onboarding/src/utils/flows.ts
  test/e2e/specs/onboarding/setup__start-writing.ts
Labels: [Status] Needs Review

#81302 BackupBrowser: Add ID to the Redux include/exclude lists
  client/my-sites/backup/backup-contents-page/file-browser/file-browser-node.tsx
  client/state/rewind/browser/actions.ts
  client/state/rewind/browser/reducer.ts
  client/state/rewind/browser/types.ts
  client/state/rewind/selectors/get-backup-browser-check-list.ts
Labels: [Status] Needs Review

#81067 Pro Dashboard: Add Create new site split button in the dashboard.
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/style.scss
  client/jetpack-cloud/style.scss
Labels: [Status] Needs Review, Jetpack Cloud

#81288 Subscriptions Management: Move SiteSubscriptionPage component to client/blocks
  client/blocks/reader-site-subscription/cancel-paid-subscription-modal.tsx
  client/blocks/reader-site-subscription/context.tsx
  client/blocks/reader-site-subscription/details.tsx
  client/blocks/reader-site-subscription/helpers.tsx
  client/blocks/reader-site-subscription/index.tsx
  client/blocks/reader-site-subscription/settings.tsx
  client/blocks/reader-site-subscription/styles.scss
  client/blocks/reader-site-subscription/test/index.tsx
  client/landing/subscriptions/components/cancel-paid-subscription-modal/index.ts
  client/landing/subscriptions/components/site-subscription-page/index.tsx
  client/landing/subscriptions/components/site-subscription-page/site-subscription-context.tsx
  client/landing/subscriptions/components/site-subscription-page/site-subscription-provider.tsx
  packages/data-stores/src/reader/helpers/type-guards.ts
  packages/data-stores/src/reader/queries/use-site-subscription-details-query.ts
  packages/data-stores/src/reader/types/index.ts
Labels: [Status] Needs Review, Subscription Management, [SM] Reader Portal

#81217 Migration trial: Add tracking events on 'Trial expired' page
  client/my-sites/plans/ecommerce-trial/controller.jsx
  client/my-sites/plans/ecommerce-trial/ecommerce-trial-expired/index.tsx
  client/my-sites/plans/trials/business-trial-expired/index.tsx
  client/my-sites/site-settings/controller.js
Labels: [Status] Needs Review, Migration Trials

#81091 Marketplace: Add notice to indicate plugins not tested with recent WordPress version
  client/data/wp-version/use-wp-version-query.ts
  client/lib/wporg/index.js
  client/my-sites/plugins/plugin-details-sidebar/index.jsx
  client/my-sites/plugins/plugin-details.jsx
  client/my-sites/plugins/use-plugin-is-maintained/index.js
Labels: [Status] String Freeze

#80618 Logged Out Theme Showcase: Add new categories to SEO map
  client/my-sites/themes/use-theme-showcase-logged-out-seo-content.js
Labels: [Status] Needs Review, [Status] String Freeze, T-Rex

#81087 Design Picker: Upgrade Modal to support Marketplace Themes
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/upgrade-modal.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/upgrade-modal.tsx
Labels: [Status] Needs Review

#81248 Localize the links to support documents on https://wordpress.com/subscribers
  client/my-sites/subscribers/components/empty-list-view/empty-list-view.tsx
  client/my-sites/subscribers/components/grow-your-audience/grow-your-audience.tsx
Labels: [Status] Needs Review

#81296 Remove white behind action bar icons in reader
  client/blocks/follow-button/style.scss
  client/blocks/reader-full-post/style.scss
Labels: [Type] Bug, [Pri] Low, [Status] Needs Review, [Size] XS

#81295 Hosting metrics: Add bottom space for big screens
  client/my-sites/site-monitoring/style.scss
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting Metrics i1

#81305 Launchpad: Added skip button to fullscreen Launchpad - Pt 2
  client/my-sites/customer-home/cards/launchpad/pre-launch.tsx
  packages/launchpad/src/setup-actions.ts
  packages/launchpad/src/types.ts
Labels: [Status] Needs Review, [Feature] Launchpad

#81304 BackupBrowser: Add granular restore page skeleton
  client/my-sites/backup/backup-contents-page/file-browser/file-browser-node.tsx
  client/my-sites/backup/backup-contents-page/file-browser/file-info-card.tsx
  client/my-sites/backup/backup-contents-page/style.scss
  client/my-sites/backup/controller.js
  client/my-sites/backup/index.js
  client/my-sites/backup/paths.ts
  client/my-sites/backup/rewind-flow/granular-restore.tsx
  client/my-sites/backup/rewind-flow/index.tsx
  client/my-sites/backup/rewind-flow/style.scss
  client/my-sites/backup/rewind-flow/types.ts
Labels: [Status] Needs Review, Jetpack Backup

#81294 hide owner column if all domains belong to the same current user
  packages/domains-table/src/domains-table/__tests__/index.tsx
  packages/domains-table/src/utils.ts
Labels: [Status] Needs Review, Reviewer Can Merge, Domain Management i1

#80982 Mailing Lists: Remove category for Jetpack agency onboarding notifications
  client/mailing-lists/main.jsx
Labels: [Status] Needs Review

#81317 Handle skipped launchpad screen in update-design flow and launchpad step
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx
  client/landing/stepper/declarative-flow/update-design.ts
  packages/data-stores/src/queries/use-launchpad.ts
Labels: [Status] Needs Review, [Feature Group] Signup & Site Onboarding, [Feature] Design Picker, Stepper, [Feature] Launchpad

#81104 100 Year Plan: Update checkout line item and sidebar sublabels
  client/my-sites/checkout/src/components/wp-checkout-order-summary.tsx
  packages/shopping-cart/src/empty-carts.ts
  packages/shopping-cart/src/types.ts
  packages/wpcom-checkout/src/checkout-line-items.tsx
Labels: [Status] Needs Review

#81120 Domain Management i1: Refactor domain links into their own module
  packages/domains-table/src/domains-table/domains-table-row.tsx
  packages/domains-table/src/domains-table/domains-table-site-cell.tsx
  packages/domains-table/src/utils/paths.ts
Labels: [Status] Needs Review, Reviewer Can Merge, Domain Management i1

#81254 Paid Stats: Apply commercial site detection to Notice Banners
  client/my-sites/stats/stats-notices/all-notice-definitions.ts
  client/my-sites/stats/stats-notices/index.tsx
  client/my-sites/stats/stats-notices/types.ts
Labels: Stats, [Status] Needs Review

#81250 Stats: Add new commercial purchase page
  client/my-sites/stats/stats-purchase/index.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-commercial.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-notice.jsx
  client/my-sites/stats/stats-purchase/stats-purchase-shared.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
  client/my-sites/stats/stats-purchase/styles.scss
Labels: Stats, [Status] Needs Review

#80893 Theme Detail page: Update banner copy for Partner themes
  client/my-sites/theme/main.jsx
Labels: [Status] Needs Review, [Status] String Freeze

#81070 Assembler: CTA copy update
  packages/design-picker/src/components/pattern-assembler-cta/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#81130 Assembler: Categories should only show 6-8 patterns by default
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/events.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-patterns-map-by-category.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-panel.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-panel.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-renderer.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-pattern-list-panel.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/types.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/utils.ts
Labels: [Status] Needs Review

#81019 Assembler: Add the Upsell screen
  client/components/premium-global-styles-upgrade-modal/index.tsx
  client/components/premium-global-styles-upgrade-modal/use-global-styles-upgrade-translations.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/constants.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/events.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-current-screen.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-custom-styles.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-global-styles-upgrade-modal.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-global-styles-upgrade-props.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-screen.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-main.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-styles.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-upsell.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-upsell.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#81334 Stats: Add new personal plan purchase page
  client/my-sites/stats/stats-purchase/index.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-personal.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-wizard.jsx
Labels: Stats, [Status] Needs Review

#81330 Domain Management i1: refactored table proposal based on React.Context
  packages/domains-table/src/domains-table-header/index.tsx
  packages/domains-table/src/domains-table/domains-table-body.tsx
  packages/domains-table/src/domains-table/domains-table-header.tsx
  packages/domains-table/src/domains-table/domains-table-row.tsx
  packages/domains-table/src/domains-table/domains-table-toolbar.tsx
  packages/domains-table/src/domains-table/domains-table.tsx
  packages/domains-table/src/domains-table/index.tsx
Labels: [Status] Needs Review, DO NOT MERGE, Domain Management i1

#81337 Disable Live Preview on Atomic sites
  client/state/themes/selectors/get-is-live-preview-supported.ts
Labels: [Status] Needs Review

#81335 Track canvas mode changes in the Site Editor
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/block-editor-nux.js
  apps/wpcom-block-editor/package.json
  apps/wpcom-block-editor/src/wpcom/features/tracking/site-editor-load.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/site-editor-load.tsx
  yarn.lock
Labels: [Status] Needs Review

#81127 Jetpack E2E: new flow for the `Ad` block.
  packages/calypso-e2e/src/lib/blocks/block-flows/ad.ts
  packages/calypso-e2e/src/lib/blocks/block-flows/index.ts
  test/e2e/specs/blocks/blocks__jetpack-earn.ts
Labels: [Status] Needs Review

#80867 Update custom name servers info notice copy (Dns Records setting and card)
  client/my-sites/domains/domain-management/dns/dns-records.jsx
  client/my-sites/domains/domain-management/settings/cards/style.scss
  client/my-sites/domains/domain-management/settings/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#81341 Stats: Add upgrade buttons for already purchase notices
  client/my-sites/stats/stats-purchase/index.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-notice.jsx
  client/my-sites/stats/stats-purchase/styles.scss
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#80812 Add "Restore default CNAME record" option
  client/my-sites/domains/domain-management/dns/dns-menu-options-button.tsx
  client/my-sites/domains/domain-management/dns/dns-records.jsx
  client/my-sites/domains/domain-management/dns/restore-default-cname-record-dialog.jsx
  client/my-sites/domains/domain-management/dns/types.ts
Labels: [Status] Needs Review, [Status] String Freeze

#81178 Migration trial: Extend tracking event properties
  client/blocks/importer/wordpress/import-everything/index.tsx
  client/blocks/importer/wordpress/import-everything/pre-migration/index.tsx
  client/blocks/importer/wordpress/import-everything/pre-migration/migration-credentials-form.tsx
  client/blocks/importer/wordpress/import-everything/pre-migration/types.ts
  client/blocks/importer/wordpress/import-everything/pre-migration/update-plugins.tsx
  client/blocks/importer/wordpress/import-everything/pre-migration/upgrade-plan.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/migration-trial/style.scss
Labels: [Status] Needs Review, Migration Trials

#81047 Domain Forwarding: Add subdomain support
  client/data/domains/forwarding/use-domain-forwarding-query.ts
  client/my-sites/domains/domain-management/settings/cards/domain-forwarding-card.tsx
  client/my-sites/domains/domain-management/settings/cards/style.scss
Labels: [Status] Needs Review, [Status] String Freeze

#81333 Stats: unify purchases loading for Odyssey and Calypso
  apps/odyssey-stats/src/components/odyssey-query-site-purchases.ts
  apps/odyssey-stats/webpack.config.js
  client/my-sites/stats/stats-notices/index.tsx
  client/my-sites/stats/stats-notices/use-site-purchases-on-odyssey-stats.tsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#81326 BackupBrowser: Integrate granular restore flow
  client/my-sites/backup/rewind-flow/granular-restore.tsx
  client/my-sites/backup/rewind-flow/style.scss
  client/state/action-types.ts
  client/state/activity-log/actions.js
  client/state/data-layer/wpcom/activity-log/rewind/to/index.js
Labels: [Status] Needs Review, Jetpack Backup

#81336 Stats: refactor product test to a hook
  client/my-sites/stats/hooks/use-stats-purchases.ts
  client/my-sites/stats/stats-purchase/index.tsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#81048 Earn: Refactor ad settings to functional component
  client/my-sites/earn/ads/form-settings.jsx
Labels: [Status] Needs Review, Earn

#80661 Launchpad: Added skip button to fullscreen Launchpad
  client/landing/stepper/declarative-flow/write.ts
  client/my-sites/customer-home/cards/constants.js
  client/my-sites/customer-home/cards/launchpad/pre-launch.tsx
  client/my-sites/customer-home/locations/secondary/index.jsx
  packages/data-stores/src/queries/use-launchpad.ts
  packages/launchpad/src/setup-actions.ts
  packages/launchpad/src/types.ts
Labels: [Status] Needs Review, [Feature] Launchpad

#81372 Paid Stats: Refactor givenSiteId for the purchase page
  client/my-sites/stats/controller.jsx
  client/my-sites/stats/stats-purchase/index.tsx
Labels: Stats, [Status] Needs Review

#81380 Stats: add commercial use support for Complete plans
  client/my-sites/stats/hooks/use-stats-purchases.ts
  client/my-sites/stats/stats-purchase/index.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-notice.jsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#81350 Update text styles for launchpad checklist items
  packages/launchpad/src/checklist-item/style.scss
Labels: [Status] Needs Review, [Feature] Launchpad

#81161 Jetpack Partner Portal: implement UI for creating a site page.
  client/jetpack-cloud/sections/partner-portal/primary/wpcom-atomic-hosting/card-content.tsx
  client/jetpack-cloud/sections/partner-portal/primary/wpcom-atomic-hosting/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/wpcom-atomic-hosting/style.scss
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#81382 Jetpack Partner Portal: implement tooltip for the feature items in the create site page
  client/jetpack-cloud/sections/partner-portal/primary/wpcom-atomic-hosting/card-content.tsx
  client/jetpack-cloud/sections/partner-portal/primary/wpcom-atomic-hosting/feature-item.tsx
  client/jetpack-cloud/sections/partner-portal/primary/wpcom-atomic-hosting/style.scss
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#81311 Jetpack Pro Dashboard: Implement a popover to showcase the WPCOM hosting feature
  client/components/split-button/index.jsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-top-header-buttons/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-top-header-buttons/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-top-header-buttons/wpcom-hosting-popover.tsx
  client/state/jetpack-agency-dashboard/selectors.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#81356 User Intent: Survey urls and copy adjustments.
  client/landing/stepper/declarative-flow/internals/steps-repository/videopress-onboarding-intent/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/videopress-onboarding-intent/videopress-onboarding-intent-modal-channel.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/videopress-onboarding-intent/videopress-onboarding-intent-modal-video-upload.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/videopress-onboarding-intent/videopress-onboarding-intent-modal.tsx
Labels: [Status] Needs Review

#81389 Subscriptions Management: Introduce use-site-subscription-query hook
  client/blocks/reader-site-subscription/details.tsx
  client/blocks/reader-site-subscription/helpers.tsx
  client/blocks/reader-site-subscription/index.tsx
  client/blocks/reader-site-subscription/settings.tsx
  client/landing/subscriptions/components/site-subscriptions-list/site-row.tsx
  client/reader/hooks/use-site-subscription-query.ts
  packages/data-stores/src/reader/index.ts
  packages/data-stores/src/reader/mutations/test/use-site-delivery-frequency-mutation.test.tsx
  packages/data-stores/src/reader/mutations/use-site-delivery-frequency-mutation.ts
  packages/data-stores/src/reader/mutations/use-site-email-me-new-comments-mutation.ts
  packages/data-stores/src/reader/mutations/use-site-email-me-new-posts-mutation.ts
  packages/data-stores/src/reader/mutations/use-site-notify-me-of-new-posts-mutation.ts
  packages/data-stores/src/reader/mutations/use-site-subscribe-mutation.ts
  packages/data-stores/src/reader/mutations/use-site-unsubscribe-mutation.ts
Labels: [Status] Needs Review, [Feature] Reader, Subscription Management, [SM] Reader Portal

#81211 Design picker: Fix overflowing sidebar
  packages/design-preview/src/components/style.scss
Labels: [Status] Ready to Merge, [Feature] Design Picker

#81358 Enable VideoPress User Intent In Prod.
  config/horizon.json
  config/production.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#81398 I18N: Add context to total number of subscribers.
  client/my-sites/subscribers/components/subscriber-list-container/subscriber-list-container.tsx
Labels: [Status] Needs Review

#81403 Fix failing e2e videopress test
  test/e2e/specs/onboarding/setup__videopress.ts
Labels: [Status] Needs Review

#81320 Hosting Metrics: Toggle the expanded row on click
  client/my-sites/site-monitoring/components/site-logs-table/site-logs-table-row.tsx
  client/my-sites/site-monitoring/components/site-logs-table/style.scss
Labels: [Status] Needs Review, Site Monitoring

#81392 Change DSP widget JS URL
  client/lib/promote-post/index.ts
Labels: [Status] Needs Review

#81396 Subscriptions Management: Render site subscription details page in reader
  client/blocks/reader-site-subscription/context.tsx
  client/blocks/reader-site-subscription/index.tsx
  client/landing/subscriptions/components/site-subscription-page/site-subscription-provider.tsx
  client/landing/subscriptions/components/site-subscriptions-list/site-row.tsx
  client/reader/controller.js
  client/reader/index.js
  client/reader/site-subscription/index.tsx
  client/reader/site-subscription/site-subscription-provider.tsx
  client/reader/site-subscription/site-subscription.tsx
  client/sections.js
Labels: [Status] Needs Review, Subscription Management, [SM] Reader Portal

#81114 Refactor/minimum currency amounts
  client/my-sites/earn/components/add-edit-plan-modal/index.tsx
  client/state/memberships/settings/reducer.js
  client/state/memberships/settings/selectors.js
Labels: [Status] In Progress, [Status] Needs Review

#81368 Import flow: Update importer URL generation logic
  client/blocks/import/util.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/import-ready-preview/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import-ready/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import/helper.ts
Labels: [Status] Needs Review

#81402 Redirect to Customer Home from domain-upsell flow in some cases
  client/landing/stepper/declarative-flow/domain-upsell.ts
Labels: [Status] Needs Review, Stepper, [Feature] Launchpad

#81318 Launchpad: Add the skip behavior for the Build intent
  client/landing/stepper/declarative-flow/build.ts
Labels: [Status] Needs Review, [Feature] Launchpad

#81420 Revert "Launchpad: Add the skip behavior for the Build intent"
  client/landing/stepper/declarative-flow/build.ts
Labels: [Status] Needs Review

#81378 BackupBrowser: Disable restore button when site has no valid credentials
  client/my-sites/backup/backup-contents-page/file-browser/file-info-card.tsx
  client/state/rewind/selectors/can-restore-site.ts
  client/state/rewind/selectors/test/can-restore-site.js
Labels: [Status] Needs Review, Jetpack Backup

#81319 Newsletter Categories: Fix error when marking as newsletter category
  client/data/newsletter-categories/use-mark-as-newsletter-category-mutation.tsx
  client/data/newsletter-categories/use-unmark-as-newsletter-category-mutation.tsx
Labels: [Status] Needs Review, Newsletter Categories

#81327 BackupBrowser: release granular restore for single files
  client/my-sites/backup/backup-contents-page/file-browser/file-info-card.tsx
  client/my-sites/backup/rewind-flow/granular-restore.tsx
Labels: [Status] Needs Review, [Status] Needs Privacy Updates

#81359 Adjust commercial page styling for WPCOM
  client/assets/images/stats/calypso-purchase-stats-graph.svg
  client/my-sites/stats/stats-purchase/index.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-svg.tsx
  client/my-sites/stats/stats-purchase/styles.scss
Labels: Stats, [Status] Needs Review

#81430 Fix E2E block insertion from sidebar
  packages/calypso-e2e/src/lib/components/editor-sidebar-block-inserter-component.ts
Labels: [Status] Needs Review

#81173 Jetpack Partner Portal: implement WPCOM atomic hosting notification banner
  client/components/banner/index.jsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/lib/constants.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-add-license-notification/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-add-license-notification/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-add-license-notification/wpcom-atomic-hosting-notification.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud, Jetpack Licensing Portal, Jetpack Licensing

#81256 Jetpack E2E: Paywall block.
  packages/calypso-e2e/src/lib/blocks/block-flows/donations-form.ts
  packages/calypso-e2e/src/lib/blocks/block-flows/index.ts
  packages/calypso-e2e/src/lib/blocks/block-flows/paywall.ts
  packages/calypso-e2e/src/lib/blocks/block-flows/types.ts
  packages/calypso-e2e/src/lib/pages/editor-page.ts
  test/e2e/specs/blocks/blocks__jetpack-earn.ts
  test/e2e/specs/blocks/shared/block-smoke-testing.ts
Labels: [Status] Needs Review

#81279 ToS on the checkout page for the 100 year plan
  client/lib/cart-values/cart-items.ts
  client/me/purchases/manage-purchase/payment-method-selector/index.tsx
  client/me/purchases/manage-purchase/payment-method-selector/tos-text.tsx
  client/my-sites/checkout/src/components/bundled-domain-notice.jsx
  client/my-sites/checkout/src/components/checkout-terms.tsx
  client/my-sites/checkout/src/components/plan-terms-100-year.tsx
  client/my-sites/checkout/src/components/refund-terms-100-year.tsx
  client/my-sites/checkout/src/components/terms-of-service.tsx
Labels: [Status] Needs Review

#81312 Domain Management i1: show indicators when bulk jobs are happening
  packages/data-stores/src/index.ts
  packages/data-stores/src/queries/use-bulk-domain-update-status-query.ts
  packages/domains-table/src/bulk-actions-toolbar/style.scss
  packages/domains-table/src/domains-table-filters/style.scss
  packages/domains-table/src/domains-table/domains-table-body.tsx
  packages/domains-table/src/domains-table/domains-table-bulk-update-notice.tsx
  packages/domains-table/src/domains-table/domains-table-row.tsx
  packages/domains-table/src/domains-table/domains-table-status-cell.tsx
  packages/domains-table/src/domains-table/domains-table.tsx
  packages/domains-table/src/domains-table/index.tsx
  packages/domains-table/src/domains-table/style.scss
  packages/domains-table/src/status-popover/index.tsx
  packages/domains-table/src/type-declarations.d.ts
  packages/domains-table/src/use-domain-bulk-update-status.ts
Labels: [Status] Needs Review, Domain Management i1

#81440 Earn: Convert membership constants to TS
  client/my-sites/earn/memberships/constants.ts
Labels: [Status] Needs Review, Earn

#81425 Launchpad: Add the skip behavior for the Build intent
  client/landing/stepper/declarative-flow/build.ts
  test/e2e/specs/plans/plans__signup-business.ts
Labels: [Status] Needs Review

#81260 Domains: Add Apple iCloud Mail to DNS Records page
  client/lib/domains/constants.js
  client/my-sites/domains/domain-management/email-setup/index.jsx
  client/my-sites/domains/domain-management/email-setup/style.scss
Labels: [Status] Needs Review

#81410 Inline Comments - move isExpanded component state to calypso state
  client/blocks/comments/post-comment-list.jsx
  client/blocks/reader-post-card/index.jsx
  client/blocks/reader-post-card/post-card-comments.jsx
  client/reader/stream/empty-search-recommended-post.jsx
  client/reader/stream/post.jsx
  client/state/action-types.ts
  client/state/comments/actions.js
  client/state/comments/reducer.js
  client/state/comments/selectors/get-inline-comments-expanded-state.js
  client/state/comments/selectors/index.js
  client/state/comments/test/actions.js
  client/state/comments/test/reducer.js
  client/state/comments/test/selectors.js
Labels: [Status] Needs Review

#81281 Jetpack Error UX: Fix rpc handling error
  client/state/jetpack-connection-health/selectors/is-jetpack-connection-problem.js
Labels: [Type] Bug, [Status] Needs Review

#81452 I18N: Translate Video stats headers
  client/my-sites/stats/videopress-stats-module/index.jsx
Labels: [Status] Needs Review

#81344 Add an A/B test for quick responses in the Help Center
  packages/help-center/src/components/help-center-contact-form.tsx
  packages/help-center/src/hooks/use-chat-status.ts
  packages/help-center/src/types.ts
Labels: [Status] Needs Review

#81419 Importers list: Fix alignment bug and adapt screen for mobile device
  client/blocks/import/list/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/import/style.scss
Labels: [Status] Needs Review

#81429 Import flow: Get rid of obsolete capture-retired screen and feature flag
  client/blocks/import/capture-retired/index.tsx
  client/blocks/import/capture-retired/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/import/index.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#81448 Theme Showcase: Track clicks on the active theme
  client/my-sites/themes/themes-selection.jsx
Labels: [Status] Needs Review, T-Rex

#81447 Update log queries to use GET method
  client/data/hosting/use-site-logs-query.ts
  client/my-sites/site-monitoring/hooks/use-site-logs-downloader.ts
Labels: [Status] Needs Review

#81408 Paid/Free Confidence check experiment name update
  client/my-sites/plans-features-main/hooks/use-is-custom-domain-allowed-on-free-plan.ts
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review

#81416 SiteSelector: Redirect to /backup when switching site while on granular-restore page
  client/components/site-selector/index.jsx
Labels: [Status] Needs Review

#81454 Fix lack of padding under comment form button
  client/blocks/comments/form.scss
Labels: [Type] Bug, [Pri] Normal, [Status] Needs Review, [Size] XS

#81451 Do not show bottom image on coming-soon modals.
  client/assets/images/onboarding/videopress-onboarding-intent/intent-blog.png
  client/assets/images/onboarding/videopress-onboarding-intent/intent-channel.png
  client/assets/images/onboarding/videopress-onboarding-intent/intent-jetpack.png
  client/assets/images/onboarding/videopress-onboarding-intent/intent-other.png
  client/assets/images/onboarding/videopress-onboarding-intent/intent-portfolio.png
  client/assets/images/onboarding/videopress-onboarding-intent/intent-single-video.png
  client/landing/stepper/declarative-flow/internals/steps-repository/videopress-onboarding-intent/videopress-onboarding-intent-modal-blog.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/videopress-onboarding-intent/videopress-onboarding-intent-modal-channel.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/videopress-onboarding-intent/videopress-onboarding-intent-modal-jetpack.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/videopress-onboarding-intent/videopress-onboarding-intent-modal-other.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/videopress-onboarding-intent/videopress-onboarding-intent-modal-portfolio.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/videopress-onboarding-intent/videopress-onboarding-intent-modal-video-upload.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/videopress-onboarding-intent/videopress-onboarding-intent-modal.tsx
Labels: [Status] Needs Review, VideoPress

#81298 Add forms AI e2e block smoke test
  packages/calypso-e2e/src/lib/blocks/block-flows/form-ai.ts
  packages/calypso-e2e/src/lib/blocks/block-flows/index.ts
  test/e2e/specs/blocks/blocks__jetpack-forms.ts
Labels: [Status] Needs Review

#81467 VideoPress UserIntent: Filter items based on referrer, log referrer
  client/landing/stepper/declarative-flow/internals/steps-repository/videopress-onboarding-intent/index.tsx
Labels: [Status] Needs Review

#81428 Add Akismet products into the Jetpack cancellation survey flow.
  client/components/marketing-survey/cancel-jetpack-form/index.tsx
  client/components/marketing-survey/cancel-jetpack-form/jetpack-benefits-step.tsx
  client/components/marketing-survey/cancel-jetpack-form/jetpack-cancellation-survey.tsx
  client/me/purchases/cancel-purchase/button.jsx
Labels: Jetpack, [Status] Needs Review, [Feature] Purchase Management

#81468 Earn: Rename index.js to index.ts
  client/my-sites/earn/index.ts
Labels: [Status] Needs Review, Earn

#81465 Earn: Convert controller to typescript
  client/my-sites/earn/controller.js
  client/my-sites/earn/controller.ts
Labels: [Status] Needs Review, Earn

#81365 Domain Forwarding: Supporting multiple editions
  client/data/domains/forwarding/use-domain-forwarding-query.ts
  client/data/domains/forwarding/use-update-domain-forwarding-mutation.ts
  client/my-sites/domains/domain-management/settings/cards/domain-forwarding-card.tsx
  client/my-sites/domains/domain-management/settings/cards/style.scss
Labels: [Status] Needs Review

#81434 Stats: Add an option to contact support for a classification update
  client/my-sites/stats/stats-purchase/index.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
  client/my-sites/stats/stats-purchase/styles.scss
Labels: Stats, [Status] Needs Review

#81417 Stats: Modify products upgrade link according to the "is_commercial" classifier on the Add-Ons page
  client/my-sites/add-ons/components/add-ons-card.tsx
  client/my-sites/add-ons/hooks/use-add-ons.ts
  client/my-sites/stats/stats-purchase/stats-purchase-notice.jsx
Labels: Stats, [Feature] Plans & Upgrades, [Status] Needs Review

#81463 Stats: Adjust Personal purchase page styling for WPCOM sites
  client/my-sites/stats/stats-purchase/stats-purchase-personal.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
  client/my-sites/stats/stats-purchase/styles.scss
Labels: Stats, [Status] Needs Review

#81461 Add-ons: Use integer values for currency in useAddOnDisplayCost
  client/my-sites/add-ons/hooks/use-add-on-display-cost.ts
Labels: [Status] Needs Review

#81263 Jetpack Pro Dashboard: add atomic site actions to the dashboard site actions
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-actions/get-action-event-name.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-actions/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-actions/use-site-actions.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#81345 Jetpack Partner Portal: Add actions to the WPCOM hosting license
  client/jetpack-cloud/sections/partner-portal/license-preview/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-preview/license-actions.tsx
  client/jetpack-cloud/sections/partner-portal/license-preview/style.scss
  client/jetpack-cloud/sections/partner-portal/license-preview/use-license-actions.ts
  client/jetpack-cloud/sections/partner-portal/types.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#81482 Revert "Disable Live Preview on Atomic sites"
  client/state/themes/selectors/get-is-live-preview-supported.ts
Labels: [Status] Needs Review

#81487 Stats: add email link with subject and body contact jetpack support
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#81489 Domain Management i1: remove auto-renew column; standardise date formatting
  packages/domains-table/src/domains-table-header/columns.ts
  packages/domains-table/src/domains-table/domains-table-status-cell.tsx
Labels: [Status] Needs Review, Domain Management i1

#81450 VideoPress Onboarding User Intent: Submit waitlist on enter key
  client/landing/stepper/declarative-flow/internals/steps-repository/videopress-onboarding-intent/videopress-onboarding-intent-modal.tsx
Labels: [Status] Needs Review

#81445 Design Picker: Reduced spacing between elements in the category filter
  packages/design-picker/src/components/style.scss
Labels: [Status] Needs Review, [Feature] Design Picker, T-Rex

#81439 Assembler: Navigate to the sections screen with the category list
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/constants.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-screen.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-category-list.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-category-list.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-panel.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-main.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-sections.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/types.ts
  packages/onboarding/src/navigator/navigator-buttons/index.tsx
  test/e2e/specs/onboarding/ftme__site-assembler.ts
Labels: [Status] Needs Review

#81433 Launchpad: Add the Skip behavior for the Newsletter intent
  client/landing/stepper/declarative-flow/newsletter.ts
Labels: [Status] Needs Review

#81363 Launchpad: Add skip feature to the free flow
  client/landing/stepper/declarative-flow/free.ts
Labels: [Status] Ready to Merge

#81480 Update Domain Forwarding Title Case & Font Size
  client/my-sites/domains/domain-management/settings/cards/style.scss
  client/my-sites/domains/domain-management/settings/index.tsx
Labels: [Status] Needs Review

#81357 Fix `Activate this design` button for Marketplace themes
  client/my-sites/checkout/checkout-thank-you/marketplace/use-atomic-transfer.tsx
Labels: [Status] Needs Review

#81435 Make the Jetpack instant search e2e more stabile
  packages/calypso-e2e/src/lib/components/jetpack-instant-search-modal-component.ts
  test/e2e/specs/search/search__jetpack-instant.ts
Labels: [Status] Needs Review

#81301 Add full form submission e2e test
  packages/calypso-e2e/src/jest-playwright-config/environment.ts
  packages/calypso-e2e/src/lib/pages/feedback-inbox-page.ts
  packages/calypso-e2e/src/lib/pages/index.ts
  test/e2e/specs/published-content/forms__submissions.ts
Labels: [Status] Needs Review

#81456 I18N: Translate data-centers in Hosting onboarding flow
  client/blocks/data-center-picker/index.tsx
Labels: [Status] Needs Review

#81495 Jetpack Manage: Change "Setup" to "Set up" in atomic site actions
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-actions/get-action-event-name.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-actions/use-site-actions.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-add-license-notification/wpcom-atomic-hosting-notification.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
  client/jetpack-cloud/sections/partner-portal/license-preview/use-license-actions.ts
Labels: Jetpack, [Status] Needs Review, Jetpack Cloud

#81413 Newsletter Categories: Add newsletter categories to Subscribers page
  client/data/newsletter-categories/types.ts
  client/data/newsletter-categories/use-mark-as-newsletter-category-mutation.tsx
  client/data/newsletter-categories/use-newsletter-categories-query.tsx
  client/data/newsletter-categories/use-subscriber-newsletter-categories-query.tsx
  client/data/newsletter-categories/use-unmark-as-newsletter-category-mutation.tsx
  client/my-sites/subscribers/components/subscriber-details/styles.scss
  client/my-sites/subscribers/components/subscriber-details/subscriber-details.tsx
  client/my-sites/subscribers/subscriber-details-page.tsx
Labels: [Status] Needs Review, Newsletter Categories

#81209 Move the Information Icon in Traffic Settings
  client/my-sites/site-settings/seo-settings/form.jsx
  client/my-sites/site-settings/seo-settings/help.jsx
Labels: [Status] Needs Review

#81258 Gravatar: Implement passwordless login flow
  client/blocks/login/index.jsx
  client/blocks/login/login-form.jsx
  client/layout/logged-out.jsx
  client/layout/masterbar/gravatar.jsx
  client/layout/masterbar/gravatar.scss
  client/layout/masterbar/oauth-client.jsx
  client/login/magic-login/index.jsx
  client/login/magic-login/request-login-email-form.jsx
  client/login/magic-login/style.scss
  client/login/wp-login/index.jsx
  client/login/wp-login/login-links.jsx
  client/login/wp-login/style.scss
  client/state/selectors/get-magic-login-is-fetching-email.js
Labels: [Status] Needs Review, Login

#81505 I18N: Translate subscriber stats headers
  client/my-sites/subscribers/components/subscriber-stats/subscriber-stats.tsx
Labels: [Status] Needs Review

#81415 Performance History: Improve display of Boost Speed Scores
  client/components/activity-card/activity-actor.tsx
  client/my-sites/activity/activity-log-item/activity-actor.jsx
Labels: [Status] Needs Review, Activity Log

#81453 Fix ul and ol elements in the Odie messages
  client/odie/message/style.scss
Labels: [Status] Needs Review

#80960 `useMigrationEnabled`: remove `on*` handlers from `useQuery` usage
  client/blocks/importer/hooks/use-site-can-migrate.ts
  client/blocks/importer/wordpress/import-everything/pre-migration/index.tsx
  client/blocks/importer/wordpress/import-everything/pre-migration/test/index.test.tsx
  client/data/site-migration/types.ts
  client/data/site-migration/use-migration-enabled.ts
Labels: [Status] Needs Review, Data, Migration Plugin i2

#81511 use cards endpoint for reader tag tabs
  client/state/data-layer/wpcom/read/streams/index.js
  client/state/data-layer/wpcom/read/streams/test/index.js
Labels: [Status] Needs Review

#81504 Fix alignment issue for domain forwarding
  client/my-sites/domains/domain-management/settings/cards/style.scss
Labels: [Status] Needs Review

#81432 Earn: Refactor ad payments to typescript
  client/my-sites/earn/ads/payments.tsx
  client/state/wordads/payments/selectors.js
Labels: [Status] Needs Review, Earn

#81479 BackupBrowser: Add loading placeholder for granular restore page
  client/my-sites/backup/rewind-flow/granular-restore.tsx
  client/my-sites/backup/rewind-flow/loading-placeholder/granular-restore.tsx
  client/my-sites/backup/rewind-flow/loading-placeholder/style.scss
  client/my-sites/backup/rewind-flow/style.scss
Labels: [Status] Needs Review, Jetpack Backup

#81496 Checkout: add checkbox for accepting ToS of 100 year plan
  client/my-sites/checkout/src/components/accept-terms-of-service-checkbox.tsx
  client/my-sites/checkout/src/components/wp-checkout.tsx
Labels: [Status] Needs Review

#81339 BackupBrowser: Create theme/plugin/table/files lists in confirmation page
  client/my-sites/backup/backup-contents-page/file-browser/file-browser-header.tsx
  client/my-sites/backup/backup-contents-page/file-browser/file-browser-node.tsx
  client/my-sites/backup/backup-contents-page/file-browser/index.tsx
  client/my-sites/backup/rewind-flow/granular-restore.tsx
  client/my-sites/backup/rewind-flow/style.scss
  client/state/rewind/browser/reducer.ts
  client/state/rewind/browser/types.ts
  client/state/rewind/selectors/get-backup-browser-check-list.ts
  client/state/rewind/selectors/get-backup-browser-selected-list.ts
Labels: [Status] Ready to Merge

#81264 Emails: Update forwarding UI to be aware of limit; Update limit to 100
  client/my-sites/email/email-management/home/email-plan/index.jsx
Labels: [Status] Needs Review, Email

#79996 Podcasting: split into its own section
  client/my-sites/sidebar/static-data/fallback-menu.js
  client/my-sites/site-settings/podcasting-details/feed-url.jsx
  client/my-sites/site-settings/podcasting-details/index.jsx
  client/my-sites/site-settings/podcasting-details/link.jsx
  client/my-sites/site-settings/podcasting-details/style.scss
  client/my-sites/site-settings/podcasting-details/support-link.jsx
  client/my-sites/site-settings/settings-podcast/controller.ts
  client/my-sites/site-settings/settings-podcast/index.ts
  client/my-sites/site-settings/settings-podcast/main.tsx
  client/my-sites/site-settings/settings-writing/controller.js
  client/my-sites/site-settings/settings-writing/index.js
  client/sections.js
Labels: [Feature] Site Settings, [Status] Needs Review, Podcasting

#81469 Fix crowded spacing on product card prices.
  client/my-sites/plans/jetpack-plans/product-store/item-price/style.scss
  client/my-sites/plans/jetpack-plans/product-store/items-list/style-most-popular.scss
Labels: Jetpack, [Status] Needs Review, 2023 Pricing Page ⚡

#81532 Paid Stats: Fix link to the commercial plan flow
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
Labels: Stats, [Status] Needs Review

#81492 Stats: Fixing multiple purchase screens showing up at the same time
  client/my-sites/stats/stats-purchase/index.tsx
  client/my-sites/stats/stats-purchase/styles.scss
Labels: Stats, [Status] Needs Review

#81517 BackupBrowser: Update the header style of the backup browser
  client/my-sites/backup/backup-contents-page/file-browser/file-browser-header.tsx
  client/my-sites/backup/backup-contents-page/file-browser/file-browser-node.tsx
  client/my-sites/backup/backup-contents-page/file-browser/index.tsx
  client/my-sites/backup/backup-contents-page/index.tsx
  client/my-sites/backup/backup-contents-page/style.scss
Labels: [Status] Ready to Merge

#81535 Stats: re-arrange conditions on purchase page
  client/my-sites/stats/stats-purchase/index.tsx
Labels: Stats, [Status] Needs Review

#81486 Stats: force open commercial purchase page for commercial notice upgrade link
  client/my-sites/stats/stats-notices/commercial-site-upgrade-notice.tsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#81536 Stats: update some notice revisions and links
  client/my-sites/stats/stats-notices/commercial-site-upgrade-notice.tsx
  client/my-sites/stats/stats-notices/do-you-love-jetpack-stats-notice.tsx
  client/my-sites/stats/stats-notices/free-plan-purchase-success-notice.tsx
Labels: Stats, [Status] Needs Review

#81443 Jetpack E2E: smoke test of the dashboard and settings pages.
  packages/calypso-e2e/src/lib/pages/index.ts
  packages/calypso-e2e/src/lib/pages/wp-admin/index.ts
  packages/calypso-e2e/src/lib/pages/wp-admin/jetpack-dashboard-page.ts
  test/e2e/specs/jetpack/jetpack__dashboard-smoke.ts
Labels: [Status] Needs Review

#81393 Pro Dashboard: Hotwire Jetpack Cloud links to redirect to WPCOM for atomic sites
  client/components/site-selector/index.jsx
  client/jetpack-cloud/sections/agency-dashboard/sidebar/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/index.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#81483 Assembler - Fix for pattern name tooltip to show only on hover
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-renderer.tsx
Labels: [Status] Needs Review

#81540 Stats: Release new changes for streamlining purchase flow
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Stats, [Status] Needs Review

#81507 Blogger flow: Fix long usernames breaking the layout
  client/landing/stepper/declarative-flow/internals/steps-repository/blogger-intent/style.scss
Labels: [Status] Needs Review

#81494 Design Picker: Clean up design-picker-pattern-assembler flag
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/landing/stepper/hooks/use-site-data.ts
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#81542 Assembler - Fix fonts request error because names with quotes are not found
  packages/global-styles/src/components/font-pairing-variations/font-families-loader.tsx
Labels: [Status] Needs Review

#81437 Jetpack E2E: add coverage for the newsletter subscription & removal flow.
  packages/calypso-e2e/src/data-helper.ts
  packages/calypso-e2e/src/email-client.ts
  packages/calypso-e2e/src/lib/pages/index.ts
  packages/calypso-e2e/src/lib/pages/published/published-post-page.ts
  packages/calypso-e2e/src/lib/pages/subscribers-page.ts
  packages/calypso-e2e/src/lib/pages/subscription-management-page.ts
  packages/calypso-e2e/src/rest-api-client.ts
  packages/calypso-e2e/src/secrets/encrypted.enc
  packages/calypso-e2e/src/secrets/secrets-manager.ts
  packages/calypso-e2e/src/secrets/types.ts
  packages/calypso-e2e/src/types/rest-api-client.types.ts
  test/e2e/specs/users/newsletter__subscribe-remove.ts
Labels: [Status] Needs Review

#81457 Migration Trial: fix migrate and expired plan redirect conflicts
  client/my-sites/controller.js
Labels: [Status] Needs Review, Migration Trials

#81522 Magic Link: Always create an account.
  client/login/magic-login/index.jsx
Labels: [Status] Needs Review

#81550 Flaky Jetpack E2E: wait for banner to load before clicking on the Promote button.
  packages/calypso-e2e/src/lib/pages/advertising-page.ts
  test/e2e/specs/tools/advertising__promote.ts
Labels: [Status] Needs Review

#81284 Home: Fix unhandled exception on layout query
  client/my-sites/customer-home/main.jsx
Labels: [Type] Bug, [Status] Needs Review

#81523 Reader share / reblog - open reader reblogging in new tab
  client/blocks/reader-share/reblog.jsx
Labels: [Status] Needs Review

#81524 Add context to stats and ai translations
  packages/calypso-products/src/translations.tsx
Labels: [Status] Needs Review

#81556 Newsletter categories: Add blog sticker feature flag check for newsletter categories
  client/data/newsletter-categories/index.ts
  client/data/newsletter-categories/test/use-newsletter-categories-feature-enabled.tsx
  client/data/newsletter-categories/use-newsletter-categories-feature-enabled.ts
  client/my-sites/site-settings/reading-newsletter-settings/index.tsx
Labels: [Status] Needs Review, Newsletter Categories

#81519 Discover feeds - explore making feeds more recent with a post date after param.
  client/reader/discover/helper.js
  client/state/data-layer/wpcom/read/streams/index.js
  client/state/data-layer/wpcom/read/streams/test/index.js
Labels: [Status] Needs Review

#81565 Subscription Management: Launch individual subscription page on Reader portal.
  client/landing/subscriptions/components/site-subscriptions-list/site-row.tsx
  config/development.json
Labels: [Status] Needs Review, Subscription Management, [SM] Reader Portal

#81421 Domains: Improve all domains management performance
  client/my-sites/domains/domain-management/list/all-domains.jsx
  client/my-sites/domains/domain-management/list/domain-row.jsx
  client/my-sites/domains/domain-management/list/domains-table.jsx
  client/my-sites/domains/domain-management/list/helpers.ts
  client/my-sites/domains/domain-management/list/site-domains.jsx
  client/state/all-domains/helpers.js
  client/state/all-domains/schema.js
  client/state/sites/domains/assembler.js
  client/state/sites/domains/schema.js
  client/state/sites/domains/test/fixture/index.js
Labels: [Status] In Progress, [Status] Needs Review

#81567 Add handling for 1 month intro discounts in Jetpack 2 year upsell
  client/my-sites/checkout/src/components/item-variation-picker/util.ts
Labels: [Status] Needs Review
