Repository Automattic/wp-calypso, pull requests merged in 2024-10, with the labels that each got.

#95011 Logged in Performance Profiler: Update recommendations section to fit logged in styling
  client/hosting/performance/style.scss
  client/performance-profiler/components/dashboard-content/index.tsx
  client/performance-profiler/components/insights-section/index.tsx
  client/performance-profiler/components/insights-section/style.scss
  client/performance-profiler/components/metrics-insight/index.tsx
  client/performance-profiler/components/metrics-insight/insight-content.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, Logged-in Performance Profiler i1

#95025 Add tracks event to site profiler
  client/hosting/performance/site-performance.tsx
  client/performance-profiler/components/core-web-vitals-accordion/core-web-vitals-accordion-v2.tsx
  client/performance-profiler/components/insights-section/index.tsx
  client/performance-profiler/components/metric-tab-bar/metric-tab-bar-v2.tsx
  client/performance-profiler/components/tip/index.tsx
Labels: [Status] Needs Review

#94843 A4A: Add overage pricing text on the Pressable section.
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/premier-agency-hosting/style.scss
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/details.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/style.scss
Labels: [Status] Needs Review, A8c Agencies

#94992 A4A: Fix inconsistency with header spacing.
  client/a8c-for-agencies/components/content-sidebar/style.scss
  client/a8c-for-agencies/components/layout/index.tsx
  client/a8c-for-agencies/components/layout/style.scss
  client/a8c-for-agencies/sections/marketplace/checkout/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/index.tsx
  client/a8c-for-agencies/sections/overview/style.scss
  client/a8c-for-agencies/sections/purchases/billing/style.scss
  client/a8c-for-agencies/sections/purchases/invoices/invoices-overview/index.tsx
  client/a8c-for-agencies/sections/purchases/invoices/invoices-overview/style.scss
  client/a8c-for-agencies/sections/purchases/licenses/licenses-overview/style.scss
  client/a8c-for-agencies/sections/referrals/primary/referrals-overview/style.scss
  client/a8c-for-agencies/sections/team/primary/get-started/index.tsx
  client/a8c-for-agencies/sections/team/primary/team-accept-invite/index.tsx
  client/a8c-for-agencies/sections/team/primary/team-invite/index.tsx
  client/a8c-for-agencies/sections/team/primary/team-list/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#94927 Theme: Activate theme without redirection for the free/personal/premium themes
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/get-current-theme-software-sets/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
  client/landing/stepper/declarative-flow/readymade-template.tsx
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-theme-section.tsx
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/marketplace/use-plugins-thank-you-data.tsx
  client/my-sites/checkout/checkout-thank-you/marketplace/use-themes-thank-you-data.tsx
  client/my-sites/theme/main.jsx
  client/my-sites/themes/activation-modal.jsx
  client/my-sites/themes/atomic-transfer-dialog.tsx
  client/my-sites/themes/test/thanks-modal.jsx
  client/my-sites/themes/thanks-modal.jsx
  client/my-sites/themes/thanks-modal.scss
  client/my-sites/themes/theme-showcase.jsx
  client/my-sites/themes/theme-upload/index.jsx
  client/state/themes/actions/activate-theme.js
  client/state/themes/actions/activate.js
  client/state/themes/actions/install-and-activate-theme.js
  client/state/themes/actions/request-then-activate.js
  client/state/themes/actions/theme-transfer.js
  client/state/themes/selectors/is-requesting-theme.js
  client/state/themes/selectors/should-redirect-to-thank-you-page.js
  client/state/themes/selectors/theme-has-auto-loading-homepage.js
  client/state/themes/test/actions.js
Labels: [Status] Needs Review

#94277 A4A Dev Sites: Add licenseId and siteUrls to the A4A cart session storage
  client/a8c-for-agencies/sections/marketplace/hooks/use-shopping-cart.ts
Labels: [Status] Needs Review

#95029 Fix back url for domain flows started from site settings page
  client/my-sites/domains/controller.jsx
  client/my-sites/domains/domain-search/site-redirect.jsx
  client/my-sites/domains/map-domain/index.jsx
  client/my-sites/site-settings/form-general.jsx
Labels: [Status] Needs Review

#95028 Stepper: Ensure `calypso_signup_start` doesn't get recorded over and over / 50 times
  client/landing/stepper/declarative-flow/internals/hooks/use-sign-up-start-tracking/index.tsx
  client/landing/stepper/declarative-flow/internals/hooks/use-sign-up-start-tracking/test/index.tsx
Labels: [Status] Needs Review, Stepper

#94997 A4A: Remove fallback admin access when role is unset
  client/a8c-for-agencies/lib/permission.ts
Labels: [Status] Needs Review

#95052 Site Profiler: Align numbers to prevent layout shifts
  client/hosting/performance/site-performance.tsx
Labels: [Status] Needs Review

#95048 Theme: Remove Congrats screen for the DotOrg theme
  client/my-sites/theme/main.jsx
  client/my-sites/themes/theme-options.js
  client/state/themes/actions/activate.js
  client/state/themes/actions/install-theme.js
Labels: [Status] Needs Review

#95022 Add Thank You (Booking Confirmation) step to 100 Year Flow
  client/landing/stepper/declarative-flow/hundred-year-plan.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-diy-or-difm/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-schedule-appointment/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-thank-you/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-thank-you/styles.scss
Labels: [Status] Needs Review

#94998 Help Center: use Zendesk staging when proxied
  apps/help-center/config.js
  apps/help-center/package.json
  config/stage.json
  config/wpcalypso.json
  packages/calypso-e2e/package.json
  packages/calypso-e2e/src/lib/components/help-center.ts
  packages/zendesk-client/package.json
  packages/zendesk-client/src/constants.ts
  packages/zendesk-client/src/index.ts
  packages/zendesk-client/src/use-authenticate-zendesk-messaging.ts
  yarn.lock
Labels: [Status] Needs Review, [Feature] Help Center

#94945 Sidebar: Replace Gridicons and Material icons with WordPress icons
  client/layout/global-sidebar/style.scss
  client/layout/sidebar/item.jsx
  client/me/sidebar/index.jsx
  client/me/sidebar/style.scss
  client/my-sites/sidebar/static-data/global-sidebar-menu.js
  client/my-sites/sidebar/style.scss
Labels: [Status] Needs Review

#94941 Hosting: Show success notification after Atomic transfer
  client/hosting/hosting-features/components/hosting-features.tsx
  client/hosting/overview/controller.tsx
Labels: [Status] Needs Review

#94903 remove the impressions and add spend in the campaign table
  client/my-sites/promote-post-i2/components/campaign-item/index.tsx
  client/my-sites/promote-post-i2/components/campaign-item/style.scss
  client/my-sites/promote-post-i2/components/campaigns-list/index.tsx
  client/my-sites/promote-post-i2/components/campaigns-table/index.tsx
  client/my-sites/promote-post-i2/components/campaigns-table/style.scss
Labels: [Status] Needs Review

#95059 Fix top border shifting when opening a recommendation
  client/performance-profiler/components/metrics-insight/index.tsx
Labels: [Status] Needs Review

#95054 Translatable String: fix error in Calypso
  client/my-sites/sidebar/item.jsx
Labels: [Status] Needs Review

#94789 Checkout: Deploy Stripe redirect payment types to all environments
  config/horizon.json
  config/production.json
  config/wpcalypso.json
Labels: [Feature] Checkout

#95042 Remove database confirmation checkbox when syncing Woo staging sites.
  client/hosting/staging-site/components/staging-site-card/card-content/staging-sync-card.tsx
  client/hosting/staging-site/components/staging-site-card/sync-options-panel.tsx
Labels: [Status] Needs Review

#95068 Reader: Move comment input in reader-full-post view above related posts
  client/blocks/reader-full-post/index.jsx
Labels: [Status] Needs Review

#95045 Post-migration Experience: Adds the Launchpad
  client/my-sites/customer-home/cards/constants.js
  client/my-sites/customer-home/cards/launchpad/post-migration.tsx
  client/my-sites/customer-home/locations/card-components.ts
Labels: [Status] Needs Review

#95077 Help Center: fix undefined error
  apps/help-center/config.js
Labels: [Status] Needs Review

#94991 Me Developers: Links in me/developers open in Help Center or current tab
  client/me/developer/features/github-deployment-card.tsx
  client/me/developer/features/index.tsx
  client/me/developer/features/studio-card.tsx
  client/me/developer/features/use-features-list.tsx
Labels: [Status] Needs Review

#95006 Me Privacy: Open privacy links in the current tab
  client/me/privacy/main.jsx
Labels: [Status] Needs Review

#95007 Help: Update compact card link targets
  client/me/help/main.jsx
  client/me/help/style.scss
Labels: [Status] Needs Review

#95063 Reader: Update excerpt to show if not explicitly set to not show
  client/blocks/reader-excerpt/index.jsx
Labels: [Status] Needs Review

#95083 Disable Assembler
  client/components/themes-list/index.jsx
  client/components/themes-list/test/index.jsx
  client/data/site-assembler/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/design-choices/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  client/my-sites/themes/pattern-assembler-button/index.tsx
Labels: [Status] Needs Review

#95085 SSO: Fix total team member count number
  client/my-sites/people/team-members/index.tsx
Labels: [Status] Needs Review, Jetpack SSO

#95058 Theme: Redirect back to the Theme Details page after the checkout of the Partner themes
  client/my-sites/checkout/checkout-thank-you/marketplace/use-themes-thank-you-data.tsx
Labels: [Status] Needs Review

#94943 A4A: Collect Phone details during signup.
  client/a8c-for-agencies/sections/signup/agency-details-form/hooks/use-create-agency-mutation.ts
  client/a8c-for-agencies/sections/signup/agency-details-form/index.tsx
  client/a8c-for-agencies/sections/signup/agency-details-form/style.scss
  client/a8c-for-agencies/sections/signup/agency-details-form/types.ts
  client/a8c-for-agencies/sections/signup/signup-form/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#95057 A4A: Make the onboarding tasks list dismissable when it is completed.
  client/a8c-for-agencies/hooks/use-onboarding-tours.ts
  client/a8c-for-agencies/sections/onboarding-tours/constants.ts
  client/a8c-for-agencies/sections/overview/body/next-steps/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#94854 White-labeled plugin: Ensure we're retrying the query
  client/landing/stepper/hooks/test/use-prepare-site-for-migration.tsx
  client/landing/stepper/hooks/use-prepare-site-for-migration.ts
  client/landing/stepper/hooks/use-site-migration-key.ts
Labels: [Status] Needs Review, [Feature] Site Migration

#95064 Stepper: Fix mobile spacing and sizes on user
  client/landing/stepper/declarative-flow/internals/steps-repository/__user/style.scss
Labels: [Status] Needs Review, Stepper

#95060 Refetch defensive mode endpoint after it expires
  client/data/hosting/use-cache.ts
Labels: [Status] Needs Review

#95087 Server Settings Enhancements: Enable feature flag, update doc link
  client/components/inline-support-link/context-links.js
  client/hosting/server-settings/components/cache-card/index.tsx
  config/production.json
  config/stage.json
Labels: [Status] Needs Review

#95030 Fix: paid subscriber importer newsletter tier creation & no plans case
  client/data/paid-newsletter/use-paid-newsletter-query.ts
  client/my-sites/earn/components/add-edit-plan-modal/index.tsx
  client/my-sites/importer/newsletter/importer.tsx
  client/my-sites/importer/newsletter/subscribers/paid-subscribers/connect-stripe.tsx
  client/my-sites/importer/newsletter/subscribers/paid-subscribers/map-plan.scss
  client/my-sites/importer/newsletter/subscribers/paid-subscribers/map-plans.tsx
  client/my-sites/importer/newsletter/subscribers/paid-subscribers/no-plans.tsx
  client/my-sites/importer/newsletter/subscribers/paid-subscribers/success-notice.tsx
  client/my-sites/importer/newsletter/subscribers/step-done.tsx
  client/my-sites/importer/newsletter/subscribers/step-pending.tsx
  client/my-sites/importer/newsletter/subscribers/upload-form.tsx
  client/my-sites/importer/newsletter/summary.tsx
  client/my-sites/importer/newsletter/summary/subscribers.tsx
  client/my-sites/importer/newsletter/utils.tsx
  client/state/memberships/settings/actions.js
Labels: [Status] Needs Review, Import, Subscriber Importer

#95100 Proxied Image: fix console error
  client/my-sites/media-library/proxied-image.tsx
Labels: [Status] Needs Review

#95102 Help Center: Fix createRoot related console error
  apps/help-center/help-center-wp-admin-disconnected.js
  apps/help-center/help-center-wp-admin.js
Labels: [Status] Needs Review

#95082 Hosting Features: Fix hosting overview redirect to param
  client/hosting/overview/controller.tsx
Labels: [Status] Needs Review, Groundskeeping

#95091 Add site profiler test started tracks event
  client/hosting/performance/site-performance.tsx
Labels: [Status] Needs Review

#95105 Revert "Hosting Features: Fix hosting overview redirect to param"
  client/hosting/overview/controller.tsx
Labels: [Status] Needs Review

#95043 A4A: Don't fire signup page view event when redirecting
  client/a8c-for-agencies/sections/signup/controller.tsx
Labels: [Status] Needs Review, A4A

#95093 Theme: Improve the activation experience after the checkout and atomic transfer
  client/my-sites/checkout/checkout-thank-you/marketplace/use-themes-thank-you-data.tsx
  client/my-sites/theme/main.jsx
  client/my-sites/themes/atomic-transfer-dialog.tsx
  client/my-sites/themes/theme-options.js
Labels: [Status] Needs Review

#95092 Changed the existing logo with the new branding for WordPress.com
  packages/components/src/wordpress-wordmark/index.tsx
Labels: [Status] Needs Review

#93282 Site selected flow: show ecommerce plan
  client/my-sites/plans-features-main/components/plan-upsell-modal/hooks/use-modal-resolution-callback.tsx
  client/my-sites/plans-features-main/index.tsx
  client/signup/config/steps-pure.js
  client/signup/steps/plans/index.jsx
  packages/plans-grid-next/src/hooks/data-store/types.ts
  packages/plans-grid-next/src/hooks/data-store/use-grid-plans-for-comparison-grid.ts
  packages/plans-grid-next/src/hooks/data-store/use-grid-plans-for-features-grid.ts
  packages/plans-grid-next/src/hooks/data-store/use-grid-plans.tsx
  packages/plans-grid-next/src/hooks/data-store/use-highlight-labels.ts
  packages/plans-grid-next/src/types.ts
Labels: [Status] Needs Review

#95112 Stats: Filter unknown sources from the Locations module
  client/state/stats/lists/utils.js
Labels: Stats, [Status] Needs Review

#94901 Remove plan: Skip survey
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/steps.js
  client/components/marketing-survey/cancel-purchase-form/style.scss
  client/lib/purchases/actions.js
  client/me/purchases/manage-purchase/index.tsx
  client/me/purchases/remove-purchase/index.jsx
  client/me/purchases/utils.js
Labels: [Status] Needs Review

#94328 Stepper: Remove `steps` param from `useStepNavigation`
  client/landing/stepper/declarative-flow/internals/hooks/use-step-navigation-with-tracking/index.ts
  client/landing/stepper/declarative-flow/internals/hooks/use-step-navigation-with-tracking/test/index.tsx
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/types.ts
  client/landing/stepper/declarative-flow/plugin-bundle-flow.ts
Labels: [Status] Needs Review, Stepper

#94855 Migration: Add step placeholder to get more information about the user site when a wp.com site is given as input
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-already-wpcom/components/form/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-already-wpcom/hooks/use-migration-ticket-mutation.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-already-wpcom/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-already-wpcom/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-already-wpcom/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-already-wpcom/types.ts
  client/landing/stepper/declarative-flow/internals/steps.tsx
  client/landing/stepper/declarative-flow/migration/index.tsx
Labels: [Status] Needs Review

#95119 Remove plan: Fix button changing its text after submit
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/style.scss
Labels: [Status] Needs Review

#95037 Avoid broken flow and site re-creation when clicking back from checkout
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/index.tsx
  client/landing/stepper/declarative-flow/new-hosted-site-flow.ts
  client/my-sites/checkout/controller.jsx
  client/signup/storageUtils.js
Labels: [Status] Needs Review

#95116 White-labeled plugin: Install the wpcom-migration plugin from wp.org
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/test/index.tsx
  client/landing/stepper/hooks/test/use-prepare-site-for-migration.tsx
  client/landing/stepper/hooks/use-prepare-site-for-migration.ts
Labels: [Status] Needs Review

#95131 Issue templates: add new issue type option
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/task.yml
  .github/ISSUE_TEMPLATE/tooling_request.yml
Labels: [Pri] Normal, [Status] Needs Review, [Type] Janitorial

#93941 Stepper: Apply extended props to `calypso_signup_start`. Update `tailored-ecommerce` flow
  client/landing/stepper/README.md
  client/landing/stepper/declarative-flow/internals/hooks/use-sign-up-start-tracking/index.tsx
  client/landing/stepper/declarative-flow/internals/hooks/use-sign-up-start-tracking/test/index.tsx
  client/landing/stepper/declarative-flow/internals/types.ts
  client/landing/stepper/declarative-flow/tailored-ecommerce-flow.ts
  client/landing/stepper/utils/test/use-snake-cased-keys.ts
  client/landing/stepper/utils/use-snake-cased-keys.ts
Labels: [Status] Needs Review, Stepper

#95133 photon: Prepare for v4.1.0 release
  packages/photon/History.md
  packages/photon/package.json
Labels: [Pri] Normal, [Status] Needs Review, Packages, Releases

#95134 photon: Add missing tslib dep
  packages/photon/History.md
  packages/photon/package.json
  yarn.lock
Labels: [Type] Bug, [Pri] Normal, [Status] Needs Review

#95136 Reader: fix post and comment actions alignment
  client/blocks/comment-button/style.scss
  client/blocks/comments/comment-actions.scss
  client/blocks/like-button/style.scss
  client/blocks/reader-full-post/style.scss
  client/blocks/reader-post-actions/style.scss
  client/blocks/reader-post-card/style.scss
  client/blocks/reader-share/style.scss
Labels: [Status] Needs Review

#95142 Stats: Remove the scroll bar for likes
  client/my-sites/stats/post-detail-highlights-section/style.scss
Labels: Stats, [Status] Needs Review, Odyssey Stats

#94766 Remove congrats screen from single titanmail purchase
  client/my-sites/checkout/get-thank-you-page-url/index.ts
  client/my-sites/checkout/get-thank-you-page-url/test/get-thank-you-page-url.ts
  client/my-sites/email/email-management/home/email-plan-header.tsx
  client/my-sites/email/email-management/home/email-plan/index.jsx
  client/my-sites/email/email-management/home/utils.ts
Labels: [Status] Needs Review

#95141 Odyssey: Fix post like counts
  client/my-sites/stats/stats-post-detail/index.jsx
Labels: Stats, [Status] Needs Review, Odyssey Stats

#95062 Masterbar: replace 'Edit Profile' and 'My Account' with 'My Profile'
  client/layout/masterbar/logged-in.jsx
  client/layout/masterbar/style.scss
  client/layout/masterbar/test/logged-in.js
Labels: [Status] Needs Review

#95122 Plugin installation screen: Update header
  client/my-sites/marketplace/pages/marketplace-product-install/index.tsx
  client/my-sites/marketplace/pages/marketplace-product-install/style.scss
Labels: [Status] Needs Review

#95099 Domains: Fix wrong redirect in payment issue domains' table button
  packages/domains-table/src/utils/resolve-domain-status.tsx
Labels: Groundskeeping

#94284 Connections: Change Instagram "Widget" to "Block"
  client/my-sites/marketing/connections/service-description.jsx
  client/my-sites/marketing/connections/service-examples.jsx
Labels: [Status] Needs Review

#95145 Update Use your domain help link
  client/components/domains/use-my-domain/transfer-or-connect/index.jsx
  client/components/domains/use-your-domain-step/index.jsx
  client/lib/domains/registration/availability-messages.js
  packages/urls/src/index.ts
Labels: [Status] Ready to Merge, [Feature Group] Emails & Domains, Groundskeeping

#95090 White-labeled plugin: Fix reverted sites can't be used for migration
  client/landing/stepper/hooks/use-site-transfer/query.ts
Labels: [Status] Needs Review

#95095 A4A: Add error handler for 'Create referrals' mutation.
  client/a8c-for-agencies/sections/marketplace/checkout/request-client-payment.tsx
Labels: [Status] Needs Review, A8c Agencies

#95113 Help Center: Move HelpCenter navigation to header
  packages/help-center/src/components/back-button.scss
  packages/help-center/src/components/back-button.tsx
  packages/help-center/src/components/help-center-article.tsx
  packages/help-center/src/components/help-center-contact-form.tsx
  packages/help-center/src/components/help-center-contact-page.tsx
  packages/help-center/src/components/help-center-content.scss
  packages/help-center/src/components/help-center-content.tsx
  packages/help-center/src/components/help-center-header.scss
  packages/help-center/src/components/help-center-header.tsx
  packages/help-center/src/components/help-center-odie.tsx
  packages/help-center/src/components/help-center-third-party-cookies-notice.tsx
  packages/help-center/src/components/test/back-button.tsx
  packages/help-center/src/components/ticket-success-screen.tsx
  packages/help-center/src/styles.scss
Labels: [Status] Needs Review, [Feature] Help Center

#95139 Reader: Sort likes so current user is always on top
  client/blocks/post-likes/index.jsx
Labels: [Status] Needs Review

#95150 A4A: Fix the bug with PD submission redirecting to the Overview page.
  client/a8c-for-agencies/sections/partner-directory/agency-details/index.tsx
  client/a8c-for-agencies/sections/partner-directory/agency-expertise/index.tsx
  client/a8c-for-agencies/sections/partner-directory/dashboard/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#95103 Remove hasEnTranslation checks added from 94343
  client/hosting/sites/components/sites-dataviews/index.tsx
Labels: [Status] Needs Review

#95101 White-labeled plugin: Update copy when referencing the Move to WordPress.com plugin
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/steps/step-add-migration-key-fallback.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/steps/step-add-migration-key.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-started/index.tsx
Labels: [Status] Needs Review

#95153 White-labeled plugin: Enable feature flag
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/steps/step-add-migration-key-fallback.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/steps/step-get-your-site-ready.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/steps/step-install-migration-plugin.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/steps/test/use-steps.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/steps/test/utils.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/steps/use-steps.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/steps/utils.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/test/index.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#95157 White-labeled plugin: Enable the feature flag on staging
  config/stage.json
Labels: [Status] Needs Review

#95138 Stepper: Redirect to start when domain is missing on Connect-domain flow
  client/landing/stepper/declarative-flow/connect-domain.ts
Labels: [Status] Needs Review, Groundskeeping

#95160 Hosting Features: Support redirect_to param for activation
  client/hosting/hosting-features/components/hosting-features.tsx
Labels: [Status] Needs Review

#95140 Calypso 404: Redirect user to selected site home when 404 return home is clicked
  client/root.js
  client/test/root-section.ts
Labels: [Status] Needs Review, Groundskeeping

#95174 Help Center: change header back to Wapuu
  packages/help-center/src/components/help-center-header.tsx
Labels: [Status] Needs Review

#95108 Performance Profiler: logged-out profiler uses the same components as the logged-in profiler
  client/hosting/performance/components/PerformanceReport.tsx
  client/performance-profiler/components/core-web-vitals-accordion/core-web-vitals-accordion-v2.tsx
  client/performance-profiler/components/core-web-vitals-display/index.tsx
  client/performance-profiler/components/dashboard-content/index.tsx
  client/performance-profiler/components/insights-section/index.tsx
  client/performance-profiler/components/insights-section/style.scss
  client/performance-profiler/components/metric-tab-bar/metric-tab-bar-v2.tsx
  client/performance-profiler/components/metrics-insight/insight-content.tsx
  client/performance-profiler/components/metrics-insight/insight-header.tsx
  client/performance-profiler/pages/dashboard/style.scss
Labels: [Status] Needs Review, Logged-in Performance Profiler i1

#95177 Performance Profiler: logged-out profiler uses the same components as the logged-in profiler
  client/hosting/performance/components/PerformanceReport.tsx
  client/performance-profiler/components/core-web-vitals-accordion/core-web-vitals-accordion-v2.tsx
  client/performance-profiler/components/core-web-vitals-display/index.tsx
  client/performance-profiler/components/dashboard-content/index.tsx
  client/performance-profiler/components/insights-section/index.tsx
  client/performance-profiler/components/insights-section/style.scss
  client/performance-profiler/components/metric-tab-bar/metric-tab-bar-v2.tsx
  client/performance-profiler/components/metrics-insight/insight-content.tsx
  client/performance-profiler/components/metrics-insight/insight-header.tsx
  client/performance-profiler/pages/dashboard/style.scss
Labels: [Status] Needs Review, Logged-in Performance Profiler i1

#95178 Theme: Display the Atomic Transfer dialog for wporg-only themes
  client/state/themes/actions/activate.js
Labels: [Status] Needs Review

#95148 A4A > Marketplace: Implement Pressable usage limit warning banner
  client/a8c-for-agencies/sections/marketplace/common/pressable-usage-limit-notice/index.tsx
  client/a8c-for-agencies/sections/marketplace/common/pressable-usage-limit-notice/style.scss
  client/a8c-for-agencies/sections/marketplace/hosting-overview/index.tsx
  client/a8c-for-agencies/style.scss
Labels: [Status] Needs Review, A8c Agencies

#95050 Redirect to plugins.php after plugin activation instead of Congrats page
  client/my-sites/marketplace/pages/marketplace-product-install/index.tsx
Labels: [Status] Needs Review

#95180 Performance Profiler: Fix rendering of null values in performance profiler history
  client/performance-profiler/components/core-web-vitals-display/core-web-vitals-details_v2.tsx
Labels: [Status] Needs Review, Logged-in Performance Profiler i1, Performance Profiler

#95162 Stats: Fix post details page layout
  client/my-sites/stats/post-detail-highlights-section/style.scss
  client/my-sites/stats/sections/all-time-highlights-section/style.scss
  packages/components/src/post-stats-card/style.scss
Labels: Stats, [Status] Needs Review

#95184 Fix SSH key layout breaking for smaller viewports
  client/hosting/server-settings/components/sftp-card/ssh-keys.scss
Labels: [Status] Needs Review

#95149 100-year-plan: Match design for "diy or difm" step
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-diy-or-difm/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-diy-or-difm/styles.scss
Labels: [Status] Needs Review

#95159 Log `signup_domain_origin` in `calypso_signup_complete`
  client/landing/stepper/declarative-flow/internals/analytics/record-step-navigation.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/index.tsx
  client/landing/stepper/declarative-flow/onboarding.ts
  client/landing/stepper/hooks/use-record-signup-complete.ts
  packages/data-stores/src/onboard/actions.ts
  packages/data-stores/src/onboard/reducer.ts
  packages/data-stores/src/onboard/selectors.ts
Labels: [Status] Needs Review

#95009 Add platform and hosting check, add hosting error message, continue anyway path for WPCOM sites
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/components/credentials-form.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/components/site-address-field.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/hooks/use-credentials-form.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/hooks/use-form-error-mapping.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/test/index.tsx
Labels: [Status] Needs Review

#95144 Post-migration Experience: Add the completion logic for the Review Site task
  packages/launchpad/src/setup-actions.ts
Labels: [Status] Needs Review

#95051 A4A Dev Sites: Add `Refer to client` button back to the Hosting settings page
  client/my-sites/site-settings/site-visibility/launch-site.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#94676 Hosting features transfer modal: Update data center picker design
  client/blocks/data-center-picker/README.md
  client/blocks/data-center-picker/docs/example.jsx
  client/blocks/data-center-picker/index.tsx
  client/blocks/eligibility-warnings/style.scss
Labels: [Status] Needs Review

#95203 Check if tipaltiData is set before using it.
  client/a8c-for-agencies/sections/marketplace/checkout/request-client-payment.tsx
Labels: [Status] Needs Review

#95183 DIFM Signup: Redirect user to `/home` after they cancel DIFM checkout
  client/signup/steps/website-content/index.tsx
Labels: [Type] Bug, [Status] Needs Review

#95208 Performance Profiler: Fix React warnings regarding SVG props and missing keys
  client/performance-profiler/components/metrics-insight/insight-table.tsx
  client/performance-profiler/icons/thumbs.tsx
  packages/components/src/wordpress-wordmark/index.tsx
Labels: [Status] Needs Review, Logged-in Performance Profiler i1, Performance Profiler

#94403 Stepper: Onboarding experiment setup
  client/signup/controller.js
  client/signup/utils.js
Labels: [Status] Needs Review, DO NOT MERGE

#95213 Help Center: fix margin with contact support
  packages/help-center/src/components/help-center-contact-page.scss
Labels: [Status] Needs Review, [Feature] Help Center

#95202 Hosting dashboard: Add flags to remove console warnings about bottom margin.
  client/blocks/data-center-picker/index.tsx
  client/hosting/logs/components/site-logs.tsx
  client/hosting/server-settings/components/cache-card/index.tsx
  client/hosting/server-settings/components/sftp-card/index.js
  client/lib/store-sandbox-helper/index.tsx
Labels: [Status] Needs Review

#95204 Data center picker: Add a wrap style to the label
  client/blocks/data-center-picker/index.tsx
Labels: [Status] Needs Review

#94640 Me: Improve "Change Username" Account Settings
  client/me/account/main.jsx
  client/me/account/style.scss
Labels: [Feature Group] Support, OSS Citizen, [Status] String Freeze, [Feature] Support Docs Content

#95199 Add mutation to update the Migration status
  client/data/site-migration/use-update-migration-status.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx
Labels: [Status] Needs Review

#95219 A4A Dev Sites: Hide `Transfer your site` option and `Admin interface style` settings section for dev sites
  client/my-sites/site-settings/form-general.jsx
  client/my-sites/site-settings/site-tools/index.jsx
Labels: [Status] Needs Review, A4A Dev Sites

#94849 Update: Add incompatible plugin wp-downgrade to the list to match wpcomsh
  client/my-sites/plugins/plugin-compatibility.js
Labels: [Status] Needs Review

#86434 Plans: update grid for introductory offers
  packages/plans-grid-next/src/components/shared/header-price/index.tsx
  packages/plans-grid-next/src/components/shared/header-price/style.scss
  packages/plans-grid-next/src/hooks/data-store/use-plan-billing-description.tsx
Labels: [Feature] Plans & Upgrades, [Status] Needs Review, [Status] String Freeze

#95065 Purchases: Revamp Cancellation Flow (originally 93211)
  client/me/purchases/cancel-purchase/button.jsx
  client/me/purchases/cancel-purchase/domain-options.jsx
  client/me/purchases/cancel-purchase/feature-list.jsx
  client/me/purchases/cancel-purchase/index.jsx
  client/me/purchases/cancel-purchase/loading-placeholder.jsx
  client/me/purchases/cancel-purchase/refund-information.jsx
  client/me/purchases/cancel-purchase/style.scss
  client/me/purchases/cancel-purchase/support-link.jsx
  client/me/purchases/confirm-cancel-domain/index.jsx
  client/me/purchases/confirm-cancel-domain/loading-placeholder.jsx
  client/me/purchases/confirm-cancel-domain/style.scss
  client/me/purchases/controller.jsx
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/types.ts
Labels: [Feature] Purchase Management, [Status] String Freeze

#95164 Submit already WPCOM survey to endpoint, route user to survey step when WPCOM detected
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-already-wpcom/components/form/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-already-wpcom/hooks/use-migration-ticket-mutation.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-already-wpcom/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-already-wpcom/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-already-wpcom/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/components/credentials-form.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/hooks/use-credentials-form.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/test/index.tsx
  client/landing/stepper/declarative-flow/migration/index.tsx
  client/landing/stepper/declarative-flow/migration/test/index.tsx
  client/landing/stepper/declarative-flow/site-migration-flow.ts
  client/landing/stepper/declarative-flow/test/site-migration-flow.tsx
Labels: [Status] Needs Review, [Feature] Site Migration, Automated Migration i4

#95198 Fix/notifications focus styles
  apps/notifications/src/panel/boot/stylesheets/actions.scss
  apps/notifications/src/panel/boot/stylesheets/main.scss
  apps/notifications/src/panel/boot/stylesheets/shared/reset.scss
  apps/notifications/src/panel/templates/block-user.jsx
  apps/notifications/src/panel/templates/index.jsx
  apps/notifications/src/panel/templates/list-header.jsx
Labels: [Status] Needs Review

#95207 Reader: Basic Column Block support
  client/blocks/reader-full-post/_content.scss
  client/blocks/reader-full-post/columns.scss
  client/blocks/reader-full-post/style.scss
Labels: [Status] Needs Review

#95146 Performance Profiler: Remove unused components removed in #95108
  client/performance-profiler/components/core-web-vitals-accordion/core-web-vitals-accordion-v2.tsx
  client/performance-profiler/components/core-web-vitals-accordion/index.tsx
  client/performance-profiler/components/core-web-vitals-accordion/styles-v2.scss
  client/performance-profiler/components/core-web-vitals-accordion/styles.scss
  client/performance-profiler/components/core-web-vitals-display/core-web-vitals-details.tsx
  client/performance-profiler/components/core-web-vitals-display/core-web-vitals-details_v2.tsx
  client/performance-profiler/components/core-web-vitals-display/index.tsx
  client/performance-profiler/components/core-web-vitals-display/style.scss
  client/performance-profiler/components/metric-scale/index.tsx
  client/performance-profiler/components/metric-scale/style.scss
  client/performance-profiler/components/metric-tab-bar/index.tsx
  client/performance-profiler/components/metric-tab-bar/metric-tab-bar-v2.tsx
  client/performance-profiler/components/metric-tab-bar/style.scss
  client/performance-profiler/components/metric-tab-bar/style_v2.scss
  client/performance-profiler/utils/metrics.ts
Labels: [Status] Needs Review, Logged-in Performance Profiler i1

#95210 Allow getTitanSetUpMailboxPath for domain only sites
  client/my-sites/controller.js
Labels: [Status] Needs Review

#95233 Odyssey Stats: fix like count for most popular post/page
  client/my-sites/stats/sections/all-time-highlights-section/post-cards-group.tsx
Labels: Stats, [Status] Needs Review

#95236 Stats: query likes for post before selecting it
  client/my-sites/stats/sections/all-time-highlights-section/post-cards-group.tsx
Labels: Stats, [Status] Needs Review

#95187 Stats: Play nice with JITMs
  client/my-sites/stats/style.scss
Labels: Stats, [Status] Needs Review

#95241 Media Library: Fix error message
  client/my-sites/media-library/content.jsx
Labels: [Status] Needs Review

#95217 Stepper: Add locale suggestion to login/user step
  client/landing/stepper/declarative-flow/internals/steps-repository/__user/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/__user/style.scss
Labels: [Status] Needs Review, Stepper

#95117 Replace some of the support links for custom DNS records
  client/my-sites/domains/domain-management/dns/add-dns-record.jsx
  client/my-sites/domains/domain-management/dns/dns-record-data.jsx
  client/my-sites/domains/domain-management/dns/txt-record.jsx
  client/my-sites/domains/domain-management/settings/cards/domain-forwarding-card.tsx
  packages/urls/src/index.ts
Labels: [Status] Needs Review

#95239 move legend outside of heading container
  client/my-sites/stats/stats-subscribers-chart-section/index.tsx
Labels: Stats, [Status] Needs Review

#95186 A4A: Disable the referral CTA button when the current user is unverified.
  client/a8c-for-agencies/sections/marketplace/checkout/request-client-payment.tsx
  client/a8c-for-agencies/sections/marketplace/checkout/style.scss
Labels: [Status] Needs Review, A8c Agencies

#95231 Updates the migration status to started
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/index.tsx
Labels: [Status] Needs Review

#95232 Updates the migration status to started on the DIY flow
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/index.tsx
Labels: [Status] Needs Review

#95230 Reader Onboarding: Setup basic framework and feature flag
  client/reader/following/main.jsx
  client/reader/onboarding/index.tsx
  client/reader/onboarding/interests-modal/index.tsx
  client/reader/onboarding/style.scss
  client/reader/onboarding/subscribe-modal/index.tsx
  config/development.json
Labels: [Status] Needs Review

#95211 A4A > Pressable: Update limit exceeded notice text
  client/a8c-for-agencies/components/pressable-usage-limit-notice/index.tsx
  client/a8c-for-agencies/components/pressable-usage-limit-notice/style.scss
  client/a8c-for-agencies/sections/marketplace/common/pressable-usage-limit-notice/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/index.tsx
  client/a8c-for-agencies/sections/overview/overview.tsx
  client/a8c-for-agencies/sections/purchases/licenses/licenses-overview/index.tsx
  client/state/a8c-for-agencies/types.ts
Labels: [Status] Needs Review, A8c Agencies

#95004 BackupScheduleSetting: add component scaffolding and load it on Jetpack Cloud settings under a feature flag
  client/components/jetpack/backup-schedule-setting/index.tsx
  client/components/jetpack/backup-schedule-setting/style.scss
  client/jetpack-cloud/sections/settings/controller.tsx
Labels: [Status] Needs Review, [Feature] Backups

#95223 Performance Profiler: Pass the filter change callback to update the URL on the CWW recommendations link
  client/performance-profiler/pages/dashboard/index.tsx
Labels: [Status] Needs Review

#95262 Hide FollowingIntro when reader onboarding flag is set
  client/reader/following/main.jsx
Labels: [Status] Needs Review

#95200 Stats: Align the total subscriber count with the chart when subscriber accounts deleted
  client/my-sites/stats/hooks/use-subscribers-totals-query.tsx
Labels: Stats, [Status] Needs Review

#95237 Logged-in Profiler: Improve page selector readability
  client/hosting/performance/components/PageSelector.tsx
  client/hosting/performance/hooks/useSitePerformancePageReports.ts
  client/hosting/performance/style.scss
Labels: [Status] Needs Review, Logged-in Performance Profiler i1

#95268 Performance Profiler: Add translate method
  client/performance-profiler/components/metric-tab-bar/index.tsx
Labels: [Status] Needs Review

#95181 Redirect to plugins.php after paid plugin activation instead of Congrats page
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/marketplace/use-plugins-thank-you-data.tsx
  client/my-sites/marketplace/pages/marketplace-product-install/index.tsx
Labels: [Status] Needs Review

#95274 [2nd try] Redirect to plugins.php after paid plugin activation instead of Congrats page
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
  client/my-sites/checkout/checkout-thank-you/marketplace/use-plugins-thank-you-data.tsx
  client/my-sites/marketplace/pages/marketplace-product-install/index.tsx
Labels: [Status] Needs Review

#95249 Update social previews to not add url to Bluesky posts by default
  packages/social-previews/package.json
  packages/social-previews/src/bluesky-preview/post-preview.tsx
  packages/social-previews/src/bluesky-preview/post/body/index.tsx
  packages/social-previews/src/bluesky-preview/types.ts
Labels: [Status] Needs Review

#95275 /wordpress-hosting: Remove experiment related code
  client/blocks/signup-form/passwordless.jsx
  client/blocks/signup-form/social.jsx
Labels: [Status] Needs Review

#95215 A4A: Add the 'Growth Accelerator' card on the Overview sidebar.
  client/a8c-for-agencies/sections/overview/sidebar/growth-accelerator/index.tsx
  client/a8c-for-agencies/sections/overview/sidebar/growth-accelerator/style.scss
  client/a8c-for-agencies/sections/overview/sidebar/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#95270 Site Profiler: Prevent active metric tab border overflow
  client/performance-profiler/components/metric-tab-bar/style.scss
Labels: [Status] Needs Review, Reviewer Can Merge, Logged-in Performance Profiler i1

#95244 Stepper: Use persisted state on domains step
  client/landing/stepper/declarative-flow/internals/analytics/record-step-navigation.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/index.tsx
Labels: [Status] Needs Review, Stepper

#95277 A4A: Remove extra dot on the Growth Accelerator description.
  client/a8c-for-agencies/sections/overview/sidebar/growth-accelerator/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#95247 Tracking: Improve selected sign up domain origin
  client/landing/stepper/declarative-flow/onboarding.ts
Labels: [Status] Needs Review, Stepper

#95001 Performance Profiler: Handle the lang parameter in the URL
  client/performance-profiler/index.web.ts
Labels: [Status] Needs Review

#95279 Backup: fix missing "learn more" translation
  client/my-sites/backup/main.jsx
Labels: [Status] Needs Review

#95168 Gh2977/remove/stripe source from translate payment names
  client/my-sites/checkout/src/lib/translate-payment-method-names.ts
  client/my-sites/checkout/src/test/generic-redirect-processor.ts
  client/my-sites/checkout/src/test/we-chat-processor.ts
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
  packages/wpcom-checkout/src/types.ts
Labels: [Status] Needs Review, [Feature] Checkout, Payment Methods

#95266 Add migration status to sites dashboard
  client/hosting/sites/components/sites-dashboard.tsx
  client/hosting/sites/components/sites-dataviews/sites-site-status.tsx
  client/hosting/sites/components/sites-dataviews/style.scss
  packages/data-stores/src/site/types.ts
  packages/sites/src/site-excerpt-types.ts
  packages/sites/src/site-status.tsx
  packages/sites/src/site-type.ts
  packages/sites/src/use-sites-list-grouping.tsx
  packages/sites/tests/create-mock-site.ts
  packages/sites/tests/use-sites-list-grouping.test.ts
Labels: [Status] Needs Review

#95286 Site Profiler: Fix active metric tab border width
  client/performance-profiler/components/metric-tab-bar/style.scss
Labels: [Status] Needs Review, Reviewer Can Merge, Logged-in Performance Profiler i1

#95290 e2e: Fix Map block test
  packages/calypso-e2e/src/lib/blocks/block-flows/map.ts
Labels: [Status] Needs Review

#95267 Reader Onboarding: Establish Interests Overlay
  client/reader/onboarding/interests-modal/index.tsx
  client/reader/onboarding/interests-modal/style.scss
Labels: [Status] Needs Review

#93719 Launchpad: Adds the completion logic for the 'Install the mobile app' task
  packages/launchpad/src/setup-actions.ts
Labels: [Status] Needs Review

#95303 Checkout: Fix long domain names breaking checkout modal
  packages/composite-checkout/src/components/checkout-modal.tsx
Labels: [Type] Bug, [Status] Needs Review

#95280 Substack importer: add translation functions to stable strings
  client/my-sites/importer/newsletter/content-upload/author-mapping-pane.jsx
  client/my-sites/importer/newsletter/content-upload/importing-pane.jsx
  client/my-sites/importer/newsletter/content-upload/uploading-pane.jsx
  client/my-sites/importer/newsletter/content.tsx
  client/my-sites/importer/newsletter/importer.tsx
  client/my-sites/importer/newsletter/select-newsletter-form.tsx
  client/my-sites/importer/newsletter/subscribers/import-subscribers-error.tsx
  client/my-sites/importer/newsletter/subscribers/paid-subscribers.tsx
  client/my-sites/importer/newsletter/subscribers/paid-subscribers/connect-stripe.tsx
  client/my-sites/importer/newsletter/subscribers/paid-subscribers/map-plan.tsx
  client/my-sites/importer/newsletter/subscribers/paid-subscribers/map-plans.tsx
  client/my-sites/importer/newsletter/subscribers/paid-subscribers/no-plans.tsx
  client/my-sites/importer/newsletter/subscribers/paid-subscribers/success-notice.tsx
  client/my-sites/importer/newsletter/subscribers/start-import-button.tsx
  client/my-sites/importer/newsletter/subscribers/step-done.tsx
  client/my-sites/importer/newsletter/subscribers/step-importing.tsx
  client/my-sites/importer/newsletter/subscribers/step-initial.tsx
  client/my-sites/importer/newsletter/subscribers/upload-form.tsx
  client/my-sites/importer/newsletter/summary.tsx
  client/my-sites/importer/newsletter/summary/content.tsx
  client/my-sites/importer/newsletter/summary/subscribers.tsx
Labels: [Status] Needs Review

#95308 Fix for com.au and some other 2nd level TLDs detection
  client/lib/domains/tlds/wpcom-multi-level-tlds.json
Labels: [Type] Bug, [Status] Needs Review

#95053 A4A > Partner Directory: Add new industry values to PD
  client/a8c-for-agencies/sections/partner-directory/components/hooks/use-form-selectors.ts
  client/a8c-for-agencies/sections/partner-directory/components/industries-selector.tsx
Labels: [Status] Needs Review, A8c Agencies
