Repository Automattic/wp-calypso, pull requests merged in 2024-11, with the labels that each got.

#95878 Add missing page tracks
  client/hosting/overview/components/hosting-overview.tsx
  client/hosting/staging-site/controller.js
Labels: [Status] Needs Review, Groundskeeping

#95975 Stats: Hide email stats when new date filtering enabled
  client/my-sites/stats/site.jsx
Labels: Stats, [Status] Needs Review

#95924 Stats: add start date for devices and utm stats
  client/my-sites/stats/hooks/utils.ts
  client/state/data-layer/wpcom/sites/stats/utm-metrics/index.ts
Labels: Stats, [Status] Needs Review

#95974 Stats: Fix default start date
  client/my-sites/stats/site.jsx
Labels: Stats, [Status] Needs Review

#95874 SMP: Make the item preview content with sidebar responsive
  client/a8c-for-agencies/components/items-dashboard/item-preview-pane/index.tsx
  client/a8c-for-agencies/components/items-dashboard/item-preview-pane/style.scss
  client/a8c-for-agencies/components/items-dashboard/item-preview-pane/types.ts
  client/components/section-nav/index.jsx
  client/components/section-nav/item.scss
  client/components/section-nav/style.scss
  client/components/section-nav/tabs.jsx
  client/components/section-nav/tabs.scss
  client/components/section-nav/test/index.jsx
  client/my-sites/site-settings/site-setting-privacy/form.tsx
  client/sites/components/panel-sidebar/index.tsx
  client/sites/components/panel-sidebar/style.scss
  client/sites/components/site-preview-pane/dotcom-preview-pane.tsx
Labels: [Status] Needs Review

#95941 Add missing monitoring and logs tracking events
  client/hosting/logs/components/site-logs-toolbar/index.tsx
  client/hosting/logs/components/site-logs.tsx
  client/hosting/monitoring/components/time-range-picker/index.jsx
Labels: [Status] Needs Review, Groundskeeping

#95883 Add missing overview tracking events
  client/components/hosting-card/index.tsx
  client/hosting/overview/components/active-domains-card.tsx
  client/hosting/overview/components/plan-card.tsx
  client/hosting/overview/components/quick-actions-card.tsx
  client/hosting/overview/components/site-backup-card/index.js
Labels: [Status] Needs Review, Groundskeeping

#95940 Untangling: fix focus style on panel sidebar
  client/sites/components/panel-sidebar/style.scss
Labels: [Status] Needs Review

#92773 Bluehost Plans: Remove dummy plan definitions from Calypso
  packages/calypso-products/src/constants/wpcom.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/test/plan-lookups.js
Labels: [Status] Needs Review

#95981 Ensure site prop is not null
  client/my-sites/site-settings/form-general.jsx
  client/my-sites/site-settings/wrap-settings-form.jsx
Labels: [Status] Needs Review, Lego Maintenance

#95978 Untangling: redirect to /hosting-features if Advanced Tools is not supported
  client/sites/controller.tsx
  client/sites/tools/index.tsx
Labels: [Status] Needs Review

#95937 Untangling: show unsupported notice for Settings -> Administration for staging sites
  client/sites/components/panel-sidebar/index.tsx
  client/sites/settings/administration/index.tsx
  client/sites/settings/controller.tsx
Labels: [Status] Needs Review

#95979 wpcom-block-editor: Support getting the canvas mode from the query string after GB 19.6
  apps/wpcom-block-editor/src/wpcom/features/live-preview/hooks/use-previewing-theme.ts
  apps/wpcom-block-editor/src/wpcom/features/live-preview/hooks/use-sidebar-notice.tsx
  apps/wpcom-block-editor/src/wpcom/features/live-preview/live-preview-notice-plugin.tsx
  apps/wpcom-block-editor/src/wpcom/features/live-preview/upgrade-button.tsx
  apps/wpcom-block-editor/src/wpcom/features/live-preview/utils.ts
  apps/wpcom-block-editor/src/wpcom/features/tracking/site-editor-load.tsx
  apps/wpcom-block-editor/src/wpcom/hooks/use-canvas-mode.ts
  apps/wpcom-block-editor/src/wpcom/hooks/use-location.ts
  apps/wpcom-block-editor/src/wpcom/utils.ts
Labels: [Status] Needs Review

#95953 Help Center: fix aggressive styles
  apps/help-center/postcss.config.js
Labels: [Status] Needs Review

#95909 Reader: update reader sidebar icons
  client/my-sites/sidebar/style.scss
  client/reader/components/icons/a8c-conversations-icon.jsx
  client/reader/components/icons/a8c-icon.jsx
  client/reader/components/icons/comment-icon.jsx
  client/reader/components/icons/conversations-icon.jsx
  client/reader/components/icons/discover-icon.jsx
  client/reader/components/icons/following-icon.jsx
  client/reader/components/icons/likes-icon.jsx
  client/reader/components/icons/list-icon.jsx
  client/reader/components/icons/manage-subscriptions-icon.jsx
  client/reader/components/icons/notifications-icon.jsx
  client/reader/components/icons/p2-icon.jsx
  client/reader/components/icons/search-icon.jsx
  client/reader/components/icons/tag-icon.jsx
  client/reader/sidebar/index.jsx
  client/reader/sidebar/reader-sidebar-lists/index.jsx
  client/reader/sidebar/reader-sidebar-organizations/list.jsx
  client/reader/sidebar/reader-sidebar-tags/index.jsx
  client/reader/sidebar/style.scss
Labels: [Status] Needs Review

#95967 Reader Onboarding: Move continue button to modal header
  client/reader/onboarding/subscribe-modal/index.tsx
  client/reader/onboarding/subscribe-modal/style.scss
Labels: [Status] Needs Review

#95987 Reader: update post actions positioning
  client/blocks/comment-button/index.jsx
  client/blocks/comment-button/style.scss
  client/blocks/reader-post-actions/index.jsx
  client/blocks/reader-share/index.jsx
  client/reader/components/icons/repost.jsx
  client/reader/components/icons/share-icon.jsx
  client/reader/search-stream/style.scss
Labels: [Status] Needs Review

#95993 Reader: update ellipsis menu order
  client/blocks/reader-post-options-menu/reader-post-ellipsis-menu.jsx
Labels: [Status] Needs Review

#95827 Checkout: Prevent fatal in sidebar features list for unlisted product
  client/my-sites/checkout/src/lib/get-plan-features.ts
Labels: [Status] Needs Review, [Feature] Checkout

#95907 Domains: Hide cancel and transfer options for 100-year domains
  client/me/purchases/cancel-purchase/index.jsx
  client/me/purchases/manage-purchase/index.tsx
  client/my-sites/domains/domain-management/components/domain/hundred-year-domain-not-transferrable-notice.jsx
  client/my-sites/domains/domain-management/settings/index.tsx
  client/my-sites/domains/domain-management/transfer/transfer-page/index.tsx
  client/my-sites/domains/domain-management/transfer/transfer-to-any-user/transfer-domain-to-any-user.tsx
  client/my-sites/domains/domain-management/transfer/transfer-to-other-site/transfer-domain-to-other-site.tsx
Labels: [Status] Needs Review

#95838 Update copy on "How you want to migrate" step
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx
Labels: [Status] Needs Review

#96000 Check for translations before using new copy
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx
Labels: [Status] String Freeze

#95992 Help Center Remove history icon from the header on chat route
  packages/help-center/src/components/help-center-header.tsx
Labels: [Status] Needs Review, [Feature] Help Center

#95995 Fix some theme filters appearing untranslated
  client/my-sites/themes/theme-showcase.jsx
Labels: [Status] Needs Review

#95942 Stats: Chart refresh header component update
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-chart-tabs/chart-header.jsx
  client/my-sites/stats/stats-chart-tabs/index.jsx
Labels: Stats, [Status] Needs Review

#95939 A4A: Implement the 'Hosting options' section on the new Migrations page.
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-hosting-options.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-hosting-options/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-hosting-options/style.scss
  client/assets/images/a8c-for-agencies/pressable-card-banner.svg
  client/assets/images/a8c-for-agencies/wpcom-card-banner.svg
Labels: [Status] Needs Review, A8c Agencies

#95790 A4A > Overview: Fix the growth accelerator overflow issue
  client/a8c-for-agencies/sections/overview/sidebar/growth-accelerator/style.scss
Labels: [Status] Needs Review, A8c Agencies

#95859 A4A: Implement the testimonials section on the new Migrations page.
  client/a8c-for-agencies/components/page-section/backgrounds/background-6.svg
  client/a8c-for-agencies/components/page-section/backgrounds/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-testimonials.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-testimonials/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-testimonials/style.scss
  client/assets/images/a8c-for-agencies/hosting/standard-testimonial-3.png
Labels: [Status] Needs Review, A8c Agencies

#95797 A4A > Marketplace: Open Pressable support when the Contact us button is clicked
  client/a8c-for-agencies/components/a4a-contact-support-widget/get-default-product.ts
  client/a8c-for-agencies/components/a4a-contact-support-widget/index.tsx
  client/a8c-for-agencies/components/user-contact-support-modal-form/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/details.tsx
Labels: [Status] Needs Review, A8c Agencies

#95809 A4A: Implement the 'Migrations process' section on the new Migrations page.
  client/a8c-for-agencies/components/page-section/backgrounds/background-7.svg
  client/a8c-for-agencies/components/page-section/backgrounds/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-process.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-process/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-process/style.scss
Labels: [Status] Needs Review, A8c Agencies

#95807 A4A: Implement the 'Client relationship' section on the new Migrations page.
  client/a8c-for-agencies/components/page-section/index.tsx
  client/a8c-for-agencies/sections/marketplace/common/hosting-benefits-section/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-client-relationship.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-client-relationship/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-client-relationship/style.scss
Labels: [Status] Needs Review, A8c Agencies

#95804 A4A: Implement the CTA section on the new Migrations page.
  client/a8c-for-agencies/components/page-section/backgrounds/background-8.svg
  client/a8c-for-agencies/components/page-section/backgrounds/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-cta.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-cta/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-cta/style.scss
Labels: [Status] Needs Review, A8c Agencies

#95985 Help Center: Add long message validation error
  packages/odie-client/src/components/message/style_redesign.scss
  packages/odie-client/src/components/send-message-input/index.tsx
  packages/odie-client/src/components/send-message-input/resizable-textarea.tsx
Labels: [Status] Needs Review, [Feature] Help Center

#95794 A4A: Implement the banner section for the new migrations page.
  client/a8c-for-agencies/components/a4a-migration-offer/index.tsx
  client/a8c-for-agencies/components/page-section/backgrounds/background-5.svg
  client/a8c-for-agencies/components/page-section/backgrounds/index.tsx
  client/a8c-for-agencies/components/simple-list/index.tsx
  client/a8c-for-agencies/components/simple-list/style.scss
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-card/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-list/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/enterprise-agency-hosting/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/standard-agency-hosting/wpcom-plan-selector/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/details.tsx
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/wpcom-card/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-banner.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-banner/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-banner/style.scss
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/style.scss
  client/a8c-for-agencies/sections/overview/body/intro-cards/index.tsx
  client/assets/images/a8c-for-agencies/migration-icon.svg
Labels: [Status] Needs Review, A8c Agencies

#95802 A4A: Implement the 'Hosting features' section on the new Migrations page.
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-hosting-features.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-hosting-features/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-hosting-features/style.scss
Labels: [Status] Needs Review, A8c Agencies

#96005 Photos Picker: Update migration connection notification
  client/my-sites/marketing/connections/google-photos-migration.jsx
  client/my-sites/marketing/connections/picasa-migration.jsx
  client/my-sites/marketing/connections/service.jsx
Labels: [Status] Needs Review

#96017 A4A: Implement the FAQs section on the new Migrations page.
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-faqs.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-faqs/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-faqs/style.scss
Labels: [Status] Needs Review, A8c Agencies

#95906 Send the vendor string to the domain availability check to support 100 year domain prices
  client/components/domains/register-domain-step/index.jsx
  client/lib/domains/check-domain-availability.js
Labels: [Status] Needs Review

#95712 Help Center: Fix autoscroll issues
  packages/odie-client/src/components/message/index.tsx
  packages/odie-client/src/components/message/jump-to-recent.tsx
  packages/odie-client/src/components/message/message-content.tsx
  packages/odie-client/src/components/message/messages-container.tsx
  packages/odie-client/src/components/send-message-input/index.tsx
  packages/odie-client/src/context/index.tsx
  packages/odie-client/src/context/use-load-previous-chat.ts
  packages/odie-client/src/index.tsx
  packages/odie-client/src/query/use-odie-chat.ts
  packages/odie-client/src/useAutoScroll.ts
  packages/odie-client/src/useLastMessageVisibility.ts
Labels: [Status] Needs Review

#96004 Jetpack Cloud: allow redirect on "Start for free" button from My Jetpack
  client/my-sites/plans/jetpack-plans/jetpack-free-card/test/use-jetpack-free-button-props.js
  client/my-sites/plans/jetpack-plans/jetpack-free-card/use-jetpack-free-button-props.ts
Labels: [Status] Needs Review

#96020 Help Center: Fix avatar image on chat history
  packages/help-center/src/components/help-center-recent-conversations.tsx
  packages/help-center/src/components/help-center-search-results.tsx
  packages/help-center/src/components/help-center-support-chat-message.tsx
  packages/odie-client/src/assets/human-avatar.tsx
  packages/odie-client/src/components/message/index.tsx
Labels: [Status] Needs Review, [Feature] Help Center

#95839 Help Center: Add logic for archived conversations
  packages/help-center/src/components/help-center-chat-history.tsx
  packages/help-center/src/components/utils.tsx
  packages/help-center/src/styles.scss
  packages/odie-client/src/query/use-create-zendesk-conversation.ts
Labels: [Status] Needs Review, [Feature] Help Center

#95762 Post-migration purchase experience: Add "View sites dashboard" button to migration message screen
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/style.scss
Labels: [Status] Needs Review, [Status] String Freeze

#95996 Odie: add support interactions API
  packages/data-stores/src/help-center/actions.ts
  packages/data-stores/src/help-center/reducer.ts
  packages/data-stores/src/help-center/selectors.ts
  packages/help-center/src/components/utils.tsx
  packages/help-center/src/hooks/use-load-support-interaction.ts
  packages/odie-client/src/data/handle-support-interactions-fetch.ts
  packages/odie-client/src/data/use-get-support-interaction-by-id.ts
  packages/odie-client/src/data/use-get-support-interactions.ts
  packages/odie-client/src/data/use-manage-support-interaction.ts
  packages/odie-client/src/types/index.ts
Labels: [Status] Needs Review, [Feature] Help Center

#95994 Post-purchase experience: remove pending-migration sticker
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/test/index.tsx
Labels: [Status] Needs Review

#96029 Purchases and Checkout: Rename createStripeSetupIntent to confirmStripeSetupIntentAndAttachCard for clarity
  client/a8c-for-agencies/sections/purchases/payment-methods/hooks/use-assign-new-card-processor.ts
  client/jetpack-cloud/sections/partner-portal/payment-methods/assignment-processor-functions.ts
  client/me/purchases/manage-purchase/payment-method-selector/assignment-processor-functions.ts
  packages/calypso-stripe/README.md
  packages/calypso-stripe/src/index.tsx
Labels: [Status] Needs Review, [Feature] Checkout, [Feature] Purchase Management

#95969 Store site goals option in Big Sky signup flow
  client/landing/stepper/declarative-flow/internals/steps-repository/launch-big-sky/index.tsx
Labels: [Type] Task

#95965 Big Sky eligibility: Show on desktop/tablet, support personal plan
  client/landing/stepper/hooks/use-is-site-big-sky-eligible.ts
Labels: [Type] Task

#95727 Reader: Stub out DataViews
  client/reader/following/main.jsx
  client/reader/recent/index.tsx
  client/reader/recent/style.scss
Labels: [Status] Needs Review

#96030 Reader: Strip HTML from site description
  client/reader/get-helpers.js
Labels: [Status] Needs Review

#96001 Plans: ship the simplified grid to all users
  client/my-sites/plans-features-main/hooks/use-simplified-features-grid-experiment.ts
Labels: [Status] Needs Review

#95976 Stats: Change width of most cards to 50% for easier layout
  client/my-sites/stats/site.jsx
Labels: Stats, [Status] Needs Review

#96039 Stats: Fix module setting popup width
  packages/components/src/highlight-cards/style.scss
Labels: Stats, [Status] Needs Review

#96015 Untangling: Add Advanced Tools -> Monitoring
  client/hosting/monitoring/controller.tsx
  client/hosting/overview/components/plan-bandwidth.tsx
  client/sites/components/panel-sidebar/style.scss
  client/sites/components/site-preview-pane/dotcom-preview-pane.tsx
  client/sites/tools/controller.tsx
  client/sites/tools/monitoring/components/site-monitoring-line-chart/index.tsx
  client/sites/tools/monitoring/components/site-monitoring-line-chart/line-chart-tooltip.tsx
  client/sites/tools/monitoring/components/site-monitoring-line-chart/time-highlight-plugin.ts
  client/sites/tools/monitoring/components/site-monitoring-line-chart/uplot-tooltip-plugin.ts
  client/sites/tools/monitoring/components/site-monitoring-line-chart/use-site-metrics-status-codes-data.ts
  client/sites/tools/monitoring/components/site-monitoring-pie-chart/index.tsx
  client/sites/tools/monitoring/components/site-monitoring-pie-chart/style.scss
  client/sites/tools/monitoring/components/site-monitoring.tsx
  client/sites/tools/monitoring/components/style.scss
  client/sites/tools/monitoring/components/time-range-picker/index.jsx
  client/sites/tools/monitoring/components/time-range-picker/style.scss
  client/sites/tools/monitoring/hooks/use-group-by-time.ts
  client/sites/tools/monitoring/hooks/use-metrics-query.ts
  client/sites/tools/monitoring/index.tsx
  client/sites/tools/monitoring/test/main.js
  client/sites/tools/monitoring/test/use-site-metrics-status-codes-data.tsx
Labels: [Status] Needs Review

#96016 Untangling: Add Advanced Tools -> Logs
  client/hosting/logs/controller.tsx
  client/sites/components/site-preview-pane/constants.ts
  client/sites/components/site-preview-pane/dotcom-preview-pane.tsx
  client/sites/tools/controller.tsx
  client/sites/tools/index.tsx
  client/sites/tools/logs/components/filter-params.ts
  client/sites/tools/logs/components/site-logs-header/index.tsx
  client/sites/tools/logs/components/site-logs-header/style.scss
  client/sites/tools/logs/components/site-logs-table/index.tsx
  client/sites/tools/logs/components/site-logs-table/site-logs-expanded-content.tsx
  client/sites/tools/logs/components/site-logs-table/site-logs-table-row.tsx
  client/sites/tools/logs/components/site-logs-table/skeleton.tsx
  client/sites/tools/logs/components/site-logs-table/style.scss
  client/sites/tools/logs/components/site-logs-toolbar/date-time-picker.tsx
  client/sites/tools/logs/components/site-logs-toolbar/index.tsx
  client/sites/tools/logs/components/site-logs-toolbar/style.scss
  client/sites/tools/logs/components/site-logs.tsx
  client/sites/tools/logs/hooks/use-current-site-gmt-offset.ts
  client/sites/tools/logs/hooks/use-site-logs-downloader.ts
  client/sites/tools/logs/index.tsx
  client/sites/tools/logs/test/date-time-picker.tsx
  client/sites/tools/logs/test/site-logs-table.tsx
Labels: [Status] Needs Review

#95983 Untangling: refactor feature gating so that sidebar and content use same logic
  client/sites/components/site-preview-pane/dotcom-preview-pane.tsx
  client/sites/controller.tsx
  client/sites/settings/administration/hooks/use-is-administration-setting-supported.tsx
  client/sites/settings/administration/index.tsx
  client/sites/settings/agency/hooks/use-is-agency-setting-supported.tsx
  client/sites/settings/agency/index.tsx
  client/sites/settings/controller.tsx
  client/sites/utils.ts
Labels: [Status] Needs Review

#96021 Untangling: Add Advanced Tools -> Staging Site
  client/hosting/staging-site/components/staging-site-card/card-content/card-content-wrapper.tsx
  client/hosting/staging-site/components/staging-site/style.scss
  client/hosting/staging-site/controller.js
  client/my-sites/activity/activity-log/index.jsx
  client/sites/components/site-preview-pane/dotcom-preview-pane.tsx
  client/sites/tools/controller.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/card-content-wrapper.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/exceed-quota-error-content.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/manage-staging-site-card-content.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/new-staging-site-card-content.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/staging-site-loading-bar-card-content.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/staging-site-loading-error-card-content.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/staging-site-sync-loading-bar-card-content.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/staging-sync-card.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/stories/manage-staging-site-card-content.stories.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/stories/new-staging-site-card-content.stories.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/stories/staging-site-loading-bar-card-content.stories.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/stories/staging-site-loading-error-card-content.stories.tsx
  client/sites/tools/staging-site/components/staging-site-card/confirmation-modal.tsx
  client/sites/tools/staging-site/components/staging-site-card/index.js
  client/sites/tools/staging-site/components/staging-site-card/loading-placeholder.tsx
  client/sites/tools/staging-site/components/staging-site-card/staging-site-production-card.tsx
  client/sites/tools/staging-site/components/staging-site-card/sync-options-panel.tsx
  client/sites/tools/staging-site/components/staging-site-card/test/index.js
  client/sites/tools/staging-site/components/staging-site-card/test/sync-options-panel.js
  client/sites/tools/staging-site/components/staging-site-upsell-nudge/index.tsx
  client/sites/tools/staging-site/components/staging-site/index.tsx
  client/sites/tools/staging-site/components/staging-site/style.scss
  client/sites/tools/staging-site/hooks/use-add-staging-site.ts
  client/sites/tools/staging-site/hooks/use-check-staging-site-status.ts
  client/sites/tools/staging-site/hooks/use-delete-staging-site.ts
  client/sites/tools/staging-site/hooks/use-get-lock-query.ts
  client/sites/tools/staging-site/hooks/use-has-valid-quota.ts
  client/sites/tools/staging-site/hooks/use-is-status-reverting.ts
  client/sites/tools/staging-site/hooks/use-production-site-detail.ts
  client/sites/tools/staging-site/hooks/use-site-sync-status.tsx
  client/sites/tools/staging-site/hooks/use-staging-site.ts
  client/sites/tools/staging-site/hooks/use-staging-sync.ts
  client/sites/tools/staging-site/index.tsx
  client/sites/tools/staging-site/style.scss
  client/sites/tools/staging-site/test/index.js
Labels: [Status] Needs Review

#96026 Help Center: style archived no results
  packages/help-center/src/components/help-center-chat-history.scss
  packages/help-center/src/components/help-center-chat-history.tsx
Labels: [Status] Needs Review

#96024 Media: Update video/audio uploads upsell nudge
  client/my-sites/media-library/header.jsx
  client/my-sites/media-library/list-no-content.jsx
  client/my-sites/media-library/list-plan-promo.js
  client/my-sites/media-library/list-plan-upgrade-nudge.jsx
  client/my-sites/media-library/style.scss
  client/my-sites/media-library/upload-button.jsx
Labels: [Status] Needs Review, [Status] Needs Design, [Status] Design Input Requested

#96052 Help Center: Fix send message button disabled state
  packages/odie-client/src/components/send-message-input/style.scss
Labels: [Status] Needs Review, [Feature] Help Center

#95783 A4A > Overview: Update the Pressable card text
  client/a8c-for-agencies/sections/overview/body/hosting/pressable-oferring.tsx
Labels: [Status] Needs Review, [Status] String Freeze, A8c Agencies

#95784 A4A > Add Site: Update text & order of the "Add site" menu
  client/a8c-for-agencies/components/add-new-site-button/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze, A8c Agencies

#96054 Remove Tailored Flows: Fixed the event props so that the event does not end up rejected
  client/landing/stepper/utils/flow-redirect-handler.ts
Labels: [Status] Needs Review

#95787 A4A > Checkout: Update referral checkout summary notice
  client/a8c-for-agencies/sections/marketplace/checkout/notice-summary.tsx
Labels: [Status] Needs Review, [Status] String Freeze, A8c Agencies

#96062 Help Center: Update chat paragraphs text spacing
  packages/odie-client/src/components/message/messages-container.tsx
  packages/odie-client/src/components/message/style_redesign.scss
Labels: [Status] Needs Review

#96047 A4A: Enable the new Migrations page on the 'Staging' and 'Production' environment.
  config/a8c-for-agencies-production.json
  config/a8c-for-agencies-stage.json
Labels: [Status] Needs Review

#96022 Newsletter settings: add floating subscribe button
  client/my-sites/site-settings/settings-newsletter/SubscribeFloatingButtonSetting.tsx
  client/my-sites/site-settings/settings-newsletter/main.tsx
Labels: [Status] Needs Review, [Feature] Subscriptions, Newsletters

#96063 Help Center: Fix wrap for long words
  packages/odie-client/src/components/message/style_redesign.scss
Labels: [Status] Needs Review

#96025 Photos Picker: Don't provide filter params to the fetch media items request when the picker is turned ON
  client/components/data/media-list-data/index.jsx
Labels: [Status] Needs Review

#96027 Feature flag for Jetpack cloud added
  client/my-sites/plugins/main.jsx
  client/my-sites/plugins/plugin-list-header/index.jsx
  client/my-sites/plugins/plugin-list-header/style.scss
  client/my-sites/plugins/plugins-list/index.jsx
  client/my-sites/plugins/plugins-list/style-compatibilty.scss
  client/my-sites/plugins/style-compatibilty.scss
Labels: [Status] Needs Review

#96043 Recent Feed Overhaul - Use the FullPostView component
  client/reader/recent/index.tsx
  client/reader/recent/style.scss
Labels: [Status] Needs Review

#95997 Update 100-Year domains
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-step-wrapper/index.tsx
Labels: [Status] Needs Review

#96068 Help Center: Load attachments from zendesk
  packages/odie-client/src/components/message/custom-a-link.tsx
  packages/odie-client/src/components/message/message-content.tsx
  packages/odie-client/src/components/message/user-message.tsx
  packages/odie-client/src/data/use-get-zendesk-conversation.ts
  packages/odie-client/src/types/index.ts
  packages/odie-client/src/utils/zendesk-message-converter.ts
Labels: [Status] Needs Review, [Feature] Help Center

#96074 Help Center: prevent new conversation initiation if already started and disable button accordingly
  packages/odie-client/src/components/message/direct-escalation-link.tsx
  packages/odie-client/src/components/message/style_redesign.scss
Labels: [Status] Needs Review, [Feature] Help Center

#96081 Help Center: Update button text from 'Start conversation' to 'Get support'
  packages/help-center/src/components/help-center-chat-history.tsx
Labels: [Status] Needs Review, [Feature] Help Center

#96066 Reader: add recent stream
  client/reader/recent/index.tsx
  client/state/data-layer/wpcom/read/streams/index.js
Labels: [Status] Needs Review

#96041 Delete boilerplate "About" page if launching Big Sky
  client/landing/stepper/declarative-flow/internals/steps-repository/launch-big-sky/index.tsx
Labels: [Status] Needs Review, [Type] Task

#96089 Stats Traffic Page: Alway use period `day` for summarize mode
  client/my-sites/stats/site.jsx
Labels: Stats, [Status] Needs Review

#96013 Move domain search suggestion onClick to Select Button
  client/components/domains/domain-suggestion/index.jsx
  packages/calypso-e2e/src/lib/components/domain-search-component.ts
Labels: [Status] Needs Review

#96086 Domains: Fix the spacing on Domains page to match with Sites page
  client/my-sites/domains/domain-management/list/bulk-all-domains.tsx
  client/my-sites/domains/domain-management/list/style.scss
  packages/domains-table/src/domains-table-filters/index.tsx
Labels: [Status] Needs Review

#94747 A4A > Signup: Adding smoke tests
  test/e2e/specs/a8c-for-agencies/signup__smoke.ts
Labels: [Status] Needs Review

#96064 Untangling: Add Advanced Tools -> SFTP/SSH
  client/hosting/server-settings/components/sftp-card/card.tsx
  client/hosting/server-settings/components/sftp-card/test/index.js
  client/hosting/server-settings/main.tsx
  client/me/security-ssh-key/use-update-ssh-key-mutation.ts
  client/sites/components/panel-sidebar/style.scss
  client/sites/tools/controller.tsx
  client/sites/tools/sftp-ssh/hooks/use-is-sftp-ssh-setting-supported.ts
  client/sites/tools/sftp-ssh/hooks/use-is-ssh-setting-supported.ts
  client/sites/tools/sftp-ssh/hooks/use-sftp-ssh-setting-title.ts
  client/sites/tools/sftp-ssh/page.tsx
  client/sites/tools/sftp-ssh/sftp-card-loading-placeholder.tsx
  client/sites/tools/sftp-ssh/sftp-form.scss
  client/sites/tools/sftp-ssh/sftp-form.tsx
  client/sites/tools/sftp-ssh/ssh-key-card.tsx
  client/sites/tools/sftp-ssh/ssh-keys.scss
  client/sites/tools/sftp-ssh/ssh-keys.tsx
  client/sites/tools/sftp-ssh/style.scss
  client/sites/tools/sftp-ssh/use-atomic-ssh-keys.ts
  client/sites/tools/sftp-ssh/use-attach-ssh-key.ts
  client/sites/tools/sftp-ssh/use-detach-ssh-key.ts
Labels: [Status] Needs Review

#96018 Docs: Add subsection for `i18n-calypso` best practices
  docs/i18n.md
Labels: [Status] Needs Review, i18n, DevDocs

#96045 A4A > Referrals: Enable Enterprise hosting for refer mode
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/enterprise-agency-hosting/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/enterprise-agency-hosting/style.scss
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#96053 Global Styles on Personal: Update upsells and modals
  client/components/premium-global-styles-upgrade-modal/index.tsx
  client/components/premium-global-styles-upgrade-modal/use-global-styles-upgrade-translations.tsx
  client/components/theme-tier/theme-tier-badge/theme-tier-style-variation-badge.js
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/plan/index.tsx
  client/my-sites/site-settings/site-setting-privacy/notice.tsx
  client/my-sites/theme/main.jsx
  client/my-sites/themes/theme-options.js
  packages/global-styles/src/components/global-styles-variations/index.tsx
Labels: [Status] Needs Review

#96088 Help Center: Adjust spinner position and margin in send message input
  packages/help-center/src/components/help-center-chat.scss
Labels: [Status] Needs Review, [Feature] Help Center

#96087 Limit parallel DotOrg API requests
  client/components/data/query-dotorg-plugins/README.md
  client/components/data/query-dotorg-plugins/index.jsx
  client/my-sites/plugins/main.jsx
  client/my-sites/plugins/plugins-list/plugins-list-dataviews.tsx
  client/my-sites/plugins/plugins-list/use-fields.tsx
  client/state/plugins/wporg/actions.js
Labels: [Status] Needs Review

#96094 Enable Bulk Plugin Management: Fix issue where dataview page freezes
  client/my-sites/plugins/plugins-list/plugins-list-dataviews.tsx
  client/my-sites/plugins/sidebar/index.tsx
Labels: [Status] Needs Review, Logged-in Performance Profiler i1, Enable Bulk Plugin Management

#96014 Summary: Show clearer number of users imported/failed after import
  client/my-sites/importer/newsletter/importer.scss
  client/my-sites/importer/newsletter/summary.tsx
  client/my-sites/importer/newsletter/summary/SummaryStat.tsx
  client/my-sites/importer/newsletter/summary/content.tsx
  client/my-sites/importer/newsletter/summary/subscribers.tsx
Labels: [Status] In Progress, [Status] Needs Review, [Status] String Freeze

#96102 Post Purchase: Add feature flag pending status
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#96082 Payment Management and Checkout: Use dedicated endpoint to create Setup Intent
  client/me/purchases/manage-purchase/payment-method-selector/assignment-processor-functions.ts
  client/my-sites/checkout/src/lib/multi-partner-card-processor.ts
Labels: [Status] Needs Review, Payment Methods

#96071 Reader Recent Feed Overhaul: Populate posts in middle column
  client/reader/recent/index.tsx
  client/reader/recent/recent-post-field.tsx
  client/reader/recent/recent-seen-field.tsx
  client/reader/recent/style.scss
  client/reader/recent/types.ts
Labels: [Status] Needs Review

#96040 Reader: move followed sites to left sidebar
  client/reader/sidebar/reader-sidebar-recent/index.tsx
  client/state/reader-ui/action-types.js
  client/state/reader-ui/sidebar/actions.js
  client/state/reader-ui/sidebar/reducer.js
Labels: [Status] Needs Review

#96119 Remove personal plan from big sky eligibility
  client/landing/stepper/hooks/use-is-site-big-sky-eligible.ts
Labels: [Status] Needs Review

#96108 Untangling: Add Settings -> Web server subtab
  client/hosting/server-settings/components/defensive-mode-card/card.tsx
  client/hosting/server-settings/components/defensive-mode-card/test/card.tsx
  client/hosting/server-settings/components/web-server-settings-card/card.tsx
  client/hosting/server-settings/main.tsx
  client/sites/settings/controller.tsx
  client/sites/settings/web-server/defensive-mode-form.scss
  client/sites/settings/web-server/defensive-mode-form.tsx
  client/sites/settings/web-server/index.tsx
  client/sites/settings/web-server/page.tsx
  client/sites/settings/web-server/style.scss
  client/sites/settings/web-server/web-server-form.scss
  client/sites/settings/web-server/web-server-form.tsx
Labels: [Status] Needs Review

#96095 A4A > Sites: Fix the site overview flyout panel URL reset
  client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#96130 Untangling: Add Settings -> Caches subtab
  client/hosting/server-settings/components/cache-card/card.tsx
  client/hosting/server-settings/components/cache-card/test/index.tsx
  client/hosting/server-settings/main.tsx
  client/sites/features.ts
  client/sites/settings/caches/edge-cache-loading-placeholder.tsx
  client/sites/settings/caches/form.scss
  client/sites/settings/caches/form.tsx
  client/sites/settings/caches/index.tsx
  client/sites/settings/caches/page.tsx
  client/sites/settings/controller.tsx
  client/sites/settings/web-server/defensive-mode-form.tsx
Labels: [Status] Needs Review

#96134 Untangling: Hide Server Settings tab under feature flag
  client/sites/components/site-preview-pane/dotcom-preview-pane.tsx
Labels: [Status] Needs Review

#96076 Help Center: Update copy
  packages/help-center/src/components/help-center-feedback-form.tsx
  packages/help-center/src/components/help-center-header.tsx
  packages/odie-client/src/components/message/direct-escalation-link.tsx
  packages/odie-client/src/components/message/dislike-feedback-message.tsx
  packages/odie-client/src/components/message/was-this-helpful-buttons.tsx
  packages/odie-client/src/constants.ts
  packages/odie-client/src/context/get-odie-initial-message.ts
  packages/odie-client/src/context/index.tsx
  packages/odie-client/src/context/use-load-previous-chat.ts
  packages/odie-client/src/query/use-create-zendesk-conversation.ts
  packages/odie-client/src/query/use-send-odie-message.ts
Labels: [Status] Needs Review, [Status] String Freeze

#96105 Help Center: add image upload for chats
  packages/data-stores/src/help-center/actions.ts
  packages/data-stores/src/help-center/reducer.ts
  packages/data-stores/src/help-center/selectors.ts
  packages/help-center/src/components/help-center-smooch.tsx
  packages/help-center/src/components/utils.tsx
  packages/odie-client/src/components/message/uri-transformer.ts
  packages/odie-client/src/components/send-message-input/attachment-button.tsx
  packages/odie-client/src/components/send-message-input/index.tsx
  packages/odie-client/src/components/send-message-input/style.scss
  packages/odie-client/src/context/use-load-previous-chat.ts
  packages/odie-client/src/data/use-get-zendesk-conversation.ts
  packages/odie-client/src/types/index.ts
  packages/zendesk-client/src/constants.ts
  packages/zendesk-client/src/index.ts
  packages/zendesk-client/src/use-attach-file.tsx
Labels: [Status] Needs Review, [Feature] Help Center

#96111 Importer: use "import" term for CTA rather than "Start import"
  client/my-sites/importer/author-mapping-pane.jsx
  client/my-sites/importer/newsletter/content-upload/author-mapping-pane.jsx
Labels: [Status] Needs Review, [Status] String Freeze

#96135 Untangling: Add Marketing -> Connections
  client/jetpack-cloud/sections/jetpack-social/connections.jsx
  client/my-sites/marketing/controller.js
  client/my-sites/marketing/main.jsx
  client/my-sites/media-library/content.jsx
  client/my-sites/media-library/test/content.jsx
  client/sites/components/site-preview-pane/constants.ts
  client/sites/components/site-preview-pane/dotcom-preview-pane.tsx
  client/sites/marketing/connections/README.md
  client/sites/marketing/connections/account-dialog-account.jsx
  client/sites/marketing/connections/account-dialog-account.scss
  client/sites/marketing/connections/account-dialog.jsx
  client/sites/marketing/connections/account-dialog.scss
  client/sites/marketing/connections/bluesky.tsx
  client/sites/marketing/connections/connection.jsx
  client/sites/marketing/connections/connections.jsx
  client/sites/marketing/connections/google-photos-migration.jsx
  client/sites/marketing/connections/google-plus-deprecation.jsx
  client/sites/marketing/connections/index.tsx
  client/sites/marketing/connections/inline-connection-action.jsx
  client/sites/marketing/connections/inline-connection.jsx
  client/sites/marketing/connections/mailchimp-settings.jsx
  client/sites/marketing/connections/mastodon.tsx
  client/sites/marketing/connections/service-action.jsx
  client/sites/marketing/connections/service-connected-accounts.jsx
  client/sites/marketing/connections/service-description.jsx
  client/sites/marketing/connections/service-description.scss
  client/sites/marketing/connections/service-example.jsx
  client/sites/marketing/connections/service-examples.jsx
  client/sites/marketing/connections/service-examples.scss
  client/sites/marketing/connections/service-placeholder.jsx
  client/sites/marketing/connections/service-tip.jsx
  client/sites/marketing/connections/service.jsx
  client/sites/marketing/connections/services-group.jsx
  client/sites/marketing/connections/services-group.scss
  client/sites/marketing/connections/services/bluesky.jsx
  client/sites/marketing/connections/services/facebook.js
  client/sites/marketing/connections/services/fediverse.jsx
  client/sites/marketing/connections/services/google-drive.js
  client/sites/marketing/connections/services/google-my-business.js
  client/sites/marketing/connections/services/google-photos.js
  client/sites/marketing/connections/services/index.js
  client/sites/marketing/connections/services/instagram-business.jsx
  client/sites/marketing/connections/services/instagram.jsx
  client/sites/marketing/connections/services/mailchimp.js
  client/sites/marketing/connections/services/mastodon.jsx
  client/sites/marketing/connections/services/nextdoor.jsx
  client/sites/marketing/connections/services/p2-github.js
  client/sites/marketing/connections/services/p2-slack.js
  client/sites/marketing/connections/services/threads.jsx
  client/sites/marketing/connections/test/mastodon.jsx
  client/sites/marketing/connections/types.ts
  client/sites/marketing/controller.tsx
  client/sites/marketing/index.tsx
  client/sites/marketing/style.scss
Labels: [Status] Needs Review

#95943 localizeUrl: Update wp-login rule to support Romanian and Vietnamese
  packages/i18n-utils/src/locales.ts
  packages/i18n-utils/src/localize-url.tsx
Labels: [Status] Needs Review, i18n

#96139 Help Center: Add temp flag for showing simplified chat history
  packages/help-center/src/components/help-center-chat-history.tsx
  packages/help-center/src/components/help-center-header.scss
  packages/help-center/src/components/help-center-support-chat-message.scss
Labels: [Status] Needs Review, [Feature] Help Center

#96103 Post- Purchase: Set a migration as `pending-DIFM/DIF` when user arrives on the credential/instructions step
  client/data/site-migration/landing/logger.ts
  client/data/site-migration/landing/types.ts
  client/data/site-migration/landing/use-update-migration-status/index.ts
  client/data/site-migration/landing/use-update-migration-status/test/index.tsx
  client/data/site-migration/use-update-migration-status.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/use-pending-migration-status.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/test/index.tsx
Labels: [Status] Needs Review, [Feature] Site Migration

#96142 Site Address Changer: Fix Bleeding Dialog Styles
  client/blocks/site-address-changer/index.jsx
  client/blocks/site-address-changer/style.scss
  client/sites/tools/database/restore-db-password.js
Labels: OSS Citizen

#96116 Refactor: Move global staticFilters constant to class method
  client/my-sites/themes/theme-showcase.jsx
Labels: [Status] Needs Review

#96123 Post-purchase: Automatically cancel migration when user exits migration
  client/data/site-migration/landing/use-migration-cancellation/index.ts
  client/data/site-migration/landing/use-migration-cancellation/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-import-or-migrate/index.tsx
Labels: [Status] Needs Review

#96072 Recent Feed Overhaul: Add FullPostView layout prop
  client/blocks/reader-full-post/header.jsx
  client/blocks/reader-full-post/index.jsx
  client/blocks/reader-full-post/style.scss
  client/reader/recent/index.tsx
  client/reader/recent/style.scss
Labels: [Status] Needs Review

#96147 Performance Profiler: Remove Generated with AI badge as it confuses users
  client/performance-profiler/components/insights-section/index.tsx
Labels: [Status] Needs Review

#96148 Help Center Chat: Enhance file upload button styles for better accessibility
  packages/help-center/src/components/help-center-chat.scss
Labels: [Status] Needs Review

#96153 Help Center: Update odie header text based on pathname condition
  packages/help-center/src/components/help-center-header.tsx
Labels: [Status] Needs Review, [Feature] Help Center

#96152 Reader Recent Feed Overhaul: Fix site icon
  client/reader/recent/recent-seen-field.tsx
  client/reader/recent/style.scss
  client/reader/recent/types.ts
Labels: [Status] Needs Review

#96122 Reader Recent Overhaul: Add styling for sidebar section
  client/reader/sidebar/index.jsx
  client/reader/sidebar/reader-sidebar-recent/index.tsx
  client/reader/sidebar/reader-sidebar-recent/style.scss
  client/reader/sidebar/style.scss
  client/reader/stream/style.scss
  client/state/reader-ui/sidebar/actions.js
Labels: [Status] Needs Review

#96150 Optimized how we load plugins and improved load state
  client/my-sites/plugins/main.jsx
  client/state/plugins/installed/selectors.js
  client/state/plugins/installed/test/selectors.js
Labels: [Status] Needs Review, Enable Bulk Plugin Management

#96156 Jetpack cloud visual improvements for DataViews integration
  client/components/dataviews/style.scss
  client/my-sites/plugins/plugins-list/style-compatibilty.scss
  client/my-sites/plugins/plugins-list/style.scss
Labels: [Status] Needs Review, Enable Bulk Plugin Management

#96136 Update /hosting-config layout
  client/my-sites/site-settings/site-admin-interface/index.js
  client/sites/settings/caches/form.tsx
  client/sites/settings/web-server/web-server-form.tsx
  client/sites/tools/sftp-ssh/sftp-form.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#96141 Fix the flickering of upsell banners in /hosting-config
  client/hosting/server-settings/main.tsx
  client/hosting/server-settings/test/index.js
  client/state/hosting/reducer.js
  client/state/hosting/test/reducer.js
Labels: [Status] Needs Review

#96132 A4A > E2E tests: Creating a new E2E test user
  packages/calypso-e2e/src/secrets/encrypted.enc
  packages/calypso-e2e/src/secrets/secrets-manager.ts
Labels: [Status] Needs Review, A8c Agencies

#96097 Remove unnecessary style overrides regarding fly-out panel
  client/a8c-for-agencies/sections/sites/sites-dashboard/style.scss
  client/components/dataviews/style.scss
  client/sites/components/dotcom-style.scss
  client/sites/components/style.scss
Labels: [Status] Needs Review

#96138 Remove email upsell from checkout/thank-you page
  client/assets/images/thank-you-upsell/email.jpg
  client/my-sites/checkout/checkout-thank-you/index.tsx
  client/my-sites/checkout/checkout-thank-you/redesign-v2/pages/domain-only.tsx
Labels: [Status] Needs Review

#96159 Global Styles on Personal: Added FEATURE_STYLE_CUSTOMIZATION to Personal Plan
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review

#96120 Stats: Add summary data path to "statsTopAuthors" normalizer
  client/state/stats/lists/utils.js
Labels: Stats, [Status] Needs Review

#96170 Reader Recent Feed Overhaul: Handle navigation and improve site selection UX
  client/reader/sidebar/reader-sidebar-recent/index.tsx
Labels: [Status] Needs Review

#96151 Reader: add pagination to recent dataview requests
  client/reader/components/icons/repost.jsx
  client/reader/recent/index.tsx
  client/reader/recent/types.ts
  client/state/data-layer/wpcom/read/streams/index.js
  client/state/data-layer/wpcom/read/streams/test/index.js
  client/state/reader/action-types.js
  client/state/reader/streams/actions.js
  client/state/reader/streams/reducer.js
Labels: [Status] Needs Review

#96171 Stack support document on to the bottom of the UTM modal for mobile
  client/my-sites/stats/stats-module-utm-builder/style.scss
Labels: Stats, [Status] Needs Review

#96189 e2e: Disable flaky Twitter embed test
  test/e2e/specs/blocks/blocks__core-jetpack-extended.ts
Labels: [Status] Needs Review

#96167 Reader: Fix author profile for feeds on full post view
  client/blocks/author-compact-profile/index.jsx
  client/blocks/reader-full-post/index.jsx
Labels: [Status] Needs Review

#96190 Reader Recent Feed Overhaul: Enable search, disable sorting, add loading.
  client/reader/recent/index.tsx
Labels: [Status] Needs Review

#96012 Help Center: Add Clear Conversation option to Help Center chat header
  packages/help-center/src/components/help-center-header.tsx
  packages/odie-client/src/hooks/use-get-combined-chat.ts
Labels: [Status] Needs Review, [Feature] Help Center

#96184 Help Center: History and New Conversation in footer
  packages/help-center/src/components/help-center-chat-history.tsx
  packages/help-center/src/components/help-center-contact-page.tsx
  packages/help-center/src/components/help-center-header.tsx
  packages/help-center/src/components/help-center-recent-conversations.tsx
  packages/help-center/src/hooks/use-start-support-interaction.ts
  packages/odie-client/src/components/message/style_redesign.scss
  packages/odie-client/src/context/index.tsx
  packages/odie-client/src/data/use-get-support-interactions.ts
  test/e2e/specs/help-center/help-center__calypso.ts
Labels: [Status] Needs Review

#96193 Odie Client: hide contact button after clicking
  packages/odie-client/src/components/message/get-support.tsx
Labels: [Status] Needs Review

#96077 Help Center: Integrate config for conditional navigation to Odie experience
  packages/help-center/src/components/help-center-feedback-form.tsx
  packages/odie-client/src/components/message/get-support.scss
  packages/odie-client/src/components/message/get-support.tsx
Labels: [Status] Needs Review, [Feature] Help Center

#96188 Added update count at the update available column
  client/my-sites/plugins/plugins-list/plugins-list-dataviews.tsx
Labels: [Status] Needs Review

#96201 Help Center: Add styles for ellipsis menu toggle button
  packages/help-center/src/components/help-center-header.scss
Labels: [Status] Needs Review, [Feature] Help Center

#96092 ToS: Add 'b' tag to instances of productName
  client/my-sites/checkout/src/components/additional-terms-of-service-in-cart.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#96003 Jetpack connect-after-checkout: bypass license activation page & redirect directly.
  client/my-sites/checkout/checkout-thank-you/licensing-pending-async-activation.tsx
  client/my-sites/checkout/checkout-thank-you/licensing-thank-you-auto-activation.tsx
  client/my-sites/checkout/checkout-thank-you/pending/style.scss
  client/my-sites/checkout/controller.jsx
  client/my-sites/checkout/get-thank-you-page-url/index.ts
  client/my-sites/checkout/get-thank-you-page-url/test/get-thank-you-page-url.ts
  client/my-sites/checkout/index.js
Labels: [Status] Needs Review

#95977 Plans: cleanup the "show fewer features" experiment
  client/my-sites/plans-features-main/hooks/use-simplified-features-grid-experiment.ts
  client/my-sites/plans-features-main/index.tsx
  client/my-sites/plans-features-main/test/index.jsx
  packages/calypso-products/src/constants/feature-group.ts
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/experiments.ts
  packages/calypso-products/src/feature-group-plan-map.ts
  packages/calypso-products/src/features-list.tsx
  packages/calypso-products/src/main.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/types.ts
  packages/plans-grid-next/src/components/comparison-grid/index.stories.tsx
  packages/plans-grid-next/src/components/features-grid/index.stories.tsx
Labels: [Status] Needs Review

#96203 Help Center: Show history for open even if not resolved chats
  packages/help-center/src/components/help-center-chat-history.tsx
  packages/help-center/src/components/help-center-contact-page.tsx
  packages/help-center/src/components/help-center-recent-conversations.tsx
Labels: [Status] Needs Review

#96175 Bulk Plugin Management: Allow plugins menu to be contextual
  client/my-sites/plugins/plugins-list/use-actions.tsx
  client/state/plugins/installed/selectors.js
  client/state/plugins/installed/status/constants.ts
  client/state/plugins/installed/test/selectors.js
Labels: [Status] Needs Review

#96129 Stats: Allow aggregate data for Stats Tabs
  client/my-sites/stats/stats-chart-tabs/index.jsx
  client/my-sites/stats/stats-tabs/index.jsx
Labels: Stats, [Status] Needs Review

#96131 Stats: Allow summarize for video endpoint
  client/state/stats/lists/utils.js
Labels: Stats, [Status] Needs Review

#96218 A4A: Fix Contact Sales & Support submit button
  client/a8c-for-agencies/components/a4a-contact-support-widget/index.tsx
Labels: [Type] Bug, [Status] Needs Review, [Size] XS, A4A

#95618 Design Selection Onboarding: Can overwrite design variations with the default variation
  packages/data-stores/src/site/actions.ts
  packages/data-stores/src/site/test/actions.ts
Labels: [Type] Bug, [Status] Needs Review, Groundskeeping

#96065 A4A > Signup: Signup form accessibility improvements
  client/a8c-for-agencies/sections/signup/agency-details-form/index.tsx
  client/a8c-for-agencies/sections/signup/agency-details-form/style.scss
Labels: [Status] Needs Review, A8c Agencies

#96182 A4A > Migrations: Initial setup of tracking site migrations
  client/a8c-for-agencies/components/sidebar-menu/hooks/use-main-menu-items.ts
  client/a8c-for-agencies/components/sidebar-menu/hooks/use-migrations-menu-items.tsx
  client/a8c-for-agencies/components/sidebar-menu/lib/constants.ts
  client/a8c-for-agencies/components/sidebar-menu/migrations.tsx
  client/a8c-for-agencies/lib/permission.ts
  client/a8c-for-agencies/sections/migrations/controller.tsx
  client/a8c-for-agencies/sections/migrations/index.tsx
  client/sections.js
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-horizon.json
Labels: [Status] Needs Review, A8c Agencies

#96220 Untangling: Rename Settings -> {Caches -> Caching}
  client/hosting/server-settings/components/cache-card/card.tsx
  client/sites/components/site-preview-pane/constants.ts
  client/sites/components/site-preview-pane/dotcom-preview-pane.tsx
  client/sites/settings/caching/edge-cache-loading-placeholder.tsx
  client/sites/settings/caching/form.scss
  client/sites/settings/caching/form.tsx
  client/sites/settings/caching/page.tsx
  client/sites/settings/controller.tsx
  client/sites/settings/index.tsx
  client/sites/settings/web-server/defensive-mode-form.tsx
Labels: [Status] Needs Review

#96215 Start: Fix "Skip Purchase" Button Styling During Launch
  client/components/domains/domain-skip-suggestion/style.scss
  client/components/domains/domain-suggestion/style.scss
Labels: [Status] Needs Review, OSS Citizen

#96109 A4A: Update Migrations page's Pressable CTA messaging.
  client/a8c-for-agencies/sections/migrations/migrations-overview-v2/sections/migrations-hosting-options/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#95675 Social: Remove defaulting to Twitter in share log
  client/blocks/post-share/publicize-actions-list.jsx
  client/state/selectors/utils/index.js
Labels: [Status] Needs Review
