Repository Automattic/wp-calypso, pull requests merged in 2024-07, with the labels that each got.

#92228 Stats: Fixing issues with data query when switching periods
  client/my-sites/stats/features/modules/stats-countries/stats-countries.tsx
  client/my-sites/stats/features/modules/stats-referrers/stats-referrers.tsx
  client/my-sites/stats/features/modules/stats-top-posts/stats-top-posts.tsx
Labels: Stats, [Status] Needs Review

#91724 Gravatar: Implement magic code signup / login
  client/blocks/login/style.scss
  client/lib/login/index.js
  client/lib/paths/login/index.js
  client/login/magic-login/index.jsx
  client/login/magic-login/request-login-email-form.jsx
  client/login/magic-login/style.scss
  client/login/wp-login/index.jsx
  client/login/wp-login/style.scss
Labels: [Status] Needs Review, Login, [Status] Reviewer Approved

#91995 Notifications: add keyboard shortcut info
  apps/notifications/package.json
  apps/notifications/src/panel/boot/stylesheets/main.scss
  apps/notifications/src/panel/state/action-types.js
  apps/notifications/src/panel/state/selectors/get-is-shortcuts-popover-open.js
  apps/notifications/src/panel/state/ui/actions.js
  apps/notifications/src/panel/state/ui/reducer.js
  apps/notifications/src/panel/templates/gridicons.jsx
  apps/notifications/src/panel/templates/index.jsx
  apps/notifications/src/panel/templates/list-header.jsx
  apps/notifications/src/panel/templates/note-list.jsx
  apps/notifications/src/panel/templates/shortcuts-popover.jsx
  apps/notifications/src/standalone/index.jsx
  yarn.lock
Labels: [Status] Needs Review

#91612 Add Stepper framework login handling to ecommerce flow
  client/landing/stepper/declarative-flow/tailored-ecommerce-flow.ts
Labels: [Status] Needs Review, Plans: eCommerce, Stepper

#92234 Automatic for Agencies: Add Site Selector & Importer feature flag
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-horizon.json
Labels: [Status] Needs Review, A8c Agencies

#92139 Site Migration: Redirect to new site migration flow from MTWPCOM
  client/jetpack-connect/authorize.js
Labels: [Status] Needs Review

#92216 A4A-Partner Directory: Update the WordPress product to WordPress.com
  client/a8c-for-agencies/sections/partner-directory/components/hooks/use-form-selectors.ts
Labels: [Status] Needs Review

#92211 A4A > Partner Directory: Implement multi-select for industry field
  client/a8c-for-agencies/data/partner-directory/use-submit-agency-details.ts
  client/a8c-for-agencies/sections/partner-directory/agency-details/hooks/use-details-form.ts
  client/a8c-for-agencies/sections/partner-directory/agency-details/index.tsx
  client/a8c-for-agencies/sections/partner-directory/components/hooks/use-form-selectors.ts
  client/a8c-for-agencies/sections/partner-directory/components/industries-selector.tsx
  client/a8c-for-agencies/sections/partner-directory/components/industry-selector.tsx
  client/a8c-for-agencies/sections/partner-directory/types.ts
  client/a8c-for-agencies/sections/partner-directory/utils/map-application-form-data.ts
  client/state/a8c-for-agencies/types.ts
Labels: [Status] Reviewer Approved, A8c Agencies

#92093 `PluginsBrowser`: Remove breadcrumbs
  client/my-sites/plugins/plugins-navigation-header/index.jsx
  packages/calypso-e2e/src/lib/pages/plugins-page.ts
  test/e2e/specs/plugins/plugins__browse.ts
Labels: [Status] Needs Review

#91850 A4A - Partner Directory: upload the agency logo as a wpcom media file
  client/a8c-for-agencies/components/a4a-image-picker/index.tsx
  client/a8c-for-agencies/components/a4a-image-picker/style.scss
  client/a8c-for-agencies/sections/partner-directory/agency-details/hooks/use-submit-form.ts
  client/a8c-for-agencies/sections/partner-directory/agency-details/index.tsx
  client/a8c-for-agencies/sections/partner-directory/agency-details/logo-picker.tsx
Labels: [Status] Needs Review, A8c Agencies

#91890 Fix quick action styling when jetpack is not connected
  client/hosting-overview/components/quick-actions-card.tsx
  client/hosting-overview/components/style.scss
Labels: [Type] Bug, [Status] Needs Review

#92225 A4A: Implement site configurations form on modal
  client/a8c-for-agencies/components/form/field/index.tsx
  client/a8c-for-agencies/sections/sites/needs-setup-sites/index.tsx
  client/a8c-for-agencies/sections/sites/needs-setup-sites/site-configurations-modal/index.tsx
  client/a8c-for-agencies/sections/sites/needs-setup-sites/site-configurations-modal/style.scss
  client/data/data-center/use-data-center-options.ts
  client/data/php-versions/use-php-versions.jsx
  client/my-sites/hosting/web-server-settings-card/index.js
Labels: [Status] Needs Review

#91618 Blaze: Add tooltip to Status column in campaign list
  client/my-sites/promote-post-i2/components/campaign-item/index.tsx
  client/my-sites/promote-post-i2/utils/index.ts
Labels: [Status] Needs Review

#92259 Frictionless Email Subscriptions: Add customizable not you text to continue as user page
  client/blocks/login/continue-as-user.jsx
  client/blocks/signup-form/index.jsx
  client/signup/steps/subscribe-email/content.jsx
  client/signup/steps/subscribe-email/index.jsx
Labels: [Status] Needs Review, Frictionless Email Subscriptions

#92262 Frictionless Email Subscriptions: Vertically and horizontally center content
  client/signup/steps/subscribe-email/content.jsx
  client/signup/steps/subscribe-email/index.jsx
  client/signup/steps/subscribe-email/style.scss
Labels: Frictionless Email Subscriptions

#92159 Storybook: move the stories towards more calypso-agnostic
  packages/calypso-products/src/experiments.ts
  packages/plans-grid-next/src/components/comparison-grid/index.stories.tsx
  packages/plans-grid-next/src/components/features-grid/index.stories.tsx
Labels: [Status] Needs Review, Plans Next [Storybook]

#92231 Stats: Adding empty state component for Clicks
  client/my-sites/stats/features/modules/stats-clicks/index.tsx
  client/my-sites/stats/features/modules/stats-clicks/stats-clicks.tsx
  client/my-sites/stats/site.jsx
Labels: Stats, [Status] Needs Review

#91857 Code Clean Up, Remove deprecated Google Analytics (GA3) References
  client/lib/analytics/ad-tracking/google-analytics.js
  client/lib/analytics/ad-tracking/index.js
  client/lib/analytics/ad-tracking/record-order.ts
  client/lib/analytics/ga.js
  client/lib/analytics/test/google-analytics.js
Labels: [Status] Needs Review

#92213 Untangling: clean up sites-dashboard
  client/blocks/plugins-scheduled-updates-multisite/index.tsx
  client/devdocs/design/index.jsx
  client/github-deployments/index.tsx
  client/hosting-features/index.tsx
  client/hosting-overview/index.tsx
  client/hosting/sites/components/dotcom-style.scss
  client/hosting/sites/components/guided-tours.scss
  client/hosting/sites/components/site-preview-pane/constants.ts
  client/hosting/sites/components/site-preview-pane/dotcom-preview-pane.tsx
  client/hosting/sites/components/site-preview-pane/preview-pane-header-buttons.tsx
  client/hosting/sites/components/site-preview-pane/preview-pane-sample.tsx
  client/hosting/sites/components/site-preview-pane/site-environment-switcher.scss
  client/hosting/sites/components/site-preview-pane/site-environment-switcher.tsx
  client/hosting/sites/components/sites-dashboard-header.tsx
  client/hosting/sites/components/sites-dashboard.tsx
  client/hosting/sites/components/sites-dataviews/constants.tsx
  client/hosting/sites/components/sites-dataviews/dataviews-fields/actions-field.tsx
  client/hosting/sites/components/sites-dataviews/dataviews-fields/site-field.tsx
  client/hosting/sites/components/sites-dataviews/index.tsx
  client/hosting/sites/components/sites-dataviews/interfaces.ts
  client/hosting/sites/components/sites-dataviews/sites-site-actions.tsx
  client/hosting/sites/components/sites-dataviews/sites-site-sort.tsx
  client/hosting/sites/components/sites-dataviews/sites-site-stats.tsx
  client/hosting/sites/components/sites-dataviews/sites-site-status.tsx
  client/hosting/sites/components/sites-dataviews/style.scss
  client/hosting/sites/components/sites-dataviews/utils.ts
  client/hosting/sites/components/style.scss
  client/hosting/sites/controller.tsx
  client/hosting/sites/hooks/use-initialize-dataviews-page.ts
  client/hosting/sites/hooks/use-initialize-dataviews-selected-item.ts
  client/hosting/sites/hooks/use-restore-site-mutation.ts
  client/hosting/sites/hooks/use-show-site-creation-notice.tsx
  client/hosting/sites/hooks/use-show-site-transferred-notice.ts
  client/hosting/sites/hooks/use-sites-dashboard-import-site-url.ts
  client/hosting/sites/hooks/use-sync-selected-site-feature.ts
  client/hosting/sites/hooks/use-sync-selected-site.ts
  client/hosting/sites/index.tsx
  client/hosting/sites/onboarding-tours/constants.ts
  client/hosting/sites/onboarding-tours/index.ts
  client/hosting/sites/onboarding-tours/use-onboarding-tours.tsx
  client/sections.js
  client/site-logs/index.tsx
  client/site-monitoring/index.tsx
  client/sites-dashboard-v2/index.tsx
  client/sites-dashboard/components/hosting-command-palette-banner.tsx
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/components/sites-site-admin-link.tsx
  client/sites-dashboard/components/sites-table-row-loading.tsx
  client/sites-dashboard/components/sites-table-row.tsx
  client/sites-dashboard/components/sites-table-row/README.md
  client/sites-dashboard/components/sites-table-row/docs/example.jsx
  client/sites-dashboard/components/sites-table.tsx
  client/sites-dashboard/components/test/sites-dashboard.tsx
  client/sites-dashboard/controller.tsx
  client/staging-site/index.tsx
Labels: [Status] Needs Review

#92237 Social Previews | Fix Threads preview to add support for caption
  client/components/share/threads-share-preview/index.jsx
  packages/social-previews/CHANGELOG.md
  packages/social-previews/package.json
  packages/social-previews/src/instagram-preview/post-preview.tsx
  packages/social-previews/src/threads-preview/helpers.ts
  packages/social-previews/src/threads-preview/link-preview.tsx
  packages/social-previews/src/threads-preview/post-preview.tsx
  packages/social-previews/src/threads-preview/types.ts
  packages/social-previews/src/types.ts
Labels: [Status] Needs Review

#92256 Close the plugins "Manage sites" modal instantly when requested
  client/my-sites/plugins/manage-site-plugins-dialog/index.jsx
  client/my-sites/plugins/manage-site-plugins-dialog/style.scss
Labels: [Status] Needs Review

#92136 Stepper: Update`import-focused` flow to use the new login strategy #92126
  client/landing/stepper/declarative-flow/import-flow.ts
  client/landing/stepper/declarative-flow/internals/steps.tsx
Labels: [Status] Needs Review

#92218 Fix ReactDOM.render is no longer supported
  client/landing/stepper/index.tsx
Labels: [Status] Needs Review, Stepper

#92267 Gravatar: Open magic code to users & Fix i18n notice styles
  client/lib/login/index.js
  client/lib/login/test/index.js
  client/lib/paths/login/index.js
  client/login/magic-login/index.jsx
  client/login/magic-login/style.scss
  client/login/wp-login/index.jsx
Labels: [Status] Needs Review, Login

#92264 A4A > Site Selector & Importer: Implement "Add sites" button with popover menu items
  client/a8c-for-agencies/components/add-new-site-button/index.tsx
  client/a8c-for-agencies/components/add-new-site-button/site-selector-and-importer.tsx
  client/a8c-for-agencies/components/add-new-site-button/style.scss
Labels: [Status] Needs Review, A8c Agencies

#92275 Repo Gardening: allow for more time to run workflow
  .github/workflows/gardening.yml
Labels: [Type] Bug, [Status] Needs Review

#92265 A4A > Site Selector & Importer: Update links for hosting menu items
  client/a8c-for-agencies/components/add-new-site-button/site-selector-and-importer.tsx
  client/a8c-for-agencies/components/add-new-site-button/style.scss
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hooks/use-pressable-ownership-type.ts
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-list/index.tsx
Labels: [Status] Needs Review

#92254 A4A: Implement the 'Add site via Jetpack connection' modal.
  client/a8c-for-agencies/components/a4a-themed-modal/index.tsx
  client/a8c-for-agencies/components/a4a-themed-modal/style.scss
  client/a8c-for-agencies/components/add-new-site-button/jetpack-connection-modal/index.tsx
  client/a8c-for-agencies/components/add-new-site-button/jetpack-connection-modal/modal-image.png
  client/a8c-for-agencies/components/add-new-site-button/jetpack-connection-modal/style.scss
  client/a8c-for-agencies/components/add-new-site-button/site-selector-and-importer.tsx
Labels: [Status] Needs Review, A8c Agencies

#92215 Migration Instructions: Add hosting badge
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/hosting-badge/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/hosting-badge/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/hosting-badge/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/test/index.tsx
Labels: [Status] Needs Review

#92178 Site Migration: Hide the 'Do it for me' modal when the user selects the same option previously
  client/landing/stepper/declarative-flow/site-migration-flow.ts
Labels: [Status] Needs Review

#92084 browser-data-collector: export API types
  packages/browser-data-collector/src/api/device-memory.ts
  packages/browser-data-collector/src/api/environment.ts
  packages/browser-data-collector/src/api/network-information.ts
  packages/browser-data-collector/src/collectors/blocking-resources.ts
  packages/browser-data-collector/src/collectors/device-memory.ts
  packages/browser-data-collector/src/collectors/environment.ts
  packages/browser-data-collector/src/collectors/full-page-start.ts
  packages/browser-data-collector/src/collectors/inline-start.ts
  packages/browser-data-collector/src/collectors/network-information.ts
  packages/browser-data-collector/src/collectors/page-visibility.ts
  packages/browser-data-collector/src/collectors/performance-timing.ts
  packages/browser-data-collector/src/global-types.ts
  packages/browser-data-collector/src/index.ts
  packages/browser-data-collector/src/report.ts
  packages/browser-data-collector/src/types.d.ts
  packages/browser-data-collector/src/types.ts
Labels: [Type] Enhancement, [Status] Needs Review, Packages

#91798 A4A: Introduce new mixins for consistent typography scale
  client/a8c-for-agencies/components/a4a-migration-offer/style.scss
  client/a8c-for-agencies/components/a4a-popover/style.scss
  client/a8c-for-agencies/components/filter-search/style.scss
  client/a8c-for-agencies/components/foldable-nav/style.scss
  client/a8c-for-agencies/components/form/field/style.scss
  client/a8c-for-agencies/components/form/section/style.scss
  client/a8c-for-agencies/components/form/style.scss
  client/a8c-for-agencies/components/guided-tour-step/style.scss
  client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-header/style.scss
  client/a8c-for-agencies/components/items-dashboard/items-dataviews/style.scss
  client/a8c-for-agencies/components/layout/style.scss
  client/a8c-for-agencies/components/offering/style.scss
  client/a8c-for-agencies/components/sidebar/header/style.scss
  client/a8c-for-agencies/components/sidebar/style.scss
  client/a8c-for-agencies/components/slider/style.scss
  client/a8c-for-agencies/components/user-contact-support-modal-form/style.scss
  client/a8c-for-agencies/components/user-feedback-modal-form/style.scss
  client/a8c-for-agencies/sections/marketplace/checkout/style.scss
  client/a8c-for-agencies/sections/marketplace/common/simple-list/style.scss
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-card/style.scss
  client/a8c-for-agencies/sections/marketplace/products-overview/product-card/style.scss
  client/a8c-for-agencies/sections/overview/body/intro-cards/style.scss
  client/a8c-for-agencies/sections/overview/body/next-steps/style.scss
  client/a8c-for-agencies/sections/overview/header-actions/style.scss
  client/a8c-for-agencies/style.scss
  client/assets/stylesheets/shared/mixins/_a4a-typography.scss
  client/assets/stylesheets/shared/mixins/_mixins.scss
  client/hosting/sites/components/dotcom-style.scss
  client/hosting/sites/components/style.scss
  client/my-sites/domains/domain-management/list/bulk-all-domains.tsx
  client/my-sites/plugins/plugins-navigation-header/style.scss
Labels: [Status] Needs Review, A8c Agencies, A4A

#91974 Theme Tiers: Added support for theme tiers v2 features
  client/data/themes/types.ts
  client/state/themes/hooks/use-is-theme-allowed-on-site.ts
  client/types.ts
Labels: [Status] Needs Review

#92287 Fixed an error that caused the theme showcase to be blank
  client/state/themes/hooks/use-is-theme-allowed-on-site.ts
  client/state/themes/hooks/use-theme-tier-for-theme.ts
Labels: [Status] Needs Review

#91636 Stepper: Update `migration-signup` flow to use the new login strategy
  client/landing/stepper/declarative-flow/migration-signup.ts
  client/landing/stepper/declarative-flow/test/migration-signup-flow.tsx
Labels: [Status] Needs Review

#92220 Use the correct percentage sign in translations
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/product-price-with-discount-info/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#92294 ShortcutsPopover: Only render HotkeyContainer for `i` when the panel is open
  apps/notifications/src/panel/templates/shortcuts-popover.jsx
Labels: [Status] Needs Review

#92300 Frictionless Email Subscriptions: Fix subscribe email flow new user creation
  client/signup/steps/subscribe-email/index.jsx
Labels: Frictionless Email Subscriptions

#92137 Stats: Update "billable_monthly_views" by excluding the purchased plan quantity
  client/my-sites/stats/hooks/test/test-use-available-upgrade-tiers.js
  client/my-sites/stats/hooks/use-available-upgrade-tiers.tsx
  client/my-sites/stats/hooks/use-plan-usage-query.ts
  client/my-sites/stats/hooks/use-site-compulsory-plan-selection-qualified-check.ts
Labels: Stats, [Status] Needs Review

#92238 Verbum Block Editor: Remove comment area scroll
  packages/verbum-block-editor/src/editor/editor-style.scss
Labels: [Status] Needs Review

#92276 A4A site configuration modal: Random site name and basic form validation
  client/a8c-for-agencies/sections/sites/needs-setup-sites/index.tsx
  client/a8c-for-agencies/sections/sites/needs-setup-sites/site-configurations-modal/index.tsx
  client/a8c-for-agencies/sections/sites/needs-setup-sites/site-configurations-modal/style.scss
  client/a8c-for-agencies/sections/sites/needs-setup-sites/site-configurations-modal/use-site-name.tsx
Labels: [Status] Needs Review

#92208 A4A > Marketplace: Fix the hosting card overlap issues
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-card/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-card/style.scss
Labels: [Status] Needs Review, A8c Agencies

#92268 ETK: Deprecate the hide-plugin-buttons-mobile
  apps/editing-toolkit/editing-toolkit-plugin/common/hide-plugin-buttons-mobile.js
  apps/editing-toolkit/editing-toolkit-plugin/common/hide-plugin-buttons-mobile.scss
  apps/editing-toolkit/editing-toolkit-plugin/common/index.php
  apps/editing-toolkit/package.json
Labels: [Status] Needs Review

#84811 Remove error-reporting module and loader from ETK
  apps/editing-toolkit/editing-toolkit-plugin/error-reporting/index.js
  apps/editing-toolkit/editing-toolkit-plugin/error-reporting/index.php
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
  apps/editing-toolkit/editing-toolkit-plugin/phpunit/class-errorreporting-activation-test.php
  apps/editing-toolkit/package.json
  yarn.lock
Labels: [Status] Needs Review

#92060 A4A: Add a global contact support widget.
  client/a8c-for-agencies/components/a4a-contact-support-widget/index.tsx
  client/a8c-for-agencies/components/a4a-migration-offer/index.tsx
  client/a8c-for-agencies/components/sidebar/header/profile-dropdown.tsx
  client/a8c-for-agencies/components/sidebar/index.tsx
  client/a8c-for-agencies/sections/overview/sidebar/contact-support/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#92282 Stats: Empty States: Update empty state for Authors
  client/my-sites/stats/features/modules/stats-authors/index.tsx
  client/my-sites/stats/features/modules/stats-authors/stats-authors.tsx
  client/my-sites/stats/site.jsx
Labels: Stats, [Status] Needs Review

#92194 Stats: Updating UTM module with empty states
  client/my-sites/stats/features/modules/shared/stats-empty-action-utm-builder.tsx
  client/my-sites/stats/features/modules/stats-clicks/stats-clicks.tsx
  client/my-sites/stats/features/modules/stats-countries/stats-countries.tsx
  client/my-sites/stats/features/modules/stats-referrers/stats-referrers.tsx
  client/my-sites/stats/features/modules/stats-top-posts/stats-top-posts.tsx
  client/my-sites/stats/features/modules/stats-utm/index.ts
  client/my-sites/stats/features/modules/stats-utm/stats-module-utm-dropdown.scss
  client/my-sites/stats/features/modules/stats-utm/stats-module-utm-dropdown.tsx
  client/my-sites/stats/features/modules/stats-utm/stats-module-utm-overlay.scss
  client/my-sites/stats/features/modules/stats-utm/stats-module-utm-overlay.tsx
  client/my-sites/stats/features/modules/stats-utm/stats-module-utm-wrapper.tsx
  client/my-sites/stats/features/modules/stats-utm/stats-module-utm.jsx
  client/my-sites/stats/features/modules/stats-utm/utm-export-button.jsx
  client/my-sites/stats/features/modules/types.d.ts
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-module-utm-builder/stats-module-utm-builder.tsx
  client/my-sites/stats/stats-module-utm/stats-module-utm.jsx
  client/my-sites/stats/stats-post-detail/index.jsx
  client/my-sites/stats/summary/index.jsx
Labels: Stats, [Status] Needs Review

#92281 A4A: Implement the 'Add site via A4A plugin' modal.
  client/a8c-for-agencies/components/add-new-site-button/a4a-connection-modal/index.tsx
  client/a8c-for-agencies/components/add-new-site-button/a4a-connection-modal/modal-image.png
  client/a8c-for-agencies/components/add-new-site-button/a4a-connection-modal/style.scss
  client/a8c-for-agencies/components/add-new-site-button/site-selector-and-importer.tsx
  client/a8c-for-agencies/constants/index.ts
Labels: [Status] Needs Review, A8c Agencies

#92308 Add a page modal: Hide the public library homepage category
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/class-starter-page-templates.php
Labels: [Status] Needs Review

#92307 Fix social previews for social post UI changes
  client/blocks/sharing-preview-pane/index.jsx
  client/blocks/sharing-preview-pane/utils.js
Labels: [Status] Needs Review

#92309 ETK: Add error-reporting file back as we have to remove the import first
  apps/editing-toolkit/editing-toolkit-plugin/error-reporting/index.php
Labels: [Status] Needs Review

#92310 Frictionless Email Subscriptions: Reference props for create account success callback
  client/blocks/signup-form/index.jsx
Labels: Frictionless Email Subscriptions

#92020 Plans (Storage): Migrate storage add-on slugs to AddOns data-store
  client/landing/stepper/utils/get-quantity-from-storage-slug.ts
  client/lib/signup/step-actions/index.js
  client/my-sites/plans-features-main/index.tsx
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/types.ts
  packages/data-stores/src/add-ons/constants.ts
  packages/data-stores/src/add-ons/hooks/use-add-on-feature-slugs.ts
  packages/data-stores/src/add-ons/types.ts
  packages/data-stores/src/wpcom-plans-ui/actions.ts
  packages/data-stores/src/wpcom-plans-ui/types.ts
  packages/plans-grid-next/src/components/comparison-grid/index.tsx
  packages/plans-grid-next/src/components/features-grid/index.tsx
  packages/plans-grid-next/src/components/features-grid/plan-features-list.tsx
  packages/plans-grid-next/src/components/features-grid/spotlight-plan.tsx
  packages/plans-grid-next/src/components/features-grid/table.tsx
  packages/plans-grid-next/src/components/shared/storage/components/plan-storage.tsx
  packages/plans-grid-next/src/components/shared/storage/components/storage-dropdown.tsx
  packages/plans-grid-next/src/components/shared/storage/hooks/use-available-storage-dropdown-options.ts
  packages/plans-grid-next/src/components/shared/storage/hooks/use-default-storage-option.ts
  packages/plans-grid-next/src/components/shared/storage/hooks/use-storage-string-from-feature.ts
  packages/plans-grid-next/src/types.ts
Labels: [Status] Needs Review, Storage Addon

#92188 Theme Tiers: Fix Sensei setup to work with new Tiers
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-launch/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-plan/create-sensei-site.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-plan/use-plan-selection.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/sensei-purpose/index.tsx
  packages/data-stores/src/onboard/actions.ts
Labels: [Status] Needs Review

#92224 Jetpack Backup: Hide actions toolbar in the latest backup during copy to staging flow
  client/components/jetpack/daily-backup-status/status-card/backup-successful.jsx
Labels: [Status] Needs Review, [Feature] Backups

#92290 Site Migration: Add buttons to allow users to exit the Do-it-for-me flow dead-end
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/style.scss
Labels: [Status] Needs Review

#92314 Theme Tiers: Consolidate temporary Theme Grandfathering disabling
  client/state/themes/hooks/use-is-theme-allowed-on-site.ts
  client/state/themes/hooks/use-theme-tier-for-theme.ts
Labels: [Status] Needs Review

#92227 Localize the Countries on the A4A signup form
  client/landing/stepper/hooks/use-countries.ts
Labels: [Status] Needs Review

#92297 Stats: Apply module upsell to new empty state structures
  client/my-sites/stats/features/modules/stats-clicks/stats-clicks.tsx
  client/my-sites/stats/features/modules/stats-countries/stats-countries.tsx
  client/my-sites/stats/features/modules/stats-referrers/stats-referrers.tsx
  client/my-sites/stats/features/modules/stats-top-posts/stats-top-posts.tsx
  client/my-sites/stats/stats-countries/index.jsx
Labels: Stats, [Status] Needs Review, [stats] Restricted Dashboard

#92327 Disable refs to jetpackedgephp74 and jetpackedge82 pending rename
  .teamcity/_self/projects/WPComTests.kt
  packages/calypso-e2e/src/env-variables.ts
Labels: [Status] Needs Review, Testing, TeamCity

#91881 Fix the Plan grid downgrade/upgrade buttons
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/plans-wrapper.tsx
  client/my-sites/plans-features-main/hooks/use-check-plan-availability-for-purchase.ts
  packages/data-stores/src/plans/hooks/use-pricing-meta-for-grid-plans.ts
  packages/plans-grid-next/src/hooks/data-store/use-grid-plans.tsx
Labels: [Status] Needs Review

#92334 Frictionless Email Subscriptions: Add new query params to subscribe email flow
  client/signup/config/flows-pure.js
  client/signup/hooks/use-subscribe-to-mailing-list.ts
  client/signup/steps/subscribe-email/index.jsx
Labels: [Status] Needs Review, Frictionless Email Subscriptions

#92332 Site Migration: Launch the assisted migration flow for all users
  config/production.json
Labels: [Status] Needs Review

#92336 A4A-Partner Directory: Step 1 is always check when it should display the initial state
  client/a8c-for-agencies/sections/partner-directory/components/hooks/use-form-selectors.ts
  client/a8c-for-agencies/sections/partner-directory/dashboard/index.tsx
Labels: [Status] Needs Review

#92345 Frictionless Email Subscriptions: Handle relative urls for redirect_to url query param
  client/signup/steps/subscribe-email/index.jsx
Labels: [Status] Needs Review, Frictionless Email Subscriptions

#92289 Site Migration: Add the possibility of exiting the Instructions step in the Assisted Migration flow
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/style.scss
Labels: [Status] Needs Review, [Status] String Freeze

#92346 Help Center: fix overflow when minimized
  packages/help-center/src/styles.scss
Labels: [Status] Needs Review, [Feature] Help Center

#92123 A4A-Partner Directory: Highlight invalid form fields
  client/a8c-for-agencies/components/form/field/index.tsx
  client/a8c-for-agencies/components/form/field/style.scss
  client/a8c-for-agencies/components/form/fieldset/index.tsx
  client/a8c-for-agencies/components/form/fieldset/style.scss
  client/a8c-for-agencies/sections/partner-directory/agency-details/hooks/use-details-form-validation.ts
  client/a8c-for-agencies/sections/partner-directory/agency-details/hooks/use-details-form.ts
  client/a8c-for-agencies/sections/partner-directory/agency-details/index.tsx
  client/a8c-for-agencies/sections/partner-directory/agency-expertise/hooks/use-expertise-form-validation.ts
  client/a8c-for-agencies/sections/partner-directory/agency-expertise/hooks/use-expertise-form.ts
  client/a8c-for-agencies/sections/partner-directory/agency-expertise/index.tsx
  client/a8c-for-agencies/sections/partner-directory/components/products-selector.tsx
  client/a8c-for-agencies/sections/partner-directory/utils/tools.ts
Labels: [Status] Needs Review

#92344 Show sites without title on plugins schedule updates
  client/blocks/plugins-scheduled-updates-multisite/schedule-form-sites.tsx
Labels: [Status] Needs Review

#92168 Make sure the signup flows will reach the same destination after closing the checkout.
  client/signup/config/flows.js
Labels: [Status] Needs Review

#92356 ETK Migration: Remove slide width hotfix
  apps/editing-toolkit/editing-toolkit-plugin/common/index.php
  apps/editing-toolkit/editing-toolkit-plugin/common/index.scss
Labels: [Status] Needs Review

#92169 Replace the icon of the button "close checkout" from `chevron-left` to `cross`
  client/layout/masterbar/checkout.tsx
Labels: [Status] Needs Review

#92322 Jetpack Stats: reorder Views/Visitors cards in weekly highlights
  packages/components/src/highlight-cards/weekly-highlight-cards.tsx
Labels: Stats, [Status] Needs Review, Odyssey Stats

#92357 Stats: support legacy Professional (Business) plans
  client/my-sites/stats/hooks/use-stats-purchases.tsx
Labels: Stats, [Status] Needs Review

#92354 Stats: Adding missing icons
  client/my-sites/stats/features/modules/shared/stats-empty-action-ai.tsx
  client/my-sites/stats/features/modules/stats-authors/stats-authors.tsx
  client/my-sites/stats/features/modules/stats-top-posts/stats-top-posts.tsx
  client/my-sites/stats/site.jsx
  packages/components/src/icons/block-post-author.tsx
  packages/components/src/icons/comment-content.tsx
  packages/components/src/icons/index.tsx
  packages/components/src/icons/mail.tsx
  packages/components/src/icons/sparkles.tsx
Labels: Stats, [Status] Needs Review

#92359 A4A > Migrations: Fix the payment details link in the migrations overview page
  client/a8c-for-agencies/sections/migrations/migrations-overview/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#92312 ETK: Add flag to turn off the specific feature
  apps/editing-toolkit/editing-toolkit-plugin/common/index.php
  apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/helpers.php
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
Labels: [Status] Needs Review

#92365 Frictionless Email Subscriptions: Accept wordpress subdomains as valid redirect urls
  client/lib/url/is-redirect-allowed.ts
Labels: Frictionless Email Subscriptions

#92245 Login Assistance: Update the "migrate CTA when login fails" experiment
  client/blocks/login/login-form.jsx
  client/lib/login/index.js
  client/lib/login/test/index.js
Labels: [Status] Needs Review

#92269 Plans (Pricing): Use data-store pricing for EntrepreneurPlan
  client/my-sites/plans/ecommerce-trial/entrepreneur-plan/entrepreneur-plan.tsx
Labels: [Status] Needs Review

#92209 Plans (Storage): Show total storage volume + additional cost for all plans
  packages/plans-grid-next/src/components/shared/storage/components/storage-dropdown.tsx
  packages/plans-grid-next/src/components/shared/storage/components/storage-feature-label.tsx
  packages/plans-grid-next/src/components/shared/storage/hooks/use-storage-string-from-feature.ts
Labels: [Status] Needs Review, Storage Addon

#92164 Plans (Storage): Introduce `addOnSlug` to add-ons. deprecate use of `featureSlugs` for storage
  client/my-sites/plans-features-main/hooks/use-generate-action-callback.ts
  packages/data-stores/src/add-ons/constants.ts
  packages/data-stores/src/add-ons/hooks/use-add-on-feature-slugs.ts
  packages/data-stores/src/add-ons/hooks/use-add-ons.ts
  packages/data-stores/src/add-ons/types.ts
  packages/data-stores/src/plans/hooks/use-pricing-meta-for-grid-plans.ts
  packages/plans-grid-next/src/components/actions.tsx
  packages/plans-grid-next/src/components/shared/storage/components/storage-dropdown.tsx
  packages/plans-grid-next/src/components/shared/storage/hooks/use-available-storage-dropdown-options.ts
  packages/plans-grid-next/src/components/shared/storage/hooks/use-default-storage-option.ts
Labels: [Status] Needs Review, Storage Addon

#92313 A4A > Site Selector & Importer: Implement WPCOM site selector modal
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/index.tsx
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/style.scss
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/wpcom-sites-table.tsx
  client/a8c-for-agencies/components/add-new-site-button/site-selector-and-importer.tsx
  client/a8c-for-agencies/components/add-new-site-button/style.scss
Labels: [Status] Needs Review, A8c Agencies

#92377 Fix the padding for the first tag in the Reader
  client/blocks/reader-post-card/style.scss
Labels: [Status] Needs Review

#92298 Stepper: Enable to defined extra params on the login url
  client/landing/stepper/declarative-flow/internals/types.ts
  client/landing/stepper/hooks/test/use-login-url-for-flow.tsx
  client/landing/stepper/hooks/use-login-url-for-flow.ts
  client/landing/stepper/utils/path.ts
Labels: [Status] Needs Review, Stepper

#92352 E2E: Update Revisions editor tests and removing all actions menu item check
  packages/calypso-e2e/src/lib/components/editor-settings-sidebar-component.ts
Labels: Revisions, Tests

#92381 Help page: Switch to link to youtube channel
  client/me/help/main.jsx
Labels: [Status] Needs Review

#92067 Mock WordPress.com: Move to flags
  bin/mock-wordpressdotcom.sh
  bin/welcome.js
  client/server/boot/index.js
  client/server/index.js
  package.json
  yarn.lock
Labels: [Status] Needs Review

#92296 Stepper: Update the `design-first` flow to use the new login strategy
  client/landing/stepper/declarative-flow/design-first.ts
Labels: [Status] Needs Review, Stepper

#92293 Stepper: Update the `start-writing` flow to use the new login strategy
  client/landing/stepper/declarative-flow/start-writing.ts
Labels: [Status] Needs Review, Stepper

#92292 Stepper: Update `free` flow to use the new login strategy
  client/landing/stepper/declarative-flow/free.ts
Labels: [Status] Needs Review, Stepper

#92326 Guided Onboarding: Link blog_id with survey segmentation data
  client/lib/signup/step-actions/index.js
  client/signup/config/steps-pure.js
  client/signup/steps/initial-intent/index.tsx
Labels: [Status] Needs Review, Guided Onboarding

#92277 Support cross origin URL in gridicons
  client/components/activity-card/toolbar/test/actions-button.jsx
  packages/components/src/gridicon/index.tsx
Labels: [Status] Needs Review

#92348 A4A: update referral faq footer text
  client/a8c-for-agencies/sections/referrals/primary/footer/index.tsx
Labels: [Status] Needs Review, A4A

#92379 A4A > Site Selector & Importer: Implement WPCOM site table mobile view
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/style.scss
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/wpcom-sites-table.tsx
Labels: [Status] Needs Review, A8c Agencies

#92372 A4A > Site Selector & Importer: Make the whole row clickable on the WPCOM site table
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/style.scss
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/table-content.tsx
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/wpcom-sites-table.tsx
Labels: [Status] Needs Review, A8c Agencies

#92284 Plugins: add error notice explanation for a server error
  client/my-sites/plugins/notices.jsx
  client/state/action-types.ts
  client/state/plugins/installed/actions.js
  client/state/plugins/installed/reducer.js
  client/state/plugins/installed/status/reducer.js
  client/state/plugins/installed/test/actions.js
Labels: [Status] Needs Review

#92321 Translate Odie correctly
  packages/odie-client/src/components/message/index.tsx
  packages/odie-client/src/components/message/jump-to-recent.tsx
  packages/odie-client/src/components/message/was-this-helpful-buttons.tsx
  packages/odie-client/src/components/send-message-input/index.tsx
  packages/odie-client/src/context/get-odie-initial-message.ts
  packages/odie-client/src/context/index.tsx
  packages/odie-client/src/context/use-load-previous-chat.ts
  packages/odie-client/src/data/index.ts
  packages/odie-client/src/index.tsx
  packages/odie-client/src/query/index.ts
  packages/odie-client/src/types.d.ts
  packages/odie-client/types/index.d.ts
Labels: [Status] Needs Review, [Status] String Freeze

#92303 A4A: add URL connection modal
  client/a8c-for-agencies/components/add-new-site-button/a4a-connection-modal/index.tsx
  client/a8c-for-agencies/components/add-new-site-button/a4a-connection-modal/modal-image.jpg
  client/a8c-for-agencies/components/add-new-site-button/a4a-connection-modal/modal-image.png
  client/a8c-for-agencies/components/add-new-site-button/a4a-connection-modal/style.scss
  client/a8c-for-agencies/components/add-new-site-button/jetpack-connection-modal/index.tsx
  client/a8c-for-agencies/components/add-new-site-button/jetpack-connection-modal/modal-image.jpg
  client/a8c-for-agencies/components/add-new-site-button/jetpack-connection-modal/modal-image.png
Labels: [Status] Needs Review, A4A

#92358 Stats: Refactor Insights highlight cards
  client/my-sites/stats/all-time-highlights-section/index.tsx
Labels: Stats, [Status] Needs Review

#92402 Fix migration page spacing
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/style.scss
Labels: [Status] Needs Review

#92353 Backup: Do not show in the date picker a backup that is not rewindable
  client/my-sites/backup/status/hooks.js
  client/my-sites/backup/status/test/hooks.jsx
Labels: [Status] Needs Review, [Feature] Backups

#92305 Stats: Use stats built-in API for purchases whenever possible
  apps/odyssey-stats/src/components/odyssey-query-site-purchases.ts
  apps/odyssey-stats/src/lib/get-api.ts
  client/state/sites/selectors/get-env-stats-feature-supports.ts
Labels: Stats, [Status] Needs Review

#92230 Stats: Adding skeleton loaders to stats module
  client/my-sites/stats/features/modules/shared/stats-card-skeleton.scss
  client/my-sites/stats/features/modules/shared/stats-card-skeleton.tsx
  client/my-sites/stats/features/modules/stats-authors/stats-authors.tsx
  client/my-sites/stats/features/modules/stats-clicks/stats-clicks.tsx
  client/my-sites/stats/features/modules/stats-countries/stats-countries.tsx
  client/my-sites/stats/features/modules/stats-referrers/stats-referrers.tsx
  client/my-sites/stats/features/modules/stats-top-posts/stats-top-posts.tsx
  client/my-sites/stats/features/modules/stats-utm/stats-module-utm-wrapper.tsx
  client/my-sites/stats/features/modules/stats-utm/stats-module-utm.jsx
  client/my-sites/stats/geochart/index.jsx
  client/my-sites/stats/stats-module/index.jsx
Labels: Stats, [Status] Needs Review

#92306 Remove all the feature definition data from the Trail Map experiment
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/feature-group-plan-map.ts
  packages/calypso-products/src/features-list.tsx
Labels: [Status] Needs Review

#92325 Email Stats: Fix infinite loading status when email stats request failed
  client/my-sites/stats/geochart/index.jsx
  client/my-sites/stats/stats-email-module/index.jsx
  client/state/stats/emails/reducer.js
Labels: Stats, [Status] Needs Review

#92286 Stats: Paywall date period controls and force default date range
  client/components/stats-date-control/index.tsx
  client/components/stats-date-control/stats-date-control-picker-shortcuts.tsx
  client/components/stats-date-control/stats-date-control-picker.tsx
  client/components/stats-date-control/types.d.ts
  client/my-sites/stats/hooks/use-should-gate-stats.ts
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-period-navigation/index.jsx
Labels: Stats, [Status] Needs Review, [stats] Restricted Dashboard

#92386 A4A: Fix the limitation on the calculation of unmanaged sites.
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/hooks/use-managed-sites-map.ts
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/style.scss
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/wpcom-sites-table.tsx
Labels: [Status] Needs Review, A8c Agencies

#92417 A4A: Address design feedback on site creation configuration.
  client/a8c-for-agencies/sections/sites/needs-setup-sites/site-configurations-modal/index.tsx
  client/a8c-for-agencies/sections/sites/needs-setup-sites/site-configurations-modal/style.scss
Labels: [Status] Needs Review

#92317 A4A: Add Site remove functionality.
  client/a8c-for-agencies/data/sites/use-remove-site.ts
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-sites-dataviews.tsx
  client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
  client/a8c-for-agencies/sections/sites/sites-dataviews/interfaces.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-actions/get-action-event-name.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-actions/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-actions/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-actions/test/site-actions.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-actions/use-site-actions.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-card/test/site-card.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-remove-confirmation-dialog/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-remove-confirmation-dialog/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-table-row/test/site-table-row.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/types.ts
Labels: [Status] Needs Review, A8c Agencies

#92147 Add migration sticker and unify the loading experience for the upgrade plan step
  client/blocks/importer/wordpress/import-everything/pre-migration/test/index.test.tsx
  client/blocks/importer/wordpress/upgrade-plan/skeleton/index.tsx
  client/blocks/importer/wordpress/upgrade-plan/skeleton/style.scss
  client/blocks/importer/wordpress/upgrade-plan/style.scss
  client/blocks/importer/wordpress/upgrade-plan/test/upgrade-plan-details.tsx
  client/blocks/importer/wordpress/upgrade-plan/types.ts
  client/blocks/importer/wordpress/upgrade-plan/upgrade-plan-details.tsx
  client/blocks/importer/wordpress/upgrade-plan/upgrade-plan-hosting-details.tsx
  client/blocks/importer/wordpress/upgrade-plan/use-default-hosting-details.tsx
  client/blocks/importer/wordpress/upgrade-plan/with-migration-sticker.tsx
  client/data/site-migration/use-migration-sticker.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-upgrade-plan/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/test/helpers/index.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#92431 A4A > Partner Directory: Update BU Directory URL links
  client/a8c-for-agencies/sections/partner-directory/dashboard/index.tsx
  client/a8c-for-agencies/sections/partner-directory/lib/get-brand-meta.tsx
Labels: [Status] Needs Review

#92315 Plugins: Remove Domain-Only Sites from Site List
  client/my-sites/plugins/manage-site-plugins-dialog/index.jsx
Labels: [Status] Needs Review, OSS Citizen

#92440 Revert "Fix ReactDOM.render is no longer supported"
  client/landing/stepper/index.tsx
Labels: [Status] Needs Review

#92441 Track clicks to 'Compare all plans' button
  client/my-sites/plans-features-main/index.tsx
Labels: [Status] Needs Review

#92190 Domains: Show more informative message when trying to transfer an unsupported premium domain
  client/components/domains/use-my-domain/utilities/get-availability-error-message.js
  client/landing/stepper/hooks/use-is-domain-code-valid.ts
  client/lib/domains/registration/availability-messages.js
  packages/urls/src/index.ts
Labels: [Status] Needs Review

#92420 Plugin Details: Pass all sites to the notice component
  client/my-sites/plugins/plugin-details.jsx
Labels: [Status] Needs Review

#92423 Jetpack Cloud: Fix access to cloud for sites with VaultPress Backup standalone plugin
  client/state/sites/actions.js
Labels: [Status] Needs Review

#92279 Support: Open help search links in Help Center
  client/blocks/inline-help/inline-help-search-results.jsx
  packages/data-stores/src/help-center/actions.ts
Labels: [Status] Needs Review

#92457 Help Center: Simplify passing information to Zendesk Messaging chat
  packages/help-center/src/components/help-center-contact-page.tsx
  packages/help-center/src/hooks/use-chat-widget.ts
Labels: [Status] Needs Review

#92360 Stats: Add locking to Insights highlights
  client/my-sites/stats/all-time-highlights-section/index.tsx
  client/my-sites/stats/all-time-highlights-section/style.scss
  client/my-sites/stats/hooks/use-should-gate-stats.ts
Labels: Stats, [Status] Needs Review

#92427 Integrate the refer-a-friend eligibility check
  client/my-sites/earn/home.tsx
  client/my-sites/earn/main.tsx
  client/my-sites/earn/refer-a-friend/index.tsx
  client/my-sites/earn/refer-a-friend/style.scss
Labels: [Status] Needs Review

#92451 Stats: Paywall Stats Insights modules
  client/my-sites/stats/hooks/use-should-gate-stats.ts
  client/my-sites/stats/stats-comments/index.jsx
Labels: Stats, [Status] Needs Review, [Stats] Restricted Dashboard

#92362 A4A > Referrals: Update pricing text for purchases
  client/a8c-for-agencies/sections/referrals/referral-details/components/total-amount.tsx
Labels: [Status] Needs Review, A8c Agencies

#92366 A4A > Referrals: Show recent referrals on top of the referral table
  client/a8c-for-agencies/sections/referrals/consolidated-view/index.tsx
  client/a8c-for-agencies/sections/referrals/hooks/use-fetch-referrals.ts
  client/a8c-for-agencies/sections/referrals/types.ts
Labels: [Status] Needs Review, A8c Agencies

#92466 Stats: Optimize moment.js timezone dependency
  apps/odyssey-stats/src/lib/set-locale.ts
Labels: Stats, [Status] Needs Review

#92367 A4A > Referrals: Update client subscriptions price text
  client/a8c-for-agencies/sections/client/primary/subscriptions-list/field-content.tsx
Labels: [Status] Needs Review, A8c Agencies

#92460 Stats: Paywall Insights page AllTimeViewsSection
  client/my-sites/stats/all-time-views-section/index.tsx
  client/my-sites/stats/all-time-views-section/style.scss
  client/my-sites/stats/constants.ts
  client/my-sites/stats/hooks/use-should-gate-stats.ts
  client/my-sites/stats/stats-card-upsell/index.tsx
  client/my-sites/stats/stats-card-upsell/stats-card-upsell-overlay.tsx
Labels: Stats, [Status] Needs Review, [Stats] Restricted Dashboard

#92444 A4A: Remove add site via URL option in the Site selector dropdown menu.
  client/a8c-for-agencies/components/add-new-site-button/site-selector-and-importer.tsx
Labels: [Status] Needs Review, A8c Agencies

#92445 A4A: Provide source context when redirecting the user to the Jetpack connection flow.
  client/a8c-for-agencies/components/add-new-site-button/jetpack-connection-modal/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#92446 A4A: Add a hover state on the Site selector menu items.
  client/a8c-for-agencies/components/add-new-site-button/style.scss
Labels: [Status] Needs Review, A8c Agencies

#92438 A4A: Implement Import WPCOM sites CTA functionality.
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/index.tsx
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/wpcom-sites-table.tsx
  client/a8c-for-agencies/components/add-new-site-button/index.tsx
  client/a8c-for-agencies/components/add-new-site-button/site-selector-and-importer.tsx
  client/a8c-for-agencies/data/sites/use-import-wpcom-site.ts
  client/a8c-for-agencies/data/sites/use-import-wpcom-sites.ts
  client/a8c-for-agencies/sections/sites/add-sites/add-sites-from-wpcom.tsx
  client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
  client/a8c-for-agencies/sections/sites/sites-header-actions/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#92473 A4A > Site Selector & Importer: Fix the WPCOM add site modal in small screens
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/style.scss
Labels: [Status] Needs Review, A8c Agencies

#92429 Scheduled Updates: Optimistically update schedules list on add/delete action
  client/blocks/plugins-scheduled-updates-multisite/schedule-form.tsx
  client/blocks/plugins-scheduled-updates-multisite/schedule-list.tsx
  client/data/plugins/use-update-schedules-mutation.ts
Labels: [Status] Needs Review

#92363 ETK: Remove disable-heic-images
  apps/editing-toolkit/editing-toolkit-plugin/common/disable-heic-images.js
  apps/editing-toolkit/editing-toolkit-plugin/common/index.php
  apps/editing-toolkit/package.json
Labels: [Status] Needs Review

#92471 A4A: Site selector and importer UI/UX improvements.
  client/a8c-for-agencies/components/a4a-themed-modal/index.tsx
  client/a8c-for-agencies/components/a4a-themed-modal/style.scss
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/hooks/use-managed-sites-map.ts
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/index.tsx
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/style.scss
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/table-placeholder.tsx
  client/a8c-for-agencies/components/add-new-site-button/import-from-wpcom-modal/wpcom-sites-table.tsx
  client/a8c-for-agencies/components/text-placeholder/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-actions/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#92448 A4A: Enhance connection modals triggering action with Enter
  client/a8c-for-agencies/components/add-new-site-button/a4a-connection-modal/index.tsx
  client/a8c-for-agencies/components/add-new-site-button/jetpack-connection-modal/index.tsx
Labels: [Status] Needs Review, A4A

#92311 Pricing Meta: use sitePlans if siteId is available
  packages/data-stores/src/plans/constants.ts
  packages/data-stores/src/plans/hooks/test/use-pricing-meta-for-grid-plans.ts
  packages/data-stores/src/plans/hooks/use-pricing-meta-for-grid-plans.ts
  packages/data-stores/src/plans/queries/lib/unpack-cost-overrides.ts
  packages/data-stores/src/plans/queries/use-site-plans.ts
  packages/data-stores/src/plans/types.ts
  packages/plans-grid-next/src/components/header-price.tsx
Labels: [Status] Needs Review

#92482 Whats New: Add the app to Team City build
  .teamcity/_self/projects/WPComPlugins.kt
  apps/whats-new/package.json
Labels: [Status] Needs Review

#92384 Rotate unlock string for GB unstable APIs in Calypso apps v18.7.0
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/block-editor-nux.js
  apps/wpcom-block-editor/src/wpcom/features/live-preview/utils.ts
  apps/wpcom-block-editor/src/wpcom/features/tracking/site-editor-load.tsx
  packages/block-renderer/src/components/block-renderer-container.tsx
  packages/global-styles/src/gutenberg-bridge/index.tsx
Labels: [Status] Needs Review

#92480 A4A: Enable Site selector and importer feature in staging.
  config/a8c-for-agencies-stage.json
Labels: [Status] Needs Review, A8c Agencies

#91956 SignupForm: remove legacy code for handling back button
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/passwordless.jsx
  client/blocks/signup-form/signup-form-social-first.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/user/index.tsx
  client/signup/config/flows.js
  client/signup/steps/user/index.jsx
Labels: [Status] Needs Review, [Type] Janitorial

#92342 Global sidebar - show scroll bar in body
  client/layout/global-sidebar/style.scss
Labels: [Status] Needs Review

#92481 A4A: Enable Site selector and importer feature in production.
  config/a8c-for-agencies-production.json
Labels: [Status] Needs Review, A8c Agencies

#92351 Allow translators to localize the date format
  client/a8c-for-agencies/sections/purchases/billing/billing-summary/index.tsx
Labels: [Status] Needs Review, i18n, [Status] String Freeze

#92295 Stepper: Update `assembler-first` flow to use the new login strategy
  client/landing/stepper/declarative-flow/assembler-first-flow.ts
Labels: [Status] Needs Review, Stepper

#92340 Stepper: Update `newsletter` flow to use the new login strategy
  client/landing/stepper/declarative-flow/newsletter.ts
Labels: [Status] Needs Review, Stepper

#92329 Stepper: Update `import-hosted-site` flow to use the new login strategy
  client/landing/stepper/declarative-flow/import-hosted-site.ts
Labels: [Status] Needs Review, Stepper

#92335 Stepper: Update `hundred-year-plan` flow to use the new login strategy
  client/landing/stepper/declarative-flow/hundred-year-plan.ts
Labels: [Status] Needs Review, Stepper

#92330 Stepper: Update `link-in-bio-tld` flow to use the new login strategy
  client/landing/stepper/declarative-flow/link-in-bio-tld.ts
Labels: [Status] Needs Review, Stepper
