Repository Automattic/wp-calypso, pull requests merged in 2024-08, with the labels that each got.

#93048 Stats: Empty state for the page chart
  client/my-sites/stats/stats-empty-state/index.tsx
  client/my-sites/stats/stats-empty-state/style.scss
  client/my-sites/stats/stats-summary/index.jsx
Labels: Stats, [Status] Needs Review

#93123 Stats: Adding empty states for summary pages
  client/my-sites/stats/features/modules/stats-authors/stats-authors.tsx
  client/my-sites/stats/features/modules/stats-clicks/stats-clicks.tsx
  client/my-sites/stats/features/modules/stats-countries/stats-countries.tsx
  client/my-sites/stats/features/modules/stats-downloads/stats-downloads.tsx
  client/my-sites/stats/features/modules/stats-referrers/stats-referrers.tsx
  client/my-sites/stats/features/modules/stats-search/stats-search.tsx
  client/my-sites/stats/features/modules/stats-top-posts/stats-top-posts.tsx
  client/my-sites/stats/features/modules/types.d.ts
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-download-csv/index.jsx
  client/my-sites/stats/stats-module/index.jsx
  client/my-sites/stats/summary/index.jsx
Labels: Stats, [Status] Needs Review

#93142 A4A: Update Hosting page v2 to use the existing Hosting URL scheme.
  client/a8c-for-agencies/sections/marketplace/controller.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/index.tsx
  client/a8c-for-agencies/sections/marketplace/lib/hosting.tsx
Labels: [Status] Needs Review, A8c Agencies

#93073 feat(hosting-overview-refinements): render actual copy and hide activate button on hosting-features tab
  client/hosting-features/components/hosting-features.tsx
  client/state/atomic-transfer/constants.js
Labels: [Status] Needs Review

#93075 fix(hosting-overview-refinements): move hosting-features component to more appropriate place
  client/hosting/hosting-features/components/hosting-features-icon.jsx
  client/hosting/hosting-features/components/hosting-features.tsx
  client/hosting/hosting-features/components/style.scss
  client/hosting/hosting-features/controller.tsx
  client/hosting/hosting-features/index.tsx
  client/hosting/sites/components/site-preview-pane/dotcom-preview-pane.tsx
  client/sections.js
Labels: [Status] Needs Review

#93124 Masterbar: Update icon dot size and placement
  client/layout/masterbar/masterbar-cart/masterbar-cart-icon.tsx
  client/layout/masterbar/style.scss
Labels: [Status] Needs Review

#93182 Notifications: remove usage of ReactDOM.findDOMNode
  apps/notifications/src/panel/templates/note-list.jsx
Labels: [Status] Needs Review, [Type] Janitorial

#93181 Support: Change link to help
  apps/happy-blocks/block-library/support-content-links/index.php
Labels: [Status] Needs Review

#93078 feat(hosting-overview-refinements): add Site Visits block to Hosting Overview page
  client/hosting-overview/components/plan-card.tsx
  client/hosting-overview/components/plan-site-visits.tsx
Labels: [Status] Needs Review

#93110 Global nav i4 - add selected global tab styles
  client/layout/masterbar/item.tsx
  client/layout/masterbar/logged-in.jsx
  client/layout/masterbar/style.scss
  client/my-sites/sidebar/style.scss
Labels: [Status] Needs Review

#93079 feat(hosting-overview-refinements): add Bandwidth block to Hosting Overview page
  client/hosting-overview/components/plan-bandwidth.tsx
  client/hosting-overview/components/plan-card.tsx
Labels: [Status] Needs Review

#93172 Fix /themes sidebar between 600px & 780px
  client/my-sites/themes/theme-showcase.scss
Labels: [Status] Needs Review

#92980 e2e: Skip image compare block on private sites
  test/e2e/specs/blocks/blocks__jetpack-media.ts
Labels: [Type] Bug, [Pri] Normal, [Status] Needs Review

#93187 Fix domains table actions on site overview
  client/blocks/site-address-changer/index.jsx
  client/hosting-overview/components/active-domains-card.tsx
  client/my-sites/domains/domain-management/list/bulk-site-domains.tsx
  packages/domains-table/src/domains-table/domains-table-row-actions.tsx
Labels: [Status] Ready to Merge

#93180 Stepper: Add stepper team to review stepper changes
  .github/CODEOWNERS
Labels: [Status] Needs Review

#93084 Monetize: fix issue preventing JPY payment plans
  client/my-sites/earn/components/add-edit-plan-modal/index.tsx
Labels: [Status] Needs Review

#93147 Site Migration: Refresh jetpack connection when the plugin list is not available
  client/landing/stepper/hooks/test/use-plugin-auto-installation.tsx
  client/landing/stepper/hooks/use-plugin-auto-installation.ts
Labels: [Status] Needs Review

#92912 Site Migration: Only show site picker if there are sites to show.
  client/landing/stepper/declarative-flow/internals/steps-repository/site-picker/index.tsx
Labels: [Status] Needs Review, [Feature] Site Migration

#93191 fix(hosting-overview-refinements): move Overview component to more appropriate place
  client/hosting/overview/components/active-domains-card.tsx
  client/hosting/overview/components/hosting-overview.tsx
  client/hosting/overview/components/plan-bandwidth.tsx
  client/hosting/overview/components/plan-card.tsx
  client/hosting/overview/components/plan-site-visits.tsx
  client/hosting/overview/components/plan-storage-bar.tsx
  client/hosting/overview/components/quick-actions-card.tsx
  client/hosting/overview/components/site-backup-card/index.js
  client/hosting/overview/components/site-backup-card/style.scss
  client/hosting/overview/components/style.scss
  client/hosting/overview/controller.tsx
  client/hosting/overview/index.tsx
  client/sections.js
Labels: [Status] Needs Review

#93185 Masterbar: Fix layout at 782px
  client/layout/masterbar/style.scss
Labels: [Status] Needs Review

#93197 A4A: update migration incentive end date
  client/a8c-for-agencies/components/a4a-migration-offer-v2/index.tsx
  client/a8c-for-agencies/components/a4a-migration-offer/index.tsx
  client/a8c-for-agencies/sections/migrations/migrations-overview/index.tsx
Labels: [Status] Needs Review

#93175 Stats: Updating Emails component on the Subscribers page
  client/my-sites/stats/pages/subscribers/index.tsx
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-module-emails/index.jsx
Labels: Stats, [Status] Needs Review

#92015 Fix: Non-owner site buttons display
  client/my-sites/plans-features-main/hooks/test/use-check-plan-availability-for-purchase.ts
  client/my-sites/plans-features-main/hooks/test/use-generate-action-hook.ts
  client/my-sites/plans-features-main/hooks/use-check-plan-availability-for-purchase.ts
  client/my-sites/plans-features-main/hooks/use-generate-action-callback.ts
  client/my-sites/plans-features-main/hooks/use-generate-action-hook.tsx
  client/my-sites/plans-features-main/hooks/use-non-owner-handler.ts
  client/state/selectors/can-upgrade-to-plan.js
  packages/data-stores/src/help-center/actions.ts
  packages/data-stores/src/help-center/reducer.ts
  packages/data-stores/src/help-center/selectors.ts
  packages/data-stores/src/plans/hooks/use-pricing-meta-for-grid-plans.ts
  packages/data-stores/src/purchases/queries/use-site-purchases.ts
  packages/data-stores/src/site/index.ts
  packages/data-stores/src/site/queries/lib/use-query-keys-factory.ts
  packages/data-stores/src/site/queries/use-site-user-query.ts
  packages/help-center/src/components/help-center-content.tsx
  packages/odie-client/src/components/message/index.tsx
  packages/odie-client/src/context/get-odie-initial-message.ts
  packages/odie-client/src/context/index.tsx
  packages/odie-client/src/context/use-load-previous-chat.ts
  packages/odie-client/src/index.tsx
  packages/odie-client/src/types/index.ts
  packages/odie-client/src/utils/is-odie-allowed-bot.ts
  packages/plans-grid-next/src/components/actions.tsx
  packages/plans-grid-next/src/components/plan-button/style.scss
  packages/plans-grid-next/src/hooks/data-store/use-grid-plans.tsx
  packages/plans-grid-next/src/types.ts
Labels: [Status] Needs Review

#92926 A4A: Update Guide Modal styling to allow vertical expansion
  client/a8c-for-agencies/components/guide-modal/style.scss
Labels: [Status] Needs Review, i18n, A4A

#93203 A4A > Marketplace: Add hosting page track events
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/enterprise-agency-hosting/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/details.tsx
Labels: [Status] Needs Review, A8c Agencies

#93100 Stepper: Backbone for tracking step navigation at framework level
  client/landing/stepper/declarative-flow/internals/hooks/use-step-navigation-with-tracking/index.ts
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/types.ts
  client/landing/stepper/declarative-flow/newsletter.ts
Labels: [Status] Needs Review, Stepper

#92970 Plans (State): Remove unused IntroOffers selectors from Calypso state (`getBestIntroOfferDiscount`, `getIntroOfferIsEligible`)
  client/state/selectors/get-best-intro-offer-discount.ts
  client/state/selectors/get-intro-offer-is-eligible.ts
Labels: [Status] Needs Review

#93136 Stepper: Update `newsletter` flow to use framework tracking for step-submit
  client/landing/stepper/declarative-flow/internals/hooks/use-step-navigation-with-tracking/index.ts
  client/landing/stepper/declarative-flow/newsletter.ts
  packages/data-stores/src/onboard/constants.ts
Labels: [Status] Needs Review, Stepper

#93145 [Odie] Wapuu scroll rework
  packages/help-center/src/components/help-center-content.tsx
  packages/help-center/src/styles.scss
  packages/odie-client/src/components/message/dislike-feedback-message.tsx
  packages/odie-client/src/components/message/error-message.tsx
  packages/odie-client/src/components/message/index.tsx
  packages/odie-client/src/components/message/jump-to-recent.tsx
  packages/odie-client/src/components/message/message-content.tsx
  packages/odie-client/src/components/message/messages-container.tsx
  packages/odie-client/src/components/message/sources.tsx
  packages/odie-client/src/components/message/style.scss
  packages/odie-client/src/components/message/user-message.tsx
  packages/odie-client/src/components/message/was-this-helpful-buttons.tsx
  packages/odie-client/src/components/send-message-input/index.tsx
  packages/odie-client/src/context/index.tsx
  packages/odie-client/src/context/use-load-previous-chat.ts
  packages/odie-client/src/index.tsx
  packages/odie-client/src/query/index.ts
  packages/odie-client/src/style.scss
  packages/odie-client/src/useAutoScroll.ts
  packages/odie-client/src/useLastMessageVisibility.ts
Labels: [Status] Needs Review

#93186 A4A Dev Sites: Add `Development` badge for free development sites
  client/a8c-for-agencies/sections/sites/sites-dashboard/sites-dataviews-style.scss
  client/a8c-for-agencies/sections/sites/sites-dataviews/site-data-field.tsx
Labels: [Status] Needs Review

#93176 A4A > Marketplace: Hosting page UI enhancements
  client/a8c-for-agencies/components/a4a-migration-offer-v2/style.scss
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/premier-agency-hosting/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/premier-agency-hosting/style.scss
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/standard-agency-hosting/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/standard-agency-hosting/wpcom-plan-selector/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/style.scss
  client/a8c-for-agencies/sections/marketplace/hosting-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/details.tsx
  client/assets/images/a8c-for-agencies/hosting/premier-testimonial-2.png
  client/assets/images/a8c-for-agencies/hosting/standard-testimonial-1.png
  client/assets/images/a8c-for-agencies/hosting/standard-testimonial-2.png
Labels: [Status] Needs Review, A8c Agencies

#93179 Stepper: Track flow starting point
  client/landing/stepper/declarative-flow/internals/analytics/record-flow-start.ts
  client/landing/stepper/declarative-flow/internals/hooks/use-flow-analytics/index.tsx
  client/landing/stepper/declarative-flow/internals/hooks/use-flow-analytics/test/index.tsx
  client/landing/stepper/declarative-flow/internals/index.tsx
Labels: [Status] Needs Review, Stepper

#93143 A4A > Partner Directory: Redirection to overview if the agency data is not already fetched
  client/a8c-for-agencies/sections/partner-directory/index.tsx
  client/a8c-for-agencies/sections/partner-directory/partner-directory.tsx
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-horizon.json
Labels: [Status] Needs Review

#93156 Help center: update styles to work on front end of site
  packages/help-center/src/components/help-center-search.scss
  packages/help-center/src/styles.scss
Labels: [Status] Needs Review

#93158 Update: Pass fromSite URL to the Substack importer
  client/my-sites/importer/file-importer.jsx
  client/my-sites/importer/importer-substack.jsx
  client/my-sites/importer/newsletter/content.tsx
  client/my-sites/importer/newsletter/importer.tsx
  client/my-sites/importer/newsletter/select-newsletter-form.tsx
  client/my-sites/importer/newsletter/subscribers.tsx
  client/my-sites/importer/section-import.jsx
  client/my-sites/importer/uploading-pane.jsx
Labels: [Status] Needs Review, Import

#93194 Masterbar: Use hover background color for dot stroke on hover
  client/layout/masterbar/style.scss
Labels: [Status] Needs Review

#93196 Help Center: Fix `navigateToRoute`
  packages/data-stores/src/help-center/actions.ts
  packages/help-center/src/components/help-center-article.tsx
  packages/help-center/src/components/help-center-container.tsx
  packages/help-center/src/components/help-center-content.tsx
Labels: [Status] Needs Review, [Feature] Help Center

#93192 Pricing: Align the Feature Grid With Our Marketing Pages
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/feature-group-plan-map.ts
  packages/calypso-products/src/features-list.tsx
  packages/calypso-products/src/plans-list.tsx
  packages/components/src/client-logo-list/client-list.tsx
  packages/components/src/client-logo-list/index.tsx
  packages/components/src/client-logo-list/style.scss
  packages/components/src/index.ts
  packages/plans-grid-next/src/components/features-grid/enterprise-features.tsx
  packages/plans-grid-next/src/components/features-grid/index.tsx
  packages/plans-grid-next/src/components/features-grid/partner-logos.tsx
  packages/plans-grid-next/src/components/features-grid/style.scss
  packages/plans-grid-next/src/components/features-grid/table.tsx
Labels: [Status] String Freeze

#93213 Masterbar: Fix RTL border first/last item + external border
  client/layout/masterbar/style.scss
Labels: [Status] Needs Review

#93212 [Odie] Add new contact flow for free users using Wapuu
  packages/help-center/src/components/help-center-contact-page.tsx
  packages/help-center/src/components/help-center-content.tsx
  packages/help-center/src/components/help-center-extra-contact-option.tsx
  packages/help-center/src/components/utils.tsx
  packages/odie-client/src/components/message/direct-escalation-link.tsx
  packages/odie-client/src/components/message/user-message.tsx
  packages/odie-client/src/context/index.tsx
Labels: [Status] Needs Review

#93198 Paid Importer: Add Stripe connection flow
  client/assets/images/jetpack/stripe-logo-white.svg
  client/my-sites/importer/newsletter/connect-stripe.tsx
  client/my-sites/importer/newsletter/importer.scss
  client/my-sites/importer/newsletter/importer.tsx
  client/my-sites/importer/newsletter/paid-subscribers.tsx
Labels: [Status] Needs Review

#93002 Help: Open /help links in Help Center
  client/me/developer/features/index.tsx
  client/me/help/help-results/help-result-item.tsx
  client/me/help/help-results/index.jsx
  client/me/help/help-results/item.jsx
  client/me/help/help-search/index.jsx
  client/me/help/main.jsx
  packages/data-stores/src/help-center/actions.ts
  packages/help-center/src/hooks/index.ts
  packages/help-center/src/hooks/use-open-article-in-help-center.ts
Labels: [Status] Needs Review, Help, [Feature] Help Center

#92884 Stats: Fix commercial upgrade notice display logic
  client/my-sites/stats/stats-notices/all-notice-definitions.ts
  client/my-sites/stats/stats-notices/index.tsx
Labels: Stats, [Status] Needs Review

#93216 Odyssey Stats: Fix the view all link of Subscriber Stats
  client/my-sites/stats/stats-subscribers-chart-section/index.tsx
Labels: Stats, [Status] Needs Review, Odyssey Stats, [Stats] Subscribers

#93233 Reader follow: Fix the fatal error because the feed is undefined
  client/blocks/reader-feed-header/follow.jsx
Labels: [Status] Needs Review

#93199 Stats: Updating file structure and removing old code
  client/my-sites/stats/features/modules/all-time-views-section/all-time-views-section.tsx
  client/my-sites/stats/features/modules/all-time-views-section/index.ts
  client/my-sites/stats/features/modules/stats-comments/stats-comments.tsx
  client/my-sites/stats/features/modules/stats-comments/styles.scss
  client/my-sites/stats/features/modules/stats-countries/stats-countries.tsx
  client/my-sites/stats/features/modules/stats-countries/style.scss
  client/my-sites/stats/features/modules/stats-shares/index.ts
  client/my-sites/stats/features/modules/stats-shares/stats-shares.tsx
  client/my-sites/stats/pages/insights/index.jsx
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-comments/index.jsx
  client/my-sites/stats/stats-countries/index.jsx
Labels: Stats, [Status] Needs Review

#92901 Rename plans to Personal / Premium / Business / Commerce
  apps/happy-blocks/block-library/pricing-plans/hooks/pricing-plans.ts
  client/components/theme-tier/theme-tier-badge/test/theme-tier-style-variation-badge.js
  client/controller/index.web.js
  client/my-sites/hosting/test/index.js
  packages/calypso-products/src/plans.tsx
  packages/data-stores/src/plans/constants.ts
  packages/data-stores/src/plans/mock/apis/plans.ts
  packages/data-stores/src/plans/mock/store/plans.ts
  packages/data-stores/src/plans/mock/store/products.ts
  packages/data-stores/src/plans/queries/use-plans.ts
  packages/data-stores/src/plans/test/selectors.ts
  test/e2e/specs/domain-upsell/domain-upsell__sidebar.ts
  test/e2e/specs/onboarding/lifecycle__signup-onboarding-launch-cancel.ts
  test/e2e/specs/onboarding/signup__with-theme-LOHP.ts
  test/e2e/specs/onboarding/signup__with-theme-premium.ts
  test/e2e/specs/plans/plans__signup-business.ts
  test/e2e/specs/plans/plans__upgrade.ts
  test/e2e/specs/shared/get-new-plan-name.ts
  test/e2e/specs/shared/index.ts
Labels: [Status] Needs Review

#93174 Replace VideoPress upsell with plan upsell in the 'Videos' status module
  client/my-sites/stats/hooks/use-should-gate-stats.ts
  client/my-sites/stats/stats-card-upsell/stats-card-upsell-wpcom.tsx
Labels: [Status] Needs Review

#93237 Provide a fallback for the plan upgrade copy
  client/my-sites/stats/stats-card-upsell/stats-card-upsell-wpcom.tsx
Labels: [Status] Needs Review

#92827 Notifications: Update filter items on i18n data changes
  apps/notifications/src/panel/templates/filter-bar.jsx
Labels: [Type] Bug, [Status] Needs Review, i18n

#92821 Site Logs: Localize Severity table column
  client/my-sites/site-monitoring/components/site-logs-table/index.tsx
  client/my-sites/site-monitoring/components/site-logs-table/site-logs-table-row.tsx
Labels: [Type] Bug, [Status] Needs Review, i18n

#93193 A4A Dev Sites: Add site configuration modal
  client/a8c-for-agencies/components/add-new-site-button/index.tsx
  client/a8c-for-agencies/components/site-configurations-modal/index.tsx
  client/a8c-for-agencies/components/site-configurations-modal/style.scss
  client/a8c-for-agencies/components/site-configurations-modal/use-random-site-name.tsx
  client/a8c-for-agencies/components/site-configurations-modal/use-site-name.tsx
  client/a8c-for-agencies/sections/sites/needs-setup-sites/index.tsx
  client/a8c-for-agencies/sections/sites/sites-header-actions/index.tsx
Labels: [Status] Needs Review

#93236 A4A > Marketplace: Add Standard agency hosting testimonial
  client/a8c-for-agencies/sections/marketplace/common/hosting-testimonials-section/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/premier-agency-hosting/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/standard-agency-hosting/index.tsx
  client/assets/images/a8c-for-agencies/hosting/standard-testimonial-1.png
Labels: [Status] Needs Review, A8c Agencies

#93222 [Odie] Force navigation for non elegible users to forums
  packages/help-center/src/components/help-center-content.tsx
Labels: [Status] Needs Review

#93218 Update Promote Post translations
  client/lib/promote-post/string.ts
Labels: [Status] Needs Review

#93224 Adds a new variable to the promote post widget
  client/components/blazepress-widget/index.tsx
  client/lib/promote-post/index.ts
  packages/data-stores/src/site/types.ts
Labels: [Status] Needs Review

#93133 Gravatar: Allow Gravatar related OAuth2 clients to use the Gravatar login flow
  client/blocks/login/index.jsx
  client/components/data/document-head/index.jsx
  client/components/gravatar-login-logo/index.tsx
  client/components/gravatar-login-logo/style.scss
  client/document/index.jsx
  client/layout/logged-out.jsx
  client/lib/get-gravatar-oauth2-flow.js
  client/lib/login/index.js
  client/lib/oauth2-clients.js
  client/lib/paths/login/index.js
  client/login/controller.js
  client/login/magic-login/handle-emailed-link-form.jsx
  client/login/magic-login/index.jsx
  client/login/magic-login/request-login-email-form.jsx
  client/login/magic-login/style.scss
  client/login/wp-login/index.jsx
  client/state/oauth2-clients/reducer.js
  client/state/oauth2-clients/selectors.js
Labels: [Status] Needs Review, Login

#92304 Frictionless Email Subscriptions: Enable email subscription flow in production
  config/production.json
Labels: [Status] Needs Review, Frictionless Email Subscriptions

#93245 Newsletter settings: move "." to be part of setting label
  client/my-sites/site-settings/settings-newsletter/SubscribeModalSetting.tsx
  client/my-sites/site-settings/settings-newsletter/SubscribeOverlaySetting.tsx
  client/my-sites/site-settings/settings-newsletter/SubscribePostEndSetting.tsx
Labels: [Status] Needs Review, i18n, Newsletters

#93195 Fix Logged out reader masterbar broken items
  client/layout/logged-out.jsx
  client/layout/masterbar/logged-out.jsx
  client/layout/masterbar/style.scss
Labels: [Status] Needs Review

#93257 Frictionless Email Subscriptions: Update subscribe email flow page load logic
  client/signup/steps/subscribe-email/content.jsx
  client/signup/steps/subscribe-email/index.jsx
Labels: Frictionless Email Subscriptions

#93261 Masterbar: Use inline WordPress SVG logo
  client/layout/masterbar/logged-in.jsx
Labels: [Status] Needs Review

#93264 Stats: fix search and stats in my plan
  packages/calypso-products/src/translations.tsx
  packages/components/src/product-icon/config.ts
Labels: Stats, [Status] Needs Review

#92581 ETK Migration: Remove Block Editor Nav Sidebar
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/class-wpcom-block-editor-nav-sidebar.php
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/index.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/actions.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/attach-sidebar.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-item/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-item/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/index.tsx
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/style.scss
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/constants.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/global.d.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/store.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/test/attach-sidebar.test.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/types.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/wp-edit-post-types.d.ts
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.tsx
  apps/editing-toolkit/package.json
  apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
  apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-close-click.js
Labels: [Status] Needs Review

#93247 Help Center: Action hook to open home
  apps/happy-blocks/block-library/support-content-links/index.php
  packages/help-center/src/hooks/use-action-hooks.ts
Labels: [Status] Needs Review

#93223 feat(hosting-overview-refinements): render WP and PHP versions on Hosting-Overview page
  client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-header/index.tsx
  client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-header/style.scss
  client/my-sites/hosting/main.js
  client/my-sites/hosting/web-server-settings-card/index.js
Labels: [Status] Needs Review

#92794 Scroll the page to the RMT section when clicking back in details and update copy
  client/my-sites/patterns/components/pattern-library/index.tsx
  client/my-sites/patterns/components/readymade-template-details/index.tsx
  client/my-sites/patterns/components/readymade-template-details/style.scss
  client/my-sites/patterns/components/readymade-templates/client.tsx
  client/my-sites/patterns/components/readymade-templates/section.tsx
  client/my-sites/patterns/components/section/index.tsx
  client/my-sites/patterns/context.ts
  client/my-sites/patterns/index.node.tsx
  client/my-sites/patterns/index.web.tsx
  client/my-sites/patterns/types.ts
Labels: [Status] Needs Review, Readymade Templates

#93227 Paid Impoter: connect stripe add notices
  client/my-sites/importer/newsletter/connect-stripe.tsx
  client/my-sites/importer/newsletter/map-plans.tsx
  client/my-sites/importer/newsletter/paid-subscribers.tsx
Labels: [Status] Needs Review, Import

#93210 wpcom-block-editor: fix tracking events not being triggered
  apps/wpcom-block-editor/src/wpcom/features/tracking.js
Labels: [Status] Needs Review

#93088 Adds a new origin for the promote post widget
  client/lib/promote-post/index.ts
Labels: [Status] Needs Review

#91966 Site Settings: Add Jetpack Firewall Toggle to Security Settings Screen
  client/my-sites/site-settings/allow-list.jsx
  client/my-sites/site-settings/firewall.jsx
  client/my-sites/site-settings/form-security.jsx
  client/my-sites/site-settings/protect.jsx
  client/my-sites/site-settings/style.scss
Labels: [Status] In Progress, [Status] Needs Review

#92989 Overview: Visually show a minimum amount of storage used
  client/hosting/overview/components/plan-storage-bar.tsx
  client/hosting/overview/components/style.scss
Labels: [Type] Enhancement, [Status] Needs Review, DO NOT MERGE, [Status] Needs Design, [Status] Design Input Requested

#93301 Frictionless Email Subscriptions: Fix horizontal scroll on mobile
  client/signup/steps/subscribe-email/index.jsx
  client/signup/steps/subscribe-email/style.scss
Labels: Frictionless Email Subscriptions

#93262 Reader: Fix margins for Logged Out + Fix margin on < back
  client/reader/search-stream/style.scss
  client/reader/style.scss
  client/reader/tag-stream/style.scss
Labels: [Status] Needs Review

#93266 Plans: Relocate header price component into shared
  packages/plans-grid-next/src/components/comparison-grid/index.tsx
  packages/plans-grid-next/src/components/features-grid/index.tsx
  packages/plans-grid-next/src/components/features-grid/plan-prices.tsx
  packages/plans-grid-next/src/components/features-grid/spotlight-plan.tsx
  packages/plans-grid-next/src/components/features-grid/table.tsx
  packages/plans-grid-next/src/components/shared/header-price/index.tsx
  packages/plans-grid-next/src/components/test/header-price.tsx
Labels: [Status] Needs Review

#93280 Site Level User Profile: add banner and restructure /me[/account]
  client/me/account/main.jsx
  client/me/profile/index.jsx
  client/me/profile/site-level-profile-banner/index.tsx
  client/me/profile/site-level-profile-banner/style.scss
  client/me/profile/site-level-profile-modal/index.jsx
  config/wpcalypso.json
Labels: [Status] Needs Review

#93267 A4A > Marketplace: Fix the products page overlapping issues
  client/a8c-for-agencies/sections/marketplace/products-overview/product-listing/style.scss
  client/a8c-for-agencies/sections/marketplace/products-overview/style.scss
Labels: [Status] Needs Review, A8c Agencies

#93278 A4A > Marketplace: update translations for enterprise hosting testimonials
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/enterprise-agency-hosting/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#93270 Signup: show free plan and domain modal for domain-only flow
  client/signup/config/steps-pure.js
Labels: [Status] Needs Review

#93135 Update the Pressable page to disallow the users from selecting a plan if ownership is 'regular.'
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/details.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/style.scss
Labels: [Status] Needs Review, A8c Agencies

#93202 Stats: Make Upsell section recognize Complete plans
  client/my-sites/stats/hooks/use-stats-purchases.tsx
  client/my-sites/stats/jetpack-upsell-section/index.tsx
  client/my-sites/stats/site.jsx
Labels: Stats, [Status] Needs Review

#93285 RT: Improve layout of details page
  client/my-sites/patterns/components/readymade-template-details/index.tsx
  client/my-sites/patterns/components/readymade-template-details/style.scss
Labels: [Status] Needs Review

#93288 A4A Dev Sites: Introduce `useFetchDevLicenses` hook and use it to display available dev sites count
  client/a8c-for-agencies/components/add-new-site-button/index.tsx
  client/a8c-for-agencies/data/purchases/use-fetch-dev-licenses.ts
Labels: [Status] Needs Review

#93239 A4A > Marketplace: Update the standard hosting slider to support input values
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/standard-agency-hosting/wpcom-plan-selector/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/standard-agency-hosting/wpcom-plan-selector/style.scss
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/bulk-selection.tsx
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/lib/wpcom-bulk-options.ts
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/wpcom-slider/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#93311 A4A > Marketplace: Update the Pressable page when the refer mode is toggled on
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/details.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/style.scss
Labels: [Status] Needs Review, A8c Agencies

#93313 A4A > Marketplace: Minor text updates & enhancements the new hosting page
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/common-hosting-benefits.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/premier-agency-hosting/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/standard-agency-hosting/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/details.tsx
Labels: [Status] Needs Review, A8c Agencies

#93316 Move recommended sites below subscriptions in subscription management
  client/landing/subscriptions/components/site-subscriptions-list/styles/site-subscriptions-list.scss
  client/reader/site-subscriptions-manager/reader-site-subscriptions.tsx
Labels: [Status] Needs Review

#93321 Readymade Templates: Mark content generation step as complete
  client/landing/stepper/declarative-flow/internals/steps-repository/readymade-template-generate-content/index.tsx
Labels: [Status] Needs Review

#93178 Stepper: Update `free-post-setup` flow to use framework tracking for step-submit
  client/landing/stepper/declarative-flow/free-post-setup.ts
  packages/data-stores/src/onboard/constants.ts
Labels: [Status] Needs Review, Stepper

#93291 Readymade Templates: Disable "generate content" button when there is no prompt
  client/landing/stepper/declarative-flow/internals/steps-repository/readymade-template-generate-content/index.tsx
Labels: [Status] Needs Review

#93206 Stepper: Track `variant` slug with submit-step event. Update site-migration flow to use framework tracking
  client/landing/stepper/declarative-flow/free-post-setup.ts
  client/landing/stepper/declarative-flow/internals/hooks/use-step-navigation-with-tracking/index.ts
  client/landing/stepper/declarative-flow/site-migration-flow.ts
  packages/data-stores/src/onboard/constants.ts
Labels: [Status] Needs Review

#93277 New Site Migration: Add Initial flow structure
  client/landing/stepper/declarative-flow/hosted-site-migration-v2/index.tsx
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/import-or-migrate-with-upgrade/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import-or-migrate-with-upgrade/style.scss
  client/landing/stepper/declarative-flow/internals/steps.tsx
  client/landing/stepper/declarative-flow/registered-flows.ts
  packages/onboarding/src/utils/flows.ts
Labels: [Status] Needs Review

#93023 WP.com/me tweaks for Gravatar
  client/blocks/edit-gravatar/index.jsx
  client/me/profile/index.jsx
  client/me/profile/style.scss
  client/me/profile/updated-gravatar-string.js
  client/me/profile/wp-and-gravatar-logo.jsx
Labels: [Status] Needs Review, [Status] String Freeze

#93314 Jetpack Connection: Update the old Pressable logo with the new one.
  client/components/jetpack-header/pressable.jsx
Labels: [Status] Ready to Merge, Jetpack Cloud

#93317 A4A: Fix Scan column redirect to work with WPCOM sites.
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/hooks/test/use-row-metadata.ts
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/lib/get-links.ts
Labels: [Status] Needs Review, A8c Agencies

#93286 Readymade Templates: Adjust responsive CSS on generate content page
  client/landing/stepper/declarative-flow/internals/steps-repository/readymade-template-generate-content/style.scss
Labels: [Status] Needs Review

#93146 Login Assistance: Revert the "show migrate CTA when login fails" experiment
  client/blocks/login/login-form.jsx
  client/blocks/login/migrate-notice.jsx
  client/blocks/login/migrate-notice.scss
  client/blocks/login/test/migrate-notice.jsx
  client/lib/login/index.js
  client/lib/login/test/index.js
  packages/material-design-icons/src/action/outline-dns-20px.svg
  packages/material-design-icons/svg-sprite/material-icons.svg
Labels: [Status] Needs Review

#93272 Site Migration: Improve site preparation for migration logs
  client/landing/stepper/hooks/test/use-prepare-site-for-migration.tsx
  client/landing/stepper/hooks/use-prepare-site-for-migration.ts
Labels: [Status] Needs Review

#93221 A4A: Use 'Free' word for products with zero prices in marketplace
  client/a8c-for-agencies/sections/marketplace/products-overview/multi-product-card/index.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/product-card/index.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/product-card/product-price-with-discount-info/index.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/product-card/product-price-with-discount-info/style.scss
Labels: [Status] Needs Review

#93295 A4A Dev Sites: Submit dev site from configuration modal
  client/a8c-for-agencies/components/site-configurations-modal/index.tsx
  client/a8c-for-agencies/data/sites/use-create-wpcom-dev-site.ts
  client/a8c-for-agencies/sections/sites/sites-header-actions/index.tsx
Labels: [Status] Needs Review

#93335 RT: Center generating content message on mobile
  client/landing/stepper/declarative-flow/internals/steps-repository/readymade-template-generate-content/components/readymade-template-preview/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/readymade-template-generate-content/components/readymade-template-preview/style.scss
Labels: [Status] Needs Review

#93230 Passwordless Auth - Enable passwordless sign up for the core profiler flow
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/passwordless.jsx
  client/jetpack-connect/auth-form-header.jsx
  client/jetpack-connect/signup.js
  client/jetpack-connect/style.scss
  client/layout/masterbar/woo.scss
  client/state/jetpack-connect/actions/create-account.js
  client/state/selectors/get-is-woo-passwordless.ts
Labels: [Status] Needs Review

#93329 ETK: Don't load features if Jetpack_Mu_Wpcom is available and its version is v5.54.0-alpha and above
  apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
Labels: [Status] Needs Review

#93326 A4A: Fix incorrect WPCOM-owned plan calculation.
  client/a8c-for-agencies/data/purchases/use-fetch-licenses.ts
  client/a8c-for-agencies/hooks/use-wpcom-owned-sites.ts
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/standard-agency-hosting/wpcom-plan-selector/index.tsx
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/hooks/use-total-invoice-value.ts
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/index.tsx
  client/a8c-for-agencies/sections/purchases/licenses/hooks/use-refetch-licenses.ts
Labels: [Status] Needs Review

#93331 A4A: Update the new WPCOM hosting page to use the simpler A4A slider.
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/standard-agency-hosting/wpcom-plan-selector/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/standard-agency-hosting/wpcom-plan-selector/slider.tsx
Labels: [Status] Needs Review, A8c Agencies

#93358 Remove Simple Classic experiment
  client/my-sites/site-settings/form-general.jsx
  client/my-sites/site-settings/site-admin-interface/experiment.tsx
Labels: [Status] Needs Review

#93324 A4A > Marketplace: Update new hosting page testimonial images
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/premier-agency-hosting/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/standard-agency-hosting/index.tsx
  client/assets/images/a8c-for-agencies/hosting/enterprise-testimonial-2.png
  client/assets/images/a8c-for-agencies/hosting/premier-testimonial-2.png
  client/assets/images/a8c-for-agencies/hosting/standard-testimonial-1.png
  client/assets/images/a8c-for-agencies/hosting/standard-testimonial-2.png
Labels: [Status] Needs Review, A8c Agencies

#93360 Site Level User Profile: improve banner and web address field UI
  client/me/profile/index.jsx
  client/me/profile/site-level-profile-banner/index.tsx
Labels: [Status] Needs Review

#93359 A4A: UX improvement on the A4A number input.
  client/a8c-for-agencies/components/a4a-number-input/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#93363 A4A: Fix Partner directory's expertise form validation with approved directories.
  client/a8c-for-agencies/sections/partner-directory/agency-expertise/hooks/use-expertise-form-validation.ts
  client/a8c-for-agencies/sections/partner-directory/agency-expertise/hooks/use-expertise-form.ts
  client/a8c-for-agencies/sections/partner-directory/agency-expertise/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#93323 RT: Adjust header of "Generate content" step
  client/landing/stepper/declarative-flow/internals/global.scss
Labels: [Status] Needs Review

#93332 RT: Add continue button
  client/landing/stepper/declarative-flow/internals/steps-repository/readymade-template-generate-content/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/readymade-template-generate-content/style.scss
  packages/launchpad/src/checklist-item/style.scss
Labels: [Status] Needs Review

#93276 A4A > Referrals: Redirect to client pages if the current user is a client
  client/a8c-for-agencies/sections/client/client-landing.tsx
  client/a8c-for-agencies/sections/landing/index.tsx
  client/a8c-for-agencies/sections/landing/landing.tsx
  client/state/a8c-for-agencies/agency/action-types.ts
  client/state/a8c-for-agencies/agency/actions.ts
  client/state/a8c-for-agencies/agency/handlers.ts
  client/state/a8c-for-agencies/agency/reducer.ts
  client/state/a8c-for-agencies/agency/selectors.ts
  client/state/a8c-for-agencies/types.ts
Labels: [Status] Needs Review, A8c Agencies

#93361 A4A > Marketplace: Minor text updates to the hosting page
  client/a8c-for-agencies/components/a4a-migration-offer-v2/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#93344 Make mocking instructions better
  bin/welcome.js
Labels: [Status] Needs Review

#93231 Update: subscription managemnt
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/blocks/reader-site-subscription/details.tsx
  client/blocks/reader-site-subscription/index.tsx
  client/blocks/reader-site-subscription/settings.tsx
  client/blocks/reader-site-subscription/site-subscription-subheader.tsx
  client/blocks/reader-site-subscription/styles.scss
  client/blocks/reader-site-subscription/subscribe-to-newsletter-categories.tsx
  client/blocks/reader-site-subscription/test/index.tsx
  client/landing/subscriptions/components/settings/site-settings/email-me-new-comments-toggle.tsx
  client/landing/subscriptions/components/settings/site-settings/email-me-new-posts-toggle.tsx
  client/landing/subscriptions/components/settings/site-settings/notify-me-of-new-posts-toggle.tsx
  client/landing/subscriptions/components/settings/site-settings/site-settings.tsx
  client/landing/subscriptions/components/settings/site-settings/styles.scss
  client/landing/subscriptions/components/settings/styles.scss
  client/reader/site-subscription/site-subscription.tsx
Labels: [Status] Needs Review, [Feature] Reader, [Feature] Subscriptions, Subscription Management

#93365 Reader: fix export/import dropdown alignment
  client/blocks/reader-export-button/index.tsx
  client/blocks/reader-export-button/style.scss
  client/blocks/reader-import-button/index.tsx
  client/blocks/reader-import-button/style.scss
  client/reader/icons/download-cloud.tsx
  client/reader/icons/index.ts
  client/reader/icons/upload-cloud.tsx
  client/reader/site-subscriptions-manager/site-subscriptions-manager.tsx
  client/reader/site-subscriptions-manager/style.scss
Labels: [Type] Bug, [Status] Needs Review, [Feature] Reader

#93336 Masterbar: Fix out border & icon color on support-session
  client/layout/masterbar/style.scss
Labels: [Status] Needs Review

#93368 RT: Use CPT page and mShots for previewing RTs
  client/landing/stepper/declarative-flow/internals/steps-repository/readymade-template-generate-content/components/readymade-template-preview/index.tsx
  client/my-sites/patterns/components/pattern-library/index.tsx
  client/my-sites/patterns/components/readymade-template-details/client.tsx
  client/my-sites/patterns/components/readymade-template-details/index.tsx
  client/my-sites/patterns/components/readymade-template-preview/index.tsx
  client/my-sites/patterns/components/readymade-template-preview/style.scss
  client/my-sites/patterns/components/readymade-templates/client.tsx
  client/my-sites/patterns/components/readymade-templates/index.tsx
  client/my-sites/patterns/components/readymade-templates/style.scss
  client/my-sites/patterns/hooks/use-readymade-templates.ts
  client/my-sites/patterns/hooks/use-render-readymade-template.ts
  client/my-sites/patterns/index.node.tsx
  client/my-sites/patterns/index.web.tsx
  client/my-sites/patterns/types.ts
  packages/block-renderer/src/components/index.tsx
  packages/block-renderer/src/components/readymade-template-renderer.tsx
  packages/data-stores/src/onboard/types.ts
  packages/onboarding/src/mshots-image/index.tsx
Labels: [Status] Needs Review

#93376 RT: Place CTA to the right
  client/my-sites/patterns/components/readymade-template-details/style.scss
Labels: [Status] Needs Review

#93327 Add platform Identification step + site-creation + processing
  client/blocks/import/list/index.tsx
  client/landing/stepper/declarative-flow/hosted-site-migration-v2/index.tsx
  client/landing/stepper/declarative-flow/hosted-site-migration-v2/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import-list/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/platform-identification/index.tsx
  client/landing/stepper/declarative-flow/internals/steps.tsx
  client/landing/stepper/declarative-flow/test/helpers/index.tsx
Labels: [Status] Needs Review

#93377 RT: Hide Get Started CTA from the navbar on the details page
  client/my-sites/patterns/index.web.tsx
  client/my-sites/patterns/wrapper.tsx
  packages/wpcom-template-parts/src/types.ts
  packages/wpcom-template-parts/src/universal-header-navigation/index.tsx
Labels: [Status] Needs Review

#93383 More granual Stepper code owners
  .github/CODEOWNERS
Labels: [Status] Needs Review

#93337 feat(hosting-overview-refinements): display WP version name in Hosting header
  client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-header/index.tsx
  client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-header/style.scss
Labels: [Status] Needs Review

#93364 Stepper: Fix `calypso_stepper_flow_start` tracking param names
  client/landing/stepper/declarative-flow/internals/hooks/use-flow-analytics/index.tsx
  client/landing/stepper/declarative-flow/internals/hooks/use-flow-analytics/test/index.tsx
Labels: [Status] Needs Review

#93371 100 year plan fix padding
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-setup/styles.scss
Labels: [Status] Needs Review

#92772 Add the translator nudge for non-Mag-16 locales
  client/components/language-picker/modal.scss
  client/components/language-picker/modal.tsx
  client/components/translator-invite/index.jsx
  client/components/translator-invite/style.scss
  client/components/translator-invite/test/index.js
  client/components/translator-invite/test/utils.js
  client/my-sites/customer-home/locations/tertiary/index.jsx
  packages/languages/src/languages-meta.json
  packages/material-design-icons/src/communication/outline-emoji_language-24px.svg
  packages/material-design-icons/svg-sprite/material-icons.svg
Labels: [Status] Needs Review, i18n, [Status] String Freeze

#93380 feat(hosting-overview-refinements): add spinner for activation hosting-features
  client/hosting/hosting-features/components/hosting-features.tsx
  client/hosting/hosting-features/components/style.scss
Labels: [Status] Needs Review

#93305 Help center: Add fallback and tracking event when API fails to load the article
  packages/help-center/src/components/help-center-article.tsx
  packages/help-center/src/hooks/use-post-by-url.ts
  packages/help-center/src/styles.scss
Labels: [Status] Needs Review

#92701 A4A: remove signup feature flag
  client/a8c-for-agencies/sections/signup/signup-form/index.tsx
  client/boot/common.js
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-horizon.json
  config/a8c-for-agencies-production.json
  config/a8c-for-agencies-stage.json
Labels: [Status] Needs Review, A4A

#93303 Make reauth modal fullscreen and keep the left hand Masterbar accessible
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/me/reauth-required/index.jsx
  client/me/reauth-required/style.scss
  packages/components/src/dialog/index.tsx
Labels: [Status] Needs Review

#93346 Frictionless Email Subscriptions: Default to loading screen on initial page render
  client/signup/steps/subscribe-email/index.jsx
Labels: [Status] Needs Review, Frictionless Email Subscriptions

#93382 Migration Revamp: Connect Steps
  client/landing/stepper/declarative-flow/hosted-site-migration-v2/index.tsx
  client/landing/stepper/declarative-flow/hosted-site-migration-v2/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/style.scss
  client/landing/stepper/declarative-flow/test/helpers/index.tsx
Labels: [Status] Needs Review

#93399 Help Center: add postcss-prefix-selector
  apps/help-center/package.json
  apps/help-center/postcss.config.js
  yarn.lock
Labels: [Status] Needs Review

#93393 Update: validate substack url
  client/my-sites/importer/newsletter/importer.scss
  client/my-sites/importer/newsletter/importer.tsx
  client/my-sites/importer/newsletter/select-newsletter-form.tsx
Labels: [Status] Needs Review

#93379 Add/add subscribers paid importer
  client/my-sites/importer/newsletter/importer.scss
  client/my-sites/importer/newsletter/subscriber-upload-form.tsx
  client/my-sites/importer/newsletter/subscribers.tsx
  packages/subscriber/src/index.ts
Labels: [Status] Needs Review, Subscriber Importer

#93318 Stats: Filter upsells in Odyssey based on bundle plans
  client/my-sites/stats/hooks/use-stats-purchases.tsx
  client/my-sites/stats/jetpack-upsell-section/index.tsx
Labels: Stats, [Status] Needs Review

#93322 Fix bad Odie chat input position (when system scrollbar is visible)
  packages/odie-client/src/style.scss
Labels: [Status] Needs Review

#93372 A4A > Marketplace: Implement new migration support form
  client/a8c-for-agencies/components/a4a-contact-support-widget/index.tsx
  client/a8c-for-agencies/components/a4a-migration-offer-v2/migration-contact-support-form/index.tsx
  client/a8c-for-agencies/components/a4a-migration-offer-v2/migration-contact-support-form/style.scss
  client/a8c-for-agencies/data/support/types.ts
Labels: [Status] Needs Review, A8c Agencies

#93283 Gravatar: Update login and 2FA pages
  client/blocks/login/index.jsx
  client/blocks/login/style.scss
  client/blocks/login/two-factor-authentication/two-factor-content.jsx
  client/blocks/login/two-factor-authentication/verification-code-form.jsx
  client/components/forms/form-verification-code-input/index.jsx
  client/layout/logged-out.jsx
  client/login/controller.js
  client/login/magic-login/emailed-login-link-expired.jsx
  client/login/magic-login/handle-emailed-link-form.jsx
  client/login/magic-login/style.scss
  client/login/wp-login/index.jsx
  client/login/wp-login/login-links.jsx
  client/login/wp-login/style.scss
Labels: [Status] Needs Review, Login, 2FA

#93240 A4A > Marketplace: Enable hosting page redesign on staging
  config/a8c-for-agencies-stage.json
Labels: [Status] Needs Review, DO NOT MERGE, A8c Agencies

#93404 Fix the default migration support form message
  client/a8c-for-agencies/components/a4a-contact-support-widget/index.tsx
  client/a8c-for-agencies/components/a4a-migration-offer-v2/migration-contact-support-form/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#93405 Stats: Add feature "stats-paid" to Jetpack Professional plan
  packages/calypso-products/src/plans-list.tsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#93338 Performance Profiler: Add route and page
  client/layout/logged-out.jsx
  client/performance-profiler/controller.tsx
  client/performance-profiler/index.node.ts
  client/performance-profiler/index.web.ts
  client/performance-profiler/package.json
  client/performance-profiler/pages/dashboard/index.tsx
  client/performance-profiler/pages/dashboard/style.scss
  client/sections.js
  config/development.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#93366 A4A: Remove mention of "Creator" within the WordPress license revoke dialog
  client/a8c-for-agencies/sections/purchases/licenses/license-list/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#93394 Overview: Remove refinements feature flag indicator
  client/a8c-for-agencies/components/items-dashboard/item-preview-pane/index.tsx
  client/hosting/overview/components/hosting-overview.tsx
Labels: [Status] Needs Review

#93032 Overview: Apply design to new bandwidth and site views
  client/hosting/overview/components/plan-bandwidth.tsx
  client/hosting/overview/components/plan-card.tsx
  client/hosting/overview/components/plan-site-visits.tsx
  client/hosting/overview/components/plan-storage-bar.tsx
  client/hosting/overview/components/style.scss
Labels: [Status] Needs Review

#93381 Global plugins marketplace - fix layout breakage due to pugins browser container and section component.
  client/components/section/index.tsx
  client/my-sites/plugins/education-footer/index.tsx
  client/my-sites/plugins/plugins-browser/style.scss
  client/state/global-sidebar/selectors.ts
Labels: [Status] Needs Review

#93412 Subscribers: Paid subscribers content importer UI fixes
  client/my-sites/importer/file-importer.jsx
  client/my-sites/importer/importer-action-buttons/action-button.jsx
  client/my-sites/importer/importer-action-buttons/action-button.scss
  client/my-sites/importer/importer-action-buttons/container.tsx
  client/my-sites/importer/importer-substack.jsx
  client/my-sites/importer/newsletter/connect-stripe.tsx
  client/my-sites/importer/newsletter/content.tsx
  client/my-sites/importer/newsletter/subscriber-upload-form.tsx
  client/my-sites/importer/newsletter/subscribers.tsx
  client/my-sites/importer/uploading-pane.jsx
Labels: [Status] Needs Review

#93418 fix(hosting-overview-refinements): a few fixes of hosting overview UI
  client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-header/index.tsx
  client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-header/style.scss
Labels: [Status] Needs Review
