Repository Automattic/wp-calypso, pull requests merged in 2024-04, with the labels that each got.

#89067 Automattic for Agencies: Set isEnabled flag to Invoice list only if agency ID exists
  client/a8c-for-agencies/data/purchases/use-fetch-invoices.ts
Labels: [Status] Needs Review, A8c Agencies

#88788 Adjust Odyssey Stats to allow Simple Classic to load properly
  apps/odyssey-stats/src/components/odyssey-query-site-purchases.ts
  apps/odyssey-stats/src/hooks/use-module-data-query.ts
  apps/odyssey-stats/src/lib/get-api.ts
  apps/odyssey-stats/src/lib/test/get-api.test.js
  apps/odyssey-stats/src/routes.ts
  client/my-sites/stats/stats-date-picker/index.jsx
  client/state/sites/selectors/is-jetpack-site-pred.ts
  packages/data-stores/src/site/types.ts
Labels: [Status] Needs Review

#89034 A4A: Implement Sites dashboard empty state.
  client/a8c-for-agencies/components/sidebar-menu/sites.tsx
  client/a8c-for-agencies/hooks/use-no-active-site.ts
  client/a8c-for-agencies/sections/sites/sites-dashboard/empty-state.tsx
  client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
  client/a8c-for-agencies/sections/sites/sites-dashboard/style.scss
  client/a8c-for-agencies/style.scss
Labels: [Status] Needs Review, A8c Agencies

#88965 Pattern Library: Change CTA URLs to `/setup/assembler-first`
  client/layout/logged-out.jsx
  client/my-sites/patterns/components/get-started/index.tsx
  client/my-sites/patterns/components/get-started/style.scss
  client/my-sites/patterns/paths.ts
  client/my-sites/patterns/wrapper.tsx
Labels: [Status] Needs Review

#88994 Pattern Library: More tweaks to Masonry logic
  client/my-sites/patterns/components/pattern-gallery/client.tsx
Labels: [Status] Needs Review

#89071 Limited Global Styles: Fix E2E test
  packages/calypso-e2e/src/lib/components/full-side-editor-nav-sidebar-component.ts
Labels: [Status] Needs Review

#89072 Updating the stats tab in the preview pane to match design specs
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-stats.tsx
  client/a8c-for-agencies/sections/sites/site-preview-pane/site-preview-pane-content/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/insights-stats.tsx
Labels: [Status] Needs Review

#89045 Stats: Refactor mobile highlight cards
  client/my-sites/stats/stats-subscribers-highlight-section/index.tsx
  client/my-sites/stats/stats-subscribers-highlight-section/style.scss
  packages/components/src/highlight-cards/annual-highlight-cards.tsx
  packages/components/src/highlight-cards/mobile-highlight-cards.tsx
  packages/components/src/highlight-cards/style.scss
  packages/components/src/highlight-cards/weekly-highlight-cards.tsx
  packages/components/src/index.ts
Labels: Stats, [Status] Needs Review

#88661 Signup: Vertically align the Create your account component
  client/signup/style.scss
Labels: [Status] Needs Review

#89077 Remove Hotjar script from /advertising page
  client/my-sites/promote-post-i2/main.tsx
Labels: [Status] Needs Review

#88964 Pattern Library: Fix scroll bug when loading single-pattern permalink
  client/components/category-pill-navigation/index.tsx
  client/my-sites/patterns/components/page-view-tracker.tsx
  client/my-sites/patterns/components/pattern-library/index.tsx
  client/my-sites/patterns/components/pattern-preview/index.tsx
  client/my-sites/patterns/components/pattern-preview/placeholder.tsx
Labels: [Status] Needs Review

#89058 A4A: Sites dashboard preview pane monitor section design update
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-monitor.tsx
  client/a8c-for-agencies/sections/sites/site-preview-pane/site-preview-pane-content/style.scss
Labels: [Status] Needs Review

#89074 A4A: Adding horizontal scroll for sites preview pane navigation
  client/a8c-for-agencies/sections/sites/site-preview-pane/style.scss
Labels: [Status] Needs Review

#88906 Backup: Add a backup-no-storage card
  client/components/jetpack/daily-backup-status/index.jsx
  client/components/jetpack/daily-backup-status/status-card/backup-no-storage.jsx
  client/components/jetpack/daily-backup-status/test/index.jsx
  client/lib/jetpack/backup-utils.js
Labels: [Status] Needs Review

#89084 Page Templates: Ensure function exists before call
  apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/class-starter-page-templates.php
Labels: [Status] Needs Review

#89082 A4A: Sites dashboard preview pane Boost section design update
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-boost.tsx
  client/a8c-for-agencies/sections/sites/site-preview-pane/site-preview-pane-content/style.scss
Labels: [Status] Needs Review

#89070 Migration Creator step: Main CTA is trial
  client/blocks/importer/wordpress/upgrade-plan/index.tsx
  client/blocks/importer/wordpress/upgrade-plan/style.scss
Labels: [Status] Needs Review

#89085 E2E: Use different block pattern
  test/e2e/specs/editor/editor__post-basic-flow.ts
Labels: [Status] Needs Review

#88986 Add skeleton for next steps component on the overview page
  client/a8c-for-agencies/components/sidebar-menu/lib/constants.ts
  client/a8c-for-agencies/sections/onboarding-tours/constants.ts
  client/a8c-for-agencies/sections/overview/body/next-steps/index.tsx
  client/a8c-for-agencies/sections/overview/body/next-steps/style.scss
Labels: [Status] Needs Review, A4A

#89086 Calypso users: Remove mapping when no email
  client/my-sites/people/team-members/index.tsx
Labels: [Status] Needs Review

#89050 Site Migration: Add tests to the upgrade plan step
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-upgrade-plan/test/index.tsx
Labels: [Status] Needs Review, Site Migration

#89021 Stats: Patch missing summary module relevant styles to the Email Stats summary page
  client/my-sites/stats/stats-email-summary/index.jsx
  packages/components/src/horizontal-bar-list/stats-card.tsx
Labels: Stats, [Status] Needs Review

#88932 Stats: Roll out compulsory plan selection for 1% of users
  client/my-sites/stats/hooks/use-site-complusory-plan-selection-qualified-check.ts
  client/my-sites/stats/stats-redirect/index.tsx
Labels: Stats, [Status] Needs Review

#89076 Automattic for Agencies: Fix the issue with Pressable plan list items not showing up
  client/a8c-for-agencies/sections/marketplace/checkout/product-info.tsx
Labels: [Status] Needs Review, A8c Agencies

#88943 Untangling: show unified sidebar for early classic view
  client/layout/index.jsx
  client/layout/masterbar/logged-in.jsx
  client/my-sites/navigation/index.jsx
  client/my-sites/sidebar/index.jsx
  client/my-sites/sidebar/static-data/global-site-sidebar-menu.ts
  client/my-sites/sidebar/style.scss
  client/my-sites/sidebar/use-site-menu-items.js
  client/state/global-sidebar/selectors.ts
Labels: [Status] Needs Review

#88998 Automattic for Agencies: Check if payment method is required and redirect to add payment page
  client/a8c-for-agencies/sections/marketplace/assign-license-step-progress/index.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/hooks/use-issue-licenses.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/product-listing/hooks/use-submit-form.tsx
  client/a8c-for-agencies/sections/marketplace/shopping-cart/index.tsx
  client/a8c-for-agencies/sections/purchases/invoices/invoices-overview/index.tsx
  client/a8c-for-agencies/sections/purchases/licenses/license-preview/index.tsx
  client/a8c-for-agencies/sections/purchases/payment-methods/hooks/use-payment-method.ts
  client/a8c-for-agencies/sections/purchases/payment-methods/hooks/use-return-url.ts
  client/a8c-for-agencies/sections/purchases/payment-methods/lib/get-stripe-configuration.ts
  client/a8c-for-agencies/sections/purchases/payment-methods/payment-method-add/payment-method-form/index.tsx
  client/state/a8c-for-agencies/agency/selectors.ts
Labels: [Status] Needs Review, A8c Agencies

#89018 Revert "ExPlat: Update UseExperiment README"
  packages/explat-client-react-helpers/README.md
Labels: [Status] Needs Review

#89099 Ensure we have a fallback CTA in UpgradePlan; re-add site migration tests
  client/blocks/importer/wordpress/upgrade-plan/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-upgrade-plan/test/index.tsx
Labels: [Status] Needs Review, Site Migration

#84462 SegmentedControl to packages (Step 4): Remove SegmentedControl component shim
  client/components/button-group/README.md
  client/components/pagination/README.md
  client/components/section-nav/README.md
  client/components/segmented-control/index.jsx
  client/components/segmented-control/simplified.jsx
  client/my-sites/promote-post-i2/components/search-bar/index.tsx
Labels: [Status] Needs Review

#85028 PlanPrice to packages (Step 4): Remove PlanPrice component shim
  client/my-sites/plan-price/index.tsx
Labels: [Status] Needs Review, Plans: NPM essential

#89096 A4A: Add requireAccessContext to all restricted pages.
  client/a8c-for-agencies/sections/landing/landing.tsx
  client/a8c-for-agencies/sections/marketplace/index.tsx
  client/a8c-for-agencies/sections/plugins/index.tsx
  client/a8c-for-agencies/sections/purchases/index.tsx
  client/a8c-for-agencies/sections/sites/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#89069 Pattern Library: Fix double `calypso_pattern_library_view` call
  client/my-sites/patterns/components/page-view-tracker.tsx
Labels: [Status] Needs Review

#89073 Pattern Library: Add pagination button
  client/my-sites/patterns/components/pattern-gallery/client.tsx
  client/my-sites/patterns/components/pattern-gallery/server.tsx
  client/my-sites/patterns/components/pattern-gallery/style.scss
  client/my-sites/patterns/components/pattern-library/index.tsx
Labels: [Status] Needs Review

#89033 Remove lazy-loading and add page-cache in boost feature listings
  client/my-sites/checkout/src/lib/get-jetpack-product-features.ts
  packages/calypso-products/src/translations.tsx
Labels: [Status] Needs Review

#88175 Site Monitoring: Localize Response Types Legend
  client/my-sites/site-monitoring/metrics-tab.tsx
Labels: [Type] Bug, [Status] Needs Review, i18n, [Status] String Freeze

#89095 Automattic for Agencies: Fix Sign out flow by adding `logout_url`
  client/a8c-for-agencies/components/sidebar/header/style.scss
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-horizon.json
  config/a8c-for-agencies-production.json
  config/a8c-for-agencies-stage.json
Labels: [Status] Needs Review, A8c Agencies

#89091 GitHub Deployments: Fix calypso_page_view tracking
  client/lib/analytics/page-view-tracker/index.jsx
  client/lib/analytics/page-view-tracker/test/index.jsx
  client/my-sites/github-deployments/controller.tsx
  client/my-sites/github-deployments/deployments/deployment-status.tsx
  client/my-sites/promote-post-i2/components/blaze-page-view-tracker/index.tsx
  client/my-sites/promote-post-i2/components/blaze-page-view-tracker/test/index.jsx
  client/my-sites/site-monitoring/controller.tsx
Labels: [Status] Needs Review, GitHub Deployments

#88509 i18n: Localize `None` option in podcasting topics selector
  client/my-sites/site-settings/podcasting-details/topics-selector.jsx
Labels: [Status] Needs Review, i18n, [Status] String Freeze

#89078 Add styles to hide links and CTA buttons
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-preview-pane.tsx
  client/a8c-for-agencies/sections/sites/features/jetpack/style.scss
Labels: [Status] Needs Review

#88683 i18n: Fix build-languages script translations ref key
  bin/build-languages.js
Labels: [Type] Bug, [Status] Needs Review, i18n, Build

#89042 Site Migration: Add tests to the site-migration-plugin install
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-plugin-install/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-plugin-install/test/index.tsx
Labels: [Status] Needs Review, Site Migration

#89031 update: a4a improve mobile layout
  client/a8c-for-agencies/components/layout/header.tsx
  client/a8c-for-agencies/components/layout/style.scss
  client/a8c-for-agencies/sections/marketplace/hosting-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/filter.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/style.scss
  client/a8c-for-agencies/sections/marketplace/pressable-overview/style.scss
  client/a8c-for-agencies/sections/marketplace/products-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/product-card/style.scss
  client/a8c-for-agencies/sections/marketplace/products-overview/style.scss
  client/a8c-for-agencies/sections/overview/header-actions/index.tsx
  client/a8c-for-agencies/sections/overview/overview.tsx
  client/a8c-for-agencies/sections/overview/style.scss
  client/a8c-for-agencies/sections/purchases/billing/billing-dashboard.tsx
  client/a8c-for-agencies/sections/purchases/billing/style.scss
  client/a8c-for-agencies/sections/purchases/licenses/licenses-overview/index.tsx
  client/a8c-for-agencies/sections/purchases/licenses/licenses-overview/style.scss
  client/a8c-for-agencies/sections/purchases/payment-methods/payment-method-overview/index.tsx
  client/a8c-for-agencies/sections/purchases/payment-methods/payment-method-overview/style.scss
  client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
  client/a8c-for-agencies/sections/sites/sites-dashboard/style.scss
Labels: [Status] Needs Review, Mobile Web, A4A

#89115 E2E: Fix broken use of `for...in` rather than `for...of`
  test/e2e/specs/editor/editor__post-basic-flow.ts
Labels: [Type] Bug, [Pri] Normal, [Status] Needs Review

#89130 E2E: genericize block pattern selection
  packages/calypso-e2e/src/lib/components/editor-inline-block-inserter-component.ts
  packages/calypso-e2e/src/lib/components/page-template-modal-component.ts
  test/e2e/specs/editor/editor__page-basic-flow.ts
  test/e2e/specs/editor/editor__post-basic-flow.ts
Labels: [Status] Needs Review

#88977 Checkout: Add min-height to SubmitFooterWrapper
  packages/composite-checkout/src/components/checkout-steps.tsx
Labels: [Status] Needs Review

#89075 Me: Make the back button point to the previous page
  client/layout/global-sidebar/main.jsx
  client/reader/sidebar/index.jsx
  client/sites-dashboard/components/sites-content-controls.tsx
  client/state/ui/selectors/get-section.js
Labels: [Status] Needs Review

#89126 Removed unnecessary calls to backend API at the hosting-config page
  client/my-sites/hosting/hosting-activate-status.tsx
  client/my-sites/hosting/main.js
  client/my-sites/hosting/test/hosting-activate-status.jsx
Labels: [Status] Needs Review

#89101 Stats: Update usePlanUsageQuery to use query defaults
  client/my-sites/stats/hooks/default-query-params.ts
  client/my-sites/stats/hooks/use-plan-usage-query.ts
  client/my-sites/stats/pages/providers/global-provider.tsx
  client/my-sites/stats/stats-module-utm/index.jsx
Labels: Stats, [Status] Needs Review

#89141 Stats: Move data requests etc to the real UTM module
  client/my-sites/stats/stats-module-utm/index.jsx
  client/my-sites/stats/stats-module-utm/stats-module-utm-dropdown.tsx
  client/my-sites/stats/stats-module-utm/stats-module-utm.jsx
  client/my-sites/stats/stats-module/stats-module-data-query.jsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#89137 Stats: Reduce min-wdith to fix module width for iPhones
  client/my-sites/stats/style.scss
  packages/components/src/horizontal-bar-list/_stats-variables.scss
Labels: Stats, [Status] Needs Review

#89142 Stats: Scroll to top for purchase page
  client/my-sites/stats/pages/purchase/index.tsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#89143 Stats: explicitly exclude UTM from benefit list
  client/my-sites/stats/stats-purchase/stats-purchase-personal.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-shared.tsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#89097 A4A: Arranged the 'Next steps' checklist based on availability of active site.
  client/a8c-for-agencies/sections/overview/body/next-steps/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#89098 A4A: Fix Overview page offering items CTA button hover style.
  client/a8c-for-agencies/components/offering/offering-item.tsx
  client/a8c-for-agencies/components/offering/style.scss
Labels: [Status] Needs Review, A8c Agencies

#89112 A4A: Add a placeholder page when checking access permission.
  client/a8c-for-agencies/components/sidebar-placeholder/index.tsx
  client/a8c-for-agencies/components/sidebar-placeholder/style.scss
  client/a8c-for-agencies/sections/landing/controller.tsx
  client/a8c-for-agencies/sections/landing/landing.tsx
  client/a8c-for-agencies/sections/landing/style.scss
Labels: [Status] Needs Review, A8c Agencies

#89147 Remove box-shadow from global nav
  client/layout/global-sidebar/style.scss
Labels: [Status] Needs Review

#89104 DIFM Content Form: add content guidelines dialog
  client/signup/steps/website-content/index.tsx
Labels: [Status] Needs Review

#89023 Patterns: Fix patterns that could be copied when searching
  client/my-sites/patterns/components/pattern-gallery/client.tsx
  client/my-sites/patterns/components/pattern-library/index.tsx
  client/my-sites/patterns/constants.ts
  client/my-sites/patterns/hooks/test/use-patterns.tsx
  client/my-sites/patterns/hooks/use-patterns.ts
  client/my-sites/patterns/lib/filter-patterns-by-term.ts
  client/my-sites/patterns/types.ts
Labels: [Status] Needs Review

#88898 Self-service site restore: update UI
  client/data/sites/use-site-excerpts-query.ts
  client/sites-dashboard/components/sites-content-controls.tsx
  client/sites-dashboard/components/sites-dashboard.tsx
  client/sites-dashboard/components/sites-table-row.tsx
  client/sites-dashboard/hooks/use-restore-site-mutation.ts
  packages/data-stores/src/site/types.ts
  packages/sites/src/create-sites-list-component.ts
  packages/sites/src/site-excerpt-constants.ts
  packages/sites/src/site-excerpt-types.ts
  packages/sites/src/site-status.tsx
  packages/sites/src/site-type.ts
  packages/sites/src/use-sites-list-grouping.tsx
  packages/sites/tests/create-mock-site.ts
  packages/sites/tests/use-sites-list-grouping.test.ts
Labels: [Status] Needs Review, self-service site restore

#89127 Migration plan step: Update trial position
  client/blocks/importer/wordpress/upgrade-plan/index.tsx
Labels: [Status] Needs Review

#89132 Pattern Library: Add tracking for when no results are found for a search
  client/my-sites/patterns/components/page-view-tracker.tsx
  client/my-sites/patterns/components/pattern-library/index.tsx
Labels: [Status] Needs Review

#89163 Self-service site restore: improve error message and show visual feedback
  client/sites-dashboard/components/sites-table-row.tsx
Labels: [Status] Needs Review, self-service site restore

#89149 A4A: Improve the Pressable plan purchase flow.
  client/a8c-for-agencies/controller.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/shopping-cart/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#89125 Global sidebar - update alternative text color when selected
  client/my-sites/sidebar/style.scss
Labels: [Status] Needs Review

#89144 Fix/a4a/164 sites dashboard preview pane remember filters and sort upon closing
  client/a8c-for-agencies/sections/sites/sites-dashboard-provider.tsx
Labels: [Status] Needs Review, A4A

#89116 Pattern Library: Pass `redirect_to` param to signup and login URLs
  client/my-sites/patterns/components/get-access-modal/index.tsx
  client/my-sites/patterns/components/pattern-library/index.tsx
  client/my-sites/patterns/components/pattern-preview/index.tsx
  client/my-sites/patterns/index.node.tsx
  client/my-sites/patterns/index.web.tsx
  client/my-sites/patterns/lib/get-pattern-permalink.ts
  client/my-sites/patterns/paths.ts
Labels: [Status] Needs Review

#89164 Pattern Library: Fix wonky `writing-mode` styles in Firefox, Safari
  client/my-sites/patterns/components/pattern-preview/index.tsx
  packages/block-renderer/src/components/pattern-renderer.tsx
Labels: [Status] Needs Review

#89120 Patterns: option to search in all categories
  client/my-sites/patterns/components/page-view-tracker.tsx
  client/my-sites/patterns/components/pattern-library/index.tsx
  client/my-sites/patterns/components/pattern-library/style.scss
Labels: [Status] String Freeze

#88832 Help Centre: Check Default Locale against English Variants
  packages/help-center/src/components/help-center-contact-page.tsx
Labels: OSS Citizen

#89177 Self-service site restore: Always show stats off indicator for deleted sites.
  client/sites-dashboard/components/sites-table-row.tsx
Labels: [Status] Needs Review, Maintenance, self-service site restore

#89146 Stats: Update date picker CSS for small screens
  client/components/stats-date-control/style.scss
Labels: Stats, [Status] Needs Review

#89139 Stats: Fixed various warnings from console
  client/my-sites/stats/all-time-views-section/index.tsx
  client/my-sites/stats/hooks/use-stats-purchases.ts
  client/my-sites/stats/summary/index.jsx
  client/state/sites/selectors/get-env-stats-feature-supports.ts
  client/state/stats/lists/selectors.js
  packages/components/src/horizontal-bar-list/horizontal-bar-grid-item.tsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#89168 E2E: getByRole → locator on page template selector
  test/e2e/specs/editor/editor__page-basic-flow.ts
Labels: [Status] Needs Review

#89152 Automattic for Agencies: Add site button enhancements
  client/a8c-for-agencies/components/add-new-site-button/index.tsx
  client/a8c-for-agencies/style.scss
Labels: [Status] Needs Review, Reviewer Can Merge, A8c Agencies

#89159 Automattic for Agencies: Fix the 'Connect a site to Jetpack' redirect
  client/jetpack-connect/authorize.js
Labels: [Status] Needs Review, Reviewer Can Merge, A8c Agencies

#89184 Fix Themes filters toolbar CSS wrap
  packages/components/src/responsive-toolbar-group/style.scss
Labels: [Status] Needs Review

#89124 Stats: Adjust the Stats purchase page layout on mobile
  client/my-sites/stats/modernized-layout-styles.scss
  client/my-sites/stats/stats-purchase/styles.scss
  client/my-sites/stats/stats-purchase/tier-upgrade-slider/styles.scss
Labels: Stats, [Status] Needs Review, [Status] Needs Design Review, [Status] Design Input Requested

#89179 Stats: add ecommerce to commercial reasons
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#89181 Odyssey Stats: Release compulsory plan selection for 1% existing users
  client/my-sites/stats/hooks/use-site-complusory-plan-selection-qualified-check.ts
Labels: Stats, [Status] Needs Review, Odyssey Stats

#89154 Fix unsusafe check for document in Server Side Rending context
  packages/help-center/src/hooks/use-zendesk-messaging.ts
Labels: [Status] Needs Review

#89150 Remove hotjar from Jetpack plans page
  client/blocks/importer/components/importing-pane/importing-pane.tsx
  client/my-sites/plans/jetpack-plans/selector.tsx
  client/signup/main.jsx
Labels: [Status] Needs Review

#89197 A4A: Fix the issue with the Monitoring toggle and Set Favorite button not reflecting changes in the Dashboard.
  client/a8c-for-agencies/sections/sites/site-set-favorite/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/hooks/use-toggle-activate-monitor.tsx
  client/jetpack-cloud/sections/agency-dashboard/hooks/use-update-monitor-settings.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/site-boost-column/boost-license-info-modal.tsx
Labels: [Status] Needs Review, A8c Agencies

#89203 Jetpack Start: Utilize partner type to determine the appropriate purchase label to use
  client/lib/purchases/index.ts
  client/me/purchases/manage-purchase/index.tsx
  packages/data-stores/src/purchases/lib/assembler.ts
  packages/data-stores/src/purchases/types.ts
Labels: [Status] Needs Review, [Feature] Subscriptions

#89199 Pattern Library: Don't filter search results by type
  client/my-sites/patterns/components/pattern-library/index.tsx
Labels: [Status] Needs Review

#89166 Updated transfer status handler on the hosting page
  client/my-sites/hosting/hosting-activate-status.tsx
  client/my-sites/hosting/main.js
  client/my-sites/hosting/test/hosting-activate-status.jsx
  client/state/automated-transfer/constants.ts
Labels: [Status] Needs Review

#89090 Scheduled Updates: Add schedule timeline logs screen
  client/blocks/plugins-update-manager/hooks/use-site-admin-url.ts
  client/blocks/plugins-update-manager/hooks/use-site-date-time-format.ts
  client/blocks/plugins-update-manager/schedule-logs.tsx
  client/blocks/plugins-update-manager/styles.scss
  client/components/timeline/timeline-event.jsx
  client/my-sites/site-settings/date-time-format/utils.js
Labels: [Status] Needs Review

#89135 disable upgrade to p2+, only show plan if it is the current plan
  client/state/selectors/can-upgrade-to-plan.js
  packages/plans-grid-next/src/hooks/data-store/use-grid-plans.tsx
Labels: [Status] Needs Review

#88490 Rollback hosting trial banner from theme upload page
  client/my-sites/themes/theme-upload/index.jsx
Labels: [Status] Needs Review, Upsell Nudge

#88486 Rollback hosting free trial CTA on Hosting Settings page
  client/my-sites/hosting/hosting-upsell-nudge/index.tsx
  client/my-sites/hosting/main.js
Labels: [Status] Needs Review, Upsell Nudge

#89140 Pattern Library: Add click tracking for load more clicks
  client/my-sites/patterns/components/pattern-gallery/client.tsx
Labels: [Status] Needs Review

#89190 Checkout: Fix keyboard tab directionality and focus styling
  client/my-sites/checkout/src/components/checkout-main-content.tsx
Labels: [Status] Needs Review

#89209 A4A: fix "go back" button styling on the payment methods page
  client/a8c-for-agencies/sections/purchases/payment-methods/payment-method-add/payment-method-form/style.scss
Labels: [Status] Needs Review, [Size] XS, A4A

#88271 Bluehost on Plans: Feature refresh for Bluehost launch
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/features-list.tsx
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#89220 Site migration: Update customer copy "Business" plan reference
  client/blocks/importer/wordpress/upgrade-plan/constants.tsx
Labels: [Status] Needs Review

#89218 Update site landing toggle copy
  client/me/account/toggle-sites-as-landing-page.tsx
Labels: [Status] Needs Copy Review, [Status] Editorial Input Requested

#89201 Untangling: make masterbar in Hosting menus look like wp-admin's
  client/layout/masterbar/logged-in.jsx
  client/layout/masterbar/style.scss
Labels: [Status] Needs Review

#89081 A4A: Add "Next Steps" Onboarding Tours
  client/a8c-for-agencies/components/guided-tour-step/index.tsx
  client/a8c-for-agencies/components/guided-tour-step/style.scss
  client/a8c-for-agencies/components/guided-tour/index.tsx
  client/a8c-for-agencies/components/layout/index.tsx
  client/a8c-for-agencies/data/guided-tours/guided-tour-context.tsx
  client/a8c-for-agencies/data/guided-tours/tours/use-add-new-site-tour.tsx
  client/a8c-for-agencies/data/guided-tours/tours/use-sites-walkthrough-tour.tsx
  client/a8c-for-agencies/data/guided-tours/use-guided-tours.tsx
  client/a8c-for-agencies/sections/overview/body/next-steps/index.tsx
  client/a8c-for-agencies/sections/sites/site-preview-pane/index.tsx
  client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
  client/a8c-for-agencies/sections/sites/sites-dataviews/index.tsx
  client/a8c-for-agencies/sections/sites/sites-dataviews/interfaces.ts
  client/a8c-for-agencies/sections/sites/sites-dataviews/site-data-field.tsx
  client/a8c-for-agencies/sections/sites/sites-dataviews/style.scss
  client/a8c-for-agencies/sections/sites/sites-dataviews/types.d.ts
  client/a8c-for-agencies/sections/sites/sites-header-actions/index.tsx
  client/a8c-for-agencies/sections/sites/sites-header-actions/style.scss
Labels: [Status] Needs Review, [Size] M, A4A

#89110 DIFM Content Form: add character limit warning
  client/signup/accordion-form/form-components.tsx
  client/signup/steps/website-content/section-generator.tsx
  client/signup/steps/website-content/section-types/components/media-upload.tsx
  client/signup/steps/website-content/section-types/components/wordpress-media-upload.tsx
  client/signup/steps/website-content/section-types/constants.ts
  client/signup/steps/website-content/section-types/contact-page-details.tsx
  client/signup/steps/website-content/section-types/custom-page-details.tsx
  client/signup/steps/website-content/section-types/default-page-details.tsx
  client/signup/steps/website-content/section-types/site-information-section.tsx
  client/state/signup/steps/website-content/actions.ts
  client/state/signup/steps/website-content/test/reducer.ts
Labels: [Status] Needs Review

#89235 Command Palette: Fix global nav opening
  packages/command-palette/src/context.tsx
Labels: [Status] Needs Review

#89237 Pattern Library: Change iframe `lazy` attribute for mirrored category preview
  client/my-sites/patterns/components/category-gallery/client.tsx
  client/my-sites/patterns/components/category-gallery/style.scss
Labels: [Status] Needs Review

#89171 A4A: Sites dashboard - Fixing Lightbox functionality for Boost within the Preview Pane
  client/a8c-for-agencies/sections/sites/sites-dashboard/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/hooks/use-install-boost.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/license-info-modal/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/boost-site-performance.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/test/boost-site-performance.test.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/site-boost-column/boost-license-info-modal.tsx
  client/state/jetpack-agency-dashboard/hooks/use-install-plugin-mutation.ts
Labels: [Status] Needs Review

#89210 Fix category pill navigation arrows for RTL languages
  client/components/category-pill-navigation/index.tsx
Labels: [Status] Needs Review

#89223 Scheduled updates: Print real logs data into ScheduleLogs component
  client/blocks/plugins-update-manager/schedule-logs.helper.ts
  client/blocks/plugins-update-manager/schedule-logs.tsx
  client/blocks/plugins-update-manager/test/schedule-logs.helper.test.tsx
  client/data/plugins/use-update-schedule-logs-query.ts
Labels: [Status] Needs Review

#89204 Patterns: fix rendering Footer pattern preview
  client/my-sites/patterns/components/category-gallery/client.tsx
  client/my-sites/patterns/components/category-gallery/style.scss
Labels: [Status] Needs Review

#89224 Plans Grid: Advertise Akismet Consistently With Our Marketing Pages
  packages/calypso-products/src/features-list.tsx
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#89214 A4A: Hide the Overview top navbar if it has only 1 item
  client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
  client/a8c-for-agencies/sections/sites/sites-dashboard/style.scss
Labels: [Status] Needs Review

#89165 Hosting Command Palette: Remove send feedback command
  client/sites-dashboard/components/wpcom-smp-commands.tsx
  packages/command-palette/src/commands/use-single-site-commands.tsx
  packages/help-center/src/components/help-center-contact-form.tsx
Labels: [Type] Enhancement, [Status] Needs Review, Hosting Command Palette

#89040 Command Palette: Unify commands
  apps/command-palette-wp-admin/package.json
  apps/command-palette-wp-admin/src/index.js
  apps/command-palette-wp-admin/src/use-commands.ts
  apps/command-palette-wp-admin/src/use-sites.ts
  client/layout/index.jsx
  client/lib/navigate/index.ts
  client/package.json
  client/sites-dashboard/components/wpcom-smp-commands.tsx
  packages/command-palette/README.md
  packages/command-palette/src/commands.tsx
  packages/command-palette/src/commands/types.tsx
  packages/command-palette/src/commands/use-command-navigation.tsx
  packages/command-palette/src/commands/use-single-site-commands.tsx
  packages/command-palette/src/context.tsx
  packages/command-palette/src/index.tsx
  packages/command-palette/src/use-command-palette.tsx
  packages/command-palette/src/utils.ts
  packages/command-palette/test/commands.tsx
  packages/command-palette/test/use-command-palette.tsx
  yarn.lock
Labels: [Status] Needs Review

#89228 A4A: Sites Dashboard - Show favorite icon on row focus
  client/a8c-for-agencies/sections/sites/sites-dashboard/style.scss
Labels: [Status] Needs Review

#89247 A4A: Sites Dashboard - Fix broken Boost table links
  client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/site-boost-column/index.tsx
Labels: [Status] Needs Review

#88892 Plans Next: Fix plan-type-selector sticky behaviour/styling
  client/my-sites/plans-features-main/style.scss
  packages/plans-grid-next/src/components/plan-type-selector/index.tsx
  packages/plans-grid-next/src/components/plan-type-selector/style.scss
Labels: [Status] Needs Review

#89215 A4A: Set the DocumentHead to Jetpack feature tabs in the Preview Pane
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-boost.tsx
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-monitor.tsx
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-plugins.tsx
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-stats.tsx
  client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
Labels: [Status] Needs Review

#89226 Render copy+header above pattern only for list view
  client/my-sites/patterns/components/pattern-preview/style.scss
Labels: [Status] Needs Review

#89202 A4A: Remove the site selector in the sidebar.
  client/a8c-for-agencies/components/sidebar-menu/marketplace.tsx
  client/a8c-for-agencies/components/sidebar-menu/purchases.tsx
  client/a8c-for-agencies/components/sidebar-menu/sites.tsx
  client/a8c-for-agencies/components/sidebar/header/index.tsx
  client/a8c-for-agencies/components/sidebar/header/style.scss
  client/a8c-for-agencies/components/sidebar/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#89221 A4A: Fixing pagination on the sites dashboard
  client/a8c-for-agencies/sections/sites/sites-dashboard/style.scss
  client/a8c-for-agencies/sections/sites/sites-dataviews/style.scss
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/sites-dataviews/style.scss
Labels: [Status] Needs Review

#89234 Plugin updates manager: Add Logs button to menu
  client/blocks/plugins-update-manager/index.tsx
  client/blocks/plugins-update-manager/schedule-list-cards.tsx
  client/blocks/plugins-update-manager/schedule-list-table.tsx
  client/blocks/plugins-update-manager/schedule-list.tsx
  client/my-sites/plugins/controller.js
Labels: [Status] Needs Review

#89242 Scheduled updates: Make the last run timestamp clickable and redirect to logs page
  client/blocks/plugins-update-manager/schedule-list-cards.tsx
  client/blocks/plugins-update-manager/schedule-list-table.tsx
  client/blocks/plugins-update-manager/styles.scss
Labels: [Status] Needs Review

#89151 Disable pagination when page is loaded with pattern hash
  client/my-sites/patterns/components/pattern-gallery/client.tsx
Labels: [Status] Needs Review

#89216 A4A: Sites Dashboard - Fix scan and backup not showing upsell buttons
  client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/site-status-column.tsx
Labels: [Status] Needs Review, A4A

#89253 Scheduled updates: Refetch schedules + in progress status
  client/blocks/plugins-update-manager/badge.scss
  client/blocks/plugins-update-manager/badge.tsx
  client/blocks/plugins-update-manager/schedule-list-cards.tsx
  client/blocks/plugins-update-manager/schedule-list-table.tsx
  client/blocks/plugins-update-manager/schedule-list.tsx
  client/blocks/plugins-update-manager/schedule-logs.helper.ts
  client/blocks/plugins-update-manager/styles.scss
  client/data/plugins/use-update-schedules-query.ts
Labels: [Status] Needs Review

#89256 Global sidebar - add a border
  client/my-sites/sidebar/style.scss
Labels: [Status] Needs Review

#89178 Site Migration: Update site migraton flow to conditionally verify the account email
  client/landing/stepper/declarative-flow/site-migration-flow.ts
  client/landing/stepper/declarative-flow/test/site-migration-flow.tsx
Labels: [Status] Needs Review

#89217 Rollback hosting trial CTA from plugin upload page
  client/my-sites/plugins/plugin-upload/index.jsx
Labels: [Status] Needs Review

#89248 A4A: Fixing various flows in the sites preview pane Activity panel
  client/my-sites/activity/activity-log-v2/index.tsx
Labels: [Status] Needs Review

#89267 Fixes a problem with tracking on the blaze card in the home screen
  client/my-sites/customer-home/cards/tasks/promote-post/index.js
Labels: [Status] Needs Review

#89269 Fixes the redirection we have to Blaze in the Home screen
  client/my-sites/advertising/useAdvertisingUrl.jsx
Labels: [Status] Needs Review

#89186 Migration Step: Update site-migration header text
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-upgrade-plan/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#89167 Migration Plan step: Update upgrade plan CTA copy
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-upgrade-plan/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-upgrade-plan/test/index.tsx
  test/e2e/specs/importer/importer__import-focused.ts
Labels: [Status] String Freeze, Site Migration

#89255 A4A: Intercept Activity Log links and redirect it to the Preview Pane
  client/a8c-for-agencies/sections/sites/features/contexts.ts
  client/a8c-for-agencies/sections/sites/features/jetpack/activity/routes.ts
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-contexts.tsx
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-routes.tsx
  client/a8c-for-agencies/sections/sites/features/jetpack/scan/routes.ts
  client/a8c-for-agencies/sections/sites/features/routes.ts
  client/a8c-for-agencies/sections/sites/index.tsx
Labels: [Status] Needs Review

#89133 Segmentation Survey: Implement save answers mutation and localStorage
  client/components/survey-container/components/question-multiple-selection.tsx
  client/components/survey-container/components/question-single-selection.tsx
  client/components/survey-container/context.tsx
  client/components/survey-container/index.tsx
  client/components/survey-container/types.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/ecommerce-segmentation-survey/hooks/use-cached-answers.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/ecommerce-segmentation-survey/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/ecommerce-segmentation-survey/mock.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/ecommerce-segmentation-survey/mutations/use-save-answers-mutation.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/ecommerce-segmentation-survey/provider.tsx
Labels: [Status] Needs Review

#89219 Pattern Library: add `search_term` to the `calypso_pattern_library_load_more` event
  client/my-sites/patterns/components/pattern-gallery/client.tsx
  client/my-sites/patterns/components/pattern-library/index.tsx
  client/my-sites/patterns/types.ts
Labels: [Status] Needs Review, [Feature] Tracks Metrics & Monitoring

#89257 Remove locale checks for redirects to site-migration flow
  client/landing/stepper/declarative-flow/helpers/index.ts
  client/landing/stepper/declarative-flow/helpers/test/index.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
Labels: [Status] Needs Review, i18n, Site Migration

#89265 A4A: Fix scan upsell link to make sure it goes to marketplace/products, plus header button style fixes
  client/a8c-for-agencies/components/sidebar-menu/lib/constants.ts
  client/a8c-for-agencies/sections/overview/header-actions/style.scss
  client/a8c-for-agencies/sections/sites/sites-header-actions/style.scss
  client/components/jetpack/unassigned-license-notice/index.tsx
  client/components/jetpack/upsell-product-card/index.tsx
Labels: [Status] Needs Review

#89227 Checkout: Fix prominence of dropdown picker
  client/my-sites/checkout/src/components/akismet-pro-quantity-dropdown/index.tsx
  client/my-sites/checkout/src/components/item-variation-picker/styles.tsx
  client/my-sites/checkout/src/payment-methods/credit-card/form-layout-components.tsx
Labels: [Status] Needs Review

#89238 Self-service site restore: make wording of error message compatible with D144421
  client/sites-dashboard/components/sites-table-row.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, self-service site restore

#89288 Revert "Plugins: Add pre-sales chat for logged-out users"
  client/my-sites/plugins/plugins-browser/index.jsx
Labels: [Status] Needs Review

#88598 GitHub Deployments: include link to workflow recipes
  client/my-sites/github-deployments/components/deployment-style/advanced-workflow-style.tsx
  client/my-sites/github-deployments/components/deployment-style/new-workflow-wizard.tsx
  client/my-sites/github-deployments/components/deployment-style/style.scss
Labels: [Status] Needs Review, Reviewer Can Merge, GitHub Deployments

#89290 A8C For Agencies: Site details pane tab on site flyout
  client/a8c-for-agencies/sections/sites/features/features.ts
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-preview-pane.tsx
  config/a8c-for-agencies-development.json
Labels: A8c Agencies

#89292 A4A: Add site details feature pane and site tags components
  client/a8c-for-agencies/components/agency-site-tag/index.tsx
  client/a8c-for-agencies/components/agency-site-tags/index.tsx
  client/a8c-for-agencies/sections/sites/features/a4a/site-details.tsx
  client/a8c-for-agencies/sections/sites/features/features.ts
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-preview-pane.tsx
  client/a8c-for-agencies/sections/sites/features/jetpack/site-details-pane/index.tsx
  client/a8c-for-agencies/types/site-tag.ts
Labels: [Status] Needs Review

#89295 Stats: Release paywall for 10% of existing sites
  client/my-sites/stats/hooks/use-site-complusory-plan-selection-qualified-check.ts
Labels: Stats, [Status] Needs Review

#89105 Odyssey Stats: Fix mini carousel banner button routing
  client/my-sites/stats/mini-carousel/index.jsx
  client/my-sites/stats/mini-carousel/mini-carousel-block.jsx
Labels: [Status] Needs Review

#89279 A4A: Minor style changes: Removing Jetpack Manage wording, button style fix
  client/a8c-for-agencies/sections/overview/header-actions/style.scss
  client/a8c-for-agencies/sections/sites/sites-header-actions/style.scss
  client/components/jetpack/upsell-product-card/index.tsx
Labels: [Status] Needs Review

#89239 Pattern Library: Add icon to copy button
  client/my-sites/patterns/components/pattern-preview/index.tsx
  client/my-sites/patterns/components/pattern-preview/style.scss
Labels: [Status] Needs Review

#89229 DIFM Design picker: update copy & styles
  client/signup/steps/design-picker/index.jsx
  client/signup/steps/design-picker/let-us-choose.tsx
  client/signup/steps/design-picker/style.scss
  client/state/difm/assemblers.ts
Labels: [Status] Needs Review, DIFM Express

#89245 Continue with Google: Fix failing e2e test (missing "Continue" button click)
  test/e2e/specs/onboarding/signup__woo-google.ts
Labels: [Status] Needs Review

#89275 A4A: Add the Backup feature subsection support and intercept cloud backup links redirect to A4A
  client/a8c-for-agencies/sections/sites/features/jetpack/backup/controller.js
  client/a8c-for-agencies/sections/sites/features/jetpack/backup/index.tsx
  client/a8c-for-agencies/sections/sites/features/jetpack/backup/routes.ts
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-preview-pane.tsx
  client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-routes.tsx
  client/a8c-for-agencies/sections/sites/features/jetpack/scan/index.tsx
  client/a8c-for-agencies/sections/sites/features/jetpack/scan/routes.ts
  client/a8c-for-agencies/sections/sites/sites-dashboard/style.scss
Labels: [Status] Needs Review

#89280 Subscribers: Update Odyssey stats links to JP Cloud
  client/my-sites/stats/stats-followers/index.jsx
  client/my-sites/stats/stats-reach/index.jsx
  client/my-sites/stats/stats-subscribers-chart-section/index.tsx
Labels: [Status] Needs Review

#89311 Fix Stats Subscribers > View Details for Calypso stats and Simple Classic
  client/my-sites/stats/stats-followers/index.jsx
Labels: [Status] Needs Review

#89250 `CommandPalette`: Hide the page's vertical scrollbar when it's open
  client/layout/style.scss
  packages/command-palette/src/index.tsx
Labels: [Status] Needs Review

#89004 Add Reddit tracking event for trial starts in new-hosted-site flow.
  client/landing/stepper/declarative-flow/new-hosted-site-flow.ts
  client/lib/analytics/ad-tracking/ad-track-trial-start.ts
Labels: [Status] Needs Review
