Repository Automattic/wp-calypso, pull requests merged in 2024-02, with the labels that each got.

#87064 Stats: Adding new purchase analytics events
  client/my-sites/stats/stats-purchase/stats-purchase-shared.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
  client/my-sites/stats/stats-redirect/index.tsx
Labels: Stats, [Status] Needs Review

#87066 Subscriber Stats: hide fractional number for y axis
  client/my-sites/stats/stats-subscribers-chart-section/chart-utils.ts
  client/my-sites/stats/stats-subscribers-chart-section/index.tsx
  client/my-sites/stats/stats-subscribers-chart-section/test/hide-fractional-number.test.js
  packages/components/src/chart-uplot/index.tsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge, [Stats] Subscribers

#87026 Hosting page: Update page title when admin interface is set to wp-admin
  client/my-sites/hosting/main.js
Labels: [Status] Needs Review, [Status] String Freeze

#87070 Stats: Adding busy button indication
  client/my-sites/stats/stats-purchase/stats-purchase-personal.tsx
Labels: Stats, [Status] Needs Review

#87071 Stats: Release new purchase flow
  config/client.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Stats, [Status] Needs Review

#87075 Stats: Small fix for typos
  client/my-sites/stats/stats-purchase/stats-purchase-personal.tsx
Labels: Stats, [Status] Needs Review

#87072 Assembler: use text and button colors for color variation swatches
  packages/global-styles/src/components/color-palette-variations/index.tsx
  packages/global-styles/src/components/color-palette-variations/preview.tsx
Labels: [Status] Needs Review

#86991 Fix `Free for…` text alignment in domain onboarding
  client/components/domains/domain-suggestion/style.scss
Labels: [Status] Needs Review

#87077 Assembler: inject page titles in the upsell screen
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/index.tsx
Labels: [Status] Needs Review

#86796 Plans Next: Untangle Features Grid from media queries, up reuse and default responsiveness
  .vscode/settings-sample.jsonc
  client/jetpack-app/plans/style.scss
  client/my-sites/plans-features-main/index.tsx
  client/my-sites/plans-features-main/style.scss
  client/signup/steps/plans/style.scss
  client/signup/style.scss
  packages/plans-grid-next/src/_media-queries.scss
  packages/plans-grid-next/src/_mixins.scss
  packages/plans-grid-next/src/components/features-grid/index.tsx
  packages/plans-grid-next/src/hooks/use-grid-size.ts
  packages/plans-grid-next/src/index.tsx
  packages/plans-grid-next/src/media-queries.tsx
  packages/plans-grid-next/src/style.scss
  packages/plans-grid-next/src/types.ts
Labels: [Status] Needs Review, Plans: NPM essential

#87050 Jetpack Manage: Pricing page -adding a more about link leading to a LicenseLightbox
  client/jetpack-cloud/sections/manage/pricing/license-products-list/all-license-items.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-multi-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/get-issue-license-url.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/most-popular-plans.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-multi-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/style.scss
Labels: [Status] Needs Review, Jetpack Cloud

#87061 Reader: Fix spacing around no tags found message
  client/reader/tag-stream/empty.jsx
  client/reader/tag-stream/style.scss
Labels: [Status] Needs Review, [Reader] Tags

#86950 Localize the My Home widget when showing Support Articles
  client/blocks/inline-help/inline-help-search-results.jsx
Labels: [Status] Needs Review

#87087 Jetpack Manage: Pricing page - Fix multi select options in product and plan cards generating console errors
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-multi-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-multi-item-card.tsx
Labels: [Status] Needs Review

#87004 Don't Merge until Jan 31 => Theme Tiers: Enable in all Calypso envs
  client/components/theme/test/__snapshots__/index.jsx.snap
  client/components/theme/test/index.jsx
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, DO NOT MERGE

#86539 Theme Tiers: Release Starter Themes on Live Preview
  apps/wpcom-block-editor/src/wpcom/features/live-preview/hooks/use-can-preview-but-need-upgrade.ts
  apps/wpcom-block-editor/src/wpcom/features/live-preview/hooks/use-previewing-theme.ts
Labels: [Status] Needs Review

#87060 AI Logo Generator: Release to production
  config/production.json
Labels: [Status] Needs Review

#87079 Email management: mailbox names link to email app
  client/components/popover-menu/item.jsx
  client/my-sites/email/email-management/home/email-mailbox-action-menu.jsx
  client/my-sites/email/email-management/home/email-plan-mailboxes-list.jsx
  client/my-sites/email/email-management/style.scss
Labels: [Status] Needs Review

#87096 Disable theme tiers on Calypso
  client/components/theme/test/__snapshots__/index.jsx.snap
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#86969 Command Palette: Add Visit Site Command
  client/jetpack-connect/test/authorize.js
  client/lib/navigate/index.ts
  client/sites-dashboard/components/wpcom-smp-commands.tsx
Labels: [Status] Needs Review, Reviewer Can Merge, Hosting Command Palette

#86618 Include `user_is_dev_account` property in page view tracking
  client/lib/analytics/page-view-tracker/index.jsx
  client/state/analytics/README.md
  client/state/analytics/actions/enhance-with-user-is-dev-account.ts
  client/state/analytics/actions/index.js
  client/state/selectors/get-user-setting.ts
Labels: [Status] Needs Review

#86633 Site selector: add missing section translations
  client/my-sites/sites/index.jsx
Labels: [Type] Bug, [Status] Needs Review, i18n

#87090 Jetpack Manage: Pricing page - Modifying default bundleSize for Addons and Woo Extensions
  client/jetpack-cloud/sections/manage/pricing/license-products-list/index.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#82620 composite-checkout: Combine form and transaction status state
  packages/composite-checkout/README.md
  packages/composite-checkout/src/components/form-and-transaction-event-handler.ts
  packages/composite-checkout/src/components/form-and-transaction-provider.tsx
  packages/composite-checkout/src/lib/form-and-transaction-status.ts
  packages/composite-checkout/src/lib/form-status.ts
  packages/composite-checkout/src/lib/transaction-status.ts
  packages/composite-checkout/src/types.ts
  packages/composite-checkout/test/checkout-provider.tsx
Labels: [Status] Needs Review, [Feature] Checkout

#87015 Checkout: Add gap to CostOverridesListItem between price and name
  client/my-sites/checkout/src/components/cost-overrides-list.tsx
Labels: [Status] Needs Review, [Feature] Checkout

#87106 Automattic Components: Remove form label component shim
  client/components/forms/form-label/index.tsx
  client/devdocs/design/playground-scope.js
  client/my-sites/exporter/export-card/post-type-options.jsx
Labels: Storage Addon

#85921 Jetpack Backup: add preflight checks on restore confirmation page
  client/my-sites/activity/activity-log-v2/index.tsx
  client/my-sites/backup/main.jsx
  client/my-sites/backup/rewind-flow/restore.tsx
  client/my-sites/backup/rewind-flow/steps/missing-credentials.tsx
  client/my-sites/backup/rewind-flow/style.scss
  client/state/rewind/preflight/hooks.tsx
Labels: [Status] Needs Review, [Feature] Backups

#87107 Shopping Cart: Remove hacks for introductory offer discounts
  client/my-sites/checkout/src/components/jetpack-akismet-checkout-sidebar-plan-upsell/index.tsx
  packages/shopping-cart/src/empty-carts.ts
  packages/shopping-cart/src/types.ts
  packages/wpcom-checkout/src/transformations.ts
Labels: [Status] Needs Review, [Feature] Checkout, [Feature] Shopping Cart

#86772 Update error notice for card errors
  client/jetpack-cloud/sections/partner-portal/payment-method-form/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#87110 Automattic Components: Update Select Dropdown component references to use package component
  client/components/section-nav/tabs.jsx
  client/components/web-preview/toolbar.jsx
  client/devdocs/design/playground-scope.js
  client/devdocs/design/playground.jsx
  client/jetpack-cloud/sections/agency-dashboard/dashboard-bulk-actions/index.tsx
  client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/notification-settings/form-content/notification-duration.tsx
  client/jetpack-cloud/sections/partner-portal/select-partner-key-dropdown/index.tsx
  client/landing/subscriptions/components/site-subscriptions-list/site-subscriptions-list-actions-bar.tsx
  client/landing/subscriptions/components/tab-views/comments/comments.tsx
  client/me/purchases/billing-history/billing-history-filters.jsx
  client/my-sites/checkout/checkout-thank-you/licensing-thank-you-auto-activation.tsx
  client/my-sites/plugins/plugin-list-header/index.jsx
  client/my-sites/promote-post-i2/components/search-bar/index.tsx
  client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx
  client/my-sites/stats/stats-module/all-time-nav.jsx
  client/my-sites/stats/stats-module/select-dropdown.jsx
  client/my-sites/subscribers/components/subscriber-list-actions-bar/subscriber-list-actions-bar.tsx
  client/my-sites/themes/theme-showcase.jsx
  client/post-editor/media-modal/gallery/fields.jsx
  client/sites-dashboard/components/sites-content-controls.tsx
  packages/components/src/select-dropdown/docs/example.jsx
Labels: [Status] Needs Review, Storage Addon

#87111 Automattic Components: Remove select dropdown component shim
  client/components/select-dropdown/index.jsx
Labels: Storage Addon

#87116 Stats: Update the cut-off date
  client/my-sites/stats/stats-redirect/index.tsx
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#87119 GitHub Deployments: add connect/disconnect UI
  client/my-sites/github-deployments/authorize/authorize-button.tsx
  client/my-sites/github-deployments/authorize/index.tsx
  client/my-sites/github-deployments/authorize/style.scss
  client/my-sites/github-deployments/connected/accounts/account-list-item.tsx
  client/my-sites/github-deployments/connected/accounts/account-list.tsx
  client/my-sites/github-deployments/connected/accounts/index.tsx
  client/my-sites/github-deployments/connected/accounts/search-accounts.tsx
  client/my-sites/github-deployments/connected/accounts/style.scss
  client/my-sites/github-deployments/connected/index.tsx
  client/my-sites/github-deployments/connected/repositories/index.tsx
  client/my-sites/github-deployments/connected/style.scss
  client/my-sites/github-deployments/constants.ts
  client/my-sites/github-deployments/controller.tsx
  client/my-sites/github-deployments/loading-placeholder.tsx
  client/my-sites/github-deployments/main.tsx
  client/my-sites/github-deployments/style.scss
  client/my-sites/github-deployments/types.ts
  client/my-sites/github-deployments/use-github-connection-query.ts
  client/my-sites/hosting/github/github-connect-card/index.tsx
  client/state/sharing/keyring/actions.js
Labels: [Status] Needs Review, Reviewer Can Merge, GitHub Deployments i1

#86988 Fix email upsell slug for secondary domains
  client/components/thank-you-v2/upsell/style.scss
  client/my-sites/checkout/checkout-thank-you/redesign-v2/pages/domain-only.tsx
  client/my-sites/checkout/get-thank-you-page-url/index.ts
  client/signup/config/flows.js
Labels: [Status] Needs Review

#87035 Updated CTAs on domain only thank you page
  client/my-sites/checkout/checkout-thank-you/redesign-v2/pages/domain-only.tsx
  client/my-sites/checkout/checkout-thank-you/redesign-v2/products/domain-product.tsx
Labels: [Status] Needs Review

#87121 Theme Tiers: Enable flag in dev
  client/components/theme/test/__snapshots__/index.jsx.snap
  config/development.json
  config/test.json
Labels: [Status] Needs Review

#87122 Social: update feature comparison copy.
  client/jetpack-cloud/sections/comparison/table/useComparisonData.tsx
Labels: [Status] Needs Review

#87078 Two Step: Fix security keys invalid nonce and missing backup code section
  client/me/reauth-required/index.jsx
  client/me/reauth-required/security-key-form.jsx
  client/me/two-step/index.jsx
Labels: [Status] Needs Review

#87085 Migration flow: Improve guidance and messaging for the NotAuthorized component
  client/blocks/importer/components/not-authorized/index.tsx
  client/blocks/importer/components/not-authorized/style.scss
  client/blocks/importer/util.ts
  client/blocks/importer/wordpress/import-everything/index.tsx
  client/blocks/importer/wordpress/import-everything/migration-error/hint-jetpack-connection-move-plugin.tsx
  client/blocks/importer/wordpress/import-everything/pre-migration/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/migration-handler/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/migration-handler/test/index.test.tsx
Labels: [Status] Needs Review

#87129 Theme tiers: Enable theme tiers on WPCalypso
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#87131 JP Manage: Pricing page redirect should open correct modal and select product on page load
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-multi-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-multi-item-card.tsx
  client/jetpack-cloud/sections/partner-portal/license-multi-product-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/primary/issue-license/index.tsx
Labels: [Status] Needs Review

#87126 Theme Tiers: Fix Warnings and Update Tracks Events
  client/components/theme-tier/theme-tier-badge/index.js
  client/components/themes-list/index.jsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  client/my-sites/theme/main.jsx
  client/my-sites/themes/collections/showcase-theme-collection.tsx
  client/my-sites/themes/collections/use-theme-collection.ts
  client/my-sites/themes/events/theme-showcase-tracks.ts
  client/my-sites/themes/themes-selection.jsx
  client/state/themes/actions/live-preview.ts
  client/state/themes/actions/theme-activated.js
  client/state/themes/selectors/get-active-theme.ts
  client/state/themes/selectors/is-theme-premium.js
Labels: [Status] Needs Review, [Feature] Theme Showcase

#86826 Checkout: Add Pix payment method
  client/my-sites/checkout/purchase-modal/index.tsx
  client/my-sites/checkout/src/components/checkout-main.tsx
  client/my-sites/checkout/src/hooks/use-create-payment-methods/index.tsx
  client/my-sites/checkout/src/lib/pix-confirmation.tsx
  client/my-sites/checkout/src/lib/pix-processor.ts
  client/my-sites/checkout/src/lib/translate-payment-method-names.ts
  client/my-sites/checkout/src/payment-methods/pix.tsx
  client/my-sites/checkout/src/types/payment-processors.ts
  packages/composite-checkout/src/lib/validation.ts
  packages/wpcom-checkout/src/types.ts
Labels: [Status] Needs Review, [Feature] Checkout, [Status] String Freeze

#87136 Theme Tiers: Fix premium theme signup E2E
  client/components/theme-tier/theme-tier-badge/index.js
  test/e2e/specs/onboarding/signup__with-theme-premium.ts
Labels: [Status] Needs Review

#87100 fix(developer): enchancer for adding is_dev_account to tracking events
  client/me/developer/features/handle-click-link.tsx
  client/me/developer/features/index.tsx
  client/me/developer/features/use-features-list.tsx
  client/me/developer/features/use-handle-click-link.tsx
  client/me/developer/features/use-record-tracks-event-with-user-is-dev-account.tsx
Labels: [Status] Needs Review

#87138 Fix multi-site /stats page
  client/my-sites/stats/controller.jsx
Labels: [Type] Bug, Stats, [Status] Ready to Merge

#87118 Jetpack Backup: add preflight checks for granular restores
  client/my-sites/backup/backup-contents-page/index.tsx
  client/my-sites/backup/rewind-flow/granular-restore.tsx
  client/my-sites/backup/rewind-flow/restore.tsx
  client/my-sites/backup/rewind-flow/steps/missing-credentials.tsx
Labels: [Status] Needs Review, [Feature] Backups

#87143 Jetpack Manage - Pricing page: Fix Get buttons not passing bundle sizes and licensing page behavior when source is manage-pricing-page
  client/jetpack-cloud/sections/agency-signup/agency-signup-form/index.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/all-license-items.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-multi-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/index.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/most-popular-plans.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-multi-item-card.tsx
  client/jetpack-cloud/sections/partner-portal/primary/issue-license/index.tsx
Labels: [Status] Needs Review

#87148 Jetpack Manage: Pricing page - Fix Error when navigating to the "Single license tab"
  client/jetpack-cloud/sections/manage/pricing/license-products-list/all-license-items.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/most-popular-plans.tsx
Labels: [Status] Needs Review

#87152 Github Deployments i1: Add UI to create repository based on selected templates
  client/my-sites/github-deployments/components/create-repository/create-repository-form.tsx
  client/my-sites/github-deployments/components/create-repository/index.tsx
  client/my-sites/github-deployments/components/create-repository/style.scss
  client/my-sites/github-deployments/components/create-repository/templates.ts
Labels: [Status] Needs Review, Reviewer Can Merge, GitHub Deployments i1

#87163 Stats: Fix for unhandled exception
  client/my-sites/stats/stats-purchase/stats-commercial-upgrade-slider/index.tsx
Labels: Stats, [Status] Needs Review

#87125 Assembler: clean up code for testing that forces using site data from Assembler demo site in previews on Horizon
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-assembler-container.tsx
Labels: [Status] Needs Review

#87042 [WooCommerce NUX] Fix incorrect redirection for existing user
  client/blocks/login/login-form.jsx
  client/blocks/signup-form/index.jsx
  client/components/notice/index.jsx
  client/layout/masterbar/woo.scss
  client/state/action-types.ts
  client/state/login/actions/cancel-social-account-connect-linking.js
  client/state/login/reducer.js
  packages/components/src/icons/alert.tsx
Labels: [Status] Needs Review

#86059 Replace harcoded plan name in video upload notice
  client/my-sites/media-library/content.jsx
Labels: [Status] Needs Review, [Status] String Freeze

#87162 Migration onboarding: Hide nav back button when migration is in progress
  client/blocks/importer/wordpress/utils.js
  client/landing/stepper/declarative-flow/internals/steps-repository/importer/index.tsx
  client/my-sites/migrate/section-migrate.jsx
Labels: [Status] Needs Review

#86789 Live Preview: fix wrapping in narrow screens
  apps/wpcom-block-editor/src/wpcom/features/live-preview/index.scss
  apps/wpcom-block-editor/src/wpcom/features/live-preview/live-preview-notice-plugin.tsx
  apps/wpcom-block-editor/src/wpcom/features/live-preview/upgrade-notice.tsx
Labels: [Status] Needs Review

#87104 Jetpack Manage: Pricing page - styling adjustments to match design specifications
  client/components/jetpack/card/jetpack-product-card/display-price/index.tsx
  client/components/jetpack/card/jetpack-product-card/display-price/paid.tsx
  client/jetpack-cloud/sections/manage/pricing/header/style.scss
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-multi-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/item-price.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-multi-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/style.scss
  client/jetpack-cloud/sections/manage/pricing/pricing-license-selector/style.scss
  client/jetpack-cloud/sections/manage/pricing/primary/index.tsx
  client/jetpack-cloud/sections/manage/pricing/primary/style.scss
  client/jetpack-cloud/sections/partner-portal/license-multi-product-card/index.tsx
  client/jetpack-cloud/sections/partner-portal/license-product-card/index.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#87081 Theme Showcase: Update the Search Suggestions Layout
  client/components/search-themes/style.scss
Labels: [Status] Needs Review, [Feature] Theme Showcase

#87170 Themes: Only Show Download Card for Free Themes
  client/my-sites/theme/main.jsx
Labels: [Status] Needs Review, [Feature] Theme Showcase

#87167 Signup: enable hotjar for BBE flow and disable for Stepper
  client/gutenberg/editor/calypsoify-iframe.tsx
  client/landing/stepper/index.tsx
  client/my-sites/customer-home/main.jsx
  client/signup/main.jsx
Labels: [Status] Needs Review

#87168 Fix GA module in Tools > Marketing > Traffic for Atomic sites
  client/my-sites/site-settings/analytics/form-google-analytics.jsx
Labels: [Status] Needs Review

#87176 Colour Schemes: Bring Back Classic Bright
  packages/calypso-color-schemes/src/calypso-color-schemes.scss
  packages/calypso-color-schemes/src/shared/color-schemes/_classic-bright.scss
Labels: OSS Citizen

#87157 Reader: Fix "Add a tag" Visibility
  client/reader/sidebar/style.scss
Labels: [Status] Needs Review, OSS Citizen, [Reader] Tags

#87178 Fixed the spacing between badges on the design setup screen
  packages/design-preview/src/components/style.scss
Labels: [Status] Needs Review

#87146 JP Manage Pricing: Technical polish - simplifying markup, moving CSS
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-multi-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-multi-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/style.scss
  client/jetpack-cloud/sections/manage/pricing/primary/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/featured-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/simple-item-card/index.tsx
  client/my-sites/plans/jetpack-plans/product-store/simple-item-card/style.scss
  client/my-sites/plans/jetpack-plans/product-store/types.ts
Labels: [Status] Needs Review, Jetpack Cloud

#87172 Theme Tiers: Remove hasTranslation checks
  client/components/theme-upgrade-modal/index.tsx
  client/lib/plans/features-list.tsx
Labels: [Status] Needs Review

#87190 Jetpack Manage: Pricing Page - Make it public
  client/boot/common.js
  config/jetpack-cloud-production.json
Labels: [Status] Needs Review

#87147 Checkout: Fix "Tax" line border position without discounts
  client/my-sites/checkout/src/components/wp-checkout-order-summary.tsx
Labels: [Status] Needs Review, [Feature] Checkout

#73246 Settings: Adjust setting section title's padding
  client/my-sites/site-settings/reading-rss-feed-settings/ExcerptSetting.tsx
  client/my-sites/site-settings/reading-rss-feed-settings/SyndicationFeedsSetting.tsx
  client/my-sites/site-settings/reading-site-settings/BlogPagesSetting.tsx
  client/my-sites/site-settings/reading-site-settings/RelatedPostsSetting.tsx
  client/my-sites/site-settings/settings-newsletter/ExcerptSetting.tsx
  client/my-sites/site-settings/style.scss
Labels: [Status] Needs Review, Reading Settings

#87199 Jetpack Manage: Pricing page redirect fix from agency signup form to the issue license form
  client/jetpack-cloud/sections/agency-signup/agency-signup-form/index.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#86960 Launchpad: Clean up task-helper
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/bio/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/bio/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/design/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/domain/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/domain/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/payments/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/plan/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/plan/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/post/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/post/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/setup/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/site/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/task-helper.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/types.ts
Labels: [Status] Needs Review, [Feature] Launchpad

#87205 Jetpack Manage Pricing page: Refactor redirect logic so it works with authorizePath()
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-multi-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-multi-item-card.tsx
Labels: [Status] Needs Review

#86267 Checkout: Move checkout line items into CSS Grid containers
  client/my-sites/checkout/src/components/item-variation-picker/styles.tsx
  client/my-sites/checkout/src/components/wp-order-review-line-items.tsx
  packages/wpcom-checkout/src/checkout-line-items.tsx
Labels: [Status] Needs Review

#87123 Add WordPress.com > Site Tools page and Other tools section
  client/my-sites/site-settings/controller.js
  client/my-sites/site-settings/index.js
  client/my-sites/site-settings/section-general.jsx
  client/my-sites/site-settings/site-tools/index.jsx
  client/my-sites/site-settings/wpcom-site-tools-settings/index.jsx
  client/my-sites/site-settings/wpcom-site-tools.jsx
Labels: [Status] Needs Review

#86825 Extract separate components from FeaturesGrid
  packages/plans-grid-next/src/components/actions.tsx
  packages/plans-grid-next/src/components/features-grid/billing-timeframes.tsx
  packages/plans-grid-next/src/components/features-grid/index.tsx
  packages/plans-grid-next/src/components/features-grid/mobile-free-domain.tsx
  packages/plans-grid-next/src/components/features-grid/plan-features-list.tsx
  packages/plans-grid-next/src/components/features-grid/plan-headers.tsx
  packages/plans-grid-next/src/components/features-grid/plan-logos.tsx
  packages/plans-grid-next/src/components/features-grid/plan-price.tsx
  packages/plans-grid-next/src/components/features-grid/plan-storage-options.tsx
  packages/plans-grid-next/src/components/features-grid/plan-tagline.tsx
  packages/plans-grid-next/src/components/features-grid/previous-features-included-title.tsx
  packages/plans-grid-next/src/components/features-grid/spotlight-plan.tsx
  packages/plans-grid-next/src/components/features-grid/table.tsx
  packages/plans-grid-next/src/components/features-grid/top-buttons.tsx
  packages/plans-grid-next/src/components/plan-features-container.tsx
Labels: [Status] Needs Review, Plans: NPM essential

#86805 Displaying the gift subscription in subscriber's page
  client/blocks/reader-site-subscription/details.tsx
  client/blocks/reader-site-subscription/helpers.tsx
  client/my-sites/subscribers/components/gift-modal/gift-modal.tsx
  client/my-sites/subscribers/components/subscriber-details/subscriber-details.tsx
  client/my-sites/subscribers/components/subscriber-list/subscriber-row.tsx
  client/my-sites/subscribers/components/subscribers-page/subscribers-page-context.tsx
  client/my-sites/subscribers/controller.js
  client/my-sites/subscribers/helpers/index.ts
  client/my-sites/subscribers/hooks/use-subscription-plans.ts
  client/my-sites/subscribers/main.tsx
  client/my-sites/subscribers/queries/use-subscribers-query.tsx
  client/my-sites/subscribers/types/index.ts
  client/state/memberships/gifts/actions.js
  packages/data-stores/src/reader/types/index.ts
Labels: [Status] Needs Review

#87171 Update copy and order for admin interface style
  client/my-sites/hosting/site-admin-interface-card/index.js
Labels: [Status] Needs Review, [Status] String Freeze

#87213 Jetpack Manage: Pricing - adding a tracks event linked to clicking the Get / Select license button
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-multi-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-multi-item-card.tsx
Labels: [Status] Needs Review, Jetpack Cloud

#87207 Add padding to developer features page header to prevent notice overlap
  client/me/developer/style.scss
Labels: [Status] Needs Review

#86945 Signup: Reduced google error message
  client/blocks/signup-form/index.jsx
Labels: [Status] Needs Review, [Status] String Freeze, Social Signup

#87191 Allow subdomains in glue records
  client/my-sites/domains/domain-management/settings/cards/glue-records-card.tsx
Labels: [Status] Needs Review

#87083 User invite: Make invite passwordless
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/passwordless.jsx
  client/my-sites/invites/invite-accept-logged-out/index.jsx
  client/my-sites/invites/p2/invite-accept-logged-out.jsx
Labels: [Status] Needs Review, Jetpack SSO

#87149 Fix redirect after user connection coming from My Jetpack
  client/jetpack-connect/authorize.js
Labels: [Status] Needs Review

#87197 Ensure hosting flow colors are not overriden
  client/sites-dashboard/components/hosting-flow-forking-page.tsx
  client/sites-dashboard/controller.tsx
Labels: [Status] Needs Review

#86876 Comments: Allow Filtering Replied Comments
  client/my-sites/comments/comment-list/index.jsx
  client/my-sites/comments/comment-navigation/index.jsx
  client/my-sites/comments/comment/index.jsx
  client/my-sites/comments/comment/style.scss
  client/my-sites/comments/main.jsx
  client/my-sites/comments/style.scss
Labels: [Status] Needs Review, OSS Citizen

#87223 Revert "Comments: Allow Filtering Replied Comments "
  client/my-sites/comments/comment-list/index.jsx
  client/my-sites/comments/comment-navigation/index.jsx
  client/my-sites/comments/comment/index.jsx
  client/my-sites/comments/comment/style.scss
  client/my-sites/comments/main.jsx
  client/my-sites/comments/style.scss
Labels: [Status] Needs Review

#87130 Design Setup: Fetch Starter Design with locale
  packages/data-stores/src/starter-designs-queries/use-starter-design-by-slug.ts
Labels: [Type] Bug, [Status] Needs Review, i18n

#87224 Revert "Revert "Comments: Allow Filtering Replied Comments ""
  client/my-sites/comments/comment-list/index.jsx
  client/my-sites/comments/comment-navigation/index.jsx
  client/my-sites/comments/comment/index.jsx
  client/my-sites/comments/comment/style.scss
  client/my-sites/comments/main.jsx
  client/my-sites/comments/style.scss
Labels: [Status] Needs Review

#87109 Checkout: Show introductory offer details in discount list
  client/my-sites/checkout/src/components/cost-overrides-list.tsx
  client/my-sites/checkout/src/components/wp-checkout-order-summary.tsx
  packages/shopping-cart/src/types.ts
  packages/wpcom-checkout/src/transformations.ts
Labels: [Status] Needs Review, [Feature] Checkout

#87024 (e2e)(chore) Fix failing tests in `authentication/authentication__google.ts`
  packages/calypso-e2e/src/lib/pages/external/google-login-page.ts
  test/e2e/specs/authentication/authentication__google.ts
Labels: [Status] Needs Review

#86846 Membership: Enable/disable auto-renew in memberships
  client/me/memberships/subscription.jsx
  client/me/purchases/membership-item/index.tsx
  client/me/purchases/remove-purchase/style.scss
  client/state/action-types.ts
  client/state/memberships/subscriptions/actions.js
  client/state/memberships/subscriptions/reducer.js
  client/state/memberships/subscriptions/selectors.js
Labels: [Status] Needs Review, [Status] String Freeze

#87231 Overwrite useSubscribersQuery loading state.
  client/my-sites/subscribers/queries/use-subscribers-query.tsx
Labels: [Status] Needs Review

#86497 Stepper: Rename the SiteCreationStep to CreateSite
  client/landing/stepper/README.md
  client/landing/stepper/declarative-flow/ai-assembler.ts
  client/landing/stepper/declarative-flow/assembler-first-flow.ts
  client/landing/stepper/declarative-flow/connect-domain.ts
  client/landing/stepper/declarative-flow/copy-site.tsx
  client/landing/stepper/declarative-flow/design-first.ts
  client/landing/stepper/declarative-flow/free.ts
  client/landing/stepper/declarative-flow/hundred-year-plan.ts
  client/landing/stepper/declarative-flow/import-flow.ts
  client/landing/stepper/declarative-flow/import-hosted-site.ts
  client/landing/stepper/declarative-flow/internals/analytics/record-submit-step.ts
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/create-site/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/create-site/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/hooks/use-processing-loading-messages.tsx
  client/landing/stepper/declarative-flow/internals/steps.tsx
  client/landing/stepper/declarative-flow/link-in-bio-domain.ts
  client/landing/stepper/declarative-flow/link-in-bio-tld.ts
  client/landing/stepper/declarative-flow/link-in-bio.ts
  client/landing/stepper/declarative-flow/new-hosted-site-flow.ts
  client/landing/stepper/declarative-flow/newsletter.ts
  client/landing/stepper/declarative-flow/reblogging.ts
  client/landing/stepper/declarative-flow/start-writing.ts
  client/landing/stepper/declarative-flow/tailored-ecommerce-flow.ts
  client/landing/stepper/declarative-flow/trial-wooexpress-flow.ts
  client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-registration.tsx
  packages/onboarding/src/flow-progress/use-flow-progress.ts
Labels: [Status] Needs Review, Stepper

#87229 Checkout: fix chargeback-only display issues
  client/my-sites/checkout/src/components/CheckoutMoneyBackGuarantee.jsx
  client/my-sites/checkout/src/components/wp-checkout-order-summary.tsx
  client/my-sites/checkout/src/components/wp-checkout.tsx
Labels: [Status] Needs Review, [Feature] Checkout

#86830 Checkoutv2: Term variant picker dropdown
  client/my-sites/checkout/src/components/item-variation-picker/styles.tsx
Labels: [Status] Needs Review

#87248 Checkout: Update PixConfirmation to use the correct code for its QR code
  client/my-sites/checkout/src/lib/pix-confirmation.tsx
  client/my-sites/checkout/src/lib/pix-processor.ts
  packages/wpcom-checkout/src/types.ts
Labels: [Status] Needs Review

#86725 Reuse existing type 'PlanFeaturesForGridPlan'
  packages/plans-grid-next/src/types.ts
Labels: [Status] Needs Review

#87206 Plans 2023: Abstract plans grid dropdown options
  packages/plans-grid-next/src/components/dropdown-option.tsx
  packages/plans-grid-next/src/components/plan-type-selector/components/interval-type-dropdown.tsx
  packages/plans-grid-next/src/components/plan-type-selector/style.scss
  packages/plans-grid-next/src/components/storage-add-on-dropdown.tsx
  packages/plans-grid-next/src/style.scss
Labels: [Status] Needs Review, 2023 Pricing Page ⚡, Plan Type Selector

#87246 Stats: Avoid fetching notice flag for non-admins
  client/my-sites/stats/hooks/use-notice-visibility-query.ts
  client/my-sites/stats/stats-redirect/index.tsx
Labels: Stats, [Status] Needs Review

#87209 Remove hotjar tracking from unused instances
  client/my-sites/customer-home/main.jsx
  client/my-sites/importer/importing-pane.jsx
  client/my-sites/people/invite-people/index.jsx
  client/my-sites/plans/main.jsx
Labels: [Status] Needs Review

#85866 For Jetpack Sharing Buttons block add learn more link
  apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-description-links/src/block-links-map.ts
Labels: [Status] Needs Review, Blocks, [Plugin] Jetpack

#87255 [Continue with GitHub] response handler scaffolding
  client/blocks/authentication/social/index.tsx
  client/blocks/login/social.jsx
  client/blocks/signup-form/social.jsx
  client/components/social-buttons/github.tsx
Labels: [Status] Needs Review

#87003 Plans Next: Untangle Comparison Grid from media queries, up reuse and default responsiveness
  client/my-sites/plans-features-main/components/comparison-grid-toggle.tsx
  client/my-sites/plans-features-main/media-queries.tsx
  client/my-sites/plans-features-main/style.scss
  client/signup/steps/plans/style.scss
  packages/plans-grid-next/src/_media-queries.scss
  packages/plans-grid-next/src/_mixins.scss
  packages/plans-grid-next/src/components/comparison-grid/index.tsx
  packages/plans-grid-next/src/css-mixins.tsx
  packages/plans-grid-next/src/index.tsx
  packages/plans-grid-next/src/media-queries.tsx
  packages/plans-grid-next/src/style.scss
  packages/plans-grid-next/src/util.ts
Labels: [Status] Needs Review, Plans: NPM essential

#87218 Revert "Revert "Launchpad: Clean up task-helper""
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/bio/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/bio/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/design/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/domain/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/domain/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/payments/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/plan/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/plan/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/post/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/post/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/setup/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/setup/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/site/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/task-helper.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/types.ts
Labels: [Status] Needs Review

#87240 Fix Jetpack menu item on Cloud sidebar menu
  client/state/sites/selectors/get-site-admin-page.js
Labels: [Status] Needs Review

#87243 Checkout: Remove custom multi-year discount from Jetpack plans
  client/my-sites/checkout/src/components/jetpack-akismet-checkout-sidebar-plan-upsell/index.tsx
  client/my-sites/checkout/src/components/wp-checkout-order-summary.tsx
  packages/wpcom-checkout/src/transformations.ts
Labels: [Status] Needs Review, [Feature] Checkout

#87279 Theme Tiers: Fix pub/ Premium Themes in Onboarding
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  test/e2e/specs/onboarding/signup__with-theme-premium.ts
Labels: [Status] Needs Review, [Feature] Design Picker

#87251 JP Manage: 281 - refine pricing page routing path
  client/sections.js
Labels: [Status] Needs Review, [Status] Needs Author Reply

#87275 Stats: Make the Plan Usage section background solid
  client/my-sites/stats/stats-plan-usage/style.scss
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#87276 Stats: Refactor Stats page elements layout distance
  client/my-sites/stats/modernized-layout-styles.scss
  client/my-sites/stats/post-trends/style.scss
  client/my-sites/stats/stats-heap-map/style.scss
  client/my-sites/stats/wordads/earnings.scss
Labels: Stats, [Status] Needs Review, Reviewer Can Merge

#87214 Stats: Add mobile version of Subscriber highlights
  client/my-sites/stats/stats-subscribers-highlight-section/index.tsx
  client/my-sites/stats/stats-subscribers-highlight-section/style.scss
Labels: Stats, [Status] Needs Review, [Status] Needs Design Review, [Status] Design Input Requested, Reviewer Can Merge

#87254 Back buttons goes back to correct settings page for transfer, reset, delete site pages
  client/my-sites/site-settings/delete-site/index.jsx
  client/my-sites/site-settings/section-general.jsx
  client/my-sites/site-settings/site-owner-transfer/site-owner-transfer.tsx
  client/my-sites/site-settings/site-tools/index.jsx
  client/my-sites/site-settings/site-tools/utils.ts
  client/my-sites/site-settings/start-over.jsx
  client/my-sites/site-settings/wpcom-site-tools-settings/index.jsx
Labels: [Status] Needs Review

#87073 [WooCommerce] Fix inconsistent social login screen when email matches an existing account
  client/blocks/login/index.jsx
  client/blocks/login/login-form.jsx
  client/layout/masterbar/woo.scss
  client/lib/login/index.js
  client/login/magic-login/emailed-login-link-successfully.jsx
  client/login/magic-login/index.jsx
Labels: [Status] Needs Review

#87282 Migration flow: Extend list of hosts with Pressable with support link
  client/components/advanced-credentials/host-info.ts
Labels: [Status] Needs Review

#87271 Plans Next: Fix comparison grid stretching infinitely
  packages/plans-grid-next/src/components/comparison-grid/index.tsx
Labels: [Status] Needs Review, Plans: NPM essential

#87256 Modularize Launch Site and add Launch Site button to Site Tools
  client/my-sites/site-settings/form-general.jsx
  client/my-sites/site-settings/site-visibility/launch-site-trial-notice.jsx
  client/my-sites/site-settings/site-visibility/launch-site.jsx
  client/my-sites/site-settings/site-visibility/styles.scss
  client/my-sites/site-settings/style.scss
  client/my-sites/site-settings/wpcom-site-tools-settings/index.jsx
Labels: [Status] Needs Review

#87228 feat(developer): new dev survey notice
  client/assets/images/illustrations/developer-survey.svg
  client/me/developer/dev-survey-notice.tsx
  client/me/developer/main.jsx
  client/me/developer/style.scss
Labels: [Status] Needs Review, [Status] String Freeze

#87288 Untangle: Remove import-php URL override
  client/state/data-layer/wpcom/sites/admin-menu/index.js
Labels: [Status] Needs Review

#87266 Remove multi year discount line from upsell
  client/my-sites/checkout/src/components/jetpack-akismet-checkout-sidebar-plan-upsell/index.tsx
Labels: [Status] Needs Review

#86612 Domains: Add option to restore default email records in DNS management page
  client/my-sites/domains/domain-management/dns/dns-menu-options-button.tsx
  client/my-sites/domains/domain-management/dns/dns-records.jsx
  client/my-sites/domains/domain-management/dns/restore-default-email-records-dialog.jsx
  client/my-sites/domains/domain-management/dns/types.ts
Labels: [Status] Needs Review

#87313 Untangle: Move `recordTracksEventForTrialNoticeClick` to `LaunchSiteTrialUpsellNotice`
  client/my-sites/site-settings/form-general.jsx
  client/my-sites/site-settings/site-visibility/launch-site-trial-notice.jsx
Labels: [Status] Needs Review

#87317 Revert modularize launch from general settings
  client/my-sites/site-settings/form-general.jsx
Labels: [Status] Needs Review

#87253 Plans Next: Cleanup calls to `useUpgradeClickHandler`
  packages/plans-grid-next/src/components/comparison-grid/index.tsx
  packages/plans-grid-next/src/components/features-grid/index.tsx
  packages/plans-grid-next/src/hooks/use-upgrade-click-handler.ts
  packages/plans-grid-next/src/index.tsx
  packages/plans-grid-next/src/types.ts
Labels: [Status] Needs Review, Plans: NPM essential

#87127 Assembler: Enabled feature flag pattern-assembler/v2 for the release of v2 patterns
  config/development.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#87257 Jetpack Manage: Fix the issue with Atomic sites showing managed plugins requiring updates.
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-content/hooks/use-formatted-sites.ts
Labels: [Status] Needs Review, Jetpack Cloud

#87299 Import content onboarding flow: Fix the ProgressBar screen alignments
  client/blocks/importer/components/progress-screen/index.tsx
  client/blocks/importer/wordpress/import-content-only/index.tsx
Labels: [Status] Needs Review

#87287 JP Manage: 283 - show pricing page in non-English languages (and other goodies)
  client/components/jetpack/intro-pricing-banner/index.tsx
  client/jetpack-cloud/sections/manage/pricing/index.node.ts
  client/jetpack-cloud/sections/manage/pricing/index.web.js
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/featured-license-multi-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/license-products-list/simple-license-multi-item-card.tsx
  client/jetpack-cloud/sections/manage/pricing/package.json
  client/jetpack-cloud/sections/manage/pricing/pricing-license-selector/style.scss
  client/jetpack-cloud/sections/manage/pricing/pricing-need-more-info/index.tsx
  client/jetpack-cloud/sections/manage/pricing/primary/index.tsx
  client/lib/jetpack/paths.ts
  client/my-sites/plans/jetpack-plans/product-store/need-more-info/index.tsx
  client/sections.js
  packages/i18n-utils/src/localize-url.tsx
  packages/i18n-utils/src/test/localize-url.js
Labels: [Status] Needs Review

#87298 Plans 2023: Refactor interval type toggle on change handler
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/plans-wrapper.tsx
  client/my-sites/plans-features-main/components/plan-interval-selector/index.tsx
  client/my-sites/plans-features-main/index.tsx
  client/my-sites/plans/ecommerce-trial/wooexpress-plans/index.tsx
  packages/components/src/segmented-control/item.jsx
  packages/plans-grid-next/src/components/plan-type-selector/components/interval-type-dropdown.tsx
  packages/plans-grid-next/src/components/plan-type-selector/components/interval-type-toggle.tsx
  packages/plans-grid-next/src/components/plan-type-selector/utils.ts
  packages/plans-grid-next/src/types.ts
Labels: [Status] Needs Review, 2023 Pricing Page ⚡, Plan Type Selector

#87348 Jetpack Backup: Add BackupNowButton component scaffolding
  client/components/jetpack/backup-now-button/README.md
  client/components/jetpack/backup-now-button/index.tsx
Labels: [Status] Needs Review, [Feature] Backups

#86949 E2E: Add GutenbergCoreE2E TC project
  .teamcity/_self/projects/WPComTests.kt
  .teamcity/settings.kts
Labels: [Status] Needs Review

#87352 Jetpack Backup: Add feature flag for on demand backups
  client/my-sites/backup/main.jsx
  client/my-sites/backup/style.scss
  config/development.json
  config/jetpack-cloud-development.json
Labels: [Status] Needs Review, [Feature] Backups

#87357 Jetpack Backup: Connect BackupNowButton to rewindBackupSite
  client/components/jetpack/backup-now-button/index.tsx
  client/my-sites/backup/main.jsx
Labels: [Status] Needs Review, [Feature] Backups

#87356 Jetpack Backup: Add backup actions toolbar
  client/components/jetpack/backup-actions-toolbar/README.md
  client/components/jetpack/backup-actions-toolbar/index.tsx
  client/components/jetpack/backup-actions-toolbar/style.scss
  client/my-sites/backup/main.jsx
Labels: [Status] Needs Review, [Feature] Backups

#87358 Jetpack Backup: Improve actions toolbar on mobile resolutions
  client/components/jetpack/backup-actions-toolbar/style.scss
Labels: [Status] Needs Review, [Feature] Backups

#87359 Jetpack Backup: Update disabled state, button label and tooltip for BackupNowButton
  client/components/jetpack/backup-now-button/README.md
  client/components/jetpack/backup-now-button/index.tsx
Labels: [Status] Needs Review, [Feature] Backups

#87360 Jetpack Backups: Disable the backup button if backup in progress
  client/components/jetpack/backup-now-button/index.tsx
Labels: [Status] Needs Review, [Feature] Backups

#87362 Checkout: Disable Pix for production
  client/my-sites/checkout/src/hooks/use-create-payment-methods/index.tsx
  config/development.json
  config/horizon.json
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Feature] Checkout

#87315 Stats: Fix purchase recoganization on Odyssey
  apps/odyssey-stats/src/components/odyssey-query-products.ts
  apps/odyssey-stats/src/components/odyssey-query-site-purchases.ts
  client/my-sites/stats/stats-redirect/index.tsx
  client/my-sites/stats/stats-redirect/load-stats-page.tsx
Labels: Stats, [Status] Needs Review

#87371 Stats: Query purchase for Calypso Stats too
  client/my-sites/stats/stats-notices/index.tsx
  client/my-sites/stats/stats-redirect/index.tsx
  client/my-sites/stats/stats-redirect/load-stats-page.tsx
Labels: Stats, [Status] Needs Review

#87292 Implement a new Calypso Environment for Automattic for Agencies
  bin/feature-search.js
  client/a8c-for-agencies/controller.tsx
  client/a8c-for-agencies/index.tsx
  client/sections.js
  client/server/pages/index.js
  config/README.md
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-production.json
  config/a8c-for-agencies-stage.json
  package.json
  packages/calypso-config/src/index.ts
  packages/wpcom-proxy-request/src/index.js
Labels: [Status] Needs Review, DO NOT MERGE, A8c Agencies

#87258 wp-babel-makepot: Use @babel/preset-env for default preset
  packages/wp-babel-makepot/CHANGELOG.md
  packages/wp-babel-makepot/package.json
  packages/wp-babel-makepot/presets/default.js
  packages/wp-babel-makepot/test/__snapshots__/index.js.snap
  packages/wp-babel-makepot/test/examples/private-fields.js
  yarn.lock
Labels: [Status] Needs Review, i18n, Packages

#87378 Assembler: Make headers and footers always prioritized so they aren't all of them featured in the editor
  client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/utils.ts
Labels: [Status] Needs Review

#87381 Components: Refactor PlanStorage away from Reakit, remove Reakit dependency
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/blocks/plan-storage/index.jsx
  client/blocks/plan-storage/style.scss
  client/blocks/plan-storage/tooltip.jsx
  client/package.json
  packages/components/src/tooltip/index.jsx
  yarn.lock
Labels: [Type] Enhancement, Components, dependencies

#87363 Jetpack Backup: Update backup button labels and catch in progress status when queuing a new backup
  client/components/jetpack/backup-actions-toolbar/index.tsx
  client/components/jetpack/backup-now-button/README.md
  client/components/jetpack/backup-now-button/index.tsx
Labels: [Status] Needs Review, [Feature] Backups

#87386 Site Migration: Add feature flag for the site migration flow
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Stepper, Site Migration

#87388 E2E: Fix Jetpack Related Posts block test
  packages/calypso-e2e/src/lib/blocks/block-flows/related-posts.ts
Labels: [Status] Needs Review

#87252 Stats: Refactoring controller and page files
  client/my-sites/stats/controller.jsx
  client/my-sites/stats/pages/insights/controller.tsx
  client/my-sites/stats/pages/insights/index.jsx
  client/my-sites/stats/pages/purchase/controller.tsx
  client/my-sites/stats/pages/purchase/index.tsx
  client/my-sites/stats/pages/shared/helpers.tsx
  client/my-sites/stats/pages/shared/page-loading.tsx
  client/my-sites/stats/pages/subscribers/controller.tsx
  client/my-sites/stats/pages/subscribers/index.tsx
Labels: Stats, [Status] Needs Review

#87401 GitHub Deployments: Remove old code and rename feature flag
  client/my-sites/github-deployments/controller.tsx
  client/my-sites/hosting/github/constants.ts
  client/my-sites/hosting/github/deployment-card/deployment-status-badge.tsx
  client/my-sites/hosting/github/deployment-card/deployment-status-explanation.tsx
  client/my-sites/hosting/github/deployment-card/empty-deployments.tsx
  client/my-sites/hosting/github/deployment-card/index.tsx
  client/my-sites/hosting/github/deployment-card/last-deployment-information.tsx
  client/my-sites/hosting/github/deployment-card/style.scss
  client/my-sites/hosting/github/deployment-card/use-deployment-logs-url.ts
  client/my-sites/hosting/github/deployment-card/use-deployment-status-query.ts
  client/my-sites/hosting/github/deployment-card/use-disconnect-repo.ts
  client/my-sites/hosting/github/disconnect-github-button/index.tsx
  client/my-sites/hosting/github/disconnect-github-button/style.scss
  client/my-sites/hosting/github/github-authorize-card/index.tsx
  client/my-sites/hosting/github/github-card-heading/index.tsx
  client/my-sites/hosting/github/github-card-heading/style.scss
  client/my-sites/hosting/github/github-connect-card/index.tsx
  client/my-sites/hosting/github/github-connect-card/search-branches.tsx
  client/my-sites/hosting/github/github-connect-card/search-repos.tsx
  client/my-sites/hosting/github/github-connect-card/search.tsx
  client/my-sites/hosting/github/github-connect-card/style.scss
  client/my-sites/hosting/github/github-connect-card/use-github-branches-query.ts
  client/my-sites/hosting/github/github-connect-card/use-github-connect-mutation.ts
  client/my-sites/hosting/github/github-connect-card/use-github-repos-query.ts
  client/my-sites/hosting/github/github-placeholder-card/index.tsx
  client/my-sites/hosting/github/index.tsx
  client/my-sites/hosting/github/style.scss
  client/my-sites/hosting/github/use-github-connection-query.ts
  client/my-sites/hosting/main.js
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
  config/development.json
  config/wpcalypso.json
Labels: [Status] Needs Review, GitHub Deployments i1

#87370 Odyssey Stats: Link Store Stats to Woo Analytics
  client/blocks/stats-navigation/index.js
Labels: Stats, [Status] Needs Review

#87396 Jetpack Backup: Release on demand backups
  client/components/jetpack/backup-actions-toolbar/index.tsx
  client/my-sites/backup/main.jsx
  client/my-sites/backup/style.scss
  config/development.json
  config/jetpack-cloud-development.json
Labels: [Status] Needs Review, [Feature] Backups
