Repository Automattic/wp-calypso, pull requests merged in 2024-06, with the labels that each got.

#91376 Revert "Update domain messaging in paid media flow"
  client/components/domains/register-domain-step/index.jsx
  client/components/domains/register-domain-step/style.scss
  client/signup/config/flows-pure.js
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review

#91381 Plans revert experiment: Refactor call to `getPlansListExperiment()`.
  packages/calypso-products/src/plans.tsx
Labels: [Status] Needs Review

#91379 Add translator comments
  client/blocks/importer/wordpress/upgrade-plan/index.tsx
  client/dev-tools/components/dev-tools.tsx
  client/landing/stepper/declarative-flow/internals/components/migration-assistance-modal/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-import-or-migrate/index.tsx
  client/my-sites/plans/ecommerce-trial/entrepreneur-plan/entrepreneur-plan.tsx
  client/my-sites/plans/main.jsx
Labels: [Status] Needs Review

#91289 Command palette: Add more commands (1st batch)
  packages/command-palette/package.json
  packages/command-palette/src/commands.tsx
  yarn.lock
Labels: [Status] Needs Review

#91328 Entrepreneur Flow: Fix Signup `trialAcknowledge` step redirection
  client/landing/stepper/declarative-flow/entrepreneur-flow.ts
  client/landing/stepper/utils/path.ts
  client/signup/reskinned-processing-screen/index.jsx
Labels: [Status] Needs Review

#90809 Add intent based plans
  client/components/segmentation-survey/constants.ts
  client/components/segmentation-survey/hooks/use-segmentation-survey-navigation.ts
  client/components/segmentation-survey/index.tsx
  client/components/survey-container/components/survey-flow-card.tsx
  client/my-sites/plans/utils/get-segmented-intent.tsx
  client/signup/config/flows-pure.js
  client/signup/config/steps-pure.js
  client/signup/hooks/use-guided-flow-get-segment.tsx
  client/signup/steps/initial-intent/constants.ts
  client/signup/steps/initial-intent/index.tsx
  client/signup/steps/plans/index.jsx
  client/state/signup/progress/actions.js
  packages/plans-grid-next/src/hooks/data-store/use-grid-plans.tsx
  packages/plans-grid-next/src/types.ts
Labels: [Status] Needs Review, Guided Onboarding

#91347 Command palette: Add more commands (2nd batch)
  packages/command-palette/src/commands.tsx
  packages/command-palette/src/use-command-palette.tsx
Labels: [Status] Needs Review

#91250 Plugins page: Align header style with domains and sites pages
  client/layout/style.scss
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/plugins/plugins-browser/style.scss
  client/my-sites/plugins/plugins-navigation-header/index.jsx
  client/my-sites/plugins/plugins-navigation-header/style.scss
  client/my-sites/plugins/style.scss
Labels: [Status] Needs Review

#91402 Feature List Cleanup: Part 3
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/feature-group-plan-map.ts
  packages/calypso-products/src/features-list.tsx
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review

#91346 Notifications: use absolute widgets.wp.com links in iframe HTML
  apps/notifications/src/index.ejs
  apps/notifications/webpack.config.js
Labels: [Status] Needs Review, [Feature] Notifications, Build

#91385 Command palette: Add more commands (3rd batch)
  packages/command-palette/src/commands.tsx
Labels: [Status] Needs Review

#91389 Command Palette: Add specific keywords for common settings
  packages/command-palette/src/commands.tsx
Labels: [Status] Needs Review

#91387 Profile: Add UI frame to /help
  client/me/help/style.scss
  client/me/style.scss
Labels: [Status] Needs Review

#91406 Guided Onboarding: Redirect newsletter directly to setup
  client/signup/steps/initial-intent/index.tsx
Labels: [Status] Needs Review, Guided Onboarding

#91396 Scheduled Updates: Optimize styles and data presentation for the lower resolution
  client/blocks/plugin-scheduled-updates-common/hooks/use-date-time-format.ts
  client/blocks/plugin-scheduled-updates-common/styles.scss
  client/blocks/plugins-scheduled-updates-multisite/schedule-list-last-run-status.tsx
  client/blocks/plugins-scheduled-updates-multisite/schedule-list-table-row.tsx
  client/blocks/plugins-scheduled-updates-multisite/schedule-list-table.tsx
  client/blocks/plugins-scheduled-updates-multisite/styles.scss
  client/blocks/plugins-scheduled-updates/schedule-list-table.tsx
  client/blocks/plugins-scheduled-updates/styles.scss
Labels: [Status] Needs Review

#91364 Jetpack Cloud Classic: Update Activity log upsells for wpcom
  client/components/activity-card-list/index.jsx
  client/components/activity-card/plan-upsell.tsx
  client/my-sites/activity/activity-log-v2/index.tsx
Labels: [Status] Needs Review

#90966 Update metrics presented on import flow
  client/blocks/importer/wordpress/upgrade-plan/constants.tsx
  client/blocks/importer/wordpress/upgrade-plan/cwvtech-report.json
  client/blocks/importer/wordpress/upgrade-plan/hooks/use-get-upgrade-plan-hosting-details-list.tsx
  client/blocks/importer/wordpress/upgrade-plan/upgrade-plan-hosting-details.tsx
  client/blocks/importer/wordpress/upgrade-plan/use-default-hosting-details.tsx
  client/blocks/importer/wordpress/upgrade-plan/wordpress-cwvtech-report.json
Labels: [Status] Needs Review, [Status] String Freeze

#91418 Site Migrations: Update permissions check from owner to admin
  client/landing/stepper/declarative-flow/site-migration-flow.ts
  client/landing/stepper/declarative-flow/test/site-migration-flow.tsx
Labels: [Status] Needs Review, Site Migration

#91354 A4A: add referrals guide content
  client/a8c-for-agencies/components/guide-modal/guides/useReferralsGuide.tsx
  client/a8c-for-agencies/components/guide-modal/index.tsx
  client/a8c-for-agencies/components/guide-modal/style.scss
  client/a8c-for-agencies/sections/marketplace/common/referral-toggle/style.scss
  client/assets/images/a8c-for-agencies/referral-step-1.jpg
  client/assets/images/a8c-for-agencies/referral-step-2.jpg
  client/assets/images/a8c-for-agencies/referral-step-3.jpg
  client/assets/images/a8c-for-agencies/referral-step-4.jpg
  client/assets/images/a8c-for-agencies/referral-step-5.jpg
  client/assets/images/a8c-for-agencies/referral-step-background.png
Labels: [Status] Needs Review, A4A

#91427 Site Migration: redirect to site-migration from Calypso
  client/lib/importer/importer-config.tsx
Labels: [Status] Needs Review

#91340 Site Migration: Remove new migration flow feature flag
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/goals.tsx
  client/landing/stepper/declarative-flow/registered-flows.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, Site Migration

#91029 Domains: Remove CTAs from Gravatar flow
  client/components/domains/register-domain-step/index.jsx
  client/lib/domains/registration/availability-messages.js
Labels: [Status] Needs Review

#91431 Revert "Domains: Remove CTAs from Gravatar flow"
  client/components/domains/register-domain-step/index.jsx
  client/lib/domains/registration/availability-messages.js
Labels: [Status] Needs Review

#91368 Jetpack Backup: add some additional Tracks events on Storage Retention settings and update `Learn more` link
  client/components/backup-retention-management/index.tsx
  client/components/backup-retention-management/info-tooltip/index.tsx
  client/components/backup-retention-management/info-tooltip/style.scss
Labels: [Status] Needs Review

#91369 Jetpack Backup: add some additional Tracks events on Staging Site settings
  client/components/jetpack-staging-sites-management/index.tsx
Labels: [Status] Needs Review, [Feature] Backups

#91383 Global Sidebar: Support url param 'from'
  client/layout/global-sidebar/main.jsx
  client/me/help/controller.js
Labels: [Status] Needs Review

#90534 CheckoutV2 tidying: Add prop to show or hide features list in checkout
  client/my-sites/checkout/src/components/checkout-main-content.tsx
  client/my-sites/checkout/src/components/wp-checkout-order-summary.tsx
  client/my-sites/checkout/src/test/wp-checkout-order-summary.tsx
Labels: [Status] Needs Review

#91391 Add feature flag jetpack/manage-simple-sites to config
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
Labels: [Status] Needs Review

#91434 Site Management Panel: Update tab names
  client/dev-tools/components/dev-tools.tsx
  client/my-sites/hosting/main.js
  client/sites-dashboard-v2/site-preview-pane/dotcom-preview-pane.tsx
Labels: [Status] Needs Review

#91362 Jetpack Cloud Classic: Point Start earning link to /monetize
  client/my-sites/subscribers/components/grow-your-audience/grow-your-audience.tsx
Labels: [Status] Needs Review

#91407 (Take 2) explat-client: calypso-lib: Skip requests for E2E
  client/lib/explat/internals/fetch-experiment-assignment.ts
Labels: [Status] Needs Review

#91257 Stats: Query paid subscribers for another series on the Subscriber Stats chart
  client/my-sites/stats/hooks/use-subscribers-query.tsx
  client/my-sites/stats/stats-subscribers-chart-section/index.tsx
  packages/components/src/chart-uplot/index.tsx
Labels: Stats, [Status] Needs Review, [Stats] Subscribers

#91384 Help Center: Improve the a11y
  client/blocks/inline-help/inline-help-search-card.tsx
  client/layout/global-sidebar/menu-items/help-center/help-center.jsx
  packages/help-center/src/components/back-button.tsx
  packages/help-center/src/components/help-center-container.tsx
  packages/help-center/src/components/help-center-content.tsx
  packages/help-center/src/components/help-center-search.scss
  packages/help-center/src/styles.scss
  packages/odie-client/src/components/message/jump-to-recent.tsx
  packages/odie-client/src/components/message/style.scss
Labels: [Status] Needs Review

#91404 Feature List Cleanup: Part 3
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/features-list.tsx
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review

#91441 Help Center: Don't auto focus on the input on custom home
  client/blocks/inline-help/inline-help-search-card.tsx
Labels: [Status] Needs Review

#91401 Feature List Cleanup: Part 2
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/feature-group-plan-map.ts
  packages/calypso-products/src/features-list.tsx
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review

#91443 Revert update webpack packages
  apps/blaze-dashboard/package.json
  apps/command-palette-wp-admin/package.json
  apps/editing-toolkit/package.json
  apps/odyssey-stats/package.json
  apps/wpcom-block-editor/package.json
  package.json
  packages/calypso-build/package.json
  yarn.lock
Labels: [Status] Needs Review

#91392 Replace references to email support
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/wpcom-card/hooks/use-wpcom-plan-description.ts
  client/blocks/eligibility-warnings/hold-list.tsx
  client/components/marketing-survey/cancel-purchase-form/step-components/upsell-step.tsx
  client/my-sites/checkout/src/components/wp-checkout-order-summary.tsx
  client/my-sites/checkout/src/lib/get-plan-features.ts
Labels: [Status] Needs Review

#91438 Calypso - Remove hosting overview menu option
  client/my-sites/sidebar/use-site-menu-items.js
Labels: [Status] Needs Review

#91439 Jetpack Cloud pricing | Replace Social plans with the new v1 plan
  client/my-sites/plans/jetpack-plans/product-store/utils/get-product-icon.ts
  client/my-sites/plans/jetpack-plans/product-store/utils/get-sorted-displayable-products.ts
  client/my-sites/plans/jetpack-plans/use-get-plans-grid-products.ts
  config/development.json
  config/horizon.json
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
  config/production.json
  config/stage.json
  packages/calypso-products/src/translations.tsx
Labels: [Status] Needs Review

#91400 Feature List Cleanup: Part 1
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/feature-group-plan-map.ts
  packages/calypso-products/src/features-list.tsx
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/types.ts
Labels: [Status] Needs Review

#91386 Subscriptions: Add the Subscribe block navigation placement toggle
  client/my-sites/site-settings/settings-newsletter/SubscribeNavigationSetting.tsx
  client/my-sites/site-settings/settings-newsletter/main.tsx
  client/my-sites/site-settings/settings-reading/main.tsx
  client/my-sites/site-settings/wrap-settings-form.jsx
Labels: [Status] Needs Review, [Status] String Freeze, [Feature] Subscriptions

#91394 Scheduled Updates: Only load the component if it's not loading
  client/blocks/plugins-scheduled-updates-multisite/schedule-list.tsx
Labels: [Status] Needs Review

#91413 clsx: consistent import names
  apps/editing-toolkit/editing-toolkit-plugin/help-center/src/help-center.js
  client/components/marketing-message/index.tsx
  packages/design-carousel/src/item.tsx
  packages/site-picker/src/index.tsx
  packages/social-previews/src/nextdoor-preview/post-preview.tsx
Labels: [Type] Enhancement, Framework, [Status] Needs Review

#91421 Help center - don't show whats new menu item if there are no announcements.
  packages/help-center/src/components/help-center-more-resources.tsx
Labels: [Status] Needs Review

#91449 A4A: Add Form layout.
  client/a8c-for-agencies/components/form/field/index.tsx
  client/a8c-for-agencies/components/form/field/style.scss
  client/a8c-for-agencies/components/form/index.tsx
  client/a8c-for-agencies/components/form/section/index.tsx
  client/a8c-for-agencies/components/form/section/style.scss
  client/a8c-for-agencies/components/form/style.scss
Labels: [Status] Needs Review, A8c Agencies

#91398 Notifications: Focus the first element when opening
  apps/notifications/src/panel/boot/stylesheets/main.scss
  apps/notifications/src/panel/templates/filter-bar.jsx
  apps/notifications/src/panel/templates/index.jsx
  apps/notifications/src/panel/templates/note-list.jsx
  apps/notifications/src/panel/templates/note.jsx
  client/layout/global-notifications/index.tsx
  client/notifications/index.jsx
  client/notifications/style.scss
Labels: [Status] Needs Review

#90060 Nav Redesign: Enable flag on production
  config/production.json
Labels: DO NOT MERGE

#91450 Scheduled Updates: Hide update status text and frequency column when data is expanded
  client/blocks/plugins-scheduled-updates-multisite/schedule-list-last-run-status.tsx
  client/blocks/plugins-scheduled-updates-multisite/schedule-list-table-row.tsx
Labels: [Status] Needs Review

#91466 Guided Onboarding: Switch to site-migration
  client/signup/steps/initial-intent/index.tsx
Labels: [Status] Needs Review, Guided Onboarding

#91467 A4A: Improve agency signup form spacing on mobile
  client/a8c-for-agencies/sections/signup/signup-form/style.scss
Labels: Design, A4A

#91444 Guided Onboarding: deemphasize free plan for paid domains
  client/my-sites/plans-features-main/components/plans-page-subheader.tsx
  client/my-sites/plans-features-main/index.tsx
  client/signup/steps/plans/index.jsx
Labels: [Status] Needs Review, Guided Onboarding

#91464 Guided Onboarding: fix back button in domains step
  client/components/segmentation-survey/hooks/use-segmentation-survey-navigation.ts
  client/components/segmentation-survey/index.tsx
  client/signup/steps/initial-intent/index.tsx
Labels: [Status] Needs Review

#91465 A8C For Agencies: Fix empty and disabled states for site tags and add copy
  client/a8c-for-agencies/components/agency-site-tags/index.tsx
Labels: A8c Agencies

#91455 Guided onboarding: fix back button in domains step
  client/components/segmentation-survey/hooks/use-segmentation-survey-navigation.ts
  client/components/segmentation-survey/index.tsx
  client/signup/steps/domains/index.jsx
  client/signup/steps/initial-intent/index.tsx
Labels: [Status] Needs Review, Guided Onboarding

#90033 Nav Redesign: drop the early access gating
  client/state/sites/selectors/is-global-site-view-enabled.ts
Labels: [Status] Needs Review, DO NOT MERGE

#91425 Site Profiler: Use the translate method to display milliseconds
  client/data/site-profiler/metrics-dictionaries.ts
  client/site-profiler/components/basic-metrics/index.tsx
  client/site-profiler/components/metrics-insight/insight-table.tsx
Labels: [Status] Needs Review

#91471 Reader - Removed background color from Reader cards
  client/blocks/reader-post-card/style.scss
Labels: [Status] Needs Review

#91433 A4A: update Referral guide modal wording
  client/a8c-for-agencies/components/guide-modal/guides/useReferralsGuide.tsx
Labels: [Status] Needs Review, A4A

#91463 Renovate: Update reviewer team
  renovate.json5
Labels: [Status] Needs Review

#91476 Segmentation Survey: Fix Invalid Data issue when saving answers for previously skipped questions
  client/components/segmentation-survey/index.tsx
Labels: [Status] Needs Review

#91348 Guided Onboarding Flow: Store additional data after survey is completed
  client/lib/signup/step-actions/index.js
  client/my-sites/plans/utils/get-segmented-intent.tsx
  client/signup/config/steps-pure.js
  client/signup/steps/initial-intent/index.tsx
  client/signup/steps/initial-intent/types.ts
  client/signup/steps/plans/index.jsx
Labels: [Status] Needs Review, Guided Onboarding

#91470 Subscription Management: Fix focus outline and column sizes on Comment Subscriptions page
  client/landing/subscriptions/components/comment-list/styles.scss
Labels: [Status] Needs Review

#91480 Site Migration: Remove Domains step migration card experiment code.
  client/components/domains/reskin-side-explainer/index.jsx
  client/lib/analytics/signup.js
  client/signup/config/flows-pure.js
  client/signup/main.jsx
  client/signup/steps/domains/index.jsx
  client/signup/steps/domains/style.scss
Labels: [Status] Needs Review

#91485 Github Deployments: Always show deployments survey
  client/my-sites/github-deployments/components/deployments-survey/index.tsx
  client/my-sites/github-deployments/deployments/index.tsx
Labels: [Status] Needs Review, Maintenance, Reviewer Can Merge

#91460 Add `media-feature-parentheses-space-inside: never` rev to ignore list
  .git-blame-ignore-revs
Labels: [Status] Needs Review

#91483 A4A: fix bulk bundle purchases
  client/a8c-for-agencies/sections/marketplace/hooks/use-issue-license-mutation.ts
  client/a8c-for-agencies/sections/marketplace/products-overview/hooks/use-issue-licenses.tsx
Labels: [Status] Needs Review, A4A

#91452 Render Agency Managed Plan in sites overview
  client/hosting-overview/components/plan-card.tsx
Labels: [Status] Needs Review

#91488 A4A: remove Copy site button from sites flyout panel
  client/components/jetpack/backup-actions-toolbar/index.tsx
  client/my-sites/activity/activity-log-v2/index.tsx
Labels: [Status] Needs Review, A4A

#91437 Jetpack Backup: add some additional Tracks events on the backup browser
  client/my-sites/backup/backup-contents-page/file-browser/file-browser-node.tsx
  client/my-sites/backup/backup-contents-page/file-browser/file-preview.tsx
Labels: [Status] Needs Review, [Feature] Backups

#91440 Jetpack Backup: fix Jetpack review prompt Tracks event to trigger only when the review prompt is rendered
  client/blocks/jetpack-review-prompt/index.tsx
Labels: [Status] Needs Review, [Feature] Backups

#91491 Stats: Change L to LL for week formatting
  client/my-sites/stats/stats-chart-tabs/utility.js
Labels: Stats, [Status] Needs Review

#91500 DIFM Content Form: enable filler content for all locales
  client/signup/steps/website-content/section-types/custom-page-details.tsx
  client/signup/steps/website-content/section-types/default-page-details.tsx
Labels: [Status] Needs Review, DIFM Express

#91451 Site Dashboard: Add See all backups link to the backup card
  client/my-sites/hosting/site-backup-card/index.js
  client/my-sites/hosting/site-backup-card/style.scss
Labels: [Status] Needs Review

#91447 A4A > Partner Directory: Implement Welcome View for the Dashboard
  client/a8c-for-agencies/sections/partner-directory/dashboard/index.tsx
  client/a8c-for-agencies/sections/partner-directory/dashboard/style.scss
  client/a8c-for-agencies/sections/partner-directory/partner-directory.tsx
  client/a8c-for-agencies/sections/referrals/common/step-section-item/index.tsx
  client/a8c-for-agencies/sections/referrals/common/step-section-item/style.scss
  client/a8c-for-agencies/sections/referrals/primary/referrals-overview/layout-body-content.tsx
  client/a8c-for-agencies/style.scss
Labels: [Status] Needs Review, A8c Agencies

#91458 Replace FEATURE_LIVE_CHAT_SUPPORT with FEATURE_PRIORITY_24_7_SUPPORT
  client/components/theme-upgrade-modal/index.tsx
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/feature-group-plan-map.ts
  packages/calypso-products/src/features-list.tsx
  packages/calypso-products/src/plans-list.tsx
Labels: [Status] Needs Review

#91456 A4A > Partner Directory: Implement Partner Directory In-Progress view
  client/a8c-for-agencies/sections/partner-directory/dashboard/index.tsx
  client/a8c-for-agencies/sections/partner-directory/dashboard/style.scss
  client/a8c-for-agencies/sections/referrals/common/step-section-item/index.tsx
  client/a8c-for-agencies/sections/referrals/common/step-section-item/style.scss
Labels: [Status] Needs Review, A8c Agencies

#91291 A4A: Product marketplace filtering improvements
  client/a8c-for-agencies/sections/marketplace/lib/product-filter.ts
  client/a8c-for-agencies/sections/marketplace/products-overview/product-filter/hooks/use-product-filter-options.ts
  client/a8c-for-agencies/sections/marketplace/products-overview/product-filter/index.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/product-filter/product-filter-item.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/product-filter/product-filter-select.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/product-filter/style.scss
  client/a8c-for-agencies/sections/marketplace/products-overview/product-listing/empty-result-message.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/product-listing/hooks/use-selected-product-filters.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/product-listing/index.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/product-listing/style.scss
Labels: [Status] Needs Review, A8c Agencies

#91506 Command Palette: Add "Open hosting overview" command to wp-admin app
  packages/command-palette/package.json
  packages/command-palette/src/commands.tsx
  yarn.lock
Labels: [Status] Needs Review

#91448 Site Profiler: Fix scroll for get report form on Mobile
  client/site-profiler/components/get-report-form/styles.scss
Labels: [Status] Needs Review

#91446 Stats: Restore download button on UTM summary page
  client/my-sites/stats/stats-module-utm/index.jsx
Labels: Stats, [Status] Needs Review

#91502 A4A: Add Partner Directory interfaces: AgencyDetails AgencyApplication
  client/a8c-for-agencies/sections/partner-directory/types.ts
Labels: [Status] Needs Review

#91490 Update the Plugins link in /sites Ellipses menu
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
Labels: [Status] Needs Review

#91453 Command palette: Add support for wildcard keywords
  packages/command-palette/src/commands.tsx
  packages/command-palette/src/use-command-filter.ts
  packages/command-palette/test/use-command-filter.tsx
Labels: Hosting Command Palette, Launch Command Palette

#91390 Redirect to Jetpack Cloud for Subscribers View Details in Stats
  client/my-sites/stats/stats-followers/index.jsx
Labels: [Status] Needs Review

#91505 A4A: Add Partner Directory's Expertise form.
  client/a8c-for-agencies/components/form/field/index.tsx
  client/a8c-for-agencies/components/form/field/style.scss
  client/a8c-for-agencies/components/form/style.scss
  client/a8c-for-agencies/sections/partner-directory/agency-expertise/hooks/use-expertise-form.ts
  client/a8c-for-agencies/sections/partner-directory/agency-expertise/index.tsx
  client/a8c-for-agencies/sections/partner-directory/agency-expertise/style.scss
  client/a8c-for-agencies/sections/partner-directory/constants.ts
  client/a8c-for-agencies/sections/partner-directory/utils/get-partner-directory-label.ts
  client/a8c-for-agencies/style.scss
Labels: [Status] Needs Review, A8c Agencies

#91420 Make loading screen animation slower
  client/site-profiler/components/loading-screen/index.tsx
Labels: [Status] Needs Review

#91486 Update description on staging site card
  client/my-sites/hosting/staging-site-card/card-content/manage-staging-site-card-content.tsx
  client/my-sites/hosting/staging-site-card/card-content/new-staging-site-card-content.tsx
Labels: [Status] Needs Review

#91380 Stats: Remove "checkout-flows-v2" feature flag
  client/my-sites/stats/controller.jsx
  client/my-sites/stats/pages/insights/controller.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-notice.jsx
  client/my-sites/stats/stats-purchase/stats-purchase-personal.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-shared.tsx
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
  client/my-sites/stats/stats-redirect/index.tsx
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Stats, [Status] Needs Review

#91511 Site Migration: Increase to 5 minutes time to wait for install a plugin
  client/landing/stepper/hooks/use-plugin-auto-installation.ts
Labels: [Status] Needs Review, Site Migration

#91518 A4A: Remove beta from the A4A Overview page's title
  client/a8c-for-agencies/sections/overview/body/intro-cards/index.tsx
  client/a8c-for-agencies/sections/overview/overview.tsx
Labels: [Status] Needs Review, [Size] XS, A8c Agencies

#91338 Site Migration: Remove deprecated instructions step
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions-i2/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions-i2/maybe-link/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions-i2/show-hide-input/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions-i2/show-hide-input/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps.tsx
Labels: [Status] Needs Review, Site Migration

#90771 Advertising A4A: Add touchpoint to /me/developer page
  client/me/developer/features/use-features-list.tsx
Labels: [Status] String Freeze, Advertising A4A

#90963 Advertising A4A: Add touchpoint to sites dashboard
  client/sites-dashboard-v2/dotcom-style.scss
  client/sites-dashboard-v2/sites-dashboard.tsx
Labels: [Status] Needs Review, [Status] String Freeze, Advertising A4A

#91522 Advertising A4A: Fix /me/developer page link
  client/me/developer/features/use-features-list.tsx
Labels: Advertising A4A

#91521 Dashboard v2 - re-add Icons to the header
  client/sites-dashboard-v2/site-preview-pane/dotcom-preview-pane.tsx
Labels: [Status] Needs Review

#91527 Advertising A4A: Update a4a touchpoint marketing copy
  client/me/developer/features/use-features-list.tsx
  client/sites-dashboard-v2/sites-dashboard.tsx
Labels: Advertising A4A

#91523 Dashboard v2 flyout list - increase size of search input.
  client/sites-dashboard-v2/dotcom-style.scss
Labels: [Status] Needs Review

#91526 Dashboard v2 - hide a4a banner in collapsed flyout sidebar
  client/sites-dashboard-v2/dotcom-style.scss
Labels: [Status] Needs Review

#91528 E2E tests: Increase specificity of selector
  packages/calypso-e2e/src/lib/blocks/story-block.ts
Labels: [Status] Needs Review

#91519 Remove English locale check from testimonials
  client/blocks/importer/wordpress/upgrade-plan/upgrade-plan-hosting-details.tsx
Labels: [Status] Needs Review

#91489 Jetpack Visibility i1: Show jetpack scan history for atomic sites
  client/jetpack-cloud/sections/sidebar-navigation/lib/constants.ts
  client/jetpack-cloud/sections/sidebar-navigation/manage-selected-site.tsx
  client/my-sites/scan/controller.js
Labels: [Status] Needs Review, Jetpack Cloud, Jetpack Scan Visibility i1

#91535 Remove the extra 'the' from the title
  client/a8c-for-agencies/sections/overview/body/intro-cards/index.tsx
Labels: [Status] Needs Review, [Size] XS, A8c Agencies

#91531 Hosting Overview: Get purchase currency code to match purchase price.
  client/hosting-overview/components/plan-card.tsx
  packages/data-stores/src/plans/hooks/use-pricing-meta-for-grid-plans.ts
  packages/data-stores/src/plans/types.ts
Labels: [Status] Needs Review

#91536 A4A: Update Migrate to WordPress.com link to WordPress.com Developers
  client/a8c-for-agencies/sections/migrations/migrations-overview/index.tsx
Labels: [Status] Needs Review, [Size] XS, A8c Agencies

#91484 Calypso Green: add links to footer menu
  client/jetpack-cloud/sections/pricing/jpcom-footer/index.tsx
Labels: [Status] In Progress

#91474 Domains: Remove CTAs from Gravatar flow (2nd take)
  client/components/domains/register-domain-step/index.jsx
Labels: [Status] Needs Review

#91538 Fixes the signup oauth flor for Blaze Pro
  client/blocks/signup-form/index.jsx
Labels: [Status] Needs Review

#91432 A4A: When first entering referral modal modal should be shown
  client/a8c-for-agencies/sections/marketplace/common/referral-toggle/index.tsx
Labels: [Status] Needs Review, A4A

#91442 Jetpack Cloud Simple > Monetize: Upsells should go to WP.com instead of Jetpack Upsells
  client/my-sites/earn/home.tsx
Labels: [Status] Needs Review

#91501 Jetpack Cloud: Change the copy to include Atomic when there're no sites
  client/components/jetpack/no-jetpack-sites-message/index.tsx
Labels: [Status] Needs Review

#91499 Jetpack Backup: Add new Tracks events for download process
  client/components/activity-card/toolbar/actions-button.tsx
  client/my-sites/backup/rewind-flow/download.tsx
Labels: [Status] Needs Review, [Feature] Backups

#91498 Jetpack Backup: Add new Tracks events for the copy to staging process
  client/my-sites/backup/clone-flow/index.tsx
Labels: [Status] Needs Review, [Feature] Backups

#91496 Jetpack Backup: Add new Tracks events for the restore process
  client/my-sites/backup/rewind-flow/error.tsx
  client/my-sites/backup/rewind-flow/restore.tsx
Labels: [Status] Needs Review, [Feature] Backups

#91546 Site Logs: Improve toggle button width
  client/site-logs/components/logs-header/style.scss
Labels: [Status] Needs Review

#91543 Hosting Settings: Remove GitHub banner in Hosting Settings
  client/my-sites/hosting/main.js
  client/my-sites/hosting/style.scss
Labels: [Status] Needs Review

#91510 Site Dashboard: Always display all sites
  client/a8c-for-agencies/components/items-dashboard/items-dataviews/index.tsx
  client/components/dataviews/style.scss
  client/components/route/index.js
  client/layout/index.jsx
  client/sites-dashboard-v2/dotcom-style.scss
  client/sites-dashboard-v2/sites-dashboard.tsx
Labels: [Status] Needs Review

#91363 Jetpack Cloud Simple: Add copy and a see all plans link to match the design.
  client/components/jetpack/card/jetpack-rna-action-card/index.tsx
  client/components/jetpack/card/jetpack-rna-action-card/style.scss
  client/components/jetpack/upsell-product-wpcom-plan-card/index.tsx
Labels: [Status] Needs Review

#91513 Use plan purchase to render correct billing periods
  client/hosting-overview/components/plan-card.tsx
Labels: [Status] Needs Review

#91532 Jetpack Cloud Simple: Filter sites to only show Simple Classic
  client/state/sites/actions.js
Labels: [Status] Needs Review

#91549 Dev Tools: Copy update
  client/dev-tools/components/dev-tools.tsx
Labels: [Status] Needs Review

#91503 A4A > Partner Directory: Implement Partner Directory Success view
  client/a8c-for-agencies/sections/partner-directory/dashboard/index.tsx
  client/a8c-for-agencies/sections/partner-directory/dashboard/style.scss
  client/a8c-for-agencies/sections/partner-directory/lib/get-brand-meta.tsx
Labels: [Status] Needs Review, A8c Agencies

#91416 Subscriptions: Grouping Newsletter settings
  client/my-sites/site-settings/settings-newsletter/main.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#91241 Improve login redirects and step tracking in stepper
  client/landing/stepper/declarative-flow/helpers/get-step-old-slug.ts
  client/landing/stepper/declarative-flow/internals/analytics/record-submit-step.ts
  client/landing/stepper/declarative-flow/internals/components/step-route/hooks/use-step-route-tracking/index.tsx
  client/landing/stepper/declarative-flow/internals/components/step-route/index.tsx
  client/landing/stepper/declarative-flow/internals/components/step-route/test/index.tsx
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/types.ts
  client/landing/stepper/declarative-flow/site-migration-flow.ts
  client/landing/stepper/declarative-flow/test/site-migration-flow.tsx
  client/landing/stepper/hooks/test/use-login-url-for-flow.tsx
  client/landing/stepper/hooks/use-login-url-for-flow.ts
  client/landing/stepper/hooks/use-selected-design.ts
  client/landing/stepper/utils/step-with-required-login.ts
  client/landing/stepper/utils/steps-with-required-login.ts
  client/test-helpers/testing-library/index.js
Labels: [Status] Needs Review, [Feature] Tracks Metrics & Monitoring, [Feature] Signup & Account Creation, [Feature Group] Signup & Site Onboarding, Stepper, [Feature] Tailored Onboarding Flows

#91552 A4A > Partner Directory: Implement popover for the `Not Approved` badge on the Partner Directory
  client/a8c-for-agencies/components/a4a-popover/index.tsx
  client/a8c-for-agencies/components/a4a-popover/style.scss
  client/a8c-for-agencies/sections/partner-directory/dashboard/index.tsx
  client/a8c-for-agencies/sections/partner-directory/dashboard/status-badge.tsx
  client/a8c-for-agencies/sections/partner-directory/dashboard/style.scss
Labels: [Status] Needs Review, A8c Agencies

#91445 Plans (Storage): Fix dropdown offsets & other styles cleanup
  packages/plans-grid-next/src/components/comparison-grid/index.tsx
  packages/plans-grid-next/src/components/features-grid/plan-storage-options.tsx
  packages/plans-grid-next/src/style.scss
Labels: [Status] Needs Review

#91517 Site Profiler: security results polling.
  client/data/site-profiler/types.ts
  client/data/site-profiler/use-url-security-metrics-query.ts
  client/site-profiler/components/site-profiler-v2.tsx
Labels: [Status] Needs Review

#91524 A4A: remove hubspot script loading for signup finish page
  client/a8c-for-agencies/sections/signup/primary/agency-signup-finish/index.tsx
Labels: [Status] Needs Review, A4A

#91567 Update TOS wording for Blaze Pro authentication
  client/blocks/authentication/social/social-tos.jsx
  client/blocks/signup-form/index.jsx
Labels: [Status] Needs Review

#91537 Update hosting check because it was depending on translations
  client/blocks/importer/wordpress/upgrade-plan/upgrade-plan-hosting-details.tsx
Labels: [Status] Needs Review

#91574 Help Center: Update live chat text to contact us
  packages/help-center/src/components/help-center-contact-form.tsx
  packages/help-center/src/hooks/use-contact-form-title.tsx
Labels: [Status] Needs Review

#91469 Extract `DiscoverNavigation` to `ScrollableHorizontalNavigation`
  client/components/scrollable-horizontal-navigation/index.tsx
  client/components/scrollable-horizontal-navigation/styles.scss
  client/my-sites/customer-home/cards/features/reader/style.scss
  client/reader/discover/discover-navigation.js
  client/reader/discover/discover-navigation.scss
Labels: [Status] Needs Review

#91578 A4A: remove `chat with us` mentions
  client/a8c-for-agencies/components/a4a-migration-offer/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/details.tsx
Labels: [Status] Needs Review, A4A

#91576 A4A: add signup form validation
  client/a8c-for-agencies/sections/signup/agency-details-form/hooks/use-signup-form-validation.ts
  client/a8c-for-agencies/sections/signup/agency-details-form/index.tsx
  client/a8c-for-agencies/sections/signup/agency-details-form/style.scss
Labels: [Status] Needs Review, A4A

#91580 E2E tests: Bump Jetpack deployment tests timeout
  .teamcity/_self/projects/WPComTests.kt
Labels: [Status] Needs Review

#91581 A4A: add links to knowledge base to the Overview page
  client/a8c-for-agencies/components/sidebar-menu/lib/constants.ts
  client/a8c-for-agencies/components/sidebar/header/profile-dropdown.tsx
  client/a8c-for-agencies/components/sidebar/header/style.scss
  client/a8c-for-agencies/sections/overview/sidebar/quick-links/index.tsx
  client/a8c-for-agencies/sections/overview/sidebar/quick-links/style.scss
Labels: [Status] Needs Review, [Size] XS, A8c Agencies

#91557 Stats: Add promotes-service as a commercial reason.
  client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
Labels: Stats, [Status] Needs Review

#91497 Update site identification step Heading, SubTitle and CTA text
  client/blocks/import/capture/capture-input.tsx
  client/blocks/import/capture/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/test/index.tsx
Labels: [Status] Needs Review

#91541 Plans: Currency symbol doesn't match amount
  client/hosting-overview/components/plan-card.tsx
  packages/data-stores/src/plans/hooks/use-pricing-meta-for-grid-plans.ts
  packages/data-stores/src/plans/types.ts
  test/e2e/specs/tools/advertising__promote.ts
Labels: [Status] Needs Review

#91582 Guided onboarding: Show plan upsell in guided flow
  client/my-sites/plans-features-main/components/plan-upsell-modal/hooks/use-modal-resolution-callback.tsx
Labels: [Status] Needs Review, Guided Onboarding

#89195 Stats: Add UTM builder
  client/blocks/stats-navigation/constants.ts
  client/my-sites/stats/components/stats-button/index.ts
  client/my-sites/stats/components/stats-button/stats-button.tsx
  client/my-sites/stats/stats-module-utm-builder/index.ts
  client/my-sites/stats/stats-module-utm-builder/stats-modeule-utm-builder-form.tsx
  client/my-sites/stats/stats-module-utm-builder/stats-module-utm-builder.tsx
  client/my-sites/stats/stats-module-utm-builder/style.scss
  client/my-sites/stats/stats-module-utm/stats-module-utm.jsx
  client/my-sites/stats/utils.js
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: Stats, [Status] Needs Review

#91583 Stats: Fixing missed UTM builder check
  client/my-sites/stats/stats-module-utm/stats-module-utm.jsx
Labels: Stats, [Status] Needs Review

#91572 Site management panel: Update "Hosting Settings" to "Hosting Features"
  client/blocks/eligibility-warnings/index.tsx
  client/blocks/eligibility-warnings/warning-list.tsx
  client/controller/index.node.js
  client/controller/index.web.js
  client/dev-tools/controller.tsx
  client/github-deployments/index.tsx
  client/hosting-features/components/hosting-features-icon.jsx
  client/hosting-features/components/hosting-features.tsx
  client/hosting-features/components/style.scss
  client/hosting-features/controller.tsx
  client/hosting-features/index.tsx
  client/hosting-overview/index.tsx
  client/sections.js
  client/site-logs/index.tsx
  client/site-monitoring/index.tsx
  client/sites-dashboard-v2/dotcom-style.scss
  client/sites-dashboard-v2/site-preview-pane/constants.ts
  client/sites-dashboard-v2/site-preview-pane/dotcom-preview-pane.tsx
  client/sites-dashboard/components/sites-ellipsis-menu.tsx
  client/staging-site/index.tsx
  client/state/global-sidebar/selectors.ts
Labels: [Status] Needs Review

#91547 Site Management Panel: Fix the description on the pricing card
  client/hosting-overview/components/plan-card.tsx
  packages/plans-grid-next/src/components/shared/billing-timeframe/index.tsx
  packages/plans-grid-next/src/hooks/data-store/use-plan-billing-description.tsx
  packages/plans-grid-next/src/index.tsx
Labels: [Status] Needs Review

#90487 Theme Showcase: Use the screenshot to preview themes without the style variations
  client/my-sites/theme/main.jsx
Labels: [Status] Needs Review

#91560 Site Management Panel: Track the upgrade button
  client/hosting-features/components/hosting-features.tsx
  client/hosting-overview/components/plan-card.tsx
Labels: [Status] Needs Review

#91588 Overview tab: Update the See all backups button style in the Site backup card
  client/my-sites/hosting/site-backup-card/index.js
  client/my-sites/hosting/site-backup-card/style.scss
Labels: [Status] Needs Review

#91553 Add tracks event prop to upsell cards in Jetpack Cloud
  client/components/jetpack/card/jetpack-rna-action-card/index.tsx
  client/components/jetpack/upsell-product-wpcom-plan-card/index.tsx
Labels: [Status] Needs Review

#91592 Remove free hosting trial slug from useFreeTrialPlanSlugs()
  client/my-sites/plans-features-main/hooks/use-free-trial-plan-slugs.ts
Labels: [Status] Needs Review, Hosting onboarding, Free Hosting Trial, Expose Hosting Trial

#91593 Sensei: Set sensei as a signup flow
  client/landing/stepper/declarative-flow/sensei.ts
Labels: [Status] Needs Review, Stepper, Sensei Onboarding Flow
