Repository Automattic/wp-calypso, pull requests merged in 2025-06, with the labels that each got.

#103791 Dashboard: Add the ability to not persist query data to cache.
  client/dashboard/app/auth/index.tsx
  client/dashboard/app/query-client.ts
Labels: [Status] Needs Review, [Feature] Hosting Dashboard

#103723 Dashboard: Add reset site to settings.
  client/dashboard/app/queries.ts
  client/dashboard/data/index.ts
  client/dashboard/data/types.ts
  client/dashboard/sites/settings/danger-zone.tsx
  client/dashboard/sites/site-reset-modal/content-info.tsx
  client/dashboard/sites/site-reset-modal/index.tsx
  client/dashboard/sites/site-reset-modal/style.scss
Labels: [Status] Needs Review, [Feature] Hosting Dashboard

#103794 Hosting Dashboard v2: Implement Agency Settings
  client/dashboard/app/queries.ts
  client/dashboard/app/router.tsx
  client/dashboard/data/index.ts
  client/dashboard/data/types.ts
  client/dashboard/sites/settings-agency/index.tsx
  client/dashboard/sites/settings-agency/summary.tsx
  client/dashboard/sites/settings/index.tsx
Labels: [Status] Needs Review

#103872 Dashboard v2: Update Notice's in defensive mode settings
  client/dashboard/sites/settings-defensive-mode/index.tsx
Labels: [Status] Needs Review

#103814 Accessibility: Update disabled text color from `Gray 10` to `Gray 50` for better contrast in checkout
  packages/composite-checkout/src/lib/theme.ts
Labels: [Status] Needs Review

#103826 Dashboard v2: Implement Settings -> Caching
  client/dashboard/app/queries.ts
  client/dashboard/app/router.tsx
  client/dashboard/data/index.ts
  client/dashboard/sites/settings-caching/index.tsx
  client/dashboard/sites/settings-caching/summary.tsx
  client/dashboard/sites/settings/index.tsx
Labels: [Status] Needs Review

#103809 Update reader menu icons
  client/blocks/comments/post-comment-list.jsx
  client/blocks/conversation-follow-button/style.scss
  client/blocks/reader-post-card/style.scss
  client/blocks/reader-post-options-menu/blog-sticker-menu-item.jsx
  client/blocks/reader-post-options-menu/blog-stickers.jsx
  client/blocks/reader-post-options-menu/reader-post-ellipsis-menu.jsx
  client/components/ellipsis-menu/index.jsx
  client/components/popover-menu/item.jsx
  client/components/popover-menu/style.scss
  client/reader/components/icons/external-icon.jsx
  client/reader/components/icons/follow-conversation-icon.jsx
  client/reader/components/icons/following-conversation-icon.jsx
Labels: [Status] Needs Review

#103819 DateRangeCalendar: support `min` `max` and `excludeDisabled` props in selection preview
  packages/components/src/calendar/date-range-calendar/index.tsx
  packages/components/src/calendar/date-range-calendar/test/index.tsx
  packages/components/src/calendar/types.ts
  packages/components/src/calendar/utils/day-cell.tsx
Labels: [Type] Enhancement, [Status] Needs Review, Components

#103835 Experiment streamlining the plans grid + checkout:: Update title copy in Checkout upsell widget
  client/my-sites/checkout/src/components/checkout-sidebar-plan-upsell/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#103907 STATS: Introduce stats/archive-breakdown feature flag.
  client/my-sites/stats/stats-strings.js
  client/my-sites/stats/summary/index.jsx
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Feature] Stats, [Status] Needs Review

#103796 Connect Refresh: Migrate Akismet to unified Login
  client/assets/images/icons/akismet-logo.svg
  client/blocks/login/login-header.tsx
  client/login/wp-login/components/heading-logo.tsx
  client/login/wp-login/index.jsx
  client/login/wp-login/style.scss
Labels: [Status] Needs Review

#103927 Cancel Button: Add the Zendesk ticket lookup query
  client/sites/overview/components/migration-overview/components/cancel-difm-migration/index.tsx
  client/sites/overview/components/migration-overview/components/cancel-difm-migration/test/index.tsx
  client/sites/overview/components/migration-overview/components/cancel-difm-migration/use-find-zendesk-migration-ticket.ts
Labels: [Status] Needs Review

#103837 Add GitHub Actions workflow for deploying production Design System Docs
  .github/actions/build-design-system-docs/action.yml
  .github/workflows/ds-docs-deploy-production.yml
  .github/workflows/ds-docs-pr-preview.yml
Labels: [Status] Needs Review, Components

#103933 Launches the Cancel Migration button
  client/sites/overview/components/migration-overview/components/cancel-difm-migration/index.tsx
  client/sites/overview/components/migration-overview/components/cancel-difm-migration/test/index.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#103937 Close the help center when clicking the Big Sky add site card
  client/dashboard/sites/add-new-site/index.tsx
Labels: [Status] Needs Review

#103871 A4A > Reports: Implement Overview page
  client/a8c-for-agencies/sections/reports/primary/overview/index.tsx
  client/a8c-for-agencies/sections/reports/primary/overview/style.scss
  client/assets/images/a8c-for-agencies/reports/report-mock-2.png
  client/assets/images/a8c-for-agencies/reports/report-mock-3.png
  client/assets/images/a8c-for-agencies/reports/report-mock.png
Labels: [Status] Needs Review, A8c Agencies

#103911 A4A > Reports: Implement Dashboard page
  client/a8c-for-agencies/sections/reports/hooks/use-fetch-reports.ts
  client/a8c-for-agencies/sections/reports/lib/get-site-reports.ts
  client/a8c-for-agencies/sections/reports/primary/dashboard/empty-state.tsx
  client/a8c-for-agencies/sections/reports/primary/dashboard/index.tsx
  client/a8c-for-agencies/sections/reports/primary/dashboard/report-columns.tsx
  client/a8c-for-agencies/sections/reports/primary/dashboard/reports-list.tsx
  client/a8c-for-agencies/sections/reports/primary/dashboard/style.scss
  client/a8c-for-agencies/sections/reports/reports-details/index.tsx
  client/a8c-for-agencies/sections/reports/reports-details/mobile-view.tsx
  client/a8c-for-agencies/sections/reports/reports-details/reports.tsx
  client/a8c-for-agencies/sections/reports/reports-details/style.scss
  client/a8c-for-agencies/sections/reports/types.ts
  client/a8c-for-agencies/style.scss
Labels: [Status] Needs Review

#103908 Experiment streamlining the plans grid + checkout: Update first year discount copy
  client/my-sites/checkout/src/components/cost-overrides-list.tsx
  packages/wpcom-checkout/src/checkout-line-items.tsx
  packages/wpcom-checkout/src/introductory-offer.ts
  packages/wpcom-checkout/src/transformations.ts
Labels: [Status] Needs Review, [Status] String Freeze

#103916 100-year plan flow: Close calendly right after scheduling
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-diy-or-difm/index.tsx
Labels: [Status] Needs Review

#103924 Fix 100-year domain header
  client/landing/stepper/declarative-flow/flows/hundred-year-domain/hundred-year-domain.ts
  client/landing/stepper/declarative-flow/flows/hundred-year-domain/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-step-wrapper/style.scss
Labels: [Status] Needs Review

#103909 Implement A4A development site launch flow
  client/dashboard/app/queries.ts
  client/dashboard/data/constants.ts
  client/dashboard/data/index.ts
  client/dashboard/data/types.ts
  client/dashboard/sites/settings-site-visibility/agency-development-site-launch-modal.tsx
  client/dashboard/sites/settings-site-visibility/index.tsx
  client/dashboard/sites/settings-site-visibility/launch-form.tsx
Labels: [Status] Needs Review

#103951 Dashboard v2: Update styles of the SectionHeader
  client/dashboard/components/section-header/index.tsx
  client/dashboard/components/section-header/style.scss
Labels: [Status] Needs Review

#103954 GitHub Deployments: Ensure workflow syntax highlighter height (used for the default workflow file) adjusts based on its content
  client/sites/deployments/components/code-highlighter/style.scss
Labels: [Status] Needs Review

#103843 `Tabs.Tablist`: add `density` prop with `compact` variant
  packages/components/CHANGELOG.md
  packages/components/src/tabs/index.tsx
  packages/components/src/tabs/stories/index.stories.tsx
  packages/components/src/tabs/style.module.scss
  packages/components/src/tabs/tablist.tsx
  packages/components/src/tabs/types.ts
Labels: [Status] Needs Review

#103800 Improve voiceover navigation on the plan comparison step
  packages/components/src/logos/woo-logo/index.tsx
  packages/plans-grid-next/src/components/comparison-grid/index.tsx
  packages/plans-grid-next/src/components/comparison-grid/style.scss
  packages/plans-grid-next/src/components/features-grid/plan-headers.tsx
  packages/plans-grid-next/src/components/features-grid/style.scss
  packages/plans-grid-next/src/components/features-grid/table.tsx
  packages/plans-grid-next/src/components/plan-div-td-container.tsx
Labels: [Status] Needs Review

#103886 Environment Badge: show on mobile
  client/components/environment-badge/style.scss
Labels: [Status] Needs Review

#103957 Newsletter: Update launchpad CTA when all tasks are completed
  client/my-sites/customer-home/components/full-screen-launchpad.tsx
Labels: [Status] Needs Review

#103972 A4A: Show correct 3pd vendor in product details modal for recently added products
  client/a8c-for-agencies/sections/marketplace/products-overview/lib/get-vendor-info.ts
Labels: [Status] Needs Review

#103944 Fix color contrast and link style issues in A4A login
  client/assets/stylesheets/_wp-components-overrides.scss
  client/blocks/login/login-form.jsx
  client/blocks/login/style.scss
  client/layout/masterbar/oauth-client.scss
Labels: [Status] Needs Review, Accessibility, [Feature] Authentication, A8c Agencies

#103977 Hosting Dashboard v2: Update site settings badge for Simple sites
  client/dashboard/app/router.tsx
  client/dashboard/sites/settings-caching/summary.tsx
  client/dashboard/sites/settings-defensive-mode/summary.tsx
  client/dashboard/sites/settings-php/summary.tsx
  client/dashboard/sites/settings/index.tsx
Labels: [Status] Needs Review

#103797 Stats: Set jetpack green color as theme accent colors
  apps/odyssey-stats/src/app.scss
  apps/odyssey-stats/src/styles/variables.scss
  apps/odyssey-stats/src/styles/wp-admin.scss
  client/my-sites/stats/geochart/index.jsx
Labels: [Feature] Stats, [Status] Needs Review, [Status] Needs Design Review, [Status] Design Input Requested

#103974 E2E: Fix tests for refactored form fields
  packages/calypso-e2e/src/lib/blocks/block-flows/all-form-fields.ts
  packages/calypso-e2e/src/lib/blocks/block-flows/shared/block-helpers.ts
Labels: [Status] Needs Review, [Feature] Jetpack, Tests (new)

#103978 Dashboard v2: refactor: consistently add padding around forms to conform with design
  client/dashboard/app/style.scss
  client/dashboard/sites/settings-agency/index.tsx
  client/dashboard/sites/settings-caching/index.tsx
  client/dashboard/sites/settings-hundred-year-plan/index.tsx
  client/dashboard/sites/settings-subscription-gifting/index.tsx
  client/dashboard/sites/settings-transfer-site/confirm-new-owner-form.tsx
  client/dashboard/sites/site-delete-modal/index.tsx
Labels: [Status] Needs Review

#103945 Stats: Introduce statType `statsArchives` to StatsTopPosts module with data normalizer
  client/my-sites/stats/features/modules/stats-top-posts/stats-top-posts.tsx
  client/state/stats/lists/test/utils.js
  client/state/stats/lists/utils.js
  packages/wpcom.js/src/lib/runtime/site.get.js
Labels: [Feature] Stats, [Status] Needs Review

#103979 Dashboard: Add subtitle to "Handling requests for nonexistent assets"
  client/dashboard/sites/settings-static-file-404/index.tsx
Labels: [Status] Needs Review

#103984 Revert "Stats: Set jetpack green color as theme accent colors"
  apps/odyssey-stats/src/app.scss
  apps/odyssey-stats/src/styles/variables.scss
  apps/odyssey-stats/src/styles/wp-admin.scss
  client/my-sites/stats/geochart/index.jsx
Labels: [Feature] Stats

#103783 Dashboard v2: Add the ability to configure sftp and ssh
  .eslintrc.js
  client/dashboard/app/queries.ts
  client/dashboard/app/router.tsx
  client/dashboard/components/clipboard-input-control/index.tsx
  client/dashboard/data/constants.ts
  client/dashboard/data/index.ts
  client/dashboard/data/types.ts
  client/dashboard/sites/settings-sftp-ssh/callout-illustration.svg
  client/dashboard/sites/settings-sftp-ssh/enable-sftp-card.tsx
  client/dashboard/sites/settings-sftp-ssh/index.tsx
  client/dashboard/sites/settings-sftp-ssh/sftp-card.tsx
  client/dashboard/sites/settings-sftp-ssh/ssh-card.tsx
  client/dashboard/sites/settings-sftp-ssh/summary.tsx
  client/dashboard/sites/settings/index.tsx
  client/dashboard/utils/site-features.ts
Labels: [Status] Needs Review

#103982 Hosting Dashboard v2: Update layout for static file 404 screen
  client/dashboard/sites/settings-static-file-404/index.tsx
Labels: [Status] Needs Review

#103999 Support Link: Better routing when opening Help Center
  client/me/purchases/cancel-purchase-support-link/support-link.jsx
  packages/zendesk-client/src/use-can-connect-to-zendesk-messaging.ts
Labels: [Status] Needs Review

#103949 DataViews filters: fix visibility
  packages/dataviews/CHANGELOG.automattic.md
  packages/dataviews/src/components/dataviews-filters/index.tsx
  packages/dataviews/src/components/dataviews/stories/fixtures.tsx
  packages/dataviews/src/dataviews-layouts/table/column-header-menu.tsx
  packages/dataviews/src/field-types/boolean.tsx
  packages/dataviews/src/field-types/datetime.tsx
  packages/dataviews/src/field-types/email.tsx
  packages/dataviews/src/field-types/index.tsx
  packages/dataviews/src/field-types/integer.tsx
  packages/dataviews/src/field-types/media.tsx
  packages/dataviews/src/field-types/text.tsx
  packages/dataviews/src/types.ts
  packages/dataviews/src/utils.ts
Labels: [Status] Needs Review

#103996 Ensure "/ year" price is read "per year" using VoiceOver
  client/components/domains/domain-product-price/index.jsx
Labels: [Status] Needs Review

#103883 Connect Refresh: Migrate Gravatar & WP Job Manager to unified Login
  client/assets/images/icons/gravatar.svg
  client/assets/images/icons/wp-job-manager.png
  client/blocks/login/login-form.jsx
  client/blocks/login/login-header.tsx
  client/blocks/login/style.scss
  client/layout/logged-out.jsx
  client/login/controller.js
  client/login/wp-login/components/heading-logo.tsx
  client/login/wp-login/index.jsx
  client/login/wp-login/login-footer.tsx
  client/login/wp-login/style.scss
Labels: [Status] Needs Review

#104003 Newsletter: Use total_subscribers field while displaying all subscribers
  client/my-sites/stats/hooks/use-subscribers-totals-query.tsx
  client/my-sites/subscribers/components/subscriber-data-views/subscriber-data-views.tsx
  client/my-sites/subscribers/components/subscribers-header-popover/subscribers-header-popover.tsx
  client/my-sites/subscribers/hooks/use-add-subscribers-callback.ts
  client/my-sites/subscribers/mutations/use-subscriber-remove-mutation.ts
  client/my-sites/subscribers/queries/test/use-subscriber-count-query-test.tsx
  client/my-sites/subscribers/queries/use-subscriber-count-query.ts
Labels: [Status] Needs Review

#103970 Update Jetpack Forms dashboard URL
  client/my-sites/sidebar/static-data/jetpack-fallback-menu.js
  client/state/admin-menu/test/fixture/menu-fixture.js
  packages/command-palette/src/commands.tsx
  packages/data-stores/src/contextual-help/admin-sections.ts
  packages/help-center/src/route-to-query-mapping.ts
Labels: [Status] Needs Review, [Type] Task

#103991 Forms E2E tests: Fix inline block insertion and options menu open state
  packages/calypso-e2e/src/lib/blocks/block-flows/all-form-fields.ts
  packages/calypso-e2e/src/lib/components/editor-block-toolbar-component.ts
  packages/calypso-e2e/src/lib/pages/editor-page.ts
Labels: [Status] Needs Review, [Status] Needs Jetpack e2e Testing, Tests

#103989 Hosting Dashboard v2: Halt retry if error code is partner_for_blog_not_found
  client/dashboard/app/queries.ts
Labels: [Status] Needs Review

#104017 [DataViews]: bump to 0.2.1
  packages/dataviews/CHANGELOG.automattic.md
  packages/dataviews/package.json
Labels: [Status] Needs Review

#104018 Backport Site Settings router into existing dashboard
  client/sites/settings/v2/router.tsx
Labels: [Status] Needs Review

#103958 A4A: Disable magic link flow for Signup v2.
  client/a8c-for-agencies/sections/signup/agency-details-form/hooks/use-create-agency-mutation.ts
  client/a8c-for-agencies/sections/signup/agency-details-form/types.ts
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/hooks/use-submit-signup.ts
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/index.tsx
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-horizon.json
  config/a8c-for-agencies-production.json
  config/a8c-for-agencies-stage.json
  test/e2e/specs/a8c-for-agencies/signup__smoke.ts
Labels: [Status] Needs Review, A8c Agencies

#103895 A4A: Add the 'Unified onboarding flow' feature flag.
  client/a8c-for-agencies/sections/overview/body/index.tsx
  client/a8c-for-agencies/sections/overview/sidebar/index.tsx
  client/a8c-for-agencies/sections/overview/sidebar/relaunch-welcome-tour/index.tsx
  client/a8c-for-agencies/sections/overview/sidebar/relaunch-welcome-tour/style.scss
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-horizon.json
  config/a8c-for-agencies-production.json
  config/a8c-for-agencies-stage.json
Labels: [Status] Needs Review, A8c Agencies

#103923 A4A: Implement the withOnboardingTour HOC.
  client/a8c-for-agencies/components/hoc/with-onboarding-tour.tsx
  client/a8c-for-agencies/components/onboarding-tour-modal/index.tsx
  client/a8c-for-agencies/components/onboarding-tour-modal/section.tsx
  client/a8c-for-agencies/sections/overview/overview.tsx
  client/a8c-for-agencies/sections/overview/sidebar/relaunch-welcome-tour/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#104022 Dashboard v2: Fix the reset site endpoints because of incorrect namespace
  client/dashboard/data/index.ts
Labels: [Status] Needs Review

#104019 Hosting Dashboard v2: Enable site settings backport in horizon, and, wpcalypso
  client/sites/settings/controller.tsx
  client/sites/settings/index.tsx
  client/sites/settings/v2/controller.tsx
  config/development.json
  config/horizon.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#104024 Dashboard v2: Display an error notice if any error occurs during the site transfer process
  client/dashboard/sites/settings-transfer-site/confirm-new-owner-form.tsx
  client/dashboard/sites/settings-transfer-site/start-site-transfer-form.tsx
Labels: [Status] Needs Review

#104029 Add story for each field type definition (DataViews & DataForm)
  packages/dataviews/CHANGELOG.automattic.md
  packages/dataviews/src/components/dataviews-dataform-story/index.story.tsx
  packages/dataviews/src/components/dataviews/stories/fixtures.tsx
Labels: [Status] Needs Review

#104004 Stats: Update possible Archive types to display label
  client/state/stats/lists/test/utils.js
  client/state/stats/lists/utils.js
Labels: [Feature] Stats, [Status] Needs Review

#104015 Reader: Fix extra underlines on user profile lists
  client/reader/user-profile/style.scss
Labels: [Status] Needs Review

#103899 Notifications: Improve padding on tabs
  apps/notifications/src/panel/boot/stylesheets/main.scss
  client/notifications/style.scss
Labels: [Type] Bug, [Pri] Normal, [Status] Needs Review, [Status] Needs Author Reply, [Feature] Notifications, i18n, Bug

#103850 Reader: Fixes react warnings on console
  client/blocks/author-compact-profile/index.tsx
  client/blocks/reader-avatar/index.tsx
  client/layout/sidebar/item.jsx
Labels: [Status] Needs Review

#103692 i18n: Add context to several category names
  client/my-sites/plugins/categories/use-categories.tsx
Labels: [Status] String Freeze

#104061 Theme Preview: Pass the user language to the demo URL
  client/my-sites/themes/theme-preview.jsx
Labels: [Status] Needs Review

#103993 Stats: Add toggle component to the `Most viewed` module
  client/my-sites/stats/features/modules/stats-top-posts/stats-top-posts.tsx
  client/my-sites/stats/stats-module/index.jsx
  client/my-sites/stats/style.scss
Labels: [Feature] Stats, [Status] Needs Review

#104027 Dashboard V2: Nav bar styling fixes
  client/dashboard/app-a4a/style.scss
  client/dashboard/app-dotcom/style.scss
  client/dashboard/app/secondary-menu/index.tsx
  client/dashboard/components/menu-divider/style.scss
  client/dashboard/sites/site-icon/style.scss
  client/dashboard/sites/site/index.tsx
  client/dashboard/sites/site/switcher.tsx
Labels: [Status] Needs Review

#103997 Hosting Dashboard v2: Implement Big Sky trial site launch flow
  client/dashboard/data/constants.ts
  client/dashboard/data/types.ts
  client/dashboard/sites/settings-site-visibility/launch-form.tsx
  client/dashboard/utils/site-features.ts
Labels: [Status] Needs Review

#103964 Settings > Auto Renew: Use core modal + buttons
  client/components/confirm-dialog/README.md
  client/components/confirm-dialog/index.tsx
  client/components/confirm-dialog/style.scss
  client/components/confirm-modal/index.tsx
  client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-disabling-dialog/index.jsx
  client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-disabling-dialog/style.scss
Labels: [Status] Needs Review

#104065 Subscriber Stats: Fix and unify the Total subscribers count source
  client/my-sites/stats/hooks/use-subscribers-totals-query.tsx
Labels: [Feature] Stats, [Status] Needs Review, [Stats] Subscribers

#104002 Downgrade plan: Check Zendesk before connecting
  client/my-sites/plans-features-main/hooks/use-generate-action-callback.ts
  packages/data-stores/src/help-center/actions.ts
Labels: [Status] Needs Review

#104063 Fixup PHP version capitalisation
  client/data/php-versions/index.jsx
Labels: [Status] Needs Review, [Status] String Freeze, [Status] Reviewer Approved

#104016 Help Center: Remove query mappings
  packages/help-center/src/route-to-query-mapping.ts
Labels: [Status] Needs Review

#104041 A4A Overview -> Upcoming events: Fix dashes in event names
  client/a8c-for-agencies/sections/overview/body/events/index.tsx
Labels: [Status] Needs Review, A4A

#104071 Help Center: Filter out odie conversations that have zendesk events
  packages/help-center/src/hooks/use-get-history-chats.ts
Labels: [Status] Needs Review

#104073 Update Studio download links on /me/get-apps to v1.5.3
  client/blocks/get-apps/apps-config.tsx
Labels: [Status] Needs Review

#104072 Explicitly set the locale in requestTheme
  client/components/data/query-theme/index.jsx
Labels: [Status] Needs Review

#104074 Forms AI: update e2e tests
  packages/calypso-e2e/src/lib/blocks/block-flows/form-ai.ts
Labels: [Status] Ready to Merge, Tests

#104007 Dashboard v2: Implement InlineSupportLink
  client/components/help-center/use-show-help-center.tsx
  client/components/inline-support-link/index.jsx
  client/components/inline-support-link/types.ts
  client/components/inline-support-link/use-support-doc-data.ts
  client/dashboard/components/inline-support-link/index.tsx
  client/dashboard/me/profile/index.tsx
  client/dashboard/sites/overview/storage-card.tsx
  client/dashboard/sites/settings-caching/index.tsx
  client/dashboard/sites/settings-defensive-mode/index.tsx
  client/dashboard/sites/settings-hundred-year-plan/index.tsx
  client/dashboard/sites/settings-sftp-ssh/enable-sftp-card.tsx
  client/dashboard/sites/settings-sftp-ssh/sftp-card.tsx
  client/dashboard/sites/settings-sftp-ssh/ssh-card.tsx
  client/dashboard/sites/settings-site-visibility/privacy-form.tsx
  client/dashboard/sites/settings-transfer-site/index.tsx
  client/dashboard/sites/site-delete-modal/index.tsx
Labels: [Status] Needs Review

#104048 Customer Home Help Card: Improve Design
  client/blocks/inline-help/style.scss
  client/my-sites/customer-home/cards/features/help-search/index.jsx
  client/my-sites/customer-home/cards/features/help-search/style.scss
  packages/help-center/src/components/help-center-search.scss
Labels: [Status] Needs Review, [Status] String Freeze

#104028 Add the WordPress title to the logo to improve the voiceover for A11y enhancement
  client/my-sites/marketplace/pages/submission-success/test/__snapshots__/index.js.snap
  packages/components/src/logos/wordpress-logo/index.tsx
Labels: [Status] Needs Review

#104032 Make the search icon non-focusable when `enableOpenIcon` is false.
  packages/search/src/search.tsx
Labels: [Status] Needs Review

#104076 Improve Site Settings backport UI
  client/sites/settings/v2/style.scss
Labels: [Status] Needs Review

#104038 Help Center: Persist Router State in User Preferences
  packages/data-stores/src/help-center/actions.ts
  packages/data-stores/src/help-center/reducer.ts
  packages/data-stores/src/help-center/resolvers.ts
  packages/data-stores/src/help-center/selectors.ts
  packages/help-center/src/components/help-center-container.tsx
  packages/help-center/src/components/persistent-router.tsx
  packages/help-center/src/hooks/use-persisted-history.ts
Labels: [Status] Needs Review

#104030 Dashboard v2: Ensure consistent page structure across each setting screen
  client/dashboard/app/style.scss
  client/dashboard/sites/settings-defensive-mode/index.tsx
  client/dashboard/sites/settings-hundred-year-plan/index.tsx
  client/dashboard/sites/settings-primary-data-center/index.tsx
  client/dashboard/sites/settings-sftp-ssh/enable-sftp-card.tsx
  client/dashboard/sites/settings-sftp-ssh/sftp-card.tsx
  client/dashboard/sites/settings-sftp-ssh/ssh-card.tsx
  client/dashboard/sites/settings-transfer-site/confirm-new-owner-form.tsx
  client/dashboard/sites/settings-transfer-site/email-confirmation.tsx
  client/dashboard/sites/settings-transfer-site/start-site-transfer-form.tsx
  client/dashboard/sites/site-preview-links/index.tsx
Labels: [Status] Needs Review

#104040 DataViews: declare which operators are valid per field type
  packages/dataviews/CHANGELOG.automattic.md
  packages/dataviews/src/components/dataviews-filters/index.tsx
  packages/dataviews/src/dataviews-layouts/table/column-header-menu.tsx
  packages/dataviews/src/field-types/boolean.tsx
  packages/dataviews/src/field-types/datetime.tsx
  packages/dataviews/src/field-types/email.tsx
  packages/dataviews/src/field-types/integer.tsx
  packages/dataviews/src/field-types/text.tsx
  packages/dataviews/src/normalize-fields.ts
  packages/dataviews/src/test/normalize-fields.ts
  packages/dataviews/src/types.ts
  packages/dataviews/src/utils.ts
Labels: [Status] Needs Review

#104070 Accessibility: Add missing `aria-label` to free domain removal button
  client/signup/steps/domains/domains-mini-cart.jsx
Labels: [Status] Needs Review

#103782 Help Center: Enable email fallback
  packages/help-center/src/components/help-center-chat-history.tsx
  packages/help-center/src/components/help-center-chat.tsx
  packages/help-center/src/components/help-center-contact-form.scss
  packages/help-center/src/components/help-center-contact-form.tsx
  packages/help-center/src/components/help-center-feedback-form.tsx
  packages/help-center/src/components/help-center-search.tsx
  packages/help-center/src/components/notices.scss
  packages/help-center/src/components/notices.tsx
  packages/help-center/src/components/ticket-success-screen.scss
  packages/help-center/src/hooks/use-chat-status.ts
  packages/help-center/src/types.ts
  packages/odie-client/src/components/closed-conversation-footer/index.tsx
  packages/odie-client/src/components/message/direct-escalation-link.tsx
  packages/odie-client/src/components/message/error-message.tsx
  packages/odie-client/src/components/message/get-support.scss
  packages/odie-client/src/components/message/get-support.tsx
  packages/odie-client/src/components/message/message-content.tsx
  packages/odie-client/src/components/message/messages-container.tsx
  packages/odie-client/src/components/message/style.scss
  packages/odie-client/src/components/message/user-message.tsx
  packages/odie-client/src/components/send-message-input/attachment-button.tsx
  packages/odie-client/src/components/send-message-input/index.tsx
  packages/odie-client/src/constants.ts
  packages/odie-client/src/context/index.tsx
  packages/odie-client/src/data/use-send-odie-message.ts
  packages/odie-client/src/hooks/use-get-combined-chat.ts
  packages/odie-client/src/index.tsx
  packages/odie-client/src/style.scss
  packages/odie-client/src/types.ts
  packages/odie-client/src/utils/get-odie-initial-message.ts
  packages/odie-client/src/utils/index.ts
Labels: [Status] Needs Review, [Status] String Freeze

#104049 Storybook: Fix Overview doc
  packages/components/.storybook/main.js
  packages/components/.storybook/overview.mdx
  packages/components/.storybook/preview.js
  packages/components/src/calendar/date-calendar/index.stories.tsx
  packages/components/src/calendar/date-range-calendar/index.stories.tsx
  packages/components/src/icon/index.stories.tsx
  packages/components/src/tabs/stories/index.stories.tsx
Labels: Documentation, [Status] Needs Review, Regression, Storybook

#104090 Purchases: Always call getSitePurchases for site-level even if loading
  client/my-sites/purchases/subscriptions/subscriptions-content.tsx
Labels: [Status] Needs Review

#103986 Stats: Set jetpack green color as theme accent colors (v2)
  apps/odyssey-stats/src/app.scss
  apps/odyssey-stats/src/styles/variables.scss
  apps/odyssey-stats/src/styles/wp-admin.scss
  client/components/jetpack/jetpack-footer/style.scss
  client/components/post-stats-card/style.scss
  client/components/stats-interval-dropdown/index.jsx
  client/my-sites/stats/geochart/index.jsx
  client/my-sites/stats/style.scss
  client/my-sites/subscribers/components/empty-list-view/style.scss
Labels: [Feature] Stats, [Status] Needs Review, Odyssey Stats

#103610 Remove color override from stepper nav top bar right element
  client/assets/stylesheets/_wp-components-overrides.scss
  packages/onboarding/src/step-container-v2/components/TopBar/style.scss
Labels: [Status] Needs Review

#104085 Record impression and click events for settings callouts
  client/dashboard/sites/settings-caching/index.tsx
  client/dashboard/sites/settings-callout/index.tsx
  client/dashboard/sites/settings-database/index.tsx
  client/dashboard/sites/settings-php/index.tsx
  client/dashboard/sites/settings-sftp-ssh/index.tsx
  client/dashboard/sites/settings-static-file-404/index.tsx
Labels: [Status] Needs Review

#103960 A4A > Reports: Implement Example Report
  client/a8c-for-agencies/sections/reports/primary/overview/example-report.tsx
  client/a8c-for-agencies/sections/reports/primary/overview/index.tsx
  client/a8c-for-agencies/sections/reports/primary/overview/style.scss
  client/a8c-for-agencies/style.scss
  client/assets/images/a8c-for-agencies/reports/doodle.png
Labels: [Status] Needs Review, A8c Agencies

#104069 Dashboard v2: Show deleted sites only when a search keyword is entered or a status filter is applied
  client/dashboard/app/queries.ts
  client/dashboard/data/index.ts
  client/dashboard/data/types.ts
  client/dashboard/sites/index.tsx
Labels: [Status] Needs Review

#104095 Forms: E2E test for form AI with correct capitalization
  packages/calypso-e2e/src/lib/blocks/block-flows/form-ai.ts
Labels: [Status] Ready to Merge, Tests

#104000 Settings Auto-Renew: Use core components on the survey modal
  client/components/chat-button/index.tsx
  client/components/confirm-dialog/index.tsx
  client/components/confirm-dialog/style.scss
  client/components/marketing-survey/cancel-auto-renewal-form/index.jsx
  client/components/marketing-survey/cancel-auto-renewal-form/style.scss
  client/components/marketing-survey/cancel-purchase-form/precancellation-chat-button/index.tsx
Labels: [Status] Needs Review

#104091 Add a click event for the launch site button in calypso site settings
  client/sites/settings/site/visibility/index.jsx
Labels: [Status] Needs Review

#103030 Change the help center button in DIFM flow to use a locale instead of geo check
  client/landing/stepper/declarative-flow/internals/steps-repository/difm-starting-point/index.tsx
  client/signup/config/flows-pure.js
  client/signup/help-center-step-button/index.tsx
  client/signup/help-center-step-button/use-should-render-help-center-button.ts
  client/signup/step-wrapper/index.jsx
  client/signup/types.ts
Labels: [Status] Needs Review

#104118 Purchases: Update DataViews version to implement design feedback, third pass
  client/me/purchases/add-new-payment-method/index.tsx
  client/me/purchases/controller.jsx
  client/me/purchases/purchase-item/index.tsx
  client/me/purchases/purchases-list-in-dataviews/purchases-data-field.tsx
  client/me/purchases/purchases-list-in-dataviews/purchases-data-view.tsx
Labels: [Status] Needs Review

#103616 Update login form fields to match core components
  bin/render-stylesheet.js
  client/assets/stylesheets/_wp-base-styles-overrides.scss
  client/assets/stylesheets/shared/_extends-forms.scss
  client/assets/stylesheets/style.scss
  client/blocks/login/login-form.jsx
  client/blocks/login/style.scss
  client/blocks/login/test/login-form.jsx
  client/blocks/signup-form/crowdsignal.scss
  client/blocks/signup-form/style.scss
  client/components/forms/form-password-input/index.jsx
  client/components/forms/form-password-input/style.scss
  client/components/forms/form-text-input/README.md
  client/components/forms/form-text-input/index.jsx
  client/components/forms/form-text-input/style.scss
  client/jetpack-connect/test/__snapshots__/signup.js.snap
  client/layout/masterbar/blaze-pro.scss
  client/layout/masterbar/oauth-client.scss
  client/layout/masterbar/woo.scss
  client/login/wp-login/style.scss
  client/my-sites/email/form/mailboxes/components/test/list.tsx
  packages/components/src/forms/form-label/index.stories.jsx
  packages/components/src/forms/form-label/index.tsx
  packages/components/src/forms/form-label/style.scss
Labels: [Status] Needs Review, Accessibility, [Feature] Authentication

#104067 A4A: Implement A4ASelectSite component
  client/a8c-for-agencies/components/a4a-select-site/index.tsx
  client/a8c-for-agencies/components/a4a-select-site/modal.tsx
  client/a8c-for-agencies/components/a4a-select-site/site-table.tsx
  client/a8c-for-agencies/components/a4a-select-site/types.ts
Labels: [Status] Needs Review, A8c Agencies

#104080 A4A > Reports: Implement Report Builder
  client/a8c-for-agencies/lib/permission.ts
  client/a8c-for-agencies/sections/reports/constants.ts
  client/a8c-for-agencies/sections/reports/controller.tsx
  client/a8c-for-agencies/sections/reports/hooks/use-fetch-reports.ts
  client/a8c-for-agencies/sections/reports/index.tsx
  client/a8c-for-agencies/sections/reports/lib/format-date.ts
  client/a8c-for-agencies/sections/reports/primary/build-report/index.tsx
  client/a8c-for-agencies/sections/reports/primary/build-report/style.scss
  client/a8c-for-agencies/sections/reports/primary/dashboard/empty-state.tsx
  client/a8c-for-agencies/sections/reports/primary/dashboard/index.tsx
  client/a8c-for-agencies/sections/reports/primary/overview/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#103932 Domain: Restyle pages in the Gravatar domain subscription flow for Gravatar branding
  client/components/domains/register-domain-step/index.jsx
  client/layout/index.jsx
  client/layout/masterbar/checkout.tsx
  client/layout/masterbar/logged-in.jsx
  client/layout/style.scss
  client/my-sites/checkout/checkout-thank-you/index.tsx
  client/my-sites/checkout/checkout-thank-you/redesign-v2/masterbar-styled/index.tsx
  client/my-sites/checkout/checkout-thank-you/style.scss
  client/my-sites/checkout/get-thank-you-page-url/index.ts
  client/my-sites/checkout/get-thank-you-page-url/test/get-thank-you-page-url.ts
  client/my-sites/checkout/src/components/checkout-main.tsx
  client/my-sites/checkout/src/hooks/use-create-payment-complete-callback.tsx
  client/my-sites/checkout/src/hooks/use-get-thank-you-url/index.tsx
  client/my-sites/checkout/src/lib/pending-page.ts
  client/my-sites/checkout/src/test/pending-page.ts
  client/signup/config/flows-pure.js
  client/signup/config/flows.js
  client/signup/main.jsx
  client/signup/signup-header/index.tsx
  client/signup/steps/domains/index.jsx
  client/state/selectors/has-gravatar-domain-query-param.ts
  client/state/selectors/test/has-gravatar-domain-query-param.ts
  packages/components/src/index.ts
  packages/components/src/logos/gravatar-text-logo/index.tsx
Labels: [Status] Needs Review, [Feature] Checkout, Domains UI

#104128 Admin color: treat sites without admin color to have default one
  client/state/admin-color/reducer.js
Labels: [Status] Needs Review, Lego Maintenance

#104116 Reader lists - fix scrolling and frame for lists add and manage pages.
  client/reader/list-manage/index.jsx
Labels: [Status] Needs Review

#104035 A4A: Make the Onboarding tour modal mobile responsive.
  client/a8c-for-agencies/components/hoc/with-onboarding-tour/style.scss
  client/a8c-for-agencies/components/onboarding-tour-modal/index.tsx
  client/a8c-for-agencies/components/onboarding-tour-modal/style.scss
Labels: [Status] Needs Review, A8c Agencies

#104105 A4A: Add Swipe gesture on the Onboard tour mobile navigation.
  client/a8c-for-agencies/components/onboarding-tour-modal/index.tsx
  client/a8c-for-agencies/components/onboarding-tour-modal/mobile-navigation.tsx
  client/a8c-for-agencies/components/onboarding-tour-modal/style.scss
Labels: [Status] Needs Review, A8c Agencies

#104106 Accessibility: Improve the VoiceOver on domains filter
  client/components/domains/search-filters/dropdown-filters.jsx
  client/components/token-field/index.jsx
  client/components/token-field/suggestions-list.jsx
  client/components/token-field/test/__snapshots__/index.jsx.snap
  client/components/token-field/test/index.jsx
Labels: [Status] Needs Review

#104113 Add missing parent aria role for menu items on themes page
  packages/wpcom-template-parts/src/universal-header-navigation/index.tsx
  packages/wpcom-template-parts/src/universal-header-navigation/menu-items.tsx
Labels: [Status] Needs Review

#104132 JP Login: Redirect to fallback if there is no redirect_to provided
  client/login/magic-login/verify-login-code.jsx
Labels: [Status] Needs Review

#104099 Connect Refresh: Migrate A4A to unified Login
  client/blocks/login/login-header.tsx
  client/blocks/login/style.scss
  client/layout/logged-out.jsx
  client/lib/login/index.js
  client/login/controller.js
  client/login/wp-login/components/heading-logo.tsx
  client/login/wp-login/index.jsx
  client/login/wp-login/login-links.jsx
Labels: [Status] Needs Review

#104120 Fix tiny padding issue in plan comparison grid
  packages/plans-grid-next/src/components/comparison-grid/index.tsx
Labels: [Status] Needs Review

#104114 Fix link contrast on Jetpack Cloud login page
  client/components/notice/style.scss
  client/layout/masterbar/oauth-client.scss
Labels: [Status] Needs Review

#104138 Fix/e2e tests for launchpad
  test/e2e/specs/onboarding/signup__start-writing-tailored.ts
Labels: [Status] Needs Review

#104134 A4A: Enable the Unified onboarding tour feature in staging.
  config/a8c-for-agencies-stage.json
Labels: [Status] Needs Review, A8c Agencies

#104115 DS Site: Tweak guidance for calendar components
  apps/design-system-docs/docs/components/packages/wp-components/data.ts
Labels: Documentation, [Status] Needs Review

#104131 Help Center: Update recommended resources, Hosting Overview
  packages/help-center/src/route-to-query-mapping.ts
Labels: [Status] Needs Review

#104117 DOTCON-82: Treat migration-in-progress sites as DIFM migrations
  client/sites-dashboard/utils.ts
Labels: [Status] Needs Review

#104122 Newsletter importer: Improve file upload error
  client/my-sites/importer/error-pane.jsx
  client/my-sites/importer/importer-action-buttons/close-button.jsx
  client/my-sites/importer/newsletter/content-upload/importing-pane.jsx
  client/my-sites/importer/newsletter/content.tsx
  client/my-sites/importer/newsletter/importer.scss
Labels: [Status] Needs Review

#104148 Refactor: Centralize the migration status/type detection in a common layer
  client/data/site-migration/index.ts
  client/data/site-migration/test/index.test.ts
  client/sites-dashboard/test/utils.js
  client/sites-dashboard/utils.ts
  client/sites/components/site-preview-pane/dotcom-preview-pane.tsx
  client/sites/components/sites-dataviews/dataviews-fields/site-field.tsx
  client/sites/components/sites-dataviews/site-icon.tsx
  client/sites/components/sites-dataviews/sites-site-status.tsx
  client/sites/overview/components/hosting-overview.tsx
  client/sites/overview/components/migration-overview/components/migration-in-progress/index.tsx
  client/sites/overview/components/migration-overview/components/migration-pending/index.tsx
  client/sites/overview/components/migration-overview/index.tsx
  packages/sites/src/site-excerpt-types.ts
Labels: [Status] Needs Review

#104139 Site settings backport: Fix issue where the SFTP/SSH panel toggle button is center aligned
  client/sites/settings/v2/style.scss
Labels: [Status] Needs Review

#104094 Add `before`, `after`, `beforeInc`, and `afterInc` operators for date field type
  packages/dataviews/CHANGELOG.automattic.md
  packages/dataviews/README.md
  packages/dataviews/src/components/dataviews-filters/filter.tsx
  packages/dataviews/src/constants.ts
  packages/dataviews/src/field-types/datetime.tsx
  packages/dataviews/src/filter-and-sort-data-view.ts
  packages/dataviews/src/test/filter-and-sort-data-view.js
  packages/dataviews/src/types.ts
Labels: [Status] Needs Review

#103000 Experience Control: Improve accessibility and minor refactoring
  client/a8c-for-agencies/components/a4a-feedback/index.tsx
  client/a8c-for-agencies/components/a4a-feedback/style.scss
  packages/calypso-storybook/src/index.js
  packages/components/src/experience-control/README.md
  packages/components/src/experience-control/icons.tsx
  packages/components/src/experience-control/index.stories.tsx
  packages/components/src/experience-control/index.tsx
  packages/components/src/experience-control/style.scss
  packages/components/src/experience-control/types.ts
Labels: [Status] Needs Review, A8c Agencies

#104135 Accessibility: Add ARIA label for selected item in token component
  client/components/token-field/test/__snapshots__/index.jsx.snap
  client/components/token-field/token.jsx
Labels: [Status] Needs Review

#104154 Replace straight quotes with curly/smart quotes
  client/dashboard/sites/settings-agency/index.tsx
  client/dashboard/sites/settings-sftp-ssh/enable-sftp-card.tsx
  client/dashboard/sites/settings-sftp-ssh/ssh-card.tsx
  client/dashboard/sites/settings-site-visibility/agency-development-site-launch-modal.tsx
  client/dashboard/sites/settings-site-visibility/launch-form.tsx
  client/dashboard/sites/settings-site-visibility/privacy-form.tsx
  client/dashboard/sites/settings-transfer-site/confirm-new-owner-form.tsx
  client/dashboard/sites/settings/danger-zone.tsx
  client/dashboard/sites/site-delete-modal/index.tsx
  client/dashboard/sites/site-reset-modal/index.tsx
Labels: [Status] Needs Review

#103981 Dashboard: Add php subtitle to settings page.
  client/dashboard/sites/settings-php/index.tsx
Labels: [Status] Needs Review

#104033 Fix voice over on choose how to use your domain three cards
  client/signup/steps/site-or-domain/index.jsx
  packages/onboarding/src/intent-screen/test/index.tsx
  packages/onboarding/src/select-items/index.tsx
Labels: [Status] Needs Review

#104107 A4A > Reports: Implement Report Builder form validations
  client/a8c-for-agencies/components/a4a-select-site/index.tsx
  client/a8c-for-agencies/components/a4a-select-site/modal.tsx
  client/a8c-for-agencies/components/a4a-select-site/site-table.tsx
  client/a8c-for-agencies/components/a4a-select-site/types.ts
  client/a8c-for-agencies/sections/reports/hooks/use-build-report-form-validation.tsx
  client/a8c-for-agencies/sections/reports/primary/build-report/index.tsx
  client/a8c-for-agencies/sections/reports/primary/build-report/style.scss
  client/a8c-for-agencies/sections/reports/types.ts
Labels: [Status] Needs Review, A8c Agencies

#104075 DOTCON-75 Remove onboarding/step-container-v2-import-flow feature flag and conditional code
  client/blocks/import/list/index.tsx
  client/landing/stepper/declarative-flow/helpers/should-use-step-container-v2.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/import-list/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/import/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/importer/index.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#104133 Remove invalid ARIA attribute aria-expanded="false" from checkout screen
  client/my-sites/checkout/src/components/item-variation-picker/item-variation-dropdown.tsx
Labels: [Status] Needs Review

#104111 Unsubscribe clean up
  client/blocks/comments/post-comment-list.jsx
  client/blocks/reader-feed-header/follow.jsx
  client/blocks/reader-post-card/compact.jsx
  client/blocks/reader-post-options-menu/reader-post-ellipsis-menu.jsx
  client/landing/subscriptions/components/settings/site-settings/site-settings.tsx
  client/landing/subscriptions/components/subscriptions-ellipsis-menu/subscriptions-ellipsis-menu.tsx
  client/reader/components/icons/following-conversation-icon.jsx
Labels: [Status] Needs Review

#104161 My Home: Add survey
  client/my-sites/customer-home/components/home-content/index.jsx
  client/my-sites/customer-home/components/home-survey/assets/images/home-survey.png
  client/my-sites/customer-home/components/home-survey/index.jsx
Labels: [Status] Needs Review

#104149 Reduce specificity of form label selector
  client/components/chart/style.scss
  packages/components/src/forms/README.md
  packages/components/src/forms/form-label/style.scss
Labels: [Status] Needs Review

#104089 Add site-specific props to tracks events when possible
  client/dashboard/.eslintrc.js
  client/dashboard/app/analytics/super-props.ts
  client/dashboard/app/layout.tsx
  client/dashboard/data/site.ts
Labels: [Status] Needs Review

#104096 Hosting Dashboard v2: Implement site visibility launch flows for paid plans with domains, and hosting trials
  client/dashboard/app/queries/site-domains.ts
  client/dashboard/data/constants.ts
  client/dashboard/data/site-domains.ts
  client/dashboard/sites/settings-site-visibility/agency-development-site-launch-modal.tsx
  client/dashboard/sites/settings-site-visibility/index.tsx
  client/dashboard/sites/settings-site-visibility/launch-form.tsx
  client/dashboard/utils/site-features.ts
  client/dashboard/utils/site-plans.ts
Labels: [Status] Needs Review

#104186 Fix form input regressions
  client/assets/stylesheets/shared/_extends-forms.scss
  client/components/forms/form-text-input/stories/index.stories.tsx
  client/components/forms/form-text-input/style.scss
Labels: [Type] Bug, [Status] Needs Review, [Feature] Authentication

#104190 Dashboard V2: Remove view transitions, for now.
  client/dashboard/app/style.scss
  client/dashboard/app/view-transitions.scss
Labels: [Status] Needs Review

#104202 Remove the e2e test for the woocommerce landing page as it is not shown anymore
  test/e2e/specs/woop/woocommerce__landing-page.ts
Labels: [Status] Needs Review

#104159 A4A: Increase onboarding tour font size and fix agency tier resume button.
  client/a8c-for-agencies/components/hoc/with-onboarding-tour/hooks/use-onboarding-tour-sections.tsx
  client/a8c-for-agencies/components/onboarding-tour-modal/style.scss
Labels: [Status] Needs Review, A8c Agencies

#104175 A4A-837 A4A/Jeptack Cloud: Adjust billing explanation verbiage
  client/a8c-for-agencies/sections/purchases/billing/billing-details/index.tsx
  client/a8c-for-agencies/sections/purchases/billing/billing-summary/index.tsx
  client/a8c-for-agencies/sections/purchases/billing/billing-summary/style.scss
  client/jetpack-cloud/sections/partner-portal/billing-details/index.tsx
  client/jetpack-cloud/sections/partner-portal/billing-summary/index.tsx
Labels: [Status] Needs Review

#104197 Accessibility: Fix a11y issues on VIP login page
  client/layout/masterbar/item.tsx
  client/layout/masterbar/logged-out.jsx
Labels: [Status] Needs Review

#104174 Stats: Apply `skip_archives` parameter to the `top-posts` query
  client/my-sites/stats/features/modules/stats-top-posts/stats-top-posts.tsx
Labels: [Feature] Stats, [Status] Needs Review

#104144 Fix contrast issue on Blaze Pro Oauth page
  client/assets/stylesheets/_wp-components-overrides.scss
Labels: [Status] Needs Review

#104179 A4A: Update Onboarding tour content and include PD section.
  client/a8c-for-agencies/components/hoc/with-onboarding-tour/hooks/use-onboarding-tour-sections.tsx
  client/assets/images/a8c-for-agencies/onboarding-tour-banner-partner-directory.svg
Labels: [Status] Needs Review, A8c Agencies

#104194 Stats: Fix `Homepage` item display on the `Archive pages` list
  client/my-sites/stats/features/modules/stats-top-posts/use-option-labels.ts
  client/state/stats/lists/test/utils.js
  client/state/stats/lists/utils.js
Labels: [Feature] Stats, [Status] Needs Review

#104207 Stats: Enable Archive pages on staging
  client/my-sites/stats/controller.jsx
  client/my-sites/stats/features/modules/stats-top-posts/nav-tabs.tsx
  client/my-sites/stats/features/modules/stats-top-posts/stats-top-posts.tsx
  client/my-sites/stats/features/modules/stats-top-posts/use-option-labels.ts
  config/stage.json
Labels: [Feature] Stats, [Status] Needs Review

#104162 Open plugins 'How to get help' in support center
  client/components/inline-support-link/context-links.js
  client/my-sites/plugins/plugin-details-sidebar-usp/index.jsx
  client/my-sites/plugins/plugin-details-sidebar/index.jsx
Labels: [Status] Needs Review

#104172 Add WP Admin util to open support links in Help Center
  apps/help-center/help-center-wp-admin.js
Labels: [Status] Needs Review, [Feature] Help Center

#104181 Improve Help Center chat ellipsis menu voice over navigation
  packages/help-center/src/components/help-center-header.scss
  packages/help-center/src/components/help-center-header.tsx
  packages/odie-client/src/components/ellipsis-menu/index.tsx
Labels: [Status] Needs Review

#104171 Add accessibility item to PR template checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Needs Review

#104189 Keep the original order of finished items of Launchpad
  packages/data-stores/src/queries/use-launchpad.ts
  packages/launchpad/src/launchpad.tsx
Labels: [Status] Needs Review

#104215 Checkout: Set max wait time for auto-completing contact step
  client/my-sites/checkout/src/hooks/use-prefill-checkout-contact-form.ts
Labels: [Status] Needs Review

#104216 Stats: Fix query from summary page to the download CSV button
  client/my-sites/stats/summary/index.jsx
Labels: [Feature] Stats, [Status] Needs Review
