Repository Automattic/wp-calypso, pull requests merged in 2025-10, with the labels that each got.

#106166 Hosting Dashboard Logs: Fix PageHeader
  client/dashboard/sites/logs/index.tsx
Labels: [Status] Needs Review

#106139 FileBrowser: Make `notices` optional in `FileBrowserProvider`
  client/dashboard/sites/staging-site-sync-modal/index.tsx
  client/my-sites/backup/backup-contents-page/file-browser/file-browser-context.tsx
  client/my-sites/backup/backup-contents-page/file-browser/file-info-card.tsx
Labels: [Status] Needs Review

#106128 Untangle: Remove /posts and its components
  client/my-sites/post/README.md
  client/my-sites/posts/README.md
  client/my-sites/posts/controller.js
  client/my-sites/posts/index.js
  client/my-sites/posts/main.jsx
  client/state/sites/selectors/get-site-admin-url.ts
Labels: [Status] Needs Review

#106168 Update copy on the Manage repositories button
  client/dashboard/sites/deployments-list/index.tsx
Labels: [Status] Needs Review

#105786 Hosting dashboard: Scheduled updates list.
  client/dashboard/plugins/scheduled-updates/hooks/use-scheduled-updates.ts
  client/dashboard/plugins/scheduled-updates/index.tsx
  client/dashboard/plugins/scheduled-updates/types.ts
Labels: [Status] Needs Review

#106183 Hosting Dashboard: Fix glue records file structure inconsistency
  client/dashboard/domains/domain-glue-records/summary.tsx
  client/dashboard/domains/domain-overview/settings.tsx
Labels: [Status] Needs Review

#106132 Calypso Cleanup: Comments
  client/components/data/moderate-comment/index.jsx
  client/components/data/query-comment/README.md
  client/components/data/query-comment/index.jsx
  client/components/data/query-site-comment-counts/index.jsx
  client/components/data/query-site-comments-list/README.md
  client/components/data/query-site-comments-list/index.jsx
  client/components/section-nav/index.jsx
  client/my-sites/comment/comment-delete-warning.jsx
  client/my-sites/comment/comment-permalink.jsx
  client/my-sites/comment/main.jsx
  client/my-sites/comment/style.scss
  client/my-sites/comments/comment-list/comment-list-header.jsx
  client/my-sites/comments/comment-list/index.jsx
  client/my-sites/comments/comment-navigation/comment-navigation-tab.jsx
  client/my-sites/comments/comment-navigation/index.jsx
  client/my-sites/comments/comment-tips.jsx
  client/my-sites/comments/comment/comment-actions.jsx
  client/my-sites/comments/comment/comment-author-more-info.jsx
  client/my-sites/comments/comment/comment-author.jsx
  client/my-sites/comments/comment/comment-block-editor/index.tsx
  client/my-sites/comments/comment/comment-content.jsx
  client/my-sites/comments/comment/comment-edit.jsx
  client/my-sites/comments/comment/comment-header.jsx
  client/my-sites/comments/comment/comment-html-editor/add-image-dialog.jsx
  client/my-sites/comments/comment/comment-html-editor/add-link-dialog.jsx
  client/my-sites/comments/comment/comment-html-editor/index.jsx
  client/my-sites/comments/comment/comment-link.jsx
  client/my-sites/comments/comment/comment-post-link.jsx
  client/my-sites/comments/comment/comment-reply.jsx
  client/my-sites/comments/comment/index.jsx
  client/my-sites/comments/comment/style.scss
  client/my-sites/comments/comment/utils.js
  client/my-sites/comments/constants.js
  client/my-sites/comments/controller.js
  client/my-sites/comments/index.js
  client/my-sites/comments/main.jsx
  client/my-sites/comments/style.scss
Labels: [Status] Needs Review

#106114 Checkout: Remove unused isInModal/onAfterPaymentComplete from CheckoutMain
  client/a8c-for-agencies/sections/client/primary/checkout-v2/index.tsx
  client/a8c-for-agencies/sections/marketplace/billing-dragon-checkout/index.tsx
  client/my-sites/checkout/src/components/checkout-main.tsx
  client/my-sites/checkout/src/hooks/use-prepare-products-for-cart.ts
Labels: [Status] Needs Review

#105490 Hosting Dashboard: Add PurchaseNotice to purchase settings page
  client/dashboard/me/billing-purchases/purchase-settings/index.tsx
  client/dashboard/me/billing-purchases/purchase-settings/other-renewable-purchases-notice.tsx
  client/dashboard/me/billing-purchases/purchase-settings/purchase-expiring-notice.tsx
  client/dashboard/me/billing-purchases/purchase-settings/purchase-notice.tsx
  client/dashboard/me/billing-purchases/purchase-settings/renew-notice-action.tsx
  client/dashboard/me/billing-purchases/purchase-settings/style.scss
  client/dashboard/me/billing-purchases/purchase-settings/upcoming-renewals-dialog.tsx
  client/dashboard/utils/purchase.ts
Labels: [Status] Needs Review

#106160 Disable zoom for login page
  client/components/head/index.jsx
  client/login/wp-login/style.scss
Labels: [Status] Needs Review

#106165 Hosting Dashboard: Move description under heading in `<PageHeader>`
  client/dashboard/components/section-header/index.tsx
Labels: [Status] Needs Review

#106174 Hosting Dashboard: Add /ciab path to the backport check
  client/dashboard/app-ciab/logo.tsx
  client/dashboard/sites/features.ts
  client/dashboard/sites/notices.tsx
  client/dashboard/sites/overview-latest-activity-card/index.tsx
  client/dashboard/sites/overview-performance-card/index.tsx
  client/dashboard/sites/overview-plan-card/index.tsx
  client/dashboard/sites/overview-scan-card/index.tsx
  client/dashboard/sites/staging-site-delete-modal/index.tsx
  client/dashboard/sites/staging-site-sync-dropdown/index.tsx
  client/dashboard/utils/is-dashboard-backport.ts
  client/dashboard/utils/site-backup.ts
Labels: [Status] Needs Review

#106193 Replace more logic with isDashboardBackport
  client/dashboard/sites/staging-site-sync-dropdown/index.tsx
  client/dashboard/utils/site-backup.ts
Labels: [Status] Needs Review

#106163 Hosting Dashboard: Rough in performance page.
  client/dashboard/.eslintrc.js
  client/dashboard/app/hooks/site-performance.ts
  client/dashboard/sites/overview-performance-card/index.tsx
  client/dashboard/sites/performance/core-metrics-chart.tsx
  client/dashboard/sites/performance/core-metrics-content.tsx
  client/dashboard/sites/performance/core-metrics-explanation.tsx
  client/dashboard/sites/performance/core-metrics-recommend-link.tsx
  client/dashboard/sites/performance/core-metrics-score.tsx
  client/dashboard/sites/performance/core-metrics-status-badge.tsx
  client/dashboard/sites/performance/core-metrics-tabs.tsx
  client/dashboard/sites/performance/core-metrics.tsx
  client/dashboard/sites/performance/device-toggle.tsx
  client/dashboard/sites/performance/index.tsx
  client/dashboard/sites/performance/page-selector.scss
  client/dashboard/sites/performance/page-selector.tsx
  client/dashboard/sites/performance/performance-callout.tsx
  client/dashboard/sites/performance/performance-insights.tsx
  client/dashboard/sites/performance/report-error-notice.tsx
  client/dashboard/sites/performance/report-expired-notice.tsx
  client/dashboard/sites/performance/report-footer.tsx
  client/dashboard/sites/performance/report-loading.tsx
  client/dashboard/sites/performance/report.tsx
  client/dashboard/sites/performance/screenshot-timeline.tsx
  client/dashboard/sites/performance/subtitle.tsx
  client/dashboard/utils/site-performance.ts
  client/performance-profiler/components/performance-score/index.tsx
  packages/api-core/src/index.ts
  packages/api-core/src/site-performance-pages/fetchers.ts
  packages/api-core/src/site-performance-pages/index.ts
  packages/api-core/src/site-performance-pages/types.ts
  packages/api-core/src/site-performance/fetchers.ts
  packages/api-core/src/site-performance/index.ts
  packages/api-core/src/site-performance/types.ts
  packages/api-core/src/site-profiler/types.ts
  packages/api-queries/src/index.ts
  packages/api-queries/src/performance.ts
  packages/api-queries/src/site-performance.ts
Labels: [Status] Needs Review

#106173 Add repositories to settings page
  client/dashboard/sites/deployments-list/branch-display.tsx
  client/dashboard/sites/deployments/deployments-callout.tsx
  client/dashboard/sites/deployments/icons/branch.tsx
  client/dashboard/sites/deployments/icons/gh-icon.svg
  client/dashboard/sites/settings-repositories/index.tsx
  client/dashboard/sites/settings-repositories/summary.tsx
  client/dashboard/sites/settings/index.tsx
Labels: [Status] Needs Review

#106090 Grid: Add support for overlay actions in tiles
  packages/grid/README.md
  packages/grid/src/grid-item.tsx
  packages/grid/src/grid.tsx
  packages/grid/src/stories/grid.stories.tsx
Labels: [Status] Needs Review

#106201 Notification Settings: Use static typed routes instead of strings
  client/dashboard/me/notifications-comments/summary.tsx
  client/dashboard/me/notifications-emails/summary.tsx
  client/dashboard/me/notifications-extras/summary.tsx
  client/dashboard/me/notifications-sites/summary.tsx
Labels: [Status] Needs Review, Code Quality

#105963 Streamlined pricing grid: Enable for Akismet and Jetpack checkout
  client/my-sites/plans-features-main/hooks/use-streamlined-price-experiment.ts
Labels: [Status] Needs Review

#106202 I18N: Fix Hosting Dashboard V2 schedule interval translation
  client/dashboard/plugins/scheduled-updates/index.tsx
Labels: [Status] Needs Review

#106199 Remove unsued `ListItem` components
  client/my-sites/media-library/list-item-audio.jsx
  client/my-sites/media-library/list-item-video.jsx
  client/my-sites/media-library/list-item-video.scss
  client/my-sites/media-library/list-item.tsx
  client/my-sites/media-library/list-no-content.jsx
  client/my-sites/media-library/list-no-results.jsx
  client/my-sites/media-library/test/list-item-video.jsx
  client/post-editor/media-modal/detail/detail-item.jsx
  client/post-editor/media-modal/detail/detail-preview-audio.jsx
  client/post-editor/media-modal/detail/detail-preview-media-file.tsx
  client/post-editor/media-modal/detail/detail-preview-video.jsx
  client/post-editor/media-modal/detail/detail-preview-videopress.jsx
Labels: [Status] Needs Review

#106080 Notification Settings: Enable to configure notification settings by site
  client/dashboard/.eslintrc.js
  client/dashboard/me/notifications-comments/device-settings/index.tsx
  client/dashboard/me/notifications-sites/collapsible-card/index.scss
  client/dashboard/me/notifications-sites/collapsible-card/index.tsx
  client/dashboard/me/notifications-sites/helpers/translations.ts
  client/dashboard/me/notifications-sites/hooks/index.ts
  client/dashboard/me/notifications-sites/index.tsx
  client/dashboard/me/notifications-sites/loading/index.tsx
  client/dashboard/me/notifications-sites/site-list-settings/index.scss
  client/dashboard/me/notifications-sites/site-list-settings/index.tsx
  client/dashboard/me/notifications-sites/site-preview/index.scss
  client/dashboard/me/notifications-sites/site-preview/index.tsx
  client/dashboard/me/notifications-sites/site-settings/apply-settings-to-all-sites-confirmation-modal/index.tsx
  client/dashboard/me/notifications-sites/site-settings/device-settings/index.tsx
  client/dashboard/me/notifications-sites/site-settings/device-settings/test/index.test.tsx
  client/dashboard/me/notifications-sites/site-settings/email-settings/index.tsx
  client/dashboard/me/notifications-sites/site-settings/email-settings/test/index.test.tsx
  client/dashboard/me/notifications-sites/site-settings/index.scss
  client/dashboard/me/notifications-sites/site-settings/index.tsx
  client/dashboard/me/notifications-sites/site-settings/web-settings/index.tsx
  client/dashboard/me/notifications-sites/site-settings/web-settings/test/index.test.tsx
  client/dashboard/sites/site-fields/index.tsx
  client/dashboard/utils/site-types.ts
  packages/api-core/src/me-notification-settings/mutators.ts
  packages/api-queries/src/me-notifications-settings/helper/index.ts
  packages/api-queries/src/me-notifications-settings/index.ts
Labels: [Status] Needs Review

#106157 Modify the Contact Details fields dynamically based on the selected country
  client/dashboard/domains/domain-contact-details/contact-form-fields.tsx
  client/dashboard/domains/domain-contact-details/contact-form.tsx
  client/dashboard/domains/domain-contact-details/custom-form-fieldsets/constants.ts
  client/dashboard/domains/domain-contact-details/custom-form-fieldsets/get-country-postal-code-support.ts
  client/dashboard/domains/domain-contact-details/custom-form-fieldsets/test/region-address-fieldsets.js
  client/dashboard/domains/domain-contact-details/custom-form-fieldsets/types.ts
  client/dashboard/domains/domain-contact-details/region-address-fieldsets.tsx
Labels: [Status] Needs Review

#105997 Domain Search Rewrite: Retire domainAndPlanPackage flow
  client/components/domains/domain-upsell-callout/index.jsx
  client/dashboard/sites/overview-domain-upsell-card/index.tsx
  client/landing/stepper/declarative-flow/flows/domain-and-plan/README.md
  client/landing/stepper/declarative-flow/flows/domain-and-plan/domain-and-plan.ts
  client/landing/stepper/declarative-flow/flows/domain-upsell/domain-upsell.ts
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/domain-search/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/domain-form-control.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/domain/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/domain/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/plans-wrapper.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/plans/style.scss
  client/landing/stepper/declarative-flow/registered-flows.ts
  client/landing/stepper/declarative-flow/test/deprecated-flows.tsx
  client/landing/stepper/utils/flow-redirect-handler.ts
  client/lib/domains/get-domain-and-plan-upsell-url.ts
  client/lib/domains/index.js
  client/me/domain-upsell/index.jsx
  client/my-sites/customer-home/cards/features/domain-upsell/index.jsx
  client/my-sites/customer-home/cards/features/domain-upsell/test/index.jsx
  client/my-sites/customer-home/cards/tasks/domain-upsell/index.jsx
  client/my-sites/customer-home/cards/tasks/domain-upsell/test/index.jsx
  client/my-sites/domains/controller.jsx
  client/my-sites/domains/index.js
  client/my-sites/plans-features-main/index.tsx
  client/reader/sidebar/reader-sidebar-nudges/index.jsx
  packages/launchpad/src/msw/setup-free.ts
  packages/onboarding/src/utils/flows.ts
Labels: [Status] Needs Review

#106214 Dashboard v2: fix opt-in preference form stylings
  client/dashboard/me/preferences-new-hosting-dashboard/index.tsx
Labels: [Status] Needs Review

#106228 Hosting Dashboard: Keep the current path when switching the site.
  client/dashboard/sites/site/index.tsx
Labels: [Status] Needs Review

#106230 Hosting Dashboard: Minor issues fixes
  client/dashboard/components/dataviews-card/index.tsx
  client/dashboard/domains/domain-connection-setup/steps/advanced-records.tsx
  client/dashboard/domains/domain-contact-verification/index.tsx
  client/dashboard/emails/index.tsx
  client/dashboard/emails/resources/email-empty-illustration.tsx
  client/dashboard/me/billing-purchases/purchase-settings/index.tsx
  client/dashboard/me/profile-deletion/alternatives-modal.tsx
  client/dashboard/plugins/scheduled-updates/index.tsx
  client/dashboard/sites/settings-repositories/advanced-workflow-validation.tsx
  client/dashboard/sites/settings-repositories/connect-repository-form.tsx
Labels: [Status] Needs Review

#106213 Plugins Management: Add `No` text fallback for plugins with no updates available
  client/my-sites/plugins/plugins-list/use-fields.tsx
Labels: [Status] Needs Review

#106232 Dashboard v2: fix upsellDescription nested texts
  client/dashboard/sites/backups/index.tsx
  client/dashboard/sites/deployments/deployments-callout.tsx
  client/dashboard/sites/hosting-feature-gated-with-callout/upsell.tsx
  client/dashboard/sites/logs-activity/activity-logs-callout.tsx
  client/dashboard/sites/logs/logs-callout.tsx
  client/dashboard/sites/monitoring/monitoring-callout.tsx
  client/dashboard/sites/performance/performance-callout.tsx
  client/dashboard/sites/scan/index.tsx
  client/dashboard/sites/settings-repositories/index.tsx
Labels: [Status] Needs Review

#106071 v2 Plugins - Scheduled Updates: Edit-schedule route and screen skeleton. placeholder data.
  client/dashboard/app/router/plugins.tsx
  client/dashboard/plugins/scheduled-updates/components/frequency-selection.tsx
  client/dashboard/plugins/scheduled-updates/components/plugins-selection.tsx
  client/dashboard/plugins/scheduled-updates/components/schedule-form.tsx
  client/dashboard/plugins/scheduled-updates/components/sites-selection.tsx
  client/dashboard/plugins/scheduled-updates/edit/index.tsx
  client/dashboard/plugins/scheduled-updates/hooks/use-create-schedules.ts
  client/dashboard/plugins/scheduled-updates/new/index.tsx
Labels: [Status] Needs Review

#106134 v2 Plugins - Scheduled Updates: Pre-fill form with schedule data for Edit
  client/dashboard/plugins/scheduled-updates/constants.ts
  client/dashboard/plugins/scheduled-updates/edit/index.tsx
  client/dashboard/plugins/scheduled-updates/helpers.ts
  client/dashboard/plugins/scheduled-updates/hooks/use-load-schedule-by-id.ts
  client/dashboard/plugins/scheduled-updates/types.ts
Labels: [Status] Needs Review

#106135 v2 Plugins - Scheduled Updates: Exclude current schedule from validations in Edit
  client/dashboard/plugins/scheduled-updates/components/schedule-form.tsx
  client/dashboard/plugins/scheduled-updates/edit/index.tsx
  client/dashboard/plugins/scheduled-updates/hooks/use-schedule-collisions.ts
Labels: [Status] Needs Review

#106204 Performance v2: Implement metric charts
  client/dashboard/sites/performance/core-metrics-chart.tsx
  client/dashboard/sites/performance/core-metrics-content.tsx
  client/dashboard/sites/performance/core-metrics-score.tsx
  client/dashboard/utils/site-performance.ts
  package.json
  packages/api-core/src/site-performance/types.ts
  yarn.lock
Labels: [Status] Needs Review

#106151 Notification Settings: Show notification when all emails are paused
  client/dashboard/components/notice/index.tsx
  client/dashboard/components/notice/types.ts
  client/dashboard/me/notifications-emails/summary/index.tsx
  client/dashboard/me/notifications-emails/summary/test/index.test.tsx
  client/dashboard/me/notifications-sites/browser-notification-card/index.tsx
  client/dashboard/me/notifications-sites/browser-notification-card/test/index.test.tsx
  client/dashboard/me/notifications-sites/browser-notification-notice/index.tsx
  client/dashboard/me/notifications-sites/browser-notification-notice/test/index.test.tsx
  client/dashboard/me/notifications-sites/index.tsx
  client/dashboard/me/notifications-sites/paused-notification-notice/index.tsx
  client/dashboard/me/notifications-sites/paused-notification-notice/test/index.test.tsx
Labels: [Status] Needs Review

#106197 Hosting Dashboard Performance: Fix timezone in subtitle
  client/dashboard/sites/backup-download/index.tsx
  client/dashboard/sites/backup-restore/index.tsx
  client/dashboard/sites/backups/index.tsx
  client/dashboard/sites/logs/index.tsx
  client/dashboard/sites/performance/index.tsx
  client/dashboard/sites/performance/subtitle.tsx
  client/dashboard/sites/scan/index.tsx
  packages/api-core/src/site-settings/types.ts
Labels: [Status] Needs Review

#106224 A4A: Implement Copy referral flow.
  client/a8c-for-agencies/constants/index.ts
  client/a8c-for-agencies/sections/marketplace/checkout/notice-summary.tsx
  client/a8c-for-agencies/sections/marketplace/checkout/request-client-payment.tsx
  client/a8c-for-agencies/sections/marketplace/checkout/style-v1.scss
  client/a8c-for-agencies/sections/marketplace/hooks/use-request-client-payment-mutation.ts
  client/a8c-for-agencies/sections/referrals/primary/referrals-overview/index.tsx
  client/a8c-for-agencies/sections/referrals/primary/referrals-overview/new-referral-order-notification.tsx
  client/a8c-for-agencies/sections/referrals/primary/referrals-overview/style.scss
  client/a8c-for-agencies/sections/referrals/types.ts
Labels: [Status] Needs Review

#106248 Domain Search Rewrite: Enable feature flag in Horizon
  config/horizon.json
Labels: [Status] Needs Review

#106247 Domain Search Rewrite: Add reset filter functionality
  packages/domain-search/src/components/search-bar/constants.ts
  packages/domain-search/src/components/search-bar/filter.tsx
  packages/domain-search/src/components/search-results/index.tsx
  packages/domain-search/src/page/constants.ts
  packages/domain-search/src/page/context.ts
  packages/domain-search/src/page/types.ts
Labels: [Status] Needs Review, Reviewer Can Merge

#106162 Domain Search Rewrite: Make sure all Stepper flows behave correctly
  client/landing/stepper/declarative-flow/flows/copy-site/copy-site.tsx
  client/landing/stepper/declarative-flow/flows/domain/domain.ts
  client/landing/stepper/declarative-flow/flows/hundred-year-domain/hundred-year-domain.ts
  client/landing/stepper/declarative-flow/flows/hundred-year-plan/hundred-year-plan.ts
  client/landing/stepper/declarative-flow/flows/newsletter/newsletter.ts
  client/landing/stepper/declarative-flow/flows/onboarding/onboarding.ts
  client/landing/stepper/declarative-flow/flows/reblogging/reblogging.ts
  client/landing/stepper/declarative-flow/flows/start-writing/start-writing.ts
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/domain-search/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domain-search/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-step-wrapper/style.scss
  client/signup/steps/domains/legacy/index.jsx
  client/signup/steps/domains/rewritten/index.tsx
  packages/domain-search/src/components/search-form/index.tsx
Labels: [Status] Needs Review

#105944 Domain Search Rewrite: Add Tracks events to new domain search components
  client/components/domains/wpcom-domain-search/index.tsx
  client/components/domains/wpcom-domain-search/use-query-handler.ts
  client/components/domains/wpcom-domain-search/use-wpcom-shopping-cart-for-domain-search.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/domain-search/index.tsx
  client/my-sites/domains/domain-search/index.tsx
  client/signup/steps/domains/rewritten/index.tsx
  packages/domain-search/src/components/featured-search-results/item.tsx
  packages/domain-search/src/components/search-results/item.tsx
  packages/domain-search/src/components/suggestion-cta/index.tsx
  packages/domain-search/src/hooks/use-suggestion.ts
  packages/domain-search/src/hooks/use-suggestions-list.ts
  packages/domain-search/src/page/context.ts
  packages/domain-search/src/page/index.tsx
  packages/domain-search/src/page/types.ts
  packages/domain-search/src/ui/featured-domain-suggestions-list/index.tsx
Labels: [Status] Needs Review

#106259 Domain Search Rewrite: Enable feature flag in WPCalypso
  config/wpcalypso.json
Labels: [Status] Needs Review

#106261 Dashboard v2: send no impression event after user has opt'd in
  client/my-sites/hosting-dashboard-opt-in-banner/index.tsx
Labels: [Status] Needs Review

#106263 Prevent from recording double impression events for opt-in banner
  client/my-sites/hosting-dashboard-opt-in-banner/index.tsx
Labels: [Status] Needs Review

#106053 Hosting Dashboard Plugins: Improve icon handling
  client/dashboard/app/router/plugins.tsx
  client/dashboard/plugins/manage/fields/name.tsx
  client/dashboard/plugins/manage/index.tsx
  client/dashboard/plugins/manage/types.ts
  client/dashboard/plugins/plugin/index.tsx
  client/dashboard/plugins/plugin/use-plugin.ts
  packages/api-core/src/marketplace-products/fetchers.ts
  packages/api-core/src/plugins/types.ts
  packages/api-queries/src/plugin.ts
Labels: [Status] Needs Review

#106219 Remove Calypsoify
  client/my-sites/sidebar/static-data/jetpack-fallback-menu.js
  client/state/selectors/get-editor-url.ts
  client/state/selectors/should-calypsoify-jetpack.js
Labels: [Status] Needs Review

#106225 Ensure we set the user's email on Survicate after they log in on sign up
  client/landing/stepper/declarative-flow/flows/onboarding/onboarding.ts
  client/landing/stepper/declarative-flow/test/onboarding-flow.tsx
  client/lib/analytics/survicate.js
  client/lib/analytics/test/survicate.js
Labels: [Status] Needs Review

#106245 Dashboard v2: introduce breadcrumbs mechanism for site settings routes
  client/dashboard/app/breadcrumbs/index.tsx
  client/dashboard/app/router/sites.tsx
  client/dashboard/sites/settings-agency/index.tsx
  client/dashboard/sites/settings-caching/index.tsx
  client/dashboard/sites/settings-database/index.tsx
  client/dashboard/sites/settings-defensive-mode/index.tsx
  client/dashboard/sites/settings-hundred-year-plan/index.tsx
  client/dashboard/sites/settings-page-header/index.tsx
  client/dashboard/sites/settings-php/index.tsx
  client/dashboard/sites/settings-primary-data-center/index.tsx
  client/dashboard/sites/settings-repositories/index.tsx
  client/dashboard/sites/settings-sftp-ssh/index.tsx
  client/dashboard/sites/settings-site-visibility/index.tsx
  client/dashboard/sites/settings-static-file-404/index.tsx
  client/dashboard/sites/settings-subscription-gifting/index.tsx
  client/dashboard/sites/settings-transfer-site/index.tsx
  client/dashboard/sites/settings-web-application-firewall/index.tsx
  client/dashboard/sites/settings-wordpress/index.tsx
  client/dashboard/sites/settings-wpcom-login/index.tsx
  client/sites/v2/site-settings/router.tsx
  packages/components/src/breadcrumbs/style.scss
Labels: [Status] Needs Review

#106200 Dashboard v2: show opt-in banner in v1 global sidebar -- mobile view
  client/layout/sidebar/footer.jsx
  client/my-sites/hosting-dashboard-opt-in-banner/index.tsx
  client/sites/components/sites-dashboard-banners-manager.tsx
  client/sites/components/sites-dashboard-banners/use-dashboard-opt-in-banner.tsx
Labels: [Status] Needs Review

#106280 Remove dashboard survey banner
  client/sites/components/sites-dashboard-banners-manager.tsx
  client/sites/components/sites-dashboard-banners/use-dashboard-survey-banner.tsx
  client/sites/components/test/sites-dashboard-banners-manager.test.tsx
Labels: [Status] Needs Review

#106271 Add plans intent to the calypso_signup_step_start Tracks event
  client/landing/stepper/declarative-flow/internals/analytics/record-step-start.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/unified-plans/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/unified-plans/util.ts
Labels: [Status] Needs Review

#106249 Add primary site address selector
  client/dashboard/sites/domains/index.tsx
  client/dashboard/sites/domains/primary-domain-selector.tsx
  client/dashboard/utils/domain.ts
Labels: [Status] Needs Review

#106288 Domain Search Rewrite: Add some UI unit tests and reorder some code
  packages/domain-search/src/components/cart/index.tsx
  packages/domain-search/src/components/cart/item.tsx
  packages/domain-search/src/components/search-bar/filter.tsx
  packages/domain-search/src/hooks/test/use-has-scrolled-to-end.ts
  packages/domain-search/src/hooks/use-has-scrolled-to-end.ts
  packages/domain-search/src/hooks/use-request-tracking.ts
  packages/domain-search/src/hooks/use-suggestions-list.ts
  packages/domain-search/src/page/context.ts
  packages/domain-search/src/page/index.tsx
  packages/domain-search/src/page/results.tsx
  packages/domain-search/src/ui/domain-search-controls/filter-button.tsx
  packages/domain-search/src/ui/domain-search-controls/filter-popover-tld.tsx
  packages/domain-search/src/ui/domain-search-controls/filter-popover.scss
  packages/domain-search/src/ui/domain-search-controls/filter-popover.tsx
  packages/domain-search/src/ui/domain-search-controls/test/filter-button.tsx
  packages/domain-search/src/ui/domain-search-controls/test/filter-popover.tsx
Labels: [Status] Needs Review

#106294 Disable renew action for non-owners
  client/dashboard/domains/domain-overview/actions.tsx
  client/dashboard/domains/domain-overview/index.tsx
Labels: [Status] Needs Review

#106191 Domain Search Rewrite: Hook events in get availability notice
  client/components/domains/wpcom-domain-search/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domain-search/index.tsx
  client/my-sites/domains/domain-search/index.tsx
  client/signup/steps/domains/rewritten/index.tsx
  packages/api-core/src/domain-suggestions/types.ts
  packages/api-queries/src/domain-availability.ts
  packages/domain-search/src/components/search-notice/index.tsx
  packages/domain-search/src/components/skip-suggestion/index.tsx
  packages/domain-search/src/helpers/get-availability-notice.tsx
  packages/domain-search/src/page/context.ts
  packages/domain-search/src/page/types.ts
Labels: [Status] Needs Review

#106281 Hosting Dashboard: Add username to account deletion modal
  client/dashboard/me/profile-deletion/final-confirmation-modal.tsx
Labels: [Status] Needs Review

#106304 Domain Search Rewrite: Add cart tests
  packages/domain-search/src/components/cart/full-cart.tsx
  packages/domain-search/src/components/cart/index.tsx
  packages/domain-search/src/components/cart/item.tsx
  packages/domain-search/src/components/cart/mini-cart.tsx
  packages/domain-search/src/components/cart/test/full-cart.tsx
  packages/domain-search/src/components/cart/test/index.tsx
  packages/domain-search/src/components/cart/test/mini-cart.tsx
  packages/domain-search/src/page/test/results.tsx
  packages/domain-search/src/test-helpers/factories/cart.ts
  packages/domain-search/src/test-helpers/renderer.tsx
  packages/domain-search/src/ui/domains-full-cart-items/item.tsx
  packages/domain-search/src/ui/domains-full-cart-skip-button/index.tsx
Labels: [Status] Needs Review

#106296 Performance v2: Implement insight feedback
  client/dashboard/sites/performance/performance-insight.tsx
Labels: [Status] Needs Review

#106244 Performance v2: Implement PerformanceInsightTable
  client/dashboard/sites/performance/performance-insight-screenshot.tsx
  client/dashboard/sites/performance/performance-insight-table.tsx
  client/dashboard/sites/performance/performance-insight.tsx
  client/dashboard/sites/performance/types.ts
  client/dashboard/utils/site-performance.ts
Labels: [Status] Needs Review

#106076 Plans logged in: Disable upgrade button if not the owner
  client/my-sites/plans-features-main/components/plan-notice.tsx
  client/my-sites/plans-features-main/hooks/use-generate-action-hook.tsx
  client/my-sites/plans-features-main/style.scss
  packages/plans-grid-next/src/components/plan-button/index.tsx
  packages/plans-grid-next/src/components/plan-button/style.scss
Labels: [Status] Needs Review

#106215 Dashboard v2: Add analytics tracking for activity logs dataviews interactions
  client/dashboard/sites/logs-activity/dataviews/actions.tsx
  client/dashboard/sites/logs-activity/dataviews/index.tsx
Labels: [Status] Needs Review

#106251 Notification Settings: Add track events to Notification > Extras page
  client/dashboard/me/notifications-extras/extras-toggle-card/index.tsx
  client/dashboard/me/notifications-extras/extras-toggle-card/test/index.test.tsx
  client/dashboard/me/notifications-extras/index.tsx
Labels: [Status] Needs Review

#106285 Update/show site redirects in sites
  client/dashboard/sites/overview-site-fields/index.tsx
  client/dashboard/sites/site-fields/index.tsx
  client/dashboard/utils/site-url.ts
  packages/api-core/src/me-sites/fetchers.ts
  packages/api-core/src/site/fetchers.ts
  packages/api-core/src/site/types.ts
Labels: [Status] Needs Review

#106313 Hosting Dashboard Plugins: Remove bulk actions
  client/dashboard/plugins/manage/actions/activate.tsx
  client/dashboard/plugins/manage/actions/deactivate.tsx
  client/dashboard/plugins/manage/actions/delete.tsx
  client/dashboard/plugins/manage/actions/disable-autoupdate.tsx
  client/dashboard/plugins/manage/actions/enable-autoupdate.tsx
Labels: [Status] Needs Review

#106316 HD Domains: show site field for domain connections
  client/dashboard/domains/dataviews/field-domain-site.tsx
Labels: [Status] Needs Review

#106325 A4A: UI fixes & enhancements
  client/a8c-for-agencies/hooks/use-onboarding-tours.ts
  client/a8c-for-agencies/sections/team/primary/team-invite/index.tsx
  client/a8c-for-agencies/style.scss
Labels: [Status] Needs Review, A8c Agencies

#106331 Hosting Dashboard: Remove "Monetize Subscriptions" from MeMenu
  client/dashboard/me/me-menu/index.tsx
Labels: [Status] Needs Review
