Repository Automattic/wp-calypso, pull requests merged in 2025-07, with the labels that each got.

#104492 Backport Sites List: Keep the loading state active to prevent displaying a white screen during the redirection
  client/sites/v2/sites-list/router.tsx
Labels: [Status] Needs Review

#104460 A4A > Reports: Report builder accessibility improvements
  client/a8c-for-agencies/sections/reports/controller.tsx
  client/a8c-for-agencies/sections/reports/lib/stat-options.tsx
  client/a8c-for-agencies/sections/reports/primary/build-report/steps/step-1-details.tsx
  client/a8c-for-agencies/sections/reports/primary/build-report/steps/step-2-content.tsx
  client/a8c-for-agencies/sections/reports/primary/build-report/steps/step-3-send.tsx
  client/a8c-for-agencies/sections/reports/primary/build-report/style.scss
Labels: [Status] Needs Review, A8c Agencies

#104491 Sites List v2: Add Prepare for launch feature for a4a sites
  client/dashboard/sites/actions.tsx
  client/layout/hosting-dashboard/item-view/item-view-header/index.tsx
  client/sites/components/sites-dataviews/actions.tsx
  client/sites/v2/sites-list/router.tsx
Labels: [Status] Needs Review

#104516 Dashboard v2: Fix untranslated strings
  client/dashboard/sites/site-delete-modal/index.tsx
  client/dashboard/sites/site-leave-modal/content-info.tsx
Labels: [Status] Needs Review

#104335 Change the Order of Cancellation API Calls to Meet Requirements
  client/components/marketing-survey/cancel-jetpack-form/index.tsx
  client/components/marketing-survey/cancel-jetpack-form/style.scss
  client/components/marketing-survey/cancel-purchase-form/domain-cancellation-survey.tsx
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/step-components/upsell-step.tsx
  client/components/marketing-survey/cancel-purchase-form/style.scss
  client/me/purchases/cancel-purchase/atomic-revert-changes.tsx
  client/me/purchases/cancel-purchase/button.jsx
  client/me/purchases/cancel-purchase/domain-options.jsx
  client/me/purchases/cancel-purchase/feature-list.jsx
  client/me/purchases/cancel-purchase/index.jsx
  client/me/purchases/cancel-purchase/style.scss
  client/me/purchases/confirm-cancel-domain/index.jsx
  client/me/purchases/manage-purchase/index.tsx
  client/me/purchases/remove-purchase/index.jsx
Labels: [Status] In Progress, [Status] Needs Review

#104483 Purchases: Replace globe generic icon with Passport logo in Purchases dashboard
  client/assets/images/icons/passport-icon.svg
  client/me/purchases/purchase-item/index.tsx
Labels: [Status] Needs Review

#104517 Revert "Change the Order of Cancellation API Calls to Meet Requirements"
  client/components/marketing-survey/cancel-jetpack-form/index.tsx
  client/components/marketing-survey/cancel-jetpack-form/style.scss
  client/components/marketing-survey/cancel-purchase-form/domain-cancellation-survey.tsx
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/step-components/upsell-step.tsx
  client/components/marketing-survey/cancel-purchase-form/style.scss
  client/me/purchases/cancel-purchase/atomic-revert-changes.tsx
  client/me/purchases/cancel-purchase/button.jsx
  client/me/purchases/cancel-purchase/domain-options.jsx
  client/me/purchases/cancel-purchase/feature-list.jsx
  client/me/purchases/cancel-purchase/index.jsx
  client/me/purchases/cancel-purchase/style.scss
  client/me/purchases/confirm-cancel-domain/index.jsx
  client/me/purchases/manage-purchase/index.tsx
  client/me/purchases/remove-purchase/index.jsx
Labels: [Status] Needs Review

#104367 Connect Refresh: Use Calypso lost-password form for all unified Logins
  client/blocks/login/index.jsx
  client/blocks/login/lost-password-form.jsx
  client/layout/masterbar/blaze-pro.scss
  client/layout/masterbar/oauth-client.scss
  client/layout/masterbar/woo.scss
  client/login/controller.js
  client/login/index.web.js
  client/login/test/controller.js
  client/login/wp-login/components/heading-subtext.tsx
  client/login/wp-login/index.jsx
  client/login/wp-login/login-footer.tsx
  client/login/wp-login/style.scss
Labels: [Status] Needs Review, [Status] String Freeze

#104443 Staging Sites Redesign: Enable site deletion for staging sites
  client/dashboard/app/queries/site-staging-sites.ts
  client/dashboard/data/site-staging-site.ts
  client/dashboard/data/site.ts
  client/dashboard/sites/features.ts
  client/dashboard/sites/settings/danger-zone.tsx
  client/dashboard/sites/staging-site-delete-modal/index.tsx
Labels: [Status] Needs Review

#104518 Dashboard v2: always remove version suffix from WP version
  client/dashboard/utils/wp-version.ts
Labels: [Status] Needs Review

#104519 Update order of api calls cancel survey
  client/components/marketing-survey/cancel-jetpack-form/index.tsx
  client/components/marketing-survey/cancel-jetpack-form/style.scss
  client/components/marketing-survey/cancel-purchase-form/domain-cancellation-survey.tsx
  client/components/marketing-survey/cancel-purchase-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/step-components/upsell-step.tsx
  client/components/marketing-survey/cancel-purchase-form/style.scss
  client/me/purchases/cancel-purchase/atomic-revert-changes.tsx
  client/me/purchases/cancel-purchase/button.jsx
  client/me/purchases/cancel-purchase/domain-options.jsx
  client/me/purchases/cancel-purchase/feature-list.jsx
  client/me/purchases/cancel-purchase/index.jsx
  client/me/purchases/cancel-purchase/style.scss
  client/me/purchases/confirm-cancel-domain/index.jsx
  client/me/purchases/manage-purchase/index.tsx
  client/me/purchases/remove-purchase/index.jsx
  packages/calypso-e2e/src/lib/flows/cancel-purchase-flow.ts
  test/e2e/specs/onboarding/lifecycle__signup-onboarding-launch-cancel.ts
  test/e2e/specs/onboarding/onboarding__new-hosted-site.ts
  test/e2e/specs/onboarding/signup__with-theme-LOHP.ts
  test/e2e/specs/onboarding/signup__with-theme-premium.ts
Labels: [Status] Needs Review

#104487 Help Center: Open Odie in DIFM
  client/signup/steps/difm-site-picker/index.tsx
  packages/data-stores/src/help-center/actions.ts
  packages/help-center/src/components/help-center-inline-button.tsx
  packages/help-center/src/hooks/use-action-hooks.ts
  packages/help-center/src/hooks/use-reset-support-interaction.ts
Labels: [Status] Needs Review

#104428 Domain Redesign: Add new package and placeholder components
  client/package.json
  packages/domain-search/.storybook/index.scss
  packages/domain-search/.storybook/main.ts
  packages/domain-search/.storybook/preview.ts
  packages/domain-search/README.md
  packages/domain-search/jest.config.js
  packages/domain-search/package.json
  packages/domain-search/src/DomainSearch.stories.tsx
  packages/domain-search/src/components/DomainSearch/DomainSearch.tsx
  packages/domain-search/src/components/DomainSearchControls/DomainSearchControls.tsx
  packages/domain-search/src/components/DomainSearchControls/Filters.tsx
  packages/domain-search/src/components/DomainSearchControls/Input.tsx
  packages/domain-search/src/components/DomainSuggestions/List.tsx
  packages/domain-search/src/components/DomainSuggestions/Recommendations.tsx
  packages/domain-search/src/components/DomainSuggestions/index.ts
  packages/domain-search/src/components/DomainsFullCart/DomainsFullCart.tsx
  packages/domain-search/src/components/DomainsFullCart/Items.tsx
  packages/domain-search/src/components/DomainsMiniCart/Actions.tsx
  packages/domain-search/src/components/DomainsMiniCart/DomainsMiniCart.tsx
  packages/domain-search/src/components/DomainsMiniCart/Summary.tsx
  packages/domain-search/src/index.ts
  packages/domain-search/src/types.d.ts
  packages/domain-search/tsconfig-cjs.json
  packages/domain-search/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review

#104507 Reader subscriptions management: Fix mobile padding and header after
  client/reader/site-subscriptions-manager/style.scss
  client/reader/style.scss
Labels: [Status] Needs Review

#104523 Help Center: Remove session storage checks
  client/blocks/eligibility-warnings/support-link.tsx
  client/blocks/eligibility-warnings/test/index.tsx
  client/me/purchases/vat-info/index.tsx
  packages/help-center/src/components/help-center-header.tsx
  packages/odie-client/src/components/message/direct-escalation-link.tsx
  packages/odie-client/src/hooks/use-create-zendesk-conversation.ts
  packages/odie-client/src/utils/index.ts
  packages/odie-client/src/utils/storage-utils.ts
Labels: [Status] Needs Review

#104527 Stats: Determine default statType by available fetched data
  client/my-sites/stats/features/modules/stats-top-posts/stats-top-posts.tsx
Labels: [Feature] Stats, [Status] Needs Review

#104424 Connect Refresh: Login Footer cleanup
  client/blocks/login/style.scss
  client/layout/masterbar/blaze-pro.scss
  client/layout/masterbar/oauth-client.scss
  client/layout/masterbar/woo.scss
  client/lib/paths/login/index.js
  client/login/wp-login/gravatar/grav-powered-login-block-footer.tsx
  client/login/wp-login/index.jsx
  client/login/wp-login/login-block-footer.tsx
  client/login/wp-login/style.scss
Labels: [Status] Needs Review

#104447 Connect Refresh: Login Header cleanup
  client/blocks/login/index.jsx
  client/blocks/login/login-header.scss
  client/blocks/login/login-header.tsx
  client/blocks/login/style.scss
  client/blocks/login/two-factor-authentication/verification-code-form.scss
  client/jetpack-connect/style.scss
  client/layout/masterbar/blaze-pro.scss
  client/layout/masterbar/oauth-client.scss
  client/layout/masterbar/woo.scss
  client/login/magic-login/style.scss
  client/login/wp-login/gravatar/grav-powered-login-block-header.tsx
  client/login/wp-login/hooks/get-header-text.tsx
  client/login/wp-login/index.jsx
  client/login/wp-login/style.scss
  client/state/oauth2-clients/selectors.js
  client/state/oauth2-clients/ui/selectors.js
Labels: [Status] Needs Review

#104528 A4A: Add Pressable Titan Addon info card
  client/a8c-for-agencies/components/pressable-usage-details/index.tsx
  client/a8c-for-agencies/components/pressable-usage-details/style.scss
  client/state/a8c-for-agencies/types.ts
Labels: [Status] Needs Review

#104542 Dashboard v2: display correct site url for multisite
  client/dashboard/sites/fields.tsx
  client/dashboard/sites/overview/index.tsx
  client/dashboard/sites/site-restore-modal/content-info.tsx
  client/dashboard/sites/site/index.tsx
  client/dashboard/sites/site/switcher.tsx
  client/dashboard/utils/site-name.ts
  client/dashboard/utils/site-url.ts
Labels: [Status] Needs Review

#104543 A4A > Reports: Enable the feature on staging
  config/a8c-for-agencies-stage.json
Labels: [Status] Needs Review, A8c Agencies

#104505 Staging Sites Redesign: Add environment labels and direction arrow to the new staging sync modal
  client/dashboard/components/site-environment-badge/index.tsx
  client/dashboard/sites/staging-site-sync-modal/index.tsx
Labels: [Status] Needs Review

#104209 Remove the need to add FTP/SSH credentials to run threat fixers via Calypso.
  client/components/jetpack/fix-all-threats-dialog/index.tsx
  client/components/jetpack/server-credentials-wizard-dialog/index.tsx
  client/components/jetpack/server-credentials-wizard-dialog/style.scss
  client/components/jetpack/threat-dialog/index.tsx
Labels: [Type] Enhancement, [Status] Needs Review, [Feature] Scan

#104560 Checkout: show JCB logo for JPY users
  client/my-sites/checkout/src/payment-methods/credit-card/index.tsx
Labels: [Status] Needs Review, [Feature] Checkout, Payment Methods

#104559 Update Domains page background color to white
  client/components/domains/use-my-domain/index.jsx
  client/my-sites/domains/domain-search/index.tsx
Labels: [Status] Needs Review

#104564 Connect Refresh: Extract Login internal layout into a separate component
  client/login/wp-login/components/one-login-layout.tsx
  client/login/wp-login/hooks/get-heading-subtext.tsx
  client/login/wp-login/index.jsx
Labels: [Status] Needs Review

#104533 Admin Bar: Make the plan sub-item clickable
  client/layout/masterbar/logged-in.jsx
  client/layout/masterbar/style.scss
Labels: [Status] Needs Review

#104567 Purchases: Default to primary domain when linking to purchase
  client/me/purchases/purchases-list-in-dataviews/purchases-data-field.tsx
  client/me/purchases/purchases-list-in-dataviews/purchases-data-view.tsx
  packages/data-stores/src/purchases/lib/assembler.ts
  packages/data-stores/src/purchases/types.ts
Labels: [Status] Needs Review

#104539 Purchases: Update DataViews links to use links instead of buttons
  client/me/purchases/billing-history/field-definitions.tsx
  client/me/purchases/billing-history/style-data-view.scss
  client/me/purchases/purchases-list-in-dataviews/purchases-data-field.tsx
  client/me/purchases/purchases-list-in-dataviews/style.scss
  packages/calypso-e2e/src/lib/pages/me/purchases-page.ts
Labels: [Status] Needs Review

#104561 Email Stats: Fix Email Clicks chart tooltip data for display
  client/my-sites/stats/stats-email-chart-tabs/utility.js
Labels: [Feature] Stats, [Status] Needs Review

#104552 Staging Sites Redesign: Move staging sites sync modal from V2 dashboard to sites
  client/dashboard/sites/staging-site-sync-dropdown/index.tsx
  client/sites/staging-site/components/staging-site-sync-modal/index.tsx
Labels: [Status] Needs Review

#104574 Stats: Update E2E test to use Jetpack > Stats
  packages/calypso-e2e/src/lib/components/sidebar-component.ts
  test/e2e/specs/stats/stats.ts
Labels: [Feature] Stats, [Status] Needs Review

#104493 Dashboard v2: show AT transfer status in Status column
  client/dashboard/app/queries/site-atomic-transfers.ts
  client/dashboard/app/query-client.ts
  client/dashboard/data/site-atomic-transfers.ts
  client/dashboard/data/types.ts
  client/dashboard/sites/site-fields/index.tsx
  client/dashboard/utils/site-atomic-transfers.ts
Labels: [Status] Needs Review

#104562 Checkout: Remove duplicate "Need help?" text during DIFM checkout
  packages/help-center/src/hooks/use-products-with-premium-support.ts
Labels: [Status] Needs Review, [Feature] Checkout, [Feature] Help Center, [Feature] DIFM (Do It For Me) Flows

#104508 Scan: Add Jetpack > Scan upsell for Simple Sites
  client/components/jetpack/business-at-switch/index.tsx
  client/components/jetpack/wpcom-business-at/index.tsx
  client/lib/jetpack/wpcom-atomic-transfer.tsx
  client/my-sites/scan/index.js
  client/my-sites/scan/wpcom-atomic-transfer.tsx
  client/my-sites/scan/wpcom-upsell.tsx
Labels: [Status] Needs Review

#104570 A4A > Reports: Minor UI enhancements & copy changes
  client/a8c-for-agencies/components/a4a-select-site/index.tsx
  client/a8c-for-agencies/components/list-item-cards/index.tsx
  client/a8c-for-agencies/sections/reports/primary/build-report/steps/step-1-details.tsx
  client/a8c-for-agencies/sections/reports/primary/dashboard/empty-state.tsx
  client/a8c-for-agencies/sections/reports/primary/dashboard/index.tsx
  client/a8c-for-agencies/sections/reports/primary/dashboard/style.scss
  client/layout/hosting-dashboard/column.tsx
  client/layout/hosting-dashboard/style.scss
Labels: [Status] Needs Review, A8c Agencies

#104540 Replace AsyncLoad in v2 dashboard with new lazyModal function
  client/dashboard/.eslintrc.js
  client/dashboard/sites/actions.tsx
  client/dashboard/sites/hosting-feature/activation.tsx
Labels: [Status] Needs Review

#104588 Checkout: Fix unit tests that are failing due to a missing Country field
  client/my-sites/checkout/src/components/wp-contact-form.tsx
Labels: [Status] Needs Review

#104578 Dashboard v2: fix styles of title fields
  client/dashboard/sites/fields.tsx
  client/dashboard/sites/site-fields/index.tsx
Labels: [Status] Needs Review

#104581 Dashboard v2: reapply the font antialiasing styles
  client/dashboard/app/style.scss
Labels: [Status] Needs Review

#104596 Enable Sites List v2 on wpcalypso and horizon envs
  config/horizon.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#104558 Substack Import: fix finished state
  client/data/paid-newsletter/use-paid-newsletter-query.ts
  client/my-sites/importer/newsletter/importer.tsx
  client/my-sites/importer/newsletter/summary.tsx
  client/my-sites/importer/newsletter/types.ts
  client/my-sites/importer/newsletter/utils.tsx
Labels: [Status] Needs Review, [Feature] Importing & Exporting

#104594 Reader: empty content styling tweak
  client/components/empty-content/style.scss
  client/reader/style.scss
Labels: [Status] Needs Review, Reader

#104548 Sites List v2: Save view options to calypso preferences
  client/dashboard/app/queries/me-a8c.ts
  client/dashboard/app/queries/me-preferences.ts
  client/dashboard/app/queries/me-profile.ts
  client/dashboard/app/router.tsx
  client/dashboard/data/me-preferences.ts
  client/dashboard/me/profile/index.tsx
  client/dashboard/sites/fields.tsx
  client/dashboard/sites/index.tsx
  client/dashboard/sites/views.ts
  client/package.json
  client/sites/v2/sites-list/router.tsx
  yarn.lock
Labels: [Status] Needs Review

#104496 Calypso: Add transferred license ownership purchases to `me/purchases` page.
  client/lib/purchases/index.ts
  client/me/purchases/controller.jsx
  client/me/purchases/hooks/use-is-transferred-ownership.ts
  client/me/purchases/purchase-item/index.tsx
  client/me/purchases/purchase-item/owner-info.tsx
  client/me/purchases/purchases-list-in-dataviews/hooks/use-field-definitions.ts
  client/me/purchases/purchases-list-in-dataviews/index.tsx
  client/me/purchases/purchases-list-in-dataviews/purchases-data-field.tsx
  client/me/purchases/purchases-list-in-dataviews/purchases-data-view.tsx
  client/me/purchases/purchases-site/index.tsx
  packages/data-stores/src/purchases/lib/assembler.ts
  packages/data-stores/src/purchases/queries/lib/use-query-keys-factory.ts
  packages/data-stores/src/purchases/queries/use-get-jetpack-transferred-license-purchases.tsx
  packages/data-stores/src/purchases/types.ts
Labels: [Status] Needs Review

#104604 Track smooch auth errors
  packages/help-center/src/components/help-center-smooch.tsx
Labels: [Status] Needs Review

#104598 wpcom-block-editor: Remove the coblocks/applyFontSettings filter when dom is ready
  apps/wpcom-block-editor/src/wpcom/features/fix-coblocks-fonts.js
Labels: [Status] Needs Review, Lego Maintenance

#104538 Billing History: Preserve and restore view state in URL
  client/me/purchases/billing-history/billing-history-list-data-view.tsx
  client/me/purchases/billing-history/constants.ts
  client/me/purchases/billing-history/hooks/use-view-state-update.ts
  client/me/purchases/billing-history/receipt.tsx
  client/me/purchases/purchases-list-in-dataviews/purchases-data-view.tsx
  client/my-sites/purchases/billing-history/index.tsx
Labels: [Status] Needs Review

#104586 Retire /help page
  client/me/help/README.md
  client/me/help/controller.js
  client/me/help/help-contact-us-footer.tsx
  client/me/help/help-contact-us-header.tsx
  client/me/help/help-results/help-result-item.tsx
  client/me/help/help-results/index.jsx
  client/me/help/help-results/style.scss
  client/me/help/help-search/index.jsx
  client/me/help/help-search/style.scss
  client/me/help/help-unverified-warning/index.jsx
  client/me/help/help-unverified-warning/style.scss
  client/me/help/index.js
  client/me/help/main.jsx
  client/me/help/style.scss
  client/me/help/test/main.jsx
  client/me/sidebar/index.jsx
  client/sections.js
  client/server/pages/index.js
Labels: [Status] Needs Review

#104551 Entrepreneur flow: Use `site-migration` flow to create sites when the user wants to migrate a store
  client/landing/stepper/declarative-flow/flows/entrepreneur-flow/entrepreneur-flow.ts
  client/landing/stepper/declarative-flow/flows/site-migration-flow/site-migration-flow.ts
  client/landing/stepper/declarative-flow/flows/site-migration-flow/test/site-migration-flow.tsx
  config/development.json
Labels: [Status] Needs Review

#104611 Help Center: Remove unused contact page
  packages/help-center/src/components/help-center-contact-page.tsx
  packages/help-center/src/components/help-center-contact-support-option.scss
  packages/help-center/src/components/help-center-contact-support-option.tsx
Labels: [Status] Needs Review

#104620 Sites List v2: Remove the a4a dev site check in the Prepare for launch action eligibility
  client/dashboard/sites/actions.tsx
Labels: [Status] Needs Review

#104617 Site settings v2: implement edge cache rate limiting
  client/dashboard/app/queries/site-cache.ts
  client/dashboard/sites/settings-caching/index.tsx
Labels: [Status] Needs Review

#104618 A4A > Onboarding tour: Add Reports feature
  client/a8c-for-agencies/components/hoc/with-onboarding-tour/hooks/use-onboarding-tour-sections.tsx
  client/assets/images/a8c-for-agencies/onboarding-tour-banner-reports.svg
Labels: [Status] Needs Review, A8c Agencies

#104628 Sites List v2: Update Preview field behavior depending on the selected view type
  client/dashboard/sites/fields.tsx
Labels: [Status] Needs Review

#104624 Help Center: Update article ToC background color
  packages/help-center/src/components/help-center-article.scss
Labels: [Status] Needs Review

#104623 Help Center: Update help on Marketing > Connections
  client/sites/marketing/connections/connections.jsx
Labels: [Status] Needs Review

#104511 Staging Sync: Add the rewind FileBrowser to the Sync Modal
  client/dashboard/sites/staging-site-sync-dropdown/index.tsx
  client/my-sites/backup/backup-contents-page/file-browser/file-browser-header.tsx
  client/my-sites/backup/backup-contents-page/file-browser/index.tsx
  client/sites/components/site-preview-pane/preview-pane-header-buttons.tsx
  client/sites/staging-site/components/staging-site-sync-modal/index.tsx
  client/sites/staging-site/components/staging-site-sync-modal/style.scss
  client/sites/staging-site/hooks/use-staging-sync.ts
Labels: [Status] Needs Review

#104621 Fix login form not having padding on mobile
  client/blocks/login/style.scss
  client/layout/logged-out.jsx
  client/login/wp-login/style.scss
Labels: [Status] Needs Review

#104633 Domain Search Redesign: Set up UI changes foundation
  .github/CODEOWNERS
  client/components/domain-search-v2/domain-cart/index.tsx
  client/components/domain-search-v2/register-domain-step/already-own-a-domain.jsx
  client/components/domain-search-v2/register-domain-step/analytics.js
  client/components/domain-search-v2/register-domain-step/index.jsx
  client/components/domain-search-v2/register-domain-step/style.scss
  client/components/domain-search-v2/register-domain-step/test/utility.js
  client/components/domain-search-v2/register-domain-step/utility.js
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/domain-form-control.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/style.scss
  client/lib/domains/use-domain-search-v2.ts
  client/my-sites/domains/domain-search/index.tsx
  client/my-sites/domains/domain-search/style.scss
  client/my-sites/domains/style.scss
  client/signup/steps/domains/index.jsx
  client/signup/steps/domains/style.scss
  config/development.json
  config/horizon.json
  config/production.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#104622 Dashboard v2: update upsell illustrations
  client/dashboard/sites/deployments/deployments-callout-illustration.svg
  client/dashboard/sites/hosting-feature/activation-illustration.svg
  client/dashboard/sites/hosting-feature/activation.tsx
  client/dashboard/sites/hosting-feature/upsell-illustration.svg
  client/dashboard/sites/settings-database/upsell-illustration.svg
  client/dashboard/sites/settings-sftp-ssh/upsell-illustration.svg
Labels: [Status] Needs Review

#104635 Site list v2: fix Jetpack plan alignment in grid layout
  client/dashboard/sites/site-fields/index.tsx
Labels: [Status] Needs Review

#104636 Help Center: Open Odie links in the Help Center
  packages/help-center/src/hooks/use-content-filter.ts
  packages/odie-client/src/components/message/custom-a-link.tsx
  packages/urls/src/index.ts
Labels: [Status] Needs Review

#104650 Reader profile - register Id route before username and view routes.
  client/reader/index.ts
Labels: [Status] Needs Review

#104647 Lists management - improve empty state.
  client/reader/list-manage/feed-item.tsx
  client/reader/list-manage/index.jsx
  client/reader/list-manage/item-adder.jsx
  client/reader/list-manage/site-item.tsx
  client/reader/list-manage/style.scss
  client/reader/list-manage/subscription-item-adder.jsx
Labels: [Status] Needs Review

#104640 Connect Refresh: Remove obsolete ".wp-login__links"
  client/layout/masterbar/oauth-client.scss
  client/layout/masterbar/woo.scss
  client/login/wp-login/style.scss
Labels: [Status] Needs Review

#104639 Connect Refresh: Woo Login - fix header alignment
  client/layout/masterbar/woo.scss
Labels: [Status] Needs Review

#104110 Show the same plans in the comparison grid when changing the plan term
  packages/plans-grid-next/src/components/comparison-grid/index.tsx
  packages/plans-grid-next/src/hooks/test/use-visible-grid-plans.tsx
  packages/plans-grid-next/src/hooks/use-visible-grid-plans.tsx
Labels: [Status] Needs Review

#104657 Revert "Magic login: Hide Jetpack Mobile App promo on desktop / non-mobile UAs"
  client/login/magic-login/index.jsx
  client/login/magic-login/style.scss
Labels: [Status] Needs Review

#100955 Help Center: Multiple notices
  packages/odie-client/src/components/message/messages-container.tsx
  packages/odie-client/src/components/notices/index.tsx
  packages/odie-client/src/components/notices/style.scss
  packages/odie-client/src/components/notices/use-message-size-error-notice.tsx
  packages/odie-client/src/components/notices/use-view-most-recent-conversation-notice.tsx
  packages/odie-client/src/components/odie-notice/index.tsx
  packages/odie-client/src/components/send-message-input/index.tsx
  packages/odie-client/src/components/send-message-input/resizable-textarea.tsx
  packages/odie-client/src/context/index.tsx
  packages/odie-client/src/style.scss
  packages/odie-client/src/types.ts
Labels: [Status] Needs Review

#104668 A4A: Add the 'Woo and A4A' July 25th event tracker on the Overview page.
  client/a8c-for-agencies/components/upcoming-event/index.tsx
  client/a8c-for-agencies/components/upcoming-event/style.scss
  client/a8c-for-agencies/components/upcoming-event/types.ts
  client/a8c-for-agencies/sections/overview/body/events/hooks/use-upcoming-events.tsx
  client/a8c-for-agencies/sections/overview/body/events/index.tsx
  client/a8c-for-agencies/sections/overview/body/events/styles.scss
  client/assets/images/a8c-for-agencies/events/a4a-compliment-image.svg
  client/assets/images/a8c-for-agencies/events/a4a-logo.svg
Labels: [Status] Needs Review, A8c Agencies

#104625 Staging Sites Redesign: Add information component on staging site management move
  client/sites/staging-site/components/staging-site-card/index.js
  client/sites/staging-site/components/staging-site-card/staging-site-production-card.tsx
  client/sites/staging-site/components/staging-site-management-move-info/index.tsx
Labels: [Status] Needs Review

#104662 Help Center: don't translate before translations are loaded
  packages/odie-client/src/components/message/user-message.tsx
  packages/odie-client/src/components/send-message-input/index.tsx
  packages/odie-client/src/constants.ts
  packages/odie-client/src/data/use-send-odie-message.ts
  packages/odie-client/src/hooks/use-create-zendesk-conversation.ts
  packages/odie-client/src/hooks/use-get-combined-chat.ts
Labels: [Feature] Help Center

#104606 Help Center: block access to chat from the get go when ZD is blocked
  client/components/chat-button/index.tsx
  packages/help-center/src/components/help-center-chat.tsx
  packages/help-center/src/components/help-center-feedback-form.tsx
  packages/help-center/src/components/help-center-smooch.tsx
  packages/help-center/src/components/help-center.tsx
  packages/help-center/src/components/notices.tsx
  packages/help-center/src/contexts/HelpCenterContext.tsx
  packages/odie-client/src/data/use-get-support-interactions.ts
  packages/zendesk-client/src/use-can-connect-to-zendesk-messaging.ts
Labels: [Status] Needs Review

#104672 Prevent `ref` and `help-center` search params from being added to external URLs sent via ZD messaging
  packages/odie-client/jest.config.js
  packages/odie-client/package.json
  packages/odie-client/src/components/message/custom-a-link.tsx
  packages/odie-client/src/components/message/test/custom-a-link.tsx
  packages/odie-client/src/components/message/test/uri-transformer.ts
  packages/odie-client/src/components/message/uri-transformer.ts
  packages/odie-client/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review

#104648 Staging Sync: Add siteId prop to File Browser
  client/my-sites/backup/backup-contents-page/file-browser/file-browser-header.tsx
  client/my-sites/backup/backup-contents-page/file-browser/file-browser-node.tsx
  client/my-sites/backup/backup-contents-page/file-browser/index.tsx
  client/sites/staging-site/components/staging-site-sync-modal/index.tsx
Labels: [Status] Needs Review

#104568 Granular Sync: Accept config to filter children in FileBrowser
  client/my-sites/backup/backup-contents-page/file-browser/file-browser-node.tsx
  client/my-sites/backup/backup-contents-page/file-browser/index.tsx
  client/sites/staging-site/components/staging-site-sync-modal/index.tsx
  client/sites/staging-site/components/staging-site-sync-modal/style.scss
Labels: [Status] Needs Review

#104656 Domain Search Retrofitting: Implement bottom bar for desktop and mobile
  client/components/domain-search-v2/domain-cart/index.tsx
  client/components/domain-search-v2/domain-cart/style.scss
  packages/domain-search/src/components/DomainsMiniCart/Actions.tsx
  packages/domain-search/src/components/DomainsMiniCart/DomainsMiniCart.tsx
  packages/domain-search/src/components/domain-search/index.tsx
  packages/domain-search/src/components/domain-search/test/index.tsx
  packages/domain-search/src/components/domains-full-cart-items/test/index.test.tsx
  packages/domain-search/src/components/domains-full-cart-summary/test/index.test.tsx
  packages/domain-search/src/components/domains-full-cart/test/index.test.tsx
  packages/domain-search/src/components/domains-mini-cart/actions.tsx
  packages/domain-search/src/components/domains-mini-cart/index.tsx
  packages/domain-search/src/components/domains-mini-cart/style.scss
  packages/domain-search/src/components/domains-mini-cart/summary.tsx
  packages/domain-search/src/components/domains-mini-cart/test/index.tsx
  packages/domain-search/src/index.ts
  packages/domain-search/src/test-helpers/factories.ts
Labels: [Status] Needs Review

#104645 HC CSAT: Minor improvements
  packages/help-center/src/components/help-center-support-chat-message.scss
  packages/help-center/src/components/help-center-support-chat-message.tsx
  packages/odie-client/src/components/message/feedback-form.tsx
  packages/odie-client/src/components/message/style.scss
  packages/odie-client/src/utils/zendesk-message-converter.ts
  packages/zendesk-client/src/util.tsx
  packages/zendesk-client/types.d.ts
Labels: [Status] Needs Review

#104684 Sites List v2: Remove WP version field as default column
  client/dashboard/sites/views.ts
Labels: [Status] Needs Review

#104685 Sites List v2: Add action Jetpack Cloud
  client/dashboard/sites/actions.tsx
Labels: [Status] Needs Review

#104651 Site list v2: retain `fields` and type-specific `layout` when changing view type
  client/dashboard/app/queries/me-preferences.ts
  client/dashboard/data/me-preferences.ts
  client/dashboard/sites/index.tsx
  client/dashboard/sites/views.ts
Labels: [Status] Needs Review

#104688 Site list v2: correctly deserialize view search params on first page load
  client/dashboard/app/router.tsx
  client/sites/v2/sites-list/router.tsx
Labels: [Status] Needs Review

#104658 Hosting Dashboard: Record tracks when users change site list settings
  client/dashboard/sites/index.tsx
  client/dashboard/sites/test/views.ts
  client/dashboard/sites/views.ts
Labels: [Status] Needs Review

#104677 Staging Sites Redesign: Update "Push/Pull" and "To" labels in the Sync modal to use site titles and new design
  client/sites/staging-site/components/staging-site-sync-modal/index.tsx
Labels: [Status] Needs Review

#104679 A4A: Hide product line counter on referral checkout.
  client/a8c-for-agencies/sections/marketplace/checkout/product-info.tsx
Labels: [Status] Needs Review, A8c Agencies

#104674 ChatButton: Just use "Need help?"
  client/components/marketing-survey/cancel-auto-renewal-form/index.jsx
  client/components/marketing-survey/cancel-purchase-form/precancellation-chat-button/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-intro/index.tsx
Labels: [Status] Needs Review

#104673 Add tracking events to search card in /support
  apps/happy-blocks/block-library/search-card/index.php
  apps/happy-blocks/block-library/search-card/view.js
Labels: [Status] Needs Review

#104699 Help Center History: Remove unused code
  packages/help-center/src/components/help-center-chat-history.scss
  packages/help-center/src/components/help-center-chat-history.tsx
Labels: [Status] Needs Review

#104678 Connect Refresh: Update Login heading to adapt multiple subs
  client/login/wp-login/components/one-login-layout.tsx
  client/login/wp-login/style.scss
Labels: [Status] Needs Review

#104556 Single post view in Reader: add tooltip to Edit post link, and consolidate tooltip usage in different components
  client/assets/stylesheets/shared/mixins/_mixins.scss
  client/assets/stylesheets/shared/mixins/_tooltip.scss
  client/blocks/comment-button/style.scss
  client/blocks/post-edit-button/index.jsx
  client/blocks/post-edit-button/style.scss
  client/blocks/reader-share/style.scss
  client/layout/global-sidebar/style.scss
Labels: [Type] Enhancement, [Pri] Low, [Status] Needs Review, Enhancement, Reader

#104173 Connect Refresh: Clean up some of the Jetpack magic-login screen customisations
  client/layout/logged-out.jsx
  client/login/magic-login/index.jsx
  client/login/magic-login/style.scss
  client/login/magic-login/verify-login-code.jsx
Labels: [Status] Needs Review

#104695 Domain Search Rewrite: Create domain suggestions list and item components
  client/components/domain-search-v2/domain-cart/index.tsx
  packages/domain-search/package.json
  packages/domain-search/src/components/DomainSuggestions/List.tsx
  packages/domain-search/src/components/DomainSuggestions/Recommendations.tsx
  packages/domain-search/src/components/DomainSuggestions/index.ts
  packages/domain-search/src/components/domain-search/index.tsx
  packages/domain-search/src/components/domain-search/style.scss
  packages/domain-search/src/components/domain-search/test/index.tsx
  packages/domain-search/src/components/domain-search/types.ts
  packages/domain-search/src/components/domain-suggestion-badge/index.tsx
  packages/domain-search/src/components/domain-suggestion-badge/style.scss
  packages/domain-search/src/components/domain-suggestion-badge/test/index.tsx
  packages/domain-search/src/components/domain-suggestion-cta/index.tsx
  packages/domain-search/src/components/domain-suggestion-cta/shopping-cart-icon.tsx
  packages/domain-search/src/components/domain-suggestion-cta/style.scss
  packages/domain-search/src/components/domain-suggestion-cta/test/index.tsx
  packages/domain-search/src/components/domain-suggestion-price/index.tsx
  packages/domain-search/src/components/domain-suggestion-price/test/index.tsx
  packages/domain-search/src/components/domain-suggestion/index.tsx
  packages/domain-search/src/components/domain-suggestion/style.scss
  packages/domain-search/src/components/domain-suggestion/test/index.tsx
  packages/domain-search/src/components/domain-suggestion/test/unavailable.tsx
  packages/domain-search/src/components/domain-suggestion/unavailable.scss
  packages/domain-search/src/components/domain-suggestion/unavailable.stories.tsx
  packages/domain-search/src/components/domain-suggestion/unavailable.tsx
  packages/domain-search/src/components/domain-suggestions-list/index.stories.tsx
  packages/domain-search/src/components/domain-suggestions-list/index.tsx
  packages/domain-search/src/components/domains-full-cart-items/index.tsx
  packages/domain-search/src/components/domains-full-cart-items/test/index.test.tsx
  packages/domain-search/src/components/domains-full-cart/index.stories.tsx
  packages/domain-search/src/hooks/use-container-query.ts
  packages/domain-search/src/index.stories.tsx
  packages/domain-search/src/index.ts
  packages/domain-search/src/test-helpers/factories.ts
  packages/domain-search/tsconfig-build.json
  packages/domain-search/tsconfig-cjs.json
  packages/domain-search/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review

#104706 Make mini-cart and wpcom-checkout packages non-private
  packages/mini-cart/package.json
  packages/wpcom-checkout/package.json
Labels: [Status] Needs Review

#104687 Site list v2: prepend Uptime, Visitors, Views, Likes with '7-day' (ultimate approach)
  client/dashboard/sites/fields.tsx
Labels: [Status] Needs Review

#104660 Site List v2: Update the design of the site icon and make it clickable
  client/blocks/site-favicon/index.tsx
  client/blocks/site-favicon/style.scss
  client/blocks/site-icon/index.tsx
  client/blocks/site-icon/style.scss
  client/dashboard/sites/fields.tsx
  client/dashboard/sites/site-fields/index.tsx
  client/dashboard/sites/site-icon/index.tsx
  client/dashboard/sites/site-icon/site-migration-icon.tsx
  client/dashboard/sites/site-icon/style.scss
  client/layout/hosting-dashboard/item-view/item-view-header/index.tsx
  client/sites/components/sites-dataviews/dataview-style.scss
  client/sites/components/sites-dataviews/site-icon.tsx
Labels: [Status] Needs Review

#104577 Sites List v2: Adjust the number of the items per page
  client/dashboard/sites/index.tsx
  client/dashboard/sites/views.ts
Labels: [Status] Needs Review

#104686 Sites List v2: Update label from Coming Soon to Prepare for Launch when linking to Launchpad
  client/dashboard/sites/site-fields/index.tsx
  client/dashboard/sites/site-fields/test/status.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#104697 Copy Site: Add useRef to prevent redundant API calls in useEffect
  client/landing/stepper/declarative-flow/internals/steps-repository/automated-copy-site/index.tsx
Labels: [Status] Needs Review

#104676 Theme Showcase: Show an unsupported message on third-party themes
  client/my-sites/theme/theme-support-tab/index.jsx
Labels: [Status] Needs Review

#104683 Stepper: Fix the user step margin style regression
  client/landing/stepper/declarative-flow/internals/steps-repository/__user/style.scss
Labels: [Status] Needs Review

#104720 Hovercards - fix issue with low resolution gravatar in hovercard.
  client/components/gravatar-with-hovercards/gravatar-header/index.jsx
  client/components/gravatar-with-hovercards/hovercard-content.jsx
  client/components/gravatar-with-hovercards/index.jsx
Labels: [Status] Needs Review

#104724 Bump composite-checkout package to v2
  packages/composite-checkout/CHANGELOG.md
  packages/composite-checkout/package.json
Labels: [Status] Needs Review

#104725 Reader related: Fix flex column widths
  client/blocks/reader-related-card/style.scss
Labels: [Status] Needs Review

#104430 Command Palette: Refactor the logic for determining the locale slug
  apps/command-palette-wp-admin/src/index.js
  apps/command-palette-wp-admin/src/set-locale.ts
Labels: [Status] Needs Review

#104718 A4A: Add TOS link in the User profile dropdown menu.
  client/a8c-for-agencies/components/sidebar/header/profile-dropdown.tsx
  client/a8c-for-agencies/components/sidebar/header/style.scss
Labels: [Status] Needs Review, A8c Agencies

#104733 Update Studio download links on /me/get-apps to v1.5.5
  client/blocks/get-apps/apps-config.tsx
Labels: [Status] Needs Review

#104740 Restore and fix copy-assets to wpcom-checkout
  packages/wpcom-checkout/package.json
  yarn.lock
Labels: [Status] Needs Review

#104690 Site Overview v2: Implement Scan card
  client/dashboard/app/queries/site-scan.ts
  client/dashboard/app/router.tsx
  client/dashboard/components/time-since/index.tsx
  client/dashboard/data/site-scan.ts
  client/dashboard/sites/features.ts
  client/dashboard/sites/overview-card/card.stories.tsx
  client/dashboard/sites/overview-card/index.tsx
  client/dashboard/sites/overview-card/style.scss
  client/dashboard/sites/overview/comments-card.tsx
  client/dashboard/sites/overview/index.tsx
  client/dashboard/sites/overview/likes-card.tsx
  client/dashboard/sites/overview/scan-card.tsx
  client/dashboard/sites/overview/subscribers-card.tsx
  client/dashboard/sites/overview/views-card.tsx
  client/dashboard/sites/overview/visitors-card.tsx
Labels: [Status] Needs Review

#104713 My Home: Fix the site preview so it loads the expected admin-bar-blocking code
  client/dashboard/sites/site-preview/index.tsx
  client/my-sites/customer-home/cards/features/site-preview/index.tsx
  client/my-sites/customer-home/cards/features/site-preview/style.scss
Labels: [Status] Needs Review, Reviewer Can Merge

#104710 Dashboard v2: Add environment switcher to the secondary header
  client/dashboard/app/queries/site-owner-transfer.ts
  client/dashboard/app/queries/site-settings.ts
  client/dashboard/app/queries/site-staging-sites.ts
  client/dashboard/app/queries/site-users.ts
  client/dashboard/app/queries/site.ts
  client/dashboard/app/router.tsx
  client/dashboard/components/icons/index.tsx
  client/dashboard/data/constants.ts
  client/dashboard/data/site-staging-site.ts
  client/dashboard/data/site.ts
  client/dashboard/sites/features.ts
  client/dashboard/sites/site/environment-switcher.tsx
  client/dashboard/sites/site/index.tsx
Labels: [Status] Needs Review

#104746 Site overview v2: remove stats cards and the corresponding backend call
  client/dashboard/app/router.tsx
  client/dashboard/sites/overview/comments-card.tsx
  client/dashboard/sites/overview/index.tsx
  client/dashboard/sites/overview/likes-card.tsx
  client/dashboard/sites/overview/subscribers-card.tsx
  client/dashboard/sites/overview/views-card.tsx
  client/dashboard/sites/overview/visitors-card.tsx
Labels: [Status] Needs Review

#104747 Site Overview v2: Implement Scan upsell card
  client/dashboard/components/icons/index.tsx
  client/dashboard/sites/overview-card/index.tsx
  client/dashboard/sites/overview-card/style.scss
  client/dashboard/sites/overview/scan-card.tsx
  client/dashboard/sites/overview/upsell-card.tsx
Labels: [Status] Needs Review

#104680 One Tap Auth: Show centered progress bar overlay on form submission
  client/blocks/login/login-form.jsx
  client/blocks/login/one-tap-auth-loader-overlay.scss
  client/blocks/login/one-tap-auth-loader-overlay.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/__user/index.tsx
  packages/onboarding/src/step-container-v2/components/TopBar/TopBar.tsx
  packages/onboarding/src/step-container-v2/wireframes/Loading/Loading.tsx
Labels: [Status] Needs Review

#104535 Marketing: Add Activitypub card
  client/assets/images/icons/activitypub-logo.svg
  client/sites/marketing/tools/marketing-features-data.ts
Labels: [Status] Needs Review

#104739 ActivityPub: Redirect to Onboarding after activation
  client/my-sites/site-settings/fediverse-settings/WpcomFediverseSettingsSection.js
Labels: [Status] Needs Review

#104742 Bump wpcom-checkout package to 1.0.1
  packages/wpcom-checkout/package.json
Labels: [Status] Needs Review

#104704 Connect Refresh: Remove `isWhiteLogin`. Replace with `! isGravatar` where relevant
  client/assets/stylesheets/_wp-components-overrides.scss
  client/blocks/authentication/form-divider/style.scss
  client/blocks/login/continue-as-user.scss
  client/blocks/login/index.jsx
  client/blocks/login/login-form.scss
  client/blocks/login/stories/shared.tsx
  client/blocks/login/style.scss
  client/layout/logged-out.jsx
  client/layout/masterbar/blaze-pro.scss
  client/layout/masterbar/woo.scss
  client/login/controller.js
  client/login/magic-login/index.jsx
  client/login/magic-login/style.scss
  client/login/qr-code-login-page/index.jsx
  client/login/wp-login/index.jsx
  client/login/wp-login/style.scss
  test/e2e/specs/martech/tos-screenshots__login-white.ts
Labels: [Status] Needs Review

#104745 AppBanner: fix accidental removal
  client/layout/index.jsx
Labels: [Status] Needs Review

#104689 Hosting Dashboard: Improve `userPreferencesQuery()` types and force all preferences to have a default
  client/dashboard/app/queries/me-preferences.ts
  client/dashboard/app/router.tsx
  client/dashboard/data/me-preferences.ts
  client/dashboard/data/types.ts
  client/dashboard/sites/index.tsx
  client/dashboard/sites/views.ts
  client/sites/v2/sites-list/router.tsx
Labels: [Status] Needs Review

#104761 Use risk instead of threat
  client/dashboard/sites/overview/scan-card.tsx
Labels: [Status] Needs Review

#104755 Site overview v2: add Last Backup card
  client/dashboard/app/queries/site-backups.ts
  client/dashboard/app/router.tsx
  client/dashboard/components/time-since/index.tsx
  client/dashboard/data/site-jetpack-rewind-backups.ts
  client/dashboard/data/types.ts
  client/dashboard/sites/fields.tsx
  client/dashboard/sites/overview/backup-card.tsx
  client/dashboard/sites/overview/index.tsx
  client/dashboard/sites/site-fields/index.tsx
Labels: [Status] Needs Review

#104735 Connect Refresh: Magin login - ensure link to reset-your-password is to the unified screen
  client/login/magic-login/emailed-login-link-successfully.jsx
Labels: [Status] Needs Review

#104736 Connect Refresh: Magic login - deprecate `calypso_magic_login_lost_password_click` Tracks event
  client/login/magic-login/emailed-login-link-successfully.jsx
Labels: [Status] Needs Review

#104762 A4A > Reports: Hide the reports without a managed site
  client/a8c-for-agencies/sections/reports/lib/get-site-reports.ts
Labels: [Status] Needs Review, A8c Agencies

#104738 Staging Sites: Allow syncing from Production to Staging
  client/sites/staging-site/components/staging-site-sync-modal/index.tsx
  client/sites/staging-site/hooks/use-staging-sync.ts
Labels: [Status] Needs Review

#104773 Recommend blogs: Fix site icon alignment
  client/reader/user-profile/style.scss
Labels: [Status] Needs Review

#104759 Staging Sites Redesign: Update sync button when site is synchronized
  client/dashboard/sites/staging-site-sync-dropdown/index.tsx
  client/sites/components/site-preview-pane/preview-pane-header-buttons.tsx
  client/sites/staging-site/components/staging-site-sync-modal/index.tsx
Labels: [Status] Needs Review

#104613 A4A: Add Wordcamp US 2025 event tracker in the Overview page.
  client/a8c-for-agencies/components/copy-to-clipboard-button/index.tsx
  client/a8c-for-agencies/components/upcoming-event/index.tsx
  client/a8c-for-agencies/components/upcoming-event/style.scss
  client/a8c-for-agencies/sections/overview/body/events/hooks/use-upcoming-events.tsx
  client/a8c-for-agencies/sections/overview/body/events/styles.scss
  client/assets/images/a8c-for-agencies/events/wordcamp-us2025-image.svg
  client/assets/images/a8c-for-agencies/events/wporg-logo-green.svg
Labels: [Status] Needs Review, A8c Agencies

#104778 Connections: Add tracking to Fediverse toggle
  client/my-sites/site-settings/fediverse-settings/WpcomFediverseSettingsSection.js
Labels: [Status] Needs Review

#104125 Fix build errors in Crowdsignal button stories
  client/blocks/login/stories/submit-button/crowdsignal.stories.tsx
  client/blocks/signup-form/stories/submit-button/crowdsignal.stories.tsx
Labels: [Status] Needs Review

#104768 Site Domains: Enable premium suggestions
  packages/domain-picker/src/utils/index.ts
Labels: [Status] Needs Review

#104777 Connect Refresh: Stop showing the JP AppPromo in OAuth client Magic Login
  client/login/magic-login/index.jsx
Labels: [Status] Needs Review

#104775 Connect Refresh: Update ToS in Magic Login to not mention "By creating an account..."
  client/login/magic-login/index.jsx
Labels: [Status] Needs Review

#104756 HC: Stay on last support interaction
  packages/help-center/src/components/help-center-chat.tsx
  packages/help-center/src/components/help-center-content.tsx
  packages/help-center/src/components/help-center-support-chat-message.tsx
  packages/help-center/src/hooks/index.ts
  packages/help-center/src/hooks/use-last-support-interaction.ts
Labels: [Status] Needs Review

#104629 Untangling: Show "Jetpack -> Monetize" callout in "Tools -> Monetize"
  client/components/feature-moved/index.tsx
  client/components/feature-moved/style.scss
  client/my-sites/earn/controller.ts
  client/my-sites/earn/index.ts
  client/my-sites/earn/jetpack-monetize/images/menu-ar.png
  client/my-sites/earn/jetpack-monetize/images/menu-de.png
  client/my-sites/earn/jetpack-monetize/images/menu-en.png
  client/my-sites/earn/jetpack-monetize/images/menu-es.png
  client/my-sites/earn/jetpack-monetize/images/menu-fr.png
  client/my-sites/earn/jetpack-monetize/images/menu-he.png
  client/my-sites/earn/jetpack-monetize/images/menu-id.png
  client/my-sites/earn/jetpack-monetize/images/menu-it.png
  client/my-sites/earn/jetpack-monetize/images/menu-ja.png
  client/my-sites/earn/jetpack-monetize/images/menu-ko.png
  client/my-sites/earn/jetpack-monetize/images/menu-nl.png
  client/my-sites/earn/jetpack-monetize/images/menu-pt-br.png
  client/my-sites/earn/jetpack-monetize/images/menu-ru.png
  client/my-sites/earn/jetpack-monetize/images/menu-sv.png
  client/my-sites/earn/jetpack-monetize/images/menu-tr.png
  client/my-sites/earn/jetpack-monetize/images/menu-zh-cn.png
  client/my-sites/earn/jetpack-monetize/images/menu-zh-tw.png
  client/my-sites/earn/jetpack-monetize/index.tsx
  client/my-sites/sidebar/utils.js
Labels: [Status] Needs Review

#104774 Site overview v2: fix Last Backup and Last Scan hosting feature logic
  client/dashboard/app/router.tsx
  client/dashboard/data/constants.ts
  client/dashboard/sites/features.ts
  client/dashboard/sites/hosting-feature-gate/index.tsx
  client/dashboard/sites/hosting-feature-gated-with-overview-card/index.tsx
  client/dashboard/sites/overview-card/index.tsx
  client/dashboard/sites/overview-card/upsell.tsx
  client/dashboard/sites/overview/backup-card.tsx
  client/dashboard/sites/overview/scan-card.tsx
  client/dashboard/sites/site-fields/index.tsx
  client/dashboard/utils/site-features.ts
Labels: [Status] Needs Review

#104798 Theme showcase: fix pagination
  client/my-sites/themes/themes-selection.jsx
Labels: [Status] Needs Review, Reviewer Can Merge

#104765 Site Overview v2: Implement A4A Share card
  client/dashboard/app/router.tsx
  client/dashboard/sites/overview-card/index.tsx
  client/dashboard/sites/overview-card/style.scss
  client/dashboard/sites/overview/agency-site-share-card.tsx
  client/dashboard/sites/overview/index.tsx
Labels: [Status] Needs Review

#104794 Domain Search Retrofitting: Create DomainSuggestionLoadMore button component
  client/components/domain-search-v2/register-domain-step/index.jsx
  packages/domain-search/src/components/domain-search/style.scss
  packages/domain-search/src/components/domain-suggestion-load-more/index.tsx
  packages/domain-search/src/components/domain-suggestion-load-more/style.scss
  packages/domain-search/src/index.ts
Labels: [Status] Needs Review

#104803 Fix TS lint
  client/dashboard/sites/overview/agency-site-share-card.tsx
Labels: [Status] Needs Review

#104764 Reader Council: add the banner back
  client/reader/stream/index.jsx
Labels: [Status] Ready to Merge, Reader

#104767 Connect Refresh: Clean up styles for login-form ToS (only used for Gravatar)
  client/blocks/login/login-form.jsx
  client/blocks/login/style.scss
  client/layout/masterbar/blaze-pro.scss
  client/layout/masterbar/oauth-client.scss
  client/layout/masterbar/woo.scss
  client/login/wp-login/style.scss
Labels: [Status] Needs Review

#104329 Update Speed Test Tool links to local ones
  client/performance-profiler/components/core-web-vitals-display/core-web-vitals-details.tsx
  client/performance-profiler/components/disclaimer-section/index.tsx
  client/performance-profiler/components/performance-score/index.tsx
  client/performance-profiler/utils/metrics.ts
  client/site-profiler/components/footnote/index.tsx
Labels: [Status] Needs Review

#104792 Help Center: use first message instead of the last message in messasge summary
  packages/odie-client/src/data/use-get-odie-conversations.ts
Labels: [Status] Needs Review

#104805 Untangling: Show "Jetpack > Podcasting" callout
  client/components/feature-moved/index.tsx
  client/my-sites/site-settings/settings-podcast/controller.ts
  client/my-sites/site-settings/settings-podcast/index.ts
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-ar.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-de.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-en.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-es.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-fr.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-he.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-id.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-it.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-ja.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-ko.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-nl.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-pt-br.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-ru.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-sv.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-tr.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-zh-cn.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-zh-tw.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/index.tsx
  client/sections.js
Labels: [Status] Needs Review

#104791 Domain Search Retrofitting: Apply new designs to featured domains
  client/components/domain-search-v2/domain-registration-suggestion/index.jsx
  client/components/domain-search-v2/domain-search-results/index.jsx
  client/components/domain-search-v2/featured-domain-suggestions/index.jsx
  client/components/domain-search-v2/featured-domain-suggestions/placeholder.jsx
  client/components/domain-search-v2/featured-domain-suggestions/placeholder.scss
  client/components/domain-search-v2/featured-domain-suggestions/style.scss
  packages/domain-search/src/components/domain-search/style.scss
  packages/domain-search/src/components/domain-suggestion-badge/index.tsx
  packages/domain-search/src/components/domain-suggestion-badge/style.scss
  packages/domain-search/src/components/domain-suggestion-cta/index.tsx
  packages/domain-search/src/components/domain-suggestion-match-reasons/index.tsx
  packages/domain-search/src/components/domain-suggestion-match-reasons/style.scss
  packages/domain-search/src/components/domain-suggestion-price/index.tsx
  packages/domain-search/src/components/domain-suggestion/featured.scss
  packages/domain-search/src/components/domain-suggestion/featured.stories.tsx
  packages/domain-search/src/components/domain-suggestion/featured.tsx
  packages/domain-search/src/components/domain-suggestion/index.tsx
  packages/domain-search/src/components/domain-suggestion/unavailable.tsx
  packages/domain-search/src/components/domain-suggestions-list/index.tsx
  packages/domain-search/src/hooks/use-domain-suggestion-container.ts
Labels: [Status] Needs Review

#104776 Domain Search Retrofitting: Create "Skip" suggestions component
  client/components/domain-search-v2/domain-search-results/index.jsx
  client/components/domain-search-v2/domain-skip-suggestion/index.tsx
  client/components/domain-search-v2/domain-skip-suggestion/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/index.tsx
  packages/domain-search/src/components/domain-suggestion-cta/index.tsx
  packages/domain-search/src/components/domain-suggestion-cta/style.scss
  packages/domain-search/src/components/domain-suggestion/featured.tsx
Labels: [Status] Needs Review

#104799 Workflows: update stalebot to only operate on pull requests
  .github/workflows/mark-issue-stale.yml
Labels: [Status] Needs Review, [Type] Task, github_actions

#104812 Domain Search Retrofitting: Show free domain promo conditionally
  client/components/domain-search-v2/domain-cart/free-domain-for-a-year-promo.tsx
  client/components/domain-search-v2/domain-cart/index.tsx
  client/components/domain-search-v2/domain-search-results/index.jsx
  client/components/domain-search-v2/free-domain-for-a-year-promo/graphic.svg
  client/components/domain-search-v2/free-domain-for-a-year-promo/index.tsx
  client/components/domain-search-v2/free-domain-for-a-year-promo/style.scss
  client/components/domain-search-v2/register-domain-step/index.jsx
  client/signup/steps/domains/index.jsx
  packages/domain-search/src/index.ts
Labels: [Status] Needs Review
