Repository Automattic/wp-calypso, pull requests merged in 2025-08, with the labels that each got.

#104959 Sites Overview v2: Implement Jetpack Plan card
  client/dashboard/data/constants.ts
  client/dashboard/data/site-purchases.ts
  client/dashboard/sites/fields.tsx
  client/dashboard/sites/overview-card/style.scss
  client/dashboard/sites/overview-plan-card/index.tsx
  client/dashboard/sites/overview-plan-card/style.scss
  client/dashboard/sites/settings-caching/index.tsx
  client/dashboard/sites/settings-php/index.tsx
  client/dashboard/sites/site-fields/index.tsx
  client/dashboard/utils/site-features.ts
  client/dashboard/utils/site-plan.ts
  packages/components/src/logos/jetpack-logo/index.tsx
Labels: [Status] Needs Review

#105025 Callout component: Set the max-width only when it's inside the CalloutOverlay
  client/components/feature-moved/style.scss
  client/dashboard/components/callout-overlay/style.scss
  client/dashboard/components/callout/styles.scss
  client/dashboard/sites/overview-card/style.scss
Labels: [Status] Needs Review

#105009 GitHub Deployments: Add confirmation dialog for manual production deployments
  client/sites/deployments/deployments/deployments-list-item.tsx
  client/sites/deployments/deployments/styles.scss
Labels: [Status] Needs Review

#104995 Hosting Overview: Add plan description and link for a4a sites
  client/dashboard/sites/overview-plan-card/index.tsx
  client/dashboard/sites/overview-plan-card/site-bandwidth-stat.tsx
  client/dashboard/sites/overview-plan-card/site-storage-stat.tsx
Labels: [Status] Needs Review, Reviewer Can Merge

#104958 Add flow_name for domain registration products in cart
  client/landing/stepper/declarative-flow/flows/hundred-year-domain/hundred-year-domain.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx
  client/me/domain-upsell/index.jsx
  client/my-sites/customer-home/cards/features/domain-upsell/index.jsx
  client/my-sites/customer-home/cards/tasks/domain-upsell/index.jsx
  client/signup/steps/domains/index.jsx
  client/signup/steps/site-or-domain/index.jsx
  packages/shopping-cart/src/types.ts
Labels: [Status] Needs Review

#104956 Stats: Fix TS errors for Line Chart
  client/my-sites/stats/components/line-chart/index.tsx
  package.json
  yarn.lock
Labels: [Type] Bug, [Feature] Stats, [Status] Needs Review

#104973 A4A: Fix missing BD product name in client cancel modal
  client/a8c-for-agencies/sections/client/cancel-subscription-confirmation-dialog/index.tsx
Labels: [Status] Needs Review

#105043 Callout: Update the upsell icon
  client/dashboard/components/icons/index.tsx
Labels: [Status] Needs Review

#104918 My Jetpack: Show the new page layout to reconnecting users
  client/jetpack-connect/authorize.js
  client/jetpack-connect/disclaimer.jsx
  client/jetpack-connect/style.scss
Labels: [Status] Needs Review

#105044 Siteless URLs in Billing: Add comment clarifying hidden domains
  client/me/purchases/billing-history/field-definitions.tsx
Labels: [Status] Needs Review

#105026 A4A: Add VIP Webinar event in the Overview page.
  client/a8c-for-agencies/components/upcoming-event/index.tsx
  client/a8c-for-agencies/components/upcoming-event/types.ts
  client/a8c-for-agencies/sections/overview/body/events/hooks/use-upcoming-events.tsx
  client/a8c-for-agencies/sections/overview/body/events/styles.scss
  client/a8c-for-agencies/style.scss
  client/assets/images/a8c-for-agencies/events/vip-compliment-image.svg
  client/assets/images/a8c-for-agencies/events/vip-logo.svg
Labels: [Status] Needs Review, A8c Agencies

#104637 SIte Migration: Use history.back to manage the flow navigation instead of do it manually
  client/landing/stepper/declarative-flow/flows/site-migration-flow/site-migration-flow.ts
  client/landing/stepper/declarative-flow/flows/site-migration-flow/test/site-migration-flow.tsx
  client/landing/stepper/declarative-flow/flows/site-setup-flow/site-setup-flow.ts
  client/landing/stepper/declarative-flow/internals/hooks/use-step-navigation-with-tracking/can-use-automatic-go-back/index.tsx
  client/landing/stepper/declarative-flow/internals/hooks/use-step-navigation-with-tracking/can-use-automatic-go-back/test/index.test.tsx
  client/landing/stepper/declarative-flow/internals/hooks/use-step-navigation-with-tracking/index.ts
  client/landing/stepper/declarative-flow/internals/hooks/use-step-navigation-with-tracking/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/create-site/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-already-wpcom/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-application-password-authorization/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-fallback-credentials/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-import-or-migrate/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-other-platform-detected-import/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-upgrade-plan/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-picker/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/test/helpers/index.tsx
  client/landing/stepper/utils/checkout.ts
  client/my-sites/checkout/src/lib/leave-checkout.ts
  client/my-sites/checkout/src/test/leave-checkout.ts
Labels: [Status] Needs Review

#104852 Login: Fix UI issues with Jetpack login code input
  client/login/magic-login/verify-login-code.jsx
Labels: [Status] Needs Review

#105011 Site overview v2: implement performance card
  client/dashboard/app/hooks/site-performance.ts
  client/dashboard/data/site-profiler.ts
  client/dashboard/sites/overview-card/index.tsx
  client/dashboard/sites/overview-card/style.scss
  client/dashboard/sites/overview-performance-card/index.tsx
  client/dashboard/sites/overview/index.tsx
  client/dashboard/utils/site-performance.ts
  client/hosting/performance/site-performance.tsx
  client/performance-profiler/components/performance-score/index.tsx
Labels: [Status] Needs Review

#105013 Support Search: Handle the new navigation header
  apps/happy-blocks/block-library/search-card/index.php
  apps/happy-blocks/block-library/search-card/style.scss
Labels: [Status] Needs Review

#105040 Connect: clicking "create an account" logs you out first
  client/login/wp-login/components/one-login-layout.tsx
Labels: [Status] Needs Review

#105017 Add all site domain-management routes and a placeholder
  client/dashboard/app/router.tsx
  client/dashboard/app/routes/domain-routes.ts
  client/dashboard/domains/dataviews/fields.tsx
  client/dashboard/sites/domains/placeholder.tsx
Labels: [Status] Needs Review

#105042 Site overview v2: implement Plan card remaining cases
  client/dashboard/sites/overview-plan-card/index.tsx
  client/dashboard/sites/site-fields/index.tsx
  client/dashboard/sites/site-fields/test/plan.tsx
  client/dashboard/utils/site-plan.ts
Labels: [Status] Needs Review

#105053 Update site plan display name logic
  client/dashboard/data/site.ts
  client/dashboard/utils/site-plan.ts
Labels: [Status] Needs Review

#105024 Dashboard v2: Add the trial ended page
  client/dashboard/app/queries/site-plans.ts
  client/dashboard/app/queries/site-purchases.ts
  client/dashboard/app/router.tsx
  client/dashboard/data/site-plans.ts
  client/dashboard/data/site-purchases.ts
  client/dashboard/data/site.ts
  client/dashboard/sites/features.ts
  client/dashboard/sites/site-menu/index.tsx
  client/dashboard/sites/site/index.tsx
  client/dashboard/sites/trial-ended/index.tsx
  client/dashboard/sites/trial-ended/style.scss
  client/dashboard/utils/site-trial.ts
  client/sites/v2/router.tsx
Labels: [Status] Needs Review

#105048 Staging Sites: Add some space below the title in the info card
  client/sites/staging-site/components/staging-site-management-move-info/index.tsx
Labels: [Status] Needs Review

#105049 A4A: Add new 'Strategic Agency Partner' tier
  client/a8c-for-agencies/sections/agency-tier/lib/get-agency-tier-info.tsx
  client/a8c-for-agencies/sections/agency-tier/lib/get-tier-benefits.ts
  client/a8c-for-agencies/sections/agency-tier/primary/agency-tier-overview/index.tsx
  client/a8c-for-agencies/sections/agency-tier/primary/agency-tier-overview/style.scss
  client/a8c-for-agencies/sections/agency-tier/types.ts
  client/a8c-for-agencies/sections/overview/sidebar/agency-tier/celebration-modal/style.scss
  client/assets/images/a8c-for-agencies/agency-tier/strategic-agency-partner-background.svg
  client/assets/images/a8c-for-agencies/agency-tier/strategic-agency-partner-logo-small.svg
  client/assets/images/a8c-for-agencies/agency-tier/strategic-agency-partner-logo.svg
  client/assets/images/a8c-for-agencies/agency-tier/strategic-agency-partner-vip-logo.svg
Labels: [Status] Needs Review, A4A

#105045 Staging sites: don't show domain-related actions
  client/dashboard/sites/overview-domains-card/index.tsx
  client/dashboard/sites/settings-site-visibility/privacy-form.tsx
  client/dashboard/sites/settings-site-visibility/test/index.tsx
Labels: [Status] Needs Review

#105056 Site Overview: Don't show *.wordpress.com domain on domains card for the atomic site
  client/dashboard/sites/overview-domains-card/index.tsx
Labels: [Status] Needs Review

#105055 Site Overview: Introduce Sync button
  client/dashboard/app/queries/site-staging-sites.ts
  client/dashboard/data/site-staging-site.ts
  client/dashboard/data/types.ts
  client/dashboard/sites/overview/index.tsx
  client/dashboard/sites/site/environment-switcher.tsx
  client/dashboard/sites/staging-site-sync-dropdown/index.tsx
  client/dashboard/utils/site-staging-site.ts
  client/sites/components/site-preview-pane/preview-pane-header-buttons.tsx
Labels: [Status] Needs Review

#105065 Staging Sites Redesign: Add a link to staging site settings
  client/sites/staging-site/components/staging-site-management-move-info/index.tsx
Labels: [Status] Needs Review

#104885 Jetpack Search purchase flow: Allow 'enter' key form submission during purchase flow
  client/jetpack-connect/site-url-input.jsx
Labels: [Status] Needs Review

#105078 A4A: Rename 'Strategic Agency Partner' to 'Premier Partner' tier
  client/a8c-for-agencies/sections/agency-tier/lib/get-agency-tier-info.tsx
  client/a8c-for-agencies/sections/agency-tier/lib/get-tier-benefits.ts
  client/a8c-for-agencies/sections/agency-tier/primary/agency-tier-overview/index.tsx
  client/a8c-for-agencies/sections/agency-tier/primary/agency-tier-overview/style.scss
  client/a8c-for-agencies/sections/agency-tier/types.ts
  client/a8c-for-agencies/sections/overview/sidebar/agency-tier/celebration-modal/style.scss
  client/assets/images/a8c-for-agencies/agency-tier/premier-partner-background.svg
  client/assets/images/a8c-for-agencies/agency-tier/premier-partner-logo-small.svg
  client/assets/images/a8c-for-agencies/agency-tier/premier-partner-logo.svg
  client/assets/images/a8c-for-agencies/agency-tier/strategic-agency-partner-vip-logo.svg
Labels: [Status] Needs Review

#104948 Connect Refresh (Signup): Backbone for unification and Woo migration
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/social.jsx
  client/blocks/signup-form/style.scss
  client/layout/logged-out.jsx
  client/layout/masterbar/woo.scss
  client/login/magic-login/index.jsx
  client/login/wp-login/components/heading-logo.tsx
  client/login/wp-login/components/one-login-layout.scss
  client/login/wp-login/components/one-login-layout.tsx
  client/login/wp-login/hooks/get-heading-subtext.tsx
  client/login/wp-login/style.scss
  client/signup/main.jsx
  client/signup/steps/user/index.jsx
  client/signup/style.scss
Labels: [Status] Needs Review

#105077 Hosting Config: Redirect to site settings or hosting features depends on the site type
  client/a8c-for-agencies/sections/purchases/licenses/license-preview/use-license-actions.ts
  client/a8c-for-agencies/sections/sites/site-actions/use-site-actions.ts
  client/hosting/overview/controller.tsx
  client/hosting/server-settings/components/hosting-upsell-nudge/index.tsx
  client/hosting/server-settings/main.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-actions/use-site-actions.ts
  client/jetpack-cloud/sections/partner-portal/license-preview/use-license-actions.ts
  client/layout/hosting-dashboard/item-view/item-view-header/index.tsx
  client/my-sites/checkout/checkout-thank-you/header.jsx
  client/my-sites/customer-home/cards/actions/quick-links-for-hosted-sites/index.jsx
  client/my-sites/customer-home/cards/tasks/revive-auto-reverted-atomic/index.tsx
  client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
  client/sites-dashboard/components/wpcom-smp-commands.tsx
  client/sites-dashboard/utils.ts
  client/sites/components/site-preview-pane/constants.ts
  client/sites/components/sites-dataviews/actions.tsx
  client/sites/controller.tsx
  client/sites/hosting/components/hosting-features.tsx
  client/sites/hosting/controller.tsx
  client/sites/hosting/index.tsx
  client/sites/settings/controller.tsx
  client/sites/staging-site/components/staging-site-card/card-content/manage-staging-site-card-content.tsx
  client/sites/v2/site-settings/controller.tsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#105074 Release Survicate service on prod and desktop only
  client/lib/analytics/survicate.js
  config/production.json
Labels: [Status] Needs Review, DO NOT MERGE

#105032 Staging Sites Redesign: Show banner while the staging site is transferring to Atomic
  client/layout/hosting-dashboard/item-view/index.tsx
  client/sites/staging-site/components/staging-site-transfer-banner/index.tsx
  client/sites/staging-site/components/staging-site-transfer-banner/staging-site-transfer-banner-background.svg
  client/sites/staging-site/components/staging-site-transfer-banner/staging-site-transfer-banner-illustration.svg
  client/sites/staging-site/components/staging-site-transfer-banner/style.scss
Labels: [Status] Needs Review

#105064 Staging Sites Redesign: Fix design issues with dropdowns
  client/dashboard/sites/staging-site-sync-dropdown/index.tsx
  client/sites/components/site-preview-pane/preview-pane-header-buttons.scss
  client/sites/components/site-preview-pane/site-environment-switcher.scss
Labels: [Status] Needs Review

#105063 Add domains/dnssec hosting dashboard
  client/dashboard/app/queries/domain-dnssec.ts
  client/dashboard/app/routes/domain-routes.ts
  client/dashboard/data/domain-dnssec.ts
  client/dashboard/data/domains.ts
  client/dashboard/domains/overview-dnssec/index.tsx
Labels: [Status] Needs Review

#104900 A4A > Referrals: Handle BD referral commissions
  client/a8c-for-agencies/sections/referrals/hooks/test/use-get-consolidated-payout-data.ts
  client/a8c-for-agencies/sections/referrals/hooks/use-get-consolidated-payout-data.ts
  client/a8c-for-agencies/sections/referrals/lib/get-estimated-commission.ts
  client/a8c-for-agencies/sections/referrals/lib/test/get-estimated-commission.ts
  client/a8c-for-agencies/sections/referrals/types.ts
Labels: [Status] Needs Review

#105094 A4A: Use Billing Dragon for Client Referrals
  config/a8c-for-agencies-production.json
Labels: A4A

#105041 Add storage warning banner to the top of overview page
  client/dashboard/app/queries/me-preferences.ts
  client/dashboard/app/router.tsx
  client/dashboard/components/notice/index.tsx
  client/dashboard/data/me-preferences.ts
  client/dashboard/sites/overview-plan-card/site-storage-stat.tsx
  client/dashboard/sites/overview/index.tsx
  client/dashboard/sites/overview/storage-warning-banner.tsx
  client/dashboard/sites/overview/test/storage-warning-banner.tsx
  client/dashboard/sites/settings-site-visibility/test/index.tsx
  client/dashboard/test-utils.tsx
  client/dashboard/utils/site-storage.ts
Labels: [Status] Needs Review

#105100 Dashboard v1: Fix the incorrect redirection when accessing feature tabs on simple sites
  client/hosting/performance/index.tsx
  client/sites/deployments/index.tsx
  client/sites/logs/index.tsx
  client/sites/monitoring/index.tsx
Labels: [Status] Needs Review

#105093 Reader: Add Freshly pressed tab
  client/my-sites/customer-home/cards/features/reader/index.tsx
  client/reader/discover/components/freshly-pressed/index.tsx
  client/reader/discover/components/freshly-pressed/lazy.tsx
  client/reader/discover/components/header-and-navigation/index.tsx
  client/reader/discover/components/navigation/index.tsx
  client/reader/discover/discover-stream.js
  client/reader/discover/helper/index.ts
  client/reader/discover/helper/test/index.test.ts
  client/reader/discover/index.node.js
  client/reader/discover/index.web.js
  client/reader/discover/routes/index.ts
  client/reader/discover/routes/test/index.test.ts
  config/development.json
  config/test.json
Labels: [Status] Needs Review

#105092 Sync Modal: Update wording for backup information message
  client/my-sites/backup/backup-contents-page/file-browser/index.tsx
Labels: [Status] Needs Review

#105102 A4A: Enable VIP Referrals on production
  config/a8c-for-agencies-production.json
Labels: A4A

#105091 Add the Domain Forwarding DataView
  client/dashboard/app/queries/domain-forwarding.ts
  client/dashboard/app/router.tsx
  client/dashboard/app/routes/domain-routes.ts
  client/dashboard/data/domain-forwarding.ts
  client/dashboard/domains/domain-forwardings/index.tsx
Labels: [Status] Needs Review

#105012 Connect Refresh: Migrate A4A to unified account-creation screen
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/social.jsx
  client/blocks/signup-form/style.scss
  client/layout/logged-out.jsx
  client/layout/masterbar/woo.scss
  client/signup/main.jsx
  client/signup/steps/user/index.jsx
  client/signup/style.scss
Labels: [Status] Needs Review

#105031 Stepper: Provide queryFn to the useQuery in useFlowState
  client/landing/stepper/declarative-flow/internals/state-manager/store.ts
  client/landing/stepper/index.tsx
Labels: [Status] Needs Review

#105084 Untangling: Deprecate "Hosting/Tools > Marketing > Traffic"
  client/my-sites/marketing/controller.js
  client/my-sites/marketing/index.js
  client/my-sites/marketing/main.jsx
  client/my-sites/sidebar/test/index.js
  client/my-sites/sidebar/utils.js
  client/sites/marketing/traffic/index.tsx
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-ar.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-de.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-en.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-es.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-fr.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-he.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-id.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-it.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-ja.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-ko.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-nl.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-pt-br.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-ru.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-sv.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-tr.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-zh-cn.png
  client/sites/marketing/traffic/jetpack-traffic/images/atomic/menu-zh-tw.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-ar.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-de.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-en.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-es.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-fr.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-he.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-id.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-it.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-ja.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-ko.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-nl.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-pt-br.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-ru.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-sv.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-tr.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-zh-cn.png
  client/sites/marketing/traffic/jetpack-traffic/images/simple/menu-zh-tw.png
  client/sites/marketing/traffic/jetpack-traffic/index.tsx
  client/sites/marketing/traffic/jetpack-traffic/style.scss
  client/sites/marketing/traffic/traffic.js
Labels: [Status] Needs Review

#105052 Allow editing of VAT details
  client/me/purchases/vat-info/types.ts
  client/me/purchases/vat-info/vat-form.tsx
  packages/wpcom-checkout/src/types.ts
Labels: [Status] Needs Review

#105101 A4A: Allow multiple payment methods for new referrals
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-horizon.json
  config/a8c-for-agencies-production.json
  config/a8c-for-agencies-stage.json
Labels: [Status] Needs Review

#105125 Enable flag dashboard/v2/backport/site-overview for horizon and wpcalypso
  config/horizon.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#105123 Site overview v2: make Latest Activity card readonly
  client/dashboard/sites/overview-latest-activity-card/index.tsx
  client/dashboard/sites/overview-latest-activity-card/style.scss
Labels: [Status] Needs Review

#105068 Add Payments tab for blaze dashboard
  apps/blaze-dashboard/src/routes.js
  client/data/promote-post/use-promote-post-payment-details-query.ts
  client/data/promote-post/use-promote-post-payments-query.ts
  client/my-sites/promote-post-i2/components/empty-promotion-list/index.tsx
  client/my-sites/promote-post-i2/components/payment-item/index.tsx
  client/my-sites/promote-post-i2/components/payments-filter/index.tsx
  client/my-sites/promote-post-i2/components/payments-filter/style.scss
  client/my-sites/promote-post-i2/components/payments-list/index.tsx
  client/my-sites/promote-post-i2/components/payments-list/style.scss
  client/my-sites/promote-post-i2/components/payments-receipt/Receipt.tsx
  client/my-sites/promote-post-i2/components/payments-receipt/WPComPrintLogo.tsx
  client/my-sites/promote-post-i2/components/payments-receipt/index.tsx
  client/my-sites/promote-post-i2/components/payments-receipt/print-utils.tsx
  client/my-sites/promote-post-i2/components/payments-receipt/style.scss
  client/my-sites/promote-post-i2/components/promoted-post-filter/index.tsx
  client/my-sites/promote-post-i2/controller.js
  client/my-sites/promote-post-i2/index.js
  client/my-sites/promote-post-i2/main.tsx
  client/my-sites/promote-post-i2/style.scss
  client/my-sites/promote-post-i2/utils/index.ts
Labels: [Status] Needs Review, [Status] String Freeze

#105087 Connect Refresh: Migrate Blaze Pro create-account to unified Signup
  client/assets/stylesheets/_wp-components-overrides.scss
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/social.jsx
  client/layout/logged-out.jsx
  client/layout/masterbar/blaze-pro.scss
  client/login/wp-login/style.scss
  client/signup/main.jsx
  client/signup/steps/user/index.jsx
Labels: [Status] Needs Review

#105141 Purchases: Convert more pieces of purchase settings to TypeScript
  client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-disabling-dialog/index.tsx
  client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-payment-method-dialog/index.tsx
  client/me/purchases/manage-purchase/auto-renew-toggle/index.tsx
  client/me/purchases/manage-purchase/index.tsx
  client/me/purchases/manage-purchase/plan-details/billing-period.tsx
  client/me/purchases/manage-purchase/plan-details/index.tsx
  client/state/plugins/premium/selectors.js
Labels: [Status] Needs Review

#105145 Add domain action Transfer to WP.com
  client/dashboard/domains/dataviews/actions.tsx
Labels: [Status] Needs Review

#105058 Hosting dashboard: Add a redirect to block in-progress DIFM sites
  client/dashboard/app/queries/site-do-it-for-me.ts
  client/dashboard/app/router.tsx
  client/dashboard/data/constants.ts
  client/dashboard/data/site-do-it-for-me.ts
  client/dashboard/data/site-domains.ts
  client/dashboard/data/types.ts
  client/dashboard/sites/difm-lite-in-progress/index.tsx
  client/dashboard/sites/site-menu/index.tsx
  client/dashboard/utils/domain.ts
Labels: [Status] Needs Review

#105126 Untangling: Deprecate "Hosting/Tools > Marketing > Sharing Buttons"
  client/my-sites/marketing/controller.js
  client/my-sites/marketing/settings-sharing/images/menu-ar.png
  client/my-sites/marketing/settings-sharing/images/menu-de.png
  client/my-sites/marketing/settings-sharing/images/menu-en.png
  client/my-sites/marketing/settings-sharing/images/menu-es.png
  client/my-sites/marketing/settings-sharing/images/menu-fr.png
  client/my-sites/marketing/settings-sharing/images/menu-he.png
  client/my-sites/marketing/settings-sharing/images/menu-id.png
  client/my-sites/marketing/settings-sharing/images/menu-it.png
  client/my-sites/marketing/settings-sharing/images/menu-ja.png
  client/my-sites/marketing/settings-sharing/images/menu-ko.png
  client/my-sites/marketing/settings-sharing/images/menu-nl.png
  client/my-sites/marketing/settings-sharing/images/menu-pt-br.png
  client/my-sites/marketing/settings-sharing/images/menu-ru.png
  client/my-sites/marketing/settings-sharing/images/menu-sv.png
  client/my-sites/marketing/settings-sharing/images/menu-tr.png
  client/my-sites/marketing/settings-sharing/images/menu-zh-cn.png
  client/my-sites/marketing/settings-sharing/images/menu-zh-tw.png
  client/my-sites/marketing/settings-sharing/index.tsx
  client/my-sites/marketing/settings-sharing/style.scss
Labels: [Status] Needs Review

#105134 Hide 'Add staging site' button while loading staging sites
  client/layout/hosting-dashboard/item-view/item-view-header/header-staging-site-button.tsx
Labels: [Status] Needs Review

#105159 Summer special: Update Install plugin tooltip copy
  client/blocks/summer-special-banner/index.jsx
  packages/calypso-products/src/features-list.tsx
Labels: [Status] Needs Review

#105139 Reader: Show Freshly pressed content
  client/reader/discover/components/freshly-pressed/index.tsx
  client/reader/discover/components/freshly-pressed/lazy.tsx
  client/reader/discover/discover-stream.js
  client/state/data-layer/wpcom/read/streams/index.js
  client/state/data-layer/wpcom/read/streams/test/index.js
Labels: [Status] Needs Review

#105162 Hosting Dashboard: Add DataViewsCard to PurchasesList
  client/dashboard/me/billing-purchases/index.tsx
Labels: [Status] Needs Review

#105167 Substack Import: fix flow bug
  client/my-sites/importer/newsletter/utils.tsx
Labels: [Status] Needs Review

#105174 Increase timeout between atomic transfer and redirect
  client/my-sites/marketplace/pages/marketplace-product-install/index.tsx
Labels: [Status] Needs Review

#105116 Connect Refresh: Migrate Akismet create-account to unified Signup
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/social.jsx
  client/layout/logged-out.jsx
  client/login/magic-login/index.jsx
  client/login/wp-login/components/heading-logo.tsx
  client/login/wp-login/components/one-login-layout.tsx
  client/login/wp-login/index.jsx
  client/signup/main.jsx
  client/signup/steps/user/index.jsx
  client/signup/style.scss
  client/state/selectors/get-is-akismet.ts
Labels: [Status] Needs Review

#105163 Fixes the Promote Post version check hook
  client/lib/promote-post/index.ts
Labels: [Status] Needs Review

#105176 Allow plugins upload for plans without sftp
  client/my-sites/plugins/plugin-upload/index.jsx
Labels: [Status] Needs Review

#105132 Connect Refresh: Migrate VIP create-account to unified Signup
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/social.jsx
  client/layout/logged-out.jsx
  client/signup/main.jsx
  client/signup/steps/user/index.jsx
Labels: [Status] Needs Review

#105142 Updating @wordpress/components and @wordpress/dataviews packages
  client/dashboard/sites/site-icon/style.scss
  client/my-sites/plugins/plugins-dashboard/style.scss
  package.json
  yarn.lock
Labels: [Status] Needs Review

#105158 Staging Sites Redesign: Update Tooltip and checkbox disable style
  client/sites/staging-site/components/staging-site-sync-modal/index.tsx
  client/sites/staging-site/components/staging-site-sync-modal/style.scss
Labels: [Status] Needs Review

#105118 Hosting Dashboard: Add site logs initial dataviews with data
  client/dashboard/app/queries/site-logs.ts
  client/dashboard/app/router.tsx
  client/dashboard/data/site-logs.ts
  client/dashboard/sites/logs/dataviews/views.ts
  client/dashboard/sites/logs/index.tsx
Labels: [Status] Needs Review

#103385 Components: Fix ambiguous `rem()` import
  packages/components/src/responsive-toolbar-group/style.scss
Labels: Components, Bug

#105175 A4A > Sign up: Show onboarding tour in WC flow
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/hooks/use-submit-signup.ts
Labels: [Status] Needs Review

#105161 Staging Sites: Add separate expand button and allow selecting nodes by clicking on them in the Jetpack Backup FileBrowser
  client/my-sites/backup/backup-contents-page/file-browser/file-browser-node.tsx
  client/my-sites/backup/backup-contents-page/file-browser/index.tsx
  client/sites/staging-site/components/staging-site-sync-modal/index.tsx
  client/sites/staging-site/components/staging-site-sync-modal/style.scss
Labels: [Status] Needs Review

#105184 Hosting Dashboard: Add domain glue records DataView
  client/dashboard/app/queries/domain-glue-records.ts
  client/dashboard/app/router.tsx
  client/dashboard/app/routes/domain-routes.ts
  client/dashboard/data/domain-glue-records.ts
  client/dashboard/domains/overview-glue-records/index.tsx
Labels: [Status] Needs Review

#105186 Packages: Add domain-search to tsconfig
  packages/tsconfig.json
Labels: [Status] Needs Review

#105192 Gravatar: Adjust login-related screens for Gravatar-owned services
  client/components/gravatar-login-logo/index.tsx
  client/components/gravatar-login-logo/style.scss
  client/lib/oauth2-clients.js
  client/login/magic-login/gravatar/index.tsx
  client/login/wp-login/gravatar/grav-powered-login-block-header.tsx
Labels: [Status] Needs Review, Login

#104544 Hosting dashboard: Add a custom empty state to the site list
  client/dashboard/components/dataviews-empty-state/index.stories.tsx
  client/dashboard/components/dataviews-empty-state/index.tsx
  client/dashboard/components/dataviews-empty-state/styles.scss
  client/dashboard/sites/index.tsx
  client/dashboard/sites/no-sites-illustration.svg
Labels: [Status] Needs Review, [Status] String Freeze

#105190 Backups Dashboard: add back up now button
  client/dashboard/app/queries/site-backups.ts
  client/dashboard/data/site-backup.ts
  client/dashboard/data/site-backups.ts
  client/dashboard/sites/backups/backup-now-button.tsx
  client/dashboard/sites/backups/index.tsx
Labels: [Status] Needs Review

#105129 Domains Hosting Dashboard: DNS records list
  client/dashboard/app/queries/domain-dns-records.ts
  client/dashboard/app/routes/domain-routes.ts
  client/dashboard/data/domain-dns-records.ts
  client/dashboard/data/domain.ts
  client/dashboard/domains/dns/add/dns-record-configs.ts
  client/dashboard/domains/dns/add/index.tsx
  client/dashboard/domains/domain-dns/actions.tsx
  client/dashboard/domains/domain-dns/dns-actions-menu.tsx
  client/dashboard/domains/domain-dns/fields.tsx
  client/dashboard/domains/domain-dns/index.tsx
  client/dashboard/domains/domain-dns/restore-default-a-records.tsx
  client/dashboard/domains/domain-dns/restore-default-cname-record.tsx
  client/dashboard/domains/domain-dns/restore-default-email-records.tsx
  client/dashboard/domains/domain-dns/utils.ts
  client/dashboard/domains/domain-dnssec/index.tsx
  client/dashboard/domains/domain-forwardings/index.tsx
Labels: [Status] Needs Review

#105193 Help Center: Implement new homepage conversation
  packages/components/src/summary-button/types.ts
  packages/help-center/src/components/help-center-recent-conversations.tsx
  packages/help-center/src/components/help-center-search-results.scss
  packages/help-center/src/components/help-center-support-chat-message.scss
  packages/help-center/src/components/help-center-support-chat-message.tsx
Labels: [Status] Needs Review

#101899 E2E: Disable double log in test from prelease tests
  test/e2e/specs/onboarding/onboarding__double-login.ts
Labels: [Status] Stale

#105191 Site Overview: Implement change site address action
  .eslintrc.js
  client/dashboard/app/queries/site-address-change.ts
  client/dashboard/components/clipboard-input-control/index.tsx
  client/dashboard/components/input-control/suffix-input-control.tsx
  client/dashboard/data/site-address-change.ts
  client/dashboard/domains/dataviews/actions.tsx
  client/dashboard/sites/site-change-address-modal/content.tsx
  client/me/purchases/vat-info/vat-form.tsx
  client/sites/staging-site/components/staging-site-sync-modal/index.tsx
  packages/components/src/validated-form-controls/components/input-control.tsx
Labels: [Status] Needs Review

#105206 fix(sites): prevent PreviewSizePicker crash from invalid previewSize …
  client/dashboard/sites/views.ts
Labels: [Status] Needs Review

#105062 Domains: Create name-servers component
  client/dashboard/app/queries/domain-name-servers.ts
  client/dashboard/app/routes/domain-routes.ts
  client/dashboard/data/domain-name-servers.ts
  client/dashboard/domains/name-servers/form.stories.tsx
  client/dashboard/domains/name-servers/form.tsx
  client/dashboard/domains/name-servers/index.tsx
  client/dashboard/domains/name-servers/types.ts
  client/dashboard/domains/name-servers/upsell-nudge-illustration.svg
  client/dashboard/domains/name-servers/upsell-nudge.tsx
  client/dashboard/domains/name-servers/utils.ts
Labels: [Status] Needs Review

#105047 Marketplace Site Selector: Fix highlight styles within component
  client/components/site-selector/style.scss
  client/components/theme-site-selector-modal/style.scss
  client/my-sites/sidebar/style.scss
Labels: [Status] Needs Review

#105113 Add the hosting dashboard domain forwarding add/edit form
  client/dashboard/app/queries/domain-forwarding.ts
  client/dashboard/app/routes/domain-routes.ts
  client/dashboard/data/domain-forwarding.ts
  client/dashboard/domains/domain-forwardings/add.tsx
  client/dashboard/domains/domain-forwardings/edit.tsx
  client/dashboard/domains/domain-forwardings/form.tsx
  client/dashboard/domains/domain-forwardings/utils.ts
Labels: [Status] Needs Review

#105203 Newsletter importer: Update billing warning copy
  client/my-sites/importer/newsletter/summary.tsx
Labels: [Status] Needs Review, [Status] Editorial Input Requested

#105156 Connect Refresh: Fix copy/layout issues with Woo DNA/JPC signup (create-account) form
  client/jetpack-connect/style.scss
  client/signup/steps/user/index.jsx
  client/signup/style.scss
Labels: [Status] Needs Review

#105131 Domain Search: Update experiment name
  client/lib/domains/use-domain-search-v2.ts
Labels: [Status] Needs Review

#105218 A4A: Enable multiple payment methods on production
  config/a8c-for-agencies-production.json
Labels: [Status] Needs Review

#105198 Site overview v2: show v1 migration status in retrofitted overview
  client/sites/overview/controller.tsx
Labels: [Status] Needs Review

#105207 Site Overview: Update the upsell link for performance and backups
  client/dashboard/sites/hosting-feature-gated-with-overview-card/index.tsx
  client/dashboard/sites/overview-backup-card/index.tsx
  client/dashboard/sites/overview-performance-card/index.tsx
  client/dashboard/sites/overview-scan-card/index.tsx
  client/dashboard/utils/site-backup.ts
  client/dashboard/utils/url.ts
Labels: [Status] Needs Review

#105197 Hosting Dashboard: Adding site logs fields
  client/dashboard/app/router.tsx
  client/dashboard/data/site-settings.ts
  client/dashboard/sites/logs/dataviews/fields.tsx
  client/dashboard/sites/logs/dataviews/style.scss
  client/dashboard/sites/logs/index.tsx
  client/dashboard/utils/datetime.ts
Labels: [Status] Needs Review

#105185 Connect Refresh: Clean up `isUnifiedCreateAccount`. Make it the default
  client/blocks/authentication/form-divider/style.scss
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/social.jsx
  client/blocks/signup-form/style.scss
  client/jetpack-connect/test/__snapshots__/signup.js.snap
  client/layout/logged-out.jsx
  client/layout/masterbar/blaze-pro.scss
  client/layout/masterbar/woo.scss
  client/signup/main.jsx
  client/signup/steps/user/index.jsx
  client/signup/steps/user/test/index.js
  client/signup/style.scss
Labels: [Status] Needs Review

#105209 Domains: Handle name-servers management access
  client/dashboard/data/domain.ts
  client/dashboard/domains/name-servers/form.stories.tsx
  client/dashboard/domains/name-servers/form.tsx
  client/dashboard/domains/name-servers/index.tsx
Labels: [Status] Needs Review

#105166 Add Backup details card
  client/dashboard/sites/backups/backup-details.tsx
  client/dashboard/sites/backups/backups-list.tsx
  client/dashboard/sites/backups/dataviews/fields.tsx
  client/dashboard/sites/backups/index.tsx
  client/dashboard/sites/backups/style.scss
Labels: [Status] Needs Review

#105219 Remove validated form controls
  packages/components/.storybook/preview.js
  packages/components/src/validated-form-controls/components/checkbox-control.stories.tsx
  packages/components/src/validated-form-controls/components/checkbox-control.tsx
  packages/components/src/validated-form-controls/components/combobox-control.stories.tsx
  packages/components/src/validated-form-controls/components/combobox-control.tsx
  packages/components/src/validated-form-controls/components/custom-select-control.stories.tsx
  packages/components/src/validated-form-controls/components/custom-select-control.tsx
  packages/components/src/validated-form-controls/components/input-control.stories.tsx
  packages/components/src/validated-form-controls/components/input-control.tsx
  packages/components/src/validated-form-controls/components/number-control.stories.tsx
  packages/components/src/validated-form-controls/components/number-control.tsx
  packages/components/src/validated-form-controls/components/radio-control.stories.tsx
  packages/components/src/validated-form-controls/components/radio-control.tsx
  packages/components/src/validated-form-controls/components/range-control.stories.tsx
  packages/components/src/validated-form-controls/components/range-control.tsx
  packages/components/src/validated-form-controls/components/select-control.stories.tsx
  packages/components/src/validated-form-controls/components/select-control.tsx
  packages/components/src/validated-form-controls/components/story-utils.tsx
  packages/components/src/validated-form-controls/components/text-control.stories.tsx
  packages/components/src/validated-form-controls/components/text-control.tsx
  packages/components/src/validated-form-controls/components/textarea-control.stories.tsx
  packages/components/src/validated-form-controls/components/textarea-control.tsx
  packages/components/src/validated-form-controls/components/toggle-control.stories.tsx
  packages/components/src/validated-form-controls/components/toggle-control.tsx
  packages/components/src/validated-form-controls/components/toggle-group-control.stories.tsx
  packages/components/src/validated-form-controls/components/toggle-group-control.tsx
  packages/components/src/validated-form-controls/components/types.ts
  packages/components/src/validated-form-controls/control-with-error.tsx
  packages/components/src/validated-form-controls/overview.mdx
  packages/components/src/validated-form-controls/overview.stories.tsx
  packages/components/src/validated-form-controls/style.scss
Labels: [Status] Needs Review, Code Quality

#105229 Connect Refresh: Clean up isUnifiedCreateAccount. Make it the default -- take 2
  client/blocks/authentication/form-divider/style.scss
  client/blocks/signup-form/index.jsx
  client/blocks/signup-form/social.jsx
  client/blocks/signup-form/style.scss
  client/jetpack-connect/test/__snapshots__/signup.js.snap
  client/layout/logged-out.jsx
  client/layout/masterbar/blaze-pro.scss
  client/layout/masterbar/woo.scss
  client/signup/main.jsx
  client/signup/steps/user/index.jsx
  client/signup/steps/user/test/index.js
  client/signup/style.scss
  packages/calypso-e2e/src/lib/pages/signup/user-signup-page.ts
  test/e2e/specs/onboarding/signup__wpcc.ts
Labels: [Status] Needs Review

#105239 Domain Search Rewrite: Create stub domain search connected component
  client/components/domains/wpcom-domain-search/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domain-search/index.tsx
  client/my-sites/domains/domain-search/index.tsx
  client/signup/steps/domain-search/index.tsx
  packages/domain-search/src/components/domain-search/index.tsx
  packages/domain-search/src/index.ts
  packages/domain-search/src/ui/index.ts
Labels: [Status] Needs Review

#105224 Dashboard v2: apply default font size to modals as well
  client/dashboard/app/style.scss
Labels: [Status] Needs Review

#105223 Site overview v2: implement empty state for Latest Activity card
  client/dashboard/sites/overview-latest-activity-card/index.tsx
  client/sites/v2/site-overview/style.scss
Labels: [Status] Needs Review

#105260 Hosting Dashboard Privacy: Implement DPA card
  client/dashboard/app/queries/me-dpa.ts
  client/dashboard/app/snackbars/index.tsx
  client/dashboard/data/me-dpa.ts
  client/dashboard/me/privacy/dpa-card.tsx
  client/dashboard/me/privacy/index.tsx
Labels: [Status] Needs Review

#105244 Dashboard v2: Refactor app router
  client/dashboard/app/router/domains.ts
  client/dashboard/app/router/emails.tsx
  client/dashboard/app/router/index.tsx
  client/dashboard/app/router/me.tsx
  client/dashboard/app/router/overview.tsx
  client/dashboard/app/router/root.tsx
  client/dashboard/app/router/sites.tsx
  client/dashboard/domains/dataviews/fields.tsx
  client/dashboard/domains/dns/add/index.tsx
  client/dashboard/domains/domain-dns/actions.tsx
  client/dashboard/domains/domain-dns/index.tsx
  client/dashboard/domains/domain-dnssec/index.tsx
  client/dashboard/domains/domain-forwardings/add.tsx
  client/dashboard/domains/domain-forwardings/edit.tsx
  client/dashboard/domains/domain-forwardings/index.tsx
  client/dashboard/domains/domain-menu/index.tsx
  client/dashboard/domains/domain-overview/index.tsx
  client/dashboard/domains/domain/index.tsx
  client/dashboard/domains/name-servers/index.tsx
  client/dashboard/domains/overview-glue-records/index.tsx
  client/dashboard/me/billing-purchases/index.tsx
  client/dashboard/me/billing/index.tsx
  client/dashboard/sites/backup-restore/index.tsx
  client/dashboard/sites/backups/backup-details.tsx
  client/dashboard/sites/backups/dataviews/actions.tsx
  client/dashboard/sites/backups/index.tsx
  client/dashboard/sites/deployments/index.tsx
  client/dashboard/sites/domains/index.tsx
  client/dashboard/sites/domains/placeholder.tsx
  client/dashboard/sites/emails/index.tsx
  client/dashboard/sites/index.tsx
  client/dashboard/sites/logs/dataviews/fields.tsx
  client/dashboard/sites/logs/index.tsx
  client/dashboard/sites/monitoring/index.tsx
  client/dashboard/sites/notices.tsx
  client/dashboard/sites/performance/index.tsx
  client/dashboard/sites/settings-page-header/index.tsx
  client/dashboard/sites/site/error.tsx
  client/dashboard/sites/site/index.tsx
  client/sites/v2/site-overview/router.tsx
  client/sites/v2/site-settings/router.tsx
  client/sites/v2/sites-list/router.tsx
Labels: [Status] Needs Review

#105155 A4A > WooPayments: Show estimated earnings for previous and current quarters
  client/a8c-for-agencies/sections/referrals/consolidated-view/payout-cards.tsx
  client/a8c-for-agencies/sections/referrals/consolidated-view/test/payout-cards.tsx
  client/a8c-for-agencies/sections/referrals/hooks/use-get-payout-data.ts
  client/a8c-for-agencies/sections/referrals/lib/get-next-payout-date.ts
  client/a8c-for-agencies/sections/woopayments/dashboard-content/consolidated-views.tsx
  client/a8c-for-agencies/sections/woopayments/types.ts
Labels: [Status] Needs Review

#104870 Do not allow components shared with dashboard to import Calypso code
  client/dashboard/.eslintrc.js
  client/dashboard/components/summary-button-list/test/index.tsx
  packages/components/.eslintrc.dashboard-shared.js
  packages/components/src/breadcrumbs/.eslintrc.js
  packages/components/src/circular-progress-bar/.eslintrc.js
  packages/components/src/logos/.eslintrc.js
  packages/components/src/summary-button/.eslintrc.js
Labels: [Status] Needs Review

#105233 Staging Sites Redesign: Sync button showing too early
  client/layout/hosting-dashboard/item-view/index.tsx
  client/sites/components/site-preview-pane/preview-pane-header-buttons.tsx
Labels: [Status] Needs Review

#105034 Update password reset page
  client/blocks/login/lost-password-form.jsx
  client/blocks/login/test/lost-password-form.jsx
  client/login/wp-login/components/one-login-footer.scss
  client/login/wp-login/components/one-login-footer.tsx
  client/login/wp-login/components/one-login-layout.tsx
  client/login/wp-login/hooks/get-header-text.tsx
  client/login/wp-login/index.jsx
Labels: [Status] Needs Review

#105273 Enable dashboard/v2/backport/site-overview in stage and production
  config/production.json
  config/stage.json
Labels: [Status] Needs Review

#105252 Hosting dashboard: Domains/Add dns zone import
  client/dashboard/app/queries/domain-dns-records.ts
  client/dashboard/data/domain-dns-records.ts
  client/dashboard/domains/domain-dns/dns-import-dialog.tsx
  client/dashboard/domains/domain-dns/import-bind-file-button.tsx
  client/dashboard/domains/domain-dns/index.tsx
Labels: [Status] Needs Review

#105278 Hosting Dashboard Update .eslintrc
  client/dashboard/.eslintrc.js
Labels: [Status] Needs Review

#105255 Help Center: Redesign recommend and more resources
  client/blocks/inline-help/inline-help-search-results.jsx
  packages/calypso-e2e/src/lib/components/help-center.ts
  packages/help-center/.stylelintrc
  packages/help-center/src/components/_mixins.scss
  packages/help-center/src/components/help-center-more-resources.scss
  packages/help-center/src/components/help-center-more-resources.tsx
  packages/help-center/src/components/help-center-search-results.scss
  packages/help-center/src/components/help-center-search-results.tsx
  packages/help-center/src/styles.scss
Labels: [Status] Needs Review

#105292 Domain Search Rewrite: Assemble the static search UI
  client/components/domain-search-v2/__legacy/domain-search/style.scss
  client/components/domain-search-v2/domain-cart/index.tsx
  client/components/domains/wpcom-domain-search/index.tsx
  client/dashboard/components/domain-search/index.tsx
  client/dashboard/components/domain-search/style.scss
  client/dashboard/components/page-layout/index.tsx
  client/dashboard/components/page-layout/style.scss
  client/dashboard/domains/purchase.tsx
  packages/domain-search/src/components/cart/index.tsx
  packages/domain-search/src/components/domain-search/index.tsx
  packages/domain-search/src/components/search-bar/index.tsx
  packages/domain-search/src/components/search-form/index.tsx
  packages/domain-search/src/components/search-results/index.tsx
  packages/domain-search/src/components/search-results/types.ts
  packages/domain-search/src/components/suggestion-cta/index.tsx
  packages/domain-search/src/index.ts
  packages/domain-search/src/page/context.ts
  packages/domain-search/src/page/index.tsx
  packages/domain-search/src/page/style.scss
  packages/domain-search/src/page/types.ts
  packages/domain-search/src/ui/domain-search-controls/input.tsx
  packages/domain-search/src/ui/domain-search-controls/submit.tsx
  packages/domain-search/src/ui/domains-full-cart-items/item.tsx
  packages/domain-search/src/ui/domains-full-cart/style.scss
  packages/domain-search/src/ui/domains-mini-cart/style.scss
Labels: [Status] Needs Review

#105294 Domain Search Rewrite: Add featured domains and badges to the domain search page
  client/dashboard/components/full-screen-overlay/style.scss
  packages/domain-search/package.json
  packages/domain-search/src/components/featured-search-results/index.tsx
  packages/domain-search/src/components/featured-search-results/item.tsx
  packages/domain-search/src/components/featured-search-results/placeholder.tsx
  packages/domain-search/src/components/search-form/index.tsx
  packages/domain-search/src/components/search-results/index.tsx
  packages/domain-search/src/components/search-results/item.tsx
  packages/domain-search/src/components/search-results/placeholder.tsx
  packages/domain-search/src/components/search-results/types.ts
  packages/domain-search/src/components/suggestion-cta/index.tsx
  packages/domain-search/src/helpers/partition-featured-suggestions.ts
  packages/domain-search/src/hooks/use-suggestion-badges.tsx
  packages/domain-search/src/hooks/use-suggestion.ts
  packages/domain-search/src/page/context.ts
  packages/domain-search/src/page/empty.tsx
  packages/domain-search/src/page/index.tsx
  packages/domain-search/src/page/results.tsx
  packages/domain-search/src/page/style.scss
  packages/domain-search/src/page/types.ts
  packages/domain-search/src/queries/availability.ts
  packages/domain-search/src/queries/suggestions.ts
  packages/domain-search/src/ui/featured-domain-suggestions-list/index.tsx
  packages/domain-search/src/ui/index.ts
  yarn.lock
Labels: [Status] Needs Review

#105279 Update isCountryInGdprZone and isRegionInCcpaZone to import from client/dashboard
  client/lib/analytics/test/gpc-opt-out.js
  client/lib/analytics/utils/is-gpc-flag-set.ts
  client/lib/analytics/utils/should-see-cookie-banner.ts
  client/lib/analytics/utils/use-do-not-sell.ts
  packages/calypso-analytics/src/index.ts
  packages/calypso-analytics/src/utils/get-tracking-prefs.ts
  packages/calypso-analytics/src/utils/is-country-in-gdpr-zone.ts
  packages/calypso-analytics/src/utils/is-region-in-ccpa-zone.ts
Labels: [Status] Needs Review

#105297 Domain Search Rewrite: Move Skip Purchase button to the package
  client/components/domain-search-v2/domain-search-results/index.jsx
  client/components/domain-search-v2/domain-skip-suggestion/index.tsx
  client/dashboard/app/router/sites.tsx
  client/dashboard/components/domain-search/index.tsx
  client/dashboard/sites/domains/index.tsx
  client/dashboard/sites/domains/purchase.tsx
  packages/domain-search/src/components/featured-search-results/index.tsx
  packages/domain-search/src/components/featured-search-results/item.tsx
  packages/domain-search/src/components/skip-suggestion/index.tsx
  packages/domain-search/src/helpers/partition-suggestions.ts
  packages/domain-search/src/page/index.tsx
  packages/domain-search/src/page/results.tsx
  packages/domain-search/src/page/types.ts
  packages/domain-search/src/queries/suggestions.ts
  packages/domain-search/src/ui/domain-search-skip-suggestion/index.placeholder.tsx
  packages/domain-search/src/ui/domain-search-skip-suggestion/index.skeleton.tsx
  packages/domain-search/src/ui/domain-search-skip-suggestion/index.tsx
  packages/domain-search/src/ui/domain-search-skip-suggestion/style.scss
  packages/domain-search/src/ui/index.ts
Labels: [Status] Needs Review

#105276 A4A > Marketplace: Refactor refer hosting form to support Enterprise and Premium plans
  client/a8c-for-agencies/components/sidebar-menu/lib/constants.ts
  client/a8c-for-agencies/sections/marketplace/controller.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-content/premier-agency-hosting/pressable-plan-section/premium-plan-section.tsx
  client/a8c-for-agencies/sections/marketplace/index.tsx
  client/a8c-for-agencies/sections/marketplace/refer-enterprise-hosting/hooks/use-refer-enterprise-hosting-mutation.ts
  client/a8c-for-agencies/sections/marketplace/refer-enterprise-hosting/types.ts
  client/a8c-for-agencies/sections/marketplace/refer-hosting/form.tsx
  client/a8c-for-agencies/sections/marketplace/refer-hosting/hooks/use-refer-hosting-form.ts
  client/a8c-for-agencies/sections/marketplace/refer-hosting/hooks/use-refer-hosting-mutation.ts
  client/a8c-for-agencies/sections/marketplace/refer-hosting/index.tsx
  client/a8c-for-agencies/sections/marketplace/refer-hosting/lib/get-form-data.ts
  client/a8c-for-agencies/sections/marketplace/refer-hosting/lib/get-referral-config.ts
  client/a8c-for-agencies/sections/marketplace/refer-hosting/style.scss
  client/a8c-for-agencies/sections/marketplace/refer-hosting/types.ts
  config/a8c-for-agencies-horizon.json
Labels: [Status] Needs Review, A8c Agencies

#105286 Summer Special banner: only show if Personal and Premium plans are visible
  client/blocks/summer-special-banner/index.jsx
Labels: [Status] Needs Review

#105172 Untangling: Remove "Jetpack > Subscribers" callout
  client/my-sites/sidebar/utils.js
  client/my-sites/subscribers/controller.js
  client/my-sites/subscribers/index.js
  client/my-sites/subscribers/jetpack-subscribers/images/menu-ar.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-de.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-en.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-es.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-fr.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-he.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-id.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-it.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-ja.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-ko.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-nl.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-pt-br.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-ru.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-sv.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-tr.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-zh-cn.png
  client/my-sites/subscribers/jetpack-subscribers/images/menu-zh-tw.png
  client/my-sites/subscribers/jetpack-subscribers/index.tsx
Labels: [Status] Needs Review

#105173 Untangling: Remove "Jetpack > Podcasting" callout
  client/my-sites/site-settings/settings-podcast/controller.ts
  client/my-sites/site-settings/settings-podcast/index.ts
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-ar.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-de.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-en.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-es.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-fr.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-he.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-id.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-it.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-ja.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-ko.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-nl.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-pt-br.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-ru.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-sv.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-tr.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-zh-cn.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/images/menu-zh-tw.png
  client/my-sites/site-settings/settings-podcast/jetpack-podcasting/index.tsx
  client/sections.js
Labels: [Status] Needs Review

#105171 Untangling: Remove "Jetpack > Monetize" callout
  client/my-sites/earn/controller.ts
  client/my-sites/earn/index.ts
  client/my-sites/earn/jetpack-monetize/images/menu-ar.png
  client/my-sites/earn/jetpack-monetize/images/menu-de.png
  client/my-sites/earn/jetpack-monetize/images/menu-en.png
  client/my-sites/earn/jetpack-monetize/images/menu-es.png
  client/my-sites/earn/jetpack-monetize/images/menu-fr.png
  client/my-sites/earn/jetpack-monetize/images/menu-he.png
  client/my-sites/earn/jetpack-monetize/images/menu-id.png
  client/my-sites/earn/jetpack-monetize/images/menu-it.png
  client/my-sites/earn/jetpack-monetize/images/menu-ja.png
  client/my-sites/earn/jetpack-monetize/images/menu-ko.png
  client/my-sites/earn/jetpack-monetize/images/menu-nl.png
  client/my-sites/earn/jetpack-monetize/images/menu-pt-br.png
  client/my-sites/earn/jetpack-monetize/images/menu-ru.png
  client/my-sites/earn/jetpack-monetize/images/menu-sv.png
  client/my-sites/earn/jetpack-monetize/images/menu-tr.png
  client/my-sites/earn/jetpack-monetize/images/menu-zh-cn.png
  client/my-sites/earn/jetpack-monetize/images/menu-zh-tw.png
  client/my-sites/earn/jetpack-monetize/index.tsx
  client/my-sites/sidebar/utils.js
Labels: [Status] Needs Review

#105308 Staging Sites: Fix site refresh issue
  client/sites/components/site-preview-pane/dotcom-preview-pane.tsx
Labels: [Status] Needs Review

#105301 Backups Dashboard: add restore feature
  client/dashboard/app/queries/site-backup-restore.ts
  client/dashboard/data/site-backup-restore.ts
  client/dashboard/sites/backup-restore/error.tsx
  client/dashboard/sites/backup-restore/form.tsx
  client/dashboard/sites/backup-restore/index.tsx
  client/dashboard/sites/backup-restore/progress.tsx
  client/dashboard/sites/backup-restore/success.tsx
Labels: [Status] Needs Review, [Feature] Hosting Dashboard

#105315 Tests: Remove Pay with PayPal block test after hiding the block from inserter
  test/e2e/specs/blocks/blocks__jetpack-earn.ts
Labels: [Pri] Normal, [Type] Janitorial

#105316 Domains: Fix CSS style of the org field explanation notice
  client/components/domains/contact-details-form-fields/style.scss
Labels: [Status] Needs Review

#105317 Domain Search Rewrite: Add common cart implementation
  client/components/domain-search-v2/domain-cart/index.tsx
  client/dashboard/app/shopping-cart/index.tsx
  client/dashboard/app/shopping-cart/use-wpcom-shopping-cart-for-domain-search.ts
  client/dashboard/components/domain-search/index.tsx
  client/dashboard/sites/domains/purchase.tsx
  packages/domain-search/src/components/cart/index.tsx
  packages/domain-search/src/components/suggestion-cta/index.tsx
  packages/domain-search/src/hooks/use-is-current-mutation.ts
  packages/domain-search/src/page/fallback-query-client.ts
  packages/domain-search/src/page/index.tsx
  packages/domain-search/src/page/types.ts
  packages/domain-search/src/queries/suggestions.ts
  packages/domain-search/src/ui/domains-full-cart-items/item.tsx
  packages/shopping-cart/src/types.ts
Labels: [Status] Needs Review

#105304 Notifications v2: add Settings menu action
  apps/notifications/src/app/note-panel/actions.tsx
  apps/notifications/src/app/note-panel/index.tsx
  apps/notifications/src/dropdown/index.tsx
  client/dashboard/app/notifications/index.tsx
  client/dashboard/app/secondary-menu/index.tsx
Labels: [Status] Needs Review

#105324 Notifications v2: refactor: dont async-load bell icon to avoid layout shift
  apps/notifications/src/dropdown/index.tsx
  client/dashboard/app/notifications/index.tsx
Labels: [Status] Needs Review

#105321 DataViews: Upgrade to 7.0.0
  apps/design-system-docs/package.json
  client/dashboard/domains/dns/form.tsx
  client/dashboard/domains/dns/records/a-record.tsx
  client/dashboard/domains/dns/records/aaaa-record.tsx
  client/dashboard/domains/dns/records/alias-record.tsx
  client/dashboard/domains/dns/records/caa-record.tsx
  client/dashboard/domains/dns/records/cname-record.tsx
  client/dashboard/domains/dns/records/dns-record-configs.ts
  client/dashboard/domains/dns/records/mx-record.tsx
  client/dashboard/domains/dns/records/ns-record.tsx
  client/dashboard/domains/dns/records/srv-record.tsx
  client/dashboard/domains/dns/records/txt-record.tsx
  client/dashboard/domains/domain-dns/email-setup-form.tsx
  client/dashboard/domains/domain-dnssec/index.tsx
  client/dashboard/domains/domain-forwardings/form.tsx
  client/dashboard/domains/name-servers/form.tsx
  client/dashboard/me/privacy/do-not-sell-card.tsx
  client/dashboard/me/privacy/usage-information-card.tsx
  client/dashboard/me/profile/index.tsx
  client/dashboard/sites/index.tsx
  client/dashboard/sites/settings-agency/index.tsx
  client/dashboard/sites/settings-caching/index.tsx
  client/dashboard/sites/settings-defensive-mode/index.tsx
  client/dashboard/sites/settings-hundred-year-plan/index.tsx
  client/dashboard/sites/settings-php/index.tsx
  client/dashboard/sites/settings-sftp-ssh/sftp-card.tsx
  client/dashboard/sites/settings-sftp-ssh/ssh-card.tsx
  client/dashboard/sites/settings-site-visibility/privacy-form.tsx
  client/dashboard/sites/settings-static-file-404/index.tsx
  client/dashboard/sites/settings-subscription-gifting/index.tsx
  client/dashboard/sites/settings-transfer-site/confirm-new-owner-form.tsx
  client/dashboard/sites/settings-transfer-site/start-site-transfer-form.tsx
  client/dashboard/sites/settings-web-application-firewall/allow-list-form.tsx
  client/dashboard/sites/settings-web-application-firewall/automatic-rules-form.tsx
  client/dashboard/sites/settings-web-application-firewall/block-list-form.tsx
  client/dashboard/sites/settings-web-application-firewall/protect-form.tsx
  client/dashboard/sites/settings-wordpress/index.tsx
  client/dashboard/sites/settings-wpcom-login/sso-form.tsx
  client/dashboard/sites/site-change-address-modal/content.tsx
  client/dashboard/sites/site-delete-modal/index.tsx
  client/dashboard/sites/site-leave-modal/content-info.tsx
  client/dashboard/sites/site-preview-links/index.tsx
  client/dashboard/sites/site-reset-modal/index.tsx
  client/me/purchases/vat-info/vat-form.tsx
  client/package.json
  package.json
  yarn.lock
Labels: [Status] Needs Review

#105333 Substack Importer: fix console errors
  client/my-sites/importer/newsletter/content-upload/author-mapping-pane.jsx
  client/my-sites/sidebar/menu.jsx
Labels: [Status] Needs Review

#105328 Experiment streamlining the plans grid + checkout: Enforce the winning solution of the experiment
  client/my-sites/plans-features-main/hooks/use-streamlined-price-experiment.ts
  client/my-sites/plans-features-main/index.tsx
Labels: [Status] Needs Review

#105254 Fix Wix import in Stepper
  client/blocks/importer/components/importer-drag/config.tsx
Labels: [Status] Needs Review

#105325 Retain the existing site list data when you start searching
  client/dashboard/sites/index.tsx
Labels: [Status] Needs Review

#105322 Ensure links are called "Preview links"
  client/dashboard/app/router/sites.tsx
  client/dashboard/sites/site-preview-links/index.tsx
Labels: [Status] Needs Review

#105243 Add Playwright Test library with three features
  .gitignore
  packages/calypso-e2e/package.json
  packages/calypso-e2e/src/lib/pages/login-page.ts
  packages/calypso-e2e/tsconfig.cjs.json
  test/e2e/README.md
  test/e2e/docs-new/files/example_test_report.png
  test/e2e/docs-new/new_style_guide.md
  test/e2e/docs-new/overview.md
  test/e2e/docs/tests_local.md
  test/e2e/lib/pw_base.ts
  test/e2e/package.json
  test/e2e/playwright.config.ts
  test/e2e/specs/a8c-for-agencies/signup__smoke.spec.ts
  test/e2e/specs/appearance/theme__details-preview.spec.ts
  test/e2e/specs/appearance/widgets__legacy-visibility.spec.ts
  test/e2e/specs/authentication/authentication__apple.spec.ts
  test/e2e/specs/authentication/authentication__magic-link.spec.ts
  test/e2e/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review, OSS Citizen

#105319 Notifications v2: Implement infinite scroll
  apps/notifications/package.json
  apps/notifications/src/app/context.ts
  apps/notifications/src/app/index.tsx
  apps/notifications/src/app/note-list/dataviews.tsx
  apps/notifications/src/app/note-list/index.tsx
  apps/notifications/src/app/note-panel/index.tsx
  apps/notifications/src/app/note/index.tsx
  apps/notifications/src/app/types.ts
  client/dashboard/app/notifications/index.tsx
  yarn.lock
Labels: [Status] Needs Review

#105330 Staging Sites: Ensure that the env switcher becomes available at the same time on prod and staging
  client/sites/components/site-preview-pane/dotcom-preview-pane.tsx
  client/sites/components/site-preview-pane/site-environment-switcher.tsx
  packages/sites/src/site-excerpt-constants.ts
Labels: [Status] Needs Review

#105350 Hosting Dashboard: Add notices/warning in DNS records page
  client/dashboard/domains/domain-dns/import-bind-file-button.tsx
  client/dashboard/domains/domain-dns/index.tsx
Labels: [Status] Needs Review

#105345 Domains: Allow users to disable transfer lock of .uk domains
  client/my-sites/domains/domain-management/transfer/transfer-out/select-ips-tag.jsx
  client/my-sites/domains/domain-management/transfer/transfer-page/index.tsx
Labels: [Status] Needs Review

#105348 Remove `lodash` dependency from `@automattic/i18n-utils`
  packages/i18n-utils/.eslintrc.js
  packages/i18n-utils/CHANGELOG.md
  packages/i18n-utils/src/locale-context.tsx
  packages/i18n-utils/src/test/utils.js
  packages/i18n-utils/src/utils.ts
Labels: [Status] Needs Review, [Type] Janitorial

#105346 Hosting Dashboard: Implement /me/apps
  client/dashboard/app-a4a/index.tsx
  client/dashboard/app-dotcom/index.tsx
  client/dashboard/app/context.tsx
  client/dashboard/app/router/me.tsx
  client/dashboard/components/svg-icon/index.tsx
  client/dashboard/me/apps/apps-card.tsx
  client/dashboard/me/apps/apps-desktop-card.tsx
  client/dashboard/me/apps/apps-mobile-card.tsx
  client/dashboard/me/apps/images/apple-logo.svg
  client/dashboard/me/apps/images/desktop-app-logo.svg
  client/dashboard/me/apps/images/jetpack-app-logo.svg
  client/dashboard/me/apps/images/linux-logo.svg
  client/dashboard/me/apps/images/studio-app-logo.svg
  client/dashboard/me/apps/images/windows-logo.svg
  client/dashboard/me/apps/index.tsx
  client/dashboard/me/me-menu/index.tsx
Labels: [Status] Needs Review

#105351 Notifications v2: show blue dot on icon on unseen notifications
  client/dashboard/app/notifications/index.tsx
  client/dashboard/app/notifications/style.scss
  client/dashboard/data/me.ts
Labels: [Status] Needs Review

#105341 Notifications v2: add Keybord Shortcuts action menu
  apps/notifications/src/app/note-panel/actions.tsx
  apps/notifications/src/app/note-shortcuts/index.tsx
  apps/notifications/src/app/note-shortcuts/style.scss
Labels: [Status] Needs Review

#105357 Hosting Dashboard: Initial structure for me/security
  client/dashboard/app/router/me.tsx
  client/dashboard/me/security-account-recovery/index.tsx
  client/dashboard/me/security-account-recovery/summary.tsx
  client/dashboard/me/security-connected-apps/index.tsx
  client/dashboard/me/security-connected-apps/summary.tsx
  client/dashboard/me/security-page-header/index.tsx
  client/dashboard/me/security-password/index.tsx
  client/dashboard/me/security-password/summary.tsx
  client/dashboard/me/security-social-logins/index.tsx
  client/dashboard/me/security-social-logins/summary.tsx
  client/dashboard/me/security-ssh-key/index.tsx
  client/dashboard/me/security-ssh-key/summary.tsx
  client/dashboard/me/security-two-step-auth/index.tsx
  client/dashboard/me/security-two-step-auth/summary.tsx
  client/dashboard/me/security/index.tsx
Labels: [Status] Needs Review

#105338 Experiment streamlining the plans grid + checkout: Enforce the winning solution of the experiment
  client/my-sites/checkout/src/test/checkout-main.tsx
  client/my-sites/checkout/src/test/composite-checkout-variant-picker-dropdown.tsx
  client/my-sites/plans-features-main/hooks/use-streamlined-price-experiment.ts
  client/my-sites/plans-features-main/index.tsx
Labels: [Status] Needs Review

#105310 Reader: Record algo during the like action
  client/reader/like-button/index.jsx
Labels: [Status] Needs Review

#105290 Hosting Dashboard: Adding a site logs downloader
  client/dashboard/data/site-logs.ts
  client/dashboard/sites/logs/downloader.tsx
  client/dashboard/sites/logs/index.tsx
Labels: [Status] Needs Review

#105305 Staging Sites: Add success notice and redirect to production site after successful staging site deletion
  client/dashboard/app/router/index.tsx
  client/dashboard/sites/staging-site-delete-modal/index.tsx
Labels: [Status] Needs Review

#105373 Hosting Dashboard: Import CSS overrides
  client/sites/v2/site-overview/style.scss
  client/sites/v2/site-settings/style.scss
  client/sites/v2/sites-list/style.scss
Labels: [Status] Needs Review

#105362 Help Center: Fix recent conversations alignment
  packages/help-center/.stylelintrc
  packages/help-center/src/components/help-center-header.scss
  packages/help-center/src/components/help-center-recent-conversations.scss
  packages/help-center/src/styles.scss
  packages/odie-client/src/style.scss
Labels: [Status] Needs Review

#105364 Hosting Dashboard Purchases: Fix payment method image size
  client/dashboard/me/billing-purchases/dataviews.tsx
  client/dashboard/me/billing-purchases/payment-method-image.tsx
  client/dashboard/me/billing-purchases/purchase-payment-method.tsx
  client/dashboard/me/billing-purchases/style.scss
Labels: [Status] Needs Review

#105344 Purchases: Update purchase types to use numbers for numbers
  client/dashboard/app/queries/me-purchases.ts
  client/dashboard/app/queries/site-purchases.ts
  client/dashboard/data/me-purchases.ts
  client/dashboard/data/purchase.ts
  client/dashboard/data/site-purchases.ts
  client/dashboard/data/upgrades.ts
  client/dashboard/domains/dataviews/actions.tsx
  client/dashboard/me/billing-purchases/dataviews.tsx
  client/dashboard/me/billing-purchases/purchase-settings/index.tsx
  client/me/purchases/downgrade/index.tsx
  client/me/purchases/manage-purchase/test/change-payment-method.tsx
  client/me/purchases/manage-purchase/test/purchase-management-buttons.js
  client/my-sites/checkout/src/components/test/lib/fixtures.ts
  client/state/purchases/test/selectors.js
  packages/data-stores/src/purchases/lib/assembler.ts
  packages/data-stores/src/purchases/types.ts
  packages/plans-grid-next/src/fixtures/sites-purchases.ts
Labels: [Status] Needs Review

#105361 Domain Search Rewrite: Add a data layer package to fetch suggestions
  client/components/domain-search-v2/register-domain-step/index.jsx
  client/dashboard/.eslintrc.js
  client/dashboard/app/queries/domains.ts
  client/dashboard/data/domains.ts
  client/package.json
  packages/data/README.md
  packages/data/jest.config.js
  packages/data/package.json
  packages/data/src/domain-suggestions/fetchers.ts
  packages/data/src/domain-suggestions/index.ts
  packages/data/src/domain-suggestions/types.ts
  packages/data/src/index.ts
  packages/data/src/wpcom-fetcher.ts
  packages/data/tsconfig-cjs.json
  packages/data/tsconfig.json
  packages/domain-search/package.json
  packages/domain-search/src/components/skip-suggestion/index.tsx
  packages/domain-search/src/components/suggestion-price/index.tsx
  packages/domain-search/src/helpers/partition-suggestions.ts
  packages/domain-search/src/page/types.ts
  packages/domain-search/src/queries/availability.ts
  packages/domain-search/src/queries/suggestions.ts
  packages/domain-search/tsconfig.json
  packages/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review
