Repository Automattic/wp-calypso, pull requests merged in 2025-01, with the labels that each got.

#97873 January Bump promo: Fix overflow breaking edge case
  client/my-sites/customer-home/cards/tasks/january-bump/style.scss
Labels: [Type] Bug, [Status] Needs Review

#97881 Sites Dashboard: Add margin-top to banner
  client/sites/components/dotcom-style.scss
Labels: [Status] Needs Review, Lego Maintenance

#97809 Email comparison: Add email upsell navigation to the compare plans page
  client/my-sites/email/controller.js
  client/my-sites/email/email-providers-comparison/in-depth/index.tsx
  client/my-sites/email/email-providers-comparison/in-depth/types.ts
Labels: [Status] Needs Review

#97808 Style Variations: Filter out the colors and fonts (2nd try)
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/hooks/use-recipe.ts
  client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx
  packages/data-stores/src/site/types.ts
  packages/data-stores/tsconfig.json
  packages/design-picker/package.json
  packages/design-picker/src/components/index.ts
  packages/design-picker/src/components/style-variation-badges/index.tsx
  packages/design-picker/src/components/style-variation-badges/utils.ts
  packages/design-picker/src/components/theme-card/index.tsx
  packages/design-picker/src/index.ts
  packages/design-picker/src/types.ts
  packages/design-picker/tsconfig.json
  packages/design-preview/src/hooks/use-inline-css.ts
  packages/global-styles/package.json
  packages/global-styles/src/components/global-styles-variations/index.tsx
  packages/global-styles/src/gutenberg-bridge/index.tsx
  packages/global-styles/src/types.ts
  packages/global-styles/src/utils.ts
  packages/global-styles/tsconfig.json
  yarn.lock
Labels: [Status] Needs Review

#97866 Update layout container height to full page height in /me pages
  client/me/style.scss
Labels: [Status] Needs Review

#97212 Update busy state for self-restore account
  client/me/account-close/closed.jsx
  client/me/account-close/closed.scss
Labels: [Status] Needs Review, [Status] String Freeze

#97641 Help Center: Underline links in article titles for better visibility
  packages/help-center/src/components/help-center-article.scss
Labels: [Status] Needs Review

#97861 Help Center: Add site domain to HC doc /plans link
  packages/data-stores/src/help-center/types.ts
  packages/help-center/src/hooks/use-content-filter.ts
Labels: [Status] Needs Review

#97883 Enable me/account-restore flag up to staging
  client/me/account-close/closed.jsx
  config/development.json
  config/horizon.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#97889 Stats: Record track events for date range navigation
  client/my-sites/stats/stats-period-navigation/index.jsx
Labels: [Feature] Stats, [Status] Needs Review

#97863 Stats: add locations module scaffolding using country views as a base
  client/my-sites/stats/features/modules/stats-locations/index.tsx
  client/my-sites/stats/features/modules/stats-locations/stats-locations.tsx
  client/my-sites/stats/features/modules/stats-locations/style.scss
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-strings.js
  client/my-sites/stats/summary/index.jsx
Labels: [Status] Needs Review

#97292 Add category selection to subscriber modal.
  client/my-sites/importer/newsletter/subscribers/upload-form.tsx
  client/my-sites/subscribers/components/add-subscribers-modal/add-subscribers-modal.tsx
  packages/data-stores/src/subscriber/actions.ts
  packages/subscriber/src/components/add-form/categories-section.tsx
  packages/subscriber/src/components/add-form/index.tsx
  packages/subscriber/src/components/add-form/style.scss
  packages/subscriber/src/components/upload-form/index.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#97729 Email Stats: Add Opens and Clicks tooltips
  client/my-sites/stats/features/modules/stats-emails/stats-emails.tsx
  client/my-sites/stats/features/modules/stats-emails/tooltips.tsx
  client/my-sites/stats/stats-email-summary/index.jsx
  client/state/stats/lists/utils.js
  packages/components/src/horizontal-bar-list/horizontal-bar-grid-item.tsx
  packages/components/src/horizontal-bar-list/types.ts
Labels: [Status] Needs Review

#97905 Newsletter: fix import CSV bug
  packages/data-stores/src/subscriber/actions.ts
Labels: [Status] Needs Review, Newsletter Categories

#97876 Remove dot from learn more text to make it uniform
  client/my-sites/people/subscribers-team/index.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/card-content-wrapper.tsx
Labels: [Status] Needs Review

#97913 Stats: Stop disabling module toggles
  client/blocks/stats-navigation/index.js
  client/blocks/stats-navigation/page-module-toggler.tsx
Labels: [Feature] Stats, [Status] Needs Review

#97868 Refactor a8c-for-agencies sites dashboard banner
  client/sites/components/sites-dashboard-banners-manager.tsx
  client/sites/components/sites-dashboard-banners/use-a8c-for-agencies-sites-banner.tsx
Labels: [Status] Needs Review

#97840 Stepper: Clear siteUrl data when skipping domain step
  client/signup/steps/domains/index.jsx
Labels: [Status] Needs Review

#97694 Hosting dashboard: Rework site logs header and toolbar
  client/hosting/logs/controller.tsx
  client/sites/tools/controller.tsx
  client/sites/tools/logs/components/filter-params.ts
  client/sites/tools/logs/components/site-logs-header/index.tsx
  client/sites/tools/logs/components/site-logs-header/style.scss
  client/sites/tools/logs/components/site-logs-table/index.tsx
  client/sites/tools/logs/components/site-logs-table/site-logs-table-row.tsx
  client/sites/tools/logs/components/site-logs-toolbar/date-time-picker.tsx
  client/sites/tools/logs/components/site-logs-toolbar/index.tsx
  client/sites/tools/logs/components/site-logs-toolbar/style.scss
  client/sites/tools/logs/components/site-logs.tsx
  client/sites/tools/logs/hooks/use-site-logs-downloader.ts
  client/sites/tools/logs/index.tsx
  client/sites/tools/logs/style.scss
Labels: [Status] Needs Review

#97893 Stats: Remove unused HighlightsSection component
  client/my-sites/stats/highlights-section/index.tsx
Labels: [Feature] Stats, [Status] Needs Review

#97895 Sites: Cleanup `CurrentSite` component, convert to FC
  client/my-sites/current-site/index.jsx
Labels: Sites, [Status] Needs Review, [Type] Janitorial

#97697 Update sites per plugin view for bulk management
  client/jetpack-cloud/sections/plugin-management/controller.tsx
  client/jetpack-cloud/sections/plugin-management/index.ts
  client/jetpack-cloud/sections/sidebar-navigation/lib/constants.ts
  client/my-sites/plugins/controller.js
  client/my-sites/plugins/index.web.js
  client/my-sites/plugins/plugin-management-v2/plugin-details-v2/plugin-available-on-sites-list.tsx
  client/my-sites/plugins/plugin-management-v2/plugin-details-v2/sites-with-installed-plugin-list.tsx
  client/my-sites/plugins/plugin-management-v2/sites-list/index.tsx
  client/my-sites/plugins/plugin-management-v2/types.ts
  client/my-sites/plugins/plugins-dashboard/index.tsx
  client/my-sites/plugins/plugins-dashboard/style.scss
  client/my-sites/plugins/plugins-list/plugins-list-dataviews.tsx
  client/my-sites/plugins/plugins-list/style-compatibilty.scss
  client/my-sites/plugins/plugins-list/style.scss
  client/my-sites/plugins/plugins-list/use-fields.tsx
  client/state/global-sidebar/selectors.ts
Labels: [Status] Needs Review

#97894 Theme: Cleanup unused code
  client/my-sites/theme/main.jsx
  client/my-sites/theme/style.scss
Labels: [Status] Needs Review, [Type] Janitorial, [Feature] Theme Showcase

#97907 Subscribers: Update placeholder text when adding subscribers with categories
  packages/subscriber/src/components/add-form/categories-section.tsx
Labels: [Status] Needs Review

#97896 Fixup domain row alignment
  client/components/domains/domain-product-price/style.scss
  client/components/domains/domain-suggestion/style.scss
Labels: [Status] Needs Review

#97942 Fix: more specific css rule on import list
  client/blocks/import/list/style.scss
Labels: [Status] Needs Review

#97794 Storage add-ons v2: Expose the extended storage add-ons behind the feature flag.
  config/development.json
  packages/data-stores/src/add-ons/add-ons-list.ts
  packages/data-stores/src/add-ons/constants.ts
  packages/data-stores/src/add-ons/hooks/use-add-ons.ts
  packages/data-stores/src/add-ons/hooks/use-available-storage-add-ons.ts
  packages/data-stores/src/add-ons/types.ts
  packages/plans-grid-next/src/components/shared/storage/hooks/use-storage-string-from-feature.ts
Labels: [Status] Needs Review, Storage Addon

#97862 Correct the storage dropdown list data
  packages/plans-grid-next/src/components/shared/storage/components/storage-dropdown.tsx
  packages/plans-grid-next/src/components/shared/storage/components/storage-feature-label.tsx
  packages/plans-grid-next/src/components/shared/storage/hooks/use-available-storage-dropdown-options.ts
  packages/plans-grid-next/src/components/shared/storage/hooks/use-default-storage-option.ts
  packages/plans-grid-next/src/components/shared/storage/hooks/use-plan-storage.ts
  packages/plans-grid-next/src/components/shared/storage/hooks/use-purchased-storage-add-on.ts
  packages/plans-grid-next/src/components/shared/storage/hooks/use-storage-string-from-feature.ts
  packages/plans-grid-next/src/components/shared/storage/hooks/use-storage-string.ts
  packages/plans-grid-next/src/components/test/actions-button.tsx
Labels: [Status] Needs Review, Storage Addon

#97969 Help Center: Return focus to input field after message submission
  packages/odie-client/src/components/send-message-input/index.tsx
Labels: [Status] Needs Review

#97965 Keep consistent punctuation (or lack thereof) in onboarding modals
  client/my-sites/plans-features-main/components/plan-upsell-modal/components/paid-domain-suggested-plan-section.tsx
Labels: [Status] Needs Review

#97884 Remove body overflow in hosting-dashboard styles to allow content scrolling
  client/layout/hosting-dashboard/style.scss
Labels: [Status] Needs Review

#97933 A4A: Remove the 'a4a-hosting-page-redesign' feature flag and conditional flows.
  client/a8c-for-agencies/components/a4a-contact-support-widget/index.tsx
  client/a8c-for-agencies/sections/marketplace/controller.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/details.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/referral-mode/index.tsx
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/lib/wpcom-bulk-options.ts
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-horizon.json
  config/a8c-for-agencies-production.json
  config/a8c-for-agencies-stage.json
Labels: [Status] Needs Review, A8c Agencies

#97932 Help Center: Change focus outline
  packages/help-center/src/components/_mixins.scss
  packages/help-center/src/components/help-center-footer.scss
  packages/help-center/src/components/help-center-header.scss
  packages/help-center/src/components/help-center-more-resources.scss
  packages/help-center/src/components/help-center-recent-conversations.scss
  packages/help-center/src/components/help-center-search-results.scss
  packages/help-center/src/components/help-center-search.scss
Labels: [Status] Needs Review

#96863 Add VS Code debugging configurations
  .vscode/extensions.json
  .vscode/launch.json
  docs/development-workflow.md
  package.json
Labels: [Status] Needs Review

#97891 Masterbar: Clean up for logged in users
  client/blocks/daily-post-button/README.md
  client/blocks/daily-post-button/docs/example.jsx
  client/blocks/daily-post-button/helper.js
  client/blocks/daily-post-button/index.jsx
  client/blocks/daily-post-button/style.scss
  client/blocks/daily-post-button/test/fixtures/index.js
  client/blocks/daily-post-button/test/helper.js
  client/blocks/daily-post-button/test/index.jsx
  client/blocks/reader-full-post/index.jsx
  client/blocks/reader-post-card/index.jsx
  client/blocks/site/style.scss
  client/components/sites-popover/README.md
  client/components/sites-popover/index.jsx
  client/components/sites-popover/style.scss
  client/devdocs/design/blocks.jsx
  client/layout/masterbar/drafts-popover.jsx
  client/layout/masterbar/drafts.jsx
  client/layout/masterbar/logged-in.jsx
  client/layout/masterbar/masterbar-menu.tsx
  client/layout/masterbar/publish.jsx
  client/layout/masterbar/style.scss
  client/layout/popup-search/index.js
  client/layout/popup-search/style.scss
  client/my-sites/draft/README.md
  client/my-sites/draft/index.jsx
  client/my-sites/draft/style.scss
  client/state/posts/counts/selectors.js
  client/state/posts/counts/test/selectors.js
  config/_shared.json
  config/client.json
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  packages/calypso-e2e/src/lib/components/navbar-component.ts
  packages/calypso-e2e/src/lib/flows/index.ts
  packages/calypso-e2e/src/lib/flows/new-post-flow.ts
Labels: [Status] Needs Review, [Type] Janitorial, Masterbar

#97975 A4A > Feedback: Remove feature flag logic
  client/a8c-for-agencies/sections/marketplace/checkout/request-client-payment.tsx
  client/a8c-for-agencies/sections/partner-directory/agency-details/index.tsx
  client/a8c-for-agencies/sections/referrals/primary/referrals-overview/index.tsx
  client/a8c-for-agencies/sections/team/primary/team-invite/index.tsx
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-horizon.json
  config/a8c-for-agencies-production.json
  config/a8c-for-agencies-stage.json
Labels: [Status] Needs Review, A8c Agencies

#97940 State: Remove unused stats state
  client/state/action-types.ts
  client/state/data-layer/wpcom/sites/stats/highlights/index.ts
  client/state/data-layer/wpcom/sites/stats/module-settings/index.ts
  client/state/stats/highlights/actions.ts
  client/state/stats/highlights/reducer.ts
  client/state/stats/highlights/schema.ts
  client/state/stats/highlights/selectors.ts
  client/state/stats/module-settings/actions.ts
  client/state/stats/module-settings/reducer.ts
  client/state/stats/module-settings/schema.ts
  client/state/stats/module-settings/selectors.ts
  client/state/stats/notices/actions.js
  client/state/stats/notices/reducer.js
  client/state/stats/notices/selectors.js
  client/state/stats/reducer.js
Labels: [Feature] Stats, [Status] Needs Review, [Type] Janitorial

#97971 Help Center: Update recommend resources loading placement
  packages/help-center/src/components/help-center-search-results.tsx
Labels: [Status] Needs Review, [Feature] Help Center

#97979 Help Center: Refactor Help Center styles to use blueberry blue for consistency
  packages/help-center/src/components/help-center-chat.scss
  packages/help-center/src/components/help-center-header.scss
  packages/help-center/src/components/help-center-search.scss
  packages/help-center/src/components/help-center-support-chat-message.scss
  packages/help-center/src/styles.scss
  packages/odie-client/src/components/message/style_redesign.scss
  packages/odie-client/src/style.scss
Labels: [Status] Needs Review, [Feature] Help Center

#97951 Stats: add location views query hook
  client/my-sites/stats/features/modules/stats-locations/stats-locations.tsx
  client/my-sites/stats/hooks/use-location-views-query.ts
Labels: [Feature] Stats, [Status] Needs Review

#97980 Increase delay of odie feedback animation
  packages/odie-client/src/components/message/style.scss
  packages/odie-client/src/components/message/style_redesign.scss
Labels: [Status] Needs Review, [Feature] Help Center

#97984 Adjust help center unread icon
  apps/help-center/help-icon.svg
  client/layout/masterbar/masterbar-help-center/help-center-icon.tsx
  packages/help-center/src/components/help-icon.tsx
Labels: [Status] Needs Review, [Feature] Help Center

#97944 Domains Management Revamp: Add email plans comparison subpage
  client/my-sites/domains/domain-management/subpage-wrapper/headers/compare-email-providers.tsx
  client/my-sites/domains/domain-management/subpage-wrapper/style.scss
  client/my-sites/domains/domain-management/subpage-wrapper/subpages.tsx
  client/my-sites/domains/index.js
  client/my-sites/domains/style.scss
  client/my-sites/email/email-providers-comparison/in-depth/index.tsx
  client/my-sites/email/paths.ts
  client/my-sites/email/test/paths.ts
Labels: [Status] Needs Review

#97877 Update WordPress.com Reader icons to use Core Icons
  apps/notifications/src/panel/templates/gridicons.tsx
  client/assets/images/icons/check-mark.svg
  client/assets/images/icons/plus.svg
  client/blocks/follow-button/style.scss
  client/blocks/reader-feed-header/style.scss
  client/blocks/reader-post-card/style.scss
  client/components/infinite-list/index.jsx
  client/landing/subscriptions/components/settings/comment-settings/comment-settings.tsx
  client/landing/subscriptions/components/settings/icons/feed-icon.tsx
  client/landing/subscriptions/components/settings/icons/index.ts
  client/landing/subscriptions/components/settings/icons/unsubscribe-icon.tsx
  client/landing/subscriptions/components/settings/site-settings/site-settings.tsx
  client/landing/subscriptions/components/settings/site-settings/styles.scss
  client/reader/components/icons/follow-feed-icon.jsx
  client/reader/components/icons/follow-feed-icon.tsx
  client/reader/components/icons/following-feed-icon.jsx
  client/reader/components/icons/following-feed-icon.tsx
  client/reader/discover/follow-button.jsx
  client/reader/follow-button/index.jsx
  client/reader/search-stream/search-follow-button.jsx
  client/reader/search-stream/style.scss
  client/reader/site-subscriptions-manager/style.scss
  client/reader/stream/reader-tag-sidebar/index.jsx
  client/reader/tag-stream/main.jsx
Labels: [Status] Needs Review

#97903 Site Migration: Support application password steps on `/setup/migration` flow
  client/landing/stepper/declarative-flow/migration/index.tsx
  client/landing/stepper/declarative-flow/migration/test/index.tsx
  client/landing/stepper/declarative-flow/test/site-migration-flow.tsx
Labels: [Status] Needs Review, [Feature] Site Migration, [Feature Group] Site Migration

#97716 Add currency to pricing page and checkout page view tracks
  client/my-sites/checkout/src/hooks/use-record-checkout-loaded.ts
  client/my-sites/plans/jetpack-plans/selector.tsx
Labels: [Status] Needs Review

#97948 Stats: add Regions/Cities tab
  client/my-sites/stats/features/modules/stats-locations/stats-locations.tsx
  client/state/stats/lists/utils.js
Labels: [Status] Needs Review

#97728 Reader profile - Add profile image
  client/reader/user-stream/index.tsx
  client/state/reader/action-types.js
  client/state/reader/reducer.js
  client/state/reader/users/actions.js
  client/state/reader/users/reducer.js
Labels: [Status] Needs Review

#97958 /start/onboarding always redirects to /setup/onboarding
  client/signup/controller.js
  client/signup/storageUtils.js
Labels: [Status] Needs Review, [Feature] Site Goals & Onboarding Paths

#98002 Reader profile: Add feature flag
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#97435 Login: add Akismet-branded login
  client/blocks/login/index.jsx
  client/blocks/login/login-form.scss
  packages/calypso-color-schemes/src/shared/color-schemes/_default.scss
Labels: [Status] Ready to Merge, [Feature] Akismet

#98004 Login: apply Akismet color to all buttons in login form
  client/blocks/login/login-form.scss
Labels: Login, [Feature] Akismet

#97989 Refactor sites dashboard banners manager
  client/sites/components/sites-dashboard-banners-manager.tsx
  client/sites/components/sites-dashboard-banners/use-a8c-for-agencies-sites-banner.tsx
  client/sites/components/sites-dashboard-banners/use-migration-pending-sites-banner.tsx
  client/sites/components/sites-dashboard-banners/use-restore-sites-reminder-banner.tsx
Labels: [Status] Needs Review

#97936 Goals first: Reset onboard store when entering the flow
  client/landing/stepper/declarative-flow/internals/steps-repository/create-site/index.tsx
  client/landing/stepper/declarative-flow/onboarding.ts
  client/landing/stepper/declarative-flow/site-setup-flow.ts
  client/signup/steps/domains/index.jsx
  client/signup/storageUtils.js
  packages/onboarding/src/hooks/use-persisted-state.ts
  packages/onboarding/src/index.ts
Labels: [Status] Needs Review

#97023 Make the tracks events for domain suggestion better
  client/components/domains/domain-registration-suggestion/index.jsx
  client/components/domains/map-domain-step/index.jsx
  client/components/domains/register-domain-step/analytics.js
  client/components/domains/register-domain-step/index.jsx
  client/components/domains/transfer-domain-step/index.jsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx
  client/my-sites/domains/domain-search/index.tsx
  client/signup/steps/domains/index.jsx
  client/state/domains/actions.js
Labels: [Status] Needs Review

#97698 adds a notice when the user has debt
  client/data/promote-post/use-promote-post-billing-summary-query.ts
  client/my-sites/promote-post-i2/components/campaign-item-details/index.tsx
  client/my-sites/promote-post-i2/components/campaign-item-details/style.scss
  client/my-sites/promote-post-i2/components/campaigns-table/style.scss
  client/my-sites/promote-post-i2/components/payment-links/index.tsx
  client/my-sites/promote-post-i2/components/payment-links/style.scss
  client/my-sites/promote-post-i2/main.tsx
Labels: [Status] Needs Review

#97988 Restore isolated `@automattic/components` Storybook
  package.json
  packages/components/README.md
  packages/components/package.json
  yarn.lock
Labels: [Status] Needs Review, Components, Storybook

#97906 Stats: Add "Zoom Out" actions to go back from date drill down
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-date-picker/date-label-drill/index.scss
  client/my-sites/stats/stats-date-picker/date-label-drill/index.tsx
  client/my-sites/stats/stats-date-picker/index.jsx
  client/my-sites/stats/stats-date-picker/with-is-drilling-down-hook.tsx
Labels: [Feature] Stats, [Status] Needs Review

#97900 Sensei: Cleanup old flow remnants
  client/assets/images/onboarding/sensei/progress-bg-bottom-left.png
  client/assets/images/onboarding/sensei/progress-bg-top-right.png
  client/landing/stepper/declarative-flow/internals/sensei-variables.scss
  client/landing/stepper/declarative-flow/internals/sensei.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/components/sensei-step-error/components.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/components/sensei-step-error/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/components/sensei-step-progress/components.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/components/sensei-step-progress/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/intro/styles.scss
  packages/onboarding/src/flow-progress/use-flow-progress.ts
  packages/onboarding/src/step-container/style.scss
Labels: [Status] Needs Review, [Type] Janitorial, Stepper, Sensei Onboarding Flow

#96750 Update 100-year domain copy
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-step-wrapper/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-step-wrapper/info-modal.tsx
Labels: [Status] Needs Review

#97956 Show domain in site context - layout, tab, main pages
  client/hosting/overview/index.tsx
  client/my-sites/domains/domain-management/controller.jsx
  client/my-sites/domains/domain-management/domain-overview-pane/constants.ts
  client/my-sites/domains/domain-management/domain-overview-pane/index.tsx
  client/my-sites/domains/domain-management/domain-overview-pane/style.scss
  client/my-sites/domains/domain-management/settings/style.scss
  client/my-sites/domains/paths.js
  client/my-sites/email/email-management/style.scss
  client/sites/components/sites-dashboard.tsx
  client/sites/components/style.scss
  client/sites/controller.tsx
  packages/domains-table/src/domains-table/domains-table-row.tsx
  packages/domains-table/src/utils/paths.ts
Labels: [Status] Needs Review

#97847 Domain management: Create add new mailbox subpage
  client/my-sites/domains/domain-management/subpage-wrapper/headers/add-mailbox-header.tsx
  client/my-sites/domains/domain-management/subpage-wrapper/index.tsx
  client/my-sites/domains/domain-management/subpage-wrapper/style.scss
  client/my-sites/domains/domain-management/subpage-wrapper/subpages.tsx
  client/my-sites/domains/index.js
  client/my-sites/email/add-mailboxes/index.tsx
  client/my-sites/email/controller.js
  client/my-sites/email/paths.ts
Labels: [Status] Needs Review

#98005 Login: ensure social login button is Akismet color where appropriate
  client/blocks/login/login-form.scss
Labels: Login, [Feature] Akismet

#97974 Help Center: Enhance back button accessibility
  packages/calypso-e2e/src/lib/components/help-center.ts
  packages/help-center/src/components/back-button.tsx
  packages/help-center/src/components/test/back-button.tsx
Labels: [Status] Needs Review, [Status] String Freeze, [Feature] Help Center

#97882 Update social-logos to the latest version
  client/components/social-logo/social-logos.d.ts
  client/package.json
  packages/wpcom-template-parts/package.json
  packages/wpcom-template-parts/src/universal-footer-navigation/index.tsx
  yarn.lock
Labels: [Status] Needs Review, [Type] Task

#98038 Reader: Refactor AuthorCompactProfileProps, EmptyContent, ReaderAuthorLink and ReaderFollowButton components
  client/blocks/author-compact-profile/index.jsx
  client/blocks/author-compact-profile/index.tsx
  client/blocks/reader-author-link/README.md
  client/blocks/reader-author-link/docs/example.jsx
  client/blocks/reader-author-link/docs/example.tsx
  client/blocks/reader-author-link/index.tsx
  client/blocks/reader-author-link/style.scss
  client/blocks/reader-author-link/test/index.tsx
  client/blocks/reader-avatar/index.tsx
  client/components/empty-content/index.jsx
  client/components/empty-content/index.tsx
  client/reader/follow-button/index.tsx
  client/reader/user-stream/views/lists.tsx
  client/reader/user-stream/views/posts.tsx
Labels: [Status] Needs Review

#98036 Reader: Add empty states of user profile screens
  client/components/empty-content/index.tsx
  client/components/empty-content/style.scss
  client/lib/user/user.d.ts
  client/reader/index.js
  client/reader/user-stream/controller.tsx
  client/reader/user-stream/index.tsx
  client/reader/user-stream/style.scss
  client/reader/user-stream/views/comments.tsx
  client/reader/user-stream/views/likes.tsx
  client/reader/user-stream/views/lists.tsx
  client/reader/user-stream/views/posts.tsx
  client/reader/user-stream/views/reposts.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#98065 Remove event calypso_signup_unified_design_picker_view
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
Labels: [Status] Needs Review

#98067 Fire calypso_signup_actions_submit_step event for Goals step skip button
  client/landing/stepper/declarative-flow/internals/steps-repository/goals/index.tsx
Labels: [Status] Needs Review

#98069 Tracks: Improve calypso_signup_skip_step in the Design Picker
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
Labels: [Status] Needs Review

#97650 Cancellation Form: Minor UI updates
  client/components/marketing-survey/cancel-purchase-form/style.scss
  packages/calypso-e2e/src/lib/flows/cancel-purchase-flow.ts
Labels: [Status] Needs Review

#98033 Localize the login link in the user step
  client/landing/stepper/declarative-flow/internals/steps-repository/__user/index.tsx
Labels: [Status] Needs Review, Groundskeeping

#97657 Hosting Panel: Fix backups link
  client/sites/overview/components/site-backup-card/index.js
Labels: [Status] Ready to Merge

#97987 Hosting dashboard: More refinements for logs header
  client/sites/tools/logs/components/site-logs-header/style.scss
  client/sites/tools/logs/components/site-logs-toolbar/index.tsx
  client/sites/tools/logs/components/site-logs-toolbar/style.scss
Labels: [Status] Needs Review

#98055 Stats: add Geochart regions/cities
  client/my-sites/stats/features/modules/stats-locations/stats-locations.tsx
  client/my-sites/stats/geochart/index.jsx
Labels: [Feature] Stats, [Status] Needs Review

#98046 Reader: Check for missing pageHandle in lastPage stream reducer
  client/state/reader/streams/reducer.js
  client/state/reader/streams/test/reducer.js
Labels: [Status] Needs Review

#98071 Improve VSCode performance by removing jsconfig.json
  jsconfig.json
Labels: [Status] Needs Review

#98097 Goals First: Add prop to `caypso_signup_start` event
  client/landing/stepper/declarative-flow/onboarding.ts
Labels: Reviewer Can Merge

#98098 Uses a consistent string in all cases.
  client/my-sites/checkout/src/components/wp-checkout-order-summary.tsx
Labels: [Status] Needs Review

#98084 Prevent infinite redirect after processing site on onboarding flow
  client/landing/stepper/hooks/use-record-signup-complete.ts
Labels: [Status] Needs Review

#97892 Site Migration: Use the new experiment identifier
  client/sites/hooks/use-sites-dashboard-import-site-url.ts
Labels: [Status] Needs Review, [Feature] Site Migration, [Feature Group] Site Migration

#97855 A4A: Use MigrationOfferV3 component on overview page
  client/a8c-for-agencies/sections/overview/body/hosting/index.tsx
  client/a8c-for-agencies/sections/overview/body/hosting/styles.scss
Labels: [Status] Needs Review

#98054 Stats: Fix unhandled exception on Post Summary page
  client/my-sites/stats/stats-post-summary/index.jsx
Labels: [Feature] Stats, [Status] Needs Review

#98120 Login: style button for Akismet-branded login in 'continue as user' scenario
  client/blocks/login/login-form.scss
Labels: Login, [Feature] Akismet

#98104 Goals First: Record selected goals for every step in the calypso_signup_step_start event
  client/landing/stepper/declarative-flow/onboarding.ts
Labels: [Status] Needs Review, Reviewer Can Merge

#98118 Fix colours on email create account screen
  client/landing/stepper/declarative-flow/internals/steps-repository/__user/style.scss
Labels: [Status] Needs Review

#98125 Tracks: Remove event prop assembler_source
  client/landing/stepper/declarative-flow/internals/analytics/record-design.ts
  client/landing/stepper/declarative-flow/internals/components/step-route/hooks/use-step-route-tracking/index.tsx
  client/landing/stepper/declarative-flow/internals/components/step-route/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
Labels: [Status] Needs Review, Lego Maintenance

#98127 Clean-up: Remove isAssembler util function
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  packages/design-picker/src/index.ts
  packages/design-picker/src/utils/designs.ts
Labels: [Status] Needs Review

#98129 Fix typo
  packages/data-stores/src/queries/use-launchpad.ts
Labels: [Status] Needs Review

#98070 Sites Dashboard: Update border styles to use neutral color for consistency
  client/blocks/plugin-scheduled-updates-common/styles.scss
  client/blocks/plugins-scheduled-updates-multisite/styles.scss
  client/components/dataviews/style.scss
  client/my-sites/domains/domain-management/list/bulk-all-domains.tsx
  client/my-sites/plugins/plugins-list/style.scss
  client/my-sites/plugins/plugins-navigation-header/style.scss
  client/my-sites/plugins/style.scss
  client/my-sites/themes/theme-showcase.scss
Labels: [Status] Needs Review, Lego Maintenance

#98013 Help Center: Remove AI response when creating Support forum topic
  packages/help-center/src/components/help-center-contact-form.scss
  packages/help-center/src/components/help-center-contact-form.tsx
  packages/help-center/src/components/ticket-success-screen.scss
Labels: [Status] Needs Review

#98135 Add tracks events to design picker on filter select and deselect
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
Labels: [Status] Needs Review

#98133 Manage Plugins: Fix layout shift when opening a dropdown
  client/assets/stylesheets/shared/_reset.scss
Labels: [Status] Needs Review

#98087 Pattern Library: Visual tweaks for resize handle
  client/my-sites/patterns/components/pattern-preview/style.scss
Labels: [Status] Needs Review

#97996 Update: heading tags on plugins/themes pages
  client/components/navigation-header/index.tsx
  client/my-sites/plugins/plugins-browser-list/index.jsx
  client/my-sites/plugins/plugins-navigation-header/index.jsx
  client/my-sites/plugins/plugins-results-header/index.tsx
Labels: [Status] Needs Review

#98139 A4A: Remove commissions payment delayed banner
  client/a8c-for-agencies/components/a4a-payment-delayed-notice/index.tsx
  client/a8c-for-agencies/components/a4a-payment-delayed-notice/style.scss
  client/a8c-for-agencies/sections/migrations/primary/migrations-commissions/index.tsx
  client/a8c-for-agencies/sections/referrals/primary/referrals-overview/index.tsx
Labels: [Status] Needs Review

#98143 Revert "Site Migration: Use the new experiment identifier"
  client/sites/hooks/use-sites-dashboard-import-site-url.ts
Labels: [Status] Needs Review

#97572 Site Migration: Add A/B test check before showing certain UI/UX updates
  client/landing/stepper/declarative-flow/internals/hooks/use-migration-experiment/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-import-or-migrate/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-upgrade-plan/index.tsx
Labels: [Status] Needs Review, [Feature] Site Migration

#98117 Fix layout bugs for 100 year plan
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-diy-or-difm/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-diy-or-difm/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-step-wrapper/info-modal.tsx
Labels: [Status] Needs Review

#98015 i18n: Update theme-tier translations to use fixMe
  client/components/theme-tier/constants.js
Labels: [Status] Needs Review, i18n

#97557 i18n: Fix translate calls in hosting overview components
  client/sites/overview/components/hosting-overview.tsx
  client/sites/overview/components/migration-overview/components/cards.tsx
  client/sites/overview/components/migration-overview/components/migration-pending/index.tsx
  client/sites/overview/components/migration-overview/components/migration-started-diy.tsx
Labels: [Status] Needs Review, i18n

#98096 i18n: Remove redundant `hasTranslation` checks (across the codebase)
  client/components/domains/use-my-domain/domain-input.jsx
  client/components/jetpack/card/jetpack-product-card/display-price/time-frame.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-intro/intro.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/error-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/components/access-method-picker.tsx
  client/lib/domains/resolve-domain-status.tsx
  client/login/magic-login/request-login-email-form.jsx
  client/me/account/toggle-sites-as-landing-page.tsx
  client/me/developer/dev-survey-notice.tsx
  client/me/notification-settings/reader-subscriptions/index.jsx
  client/me/purchases/confirm-cancel-domain/index.jsx
  client/my-sites/customer-home/cards/actions/quick-links/index.jsx
  client/my-sites/customer-home/cards/tasks/domain-upsell/index.jsx
  client/my-sites/domains/domain-management/list/empty-domains-list-card.jsx
  client/my-sites/domains/domain-management/settings/cards/transferred-domain-details.tsx
  client/my-sites/domains/domain-management/settings/index.tsx
  client/my-sites/patterns/components/get-started/index.tsx
  client/my-sites/patterns/components/pattern-library/index.tsx
  client/my-sites/patterns/components/pattern-preview/index.tsx
  client/my-sites/plans/ecommerce-trial/entrepreneur-plan/entrepreneur-plan.tsx
  client/my-sites/plans/ecommerce-trial/wooexpress-plans/index.tsx
  client/my-sites/plans/main.jsx
  client/my-sites/plugins/plugins-browser/index.jsx
  client/my-sites/site-settings/settings-newsletter/newsletter-categories-section/newsletter-categories-toggle.tsx
  client/my-sites/subscribers/components/grow-your-audience/grow-your-audience.tsx
  client/my-sites/subscribers/main.tsx
  client/signup/config/steps-pure.js
  client/signup/steps/design-picker/design-picker.tsx
  client/signup/steps/site-or-domain/index.jsx
  client/sites-dashboard/components/sites-site-launch-nag.tsx
  client/sites/settings/administration/tools/delete-site/index.jsx
  client/sites/tools/deployments/components/deployments-survey/index.tsx
  client/sites/tools/staging-site/components/staging-site-card/card-content/staging-sync-card.tsx
  packages/calypso-products/src/features-list.tsx
  packages/calypso-products/src/plans-list.tsx
  packages/domain-picker/src/components/domain-suggestion-item/suggestion-item.tsx
  packages/help-center/src/components/help-center-contact-page.tsx
  packages/help-center/src/components/help-center-contact-support-option.tsx
  packages/help-center/src/components/help-center-gpt.tsx
  packages/plans-grid/src/plans-interval-toggle/index.tsx
  packages/plans-grid/src/plans-table/plan-item.tsx
Labels: [Status] Needs Review, i18n, [Status] String Freeze

#98072 i18n: Remove fallback translations from landing/subscriptions hook
  client/landing/subscriptions/hooks/use-subheader-text.tsx
Labels: [Status] Needs Review, i18n

#97659 Improve `Points to WPCOM` cta beahviour
  client/components/inline-support-link/context-links.js
  client/my-sites/domains/domain-management/dns/dns-records.jsx
  client/my-sites/domains/domain-management/dns/style.scss
  packages/domains-table/src/domains-table/__tests__/domains-table-row.tsx
  packages/domains-table/src/domains-table/domains-table-row-actions.tsx
  packages/domains-table/src/utils/paths.ts
  packages/domains-table/src/utils/resolve-domain-status.tsx
  packages/urls/src/index.ts
Labels: [Status] Needs Review

#97699 Goals first: Use actual experiment checks within useGoalsFirstExperiment
  client/landing/stepper/declarative-flow/helpers/use-goals-first-experiment.ts
  client/landing/stepper/declarative-flow/internals/components/boot/index.tsx
  config/development.json
  config/stage.json
  config/wpcalypso.json
  packages/calypso-e2e/src/lib/pages/signup/signup-pick-plan-page.ts
  packages/calypso-e2e/src/lib/pages/site-settings-page.ts
  test/e2e/specs/onboarding/lifecycle__signup-onboarding-launch-cancel.ts
  test/e2e/specs/onboarding/onboarding__write.ts
Labels: [Status] Needs Review

#98083 Stepper: Fix navigating to a gated step
  client/landing/stepper/declarative-flow/internals/components/step-route/index.tsx
  client/landing/stepper/declarative-flow/internals/components/survery-manager/index.tsx
  client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx
  client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/test/index.tsx
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/hooks/use-login-url-for-flow.ts
Labels: [Status] Needs Review

#98085 Improve consistency of the login form
  client/blocks/login/login-form.jsx
Labels: [Status] Needs Review

#98178 Fix hundred year domain spacing on mobile
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-step-wrapper/index.tsx
Labels: [Status] Needs Review

#98182 Goals First: Prevent `calypso_signup_start` from firing multiple times
  client/landing/stepper/declarative-flow/onboarding.ts
Labels: [Status] Needs Review

#97937 Update hideTaxString logic to handle cases where purchase price is zero
  client/me/purchases/manage-purchase/purchase-meta.tsx
Labels: OSS Citizen

#97950 Plan Downgrade: Allow plan downgrades to monthly when purchased with credits
  client/components/marketing-survey/cancel-purchase-form/get-upsell-type.ts
  client/components/marketing-survey/cancel-purchase-form/step-components/upsell-step.tsx
Labels: [Status] Needs Review

#98144 Stats: Bring back Subscribers tab for self-hosted sites
  client/blocks/stats-navigation/index.js
Labels: [Type] Bug, [Feature] Stats, [Status] Needs Review

#98183 My Home doesn't navigate to launchpad if that's where it came from
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/index.tsx
  client/my-sites/customer-home/controller.jsx
Labels: [Status] Needs Review, Reviewer Can Merge

#98074 Design Picker: Remove Trending for your goals section
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
  packages/data-stores/src/starter-designs-queries/types.ts
  packages/data-stores/src/starter-designs-queries/use-starter-designs-query.ts
  packages/design-picker/src/components/unified-design-picker.tsx
  packages/design-picker/src/hooks/use-filtered-designs.ts
Labels: [Status] Needs Review

#97981 A4A: Remove unused marketplace codes.
  client/a8c-for-agencies/components/slider/style.scss
  client/a8c-for-agencies/sections/marketplace/checkout/pricing-summary.tsx
  client/a8c-for-agencies/sections/marketplace/controller.tsx
  client/a8c-for-agencies/sections/marketplace/hooks/use-total-invoice-value.ts
  client/a8c-for-agencies/sections/marketplace/hooks/use-wpcom-plan-description.ts
  client/a8c-for-agencies/sections/marketplace/hosting-overview-v3/hosting-content/premier-agency-hosting/pressable-plan-section/regular-plan-card-content.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview-v3/hosting-content/standard-agency-hosting/wpcom-plan-section/wpcom-plan-selector.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview-v3/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hooks/use-wpcom-discount-tiers.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-card/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-card/style.scss
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-list/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-list/style.scss
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/standard-agency-hosting/wpcom-plan-selector/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/standard-agency-hosting/wpcom-plan-selector/slider.tsx
  client/a8c-for-agencies/sections/marketplace/lib/wpcom-bulk-options.ts
  client/a8c-for-agencies/sections/marketplace/lib/wpcom-bulk-values-utils.ts
  client/a8c-for-agencies/sections/marketplace/pressable-overview/footer/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/details.tsx
  client/a8c-for-agencies/sections/marketplace/pressable-overview/style.scss
  client/a8c-for-agencies/sections/marketplace/products-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/shopping-cart/shopping-cart-menu/index.tsx
  client/a8c-for-agencies/sections/marketplace/shopping-cart/shopping-cart-menu/item.tsx
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/bulk-selection.tsx
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/index.tsx
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/style.scss
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/wpcom-card/index.tsx
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/wpcom-card/style.scss
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/wpcom-slider/index.tsx
  client/a8c-for-agencies/sections/marketplace/wpcom-overview/wpcom-slider/style.scss
Labels: [Status] Needs Review, A8c Agencies

#98132 Server settings: prevent loading SFTP settings for sites that don't support them
  client/sites/tools/sftp-ssh/sftp-form.tsx
Labels: [Type] Bug, [Status] Needs Review, [Feature] SFTP & SSH Access

#98200 Clean-up: Remove ai-assembler flow
  client/landing/stepper/declarative-flow/ai-assembler.ts
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/create-site/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/launchpad-site-preview.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/domain/test/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/new-or-existing-site/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/new-or-existing-site/styles.scss
  client/landing/stepper/declarative-flow/registered-flows.ts
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
  packages/onboarding/src/utils/flows.ts
Labels: [Status] Needs Review, Lego Maintenance

#98206 Checkout: explain better what happens when plan renewal gets removed.
  packages/wpcom-checkout/src/checkout-line-items.tsx
Labels: [Status] Needs Review

#98091 Vdimitrakis/2960 evergreen campaign info fixes
  client/my-sites/promote-post-i2/components/campaign-item-details/index.tsx
  client/my-sites/promote-post-i2/utils/index.ts
Labels: [Status] Needs Review

#98113 Domains Management: Add breadcrumb to the Domain page on site context
  client/blocks/site-favicon/index.tsx
  client/components/breadcrumb/index.tsx
  client/my-sites/domains/domain-management/domain-overview-pane/index.tsx
  client/my-sites/domains/domain-management/domain-overview-pane/style.scss
Labels: [Status] Needs Review

#97897 Domain Picker: Fix `useDomainSuggestions` warning
  packages/domain-picker/src/hooks/use-domain-suggestions.ts
Labels: [Type] Enhancement, [Status] Needs Review, [Feature] Domain Purchases

#98093 Reader: fix scroll depth tracking
  client/blocks/reader-full-post/index.jsx
  client/blocks/reader-full-post/scroll-tracker.ts
  client/blocks/reader-full-post/test/scroll-tracker.ts
  client/reader/recent/style.scss
Labels: [Status] Needs Review

#98220 Points to WPCOM CTA: Fix typo
  client/my-sites/domains/domain-management/dns/dns-records.jsx
Labels: [Status] Needs Review, [Status] String Freeze

#98158 Stats: add Summary 'Locations' path
  client/my-sites/stats/controller.jsx
  client/my-sites/stats/index.js
  client/my-sites/stats/site.jsx
  client/my-sites/stats/summary/index.jsx
  client/my-sites/stats/test/index.js
Labels: [Feature] Stats, [Status] Needs Review

#97674 Reader: enable pagination controls for Recent Feed
  client/reader/recent/index.tsx
  client/reader/recent/style.scss
  client/state/data-layer/wpcom/read/streams/index.js
  client/state/reader/streams/actions.js
  client/state/reader/streams/reducer.js
Labels: [Status] Needs Review

#98045 Reader: Pass header content to Stream components
  client/reader/user-stream/components/user-profile-header/index.tsx
  client/reader/user-stream/components/user-profile-header/style.scss
  client/reader/user-stream/index.tsx
  client/reader/user-stream/style.scss
  client/reader/user-stream/views/lists.tsx
  client/reader/user-stream/views/posts.tsx
Labels: [Status] Needs Review

#98221 A4A: Remove "early access" tier banner
  client/a8c-for-agencies/sections/agency-tier/early-access-banner/index.tsx
  client/a8c-for-agencies/sections/agency-tier/primary/agency-tier-overview/index.tsx
Labels: [Status] Needs Review

#98228 Builk Plugin Management: Use the same URL for Manage Plugins to avoid recreating the Dashboard
  client/my-sites/plugins/sidebar/index.tsx
Labels: [Status] Needs Review

#98229 Using page calypso router to navigate to /home to avoid flickering
  client/my-sites/site-settings/wrap-settings-form.jsx
Labels: [Status] Needs Review

#98219 Stepper: Support loading in `useTracksEventProps`
  client/landing/stepper/declarative-flow/connect-domain.ts
  client/landing/stepper/declarative-flow/internals/components/step-route/hooks/use-step-route-tracking/index.tsx
  client/landing/stepper/declarative-flow/internals/hooks/use-sign-up-start-tracking/index.tsx
  client/landing/stepper/declarative-flow/internals/hooks/use-sign-up-start-tracking/test/index.tsx
  client/landing/stepper/declarative-flow/internals/hooks/use-step-navigation-with-tracking/index.ts
  client/landing/stepper/declarative-flow/internals/types.ts
  client/landing/stepper/declarative-flow/onboarding.ts
  client/landing/stepper/declarative-flow/tailored-ecommerce-flow.ts
Labels: [Status] Needs Review

#98234 Reader: Auto-launch onboarding on first visit
  client/reader/onboarding/constants.tsx
  client/reader/onboarding/index.tsx
Labels: [Status] Needs Review

#98235 Stepper: ignore ref changes when customizing calypso_signup_start
  client/landing/stepper/declarative-flow/internals/hooks/use-sign-up-start-tracking/index.tsx
  client/landing/stepper/declarative-flow/internals/hooks/use-sign-up-start-tracking/test/index.tsx
Labels: [Status] Needs Review, Reviewer Can Merge

#97921 Enable me/account-restore on production
  config/production.json
Labels: [Status] Needs Review, DO NOT MERGE

#98218 Sites Dashboard: Implement survey
  client/components/survey-modal/index.jsx
  client/components/survey-modal/style.scss
  client/sites/components/sites-dashboard-survey/assets/images/survey-sites-dashboard.svg
  client/sites/components/sites-dashboard-survey/index.tsx
  client/sites/components/sites-dashboard.tsx
  config/development.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#98209 Put all the products into the cart on the plans step.
  client/landing/stepper/declarative-flow/onboarding.ts
Labels: [Status] Needs Review, Storage Addon

#98123 Add spacing to unglue buttons when no domain exist.
  client/my-sites/email/email-management/style.scss
Labels: [Status] Needs Review

#98232 Help Center: Remove unneeded Storybook config
  packages/help-center/.storybook/main.js
  packages/help-center/.storybook/preview.js
  packages/help-center/.storybook/styles.scss
  packages/help-center/package.json
  yarn.lock
Labels: [Status] Needs Review, Storybook

#98160 Stats: Improve shortcuts for date range picker
  client/components/date-range/use-shortcuts.ts
  client/components/stats-date-control/index.tsx
  client/my-sites/stats/constants.ts
  client/my-sites/stats/hooks/use-should-gate-stats.ts
Labels: [Feature] Stats, [Status] Needs Review

#98231 Storybook: Fix CSF parsing error
  .storybook/main.js
  packages/calypso-storybook/README.md
  packages/components/.storybook/main.js
  packages/composite-checkout/.storybook/main.js
  packages/plans-grid-next/.storybook/main.js
  packages/privacy-toolset/.storybook/main.js
  packages/search/.storybook/main.js
Labels: [Status] Needs Review, Storybook

#97982 A4A > Migrations: Remove feature flag logic
  client/a8c-for-agencies/components/sidebar-menu/hooks/use-main-menu-items.tsx
  client/a8c-for-agencies/sections/migrations/controller.tsx
  client/a8c-for-agencies/sections/migrations/index.tsx
  client/a8c-for-agencies/sections/migrations/primary/migrations-overview-v2/index.tsx
  client/a8c-for-agencies/sections/migrations/primary/migrations-overview-v2/sections/migrations-faqs/index.tsx
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-horizon.json
  config/a8c-for-agencies-production.json
  config/a8c-for-agencies-stage.json
Labels: [Status] Needs Review, A8c Agencies

#98252 Fix migration flow from white screen
  client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx
Labels: [Status] Needs Review

#98152 Fix email upsell page styles in site context
  client/my-sites/domains/domain-management/domain-overview-pane/style.scss
  client/my-sites/email/email-management/email-home.tsx
  client/my-sites/email/email-management/home/email-plan-mailboxes-list.tsx
  client/sites/components/dotcom-style.scss
Labels: [Status] Needs Review

#98215 Pattern Library: Add resize handle tooltip
  client/my-sites/patterns/components/pattern-preview/index.tsx
  client/my-sites/patterns/components/pattern-preview/style.scss
Labels: [Status] Needs Review

#98086 A4A: Add feature flag for Products overview v2 page.
  client/a8c-for-agencies/sections/marketplace/controller.tsx
  client/a8c-for-agencies/sections/marketplace/index.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview-v2/index.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview-v2/style.scss
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-horizon.json
  config/a8c-for-agencies-production.json
  config/a8c-for-agencies-stage.json
Labels: [Status] Needs Review, A8c Agencies

#98153 A4A: Implement the initial product category menu using a standardized side-scrolling behavior.
  client/a8c-for-agencies/components/a4a-carousel/index.tsx
  client/a8c-for-agencies/components/a4a-carousel/style.scss
  client/a8c-for-agencies/sections/marketplace/products-overview-v2/hooks/use-compact-on-scroll.ts
  client/a8c-for-agencies/sections/marketplace/products-overview-v2/index.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview-v2/product-category-menu/index.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview-v2/product-category-menu/style.scss
  client/a8c-for-agencies/sections/marketplace/products-overview-v2/style.scss
Labels: [Status] Needs Review, A8c Agencies

#98095 Match style of site overview in site context
  client/layout/hosting-dashboard/item-view/index.tsx
  client/layout/hosting-dashboard/item-view/types.ts
  client/my-sites/domains/domain-management/domain-overview-pane/index.tsx
  client/my-sites/domains/domain-management/domain-overview-pane/style.scss
  client/my-sites/domains/style.scss
  client/my-sites/email/email-management/email-home.tsx
  client/my-sites/email/email-management/home/email-plan-mailboxes-list.tsx
  client/sites/components/dotcom-style.scss
  client/sites/overview/components/active-domains-card.tsx
  packages/domains-table/src/domains-table/domains-table-row.tsx
  packages/domains-table/src/domains-table/domains-table.tsx
  packages/domains-table/src/utils/paths.ts
Labels: [Status] Needs Review

#98264 Remove always-enabled subscriber-csv-upload feature flag
  client/landing/stepper/declarative-flow/internals/steps-repository/subscribers/index.tsx
  client/my-sites/people/followers-list/followers.jsx
  client/my-sites/subscribers/components/add-subscribers-modal/add-subscribers-modal.tsx
  config/development.json
  config/horizon.json
  config/jetpack-cloud-development.json
  config/jetpack-cloud-horizon.json
  config/jetpack-cloud-production.json
  config/jetpack-cloud-stage.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Type] Janitorial

#98159 /me/get-apps new design and add studio
  client/assets/images/icons/apple-logo.svg
  client/assets/images/icons/desktop-app-logo.svg
  client/assets/images/icons/jetpack-app-logo.svg
  client/assets/images/icons/linux-logo.svg
  client/assets/images/icons/studio-app-logo.svg
  client/assets/images/icons/windows-logo.svg
  client/blocks/app-promo/qr-code.tsx
  client/blocks/get-apps/apps-badge.tsx
  client/blocks/get-apps/apps-card.tsx
  client/blocks/get-apps/apps-config.ts
  client/blocks/get-apps/desktop-download-card.jsx
  client/blocks/get-apps/desktop-download-card.tsx
  client/blocks/get-apps/desktop-download-options.tsx
  client/blocks/get-apps/index.jsx
  client/blocks/get-apps/index.tsx
  client/blocks/get-apps/mobile-download-card.jsx
  client/blocks/get-apps/mobile-download-card.tsx
  client/blocks/get-apps/style.scss
  client/components/split-button/index.jsx
Labels: [Status] Needs Review

#98195 Plans Spotlight: Align action button with a flexbox
  packages/plans-grid-next/src/components/features-grid/spotlight-plan.tsx
  packages/plans-grid-next/src/components/features-grid/style.scss
Labels: [Status] Needs Review

#98011 A4A > Checkout: Show Pressable limit warning
  client/a8c-for-agencies/sections/marketplace/checkout/index.tsx
  client/a8c-for-agencies/sections/marketplace/checkout/product-info.tsx
  client/a8c-for-agencies/sections/marketplace/checkout/style.scss
Labels: [Status] Needs Review, A8c Agencies
