Repository Automattic/wp-calypso, pull requests merged in 2025-02, with the labels that each got.

#99170 Stats: Memoize moment site timezone selector
  client/my-sites/stats/hooks/use-moment-site-zone.ts
Labels: [Type] Enhancement, [Feature] Stats, [Status] Needs Review, State, [Type] Performance

#99171 Stats: Memoize gated intervals selector
  client/my-sites/stats/hooks/use-intervals.tsx
Labels: [Type] Enhancement, [Feature] Stats, [Status] Needs Review, State, [Type] Performance

#99133 Update experiment slug for goals-first experience
  client/landing/stepper/declarative-flow/helpers/use-goals-first-experiment.ts
  config/development.json
Labels: [Status] Needs Review

#99174 Move user to /plans page when exiting and clearing cart from checkout
  client/landing/stepper/declarative-flow/onboarding.ts
Labels: [Status] Needs Review

#99140 Stats: navigate by full periods
  client/my-sites/stats/hooks/use-moment-site-zone.ts
  client/my-sites/stats/stats-period-navigation/index.jsx
Labels: [Feature] Stats, [Status] Needs Review

#99096 Add experiment assignment to Big Sky before plans
  client/landing/stepper/declarative-flow/helpers/use-bigsky-before-plans-experiment.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/__user/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/design-choices/index.tsx
  client/landing/stepper/declarative-flow/onboarding.ts
  client/landing/stepper/declarative-flow/test/site-setup-flow.tsx
  client/landing/stepper/hooks/use-is-site-big-sky-eligible.ts
  config/development.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#99127 Big Sky GF: Add AI Copy to big sky plans step
  client/landing/stepper/declarative-flow/helpers/use-bigsky-before-plans-experiment.ts
  client/landing/stepper/declarative-flow/onboarding.ts
  client/my-sites/checkout/checkout-main-wrapper.tsx
  packages/calypso-products/src/constants/feature-group.ts
  packages/calypso-products/src/constants/features.ts
  packages/calypso-products/src/feature-group-plan-map.ts
  packages/calypso-products/src/features-list.tsx
  packages/calypso-products/src/is-big-sky-onboarding.ts
  packages/calypso-products/src/plans-list.tsx
  packages/calypso-products/src/types.ts
Labels: [Status] Needs Review, [Status] String Freeze, Reviewer Can Merge

#98519 Redirect users to /domains/add when cart is cleared in EmailUpsell flow.
  client/layout/masterbar/checkout.tsx
  client/my-sites/checkout/src/hooks/use-remove-from-cart-and-redirect.ts
  client/my-sites/checkout/src/lib/leave-checkout.ts
  client/my-sites/checkout/src/test/leave-checkout.ts
Labels: [Status] Needs Review

#98867 Update the shopping cart skeleton.
  client/my-sites/checkout/src/components/checkout-main-content.tsx
  packages/composite-checkout/src/components/loading-content.tsx
Labels: [Status] Needs Review, [Status] Needs Design Review, [Status] Design Input Requested

#99196 Removes the Design with AI button from the design picker
  packages/design-picker/src/components/unified-design-picker.tsx
Labels: [Status] Needs Review

#96100 Assets: Fix the order of the chunk files (2nd try)
  bin/loader-stats.js
  build-tools/webpack/assets-writer-plugin.js
  client/server/middleware/assets.js
  client/server/pages/index.js
  client/server/pages/test/index.js
  package.json
  yarn.lock
Labels: [Status] Needs Review

#98543 Remove the window.AppBoot function
  client/boot/app.js
  client/document/index.jsx
  client/landing/login/index.js
  client/landing/stepper/index.tsx
  client/landing/subscriptions/index.tsx
  client/server/README.md
  client/server/pages/index.js
  client/types.ts
Labels: [Status] Needs Review, Build, [Type] Janitorial

#99113 100 year domain - use "Paid until" label in domains list
  packages/data-stores/src/queries/use-all-domains-query.ts
  packages/domains-table/src/domains-table/domains-table-expires-renews-cell.tsx
  packages/domains-table/src/test-utils.tsx
Labels: [Status] Needs Review

#98917 Reader: remove some always-true feature flags
  client/reader/discover/discover-navigation.js
  client/reader/following/main.tsx
  client/reader/list-stream/index.jsx
  client/reader/list/index.js
  client/reader/sidebar/index.jsx
  client/reader/sidebar/reader-sidebar-lists/list-item-create-link.jsx
  client/reader/sidebar/reader-sidebar-lists/list.jsx
  client/reader/tag-stream/index.js
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Feature] Reader, [Type] Janitorial

#99123 Reader: fix broken back navigation when mounting reader onboarding
  client/reader/onboarding/index.tsx
Labels: [Status] Needs Review

#98611 Staging sites: Update translations of error messages
  client/sites/tools/staging-site/components/staging-site-card/card-content/staging-sync-card.tsx
Labels: [Status] Needs Review, [Status] String Freeze

#99175 A4A: Add upgrade link to WordPress.com/Pressable licenses
  client/a8c-for-agencies/sections/purchases/licenses/license-details/actions.tsx
  client/a8c-for-agencies/sections/purchases/licenses/license-details/index.tsx
  client/a8c-for-agencies/sections/purchases/licenses/license-preview/index.tsx
  client/a8c-for-agencies/sections/purchases/licenses/license-preview/license-actions.tsx
  client/a8c-for-agencies/sections/purchases/licenses/license-preview/use-license-actions.ts
Labels: [Status] Needs Review

#99206 Remove custom style from highlight selection
  client/assets/stylesheets/_main.scss
Labels: [Status] Needs Review

#99209 Add dark mode support to VBE
  client/my-sites/comments/comment/comment-block-editor/index.tsx
  packages/verbum-block-editor/src/editor/editor-types.ts
  packages/verbum-block-editor/src/editor/index.tsx
  packages/verbum-block-editor/src/editor/inline-iframe-style-dark-mode.scss
  packages/verbum-block-editor/src/text-area-injector.tsx
  packages/verbum-block-editor/src/types.d.ts
Labels: [Status] Needs Review

#99181 Reader: clean up scrolling on disabled onboarding modal
  client/reader/onboarding/subscribe-modal/index.tsx
  client/reader/onboarding/subscribe-modal/style.scss
Labels: [Status] Needs Review

#99179 Close the dropdown when the user clicks outside of it
  client/my-sites/checkout/src/components/wp-order-review-line-items.tsx
Labels: [Type] Enhancement, [Status] Needs Review

#99064 Add link to reader profile on /me page
  client/me/profile/index.jsx
Labels: [Status] Needs Review

#99049 Fix link button color in domain forward accordion
  client/my-sites/domains/domain-management/components/domain/domain-info-card/disconnect/index.tsx
  client/my-sites/domains/domain-management/domain-overview-pane/style.scss
  client/my-sites/domains/domain-management/settings/cards/domain-forwarding-card.tsx
Labels: [Status] Needs Review

#98991 i18n: Fix missing/wrong number translations on subscribers page
  client/my-sites/stats/features/modules/stats-emails/stats-emails.tsx
  client/my-sites/stats/features/modules/stats-emails/tooltips.tsx
  client/my-sites/stats/stats-email-summary/index.jsx
Labels: [Status] Needs Review, i18n, [Status] String Freeze, i18n: number-format

#99219 Persisting subdomain during the free site setup Big Sky onboarding flow
  client/landing/stepper/declarative-flow/internals/steps-repository/unified-plans/index.tsx
Labels: [Status] Needs Review

#99233 Tracks Event: Add `is_in_signup` property to `calypso_plans_plan_type_selector_option_change`
  packages/plans-grid-next/src/components/plan-type-selector/components/interval-type-dropdown.tsx
Labels: [Status] Needs Review

#99235 Updates to design choice step copy
  client/landing/stepper/declarative-flow/internals/steps-repository/design-choices/goals-first-design-choice.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/design-choices/index.tsx
Labels: [Status] Needs Review

#99230 Fix design choice screen missing W logo
  client/landing/stepper/declarative-flow/internals/global.scss
Labels: [Status] Needs Review, Reviewer Can Merge

#99246 Fix AI copy not being displayed when plans page is refreshed
  client/landing/stepper/declarative-flow/onboarding.ts
Labels: [Status] Needs Review, Reviewer Can Merge

#98968 Deploy Woo rebrand on all environments
  client/assets/images/icons/woocommerce-logo.svg
  client/components/jetpack-header/index.jsx
  client/components/jetpack-header/woocommerce.jsx
  client/layout/index.jsx
  client/layout/logged-out.jsx
  client/layout/masterbar/woo-core-profiler.tsx
  client/layout/masterbar/woo.jsx
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#99250 Domain-To-Plan Credit: Add feature flag
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
Labels: [Status] Needs Review

#99150 A4A: update Woo logo
  client/a8c-for-agencies/sections/marketplace/products-overview-v2/product-listing/index.tsx
  client/a8c-for-agencies/sections/marketplace/products-overview/product-filter/hooks/use-product-filter-options.tsx
  client/a8c-for-agencies/sections/overview/body/products/index.tsx
  client/a8c-for-agencies/sections/partner-directory/lib/get-brand-meta.tsx
  client/a8c-for-agencies/sections/referrals/primary/commission-overview/index.tsx
  client/a8c-for-agencies/sections/referrals/primary/referrals-overview/layout-body-content.tsx
  client/assets/images/woocommerce/product-icon.svg
  client/my-sites/plans/jetpack-plans/product-store/utils/get-product-icon.ts
Labels: [Status] Needs Review, DO NOT MERGE, A8c Agencies

#99144 Domain-To-Plan Credit: Don't apply domain proration cost override to plans grid
  packages/data-stores/src/plans/constants.ts
  packages/data-stores/src/plans/hooks/test/use-pricing-meta-for-grid-plans.ts
  packages/data-stores/src/plans/hooks/use-pricing-meta-for-grid-plans.ts
Labels: [Status] Needs Review

#99200 Help Center: Add bottom spacing for article content if notice is visible
  packages/odie-client/src/components/message/messages-container.tsx
  packages/odie-client/src/components/odie-notice/index.tsx
  packages/odie-client/src/components/odie-notice/view-most-recent-conversation-notice.tsx
  packages/odie-client/src/style.scss
Labels: [Status] Needs Review

#99156 i18n: Update several `/client` components to replace `formatNumnber` with i18n-calypso `numberFormat`
  client/blocks/author-compact-profile/index.tsx
  client/blocks/reader-full-post/header.jsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/site-stats-column.tsx
  client/my-sites/stats/stats-purchase/stats-commercial-upgrade-slider/index.tsx
  client/my-sites/subscribers/components/subscriber-list-container/subscriber-list-container.tsx
  client/reader/stream/site-feed-sidebar/index.jsx
  packages/components/src/number-formatters/lib/format-number.ts
Labels: [Status] Needs Review, i18n: number-format

#99221 Post-Checkout: Use Core ProgressBar
  client/my-sites/checkout/checkout-thank-you/pending/index.tsx
  client/my-sites/checkout/checkout-thank-you/pending/style.scss
Labels: [Status] Needs Review

#99204 i18n: Update highlight-cards component to use i18n-calypso `numberFormat`
  packages/components/src/highlight-cards/lib/numbers.ts
  packages/components/src/highlight-cards/mobile-highlight-cards.tsx
Labels: [Status] Needs Review, i18n: number-format

#99242 Fix gigantic previews and icons in connections settings
  client/sites/marketing/connections/service-examples.scss
Labels: [Status] Needs Review

#99187 Signup form: use `TextControl` from `@wordpress/components`
  client/blocks/signup-form/index.jsx
  client/jetpack-connect/style.scss
  client/signup/style.scss
Labels: [Status] Needs Review, [Feature] Signup & Account Creation, [Type] Janitorial

#99248 Add reset action to onboard reducer
  packages/data-stores/src/onboard/reducer.ts
Labels: [Type] Bug, [Status] Needs Review, Reviewer Can Merge

#99229 Components: Remove unused logos
  packages/components/CHANGELOG.md
  packages/components/src/index.ts
  packages/components/src/logos/bloomberg-logo/index.tsx
  packages/components/src/logos/condenast-logo/index.tsx
  packages/components/src/logos/disney-logo/index.tsx
  packages/components/src/logos/docs/example.tsx
  packages/components/src/logos/facebook-logo/index.tsx
  packages/components/src/logos/time-logo/index.tsx
Labels: [Status] Needs Review, Components, [Type] Janitorial

#99260 @automattic/components: align @wordpress/* dependencies with the rest of the repo
  packages/components/package.json
  yarn.lock
Labels: [Status] Needs Review, [Type] Task, dependencies

#99112 Remove Is Reskinned Flag: Remove from user and notice sections
  client/blocks/signup-form/index.jsx
  client/blocks/time-mismatch-warning/test/__snapshots__/index.jsx.snap
  client/components/global-notices/test/__snapshots__/index.js.snap
  client/components/notice/README.md
  client/components/notice/index.jsx
  client/components/notice/style.scss
  client/jetpack-connect/test/__snapshots__/jetpack-connect-notices.js.snap
  client/my-sites/plans-features-main/components/plan-notice-credit-update.tsx
  client/my-sites/plans-features-main/components/plan-notice.tsx
  client/my-sites/promote-post-i2/components/campaign-item-details/index.tsx
  client/my-sites/promote-post-i2/main.tsx
  client/my-sites/subscribers/components/add-subscribers-modal/add-subscribers-modal.tsx
  client/signup/signup-header/index.tsx
  client/signup/steps/design-picker/index.jsx
  client/signup/steps/domains/test/index.js
  client/signup/steps/intent/index.tsx
  client/signup/steps/starting-point/index.tsx
  client/signup/steps/store-features/index.tsx
  client/signup/steps/user/index.jsx
  packages/plans-grid-next/src/types.ts
Labels: [Status] Needs Review

#99142 Stats Location: update geochart to use coordinates for Regions and Cities
  client/my-sites/stats/features/modules/stats-locations/sample-locations.js
  client/my-sites/stats/features/modules/stats-locations/stats-locations.tsx
  client/my-sites/stats/geochart/index.jsx
  client/state/stats/lists/utils.js
Labels: [Feature] Stats, [Status] Needs Review

#99100 Hundred Year Plan Site Picker: Replace presales-chat with Help Center
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-site-picker/index.tsx
Labels: [Status] Needs Review

#73409 Jetpack Cloud: Open support doc link in new window
  client/my-sites/site-settings/disconnect-site/down-flow.jsx
Labels: [Status] In Progress

#99218 Big Sky: Updated free site modal copy, size and console error
  client/landing/stepper/declarative-flow/helpers/use-goals-first-experiment.ts
  client/my-sites/plans-features-main/components/plan-upsell-modal/components/suggested-plan-section.tsx
  client/my-sites/plans-features-main/components/plan-upsell-modal/index.tsx
Labels: [Status] Needs Review

#99225 Reader User Profile: Add Read More link
  client/lib/user/user.d.ts
  client/reader/user-profile/components/user-profile-header/index.tsx
  client/reader/user-profile/components/user-profile-header/style.scss
Labels: [Status] Needs Review

#98837 Domains: Implement multi-target email forwards
  client/data/emails/types.ts
  client/data/emails/use-add-email-forward-mutation.tsx
  client/data/emails/use-remove-email-forward-mutation.tsx
  client/data/emails/use-resend-verify-email-forward-mutation.tsx
  client/lib/domains/email-forwarding/has-duplicated-email-forwards.js
  client/lib/domains/email-forwarding/index.js
  client/my-sites/email/email-forwarding/actions-menu/index.tsx
  client/my-sites/email/email-forwarding/actions-menu/style.scss
  client/my-sites/email/email-forwarding/email-forwarding-add-new-compact-list.tsx
  client/my-sites/email/email-forwarding/email-forwarding-add-new-compact.jsx
  client/my-sites/email/email-forwarding/email-forwards-list/index.tsx
  client/my-sites/email/email-forwarding/email-forwards-list/style.scss
  client/my-sites/email/email-forwarding/hooks.ts
  client/my-sites/email/email-forwarding/style.scss
  client/my-sites/email/email-forwarding/verification-notices/index.tsx
  client/my-sites/email/email-forwarding/verification-notices/style.scss
  client/my-sites/email/email-forwards-add/add-new-form/destination-input.tsx
  client/my-sites/email/email-forwards-add/add-new-form/index.tsx
  client/my-sites/email/email-forwards-add/add-new-form/source-input.tsx
  client/my-sites/email/email-forwards-add/add-new-form/styles.scss
  client/my-sites/email/email-forwards-add/add-new-form/types.ts
  client/my-sites/email/email-forwards-add/add-new-form/utils.tsx
  client/my-sites/email/email-forwards-add/index.tsx
  client/my-sites/email/email-forwards-add/style.scss
  client/my-sites/email/email-management/home/email-mailbox-action-menu.jsx
  client/my-sites/email/email-management/home/email-mailbox-warnings.jsx
  client/my-sites/email/email-management/home/email-plan-mailboxes-list.tsx
  client/my-sites/email/email-management/home/email-plan-mailboxes/email-forward-header.tsx
  client/my-sites/email/email-management/home/email-plan-mailboxes/email-forward-secondary-details.tsx
  client/my-sites/email/email-management/home/email-plan-mailboxes/email-forward-target.tsx
  client/my-sites/email/email-management/home/email-plan/index.jsx
  client/my-sites/email/email-management/style.scss
  packages/components/src/confirmation-dialog/index.tsx
  packages/components/src/confirmation-dialog/style.scss
  packages/components/src/index.ts
Labels: [Status] Needs Review, [Status] String Freeze

#99276 Prep - Revert "Domains: Implement multi-target email forwards"
  client/data/emails/types.ts
  client/data/emails/use-add-email-forward-mutation.tsx
  client/data/emails/use-remove-email-forward-mutation.tsx
  client/data/emails/use-resend-verify-email-forward-mutation.tsx
  client/lib/domains/email-forwarding/has-duplicated-email-forwards.js
  client/lib/domains/email-forwarding/index.js
  client/my-sites/email/email-forwarding/actions-menu/index.tsx
  client/my-sites/email/email-forwarding/actions-menu/style.scss
  client/my-sites/email/email-forwarding/email-forwarding-add-new-compact-list.tsx
  client/my-sites/email/email-forwarding/email-forwarding-add-new-compact.jsx
  client/my-sites/email/email-forwarding/email-forwards-list/index.tsx
  client/my-sites/email/email-forwarding/email-forwards-list/style.scss
  client/my-sites/email/email-forwarding/hooks.ts
  client/my-sites/email/email-forwarding/style.scss
  client/my-sites/email/email-forwarding/verification-notices/index.tsx
  client/my-sites/email/email-forwarding/verification-notices/style.scss
  client/my-sites/email/email-forwards-add/add-new-form/destination-input.tsx
  client/my-sites/email/email-forwards-add/add-new-form/index.tsx
  client/my-sites/email/email-forwards-add/add-new-form/source-input.tsx
  client/my-sites/email/email-forwards-add/add-new-form/styles.scss
  client/my-sites/email/email-forwards-add/add-new-form/types.ts
  client/my-sites/email/email-forwards-add/add-new-form/utils.tsx
  client/my-sites/email/email-forwards-add/index.tsx
  client/my-sites/email/email-forwards-add/style.scss
  client/my-sites/email/email-management/home/email-mailbox-action-menu.jsx
  client/my-sites/email/email-management/home/email-mailbox-warnings.jsx
  client/my-sites/email/email-management/home/email-plan-mailboxes-list.tsx
  client/my-sites/email/email-management/home/email-plan-mailboxes/email-forward-header.tsx
  client/my-sites/email/email-management/home/email-plan-mailboxes/email-forward-secondary-details.tsx
  client/my-sites/email/email-management/home/email-plan-mailboxes/email-forward-target.tsx
  client/my-sites/email/email-management/home/email-plan/index.jsx
  client/my-sites/email/email-management/style.scss
  packages/components/src/confirmation-dialog/index.tsx
  packages/components/src/confirmation-dialog/style.scss
  packages/components/src/index.ts
Labels: [Status] Needs Review

#99240 Domains: Add price to 100-year domain transfer flow before inputting the auth code
  client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/domain-code-pair.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/use-validation-message.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx
Labels: [Status] Needs Review

#99188 Login form: use `TextControl` from `@wordpress/components` instead of local one
  client/blocks/login/login-form.jsx
  client/login/wp-login/style.scss
Labels: [Status] Needs Review, [Type] Janitorial, Login

#99291 Domains: Implement multi-target email forwards - take II
  client/data/emails/types.ts
  client/data/emails/use-add-email-forward-mutation.tsx
  client/data/emails/use-remove-email-forward-mutation.tsx
  client/data/emails/use-resend-verify-email-forward-mutation.tsx
  client/lib/domains/email-forwarding/has-duplicated-email-forwards.js
  client/lib/domains/email-forwarding/index.js
  client/my-sites/email/email-forwarding/actions-menu/index.tsx
  client/my-sites/email/email-forwarding/actions-menu/style.scss
  client/my-sites/email/email-forwarding/email-forwarding-add-new-compact-list.tsx
  client/my-sites/email/email-forwarding/email-forwarding-add-new-compact.jsx
  client/my-sites/email/email-forwarding/email-forwards-list/index.tsx
  client/my-sites/email/email-forwarding/email-forwards-list/style.scss
  client/my-sites/email/email-forwarding/hooks.ts
  client/my-sites/email/email-forwarding/style.scss
  client/my-sites/email/email-forwarding/verification-notices/index.tsx
  client/my-sites/email/email-forwarding/verification-notices/style.scss
  client/my-sites/email/email-forwards-add/add-new-form/destination-input.tsx
  client/my-sites/email/email-forwards-add/add-new-form/index.tsx
  client/my-sites/email/email-forwards-add/add-new-form/source-input.tsx
  client/my-sites/email/email-forwards-add/add-new-form/styles.scss
  client/my-sites/email/email-forwards-add/add-new-form/types.ts
  client/my-sites/email/email-forwards-add/add-new-form/utils.tsx
  client/my-sites/email/email-forwards-add/index.tsx
  client/my-sites/email/email-forwards-add/style.scss
  client/my-sites/email/email-management/home/email-mailbox-action-menu.jsx
  client/my-sites/email/email-management/home/email-mailbox-warnings.jsx
  client/my-sites/email/email-management/home/email-plan-mailboxes-list.tsx
  client/my-sites/email/email-management/home/email-plan-mailboxes/email-forward-header.tsx
  client/my-sites/email/email-management/home/email-plan-mailboxes/email-forward-secondary-details.tsx
  client/my-sites/email/email-management/home/email-plan-mailboxes/email-forward-target.tsx
  client/my-sites/email/email-management/home/email-plan/index.jsx
  client/my-sites/email/email-management/style.scss
  packages/components/src/confirmation-dialog/index.tsx
  packages/components/src/confirmation-dialog/style.scss
  packages/components/src/index.ts
Labels: [Status] Needs Review

#99300 Email Forwards: Fix email forward translations
  client/my-sites/email/email-forwarding/actions-menu/index.tsx
Labels: [Status] Needs Review

#99297 Reader User Profile: Fix styles on User Not Found page
  client/reader/user-profile/style.scss
Labels: [Status] Needs Review

#99299 Domains: Add `isGravatarRestrictedDomain` to Calypso domain objects
  client/state/sites/domains/assembler.js
  client/state/sites/domains/test/fixture/index.js
  packages/data-stores/src/queries/use-site-domains-query.ts
  packages/domains-table/src/test-utils.tsx
  packages/domains-table/src/utils/assembler.ts
Labels: [Status] Needs Review

#99141 Stats: Add line chart for real-time stats prototype
  client/my-sites/stats/components/line-chart/index.tsx
  client/my-sites/stats/pages/realtime/index.jsx
  client/my-sites/stats/pages/realtime/style.scss
  package.json
  yarn.lock
Labels: [Feature] Stats, [Status] Needs Review

#95172 Invites: Fix Invite Accept Form Title
  client/my-sites/invites/invite-accept-logged-in/index.jsx
  client/my-sites/invites/invite-accept-logged-in/style.scss
  client/my-sites/invites/invite-accept-logged-out/index.jsx
  client/my-sites/invites/invite-accept-logged-out/style.scss
  client/my-sites/invites/invite-form-header/index.jsx
  client/my-sites/invites/invite-form-header/style.scss
  client/my-sites/invites/utils.js
Labels: OSS Citizen, [Status] String Freeze

#99271 Reader: Link likes to user profile page
  client/blocks/post-likes/index.jsx
Labels: [Status] Needs Review

#99311 Revert "Remove Is Reskinned Flag: Remove is reskinned flag from user …
  client/blocks/signup-form/index.jsx
  client/blocks/time-mismatch-warning/test/__snapshots__/index.jsx.snap
  client/components/global-notices/test/__snapshots__/index.js.snap
  client/components/notice/README.md
  client/components/notice/index.jsx
  client/jetpack-connect/test/__snapshots__/jetpack-connect-notices.js.snap
  client/my-sites/plans-features-main/components/plan-notice-plan-to-higher-plan-credit.tsx
  client/my-sites/plans-features-main/components/plan-notice.tsx
  client/my-sites/promote-post-i2/components/campaign-item-details/index.tsx
  client/my-sites/promote-post-i2/main.tsx
  client/my-sites/subscribers/components/add-subscribers-modal/add-subscribers-modal.tsx
  client/signup/signup-header/index.tsx
  client/signup/steps/design-picker/index.jsx
  client/signup/steps/domains/test/index.js
  client/signup/steps/intent/index.tsx
  client/signup/steps/starting-point/index.tsx
  client/signup/steps/store-features/index.tsx
  client/signup/steps/user/index.jsx
  packages/plans-grid-next/src/types.ts
Labels: [Status] Needs Review, Reverted

#98875 Make Site Settings available to duplicate views experiment users
  client/controller/index.web.js
  client/hosting/overview/controller.tsx
  client/hosting/server-settings/main.tsx
  client/lib/remove-duplicate-views-experiment/index.ts
  client/my-sites/site-settings/form-general.jsx
  client/my-sites/site-settings/index.js
  client/my-sites/site-settings/section-general.jsx
  client/my-sites/site-settings/settings-controller.js
  client/my-sites/site-settings/site-admin-interface/index.js
  client/my-sites/site-settings/sitemaps.jsx
  client/sites/components/site-preview-pane/constants.ts
  client/sites/components/site-preview-pane/dotcom-preview-pane.tsx
  client/sites/hosting-features/components/hosting-features.tsx
  client/sites/settings/administration/controller.ts
  client/sites/settings/administration/tools/card.jsx
  client/sites/settings/administration/tools/delete-site/delete-site-warnings.jsx
  client/sites/settings/administration/tools/delete-site/index.jsx
  client/sites/settings/administration/tools/index.jsx
  client/sites/settings/administration/tools/reset-site/index.jsx
  client/sites/settings/administration/tools/transfer-site/confirmation-transfer.tsx
  client/sites/settings/administration/tools/transfer-site/index.tsx
  client/sites/settings/administration/tools/transfer-site/pending-domain-transfer.tsx
  client/sites/settings/administration/tools/transfer-site/site-owner-user-search.tsx
  client/sites/settings/administration/tools/transfer-site/site-transfer-card.tsx
  client/sites/settings/administration/tools/transfer-site/start-site-owner-transfer.tsx
  client/sites/settings/caching/form.tsx
  client/sites/settings/controller.tsx
  client/sites/settings/hooks/use-is-site-settings-untangled.ts
  client/sites/settings/index.tsx
  client/sites/settings/site/agency.tsx
  client/sites/settings/site/enhanced-ownership.jsx
  client/sites/settings/site/footer-credit/index.jsx
  client/sites/settings/site/holiday-snow.jsx
  client/sites/settings/site/index.tsx
  client/sites/settings/site/privacy/index.tsx
  client/sites/settings/site/subscription-gifting.jsx
  client/sites/settings/site/toolbar.jsx
  client/sites/settings/site/visibility/index.jsx
  client/sites/settings/utils.ts
  client/sites/settings/web-server/server-configuration-form.tsx
  client/sites/tools/sftp-ssh/ssh-keys.scss
Labels: [Status] Needs Review

#99266 Jetpack WooCommerce login: fix logo
  client/blocks/login/index.jsx
Labels: [Status] Needs Review

#99109 Theme Tiers: Switching away from a theme requires confirmation
  client/my-sites/themes/activation-modal.jsx
  client/my-sites/themes/activation-modal.scss
  client/state/themes/hooks/use-is-theme-allowed-on-site.ts
  client/state/themes/selectors/index.js
  client/state/themes/selectors/is-theme-allowed-on-site.ts
Labels: [Status] Needs Review

#99336 chore: update Studio links to the latest build 1.3.3
  client/blocks/get-apps/apps-config.tsx
Labels: [Status] Needs Review

#99220 Apps/Notifications: prevent overscroll on notifications list
  apps/notifications/src/panel/boot/stylesheets/main.scss
  apps/notifications/src/panel/templates/note-list.jsx
Labels: [Type] Enhancement, [Status] Needs Review

#99216 Add from url param to Substack importer URL
  client/blocks/import/list/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/create-site/index.tsx
  client/landing/stepper/declarative-flow/site-migration-flow.ts
  client/my-sites/importer/newsletter/content.tsx
Labels: [Status] Needs Review

#99279 Storybook: Remove `@storybook/preset-scss`
  packages/calypso-storybook/package.json
  packages/calypso-storybook/src/index.js
  yarn.lock
Labels: [Status] Needs Review, [Type] Janitorial, Storybook

#99335 style fixed for jetpack promoted posts pages for the outstanding balance notice
  client/my-sites/promote-post-i2/components/campaigns-table/style.scss
  client/my-sites/promote-post-i2/main.tsx
  client/my-sites/promote-post-i2/style.scss
Labels: [Status] Needs Review

#99189 Remove client component `TextControl`
  client/blocks/signup-form/style.scss
  client/components/text-control/index.js
  client/components/text-control/style.scss
  client/jetpack-connect/style.scss
  client/login/wp-login/style.scss
  client/signup/style.scss
Labels: [Status] Needs Review, [Type] Janitorial

#99308 Stats Locations: Add tracking for Locations' module interactions
  client/my-sites/stats/features/modules/stats-locations/stats-locations.tsx
  client/my-sites/stats/stats-list/stats-list-card.jsx
  client/my-sites/stats/stats-module/all-time-nav.jsx
  packages/components/src/horizontal-bar-list/stats-hero-card.tsx
  packages/components/src/horizontal-bar-list/types.ts
Labels: [Feature] Stats, [Status] Needs Review

#98760 Site Migrations: In the DIY flow, specify the plugin to install via the API param
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/provision-status/index.tsx
  client/landing/stepper/hooks/test/use-plugin-auto-installation.tsx
  client/landing/stepper/hooks/test/use-plugin-installation.tsx
  client/landing/stepper/hooks/test/use-prepare-site-for-migration.tsx
  client/landing/stepper/hooks/use-plugin-auto-installation.ts
  client/landing/stepper/hooks/use-plugin-installation.ts
  client/landing/stepper/hooks/use-prepare-site-for-migration.ts
  client/landing/stepper/hooks/use-site-transfer/mutation.ts
  client/landing/stepper/hooks/use-site-transfer/test/index.tsx
Labels: [Status] Needs Review, [Feature] Site Migration

#99270 JetpackLogo: Add story
  packages/components/src/index.ts
  packages/components/src/logos/docs/example.tsx
  packages/components/src/logos/jetpack-logo/index.tsx
  packages/components/src/logos/jetpack-logo/stories/index.stories.tsx
Labels: [Status] Needs Review, Components, [Type] Janitorial, Storybook

#99129 Site Migration: Persist `from` param through flow, pass to Atomic transfer API
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions/index.tsx
  client/landing/stepper/declarative-flow/site-migration-flow.ts
  client/landing/stepper/declarative-flow/test/site-migration-flow.tsx
  client/landing/stepper/hooks/use-prepare-site-for-migration.ts
  client/landing/stepper/hooks/use-site-transfer/index.ts
  client/landing/stepper/hooks/use-site-transfer/mutation.ts
  client/landing/stepper/utils/checkout.ts
Labels: [Status] Needs Review, [Feature] Site Migration

#99358 Reader Discovery V2: Add feature flag
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/wpcalypso.json
Labels: [Status] Needs Review, [Feature] Reader

#99241 A4A: Use svg logos as images
  client/a8c-for-agencies/sections/marketplace/hosting-overview-v3/hosting-content/enterprise-agency-hosting/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/enterprise-agency-hosting/index.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview/hosting-v2/enterprise-agency-hosting/style.scss
  client/assets/images/logos/cnn.svg
  client/assets/images/logos/salesforce.svg
  client/assets/images/logos/slack.svg
Labels: [Type] Bug, [Status] Needs Review, Accessibility, [Type] Janitorial, A4A

#99309 GMClosureNotice: Move to `help-center` package and rename
  packages/components/CHANGELOG.md
  packages/components/src/index.ts
  packages/help-center/src/components/help-center-closure-notice.scss
  packages/help-center/src/components/help-center-closure-notice.tsx
  packages/help-center/src/components/help-center-contact-page.tsx
Labels: [Status] Needs Review, Components, [Type] Janitorial, [Feature] Help Center

#99365 Build: Bump base image execution timeout limit
  .teamcity/settings.kts
Labels: Build, TeamCity

#99238 Reader User Profile: Add back button to profile page
  client/reader/user-profile/components/user-profile-header/style.scss
  client/reader/user-profile/controller.tsx
  client/reader/user-profile/index.tsx
  client/reader/user-profile/style.scss
  packages/calypso-router/types/index.d.ts
Labels: [Status] Needs Review

#99370 Release focused launchpad to wpcalypso
  config/wpcalypso.json
Labels: [Status] Needs Review

#99367 Remove CNN, Salesforce, Slack logo components
  packages/components/CHANGELOG.md
  packages/components/src/index.ts
  packages/components/src/logos/cnn-logo/index.tsx
  packages/components/src/logos/docs/example.tsx
  packages/components/src/logos/salesforce-logo/index.tsx
  packages/components/src/logos/slack-logo/index.tsx
Labels: [Status] Needs Review, Components, [Type] Janitorial

#99301 Rollout site migration flow 2025 to all users.
  client/landing/stepper/declarative-flow/internals/hooks/use-migration-experiment/index.ts
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-import-or-migrate/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-import-or-migrate/test/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-upgrade-plan/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-upgrade-plan/test/index.tsx
Labels: [Status] Needs Review

#99278 Stats: prompt users to update the Jetpack plugin
  client/my-sites/stats/features/modules/stats-locations/stats-locations.tsx
  client/my-sites/stats/site.jsx
  client/my-sites/stats/stats-card-upsell/stats-card-update-jetpack-version.tsx
  client/my-sites/stats/stats-card-upsell/stats-card-upsell-overlay.tsx
Labels: [Feature] Stats, [Status] Needs Review

#99186 A4A: add forms for new signup flow
  client/a8c-for-agencies/sections/signup/index.ts
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/blueprint-form/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/choice-blueprint/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/choice-blueprint/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/contact-form/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/contact-form/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/finish-signup-survey/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/personalization/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/personalization/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/signup-wrapper/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/signup-wrapper/sidebar-image.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/signup-wrapper/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/step-progress/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/step-progress/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/types.ts
  config/a8c-for-agencies-development.json
  config/a8c-for-agencies-horizon.json
Labels: [Status] Needs Review

#99383 Include query params in start-site-transfer redirect
  client/my-sites/site-settings/settings-controller.js
Labels: [Status] Needs Review

#99310 Plans Grid: fix default state of storage dropdown when an addon is purchased
  packages/plans-grid-next/src/components/shared/storage/components/storage-dropdown.tsx
Labels: [Status] Needs Review

#99329 A4A > Agency Tier: Allow agencies to download the agency tier badges
  client/a8c-for-agencies/sections/agency-tier/download-badges/download-link.tsx
  client/a8c-for-agencies/sections/agency-tier/primary/agency-tier-overview/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#99393 E2E: Remove invalid test after Settings > Media untangling
  test/e2e/specs/media/settings__media.ts
Labels: [Status] Needs Review

#99333 Fix design picker active theme styles during /setup/site-setup
  packages/design-picker/src/components/style.scss
  packages/design-picker/src/components/theme-card/style.scss
Labels: [Status] Needs Review

#99334 Hide active badge for design picker in /setup/site-setup flow
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
Labels: [Status] Needs Review

#99350 Server: re-read assets.json file when modified
  client/server/middleware/assets.js
Labels: [Type] Enhancement, [Status] Needs Review, Build

#99361 RDV: Update overriding preference
  client/controller/index.web.js
Labels: [Status] Needs Review

#99165 Newsletter: Add hide category selection modal setting
  client/my-sites/site-settings/settings-newsletter/main.tsx
  client/my-sites/site-settings/settings-newsletter/newsletter-categories-section/newsletter-categories-hide-modal-toggle.tsx
  client/my-sites/site-settings/settings-newsletter/newsletter-categories-section/newsletter-categories-section.tsx
  client/my-sites/site-settings/settings-newsletter/newsletter-categories-section/style.scss
  config/wpcalypso.json
Labels: [Status] Needs Review

#99094 A4A: Convert Bundle price selector to use core component.
  client/a8c-for-agencies/sections/marketplace/products-overview-v2/bundle-price-selector/index.tsx
Labels: [Status] Needs Review

#99091 A4A: Add few improvements on the new product marketplace.
  client/a8c-for-agencies/sections/marketplace/hooks/use-product-and-plans.tsx
  client/a8c-for-agencies/sections/marketplace/hosting-overview-v3/style.scss
  client/a8c-for-agencies/sections/marketplace/products-overview-v2/style.scss
  client/a8c-for-agencies/sections/marketplace/products-overview/product-filter/hooks/use-product-filter-options.tsx
  client/components/jetpack/jetpack-product-info/section.tsx
Labels: [Status] Needs Review, A8c Agencies

#99356 Domain management: Update domain header font-size
  client/my-sites/domains/domain-management/components/domain-header/index.tsx
  client/my-sites/domains/domain-management/components/domain-header/style.scss
Labels: [Status] Needs Review

#99272 i18n: Update several cases of `ShortenedNumber` component with `numberFormat`
  apps/odyssey-stats/src/widget/modules.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-expanded-content/insights-stats.tsx
  client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content/site-stats-column.tsx
  client/my-sites/stats/sections/all-time-highlights-section/index.tsx
  client/my-sites/stats/stats-email-top-row/top-card.jsx
  client/my-sites/subscribers/components/subscriber-stats-card/subscriber-stats-card.tsx
  packages/components/src/horizontal-bar-list/horizontal-bar-grid-item.tsx
  packages/components/src/post-stats-card/index.tsx
Labels: [Status] Needs Review, i18n, i18n: number-format

#99403 Fix promise and add timeout for more resilience
  packages/calypso-e2e/src/lib/pages/signup/user-signup-page.ts
  test/e2e/specs/onboarding/signup__woo-email.ts
Labels: [Status] Needs Review

#98351 A4A: Load schedule call link from company record.
  client/a8c-for-agencies/data/agencies/use-fetch-schedule-call-link.ts
  client/a8c-for-agencies/sections/overview/sidebar/growth-accelerator/index.tsx
  client/a8c-for-agencies/style.scss
Labels: [Status] Needs Review, A8c Agencies

#99366 Onboarding: Prevent the user from seeing the designSetup step again after the upgrade flow
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx
Labels: [Status] Needs Review, Free Onboarding Flow

#99375 Jetpack Connect: Cleanup unused Jetpack Complete Page
  client/assets/images/jetpack/rna-image-complete.png
  client/assets/images/jetpack/rna-image-complete@2x.png
  client/components/jetpack/card/jetpack-rna-dialog-card/index.tsx
  client/components/jetpack/card/jetpack-rna-dialog-card/style.scss
  client/jetpack-connect/authorize.js
  client/jetpack-connect/constants.js
  client/jetpack-connect/index.js
  client/jetpack-connect/test/authorize.js
  client/my-sites/plans/jetpack-plans/controller.tsx
  client/my-sites/plans/jetpack-plans/index.ts
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/components/cta-buttons/index.tsx
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/components/cta-buttons/style.scss
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/hooks/use-individual-peoducts.ts
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/index.tsx
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/item-price/index.tsx
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/item-price/style.scss
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/items-included/index.tsx
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/items-included/single-product.tsx
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/items-included/style.scss
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/items-included/utils.ts
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/product-header/index.tsx
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/product-header/style.scss
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/show-license-activation-link-if-available.tsx
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/style.scss
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/test/index.js
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/view-all-products-link/index.tsx
  client/my-sites/plans/jetpack-plans/jetpack-complete-page/view-all-products-link/style.scss
  config/development.json
  config/horizon.json
  config/production.json
  config/stage.json
  config/test.json
  config/wpcalypso.json
  packages/calypso-products/src/constants/jetpack.ts
Labels: Jetpack, [Status] Needs Review, [Type] Janitorial, post-connection

#99158 Stepper: Unify loading states
  client/landing/stepper/declarative-flow/internals/components/stepper-loader/index.tsx
  client/landing/stepper/declarative-flow/internals/components/stepper-loader/style.scss
  client/landing/stepper/declarative-flow/internals/global.scss
  client/landing/stepper/declarative-flow/internals/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/assign-trial-plan/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/assign-trial-plan/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/automated-copy-site/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/bundle-install-plugins/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/bundle-transfer/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/create-site/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/create-site/styles.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/launch-big-sky/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/README.md
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/tailored-flow-precheckout-screen/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/tailored-flow-precheckout-screen/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/site-launch/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-plugin-install/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-plugin-install/test/index.tsx
  client/my-sites/checkout/checkout-thank-you/pending/style.scss
  client/signup/steps/woocommerce-install/transfer/install-plugins.tsx
  client/signup/steps/woocommerce-install/transfer/transfer-site.tsx
  packages/data-stores/src/onboard/reducer.ts
Labels: [Status] Needs Review

#99263 Domain management: Fix redirect context on mailbox purchase
  client/my-sites/email/add-mailboxes/index.tsx
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/get-on-submit-new-mailboxes-handler.ts
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/google-workspace-card.tsx
  client/my-sites/email/email-providers-comparison/stacked/provider-cards/professional-email-card.tsx
  client/my-sites/email/paths.ts
  client/my-sites/email/test/paths.ts
Labels: [Status] Needs Review

#99337 Fix issues when conversation can't be found
  packages/odie-client/src/data/use-get-zendesk-conversation.ts
  packages/odie-client/src/hooks/use-get-combined-chat.ts
Labels: [Status] Needs Review

#99377 Align all domain overview pages to center (except upsells)
  client/my-sites/domains/domain-management/domain-overview-pane/style.scss
  client/my-sites/email/email-management/email-home.tsx
  client/my-sites/email/email-providers-comparison/in-depth/index.tsx
Labels: [Status] Needs Review

#99369 Fix hundred year plan layout
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-setup/styles.scss
Labels: [Status] Needs Review

#99413 E2E: Fix media settings test on Atomic
  test/e2e/specs/media/settings__media.ts
Labels: [Type] Bug, [Pri] Normal, [Status] Needs Review

#99409 Show Global Styles under the Personal plan (if eligible)
  packages/calypso-products/src/is-global-styles-on-personal-enabled.ts
Labels: [Status] Needs Review

#99273 i18n: Update several cases of `formattedNumber` usage with `numberFormat`
  apps/odyssey-stats/src/widget/highlights.tsx
  client/my-sites/stats/sections/all-time-highlights-section/index.tsx
  client/my-sites/stats/stats-plan-usage/index.tsx
Labels: [Status] Needs Review, i18n, i18n: number-format

#99371 Concierge: Refactor closure notice
  client/me/concierge/shared/closure-notice.js
  client/me/concierge/shared/gm-closure-notice.js
  client/me/concierge/shared/primary-header.js
Labels: [Status] Needs Review, [Type] Janitorial, Concierge

#99381 Reader Onboarding: Remove wide screen flex style
  client/reader/onboarding/style.scss
Labels: [Status] Needs Review

#99093 Fix: Handle introductory offer periods longer than billing periods
  client/my-sites/checkout/src/components/item-variation-picker/variant-dropdown-price.tsx
Labels: OSS Citizen

#99416 Update email forward list and DNS records table headers to match styles of DataViews of site management
  client/my-sites/domains/domain-management/dns/dns-records-list-item.jsx
  client/my-sites/domains/domain-management/domain-overview-pane/style.scss
Labels: [Status] Needs Review

#99392 For domains overview pane, fix styling for navigation bottom border
  client/my-sites/domains/domain-management/domain-overview-pane/style.scss
Labels: [Status] Needs Review

#99422 Fix env inconsistency
  packages/help-center/src/components/help-center-smooch.tsx
  packages/zendesk-client/src/use-attach-file.tsx
Labels: [Status] Needs Review

#99415 Domain management: Fix table header spacings to match /sites
  client/my-sites/domains/domain-management/list/bulk-all-domains.tsx
  client/my-sites/domains/domain-management/list/style.scss
  client/sites/components/sites-dataviews/dataview-style.scss
  packages/domains-table/src/domains-table/style.scss
Labels: [Status] Needs Review

#99307 WordPressLogo: Add story
  packages/components/src/index.ts
  packages/components/src/logos/wordpress-logo/README.md
  packages/components/src/logos/wordpress-logo/docs/example.jsx
  packages/components/src/logos/wordpress-logo/index.tsx
  packages/components/src/logos/wordpress-logo/stories/index.stories.tsx
  packages/components/src/logos/wordpress-logo/style.scss
  packages/components/src/site-thumbnail/docs/example.jsx
Labels: [Status] Needs Review, Components, [Type] Janitorial, Storybook

#99390 Streamline `@automattic/components` Storybook devex
  .storybook/main.js
  package.json
  packages/components/package.json
Labels: [Status] Needs Review, [Type] Janitorial, Storybook

#99424 Reader full post - update tag styles
  client/blocks/reader-full-post/style.scss
Labels: [Status] Needs Review

#99430 Enable revamped domain management in production
  config/production.json
  config/test.json
Labels: [Status] Needs Review

#99423 Subscribers: Add tooltip and true / false filter options
  client/my-sites/subscribers/components/subscriber-data-views/style.scss
  client/my-sites/subscribers/components/subscriber-data-views/subscriber-data-views.tsx
Labels: [Status] String Freeze

#99431 Reader - fix 0 at bottom of loading following stream.
  client/reader/stream/index.jsx
Labels: [Status] Needs Review

#99379 Reader: `reader` and `account` flows set Reader as the user's default landing page
  client/signup/config/flows-pure.js
  client/signup/main.jsx
Labels: [Status] Needs Review

#99264 Fix: Untangle domain price of the isReskinned flag
  client/components/domains/domain-product-price/index.jsx
  client/components/domains/domain-product-price/test/domain-product-price.tsx
Labels: [Status] Needs Review

#99394 A4A > Marketplace: Fix WordPress.com hosting discount calculation
  .eslintrc.js
  client/a8c-for-agencies/components/a4a-number-input-v2/index.tsx
Labels: [Status] Needs Review, A8c Agencies

#99445 Release newsletter goal launchpad tasks
  client/landing/stepper/declarative-flow/onboarding.ts
  config/development.json
  packages/data-stores/src/onboard/test/utils.ts
  packages/data-stores/src/onboard/utils.ts
Labels: [Status] Needs Review

#99162 Newsletter imports: Handle errors correctly
  client/my-sites/subscribers/components/add-subscribers-modal/add-subscribers-modal.tsx
  client/my-sites/subscribers/components/subscribers-page/subscribers-page-context.tsx
  packages/data-stores/src/subscriber/actions.ts
  packages/subscriber/src/hooks/use-import-error.ts
Labels: [Status] Needs Review

#99414 A4A: Fix discrepancies in the Signup form v2 styling.
  client/a8c-for-agencies/components/form/footer/index.tsx
  client/a8c-for-agencies/components/form/footer/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/blueprint-form/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/blueprint-form/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/choice-blueprint/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/choice-blueprint/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/contact-form/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/contact-form/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/finish-signup-survey/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/personalization/index.tsx
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/personalization/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/signup-wrapper/style.scss
Labels: [Status] Needs Review, A8c Agencies

#99420 A4A: adds 'Dark' mode support on the new Signup form.
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/choice-blueprint/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/contact-form/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/multi-step-form/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/signup-wrapper/style.scss
  client/a8c-for-agencies/sections/signup/signup-v2/components/step-progress/style.scss
  packages/components/src/logos/wordpress-logo/README.md
Labels: [Status] Needs Review, A8c Agencies

#99452 A4A > Partner Directory: Fix access control
  client/a8c-for-agencies/controller.tsx
Labels: [Status] Needs Review, A8c Agencies

#99274 Add Tracks events when a default dns record notice is showed
  client/my-sites/domains/domain-management/dns/dns-records.jsx
Labels: [Status] Needs Review

#98806 Stepper: Implement signup sessions
  client/landing/stepper/declarative-flow/example.ts
  client/landing/stepper/declarative-flow/internals/state-manager/create-session-id.ts
  client/landing/stepper/declarative-flow/internals/state-manager/stepper-state-manifest.ts
  client/landing/stepper/declarative-flow/internals/state-manager/store.ts
  client/landing/stepper/declarative-flow/internals/state-manager/types.ts
  client/landing/stepper/declarative-flow/internals/types.ts
  client/landing/stepper/index.tsx
  client/landing/stepper/utils/use-session-id.ts
  client/state/query-client.ts
Labels: [Status] Needs Review, Stepper

#99438 Domains: Replace `isGravatarDomain` checks by `isGravatarRestrictedDomain` checks where applicable
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/lib/fixtures.ts
  client/lib/domains/types.ts
  client/me/purchases/cancel-purchase/refund-information.jsx
  client/me/purchases/remove-purchase/remove-domain-dialog/index.jsx
  client/my-sites/domains/domain-management/settings/index.tsx
  client/my-sites/domains/domain-management/transfer/transfer-page/index.tsx
  client/my-sites/email/email-forwards-add/index.tsx
  client/my-sites/email/email-providers-comparison/stacked/index.tsx
  client/state/sites/domains/schema.js
  packages/domains-table/src/utils/types.ts
  packages/launchpad/src/test/lib/fixtures.ts
Labels: [Status] Needs Review

#99486 Hundred Year Plan Site Picker:Add the siteId and siteUrl parameters to the Help Center url
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-site-picker/index.tsx
Labels: [Status] Needs Review

#99207 Launchpad - add handling for new `add_first_subscribers` task.
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-definitions/subscribers/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/types.ts
  client/landing/stepper/declarative-flow/write.ts
  client/my-sites/subscribers/components/add-subscribers-modal/add-subscribers-modal.tsx
  packages/launchpad/src/setup-actions.ts
Labels: [Status] Needs Review

#99247 A4A: create custom cursor rules
  .cursor/rules/a4a-custom-rules.mdc
Labels: [Status] Needs Review, DO NOT MERGE, A4A

#99399 For email actions use the same icon as in Sites
  client/my-sites/email/email-forwarding/actions-menu/index.tsx
  client/my-sites/email/email-management/home/email-mailbox-action-menu.jsx
  client/my-sites/email/email-management/home/email-plan-mailboxes/context-menu.tsx
Labels: [Status] Needs Review

#99451 Stats Locations: add support for preserving geo mode in summary view
  client/my-sites/stats/features/modules/stats-locations/stats-locations.tsx
  client/my-sites/stats/summary/index.jsx
Labels: [Feature] Stats, [Status] Needs Review

#99446 Add announcement post URL
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-step-wrapper/info-modal.tsx
Labels: [Status] Needs Review

#99447 Fix alignment for hundred year plan
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-diy-or-difm/index.tsx
  client/landing/stepper/declarative-flow/internals/steps-repository/hundred-year-plan-diy-or-difm/styles.scss
Labels: [Status] Needs Review

#99354 Remove Is Reskinned Flag: Remove from user and notice sections - Attempt 2
  client/blocks/eligibility-warnings/hold-list.tsx
  client/blocks/signup-form/index.jsx
  client/blocks/time-mismatch-warning/index.tsx
  client/components/global-notices/index.jsx
  client/components/global-notices/test/__snapshots__/index.js.snap
  client/components/notice/README.md
  client/components/notice/index.tsx
  client/components/notice/style.scss
  client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-already-wpcom/components/form/index.tsx
  client/me/purchases/manage-purchase/notices.tsx
  client/my-sites/earn/ads/payments.tsx
  client/my-sites/earn/ads/wrapper.tsx
  client/my-sites/plans-features-main/components/plan-notice-domain-to-plan-credit.tsx
  client/my-sites/plans-features-main/components/plan-notice-plan-to-higher-plan-credit.tsx
  client/my-sites/plans-features-main/components/plan-notice.tsx
  client/my-sites/promote-post-i2/components/campaign-item-details/index.tsx
  client/my-sites/promote-post-i2/main.tsx
  client/my-sites/subscribers/components/add-subscribers-modal/add-subscribers-modal.tsx
  client/signup/signup-header/index.tsx
  client/signup/steps/design-picker/index.jsx
  client/signup/steps/domains/test/index.js
  client/signup/steps/intent/index.tsx
  client/signup/steps/starting-point/index.tsx
  client/signup/steps/store-features/index.tsx
  client/signup/steps/user/index.jsx
  packages/plans-grid-next/src/types.ts
Labels: [Status] Needs Review

#99281 Reader User Profile: Add fader behind Read More link
  client/assets/stylesheets/shared/functions/_z-index.scss
  client/reader/user-profile/components/user-profile-header/index.tsx
  client/reader/user-profile/components/user-profile-header/style.scss
Labels: [Status] Needs Review, [Feature] Reader

#99380 Domains: Remove email restrictions for Gravatar domains
  client/my-sites/domains/domain-management/settings/index.tsx
  client/my-sites/email/email-management/home/email-plan-warning-notice.tsx
  client/my-sites/email/email-management/home/utils.ts
  client/my-sites/email/email-providers-comparison/stacked/index.tsx
Labels: [Status] Needs Review

#99442 Launchpad My Home: Show celebration confetti when user competes all tasks
  client/my-sites/customer-home/cards/launchpad/use-launchpad.ts
  client/my-sites/customer-home/components/full-screen-launchpad.tsx
Labels: [Status] Needs Review, Reviewer Can Merge

#99499 Reader User Profile: Make Read More link open in a separate tab
  client/reader/user-profile/components/user-profile-header/index.tsx
Labels: [Status] Needs Review

#99503 Reader User Profile: Revert Read More link opening in a separate tab
  client/reader/user-profile/components/user-profile-header/index.tsx
Labels: [Status] Needs Review

#99510 Hide DNS records summary if nameserver is external
  client/my-sites/domains/domain-management/settings/dns/index.tsx
  client/my-sites/domains/domain-management/settings/dns/types.ts
  client/my-sites/domains/domain-management/settings/index.tsx
Labels: [Status] Needs Review

#99378 Checkout: Set Google and Apple Pay button to 100% width
  packages/wpcom-checkout/src/payment-request-button.tsx
Labels: [Status] Needs Review

#99384 Adds gravatar wont load notice
  client/my-sites/domains/domain-management/dns/dns-menu-options-button.tsx
  client/my-sites/domains/domain-management/dns/dns-records.jsx
  client/my-sites/domains/domain-management/dns/restore-default-a-records-dialog.tsx
  client/my-sites/domains/domain-management/dns/restore-default-cname-record-dialog.tsx
Labels: [Status] Needs Review

#99472 Stats: Refactor Insights page away from connect pattern
  client/my-sites/stats/pages/insights/index.jsx
Labels: [Feature] Stats, [Status] Needs Review

#99471 Stats: Update feature slugs for Security upsell
  client/my-sites/stats/jetpack-upsell-section/upsell-card/available-upsells.tsx
Labels: [Feature] Stats, [Status] Needs Review
